recipes/ninja/all/conanfile.py
Specify library name and version:  **Ninja/1.11.1**
Added declaration of package_type to highlight that Ninja is an "application"
Added conditional logic around self.env_info settings to prevent errors when using Conan 2.0
fixes #13503
---
=> Declare package_type and prevent Conan 2 errors with self.env_info

recipes/aws-c-s3/all/CMakeLists.txt, recipes/aws-c-s3/all/conandata.yml, recipes/aws-c-s3/all/conanfile.py, recipes/aws-c-s3/all/test_package/conanfile.py, recipes/aws-c-s3/all/test_v1_package/CMakeLists.txt, recipes/aws-c-s3/all/test_v1_package/conanfile.py, recipes/aws-c-s3/config.yml
Specify library name and version:  **aws-c-s3/***
There is a "missing dependencies" issue related to the aws-c-io API breaking changes.
aws-c-io made incompatible changes to the Input Stream API in 0.11.
https://github.com/awslabs/aws-c-io/releases/tag/v0.11.0
And aws-c-s3 uses new Input Stream API since 0.1.36.
(no official release note)
https://github.com/awslabs/aws-c-s3/blob/v0.1.36/source/s3_checksum_stream.c
The version of aws-c-s3 needs to change the version of aws-c-io that it depends on, which causes missing dependencies in aws-c-auth and aws-c-http.
For this reason, I would like to split the version of aws-c-auth and aws-c-http as follows.
---
=> aws-c-s3: add version 0.1.49 and support conan v2

recipes/wayland/all/test_package/conanfile.py
Update test package for Conan V2.
Test wayland as a build requirement.
This is a common use case for wayland-scanner.
Use PkgConfigDeps build context to find wayland-scanner.
---
=> wayland: Modernize test package

recipes/wayland-protocols/all/conanfile.py, recipes/wayland-protocols/all/test_package/conanfile.py, recipes/wayland-protocols/all/test_package/meson.build, recipes/wayland-protocols/all/test_package/meson_options.txt, recipes/wayland-protocols/all/test_v1_package/conanfile.py, recipes/wayland-protocols/all/test_v1_package/meson.build
Update for Conan V2.
Use build context for PkgConfigDeps in test package.
Allows cross-compilation.
Specify library name and version:  **wayland-protocols/***
---
=> wayland-protocols: Conan V2

recipes/opentdf-client/all/conandata.yml, recipes/opentdf-client/config.yml
Specify library name and version: opentdf-client/1.3.2
- Changes to support OIDC authentication 
---
=> opentdf-client: add version 1.3.2

docs/v2_migration.md
Docs!
This came up in #12896 
and in #13429 
---
=> docs: v2 migration guidence for `conf_info`

recipes/xorg/all/conanfile.py
fixes:
- https://github.com/conan-io/conan-center-index/issues/13588
`xkeyboard-config` and `xtrans` are system packages with no architecture, so the recipe installing them needs to have no `arch` setting. Recipes actually using them will need to add a `requires("xtrans/system")` or `requires("xkeyboard-config/system")` once https://github.com/conan-io/conan-center-index/pull/13594 and https://github.com/conan-io/conan-center-index/pull/13595 are merged. The only package I know on CCI uses one of these packages is `xkbcommon`, so I did the correction in https://github.com/conan-io/conan-center-index/pull/13604
---
=> xorg: remove xkeyboard-config and xtrans

docs/package_templates/header_only/all/conanfile.py
I want to update header_only template to remove frameworkdirs and resdirs assignment lines.
Please see https://github.com/conan-io/conan-center-index/pull/13499#discussion_r998062421.
---
=> docs: remove lines to make frameworkdirs and resdirs empty on header_only template

recipes/aws-c-mqtt/all/conanfile.py
Specify library name and version:  **aws-c-mqtt/***
Try to fix https://github.com/conan-io/conan-center-index/pull/13607.
---
=> aws-c-mqtt: change dependant recipe version for aws-crt-cpp

recipes/xerces-c/all/conanfile.py
Fix for https://github.com/conan-io/conan-center-index/pull/13502#issuecomment-1284632958
It comes from https://github.com/apache/xerces-c/blob/v3.2.3/cmake/XercesDLL.cmake#L23 and how `BUILD_SHARED_LIBS` is injected in toolchain file (see https://github.com/conan-io/conan/issues/11937 & https://github.com/conan-io/conan/issues/11840).
---
=> xerces-c: hotfix - honor `shared=False` option

recipes/aws-c-event-stream/all/conanfile.py
Specify library name and version:  **aws-c-event-stream/***
Try to fix https://github.com/conan-io/conan-center-index/pull/13607.
---
=> aws-c-event-stream: change dependant recipe version for aws-crt-cpp

docs/package_templates/meson_package/all/conanfile.py, docs/package_templates/meson_package/all/test_package/conanfile.py, docs/package_templates/meson_package/all/test_v1_package/conanfile.py
- remove `ninja` from tool_requires, it's the job of meson recipe to require ninja or not.
- fix `install_name` of shared libs on macOS (`@rpath` instead of lib dir absolute path)
- do not add `pkgconf` to tool_requires if `tools.gnu:pkg_config` config is set
---
=> meson-template: several improvements

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.72.0**
---
=> daw_header_libraries: add version 2.72.0

docs/package_templates/autotools_package/all/conanfile.py, docs/package_templates/autotools_package/all/test_package/CMakeLists.txt, docs/package_templates/autotools_package/all/test_package/conanfile.py, docs/package_templates/autotools_package/all/test_v1_package/CMakeLists.txt
- handle windows as build machine
- handle `tools.gnu:pkg_config` config
- handle msvc
- fix `install_name` of shared libs on macOS (to set `@rpath` instead of lib dir absolute path)
- call `VirtualBuildEnv` & `VirtualRunEnv` first in generate to avoid side effects
---
=> autotools template: several improvements

recipes/xkbcommon/all/conanfile.py, recipes/xkbcommon/all/test_package/conanfile.py
Now that PkgConfigDeps can generate pkg-config files for the build context as of Conan 1.52.0, the ` xkbcommon` recipe should make use of it for the `wayland` and `wayland-protocols` dependencies which are used as `tool_requires`.
---
=> xkbcommon: Use PkgConfigDeps build context for wayland

docs/package_templates/header_only/all/conanfile.py, docs/package_templates/header_only/all/test_package/CMakeLists.txt, docs/package_templates/header_only/all/test_package/conanfile.py, docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt
- handle self.info in `validate()` depending on whether conan client is v1 or v2
- transitive headers of direct dependencies
- remove build_requirements
---
=> header-only template: several improvements

recipes/xnnpack/all/CMakeLists.txt, recipes/xnnpack/all/conandata.yml, recipes/xnnpack/all/conanfile.py, recipes/xnnpack/all/test_package/conanfile.py, recipes/xnnpack/all/test_v1_package/CMakeLists.txt, recipes/xnnpack/all/test_v1_package/conanfile.py, recipes/xnnpack/config.yml
=> xnnpack: conan v2 support

recipes/libcurl/all/CMakeLists.txt, recipes/libcurl/all/conandata.yml, recipes/libcurl/all/conanfile.py, recipes/libcurl/all/test_package/conanfile.py, recipes/libcurl/all/test_v1_package/CMakeLists.txt, recipes/libcurl/all/test_v1_package/conanfile.py
Specify library name and version:  **libcurl/xxx**
Replacing #12377 after merge conflict.
I rebased on master and will try to reference all the ongoing issues.
---
=> [libcurl/xxx] Conan v2 migration

docs/package_templates/cmake_package/all/test_v1_package/CMakeLists.txt
Instead of duplicating, let's re-use from test_package/
- Don't specify LANGUAGE as it's just a wrapper and it will be filled by test_package/
- CMake 3.1 is more than enough. Also, test_package/ will have the real required version
- As test_package/ is not a sub directory, but an external folder, binary dir must be passed
---
=> [cmake-template] Simplify test_v1_package CMakeLists.txt

recipes/restbed/all/conandata.yml, recipes/restbed/all/conanfile.py, recipes/restbed/all/patches/4.8-0001-cmake-conan.patch, recipes/restbed/all/patches/4.8-0002-mingw-deprecated-fix.patch, recipes/restbed/all/test_package/CMakeLists.txt, recipes/restbed/all/test_package/conanfile.py, recipes/restbed/all/test_package/test_package.cpp, recipes/restbed/all/test_v1_package/CMakeLists.txt, recipes/restbed/all/test_v1_package/conanfile.py, recipes/restbed/config.yml
Specify library name and version:  **restbed/4.8**
Tested with MSVC2019, gcc@Linux, mingw@Linux
---
=> restbed: add restbed/4.8 recipe

recipes/daw_json_link/all/conandata.yml, recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.1.1**
---
=> daw_json_link: add version 3.1.1

recipes/libmicrohttpd/all/conandata.yml, recipes/libmicrohttpd/all/conanfile.py, recipes/libmicrohttpd/all/patches/0.9.75-0002-allow-release-with-debug-runtime.patch
Specify library name and version:  **libmicrohttpd/all**
Fixes 32-bit MSVC build
---
=> libmicrohttpd: fix 32-bit MSVC build

recipes/blend2d/all/CMakeLists.txt, recipes/blend2d/all/conanfile.py, recipes/blend2d/all/test_package/CMakeLists.txt, recipes/blend2d/all/test_package/conanfile.py, recipes/blend2d/all/test_v1_package/CMakeLists.txt, recipes/blend2d/all/test_v1_package/conanfile.py
- fix improper imports of conan v2 features (`from conan import tools` is strongly discouraged, https://docs.conan.io/en/latest/reference/conanfile/tools.html)
- use `export_conandata_patches`
- remove CMakeLists wrapper
- `get_safe` of compiler.cppstd
- inject `BL_STATIC` with `tc.preprocessor_definitions`
- explicit cmake names
- use `can_run` in test package
- avoid duplication of CMake code logic in test v1 package
---
=> blend2d: more conan v2 stuff & fix improper imports

recipes/libcurl/all/conanfile.py
- do not delete settings.compiler from package id (comes from https://github.com/conan-io/conan-center-index/pull/12956)
- no need to copy dylib files of dependencies for conftest of autotools build, it's the job of VirtualRunEnv to inject paths of dylib files to DYLD_LIBRARY_PATH (SIP is not triggered in configure script AFAIK).
- fix installation of autotools if build machine is windows
- protect deletion of settings & options
---
=> libcurl: several fixes & bump dependencies

recipes/folly/all/conanfile.py, recipes/folly/all/test_package/CMakeLists.txt, recipes/folly/all/test_v1_package/conanfile.py
**folly**
refine folly recipe
1. add sse42 option
some libraries depends on folly, but with simd enabled. It will causes
compiling error if folly has no such option.
2. folly project exports cmake file with components, such as folly::follybenchmark.
To keep consistent with folly's project, add components info
---
=> refine Folly recipe

recipes/libnghttp2/all/CMakeLists.txt, recipes/libnghttp2/all/conandata.yml, recipes/libnghttp2/all/conanfile.py, recipes/libnghttp2/all/test_package/CMakeLists.txt, recipes/libnghttp2/all/test_package/conanfile.py, recipes/libnghttp2/all/test_v1_package/CMakeLists.txt, recipes/libnghttp2/all/test_v1_package/conanfile.py, recipes/libnghttp2/config.yml
Specify library name and version:  **libnghttp2/1.50.0**
---
=> libnghttp2: add 1.50.0, bump deps

recipes/xkbcommon/all/conanfile.py
I made an oops in my previous change #13612.
This actually does end up breaking cross-compilation. The requirements of `wayland-scanner` aren't available in the build context. This causes pkg-config to fail to "find" `wayland-scanner`. The `expat` and `libxml2` files would need to be in this same directory. Omitting the separate build context directory for pkg-config files works around this issue for now. Work will need to be done upstream to ensure dependencies are also made available in the build context for PkgConfigDeps. See conan-io/conan#12342 for progress on the issue upstream.
It's important to note that pointing Meson to the generators directory for "native" pkg-config files isn't the safest thing to do. It's possible for Meson to mistakenly think dependencies in the generators …
=> xkbcommon: Revert using a separate directory for the build context

recipes/c-blosc2/all/conandata.yml, recipes/c-blosc2/all/conanfile.py, recipes/c-blosc2/config.yml
Specify library name and version:  **c-blosc2/***
- add version 2.4.3
- update zlib, lz4
- use export_conandata_patches
---
=> c-blosc2: add version 2.4.3 and update dependencies

recipes/eigen/all/conanfile.py, recipes/eigen/all/test_package/CMakeLists.txt, recipes/eigen/all/test_package/conanfile.py, recipes/eigen/all/test_package/test_package.cpp, recipes/eigen/all/test_v1_package/CMakeLists.txt
Specify library name and version:  **eigen/***
---
=> eigen: Use export_conanadata_patches and explicit test_type

recipes/exiv2/all/CMakeLists.txt, recipes/exiv2/all/conandata.yml, recipes/exiv2/all/conanfile.py, recipes/exiv2/all/patches/0001-link-0.27.5.patch, recipes/exiv2/all/patches/0004-find-expat.patch, recipes/exiv2/all/test_package/conanfile.py, recipes/exiv2/all/test_v1_package/CMakeLists.txt, recipes/exiv2/all/test_v1_package/conanfile.py, recipes/exiv2/config.yml
Specify library name and version:  **exiv2/0.27.5**
---
=> exiv2: add 0.27.5 + conan v2 support

recipes/fmt/all/conandata.yml, recipes/fmt/all/conanfile.py, recipes/fmt/all/test_package/CMakeLists.txt, recipes/fmt/all/test_package/conanfile.py, recipes/fmt/all/test_v1_package/CMakeLists.txt, recipes/fmt/config.yml
Specify library name and version:  **fmt/***
---
=> fmt: Safely delete options in configure plus clean up

recipes/glib/all/conanfile.py
Specify library name and version:  **glib/***
Required to update `gstreamer` to use PkgConfigDeps: #13400.
Related issue is here: conan-io/conan#12279.
---
=> glib: Fix libdir for PkgConfigDeps

recipes/openapi-generator/all/conandata.yml, recipes/openapi-generator/all/conanfile.py, recipes/openapi-generator/all/test_package/conanfile.py, recipes/openapi-generator/all/test_v1_package/conanfile.py, recipes/openapi-generator/config.yml
I thought adding this tool would be a nightmare due to maven dependency but being able to handle prebuilt binaries makes it awesomely simple!
---
=> Add openapi-generator/6.0.1

recipes/opencl-icd-loader/all/CMakeLists.txt, recipes/opencl-icd-loader/all/conandata.yml, recipes/opencl-icd-loader/all/conanfile.py, recipes/opencl-icd-loader/all/test_package/CMakeLists.txt, recipes/opencl-icd-loader/all/test_package/conanfile.py, recipes/opencl-icd-loader/all/test_v1_package/CMakeLists.txt, recipes/opencl-icd-loader/all/test_v1_package/conanfile.py, recipes/opencl-icd-loader/config.yml
=> opencl-icd-loader: add 2022.05.18 + conan v2 support

recipes/libslz/all/conandata.yml, recipes/libslz/config.yml
Specify library name and version:  **libslz/1.2.1**
---
=> libslz: add version 1.2.1

recipes/libjpeg-turbo/all/CMakeLists.txt, recipes/libjpeg-turbo/all/conandata.yml, recipes/libjpeg-turbo/all/conanfile.py, recipes/libjpeg-turbo/all/test_package/CMakeLists.txt, recipes/libjpeg-turbo/all/test_package_module/CMakeLists.txt, recipes/libjpeg-turbo/all/test_package_module/conanfile.py, recipes/libjpeg-turbo/all/test_v1_package/CMakeLists.txt, recipes/libjpeg-turbo/all/test_v1_package/conanfile.py, recipes/libjpeg-turbo/all/test_v1_package_module/CMakeLists.txt, recipes/libjpeg-turbo/all/test_v1_package_module/conanfile.py
This PR also enables generation of `FindJPEG.cmake` in `CMakeDeps` and `cmake_find_package` generator, as well as JPEG::JPEG target, since official `FindJPEG.cmake` is able to find libjpeg implementation of libjpeg-turbo.
---
=> libjpeg-turbo: conan v2 support

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/0.1.0**
---
=> glaze: add version 0.1.0

recipes/innoextract/all/CMakeLists.txt, recipes/innoextract/all/conandata.yml, recipes/innoextract/all/conanfile.py, recipes/innoextract/all/patches/0001-cmake-fix-module.patch, recipes/innoextract/all/test_package/conanfile.py, recipes/innoextract/all/test_v1_package/conanfile.py, recipes/libevent/all/conanfile.py
Specify library name and version:  **innoextract/1.9.0**
---
=> innoextract: requirements version bump

recipes/watcher/all/conandata.yml, recipes/watcher/config.yml
Specify library name and version:  **watcher/0.3.3**
---
=> watcher: add version 0.3.3

recipes/quill/all/conandata.yml, recipes/quill/config.yml
Specify library name and version:  **quill/2.3.2**
---
=> quill: add version 2.3.2

recipes/kuba-zip/all/conandata.yml, recipes/kuba-zip/config.yml
Specify library name and version:  **kuba-zip/0.2.6**
---
=> kuba-zip: add version 0.2.6

recipes/glib/all/conandata.yml, recipes/glib/all/conanfile.py, recipes/glib/all/test_package/conanfile.py, recipes/glib/all/test_v1_package/CMakeLists.txt, recipes/glib/all/test_v1_package/conanfile.py, recipes/glib/config.yml
- fix PkgConfigDeps
- relocatable shared libs on macOS (install_name set to `@rpath`)
- properly rename lib names for `compiler=msvc` as well
- no need to define libdir in MesonToolchain since min conan version is 1.52.0
- add tests for CMakeDeps & PkgConfigDeps
- use basic_layout (for consistency among CCI recipes)
---
=> glib: several fixes & improvements

docs/changelog.md
A new release has been merged!
- Since this new release, users which are not contributing anymore for months, will be removed from the access list by the Access Request PR created by the CI Bot. Those removed users can be added again, just need to ask on the issue #4. 
- Projects which use <major.minor> as tag version, will be computed automatically for Bump Version. So far, only SEMVER has been accepted.
---
=> [release] 27 October 2022

recipes/cairo/meson/conandata.yml, recipes/cairo/meson/conanfile.py, recipes/cairo/meson/test_package/CMakeLists.txt, recipes/cairo/meson/test_package/conanfile.py, recipes/cairo/meson/test_v1_package/CMakeLists.txt, recipes/cairo/meson/test_v1_package/conanfile.py
Specify library name and version:  **cairo**
Update the cairo meson build to the new toolchains
---
=> [cairo] update toolchain

recipes/grpc/all/conanfile.py
- use conan.tools.files.copy instead of self.copy
- no more usage of msvc_version_to_vs_ide_version, it's not part of conan public API. Use check_min_vs instead.
- access to dependencies options through self.dependencies
- self.info in validate()
- bump zlib to 1.2.13
---
=> grpc: more conan v2 stuff + bump zlib

recipes/jsonnet/all/conandata.yml, recipes/jsonnet/config.yml
Specify library name and version:  **jsonnet/0.19.1**
---
=> jsonnet: add version 0.19.1

recipes/highway/all/conandata.yml, recipes/highway/config.yml
Specify library name and version:  **highway/1.0.2**
---
=> highway: add version 1.0.2

docs/labels.md
- Document those acceptable version formats computed by the CI automatically.
---
=> [docs] Bump version label only accepts SEMVER and MAJOR.MINOR

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.73.1**
---
=> daw_header_libraries: add version 2.73.1

recipes/flatbuffers/all/conandata.yml, recipes/flatbuffers/config.yml
Added flatbuffers 22.9.24/29
I need this version since I want to align the version of the flatbuffers nuget package and the conan package. This way I can use flatc.exe from the conan package to generate the cs files. 
---
=> updated flatbuffers 22.9.24 and 22.9.29

recipes/utf8proc/all/conandata.yml, recipes/utf8proc/config.yml
Specify library name and version:  **utf8proc/2.8.0**
---
=> utf8proc: add version 2.8.0

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.35.0**
---
=> etl: add version 20.35.0

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/0.1.2**
---
=> glaze: add version 0.1.2

docs/faqs.md, docs/how_to_add_packages.md
When an user becomes inactive (passed 4 months), the CI will ask to that user with the Access Request PR.
---
=> [docs] Document inactive users process

recipes/gtest/all/conandata.yml, recipes/gtest/all/conanfile.py, recipes/gtest/all/patches/gtest-1.10.0-override.patch, recipes/gtest/all/patches/gtest-1.10.0.patch, recipes/gtest/config.yml
**gtest/1.10.0**
there is a compatible issue in version > 1.10.0.
'enum class' is forced to use ADL lookup, and what's more, the template<> version does not work. The user has to write lots of customized funciton operator<<() to pass compiling, it is a bit annoying. Add 1.10.0 support for convenience.
---
=> add gtest v1.10.0 support

recipes/ninja/all/conanfile.py
It's not the responsibility of ninja recipe to set `tools.cmake.cmaketoolchain:generator` config (or `tools.meson.mesontoolchain:backend`), and change behavior of another tool, it's a user preference.
`CONAN_CMAKE_GENERATOR` is kept (for conan v1 build helpers) to avoid potential breakage.
see https://github.com/conan-io/conan-center-index/pull/12918#discussion_r1008700211
---
=> ninja: do not override `tools.cmake.cmaketoolchain:generator`

recipes/gcc/all/conandata.yml, recipes/gcc/all/test_package/conanfile.py, recipes/gcc/all/test_package/hello.c, recipes/gcc/all/test_package/hello.cpp, recipes/gcc/config.yml
* Bump GCC recipe version to 12.2.0
* Modify test recipe to use `deps_env_info` instead of `os.environ` to extract `CC` and `CXX` data. This is because `env_info.{CC,CXX}` was not being propagated to the run environment and the generated compilers were not being appropriately tested.
* Rename the output from the test executable to be `"Hello, World!"` for consistency with the filename, remove references to Bincrafters
Closes #13812.
Specify library name and version:  **gcc/12.2.0**
Bumping version prior to investigating a recipe migration for conan 2.0 …
=> [gcc] Bump gcc recipe version to 12.2.0

recipes/bzip3/all/conandata.yml, recipes/bzip3/config.yml
Specify library name and version:  **bzip3/1.2.0**
---
=> bzip3: add version 1.2.0

recipes/lcms/all/conandata.yml, recipes/lcms/config.yml
Specify library name and version:  **lcms/2.14**
---
=> lcms: add version 2.14

recipes/objectbox/all/conandata.yml, recipes/objectbox/config.yml
Specify library name and version:  **objectbox/0.18.0**
---
=> objectbox: add version 0.18.0

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/0.1.3**
---
=> glaze: add version 0.1.3

recipes/yder/all/conandata.yml, recipes/yder/all/conanfile.py, recipes/yder/all/patches/1.4.18-0001-shared-static-conan.patch, recipes/yder/all/test_package/CMakeLists.txt, recipes/yder/all/test_package/conanfile.py, recipes/yder/all/test_package/test_package.c, recipes/yder/all/test_v1_package/CMakeLists.txt, recipes/yder/all/test_v1_package/conanfile.py, recipes/yder/config.yml
Specify library name and version:  **yder/1.4.18**
Depends on https://github.com/conan-io/conan-center-index/pull/13589
---
=> yder: add yder/1.4.18 recipe

recipes/tensorpipe/all/CMakeLists.txt, recipes/tensorpipe/all/conanfile.py, recipes/tensorpipe/all/test_package/conanfile.py, recipes/tensorpipe/all/test_v1_package/CMakeLists.txt, recipes/tensorpipe/all/test_v1_package/conanfile.py
=> tensorpipe: conan v2 support

recipes/trompeloeil/all/conandata.yml, recipes/trompeloeil/config.yml
Specify library name and version:  **trompeloeil/***
---
=> trompeloeil: add version 43

recipes/opentelemetry-cpp/all/conandata.yml, recipes/opentelemetry-cpp/all/conanfile.py, recipes/opentelemetry-cpp/all/patches/1.7.0-0001-fix-cmake.patch, recipes/opentelemetry-cpp/config.yml
Specify library name and version:  **opentelemetry/1.7.0**
In addition to adding the new version, I also noticed that we're missing a number of libraries in the package info meaning they couldn't be linked when consuming the package, so I've added the ones that I could see were missing.
---
=> Add opentelemetry/1.7.0 and missing  libraries

.gitignore
according to git docs
> If there is a separator at the beginning or middle (or both) > of the pattern, then the pattern is relative to the directory
> level of the particular .gitignore file itself.
---
=> ignore test_package's output at all levels

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/0.1.4**
---
=> glaze: add version 0.1.4

recipes/spdlog/all/conandata.yml, recipes/spdlog/all/conanfile.py, recipes/spdlog/config.yml
Specify library name and version:  **spdlog/1.11.0**
Add v1.11.0.
Also bump fmt to v9.1.0 to follow the version used upstream (see [here](https://github.com/gabime/spdlog/releases/tag/v1.11.0)).
---
=> spdlog: add v1.11.0

recipes/cpp-sort/all/conandata.yml, recipes/cpp-sort/all/conanfile.py, recipes/cpp-sort/all/test_package/CMakeLists.txt, recipes/cpp-sort/all/test_package/conanfile.py, recipes/cpp-sort/all/test_v1_package/CMakeLists.txt, recipes/cpp-sort/all/test_v1_package/conanfile.py, recipes/cpp-sort/all/test_v1_package/cpp-sort-integrity.cpp, recipes/cpp-sort/config.yml
Specify library name and version:  **cpp-sort/1.13.2**
Along with the minor version bump, this merge request significantly updates the recipe to be compatible with Conan v2. I haven't actually installed v2-beta nor written recipes or followed Conan evolution in a while, so there might be antipatterns I'm not aware of.
---
=> Add cpp-sort 1.13.2, make recipe compatible with Conan v2

recipes/libcurl/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/13910
Some explanation: https://github.com/conan-io/conan-center-index/issues/13910#issuecomment-1298379737
---
=> libcurl: honor default upstream values of with_ca_bundle & with_ca_path options

recipes/fast_float/all/conandata.yml, recipes/fast_float/config.yml
Specify library name and version:  **fast_float/3.6.0**
---
=> fast_float: add version 3.6.0

docs/conandata_yml_format.md
Related to https://github.com/conan-io/conan/issues/12455#issuecomment-1301954685
- patches are local copied, do not need to download and validate
- there is no intention to validate by apply_conandata_patches
---
=> [docs] Remove sha256 for patches in conandata.yml

recipes/daw_json_link/all/conandata.yml, recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.4.1**
---
=> daw_json_link: add version 3.4.1

recipes/mdnsresponder/all/conandata.yml
Apple asked us to use new tarballs at https://github.com/apple-oss-distributions. The content is same but tarballs have been regenerated so have different SHA256...
=> [mdnsresponder] https://opensource.apple.com/tarballs is gone

recipes/meson/all/conandata.yml, recipes/meson/config.yml
Specify library name and version:  **meson/0.64.0**
---
=> meson: add version 0.64.0

recipes/openjdk/all/conanfile.py, recipes/openjdk/all/test_package/conanfile.py, recipes/openjdk/all/test_v1_package/conanfile.py
=> [openjdk/xxx] Conan v2 migration

recipes/fontconfig/all/conandata.yml, recipes/fontconfig/all/conanfile.py, recipes/fontconfig/config.yml, recipes/fontconfig/meson/conandata.yml, recipes/fontconfig/meson/conanfile.py, recipes/fontconfig/meson/patches/0001-meson-win32.patch, recipes/fontconfig/meson/test_package/CMakeLists.txt, recipes/fontconfig/meson/test_package/conanfile.py, recipes/fontconfig/meson/test_package/test_package.c, recipes/fontconfig/meson/test_v1_package/CMakeLists.txt, recipes/fontconfig/meson/test_v1_package/conanfile.py
Specify library name and version:  **fontconfig**
Split the version of fontconfig supporting Meson into its own folder and use the new toolchain.
---
=> [fontconfig] use new meson toolchain where supported

recipes/libmp3lame/all/conanfile.py, recipes/libmp3lame/all/test_v1_package/CMakeLists.txt
Regarding msvc, see https://github.com/conan-io/conan-center-index/pull/13791#discussion_r1008586781 & https://github.com/conan-io/conan/issues/12188
MinGW cross-build from linux to Windows was likely broken due to another regression coming from https://github.com/conan-io/conan-center-index/pull/13791 where target os was tested instead of build machien os.
---
=> libmp3lame: fix msvc & mingw build regressions

recipes/psyinf-gmtl/all/conandata.yml, recipes/psyinf-gmtl/all/conanfile.py, recipes/psyinf-gmtl/all/test_package/CMakeLists.txt, recipes/psyinf-gmtl/all/test_v1_package/CMakeLists.txt
Updated cmake settings to allow for drop-in replacement use of the library
=> Fixed psyinf-gmtl cmake setup

recipes/utfcpp/all/conandata.yml, recipes/utfcpp/config.yml
Specify library name and version:  **utfcpp/3.2.2**
---
=> utfcpp: add version 3.2.2

docs/conandata_yml_format.md, linter/conandata_yaml_linter.py
Docs! Config!
The description of this field does not match the normative convention of who it could be used to mean "this came from the project" and not the "this changes source code" which is the written definition here.
This should hopefully reduce the incorrect usage and encourage contributors to pick more descriptive options and fill in the `patch_source` that we offer instead.
=> docs: rename patch field "backport" to "bugfix" to avoid confusion

recipes/boost/all/conanfile.py
As of Xcode 14, Bitcode is deprecated and no longer accepted for AppStore submissions.
(see: https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes under the "Apple Clang Compiler: Deprecations" heading.)
This commit adds an `embed_bitcode` option with a default value of `True` to match the current behavior.
When the compiler version is 14.0+ the option is deleted and the `-fembed-bitcode` flag is not added to the cxx_flags.
---
=> Boost: Add embed_bitcode option

recipes/autoconf/all/conanfile.py, recipes/autoconf/all/test_package/conanfile.py, recipes/autoconf/all/test_v1_package/conanfile.py
Fix regression on windows introduced in https://github.com/conan-io/conan-center-index/pull/12896
We must still use legacy unix_path in package_info().
see: https://github.com/conan-io/conan/issues/12499 & https://github.com/conan-io/conan/issues/12192#issuecomment-1308589581
---
=> autoconf: fix package info on windows

recipes/googleapis/all/conanfile.py, recipes/googleapis/all/test_v1_package/CMakeLists.txt, recipes/googleapis/all/test_v1_package/conanfile.py
Specify library name and version:  googleapis/any
When compiling for Android, there is an additional define of `ANDROID 1` added on the command line.
This causes some of the libraries for the googleapis library to fail compilation, since some of the proto files have enums defining `ANDROID`.
This PR deactivates these libraries and therefore enables compilation of this package (and some packages that rely on it, like gRPC) to be compiled for android.
---
=> [googleapis] deactivate libraries that cause issues for Android builds.

recipes/libunwind/all/conanfile.py
=> libunwind: robust build if all shared + cleanup + use self.info in validate()

recipes/gtest/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/14143
---
=> gtest/1.10.0: fix compiler min versions

recipes/ffmpeg/all/conanfile.py
=> ffmpeg: bump dependencies

recipes/icu/all/conandata.yml, recipes/icu/all/conanfile.py, recipes/icu/all/patches/0001-71.1-fix-emscripten.patch
Specify library name and version:  **icu/71.1**
Fixes https://github.com/conan-io/conan-center-index/issues/13888
There were bunch of underlying issues:
- ICU didn't recognise wasm32-*-emscripten as a host (fixed with a patch).
- ICU's autoconfig didn't properly recognize that we are cross-building (fixed by adding "--build=" parameter to build configuration in the recipe).
- ICU tools needs to be disabled for emscripten (fixed in the recipe).
- While packaging ICU data '-w' param needs to be passed in the PKGDATA_OPTS (fixed with a patch), because there is no pre-built assembly code for wasm
---
=> icu: fix emscripten build for 71.1

recipes/boost/all/conanfile.py
remove option introduced in https://github.com/conan-io/conan-center-index/pull/13970, bitcode is a first class citizen of conan v2 through `tools.apple:enable_bitcode` (but it must be manually handled in build system without conan build helpers).
---
=> boost: rely on `tools.apple:enable_bitcode` conf instead of a custom option

recipes/flatbuffers/all/conandata.yml, recipes/flatbuffers/config.yml
Specify library name and version:  **flatbuffers/22.10.26**
---
=> flatbuffers: add version 22.10.26

recipes/roaring/all/conandata.yml, recipes/roaring/config.yml
Specify library name and version:  **roaring/0.7.3**
---
=> roaring: add version 0.7.3

recipes/gdal/post_3.5.0/conanfile.py
This fixes issue https://github.com/conan-io/conan-center-index/issues/13818 
Specify library name and version:  gdal/3.5.* 
---
=> GDAL: Add cmake_find_packages_multi generator 

recipes/json-schema-validator/all/CMakeLists.txt, recipes/json-schema-validator/all/conandata.yml, recipes/json-schema-validator/all/conanfile.py, recipes/json-schema-validator/all/patches/2.0.0-cmake_minimum_version.patch, recipes/json-schema-validator/all/patches/2.1.0-cmake_minimum_version.patch, recipes/json-schema-validator/all/test_package/CMakeLists.txt, recipes/json-schema-validator/all/test_package/conanfile.py, recipes/json-schema-validator/all/test_v1_package/CMakeLists.txt, recipes/json-schema-validator/all/test_v1_package/conanfile.py
* Conan v2 support
* Bump nlohmann_json/3.11.2
=> [json-schema-validator] Conan v2 support

recipes/ffmpeg/all/conanfile.py
ValueError: too many values to unpack (expected 3) for instance, `e2k-unknown-linux-gnu`
Specify library name and version:  **ffmpeg/all**
/cc @r-a-sattarov
---
=> - [ffmpeg] get_gnu_triplet may return more than 3 values for some triplets

recipes/boost/all/conanfile.py
Specify library name and version:  **boost/1.80.0**
Update Boost reference to ICU to the latest version in conan-center-index.
This resolves problems using the dependency implicitly in a dependency tree that uses it elsewhere.
---
=> [boost] Update icu reference in boost to use the latest.

recipes/json-schema-validator/all/conanfile.py, recipes/json-schema-validator/all/test_package/CMakeLists.txt, recipes/json-schema-validator/all/test_v1_package/CMakeLists.txt
handle this regression: https://github.com/conan-io/conan-center-index/pull/13959#discussion_r1022160270
---
=> json-schema-validator: restore correct CMake target name in CMakeDeps

recipes/fast_float/all/conandata.yml, recipes/fast_float/config.yml
Specify library name and version:  **fast_float/3.7.0**
---
=> fast_float: add version 3.7.0

recipes/trantor/all/conandata.yml, recipes/trantor/config.yml
Specify library name and version:  **trantor/1.5.8**
---
=> trantor: add version 1.5.8

recipes/msgpack-cxx/all/conandata.yml, recipes/msgpack-cxx/config.yml
Specify library name and version:  **msgpack-cxx/4.1.3**
---
=> msgpack-cxx: add version 4.1.3

recipes/cppcommon/all/conandata.yml, recipes/cppcommon/all/patches/0001-update-cmakelists-1-0-3-0.patch, recipes/cppcommon/config.yml
Specify library name and version:  cppcommon/1.0.3.0
Reason : dependency to cpplogging library
---
=> Update cppcommon to 1.0.3.0

recipes/canvas_ity/all/conandata.yml, recipes/canvas_ity/all/conanfile.py, recipes/canvas_ity/all/test_package/CMakeLists.txt, recipes/canvas_ity/all/test_package/conanfile.py, recipes/canvas_ity/all/test_package/test_package.cpp, recipes/canvas_ity/all/test_v1_package/CMakeLists.txt, recipes/canvas_ity/all/test_v1_package/conanfile.py, recipes/canvas_ity/config.yml
Specify library name and version:  **canvas_ity/1.00**
---
=> canvas_ity: add recipe

recipes/simdutf/all/conandata.yml, recipes/simdutf/all/conanfile.py, recipes/simdutf/all/patches/2.0.3-0001-fix-cmake.patch, recipes/simdutf/config.yml
Specify library name and version:  **simdutf/2.0.3**
Since 2.0.3, simdutf provides `SIMDUTF_TOOLS` option to control tools build/installation.
---
=> simdutf: add version 2.0.3

recipes/poco/all/conandata.yml, recipes/poco/all/conanfile.py, recipes/poco/all/patches/1.12.3.patch, recipes/poco/all/patches/1.12.4.patch, recipes/poco/config.yml
updated dependencies:
- expat 2.5.0 (CVE fix)
- odbc 2.3.11
I the meantime already bumped by previous commits:
- zlib 1.2.13 (CVE fix)
- sqlite3 3.39.4
- openssl 1.1.1s (HIGH vulnerability fix)
- libpq 14.5
- libmysqlclient 8.0.30
Closes #13865
Closes #13921
=> [poco] update to version 1.12.4

recipes/roaring/all/conandata.yml, recipes/roaring/config.yml
Specify library name and version:  **roaring/0.8.0**
---
=> roaring: add version 0.8.0

recipes/quill/all/conandata.yml, recipes/quill/config.yml
Specify library name and version:  **quill/2.3.3**
---
=> quill: add version 2.3.3

.c3i/config_v1.yml
Related to https://github.com/conan-io/conan-center-index/pull/13913.
Seems like linux pods are dying when compiling the library. Let's try assigning more resources.
=> [config] Use larger resources to build cppfront packages

recipes/glaze/all/conandata.yml, recipes/glaze/all/conanfile.py, recipes/glaze/all/test_package/CMakeLists.txt, recipes/glaze/all/test_v1_package/CMakeLists.txt, recipes/glaze/config.yml
Specify library name and version:  **glaze/0.1.7**
- add version 0.1.7
- require dragonbox for version 0.1.7
---
=> glaze: add version 0.1.7

recipes/libcurl/all/conandata.yml, recipes/libcurl/all/conanfile.py, recipes/libcurl/all/test_package/CMakeLists.txt, recipes/libcurl/config.yml
This supersedes https://github.com/conan-io/conan-center-index/pull/14146 in an attempt to get the CLA check to work.
Specify library name and version:  **libcurl/7.86.0**
I saw that https://github.com/conan-io/conan-center-index/pull/13783 had been closed without any comment so figured I'd put up a PR in its place. I ran local builds of this on both macOS and Windows, as the recipe uses autotools on *nix and CMake on Windows. 
If the cleanups I've included as part of this aren't appropriate I can easily back them out.
---
=> libcurl 7.86.0

recipes/catch2/3.x.x/conandata.yml, recipes/catch2/config.yml
Specify library name and version:  **catch2/3.2.0**
all patches for 3.1.0 are already merged in 3.2.0.
Try to solve https://github.com/conan-io/conan-center-index/issues/14244.
---
=> catch2: add version 3.2.0

recipes/libnghttp2/all/conandata.yml, recipes/libnghttp2/config.yml
Specify library name and version:  **libnghttp2/1.51.0**
---
=> libnghttp2: add version 1.51.0

recipes/uwebsockets/all/conandata.yml, recipes/uwebsockets/all/conanfile.py, recipes/uwebsockets/all/test_package/CMakeLists.txt, recipes/uwebsockets/all/test_package/conanfile.py, recipes/uwebsockets/all/test_v1_package/CMakeLists.txt, recipes/uwebsockets/all/test_v1_package/conanfile.py, recipes/uwebsockets/config.yml
Specify library name and version:  **uwebsockets/***
- add version 20.17.0
- 
uwebsockets/20.30.0 was already released.
However, uwebsockets>=20.18.0 requires the latest usockets which are not yet released.
---
=> uwebsockets: add version 20.17.0, support conan v2

recipes/quill/all/conandata.yml, recipes/quill/config.yml
Specify library name and version:  **quill/2.3.4**
---
=> quill: add version 2.3.4

recipes/cccl/all/conandata.yml, recipes/cccl/all/conanfile.py, recipes/cccl/all/test_package/conanfile.py, recipes/cccl/all/test_v1_package/conanfile.py, recipes/cccl/all/test_v1_package/example.cpp, recipes/cccl/config.yml
Specify tool name and version:  **cccl/1.2**
Mainly because it was seemingly broken, and is needed for genie.
---
=> cccl: migrate to Conan v2 and add v1.3

recipes/unordered_dense/all/conandata.yml, recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/2.0.1**
---
=> unordered_dense: add version 2.0.1

recipes/libpng/all/conandata.yml, recipes/libpng/config.yml
Specify library name and version:  **libpng/1.6.39**
---
=> libpng: add version 1.6.39

recipes/quill/all/conandata.yml, recipes/quill/config.yml
Specify library name and version:  **quill/2.4.2**
---
=> quill: add version 2.4.2

recipes/openapi-generator/all/conandata.yml, recipes/openapi-generator/all/conanfile.py, recipes/openapi-generator/config.yml
I change to way to reference the jar file to a relative path because I noticed that if this package was fetched from the conan center, the link to the openapi-generator.jar was absolute to the jar in the ci machine.
---
=> [openapi-generator/6.2.1] Add version and improve jar reference

recipes/taywee-args/all/conandata.yml, recipes/taywee-args/config.yml
Specify library name and version:  **taywee-args/6.4.2**
---
=> taywee-args: add version 6.4.2

recipes/opentdf-client/all/conandata.yml, recipes/opentdf-client/config.yml
Specify library name and version: opentdf-client/1.3.4
- For decrypt use KAS URL from tdf
---
=> opentdf-client: add version 1.3.4

docs/error_knowledge_base.md
Documented about the new hook added to conan-center
Related: https://github.com/conan-io/hooks/pull/458
---
=> [docs] New hook kb-h075: Override is not allowed

.github/actions/pr_changed_files/action.yml, recipes/7zip/19.00/conandata.yml
=> fix conandata lint

recipes/si/all/conandata.yml, recipes/si/config.yml
Specify library name and version:  **si/2.5.1**
2.5.1 contains an important bugfix. I am the author of si
---
=> Version bump for si to 2.5.1

recipes/cppfront/all/conanfile.py
Specify library name and version:  **cppfront/cci.20221024**
`includedirs` information is missing
---
=> [CppFront] Adds includedirs info

recipes/foonathan-lexy/all/conandata.yml, recipes/foonathan-lexy/all/conanfile.py, recipes/foonathan-lexy/all/test_package/CMakeLists.txt, recipes/foonathan-lexy/all/test_package/conanfile.py, recipes/foonathan-lexy/all/test_package/test_package.cpp, recipes/foonathan-lexy/all/test_v1_package/CMakeLists.txt, recipes/foonathan-lexy/all/test_v1_package/conanfile.py, recipes/foonathan-lexy/config.yml
Specify library name and version:  **foonathan-lexy/2022.05.01**
Since there is a recipe which has same author name(`foonathan-memory`), 
I added `foonathan` to this recipe as well.
If it is not convenient, please point this out to me so I can correct it.
---
=> foonathan-lexy: add recipe

recipes/fast_float/all/conandata.yml, recipes/fast_float/config.yml
Specify library name and version:  **fast_float/3.8.0**
---
=> fast_float: add version 3.8.0

recipes/immer/all/conandata.yml, recipes/immer/config.yml
Specify library name and version:  **immer/0.8.0**
---
=> immer: add version 0.8.0

recipes/arrow/all/conanfile.py
Because hiveserver2 support was dropped since Apache Arrow 9.0.0: https://github.com/apache/arrow/commit/450c1c0ab460e4c1ce7ece9d5ebd8bcdab5d05ab
We can't use with_hiveserver2 option with Apache Arrow 8.0.0 or earlier because Conan Center Index doesn't have a recipe for hiveserver2.
So we can remove with_hiveserver option without breaking backward compatibility.
---
=> arrow: remove with_hiveserver2 option

recipes/highfive/all/conandata.yml, recipes/highfive/all/conanfile.py, recipes/highfive/config.yml
Specify library name and version:  **highfive/2.x.x**
Add version 2.5.1 and 2.6.2
---
=> highfive: add v2.5.1 and v2.6.2

recipes/roaring/all/CMakeLists.txt, recipes/roaring/all/conanfile.py, recipes/roaring/all/test_package/CMakeLists.txt, recipes/roaring/all/test_package/conanfile.py, recipes/roaring/all/test_v1_package/CMakeLists.txt, recipes/roaring/all/test_v1_package/conanfile.py
=> roaring: conan v2 support

recipes/botan/all/conandata.yml, recipes/botan/config.yml
Specify library name and version:  **botan/2.19.3**
Botan has fixed a vulnerability in its OCSP response validation.
---
=> botan: add version 2.19.3

recipes/quill/all/conandata.yml, recipes/quill/config.yml
Specify library name and version:  **quill/2.5.1**
---
=> quill: add version 2.5.1

recipes/protopuf/all/conandata.yml, recipes/protopuf/config.yml
Specify library name and version:  **protopuf/2.2.1**
---
=> protopuf: add version 2.2.1

recipes/sqlitecpp/all/conanfile.py, recipes/sqlitecpp/all/test_package/CMakeLists.txt, recipes/sqlitecpp/all/test_v1_package/CMakeLists.txt
Specify library name and version:  **sqlitecpp/***
- update sqlite3
- support mingw
---
=> sqlitecpp: update dependencies, support mingw

recipes/wasmtime-cpp/all/conandata.yml, recipes/wasmtime-cpp/config.yml
Specify library name and version:  **wasmtime-cpp/3.0.0**
---
=> wasmtime-cpp: add version 3.0.0

recipes/flatbuffers/all/conandata.yml, recipes/flatbuffers/config.yml
Specify library name and version:  **flatbuffers/22.11.23**
---
=> flatbuffers: add version 22.11.23

recipes/confu_json/all/conandata.yml, recipes/confu_json/config.yml
Specify library name and version:  **confu_json/0.0.10**
---
=> confu_json: add version 0.0.10

recipes/capstone/all/CMakeLists.txt, recipes/capstone/all/conandata.yml, recipes/capstone/all/conanfile.py, recipes/capstone/all/test_package/CMakeLists.txt, recipes/capstone/all/test_package/conanfile.py, recipes/capstone/all/test_v1_package/CMakeLists.txt, recipes/capstone/all/test_v1_package/conanfile.py
=> capstone: conan v2 support

recipes/zlib-ng/all/conanfile.py, recipes/zlib-ng/all/test_package/CMakeLists.txt, recipes/zlib-ng/all/test_package/conanfile.py, recipes/zlib-ng/all/test_package_v1/CMakeLists.txt, recipes/zlib-ng/all/test_v1_package/CMakeLists.txt, recipes/zlib-ng/all/test_v1_package/conanfile.py
=> zlib-ng: modernize more

recipes/gcem/all/conanfile.py, recipes/gcem/all/test_package/CMakeLists.txt, recipes/gcem/all/test_package/conanfile.py, recipes/gcem/all/test_v1_package/CMakeLists.txt, recipes/gcem/all/test_v1_package/conanfile.py
CMake imported target is not namespaced: https://github.com/kthohr/gcem/blob/68e01fae5c8b074fdeafb975cd3f06c13f1f1965/CMakeLists.txt#L101-L103
---
=> gcem: conan v2 support + fix CMake imported target

recipes/cpu_features/all/CMakeLists.txt, recipes/cpu_features/all/conandata.yml, recipes/cpu_features/all/conanfile.py, recipes/cpu_features/all/test_package/CMakeLists.txt, recipes/cpu_features/all/test_package/conanfile.py, recipes/cpu_features/all/test_v1_package/CMakeLists.txt, recipes/cpu_features/all/test_v1_package/conanfile.py
=> cpu_features: conan v2 support

recipes/litehtml/all/CMakeLists.txt, recipes/litehtml/all/conandata.yml, recipes/litehtml/all/conanfile.py, recipes/litehtml/all/test_package/CMakeLists.txt, recipes/litehtml/all/test_package/conanfile.py, recipes/litehtml/all/test_v1_package/CMakeLists.txt, recipes/litehtml/all/test_v1_package/conanfile.py
=> litehtml: conan v2 support

recipes/polymorphic_value/all/conanfile.py, recipes/polymorphic_value/all/test_package/CMakeLists.txt, recipes/polymorphic_value/all/test_package/conanfile.py, recipes/polymorphic_value/all/test_v1_package/CMakeLists.txt, recipes/polymorphic_value/all/test_v1_package/conanfile.py
Specify library name and version:  **polymorphic_value/***
done as part of @prince-chrismc's webinar
---
=> polymorphic_value: conan v2 support

recipes/heatshrink/all/CMakeLists.txt, recipes/heatshrink/all/conanfile.py, recipes/heatshrink/all/test_package/CMakeLists.txt, recipes/heatshrink/all/test_package/conanfile.py, recipes/heatshrink/all/test_v1_package/CMakeLists.txt, recipes/heatshrink/all/test_v1_package/conanfile.py
=> heatshrink: conan v2 support

recipes/arrow/all/conanfile.py
compute module is also required by parquet module: https://github.com/apache/arrow/commit/75cf66a895e257cb3a432d57c3d8bfa70febb0da#diff-645ff3e44561e45a579725c47e88f7b46b0120f240c4999ab82770a128044e97R25
---
=> arrow: fix compute option dependency

recipes/boost/all/conanfile.py
Use C++17's std::filesystem::path, std::system_error and std::error_code
Closes #14402 
---
=> (#14402) boost: Add filesystem_use_std_fs option

recipes/cpp-httplib/all/conandata.yml, recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.11.3**
---
=> cpp-httplib: add version 0.11.3

recipes/mikktspace/all/CMakeLists.txt, recipes/mikktspace/all/conanfile.py, recipes/mikktspace/all/test_package/CMakeLists.txt, recipes/mikktspace/all/test_package/conanfile.py, recipes/mikktspace/all/test_package/test_package.c, recipes/mikktspace/all/test_v1_package/CMakeLists.txt, recipes/mikktspace/all/test_v1_package/conanfile.py
=> mikktspace: conan v2 support

recipes/jfalcou-eve/all/conandata.yml, recipes/jfalcou-eve/config.yml
Specify library name and version:  **jfalcou-eve/v2022.09.1**
Version upgrade
---
=> [jfalcou-eve] upgrade to v2022.09.1

recipes/geotrans/all/CMakeLists.txt, recipes/geotrans/all/conandata.yml, recipes/geotrans/all/conanfile.py, recipes/geotrans/all/test_package/CMakeLists.txt, recipes/geotrans/all/test_package/conanfile.py, recipes/geotrans/all/test_v1_package/CMakeLists.txt, recipes/geotrans/all/test_v1_package/conanfile.py
=> geotrans: conan v2 support

recipes/easyloggingpp/all/CMakeLists.txt, recipes/easyloggingpp/all/conanfile.py
Specify library name and version: easyloggingpp/9.97.0
Exposes more configuration options to conan.
---
=> easyloggingpp: add options

recipes/libsodium/all/conandata.yml, recipes/libsodium/all/conanfile.py, recipes/libsodium/all/test_package/CMakeLists.txt, recipes/libsodium/all/test_package/conanfile.py, recipes/libsodium/all/test_v1_package/CMakeLists.txt, recipes/libsodium/all/test_v1_package/conanfile.py
I expect this to build on the CI ok, and the latest version builds locally on vs2022,
but interestingly (bug in conan?), I can't get it to build the older 1.0.18 version for vs2022.
The older 1.0.18 has a vs2019 (and older) sln only, and the new autotools doesn't seem to have a vs-upgrade_project option anymore, so the build fails and asks me to install vs2019.
I'm not sure what to do about that.
=> libsodium: support conan v2

recipes/qarchive/all/CMakeLists.txt, recipes/qarchive/all/conandata.yml, recipes/qarchive/all/conanfile.py, recipes/qarchive/all/test_package/conanfile.py, recipes/qarchive/all/test_package/test_package.cpp, recipes/qarchive/all/test_v1_package/CMakeLists.txt, recipes/qarchive/all/test_v1_package/conanfile.py, recipes/qarchive/config.yml
Add support for the latest version and modernize recipe and test packages.
---
=> QArchive: Add version 2.2.2 and modernize

recipes/libgettext/all/conanfile.py
For MSVC / VisualStudio, you need the -FS if multiple compiler instances are writing to the same .PDB at the same time.
The existing recipe adds `-FS` correctly, but only when building in Debug mode.
This change adds the flag for the RelWithDebInfo mode as well.
=> libgettext - add -FS flag for RelWithDebInfo as well as Debug builds

recipes/stb/all/conandata.yml, recipes/stb/config.yml
Specify library name and version:  **stb/cci.20220909**
---
=> stb: add version cci.20220909 for restoring stb_perlin.h

recipes/miniaudio/all/CMakeLists.txt, recipes/miniaudio/all/conandata.yml, recipes/miniaudio/all/conanfile.py, recipes/miniaudio/all/test_package/CMakeLists.txt, recipes/miniaudio/all/test_package/conanfile.py, recipes/miniaudio/all/test_v1_package/CMakeLists.txt, recipes/miniaudio/all/test_v1_package/conanfile.py, recipes/miniaudio/config.yml
Specify library name and version:  **miniaudio/***
---
=> miniaudio: add version 0.11.11, support conan v2

recipes/arrow/all/conanfile.py
Specify library name and version:  **arrow/10.0.0**
I am submitting this pull request to fix the bug in Parquet component when building the Arrow package as static library: closes https://github.com/conan-io/conan-center-index/issues/14374
This should fix the issue, but the tests should be added to ensure they check against.  Can somebody please advice or point to an example s of where tests optionally check against a sub component of a package and I am happy to add to the tests.
---
=> [arrow] Ensure static library do not attempt to dllimport symbols

recipes/libpqxx/all/CMakeLists.txt, recipes/libpqxx/all/conandata.yml, recipes/libpqxx/all/conanfile.py, recipes/libpqxx/all/patches/0001-cmake-fix-module-6.4.8.patch, recipes/libpqxx/all/test_package/CMakeLists.txt, recipes/libpqxx/all/test_package/conanfile.py, recipes/libpqxx/all/test_v1_package/CMakeLists.txt, recipes/libpqxx/all/test_v1_package/conanfile.py, recipes/libpqxx/config.yml
Specify library name and version:  **libpqxx/***
- add version 6.4.8 (last C++14 version)
- suppor conan v2
---
=> libpqxx: add version 6.4.8, support conan v2, remove older versions

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.76.3**
---
=> daw_header_libraries: add version 2.76.3

recipes/daw_utf_range/all/conandata.yml, recipes/daw_utf_range/config.yml
Specify library name and version:  **daw_utf_range/2.2.3**
---
=> daw_utf_range: add version 2.2.3

recipes/verilator/all/conanfile.py
Specify library name and version:  **verilator/4.224**
verilator_ccache_report and verilator_includer scripts were missing in the previous conan package,
but they are available in the official verilator release https://github.com/verilator/verilator/tree/v4.224/bin
So this patch just adds them to the conan package.
---
=> Verilator:  ccache_report and includer scripts were missing in the conan package

recipes/binutils/all/conanfile.py
Specify library name and version:  binutils, all versions
Remove logic defining environment variables for each executable inside the package. This is being actively investigated, but these were not part of the recipe until https://github.com/conan-io/conan-center-index/pull/14137, which was very recently merged.
Should these variables be needed, we can revisit the logic and ensure that the `test_package` covers the relevant use cases.
Close https://github.com/conan-io/conan-center-index/issues/14566
=> Partially revert logic defining environment variables in binutils recipe

recipes/json-schema-validator/all/conandata.yml, recipes/json-schema-validator/all/patches/2.2.0-signed-char.patch
Specify library name and version:  **json-schema-validator/2.2.0**
https://github.com/pboettch/json-schema-validator/pull/242
=> Fix json-schema-validator build on arm64/GCC 9.4

recipes/pybind11_json/all/conandata.yml, recipes/pybind11_json/config.yml
Specify library name and version:  **pybind11_json/0.2.13**
Just a new version patch by [Conan Center Bot](https://github.com/qchateau/conan-center-bot). /cc @qchateau 
---
=> pybind11_json: add version 0.2.13

recipes/libzip/all/conandata.yml
https://libzip.org is down
Use github mirror for releases.
The difference in SHA-s is related to .github directory and .clang-format file, which are present in github release.
The source was compared to original used by conan to avoid potential attack by getting libzip.org down and fak-ing github sources
Specify library name and version:  **libzip/all**
Closes #14620
---
=> (#14620) libzip: Use robust github mirror

recipes/googleapis/all/conanfile.py
Specify library name and version:  **googleapis/all**
An issue was reported were installation was failing due to an out of date settings.yml were `msvc` was missing (https://github.com/conan-io/conan/issues/12646). In Conan 2 the opposite is the case ("Visual Studio" is no longer the compiler name). This PR updates the recipe logic such that it uses the helper that abstracts away the compiler check in a way that is compatible with both (and, also, covers the case for users with an older settings.yml in conan 1.x)
=> [googleapis] Use is_msvc to abstract away compiler name setting

recipes/flatbuffers/all/conandata.yml, recipes/flatbuffers/config.yml
Specify library name and version:  **flatbuffers/22.12.06**
---
=> flatbuffers: add version 22.12.06

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.35.5**
---
=> etl: add version 20.35.5

recipes/boost-leaf/all/conandata.yml, recipes/boost-leaf/all/conanfile.py, recipes/boost-leaf/all/test_package/CMakeLists.txt, recipes/boost-leaf/all/test_package/conanfile.py, recipes/boost-leaf/all/test_package/main.cpp, recipes/boost-leaf/all/test_v1_package/CMakeLists.txt, recipes/boost-leaf/all/test_v1_package/conanfile.py, recipes/boost-leaf/config.yml
Resolves boostorg/leaf#47
Specify library name and version:  **boost-leaf/1.81.0-prerelease**
I work with and have consent by the author to put `Boost.LEAF` on the Conan Center Index. This library is a dependency of my library `libhal`.
---
=> Add Boost.LEAF to Conan Center

docs/changelog.md
A couple of comments on the changes:
- New env var for macos to select the xcode version will allow the service to build for different apple-clang versions regardless of the machine we select. Previously, each macos machine had only one apple-clang compiler and this caused huge bottlenecks. Now with other env vars like `SDKROOT` and `MACOSX_DEPLOYMENT_TARGET` we make sure that the environment is the correct one to produce the same binaries.
- We have added a check to verify out windows machines have long paths enabled. However, they have not been updated yet (they had this reg key disabled). It will be added soon and updated its status at https://github.com/conan-io/conan-center-index/issues/14216
=> Update changelog 09-December-2022

recipes/sqlite_orm/all/conandata.yml, recipes/sqlite_orm/config.yml
Specify library name and version:  **sqlite_orm/1.8**
---
=> sqlite_orm: add version 1.8

recipes/fast_double_parser/all/conandata.yml, recipes/fast_double_parser/config.yml
Specify library name and version:  **fast_double_parser/0.7.0**
---
=> fast_double_parser: add version 0.7.0

recipes/luau/all/conandata.yml, recipes/luau/config.yml
Specify library name and version:  **luau/0.556**
---
=> luau: add version 0.556

recipes/tgbot/all/conandata.yml, recipes/tgbot/config.yml
Specify library name and version:  **tgbot/1.5**
---
=> tgbot: add version 1.5

recipes/imath/all/conandata.yml, recipes/imath/config.yml
Specify library name and version:  **imath/3.1.6**
---
=> imath: add version 3.1.6

recipes/android-ndk/all/conanfile.py
define new `tools.build:compiler_executables` config introduced in conan 1.55.0, see https://github.com/conan-io/conan/pull/12556
---
=> android-ndk: define `tools.build:compiler_executables` config

recipes/icu/all/conanfile.py
Specify library name and version: icu/*
Fixes https://github.com/conan-io/conan-center-index/issues/14513.
Workaround for https://github.com/conan-io/conan/issues/12642.
Passing `--with-cross-build` icu config options messes up with `AutotoolsToolchain` and it doesn't pass `--build` option.
---
=> ICU: Workaround for proper cross-building after conan v2 recipe update

recipes/llvm-core/all/CMakeLists.txt, recipes/llvm-core/all/conanfile.py
There is no reason why we can't allow compiling with ZLIB support on Windows. It is supported and works fine in my tests with version 13.0.0.
Let's see if the CI agrees.
Specify library name and version:  **llvm-core/<all_versions>**
---
=> [llvm-core] Allow to compile with ZLIB support on Windows

recipes/boost-ext-ut/all/conanfile.py, recipes/boost-leaf/all/conanfile.py
Reverting Boost Leaf as it's part of Boost itself and does not make sense splitting Boost, as we already tried in the past. 
https://github.com/conan-io/conan-center-index/pull/14525#pullrequestreview-1211744714
/cc @grafikrobot 
---
=> Deprecate Boost.LEAF

recipes/hana/all/conanfile.py
Specify library name and version:  **hana/1.79.0**
This PR is the continuation of #14660. We decided to keep only Boost as main package.
---
=> [hana] Deprecate package in favor of Boost

recipes/catch2/3.x.x/conandata.yml, recipes/catch2/config.yml
Specify library name and version:  **catch2/3.2.1**
---
=> catch2: add version 3.2.1

recipes/libdeflate/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/14545
---
=> libdeflate: fix installation for conan >=1.55.0

recipes/wasmedge/all/conandata.yml, recipes/wasmedge/all/conanfile.py, recipes/wasmedge/all/test_package/CMakeLists.txt, recipes/wasmedge/all/test_package/conanfile.py, recipes/wasmedge/all/test_v1_package/CMakeLists.txt, recipes/wasmedge/all/test_v1_package/conanfile.py, recipes/wasmedge/config.yml
Specify library name and version:  **wasmedge/0.11.2**
---
=> wasmedge: add version 0.11.2, support conan v2

recipes/glfw/all/conanfile.py
- lib name suffix if shared on Windows: https://github.com/glfw/glfw/blob/3.3.8/src/CMakeLists.txt#L165-L169
- GLFW_DLL: https://github.com/glfw/glfw/blob/3.3.8/src/CMakeLists.txt#L172
- don't force static link to libgcc if MinGW since it may not be the default behavior of the compiler, so it's removed (but users can statically link to libgcc with appropriate flags in profile)
---
=> glfw: few fixes for MinGW (shared lib name, no static link to libgcc, define GLFW_DLL)

recipes/libarchive/all/conanfile.py
=> libarchive: Use rm_safe from Conan 1.53 and fix cmake_layout import

recipes/libmount/all/conanfile.py
```
make[4]: Leaving directory '/var/home/jordan/.conan/data/libmount/2.36.2/_/_/build/6ebfbd5253c2e471abd9b05fe5694d02f770a3af/build-debug'
make[3]: Leaving directory '/var/home/jordan/.conan/data/libmount/2.36.2/_/_/build/6ebfbd5253c2e471abd9b05fe5694d02f770a3af/build-debug'
make[2]: Leaving directory '/var/home/jordan/.conan/data/libmount/2.36.2/_/_/build/6ebfbd5253c2e471abd9b05fe5694d02f770a3af/build-debug'
make[1]: Leaving directory '/var/home/jordan/.conan/data/libmount/2.36.2/_/_/build/6ebfbd5253c2e471abd9b05fe5694d02f770a3af/build-debug'
[HOOK - conan-center.py] post_package(): [PACKAGE LICENSE (KB-H012)] OK
[HOOK - conan-center.py] post_package(): ERROR: [DEFAULT PACKAGE LAYOUT (KB-H013)] Unknown folder 'usr' in the package …
```
=> libmount: Remove usr directory

recipes/dbus/1.x.x/conanfile.py, recipes/dbus/1.x.x/test_v1_package/CMakeLists.txt
Fix cmake_layout import.
Update dependencies.
---
=> dbus: Use rm_safe from Conan 1.53 and simplify test package

recipes/duckdb/all/conandata.yml, recipes/duckdb/all/conanfile.py, recipes/duckdb/all/test_v1_package/CMakeLists.txt, recipes/duckdb/config.yml
Specify library name and version:  **duckdb/***
- add version 0.6.1
- update openssl
---
=> duckdb: add version 0.6.1, update openssl

recipes/b2/portable/conanfile.py
Specify library name and version:  **b2/all**
Readd toolset option for install that was lost during conan v2 migration.
Fixes #14621
---
=> b2: pass toolset to b2

recipes/range-v3/all/conanfile.py
Specify library name and version:  **ranges-v3/all**
* Use `is_msvc` to check for the Visual C++ compiler instead of testing for the compiler name, as Conan 2 will raise an error since `Visual Studio` was removed in favour of `msvc`
* Use `self.output.warning` instead of `warn` which is no longer in conan 2
=> [ranges-v3] Fix issues with ranges-v3 recipe in Conan 2.0

recipes/shapelib/all/conanfile.py
=> shapelib: Use rm_safe from Conan 1.53 and fix cmake_layout import

recipes/modern-cpp-kafka/all/conandata.yml, recipes/modern-cpp-kafka/all/conanfile.py, recipes/modern-cpp-kafka/all/test_package/CMakeLists.txt, recipes/modern-cpp-kafka/all/test_package/conanfile.py, recipes/modern-cpp-kafka/all/test_v1_package/CMakeLists.txt, recipes/modern-cpp-kafka/all/test_v1_package/conanfile.py, recipes/modern-cpp-kafka/config.yml
Specify library name and version:  **modern-cpp-kafka/***
- add version 2022.12.07
- update librdkafka
- add cmake_file_name
---
=> modern-cpp-kafka: add version 2022.12.07, support conan v2

recipes/wayland-protocols/all/conanfile.py, recipes/wayland-protocols/all/test_package/conanfile.py, recipes/wayland-protocols/all/test_v1_package/conanfile.py
=> wayland-protocols: Update Meson

.c3i/config_v1.yml, .c3i/config_v2.yml
New windows machines added to the CI (with new environment for conan 1.54.0 and long paths enabled)
closes #14624 
Related to the latest changes described at #14658 as it closes https://github.com/conan-io/conan-center-index/issues/14216
=> [config] Add new windows nodes and bump conan v1 version

recipes/boost/all/conandata.yml, recipes/boost/all/conanfile.py, recipes/boost/all/test_package/CMakeLists.txt, recipes/boost/all/test_package/conanfile.py, recipes/boost/all/test_v1_package/CMakeLists.txt, recipes/boost/all/test_v1_package/conanfile.py, recipes/boost/config.yml
=> boost: conan v2 support

recipes/unicorn/all/CMakeLists.txt, recipes/unicorn/all/conandata.yml, recipes/unicorn/all/conanfile.py, recipes/unicorn/all/patches/2.0.0-0002-cmake-msvc-runtime.patch, recipes/unicorn/all/patches/2.0.1-0001-cmake-msvc-support.patch, recipes/unicorn/all/patches/2.0.1-0002-cmake-msvc-runtime.patch, recipes/unicorn/all/test_package/conanfile.py, recipes/unicorn/all/test_v1_package/CMakeLists.txt, recipes/unicorn/all/test_v1_package/conanfile.py, recipes/unicorn/config.yml
Specify library name and version:  **unicorn/2.0.1**
Also fixed the issue about 2.0.0 when the architecture list was not applied to `UNICORN_ARCH`.
If anyone can check arm builds, they could be fixed in 2.0.1.
---
=> add unicorn/2.0.1 + conan v2

recipes/opentdf-client/all/conandata.yml, recipes/opentdf-client/config.yml
Specify library name and version: opentdf-client/1.3.6
- Use oidc token endpoint from .well-known/openid-configuration file
---
=> opentdf-client: add version 1.3.6

recipes/arrow/all/conanfile.py
compute module and gandiva module use utf8proc:
* https://github.com/apache/arrow/blob/apache-arrow-10.0.1/cpp/src/arrow/compute/kernels/scalar_string_utf8.cc#L22-L24
* https://github.com/apache/arrow/blob/apache-arrow-10.0.1/cpp/cmake_modules/DefineOptions.cmake#L330-L335
---
=> arrow: fix with_utf8proc option dependency

recipes/catch2/3.x.x/conanfile.py
Specify library name and version:  **catch2/3.x**
`catch2` has a build parameter which can set the width of the console. By default it is 80, but in some cases it might be good to make this wider. I set up an arbitrary upper bound in this PR.
I am not sure if for such a small change I need to [Request access](https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/README.md#request-access) - as it is also not a new package. But in any case let me know.
---
=> catch2: add console_width parameter

recipes/libzip/all/conandata.yml, recipes/libzip/all/conanfile.py, recipes/libzip/config.yml
find_package(Zstd) was replaced to find_package(Zstd, 1.3.6)
Specify library name and version:  **libzip/1.9.2**
Closes #14632
---
=> (#14632) libzip: Bump to 1.9.2

recipes/libressl/all/CMakeLists.txt
Specify library name and version:  **libressl/3.0.2**
Compiling libressl/3.0.2 with Visuao Studio 2022 will fail. Here are part of error output.
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt_malloc.h(125,24): error C2485: 'constant': unrecognized extended attribute (compiling source file C:\Users\zgzf1\.conan\data\libressl\3.0.2\_\_\build\2b1be0a8976ecd1cd27d7c3d01af9a8d736344f8\source_subfolder\crypto\ui\ui_openssl_win.c) [C:\Users\zgzf1\.conan\data\libressl\3.0.2\_\_\build\2b1be0a8976ecd1 cd27d7c3d01af9a8d736344f8\source_subfolder\crypto\crypto.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\corecrt_malloc.h(132,24): error C2485: 'constant': unrecognized extended attribute (compiling source file …
```
=> fix libressl build error with Visual Studio 2022

recipes/perfetto/all/conandata.yml, recipes/perfetto/all/patches/v31.0/0001-tracing-fix-compile-on-MSVC.patch
Specify library name and version:  **perfetto/31.0**
Bugreport: https://github.com/google/perfetto/issues/407
Bugfix: https://android-review.googlesource.com/c/platform/external/perfetto/+/2355222
The patch is located in `sdk.h` since this file is a result of multiple headers homologation during perfetto release process.
The fix is only needed till 32.0 is released and already merged to master.
Closes #14752 
---
=> (#14752) perfetto: Fix MSVC build for v31.0

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
- add version 0.2.2
- fix wrong url for 0.2.1 (sorry, my fault)
- delete older versions
---
=> glaze: add version 0.2.2, fix wrong url for 0.2.1, delete older versions

recipes/simdutf/all/conandata.yml, recipes/simdutf/config.yml
Specify library name and version:  **simdutf/2.0.9**
---
=> simdutf: add version 2.0.9

recipes/c-blosc2/all/conandata.yml, recipes/c-blosc2/config.yml
Specify library name and version:  **c-blosc2/2.6.1**
---
=> c-blosc2: add version 2.6.1

recipes/proj/all/CMakeLists.txt, recipes/proj/all/conandata.yml, recipes/proj/all/conanfile.py, recipes/proj/all/patches/0001-use-cmake-targets-6.x.x.patch, recipes/proj/all/patches/0001-use-cmake-targets-7.2.1.patch, recipes/proj/all/patches/0001-use-cmake-targets-8.0.0.patch, recipes/proj/all/patches/0001-use-cmake-targets-8.1.0.patch, recipes/proj/all/patches/0001-use-cmake-targets-8.1.1.patch, recipes/proj/all/patches/0001-use-cmake-targets-8.2.0.patch, recipes/proj/all/patches/0001-use-cmake-targets-9.0.0.patch, recipes/proj/all/patches/0001-use-cmake-targets-9.0.1.patch, recipes/proj/all/patches/0001-use-cmake-targets-9.1.0.patch, recipes/proj/all/test_package/CMakeLists.txt, recipes/proj/all/test_package/conanfile.py, recipes/proj/all/test_v1_package/CMakeLists.txt, recipes/proj/all/test_v1_package/conanfile.py, recipes/proj/config.yml
A nice cmake project, but this is consumed a lot of other difference recipes.
I wonder about bin paths, virtual run envs and other such things will work properly with this new recipe.
How best to test?
closes #14090 
closes https://github.com/conan-io/conan-center-index/issues/13422
=> proj: support for conan v2

recipes/qt/6.x.x/conanfile.py
related to https://github.com/conan-io/conan-center-index/issues/13472
---
=> qt6: allow gcc11 and clang12 consumers

recipes/cd3-boost-unit-definitions/all/conanfile.py, recipes/cd3-boost-unit-definitions/all/test_package/CMakeLists.txt, recipes/cd3-boost-unit-definitions/all/test_v1_package/CMakeLists.txt
Some additional cleanup and changes from the last review.
Changed the boost dependency to a range [>=1.69.0]
---
=> cd3-boost-unit-definition updates

recipes/s2n/all/conandata.yml, recipes/s2n/config.yml
Specify library name and version:  **s2n/1.3.31**
---
=> s2n: add version 1.3.31

recipes/pybind11/all/test_package/conanfile.py
* Use new `Environment` object in `generate()` method instead of the legacy `environment_append` which is not present in Conan 2
* Fix import for `cmake_layout`, which is in `conan.tools.cmake`
=> Use new environment tool in pybind11 test_package for v2 compatibility

recipes/qt/6.x.x/conanfile.py
Specify library name and version:  **qt/\***
This PR closes #14603 
---
=> add dbus requirement for building qt webengine on linux

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.35.7**
---
=> etl: add version 20.35.7

.c3i/config_v1.yml, .c3i/config_v2.yml
- Enables merging feedback from conan v1 pipeline and conan v2 one.
- Adds title to conan v2 pipeline: informative, not required for merging the PR.
- Removes conan v2 export step in conan v1 pipeline
=> [config] Activate conan v2 pipeline feedback in github comments

recipes/cryptopp/all/conanfile.py
* Replace `tools_legacy.get_env("ANDROID_NDK_HOME")` with `self.conf.get("tools.android:ndk_path")`
* Constrain the copying of `cpu-features.h` to versions older than `8.4.0` - `cryptopp-cmake` already does it: https://github.com/abdes/cryptopp-cmake/blob/206aab4cb1e6e78b8460b8c0fe08449c280e321e/cryptopp/sources.cmake#L438-L443
=> CryptoPP: get android ndk path from tools.android:ndk_path conf

recipes/libtiff/all/conanfile.py
also:
- remove special handling of libjpeg-turbo since libjpeg-turbo & mozjpeg recipes now properly generate FindJPEG.cmake module file
- fine-grained propagation of libjpeg lib if coming from libjpeg-turbo or mozjpeg
---
=> libtiff: add mozjpeg to possible libjpeg implementations

docs/faqs.md
Docs!
This comes from #13866, with some offline conversations I had with other on the team.
We see this with projects like OpenSSL or Boost which are only partially using helpers from the main client but still have custom build tools/scripts involved.
=> docs: how we handle rare build system

recipes/libiconv/all/conanfile.py
libiconv 1.17 switched to the LGPL-2.1 from the LGPL-2.0 license. The Conan package previously didn't express the license for older versions correctly.
---
=> libiconv: Update SPDX license identifier and set license based on version

docs/adding_packages/README.md, docs/adding_packages/build_and_package.md, docs/adding_packages/test_packages.md, docs/error_knowledge_base.md, docs/faqs.md
This is a pretty straight forward move, I am trying to remove some of the clutter from the README for the next installment of 
#13673 
As this is a simple move I am not included to change the wording too much, this is weaker section and most of the examples are out of date. Future work on this one.
=> docs: Move build system examples to new file

recipes/bitsery/all/conandata.yml, recipes/bitsery/config.yml
Specify library name and version:  **bitsery/5.2.3**
---
=> bitsery: add version 5.2.3

docs/error_knowledge_base.md
Docs!
There has been some rare cases where package contents were moved into folders in order to avoid the hooks. 
This layout is a general default which works for most packages but has erroneous caused some to be moved and/or broken by accident.
=> docs: Improve language around folder layouts from hooks

docs/package_templates/header_only/all/conanfile.py
Found some things in the header-only template that could use a rewording to better understand their message when I was playing around with this, so I changed some of those comments.
This also removes one important comment as a result of #14845
=> Improve the comments in the header-only template

recipes/openssl/1.x.x/conandata.yml, recipes/openssl/1.x.x/conanfile.py, recipes/openssl/1.x.x/test_package/conanfile.py, recipes/openssl/1.x.x/test_package/digest.c
Specify library name and version:  **openssl/1.x.x**
Updated conanfile.py and test_package/conanfile.py to work with Conan 2.0.0-beta4 (Resolves #13991)
Changes involve leveraging Conan 2.0 generators and other syntactic changes
Tested on Linux, Windows, and Mac for 1.0.2u, 1.1.0l, and 1.1.1s
---
=> OpenSSL 1.x.x Conan 2.0 compatibility

recipes/xkbcommon/all/conanfile.py, recipes/xkbcommon/all/test_package/CMakeLists.txt, recipes/xkbcommon/all/test_package/conanfile.py, recipes/xkbcommon/all/test_v1_package/CMakeLists.txt, recipes/xkbcommon/all/test_v1_package/conanfile.py
=> xkbcommon: Use rm_safe from Conan 1.53 and simplify test package

recipes/mbits-semver/all/conandata.yml, recipes/mbits-semver/all/conanfile.py, recipes/mbits-semver/all/test_package/CMakeLists.txt, recipes/mbits-semver/all/test_package/conanfile.py, recipes/mbits-semver/all/test_package/test_package.cpp, recipes/mbits-semver/all/test_v1_package/CMakeLists.txt, recipes/mbits-semver/all/test_v1_package/conanfile.py, recipes/mbits-semver/config.yml
Specify library name and version:  **mbits-semver/0.1.1**
I am the author of this library, which is a lowest layer of dependencies of my other libraries.
---
=> add mbits-semver/0.1.1

recipes/usockets/all/conandata.yml, recipes/usockets/all/conanfile.py, recipes/usockets/all/patches/0001-makefile_0.8.3.patch, recipes/usockets/config.yml
Specify library name and version:  **usockets/0.8.3**
- add version 0.8.3
- Since 0.8.3, usockets don't provide `uSockets.vcxproj`, upstream provides makefile for cl.exe
---
=> usockets: add version 0.8.3

recipes/libcurl/all/conanfile.py, recipes/libcurl/all/test_package/test_package.c
Fix building shared library on MinGW windows
Specify library name and version:  **libcurl/7.78.0**
Closes https://github.com/conan-io/conan-center-index/issues/14668
---
=> Fix unix sockets configure error on MinGW windows

linter/check_layout_src_folder.py
Related to https://github.com/conan-io/conan-center-index/pull/14959
bazel_layout is still not documented but it is indeed in conan v2 since https://github.com/conan-io/conan/pull/10812/files
---
=> [linter] Fix vs_layout has no folder param. Adds bazel_layout

recipes/libxml2/all/conanfile.py
icu has components, therefore cpp_info of components must be aggregated first
see https://github.com/conan-io/conan/issues/12733
---
=> libxml2: fix msvc & mingw build tricks for icu

recipes/nanobench/all/conandata.yml, recipes/nanobench/all/conanfile.py, recipes/nanobench/all/patches/4.3.9-0001-support-older-msvc.patch, recipes/nanobench/all/test_package/CMakeLists.txt, recipes/nanobench/all/test_package/conanfile.py, recipes/nanobench/all/test_v1_package/CMakeLists.txt, recipes/nanobench/all/test_v1_package/conanfile.py, recipes/nanobench/config.yml
Specify library name and version:  **nanobench/***
- add version 4.3.9
- sort conandata.yaml, config.yml
---
=> nanobench: add version 4.3.9, support conan v2

recipes/homog2d/all/conandata.yml, recipes/homog2d/all/patches/0002-pretty_function-for-msvc.patch, recipes/homog2d/all/patches/0003-support-msvc.patch
Specify library name and version:  **homog2d/2.9**
create patch for msvc compilation error in upstream.
---
=> homog2d: fix msvc compilation error by proper way

.github/PULL_REQUEST_TEMPLATE.md
https://peps.python.org/pep-0008/#maximum-line-length This is the least followed thing in PRs so it seems a bit misleading to ask people to do this extra since it creates a lot of changes.
=> docs: remove PEP8 formating request

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.35.8**
---
=> etl: add version 20.35.8

.github/workflows/linter-yaml.yml, linter/conandata_yaml_linter.py
- Stop GitHub Actions from sending email notifications about failed workflows
- Lower the patch fields to a warning to accurately reflect they dont block PRs
closes #14865
=> linter: reduce spam for notification from actions + lower error level

recipes/zulu-openjdk/all/conandata.yml, recipes/zulu-openjdk/all/conanfile.py, recipes/zulu-openjdk/all/test_package/conanfile.py, recipes/zulu-openjdk/all/test_v1_package/conanfile.py, recipes/zulu-openjdk/config.yml
Specify library name and version:  **zulu-openjdk/all**
- Modernizing the recipe to be 2.0 compatible. Tested locally in Win with 1.55 and 2.0
- Removing old patch 11.0.8, it is a patch version, old enough, and allows simplifying a bit the recipe
- Minor updates to the recipe, like removing unnecessary settings
- 
---
=> Prepare zulu-openjdk for 2.0, remove old patch version

recipes/catch2/2.x.x/conanfile.py
=> catch2/2.x: use `self.info` in package id method

.github/PULL_REQUEST_TEMPLATE.md, docs/adding_packages/README.md
we have moved away from being on the bleeding edge and no longer keep the "available in ConanCenter's build service" to the latest as aggressively and are generally 1 behind to encourage stability
=> docs: Adjust PR template to say current client version

recipes/itlib/all/conandata.yml, recipes/itlib/config.yml
Specify library name and version:  **itlib/1.8.0**
---
=> itlib: add version 1.8.0

recipes/tuplet/all/conandata.yml, recipes/tuplet/config.yml
Specify library name and version:  **tuplet/2.1.0**
---
=> tuplet: add version 2.1.0

.github/PULL_REQUEST_TEMPLATE.md
Sadly CI merged before the action finished and we missed this.
---
=> Docs: fix bad link

recipes/libxlsxwriter/all/conandata.yml, recipes/libxlsxwriter/all/conanfile.py, recipes/libxlsxwriter/all/patches/1.1.5-0001-fix-cmake.patch, recipes/libxlsxwriter/config.yml
Specify library name and version:  **libxlsxwriter/***
- add version 1.1.5
- update minimum conan version to 1.53.0
---
=> libxlsxwriter: add version 1.1.5, use rm_safe

recipes/plog/all/conandata.yml, recipes/plog/all/conanfile.py, recipes/plog/all/test_package/CMakeLists.txt, recipes/plog/all/test_package/conanfile.py, recipes/plog/all/test_package/test_package.cpp, recipes/plog/all/test_v1_package/CMakeLists.txt, recipes/plog/all/test_v1_package/conanfile.py, recipes/plog/config.yml
Specify library name and version:  **plog/***
- add version 1.1.9
---
=> plog: add version 1.1.9, support conan v2

recipes/libjpeg/all/conandata.yml
Specify library name and version:  **libjpeg/9e**
libjpeg/9e: Configuring sources in C:\Users\runneradmin\.conan\data\libjpeg\9e\_\_\source\src
ERROR: libjpeg/9e: Error in source() method, line 65
get(self, **self.conan_data["sources"][self.version],
ConanException: sha256 signature failed for 'jpegsrc.v9e.tar.gz' file. 
Provided signature: 4077d6a6a75aeb01884f708919d25934c93305e49f7e3f36db9129320e6f4f3d  
Computed signature: 5d5349c3aacc978dfcbde11f7904d2965395261dd818ce21c15806f736b8911e
Issue was reported in #15044 
fixes #15044
=> Fix libjpeg/9e sha256 signature failed  

recipes/utfcpp/all/conandata.yml, recipes/utfcpp/all/conanfile.py, recipes/utfcpp/all/test_v1_package/CMakeLists.txt, recipes/utfcpp/config.yml
Specify library name and version:  **utfcpp/3.2.3**
- add version 3.2.3
---
=> utfcpp: add version 3.2.3

recipes/xkeyboard-config/all/conanfile.py
Use clear() instead of header_only() to make it work in v2
=> Make xkeyboard-config v2 compatible

recipes/openh264/all/conanfile.py
Specify library name and version:  **openh264/**
=> openh264: fix tools legacy

.c3i/config_v1.yml
Reverts conan-io/conan-center-index#14221
This is not needed as the lib couldn't build due to a compiler bug.
=> Revert "[config] Use larger resources to build cppfront packages"

recipes/faac/all/conandata.yml, recipes/faac/all/conanfile.py, recipes/faac/all/test_package/CMakeLists.txt, recipes/faac/all/test_package/conanfile.py, recipes/faac/all/test_v1_package/CMakeLists.txt, recipes/faac/all/test_v1_package/conanfile.py
=> faac: conan v2 support

recipes/qt/5.x.x/conandata.yml, recipes/qt/5.x.x/conanfile.py, recipes/qt/5.x.x/patches/337f28c9ab-5.15.5.patch, recipes/qt/5.x.x/patches/337f28c9ab.patch
Specify library name and version:  **qt/5.x**
after #14020 it's no longer possible to cross-compile from macOS to iOS as well as from macOS Intel to macOS ARM. These scenarios don't require passing `CROSS_COMPILE` option, see e.g. https://doc.qt.io/qt-5/ios-building-from-source.html. The only valid option there I'm aware of is `-device-option QMAKE_APPLE_DEVICE_ARCHS=arm64` which Conan already passes.
Also added patch to fix building qtbase for iOS with Xcode 14.x. Had to modify the line number in the [original patch](https://code.qt.io/cgit/qt/qtbase.git/commit/src/corelib/global/qglobal.cpp?id=337f28c9abb12f28538cfe2f49e5afc460578b32) because Conan's patch applier is quite strict unlike the standard `patch` program.
---
=> qt5: Apple OSs don't require CROSS_COMPILE option

recipes/capnproto/all/CMakeLists.txt, recipes/capnproto/all/conandata.yml, recipes/capnproto/all/conanfile.py, recipes/capnproto/all/test_package/CMakeLists.txt, recipes/capnproto/all/test_package/conanfile.py, recipes/capnproto/all/test_v1_package/CMakeLists.txt, recipes/capnproto/all/test_v1_package/conanfile.py
This PR needs an update of openssl recipe due to https://github.com/conan-io/conan/issues/12106
---
=> capnproto: conan v2 support

recipes/m4/all/test_package/conanfile.py
Specify library name and version:  **m4/all**
Fixes the following issue when testing the package with Conan 2, by using a positional argument for the output variable, instead of a name one (the name differs between Conan 1 and 2).
```
m4/1.4.19 (test package): Error in test() method, line 35
self.run(f"m4 -P {self._m4_input_path}", output=output)
TypeError: run() got an unexpected keyword argument 'output'
```
=> m4: use positional arguments when calling self.run()

recipes/libjpeg/all/conandata.yml
Specify library name and version:  **libjpeg**
This PR continues https://github.com/conan-io/conan-center-index/pull/15045 and it's related to #4151
closes #13417
/cc @arekmula @mejdys @Wuqiqi123
---
=> [libjpeg] Update sha256 for 9e

recipes/libcurl/all/conanfile.py
Specify library name and version:  `libcurl/*`
With cmake build, libcurl relies on internal cmake modules that find the dependencies. For libnghttp2, this behaviour is overridden in `_patch_cmake` by making cmake look for package `libnghttp2` instead of `NGHTTP2`. This package, however, is only generated with `CMakeDeps` generator, and due to lack of it the build failed on Windows. This commit adds this generator to the recipe.
---
=> libcurl: add CMakeDeps generator

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  **imgui/1.89.2**
---
=> imgui: add version 1.89.2

recipes/charls/all/conandata.yml, recipes/charls/config.yml
Specify library name and version:  **charls/2.4.1**
---
=> charls: add version 2.4.1

recipes/sentry-breakpad/all/conandata.yml, recipes/sentry-breakpad/config.yml
Specify library name and version:  **sentry-breakpad/0.5.3**
---
=> sentry-breakpad: add version 0.5.3

recipes/libsystemd/all/conandata.yml, recipes/libsystemd/config.yml
Specify library name and version:  **libsystemd/252.4**
A new version was released, and the linter suggestions were applied to conandata,yml.
---
=> libsystemd/252.4: bump version

recipes/libsodium/all/conanfile.py
In https://github.com/conan-io/conan-center-index/pull/15041, I've removed micro management of `msbuild.platform` when arch is x86. It was a mistake, the default value in `MSBuild` helper is not correct for libsodium. It must be `Win32` (instead of the default value of `MSBuild` which is `x86`).
---
=> libsodium: fix a regression of x86 msvc build

recipes/foonathan-lexy/all/conandata.yml, recipes/foonathan-lexy/config.yml
Specify library name and version:  **foonathan-lexy/2022.12.1**
---
=> foonathan-lexy: add version 2022.12.1

recipes/roaring/all/conandata.yml, recipes/roaring/config.yml
Specify library name and version:  **roaring/0.8.1**
---
=> roaring: add version 0.8.1

recipes/qt/6.x.x/conanfile.py
Include `xkbcommon` when building with qtwayland enabled.
See related issues #15114 and #14719.
These changes have been submitted for qt/5.x.x in PR #15116 .
---
=> qt/6.x.x: Don't require xorg when gui option is enabled

recipes/luajit/all/conandata.yml, recipes/luajit/all/conanfile.py, recipes/luajit/all/patches/2.1.0-beta3-0001-remove-mac-deploy.patch, recipes/luajit/all/patches/20230104-0001-remove-mac-deploy.patch, recipes/luajit/all/test_package/CMakeLists.txt, recipes/luajit/all/test_package/conanfile.py, recipes/luajit/all/test_v1_package/CMakeLists.txt, recipes/luajit/all/test_v1_package/conanfile.py, recipes/luajit/config.yml
Specify library name and version: luajit/2.1.0-beta3
* The PR #11904  can not be re-opened
* luajit is not prepared to cross-compile from Mac intel to Mac M1
* Mac M1 support has been introduced on 2.1
* No stable release will be released soon, so beta is the only alternative
* Backporting to 2.0.5 M1 support requires a lot of effort
* Do not enforce default MACOSX_DEPLOYMENT_TARGET. It's not really mandatory and may break on OSX 12.
fixes https://github.com/conan-io/conan-center-index/issues/11884
/cc @Bobini1
---
=> [luajit] Add 2.1.0-beta3 

recipes/seasocks/all/conandata.yml, recipes/seasocks/all/conanfile.py, recipes/seasocks/all/test_package/CMakeLists.txt, recipes/seasocks/all/test_package/conanfile.py, recipes/seasocks/all/test_v1_package/CMakeLists.txt, recipes/seasocks/all/test_v1_package/conanfile.py, recipes/seasocks/config.yml
Specify library name and version:  **seasocks/***
- add version 1.4.5 (1.4.5 requires C++17)
- update zlib
---
=> seasocks: add version 1.4.5, support conan v2

recipes/mailio/all/CMakeLists.txt, recipes/mailio/all/conandata.yml, recipes/mailio/all/conanfile.py, recipes/mailio/all/test_package/CMakeLists.txt, recipes/mailio/all/test_package/conanfile.py, recipes/mailio/all/test_v1_package/CMakeLists.txt, recipes/mailio/all/test_v1_package/conanfile.py
Specify library name and version:  **mailio/***
- update dependencies 
---
=> mailio: update dependencies, support conan v2

recipes/quill/all/conandata.yml, recipes/quill/all/test_package/CMakeLists.txt, recipes/quill/config.yml
=> quill: add version 2.6.0, remove older versions

recipes/minizip/all/conanfile.py
Specify library name and version:  **minizip/all**
Fixes issue when creating the packages with Conan 2, where the `test_package` fails compilation because it cannot find headers from `zlib` or `bz2`.
=> minizip: add transitive_headers trait to dependencies (v2)

recipes/vorbis/all/conanfile.py
Specify library name and version:  **vorbis/all**
* Add dependency trait since vorbis consumers transitively require ogg headers (fixes test_package when using Conan 2)
* Safely remove `fPIC` option when building shared library (since on windows it's removed previously)
=> vorbis: add dependency trait and fix removal of fPIC options when on Windows

recipes/wayland-protocols/all/conanfile.py, recipes/wayland-protocols/all/test_package/conanfile.py, recipes/wayland-protocols/all/test_v1_package/conanfile.py
Specify library name and version:  **wayland-protocols/1.0**
---
=> wayland-protocols: Bump Meson version to 1.0.0

recipes/boost/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/15070
---
=> boost: handle spaces in path to C++ compiler

recipes/libffi/all/conanfile.py
=> libffi: Use rm_safe to delete options in the configure method

.c3i/config_v1.yml
Temporarily disable reporting status from Conan v2 pipeline - it will still run but not report status. 
Will be restored once we fix the bug of the failed tags, as well as making sure the latest beta is used.
=> Maintenance: temporarily disable message reports from Conan v2 pipeline

recipes/capnproto/all/conandata.yml, recipes/capnproto/config.yml
Specify library name and version:  **capnproto/0.10.3**
There is a patch for security advisory.
https://github.com/capnproto/capnproto/blob/master/security-advisories/2022-11-30-0-pointer-list-bounds.md
---
=> capnproto: add version 0.10.3 (for CVE-2022-46149)

recipes/odbc/all/conanfile.py, recipes/odbc/all/test_package/conanfile.py
Specify library name and version:  **odbc/all**
This package contains both library and executables, assuming that this one is primarily to be consumed as a library.
The `test_package` consumes it as a library (to build the test project against it), but it also launches an executable from the package - in this case, the consumer needs to express that it also requires the the runtime components of odbc.
This PR fixes the test_package when run with Conan 2.
=> odbc: add package type attribute and fix dependency trait in test_package

recipes/tsl-robin-map/all/conandata.yml, recipes/tsl-robin-map/all/test_v1_package/CMakeLists.txt, recipes/tsl-robin-map/config.yml
Specify library name and version:  **tsl-robin-map/1.2.1**
- add version 1.2.1
---
=> tsl-robin-map: add version 1.2.1

recipes/libcurl/all/conanfile.py
closes: #15052 
Specify library name and version:  **libcurl/all**
---
=> - [libcurl] enable Unicode

recipes/qcustomplot/all/conandata.yml, recipes/qcustomplot/config.yml
Specify library name and version:  **qcustomplot/2.1.1**
This is just a bump to the latest version of QCustomPlot.
---
=> Update qcustomplot to version 2.1.1

recipes/minizip-ng/all/conandata.yml, recipes/minizip-ng/all/conanfile.py, recipes/minizip-ng/all/patches/3.0.8-0001-fix-cmake-project.patch, recipes/minizip-ng/config.yml
Specify library name and version:  **minizip-ng/3.0.8**
- add version 3.0.8
- update xz_utils
---
=> minizip-ng: add version 3.0.8, update xz_utils

recipes/cityhash/all/conanfile.py, recipes/cityhash/all/test_package/conanfile.py, recipes/cityhash/all/test_v1_package/CMakeLists.txt, recipes/cityhash/all/test_v1_package/conanfile.py
=> cityhash: conan v2 support

recipes/libmp3lame/all/conanfile.py
`libmp3lame` shared lib was relocatable on macOS (`@rpath` in install_name) since https://github.com/conan-io/conan-center-index/pull/9457, but https://github.com/conan-io/conan-center-index/pull/13791 broke it by removing the patch without using `fix_apple_shared_install_name()` after packaging.
---
=> libmp3lame: restore relocatable shared lib on macOS

recipes/at-spi2-core/config.yml, recipes/at-spi2-core/new/conandata.yml, recipes/at-spi2-core/new/conanfile.py
Specify library name and version:  **at-spi2-core/2.47.1**
---
=> at-spi2-core: Add version 2.47.1 and support for Conan v2

recipes/daw_json_link/all/conandata.yml, recipes/daw_json_link/all/conanfile.py, recipes/daw_json_link/config.yml
- add version 3.14.0
- update daw_header_libraries
---
=> daw_json_link: add version 3.14.0, remove older versions

recipes/civetweb/all/conanfile.py
Specify library name and version:  **civetweb/all**
The type of the version object differs in Conan 1.x and Conan 2.x. This PR fixes the following error when using Conan 2.
```
ERROR: civetweb/1.15: Error in generate() method, line 108
openssl_version = Version(str(self.dependencies["openssl"].ref.version[:-1]))
TypeError: 'Version' object is not subscriptable
```
=> civetweb: fix evaluation of openssl version in conan 2

recipes/bzip3/all/conandata.yml, recipes/bzip3/all/conanfile.py, recipes/bzip3/all/test_v1_package/CMakeLists.txt, recipes/bzip3/config.yml
Specify library name and version:  **bzip3/1.2.2**
- add version 1.2.2
---
=> bzip3: add version 1.2.2

recipes/xxhash/all/conandata.yml, recipes/xxhash/all/patches/0.8.1-fix-static-assert-link-error.patch
Specify library name and version:  **xxhash/0.8.1**
Fix (rare) link error.
On some systems linking to xxHash built with Conan fails due to error like the following:
```
[ 99%] Linking CXX executable main
/opt/conda/conda-bld/main_1672789533645/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/12.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: /root/.conan/data/xxhash/0.8.1/_/_/package/2a19826344ff00be1c04403f2f8e7008ed3a7cc6/lib/libxxhash.a(xxhash.c.o): in function `XXH3_hashLong_64b_default.constprop.0':
xxhash.c:(.text.XXH3_hashLong_64b_default.constprop.0+0x406): undefined reference to `static_assert'
```
This PR backports the bugfix from https://github.com/Cyan4973/xxHash/commit/6189ecd3d44a693460f86280ccf49d33cb4b18e1.
The link error is further described here: …
=> xxhash: fix (rare) link error

recipes/libinterpolate/all/conandata.yml, recipes/libinterpolate/all/conanfile.py, recipes/libinterpolate/all/test_package/CMakeLists.txt, recipes/libinterpolate/all/test_package/conanfile.py, recipes/libinterpolate/all/test_package/test_package.cpp, recipes/libinterpolate/all/test_v1_package/CMakeLists.txt, recipes/libinterpolate/all/test_v1_package/conanfile.py, recipes/libinterpolate/config.yml
libinterpolate/2.6.2
This is an interpolation library with a simple interface that I wrote. https://github.com/CD3/libInterpolate
I submitted a PR last week but the CI builds were failing, which I think was due to the C++17 requirement not being enforced in the recipe
---
=> added libinterpolate recipe

recipes/dcmtk/all/conanfile.py, recipes/dcmtk/all/test_package/conanfile.py
Specify library name and version:  **dcmtk/all**
PR [11126](https://github.com/conan-io/conan-center-index/pull/11126) makes the recipe build with `DCMTK_ENABLE_STL` set to `ON`, however, there is no option to disable building with stl.  This PR allows disabling stl in builds.
dcmtk builds with stl enabled will define the dcmtk type `OFString` as `std::string` (instead of using the dcmtk definition).  This breaks consumers who forward declare `OFString`.
---
=> dcmtk: Allow enabling/disabling stl via new option

recipes/qt/6.x.x/conandata.yml, recipes/qt/6.x.x/conanfile.py, recipes/qt/6.x.x/qtmodules6.4.2.conf, recipes/qt/config.yml
it avoids overriding https://github.com/qt/qtbase/blob/3b60534ab9a2f467cd44ee23a1429ed46d6d5a23/cmake/3rdparty/kwin/FindLibdrm.cmake and https://github.com/qt/qtbase/blob/3b60534ab9a2f467cd44ee23a1429ed46d6d5a23/cmake/3rdparty/extra-cmake-modules/find-modules/FindWayland.cmake
related to conan-io/conan-center-index#14884
fixes conan-io/conan-center-index#15001
---
=> qt6: 6.4.2 and disable generation of cmake file for libdrm and wayland

recipes/vorbis/all/conanfile.py
Specify library name and version:  **vorbis/all**
This recipe uses [requirement traits](https://docs.conan.io/en/2.0/reference/conanfile/methods.html#requirement-traits) (`transitive_headers=True`) which were introduced in [Conan 1.52.0](https://github.com/conan-io/conan/pull/11934).
---
=> vorbis: fix required_conan_version

recipes/libraw/all/CMakeLists.txt, recipes/libraw/all/conandata.yml, recipes/libraw/all/conanfile.py, recipes/libraw/all/test_package/CMakeLists.txt, recipes/libraw/all/test_package/conanfile.py, recipes/libraw/all/test_v1_package/CMakeLists.txt, recipes/libraw/all/test_v1_package/conanfile.py, recipes/libraw/config.yml
Specify library name and version:  **libraw/***
- add version 0.21.1
---
=> libraw: add version 0.21.1, support conan v2

recipes/luau/all/conandata.yml, recipes/luau/all/conanfile.py, recipes/luau/all/test_v1_package/CMakeLists.txt, recipes/luau/config.yml
Specify library name and version:  **luau/0.557**
- add version 0.558
---
=> luau: add version 0.558

recipes/protobuf/all/conanfile.py, recipes/protobuf/all/test_package/conanfile.py
It's the same workaround than the one we have in capnproto. Though, it doesn't help when zlib is shared (in the meantime zlib is usually available on macOS, so it works indirectly).
---
=> protobuf: fix shared when cross-building for macos

recipes/cpp-httplib/all/conandata.yml, recipes/cpp-httplib/all/conanfile.py, recipes/cpp-httplib/all/test_v1_package/CMakeLists.txt, recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/***
- add version 0.11.4
- remove "cpp-httplib" from topics
---
=> cpp-httplib: add version 0.11.4, remove older versions

recipes/avahi/all/conanfile.py
Fixes Avahi being unable to build due to not finding `glib-mkenums`.
---
=> avahi: Make glib a tool_requires for glib-mkenums

recipes/mppp/all/conanfile.py
Specify library name and version:  **mppp/***
- update boost
- add with_fmt in 0.27
---
=> mppp: update boost, add with_fmt in 0.27

recipes/mongo-c-driver/all/conandata.yml, recipes/mongo-c-driver/all/conanfile.py, recipes/mongo-c-driver/config.yml
Specify library name and version:  **mongo-c-driver/***
- add version 1.22.2
- update icu
---
=> mongo-c-driver: add version 1.22.2, update icu

recipes/vulkan-loader/all/conandata.yml, recipes/vulkan-loader/all/conanfile.py, recipes/vulkan-loader/all/patches/1.3.236.0-0001-cmake-minimum-required-3.10.patch
backport an upstream fix https://github.com/KhronosGroup/Vulkan-Loader/pull/1102, instead of adding CMake 3.16 to build requirements, since Vulkan-Loader maintainers seem to want to ensure that it can be built with CMake 3.10
---
=> vulkan-loader: avoid to rely on CMake 3.16 features

recipes/drogon/all/conanfile.py, recipes/drogon/all/test_package/CMakeLists.txt
- update boost
- use `export_conandata_patches`
- use C++17 in drogon/>=1.8.2
---
=> drogon: update boost, trivial improvement

recipes/coin-utils/all/conandata.yml, recipes/coin-utils/config.yml
Specify library name and version:  **coin-utils/2.11.6**
Dependency of coin-cbc/2.10.8 (PR to follow)
---
=> coin-utils : added 2.11.6

recipes/qarchive/all/conandata.yml, recipes/qarchive/config.yml
Specify library name and version:  **qarchive/2.2.4**
---
=> qarchive: add version 2.2.4

recipes/libcap/all/conanfile.py, recipes/libcap/all/test_package/conanfile.py, recipes/libcap/all/test_v1_package/CMakeLists.txt, recipes/libcap/all/test_v1_package/conanfile.py
Specify library name and version:  **libcap/***
---
=> libcap: Modernize

recipes/lz4/all/conandata.yml, recipes/lz4/all/conanfile.py, recipes/lz4/all/test_v1_package/conanfile.py
Specify library name and version:  **lz4/all**
Additionally, it does some other minor changes:
- Also uses rm_safe for compiler.cppstd & compiler.libcxx
- Cleans its topics up
- Uses `export_conandata_patches`
- Adds info to its patches
=> lz4: Fix fPIC unsafe remove in configure

recipes/boost/all/conanfile.py, recipes/boost/all/dependencies/dependencies-1.81.0.yml, recipes/boost/all/rebuild-dependencies.py, recipes/boost/all/test_package/CMakeLists.txt, recipes/boost/all/test_package/conanfile.py, recipes/boost/all/test_package/url.cpp, recipes/boost/all/test_v1_package/conanfile.py
Specify library name and version:  **boost/1.81.0**
Closes #14991
---
=> boost: add Boost.URL

recipes/tsl-ordered-map/all/conandata.yml, recipes/tsl-ordered-map/all/test_v1_package/CMakeLists.txt, recipes/tsl-ordered-map/config.yml
Specify library name and version:  **tsl-ordered-map/1.1.0**
---
=> tsl-ordered-map: add version 1.1.0

recipes/hazelcast-cpp-client/all/conandata.yml, recipes/hazelcast-cpp-client/all/patches/gcc_11_1_0.patch, recipes/hazelcast-cpp-client/config.yml
Specify library name and version:  **hazelcast-cpp-client/5.1.0**
---
=> hazelcast-cpp-client: add version 5.1.0

recipes/qt/5.x.x/conanfile.py
The xkbcommon library supports both X11 and Wayland. Qt expects xkbcommon to be available for Wayland.
This PR relaxes the restriction for xkbcommon to only be included when the qtwayland option is enabled. Additional validation has been added to ensure that xkbcommon has been configured with the required options for X11 and Wayland support as needed.
Fixes #15114.
Additionally, the X11 packages shouldn't be required when the `gui` option is enabled as Qt supports other backends. I've added a `with_x11` to allow opting out of the default behavior.
Fixes #14719.
One more fix I snuck in is for the installation destination when cross-building.
Setting `prefix` is not enough when cross-building for a particular device as documented [here](https://doc.qt.io/qt-5/configure-linux-device.html). …
=> qt/5.x.x: Use xkbcommon when the qtwayland option is enabled

recipes/gnu-config/all/test_package/conanfile.py
Specify library name and version:  **gnu-config/all - test package only**
Refactor test_package to remove call to legacy Conan tool. The purpose of the test_package is to test that the script is callable in a valid way - the previous logic was ignoring the output in case `get_gnu_triplet` returned something that `config.sub` doesn't support. Passing `--version` or an arbitrary triple is as good as any alternative.
=> gnu-config: refactor invocation of config.sub in test_package

recipes/openssl/1.x.x/conanfile.py
addresses review in https://github.com/conan-io/conan-center-index/pull/14066#discussion_r1056155846
closes https://github.com/conan-io/conan-center-index/issues/15258
---
=> openssl 1.x: fix Mingw build regression

recipes/libxml2/all/conanfile.py
Specify library name and version:  libxml2/all
In Conan 2, options doesn't have an `items()` method - this PR provides equivalent logic to pass the same flags to the configure script, while we review the interface in the Conan client.
=> libxml2: refactor access to option names

recipes/protobuf/all/conanfile.py, recipes/protobuf/all/test_package/CMakeLists.txt
Specify library name and version: **protobuf/***
`protoc` has `fork()` and `execv()`. These functions do not exist for tvOS.
It was opened as https://github.com/conan-io/conan-center-index/pull/14474, but protobuf still needs to be migrated to use CMakeToolchain at that time. Now, that protobuf was modernized in https://github.com/conan-io/conan-center-index/pull/14851, I'm opening this PR again to skip the build of `protoc` for tvOS.
---
=> protobuf: do not build protoc for tvos

recipes/libnghttp2/all/conandata.yml, recipes/libnghttp2/all/conanfile.py, recipes/libnghttp2/all/patches/1.40.0-remove-static-suffix.patch
Specify library name and version:  `libnghttp2/*`
This patch removes an explicit setting of `STATIC_LIB_SUFFIX` thus renaming static library back to `libnghttp2.a`. It also changes `package_info` to set `nghttp2_static` as a library name only for version 1.40.0 as pointed by the author of the original change in libnghttp2:
https://github.com/curl/curl/pull/7515#issuecomment-890320856
Fixes #6241
---
=> libnghttp2: do not specify static lib suffix

recipes/opencv/2.x/CMakeLists.txt, recipes/opencv/2.x/conandata.yml, recipes/opencv/2.x/conanfile.py, recipes/opencv/2.x/patches/0002-find-openexr.patch, recipes/opencv/2.x/test_package/CMakeLists.txt, recipes/opencv/2.x/test_package/conanfile.py, recipes/opencv/2.x/test_v1_package/CMakeLists.txt, recipes/opencv/2.x/test_v1_package/conanfile.py
it's basically https://github.com/conan-io/conan-center-index/pull/13406, but only 2.x.
---
=> opencv 2.x: conan v2 support

recipes/xpack/all/conandata.yml, recipes/xpack/all/conanfile.py, recipes/xpack/all/patches/1.0.2-0001-use-cci.patch, recipes/xpack/all/test_package/CMakeLists.txt, recipes/xpack/all/test_package/conanfile.py, recipes/xpack/all/test_v1_package/CMakeLists.txt, recipes/xpack/all/test_v1_package/conanfile.py, recipes/xpack/config.yml
Specify library name and version:  **xpack/***
- add version 1.0.3
- use cci packages(rapidjson, rapidxml)
---
=> xpack: add version 1.0.3, support conan v2

recipes/gcc/all/conanfile.py
Specify library name and version:  **gcc//11.3.0**
This PR addresses the remaining compatibility issues with using Conan 2.0 as noted in #15283. More specifically, Conan 2.0 uses a new package_folder paradigm where the package folder is not known until package time. 
As an aside, these changes were provided as feedback to PR #13896, but had to be deferred at the time because CCI was using an older version of Conan 1.x that didn't support the 2.0-compatible behavior.
---
=> GCC Conan 2.0 compatibility

recipes/websocketpp/all/conandata.yml, recipes/websocketpp/all/conanfile.py, recipes/websocketpp/all/patches/support-gcc-12.patch
Specify library name and version:  **websocketpp/***
websocketpp failed to be compiled on gcc 12 by following constructor/destructor definitions.
```
~endpoint<connection,config>() {}
```
---
=> websocketpp: support gcc 12

recipes/json_dto/all/conanfile.py, recipes/json_dto/all/test_package/example.cpp
Specify library name and version:  **json_dto/0.3**
---
=> Fix json_dto missing headers

recipes/openssl/1.x.x/conanfile.py
Specify library name and version:  **openssl/***
cf https://github.com/conan-io/conan-center-index/pull/15348#issuecomment-1396740925
---
=> openssl: regenerate binaries

recipes/automake/all/conanfile.py
`cpp_info.resdirs` is empty by default with layout(), it has to be explicitly set if there is some res or share folder.
---
=> automake: fix cpp_info.resdirs & more conan v2 stuff

recipes/hiredis/all/conanfile.py
Specify library name and version:  **hiredis/1.1.0**
Trying to make it works for conan2.
---
fixes #15330
=> (#15330) hiredis: use self.settings instead of self.info.settings

recipes/gtest/all/conandata.yml, recipes/gtest/all/conanfile.py, recipes/gtest/all/test_package/CMakeLists.txt, recipes/gtest/config.yml
Specify library name and version:  **gtest/1.13.0**
- add version 1.13.0
- Because gtest requires C++14 since 1.13.0, _minimum_compilers_version is updated.
---
=> gtest: add version 1.13.0

recipes/opencv/4.x/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/13171
---
=> opencv 4.x: fix injection of `cpu_baseline` and `cpu_dispatch` options in case of empty string

recipes/cctag/all/CMakeLists.txt, recipes/cctag/all/conandata.yml, recipes/cctag/all/conanfile.py, recipes/cctag/all/test_package/conanfile.py, recipes/cctag/all/test_v1_package/CMakeLists.txt, recipes/cctag/all/test_v1_package/conanfile.py
=> cctag: conan v2 support

recipes/soxr/all/CMakeLists.txt, recipes/soxr/all/conandata.yml, recipes/soxr/all/conanfile.py, recipes/soxr/all/test_package/conanfile.py, recipes/soxr/all/test_v1_package/CMakeLists.txt, recipes/soxr/all/test_v1_package/conanfile.py, recipes/soxr/all/test_v1_package/test_package_core.c, recipes/soxr/all/test_v1_package/test_package_lsr.c
Specify library name and version:  **soxr/0.1.3**
This should fix #14485. At least it is a workaround to get soxr compiled for the Apple Silicon Macs. Im not an expert with this new architecture and SIMD, but for me it seems it is not supported by Apple Silicon.
---
=> Fix soxr for Apple Silicon architecture

recipes/tracy/all/conanfile.py, recipes/tracy/all/test_package/test_package.cpp
Specify library name and version:  **tracy/0.9**
This patch fixes two issues with tracy library:
- Several tracy options where missing from the conan package. This patch adds them
- Tracy options set to ON are exported as PUBLIC defines in CMake. However, the conan package was not adding the corresponding defines, so the behavior was different between original CMakeLists and conan package. This patch fixes that
---
=> Add tracy options

recipes/kaitai_struct_cpp_stl_runtime/all/CMakeLists.txt, recipes/kaitai_struct_cpp_stl_runtime/all/conandata.yml, recipes/kaitai_struct_cpp_stl_runtime/all/conanfile.py, recipes/kaitai_struct_cpp_stl_runtime/all/patches/0001-cmake-minimum-required.patch, recipes/kaitai_struct_cpp_stl_runtime/all/test_package/CMakeLists.txt, recipes/kaitai_struct_cpp_stl_runtime/all/test_package/conanfile.py, recipes/kaitai_struct_cpp_stl_runtime/all/test_v1_package/CMakeLists.txt, recipes/kaitai_struct_cpp_stl_runtime/all/test_v1_package/conanfile.py, recipes/kaitai_struct_cpp_stl_runtime/config.yml
Specify library name and version:  **kaitai_struct_cpp_stl_runtime/***
---
=> kaitai_struct_cpp_stl_runtime: add version 0.10, support conan v 2

recipes/leptonica/all/conandata.yml, recipes/leptonica/all/conanfile.py, recipes/leptonica/config.yml
Specify library name and version:  **leptonica/1.83.0**
There is one moment I don't fully understand. Upstream uses `find_package(GIF)` which seems to be totally fine.
But Conan generators create a bunch of `giflib-*` files so the find_package doesn't find them but picks up a system include path `/Library/Frameworks/UnixImageIO.framework/Headers`. Using `find_package(GIFLIB)` fixes the problem.
Recent giflib changes do not change a `cmake_file_name` property. If it is not changed, why doesn't it work?
---
=> leptonica: add version 1.83.0

recipes/googleapis/all/CMakeLists.txt, recipes/googleapis/all/conandata.yml, recipes/googleapis/all/conanfile.py, recipes/googleapis/all/patches/cci.20210730/001-fix-google-api-deps.patch, recipes/googleapis/all/patches/cci.20211122/001-fix-google-api-deps.patch, recipes/googleapis/all/patches/cci.20220531/001-fix-google-api-deps.patch, recipes/googleapis/all/patches/cci.20220711/001-fix-google-api-deps.patch, recipes/googleapis/all/test_package/conanfile.py, recipes/googleapis/all/test_package/test_package.cpp
The googleapis package contains over 500 libraries. These libraries depend on each other, and cannot be statically linked successfully if the libraries are out of order.
We use a file in the package to preserve this dependency order. It seems like too much of a maintenance burden to keep such information in the `conanfile.py` code.
Specify library name and version:  **googleapis/_**
Fixes #14881 
---
=> fix: preserve dependencies between googleapis libs

recipes/libsvtav1/all/conandata.yml, recipes/libsvtav1/all/conanfile.py, recipes/libsvtav1/config.yml
**libsvtav1/1.X.X**
* Update the library to the latests releases
* Fix a nitpick from a previous PR
=> libsvtav1: Added latest releases

recipes/avahi/all/conanfile.py
Avahi uses pkg-config to install, so it is required when building. Unfortunately, Avahi doesn't accept pkgconf in place of pkg-config. Overriding Avahi's check solves this problem.
Specify library name and version:  **avahi/***
---
=> avahi: Add pkgconf as a tool_requires

docs/error_knowledge_base.md
Related to https://github.com/conan-io/hooks/issues/376 and https://github.com/conan-io/hooks/pull/476
---
=> [docs] Add hooks description for KB-H076 and KB-H077 

recipes/cppcheck/all/conanfile.py
otherwise cppcheck does not find them
fixes conan-io/conan-center-index#15421
Specify library name and version:  **cppcheck/***
---
=> cppcheck: put all resources back in bin folder

recipes/msys2/all/conanfile.py
addresses review of https://github.com/conan-io/conan-center-index/pull/14686
---
=> msys2: cleanup & decrease min conan version

recipes/kplot/all/CMakeLists.txt, recipes/kplot/all/conandata.yml, recipes/kplot/all/conanfile.py, recipes/kplot/all/test_package/CMakeLists.txt, recipes/kplot/all/test_package/conanfile.py, recipes/kplot/all/test_package/test_package.c, recipes/kplot/all/test_v1_package/CMakeLists.txt, recipes/kplot/all/test_v1_package/conanfile.py, recipes/kplot/config.yml
Specify library name and version:  **kplot/0.1.15**
---
=> kplot: add recipe

recipes/autoconf/all/conanfile.py
Specify library name and version:  **autoconf/all**
Add package_type attribute needed in Conan 2 for runtime to correctly propagate transitively (e.g. when automake is a tool_requirement, autoconf comes transitively).
=> autoconf: add package_type attribute

recipes/logr/all/conandata.yml, recipes/logr/all/conanfile.py, recipes/logr/all/test_package/conanfile.py, recipes/logr/all/test_v1_package/CMakeLists.txt, recipes/logr/all/test_v1_package/conanfile.py, recipes/logr/config.yml
Specify library name and version:  **logr/0.6.0**
---
=> Update logr to v0.6.0

recipes/h5pp/all/conandata.yml, recipes/h5pp/all/conanfile.py, recipes/h5pp/config.yml
Update to newest version [h5pp/1.11.0](https://github.com/DavidAce/h5pp/releases/tag/v1.11.0)
---
=> Update to h5pp/1.11.0

recipes/libvpx/all/conandata.yml, recipes/libvpx/all/conanfile.py, recipes/libvpx/all/test_package/CMakeLists.txt, recipes/libvpx/all/test_package/conanfile.py, recipes/libvpx/all/test_v1_package/CMakeLists.txt, recipes/libvpx/all/test_v1_package/conanfile.py
Started work, got this weird message and I'm wondering if conan is injecting --bindir 
Any advice please?
```
libvpx/1.11.0: Calling:
> "/build/conandata/conan-data/libvpx/1.11.0/_/_/build/a7d7b9773babc7a104bc397939b61bb2babf96bc/src/configure" '--disable-shared' '--enable-static' '--prefix=/' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--disable-examples' '--disable-unit-tests' '--disable-tools' '--disable-docs' '--enable-vp9-highbitdepth' '--as=yasm' '--target=x86_64-linux-gcc' '--disable-avx' '--disable-avx2' '--disable-avx512' 
disabling shared
Unknown option "--bindir=${prefix}/bin".
```
=> libvpx: support for conan v2

recipes/gperf/all/conandata.yml, recipes/gperf/all/conanfile.py, recipes/gperf/all/test_package/conanfile.py, recipes/gperf/all/test_v1_package/conanfile.py
=> gperf: conan v2 support

recipes/rotor/all/conandata.yml, recipes/rotor/all/conanfile.py, recipes/rotor/config.yml
=> [rotor/0.25] add rotor, v0.25 relax boost requirements

recipes/plf_queue/all/conandata.yml, recipes/plf_queue/all/conanfile.py, recipes/plf_queue/all/test_v1_package/CMakeLists.txt, recipes/plf_queue/config.yml
Specify library name and version:  **plf_queue/1.22**
---
=> plf_queue: add version 1.22

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.35.11**
---
=> etl: add version 20.35.11

recipes/flex/all/conanfile.py, recipes/flex/all/test_package/conanfile.py
Specify library name and version:  **flex/2.6.4**
---
=> flex: Avoid CMakeDeps messing with Conan targets

recipes/libavrocpp/all/conanfile.py, recipes/libavrocpp/all/test_package/CMakeLists.txt, recipes/libavrocpp/all/test_package/conanfile.py
There is no config file upstream, so the rational for defining custom target names was wrong. Upstream logical target names don't matter, only matters imported target names in config file if it's created.
closes https://github.com/conan-io/conan-center-index/issues/15495
---
=> libavrocpp: install either static or shared + fix discovery of Snappy + do not sugget unofficial imported target names

recipes/symengine/all/CMakeLists.txt, recipes/symengine/all/conanfile.py, recipes/symengine/all/test_package/CMakeLists.txt, recipes/symengine/all/test_package/conanfile.py, recipes/symengine/all/test_v1_package/CMakeLists.txt, recipes/symengine/all/test_v1_package/conanfile.py, recipes/symengine/all/test_v1_package/test_package.cpp
Specify library name and version:  **symengine/0.9.0**
---
=> [symengine] conan v2 support

recipes/wildmidi/all/conandata.yml, recipes/wildmidi/all/conanfile.py, recipes/wildmidi/all/test_package/CMakeLists.txt, recipes/wildmidi/all/test_package/conanfile.py, recipes/wildmidi/all/test_package/test_package.c, recipes/wildmidi/all/test_v1_package/CMakeLists.txt, recipes/wildmidi/all/test_v1_package/conanfile.py, recipes/wildmidi/config.yml
Specify library name and version:  **wildmidi/0.4.5**
WildMIDI is a simple software midi player which has a core softsynth library that can be used with other applications.
Unlike other MIDI libraries here, it supports Redbook's extended MIDI files (XMI) that are used by many old games.
There are few issues that I'd like to resolve, I don't know where else I can ask for help.
- On Windows, CMAKE_BUILD_TYPE is not set automatically from build_type, so I had to set it explicitly. Why is this happening?
- CMake's find_library can't find "libWildMidi" without ".a"/."so" extension on Linux, so I had to add it in conanfile.py. Why? Why is it working for other recipes?
- Sometimes I get this error
`[HOOK - conan-center.py] post_package_info(): ERROR: [LIBRARY DOES NOT EXIST (KB-H054)] Component …
=> wildmidi: add new recipe, version 0.4.5

recipes/mfast/all/CMakeLists.txt, recipes/mfast/all/conandata.yml, recipes/mfast/all/conanfile.py, recipes/mfast/all/test_package/CMakeLists.txt, recipes/mfast/all/test_package/conanfile.py, recipes/mfast/all/test_v1_package/CMakeLists.txt, recipes/mfast/all/test_v1_package/conanfile.py
=> mfast: conan v2 support & fix CMakeDeps targets

recipes/highway/all/conandata.yml, recipes/highway/all/conanfile.py, recipes/highway/config.yml
Specify library name and version:  **highway/1.0.3**
---
=> highway: add version 1.0.3

recipes/libcurl/all/conanfile.py
This option has been added in libcurl 7.76.0  (https://github.com/curl/curl/commit/3eebbfe8f34d37c4d68d08277a44ec7aa6bd0889), which is also the oldest version maintained in CCI. It's not properly controlled by libcurl recipe, leading to non-reproducible builds.
closes https://github.com/conan-io/conan-center-index/issues/15370
---
=> libcurl: add `with_libgsasl` option (disabled by default)

recipes/hidapi/all/conandata.yml, recipes/hidapi/all/conanfile.py, recipes/hidapi/config.yml
Specify library name and version:  **hidapi/0.13.1**
---
=> hidapi: add version 0.13.1

recipes/proposal/all/conandata.yml, recipes/proposal/config.yml
Specify library name and version:  **proposal/7.5.0**
We have released version 7.5.0 of PROPOSAL 🥳 
This also means that there is a new version for conan.
---
=> proposal: bump to 7.5.0

docs/adding_packages/conanfile_attributes.md, docs/faqs.md
Docs!
- No modular boost (unless is completely not boost, take asio for example of "independent")
- Generally options must impact pgk_id unless supported by upstream
closes #14625
---
=> Revise modular boost policy and clarify options which do no impact `package_id`

recipes/miniscript/all/CMakeLists.txt, recipes/miniscript/all/conandata.yml, recipes/miniscript/all/conanfile.py, recipes/miniscript/all/test_package/CMakeLists.txt, recipes/miniscript/all/test_package/conanfile.py, recipes/miniscript/all/test_package/test_package.cpp, recipes/miniscript/all/test_v1_package/CMakeLists.txt, recipes/miniscript/all/test_v1_package/conanfile.py, recipes/miniscript/config.yml
Specify library name and version:  **miniscript/1.5.1**
---
=> miniscript: add recipe

recipes/uni-algo/all/conandata.yml, recipes/uni-algo/all/conanfile.py, recipes/uni-algo/all/test_package/CMakeLists.txt, recipes/uni-algo/all/test_package/conanfile.py, recipes/uni-algo/all/test_package/test_package.cpp, recipes/uni-algo/all/test_v1_package/CMakeLists.txt, recipes/uni-algo/all/test_v1_package/conanfile.py, recipes/uni-algo/config.yml
Specify library name and version:  **uni-algo/***
uni-algo is header-only unicode library.
---
=> uni-algo: add recipe

recipes/confu_json/all/conandata.yml, recipes/confu_json/all/conanfile.py, recipes/confu_json/config.yml
Specify library name and version:  **confu_json/1.0.0**
removed c++20 dependency. This lib should now compile with c++17
---
- [ x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
=> confu_json: support for c++17

recipes/coin-osi/all/conandata.yml, recipes/coin-osi/all/conanfile.py, recipes/coin-osi/config.yml
Specify library name and version:  **coin-iso/0.108.7**
Dependency of coin-cbc/2.10.8
Linked PR : #15261
---
=> coin-osi : added 0.108.7

recipes/xtensor/all/conandata.yml, recipes/xtensor/all/conanfile.py, recipes/xtensor/config.yml
Specify library name and version:  **xtl/***
- add version 0.24.3
- update xtl
- add patch_description
---
=> xtensor: add version 0.24.3, update xtl

recipes/fast_float/all/conandata.yml, recipes/fast_float/all/test_v1_package/CMakeLists.txt, recipes/fast_float/config.yml
Specify library name and version:  **fast_float/***
- add version 3.9.0
---
=> fast_float: add version 3.9.0, remove older versions

recipes/zpp_bits/all/conandata.yml, recipes/zpp_bits/all/conanfile.py, recipes/zpp_bits/config.yml
- add version 4.4.13
- remove version 4.1.2 (it is wrong version which I added)
- modify validate logic
---
=> zpp_bits: add 4.4.13, remove wrong version

recipes/hdrhistogram-c/all/conandata.yml, recipes/hdrhistogram-c/all/conanfile.py, recipes/hdrhistogram-c/all/test_v1_package/CMakeLists.txt, recipes/hdrhistogram-c/config.yml
Specify library name and version:  **hdrhistogram-c/***
- add version 0.11.6
---
=> hdrhistogram-c: add version 0.11.6

recipes/googleapis/all/CMakeLists.txt, recipes/googleapis/all/conanfile.py, recipes/googleapis/all/helpers.py, recipes/googleapis/all/test_package/conanfile.py
Specify library name and version:  **googleapis/all**
This PR updates the `googleapis` recipe to use functionality that is compatible with both Conan 1.x and Conan 2.0
* Use `CMakeDeps` and `CMakeToolchain` instead of legacy integrations
* Add transitive headers trait to the protobuf dependency - this is for Conan 2.0. `.pb.h` headers inside this package have transitive public header dependencies on Protobuf
* Minor changes to use new functions from `conan.tools`
* Add `resdirs` cpp_info attribute - it needs to be explicitly set in Conan 2.0 as there is no default.
* Add `package_type` attribute
* Modify the logic in the CMake code generation such that the target names _do not_ start with `google_` or end with `_proto` - this is in an attempt to get cmake to generate shorter vcxproj …
=> googleapis: use modern CMake integrations

recipes/libjpeg/all/conanfile.py
- use `NMakeToolchain` (conan 1.55.0)
- for clang-cl, get compilers paths from `tools.build:compiler_executables` then `VirtualBuildEnv` then fallback to default values.
- remove autotools install workaround for MinGW (fixed in conan 1.54.0)
---
=> libjpeg: modernize more

recipes/soxr/all/conanfile.py
Specify library name and version:  **soxr/0.1.3**
This should fix #15502.
---
=> Fix soxr for iOS ARMv8 architecture

recipes/sentry-breakpad/all/CMakeLists.txt, recipes/sentry-breakpad/all/conanfile.py, recipes/sentry-breakpad/all/test_package/CMakeLists.txt, recipes/sentry-breakpad/all/test_package/conanfile.py, recipes/sentry-breakpad/all/test_v1_package/CMakeLists.txt, recipes/sentry-breakpad/all/test_v1_package/conanfile.py
Fix of `pkg_config_name` is required for https://github.com/conan-io/conan-center-index/pull/15512
---
=> sentry-breakpad: conan v2 support & fix PkgConfigDeps

recipes/libmp3lame/all/conanfile.py, recipes/libmp3lame/all/test_package/conanfile.py
- use `NMakeToolchain` (conan 1.55.0)
- for clang-cl, get compilers paths from `tools.build:compiler_executables` then `VirtualBuildEnv` then fallback to default values.
- remove autotools install workaround for MinGW (fixed in conan 1.54.0)
---
=> libmp3lame: modernize more

recipes/tomlplusplus/all/conandata.yml, recipes/tomlplusplus/all/conanfile.py, recipes/tomlplusplus/all/test_package/CMakeLists.txt, recipes/tomlplusplus/all/test_v1_package/CMakeLists.txt, recipes/tomlplusplus/config.yml
Specify library name and version:  **tomlplusplus/3.3.0**
- add version 3.3.0
- fix msvc version check
---
=> tomlplusplus: add version 3.3.0, fix msvc version check

.c3i/config_v2.yml
All initial configurations should have the default (`0`) epoch
=> [config v2] Add default epoch to all profile configurations

recipes/cyclonedds/all/conandata.yml, recipes/cyclonedds/all/conanfile.py, recipes/cyclonedds/all/test_package/CMakeLists.txt, recipes/cyclonedds/all/test_v1_package/CMakeLists.txt, recipes/cyclonedds/all/test_v1_package/conanfile.py
for https://github.com/conan-io/hooks/pull/480
CMake config & pkgconfig file names are based on PROJECT_NAME which is CycloneDDS: https://github.com/eclipse-cyclonedds/cyclonedds/blob/0.10.2/CMakeLists.txt#L13
CMake config file name: https://github.com/eclipse-cyclonedds/cyclonedds/blob/0.10.2/CMakeLists.txt#L299-L303
pkgconfig file name: https://github.com/eclipse-cyclonedds/cyclonedds/blob/0.10.2/CMakeLists.txt#L314-L317
---
=> cyclonedds: lowercase systemlibs + modernize more + fix CMake config & pkgconfig file names

recipes/opencv/2.x/conanfile.py
Similar to https://github.com/conan-io/conan-center-index/pull/15193 but much simpler since there are far less modules in OpenCV 2.x
---
=> opencv 2.x: refactor to allow fine-grained selection of each module

recipes/qcbor/all/conandata.yml, recipes/qcbor/all/conanfile.py, recipes/qcbor/all/patches/1.2-0001-fix-cmake.patch, recipes/qcbor/all/test_v1_package/CMakeLists.txt, recipes/qcbor/config.yml
Specify library name and version:  **qcbor/***
- add version 1.2
- use rm_safe
- use add_subdirectory
- add disable_float option for 1.2
---
=> qcbor: add version 1.2

recipes/cairo/all/conandata.yml, recipes/cairo/config.yml, recipes/cairo/meson/conandata.yml, recipes/cairo/meson/conanfile.py
Specify library name and version:  **cairo/1.17.6**
* Add latest version of cairo.
* Flip `options.tee` to False as this is the default in the meson build. Otherwise the build fails and would require a patch.
---
=> [cairo] add 1.17.6

.github/workflows/linter-conan-v2.yml
it has been broken by https://github.com/conan-io/conan-center-index/pull/15005
the error was
```
line 10: syntax error near unexpected token `)'
```
broken runs:
- https://github.com/conan-io/conan-center-index/actions/runs/3803517584/jobs/6469976580#step:9:26
- https://github.com/conan-io/conan-center-index/actions/runs/4023629343/jobs/6914721612#step:9:26
- https://github.com/conan-io/conan-center-index/actions/runs/4023635893/jobs/6914735878#step:9:26
Instead of taking the 250 first recipes in alphabetical order, use `shuf` to randomize the selection
Also, fix the grouping of error messages, and order by decreasing occurance
---
=> linter workflow: fix linter change test on test_package

recipes/poco/all/conanfile.py
Specify library name and version:  **poco/all**
Add the `transitive_headers=True` trait on the OpenSSL dependency to reflect that poco headers transitively include OpenSSL headers
=> poco: add transitive_headers trait on OpenSSL dependency

recipes/c-client/all/conandata.yml, recipes/c-client/all/conanfile.py, recipes/c-client/all/test_package/CMakeLists.txt, recipes/c-client/all/test_package/conanfile.py, recipes/c-client/all/test_v1_package/CMakeLists.txt, recipes/c-client/all/test_v1_package/conanfile.py
also fix system libs casing on Windows for https://github.com/conan-io/hooks/pull/480
---
=> c-client: conan v2 support

recipes/ixwebsocket/all/CMakeLists.txt, recipes/ixwebsocket/all/conandata.yml, recipes/ixwebsocket/all/conanfile.py, recipes/ixwebsocket/all/test_package/CMakeLists.txt, recipes/ixwebsocket/all/test_package/conanfile.py, recipes/ixwebsocket/all/test_package/test_package.cpp, recipes/ixwebsocket/all/test_v1_package/CMakeLists.txt, recipes/ixwebsocket/all/test_v1_package/conanfile.py, recipes/ixwebsocket/config.yml
also fix system libs casing on Windows for https://github.com/conan-io/hooks/pull/480
---
=> ixwebsocket: conan v2 support

recipes/tcl/all/conanfile.py
Update tcl dependencies for https://github.com/conan-io/conan-center-index/pull/15383
---
=> update tcl/* dependencies

recipes/aeron/all/CMakeLists.txt, recipes/aeron/all/conandata.yml, recipes/aeron/all/conanfile.py, recipes/aeron/all/test_package/CMakeLists.txt, recipes/aeron/all/test_package/conanfile.py, recipes/aeron/all/test_v1_package/CMakeLists.txt, recipes/aeron/all/test_v1_package/conanfile.py, recipes/aeron/config.yml
also declare lowercase system libs for https://github.com/conan-io/hooks/pull/480
---
=> aeron: conan v2 support

recipes/grpc-proto/all/CMakeLists.txt, recipes/grpc-proto/all/conanfile.py, recipes/grpc-proto/all/test_package/conanfile.py, recipes/grpc-proto/all/test_v1_package/CMakeLists.txt, recipes/grpc-proto/all/test_v1_package/conanfile.py
Specify library name and version:  **grpc-proto/all**
This PR makes the recipe use syntax that is compatible with both Conan 1.x and Conan 2.0.
* Use newer `CMakeDeps` and `CMakeToolchain` instead of legacy integrations
* Add `transitive_headers=True` to dependency on protobuf (needed for 2.0 - public headers in this package transitively include protobuf headers)
* Explicitly define `cpp_info.resdirs` - needed for Conan 2.0 since it no longer has a default value
* Minor fixes to use tools from `conan.tools` instead of legacy tools.
Close https://github.com/conan-io/conan-center-index/issues/15599 - caused by `googleapis` introducing components and moving the `resdirs` definition to the component.
=> grpc-proto: use modern CMake integrations

recipes/plf_list/all/conandata.yml, recipes/plf_list/all/conanfile.py, recipes/plf_list/all/patches/2.50-0001-disable-cxx20-from-apple-clang14.patch, recipes/plf_list/all/patches/2.57-0001-disable-cxx20-from-apple-clang14.patch, recipes/plf_list/all/test_v1_package/CMakeLists.txt, recipes/plf_list/config.yml
Specify library name and version:  **plf_list/***
- add version 2.57
- plf_list >= 2.50 doesn't support apple-clang 14 because apple-clang 14 defaults C++20
---
=> plf_list: add version 2.57, support apple-clang 14

recipes/modern-cpp-kafka/all/conandata.yml, recipes/modern-cpp-kafka/config.yml
Specify library name and version:  **modern-cpp-kafka/2023.01.05**
---
=> modern-cpp-kafka: add version 2023.01.05

recipes/minizip/all/conanfile.py
Specify library name and version:  **minizip/1.2.13**
function names ending with 64 are unavailable before Android 24. Pending upstream PR: https://github.com/madler/zlib/pull/436
---
=> minizip: fix building for Android API level < 24

recipes/libpng/all/conandata.yml, recipes/libpng/all/conanfile.py
It's not necessary with CMakeToolchain, since a default `CMAKE_SYSTEM_PROCESSOR` value is always injected by CMakeToolchain in case of cross-build (either deduced from host profile or from `tools.cmake.cmaketoolchain:system_processor` conf).
Moreover `CMAKE_SYSTEM_PROCESSOR` coming from user toolchains (or Android NDK toolchain, first class citizen in CMakeToolchain) must not be overridden.
closes https://github.com/conan-io/conan-center-index/issues/8003
---
=> libpng: download official tarballs + remove manual injection of CMAKE_SYSTEM_PROCESSOR when cross-building

.github/actions/alert-community/action.yml, .github/workflows/alert-community.yml
use pull_request_target event as documented in https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target `This event allows your workflow to do things like label or comment on pull requests from forks`
see also https://github.com/conan-io/conan-center-index/pull/15333#issuecomment-1408336044
---
=> [service] fix community alerts

recipes/android-ndk/all/conanfile.py
Specify library name and version:  **android-ndk/r25b**
The android-ndk recipe includes a list of versions where a special unzip variant with symlink suppport is required. This list should have included r25b, but it was forgotten when r25b was added. This leads to r25b being unusable since the compilers are text files instead of symlinks.
All NDKs since r23 require unzipping with symlink support, and this is not likely to change, nor is it an issue in the NDK itself but rather in Python: https://bugs.python.org/issue37921
Hence this PR inverts the check to enable unzipping with symlinks for all versions except those in conandata.yml before r23.
This fixes r25b, and removes the need to add future NDK versions to that one line that enables the fix.
---
Example with cross-compiling boost, …
=> android-ndk: fix symlinks for all versions since r23

recipes/wasmtime-cpp/all/conandata.yml, recipes/wasmtime-cpp/all/test_package/CMakeLists.txt, recipes/wasmtime-cpp/all/test_v1_package/CMakeLists.txt, recipes/wasmtime-cpp/all/test_v1_package/conanfile.py, recipes/wasmtime-cpp/config.yml
Specify library name and version:  **wasmtime-cpp/***
- add version 5.0.0
---
=> wasmtime-cpp: add version 5.0.0

recipes/sqlite_orm/all/conandata.yml, recipes/sqlite_orm/all/test_v1_package/CMakeLists.txt, recipes/sqlite_orm/config.yml
Specify library name and version:  **sqlite_orm/1.8.1**
- add version 1.8.1
- add patch description
---
=> sqlite_orm: add version 1.8.1

recipes/zstd/all/conandata.yml
Since 1.3.6, zstd provides official (and stable) tarballs of each release, and it's always better to download official tarball instead of tarballs generated on the fly by github.
---
=> zstd: get source code from official release tarballs

recipes/mcap/all/conandata.yml, recipes/mcap/all/conanfile.py, recipes/mcap/all/test_package/CMakeLists.txt, recipes/mcap/all/test_v1_package/CMakeLists.txt, recipes/mcap/all/test_v1_package/conanfile.py, recipes/mcap/config.yml
Specify library name and version:  **mcap/***
- add version 0.9.0
- support conan v2 more
- sort by version in config.yml, conandata.yml
---
=> mcap: add version 0.9.0, support conan v2 more

recipes/zxing-cpp/all/conandata.yml, recipes/zxing-cpp/all/conanfile.py, recipes/zxing-cpp/all/test_package/CMakeLists.txt, recipes/zxing-cpp/all/test_package/test_package_2.0.cpp
Specify library name and version:  **zxing-cpp/2.0**
@prince-chrismc requested this PR
I'm the maintainer of the zxing-cpp project. I'm not a conan users and have no infrastructure to test those changes.
---
=> zxing-cpp: fix two issues with the recent inclusion of 2.0

recipes/trantor/all/conandata.yml, recipes/trantor/all/conanfile.py, recipes/trantor/all/test_package/CMakeLists.txt, recipes/trantor/all/test_v1_package/CMakeLists.txt, recipes/trantor/config.yml
=> trantor: add version 1.5.10

recipes/boost/all/conanfile.py
Specify library name and version:  **boost/1.81.0**
The check `self._settings_build == "Windows"` will always return `False`, since it is the settings object.
Correct check is `self._settings_build.os == "Windows"`.
---
=> fix: use correct OS check for settings_build when calling b2 or bcp exe

recipes/libvpx/all/conanfile.py
A simple patch to add support for MSVC17
A quick and simple follow-up to #13799
=> libvpx: add support for msvc17 193

recipes/c4core/all/conanfile.py
- update fast_float
- use rm_safe
---
=> c4core: update fast_float

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  imgui/cci.20230105+1.89.2.docking
There has been a new release.
---
- [ x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
=> imgui: add version cci.20230105+1.89.2.docking

recipes/opentelemetry-cpp/all/conanfile.py
**opentelemetry-cpp/1.0.1**+
fixes #15024
Looks like the feature flag has existed since the 1.0.0 release of this library: https://github.com/open-telemetry/opentelemetry-cpp/pull/807
This means that adding the feature flag for all currently supported versions in `conandata.yml` shouldn't be an issue
---
=> opentelemetry-cpp: option 'with_logs_preview' to enable experimental Logs

recipes/glibmm/all/conandata.yml, recipes/glibmm/all/conanfile.py, recipes/glibmm/all/patches/enable_static_libs_2_75_0.patch, recipes/glibmm/all/patches/fix_initialization_order_fiasco_2_75_0.patch, recipes/glibmm/all/test_package/CMakeLists.txt, recipes/glibmm/all/test_package/conanfile.py, recipes/glibmm/all/test_v1_package/CMakeLists.txt, recipes/glibmm/all/test_v1_package/conanfile.py, recipes/glibmm/config.yml
Specify library name and version:  **glibmm**
* Update glibmm for v2 toolchain
* Add version 2.74.0
---
=> Glibmm v2 toolchain

recipes/re2/all/conandata.yml, recipes/re2/config.yml
Specify library name and version:  **re2/***
- add version 20230201
- remove older versions (Oct/2020 before)
---
=> re2: add version 20230201, remove older versions

recipes/perfetto/all/conandata.yml, recipes/perfetto/config.yml
Specify library name and version:  **perfetto/v32.1**
Closes #15657 
```
v32.1 - 2023-02-01:
* Fix build on windows.
v32.0 - 2023-02-01:
* Added an explicit TraceUuid packet. The tracing service now always
generates a UUID, even if TraceConfig.trace_uuid_msb/lsb is empty.
*
UI:
*
SDK:
* Add perfetto::Tracing::ActivateTriggers() function.
* Made it possible to declare track event categories in a C++ namespace
with PERFETTO_DEFINE_CATEGORIES_IN_NAMESPACE, allowing multiple category
sets to be used in one same translation unit. Correspondingly, the
PERFETTO_COMPONENT_EXPORT and PERFETTO_TRACK_EVENT_NAMESPACE macros have
been deprecated in favor of this new functionality.
* Deprecated the PERFETTO_COMPONENT_EXPORT macro in favor of …
```
=> (#15657) Perfetto: Bump to v32.1

recipes/xorg/all/conanfile.py
On Suse Linux distributions libXScrnSaver is called libXss. 
```
wdobbe@linux-wdobbe:~> zypper se libXss
Loading repository data...
Reading installed packages...
S  | Name               | Summary                                                      | Type
---+--------------------+--------------------------------------------------------------+--------
i+ | libXss-devel       | Development files for the X11 Screen Saver extension library | package
| libXss-devel-32bit | Development files for the X11 Screen Saver extension library | package
i  | libXss1            | X11 Screen Saver extension client library                    | package
| libXss1-32bit      | X11 Screen Saver extension client library                    | package
```
---
=> xorg: on Suse systems libXScrnSaver-devel is called libXss-devel.

recipes/android-ndk/all/conandata.yml, recipes/android-ndk/config.yml
Specify library name and version:  **android-ndk/r25c**
This bumps android-ndk to r25c released two days ago.
Changelog: https://github.com/android/ndk/wiki/Changelog-r25
---
=> android-ndk: add r25c

recipes/arrow/all/conandata.yml, recipes/arrow/config.yml
Specify library name and version:  **arrow/10.0.1**
---
=> arrow: add version 10.0.1

recipes/strong_type/all/conandata.yml, recipes/strong_type/all/conanfile.py, recipes/strong_type/config.yml
Specify library name and version:  **strong_type/v9**
---
=> Update strong_type, v10

recipes/arrow/all/conanfile.py
fixes #15413
Specify library name and version:  **arrow/10.0.0**
---
=> arrow/10.0.0: link re2 to `libparquet` and `libarrow`

recipes/indicators/all/conandata.yml, recipes/indicators/all/conanfile.py
Specify library name and version:  **indicators/***
---
=> indicators: modernize

recipes/nuraft/all/conandata.yml, recipes/nuraft/all/conanfile.py, recipes/nuraft/all/patches/1001-cmake_patches.patch, recipes/nuraft/config.yml
Specify library name and version:  **nuraft/2.1.0**
Regular updates.
---
=> Update NuRAFT to v2.1.0

recipes/glm/all/conandata.yml, recipes/glm/config.yml
glm hasn't started making new official releases yet, we just take from master for now.
Commit was made during Jan 13, so I've made the datestamp cci.20230113.
There are no commits on Jan 14 (or any other day following).
=> glm: Add new release (pick latest version from master)

recipes/icu/all/conanfile.py
- use new `stdcpp_library()` instead of legacy one (since conan 1.54.0)
- write custom `_sha256sum()` function to avoid relying on legacy conans.tools.sha256sum() conan function
- remove workaround for https://github.com/conan-io/conan/issues/12642 (fixed in conan 1.57.0)
- remove workaround for https://github.com/conan-io/conan/issues/12153 (fixed in conan 1.54.0)
There is still a legacy function: `get_gnu_triplet()`. See https://github.com/conan-io/conan/issues/13028
---
=> icu: modernize more for conan v2

.github/workflows/alert-community.yml
Adding grafikrobot, aka René, to notify for b2 and lyra recipes.
=> Add René/grafikrobot to some recipes.

recipes/b2/portable/conanfile.py
Specify library name and version:  **b2/all**
Recipe broken for b2 in Windows
---
=> fix b2 to work for conan2 in windows

recipes/googleapis/all/conandata.yml, recipes/googleapis/config.yml
Specify library name and version:  **googleapis/cci.20221108**
I am planning to send a PR updating  `google-cloud-cpp` to (1) use `googleapis`, and (2) get it upgraded to `v2.5.0`. Before I do so, I need to update `googleapis`.
---
=> [googleapis]: add version matching google-cloud-cpp-2.5.0

recipes/sentry-native/all/conandata.yml, recipes/sentry-native/config.yml
=> [sentry-native/0.5.4] Bump version

recipes/boost/all/conanfile.py
Specify library name and version:  **boost/***
Fixes https://github.com/conan-io/conan-center-index/issues/15448
package_info method fails because _b2_architecture variable is empty
---
=> Fix boost recipe from crashing when host architecture is "wasm"

.github/workflows/alert-community.yml
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
---
=> config: limit alerts to on CCI

recipes/apr/all/conandata.yml, recipes/apr/all/conanfile.py
https://downloads.apache.org/apr/apr-1.7.0.tar.gz is a dead link now.
---
=> apr: fix url of source code tarball + modernize more

.github/workflows/alert-community.yml
=> Add watched recipes for jwillikers

.github/workflows/alert-community.yml
single quotes must be used, cf https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository and https://docs.github.com/en/actions/learn-github-actions/expressions#literals
all the workflows fail since [last modification](https://github.com/conan-io/conan-center-index/commit/566d7433c8403b336602f9cff86ce4d9f1ac23a1): https://github.com/conan-io/conan-center-index/actions/workflows/alert-community.yml:
```
The workflow is not valid. .github/workflows/alert-community.yml (Line: 9, Col: 9): Unexpected symbol: '"conan-io/conan-center-index"'. Located at position 22 within expression: github.repository == "conan-io/conan-center-index"
```
---
=> [service] fix alert community workflow

recipes/openssl/1.x.x/conanfile.py, recipes/openssl/1.x.x/test_package/CMakeLists.txt, recipes/openssl/1.x.x/test_package/conanfile.py, recipes/openssl/1.x.x/test_v1_package/CMakeLists.txt, recipes/openssl/1.x.x/test_v1_package/conanfile.py
- The `self.in_local_cache` is not available on Conan v2 and should be used only for "Conan Development Flow" which does not fit regular CCI recipes
- Test package needs a dependency option value which should be cached for Conan v1
---
=> [openssl] Update test_package for Conan v2

recipes/cmake/3.x.x/conanfile.py
We detected [some failures when building CMake](https://ci.conan.io/blue/organizations/jenkins/Examples2.0/detail/main/383/pipeline/38) in Windows. CMake tries to find the MFC's when there's a file association with _.vcproj_ files and will fail using the toolchain passed by Conan. Setting `BUILD_TESTING=OFF` seems to pass that test.
=> Add BUILD_TESTING OFF to CMake

recipes/icu/all/conandata.yml, recipes/icu/all/conanfile.py, recipes/icu/config.yml
Specify library name and version:  **icu/all**
* Use `str(self.ref)` to support cross-building in Conan 2
* Compose build and host triplets directly when cross-building for iOS/watchOS/tvOS, while fixing an issue cross-building from an Apple Silicon mac (the build/host triplets would be the same and the scripts were not correctly detecting cross compilation). 
* Remove logic for cross-building on Windows as the issue mentioned in the comments is now resolved in 1.57. This, however, still requires a small nudge to the build scripts, which is specific to the `icu` build system (telling the build scripts that the `mh-msys-msvc` config fragment is needed). 
* Clean-up logic to check that the version of Visual Studio/msvc is the minimum required to pass the `-FS` flag - this is now possible …
=> icu: small fixes to support Conan 2.0

recipes/log4cplus/all/CMakeLists.txt, recipes/log4cplus/all/conandata.yml, recipes/log4cplus/all/conanfile.py, recipes/log4cplus/all/patches/2.0.4-0001-fix-cmake.patch, recipes/log4cplus/all/patches/2.0.6-0001-fix-cmake.patch, recipes/log4cplus/all/test_package/CMakeLists.txt, recipes/log4cplus/all/test_package/conanfile.py, recipes/log4cplus/all/test_v1_package/CMakeLists.txt, recipes/log4cplus/all/test_v1_package/conanfile.py, recipes/log4cplus/config.yml
Specify library name and version:  **log4cplus/***
- add version 2.0.8
- update libiconv
---
=> log4cplus: add version 2.0.8, support conan v2

recipes/libbacktrace/all/conanfile.py
Specify library name and version:  **libbacktrace/all**
This fixes issue building this with Conan 2.0 on Windows:
* `self.deps_user_info` is removed from Conan 2 (it is now `self.dependencies`) - however for propagating custom variables, this is now done with a conf that can be retrieved via `self.conf` - the automake recipe was updated with this a few weeks ago.
=> libbacktrace: retrieve automake wrapper scripts using newer user conf

recipes/hdf5/all/conanfile.py, recipes/hdf5/all/test_package/conanfile.py
Needed to add the line:
```
self.cpp_info.set_property("cmake_build_modules", [self._module_file_rel_path])
```
Otherwise the consumer doesn't see the generated cmake file.
=> hdf5: specify the cmake_build_modules file correctly

recipes/spdlog/all/conanfile.py
Specify library name and version:  **spdlog/all**
Add `transitive_libs=True` dependency trait on `fmt` dependency, as public use of public `spdlog` headers cause downstream consumers to directly reference symbols from `fmt` and these need to be seen by the linker.
This fixes an error when `spdlog` and `fmt` are both shared libraries (`-o "*:shared=True"` in Conan 2.0), and the test package of `spdlog` fails to build correctly. This would also be experienced by any downstream consumer of this configuration.
The public `spdlog` headers cause the consumers to _directly_ reference symbols from `fmt` themselves (at least as far as the C++ and linker are concerned). Thus, this is not a case where `spdlog` uses `fmt` privately but rather it's a public dependency. In Conan 2 this implies we need …
=> spdlog: add transitive_libs trait on fmt dependency (Conan 2.0)

recipes/openssl/1.x.x/conanfile.py, recipes/openssl/1.x.x/test_package/conanfile.py, recipes/openssl/1.x.x/test_v1_package/conanfile.py
=> openssl 1.x.x: modernize a little bit more + do not skip tests if macOS armv8 shared

recipes/openal-soft/all/conandata.yml, recipes/openal-soft/all/conanfile.py, recipes/openal-soft/all/patches/1.19.1-0001-aligned-alloc.patch, recipes/openal-soft/all/patches/1.19.1-0002-gcc-10-fnocommon.patch, recipes/openal-soft/all/patches/1.19.1-0003-fix-windows-sdk.patch, recipes/openal-soft/all/patches/1.20.1-0001-fix-windows-sdk.patch, recipes/openal-soft/all/patches/1.21.0-0001-c++14-does-not-have-std-aligned_alloc.patch, recipes/openal-soft/all/patches/1.21.0-0002-fix-windows-sdk.patch, recipes/openal-soft/all/patches/1.22.2-0001-fix-al-optional-in-if-compile-error.patch, recipes/openal-soft/all/test_package/CMakeLists.txt, recipes/openal-soft/all/test_package/conanfile.py, recipes/openal-soft/all/test_package/test_package.c, recipes/openal-soft/all/test_v1_package/CMakeLists.txt, recipes/openal-soft/all/test_v1_package/conanfile.py, recipes/openal-soft/config.yml
`openal` recipe refers actually to OpenAL Soft (https://openal-soft.org), so `openal` recipe is deprecated in https://github.com/conan-io/conan-center-index/pull/15590 in favor of this new `openal-soft` recipe.
see also https://github.com/conan-io/conan-center-index/issues/9181
---
=> add openal-soft recipe (copy of deprecated openal recipe)

recipes/coin-utils/all/conandata.yml, recipes/coin-utils/all/conanfile.py, recipes/coin-utils/all/test_package/CMakeLists.txt, recipes/coin-utils/all/test_package/conanfile.py, recipes/coin-utils/all/test_v1_package/CMakeLists.txt, recipes/coin-utils/all/test_v1_package/conanfile.py, recipes/coin-utils/config.yml
=> coin-utils: conan v2 support

recipes/qt/6.x.x/conanfile.py
Strangely, I started getting a "Ninja cycle dependency error" on Windows (QT 6.4.2).
The error looks something like this (different files for me):
```
ninja: error: dependency cycle: src/CMakeFiles/ossia.dir/cmake_pch.cxx.obj -> src/CMakeFiles/ossia.dir/CXX.dd -> src/CMakeFiles/ossia.dir/ossia/context.cpp.obj.ddi -> src/CMakeFiles/ossia.dir/cmake_pch.cxx.pch -> src/CMakeFiles/ossia.dir/cmake_pch.cxx.obj
```
After a bit of googling, it appears that it is caused by a change in cmake 3.25,
and was later patched (apparently).
example: https://gitlab.kitware.com/cmake/cmake/-/issues/19220
https://gitlab.kitware.com/cmake/cmake/-/issues/24209
Forcing qt to build with cmake 3.25.1 (with [tool_requires] in the profile) worked, so I'm bumping the build_requirements to 3.25.2.
=> qt: don't use cmake 3.25.0, due to Ninja dependency cycle bug

recipes/openssl/1.x.x/conandata.yml, recipes/openssl/config.yml
https://www.openssl.org/news/openssl-1.1.1-notes.html
Fixes #15813
For 3.0.8 see #15802
=> openssl: add 1.1.1t + add GitHub mirror

recipes/spix/all/conandata.yml, recipes/spix/all/conanfile.py, recipes/spix/all/patches/0001-use-conan-libs-0.4.patch, recipes/spix/all/patches/0001-use-conan-libs-0.5.patch, recipes/spix/all/test_package/CMakeLists.txt, recipes/spix/all/test_package/conanfile.py, recipes/spix/all/test_v1_package/conanfile.py, recipes/spix/config.yml
Specify library name and version:  **spix/0.5**
Fixes #15292
Tested locally with Visual Studio 2019.
---
=> Add spix/0.5

recipes/ogg/all/conanfile.py, recipes/ogg/all/test_v1_package/conanfile.py
Specify library name and version:  **ogg/all**
While working for v2 migration, we found that ogg failed to compile in some instances. The reason was this double delete. I'll take a look around in the top 100 recipes and see if there are any more obvious problems
=> ogg: Fix double delete, add a few minor improvements

recipes/gperf/all/conanfile.py
Specify library name and version:  **gperf/all**
Fix issue where compiler `Visual Studio` does not exist in `settings.yml` in Conan 2.0, and clean-up logic with functionality available in Conan 1.57.
=> gperf: fix check for msvc version for conan 2 compatibility

recipes/libwebp/all/conanfile.py
There was a problem with PR #15256 
1.3.0 split the SharpYuv* functions into a separate library: libsharpyuv.a
the webp libraries need the sharpyuv lib to link.
The new libwebp.pc file generated during the build (and then deleted by conan) looks like:
```
Name: libwebp
Description: Library for the WebP graphics format
Version: 1.3.0
Requires: libsharpyuv
Cflags: -I${includedir}
Libs: -L${libdir} -lwebp
Libs.private: -lm  -lpthread
```
This corrects the problem.  I also added syslib m to webpdecoder, as per the original .pc file specifications.
=> libwebp: add component for libsharpyuv

recipes/boost/all/conanfile.py
* When building boost when `libbacktrace` is shared, the build may be misconfigured in a way that it doesn't build the stacktrace library when expected. 
```ERROR: boost/1.80.0: Error in package_info() method, line 1681
raise ConanException(f"These libraries were expected to be built, but were not built: {non_built}")
ConanException: These libraries were expected to be built, but were not built: {'boost_stacktrace_backtrace'}
```
This correlates with the following in the configuration checks:
```
- libbacktrace builds      : no [2]
- libbacktrace builds      : no [3]
```
On platforms where Boost is built against `libbacktrace` by default, the build scripts compile a test executable and then run it during configuration time. 
There are two …
=> boost: fix build-time checks against libbacktrace

recipes/simdutf/all/conandata.yml, recipes/simdutf/config.yml
Specify library name and version:  **simdutf/3.2.0**
---
=> simdutf: add version 3.2.0

recipes/simdjson/all/conandata.yml, recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.1.1**
---
=> simdjson: add version 3.1.1

recipes/zstd/all/conandata.yml, recipes/zstd/all/conanfile.py, recipes/zstd/config.yml
Specify library name and version:  **zstd/1.5.4**
---
=> zstd: add version 1.5.4

recipes/luau/all/conandata.yml, recipes/luau/all/conanfile.py, recipes/luau/config.yml
Specify library name and version:  **luau/0.563**
---
=> luau: add version 0.563, remove older versions

recipes/cpp-lazy/all/conandata.yml, recipes/cpp-lazy/all/conanfile.py, recipes/cpp-lazy/config.yml
Specify library name and version:  **cpp-lazy/7.0.2**
The patch for 6.0.0 is already merged to upstream.
---
=> cpp-lazy: add version 7.0.2

recipes/cpptoml/all/conandata.yml, recipes/cpptoml/all/conanfile.py, recipes/cpptoml/all/test_package/CMakeLists.txt, recipes/cpptoml/all/test_package/conanfile.py, recipes/cpptoml/all/test_v1_package/CMakeLists.txt, recipes/cpptoml/all/test_v1_package/conanfile.py
CMake imported target is not namespace: https://github.com/skystrife/cpptoml/blob/v0.1.1/CMakeLists.txt#L91-L92
---
=> cpptoml: conan v2 support and fix cmake target

recipes/libsvtav1/all/conandata.yml, recipes/libsvtav1/all/conanfile.py, recipes/libsvtav1/all/patches/llvm-clang-macos.patch
Specify library name and version:  **libsvtav1/all**
Honestly, I don't know if its the right way to handle that but I already submitted a patch upstream.
---
=> libsvtav1: fix static build on macos llvm-clang

recipes/cpuinfo/all/CMakeLists.txt, recipes/cpuinfo/all/conanfile.py, recipes/cpuinfo/all/test_v1_package/CMakeLists.txt
Manual handling of CMAKE_SYSTEM_PROCESSOR is not required anymore. CMakeToolchain injects correct values in case of cross-build.
---
=> cpuinfo: modernize more for conan v2

recipes/opentelemetry-cpp/all/conanfile.py
Specify library name and version:  **opentelemetry-cpp**
I was looking for some of these extra features that are hidden behind cmake options, and noticed that the recipe didn't expose them. So I've had a crack at exposing all the rest that are available in opentelemetry-cpp's CMakeLists.txt.
I've tried to keep the conan option defaults matching what the package was previously being built with, and for the new ones defaulting to what opentelemetry-cpp defaults them to. 
---
=> Expose more CMake options for opentelemetry-cpp

recipes/coin-osi/all/conandata.yml, recipes/coin-osi/all/conanfile.py, recipes/coin-osi/all/test_package/CMakeLists.txt, recipes/coin-osi/all/test_package/conanfile.py, recipes/coin-osi/all/test_v1_package/CMakeLists.txt, recipes/coin-osi/all/test_v1_package/conanfile.py, recipes/coin-osi/config.yml
=> coin-osi: conan v2 support

recipes/sdl/all/conanfile.py
Specify library name and version:  **sdl/all**
Fixes consuming static library on Android. Almost like #6105 but without HID stuff. OpenSLES was added only in 2.0.16 according to the tags of https://github.com/libsdl-org/SDL/commit/d4e96e1153906c458a53c38ccc11a3b64b0dc06a
The shared variant already has all the dependencies inside:
```
> .../llvm-objdump -p .../libSDL2.so | fgrep NEEDED
NEEDED       libm.so
NEEDED       libOpenSLES.so
NEEDED       libdl.so
NEEDED       liblog.so
NEEDED       libandroid.so
NEEDED       libGLESv1_CM.so
NEEDED       libGLESv2.so
NEEDED       libc.so
```
There's however a link error for `test_package`, but I think it can be ignored:
<details><summary>Click to expand log</summary>
```
> conan create . sdl/2.26.1@ --build=missing --profile:host=android-32 -o …
```
=> sdl: link to required Android system libs in static variant

recipes/libverto/all/conanfile.py, recipes/libverto/all/test_package/CMakeLists.txt, recipes/libverto/all/test_package/conanfile.py, recipes/libverto/all/test_v1_package/CMakeLists.txt, recipes/libverto/all/test_v1_package/conanfile.py
Specify library name and version:  **libverto/**
---
From #14226
=>  libverto: Update dependencies

recipes/atk/all/conanfile.py
Using glib on full package id mode is a solution to avoid multiple instances of glib. However, for CCI it's painful as it result on missing packages for any minimal change, we need to rebuild everything.
Specify library name and version:  **atk/2.38.0**
Related to #15756
/cc @SpaceIm
---
=> [atk] Do not use full-package-id mode for glib

docs/package_templates/meson_package/all/conanfile.py
- Conan 2.0 is removing MesonDeps, as it is broken, not being capable of managing transitive dependencies: https://github.com/conan-io/conan/pull/13134
- No ConanCenter uses it, only Pistache, and it is not needed: https://github.com/conan-io/conan-center-index/pull/16014
- Conan 1.X will mark MesonDeps as deprecated and not-recommended in the docs
---
=> remove MesonDeps from template

recipes/cxxopts/all/conanfile.py
Since gcc 4.9 is still in use, and it supports c++11
Specify library name and version:  **cxxopts/2.2.0**
---
- [+] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [+] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [+] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
=> cxxopts: lowered minimum required version of gcc to 4.9

recipes/grpc-proto/all/conanfile.py
Specify library name and version:  **grpc-proto/cci.20211106**
My best guess is that I need to make this change to unblock #15817.
In summary: `google-cloud-cpp/2.5.0` requires a new version of `googleapis` and (to be best of my limited knowledge) that requires updating `grpc-proto` and `grpc`.
---
=> [grpc-proto] bump required googleapis version

recipes/benchmark/all/conanfile.py
Specify library name and version:  **benchmark/all**
Bump the required version of CMake to 3.25.2 - this is not strictly necessary given that `3.25.0` recipe and binaries exist, but 3.25.0 is no longer a version of CMake that we build or maintain (useful for Conan 2.0).
=> benchmark: bump version of cmake tool requirement

.github/workflows/alert-community.yml
this silences a bunch of warnings
cf https://github.com/conan-io/conan-center-index/actions/runs/4202405009
---
=> service: set python version for alert-community action

recipes/libffi/all/conanfile.py
Specify library name and version:  **libffi/all**
* Fix issue on Windows with Conan 2.0 where "Visual Studio" is no longer a valid compiler setting. Now uses new tools.
* Cleanup: Use newer `update_configure_args` 
* Cleanup: Get path to ar wrapper from Automake using new conf propagation.
=> libffi: fix msvc logic in Conan 2.0

recipes/libxml2/all/conanfile.py
Specify library name and version:  **libxml2/all**
The public `libxml2` headers include `<iconv.h>`. Conan 2.0 does not propagate the include directories of the libiconv dependency unless specified in the traits. This causes a downstream failure on Windows as the iconv header cannot be found. On Linux and Mac it could also result in the system version being picked up instead. 
I can see **no** evidence that any other the other dependencies are publicly transitive.
=> libxml2: add transitive traits to libiconv dependency

recipes/rtmidi/all/conandata.yml, recipes/rtmidi/all/conanfile.py, recipes/rtmidi/all/patches/4.0.0-0003-relocatable-macos.patch
- don't use pkgconf, libalsa is discovered through find_package(): https://github.com/thestk/rtmidi/blob/5.0.0/CMakeLists.txt#L123
- cleanup package_info()
- final polishing to make this recipe v2 compatible:
- fix topics (must be a valid tuple in conan v2)
- fix double delete of fPIC option
- add package_type (not strictly required, but it's better)
---
=> rtmidi: do not use pkgconf + modernize more for conan v2

recipes/openssl/3.x.x/conandata.yml, recipes/openssl/3.x.x/conanfile.py, recipes/openssl/config.yml
https://www.openssl.org/news/openssl-3.0-notes.html
For 1.1.1t see #15860
___
=> openssl: add 3.0.8 + add GitHub as mirror

.c3i/reviewers.yml
After the last round of cleanup, I've been keeping a list of who's been helping advance Conan and ConanCenter. These contributors have submitted good PRs, done a bunch of good reviews, or answered a lot of question on slack really well.
As a result, they are going to be joining our excellent community reviewers. @System-Arch @StellaSmith @samuel-emrys I'd like to extend a warm welcome and a big thank you 👏
=> config: Adding new community reviewers to the list

recipes/autoconf-archive/all/conandata.yml, recipes/autoconf-archive/all/conanfile.py, recipes/autoconf-archive/all/test_package/conanfile.py, recipes/autoconf-archive/all/test_v1_package/Makefile.am, recipes/autoconf-archive/all/test_v1_package/conanfile.py, recipes/autoconf-archive/all/test_v1_package/configure.ac, recipes/autoconf-archive/all/test_v1_package/test_package.c, recipes/autoconf-archive/config.yml
Specify library name and version:  **autoconf-archive/2021.02.19**
Didn't find existing effort to port this to Conan 2.0, so did so in support of building MPFR from Git source.
---
=> Autoconf Archive Conan 2.0 compatibility

recipes/ffmpeg/all/conandata.yml, recipes/ffmpeg/all/conanfile.py, recipes/ffmpeg/config.yml
- [ffmpeg/5.1] Add version
- Don't patch libx264.c from 5.1
- Bump sdl and vulkan-loader
---
=> [ffmpeg/5.1] Version bump

recipes/cppunit/all/conanfile.py
=> cppunit: modernize more for conan v2

recipes/cmake/3.x.x/conanfile.py
Specify library name and version:  **cmake/3.x**
When building CMake by using system CMake, it will find OpenSSL library through FindOpenSSL from native cmake modules folder (e.g. /usr/cmake/cmake-3.15/Modules). As result, building Cmake package with Conan 2.0 will result on a linkage error between static openssl libraries and pthread. 
The error is caused because FindOpenssl finds openssl libraries associated to Conan, but the linkage order does not work and fails. However, Cmake fixed it on version 3.16: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4235. But due Conan Tribe decision, we should use 3.15.
On the other hand, we can use CMakeDeps to generate FindOpenSSL.cmake and consume our targets and variables, which is much safer.
Other changes: set the `CMAKE_SYSTEM_VERSION` …
=> [cmake] Use FindOpenSSL generated by CMakeDeps

recipes/xorg-proto/all/conanfile.py
Specify library name and version:  **xorg-proto/all**
* remove redundant call to the Autotools helper in the `generate()` method
=> xorg-proto: remove misplaced call to autotools helper

recipes/openh264/all/conanfile.py
Specify library name and version:  **openh264/all**
* Fix evaluation of "Visual Studio" as compiler by using newer `check_min_vs` which works with both old and new - fixes building recipe on Windows with Conan 2.0
=> openh264: fix check for visual studio on Windows (conan 2.0)

recipes/xorg-macros/all/conanfile.py
Specify library name and version:  **xorg-macros/all**
* Add missing `win_bash=True` and instantiate `VirtualBuildEnv` explicitly - fixes building from source on Windows.
=> xorg-macros: fix building from source on Windows

recipes/cmake/3.x.x/conanfile.py
Specify library name and version:  **cmake/all**
A _consumer_ can request binary packages for `cmake` with any compiler or setting - and if binaries exist for the os/architecture combo, they should be fetched, however it currently fails `validate()` - this PR fixes the issue but moving the checks to `validate_build()`, as they only affect creating the cmake binary, but not consuming it. 
The `validate()` still rightfully raises an exception if trying to request binaries on macOS with 32-bit Intel architecture, as those binaries cannot exist.
=> cmake: use validate_build to reflect invalid build configurations

recipes/libgettext/all/conanfile.py
Specify library name and version:  **libgettext/all**
in Conan 2.0, the value of the option cannot be reassigned in the `configure()` method. This PR replaces the logic such that the value of the `threads` option is conditionally derived depending on the platform _when the user does not provide an option explicitly_. This achieves the same intended goal as the auto option, and keeps the same package_ids. The key is to not give the option a default value statically, and do it in `config_options()` instead as per documentation.
=> libgettext: refactor logic for default value of threads option

recipes/xorg-cf-files/all/conandata.yml, recipes/xorg-cf-files/all/conanfile.py, recipes/xorg-cf-files/all/test_package/conanfile.py, recipes/xorg-cf-files/all/test_v1_package/Imakefile, recipes/xorg-cf-files/all/test_v1_package/conanfile.py, recipes/xorg-cf-files/all/test_v1_package/test_package.c
Specify library name and version:  **xorg-cf-files/all**
Ports xorg-cf-files to v2. Based on the work of @StellaSmith from https://github.com/conan-io/conan-center-index/pull/16128. Sorry that we have to open a new PR for this, but due to the maintenance mode only PRs from core team members will be built, I've tried to properly credit your work :)
=> xorg-cf-files: port to v2

.c3i/conan_v2_ready_references.yml, .c3i/config_v1.yml, .c3i/config_v2.yml
- Conan v2 pipeline now runs with 2.0.0 version
- AutomaticMerge will take into account the new "c3i/conan-v2" status check (the one from pipeline v2) for those recipes included in the list. This means that PRs that modify recipes included in the list should have this status check green in order to get merged.
=> [config] Use Conan 2.0.0 in v2 pipeline and add new conditional status check

recipes/libudev/all/conanfile.py, recipes/libudev/all/test_package/CMakeLists.txt, recipes/libudev/all/test_package/conanfile.py, recipes/libudev/all/test_v1_package/CMakeLists.txt, recipes/libudev/all/test_v1_package/conanfile.py
Specify library name and version:  **libudev/system**
This PR resolves #16238. It is an update for the libudev conanfiles to be compatible with conan v2
---
=> libudev: conanv2 update

docs/faqs.md
Spoiler: No.
Using `full_package_mode` will result on **missing package** errors on CCI, so it's not recommended. When really needed, I would recommend by using `shared=True` instead and maybe, not allowing static link. 
/cc @SpaceIm 
Related to https://github.com/conan-io/conan-center-index/pull/15756#discussion_r1106041531
---
=> [faqs] Can use full_package_mode over my dependencies

recipes/zstd/all/conandata.yml, recipes/zstd/all/conanfile.py, recipes/zstd/all/patches/1.5.4-decrease-min-cmake-version.patch
backport https://github.com/facebook/zstd/pull/3510
---
=> zstd: don't require CMake 3.18 or later

recipes/mikelankamp-fpm/all/test_package/test_package.cpp
Specify library name and version:  **mikelankamp-fpm/all**
The quick start code from this library uses cin to ask for user input, and it was used as the code from the test package in #15054
=> Fix mikelankamp-fpm test_package code

recipes/vorbis/all/conanfile.py
Specify library name and version:  **vorbis/1.3.7**
When building Vorbis with the option `"*/*:shared=True"`, the `ogg` package is not linked correctly. This PR makes OGG be visible when linking.
---
=> [vorbis] Export ogg as transitive library to avoid linkage error

recipes/boost/all/test_package/CMakeLists.txt, recipes/boost/all/test_package/conanfile.py
Some runtime error occurred when trying to run Boost test package on the CI:
https://c3i.jfrog.io/c3i/misc-v2/logs/prod-v2/TapaholesRepo/106-configs/macos-clang/boost/1.79.0//ff15167be75d82eb8c4445406fa2bff3f15f4cdb-test.txt
However, I can't reproduce that error, instead, it works for me, but I only have Clang Apple 14 installed. So my intention here is trying to use cmake build --target test, instead of invoking ctest directly, my guess is something related to DYLIB missing path. 
My build log:
```
% conan test test_package boost/1.79.0@ -o "*/*:shared=True" -o "boost/*:header_only=False" -s compiler.cppstd=gnu17
======== Input profiles ========
Profile host:
[settings]
arch=armv8
compiler=apple-clang …
```
=> [boost] Fix test package on macOS when *:shared=True

recipes/msdfgen/all/conandata.yml, recipes/msdfgen/all/conanfile.py, recipes/msdfgen/all/patches/1.10-0001-fix-cmake.patch, recipes/msdfgen/config.yml
Specify library name and version:  **msdfgen/1.10**
- 1.10 introduces MSDFGEN_PUBLIC macro
- 1.10 begins to require libpng instead of lodepng 
---
=> msdfgen: add version 1.10

recipes/grpc/all/conan_cmake_project_include.cmake, recipes/grpc/all/conandata.yml, recipes/grpc/all/conanfile.py, recipes/grpc/all/test_package/CMakeLists.txt, recipes/grpc/all/test_package/conanfile.py, recipes/grpc/all/test_package/macos_make_override.cmake, recipes/grpc/all/test_v1_package/CMakeLists.txt, recipes/grpc/all/test_v1_package/conanfile.py
Specify library name and version:  **grpc/all**
This PR makes the grpc compatible with both Conan 1.x and Conan 2.0
* Use `CMakeDeps` and `CMakeToolchain` instead of legacy integrations
* Use CMake `project()` code injection instead of enclosing the project in a superproject (docs [here](https://cmake.org/cmake/help/latest/command/project.html#code-injection)) - this preserves the logic that was previously in the recipe's `CMakeLists.txt` that acted as the top-level. The variable used ensures that this is processed _after_ the CMake toolchain file has been processed.
* Express the `transitive_headers` trait for both abseil and protobuf (public headers from grpc reference headers from these).
* Remove definition of `CMAKE_FIND_ROOT_PATH_MODE_PACKAGE` as that is already handled by …
=> grpc: use modern CMake integrations

recipes/sentry-native/all/conandata.yml, recipes/sentry-native/all/conanfile.py, recipes/sentry-native/config.yml
- [sentry-native/0.6.0] + remove old versions
- Remove performance option
---
=> [sentry-native/0.6.0] + remove old versions

docs/README.md, docs/bump_version.md
New contributors are not totally aware how to update a package with new version, and the documentation is not specific with it, only adding new packages.
This new section is focused on how to bump a conan recipe with a new upstream release. 
---
=> Document bumping version

docs/faqs.md
=> [doc] use `self.output.warning` in documentation instead of `self.output.warn` (invalid with conan v2 client)

recipes/libspatialindex/all/conanfile.py
=> libspatialindex: fix package_type

README.md
Let's point the Status Page on README to give some centralized point.
Unfortunately, it does not generate a nice embed label, instead only javascript is provided, which can not be used. More info: https://support.atlassian.com/statuspage/docs/create-and-configure-the-recommended-status-embed/
---
=> [readme] Add status page to the readme

recipes/grpc-proto/all/conanfile.py
Specify library name and version:  **grpc-proto/all**
Fixes double deletion of `fPIC` and option access for dependencies. Fixes ability to consume in Conan 2.0 when `shared=True`.
=> grpc proto: fix issues when building with shared=True in Conan 2.0

recipes/sigslot/all/conandata.yml, recipes/sigslot/config.yml
Specify library name and version:  **sigslot/1.2.2**
Add new version 1.2.2 with bugfixes.
---
=> sigslot: add version 1.2.2

recipes/duckdb/all/conandata.yml, recipes/duckdb/all/conanfile.py, recipes/duckdb/all/patches/0.7.0-0001-fix-cmake.patch, recipes/duckdb/config.yml
Specify library name and version:  **duckdb/***
---
=> duckdb: add version 0.7.1, fix wrong url of 0.6.1

recipes/openssl/1.x.x/test_package/CMakeLists.txt
Previously, the logic was checking if `_custom_var` was defined, which is clearly always true. Instead, we want to see if the variable referenced by `_custom_var` is defined.
=> Fix CMake variable check in OpenSSL test

recipes/opentdf-client/all/conandata.yml, recipes/opentdf-client/config.yml
Specify library name and version:  **opentdf-client/1.3.10**
Cumulative updates including exposing reader/writer API in preparation for IC-TDF format support
---
=> opentdf-client: add version 1.3.10

docs/changelog.md
- Once a package passes by Conan v2 build, it will be computed in `.c3i/conan_v2_ready_references.yml`, then it will mandatory to pass by Conan v2 for every new PR opened.
- Windows builds may fail for busy file handle, because they are re-using the same folder when building. Using unique temporary folder for each build should fix it.
---
=> [changelog] Release 2023-03-03

recipes/libsamplerate/all/conanfile.py
=> libsamplerate: fix `_cmake_new_enough()` for conan v2

recipes/daw_header_libraries/all/conanfile.py
remove self.warn which is not conan v2 compatible. Moreover the logic was wrong.
---
=> daw_header_libraries: modernize more for conan v2

recipes/ffmpeg/all/conanfile.py
Specify library name and version:  **ffmpeg/all**
fixes #15537
I haven't seen related bug report on ffmpeg tracker and not even sure that it should be considered as bug. Still not entirely sure what's going on inside ffmpeg's configure script, but with this change I was finally able to build it with NDK 25 (see the issue). Passing path to assembler when you request building without it doesn't make much sense anyway.
I tried debugging that script but couldn't find any difference between AS output from NDK 22 and 25 (apart from LLVM version of course) and manual checks of version output from AS duplicating script behavior (see `probe_cc()` function, it's identical in FFmpeg 4.4 and 5.1 branches) stuck in the same place, but somehow with NDK 22 it actually builds fine... Grep gets stuck on …
=> ffmpeg: don't pass --as when assembler is disabled

recipes/quill/all/conanfile.py
`QUILL_X86ARCH` uses some specific instructions for cache line optimisations (prefetch, clflushop) that are not available in each architecture. It also requires the user to compile their executable by passing specific flags (march). This option won't be needed by the majority of the users. It also should be possible to disable it. The default should be `False` and we should let the user explicitly enable it.
Specify library name and version:  **quill/2.7.0**
---
=> quill: QUILL_X86ARCH should be optional

recipes/simdutf/all/conandata.yml, recipes/simdutf/config.yml
Specify library name and version:  **simdutf/3.2.2**
---
=> simdutf: add version 3.2.2

recipes/googleapis/all/conanfile.py
Specify library name and version:  **googleapis/all**
Fix double deletion of `fPIC` and access to dependencies options.
=> googleapis: fix issues with shared=True in Conan 2.0

recipes/mgs/all/conandata.yml, recipes/mgs/all/conanfile.py, recipes/mgs/all/test_v1_package/conanfile.py
this recipe is not really v2 compatible (self.copy & self.output.warn usage)
---
=> mgs: modernize more for conan v2

recipes/cmake/binary/conandata.yml, recipes/cmake/binary/conanfile.py, recipes/cmake/binary/test_package/conanfile.py, recipes/cmake/binary/test_v1_package/conanfile.py, recipes/cmake/config.yml
Specify library name and version:  **cmake/all**
* Refactor CMake recipe to download the official CMake binaries provided by KitWare, on all 3 mainstream operating systems (Linux, macOS, Windows), on relevant architectures (x86_64 and armv8)
* Remove version 3.19 and update all current versions to the latest available patch version
* Old recipe is kept in the repository for those wishing to build CMake from source, but will no longer be built by our CI service
We aim to address a number of issues, as there is a growing number of recipes in Conan Center depend on `cmake` as provided by Conan Center.
* In Conan 1.x build requirement on CMake causes OpenSSL to become part of the dependency graph, and the version required by the CMake recipe may affect the graph resolution - overrides, …
=> CMake: Refactor recipe to download official binaries

recipes/libnop/all/conanfile.py, recipes/libnop/all/test_package/conanfile.py, recipes/libnop/all/test_v1_package/CMakeLists.txt
v2 packages are needed to pass v2 pipeline in https://github.com/conan-io/conan-center-index/pull/16037
---
=> libnop: modernize more for conan v2 (and generate v2 packages)

recipes/xorg-cf-files/all/conanfile.py
Specify library name and version:  **xorg-cf-files/all**
Workaround issue in Conan 2.0 where `package_type="build-scripts"` but a package is not created during `conan create .`, see https://github.com/conan-io/conan/issues/13431.
=> xorg-cf-files: remove package_type

recipes/libevent/all/conanfile.py, recipes/libevent/all/test_v1_package/CMakeLists.txt
pre-built v2 packages are missing. They are needed for https://github.com/conan-io/conan-center-index/pull/16181
---
=> libevent: modernize more & bump openssl (and generate packages in the meantime)

recipes/xz_utils/all/conanfile.py, recipes/xz_utils/all/test_package/CMakeLists.txt
same fix than https://github.com/conan-io/conan-center-index/pull/16389#issue-1610015353, but for test package of xz_utils.
---
=> xz_utils: add package_type + fix check of custom CMake variables in test package

recipes/expat/all/conanfile.py, recipes/expat/all/test_package_module/CMakeLists.txt
same fix than https://github.com/conan-io/conan-center-index/pull/16389#issue-1610015353, but for test package of expat.
---
=> expat: add package_type + fix check of custom CMake variables in test package

recipes/jasper/all/conanfile.py, recipes/jasper/all/test_package/CMakeLists.txt
same fix than https://github.com/conan-io/conan-center-index/pull/16389#issue-1610015353, but for test package of jasper.
---
=> jasper: add package_type + bump deps + fix check of custom CMake variables in test package

recipes/bzip2/all/conanfile.py, recipes/bzip2/all/test_package/CMakeLists.txt
same fix than https://github.com/conan-io/conan-center-index/pull/16389#issue-1610015353, but for test package of bzip2.
---
=> bzip2: add package_type + fix check of custom CMake variables in test package

recipes/boost-leaf/all/conanfile.py
So it's a warning and not a hard error this was to hard lined for #15190 considering how #14690 was too 
//cc @kammce
---
=> boost-leaf: fix deprecation

recipes/catch2/2.x.x/conanfile.py
catch2 2.x is header only, or static if with_main=True, there is no shared option.
`package_type = "library"` fails with conan v2 client when there is no shared option.
---
=> catch2 2.x: fix package_type

docs/labels.md
This new label will be used by C3I to automerge changes in `.c3i/conan_v2_ready_references.yml` without reviewers.
---
=> [docs] Document label c3i-conan2-ready

recipes/roaring/all/conandata.yml, recipes/roaring/config.yml
Specify library name and version:  **roaring/0.9.9**
---
=> roaring: add version 0.9.9

recipes/zfp/all/conanfile.py
Specify library name and version:  **zfp/1.0.0**
Fix zfp recipe failing with conan 2 when `with_cuda` or `with_openmp` options are enabled.
Error message:
```
ERROR: zfp/1.0.0: Error in validate() method, line 59
self.output.warn("Conan package for OpenMP is not available, this package will be used from system.")
AttributeError: 'ConanOutput' object has no attribute 'warn'
```
---
=> zfp: fix conan v2 package build failure

recipes/freetype/all/conanfile.py, recipes/freetype/all/test_package_module/CMakeLists.txt
same fix than https://github.com/conan-io/conan-center-index/pull/16389#issue-1610015353, but for test package of freetype.
---
=> freetype: add package_type + fix check of custom CMake variables in test package

recipes/catch2/2.x.x/conandata.yml, recipes/catch2/config.yml
Specify library name and version:  **catch2/2.13.10**
Adds the latest Catch2 v2 release: https://github.com/catchorg/Catch2/releases/tag/v2.13.10
---
=> catch2: add v2.13.10

recipes/re2/all/conanfile.py
=> re2: modernize more for conan v2

recipes/glad/all/CMakeLists.txt, recipes/glad/all/conandata.yml, recipes/glad/all/conanfile.py, recipes/glad/all/test_package/CMakeLists.txt, recipes/glad/all/test_package/conanfile.py, recipes/glad/all/test_v1_package/CMakeLists.txt, recipes/glad/all/test_v1_package/conanfile.py
I introduced Conan 2.0 support to the recipe of the **glad** library. For some reason I couldn't get hooks to work with Conan 2.0, so I'd appreciate some help with those if running them locally was necessary.
---
=> glad: modernize for Conan 2.0

recipes/pthreads4w/all/conanfile.py, recipes/pthreads4w/all/test_package/CMakeLists.txt, recipes/pthreads4w/all/test_package/conanfile.py, recipes/pthreads4w/all/test_v1_package/CMakeLists.txt, recipes/pthreads4w/all/test_v1_package/conanfile.py
Specify library name and version:  **pthreads4w/all**
Make recipe compatible with Conan 2.0
* Add `package_type` attribute
* Use new recipe tools from `conan.tools`
Build logic remains largely the same.
Tested with both msvc and mingw.
=> pthreads4w: make compatible with Conan 2.0

recipes/websocketpp/all/conanfile.py
websocketpp/0.8.x
Updated openssl to 1.1.1t due to vulnerabilities in 1.1.1s
=> websocketpp: Updated openssl dependency to 1.1.1t

recipes/pulseaudio/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/16493
---
=> pulseaudio: bump dependencies + modernize more for conan v2

.c3i/conan_v2_ready_references.yml
to unblock https://github.com/conan-io/conan-center-index/pull/15336
---
=> config: drop openssl from v2 ready since it does not work for 3.x version

recipes/gdcm/all/conandata.yml, recipes/gdcm/all/conanfile.py, recipes/gdcm/config.yml
Specify library name and version:  **gdcm/3.0.21**
---
=> gdcm: bump openssl and add 3.0.21

recipes/libcbor/all/conandata.yml, recipes/libcbor/config.yml
Specify library name and version:  **libcbor/0.10.2**
---
=> libcbor: add version 0.10.2

recipes/imath/all/conandata.yml, recipes/imath/config.yml
Specify library name and version:  **imath/3.1.7**
---
=> imath: add version 3.1.7

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  **imgui/1.89.4**
---
=> imgui: add version 1.89.4

recipes/vulkan-headers/all/conandata.yml, recipes/vulkan-headers/all/conanfile.py, recipes/vulkan-headers/all/test_v1_package/CMakeLists.txt, recipes/vulkan-headers/config.yml
conan v2 packages of vulkan-headers recipe are missing, they are fundamental for vulkan ecosystem.
I've dropped versions which are not used at all in other conan-center recipes.
---
=> vulkan-headers: modernize more + drop maintenance of several versions (and generate v2 packages)

recipes/matchit/all/conanfile.py, recipes/matchit/all/test_package/CMakeLists.txt, recipes/matchit/all/test_package/conanfile.py, recipes/matchit/all/test_v1_package/CMakeLists.txt, recipes/matchit/all/test_v1_package/conanfile.py
This recipe is not v2 compatible for `compiler=msvc` because in this case it goes in a (useless) branch relying on legacy `self.warn`
---
=> matchit: modernize more for conan v2

recipes/aws-c-auth/all/conanfile.py, recipes/aws-c-auth/all/test_v1_package/CMakeLists.txt
`aws-c-common`, `aws-c-io`, `aws-c-http` & `aws-c-sdkutils` are public dependencies of `aws-c-auth` (for sure headers, but when headers are public I assume by default that symbols of these libs must also be visible).
`aws-c-s3` recipe can't be built with conan v2 without this fix in `aws-c-auth`:
```
[1/19] Building C object CMakeFiles/aws-c-s3.dir/source/s3_checksum_stream.c.o
FAILED: CMakeFiles/aws-c-s3.dir/source/s3_checksum_stream.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DAWS_S3_EXPORTS -DAWS_S3_USE_IMPORT_EXPORT -DCJSON_HIDE_SYMBOLS -DHAVE_SYSCONF -Daws_c_s3_EXPORTS -I/Users/spaceim/.conan2/p/t/aws-c70872509acb17/b/src/include -isystem /Users/spaceim/.conan2/p/aws-cd1aa2d9c17c7a/p/include -isystem …
```
=> aws-c-auth: fix dependencies traits + modernize more

.c3i/reviewers.yml
Turns out @davidsanfal was not in the team review list
=> Add David to team reviewers

recipes/osqp/all/conandata.yml, recipes/osqp/all/conanfile.py, recipes/osqp/all/test_package/CMakeLists.txt, recipes/osqp/all/test_package/conanfile.py, recipes/osqp/all/test_package/test_package.cpp, recipes/osqp/all/test_v1_package/CMakeLists.txt, recipes/osqp/all/test_v1_package/conanfile.py, recipes/osqp/config.yml
Specify library name and version:  **osqp/0.6.2**
---
=> osqp: add recipe

recipes/getopt-for-visual-studio/all/conanfile.py, recipes/getopt-for-visual-studio/all/test_package/CMakeLists.txt, recipes/getopt-for-visual-studio/all/test_package/conanfile.py, recipes/getopt-for-visual-studio/all/test_v1_package/CMakeLists.txt
I need v2 packages to be able to generate v2 packages of `giflib` (https://github.com/conan-io/conan-center-index/pull/16566), so that I can generate v2 packages of `leptonica` (https://github.com/conan-io/conan-center-index/pull/16043)...
---
=> getopt-for-visual-studio: modernize more for conan v2 (and generate v2 packages)

recipes/glib/all/conandata.yml, recipes/glib/config.yml
Specify library name and version:  **glib/2.76.1**
---
=> glib: add version 2.76.1

recipes/backward-cpp/all/conanfile.py
Specify library name and version:  **backward-cpp/1.6**
These are transitive dependencies needed to build this package. If you include the header without this change, you get errors about it not finding the libraries this links to. Also, even if you don't have the header you want to expose the libraries as transitive dependencies because they are essential for how this library creates backtraces.
I've tested this locally using conan 2. There is still a remaining issue I'm experiencing when trying to use this package: I can't get it to print with debug info. I will continue to dig into that, but that it is unrelated to this fix.
@prince-chrismc thank you for the help over on cppslack. Let me know if there is anything I need to change about this PR.
---
=> backward-cpp: expose transitive dependencies

recipes/readerwriterqueue/all/conanfile.py
Specify library name and version:  **readerwriterqueue/all**
Fix regression introduced in https://github.com/conan-io/conan-center-index/pull/16353, where a header file is missing for the most recent version of the library.
Close https://github.com/conan-io/conan-center-index/issues/16651
=> readerwriterqueue: fix copying header files

recipes/vulkan-loader/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/16358
---
=> vulkan-loader: modernize more for conan v2

recipes/openjdk/all/conandata.yml, recipes/openjdk/all/conanfile.py, recipes/openjdk/all/test_package/conanfile.py, recipes/openjdk/config.yml
I tried removing this restriction on my Mac M1 and it worked so I wonder if we can delete it.
---
=> openjdk: Remove x86_64 architecture restriction

recipes/concurrencpp/all/conandata.yml, recipes/concurrencpp/all/conanfile.py, recipes/concurrencpp/all/patches/directory-name-0.1.6.patch, recipes/concurrencpp/config.yml
Specify library name and version:  **concurrencpp/0.1.6**
This updates the concurrencpp port to the latest version 0.1.6.
---
=> concurrencpp: add 0.1.6

recipes/asio/all/conandata.yml, recipes/asio/config.yml
Specify library name and version:  **asio/1.27.0**
Add newer versions of the standalone Asio library
I need the fixes contained in the newest version, and tested locally that depending on the created conan package works.
---
=> asio: Add versions 1.26.0 and 1.27.0

recipes/paho-mqtt-c/all/conanfile.py, recipes/paho-mqtt-c/all/test_package/conanfile.py
this recipe fails with conan v2 client because it tries to delete an option which doesn't exist anymore (deprecated `samples` option removed in https://github.com/conan-io/conan-center-index/pull/15434 but this PR forgot to remove logic in package id):
```
ERROR: paho-mqtt-c/1.3.12: Error in package_id() method, line 65
del self.info.options.samples
KeyError: 'samples'
```
---
=> paho-mqtt-c: bump openssl + modernize more for conan v2

recipes/libvpx/all/conanfile.py, recipes/libvpx/all/test_package/CMakeLists.txt, recipes/libvpx/all/test_package/conanfile.py
- relocatable shared lib on macOS
- fix legacy Visual Studio test to be v2 compatible
- move back configure logic to generate() thanks to AutotoolsToolchain.update_configure_args()
- honor compile & linker flags from profile in case of non-msvc builds
conan v2 support of this recipe (as well as libx264 & libx265) is important for `ffmpeg` (and therefore `opencv`).
/cc @paulharris I know there is https://github.com/conan-io/conan-center-index/pull/15827, but more fixes are needed for conan v2
---
=> libvpx: several fixes like relocatable share lib on macOS & proper conan v2 support

recipes/civetweb/all/conanfile.py, recipes/civetweb/all/test_package/conanfile.py, recipes/civetweb/all/test_v1_package/CMakeLists.txt, recipes/civetweb/all/test_v1_package/test_package.cpp
`ssl_dynamic_loading=True` is broken for conan v2 due to illegal usage of `self.options["openssl"]`.
---
=> civetweb: modernize more for conan v2

recipes/spirv-tools/all/conanfile.py
=> spirv-tools: fix `_cmake_new_enough()` for conan v2

recipes/minizip-ng/all/conandata.yml, recipes/minizip-ng/all/conanfile.py
Specify library name and version:  **minizip-ng/all**
Added missing frameworks
https://github.com/zlib-ng/minizip-ng/blob/cee6d8cbd4da70c48e9df1426607ff95b4f24fa6/CMakeLists.txt#L462
This allowed me to build minizip-ng for iOS (minizip-ng can't use OpenSSL that is built from recipe in CCI on iOS because of missing engine).
---
=> minizip-ng: add frameworks for Apple

recipes/mimalloc/all/conanfile.py
Specify library name and version:  **mimalloc/2.0.9**
Fixes #16160
---
=> mimalloc: Fixes #16160 (build error mimalloc MSVC x86 shared=False)

recipes/antlr4-cppruntime/all/conandata.yml, recipes/antlr4-cppruntime/all/test_package/CMakeLists.txt, recipes/antlr4-cppruntime/config.yml
Specify library name and version:  **antlr4-cppruntime/4.12.0**
---
=> antlr4-cppruntime: add version 4.12.0

recipes/sentry-crashpad/all/conanfile.py
**sentry-crashpad/0.6.0**
Seems to have been mistakenly(?) changed in #12051
---
=> sentry-crashpad: Fix wrong license being packaged

recipes/trantor/all/conandata.yml, recipes/trantor/config.yml
Specify library name and version:  **trantor/1.5.11**
---
=> trantor: add version 1.5.11

recipes/freetype/all/conanfile.py
Proposing as fix for 
https://github.com/conan-io/conan-center-index/issues/16415
chmod is called only when freetype_config file doesn't have execute permission.
Specify library name and version:  **freetype/2.12.1**
While using freetype conan package in a shared conan home environment faced permission issues (freetype/2.12.1: In Shared Conan User Home usage, seen PermissionError on "bin/freetype-config"). This is happening as every time package_info method is called, chmod is executed to change the file permissions on "freetype_config" file.
---
=> Update conanfile.py for freetype/2.12.1

recipes/harfbuzz/all/conandata.yml, recipes/harfbuzz/all/conanfile.py, recipes/harfbuzz/all/test_package/CMakeLists.txt, recipes/harfbuzz/config.yml
- fix access to self.options in package_id() (forbidden in conan v2). Actually logic in package_id() is removed to follow recommendations of https://github.com/conan-io/conan-center-index/pull/16018
- avoid glib in build requirements in case of native build or if with_glib=False (having the same dependency in requirements & build requirements can significantly increase build time because they may be built with different shared option (including transitive dependencies, and glib is not a tiny library...))
- sort methods by order of execution
- bump freetype & glib
---
=> harfbuzz: modernize more for conan v2

recipes/opengl/all/conanfile.py
Specify library name and version:  **opengl/system**
On (open)Suse systems some opengl header files are packaged in package glproto-devel. This package installs oa the following header files:
GL/glxint.h GL/glxmd.h GL/glxproto.h GL/glxtokens.h .
These header files are needed to build for example package 'qt' including the QWebEngine library.
---
=> opengl: on Suse systems some opengl header files are in package glproto-devel

recipes/wayland-protocols/all/conandata.yml, recipes/wayland-protocols/all/conanfile.py
Specify library name and version:  **wayland-protocols/***
It seems that the [wayland-project](https://github.com/wayland-project) organisation on GitHub is no longer having any public repositories. There all the source urls are no longer working. Unfortunately the GitLab setup is not having all the older versions listed in conandata available.
---
=> wayland-protocols: fix source references

recipes/spdlog/all/conanfile.py
Specify library name and version:  **spdlog/1.11.0**
fix issue https://github.com/conan-io/conan-center-index/issues/16652
---
=> spdlog fix: option 'shared' doesn't exist

recipes/libgcrypt/all/conanfile.py
Public header of libgpg-error is included by libgcrypt public header: https://github.com/gpg/libgcrypt/blob/ccfa9f2c1427b40483984198c3df41f8057f69f8/src/gcrypt.h.in#L30
I've checked and transitive_libs is not required (libgcrypt header only use static functions or typedef defined in header of libgpg-error).
---
=> libgcrypt: expose headers of libgpg-error

recipes/coin-clp/all/conanfile.py
Specify library name and version:  **coin-clp/1.17.7**
The public API of coin-clp contains the headers CoinPragma.hpp (from coin-utils, see c.f. ClpMessage.hpp) and OsiSolverInterface.hpp (from coin-osi, see c.f. OsiClpSolverInterface.hpp)
---
=> [coin-clp] Make headers of required packages transitive

recipes/cmake/binary/conandata.yml, recipes/cmake/config.yml
Specify library name and version:  **cmake/3.19.8**
CMake recipe is extensively used (even outside of its usage within other Conan Center recipes). This PR extends the newer "binary" recipe to cover down to the most recent 3.19 patch release.
=> cmake: add version 3.19.8 (from KitWare binaries)

.github/workflows/alert-community.yml
=> config: remove eric from gtk alerts

recipes/openapi-generator/all/conanfile.py
Specify library name and version:  **openapi-generator/all**
The recipe was mostly all the way there, just missing a minor self.info.settings -> self.settings change
=> openapigenerator: Use `self.settings` in `package()` for v2 support

recipes/date/all/conanfile.py
Specify library name and version:  **date/3.0.0**
Error for cross-build from linux to android-arm according to:
https://github.com/HowardHinnant/date/issues/161
---
=> date: fix for android

recipes/doxygen/all/conandata.yml, recipes/doxygen/all/patches/1.9.4-0001-enable-modern-compilers.patch
Closes #16741
Specify library name and version:  **doxygen/1.9.4**
---
=> [doxygen] Backport patch to enable modern compilers for 1.9.4

recipes/json-schema-validator/all/conanfile.py
- do not use self.ouput.warn since it's not v2 compatible
- use standard template to check min compiler version (it fixes issue above actually)
- don't use self.deps_cpp_info (not v2 compatible), otherwise versions < 2.1.0 are broken
---
=> json-schema-validator: fix msvc for conan v2 + add package_type

recipes/function2/all/conanfile.py, recipes/function2/all/test_v1_package/CMakeLists.txt
- do not use self.ouput.warn since it's not v2 compatible
- use standard template to check min compiler version (it fixes issue above actually)
- use standard template in test v1 package
---
=> function2: fix msvc for conan v2 + add package_type

recipes/bitflags/all/conanfile.py, recipes/bitflags/all/test_v1_package/CMakeLists.txt
- fix msvc (it was going into a branch calling old self.output.warn which is not available in conan v2)
---
=> bitflags: modernize more for conan v2

recipes/gnu-config/all/conandata.yml, recipes/gnu-config/all/conanfile.py, recipes/gnu-config/all/patches/cci.20210814-0001-tvos-support.patch
Specify library name and version:  **gnu-config/cci.20210804**
The intention is to use this patch to cross-build libraries, with errors like:
```
checking build system type... aarch64-apple-darwin
checking host system type... Invalid configuration `x86_64-apple-tvos': OS `tvos' not recognized
```
For example, it was reported in the issue https://github.com/conan-io/conan-center-index/issues/8990 when building iconv.
---
=> gnu-config: add support to tvOS and watchOS

docs/error_knowledge_base.md, docs/package_templates/autotools_package/all/test_package/CMakeLists.txt, docs/package_templates/autotools_package/all/test_v1_package/CMakeLists.txt, docs/package_templates/cmake_package/all/test_package/CMakeLists.txt, docs/package_templates/cmake_package/all/test_v1_package/CMakeLists.txt, docs/package_templates/header_only/all/test_package/CMakeLists.txt, docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt, docs/package_templates/msbuild_package/all/test_package/CMakeLists.txt, docs/package_templates/msbuild_package/all/test_v1_package/CMakeLists.txt
Conan 2.0 has the requirement set to 3.15 and thus everything should just default to using that as baseline.
=> docs: clarify everything should use CMake 3.15 to match Conan 2.0

recipes/sentry-native/all/conanfile.py
**sentry-native/0.6.0**
Feedback from #16530
---
=> sentry-native: Properly platform and version protect the new wer option

recipes/rang/all/conanfile.py, recipes/rang/all/test_package/CMakeLists.txt, recipes/rang/all/test_package/conanfile.py, recipes/rang/all/test_v1_package/CMakeLists.txt, recipes/rang/all/test_v1_package/conanfile.py
=> rang: conan v2 support

recipes/lightgbm/all/conandata.yml, recipes/lightgbm/all/patches/0003-fix-openmp-clang.patch, recipes/lightgbm/config.yml
lightgbm/3.3.5
Updated to version 3.3.5, fixed patch 0002-fix-openmp-clang.patch
Closes #16409
---
=> [lightgbm] Update version to 3.3.5 (#16409)

recipes/qpdf/all/conanfile.py, recipes/qpdf/all/test_v1_package/CMakeLists.txt, recipes/qpdf/all/test_v1_package/conanfile.py
- bump openssl
- Fix few issues:
- build requirements to cmake 3.24.1 prevents build with conan v2 since the specific version has not been migrated
- topics was not a tuple
- there was an unwanted qpdf::qpdf target declared in CMakeDeps
---
=> qpdf: bump dependencies + modernize more for conan v2

recipes/cityhash/all/conanfile.py
- don't try to access self.user_info_build to get path to ar-lib script of automake recipe, since it's not compatible with conan v2
- check Visual Studio versions with check_min_vs
---
=> cityhash: fix msvc for conan v2

docs/linters.md, linter/check_version_attribute.py, linter/conanv2_transition.py, linter/pylintrc_recipe
Enforcing a specific package version by the `version` attribute is no a good idea, as the same recipe should support multiple versions. 
There is an exception for `system` packages, which does not require a generic recipe version.
---
=> [linter] Do not accept version attribute on regular recipes

recipes/gnutls/all/conanfile.py, recipes/gnutls/all/test_package/CMakeLists.txt, recipes/gnutls/all/test_package/conanfile.py, recipes/gnutls/all/test_v1_package/conanfile.py
- fix libs ordering in package_info() (gnutlsxx depends on gnutls)
- allow to build with MinGW
- add pkgconf in build requirements since recipe relies on pkgconf files
- expose official CMake variabes from https://cmake.org/cmake/help/latest/module/FindGnuTLS.html in CMakeDeps & cmake_find_package generators
---
=> gnutls: several fixes & improvements (CMake variables, libs ordering, MinGW)

recipes/coin-lemon/all/conanfile.py
Short identifier of Boost Software License 1.0 is BSL-1.0, not Boost 1.0: https://spdx.org/licenses/BSL-1.0
---
=> coin-lemon: use correct BSL-1.0 license identifier (and generate v2 packages)

recipes/apr/all/conanfile.py
https://github.com/conan-io/conan-center-index/pull/16142 can't be tested in v2 pipeline if pre-built apr packages are missing
---
=> apr: add package_type (and generate v2 packages)

recipes/libyuv/all/conanfile.py, recipes/libyuv/all/patches/1768-0001-fix-cmake.patch, recipes/libyuv/all/patches/1841-0001-fix-cmake.patch, recipes/libyuv/all/patches/1854-0001-fix-cmake.patch
closes https://github.com/conan-io/conan-center-index/issues/16831
There are global symbols in libyuv, therefore CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS workaround is not sufficient and leads to an illformed imported lib for Visual Studio.
---
=> libyuv: raise if msvc & shared

recipes/rapidcheck/all/CMakeLists.txt, recipes/rapidcheck/all/conandata.yml, recipes/rapidcheck/all/conanfile.py, recipes/rapidcheck/all/test_package/CMakeLists.txt, recipes/rapidcheck/all/test_package/conanfile.py, recipes/rapidcheck/all/test_v1_package/CMakeLists.txt, recipes/rapidcheck/all/test_v1_package/conanfile.py
Specify library name and version:  **rapidcheck/cci.20220514**
This fixes #14854
---
=> rapidcheck: fix gmock option and convert to v2

recipes/libfdk_aac/all/conanfile.py
these packages are mandatory to pass v2 pipeline in https://github.com/conan-io/conan-center-index/pull/15819
---
=> libfdk_aac: add package_type (and generate v2 packages)

recipes/freetype/all/conanfile.py
This target also exists in upstream config file since 2.13.0 (in addition to `freetype` imported target): https://github.com/freetype/freetype/commit/55a97b0cb133b7a5dc28dfabec77a1b9f742c301
closes https://github.com/conan-io/conan-center-index/issues/16824
---
=> freetype: also define `Freetype::Freetype` imported target in config file generated by CMakeDeps

recipes/libexif/all/conandata.yml
Specify library name and version:  **libexif/0.6.24**
---
=> Correct libexif conandata.yml url for libexif version 0.6.24

recipes/xorg/all/conanfile.py
In Conan 2.0 the lack of package type affects how dependencies propagate when building shared libraries.
In this case, `"shared-library"` is the most accurate `package_type`. While all the system packages that are being installed by this recipe (`*-dev` packages) have both static and shared,  the `PkgConfig` helper from `conan.tools.gnu` is _not_ passing `--static`, and the libraries propagated via `cpp_info` as `system_libs` are implicitly shared (the linker will prefer them shared if both are available).
=> xorg: add package type

recipes/sqlite3/all/test_package/test_package.c
Specify library name and version:  **sqlite3/3.39.4**
package tests fails if same package is created twice.
```
conan create . sqlite3/3.39.4    -o sqlite3:shared=True
conan create . sqlite3/3.39.4    -o sqlite3:shared=True
```
I got the error:
```
SQLite Version: 3.39.4
Creating new data base ...
Done!
Creating new table...
SQL error: table package already exists
```
=> fix sqlite3 test

recipes/ccache/all/conandata.yml, recipes/ccache/all/conanfile.py, recipes/ccache/all/patches/4.7.4-cmake-msvc-runtime.patch, recipes/ccache/config.yml
I discovered ccache always wants to build with -MT (or /MT) even if conan wants /MD,
which results in a build failure on my machine as zstd and hiredis was built with /MD.
I wonder how this passed the C3I test?
=> ccache: don't override conan's MSVC runtime choice

recipes/eigen/all/conandata.yml, recipes/eigen/all/conanfile.py, recipes/eigen/all/patches/3.4.0-0001-vec-reduce-half.patch
Specify library name and version:  **eigen/3.4.0**
This fixes compilation errors.
According to https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conandata_yml_format.md#bugfix this might require a new cci version rather than a patch on 3.4.0 however, given it does not change the flow of execution or the results (compile time issue) and it seems there is a precedent in this recipe, I went with a patch on 3.4.0 (the patch itself is a cherry pick from upstream branch 3.4, there is no ETA on a 3.4.1 version upstream)
If this is not deemed acceptable, I will open a PR for a new cci version using the exact same git commit as used in onnxruntime 1.14.1 (before 3.4.0).
The fix is required to build #16849 / #16842
---
=> eigen(3.4.0): Fix vectorized reductions compilation errors for Eigen::half

recipes/pfr/all/conandata.yml, recipes/pfr/all/conanfile.py, recipes/pfr/all/test_package/conanfile.py, recipes/pfr/config.yml
- do not use self.ouput.warn since it's not v2 compatible
- use standard template to check min compiler version (it fixes issue above actually)
- order by desc versions in conandata.yml & config.yml
---
=> pfr: fix msvc for conan v2 + add package_type

recipes/nanorange/all/conandata.yml, recipes/nanorange/config.yml
Specify library name and version:  **nanorange/cci.20200505**
---
=> nanorange: add version cci.20200505

recipes/opengv/all/conanfile.py, recipes/opengv/all/test_package/CMakeLists.txt, recipes/opengv/all/test_package/conanfile.py, recipes/opengv/all/test_v1_package/CMakeLists.txt
- allow to raise gracefully on Windows by avoiding error during double deletion of fPIC (it's important for c3i to see a ConanInvalidConfiguration instead of a random python error)
- use standard template in test v1 package
- fix import of cmake_layout in test package
- bump pybind11
- use f-string
---
=> opengv: modernize more for conan v2

recipes/libiberty/all/conanfile.py
Specify library name and version:  **libiberty/9.1.0**
This MR provides `package_type = static-library` attribute.
(Secondary objective) see if CI generates conan v2 package (detected missing package here https://c3i.jfrog.io/c3i/misc-v2/logs/pr/15726/20-linux-gcc/folly/2020.08.10.00//9b276f5023f4804656038dfee5e53c428c50949e-build.txt)
---
=> libiberty provide package_type static-library

recipes/mio/all/conandata.yml, recipes/mio/config.yml
Specify library name and version:  **mio/cci.20230303**
for https://github.com/mandreyel/mio/pull/88, Avoid multiply defined s_2_ws linker error
---
=> add mio/cci.20230303

.c3i/config_v1.yml
Specify library name and version:  **gstreamer/all**
As suggested by @davidsanfal and @danimtb, let's try to put this library in a large pod, see if that helps (Although I suspect no, it's worth a try)
Ping @jwillikers sorry it's taking so long, it's been tricky :)
=> Add gstreamer to large pod

recipes/libdwarf/all/conanfile.py
Specify library name and version:  **libdwarf/all**
This MR adds `package_type=library` to libdwarf. 
Also while iterating over folly recipe I saw there was no conan2 libdwarf package https://c3i.jfrog.io/c3i/misc-v2/logs/pr/15726/20-linux-gcc/folly/2020.08.10.00//9b276f5023f4804656038dfee5e53c428c50949e-build.txt so I'm hoping this MR CI will also generate one.
---
=> libdwarf specify package_type library 

recipes/highfive/all/conandata.yml, recipes/highfive/all/conanfile.py, recipes/highfive/config.yml
Specify library name and version:  **highfive/all**
- Add `v2.7.0`
- Bump `xtensor`
---
=> highfive: add v2.7.0 and bump deps

recipes/hidapi/all/conanfile.py
Specify library name and version:  **hidapi/0.13.1**
The [configure.ac](https://github.com/libusb/hidapi/blob/4ebce6b5059b086d05ca7e091ce04a5fd08ac3ac/configure.ac#L60) file explicitly checks for libudev on Linux on all packaged versions back to 0.10.1.
Fixes: #16770
---
=> hidapi: add required libudev dependency

recipes/libmysqlclient/all/conanfile.py
generated by running:
```
conan config install https://github.com/ericLemanissier/conan-extensions.git
conan recipe:bump-deps recipes/libmysqlclient/all/
```
Specify library name and version:  **libmysqlclient/***
---
=> libmysqlclient: bump deps

recipes/readosm/all/conandata.yml, recipes/readosm/all/conanfile.py, recipes/readosm/all/patches/0001-fix-nmake.patch, recipes/readosm/all/test_package/CMakeLists.txt, recipes/readosm/all/test_package/conanfile.py, recipes/readosm/all/test_v1_package/CMakeLists.txt, recipes/readosm/all/test_v1_package/conanfile.py
=> readosm: conan v2 support

recipes/libnabo/all/conandata.yml, recipes/libnabo/all/conanfile.py, recipes/libnabo/all/patches/1.0.7-0001-fix-cmake.patch, recipes/libnabo/all/test_package/CMakeLists.txt, recipes/libnabo/all/test_package/conanfile.py, recipes/libnabo/all/test_package/test_package.cpp, recipes/libnabo/all/test_v1_package/CMakeLists.txt, recipes/libnabo/all/test_v1_package/conanfile.py, recipes/libnabo/config.yml
closes https://github.com/conan-io/conan-center-index/issues/16395
---
=> New recipe libnabo/1.0.7

recipes/proj/all/conanfile.py
proj fails in v2 pipeline: https://github.com/conan-io/conan-center-index/pull/16911#issuecomment-1499582973
I can't reproduce this issue locally neither on macOS, Windows or Linux, but here is an attempt to pass v2 pipeline.
---
=> proj: fix recipe for conan v2

recipes/s2n/all/CMakeLists.txt, recipes/s2n/all/conandata.yml, recipes/s2n/all/conanfile.py, recipes/s2n/all/test_package/CMakeLists.txt, recipes/s2n/all/test_package/conanfile.py, recipes/s2n/all/test_v1_package/CMakeLists.txt, recipes/s2n/all/test_v1_package/conanfile.py
Mandatory for the dependency graph of `aws-sdk-cpp`, since it's a dependency of `aws-c-io` on Linux (which is a mandatory dependency of `aws-sdk-cpp` since 1.9).
---
=> s2n: conan v2 support

recipes/boost/all/conanfile.py
Issue that I faced as written on Slack:
> I have boost built for android, each lib has a symlink (libboost_atomic.so) and real file (libboost_atomic.so.1.81.0). I consume the libs in a cmake project, project’s libs get linked to the real file (libboost_atomic.so.1.81.0). Now when gradle builds apk, it resolves all symlinks (i.e. libboost_atomic.so  becomes a real file in the apk) but completely ignores all files that don’t end with .so . (before running gradle I copy all libs with conan imports if it matters) Of course, app doesn’t work because it can’t find libboost_atomic.so.1.81.0 , sample error:
>
>…caused by could not load library “libboost_atomic.so.1.81.0” needed by “libvcmi.so”; caused by library “libboost_atomic.so.1.81.0” not …
=> Boost: use versionless soname on Android

recipes/safeint/all/conandata.yml, recipes/safeint/config.yml
Specify library name and version:  **safeint/3.0.28**
---
=> safeint: add version 3.0.28

recipes/paho-mqtt-c/all/conanfile.py
https://github.com/conan-io/conan-center-index/pull/16760/files#r1156719312
Flagged this
---
=> paho-mqtt-c: openssl headers are exposed in public headers

recipes/c4core/all/conanfile.py, recipes/qt/5.x.x/conanfile.py
**qt/5.x**
`python2` is only needed to build qt. Moved `python2` verification to `build_requirements` as `validate` method is also executed when using the qt package.
In other words, you don't need `python2` to be installed if you want to use pre compiled binaries.   
---
=> [qt5] only check for python2 at build time

recipes/antlr4-cppruntime/all/conanfile.py
Specify library name and version:  **antlr4-cppruntime/4.12.0**
This PR contains the following changes:
- Upgrade the runtime library to 4.12.0.
- Upgrade the receipt to build the shared/static library only instead of both of them as of 4.12.0.
- Related Issue: https://github.com/antlr/antlr4/issues/3993
- Related PR: https://github.com/antlr/antlr4/pull/3996
- Related CMake Options: `ANTLR_BUILD_SHARED` and `ANTLR_BUILD_STATIC`
- Drop the dependency `utfcpp` as of 4.10.0.
- Related PR: https://github.com/antlr/antlr4/pull/3398
- Bump the dependency `utfcpp` to 3.2.3. 
Thank you.
---
=> antlr4-cppruntime: Upgrade to 4.12.0

recipes/libudev/all/conanfile.py
Specify library name and version:  **libudev/system**
recent versions of openSUSE Leap (i.e. 15.4) changed the package containing the udev development files from `libudev-devel` to `systemd-devel` bringing it inline with the naming e.g. in fedora. This is a trivial patch to the recipe that allows it to succeed on both older and current versions of openSUSE by using the `install_substitutes` functionality.
---
=> fix opensuse naming of libudev dependency

.c3i/config_v1.yml, .c3i/config_v2.yml
Please, read https://github.com/conan-io/conan-center-index/discussions/16729 to get more information about.
We will drop the follow configurations:
Conan v1:
- compiler.libcxx=libstdc++ for all GCC profiles
- GCC 8
- Apple Clang 11.0 12.0
- Visual Studio 15
- compiler.runtime=MT/MTd for all Visual Studio profiles
Conan v2:
- compiler.runtime=static for all msvc profiles
---
=> [config] Drop some Conan v1 pipeline configurations

.c3i/config_v1.yml
This reverts commit 3c62b4dd3271c4f328e84fc447d592d2a2ba2520.
This turns out not be useful for the timeout issue, so revert it back to a normal pod as it's overkill to keep it in a large one
=> Revert "Add gstreamer to large pod"

.gitignore
In the binutils recipe (PR #16920) with `basic_layout`, a `recipes/binutils/all/test_package/build-release/`
directory appears.
---
=> Ignore more test_package build dir patterns

recipes/xorg-makedepend/all/conanfile.py
Specify library name and version:  xorg-makedepend/any
fixes #16927
---
=> Correct xorg-makedepend homepage url

recipes/lief/all/conanfile.py
=> lief: modernize more for conan v2

recipes/gnu-config/all/conanfile.py
Specify library name and version:  **gnu-config/cci.20210804**
Fix the PR https://github.com/conan-io/conan-center-index/pull/16802, which added a patch but didn't export and didn't apply the patch.
---
=> gnu-config: export and apply patches

recipes/redis-plus-plus/all/patches/1.3.7-0001-fix-dependencies-injection.patch
Fixes a missing hiredis_ssl cmake config file for 1.3.7
Specify library name and version:  **redis-plus-plus/1.3.7**
When ssl is enabled, the build currently fails with
```
CMake Error at CMakeLists.txt:133 (find_package):
By not providing "Findhiredis_ssl.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"hiredis_ssl", but CMake did not find one.
Could not find a package configuration file provided by "hiredis_ssl" with
any of the following names:
hiredis_sslConfig.cmake
hiredis_ssl-config.cmake
Add the installation prefix of "hiredis_ssl" to CMAKE_PREFIX_PATH or set
"hiredis_ssl_DIR" to a directory containing one of the above files.  If
"hiredis_ssl" provides a separate development package or SDK, be sure it
has been installed.
``` …
=> redis-plus-plus: fix build with ssl

recipes/paho-mqtt-cpp/all/CMakeLists.txt, recipes/paho-mqtt-cpp/all/conandata.yml, recipes/paho-mqtt-cpp/all/conanfile.py, recipes/paho-mqtt-cpp/all/test_package/CMakeLists.txt, recipes/paho-mqtt-cpp/all/test_package/conanfile.py, recipes/paho-mqtt-cpp/all/test_package/test_package.cpp, recipes/paho-mqtt-cpp/all/test_v1_package/CMakeLists.txt, recipes/paho-mqtt-cpp/all/test_v1_package/conanfile.py
Specify library name and version:  **paho-mqtt-cpp/1.2** (also 1.0.1 and 1.1 should their recipes be updated).
Existing recipe is not conan 2.0 compatible.  Blocker for internal projects.
This does raise an error with the hook for (KB-H055) (Both 'requires' attribute and 'requirements()' method should not be declared at same recipe) but I've not been able to identify why this assert is being triggered as there is no requires attribute set.
---
=> paho-mqtt-cpp: update for conan 2.0

recipes/ruy/all/CMakeLists.txt, recipes/ruy/all/conandata.yml, recipes/ruy/all/conanfile.py, recipes/ruy/all/test_package/CMakeLists.txt, recipes/ruy/all/test_package/conanfile.py, recipes/ruy/all/test_v1_package/CMakeLists.txt, recipes/ruy/all/test_v1_package/conanfile.py, recipes/ruy/all/test_v1_package/test_package.cpp, recipes/ruy/config.yml
Specify library name and version:  **ruy/all**
Changes in this PR:
* Use newer Conan 2.0 integrations, while maintaining compatibility with Conan 1.x
* Remove older version which has outdated CMake scripts, with limitations. Newer versions are more "conventional modern cmake" - this allows us to remove workarounds to handle the cpuinfo dependency
* Add workaround to ensure that `cmake_minimum_required()` is the first thing called in the project - this is an upstream issue which has been reported: https://github.com/google/ruy/issues/328
* Bump dependency on cpuinfo to latest
=> ruy: update to support Conan 2.0
