- recipes/glslang/all/CMakeLists.txt
- recipes/glslang/all/conandata.yml
- recipes/glslang/all/conanfile.py
- recipes/glslang/all/test_v1_package/CMakeLists.txt
- recipes/glslang/config.yml
> glslang: 1.3.231.1 + conan v2 support

- recipes/opus/all/conanfile.py
- recipes/opus/all/test_package/conanfile.py
- recipes/opus/all/test_v1_package/CMakeLists.txt
- recipes/opus/all/test_v1_package/conanfile.py
> opus: modernize more

- recipes/websocketpp/all/conandata.yml
- recipes/websocketpp/all/conanfile.py
Bump openssl/1.1.1s, zlib 1.2.13, boost/1.80.0 and standalone asio 1.24.0
> [websocketpp] Bump openssl/1.1.1s, zlib 1.2.13, boost/1.80.0

- recipes/mpark-variant/all/conanfile.py
- recipes/mpark-variant/all/test_package/CMakeLists.txt
- recipes/mpark-variant/all/test_package/conanfile.py
- recipes/mpark-variant/all/test_v1_package/CMakeLists.txt
- recipes/mpark-variant/all/test_v1_package/conanfile.py
> mpark-variant: conan v2 support

- recipes/hash-library/all/conanfile.py
Specify library name and version:  **hash-library/8.0**
Fixes #14105
---
> hash-library: fix Conan V2 support

- recipes/libzip/all/CMakeLists.txt
- recipes/libzip/all/conandata.yml
- recipes/libzip/all/conanfile.py
- recipes/libzip/all/test_package/CMakeLists.txt
- recipes/libzip/all/test_package/conanfile.py
- recipes/libzip/all/test_v1_package/CMakeLists.txt
- recipes/libzip/all/test_v1_package/conanfile.py
> libzip: conan v2 support

- recipes/create-dmg/all/conanfile.py
- recipes/create-dmg/all/test_package/conanfile.py
> create-dmg: fix package id & download logic of this recipe

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Specify library name and version:  **glib/2.75.0**
---
> glib 2.75.0

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/config.yml
> daw_json_link: add version 3.5.0, remove older versions

- recipes/qt/5.x.x/conanfile.py
cf https://github.com/conan-io/conan-center-index/issues/13999
---
> Qt5: improve cross-compilation

- recipes/embree3/all/conandata.yml
- recipes/embree3/all/conanfile.py
- recipes/embree3/config.yml
Allow compiling **embree3** with **tbb/onetbb** as task system
---
> Enable tbb use in embree3

- recipes/libpng/all/conanfile.py
fixes https://github.com/conan-io/conan-center-index/issues/13467
Specify library name and version:  **libpng/1.6.38**
---
> libpng: fix 1.6.38 on windows clang

- recipes/dragonbox/all/conandata.yml
- recipes/dragonbox/all/conanfile.py
- recipes/dragonbox/all/patches/1.1.3-fix-include-directory.patch
- recipes/dragonbox/all/test_package/CMakeLists.txt
- recipes/dragonbox/all/test_package/conanfile.py
- recipes/dragonbox/all/test_package/test_package.cpp
- recipes/dragonbox/all/test_v1_package/CMakeLists.txt
- recipes/dragonbox/all/test_v1_package/conanfile.py
- recipes/dragonbox/config.yml
Specify library name and version:  **dragonbox/1.1.3**
---
> dragonbox: add recipe

- recipes/qr-code-generator/all/CMakeLists.txt
- recipes/qr-code-generator/all/conandata.yml
- recipes/qr-code-generator/all/conanfile.py
- recipes/qr-code-generator/all/patches/002-cmake-pre-1.6.patch
- recipes/qr-code-generator/all/patches/003-cmake-1.6.patch
- recipes/qr-code-generator/all/patches/004-cmake-1.7.patch
- recipes/qr-code-generator/all/test_package/CMakeLists.txt
- recipes/qr-code-generator/all/test_package/conanfile.py
- recipes/qr-code-generator/all/test_v1_package/CMakeLists.txt
- recipes/qr-code-generator/all/test_v1_package/conanfile.py
Specify library name and version:  **qr-code-generator/all**
---
> qr-code-generator: conan v2 support

- recipes/onetbb/all/conandata.yml
- recipes/onetbb/config.yml
> onetbb: add version 2021.7.0

- recipes/libmetalink/all/conanfile.py
- recipes/libmetalink/all/test_package/conanfile.py
- recipes/libmetalink/all/test_v1_package/CMakeLists.txt
- recipes/libmetalink/all/test_v1_package/conanfile.py
> libmetalink: conan v2 support

- recipes/entt/3.x.x/conandata.yml
- recipes/entt/3.x.x/conanfile.py
- recipes/entt/3.x.x/patches/0001-3.11.0-fix-gcc-7.0-7.3.patch
- recipes/entt/3.x.x/test_package/conanfile.py
- recipes/entt/3.x.x/test_v1_package/CMakeLists.txt
- recipes/entt/3.x.x/test_v1_package/conanfile.py
- recipes/entt/config.yml
> Bump entt/3.11.0

- recipes/icu/all/conandata.yml
- recipes/icu/all/conanfile.py
- recipes/icu/all/test_package/CMakeLists.txt
- recipes/icu/all/test_package/conanfile.py
- recipes/icu/all/test_v1_package/CMakeLists.txt
- recipes/icu/all/test_v1_package/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/10160
closes https://github.com/conan-io/conan-center-index/issues/11498
---
> icu: conan v2 support

- recipes/diligent-core/all/conandata.yml
- recipes/diligent-core/all/conanfile.py
- recipes/diligent-core/config.yml
Specify library name and version:  **diligent-core/api.252009**
---
> add diligent-core/api.252009

- recipes/termcap/all/CMakeLists.txt
- recipes/termcap/all/conandata.yml
- recipes/termcap/all/conanfile.py
- recipes/termcap/all/test_package/CMakeLists.txt
- recipes/termcap/all/test_package/conanfile.py
- recipes/termcap/all/test_v1_package/CMakeLists.txt
- recipes/termcap/all/test_v1_package/conanfile.py
> termcap: conan v2 support

- recipes/expat/all/conandata.yml
- recipes/expat/all/conanfile.py
- recipes/expat/all/test_package/conanfile.py
- recipes/expat/all/test_package_module/conanfile.py
> expat: modernize more

- recipes/lief/all/conandata.yml
- recipes/lief/all/patches/0.12.3-001_link_to_conan.patch
- recipes/lief/config.yml
Specify library name and version:  **lief/0.12.3**
---
> lief: add version 0.12.3

- recipes/libharu/all/CMakeLists.txt
- recipes/libharu/all/conandata.yml
- recipes/libharu/all/conanfile.py
- recipes/libharu/all/patches/0001-allow-cmake-subproject.patch
- recipes/libharu/all/patches/0002-linux-add-m-system-library.patch
- recipes/libharu/all/test_package/CMakeLists.txt
- recipes/libharu/all/test_package/conanfile.py
- recipes/libharu/all/test_v1_package/CMakeLists.txt
- recipes/libharu/all/test_v1_package/conanfile.py
- recipes/libharu/config.yml
Upgrading the recipe and adding a new version which has better cmake files !
> libharu: conan v2 and new version

- recipes/cyrus-sasl/all/conanfile.py
- recipes/cyrus-sasl/all/test_v1_package/CMakeLists.txt
> cyrus-sasl: bump openssl + modernize a little bit more

- recipes/odbc/all/conanfile.py
- recipes/odbc/all/test_v1_package/CMakeLists.txt
> odbc: more conan v2 stuff

- recipes/lunasvg/all/conandata.yml
- recipes/lunasvg/all/conanfile.py
- recipes/lunasvg/all/patches/2.3.5-0001-fix-cmake.patch
- recipes/lunasvg/config.yml
Specify library name and version:  **lunasvg/2.3.5**
---
> lunasvg: add version 2.3.5

- recipes/clara/all/conanfile.py
- recipes/clara/all/test_package/CMakeLists.txt
- recipes/clara/all/test_package/conanfile.py
- recipes/clara/all/test_v1_package/CMakeLists.txt
- recipes/clara/all/test_v1_package/conanfile.py
Specify library name and version:  **clara/1.1.5**
---
> clara: conan v2 migration

- recipes/xerces-c/all/conandata.yml
- recipes/xerces-c/all/patches/0001-remove-test-samples-324.patch
- recipes/xerces-c/config.yml
Specify library name and version:  **xerces-c/3.2.4**
---
> xerces-c: upgrade to 3.2.4

- recipes/grpc/all/conandata.yml
- recipes/grpc/all/conanfile.py
- recipes/grpc/config.yml
Specify library name and version:  **grpc/***
---
> grpc: add version 1.50.1, update openssl

- recipes/libtiff/all/conanfile.py
- recipes/libtiff/all/test_v1_package/CMakeLists.txt
closes https://github.com/conan-io/conan-center-index/issues/14206
---
> libtiff: build static libs when shared=False

- recipes/egl-headers/all/conandata.yml
- recipes/egl-headers/all/conanfile.py
- recipes/egl-headers/all/test_package/CMakeLists.txt
- recipes/egl-headers/all/test_package/conanfile.py
- recipes/egl-headers/all/test_package/test_package.c
- recipes/egl-headers/all/test_v1_package/CMakeLists.txt
- recipes/egl-headers/all/test_v1_package/conanfile.py
- recipes/egl-headers/config.yml
Specify library name and version:  **egl-headers/cci.20220525**
---
> egl-headers

- recipes/libpng/all/conandata.yml
- recipes/libpng/all/conanfile.py
- recipes/libpng/all/test_package/CMakeLists.txt
- recipes/libpng/all/test_package/conanfile.py
- recipes/libpng/all/test_v1_package/CMakeLists.txt
- recipes/libpng/all/test_v1_package/conanfile.py
> libpng: restore generation of FindPNG.cmake by CMakeDeps & modernize more

- recipes/spdlog/all/conanfile.py
- recipes/spdlog/all/test_v1_package/CMakeLists.txt
closes https://github.com/conan-io/conan-center-index/issues/14198
---
> spdlog: fix build when fmt is header only

- .github/PULL_REQUEST_TEMPLATE.md
- docs/developing_recipes_locally.md
- docs/faqs.md
really, am I the first one to come across this?
---
> updated link in PR template

- recipes/units/all/conandata.yml
- recipes/units/config.yml
Specify library name and version:  **units/2.3.3**
---
> feat: Add units library version 2.3.3

- recipes/c4core/all/conanfile.py
> c4core: update fast_float/3.7.0

- recipes/qwt/all/conanfile.py
Specify library name and version:  **qwt/6.2.0**
Fixes #14217
---
> (#14217) qwt: Fix unresolvable conflict

- recipes/ulfius/all/conandata.yml
- recipes/ulfius/all/conanfile.py
- recipes/ulfius/all/patches/2.7.11-0001-shared-static-conan.patch
- recipes/ulfius/all/patches/2.7.11-0002-pthread-for-websockets-only.patch
- recipes/ulfius/all/test_package/CMakeLists.txt
- recipes/ulfius/all/test_package/conanfile.py
- recipes/ulfius/all/test_package/test_package.c
- recipes/ulfius/all/test_v1_package/CMakeLists.txt
- recipes/ulfius/all/test_v1_package/conanfile.py
- recipes/ulfius/config.yml
Specify library name and version:  **ulfius/2.7.11**
Depends on #13589
Depends on #13614
The patch is sent upstream: https://github.com/babelouest/ulfius/pull/242
---
> ulfius: add ulfius/2.7.11 recipe

- recipes/xqilla/all/conandata.yml
- recipes/xqilla/all/conanfile.py
- recipes/xqilla/all/patches/0001-honor-deps-ldflags.patch
- recipes/xqilla/all/test_package/CMakeLists.txt
- recipes/xqilla/all/test_package/conanfile.py
- recipes/xqilla/all/test_v1_package/CMakeLists.txt
- recipes/xqilla/all/test_v1_package/conanfile.py
> xqilla: conan v2 support

- recipes/xapian-core/all/conanfile.py
> [xapian-core] Update Dependencies

- recipes/libconfuse/all/conandata.yml
- recipes/libconfuse/all/conanfile.py
- recipes/libconfuse/all/test_package/CMakeLists.txt
- recipes/libconfuse/all/test_package/conanfile.py
- recipes/libconfuse/all/test_v1_package/CMakeLists.txt
- recipes/libconfuse/all/test_v1_package/conanfile.py
- recipes/libconfuse/config.yml
> libconfuse: conan v2 support

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.40.0**
---
> sqlite3: add version 3.40.0, remove older versions

- recipes/libev/all/conanfile.py
- recipes/libev/all/test_package/CMakeLists.txt
- recipes/libev/all/test_package/conanfile.py
- recipes/libev/all/test_v1_package/CMakeLists.txt
- recipes/libev/all/test_v1_package/conanfile.py
> libev: conan v2 support

- recipes/libunistring/all/conanfile.py
- recipes/libunistring/all/test_package/CMakeLists.txt
- recipes/libunistring/all/test_package/conanfile.py
- recipes/libunistring/all/test_v1_package/CMakeLists.txt
- recipes/libunistring/all/test_v1_package/conanfile.py
> libunistring: conan v2 support

- recipes/univalue/all/conandata.yml
- recipes/univalue/all/conanfile.py
- recipes/univalue/all/test_package/CMakeLists.txt
- recipes/univalue/all/test_package/conanfile.py
- recipes/univalue/all/test_package/test_package.cpp
- recipes/univalue/all/test_v1_package/CMakeLists.txt
- recipes/univalue/all/test_v1_package/conanfile.py
> univalue: conan v2 support

- recipes/cppunit/all/conanfile.py
- recipes/cppunit/all/test_package/CMakeLists.txt
- recipes/cppunit/all/test_package/conanfile.py
- recipes/cppunit/all/test_v1_package/CMakeLists.txt
- recipes/cppunit/all/test_v1_package/conanfile.py
> cppunit: conan v2 support

- recipes/libiconv/all/conanfile.py
- recipes/libiconv/all/test_v1_package/CMakeLists.txt
closes https://github.com/conan-io/conan-center-index/issues/3071
---
> libiconv: fix msvc if CC & LD set in profile + modernize more

- recipes/libfuse/2.x.x/conanfile.py
- recipes/libfuse/2.x.x/test_package/CMakeLists.txt
- recipes/libfuse/2.x.x/test_package/conanfile.py
- recipes/libfuse/2.x.x/test_v1_package/CMakeLists.txt
- recipes/libfuse/2.x.x/test_v1_package/conanfile.py
- recipes/libfuse/all/conanfile.py
- recipes/libfuse/all/test_package/CMakeLists.txt
- recipes/libfuse/all/test_package/conanfile.py
- recipes/libfuse/all/test_v1_package/CMakeLists.txt
- recipes/libfuse/all/test_v1_package/conanfile.py
> libfuse: conan v2 support

- recipes/hash-library/all/CMakeLists.txt
- recipes/hash-library/all/conandata.yml
- recipes/hash-library/all/conanfile.py
- recipes/hash-library/all/test_package/CMakeLists.txt
- recipes/hash-library/all/test_v1_package/CMakeLists.txt
- allow shared on windows
- add layout
- do not reconfigure during installation
- protect deletion of fPIC option
---
> hash-library: allow shared on Windows & few fixes

- recipes/aaplus/all/conanfile.py
- recipes/aaplus/all/test_package/CMakeLists.txt
- recipes/aaplus/all/test_package/conanfile.py
- recipes/aaplus/all/test_v1_package/CMakeLists.txt
- recipes/aaplus/all/test_v1_package/conanfile.py
> aaplus: modernize more

- recipes/icu/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/14205
---
> icu: fix cross build with Visual Studio

- recipes/arrow/all/conanfile.py
> arrow: fix a typo

- recipes/s2n/all/conanfile.py
Specify library name and version:  **s2n/***
---
> s2n: bump openssl

- recipes/gsl/all/conandata.yml
- recipes/gsl/all/conanfile.py
- recipes/gsl/all/test_package/CMakeLists.txt
- recipes/gsl/all/test_package/conanfile.py
- recipes/gsl/all/test_v1_package/CMakeLists.txt
- recipes/gsl/all/test_v1_package/conanfile.py
> gsl: conan v2 support

- recipes/libxcrypt/all/conandata.yml
- recipes/libxcrypt/all/conanfile.py
- recipes/libxcrypt/all/test_package/CMakeLists.txt
- recipes/libxcrypt/all/test_package/conanfile.py
- recipes/libxcrypt/all/test_v1_package/CMakeLists.txt
- recipes/libxcrypt/all/test_v1_package/conanfile.py
> libxcrypt: conan v2 support

- recipes/libsmacker/all/conandata.yml
- recipes/libsmacker/all/conanfile.py
- recipes/libsmacker/all/test_package/CMakeLists.txt
- recipes/libsmacker/all/test_package/conanfile.py
- recipes/libsmacker/all/test_v1_package/CMakeLists.txt
- recipes/libsmacker/all/test_v1_package/conanfile.py
> libsmacker: conan v2 support

- recipes/gzip-hpp/all/conandata.yml
- recipes/gzip-hpp/all/conanfile.py
- recipes/gzip-hpp/all/test_package/CMakeLists.txt
- recipes/gzip-hpp/all/test_package/conanfile.py
- recipes/gzip-hpp/all/test_package/test_package.cpp
- recipes/gzip-hpp/all/test_v1_package/CMakeLists.txt
- recipes/gzip-hpp/all/test_v1_package/conanfile.py
- recipes/gzip-hpp/config.yml
Specify library name and version:  **gzip-hpp/0.1.0**
Try to solve https://github.com/conan-io/conan-center-index/issues/14116.
---
> gzip-hpp: add recipe

- recipes/libevent/all/conanfile.py
Specify library name and version:  **libevent/**
---
From #14226
> libevent: Update dependencies

- recipes/harfbuzz/all/conanfile.py
Specify library name and version:  **harfbuzz/***
fixes https://github.com/conan-io/conan-center-index/issues/14258
---
> harfbuzz: disable gobject with glib

- recipes/trantor/all/conanfile.py
> trantor: update openssl

- recipes/drogon/all/conanfile.py
> drogon: update dependencies

- recipes/cpprestsdk/all/conandata.yml
- recipes/cpprestsdk/all/conanfile.py
- recipes/cpprestsdk/all/test_v1_package/CMakeLists.txt
- recipes/cpprestsdk/config.yml
see https://github.com/conan-io/conan-center-index/pull/13962#discussion_r1024410687
---
> cpprestsdk: honor shared=False

- recipes/libusb/all/conanfile.py
> libusb: fix pkgconfig name in PkgConfigDeps generator + relocatable shared lib on macOS

- recipes/diligent-fx/all/conandata.yml
- recipes/diligent-fx/all/conanfile.py
- recipes/diligent-fx/config.yml
Specify library name and version:  **diligent/api.252009**
---
> add new versions for diligent-fx

- recipes/dice-template-library/all/conandata.yml
- recipes/dice-template-library/config.yml
Specify library name and version:  dice-template-library/0.3.0
---
> bump version: dice-template-library/0.3.0

- recipes/cppfront/all/CMakeLists.txt
- recipes/cppfront/all/conandata.yml
- recipes/cppfront/all/conanfile.py
- recipes/cppfront/all/test_package/conanfile.py
- recipes/cppfront/all/test_package/pure2-hello.cpp2
- recipes/cppfront/all/test_v1_package/conanfile.py
- recipes/cppfront/config.yml
Specify library name and version:  **cppfront/master**
---
> [cppfront] new cppfront recipe (2nd attempt)

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/0.64.1**
---
> meson 0.64.1

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/all/test_package/CMakeLists.txt
- recipes/daw_header_libraries/all/test_v1_package/CMakeLists.txt
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.76.2**
---
> daw_header_libraries: add version 2.76.2, remove older versions

- recipes/swig/all/conandata.yml
- recipes/swig/all/conanfile.py
- recipes/swig/all/patches/0001-4.1.0-swig-linux-library-path.patch
- recipes/swig/all/patches/0002-4.1.0-do-not-define-SWIG_LIB_WIN_UNIX.patch
- recipes/swig/config.yml
Specify library name and version:  **swig/4.1.0**
* Fix #13741
* Add recipe for SWIG 4.1.0
* Note: The 0001 patch fails for 4.1.0, so make a specific one.
---
> Bump swig/4.1.0

- recipes/sdl/all/conandata.yml
- recipes/sdl/config.yml
Specify library name and version:  **sdl/2.26.0**
---
> sdl: add version 2.26.0

- recipes/winmd/all/conandata.yml
- recipes/winmd/all/conanfile.py
- recipes/winmd/all/test_package/CMakeLists.txt
- recipes/winmd/all/test_package/conanfile.py
- recipes/winmd/all/test_package/test_package.cpp
- recipes/winmd/all/test_v1_package/CMakeLists.txt
- recipes/winmd/all/test_v1_package/conanfile.py
- recipes/winmd/config.yml
Specify library name and version:  **winmd/1.0.210629.2**
Dependency of [cppwinrt](https://github.com/microsoft/cppwinrt)
---
> add winmd 1.0.210629.2

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/all/conanfile.py
- recipes/daw_json_link/all/test_v1_package/CMakeLists.txt
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.8.1**
- add version 3.8.1
- remove _info hacks
- update daw_header_libraries
---
> daw_json_link: add version 3.8.1, update dependencies

- recipes/binutils/all/conandata.yml
- recipes/binutils/all/conanfile.py
* Bump to zlib/1.2.13 to support #13896
Specify library name and version:  **binutils/2.38**
---
> [binutils] Bump zlib version

- recipes/quazip/all/CMakeLists.txt
- recipes/quazip/all/conandata.yml
- recipes/quazip/all/conanfile.py
- recipes/quazip/all/test_package/CMakeLists.txt
- recipes/quazip/all/test_package/conanfile.py
- recipes/quazip/all/test_v1_package/CMakeLists.txt
- recipes/quazip/all/test_v1_package/conanfile.py
> [quazip] conan v2 migration

- recipes/libgettext/all/conandata.yml
- recipes/libgettext/all/conanfile.py
- recipes/libgettext/all/test_package/CMakeLists.txt
- recipes/libgettext/all/test_package/conanfile.py
- recipes/libgettext/all/test_v1_package/CMakeLists.txt
- recipes/libgettext/all/test_v1_package/conanfile.py
Specify library name and version:  **libgettext**
Update libgettext to the v2 autotools toolchain
---
> [libgettext] update to v2 toolchains

- recipes/duckdb/all/conandata.yml
- recipes/duckdb/all/conanfile.py
- recipes/duckdb/all/patches/0.6.0-0001-fix-cmake.patch
- recipes/duckdb/all/patches/0.6.0-0002-include-stdlib.patch
- recipes/duckdb/config.yml
Specify library name and version:  **duckdb/0.6.0**
---
> duckdb: add version 0.6.0

- recipes/libiconv/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/14279
---
> libiconv: fix cross-build with msvc

- recipes/protobuf/all/conandata.yml
- recipes/protobuf/config.yml
Specify library name and version:  **protobuf/3.21.9**
Update to latest protobuf release
---
> [protobuf] Add protobuf 3.21.9

- recipes/pfr/all/conandata.yml
- recipes/pfr/all/conanfile.py
- recipes/pfr/all/test_package/conanfile.py
- recipes/pfr/all/test_v1_package/CMakeLists.txt
- recipes/pfr/all/test_v1_package/conanfile.py
Specify library name and version:  **pfr**
---
> pfr: conan v2 migration

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.0.1**
---
> simdjson: add version 3.0.1

- recipes/scnlib/all/conanfile.py
Specify library name and version:  **scnlib/***
---
> scnlib: update fast_float

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/all/conanfile.py
- recipes/wasmtime/all/test_package/CMakeLists.txt
- recipes/wasmtime/all/test_v1_package/CMakeLists.txt
- recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/3.0.0**
- add version 3.0.0
- remove validation code for old versions
- remove version 0.34.0
---
> wasmtime: add version 3.0.0

- recipes/libnfs/all/CMakeLists.txt
- recipes/libnfs/all/conandata.yml
- recipes/libnfs/all/conanfile.py
- recipes/libnfs/all/test_package/CMakeLists.txt
- recipes/libnfs/all/test_package/conanfile.py
- recipes/libnfs/all/test_v1_package/CMakeLists.txt
- recipes/libnfs/all/test_v1_package/conanfile.py
> libnfs: conan v2 support

- recipes/jsoncpp/all/conanfile.py
- recipes/jsoncpp/all/test_package/conanfile.py
- recipes/jsoncpp/all/test_v1_package/CMakeLists.txt
closes https://github.com/conan-io/conan-center-index/issues/14386
---
> jsoncpp: disable ccache + modernize a little bit more

- recipes/hiredis/all/conandata.yml
- recipes/hiredis/all/conanfile.py
- recipes/hiredis/all/patches/0001-fix-cmake-1.1.0.patch
- recipes/hiredis/config.yml
Specify library name and version:  **hiredis/1.1.0**
- add version 1.1.0
- update openssl
---
> hiredis: add version 1.1.0, update dependencies

- recipes/foonathan-memory/all/conandata.yml
- recipes/foonathan-memory/all/conanfile.py
- recipes/foonathan-memory/all/test_v1_package/CMakeLists.txt
- recipes/foonathan-memory/config.yml
Specify library name and version:  **foonathan-memory/0.7.2**
---
> foonathan-memomry: add version 0.7.2

- recipes/libsystemd/all/conanfile.py
Specify library name and version:  **libsystemd/***
Closes: https://github.com/conan-io/conan-center-index/issues/14422
> libsystemd: Converting to strings the major versions

- recipes/harfbuzz/all/conanfile.py
Specify library name and version:  **harfbuzz**
---
> [harfbuzz] bump dependencies

- recipes/zstd/all/conandata.yml
- recipes/zstd/all/patches/1.5.0-remove-explicit-standard-setting.patch
Specify library name and version:  **zstd/1.5.0,1.5.1,1.5.2**
retry: https://github.com/conan-io/conan-center-index/pull/14389
zstd has an performance issue which has been released yet.
https://github.com/facebook/zstd/issues/3163
This PR will solve it.
---
> zstd: fix strange performance issue

- recipes/gdk-pixbuf/all/conandata.yml
- recipes/gdk-pixbuf/all/conanfile.py
- recipes/gdk-pixbuf/config.yml
Specify library name and version:  **gdk-pixbuf/2.42.10**
Bump version and dependencies
---
> [gdk-pixbuf] bump version and dependencies, add pkg-config content

- recipes/pybind11/all/conandata.yml
- recipes/pybind11/all/conanfile.py
- recipes/pybind11/config.yml
Specify library name and version:  **pybind11/2.10.1**
New version
---
> New pybind11 2.10.1

- recipes/khrplatform/all/conanfile.py
- recipes/khrplatform/all/test_package/CMakeLists.txt
- recipes/khrplatform/all/test_package/conanfile.py
- recipes/khrplatform/all/test_v1_package/CMakeLists.txt
- recipes/khrplatform/all/test_v1_package/conanfile.py
> khrplatform: conan v2 support

- recipes/libnuma/all/conandata.yml
- recipes/libnuma/all/conanfile.py
- recipes/libnuma/all/test_package/CMakeLists.txt
- recipes/libnuma/all/test_package/conanfile.py
- recipes/libnuma/all/test_v1_package/CMakeLists.txt
- recipes/libnuma/all/test_v1_package/conanfile.py
> libnuma: conan v2 support

- recipes/butteraugli/all/CMakeLists.txt
- recipes/butteraugli/all/conandata.yml
- recipes/butteraugli/all/conanfile.py
- recipes/butteraugli/all/test_package/CMakeLists.txt
- recipes/butteraugli/all/test_package/conanfile.py
- recipes/butteraugli/all/test_v1_package/CMakeLists.txt
- recipes/butteraugli/all/test_v1_package/conanfile.py
> butteraugli: conan v2 support

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/2.8.1**
---
> fast_float: add v2.8.1

- recipes/jpeg-compressor/all/CMakeLists.txt
- recipes/jpeg-compressor/all/conandata.yml
- recipes/jpeg-compressor/all/conanfile.py
- recipes/jpeg-compressor/all/test_package/CMakeLists.txt
- recipes/jpeg-compressor/all/test_package/conanfile.py
- recipes/jpeg-compressor/all/test_v1_package/CMakeLists.txt
- recipes/jpeg-compressor/all/test_v1_package/conanfile.py
> jpeg-compressor: conan v2 support

- recipes/cpp-lazy/all/conandata.yml
- recipes/cpp-lazy/all/conanfile.py
- recipes/cpp-lazy/all/patches/0001-support-gcc5.patch
- recipes/cpp-lazy/all/test_package/CMakeLists.txt
- recipes/cpp-lazy/all/test_package/conanfile.py
- recipes/cpp-lazy/all/test_package/test_package.cpp
- recipes/cpp-lazy/all/test_v1_package/CMakeLists.txt
- recipes/cpp-lazy/all/test_v1_package/conanfile.py
- recipes/cpp-lazy/config.yml
Specify library name and version:  **cpp-lazy/6.0.0**
---
> cpp-lazy: add recipe

- recipes/alpaca/all/conandata.yml
- recipes/alpaca/all/conanfile.py
- recipes/alpaca/all/test_package/CMakeLists.txt
- recipes/alpaca/all/test_package/conanfile.py
- recipes/alpaca/all/test_package/test_package.cpp
- recipes/alpaca/all/test_v1_package/CMakeLists.txt
- recipes/alpaca/all/test_v1_package/conanfile.py
- recipes/alpaca/config.yml
Specify library name and version:  **alpaca/0.2.1**
---
> alpaca: add recipe

- recipes/diligent-core/all/conanfile.py
- recipes/diligent-core/all/test_package/test_package.cpp
Specify library name and version:  **diligent-core/all**
---
> unify diligent dependencies diligent-core/all

- recipes/asmjit/all/conandata.yml
- recipes/asmjit/all/conanfile.py
- recipes/asmjit/all/test_v1_package/CMakeLists.txt
- recipes/asmjit/all/test_v1_package/conanfile.py
- recipes/asmjit/config.yml
Specify library name and version:  **asmjit/20221111**
---
> asmjit: add version cci.20221111

- recipes/qpoases/all/CMakeLists.txt
- recipes/qpoases/all/conanfile.py
- recipes/qpoases/all/test_package/CMakeLists.txt
- recipes/qpoases/all/test_package/conanfile.py
- recipes/qpoases/all/test_v1_package/CMakeLists.txt
- recipes/qpoases/all/test_v1_package/conanfile.py
> qpoases: conan v2 support

- recipes/xtensor/all/conandata.yml
- recipes/xtensor/all/conanfile.py
- recipes/xtensor/all/test_package/CMakeLists.txt
- recipes/xtensor/all/test_package/conanfile.py
- recipes/xtensor/all/test_v1_package/CMakeLists.txt
- recipes/xtensor/all/test_v1_package/conanfile.py
> xtensor: conan v2 support

- recipes/taocpp-tuple/all/conanfile.py
- recipes/taocpp-tuple/all/test_package/CMakeLists.txt
- recipes/taocpp-tuple/all/test_package/conanfile.py
- recipes/taocpp-tuple/all/test_v1_package/CMakeLists.txt
- recipes/taocpp-tuple/all/test_v1_package/conanfile.py
> taocpp-tuple: conan v2 support

- recipes/taocpp-sequences/all/conanfile.py
- recipes/taocpp-sequences/all/test_package/CMakeLists.txt
- recipes/taocpp-sequences/all/test_package/conanfile.py
- recipes/taocpp-sequences/all/test_v1_package/CMakeLists.txt
- recipes/taocpp-sequences/all/test_v1_package/conanfile.py
> taocpp-sequences: conan v2 support

- recipes/taocpp-operators/all/conanfile.py
- recipes/taocpp-operators/all/test_package/CMakeLists.txt
- recipes/taocpp-operators/all/test_package/conanfile.py
- recipes/taocpp-operators/all/test_v1_package/CMakeLists.txt
- recipes/taocpp-operators/all/test_v1_package/conanfile.py
> taocpp-operators: conan v2 support

- recipes/nvtx/all/conanfile.py
- recipes/nvtx/all/test_package/CMakeLists.txt
- recipes/nvtx/all/test_package/conanfile.py
- recipes/nvtx/all/test_v1_package/CMakeLists.txt
- recipes/nvtx/all/test_v1_package/conanfile.py
> nvtx: conan v2 support

- recipes/libgcrypt/all/conanfile.py
- recipes/libgcrypt/all/test_package/CMakeLists.txt
- recipes/libgcrypt/all/test_package/conanfile.py
- recipes/libgcrypt/all/test_v1_package/CMakeLists.txt
- recipes/libgcrypt/all/test_v1_package/conanfile.py
> libgcrypt: conan v2 support

- recipes/vulkan-loader/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/14421
---
> vulkan-loader: no warnings as errors

- recipes/gumbo-parser/all/conandata.yml
- recipes/gumbo-parser/all/conanfile.py
- recipes/gumbo-parser/all/test_package/CMakeLists.txt
- recipes/gumbo-parser/all/test_package/conanfile.py
- recipes/gumbo-parser/all/test_v1_package/CMakeLists.txt
- recipes/gumbo-parser/all/test_v1_package/conanfile.py
> gumbo-parser: conan v2 support

- recipes/jthread-lite/all/conanfile.py
- recipes/jthread-lite/all/test_package/CMakeLists.txt
- recipes/jthread-lite/all/test_package/conanfile.py
- recipes/jthread-lite/all/test_v1_package/CMakeLists.txt
- recipes/jthread-lite/all/test_v1_package/conanfile.py
> jthread-lite: conan v2 support

- recipes/libnet/all/conanfile.py
- recipes/libnet/all/test_package/CMakeLists.txt
- recipes/libnet/all/test_package/conanfile.py
- recipes/libnet/all/test_v1_package/CMakeLists.txt
- recipes/libnet/all/test_v1_package/conanfile.py
> libnet: conan v2 support

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.10.0**
---
> daw_json_link: add version 3.10.0

- recipes/luple/all/conanfile.py
- recipes/luple/all/test_package/CMakeLists.txt
- recipes/luple/all/test_package/conanfile.py
- recipes/luple/all/test_v1_package/CMakeLists.txt
- recipes/luple/all/test_v1_package/conanfile.py
> luple: conan v2 support

- recipes/md4qt/all/conandata.yml
- recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.0.1**
---
I'm the author of the library.
> md4qt: bump version to 2.0.1.

- recipes/blend2d/all/conanfile.py
Specify library name and version:  **blend2d/***
---
> blend2d: update asmjit

- recipes/libdisasm/all/conandata.yml
- recipes/libdisasm/all/conanfile.py
- recipes/libdisasm/all/test_package/CMakeLists.txt
- recipes/libdisasm/all/test_package/conanfile.py
- recipes/libdisasm/all/test_v1_package/CMakeLists.txt
- recipes/libdisasm/all/test_v1_package/conanfile.py
> libdisasm: conan v2 support

- recipes/wasmer/all/conandata.yml
- recipes/wasmer/all/conanfile.py
- recipes/wasmer/all/test_package/CMakeLists.txt
- recipes/wasmer/all/test_package/conanfile.py
- recipes/wasmer/all/test_v1_package/CMakeLists.txt
- recipes/wasmer/all/test_v1_package/conanfile.py
- recipes/wasmer/config.yml
Specify library name and version:  **wasmer/***
---
> wasmer: add version 3.0.2 suppport conan v2

- recipes/ode/all/conandata.yml
- recipes/ode/all/conanfile.py
- recipes/ode/all/patches/0001-fix-apple.patch
- recipes/ode/all/patches/0002-dont-force-pic.patch
- recipes/ode/all/patches/0003-cmake-fix-ccd-target.patch
- recipes/ode/all/patches/0004-fix-include-ode-timer.patch
- recipes/ode/all/test_package/CMakeLists.txt
- recipes/ode/all/test_package/conanfile.py
- recipes/ode/all/test_package/test_package.c
- recipes/ode/all/test_v1_package/CMakeLists.txt
- recipes/ode/all/test_v1_package/conanfile.py
- recipes/ode/config.yml
closes https://github.com/conan-io/conan-center-index/issues/14433
---
> add ode/0.16.2

- recipes/xsimd/all/conandata.yml
- recipes/xsimd/config.yml
Specify library name and version:  **xsimd/10.0.0**
---
> xsimd: add version 10.0.0

- recipes/v-hacd/all/conandata.yml
- recipes/v-hacd/all/conanfile.py
- recipes/v-hacd/all/test_package/CMakeLists.txt
- recipes/v-hacd/all/test_package/conanfile.py
- recipes/v-hacd/all/test_package/test_package.cpp
- recipes/v-hacd/all/test_v1_package/CMakeLists.txt
- recipes/v-hacd/all/test_v1_package/conanfile.py
- recipes/v-hacd/config.yml
closes https://github.com/conan-io/conan-center-index/issues/3804
---
> add v-hacd/4.1.0

- recipes/m4/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/14508
---
> m4: fix msvc build in conan 1.55.0

- recipes/jwt-cpp/all/conanfile.py
> [jwt-cpp] Bump openssl

- recipes/quantlib/all/CMakeLists.txt
- recipes/quantlib/all/conandata.yml
- recipes/quantlib/all/conanfile.py
- recipes/quantlib/all/test_package/CMakeLists.txt
- recipes/quantlib/all/test_package/conanfile.py
- recipes/quantlib/all/test_v1_package/CMakeLists.txt
- recipes/quantlib/all/test_v1_package/conanfile.py
> quantlib: conan v2 support

- recipes/freetype/all/conanfile.py
Required by https://github.com/conan-io/conan-center-index/pull/13943
---
> [freetype] Bump libpng version

- recipes/fontconfig/meson/conanfile.py
Update expat version
Only updated meson folder to be classified as bump dependencies and merge it asap.
---
> [fontconfig] Bump expat version

- recipes/openfbx/all/CMakeLists.txt
- recipes/openfbx/all/conanfile.py
- recipes/openfbx/all/test_package/CMakeLists.txt
- recipes/openfbx/all/test_package/conanfile.py
- recipes/openfbx/all/test_v1_package/CMakeLists.txt
- recipes/openfbx/all/test_v1_package/conanfile.py
> openfbx: conan v2 support

- recipes/wayland/all/conanfile.py
> wayland: bump reqs

- recipes/metall/all/conandata.yml
- recipes/metall/all/test_v1_package/conanfile.py
- recipes/metall/config.yml
Specify library name and version:  **metall/0.23.1**
Update to latest version.
---
> bump version: metall v0.23.1

- recipes/json-schema-validator/all/conandata.yml
- recipes/json-schema-validator/all/conanfile.py
- recipes/json-schema-validator/config.yml
Specify library name and version:  **json-schema-validator/2.2.0**
---
> json-schema-validator: add version 2.2.0

- recipes/sdl_ttf/all/CMakeLists.txt
- recipes/sdl_ttf/all/conandata.yml
- recipes/sdl_ttf/all/conanfile.py
- recipes/sdl_ttf/all/test_package/CMakeLists.txt
- recipes/sdl_ttf/all/test_package/conanfile.py
- recipes/sdl_ttf/all/test_v1_package/CMakeLists.txt
- recipes/sdl_ttf/all/test_v1_package/conanfile.py
> sdl_ttf: conan v2 support

- recipes/sdl_net/all/CMakeLists.txt
- recipes/sdl_net/all/conanfile.py
- recipes/sdl_net/all/test_package/CMakeLists.txt
- recipes/sdl_net/all/test_package/conanfile.py
- recipes/sdl_net/all/test_v1_package/CMakeLists.txt
- recipes/sdl_net/all/test_v1_package/conanfile.py
> sdl_net: conan v2 support

- recipes/libalsa/all/conanfile.py
Use rm_safe functions in the configure method.
Specify library name and version:  **libalsa/***
---
> libalsa: Update SPDX license identifier

- recipes/xkbcommon/all/conanfile.py
> xkbcommon: bump reqs

- recipes/imgui/all/CMakeLists.txt
- recipes/imgui/all/conandata.yml
- recipes/imgui/all/conanfile.py
- recipes/imgui/all/test_package/CMakeLists.txt
- recipes/imgui/all/test_package/conanfile.py
- recipes/imgui/all/test_v1_package/CMakeLists.txt
- recipes/imgui/all/test_v1_package/conanfile.py
- recipes/imgui/config.yml
> imgui: add version 1.89.1, support conan v2

- recipes/md4qt/all/conandata.yml
- recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.0.3**
---
> md4qt: bump version to 2.0.3.

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json/link/3.11.1**
---
> daw_json_link: add version 3.11.1

- recipes/entt/3.x.x/conandata.yml
- recipes/entt/config.yml
> Bump entt/3.11.1

- recipes/reactiveplusplus/all/conandata.yml
- recipes/reactiveplusplus/config.yml
> Bump reactiveplusplus/0.2.1

- recipes/muparser/all/conandata.yml
- recipes/muparser/all/conanfile.py
- recipes/muparser/config.yml
> Bump muparser/2.3.4

- recipes/glibmm/all/conanfile.py
Specify library name and version:  **glibmm/***
---
> glibmm: bump reqs

- .c3i/authorized_users.yml
- .c3i/reviewers.yml
/cc @RubenRBS Welcome to the Team
---
> [config] Add Ruben as reviewer

- recipes/abseil/all/conandata.yml
- recipes/abseil/all/test_v1_package/conanfile.py
- recipes/abseil/config.yml
Specify library name and version:  **abseil/20220623.1**
Update existing package to latest released version
---
> [abseil] Add latest 20220623.1 release

- recipes/libhydrogen/all/conandata.yml
- recipes/libhydrogen/all/conanfile.py
- recipes/libhydrogen/all/patches/0001-fix-cmake.patch
- recipes/libhydrogen/all/test_package/CMakeLists.txt
- recipes/libhydrogen/all/test_package/conanfile.py
- recipes/libhydrogen/all/test_package/test_package.c
- recipes/libhydrogen/all/test_v1_package/CMakeLists.txt
- recipes/libhydrogen/all/test_v1_package/conanfile.py
- recipes/libhydrogen/config.yml
> add libhydrogen/cci.20221115

- recipes/emsdk/all/conanfile.py
> emsdk: define `tools.build:compiler_executables` config

- recipes/libselinux/all/conanfile.py
> libselinux: Use rm_safe from Conan 1.53.0

- recipes/zpp_bits/all/conandata.yml
- recipes/zpp_bits/config.yml
Specify library name and version:  **zpp_bits/4.4.12**
---
> zpp_bits: add version 4.4.12

- recipes/soundtouch/all/conandata.yml
- recipes/soundtouch/all/conanfile.py
- recipes/soundtouch/all/test_package/CMakeLists.txt
- recipes/soundtouch/all/test_package/conanfile.py
- recipes/soundtouch/all/test_package/test_package.cpp
- recipes/soundtouch/all/test_v1_package/CMakeLists.txt
- recipes/soundtouch/all/test_v1_package/conanfile.py
- recipes/soundtouch/config.yml
Specify library name and version:  **soundtouch/2.3.2**
Try to close https://github.com/conan-io/conan-center-index/issues/14201.
---
> soundtouch: add recipe

- recipes/rply/all/CMakeLists.txt
- recipes/rply/all/conandata.yml
- recipes/rply/all/conanfile.py
- recipes/rply/all/test_package/CMakeLists.txt
- recipes/rply/all/test_package/conanfile.py
- recipes/rply/all/test_package/test_package.c
- recipes/rply/all/test_package/triangle.ply
- recipes/rply/all/test_v1_package/CMakeLists.txt
- recipes/rply/all/test_v1_package/conanfile.py
- recipes/rply/config.yml
> add rply/1.1.4

- recipes/linmath.h/all/conandata.yml
- recipes/linmath.h/all/conanfile.py
- recipes/linmath.h/all/test_package/CMakeLists.txt
- recipes/linmath.h/all/test_package/conanfile.py
- recipes/linmath.h/all/test_package/test_package.c
- recipes/linmath.h/all/test_v1_package/CMakeLists.txt
- recipes/linmath.h/all/test_v1_package/conanfile.py
- recipes/linmath.h/config.yml
> add linmath.h/cci.20220619

- recipes/re2/all/conandata.yml
- recipes/re2/all/conanfile.py
- recipes/re2/all/test_package/conanfile.py
- recipes/re2/all/test_v1_package/CMakeLists.txt
- recipes/re2/all/test_v1_package/conanfile.py
- recipes/re2/config.yml
> re2: add 20221201 + modernize more

- recipes/safeint/all/conandata.yml
- recipes/safeint/all/conanfile.py
- recipes/safeint/all/test_package/conanfile.py
- recipes/safeint/all/test_v1_package/CMakeLists.txt
- recipes/safeint/config.yml
> Bump safeint/3.0.27

- recipes/hlslpp/all/conandata.yml
- recipes/hlslpp/all/conanfile.py
- recipes/hlslpp/all/test_package/conanfile.py
- recipes/hlslpp/all/test_v1_package/CMakeLists.txt
- recipes/hlslpp/config.yml
> Bump hlslpp/3.2.2

- recipes/libtar/all/conanfile.py
- recipes/libtar/all/test_v1_package/CMakeLists.txt
> libtar: bump zlib & modernize more

- recipes/glib/all/conanfile.py
> glib: Use rm_safe from Conan 1.53 and update topics and description

- recipes/wayland/all/conanfile.py
- recipes/wayland/all/test_package/CMakeLists.txt
- recipes/wayland/all/test_package/conanfile.py
- recipes/wayland/all/test_v1_package/CMakeLists.txt
Simplify v1 test package.
Update Meson version.
Fix cmake_layout import.
---
> wayland: Use rm_safe from Conan 1.53.0

- recipes/libaio/all/conandata.yml
- recipes/libaio/all/conanfile.py
- recipes/libaio/all/test_package/CMakeLists.txt
- recipes/libaio/all/test_package/conanfile.py
- recipes/libaio/all/test_package/test_package.c
- recipes/libaio/all/test_v1_package/CMakeLists.txt
- recipes/libaio/all/test_v1_package/conanfile.py
- recipes/libaio/config.yml
Specify library name and version:  **libaio/0.3.113**
---
> libaio: add recipe

- recipes/jwt-cpp/all/conanfile.py
> jwt-cpp: touch ups for 2.0 migration

- recipes/itlib/all/conandata.yml
- recipes/itlib/all/conanfile.py
- recipes/itlib/all/test_package/CMakeLists.txt
- recipes/itlib/all/test_v1_package/CMakeLists.txt
- recipes/itlib/config.yml
Specify library name and version:  **itlib/***
- add version
- use test_package's CMakeLists.txt in test_v1_package
---
> itlib: add version 1.7.0, small improvement

- recipes/yaml-cpp/all/conanfile.py
> yaml-cpp: Use rm_safe from Conan 1.53

- recipes/pcre2/all/conandata.yml
- recipes/pcre2/all/conanfile.py
- recipes/pcre2/all/test_package/conanfile.py
- recipes/pcre2/all/test_v1_package/CMakeLists.txt
- recipes/pcre2/config.yml
> pcre2: add 10.42 + modernize more for conan v2

- recipes/libspng/all/conandata.yml
- recipes/libspng/all/conanfile.py
- recipes/libspng/all/patches/0.7.3-0001-fix-dll-install.patch
- recipes/libspng/all/patches/0.7.3-0002-allow-miniz.patch
- recipes/libspng/config.yml
Specify library name and version:  **libspng/0.7.3**
---
> libspng: add version 0.7.3

- recipes/yyjson/all/conandata.yml
- recipes/yyjson/all/conanfile.py
- recipes/yyjson/all/test_v1_package/CMakeLists.txt
- recipes/yyjson/all/test_v1_package/conanfile.py
- recipes/yyjson/config.yml
Specify library name and version:  **yyjson/0.7.0**
---
> yyjson: add version 0.6.0

- recipes/bitserializer/all/conanfile.py
- recipes/bitserializer/all/test_package/CMakeLists.txt
- recipes/bitserializer/all/test_package/conanfile.py
- recipes/bitserializer/all/test_v1_package/CMakeLists.txt
- recipes/bitserializer/all/test_v1_package/conanfile.py
> bitserializer: conan v2 support

- .github/PULL_REQUEST_TEMPLATE.md
Most of the PRs leave the text suggesting to add more context intact, which creates some noise for maintenance PRs that don't even fill it.
This just hides the text in the final PR message, so that it's easier to read, but keeps it readable for anyone writing the PR message
---
> (docs) Improve PR template experience

- recipes/brynet/all/conandata.yml
- recipes/brynet/all/conanfile.py
- recipes/brynet/all/test_package/CMakeLists.txt
- recipes/brynet/all/test_package/test_package.cpp
- recipes/brynet/all/test_v1_package/CMakeLists.txt
- recipes/brynet/config.yml
Specify library name and version:  **brynet/***
---
> brynet: add version 1.12.1, update openssl

- recipes/wasmer/all/conandata.yml
- recipes/wasmer/config.yml
Specify library name and version:  **wasmer/3.1.0**
---
> wasmer: add version 3.1.0

- recipes/libtiff/all/conanfile.py
- recipes/libtiff/all/patches/4.2.0-0001-cmake-dependencies.patch
- recipes/libtiff/all/patches/4.3.0-0001-cmake-dependencies.patch
- recipes/libtiff/all/patches/4.4.0-0001-cmake-dependencies.patch
> libtiff: bump libdeflate

- recipes/glaze/all/conandata.yml
- recipes/glaze/all/conanfile.py
- recipes/glaze/config.yml
> glaze: add version 0.2.0

- recipes/taskflow/all/conandata.yml
- recipes/taskflow/all/conanfile.py
- recipes/taskflow/all/test_package/CMakeLists.txt
- recipes/taskflow/all/test_package/conanfile.py
- recipes/taskflow/all/test_v1_package/CMakeLists.txt
- recipes/taskflow/all/test_v1_package/conanfile.py
> taskflow: conan v2 support

- recipes/vulkan-headers/all/conandata.yml
- recipes/vulkan-headers/config.yml
> Bump vulkan-headers/1.3.236.0

- recipes/spirv-headers/all/conandata.yml
- recipes/spirv-headers/config.yml
> Bump spirv-headers/1.3.236.0

- recipes/tuplet/all/conandata.yml
- recipes/tuplet/all/conanfile.py
- recipes/tuplet/all/test_v1_package/CMakeLists.txt
- recipes/tuplet/all/test_v1_package/conanfile.py
- recipes/tuplet/config.yml
Specify library name and version:  **tuplet/***
- add version 2.0.0
- use check_min_vs
- remove skip pylint
- use add_subdirectory in test_v1_package 
---
> tuplet: add version 2.0.0

- recipes/libuuid/all/conanfile.py
- recipes/libuuid/all/test_v1_package/CMakeLists.txt
Refine topics.
Use self.ref in error message in validate method.
---
> libuuid: Use rm_safe from Conan 1.53 and simplify v1 test package

- recipes/flecs/all/conandata.yml
- recipes/flecs/config.yml
> Bump flecs/3.1.2

- recipes/wavelet_buffer/all/conandata.yml
- recipes/wavelet_buffer/config.yml
Specify library name and version:  **wavelet_buffer/0.5.0**
---
> wavelet_buffer: add version 0.5.0

- recipes/jungle/all/conandata.yml
- recipes/jungle/all/patches/0004-cmake-alterations-cci.20221201.patch
- recipes/jungle/config.yml
Specify library name and version:  **jungle/cci.20221201**
A general update capturing upstream fixes/enhancements.
---
> Update to jungle/cci.20221201

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/0.2.1**
---
> glaze: add version 0.2.1

- recipes/spirv-tools/all/conandata.yml
- recipes/spirv-tools/all/dependencies/dependencies-1.3.236.0.yml
- recipes/spirv-tools/config.yml
> Bump spirv-tools/1.3.236.0

- docs/changelog.md
Few changes this time 😄
Looking forward to having Conan v2 pipeline feedback reported in PRs soon!!
> [docs] Update changelog 15-December-2022

- recipes/qwt/all/conanfile.py
> qwt: hack to avoid qt in build requirements for native build

- recipes/poppler-data/all/CMakeLists.txt
- recipes/poppler-data/all/conandata.yml
- recipes/poppler-data/all/conanfile.py
- recipes/poppler-data/all/test_package/conanfile.py
- recipes/poppler-data/all/test_v1_package/conanfile.py
> poppler-data: conan v2 support

- recipes/websocketpp/all/conanfile.py
- recipes/websocketpp/all/test_package/CMakeLists.txt
- recipes/websocketpp/all/test_v1_package/CMakeLists.txt
- use self.info.clear()
- add a layout
- transitive headers / libs
- fine-grained propagation of dependencies (avoid to propagate all boost libs, header only is sufficient)
---
> websocketpp: more conan v2 stuff

- recipes/volk/all/conandata.yml
- recipes/volk/config.yml
> Bump volk/1.3.236.0

- recipes/fakeit/all/conandata.yml
- recipes/fakeit/config.yml
Specify library name and version:  **fakeit/2.3.1**
---
> fakeit: add version 2.3.1

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.79.0**
---
> daw_header_libraries: add version 2.79.0

- recipes/harfbuzz/all/conandata.yml
- recipes/harfbuzz/config.yml
Specify library name and version:  **harfbuzz/6.0.0**
---
> harfbuzz: add version 6.0.0

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.12.0**
---
> daw_json_link: add version 3.12.0

- recipes/fakeit/all/conandata.yml
- recipes/fakeit/config.yml
Specify library name and version:  **fakeit/2.3.2**
---
> fakeit: add version 2.3.2

- recipes/netcdf/all/conanfile.py
> netcdf - bump libcurl dep version

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/all/conanfile.py
- recipes/unordered_dense/all/test_package/CMakeLists.txt
- recipes/unordered_dense/all/test_v1_package/CMakeLists.txt
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/***
- add version 3.0.0
- remove wrong `pkg_config_name`
- simplify test_v1_package/CMakeLists.txt
---
> unordered_dense: add version 3.0.0, improve recipe

- recipes/spirv-cross/all/conandata.yml
- recipes/spirv-cross/all/patches/1.3.236.0-0001-fix-gcc5.patch
- recipes/spirv-cross/config.yml
> Bump spirv-cross/1.3.236.0

- recipes/libpcap/all/CMakeLists.txt
- recipes/libpcap/all/conanfile.py
- recipes/libpcap/all/test_package/CMakeLists.txt
- recipes/libpcap/all/test_package/conanfile.py
- recipes/libpcap/all/test_v1_package/CMakeLists.txt
- recipes/libpcap/all/test_v1_package/conanfile.py
> libpcap: conan v2 support

- recipes/libiberty/all/conandata.yml
- recipes/libiberty/all/conanfile.py
- recipes/libiberty/all/test_package/CMakeLists.txt
- recipes/libiberty/all/test_package/conanfile.py
- recipes/libiberty/all/test_v1_package/CMakeLists.txt
- recipes/libiberty/all/test_v1_package/conanfile.py
> libiberty: conan v2 support

- recipes/threadpool/all/conandata.yml
- recipes/threadpool/all/conanfile.py
- recipes/threadpool/all/test_package/CMakeLists.txt
- recipes/threadpool/all/test_package/conanfile.py
- recipes/threadpool/all/test_package/test_package.cpp
- recipes/threadpool/all/test_v1_package/CMakeLists.txt
- recipes/threadpool/all/test_v1_package/conanfile.py
- recipes/threadpool/config.yml
> threadpool: conan v2 support

- recipes/foonathan-lexy/all/conandata.yml
- recipes/foonathan-lexy/all/conanfile.py
- recipes/foonathan-lexy/config.yml
Specify library name and version:  **foonathan-lexy/2022.12.00**
---
> foonathan-lexy: add version 2022.12.00

- recipes/libsigcpp/2.x.x/conanfile.py
- recipes/libsigcpp/2.x.x/test_package/CMakeLists.txt
- recipes/libsigcpp/2.x.x/test_package/conanfile.py
- recipes/libsigcpp/2.x.x/test_v1_package/CMakeLists.txt
- recipes/libsigcpp/2.x.x/test_v1_package/conanfile.py
- recipes/libsigcpp/3.x.x/CMakeLists.txt
- recipes/libsigcpp/3.x.x/conandata.yml
- recipes/libsigcpp/3.x.x/conanfile.py
- recipes/libsigcpp/3.x.x/test_package/CMakeLists.txt
- recipes/libsigcpp/3.x.x/test_package/conanfile.py
- recipes/libsigcpp/3.x.x/test_v1_package/CMakeLists.txt
- recipes/libsigcpp/3.x.x/test_v1_package/conanfile.py
> libsigcpp: conan v2 support

- recipes/drogon/all/conandata.yml
- recipes/drogon/all/conanfile.py
- recipes/drogon/all/test_package/CMakeLists.txt
- recipes/drogon/all/test_v1_package/CMakeLists.txt
- recipes/drogon/config.yml
Specify library name and version:  **drogon/1.8.2**
- add version 1.8.2
- update hiredis
- use add_subdirectory in test_v1_package
---
> drogon: add version 1.8.2

- docs/faqs.md
@uilianries @grafikrobot are the more links to old discussions I could use to strengthen the position?
---
> docs: Add "no individual boost libraries" to FAQ

- recipes/netcdf/all/conanfile.py
- recipes/qt/5.x.x/conanfile.py
- recipes/qt/5.x.x/test_package/conanfile.py
Specify library name and version:  **qt**
---
> (#14820) prevent xorg require when using qtwayland opt

- recipes/jom/all/conanfile.py
- recipes/jom/all/test_package/conanfile.py
- recipes/jom/all/test_v1_package/conanfile.py
Use conan.tools.files.copy.
Update license to be GPL-3.0-only.
---
> jom: Download binaries in build method and fix test packages

- recipes/vulkan-loader/all/conandata.yml
- recipes/vulkan-loader/all/conanfile.py
- recipes/vulkan-loader/config.yml
> Bump vulkan loader/1.3.236.0

- recipes/vulkan-memory-allocator/all/conanfile.py
- recipes/vulkan-memory-allocator/all/test_package/conanfile.py
- recipes/vulkan-memory-allocator/all/test_v1_package/CMakeLists.txt
> vulkan-memory-allocator: bump vulkan-headers + modernize more

- recipes/mbits-mstch/all/conandata.yml
- recipes/mbits-mstch/all/conanfile.py
- recipes/mbits-mstch/all/test_package/CMakeLists.txt
- recipes/mbits-mstch/all/test_package/conanfile.py
- recipes/mbits-mstch/all/test_package/test_package.cpp
- recipes/mbits-mstch/all/test_v1_package/CMakeLists.txt
- recipes/mbits-mstch/all/test_v1_package/conanfile.py
- recipes/mbits-mstch/config.yml
Specify library name and version:  **mbits-mstch/1.0.4**
---
> add mbits-mstch/1.0.4

- recipes/jasper/all/conandata.yml
- recipes/jasper/all/conanfile.py
- recipes/jasper/all/patches/4.0.0-0001-skip-rpath.patch
- recipes/jasper/all/patches/4.0.0-0002-find-libjpeg.patch
- recipes/jasper/all/patches/4.0.0-0003-deterministic-libname.patch
- recipes/jasper/config.yml
> jasper: add 4.0.0 + allow to disable jpeg or use mozjpeg

- recipes/libserial/all/conandata.yml
- recipes/libserial/all/conanfile.py
- recipes/libserial/all/test_package/CMakeLists.txt
- recipes/libserial/all/test_package/conanfile.py
- recipes/libserial/all/test_package/test_package.cpp
- recipes/libserial/all/test_v1_package/CMakeLists.txt
- recipes/libserial/all/test_v1_package/conanfile.py
- recipes/libserial/config.yml
Specify library name and version:  **libserial/cci.20200930**
libserial is C++ serial port library.
---
> libserial: add recipe

- recipes/platform.interfaces/all/conandata.yml
- recipes/platform.interfaces/all/conanfile.py
- recipes/platform.interfaces/all/test_package/CMakeLists.txt
- recipes/platform.interfaces/all/test_package/conanfile.py
- recipes/platform.interfaces/all/test_package/test_package.cpp
- recipes/platform.interfaces/all/test_v1_package/CMakeLists.txt
- recipes/platform.interfaces/all/test_v1_package/conanfile.py
- recipes/platform.interfaces/config.yml
Specify library name and version:  **platform.interfaces/***
---
> platform.interfaces: add version 0.3.41, support conan v2

- recipes/glslang/all/conandata.yml
- recipes/glslang/all/patches/1.3.236.0-0001-no-force-glslang-pic.patch
- recipes/glslang/config.yml
> Bump glslang/1.3.236.0

- recipes/libzippp/all/CMakeLists.txt
- recipes/libzippp/all/conandata.yml
- recipes/libzippp/all/conanfile.py
- recipes/libzippp/all/test_package/CMakeLists.txt
- recipes/libzippp/all/test_package/conanfile.py
- recipes/libzippp/all/test_v1_package/CMakeLists.txt
- recipes/libzippp/all/test_v1_package/conanfile.py
- recipes/libzippp/config.yml
Specify library name and version:  **libzippp/***
- add version 0.6.0-1.9.2
- update zlib
---
> libzippp: add version 0.6.0-1.9.2, support conan v2

- recipes/c4core/all/conandata.yml
- recipes/c4core/all/patches/0.1.11-0001-make-fast_float-external.patch
- recipes/c4core/all/test_package/CMakeLists.txt
- recipes/c4core/all/test_v1_package/CMakeLists.txt
- recipes/c4core/config.yml
Specify library name and version:  **c4core/0.1.11**
---
> c4core: add version 0.1.11

- recipes/elfio/all/conandata.yml
- recipes/elfio/all/conanfile.py
- recipes/elfio/all/test_package/CMakeLists.txt
- recipes/elfio/all/test_package/conanfile.py
- recipes/elfio/all/test_v1_package/CMakeLists.txt
- recipes/elfio/all/test_v1_package/conanfile.py
- recipes/elfio/all/test_v1_package/example.cpp
- recipes/elfio/config.yml
Specify library name and version:  **elfio/3.11**
---
> elfio: Add version 3.11

- recipes/strong_type/all/conandata.yml
- recipes/strong_type/all/conanfile.py
- recipes/strong_type/all/test_package/CMakeLists.txt
- recipes/strong_type/all/test_package/conanfile.py
- recipes/strong_type/all/test_package/test_package.cpp
- recipes/strong_type/all/test_v1_package/CMakeLists.txt
- recipes/strong_type/all/test_v1_package/conanfile.py
- recipes/strong_type/config.yml
Specify library name and version:  **strong_type/v7**
since [strong_type](https://github.com/rollbear/strong_type) ins now available on [Compiler Explorer ](https://godbolt.org/z/6GEPz6ETe), I thought it should also be available on Conan
---
> Add new recipe: rollbear::strong_type

- recipes/commata/all/conandata.yml
- recipes/commata/all/conanfile.py
- recipes/commata/all/test_package/CMakeLists.txt
- recipes/commata/all/test_package/conanfile.py
- recipes/commata/all/test_package/test_package.cpp
- recipes/commata/all/test_v1_package/CMakeLists.txt
- recipes/commata/all/test_v1_package/conanfile.py
- recipes/commata/config.yml
Specify library name and version:  **commata/0.2.3**
commata is yet another header-only CSV parser.
---
> commata: add recipe

- recipes/rapidcsv/all/conandata.yml
- recipes/rapidcsv/all/conanfile.py
- recipes/rapidcsv/all/test_package/CMakeLists.txt
- recipes/rapidcsv/all/test_package/conanfile.py
- recipes/rapidcsv/all/test_v1_package/CMakeLists.txt
- recipes/rapidcsv/all/test_v1_package/conanfile.py
- recipes/rapidcsv/config.yml
Specify library name and version:  **rapidcsv/***
---
> rapidcsv: add version 8.69, support conan v2

- recipes/flecs/all/conandata.yml
- recipes/flecs/config.yml
> Bump flecs/3.1.3

- recipes/libpciaccess/all/conandata.yml
- recipes/libpciaccess/all/test_v1_package/conanfile.py
- recipes/libpciaccess/config.yml
Specify library name and version:  **libpciaccess/0.17**
---
> libpciaccess 0.17

- recipes/libdrm/all/conandata.yml
- recipes/libdrm/all/conanfile.py
- recipes/libdrm/config.yml
Specify library name and version:  **libdrm/2.4.114**
---
> libdrm 2.4.114

- recipes/taywee-args/all/conandata.yml
- recipes/taywee-args/config.yml
Specify library name and version:  **taywee-args/6.4.4**
---
> taywee-args: add version 6.4.4

- recipes/sdl/all/conandata.yml
- recipes/sdl/config.yml
Specify library name and version:  **sdl/2.26.1**
new SDL version
---
> sdl: add v2.26.1

- recipes/arsenalgear/all/conanfile.py
- recipes/arsenalgear/all/test_package/CMakeLists.txt
- recipes/arsenalgear/all/test_v1_package/CMakeLists.txt
Specify library name and version:  **arsenalgear/***
- update boost
---
> arsenalgear: update dependencies

- recipes/charls/all/conandata.yml
- recipes/charls/all/conanfile.py
- recipes/charls/all/test_package/CMakeLists.txt
- recipes/charls/all/test_v1_package/CMakeLists.txt
- recipes/charls/config.yml
Specify library name and version:  **charls/2.4.0**
- add version 2.4.0
---
> charls: add version 2.4.0

- recipes/libcbor/all/conandata.yml
- recipes/libcbor/all/test_package/CMakeLists.txt
- recipes/libcbor/all/test_package/test_package.c
- recipes/libcbor/config.yml
Specify library name and version:  **libcbor/0.10.0**
---
> libcbor: add version 0.10.0

- recipes/mikelankamp-fpm/all/conandata.yml
- recipes/mikelankamp-fpm/all/conanfile.py
- recipes/mikelankamp-fpm/all/test_package/CMakeLists.txt
- recipes/mikelankamp-fpm/all/test_package/conanfile.py
- recipes/mikelankamp-fpm/all/test_package/test_package.cpp
- recipes/mikelankamp-fpm/all/test_v1_package/CMakeLists.txt
- recipes/mikelankamp-fpm/all/test_v1_package/conanfile.py
- recipes/mikelankamp-fpm/config.yml
Specify library name and version:  **mikelankamp-fpm/1.1.0**
fpm is fixed-point math library.
---
> mikelankamp-fpm: add recipe

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.40.1**
---
> sqlite3: add version 3.40.1

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/config.yml
Specify library name and version:  **simdutf/2.1.0**
---
> simdutf: add version 2.1.0

- recipes/libcbor/all/conandata.yml
- recipes/libcbor/config.yml
Specify library name and version:  **libcbor/0.10.1**
---
> libcbor: add version 0.10.1

- recipes/cpr/all/conandata.yml
- recipes/cpr/all/conanfile.py
- recipes/cpr/all/patches/005-1.9.3-fix-curl-components.patch
- recipes/cpr/config.yml
Specify library name and version:  **cpr/1.9.3**
---
> cpr: add version 1.9.3

- recipes/csvmonkey/all/conanfile.py
- recipes/csvmonkey/all/test_package/CMakeLists.txt
- recipes/csvmonkey/all/test_package/conanfile.py
- recipes/csvmonkey/all/test_v1_package/CMakeLists.txt
- recipes/csvmonkey/all/test_v1_package/conanfile.py
Specify library name and version:  **csvmonkey/***
- update boost
- use `check_min_cppstd`
---
> csvmonkey: update boost, support conan v2

- recipes/xorg/all/conanfile.py
- recipes/xorg/all/test_package/conanfile.py
Some minor fixes for xorg recipe to make it work with v2
> Make xorg v2 compatible

- recipes/xorg/all/conanfile.py
Like: https://github.com/conan-io/conan-center-index/pull/15085#pullrequestreview-1234724878
> Raise required_conan_version for xorg/system

- recipes/libxshmfence/all/conanfile.py
Specify library name and version:  **libxshmfence/***
---
> libxshmfence: generate gcc11 binaries

- recipes/openexr/2.x/conanfile.py
- recipes/openexr/3.x/conanfile.py
Minor fixes to make it v2 compatible
> Make openexr v2 compatible 

- recipes/perlinnoise/all/conandata.yml
- recipes/perlinnoise/all/conanfile.py
- recipes/perlinnoise/all/test_package/CMakeLists.txt
- recipes/perlinnoise/all/test_package/conanfile.py
- recipes/perlinnoise/all/test_package/test_package.cpp
- recipes/perlinnoise/all/test_v1_package/CMakeLists.txt
- recipes/perlinnoise/all/test_v1_package/conanfile.py
- recipes/perlinnoise/config.yml
Specify library name and version:  **perlinnoise/3.0.0**
---
> perlinnoise: add recipe

- recipes/http_parser/all/conanfile.py
- recipes/http_parser/all/test_v1_package/conanfile.py
I just need new binaries :)
---
> http_parser: modernize 

- recipes/rapidyaml/all/conandata.yml
- recipes/rapidyaml/all/conanfile.py
- recipes/rapidyaml/all/patches/0.5.0-001-remove-internal-c4core.patch
- recipes/rapidyaml/all/test_v1_package/CMakeLists.txt
- recipes/rapidyaml/config.yml
Specify library name and version:  **rapidyaml/0.5.0**
- add version 0.5.0
- update c4core
---
> rapidyaml: add version 0.5.0

- recipes/gmp/all/conandata.yml
- recipes/gmp/all/conanfile.py
- recipes/gmp/all/test_package/CMakeLists.txt
- recipes/gmp/all/test_package/conanfile.py
- recipes/gmp/all/test_v1_package/CMakeLists.txt
- recipes/gmp/all/test_v1_package/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/13724
---
> gmp: conan v2 support

- recipes/moltenvk/all/conandata.yml
- recipes/moltenvk/all/conanfile.py
- recipes/moltenvk/all/dependencies/dependencies-1.2.1.yml
- recipes/moltenvk/config.yml
> moltenvk: add 1.2.1 + define new env var `VK_DRIVER_FILES` listened by Vulkan-Loader

- .github/workflows/linter-conan-v2.yml
with ~1500 recipes this was hitting the 1hrs limit for a job on GitHub Actions preventing any meaning to be taken from it the results as it was killed without showing any logs
Config!
> linter: limit how many recipes are used to test changes

- recipes/xz_utils/all/conandata.yml
- recipes/xz_utils/config.yml
Specify library name and version:
- **xz_utils/5.2.10**
- **xz_utils/5.4.0**
---
> xz_utils: add v5.2.10 and v5.4.0

- recipes/md4qt/all/conandata.yml
- recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.0.4**
---
> md4qt: bump version to 2.0.4.

- recipes/strong_type/all/conandata.yml
- recipes/strong_type/config.yml
Specify library name and version:  **strong_type/v8**
Version update
---
> Update strong_type to v8

- recipes/continuable/all/conandata.yml
- recipes/continuable/config.yml
Signed-off-by: Itay Bookstein <itay.bookstein@nextsilicon.com>
Specify library name and version:  **continuable/4.2.1**
---
> continuable: Add version 4.2.1

- recipes/packio/all/conandata.yml
- recipes/packio/config.yml
Specify library name and version:  **packio/2.3.0**
---
> packio: add version 2.3.0

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
> add meson/1.0.0

- recipes/brynet/all/conandata.yml
- recipes/brynet/config.yml
Specify library name and version:  **brynet/1.12.2**
---
> brynet: add version 1.12.2

- recipes/usockets/all/conandata.yml
- recipes/usockets/config.yml
Specify library name and version:  **usockets/0.8.5**
---
> usockets: add version 0.8.5

- recipes/xkbcommon/all/conandata.yml
- recipes/xkbcommon/all/conanfile.py
- recipes/xkbcommon/config.yml
Specify library name and version:  **xkbcommon/1.5.0**
---
> Xkbcommon 1.5.0

- recipes/cppfront/all/conandata.yml
- recipes/cppfront/config.yml
Specify library name and version:  **cppfront/cci.20230103**
---
> [cppfront] Upgrade to latest version

- recipes/libiconv/all/conanfile.py
Specify library name and version:  **libiconv/all**
Workarounds to support cross-compatibility of this recipe between Conan 1.x and Conan 2.0:
* Avoid comparing `self.settings.compiler` directly, but rather map the version to compare depending on the current compiler
* Avoid calling the legacy `get_gnu_triplet`, in practice the triplet differs only in the architecture
> libiconv: workarounds to support conan v2

- recipes/glib/all/conandata.yml
- recipes/glib/all/conanfile.py
- recipes/glib/config.yml
Specify library name and version:  **glib/2.75.2**
---
> glib 2.75.2

- recipes/asio-grpc/all/conandata.yml
- recipes/asio-grpc/all/conanfile.py
- recipes/asio-grpc/config.yml
Specify library name and version:  **asio-grpc/2.4.0**
---
> asio-grpc: add version 2.4.0

- recipes/libmysqlclient/all/conandata.yml
- recipes/libmysqlclient/config.yml
Specify library name and version:  **libmysqlclient/8.0.31**
---
> libmysqlclient: add version 8.0.31

- recipes/openxlsx/all/conandata.yml
- recipes/openxlsx/all/conanfile.py
- recipes/openxlsx/all/test_package/CMakeLists.txt
- recipes/openxlsx/all/test_package/conanfile.py
- recipes/openxlsx/all/test_package/test_package.cpp
- recipes/openxlsx/all/test_v1_package/CMakeLists.txt
- recipes/openxlsx/all/test_v1_package/conanfile.py
- recipes/openxlsx/config.yml
Specify library name and version:  **openxlsx/0.4.1**
---
> openxslx: add recipe

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/4.0.0**
---
> wasmtime: add version 4.0.0

- recipes/docopt.cpp/all/CMakeLists.txt
- recipes/docopt.cpp/all/conandata.yml
- recipes/docopt.cpp/all/conanfile.py
- recipes/docopt.cpp/all/test_package/CMakeLists.txt
- recipes/docopt.cpp/all/test_package/conanfile.py
- recipes/docopt.cpp/all/test_v1_package/CMakeLists.txt
- recipes/docopt.cpp/all/test_v1_package/conanfile.py
Specify library name and version:  **docopt.cpp/***
---
> docopt.cpp: update boost, support conan v2

- recipes/watcher/all/conandata.yml
- recipes/watcher/all/conanfile.py
- recipes/watcher/config.yml
Specify library name and version:  **watcher/0.5.4**
- add version 0.5.4
- stop using `check_min_vs`
---
> watcher: add version 0.5.4

- recipes/redis-plus-plus/all/conandata.yml
- recipes/redis-plus-plus/all/conanfile.py
- recipes/redis-plus-plus/all/patches/1.3.7-0001-fix-dependencies-injection.patch
- recipes/redis-plus-plus/config.yml
Specify library name and version:  **redis-plus-plus/***
---
> redis-plus-plus: add version 1.3.7, update hiredis

- recipes/cli11/all/conandata.yml
- recipes/cli11/config.yml
Specify library name and version:  **cli11/2.3.2**
Add v2.3.2.
---
> cli11: add v2.3.2

- recipes/winflexbison/all/conanfile.py
- recipes/winflexbison/all/test_package/conanfile.py
- recipes/winflexbison/all/test_v1_package/CMakeLists.txt
- recipes/winflexbison/all/test_v1_package/conanfile.py
> winflexbison: remove compiler from package id & modernize more

- recipes/oboe/all/conandata.yml
- recipes/oboe/all/conanfile.py
- recipes/oboe/all/patches/1.7.0-0001-fix-cmake.patch
- recipes/oboe/all/test_package/CMakeLists.txt
- recipes/oboe/all/test_package/conanfile.py
- recipes/oboe/all/test_package/test_package.cpp
- recipes/oboe/all/test_v1_package/CMakeLists.txt
- recipes/oboe/all/test_v1_package/conanfile.py
- recipes/oboe/config.yml
> add oboe/1.7.0

- recipes/libcurl/all/conandata.yml
- recipes/libcurl/config.yml
> libcurl: add version 7.87.0

- recipes/emsdk/all/conandata.yml
- recipes/emsdk/config.yml
> Bump emsdk/3.1.29

- recipes/wayland/all/conanfile.py
> wayland/*: Bump Meson version to 1.0.0

- recipes/dbus/1.x.x/conanfile.py
> dbus: Bump Meson, libsystemd, and glib versions

- recipes/xkbcommon/all/conanfile.py
> xkbcommon: Bump Meson to version 1.0.0

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/3.0.2**
---
> unordered_dense: add version 3.0.2

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/all/conanfile.py
- recipes/simdutf/config.yml
Specify library name and version:  **simdutf/2.2.0**
- add version 2.2.0
---
> simdutf: add version 2.2.0

- .c3i/config_v1.yml
Finally we are back on track updating conan versions!
> [config] Update conan version to 1.55.0

- .c3i/config_v1.yml
- .c3i/config_v2.yml
> [config] Update conan v1 to 1.56.0 and conan v2 to beta 7

- recipes/libftdi/1.x/CMakeLists.txt
- recipes/libftdi/1.x/conandata.yml
- recipes/libftdi/1.x/conanfile.py
- recipes/libftdi/1.x/patches/0001-cmake-targets.patch
- recipes/libftdi/1.x/test_package/CMakeLists.txt
- recipes/libftdi/1.x/test_package/conanfile.py
- recipes/libftdi/1.x/test_v1_package/CMakeLists.txt
- recipes/libftdi/1.x/test_v1_package/conanfile.py
Specify library name and version:  **libftdi/1.5**
This PR is a fork of PR  #14366 fixing also bug #14732 .
---
> Ftdi fixes

- recipes/libsvtav1/all/conandata.yml
- recipes/libsvtav1/all/conanfile.py
- recipes/libsvtav1/all/test_package/CMakeLists.txt
- recipes/libsvtav1/all/test_package/conanfile.py
- recipes/libsvtav1/all/test_package/test_package.cpp
- recipes/libsvtav1/all/test_v1_package/CMakeLists.txt
- recipes/libsvtav1/all/test_v1_package/conanfile.py
- recipes/libsvtav1/config.yml
Specify library name and version:  **libsvt1/1.2.1**
I'm adding this library to add ffmpeg support for AV1 in conan-center.
---
> libsvt1: conan v2 package

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/all/conanfile.py
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/***
- add version 2.85.1
- remove version 2.68.1
- set libdirs, bindirs empty
---
> daw_header_libraries: add version 2.85.1, remove version 2.68.1

- recipes/libusb/all/conandata.yml
- recipes/libusb/all/conanfile.py
- recipes/libusb/all/patches/1.0.23-0001-relax-windows-sdk-restriction.patch
- recipes/libusb/all/patches/1.0.24-0001-relax-windows-sdk-restriction.patch
- recipes/libusb/all/test_package/CMakeLists.txt
- recipes/libusb/all/test_package/conanfile.py
- recipes/libusb/all/test_package/test_package.c
- recipes/libusb/all/test_v1_package/CMakeLists.txt
- recipes/libusb/all/test_v1_package/conanfile.py
- recipes/libusb/config.yml
closes https://github.com/conan-io/conan-center-index/issues/11941
---
> libusb: conan v2 support

- recipes/c-blosc/all/conandata.yml
- recipes/c-blosc/all/conanfile.py
- recipes/c-blosc/all/patches/cmake-dependencies-1.21.2+.patch
- recipes/c-blosc/all/test_v1_package/CMakeLists.txt
- recipes/c-blosc/config.yml
Specify library name and version:  **c-blosc/***
- add version 1.21.3
- add patch_descriptions
---
> c-blosc: add version 1.21.3

- recipes/sentry-native/all/conandata.yml
- recipes/sentry-native/config.yml
Specify library name and version:  **sentry-native/0.5.3**
---
> [sentry-native/0.5.3] Bump version

- recipes/lcms/all/conandata.yml
- recipes/lcms/all/conanfile.py
- recipes/lcms/all/patches/2.13.1-0001-fix-msvc-import-lib.patch
- recipes/lcms/all/test_package/CMakeLists.txt
- recipes/lcms/all/test_package/conanfile.py
- recipes/lcms/all/test_v1_package/CMakeLists.txt
- recipes/lcms/all/test_v1_package/conanfile.py
- recipes/lcms/config.yml
closes https://github.com/conan-io/conan-center-index/issues/11129
---
> lcms: conan v2 support & move to meson build + drop old versions

- recipes/b2/portable/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/14869
---
> b2: do not allow cross-build & cleanup a little bit

- recipes/hidapi/all/conanfile.py
- recipes/hidapi/all/test_package/CMakeLists.txt
- recipes/hidapi/all/test_package/conanfile.py
- recipes/hidapi/all/test_v1_package/CMakeLists.txt
- recipes/hidapi/all/test_v1_package/conanfile.py
> hidapi: conan v2 support

- recipes/opusfile/all/conandata.yml
- recipes/opusfile/all/conanfile.py
- recipes/opusfile/all/patches/001-disable-cert-store-integration.patch
- recipes/opusfile/all/test_package/CMakeLists.txt
- recipes/opusfile/all/test_package/conanfile.py
- recipes/opusfile/all/test_v1_package/CMakeLists.txt
- recipes/opusfile/all/test_v1_package/conanfile.py
> opusfile: conan v2 support

- recipes/libavif/all/conanfile.py
Specify library name and version:  **libavif/\***
Bump libyuv dependency version
Fix casting exception 
---
> [libavif] Bump libyuv version

- recipes/lief/all/conanfile.py
- recipes/lief/all/test_v1_package/CMakeLists.txt
Specify library name and version:  **lief/***
- remove duplicated `requires` in `requirements`
---
> lief: update dependencies, delete duplicated dependencies

- recipes/xtensor/all/conanfile.py
> xtensor: bump deps

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/config.yml
Specify library name and version:  **simdutf/3.0.0**
---
> simdutf: add version 3.0.0

- recipes/watcher/all/conandata.yml
- recipes/watcher/config.yml
Specify library name and version:  **watcher/0.5.5**
---
> watcher: add version 0.5.5

- recipes/libdeflate/all/conandata.yml
- recipes/libdeflate/all/test_package/CMakeLists.txt
- recipes/libdeflate/config.yml
Specify library name and version:  **libdeflate/1.17**
---
> libdeflate: add version 1.17

- recipes/itlib/all/conandata.yml
- recipes/itlib/config.yml
Specify library name and version:  **itlib/1.8.1**
---
> itlib: add versoin 1.8.1

- recipes/wayland-protocols/all/conandata.yml
- recipes/wayland-protocols/config.yml
Specify library name and version:  **wayland-protocols/1.31**
---
> wayland-protocols: add version 1.31

- recipes/cppcheck/all/conandata.yml
- recipes/cppcheck/config.yml
Specify library name and version:  **cppcheck/2.9.3**
---
> cppcheck: add version 2.9.3

- recipes/jsoncpp/all/conanfile.py
> jsoncpp: fix compiler check for conan v2

- recipes/benchmark/all/conanfile.py
> benchmark: fix compiler check for conan v2

- recipes/emsdk/all/conandata.yml
- recipes/emsdk/config.yml
Specify library name and version:  **emsdk/3.1.30**
---
> emsdk: add version 3.1.30

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/all/patches/1.23.2-0001-disable-shared-when-static.patch
- recipes/mongo-c-driver/config.yml
Specify library name and version:  **mongo-c-driver/1.23.2**
---
> mongo-c-driver: add version 1.23.2

- docs/changelog.md
Added latest changes of last week to the changelog
> [docs] Update changelog 12-January-2023

- recipes/foonathan-memory/all/conandata.yml
- recipes/foonathan-memory/config.yml
Specify library name and version:  **foonathan-memory/0.7.3**
---
> foonathan-memory: add version 0.7.3

- recipes/bitserializer/all/conandata.yml
- recipes/bitserializer/all/conanfile.py
- recipes/bitserializer/all/test_package/CMakeLists.txt
- recipes/bitserializer/all/test_package/conanfile.py
- recipes/bitserializer/all/test_package/test_package.cpp
- recipes/bitserializer/all/test_v1_package/conanfile.py
- recipes/bitserializer/config.yml
Specify library name and version:  **bitserializer/0.50**
- Add new version of library 0.50
- Update versions of dependent libraries
- Build library via CMake (it's not "header only" since version 0.50, at least for CSV component)
- Add new library components - Csv and Ryaml
I am author of library.
---
- [ √ ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ √ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ √ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ √ ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> [BitSerializer] Add new version 0.50

- recipes/meson/all/conanfile.py
Specify library name and version:  **meson/all**
* Add package_type attribute.
> meson: add package_type attribute

- recipes/hdf5/all/conandata.yml
- recipes/hdf5/all/conanfile.py
- recipes/hdf5/all/patches/conanize-link-szip-1.14.0+.patch
- recipes/hdf5/all/test_package/conanfile.py
- recipes/hdf5/all/test_v1_package/conanfile.py
- recipes/hdf5/config.yml
Specify library name and version:  **hdf5/1.14.0**
---
> hdf5: add v1.14.0

- recipes/taskflow/all/conandata.yml
- recipes/taskflow/config.yml
Specify library name and version:  **taskflow/3.5.0**
- add version 3.5.0
- add patch_description
---
> taskflow: add version 3.5.0

- docs/changelog.md
Small changes to be able to generate the most packages for conan v2 in the background
> Update changelog 16-January-2023

- recipes/cppcheck/all/conanfile.py
Specify library name and version:  **cpcheck/***
---
> cppcheck: put all data in res folder

- recipes/opencv/4.x/conandata.yml
- recipes/opencv/4.x/conanfile.py
- recipes/opencv/4.x/patches/4.1.2-0007-android-install-layout.patch
- recipes/opencv/4.x/patches/4.5.2-0001-fix-zlib-static-android.patch
closes https://github.com/conan-io/conan-center-index/issues/15228
---
> opencv 4.x: fix android build

- recipes/mbits-utfconv/all/conandata.yml
- recipes/mbits-utfconv/all/conanfile.py
- recipes/mbits-utfconv/all/test_package/CMakeLists.txt
- recipes/mbits-utfconv/all/test_package/conanfile.py
- recipes/mbits-utfconv/all/test_package/test_package.cpp
- recipes/mbits-utfconv/all/test_v1_package/CMakeLists.txt
- recipes/mbits-utfconv/all/test_v1_package/conanfile.py
- recipes/mbits-utfconv/config.yml
Specify library name and version:  **mbits-utfconv/1.0.3**
---
> add mbits-utfconv/1.0.3

- recipes/mbits-diags/all/conandata.yml
- recipes/mbits-diags/all/conanfile.py
- recipes/mbits-diags/all/test_package/CMakeLists.txt
- recipes/mbits-diags/all/test_package/conanfile.py
- recipes/mbits-diags/all/test_package/test_package.cpp
- recipes/mbits-diags/all/test_v1_package/CMakeLists.txt
- recipes/mbits-diags/all/test_v1_package/conanfile.py
- recipes/mbits-diags/config.yml
Specify library name and version:  **mbits-diags/0.9.4**
---
> add mbits-diags/0.9.4

- recipes/hyperscan/all/conanfile.py
- recipes/hyperscan/all/test_package/conanfile.py
> hyperscan: fix pkg_config_name of chimera + bump boost + few minor improvements

- recipes/crowcpp-crow/all/conandata.yml
- recipes/crowcpp-crow/all/conanfile.py
- recipes/crowcpp-crow/all/test_package/CMakeLists.txt
- recipes/crowcpp-crow/all/test_package/conanfile.py
- recipes/crowcpp-crow/all/test_v1_package/CMakeLists.txt
- recipes/crowcpp-crow/all/test_v1_package/conanfile.py
- recipes/crowcpp-crow/config.yml
Specify library name and version:  **crowcpp-crow/***
- add version 1.0+5
- update dependencies (boost, openssl)
- fix amalgamation error
- add settings (with_ssl, with_compression)
---
> crowcpp-crow: add version 1.0+5, support conan v2, update dependencies

- recipes/erikzenker-hsm/all/conandata.yml
- recipes/erikzenker-hsm/all/conanfile.py
- recipes/erikzenker-hsm/all/test_v1_package/CMakeLists.txt
- recipes/erikzenker-hsm/all/test_v1_package/conanfile.py
- recipes/erikzenker-hsm/config.yml
Specify library name and version:  **erikzenker-hsm/***
- add version 2.3.0
- update boost
- remove pylint comment
---
> erikzenker-hsm: add version 2.3.0, update boost

- recipes/android-ndk/all/conandata.yml
- recipes/android-ndk/all/conanfile.py
- recipes/android-ndk/all/test_v1_package/CMakeLists.txt
- recipes/android-ndk/config.yml
> android-ndk: add r25b + use self.output.warning for conan v2

- recipes/msgpack-c/all/CMakeLists.txt
- recipes/msgpack-c/all/conandata.yml
- recipes/msgpack-c/all/conanfile.py
- recipes/msgpack-c/all/test_package/CMakeLists.txt
- recipes/msgpack-c/all/test_package/conanfile.py
- recipes/msgpack-c/all/test_v1_package/CMakeLists.txt
- recipes/msgpack-c/all/test_v1_package/conanfile.py
- recipes/msgpack-c/config.yml
Specify library name and version:  **msgpack-c/***
---
> msgpack-c: add version 5.0.0, support conan v2

- recipes/xtl/all/conandata.yml
- recipes/xtl/all/test_v1_package/CMakeLists.txt
- recipes/xtl/config.yml
Specify library name and version:  **xtl/0.7.5**
---
> xtl: add version 0.7.5

- recipes/bear/all/conandata.yml
- recipes/bear/all/conanfile.py
- recipes/bear/all/patches/7de12540948cd5e0ee5f966b5cc383bc0c0e5fe9.diff
- recipes/bear/all/test_package/conanfile.py
- recipes/bear/all/test_v1_package/conanfile.py
- recipes/bear/config.yml
Specify library name and version:  **bear/3.0.21**
---
> bear 3.0.21

- docs/changelog.md
We are getting some new things to the bot comments 😄
> [docs] Update changelog 16-January-2023

- recipes/libpq/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/11716
closes https://github.com/conan-io/conan-center-index/issues/15301
closes https://github.com/conan-io/conan-center-index/issues/15343
---
> libpq: fix MinGW by allowing shared only + fix link to OpenSSL

- recipes/qt/5.x.x/conanfile.py
- recipes/qt/6.x.x/conanfile.py
Specify library name and version:  **qt/***
closes conan-io/conan-center-index#14718
---
> [qt] fix: conanfile.py RuntimeError: OrderedDict mutated during iteration

- recipes/norm/all/CMakeLists.txt
- recipes/norm/all/conandata.yml
- recipes/norm/all/conanfile.py
- recipes/norm/all/patches/0001-fix-pthread.patch
- recipes/norm/all/patches/0002-fix-fpic.patch
- recipes/norm/all/test_package/CMakeLists.txt
- recipes/norm/all/test_package/conanfile.py
- recipes/norm/all/test_v1_package/CMakeLists.txt
- recipes/norm/all/test_v1_package/conanfile.py
> norm: conan v2 support

- recipes/catch2/3.x.x/conandata.yml
- recipes/catch2/config.yml
Specify library name and version:  **catch2/3.3.0**
---
> catch2: add version 3.3.0

- recipes/arrow/all/conanfile.py
> arrow: relocatable shared libs on macOS

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/all/conanfile.py
- recipes/simdjson/all/test_v1_package/CMakeLists.txt
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/***
- add version 3.1.0
- remove old versions
- use f-string
---
> simdjson: add version 3.1.0, remove older versions

- .c3i/config_v1.yml
- .c3i/config_v2.yml
> [config] Update conan versions

- recipes/jfalcou-eve/all/conanfile.py
**jfalcou-eve/v2022.09.1**
---
> [jfalcou-eve] Support for apple-clang v14

- recipes/iso8601lib/all/conandata.yml
- recipes/iso8601lib/all/conanfile.py
- recipes/iso8601lib/all/test_package/CMakeLists.txt
- recipes/iso8601lib/all/test_package/conanfile.py
- recipes/iso8601lib/all/test_package/test_package.cpp
- recipes/iso8601lib/all/test_v1_package/CMakeLists.txt
- recipes/iso8601lib/all/test_v1_package/conanfile.py
- recipes/iso8601lib/config.yml
Specify library name and version:  **iso8601lib/cci.20230123**
I'm submitting this package because we are using this library and would like to have it as a Conan package.
---
> iso8601lib: add new recipe, version cci.20230123

- recipes/uwebsockets/all/conandata.yml
- recipes/uwebsockets/all/conanfile.py
- recipes/uwebsockets/config.yml
Specify library name and version:  **uwebsockets/20.36.0**
---
> uwebsockets: add version 20.36.0

- .c3i/config_v1.yml
- .c3i/config_v2.yml
Adding some more entries to the configuration for better user feedback 🤞
> [config] Migrate cci config entries, add new ones and activate conan v2 feedback again

- recipes/msgpack-cxx/all/conandata.yml
- recipes/msgpack-cxx/all/conanfile.py
- recipes/msgpack-cxx/all/test_package/CMakeLists.txt
- recipes/msgpack-cxx/all/test_package/conanfile.py
- recipes/msgpack-cxx/all/test_v1_package/CMakeLists.txt
- recipes/msgpack-cxx/all/test_v1_package/conanfile.py
- recipes/msgpack-cxx/config.yml
Specify library name and version:  **msgpack-cxx/***
---
> msgpack-cxx: add version 5.0.0, support conan v2

- recipes/daw_utf_range/all/conanfile.py
Specify library name and version:  **daw_utf_range/***
---
> daw_utf_range: update daw_header_libraries

- recipes/openexr/3.x/conanfile.py
> openexr: bump deps + fix min conan version

- recipes/qpdf/all/conanfile.py
> qpdf: modernize

- recipes/miniz/all/conandata.yml
- recipes/miniz/all/test_v1_package/CMakeLists.txt
- recipes/miniz/config.yml
Specify library name and version:  **miniz/3.0.2**
- add version 3.0.2
---
> miniz: add version 3.0.2

- recipes/glu/all/conanfile.py
see https://github.com/conan-io/hooks/pull/480
---
> glu: lowercase system libs

- recipes/proj/all/conanfile.py
for https://github.com/conan-io/hooks/pull/480
---
> proj: lowercase system libs + bump dependencies

- recipes/openal/all/conanfile.py
for https://github.com/conan-io/hooks/pull/480
---
> openal: lowercase system libs

- recipes/plf_indiesort/all/conandata.yml
- recipes/plf_indiesort/all/conanfile.py
- recipes/plf_indiesort/all/test_v1_package/CMakeLists.txt
- recipes/plf_indiesort/config.yml
Specify library name and version:  **plf_indiesort/1.18**
---
> plf_indiesort: add version 1.18

- recipes/pgm-index/all/conandata.yml
- recipes/pgm-index/all/conanfile.py
- recipes/pgm-index/all/test_package/CMakeLists.txt
- recipes/pgm-index/all/test_package/conanfile.py
- recipes/pgm-index/all/test_package/test_package.cpp
- recipes/pgm-index/all/test_v1_package/CMakeLists.txt
- recipes/pgm-index/all/test_v1_package/conanfile.py
- recipes/pgm-index/config.yml
> add pgm-index/cci.20220801

- recipes/ffmpeg/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/15405
see https://github.com/conan-io/hooks/pull/480
---
> ffmpeg: lowercase system libs

- recipes/clipper/all/conanfile.py
- recipes/clipper/all/test_v1_package/CMakeLists.txt
> clipper: Minor recipe cleanup

- recipes/itlib/all/conandata.yml
- recipes/itlib/config.yml
Specify library name and version:  **itlib/***
- add version 1.8.2
---
> itlib: add version 1.8.2, remove older versions

- recipes/plf_stack/all/conandata.yml
- recipes/plf_stack/all/conanfile.py
- recipes/plf_stack/all/test_v1_package/CMakeLists.txt
- recipes/plf_stack/config.yml
Specify library name and version:  **plf_stack/***
- add version 1.64
---
> plf_stack: add version 1.64

- recipes/quazip/all/conandata.yml
- recipes/quazip/all/conanfile.py
- recipes/quazip/config.yml
Specify library name and version:  **quazip/1.4**
---
> quazip: add version 1.4, update qt

- recipes/librdkafka/all/conandata.yml
- recipes/librdkafka/all/conanfile.py
- recipes/librdkafka/all/patches/0002-Change-library-targets-and-result-variables-2-0-2.patch
- recipes/librdkafka/config.yml
Specify library name and version:  **librdkafka/***
- add version 2.0.2
- update libcurl
- add patch_description
---
> librdkafka: add version 2.0.2, update libcurl

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/all/conanfile.py
- recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/5.0.0**
---
> wasmtime: add version 5.0.0

- .c3i/config_v2.yml
Let's see if we can fix the report issue by replacing https://github.com/conan-io/conan-center-index/issues/11464
> [config] Update issue to report results for export check v2

- recipes/roaring/all/conandata.yml
- recipes/roaring/all/conanfile.py
- recipes/roaring/config.yml
Specify library name and version:  **roaring/***
- add version 0.9.0
---
> roaring: add version 0.9.0, remove older versions

- recipes/stduuid/all/conandata.yml
- recipes/stduuid/all/conanfile.py
- recipes/stduuid/config.yml
Specify library name and version:  **stduuid/1.2.3**
- add version 1.2.3
- update ms-gsl
---
> stduuid: add version 1.2.3

- recipes/tinycbor/all/conanfile.py
- use NMakeToolchain
- no self.info in validate()
- build either shared or static (env injection was missing in generate() of AutotoolsToolchain)
---
> tinycbor: build either shared or static + modernize more

- recipes/taocpp-taopq/all/CMakeLists.txt
- recipes/taocpp-taopq/all/conandata.yml
- recipes/taocpp-taopq/all/conanfile.py
- recipes/taocpp-taopq/all/test_package/CMakeLists.txt
- recipes/taocpp-taopq/all/test_package/conanfile.py
- recipes/taocpp-taopq/all/test_v1_package/CMakeLists.txt
- recipes/taocpp-taopq/all/test_v1_package/conanfile.py
also fix casing of system libs for https://github.com/conan-io/hooks/pull/480
---
> taocpp-taopq: conan v2 support

- recipes/plf_colony/all/conandata.yml
- recipes/plf_colony/all/conanfile.py
- recipes/plf_colony/all/patches/7.00-0001-disable-cxx20-from-apple-clang14.patch
- recipes/plf_colony/all/patches/7.06-0001-disable-cxx20-from-apple-clang14.patch
- recipes/plf_colony/all/test_v1_package/CMakeLists.txt
- recipes/plf_colony/config.yml
Specify library name and version:  **plf_colony/***
---
> plf_colony: add version 7.06, support apple-clang 14

- recipes/baical-p7/all/CMakeLists.txt
- recipes/baical-p7/all/conandata.yml
- recipes/baical-p7/all/conanfile.py
- recipes/baical-p7/all/patches/0001-fix-cmake.patch
- recipes/baical-p7/all/test_package/CMakeLists.txt
- recipes/baical-p7/all/test_package/conanfile.py
- recipes/baical-p7/all/test_v1_package/CMakeLists.txt
- recipes/baical-p7/all/test_v1_package/conanfile.py
> baical-p7: conan v2 support

- recipes/glaze/all/conandata.yml
- recipes/glaze/all/conanfile.py
- recipes/glaze/config.yml
- add version 0.3.5
- update fast_float
---
> glaze: add version 0.3.5

- recipes/breakpad/all/conandata.yml
- recipes/breakpad/all/conanfile.py
- recipes/breakpad/all/test_package/CMakeLists.txt
- recipes/breakpad/all/test_package/conanfile.py
- recipes/breakpad/all/test_v1_package/CMakeLists.txt
- recipes/breakpad/all/test_v1_package/conanfile.py
> breakpad: conan v2 support

- recipes/calceph/all/conanfile.py
- recipes/calceph/all/test_package/CMakeLists.txt
- recipes/calceph/all/test_package/conanfile.py
- recipes/calceph/all/test_v1_package/CMakeLists.txt
- recipes/calceph/all/test_v1_package/conanfile.py
> calceph: conan v2 support

- recipes/sentry-crashpad/all/conandata.yml
- recipes/sentry-crashpad/all/test_package/CMakeLists.txt
- recipes/sentry-crashpad/config.yml
> [sentry-crashpad/0.5.4] Bump version

- recipes/libdeflate/pre_1.15/conanfile.py
> libdeflate < 1.15: use NMakeToolchain

- recipes/drogon/all/conandata.yml
- recipes/drogon/all/patches/1.8.3-0003-find-package-sqlite.patch
- recipes/drogon/config.yml
Specify library name and version:  **drogon/1.8.3**
---
> drogon: add version 1.8.3

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/all/conanfile.py
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.14.1**
- add version 3.14.1
- update daw_header_libraries
- simplify `validate()`
---
> daw_json_link: add vresion 3.14.1, update daw_header_libraries

- recipes/vulkan-headers/all/conandata.yml
- recipes/vulkan-headers/config.yml
> Bump vulkan-headers/1.3.239.0

- recipes/spirv-headers/all/conandata.yml
- recipes/spirv-headers/config.yml
> Bump spirv-headers/1.3.239.0

- recipes/spirv-cross/all/conandata.yml
- recipes/spirv-cross/config.yml
> Bump spirv-cross/1.3.239.0

- recipes/cppcheck/all/conandata.yml
- recipes/cppcheck/all/conanfile.py
- recipes/cppcheck/all/patches/0001-cli-remove-dmake-cmake-2.10.patch
- recipes/cppcheck/config.yml
Specify library name and version:  **cppcheck/2.10**
---
> cppcheck 2.10

- recipes/fmt/all/conandata.yml
- recipes/fmt/all/conanfile.py
- recipes/fmt/all/test_package/conanfile.py
> fmt: download official release tarballs + modernize more

- recipes/xkbcommon/all/conandata.yml
- recipes/xkbcommon/all/conanfile.py
> xkbcommon: download official tarballs & bump wayland-protocols

- recipes/jasper/all/conandata.yml
> jasper: download official tarballs

- recipes/libnghttp2/all/conandata.yml
- recipes/libnghttp2/all/conanfile.py
> libnghttp2: download official tarballs + modernize more

- .github/actions/pr_changed_files/action.yml
unblocks conan-io/conan-center-index#15314
fixes conan-io/conan-center-index#15605
---
> action: pr_changed_files: exclude removed files

- recipes/harfbuzz/all/conanfile.py
Specify library name and version:  **harfbuzz**
Bump dependency versions
---
> [harfbuzz] bump dependency versions

- recipes/opensubdiv/all/conandata.yml
- recipes/opensubdiv/all/conanfile.py
- recipes/opensubdiv/config.yml
Specify library name and version: opensubdiv/3.5.0
---
> opensubdiv: add version 3.5.0

- recipes/lcms/all/conandata.yml
> lcms: download official tarballs

- recipes/openapi-generator/all/conandata.yml
- recipes/openapi-generator/config.yml
> [openapi-generator/6.3.0] Bump version

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/0.3.6**
---
> glaze: add version 0.3.6

- recipes/geos/all/conandata.yml
- recipes/geos/all/conanfile.py
> geos: download official tarball + modernize more

- recipes/zfp/all/conandata.yml
- recipes/zfp/all/conanfile.py
- recipes/zfp/all/test_package/conanfile.py
- recipes/zfp/all/test_v1_package/CMakeLists.txt
> zfp: use official tarball + modernize more

- .c3i/config_v1.yml
- .c3i/config_v2.yml
Updating! and removing old entry values of the config
> [config] Update conan versions to 1.58 and beta9

- recipes/libgeotiff/all/conandata.yml
- recipes/libgeotiff/all/conanfile.py
- recipes/libgeotiff/all/patches/fix-cmake-1.5.1.patch
- recipes/libgeotiff/all/patches/fix-cmake-1.6.0.patch
- recipes/libgeotiff/all/patches/fix-cmake-1.7.1.patch
- recipes/libgeotiff/all/test_v1_package/CMakeLists.txt
> libgeotiff: download official tarballs + bump proj

- recipes/glm/all/conandata.yml
- recipes/glm/all/conanfile.py
- recipes/glm/all/test_package/conanfile.py
- recipes/glm/all/test_v1_package/CMakeLists.txt
> glm: download official tarballs + modernize more

- recipes/objectbox/all/CMakeLists.txt
- recipes/objectbox/all/conandata.yml
- recipes/objectbox/all/conanfile.py
- recipes/objectbox/all/test_package/CMakeLists.txt
- recipes/objectbox/all/test_package/conanfile.py
- recipes/objectbox/all/test_v1_package/CMakeLists.txt
- recipes/objectbox/all/test_v1_package/conanfile.py
- recipes/objectbox/config.yml
Specify library name and version:  **objectbox/***
- add version 0.18.1
- add patch description
---
> objectbox: add version 0.18.1, support conan v2

- recipes/mongo-cxx-driver/all/conandata.yml
- recipes/mongo-cxx-driver/all/conanfile.py
- recipes/mongo-cxx-driver/all/test_package/conanfile.py
> mongo-cxx-driver: fix source code url of 3.6.7 + modernize more

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/3.1.0**
---
> unordered_dense: add version 3.1.0

- recipes/vulkan-loader/all/conandata.yml
- recipes/vulkan-loader/config.yml
> Bump vulkan-loader/1.3.239.0

- recipes/minizip/all/conandata.yml
- recipes/minizip/all/conanfile.py
> minizip: use official source url + modernize more

- recipes/cs_libguarded/all/conandata.yml
- recipes/cs_libguarded/config.yml
Specify library name and version:  **cs_libguarded/1.4.0**
---
> cs_libguarded: add version 1.4.0

- recipes/zeromq/all/conandata.yml
- recipes/zeromq/all/conanfile.py
- recipes/zeromq/all/test_v1_package/CMakeLists.txt
> zeromq: use official tarballs + modernize more

- recipes/catch2/3.x.x/conandata.yml
- recipes/catch2/config.yml
**catch/3.3.1**
Adds latest version
closes #15570
---
> [catch2] adds Catch2 v3.3.1

- recipes/libharu/all/conanfile.py
> libharu: bump dependency version: libpng

- recipes/netcdf/all/conanfile.py
Just bumping the dependency version
> netcdf: bump dependency version: libcurl

- docs/changelog.md
> [docs] Update changelog 03-February-2023

- recipes/cmake/3.x.x/conandata.yml
- recipes/cmake/config.yml
> cmake: add version 3.25.2

- recipes/taywee-args/all/conandata.yml
- recipes/taywee-args/config.yml
> taywee-args: add version 6.4.6

- recipes/cpp-jwt/all/conandata.yml
- recipes/cpp-jwt/all/conanfile.py
- recipes/cpp-jwt/all/test_package/CMakeLists.txt
- recipes/cpp-jwt/all/test_package/conanfile.py
- recipes/cpp-jwt/all/test_v1_package/CMakeLists.txt
- recipes/cpp-jwt/all/test_v1_package/conanfile.py
> cpp-jwt: conan v2 support

- recipes/roaring/all/conandata.yml
- recipes/roaring/all/conanfile.py
- recipes/roaring/config.yml
Specify library name and version:  **roaring/0.9.3**
---
> roaring: add version 0.9.3

- recipes/emsdk/all/conandata.yml
- recipes/emsdk/config.yml
> emsdk: add version 3.1.31

- recipes/flecs/all/conandata.yml
- recipes/flecs/config.yml
> flecs: add version 3.1.4

- recipes/xpack/all/conandata.yml
- recipes/xpack/all/conanfile.py
- recipes/xpack/all/test_package/CMakeLists.txt
- recipes/xpack/config.yml
Specify library name and version:  **xpack/1.0.4**
---
> xpack: add version 1.0.4

- recipes/mosquitto/1.x/CMakeLists.txt
- recipes/mosquitto/1.x/conandata.yml
- recipes/mosquitto/1.x/conanfile.py
- recipes/mosquitto/1.x/patches/1.6.12-0001-fix-cmake.patch
- recipes/mosquitto/1.x/patches/1.6.12-0002-fix-macos.patch
- recipes/mosquitto/1.x/test_package/CMakeLists.txt
- recipes/mosquitto/1.x/test_package/conanfile.py
- recipes/mosquitto/1.x/test_v1_package/CMakeLists.txt
- recipes/mosquitto/1.x/test_v1_package/conanfile.py
> mosquitto 1.x: use official tarball + conan v2 support

- recipes/libde265/all/conandata.yml
- recipes/libde265/all/conanfile.py
- recipes/libde265/all/test_package/conanfile.py
- recipes/libde265/all/test_v1_package/CMakeLists.txt
> libde265: use official tarball & modernize more

- recipes/meshoptimizer/all/conanfile.py
- recipes/meshoptimizer/all/test_v1_package/CMakeLists.txt
> meshoptimizer: modernize more for conan v2

- recipes/taglib/all/conanfile.py
> taglib: modernize more for conan v2

- .github/workflows/alert-community.yml
Hi, I would like to watch these recipes.
---
> Add Hopobcn to watched recipes

- recipes/bzip2/all/conanfile.py
Specify library name and version:  **bzip2/1.0.6**, **bzip2/1.0.8**
Minor improvement after 1.53.0
---
> bzip2: minor improvement

- recipes/assimp/5.x/conanfile.py
> assimp: modernize more + bump dependencies

- recipes/pugixml/all/conandata.yml
- recipes/pugixml/all/conanfile.py
- recipes/pugixml/all/test_v1_package/CMakeLists.txt
> pugixml: use official tarballs + modernize more

- recipes/flatbuffers/all/conandata.yml
- recipes/flatbuffers/all/conanfile.py
- recipes/flatbuffers/config.yml
Specify library name and version:  **flatbuffers/23.1.21**
---
> flatbuffers: add version 23.1.21

- recipes/libwebp/all/conandata.yml
- recipes/libwebp/all/conanfile.py
> libwebp: download official tarball + fix homepage

- recipes/spirv-tools/all/conandata.yml
- recipes/spirv-tools/all/conanfile.py
- recipes/spirv-tools/all/dependencies/dependencies-1.3.239.0.yml
- recipes/spirv-tools/config.yml
> spirv-tools: add 1.3.239.0 + modernize more

- recipes/fontconfig/meson/conandata.yml
- recipes/fontconfig/meson/conanfile.py
- recipes/fontconfig/meson/test_package/CMakeLists.txt
- recipes/fontconfig/meson/test_v1_package/conanfile.py
> fontconfig >= 2.13.93: relocatable shared lib on macOS + bump meson

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/all/conanfile.py
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/3.10.0**
---
> fast_float: add version 3.10.0

- recipes/cairo/all/conandata.yml
- recipes/cairo/all/conanfile.py
- recipes/cairo/config.yml
- recipes/cairo/meson/conandata.yml
- recipes/cairo/meson/conanfile.py
> cairo: relocatable shared libs on macOS + modernize a little bit more

- recipes/muparser/all/conanfile.py
> muparser: modernize more for conan v2

- recipes/libgettext/all/conandata.yml
- recipes/libgettext/all/conanfile.py
Also refactor AutotoolsDeps workaround for msvc and clang-cl.
---
> libgettext: fix mingw clang + modernize more

- recipes/ode/all/conanfile.py
> ode: modernize more for conan v2

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/all/conanfile.py
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/***
---
> cpp-httplib: add version 0.12.0, remove older versions

- recipes/itlib/all/conandata.yml
- recipes/itlib/all/conanfile.py
- recipes/itlib/config.yml
Specify library name and version:  **itlib/1.8.3**
---
> itlib: add version 1.8.3

- recipes/apr-util/all/conandata.yml
> apr-util: add mirror

- recipes/cqrlib/all/conanfile.py
> cqrlib: modernize more for conan v2

- recipes/cpp-peglib/1.x.x/conanfile.py
- recipes/cpp-peglib/1.x.x/test_package/conanfile.py
- recipes/cpp-peglib/1.x.x/test_v1_package/CMakeLists.txt
> cpp-peglib: modernize more

- recipes/edlib/all/conanfile.py
- recipes/edlib/all/test_package/conanfile.py
- recipes/edlib/all/test_v1_package/CMakeLists.txt
- recipes/edlib/all/test_v1_package/conanfile.py
> edlib: modernize more for conan v2

- recipes/flann/all/conanfile.py
- recipes/flann/all/test_package/conanfile.py
- recipes/flann/all/test_v1_package/CMakeLists.txt
- recipes/flann/all/test_v1_package/conanfile.py
> flann: modernize more for conan v2

- recipes/libheif/all/conanfile.py
- recipes/libheif/all/test_package/conanfile.py
- recipes/libheif/all/test_v1_package/CMakeLists.txt
> libheif: modernize more for conan v2

- recipes/libspatialindex/all/conandata.yml
- recipes/libspatialindex/all/conanfile.py
- recipes/libspatialindex/all/test_package/conanfile.py
- recipes/libspatialindex/all/test_v1_package/CMakeLists.txt
- recipes/libspatialindex/all/test_v1_package/conanfile.py
> libspatialindex: use official tarball + modernize more for conan v2

- recipes/nlopt/all/conanfile.py
- recipes/nlopt/all/test_package/conanfile.py
- recipes/nlopt/all/test_v1_package/CMakeLists.txt
> nlopt: modernize more for conan v2

- recipes/snappy/all/conanfile.py
- recipes/snappy/all/test_package/conanfile.py
- recipes/snappy/all/test_v1_package/CMakeLists.txt
> snappy: modernize more for conan v2

- recipes/pistache/all/CMakeLists.txt
- recipes/pistache/all/conandata.yml
- recipes/pistache/all/conanfile.py
- recipes/pistache/all/test_package/CMakeLists.txt
- recipes/pistache/all/test_package/conanfile.py
- recipes/pistache/all/test_package/test_package.cpp
- recipes/pistache/all/test_v1_package/CMakeLists.txt
- recipes/pistache/all/test_v1_package/conanfile.py
- recipes/pistache/config.yml
Specify library name and version:  **pistache/***
---
> pistache: add version 0.0.5, support connan v2

- recipes/libsndfile/all/conandata.yml
- recipes/libsndfile/all/conanfile.py
- recipes/libsndfile/all/test_v1_package/CMakeLists.txt
- recipes/libsndfile/config.yml
Specify library name and version:  **libsndfile/1.2.0**
---
> libsndfile: add version 1.2.0, update flac

- recipes/tinyxml2/all/conanfile.py
- recipes/tinyxml2/all/test_package/conanfile.py
- recipes/tinyxml2/all/test_v1_package/CMakeLists.txt
- recipes/tinyxml2/all/test_v1_package/conanfile.py
> tinyxml2: modernize more for conan v2

- recipes/double-conversion/all/conanfile.py
- recipes/double-conversion/all/test_package/conanfile.py
- recipes/double-conversion/all/test_v1_package/CMakeLists.txt
- recipes/double-conversion/all/test_v1_package/conanfile.py
> double-conversion: modernize more for conan v2

- recipes/crc_cpp/all/conandata.yml
- recipes/crc_cpp/config.yml
Specify library name and version:  **crc_cpp/1.2.0**
Updated the version of the library to the latest upstream release.
---
> crc_cpp: Update to v1.2.0

- recipes/yasm/all/conanfile.py
- recipes/yasm/all/test_package/conanfile.py
Specify library name and version:  **yasm/1.3.0**
Cleaned up a few things and got tests to pass with Conan 2.0
---
> Yasm Conan 2.0 compatibility

- recipes/tinyspline/all/conandata.yml
- recipes/tinyspline/all/conanfile.py
- recipes/tinyspline/all/test_package/CMakeLists.txt
- recipes/tinyspline/all/test_v1_package/CMakeLists.txt
- recipes/tinyspline/all/test_v1_package/conanfile.py
- recipes/tinyspline/config.yml
Specify library name and version:  **tinyspline/***
- add version 0.6.0
- use `export_conandata_patches`
---
> tinyspline: add version 0.6.0

- recipes/pixman/all/conandata.yml
- recipes/pixman/all/conanfile.py
- recipes/pixman/all/test_package/conanfile.py
- recipes/pixman/all/test_v1_package/CMakeLists.txt
- recipes/pixman/all/test_v1_package/conanfile.py
- recipes/pixman/config.yml
> pixman: relocatable shared libs on macOS + modernize more

- recipes/coin-lemon/all/conanfile.py
- recipes/coin-lemon/all/test_package/conanfile.py
- recipes/coin-lemon/all/test_v1_package/CMakeLists.txt
> coin-lemon: modernize more for conan v2

- recipes/concurrencpp/all/conanfile.py
- recipes/concurrencpp/all/test_package/conanfile.py
- recipes/concurrencpp/all/test_v1_package/CMakeLists.txt
> concurrencpp: modernize more for conan v2

- recipes/cpp-optparse/all/conanfile.py
- recipes/cpp-optparse/all/test_package/conanfile.py
- recipes/cpp-optparse/all/test_v1_package/CMakeLists.txt
> cpp-optparse: modernize more for conan v2

- recipes/cppkafka/all/conanfile.py
- recipes/cppkafka/all/test_package/conanfile.py
- recipes/cppkafka/all/test_v1_package/CMakeLists.txt
> cppkafka: bump dependencies + modernize more for conan v2

- recipes/libnoise/all/conanfile.py
- recipes/libnoise/all/test_package/conanfile.py
- recipes/libnoise/all/test_v1_package/CMakeLists.txt
- recipes/libnoise/all/test_v1_package/conanfile.py
> libnoise: modernize more for conan v2

- recipes/crunch/all/conanfile.py
- recipes/crunch/all/test_package/conanfile.py
- recipes/crunch/all/test_v1_package/CMakeLists.txt
> crunch: modernize more for conan v2

- recipes/c-ares/all/conanfile.py
- recipes/c-ares/all/test_package/conanfile.py
> c-ares: modernize more for conan v2

- recipes/uni-algo/all/conandata.yml
- recipes/uni-algo/all/test_package/CMakeLists.txt
- recipes/uni-algo/all/test_package/test_package.cpp
- recipes/uni-algo/config.yml
Specify library name and version:  **uni-algo/0.7.0**
---
> uni-algo: add version 0.7.0

- recipes/libbacktrace/all/conanfile.py
- recipes/libbacktrace/all/test_v1_package/CMakeLists.txt
> libbacktrace: modernize more for conan v2

- recipes/libiconv/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/15475
---
> libiconv: fix MinGW clang & modernize more

- docs/community_resources.md
> Add Eric's pr Status page

- recipes/anyrpc/all/conandata.yml
- recipes/anyrpc/all/conanfile.py
> anyrpc: relocatable shared lib on macOS and modernize more

- recipes/nas/all/conandata.yml
- recipes/nas/all/conanfile.py
- recipes/nas/all/patches/0001-1.9.4-extern-variable-bugfix.patch
- recipes/nas/all/test_package/CMakeLists.txt
- recipes/nas/all/test_package/conanfile.py
- recipes/nas/all/test_v1_package/CMakeLists.txt
- recipes/nas/all/test_v1_package/conanfile.py
- recipes/nas/config.yml
Specify library name and version:  **nas/all**
With the help of @jcar87
Needs imake #15880 for v2 to pass, but v1 looks good
> nas: Port to Conan v2

- recipes/cmake/3.x.x/conandata.yml
- recipes/cmake/3.x.x/conanfile.py
- recipes/cmake/config.yml
> cmake: switch to official release tarballs again + openssl update

- recipes/brotli/all/conanfile.py
- recipes/brotli/all/test_package/conanfile.py
- recipes/brotli/all/test_v1_package/conanfile.py
> brotli: modernize more for conan v2

- recipes/fftw/all/conandata.yml
- recipes/fftw/all/conanfile.py
- recipes/fftw/all/test_package/conanfile.py
- recipes/fftw/all/test_v1_package/CMakeLists.txt
- recipes/fftw/all/test_v1_package/conanfile.py
> fftw: modernize more for conan v2

- recipes/xmlsec/all/conandata.yml
- recipes/xmlsec/all/conanfile.py
- recipes/xmlsec/all/test_package/CMakeLists.txt
- recipes/xmlsec/all/test_package/conanfile.py
- recipes/xmlsec/all/test_v1_package/CMakeLists.txt
- recipes/xmlsec/all/test_v1_package/conanfile.py
> xmlsec: use official tarballs + conan v2 support

- recipes/chipmunk2d/all/conandata.yml
- recipes/chipmunk2d/all/conanfile.py
- recipes/chipmunk2d/all/test_package/conanfile.py
- recipes/chipmunk2d/all/test_v1_package/CMakeLists.txt
> chipmunk2d: use official tarball + modernize more

- recipes/imath/all/conanfile.py
- recipes/imath/all/test_package/conanfile.py
- recipes/imath/all/test_v1_package/CMakeLists.txt
> imath: modernize more for conan v2

- recipes/jansson/all/conandata.yml
- recipes/jansson/all/conanfile.py
- recipes/jansson/all/test_package/conanfile.py
- recipes/jansson/all/test_v1_package/CMakeLists.txt
> jansson: use official tarballs + modernize more for conan v2

- recipes/openjpeg/all/conanfile.py
- recipes/openjpeg/all/test_package/conanfile.py
- recipes/openjpeg/all/test_v1_package/CMakeLists.txt
> openjpeg: modernize more for conan v2

- recipes/pcre/all/conanfile.py
- recipes/pcre/all/test_package/conanfile.py
> pcre: modernize more for conan v2

- recipes/voropp/all/conanfile.py
- recipes/voropp/all/test_v1_package/CMakeLists.txt
> voropp: modernize more for conan v2

- recipes/cjson/all/conanfile.py
> cjson: modernize more for conan v2

- recipes/sqlite3/all/conanfile.py
> sqlite3: modernize more for conan v2

- recipes/atk/all/conandata.yml
- recipes/atk/all/conanfile.py
- recipes/atk/all/test_package/CMakeLists.txt
- recipes/atk/all/test_package/conanfile.py
- recipes/atk/all/test_v1_package/CMakeLists.txt
- recipes/atk/all/test_v1_package/conanfile.py
> atk: conan v2 support

- recipes/cppfront/all/CMakeLists.txt
- recipes/cppfront/all/conanfile.py
- recipes/cppfront/all/test_package/conanfile.py
- recipes/cppfront/all/test_v1_package/conanfile.py
> cppfront: modernize more for conan v2

- recipes/tinyply/all/conanfile.py
- recipes/tinyply/all/test_package/conanfile.py
- recipes/tinyply/all/test_v1_package/CMakeLists.txt
- recipes/tinyply/all/test_v1_package/conanfile.py
> tinyply: modernize more

- recipes/lzo/all/conanfile.py
- recipes/lzo/all/test_package/conanfile.py
- recipes/lzo/all/test_v1_package/CMakeLists.txt
- recipes/lzo/all/test_v1_package/conanfile.py
> lzo: modernize more for conan v2

- recipes/libsquish/all/conanfile.py
- recipes/libsquish/all/test_package/conanfile.py
- recipes/libsquish/all/test_v1_package/CMakeLists.txt
- recipes/libsquish/all/test_v1_package/conanfile.py
> libsquish: modernize more for conan v2

- recipes/irrxml/all/conanfile.py
- recipes/irrxml/all/test_package/conanfile.py
- recipes/irrxml/all/test_v1_package/CMakeLists.txt
> irrxml: modernize more for conan v2

- recipes/pffft/all/CMakeLists.txt
- recipes/pffft/all/conanfile.py
- recipes/pffft/all/test_package/conanfile.py
- recipes/pffft/all/test_v1_package/CMakeLists.txt
> pffft: modernize more for conan v2

- recipes/sofa/all/conanfile.py
- recipes/sofa/all/test_package/conanfile.py
- recipes/sofa/all/test_v1_package/CMakeLists.txt
- recipes/sofa/all/test_v1_package/conanfile.py
> sofa: modernize more for conan v2

- recipes/cmp/all/conanfile.py
- recipes/cmp/all/test_package/conanfile.py
- recipes/cmp/all/test_v1_package/CMakeLists.txt
> cmp: modernize more for conan v2

- recipes/farmhash/all/conanfile.py
- recipes/farmhash/all/test_package/conanfile.py
- recipes/farmhash/all/test_v1_package/CMakeLists.txt
> farmhash: modernize more for conan v2

- recipes/log.c/all/conanfile.py
- recipes/log.c/all/test_package/conanfile.py
- recipes/log.c/all/test_v1_package/CMakeLists.txt
> log.c: modernize more for conan v2

- recipes/mujs/all/conanfile.py
- recipes/mujs/all/test_package/conanfile.py
- recipes/mujs/all/test_v1_package/CMakeLists.txt
> mujs: modernize more for conan v2

- recipes/ntv2/all/conanfile.py
- recipes/ntv2/all/test_package/conanfile.py
- recipes/ntv2/all/test_v1_package/CMakeLists.txt
- recipes/ntv2/all/test_v1_package/conanfile.py
> ntv2: modernize more for conan v2

- recipes/poly2tri/all/conanfile.py
- recipes/poly2tri/all/test_package/conanfile.py
- recipes/poly2tri/all/test_v1_package/CMakeLists.txt
- recipes/poly2tri/all/test_v1_package/conanfile.py
> poly2tri: modernize more for conan v2

- recipes/dav1d/all/conanfile.py
- recipes/dav1d/all/test_package/conanfile.py
- recipes/dav1d/all/test_v1_package/CMakeLists.txt
- recipes/dav1d/all/test_v1_package/conanfile.py
> dav1d: modernize more for conan v2

- recipes/bigint/all/conanfile.py
- recipes/bigint/all/test_package/conanfile.py
- recipes/bigint/all/test_v1_package/CMakeLists.txt
- recipes/bigint/all/test_v1_package/conanfile.py
> bigint: modernize more for conan v2

- recipes/geographiclib/all/conandata.yml
- recipes/geographiclib/all/conanfile.py
- recipes/geographiclib/all/test_package/conanfile.py
- recipes/geographiclib/all/test_v1_package/CMakeLists.txt
- recipes/geographiclib/all/test_v1_package/conanfile.py
> geographiclib: modernize more for conan v2

- recipes/beauty/all/conanfile.py
- recipes/beauty/all/test_package/conanfile.py
- recipes/beauty/all/test_v1_package/CMakeLists.txt
- recipes/beauty/all/test_v1_package/conanfile.py
> beauty: modernize more for conan v2

- recipes/asyncplusplus/all/conanfile.py
- recipes/asyncplusplus/all/test_package/conanfile.py
- recipes/asyncplusplus/all/test_v1_package/CMakeLists.txt
- recipes/asyncplusplus/all/test_v1_package/conanfile.py
> asyncplusplus: modernize more for conan v2

- recipes/fcl/all/conanfile.py
- recipes/fcl/all/test_package/conanfile.py
- recipes/fcl/all/test_v1_package/CMakeLists.txt
- recipes/fcl/all/test_v1_package/conanfile.py
> fcl: modernize more for conan v2

- recipes/glbinding/all/conanfile.py
- recipes/glbinding/all/test_package/conanfile.py
- recipes/glbinding/all/test_v1_package/CMakeLists.txt
- recipes/glbinding/all/test_v1_package/conanfile.py
> glbinding: modernize more for conan v2

- recipes/octomap/all/conanfile.py
- recipes/octomap/all/test_package/conanfile.py
- recipes/octomap/all/test_v1_package/CMakeLists.txt
- recipes/octomap/all/test_v1_package/conanfile.py
> octomap: modernize more for conan v2

- recipes/semver.c/all/conanfile.py
- recipes/semver.c/all/test_package/conanfile.py
- recipes/semver.c/all/test_v1_package/CMakeLists.txt
> semver.c: modernize more for conan v2

- recipes/antlr4-cppruntime/all/conanfile.py
- recipes/antlr4-cppruntime/all/test_v1_package/CMakeLists.txt
> antlr4-cppruntime: relocatable shared lib on macOS and modernize more

- recipes/aravis/all/conandata.yml
- recipes/aravis/all/conanfile.py
- recipes/aravis/all/test_package/CMakeLists.txt
- recipes/aravis/all/test_package/conanfile.py
- recipes/aravis/all/test_v1_package/CMakeLists.txt
- recipes/aravis/all/test_v1_package/conanfile.py
> aravis: conan v2 support

- recipes/aruco/3.x.x/CMakeLists.txt
- recipes/aruco/3.x.x/conanfile.py
- recipes/aruco/3.x.x/test_package/CMakeLists.txt
- recipes/aruco/3.x.x/test_package/conanfile.py
- recipes/aruco/3.x.x/test_v1_package/CMakeLists.txt
- recipes/aruco/3.x.x/test_v1_package/conanfile.py
> aruco: conan v2 support

- recipes/astc-codec/all/CMakeLists.txt
- recipes/astc-codec/all/conandata.yml
- recipes/astc-codec/all/conanfile.py
- recipes/astc-codec/all/patches/0001-fix-cmake.patch
- recipes/astc-codec/all/test_package/CMakeLists.txt
- recipes/astc-codec/all/test_package/conanfile.py
- recipes/astc-codec/all/test_v1_package/CMakeLists.txt
- recipes/astc-codec/all/test_v1_package/conanfile.py
> astc-codec: conan v2 support

- recipes/acl/all/conandata.yml
- recipes/acl/all/conanfile.py
- recipes/acl/all/test_package/CMakeLists.txt
- recipes/acl/all/test_package/conanfile.py
- recipes/acl/all/test_v1_package/CMakeLists.txt
- recipes/acl/all/test_v1_package/conanfile.py
> acl: conan v2 support

- recipes/highs/all/conandata.yml
- recipes/highs/all/conanfile.py
- recipes/highs/all/patches/0001-missing-includes-msvc15-1.4.2.patch
- recipes/highs/all/test_package/CMakeLists.txt
- recipes/highs/all/test_package/conanfile.py
- recipes/highs/all/test_package/main.cpp
- recipes/highs/all/test_v1_package/CMakeLists.txt
- recipes/highs/all/test_v1_package/conanfile.py
- recipes/highs/config.yml
Specify library name and version:  **highs/1.4.2**
I am not the author of this library. We use linear programming solvers at my company and thus we created this conan package.
---
> Add HiGHS linear programming solver

- recipes/tgc/all/conanfile.py
- recipes/tgc/all/test_package/conanfile.py
- recipes/tgc/all/test_v1_package/CMakeLists.txt
> tgc: modernize more for conan v2

- recipes/tiny-bignum-c/all/conanfile.py
- recipes/tiny-bignum-c/all/test_package/conanfile.py
- recipes/tiny-bignum-c/all/test_v1_package/CMakeLists.txt
> tiny-bignum-c: modernize more for conan v2

- recipes/tiny-regex-c/all/conanfile.py
- recipes/tiny-regex-c/all/test_package/conanfile.py
- recipes/tiny-regex-c/all/test_v1_package/CMakeLists.txt
> tiny-regex-c: modernize more for conan v2

- recipes/oniguruma/all/conanfile.py
- recipes/oniguruma/all/test_package/conanfile.py
- recipes/oniguruma/all/test_v1_package/CMakeLists.txt
- recipes/oniguruma/all/test_v1_package/conanfile.py
> oniguruma: modernize more for conan v2

- recipes/parson/all/conanfile.py
- recipes/parson/all/test_package/conanfile.py
- recipes/parson/all/test_v1_package/CMakeLists.txt
- recipes/parson/all/test_v1_package/conanfile.py
> parson: modernize more for conan v2

- recipes/entityx/all/conanfile.py
- recipes/entityx/all/test_package/conanfile.py
- recipes/entityx/all/test_v1_package/CMakeLists.txt
> entityx: modernize more for conan v2

- recipes/erkir/all/conanfile.py
- recipes/erkir/all/test_v1_package/CMakeLists.txt
> erkir: modernize more for conan v2

- recipes/dataframe/all/conanfile.py
- recipes/dataframe/all/test_package/conanfile.py
> dataframe: modernize more for conan v2

- recipes/exiv2/all/conandata.yml
- recipes/exiv2/all/conanfile.py
- recipes/exiv2/all/test_package/conanfile.py
- recipes/exiv2/all/test_v1_package/CMakeLists.txt
> exiv2: use official tarballs + modernize more for conan v2

- recipes/fast-cdr/all/conanfile.py
- recipes/fast-cdr/all/test_v1_package/CMakeLists.txt
> fast-cdr: modernize more for conan v2

- recipes/abseil/all/conandata.yml
- recipes/abseil/all/conanfile.py
- recipes/abseil/all/test_package/CMakeLists.txt
- recipes/abseil/all/test_v1_package/CMakeLists.txt
- recipes/abseil/config.yml
Specify library name and version:  **abseil/20230125.0**
---
> abseil: add version 20230125.0

- recipes/ezc3d/all/conanfile.py
- recipes/ezc3d/all/test_package/conanfile.py
- recipes/ezc3d/all/test_v1_package/CMakeLists.txt
- recipes/ezc3d/all/test_v1_package/conanfile.py
> ezc3d: modernize more for conan v2

- recipes/gflags/all/conanfile.py
- recipes/gflags/all/test_package/conanfile.py
- recipes/gflags/all/test_v1_package/CMakeLists.txt
> gflags: modernize more for conan v2

- recipes/glog/all/conanfile.py
- recipes/glog/all/test_package/CMakeLists.txt
- recipes/glog/all/test_v1_package/CMakeLists.txt
> glog: modernize more for conan v2

- recipes/kissfft/all/conanfile.py
- recipes/kissfft/all/test_package/conanfile.py
- recipes/kissfft/all/test_v1_package/CMakeLists.txt
> kissfft: modernize more for conan v2

- recipes/hdf5/all/conanfile.py
I had cmake_build_modules in the wrong spot.
> hdf5: cmake_build_modules property has to be in the root self.cpp_info

- recipes/stc/all/conandata.yml
- recipes/stc/all/conanfile.py
- recipes/stc/all/test_v1_package/CMakeLists.txt
- recipes/stc/config.yml
Specify library name and version:  **stc/4.1.1**
---
> stc: add version 4.1.1

- recipes/g3log/all/conandata.yml
- recipes/g3log/all/conanfile.py
- recipes/g3log/config.yml
Specify library name and version:  **g3log/2.2**
---
> g3log: add version 2.2

- recipes/roaring/all/conandata.yml
- recipes/roaring/all/conanfile.py
- recipes/roaring/config.yml
Specify library name and version:  **roaring/***
---
> roaring: add version 0.9.6, remove older versions

- recipes/fft/all/conanfile.py
- recipes/fft/all/test_package/conanfile.py
- recipes/fft/all/test_v1_package/CMakeLists.txt
> fft: modernize more for conan v2

- recipes/inih/all/conanfile.py
- recipes/inih/all/test_package/conanfile.py
- recipes/inih/all/test_v1_package/CMakeLists.txt
- recipes/inih/all/test_v1_package/conanfile.py
> inih: modernize more for conan v2

- recipes/libccd/all/conanfile.py
- recipes/libccd/all/test_package/conanfile.py
- recipes/libccd/all/test_v1_package/CMakeLists.txt
- recipes/libccd/all/test_v1_package/conanfile.py
> libccd: modernize more for conan v2

- recipes/minitrace/all/conanfile.py
- recipes/minitrace/all/test_package/conanfile.py
- recipes/minitrace/all/test_v1_package/CMakeLists.txt
- recipes/minitrace/all/test_v1_package/conanfile.py
> minitrace: modernize more for conan v2

- recipes/freetype/all/conandata.yml
- recipes/freetype/all/conanfile.py
- recipes/freetype/all/patches/2.13.0-0001-fix-fallthrough.patch
- recipes/freetype/config.yml
> freetype: add 2.13.0 + modernize more for conan v2

- recipes/graphene/all/conandata.yml
- recipes/graphene/all/conanfile.py
- recipes/graphene/all/test_v1_package/CMakeLists.txt
- recipes/graphene/config.yml
> graphene: relocatable shared lib on macOS + modernize more for conan v2

- recipes/ade/all/conanfile.py
- recipes/ade/all/test_package/conanfile.py
- recipes/ade/all/test_v1_package/CMakeLists.txt
> ade: modernize more for conan v2

- recipes/asmjit/all/conanfile.py
- recipes/asmjit/all/test_package/conanfile.py
> asmjit: modernize more for conan v2

- recipes/pulseaudio/all/conanfile.py
- recipes/pulseaudio/all/test_package/conanfile.py
- recipes/pulseaudio/all/test_v1_package/CMakeLists.txt
Specify library name and version:  **pulseaudio/all**
> pulseaudio: Fix double delete and modernize test_package

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Specify library name and version:  **glib/2.75.3**
---
> glib 2.75.3

- recipes/c4core/all/conandata.yml
- recipes/c4core/all/conanfile.py
> c4core: modernize more for conan v2

- recipes/catch2/3.x.x/conanfile.py
> catch2 3.x: modernize more for conan v2

- recipes/cnpy/all/conanfile.py
> cnpy: modernize more for conan v2

- recipes/cyclonedds/all/conanfile.py
> cyclonedds: modernize more for conan v2

- docs/changelog.md
We are bringing some fixes here!
> [docs] Update changelog 14-February-2023 - 15:32 CET

- recipes/open-dis-cpp/all/conandata.yml
- recipes/open-dis-cpp/all/conanfile.py
- recipes/open-dis-cpp/all/test_package/CMakeLists.txt
- recipes/open-dis-cpp/all/test_package/conanfile.py
- recipes/open-dis-cpp/all/test_package/test_package.cpp
- recipes/open-dis-cpp/all/test_v1_package/CMakeLists.txt
- recipes/open-dis-cpp/all/test_v1_package/conanfile.py
- recipes/open-dis-cpp/config.yml
Specify library name and version:  open-dis-cpp/1.0.1
Submitting this PR to incorporate open-dis-cpp to support broader distribution and utilization of the library among multiple projects and the wider user community. This library implements a widely utilized IEEE standard leveraged in distributed simulation applications.
Fixes #15775 
---
> open-dis-cpp: Add new recipe

- recipes/fastpfor/all/CMakeLists.txt
- recipes/fastpfor/all/conandata.yml
- recipes/fastpfor/all/conanfile.py
- recipes/fastpfor/all/patches/cci.20221225-0001-fix-cmake.patch
- recipes/fastpfor/all/test_package/CMakeLists.txt
- recipes/fastpfor/all/test_package/conanfile.py
- recipes/fastpfor/all/test_package/test_package.cpp
- recipes/fastpfor/all/test_v1_package/CMakeLists.txt
- recipes/fastpfor/all/test_v1_package/conanfile.py
- recipes/fastpfor/config.yml
Specify library name and version:  **fastpfor/***
---
> fastpfor: add cci.20221225, support conan v2

- recipes/jbig/all/conanfile.py
- recipes/jbig/all/test_package/conanfile.py
- recipes/jbig/all/test_v1_package/CMakeLists.txt
- recipes/jbig/all/test_v1_package/conanfile.py
> jbig: modernize more for conan v2

- recipes/butteraugli/all/conanfile.py
> butteraugli: modernize more for conan v2

- recipes/xorg-macros/all/conandata.yml
- recipes/xorg-macros/all/conanfile.py
- recipes/xorg-macros/all/test_package/conanfile.py
- recipes/xorg-macros/all/test_package/src/configure.ac
- recipes/xorg-macros/all/test_v1_package/conanfile.py
- recipes/xorg-macros/all/test_v1_package/configure.ac
Specify library name and version:  **xorg-macros/all**
Needed by https://github.com/conan-io/conan-center-index/pull/15881
> xorg-macros v2 migration

- recipes/cmocka/all/conanfile.py
- recipes/cmocka/all/test_package/conanfile.py
- recipes/cmocka/all/test_v1_package/CMakeLists.txt
> cmocka: modernize more for conan v2

- recipes/openmesh/all/conanfile.py
- recipes/openmesh/all/test_package/conanfile.py
- recipes/openmesh/all/test_v1_package/CMakeLists.txt
- recipes/openmesh/all/test_v1_package/conanfile.py
> openmesh: modernize more for conan v2

- recipes/opengrm/all/conanfile.py
- recipes/opengrm/all/test_package/CMakeLists.txt
- recipes/opengrm/all/test_package/conanfile.py
- recipes/opengrm/all/test_v1_package/CMakeLists.txt
- recipes/opengrm/all/test_v1_package/conanfile.py
> opengrm: conan v2 support + do not suggest unofficial cmake names

- recipes/physfs/all/conanfile.py
- recipes/physfs/all/test_package/conanfile.py
- recipes/physfs/all/test_v1_package/CMakeLists.txt
- recipes/physfs/all/test_v1_package/conanfile.py
> physfs: modernize more for conan v2

- recipes/avcpp/all/conanfile.py
- recipes/avcpp/all/test_v1_package/CMakeLists.txt
> avcpp: modernize more for conan v2

- recipes/enet/all/conandata.yml
- recipes/enet/all/conanfile.py
- recipes/enet/all/test_package/conanfile.py
- recipes/enet/all/test_v1_package/CMakeLists.txt
> enet: modernize more for conan v2

- recipes/fribidi/all/conanfile.py
- recipes/fribidi/all/test_package/conanfile.py
- recipes/fribidi/all/test_v1_package/CMakeLists.txt
> fribidi: modernize more for conan v2

- recipes/libaom-av1/all/conanfile.py
- recipes/libaom-av1/all/test_package/conanfile.py
- recipes/libaom-av1/all/test_v1_package/CMakeLists.txt
> libaom-av1: modernize more for conan v2

- recipes/lzfse/all/conanfile.py
- recipes/lzfse/all/test_package/conanfile.py
- recipes/lzfse/all/test_v1_package/CMakeLists.txt
- recipes/lzfse/all/test_v1_package/conanfile.py
> lzfse: modernize more for conan v2

- recipes/oatpp/all/conanfile.py
- recipes/oatpp/all/test_package/conanfile.py
- recipes/oatpp/all/test_v1_package/CMakeLists.txt
> oatpp: modernize more for conan v2

- recipes/onnx/all/conanfile.py
- recipes/onnx/all/test_package/conanfile.py
- recipes/onnx/all/test_v1_package/CMakeLists.txt
> onnx: modernize more for conan v2

- recipes/openddl-parser/all/conanfile.py
- recipes/openddl-parser/all/test_package/conanfile.py
- recipes/openddl-parser/all/test_v1_package/CMakeLists.txt
> openddl-parser: modernize more for conan v2

- recipes/polylineencoder/all/conanfile.py
- recipes/polylineencoder/all/test_package/conanfile.py
- recipes/polylineencoder/all/test_v1_package/CMakeLists.txt
- recipes/polylineencoder/all/test_v1_package/conanfile.py
> polylineencoder: modernize more for conan v2

- recipes/geotrans/all/conanfile.py
> geotrans: modernize more for conan v2

- recipes/libalsa/all/conanfile.py
> libalsa: modernize more for conan v2

- recipes/libunwind/all/conanfile.py
> libunwind: modernize more for conan v2

- recipes/libelf/all/conanfile.py
> libelf: modernize more for conan v2

- recipes/xlnt/all/conanfile.py
> xlnt: modernize more for conan v2

- recipes/kmod/all/conandata.yml
- recipes/kmod/all/conanfile.py
> kmod: use official tarballs + modernize more for conan v2

- recipes/libmysqlclient/all/conanfile.py
Specify library name and version:  **libmysqlclient/***
---
> libmysqlclient: bump reqs

- recipes/libpq/all/conanfile.py
Specify library name and version:  **libpq/all**
Fixes issues on Windows with Conan 2.0 when `with_openssl` is `True`.
* Retrieve aggregated system deps using `self.dependencies`
* Reference OpenSSL components by component name, rather than by lib order
> libpq: fix dependency access on Windows with Conan 2.0

- recipes/gtest/all/conanfile.py
> gtest: modernize more for conan v2

- recipes/odbc/all/conanfile.py
> odbc: modernize more for conan v2

- recipes/sentry-breakpad/all/conandata.yml
- recipes/sentry-breakpad/all/conanfile.py
- recipes/sentry-breakpad/config.yml
> [sentry-breakpad/0.6.0] and remove old versions

- recipes/sentry-crashpad/all/conandata.yml
- recipes/sentry-crashpad/all/conanfile.py
- recipes/sentry-crashpad/config.yml
> [sentry-crashpad/0.6.0] + remove old versions

- recipes/libyaml/all/conanfile.py
- recipes/libyaml/all/test_package/conanfile.py
- recipes/libyaml/all/test_v1_package/CMakeLists.txt
> libyaml: modernize more for conan v2

- recipes/libselinux/all/conanfile.py
> libselinux: modernize more for conan v2

- recipes/freeimage/all/conanfile.py
- recipes/freeimage/all/patches/014_no_auto_ptr.patch
- recipes/freeimage/all/test_package/conanfile.py
- recipes/freeimage/all/test_v1_package/CMakeLists.txt
> freeimage: modernize more for conan v2

- recipes/roaring/all/conandata.yml
- recipes/roaring/config.yml
Specify library name and version:  **roaring/0.9.8**
---
> roaring: add version 0.9.8

- recipes/openapi-generator/all/conandata.yml
- recipes/openapi-generator/config.yml
> [openapi-generator] bump to 6.4.0 and remove old versions

- recipes/abseil/all/conandata.yml
- recipes/abseil/config.yml
Specify library name and version:  **abseil/20230125.1**
---
> abseil: add version 20230125.1

- recipes/vk-bootstrap/all/conandata.yml
- recipes/vk-bootstrap/all/conanfile.py
- recipes/vk-bootstrap/all/test_v1_package/CMakeLists.txt
- recipes/vk-bootstrap/config.yml
> vk-bootstrap: add 0.7 + modernize more for conan v2

- recipes/bullet3/all/conandata.yml
- recipes/bullet3/all/conanfile.py
- recipes/bullet3/all/test_package/conanfile.py
- recipes/bullet3/all/test_v1_package/CMakeLists.txt
- recipes/bullet3/config.yml
> bullet3: add 3.25 + modernize more

- recipes/yaml-cpp/all/conanfile.py
- recipes/yaml-cpp/all/test_package/conanfile.py
> yaml-cpp: modernize more for conan v2

- .c3i/conan_v2_ready_references.yml
- .c3i/config_v1.yml
- .c3i/config_v2.yml
- Conan v2 build configs with cppstd values.
- Add allow list for conan v2 ready references (to use in a near future).
- Cleanup
> [config] Add Conan v2 build configs with cppstd & conan v2 ready references list

- .c3i/config_v2.yml
> [config] Fix armv8 cross-compilation

- docs/changelog.md
> Add new changelog - Feb 2023

- .c3i/config_v2.yml
It's time to publish conan v2 packages!!
> [config] Conan v2: point main repo to the central repository

- docs/changelog.md
> [docs] Update changelog 21-2-2023

- recipes/xorg-makedepend/all/conanfile.py
- recipes/xorg-makedepend/all/test_package/conanfile.py
- recipes/xorg-makedepend/all/test_v1_package/conanfile.py
- recipes/xorg-makedepend/all/test_v1_package/test_package.c
- recipes/xorg-makedepend/all/test_v1_package/test_package.h
Specify library name and version:  **xorg-makedepend/all**
> Port xorg-makedepend to v2

- .c3i/conan_v2_ready_references.yml
At least the very first ones 😄
> [config] Add some conan v2 ready references to the list

- recipes/xorg-gccmakedep/all/conanfile.py
- recipes/xorg-gccmakedep/all/test_package/conanfile.py
- recipes/xorg-gccmakedep/all/test_v1_package/Makefile
- recipes/xorg-gccmakedep/all/test_v1_package/conanfile.py
- recipes/xorg-gccmakedep/all/test_v1_package/test_package.c
- recipes/xorg-gccmakedep/all/test_v1_package/test_package.h
Specify library name and version:  **xorg-gccmakedep/all**
> xorg-gccmakedep: Port to v2

- .c3i/config_v2.yml
> [config v2] Add intermediate epochs from config v1

- .c3i/authorized_users.yml
The PR #16242 can't be merged until having the author as authorized user.
---
> [access request] Add user tannerbitz to allow merging its PR

- recipes/libtool/all/conanfile.py
- recipes/libtool/all/test_package/conanfile.py
- recipes/libtool/all/test_v1_package/conanfile.py
Specify library name and version:  **libtool/all**
* Add missing empty line
* Use f strings
* Clarify comment for m4 dependency
* `test_v1_package` -> restore invocations to autoreconf
> libtool: recipe and test_package minor cleanup

- recipes/wayland-protocols/all/conanfile.py
Specify library name and version:  **wayland-protocols/all**
> wayland-protocols: fix topics attribute

- recipes/glog/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/16337
---
> glog: fix transitive traits to gflags & `_cmake_new_enough()` for conan v2

- recipes/celero/all/conanfile.py
- recipes/celero/all/test_package/conanfile.py
- recipes/celero/all/test_v1_package/CMakeLists.txt
> celero: modernize more for conan v2

- recipes/clhep/all/conanfile.py
- recipes/clhep/all/test_package/conanfile.py
- recipes/clhep/all/test_v1_package/CMakeLists.txt
> clhep: modernize more for conan v2

- recipes/cwalk/all/conanfile.py
- recipes/cwalk/all/test_package/conanfile.py
- recipes/cwalk/all/test_v1_package/CMakeLists.txt
> cwalk: modernize more for conan v2

- recipes/aaplus/all/conanfile.py
> aaplus: modernize more for conan v2

- recipes/kuba-zip/all/conanfile.py
- recipes/kuba-zip/all/test_package/conanfile.py
- recipes/kuba-zip/all/test_v1_package/CMakeLists.txt
> kuba-zip: modernize more for conan v2

- recipes/aws-crt-cpp/all/conanfile.py
- recipes/aws-crt-cpp/all/test_v1_package/CMakeLists.txt
> aws-crt-cpp: modernize more for conan v2

- recipes/backward-cpp/all/conanfile.py
> backward-cpp: modernize more for conan v2

- recipes/charls/all/conanfile.py
- recipes/charls/all/test_package/conanfile.py
> charls: modernize more for conan v2

- recipes/blend2d/all/conandata.yml
- recipes/blend2d/all/conanfile.py
> blend2d: modernize more for conan v2

- recipes/imgui/all/conandata.yml
- recipes/imgui/all/conanfile.py
- recipes/imgui/config.yml
Specify library name and version:  **imgui/1.89.3**
---
> imgui: add version 1.89.3

- recipes/cyrus-sasl/all/conanfile.py
> cyrus-sasl: modernize more for conan v2

- recipes/leveldb/all/conanfile.py
- recipes/leveldb/all/test_v1_package/CMakeLists.txt
> leveldb: modernize more for conan v2

- recipes/async_simple/all/conandata.yml
- recipes/async_simple/all/conanfile.py
- recipes/async_simple/all/test_package/CMakeLists.txt
- recipes/async_simple/all/test_package/conanfile.py
- recipes/async_simple/all/test_package/test_package.cpp
- recipes/async_simple/all/test_v1_package/CMakeLists.txt
- recipes/async_simple/all/test_v1_package/conanfile.py
- recipes/async_simple/config.yml
Specify library name and version:  **async_simple/1.0.0**
---
> add async_simple

- recipes/m4/all/conanfile.py
> m4: generate binaries

- recipes/univalue/all/conanfile.py
> univalue: modernize more for conan v2

- recipes/simdjson/all/conanfile.py
- recipes/simdjson/all/test_package/conanfile.py
> simdjson: modernize more for conan v2

- recipes/draco/all/conanfile.py
- recipes/draco/all/test_v1_package/CMakeLists.txt
> draco: modernize more for conan v2

- recipes/catch2/3.x.x/conandata.yml
- recipes/catch2/config.yml
Specify library name and version:  **catch2/3.3.2**
Try to close https://github.com/conan-io/conan-center-index/issues/16322.
---
> catch2: add version 3.3.2

- recipes/picobench/all/conandata.yml
- recipes/picobench/all/conanfile.py
- recipes/picobench/all/patches/2.02-0001-add-install.patch
- recipes/picobench/all/test_package/conanfile.py
- recipes/picobench/all/test_v1_package/CMakeLists.txt
- recipes/picobench/config.yml
Specify library name and version:  **picobench/2.02**
---
> picobench: add version 2.02

- recipes/lodepng/all/conanfile.py
- recipes/lodepng/all/test_package/conanfile.py
- recipes/lodepng/all/test_v1_package/CMakeLists.txt
> lodepng: modernize more for conan v2

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Specify library name and version:  **glib/2.76.0**
---
> glib 2.76.0

- recipes/out_ptr/all/conanfile.py
- recipes/out_ptr/all/test_package/conanfile.py
- recipes/out_ptr/all/test_v1_package/CMakeLists.txt
- recipes/out_ptr/all/test_v1_package/conanfile.py
> out_ptr: modernize more for conan v2

- recipes/cryptopp/all/conanfile.py
**cryptopp/all**
Fix an obvious typo
> cryptopp: commit 479d2eb regression (typo in set_property)

- recipes/libnuma/all/conanfile.py
> libnuma: modernize more for conan v2

- recipes/libgcrypt/all/conanfile.py
> libgcrypt: modernize more for conan v2

- recipes/joltphysics/all/conanfile.py
> joltphysics: modernize more for conan v2

- recipes/lerc/all/conanfile.py
- recipes/lerc/all/test_package/conanfile.py
> lerc: modernize more for conan v2

- recipes/libtar/all/conanfile.py
- recipes/libtar/all/test_package/conanfile.py
> libtar: modernize more for conan v2

- recipes/libuuid/all/conanfile.py
> libuuid: modernize more for conan v2

- recipes/libev/all/conanfile.py
> libev: modernize more for conan v2

- recipes/libtiff/all/conanfile.py
> libtiff: bump dependencies + add package_type

- recipes/xtrans/all/conanfile.py
Specify library name and version:  **xtrans/***
---
> xtrans: conan V2 compatibility

- recipes/h3/all/conanfile.py
- recipes/h3/all/test_package/conanfile.py
> h3: modernize more for conan v2

- recipes/aaf/all/conanfile.py
> aaf: modernize more for conan v2

- recipes/libfuse/2.x.x/conanfile.py
- recipes/libfuse/all/conanfile.py
> libfuse: modernize more for conan v2
