- recipes/wslay/all/conanfile.py
- recipes/wslay/all/test_v1_package/CMakeLists.txt
> wslay: modernize more for conan v2

- recipes/md4qt/all/conandata.yml
- recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.0.5**
---
> md4qt: bump version to 2.0.5.

- recipes/libqrencode/all/conanfile.py
- recipes/libqrencode/all/test_package/conanfile.py
- recipes/libqrencode/all/test_v1_package/CMakeLists.txt
> libqrencode: modernize more for conan v2

- recipes/mbedtls/all/conanfile.py
> mbedtls: modernize more for conan v2

- recipes/libarchive/all/conanfile.py
> libarchive: modernize more for conan v2

- recipes/libmount/all/conanfile.py
> libmount: modernize more for conan v2

- recipes/libsmacker/all/conanfile.py
> libsmacker: modernize more for conan v2

- recipes/libcds/all/conanfile.py
- recipes/libcds/all/test_package/conanfile.py
- recipes/libcds/all/test_v1_package/CMakeLists.txt
> libcds: modernize more for conan v2

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.12.1**
---
> cpp-httplib: add version 0.12.1

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.41.1**
---
> sqlite3: add version 3.41.1

- recipes/libcurl/all/conandata.yml
- recipes/libcurl/all/conanfile.py
- recipes/libcurl/config.yml
Specify library name and version:  **libcurl/7.88.0**
---
> libcurl: add 7.88.1

- recipes/dbus/1.x.x/conanfile.py
- recipes/dbus/1.x.x/test_package/conanfile.py
> dbus: modernize more for conan v2

- recipes/glibmm/all/conanfile.py
- recipes/glibmm/all/test_package/conanfile.py
> glibmm: modernize more for conan v2

- recipes/cpr/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/16507
---
> cpr: modernize more

- recipes/libpq/all/conandata.yml
- recipes/libpq/all/conanfile.py
- recipes/libpq/all/patches/14.7/002-mingw-build-static-libraries.patch
- recipes/libpq/config.yml
Specify library name and version:  **libpq/14.7**
Additionally, update the openssl dependency.
---
> libpq: add 14.7

- recipes/uriparser/all/conanfile.py
- recipes/uriparser/all/test_v1_package/CMakeLists.txt
closes https://github.com/conan-io/conan-center-index/issues/16525
---
> uriparser: modernize more for conan v2 (and generate v2 packages)

- recipes/termcap/all/conanfile.py
Mainly to generate v2 packages for https://github.com/conan-io/conan-center-index/pull/16435
---
> termcap: add package_type (and generate v2 packages)

- recipes/libsndfile/all/conanfile.py
- recipes/libsndfile/all/test_package/conanfile.py
- fix topics (must be a tuple for conan v2)
- use export_conandata_patches()
- bump mpg123
- remove CMP0077 injection (require conan >=1.54.0)
I also need pre-build v2 packages for https://github.com/conan-io/conan-center-index/pull/15965 & https://github.com/conan-io/conan-center-index/pull/16075
---
> libsndfile: modernize more for conan v2

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/all/conanfile.py
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/3.10.1**
---
> fast_float: add version 3.10.1

- recipes/vaapi/all/conanfile.py
- recipes/vaapi/all/test_package/CMakeLists.txt
- recipes/vaapi/all/test_package/conanfile.py
- recipes/vaapi/all/test_v1_package/CMakeLists.txt
- recipes/vaapi/all/test_v1_package/conanfile.py
Specify library name and version:  **vaapi/***
---
> vaapi: conan V2 compatibility

- recipes/mcap/all/conandata.yml
- recipes/mcap/all/conanfile.py
- recipes/mcap/config.yml
Specify library name and version:  **mcap/***
---
> mcap: add version 1.0.0, update zstd

- recipes/msgpack-cxx/all/conandata.yml
- recipes/msgpack-cxx/all/conanfile.py
- recipes/msgpack-cxx/config.yml
Specify library name and version:  **mscpack-cxx/6.0.0**
---
> msgpack-cxx: add version 6.0.0

- recipes/fxdiv/all/conanfile.py
- recipes/fxdiv/all/test_package/conanfile.py
- recipes/fxdiv/all/test_v1_package/CMakeLists.txt
needed to pass v2 pipeline in https://github.com/conan-io/conan-center-index/pull/16388
---
> fxdiv: modernize more for conan v2 and generate v2 packages

- docs/package_templates/cmake_package/all/conanfile.py
- docs/package_templates/header_only/all/conanfile.py
- docs/package_templates/meson_package/all/conanfile.py
- docs/package_templates/msbuild_package/all/conanfile.py
- docs/package_templates/prebuilt_tool_package/all/conanfile.py
> docs: make sure package type is set

- .c3i/config_v1.yml
https://github.com/conan-io/conan-center-index/pull/14855#issuecomment-1458484594
Config!
> config: add ceres-solver to large pod

- recipes/benchmark/all/conanfile.py
> benchmark: fix `_cmake_new_enough()` for conan v2

- recipes/drflac/all/conanfile.py
- recipes/drflac/all/test_package/CMakeLists.txt
- recipes/drflac/all/test_package/conanfile.py
- recipes/drflac/all/test_v1_package/CMakeLists.txt
> drflac: modernize more for conan v2

- recipes/mppp/all/conandata.yml
- recipes/mppp/all/conanfile.py
> mppp: modernize more for conan v2

- recipes/jfalcou-eve/all/conandata.yml
- recipes/jfalcou-eve/all/conanfile.py
- recipes/jfalcou-eve/all/test_package/CMakeLists.txt
- recipes/jfalcou-eve/all/test_v1_package/CMakeLists.txt
- recipes/jfalcou-eve/config.yml
Specify library name and version:  **jfalcou-eve/***
- add version v2023.02.15
- sort version 
---
> jfalcou-eve: add version v2023.02.15

- recipes/gmp/all/conanfile.py
> gmp: modernize more for conan v2

- recipes/unqlite/all/conanfile.py
- recipes/unqlite/all/test_package/conanfile.py
- recipes/unqlite/all/test_v1_package/CMakeLists.txt
- recipes/unqlite/all/test_v1_package/conanfile.py
> unqlite: modernize more for conan v2

- recipes/mdspan/all/conandata.yml
- recipes/mdspan/all/conanfile.py
- recipes/mdspan/all/test_package/CMakeLists.txt
- recipes/mdspan/all/test_package/conanfile.py
- recipes/mdspan/all/test_package/test_package.cpp
- recipes/mdspan/all/test_v1_package/CMakeLists.txt
- recipes/mdspan/all/test_v1_package/conanfile.py
- recipes/mdspan/config.yml
Specify library name and version:  **mdspan/***
- add version 0.5.0
---
> mdspan: add version 0.5.0, support conan v2

- recipes/tlx/all/conanfile.py
- recipes/tlx/all/test_package/conanfile.py
- recipes/tlx/all/test_v1_package/CMakeLists.txt
> tlx: modernize more for conan v2

- recipes/openal-soft/all/conanfile.py
- recipes/openal-soft/all/test_package/CMakeLists.txt
It also allows to generate v2 packages for https://github.com/conan-io/conan-center-index/pull/16387
---
> openal-soft: add package_type + fix OPENAL_VERSION_STRING in CMakeDeps

- recipes/libpciaccess/all/conanfile.py
- recipes/libpciaccess/all/test_package/conanfile.py
- recipes/libpciaccess/all/test_v1_package/CMakeLists.txt
> libpciaccess: modernize more for conan v2

- recipes/rttr/all/conanfile.py
- recipes/rttr/all/test_package/conanfile.py
- recipes/rttr/all/test_v1_package/CMakeLists.txt
> rttr: modernize more for conan v2

- recipes/serd/all/conanfile.py
- recipes/serd/all/test_package/conanfile.py
- recipes/serd/all/test_v1_package/CMakeLists.txt
> serd: modernize more for conan v2

- recipes/qhull/all/conanfile.py
- recipes/qhull/all/test_package/conanfile.py
- recipes/qhull/all/test_v1_package/CMakeLists.txt
> qhull: modernize more for conan v2

- recipes/librttopo/all/conanfile.py
- recipes/librttopo/all/test_package/conanfile.py
- recipes/librttopo/all/test_v1_package/CMakeLists.txt
> librttopo: modernize more for conan v2

- recipes/drwav/all/conanfile.py
- recipes/drwav/all/test_package/CMakeLists.txt
- recipes/drwav/all/test_package/conanfile.py
- recipes/drwav/all/test_v1_package/CMakeLists.txt
> drwav: modernize more for conan v2

- recipes/drmp3/all/conanfile.py
- recipes/drmp3/all/test_package/CMakeLists.txt
- recipes/drmp3/all/test_package/conanfile.py
- recipes/drmp3/all/test_v1_package/CMakeLists.txt
> drmp3: modernize more for conan v2

- recipes/cctz/all/conanfile.py
- recipes/cctz/all/test_package/conanfile.py
- recipes/cctz/all/test_v1_package/CMakeLists.txt
> cctz: modernize more for conan v2

- recipes/md4c/all/conanfile.py
- recipes/md4c/all/test_package/CMakeLists.txt
- recipes/md4c/all/test_v1_package/CMakeLists.txt
> md4c: modernize more for conan v2

- recipes/libconfuse/all/conanfile.py
- recipes/libconfuse/all/test_package/conanfile.py
> libconfuse: modernize more for conan v2

- recipes/im95able-rea/all/conandata.yml
- recipes/im95able-rea/all/conanfile.py
- recipes/im95able-rea/all/patches/0001-include-limits.patch
- recipes/im95able-rea/all/test_package/CMakeLists.txt
- recipes/im95able-rea/all/test_package/conanfile.py
- recipes/im95able-rea/all/test_package/test_package.cpp
- recipes/im95able-rea/all/test_v1_package/CMakeLists.txt
- recipes/im95able-rea/all/test_v1_package/conanfile.py
- recipes/im95able-rea/config.yml
Specify library name and version:  **im95able-rea/***
---
> im95able-rea: add recipe

- recipes/gamma/all/CMakeLists.txt
- recipes/gamma/all/conanfile.py
- recipes/gamma/all/test_v1_package/CMakeLists.txt
> gamma: modernize more for conan v2

- recipes/libltc/all/conanfile.py
- recipes/libltc/all/test_package/CMakeLists.txt
- recipes/libltc/all/test_package/conanfile.py
- recipes/libltc/all/test_v1_package/CMakeLists.txt
- recipes/libltc/all/test_v1_package/conanfile.py
> libltc: conan v2 support

- recipes/libcurl/all/conandata.yml
- recipes/libcurl/all/conanfile.py
- recipes/libcurl/all/test_package/CMakeLists.txt
- recipes/libcurl/all/test_v1_package/CMakeLists.txt
- recipes/libcurl/config.yml
> libcurl: add version 8.0.0, update dependencies

- recipes/cpr/all/conandata.yml
- recipes/cpr/config.yml
Specify library name and version:  **cpr/1.10.1**
---
> cpr: add version 1.10.1

- recipes/lcms/all/conanfile.py
v2 packages of lcms are required for https://github.com/conan-io/conan-center-index/pull/16339#issuecomment-1470946086
---
> lcms: modernize more for conan v2 (and generate v2 packages)

- recipes/opencl-headers/all/conanfile.py
> opencl-headers: add package_type (and generate v2 packages)

- recipes/mongo-c-driver/all/conanfile.py
> mongo-c-driver: modernize more for conan v2

- recipes/embree3/all/conandata.yml
- recipes/embree3/all/conanfile.py
- recipes/embree3/all/test_v1_package/CMakeLists.txt
> embree3: modernize more for conan v2

- recipes/fakeit/all/conanfile.py
- recipes/fakeit/all/test_package/CMakeLists.txt
- recipes/fakeit/all/test_package/conanfile.py
- recipes/fakeit/all/test_v1_package/CMakeLists.txt
- recipes/fakeit/all/test_v1_package/conanfile.py
Specify library name and version:  **fakeit/2.3.2**
---
> fakeit: modernize for Conan 2.0

- recipes/libspng/all/conanfile.py
v2 packages of libspng are required for https://github.com/conan-io/conan-center-index/pull/16339#issuecomment-1470946086
---
> libspng: add package_type & bump miniz (and generate v2 packages)

- recipes/nettle/all/conanfile.py
- recipes/nettle/all/test_v1_package/CMakeLists.txt
> nettle: modernize more for conan v2

- recipes/libtasn1/all/conanfile.py
- recipes/libtasn1/all/test_package/conanfile.py
- recipes/libtasn1/all/test_v1_package/conanfile.py
> libtasn1: modernize more for conan v2

- docs/developing_recipes_locally.md
> docs: clarify what's support with Conan 2.0

- recipes/arduinojson/all/conandata.yml
- recipes/arduinojson/all/conanfile.py
- recipes/arduinojson/all/test_package/test_package.cpp
- recipes/arduinojson/config.yml
Specify library name and version:  **ArduinoJson/6.21.0**
---
> Improve and update ArduinoJson

- docs/changelog.md
Some improvements and internal fixes have been deployed to the production during this morning.
We still are working on the delay with the Automatic Merge. One of those new changes avoid listening all open pull requests on Github as first step, so we can save some minutes from the CI build.
Also, we identified some unexpected errors when trying to promote packages recently merged on master branch to conancenter repository. We added more log points to trace those errors and help us solving it.
The [conan-extensions](https://github.com/conan-io/conan-extensions) is now installed on C3I jenkins CI job. The idea is using some customs commands from there to help us identifying which package is available for Conan v2. 
---
> [docs] Add changelog March 23 2023

- recipes/modern-cpp-kafka/all/conandata.yml
- recipes/modern-cpp-kafka/all/conanfile.py
- recipes/modern-cpp-kafka/config.yml
Specify library name and version:  **modern-cpp-kafka/2023.03.07**
---
> modern-cpp-kafka: add version 2023.03.07

- recipes/opencl-icd-loader/all/conanfile.py
> opencl-icd-loader: modernize more for conan v2

- recipes/giflib/5.2.x/conanfile.py
- recipes/giflib/5.2.x/test_package/conanfile.py
> giflib 5.2.x: add package_type & fix test package for conan v2

- recipes/mingw-builds/all/conanfile.py
Specify library name and version:  **mingw-builds/***
---
> mingw-builds: conan v2 migration

- recipes/volk/all/conandata.yml
- recipes/volk/all/conanfile.py
- recipes/volk/config.yml
> volk: add 1.3.239.0 + modernize more for conan v2

- recipes/scnlib/all/conanfile.py
> scnlib: modernize more for conan v2

- recipes/flatbuffers/all/conanfile.py
- recipes/flatbuffers/all/test_package/CMakeLists.txt
- recipes/flatbuffers/all/test_package/conanfile.py
- recipes/flatbuffers/all/test_v1_package/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/16406
---
> flatbuffers: modernize more for conan v2

- recipes/iir1/all/conanfile.py
> iir1: modernize more for conan v2

- recipes/libdisasm/all/conanfile.py
- recipes/libdisasm/all/test_package/conanfile.py
> libdisasm: modernize more for conan v2

- recipes/highway/all/conanfile.py
> highway: modernize more for conan v2

- recipes/kangaru/all/CMakeLists.txt
- recipes/kangaru/all/conandata.yml
- recipes/kangaru/all/conanfile.py
- recipes/kangaru/all/test_package/CMakeLists.txt
- recipes/kangaru/all/test_package/conanfile.py
- recipes/kangaru/all/test_v1_package/CMakeLists.txt
- recipes/kangaru/all/test_v1_package/conanfile.py
- recipes/kangaru/config.yml
> kangaru: conan v2 support

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/all/conanfile.py
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/3.1.1**
---
> unordered_dense: add version 3.1.1

- recipes/nuraft/all/conanfile.py
- recipes/nuraft/all/test_package/CMakeLists.txt
- recipes/nuraft/all/test_package/conanfile.py
- recipes/nuraft/all/test_v1_package/CMakeLists.txt
- recipes/nuraft/all/test_v1_package/conanfile.py
> nuraft: modernize more for conan v2

- recipes/libepoxy/all/conandata.yml
- recipes/libepoxy/all/conanfile.py
- recipes/libepoxy/all/test_package/CMakeLists.txt
- recipes/libepoxy/all/test_package/conanfile.py
- recipes/libepoxy/all/test_v1_package/CMakeLists.txt
- recipes/libepoxy/all/test_v1_package/conanfile.py
> libepoxy: conan v2 support

- recipes/libverto/all/conanfile.py
- recipes/libverto/all/test_package/CMakeLists.txt
- recipes/libverto/all/test_package/conanfile.py
- recipes/libverto/all/test_v1_package/CMakeLists.txt
- recipes/libverto/all/test_v1_package/conanfile.py
> libverto: modernize more for conan v2

- recipes/gli/all/conandata.yml
- recipes/gli/all/conanfile.py
- recipes/gli/all/test_package/CMakeLists.txt
- recipes/gli/all/test_package/conanfile.py
- recipes/gli/all/test_package/test_package.cpp
- recipes/gli/all/test_v1_package/CMakeLists.txt
- recipes/gli/all/test_v1_package/conanfile.py
- recipes/gli/config.yml
Specify library name and version:  **gli/cci.20210515**
gli is a library for manipulating textures made by the same author as glm. I'm adding just a cci version because the most recent release (0.8.2.0) is quite old (more than 6yo) and doesn't seem compatible with any of the glm versions in Conan Center.
The recipe is based on glm's.
---
> gli: new package

- recipes/namedtype/all/conanfile.py
- recipes/namedtype/all/test_package/CMakeLists.txt
- recipes/namedtype/all/test_package/conanfile.py
- recipes/namedtype/all/test_v1_package/CMakeLists.txt
- recipes/namedtype/all/test_v1_package/conanfile.py
Specify library name and version:  **namedtype/20190324**
---
> namedtype: modernize for Conan 2.0

- recipes/lemon/all/CMakeLists.txt
- recipes/lemon/all/conandata.yml
- recipes/lemon/all/conanfile.py
- recipes/lemon/all/test_package/CMakeLists.txt
- recipes/lemon/all/test_package/conanfile.py
- recipes/lemon/all/test_v1_package/CMakeLists.txt
- recipes/lemon/all/test_v1_package/conanfile.py
- recipes/lemon/config.yml
> lemon: conan v2 support

- recipes/doctest/2.x.x/conandata.yml
- recipes/doctest/2.x.x/conanfile.py
- recipes/doctest/2.x.x/test_package/CMakeLists.txt
- recipes/doctest/2.x.x/test_package/conanfile.py
- recipes/doctest/2.x.x/test_v1_package/CMakeLists.txt
- recipes/doctest/2.x.x/test_v1_package/conanfile.py
- recipes/doctest/config.yml
closes https://github.com/conan-io/conan-center-index/issues/16486
---
> doctest: conan v2 support

- recipes/libgpg-error/all/conandata.yml
- recipes/libgpg-error/all/conanfile.py
- recipes/libgpg-error/all/test_package/CMakeLists.txt
- recipes/libgpg-error/all/test_package/conanfile.py
- recipes/libgpg-error/all/test_v1_package/CMakeLists.txt
- recipes/libgpg-error/all/test_v1_package/conanfile.py
> libgpg-error: conan v2 support

- recipes/hipony-enumerate/all/CMakeLists.txt
- recipes/hipony-enumerate/all/conanfile.py
- recipes/hipony-enumerate/all/test_package/CMakeLists.txt
- recipes/hipony-enumerate/all/test_package/conanfile.py
- recipes/hipony-enumerate/all/test_v1_package/CMakeLists.txt
- recipes/hipony-enumerate/all/test_v1_package/conanfile.py
Specify library name and version:  **hipony-enumerate/all**
---
> hipony-enumerate: Conan v2 support

- recipes/libtorrent/all/conanfile.py
> libtorrent: bump openssl + modernize more for conan v2

- recipes/csm/all/CMakeLists.txt
- recipes/csm/all/conandata.yml
- recipes/csm/all/conanfile.py
- recipes/csm/all/test_package/CMakeLists.txt
- recipes/csm/all/test_package/conanfile.py
- recipes/csm/all/test_package/test_package.cpp
- recipes/csm/all/test_v1_package/CMakeLists.txt
- recipes/csm/all/test_v1_package/conanfile.py
- recipes/csm/config.yml
> New recipe csm/3.0.4

- recipes/doxygen/all/conanfile.py
- recipes/doxygen/all/test_package/CMakeLists.txt
- recipes/doxygen/all/test_package/conanfile.py
- recipes/doxygen/all/test_v1_package/CMakeLists.txt
- recipes/doxygen/all/test_v1_package/conanfile.py
- recipes/doxygen/all/test_v1_package/test_package.cpp
> doxygen: modernize more for conan v2

- recipes/sigslot/all/conanfile.py
- recipes/sigslot/all/test_package/CMakeLists.txt
- recipes/sigslot/all/test_package/conanfile.py
- recipes/sigslot/all/test_v1_package/CMakeLists.txt
- recipes/sigslot/all/test_v1_package/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/16705
---
> sigslot: conan v2 support

- recipes/sentry-breakpad/all/conandata.yml
- recipes/sentry-breakpad/config.yml
> [sentry-breakpad] Update to 0.6.1

- recipes/gdk-pixbuf/all/conandata.yml
- recipes/gdk-pixbuf/all/conanfile.py
- recipes/gdk-pixbuf/all/test_package/CMakeLists.txt
- recipes/gdk-pixbuf/all/test_package/conanfile.py
- recipes/gdk-pixbuf/all/test_v1_package/CMakeLists.txt
> gdk-pixbuf: relocatable shared lib on macOS + modernize more for conan v2

- recipes/roaring/all/conandata.yml
- recipes/roaring/all/conanfile.py
- recipes/roaring/config.yml
Specify library name and version:  **roaring/1.0.0**
---
> roaring: add version 1.0.0

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/3.11.0**
---
> fast_float: add version 3.11.0

- recipes/libspatialite/all/conandata.yml
- recipes/libspatialite/all/conanfile.py
- recipes/libspatialite/all/patches/0002-nmake-honor-flags.patch
- recipes/libspatialite/all/test_package/CMakeLists.txt
- recipes/libspatialite/all/test_package/conanfile.py
- recipes/libspatialite/all/test_v1_package/CMakeLists.txt
- recipes/libspatialite/all/test_v1_package/conanfile.py
> libspatialite: conan v2 support

- recipes/gemmlowp/all/conanfile.py
- recipes/gemmlowp/all/test_v1_package/CMakeLists.txt
> gemmlowp: modernize more for conan v2

- recipes/unicorn/all/conanfile.py
- recipes/unicorn/all/test_package/CMakeLists.txt
- recipes/unicorn/all/test_package/conanfile.py
- recipes/unicorn/all/test_v1_package/CMakeLists.txt
> unicorn: modernize more for conan v2

- recipes/md4qt/all/conandata.yml
- recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.0.6**
---
> md4qt: bump version.

- recipes/quirc/all/conanfile.py
for https://github.com/conan-io/conan-center-index/pull/16678
replaces https://github.com/conan-io/conan-center-index/pull/16805
---
> quirc: add package_type + generate v2

- recipes/libpsl/all/conandata.yml
- recipes/libpsl/all/conanfile.py
- recipes/libpsl/all/test_package/CMakeLists.txt
- recipes/libpsl/all/test_package/conanfile.py
- recipes/libpsl/all/test_v1_package/CMakeLists.txt
- recipes/libpsl/all/test_v1_package/conanfile.py
> libpsl: conan v2 support

- .github/workflows/alert-community.yml
> [alert] Add community alert for armadillo, gcc and geotrans for samuel-emrys

- recipes/gsl/all/conanfile.py
> gsl: modernize more for conan v2

- recipes/xerces-c/all/conanfile.py
- recipes/xerces-c/all/test_v1_package/CMakeLists.txt
> xerces-c: modernize more for conan v2

- recipes/vulkan-headers/all/conandata.yml
- recipes/vulkan-headers/config.yml
> Bump vulkan-headers/1.3.243.0

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/all/conanfile.py
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.15.0**
---
> daw_json_link: add version 3.15.0

- recipes/luau/all/conandata.yml
- recipes/luau/all/conanfile.py
- recipes/luau/all/patches/0.568-0001-fix-cmake.patch
- recipes/luau/config.yml
Specify library name and version:  **luau/0.568**
---
> luau: add version 0.568

- recipes/cpp-peglib/0.x.x/conanfile.py
- recipes/cpp-peglib/1.x.x/conandata.yml
- recipes/cpp-peglib/config.yml
Specify library name and version:  **cpp-peglib/1.8.3**
---
> cpp-peglib: add version 1.8.3, add package_type on 0.x.x

- recipes/watcher/all/conandata.yml
- recipes/watcher/all/conanfile.py
- recipes/watcher/config.yml
Specify library name and version:  **watcher/0.8.0**
---
> watcher: add version 0.8.0

- recipes/gurkenlaeufer/all/conandata.yml
- recipes/gurkenlaeufer/all/conanfile.py
- recipes/gurkenlaeufer/all/test_package/CMakeLists.txt
- recipes/gurkenlaeufer/all/test_package/conanfile.py
- recipes/gurkenlaeufer/all/test_package/main.cpp
- recipes/gurkenlaeufer/all/test_package/parsertests.cpp
- recipes/gurkenlaeufer/all/test_v1_package/CMakeLists.txt
- recipes/gurkenlaeufer/all/test_v1_package/conanfile.py
- recipes/gurkenlaeufer/config.yml
I want to package an [open source header only library](https://github.com/paulelsner/gurkenlaeufer) that we also use internally and would like to fetch using conan.
---
> feat: package gurkenlaeufer

- recipes/restinio/all/conandata.yml
- recipes/restinio/config.yml
Specify library name and version:  **restinio/0.6.18**
---
> Restinio: bump version 0.6.18

- recipes/hiredis/all/conanfile.py
> hiredis: update more for conan v2 + generate packages

- recipes/glslang/all/conandata.yml
- recipes/glslang/all/conanfile.py
- recipes/glslang/all/test_package/conanfile.py
- recipes/glslang/config.yml
> glslang: add 1.3.239.0 + modernize more for conan v2

- recipes/mariadb-connector-c/all/conanfile.py
> mariadb-connector-c: bump dependencies + modernize more for conan v2

- recipes/libmodbus/all/conanfile.py
- recipes/libmodbus/all/test_v1_package/CMakeLists.txt
> libmodbus: modernize more for conan v2

- recipes/minisat/all/conandata.yml
- recipes/minisat/all/conanfile.py
- recipes/minisat/all/patches/0001-space-before-user-literal-2.2.0.patch
- recipes/minisat/all/test_package/CMakeLists.txt
- recipes/minisat/all/test_package/conanfile.py
- recipes/minisat/all/test_package/main.cpp
- recipes/minisat/all/test_v1_package/CMakeLists.txt
- recipes/minisat/all/test_v1_package/conanfile.py
- recipes/minisat/config.yml
Specify library name and version:  **minisat/2.2.0**
I am not the author of this lib. I used it in my PhD thesis and it is a copy&paste dependency in #16053. After adding this lib, the code can be deleted from the lib in #16053.
I added a patch to make the lib compile on MSVC. The project itself is not actively maintained anymore (release is from 2008?, no commits since 2013 https://github.com/niklasso/minisat), thus I refrained from creating a PR in the original repo.
---
> Add MiniSat: a SAT solver

- recipes/leptonica/all/conanfile.py
- recipes/leptonica/all/test_v1_package/CMakeLists.txt
> leptonica: modernize more for conan v2

- recipes/tinyexif/all/conandata.yml
- recipes/tinyexif/all/conanfile.py
- recipes/tinyexif/all/test_package/CMakeLists.txt
- recipes/tinyexif/all/test_package/conanfile.py
- recipes/tinyexif/all/test_package/test_package.cpp
- recipes/tinyexif/all/test_v1_package/CMakeLists.txt
- recipes/tinyexif/all/test_v1_package/conanfile.py
- recipes/tinyexif/config.yml
Specify library name and version:  **tinyexif/***
---
> tinyexif: add recipe

- recipes/libnova/all/conanfile.py
- recipes/libnova/all/test_package/conanfile.py
- recipes/libnova/all/test_v1_package/CMakeLists.txt
> libnova: modernize more for conan v2

- recipes/spirv-headers/all/conandata.yml
- recipes/spirv-headers/config.yml
> Bump spirv-headers/1.3.243.0

- recipes/libpng/all/conanfile.py
Specify library name and version:  **libpng/***
Makes the library compile with `clang-cl` out of the box, following the same pattern as other recipes on Conan Center. 
---
> libpng: support clang-cl

- recipes/jfalcou-eve/all/conanfile.py
- msvc min version regarding C++20 was wrong
- check against min eve version supporting msvc was not future proof
- remove self.output.warn (not v2 compatible)
By the way I don't understand why this v prefix has been accepted by reviewers for the versioning
---
> jfalcou-eve: fix msvc min version check

- recipes/openapi-generator/all/conandata.yml
- recipes/openapi-generator/config.yml
> [openapi-generator/6.5.0] Add version and remove 6.2.1

- docs/changelog.md
Hopefully, this will solve some recent issues with automatic merge getting stuck and cross-building with some tools.
> [docs] Add changelog 03-April-2023

- recipes/spirv-cross/all/CMakeLists.txt
- recipes/spirv-cross/all/conandata.yml
- recipes/spirv-cross/all/conanfile.py
> spirv-cross: conan v2 support

- recipes/c-blosc2/all/conandata.yml
- recipes/c-blosc2/all/conanfile.py
> c-blosc2: bump zstd + modernize more for conan v2

- recipes/libfreenect/all/CMakeLists.txt
- recipes/libfreenect/all/conandata.yml
- recipes/libfreenect/all/conanfile.py
- recipes/libfreenect/all/test_package/CMakeLists.txt
- recipes/libfreenect/all/test_package/conanfile.py
- recipes/libfreenect/all/test_v1_package/CMakeLists.txt
- recipes/libfreenect/all/test_v1_package/conanfile.py
> libfreenect: conan v2 support

- recipes/status-code/all/CMakeLists.txt
- recipes/status-code/all/conandata.yml
- recipes/status-code/all/conanfile.py
- recipes/status-code/all/test_package/CMakeLists.txt
- recipes/status-code/all/test_package/conanfile.py
- recipes/status-code/all/test_package/test_package.cpp
- recipes/status-code/all/test_v1_package/CMakeLists.txt
- recipes/status-code/all/test_v1_package/conanfile.py
- recipes/status-code/config.yml
Specify library name and version:  **status-code/cci.20220616**
- A reference implementation for a standard paper, potentially useful
- Dependency of https://github.com/ned14/llfio
---
> Add status-code/cci.20220616

- recipes/nsync/all/CMakeLists.txt
- recipes/nsync/all/conandata.yml
- recipes/nsync/all/conanfile.py
- recipes/nsync/all/test_package/CMakeLists.txt
- recipes/nsync/all/test_package/conanfile.py
- recipes/nsync/all/test_v1_package/CMakeLists.txt
- recipes/nsync/all/test_v1_package/conanfile.py
Specify library name and version:  **nsync/***
---
> nsync: conan v2 migration

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/all/conanfile.py
- recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/6.0.0**
---
> wasmtime: add version 6.0.0

- recipes/trantor/all/conanfile.py
- update openssl 
- remove `destination` arg from `self.get()`
---
> trantor: update openssl, add package_type

- recipes/commata/all/conandata.yml
- recipes/commata/all/conanfile.py
- recipes/commata/config.yml
Specify library name and version:  **commata/0.2.4**
---
> commata: add version 0.2.4

- recipes/sentry-crashpad/all/conandata.yml
- recipes/sentry-crashpad/all/conanfile.py
- recipes/sentry-crashpad/config.yml
> [sentry-crashpad] Update to 0.6.1

- recipes/bzip3/all/conandata.yml
- recipes/bzip3/all/conanfile.py
- recipes/bzip3/config.yml
Specify library name and version:  **bzip3/***
---
> bzip3: add version 1.2.3, use official tarballs

- recipes/sentry-native/all/conandata.yml
- recipes/sentry-native/config.yml
> [sentry-native] Update to 0.6.1

- recipes/safeint/all/conanfile.py
Specify library name and version:  **safeint/***
required for conan v2 builds of https://github.com/conan-io/conan-center-index/pull/16849 / https://github.com/conan-io/conan-center-index/pull/16842
---
> safeint: set package_type (& generate conan v2 packages)

- recipes/xkbcommon/all/conanfile.py
Specify library name and version:  **xkbcommon/all**
Add `package_type` attribute to `xkbcommon`.
> xkb-common: add package type

- recipes/wasmtime-cpp/all/conandata.yml
- recipes/wasmtime-cpp/all/conanfile.py
- recipes/wasmtime-cpp/config.yml
Specify library name and version:  **wasmtime-cpp/6.0.0**
---
> wasmtime-cpp: add version 6.0.0

- recipes/moltenvk/all/conandata.yml
- recipes/moltenvk/all/conanfile.py
- recipes/moltenvk/all/dependencies/dependencies-1.2.2.yml
- recipes/moltenvk/config.yml
this PR needs https://github.com/conan-io/conan-center-index/pull/16295 & https://github.com/conan-io/conan-center-index/pull/16132
---
> moltenvk: add 1.2.2 + modernize a little bit more

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/all/conanfile.py
- recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/***
---
> wasmtime: add version 7.0.0, use self.settings.rm_safe()

- recipes/minizip-ng/all/conandata.yml
- recipes/minizip-ng/all/conanfile.py
- recipes/minizip-ng/all/patches/3.0.9-0001-fix-cmake-project.patch
- recipes/minizip-ng/config.yml
Specify library name and version:  **minizip-ng/3.0.9**
---
> minizip-ng: add version 3.0.9

- recipes/dataframe/all/conandata.yml
- recipes/dataframe/all/conanfile.py
- recipes/dataframe/all/patches/2.0.0-0001-use-abs.patch
- recipes/dataframe/config.yml
Specify library name and version:  **dataframe/2.0.0**
---
> dataframe: add version 2.0.0

- recipes/homog2d/all/conandata.yml
- recipes/homog2d/all/conanfile.py
- recipes/homog2d/config.yml
Specify library name and version:  **homog2d/2.10**
---
> homog2d: add version 2.10

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/4.0.0**
---
> fast_float: add v4.0.0

- recipes/zstd/all/conandata.yml
- recipes/zstd/config.yml
Specify library name and version:  **zstd/1.5.5**
---
> zstd: add version 1.5.5

- recipes/cppcheck/all/conandata.yml
- recipes/cppcheck/all/conanfile.py
- recipes/cppcheck/all/test_package/conanfile.py
- recipes/cppcheck/all/test_v1_package/conanfile.py
- recipes/cppcheck/config.yml
Specify library name and version:  **cppcheck/2.10.3**
---
> Cppcheck add 2.10.3

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/***
---
> meson: add version 1.0.1

- recipes/bliss/all/CMakeLists.txt
- recipes/bliss/all/conandata.yml
- recipes/bliss/all/conanfile.py
- recipes/bliss/all/patches/0001-fix-cmake.patch
- recipes/bliss/all/test_package/CMakeLists.txt
- recipes/bliss/all/test_package/conanfile.py
- recipes/bliss/all/test_v1_package/CMakeLists.txt
- recipes/bliss/all/test_v1_package/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/16473
---
> bliss: conan v2 support

- recipes/netcdf/all/conanfile.py
> netcdf: bump deps

- recipes/cgns/all/conanfile.py
> cgns: bump deps

- recipes/patchelf/all/conandata.yml
- recipes/patchelf/all/conanfile.py
- recipes/patchelf/all/test_package/conanfile.py
- recipes/patchelf/all/test_v1_package/conanfile.py
Specify library name and version:  **patchelf/***
---
> patchelf: conan v2

- recipes/highfive/all/conandata.yml
- recipes/highfive/config.yml
Specify library name and version:  **highfive/2.7.1**
---
> highfive: add v2.7.1

- recipes/xz_utils/all/conandata.yml
- recipes/xz_utils/config.yml
Specify library name and version:  **xz_utils/5.4.2**
---
> xz_utils: add v5.4.2

- recipes/fontconfig/config.yml
- recipes/fontconfig/meson/conandata.yml
Specify library name and version:  **fontconfig/2.14.2**
---
> Fontconfig 2.14

- recipes/proj/all/conanfile.py
> proj: bump dependencies

- recipes/libcurl/all/conanfile.py
Use gnu-config to identify host system type. gnu-config was patched in https://github.com/conan-io/conan-center-index/pull/16802 to accept `*-tvos` as OS.
---
> libcurl: fix host system type for crossbuild tvOS

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/all/conanfile.py
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.12.2**
---
> cpp-httplib: add version 0.12.2, update openssl

- recipes/bzip3/all/conandata.yml
- recipes/bzip3/config.yml
Specify library name and version:  **bzip3/1.3.0**
---
> bzip3: add version 1.3.0

- recipes/dirent/all/conanfile.py
- recipes/dirent/all/test_package/CMakeLists.txt
- recipes/dirent/all/test_package/conanfile.py
- recipes/dirent/all/test_v1_package/CMakeLists.txt
- recipes/dirent/all/test_v1_package/conanfile.py
Specify library name and version:  **direcnt/***
---
> dirent: support conan v2

- recipes/editline/all/conanfile.py
- recipes/editline/all/test_package/CMakeLists.txt
- recipes/editline/all/test_package/conanfile.py
- recipes/editline/all/test_v1_package/CMakeLists.txt
- recipes/editline/all/test_v1_package/conanfile.py
> editline: conan v2 support

- recipes/cgif/all/conandata.yml
- recipes/cgif/all/conanfile.py
- recipes/cgif/all/test_package/CMakeLists.txt
- recipes/cgif/all/test_package/conanfile.py
- recipes/cgif/all/test_package/test_package.c
- recipes/cgif/all/test_v1_package/CMakeLists.txt
- recipes/cgif/all/test_v1_package/conanfile.py
- recipes/cgif/config.yml
> New recipe cgif/0.3.0

- recipes/libxslt/all/conandata.yml
- recipes/libxslt/all/conanfile.py
- recipes/libxslt/all/test_package/CMakeLists.txt
- recipes/libxslt/all/test_package/conanfile.py
- recipes/libxslt/all/test_package/libxslt_tutorial.c
- recipes/libxslt/all/test_v1_package/CMakeLists.txt
- recipes/libxslt/all/test_v1_package/conanfile.py
> libxslt: conan v2 support

- recipes/md4qt/all/conandata.yml
- recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.0.7**
---
> md4qt: bump version

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.1.7**
---
> simdjson: add version 3.1.7

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/4.0.0**
---
> unordered_dense: add version 4.0.0

- recipes/frozen/all/conanfile.py
- recipes/frozen/all/test_v1_package/CMakeLists.txt
> frozen: add package_type (and generate v2 packages)

- recipes/utfcpp/all/conanfile.py
For https://github.com/conan-io/conan-center-index/pull/16328#issuecomment-1493463343
---
> utfcpp: add package_type and generate packages

- recipes/itlib/all/conandata.yml
- recipes/itlib/all/conanfile.py
- recipes/itlib/config.yml
Specify library name and version:  **itlib/1.9.0**
---
> itlib: add version 1.9.0

- recipes/re2/all/conandata.yml
- recipes/re2/config.yml
Specify library name and version:  **re2/20230301**
---
> re2: add version 20230301

- recipes/lexbor/all/CMakeLists.txt
- recipes/lexbor/all/conandata.yml
- recipes/lexbor/all/conanfile.py
- recipes/lexbor/all/test_package/CMakeLists.txt
- recipes/lexbor/all/test_package/conanfile.py
- recipes/lexbor/all/test_v1_package/CMakeLists.txt
- recipes/lexbor/all/test_v1_package/conanfile.py
- recipes/lexbor/config.yml
Specify library name and version:  **lexbor/***
---
> lexbor: add version 2.2.0, support conan v2

- recipes/spirv-cross/all/conandata.yml
- recipes/spirv-cross/config.yml
> Bump spirv-cross/1.3.243.0

- recipes/volk/all/conandata.yml
- recipes/volk/config.yml
> Bump volk/1.3.243.0

- recipes/draco/all/conandata.yml
- recipes/draco/config.yml
> Bump draco/1.5.6

- recipes/nng/all/CMakeLists.txt
- recipes/nng/all/conandata.yml
- recipes/nng/all/conanfile.py
- recipes/nng/all/test_package/CMakeLists.txt
- recipes/nng/all/test_package/conanfile.py
- recipes/nng/all/test_v1_package/CMakeLists.txt
- recipes/nng/all/test_v1_package/conanfile.py
Library name and version:  **nng/all**
---
> nng: support Conan v2

- recipes/dav1d/all/conandata.yml
- recipes/dav1d/all/conanfile.py
- recipes/dav1d/config.yml
> dav1d: add 1.1.0 + use official tarballs + add package_type

- recipes/sqlite_orm/all/conandata.yml
- recipes/sqlite_orm/all/conanfile.py
- recipes/sqlite_orm/config.yml
> sqlite_orm: add 1.8.2, package_type & bump sqlite3

- docs/package_templates/autotools_package/all/test_package/conanfile.py
- docs/package_templates/cmake_package/all/test_package/conanfile.py
- docs/package_templates/header_only/all/test_package/conanfile.py
- docs/package_templates/meson_package/all/test_package/conanfile.py
- docs/package_templates/msbuild_package/all/test_package/conanfile.py
https://github.com/conan-io/conan-center-index/pull/16847/files#r1158843293
---
> docs: Access build folder using the improved syntax from 1.53

- recipes/tabulate/all/conandata.yml
- recipes/tabulate/all/conanfile.py
- recipes/tabulate/all/test_package/CMakeLists.txt
- recipes/tabulate/all/test_package/conanfile.py
- recipes/tabulate/all/test_v1_package/CMakeLists.txt
- recipes/tabulate/all/test_v1_package/conanfile.py
- recipes/tabulate/config.yml
Specify library name and version:  **tabulate/***
---
> tabulate: add version 1.5, support conan v2

- recipes/roaring/all/conandata.yml
- recipes/roaring/config.yml
Specify library name and version:  **roaring/1.1.0**
---
> roaring: add version 1.1.0

- recipes/grpc/all/conandata.yml
- recipes/grpc/all/conanfile.py
- recipes/grpc/config.yml
Playing around for https://github.com/conan-io/conan-center-index/pull/15805
---
> grpc: bump openssl deps

- recipes/qt/5.x.x/conanfile.py
fixes conan-io/conan-center-index#16998
---
> qt5: fix env var generation

- recipes/uwebsockets/all/conanfile.py
because of https://github.com/conan-io/conan-center-index/pull/14147#issuecomment-1478862649 just looked it over but did not see anything obvious 🤔 
---
> uwebsockets: add package_type

- recipes/wasmtime-cpp/all/conandata.yml
- recipes/wasmtime-cpp/all/conanfile.py
- recipes/wasmtime-cpp/config.yml
Specify library name and version:  **wasmtime-cpp/7.0.0**
---
> wasmtime-cpp: add version 7.0.0

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.2.0**
---
> glaze: add version 1.2.0

- recipes/incbin/all/conanfile.py
- recipes/incbin/all/test_package/CMakeLists.txt
- recipes/incbin/all/test_package/conanfile.py
- recipes/incbin/all/test_v1_package/CMakeLists.txt
- recipes/incbin/all/test_v1_package/conanfile.py
Specify library name and version:  incbin
---
> incbin: conan v2 support

- recipes/libmorton/all/conandata.yml
- recipes/libmorton/all/conanfile.py
- recipes/libmorton/all/test_package/conanfile.py
- recipes/libmorton/all/test_v1_package/CMakeLists.txt
- recipes/libmorton/config.yml
- use export_conandata_patches()
---
> libmorton: add 0.2.11 + modernize more for conan v2

- recipes/sdl_image/all/conanfile.py
- recipes/sdl_image/all/test_package/conanfile.py
- recipes/sdl_image/all/test_v1_package/CMakeLists.txt
> sdl_image: modernize more for conan v2

- recipes/foonathan-memory/all/conanfile.py
These are needed for https://github.com/conan-io/conan-center-index/pull/16992#issuecomment-1505758694
---
> foonathan-memory: modernize + add package_type

- recipes/sdl_image/all/conanfile.py
see https://github.com/conan-io/conan-center-index/pull/16167#issuecomment-1508347351
---
> sdl_image: add transitive headers to sdl

- recipes/cairo/all/conanfile.py
- recipes/cairo/meson/conanfile.py
> cairo: bump dependencies

- recipes/doctest/2.x.x/conandata.yml
- recipes/doctest/config.yml
Specify library name and version:  **doctest/2.4.11**
---
> doctest: Add version 2.4.11.

- recipes/jom/all/conanfile.py
- recipes/jom/all/test_package/conanfile.py
> jom: add package_type (and generate v2 packages)

- .github/workflows/alert-community.yml
https://github.com/conan-io/conan-center-index/pull/17017#issuecomment-1507695533 looked a little funky
---
> config: remove alert with empty reviewers

- recipes/egl/system/conanfile.py
> egl: add package_type

- recipes/gtk/system/conanfile.py
> gtk/system: add package_type

- recipes/vaapi/all/conanfile.py
> vaapi: add package_type

- recipes/luau/all/conandata.yml
- recipes/luau/all/patches/0.572-0001-fix-cmake.patch
- recipes/luau/config.yml
Specify library name and version:  **luau/0.572**
---
> luau: add version 0.572

- recipes/easy_profiler/all/CMakeLists.txt
- recipes/easy_profiler/all/conandata.yml
- recipes/easy_profiler/all/conanfile.py
- recipes/easy_profiler/all/test_package/CMakeLists.txt
- recipes/easy_profiler/all/test_package/conanfile.py
- recipes/easy_profiler/all/test_package/example.cpp
- recipes/easy_profiler/all/test_v1_package/CMakeLists.txt
- recipes/easy_profiler/all/test_v1_package/conanfile.py
Specify library name and version:  **easy_profiler/2.1.0**
Update recipe to Conan 2.0
---
> easy_profiler: conan v2 support

- recipes/wolfssl/all/conandata.yml
- recipes/wolfssl/all/conanfile.py
- recipes/wolfssl/all/test_package/CMakeLists.txt
- recipes/wolfssl/all/test_package/conanfile.py
- recipes/wolfssl/all/test_v1_package/CMakeLists.txt
- recipes/wolfssl/all/test_v1_package/conanfile.py
- recipes/wolfssl/config.yml
> wolfssl: conan v2 support

- recipes/blend2d/all/conandata.yml
- recipes/blend2d/all/patches/0.8-0001-disable-embed-asmjit.patch
- recipes/blend2d/config.yml
Specify library name and version:  **blend2d/0.8**
---
> blend2d: add version 0.8

- recipes/glu/all/conanfile.py
- recipes/glu/all/test_package/test_package.c
> glu: add package_type

- recipes/civetweb/all/conandata.yml
- recipes/civetweb/all/conanfile.py
- recipes/civetweb/config.yml
Specify library name and version:  **civetweb/1.16**
---
> civetweb: add version 1.16

- docs/package_templates/meson_package/all/conandata.yml
Documentation contained invalid YAML syntax - extra commas. I removed them.
Not related to any library.
---
- [na] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [na] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> Fix example in the docs

- recipes/cyrus-sasl/all/conanfile.py
> cyrus-sasl: bump dependencies

- recipes/gdcm/all/conanfile.py
> gdcm: bump openssl

- recipes/libcurl/all/conanfile.py
> libcurl: bump openssl & zstd

- recipes/ada/all/conandata.yml
- recipes/ada/all/conanfile.py
- recipes/ada/all/test_package/CMakeLists.txt
- recipes/ada/all/test_package/conanfile.py
- recipes/ada/all/test_package/test_package.cpp
- recipes/ada/all/test_v1_package/CMakeLists.txt
- recipes/ada/all/test_v1_package/conanfile.py
- recipes/ada/config.yml
Specify library name and version:  **ada/1.0.3**
ada is an url parsing library.
---
> ada: add recipe

- recipes/string-view-lite/all/conanfile.py
Needed for https://github.com/conan-io/conan-center-index/pull/17040#issuecomment-1511116424
---
> string-view-lite: add package_type + generate v2 packages

- recipes/blend2d/all/conanfile.py
Specify library name and version:  **blend2d/***
---
> blend2d: update asmjit, support older msvc

- recipes/optional-lite/all/conanfile.py
Noticed this for https://github.com/conan-io/conan-center-index/pull/17040#issuecomment-1511116424
---
> optional-lite: add_package_type + generate v2 packages

- recipes/http_parser/all/conanfile.py
noticed this for https://github.com/conan-io/conan-center-index/pull/17040#issuecomment-1511116424
---
> http_parser: add package_type + generate v2 packages

- recipes/expected-lite/all/conanfile.py
Noticed this for https://github.com/conan-io/conan-center-index/pull/17040#issuecomment-1511116424
---
> expected-lite: add package_type + generate v2 packages

- recipes/mariadb-connector-c/all/conanfile.py
> mariadb-connector-c: bump openssl & libcurl

- recipes/nuraft/all/conanfile.py
> nuraft: bump openssl & asio

- recipes/uni-algo/all/conanfile.py
> uni-algo: remove extras left from templates

- recipes/mongo-c-driver/all/conanfile.py
> mongo-c-driver: bump openssl & zstd

- recipes/capnproto/all/conanfile.py
> capnproto: add package_type + bump openssl to 3.x.x

- recipes/minizip-ng/all/conanfile.py
> minizip-ng: bump dependencies

- recipes/caf/all/conanfile.py
> caf: bump openssl

- linter/pylintrc_testpackage
This is a regression from #15115 https://github.com/conan-io/conan-center-index/actions/runs/4736184559/jobs/8407382514?pr=17062 Space caught it ❤️ 
---
> linter: pylintrc_testpackage should not run layout checks

- recipes/fakeit/all/conandata.yml
- recipes/fakeit/config.yml
Specify library name and version:  **fakeit/2.4.0**
---
> fakeit: add version 2.4.0

- recipes/nameof/all/conandata.yml
- recipes/nameof/all/conanfile.py
- recipes/nameof/all/test_package/CMakeLists.txt
- recipes/nameof/all/test_package/conanfile.py
- recipes/nameof/all/test_v1_package/CMakeLists.txt
- recipes/nameof/all/test_v1_package/conanfile.py
- recipes/nameof/config.yml
Specify library name and version:  **nameof/***
---
> nameof: add version 0.10.3, support conan v2

- recipes/wil/all/conanfile.py
- recipes/wil/all/test_package/CMakeLists.txt
review mistakes from https://github.com/conan-io/conan-center-index/pull/16701#discussion_r1166056823
---
> wil: correct package_info and msvc version

- recipes/popt/all/conandata.yml
- recipes/popt/all/conanfile.py
- recipes/popt/all/patches/0004-vcpkg-fixmsvc.patch
- recipes/popt/all/test_package/CMakeLists.txt
- recipes/popt/all/test_package/conanfile.py
- recipes/popt/all/test_package/test_package.c
- recipes/popt/all/test_v1_package/CMakeLists.txt
- recipes/popt/all/test_v1_package/conanfile.py
- recipes/popt/config.yml
Specify library name and version:  **popt/1.16**
The popt recipe is needed for development of resiprocate.
---
> New recipe popt/1.16

- recipes/date/all/conanfile.py
Specify library name and version:  **date/***
bump libcurl version
---
> date: bump libcurl version

- recipes/libevent/all/conanfile.py
> libevent: add package_type + bump openssl

- recipes/itlib/all/conandata.yml
- recipes/itlib/config.yml
Specify library name and version:  **itlib/1.9.1**
---
> itlib: add version 1.9.1

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.2.0**
---
> ada: add version 2.2.0

- recipes/libzen/all/conanfile.py
> libzen: add package_type (and generate v2 packages)

- recipes/backward-cpp/all/conanfile.py
Specify library name and version:  **backward-cpp/1.6**
This PR tries to close https://github.com/conan-io/conan-center-index/issues/16787.
---
> backward-cpp: Add `libelf` as its direct dependency

- recipes/rapidyaml/all/conanfile.py
Specify library name and version:  **rapidyaml/***
- make c4core transitive_headers for jsonnet
---
> rapidyaml: make c4core transitive_headers

- docs/consuming_recipes.md
- docs/v2_linter.md
- docs/v2_migration.md
The old one was too detailed and never updates, we've diverged pretty far to it was easier to remove it and leave a few bullet points
---
> docs: removed v2_roadmap (updated steps in v2_migration)

- recipes/ninja/all/conanfile.py
fixes conan-io/conan-center-index#16744
fixes conan-io/conan-center-index#16314
Specify library name and version:  **ninja/***
---
> ninja: regenerate binaries

- recipes/pulseaudio/all/conanfile.py
> pulseaudio: use version range for openssl

- recipes/cyrus-sasl/all/conanfile.py
> cyrus-sasl: use version range for openssl

- recipes/kmod/all/conanfile.py
> kmod: use version range for openssl

- recipes/glog/all/conanfile.py
> glog: use version range for cmake

- recipes/nuraft/all/conanfile.py
> nuraft: use version range for openssl

- recipes/icu/all/conandata.yml
- recipes/icu/all/conanfile.py
- recipes/icu/config.yml
Specify library name and version:  **icu/73.1**
---
> icu: add version 73.1, add package_type

- recipes/gdcm/all/conanfile.py
> gdcm: use version range for openssl

- recipes/dlpack/all/conandata.yml
- recipes/dlpack/all/conanfile.py
- recipes/dlpack/all/test_package/CMakeLists.txt
- recipes/dlpack/all/test_package/conanfile.py
- recipes/dlpack/all/test_package/test_package.cpp
- recipes/dlpack/all/test_v1_package/CMakeLists.txt
- recipes/dlpack/all/test_v1_package/conanfile.py
- recipes/dlpack/config.yml
> dlpack: add 0.6 & 0.8 + conan v2 support

- recipes/soplex/all/conandata.yml
- recipes/soplex/all/conanfile.py
- recipes/soplex/all/test_package/CMakeLists.txt
- recipes/soplex/all/test_package/conanfile.py
- recipes/soplex/all/test_package/main.cpp
- recipes/soplex/all/test_v1_package/CMakeLists.txt
- recipes/soplex/all/test_v1_package/conanfile.py
- recipes/soplex/config.yml
Specify library name and version:  **soplex/6.0.3**
This is a dependency for #14180
I am not the author of this library. We use linear programming solvers at my company and thus we created this conan package.
---
> Add SoPlex linear programming solver

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.2.2**
---
> glaze: add version 1.2.2

- recipes/rapidcsv/all/conandata.yml
- recipes/rapidcsv/config.yml
Specify library name and version:  **rapidcsv/8.75**
---
> rapidcsv: Add version 8.75.

- recipes/roaring/all/conandata.yml
- recipes/roaring/config.yml
Specify library name and version:  **roaring/1.1.2**
---
> roaring: Add version 1.1.2.

- recipes/nanobench/all/conandata.yml
- recipes/nanobench/config.yml
Specify library name and version:  **nanobench/4.3.11**
---
> nanobench: Add version 4.3.11.

- recipes/libarchive/all/conanfile.py
Specify library name and version:  **libarchive/all**
Bump libxml2, xz_utils and zstd
Use version range for openssl.
---
> libarchive: bump deps

- recipes/libcurl/all/conanfile.py
> libcurl: use version range for openssl

- recipes/statslib/all/conandata.yml
- recipes/statslib/all/conanfile.py
- recipes/statslib/all/test_package/CMakeLists.txt
- recipes/statslib/all/test_package/conanfile.py
- recipes/statslib/all/test_v1_package/CMakeLists.txt
- recipes/statslib/all/test_v1_package/conanfile.py
- recipes/statslib/config.yml
Specify library name and version:  **statlib/***
---
> statslib: add version 3.4.0, support conan v2

- recipes/hdrhistogram-c/all/conanfile.py
> hdrhistogram-c: add package_type (and generate v2 packages)

- recipes/args-parser/all/conanfile.py
- recipes/args-parser/all/test_package/conanfile.py
- recipes/args-parser/all/test_v1_package/CMakeLists.txt
> args-parser: add package_type (and generate v2 packages)

- recipes/amqp-cpp/all/conanfile.py
> amqp-cpp: add package_type + bump openssl

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.41.2**
---
> update sqlite3 to version 3.41.2

- recipes/oatpp-openssl/all/conanfile.py
> oatpp-openssl: use version range for openssl

- recipes/hiredis/all/conanfile.py
> hiredis: use version range for openssl

- recipes/minizip-ng/all/conanfile.py
> minizip-ng: use version range for openssl

- recipes/trantor/all/conanfile.py
> trantor: use version range for openssl

- recipes/ada/all/conandata.yml
- recipes/ada/all/conanfile.py
- recipes/ada/config.yml
> ada: add version 2.3.2, remove _cmake_new_enough

- recipes/libsamplerate/all/conanfile.py
> libsamplerate: use version range for cmake

- recipes/brynet/all/conanfile.py
> brynet: add package_type + use version range for openssl

- recipes/rabbitmq-c/all/conanfile.py
- recipes/rabbitmq-c/all/test_package/conanfile.py
> rabbitmq-c: add package_type + use version range for openssl

- recipes/foonathan-lexy/all/conanfile.py
- recipes/foonathan-lexy/all/test_package/conanfile.py
- remove _cmake_new_enough()
---
> foonathan-lexy: add package_type + use version range for cmake

- recipes/boost/all/conanfile.py
> boost: bump deps

- recipes/mdspan/all/conandata.yml
- recipes/mdspan/all/conanfile.py
- recipes/mdspan/all/test_package/CMakeLists.txt
- recipes/mdspan/config.yml
Specify library name and version:  **mdspan/0.6.0**
---
> mdspan: add version 0.6.0, add package_type

- recipes/websocketpp/all/conanfile.py
> websocketpp: add package_type + bump boost & asio

- recipes/wavelet_buffer/all/conanfile.py
> wavelet_buffer: remove cmake_new_enough

- recipes/gsoap/all/conanfile.py
- recipes/gsoap/all/test_package/conanfile.py
- recipes/gsoap/all/test_v1_package/conanfile.py
> gsoap: add package_type + bump openssl & bison

- recipes/qpdf/all/conanfile.py
> qpdf: bump openssl

- recipes/cpp-httplib/all/conanfile.py
> cpp-httplib: use version range for openssl

- recipes/restinio/all/conanfile.py
> restinio: bump dependencies

- recipes/glib/all/conanfile.py
Specify library name and version:  **glib/***
also, generate conan v2 missing binaries
Generated by running
```
conan config install https://github.com/conan-io/conan-extensions.git
conan recipe:bump-deps recipes/glib/all -r "*"
```
---
> glib: bump deps

- recipes/armadillo/all/conanfile.py
* Bump dependency versions and fix output to ensure conan 2.0 compatibility
---
> [armadillo] Bump dependencies

- recipes/cpu_features/all/conandata.yml
- recipes/cpu_features/all/conanfile.py
- recipes/cpu_features/all/patches/0.8.0-0001-support-aarch64-macos.patch
- recipes/cpu_features/config.yml
Specify library name and version:  **cpu_features/***
- add version 0.8.0
- add patch_description
---
> cpu_features: add version 0.8.0, add package_type

- recipes/flatbuffers/all/conanfile.py
> flatbuffers: use version range for cmake

- recipes/googleapis/all/conanfile.py
> googleapis: use version range for cmake

- recipes/arduinojson/all/conandata.yml
- recipes/arduinojson/all/conanfile.py
- recipes/arduinojson/config.yml
Specify library name and version:  **arduinojson/6.21.2**
Fix blocking build issue on conan1.
---
> Improve ArduinoJson and add 6.21.2

- recipes/qxlsx/all/conanfile.py
- recipes/qxlsx/all/test_v1_package/CMakeLists.txt
- remove _cmake_new_enough
- bump qt
---
> qxlsx: add package_type + use version range for cmake

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.12.3**
---
> cpp-httplib: add version 0.12.3

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  **cmake/3.26.3**
---
> cmake: add 3.26.3

- recipes/amqp-cpp/all/conandata.yml
- recipes/amqp-cpp/all/conanfile.py
- recipes/amqp-cpp/all/patches/4.3.24-0001-cmake-openssl-install-directories.patch
- recipes/amqp-cpp/all/test_package/CMakeLists.txt
- recipes/amqp-cpp/config.yml
Specify library name and version:  **amqp-cpp/4.3.24**
Raised requirements to C++17 for latest version.
---
> amqp-cpp: add 4.3.24

- recipes/cryptopp/all/conanfile.py
> cryptopp: use version range for cmake

- recipes/ittapi/all/conandata.yml
- recipes/ittapi/config.yml
Specify library name and version:  **ittapi/3.24.0**
---
> Added ittapi 3.24.0

- recipes/cfgfile/all/conanfile.py
- recipes/cfgfile/all/test_package/conanfile.py
> cfgfile: use version range for cmake

- recipes/sentry-breakpad/all/conandata.yml
- recipes/sentry-breakpad/config.yml
> [sentry-breakpad] Add version 0.6.2

- docs/changelog.md
Finally a new deploy with features and fixes
> [docs] Update changelog 04-May-2023

- recipes/libzip/all/conanfile.py
> libzip: add package_type + bump dependencies

- recipes/libtorrent/all/conanfile.py
> libtorrent: bump openssl

- recipes/abseil/all/conandata.yml
- recipes/abseil/config.yml
Specify library name and version:  **abseil/20230125.3**
Update to latest abseil release
---
> Update abseil to 20230125.3

- docs/adding_packages/dependencies.md
add a small warning as a disclaimer
---
> docs: using openssl version range with 1.x clients

- recipes/c-blosc2/all/conanfile.py
Based on https://github.com/conan-io/conan-center-index/pull/17192
---
> c-blosc2: remove cmake_new_enough

- recipes/glfw/all/conanfile.py
> glfw: add package_type (and generate v2 packages)

- recipes/googleapis/all/helpers.py
Specify library name and version:  **googleapi/all**
---
> googleapi: fix open files with utf-8 encoding

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.2.3**
---
> glaze: add version 1.2.3

- recipes/eabase/all/CMakeLists.txt
- recipes/eabase/all/conandata.yml
- recipes/eabase/all/conanfile.py
- recipes/eabase/all/test_package/CMakeLists.txt
- recipes/eabase/all/test_package/conanfile.py
- recipes/eabase/all/test_v1_package/CMakeLists.txt
- recipes/eabase/all/test_v1_package/conanfile.py
- recipes/eabase/config.yml
Specify library name and version:  **eabase/2.09.12**
---
> eabase: add Conan v2 support, add v2.09.12

- recipes/libxft/all/conanfile.py
Specify library name and version:  **libxft/***
created from https://ericlemanissier.github.io/conan-center-index-bump-deps/
---
> libxft/all/: bump deps

- recipes/nss/all/conanfile.py
Specify library name and version:  **nss/***
created from https://ericlemanissier.github.io/conan-center-index-bump-deps/
---
> nss/all/: bump deps

- recipes/xkbcommon/all/conanfile.py
Specify library name and version:  **xkbcommon/1.0**
created from https://ericlemanissier.github.io/conan-center-index-bump-deps/
---
> xkbcommon/all/: bump deps

- recipes/opencv/4.x/conanfile.py
Bump eigen to 3.4.0 to avoid doing overrides
> Bump eigen in opencv

- recipes/tinymidi/all/CMakeLists.txt
- recipes/tinymidi/all/conanfile.py
- recipes/tinymidi/all/test_package/CMakeLists.txt
- recipes/tinymidi/all/test_package/conanfile.py
- recipes/tinymidi/all/test_v1_package/CMakeLists.txt
- recipes/tinymidi/all/test_v1_package/conanfile.py
> tinymidi: conan v2 support

- recipes/foonathan-memory/all/conanfile.py
> foonathan: cleanup warning

- recipes/ccache/all/conandata.yml
- recipes/ccache/all/conanfile.py
- recipes/ccache/all/patches/4.8-cmake-msvc-runtime.patch
- recipes/ccache/config.yml
Specify library name and version:  **ccache/4.8**
---
> ccache: add version 4.8

- recipes/ktx/all/CMakeLists.txt
- recipes/ktx/all/conandata.yml
- recipes/ktx/all/conanfile.py
- recipes/ktx/all/patches/0004-unvendor-dependencies.patch
- recipes/ktx/all/test_package/CMakeLists.txt
- recipes/ktx/all/test_package/conanfile.py
- recipes/ktx/all/test_v1_package/CMakeLists.txt
- recipes/ktx/all/test_v1_package/conanfile.py
> ktx: conan v2 support

- recipes/taocpp-json/all/conanfile.py
- recipes/taocpp-json/all/test_package/CMakeLists.txt
- recipes/taocpp-json/all/test_package/conanfile.py
- recipes/taocpp-json/all/test_v1_package/CMakeLists.txt
- recipes/taocpp-json/all/test_v1_package/conanfile.py
> taocpp-json: conan v2 support

- recipes/aws-c-sdkutils/all/conanfile.py
- recipes/aws-c-sdkutils/all/test_v1_package/CMakeLists.txt
see https://github.com/awslabs/aws-c-sdkutils/blob/v0.1.9/include/aws/sdkutils/exports.h
---
> aws-c-sdkutils: add missing interface definition if shared + modernize more for conan v2

- recipes/foxglove-websocket/all/conandata.yml
- recipes/foxglove-websocket/all/conanfile.py
- recipes/foxglove-websocket/all/test_package/CMakeLists.txt
- recipes/foxglove-websocket/all/test_package/conanfile.py
- recipes/foxglove-websocket/all/test_package/test_package.cpp
- recipes/foxglove-websocket/all/test_package/test_package_pre_1_0_0.cpp
- recipes/foxglove-websocket/all/test_v1_package/CMakeLists.txt
- recipes/foxglove-websocket/all/test_v1_package/conanfile.py
- recipes/foxglove-websocket/config.yml
Specify library name and version:  **foxglove-websocket/1.0.0**
---
> foxglove-websocket: Add version 1.0.0

- recipes/mold/all/conandata.yml
- recipes/mold/config.yml
Add the latest version of the mold linker, 1.11.0
> Add mold 1.11.0

- recipes/fmt/all/conandata.yml
- recipes/fmt/all/conanfile.py
- recipes/fmt/all/test_package/CMakeLists.txt
- recipes/fmt/all/test_v1_package/CMakeLists.txt
- recipes/fmt/config.yml
Specify library name and version:  **fmt/10.0.0**
Added version 10.0.0.
Bumped the CMake minimum required version in the test packages to 3.15.
Specified the `package_type` as `library`.
---
> fmt: Add version 10.0.0

- recipes/openexr/3.x/conandata.yml
- recipes/openexr/config.yml
> (#17536) openexr: Add version 3.1.7

- recipes/quill/all/conanfile.py
- update fmt
- remove condition for fmt version (older versions are already removed)
- add `_min_cppstd`
---
> quill: update fmt, add _min_cppstd

- recipes/bshoshany-thread-pool/all/conandata.yml
- recipes/bshoshany-thread-pool/config.yml
Specify library name and version:  **bshoshany-thread-pool/3.4.0**
---
> bshoshany-thread-pool: add version 3.4.0

- recipes/quill/all/conandata.yml
- recipes/quill/config.yml
Specify library name and version:  **quill/2.9.0**
---
> quill: add version 2.9.0

- recipes/expat/all/conanfile.py
- recipes/expat/all/test_package_module/CMakeLists.txt
- recipes/xz_utils/all/conanfile.py
- recipes/xz_utils/all/test_package/CMakeLists.txt
- recipes/zbar/all/conanfile.py
- recipes/zbar/all/test_package/CMakeLists.txt
- recipes/zbar/all/test_package/conanfile.py
Specify library name and version:  **zbar/0.23.92**
---
> port ZBar recipe to conan2

- recipes/asio/all/conandata.yml
- recipes/asio/config.yml
Specify library name and version:  **asio/1.28.0**
Edit: Resolves #17520
---
> asio: add version 1.28.0

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.4.0**
---
> ada: add version 2.4.0

- recipes/packio/all/conandata.yml
- recipes/packio/config.yml
Specify library name and version:  **packio/2.5.0**
---
> packio: add version 2.5.0

- recipes/pfr/all/conandata.yml
- recipes/pfr/config.yml
Specify library name and version:  **pfr/2.1.0**
---
> pfr: add version 2.1.0

- recipes/openapi-generator/all/conandata.yml
- recipes/openapi-generator/config.yml
> [openapi-generator] bump to 6.6.0

- recipes/benchmark/all/conandata.yml
- recipes/benchmark/config.yml
Specify library name and version:  **benchmark/1.8.0**
---
> benchmark: add version 1.8.0

- recipes/pcg-cpp/all/conandata.yml
- recipes/pcg-cpp/all/conanfile.py
- recipes/pcg-cpp/config.yml
Specify library name and version:  **pcg-cpp/***
---
> pcg-cpp: add versoin cci.20220409, add package_type

- recipes/ghc-filesystem/all/conandata.yml
- recipes/ghc-filesystem/config.yml
Specify library name and version:  **ghc-filesystem/1.5.14**
---
> ghc-filesystem: add version 1.5.14

- recipes/libmikmod/all/CMakeLists.txt
- recipes/libmikmod/all/conandata.yml
- recipes/libmikmod/all/conanfile.py
- recipes/libmikmod/all/patches/0001-fix-cmake.patch
- recipes/libmikmod/all/test_package/CMakeLists.txt
- recipes/libmikmod/all/test_package/conanfile.py
- recipes/libmikmod/all/test_v1_package/CMakeLists.txt
- recipes/libmikmod/all/test_v1_package/conanfile.py
> libmikmod: conan v2 support

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.4.1**
---
> ada: add version 2.4.1

- recipes/skyr-url/all/CMakeLists.txt
- recipes/skyr-url/all/conandata.yml
- recipes/skyr-url/all/conanfile.py
- recipes/skyr-url/all/test_package/CMakeLists.txt
- recipes/skyr-url/all/test_package/conanfile.py
- recipes/skyr-url/all/test_v1_package/CMakeLists.txt
- recipes/skyr-url/all/test_v1_package/conanfile.py
Specify library name and version:  **skyr-url/***
---
> skyr-url: support conan v2, update dependencies

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.42.0**
---
> update sqlite3 to version 3.42.0

- recipes/libcurl/all/conanfile.py
Specify library name and version:  **libcurl/all**
Superseeds https://github.com/conan-io/conan-center-index/pull/16673 because of CLA issues due to a faulty merge :)
Thanks to @roalter for pushing for this in the first instance
> libcurl: Use cert conf

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.4.2**
---
> ada: add version 2.4.2

- docs/adding_packages/conanfile_attributes.md
- docs/faqs.md
> docs: add standing convention for naming forks of projects

- recipes/luau/all/conandata.yml
- recipes/luau/config.yml
Specify library name and version:  **luau/0.577**
---
> luau: add version 0.577

- recipes/ccache/all/conandata.yml
- recipes/ccache/config.yml
Specify library name and version:  **ccache/4.8.1**
---
> ccache: add version 4.8.1

- recipes/xkbcommon/all/conanfile.py
> xkbcommon: bump deps

- recipes/sml/all/conandata.yml
- recipes/sml/all/patches/0001-arrow_up-1.1.8.patch
- recipes/sml/config.yml
Specify library name and version:  **sml/1.1.8**
---
> sml: add 1.1.8

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/4.0.1**
---
> unordered_dense: add version 4.0.1

- recipes/graphene/all/conanfile.py
Specify library name and version:  **graphene/***
---
> graphene: Bump glib and Meson versions

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/all/conanfile.py
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.17.1**
---
> daw_json_link: add version 3.17.1

- recipes/trantor/all/conandata.yml
- recipes/trantor/all/conanfile.py
- recipes/trantor/all/patches/1.5.5-0001-include-cstdint.patch
- recipes/trantor/all/patches/1.5.6-0001-include-cstdint.patch
- inclue stdint for uint8_t and intmax_t
---
> trantor: include cstdint

- recipes/gklib/all/CMakeLists.txt
- recipes/gklib/all/conandata.yml
- recipes/gklib/all/conanfile.py
- recipes/gklib/all/patches/004-increase-minimum-cmakelists.patch
- recipes/gklib/all/test_package/CMakeLists.txt
- recipes/gklib/all/test_package/conanfile.py
- recipes/gklib/all/test_v1_package/CMakeLists.txt
- recipes/gklib/all/test_v1_package/conanfile.py
Specify library name and version:  **gklib/5.1.1**
Update recipe to support conan v2
---
> gklib: conan v2 support

- recipes/bitmagic/all/conandata.yml
- recipes/bitmagic/all/conanfile.py
- recipes/bitmagic/all/test_package/conanfile.py
- recipes/bitmagic/all/test_v1_package/CMakeLists.txt
- recipes/bitmagic/config.yml
Specify library name and version:  **bitmagic/7.13.4**
---
> bitmagic: add version 7.13.4, add package_type

- recipes/naive-tsearch/all/CMakeLists.txt
- recipes/naive-tsearch/all/conandata.yml
- recipes/naive-tsearch/all/conanfile.py
- recipes/naive-tsearch/all/test_package/CMakeLists.txt
- recipes/naive-tsearch/all/test_package/conanfile.py
- recipes/naive-tsearch/all/test_v1_package/CMakeLists.txt
- recipes/naive-tsearch/all/test_v1_package/conanfile.py
- recipes/naive-tsearch/config.yml
Specify library name and version:  **naive-tsearch/***
---
> naive-tsearch: support conan v2

- recipes/harfbuzz/all/conanfile.py
> harfbuzz: bump dependencies

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Specify library name and version:  **glib/2.76.3**
---
> glib: add version 2.76.3

- recipes/sqlitecpp/all/conandata.yml
- recipes/sqlitecpp/config.yml
Specify library name and version:  **sqlitecpp/3.3.0**
---
> upgrade sqlitecpp to version 3.3.0

- recipes/lua/all/conandata.yml
- recipes/lua/all/conanfile.py
- recipes/lua/all/test_package/CMakeLists.txt
- recipes/lua/config.yml
Specify library name and version:  **lua/***
---
> lua: add version 5.4.6, add package_type

- recipes/harfbuzz/all/conanfile.py
Specify library name and version:  **harfbuzz/***
---
> harfbuzz/all: bump deps

- recipes/harfbuzz/all/conandata.yml
- recipes/harfbuzz/config.yml
Specify library name and version:  **harfbuzz/7.3.0**
---
> harfbuzz: add version 7.3.0

- recipes/hidapi/all/conandata.yml
- recipes/hidapi/all/conanfile.py
- recipes/hidapi/config.yml
Specify library name and version:  **hidapi/0.14.0**
---
> hidapi: add version 0.14.0

- recipes/lzma_sdk/9.20/conanfile.py
- recipes/lzma_sdk/9.20/test_package/conanfile.py
- recipes/lzma_sdk/9.20/test_v1_package/conanfile.py
Specify library name and version:  **lzma_sdk/9.20**
---
> lzma_sdk: Convert to Conan 2

- recipes/rectpack2d/all/conanfile.py
- recipes/rectpack2d/all/test_package/CMakeLists.txt
- recipes/rectpack2d/all/test_package/conanfile.py
- recipes/rectpack2d/all/test_v1_package/CMakeLists.txt
- recipes/rectpack2d/all/test_v1_package/conanfile.py
> rectpack2d: conan v2 support

- recipes/miniaudio/all/conandata.yml
- recipes/miniaudio/all/conanfile.py
- recipes/miniaudio/config.yml
Specify library name and version:  **miniaudio/0.11.16**
---
> miniaudio: add version 0.11.16

- recipes/tinyxml/all/conanfile.py
Specify library name and version:  **tinyxml/***
---
> tinyxml: add package_type, use rm_safe

- recipes/sobjectizer/all/conandata.yml
- recipes/sobjectizer/config.yml
Specify library name and version:  **sobjectizer/5.7.4.3**
---
> Update sobjectizer package for v5.7.4.3

- recipes/replxx/all/CMakeLists.txt
- recipes/replxx/all/conandata.yml
- recipes/replxx/all/conanfile.py
- recipes/replxx/all/test_package/CMakeLists.txt
- recipes/replxx/all/test_package/conanfile.py
- recipes/replxx/all/test_v1_package/CMakeLists.txt
- recipes/replxx/all/test_v1_package/conanfile.py
- recipes/replxx/config.yml
Specify library name and version:  **replxx/***
---
> replxx: support conan v2

- recipes/pixman/all/conanfile.py
Specify library name and version:  **pixman/***
---
> pixman: generate V2 package

- recipes/libpcap/all/conandata.yml
- recipes/libpcap/config.yml
Specify library name and version:  **libpcap/1.10.4**
---
> libpcap: add version 1.10.4

- recipes/xsimd/all/conandata.yml
- recipes/xsimd/all/conanfile.py
- recipes/xsimd/all/test_package/CMakeLists.txt
- recipes/xsimd/all/test_package/conanfile.py
- recipes/xsimd/all/test_v1_package/CMakeLists.txt
- recipes/xsimd/all/test_v1_package/conanfile.py
- recipes/xsimd/config.yml
Specify library name and version:  **xsimd/***
- add version 11.1.0
- update xtl
- use `is_apple_os`
---
> xsimd: add version 11.1.0, update xtl, minor improvement

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.5.0**
---
> ada: add version 2.5.0

- recipes/bzip3/all/conandata.yml
- recipes/bzip3/all/test_package/conanfile.py
- recipes/bzip3/config.yml
Specify library name and version:  **bzip3/1.3.1**
---
> bzip3: add version 1.3.1, add patch_description

- recipes/pystring/all/conanfile.py
Specify library name and version:  **pystring/***
---
> pystring: add package_type

- recipes/imath/all/conandata.yml
- recipes/imath/config.yml
Specify library name and version:  **imath/3.1.8**
---
> imath: add version 3.1.8

- recipes/plutovg/all/conandata.yml
- recipes/plutovg/all/conanfile.py
- recipes/plutovg/config.yml
Specify library name and version:  **plutovg/***
- add version cci.20230205
- use rm_safe
---
> plutovg: add version cci.20230205, add package_type

- recipes/ftxui/all/conandata.yml
- recipes/ftxui/all/conanfile.py
- recipes/ftxui/all/patches/4.1.1-0002-install-dll.patch
- recipes/ftxui/config.yml
Specify library name and version:  **ftxui/4.1.1**
---
> ftxui: add version 4.1.1

- recipes/bdwgc/all/conandata.yml
- recipes/bdwgc/all/conanfile.py
- recipes/bdwgc/all/patches/update-cmake-8_2_4.patch
- recipes/bdwgc/all/test_package/test_package.c
- recipes/bdwgc/config.yml
* Add gc/8.2.4 recipe
* Change requirements libatomic_ops from 7.6.14 to 7.8.0
Specify library name and version: gc/8.2.4
Full list of changes - https://github.com/ivmai/bdwgc/releases/tag/v8.2.4
I'm upstream maintainer of this library.
---
> Add gc/8.2.4 recipe

- recipes/yyjson/all/conandata.yml
- recipes/yyjson/all/conanfile.py
- recipes/yyjson/config.yml
Specify library name and version:  **yyjson/***
---
> yyjson: add version 0.7.0, add package_type

- recipes/tensorflow-lite/all/conandata.yml
- recipes/tensorflow-lite/all/conanfile.py
- recipes/tensorflow-lite/config.yml
> tensorflow-lite: Add version 2.12.0

- recipes/libnfs/all/conandata.yml
- recipes/libnfs/all/conanfile.py
- recipes/libnfs/config.yml
Specify library name and version:  **libnfs/5.0.2**
---
> libnfs: add version 5.0.2

- recipes/cyclonedds/all/conanfile.py
> cyclonedds: use version range for openssl & cmake

- recipes/lunasvg/all/conandata.yml
- recipes/lunasvg/all/conanfile.py
- recipes/lunasvg/all/test_package/CMakeLists.txt
- recipes/lunasvg/config.yml
Specify library name and version:  **lunasvg/***
---
> lunasvg: add version 2.3.8, add package_type

- recipes/roaring/all/conandata.yml
- recipes/roaring/config.yml
Specify library name and version:  **roaring/1.1.5**
---
> roaring: add version 1.1.5

- recipes/wasmtime-cpp/all/conandata.yml
- recipes/wasmtime-cpp/all/conanfile.py
- recipes/wasmtime-cpp/config.yml
Specify library name and version:  **wasmtime/9.0.0**
---
> wasmtime-cpp: add version 9.0.0

- .c3i/config_v2.yml
> conan V2 windows machine label updated

- recipes/opencl-clhpp-headers/all/conandata.yml
- recipes/opencl-clhpp-headers/all/conanfile.py
- recipes/opencl-clhpp-headers/all/test_package/CMakeLists.txt
- recipes/opencl-clhpp-headers/all/test_package/conanfile.py
- recipes/opencl-clhpp-headers/all/test_package/test_package.cpp
- recipes/opencl-clhpp-headers/all/test_v1_package/CMakeLists.txt
- recipes/opencl-clhpp-headers/all/test_v1_package/conanfile.py
- recipes/opencl-clhpp-headers/config.yml
Specify library name and version:  **opencl-clhpp-headers/2023.04.17**
Similar packages:
- https://formulae.brew.sh/formula/opencl-clhpp-headers
- https://anaconda.org/conda-forge/clhpp
Since it's hard to write apps on C API, C++ API is very helpful. 
Library was requested in several places:
- Resolves https://github.com/conan-io/conan-center-index/issues/13239
- Resolves https://github.com/KhronosGroup/OpenCL-CLHPP/issues/171
---
> Added opencl-clhpp-headers package

- recipes/mimalloc/all/conandata.yml
- recipes/mimalloc/all/conanfile.py
- recipes/mimalloc/all/patches/1.8.2-0001-change-install-paths.patch
- recipes/mimalloc/all/patches/1.8.2-0002-support-older-compiler.patch
- recipes/mimalloc/all/patches/2.1.2-0001-change-install-paths.patch
- recipes/mimalloc/all/patches/2.1.2-0002-support-older-compiler.patch
- recipes/mimalloc/config.yml
Specify library name and version:  **mimalloc/***
---
> mimalloc: add version 1.8.2, 2.1.2, add package_type

- .c3i/config_v1.yml
> conan V1 windows machine label updated

- recipes/uvw/all/conandata.yml
- recipes/uvw/all/conanfile.py
- recipes/uvw/all/test_package/CMakeLists.txt
- recipes/uvw/all/test_package/test_package.cpp
- recipes/uvw/config.yml
Specify library name and version:  **uvw/***
---
> uvw: add version 3.1.0

- recipes/sobjectizer/all/conandata.yml
- recipes/sobjectizer/config.yml
Specify library name and version:  **sobjectizer/5.7.4**
--
> Update SObjectizer v.5.7.4

- recipes/svector/all/conandata.yml
- recipes/svector/config.yml
Specify library name and version:  **svector/1.0.3**
---
> svector: add version 1.0.3

- recipes/octo-logger-cpp/all/conandata.yml
- recipes/octo-logger-cpp/config.yml
Specify library name and version:  **octo-logger-cpp/1.4.0**
---
> octo-logger-cpp: add version 1.4.0

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  **cmake/3.26.4**
---
> Bumped CMake to 3.26.4

- recipes/uni-algo/all/conandata.yml
- recipes/uni-algo/config.yml
Specify library name and version:  **uni-algo/0.8.1**
---
> uni-algo: add version 0.8.1

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/all/conanfile.py
- recipes/mongo-c-driver/config.yml
Specify library name and version:  **mongo-c-driver/1.23.4**
- add version 1.23.4
- update icu
---
> mongo-c-driver: add version 1.23.4

- recipes/duckdb/all/conandata.yml
- recipes/duckdb/all/patches/0.8.0-0001-fix-cmake.patch
- recipes/duckdb/config.yml
Specify library name and version:  **duckdb/0.8.0**
---
> [duckdb] add version 0.8.0

- recipes/quill/all/conandata.yml
- recipes/quill/config.yml
Specify library name and version:  **quill/2.9.2**
---
> quill: add version 2.9.2

- recipes/wasmer/all/conandata.yml
- recipes/wasmer/all/conanfile.py
- recipes/wasmer/config.yml
Specify library name and version:  **wasmer/***
- add version 3.2.1
- use copy instead of self.copy
---
> wasmer: add version 3.2.1

- recipes/dbcppp/all/conanfile.py
> dbcppp: remove invalid option + set package_type

- recipes/sbepp/all/conandata.yml
- recipes/sbepp/config.yml
Specify library name and version:  **sbepp/1.1.0**
Add `1.1.0` version.
---
> sbepp: add 1.1.0 version

- recipes/timsort/all/conandata.yml
- recipes/timsort/all/conanfile.py
- recipes/timsort/all/test_package/CMakeLists.txt
- recipes/timsort/all/test_package/conanfile.py
- recipes/timsort/all/test_v1_package/CMakeLists.txt
- recipes/timsort/all/test_v1_package/conanfile.py
- recipes/timsort/config.yml
> timsort: conan v2 support

- recipes/librasterlite/all/conandata.yml
- recipes/librasterlite/all/conanfile.py
- recipes/librasterlite/all/patches/0002-nmake-honor-flags.patch
- recipes/librasterlite/all/test_package/CMakeLists.txt
- recipes/librasterlite/all/test_package/conanfile.py
- recipes/librasterlite/all/test_v1_package/CMakeLists.txt
- recipes/librasterlite/all/test_v1_package/conanfile.py
> librasterlite: conan v2 support

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/config.yml
Specify library name and version:  **mongo-c-driver/1.23.5**
---
> mongo-c-driver: add version 1.23.5

- recipes/imath/all/conandata.yml
- recipes/imath/config.yml
Specify library name and version:  **imath/3.1.9**
---
> imath: add version 3.1.9

- recipes/zlib-ng/all/conandata.yml
- recipes/zlib-ng/all/conanfile.py
- recipes/zlib-ng/config.yml
Specify library name and version:  **zlib-ng/2.1.2**
---
> zlib-ng: add version 2.1.2

- recipes/dbus/1.x.x/conandata.yml
- recipes/dbus/1.x.x/conanfile.py
- recipes/dbus/config.yml
Specify library name and version:  **dbus/1.15.6**
---
> dbus 1.15.6

- recipes/libcurl/all/conandata.yml
- recipes/libcurl/all/conanfile.py
- recipes/libcurl/config.yml
> libcurl: add version 8.1.2, update c-ares

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.12.5**
---
> cpp-httplib: add version 0.12.5

- recipes/libcurl/all/conanfile.py
> libcurl: update libnghttp2 1.54.0

- recipes/hdf5/all/conandata.yml
- recipes/hdf5/config.yml
Specify library name and version: hdf5/1.14.1
---
> hdf5: add v1.14.1

- recipes/magic_enum/all/conandata.yml
- recipes/magic_enum/config.yml
Specify library name and version:  **magic_enum/0.9.2**
---
> magic_enum: add version 0.9.2

- recipes/proposal/all/conandata.yml
- recipes/proposal/config.yml
Specify library name and version:  **proposal/7.6.0**
---
> proposal: add version 7.6.0

- recipes/atk/all/conanfile.py
Specify library name and version:  **atk/***
---
> atk: remove outdated workaround

- recipes/cairo/meson/conanfile.py
Specify library name and version:  **cairo/1.0**
---
> cairo: bump deps

- recipes/mozilla-build/all/conanfile.py
- recipes/mozilla-build/all/test_package/conanfile.py
Specify library name and version:  **mozilla-build/***
---
> mozilla-build: conan V2 compatibility

- recipes/proposal/all/conandata.yml
- recipes/proposal/config.yml
Specify library name and version:  **proposal/7.6.1**
---
> proposal: add version 7.6.1

- recipes/scnlib/all/conanfile.py
Specify library name and version:  **scnlib/***
---
> scnlib: update fast_float 5.2.0

- recipes/zulu-openjdk/all/conandata.yml
- recipes/zulu-openjdk/all/conanfile.py
- recipes/zulu-openjdk/config.yml
Specify library name and version:  **zulu-openjdk/***
---
> zulu-openjdk: add version 11.0.19, several improvements

- recipes/wil/all/conandata.yml
- recipes/wil/config.yml
Specify library name and version:  **wil/1.0.230411.1**
---
> wil: add version 1.0.230411.1

- recipes/vulkan-headers/all/conandata.yml
- recipes/vulkan-headers/config.yml
**vulkan-headers/1.3.250**
Update for the new relese of Vulkan SDK.
---
> vulkan-headers: Add 1.3.250

- recipes/at-spi2-core/new/conanfile.py
Specify library name and version:  **at-spi2-core/***
---
> Bump/at spi2 core/new

- recipes/rapidfuzz/all/conandata.yml
- recipes/rapidfuzz/all/conanfile.py
- recipes/rapidfuzz/all/test_package/CMakeLists.txt
- recipes/rapidfuzz/config.yml
Specify library name and version:  **rapidfuzz/2.0.0**
---
> rapidfuzz: add version 2.0.0, add package_type

- recipes/c4core/all/conanfile.py
> c4core: update fast_float 5.2.0

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/all/conanfile.py
- recipes/daw_json_link/config.yml
> daw_json_link: add version 3.17.2, update daw_header_libraries

- recipes/glaze/all/conandata.yml
- recipes/glaze/all/conanfile.py
- recipes/glaze/config.yml
> glaze: add version 1.2.6, update fast_float

- recipes/proposal/all/conandata.yml
- recipes/proposal/config.yml
Specify library name and version:  **proposal/7.6.2**
---
> proposal: add version 7.6.2

- recipes/duckdb/all/conandata.yml
- recipes/duckdb/all/patches/0.8.1-0001-fix-cmake.patch
- recipes/duckdb/config.yml
Specify library name and version:  **duckdb/0.8.1**
---
> duckdb: add version 0.8.1

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.2.0**
---
> simdjson: add version 3.2.0

- recipes/quill/all/conandata.yml
- recipes/quill/config.yml
Specify library name and version:  **quill/3.0.2**
---
> quill: add version 3.0.2

- recipes/charls/all/conandata.yml
- recipes/charls/config.yml
Specify library name and version:  **charls/2.4.2**
---
> charls: add version 2.4.2

- recipes/watcher/all/conandata.yml
- recipes/watcher/config.yml
Specify library name and version:  **watcher/0.8.8**
---
> watcher: add version 0.8.8

- recipes/strong_type/all/conandata.yml
- recipes/strong_type/all/conanfile.py
- recipes/strong_type/all/test_package/conanfile.py
- recipes/strong_type/config.yml
Specify library name and version:  **strong_type/***
- add version v11
- sort config.yml, conandata.yml
- reorder ConanFile property
- ... other several improvements
---
> strong_type: add version v11, add package_type

- recipes/libinterpolate/all/conandata.yml
- recipes/libinterpolate/config.yml
Adding recipe for latest version of library.
---
- [x ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
> [libinterpolate]: added version 2.6.3

- recipes/cppdap/all/conandata.yml
- recipes/cppdap/all/conanfile.py
- recipes/cppdap/all/patches/0001-build-cmake-use-min-CMake-version-prior-to-project-c.patch
- recipes/cppdap/all/test_package/CMakeLists.txt
- recipes/cppdap/all/test_package/conanfile.py
- recipes/cppdap/all/test_package/test_package.cpp
- recipes/cppdap/config.yml
Specify library name and version:  **cppdap/cci.20230526**
CMake 3.27 will have `cppdap` as a dependency (see [merge request](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8338))
---
> cppdap: add recipe

- recipes/c-blosc/all/conandata.yml
- recipes/c-blosc/all/conanfile.py
- recipes/c-blosc/all/patches/cmake-dependencies-1.21.4+.patch
- recipes/c-blosc/config.yml
Specify library name and version:  **c-blosc/***
---
> c-blosc: add version 1.21.4, add package_type

- recipes/cuda-api-wrappers/all/conandata.yml
- recipes/cuda-api-wrappers/all/conanfile.py
- recipes/cuda-api-wrappers/all/test_package/CMakeLists.txt
- recipes/cuda-api-wrappers/all/test_package/conanfile.py
- recipes/cuda-api-wrappers/all/test_package/test_package.cpp
- recipes/cuda-api-wrappers/config.yml
Specify library name and version:  **cuda-api-wrappers/0.6.3**
https://github.com/eyalroz/cuda-api-wrappers
---
> cuda-api-wrappers: add new recipe

- recipes/cuda-kat/all/conanfile.py
- recipes/cuda-kat/all/test_package/CMakeLists.txt
- recipes/cuda-kat/all/test_package/conanfile.py
Specify library name and version:  **cuda-kat/0.2**
---
> cuda-kat: update recipe to Conan v2

- recipes/gperftools/all/conandata.yml
- recipes/gperftools/all/conanfile.py
- recipes/gperftools/all/test_package/CMakeLists.txt
- recipes/gperftools/all/test_package/conanfile.py
- recipes/gperftools/all/test_package/test_package.cpp
- recipes/gperftools/config.yml
Specify library name and version:  **gperftools/2.10**
This package has quite a few options affecting the library files being generated. I have tested all relevant combinations locally on Linux.
Resolves #1362.
---
> gperftools: add new recipe

- recipes/jinja2cpp/all/CMakeLists.txt
- recipes/jinja2cpp/all/conandata.yml
- recipes/jinja2cpp/all/conanfile.py
- recipes/jinja2cpp/all/patches/fix-cmake-1.1.0.patch
- recipes/jinja2cpp/all/patches/fix-cmake-1.2.1.patch
- recipes/jinja2cpp/all/test_package/CMakeLists.txt
- recipes/jinja2cpp/all/test_package/conanfile.py
Specify library name and version:  **jinja2cpp/***
---
> jinja2cpp: support conan v2, update dependencies

- recipes/vo-amrwbenc/all/conandata.yml
- recipes/vo-amrwbenc/all/conanfile.py
- recipes/vo-amrwbenc/all/test_package/CMakeLists.txt
- recipes/vo-amrwbenc/all/test_package/conanfile.py
- recipes/vo-amrwbenc/all/test_package/test_package.c
- recipes/vo-amrwbenc/config.yml
Specify library name and version:  **vo-amrwbenc/0.1.3**
We need this this G.722.2 encoder for SIP telephony.
---
> vo-amrwbenc: add version 0.1.3

- recipes/cairo/all/conanfile.py
Specify library name and version:  **cairo/***
---
> cairo: Add package_type and bump dependencies

- recipes/glpk/all/conanfile.py
- recipes/glpk/all/test_package/CMakeLists.txt
- recipes/glpk/all/test_package/conanfile.py
- recipes/glpk/all/test_package/test_package.c
- recipes/glpk/all/test_v1_package/CMakeLists.txt
- recipes/glpk/all/test_v1_package/conanfile.py
Specify library name and version:  **glpk/5.0**
This work is based on the previous attempt #14319 on providing conan v2 support for the glpk recipe.
---
> glpk: Add recipe with conan v2 support

- recipes/libdrawille/all/conandata.yml
- recipes/libdrawille/all/conanfile.py
- recipes/libdrawille/all/patches/0001-fix-cmake.patch
- recipes/libdrawille/all/patches/0001-use-cmake.patch
- recipes/libdrawille/all/patches/0002-support-msvc.patch
- recipes/libdrawille/all/test_package/CMakeLists.txt
- recipes/libdrawille/all/test_package/conanfile.py
- recipes/libdrawille/all/test_package/test_package.c
- recipes/libdrawille/all/test_v1_package/CMakeLists.txt
- recipes/libdrawille/all/test_v1_package/conanfile.py
- recipes/libdrawille/config.yml
Specify library name and version:  **libdrawille/***
---
> libdrawille: add recipe

- recipes/onnxruntime/all/conandata.yml
- recipes/onnxruntime/all/conanfile.py
- recipes/onnxruntime/all/patches/1.14.1-0002-cmake-dependencies.patch
- recipes/onnxruntime/all/patches/1.15.0-0001-cmake-dependencies.patch
- recipes/onnxruntime/all/patches/1.15.1-0001-cmake-dependencies.patch
- recipes/onnxruntime/config.yml
Specify library name and version:  **onnxruntime/1.15.1**
---
> onnxruntime: add 1.15.1

- recipes/sentry-native/all/conandata.yml
- recipes/sentry-native/config.yml
> [sentry-native] Add version 0.6.2

- recipes/numcpp/all/conandata.yml
- recipes/numcpp/all/conanfile.py
- recipes/numcpp/config.yml
Specify library name and version:  **numcpp/2.10.1**
---
> numcpp: add version 2.10.1, update boost

- recipes/libmount/all/conandata.yml
- recipes/libmount/config.yml
Specify library name and version:  **libmount/2.39**
---
> libmount 2.39

- recipes/magic_enum/all/conandata.yml
- recipes/magic_enum/config.yml
Specify library name and version:  **magic_enum/0.9.3**
---
> magic_enum: add version 0.9.3

- recipes/libgettext/all/conandata.yml
- recipes/libgettext/all/conanfile.py
- recipes/libgettext/config.yml
Specify library name and version:  **libggettext/0.22**
---
> libggettext 0.22

- recipes/sentry-breakpad/all/conandata.yml
- recipes/sentry-breakpad/config.yml
> [sentry-breakpad/0.6.3] Add version

- recipes/util-linux-libuuid/all/conandata.yml
- recipes/util-linux-libuuid/all/conanfile.py
Specify library name and version:  **util-linux-libuuid/2.39**
---
> util-linux-libuuid: enable macos

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/all/test_package/test_package.cpp
- recipes/cpp-httplib/config.yml
This PR superseeds this one: https://github.com/conan-io/conan-center-index/pull/17897
- I think that PR was stuck because the test_package so adding a minimal test_package
- Adding the 0.12.6 version but also taking the chance to clean some versions
cc/ @toge
> Simplify cpp-httplib recipe

- recipes/redis-plus-plus/all/conandata.yml
- recipes/redis-plus-plus/all/conanfile.py
- recipes/redis-plus-plus/all/patches/1.3.8-0001-fix-dependencies-injection.patch
- recipes/redis-plus-plus/all/test_package/CMakeLists.txt
- recipes/redis-plus-plus/config.yml
Specify library name and version:  **redis-plus-plus/1.3.8**
---
> redis-plus-plus: add version 1.3.8

- recipes/wayland/all/conandata.yml
- recipes/wayland/config.yml
Specify library name and version:  **wayland/1.22.0**
---
> wayland: add version 1.22.0

- recipes/lest/all/conanfile.py
- recipes/lest/all/test_package/CMakeLists.txt
- recipes/lest/all/test_package/conanfile.py
Specify library name and version:  **lest/1.35.1**
---
> lest: migrate to Conan v2

- recipes/wayland-protocols/all/conanfile.py
- recipes/wayland-protocols/all/test_package/conanfile.py
Specify library name and version:  **wayland-protocols/***
---
> wayland-protocols/all: bump deps

- recipes/tlx/all/conandata.yml
- recipes/tlx/config.yml
Specify library name and version:  **tlx/0.6.1**
---
> tlx: add version 0.6.1

- recipes/highs/all/conandata.yml
- recipes/highs/all/conanfile.py
- recipes/highs/config.yml
Specify library name and version:  **highs/1.5.3**
---
> highs: add version 1.5.3

- recipes/wasmer/all/conandata.yml
- recipes/wasmer/config.yml
Specify library name and version:  **wasmer/4.0.0**
---
> wasmer: add version 4.0.0

- recipes/luau/all/conandata.yml
- recipes/luau/config.yml
Specify library name and version:  **luau/0.582**
---
> luau: add version 0.582

- recipes/numcpp/all/conandata.yml
- recipes/numcpp/all/conanfile.py
- recipes/numcpp/config.yml
Specify library name and version:  **numcpp/***
---
> numcpp: add version 2.11.0, update boost

- recipes/sentry-crashpad/all/conandata.yml
- recipes/sentry-crashpad/all/test_package/CMakeLists.txt
- recipes/sentry-crashpad/all/test_package/conanfile.py
- recipes/sentry-crashpad/all/test_package/test_package.cpp
- recipes/sentry-crashpad/all/test_v1_package/conanfile.py
- recipes/sentry-crashpad/config.yml
> [sentry-crashpad/0.6.3] Bump version

- recipes/cpr/all/conandata.yml
- recipes/cpr/all/conanfile.py
- recipes/cpr/config.yml
Specify library name and version:  **cpr/***
---
> cpr: add version 1.10.4, update libcurl

- recipes/minimp3/all/conandata.yml
- recipes/minimp3/all/conanfile.py
- recipes/minimp3/all/test_package/conanfile.py
- recipes/minimp3/config.yml
Specify library name and version:  **minimp3/***
---
> minimp3: add version cci.20211201

- recipes/id3v2lib/all/conanfile.py
Specify library name and version:  **id3v2lib/2.1**
Fix copy & paste typo in recipe class name.
---
> id3v2lib: Fix recipe class name.

- recipes/entt/3.x.x/conandata.yml
- recipes/entt/3.x.x/conanfile.py
- recipes/entt/3.x.x/patches/0002-3.12.1-fix-gcc-7.0-7.3.patch
- recipes/entt/config.yml
Specify library name and version:  **entt/3.12.2**
---
> entt: add version 3.12.2

- recipes/sentry-breakpad/config.yml
- recipes/sentry-crashpad/all/conandata.yml
- recipes/sentry-crashpad/config.yml
> [sentry-crashpad] Update to 0.6.4

- recipes/simde/all/conandata.yml
- recipes/simde/all/conanfile.py
- recipes/simde/all/test_package/CMakeLists.txt
- recipes/simde/all/test_package/conanfile.py
- recipes/simde/all/test_package/test_package.c
- recipes/simde/config.yml
Specify library name and version:  **simde/0.7.6**
Try to close https://github.com/conan-io/conan-center-index/issues/17771.
---
> simde: add recipe

- recipes/sonic-cpp/all/conandata.yml
- recipes/sonic-cpp/all/conanfile.py
- recipes/sonic-cpp/all/patches/1.0.0-0001-use-cci.patch
- recipes/sonic-cpp/all/test_package/CMakeLists.txt
- recipes/sonic-cpp/all/test_package/conanfile.py
- recipes/sonic-cpp/all/test_package/test_package.cpp
- recipes/sonic-cpp/all/test_v1_package/CMakeLists.txt
- recipes/sonic-cpp/all/test_v1_package/conanfile.py
- recipes/sonic-cpp/config.yml
Specify library name and version:  **sonic-cpp/***
---
> sonic-cpp: add recipe

- recipes/continuable/all/conanfile.py
- recipes/continuable/all/test_package/CMakeLists.txt
- recipes/continuable/all/test_package/conanfile.py
- recipes/continuable/all/test_package/test_package.cpp
> continuable: migrate to Conan v2

- recipes/r8brain-free-src/all/conandata.yml
- recipes/r8brain-free-src/all/conanfile.py
- recipes/r8brain-free-src/config.yml
Specify library name and version:  **r8brain-free-src/***
---
> r8brain-free-src: add version 6.3, add package_type

- recipes/rapidcsv/all/conandata.yml
- recipes/rapidcsv/all/conanfile.py
- recipes/rapidcsv/config.yml
Specify library name and version:  **rapidcsv/***
---
> rapidcsv: add version 8.77, add package_type

- recipes/libpng/all/conandata.yml
- recipes/libpng/all/conanfile.py
- recipes/libpng/config.yml
Specify library name and version:  **libpng/1.6.40**
---
> libpng: add 1.6.40 version

- recipes/cute_headers/all/conanfile.py
- recipes/cute_headers/all/test_package/CMakeLists.txt
- recipes/cute_headers/all/test_package/conanfile.py
Specify library name and version:  **cute_headers/cci.20201022**
---
> cute_headers: conan v2 support

- recipes/nextsilicon-cpp-subprocess/all/conanfile.py
Follow-up to https://github.com/conan-io/conan-center-index/pull/18127/files#r1246355487
> nextsilicon-cpp-subprocess: add cppstd check, fix typo

- recipes/zlib-ng/all/conandata.yml
- recipes/zlib-ng/config.yml
Specify library name and version:  **zlib-ng/2.1.3**
---
> zlib-ng: add version 2.1.3

- recipes/libbigwig/all/conanfile.py
Specify library name and version:  **libbigwig/all**
---
> libbigwig: bump deps

- recipes/libunwind/all/conandata.yml
- recipes/libunwind/config.yml
Specify library name and version:  **libunwind/1.7.0**
---
> libunwind: Add version 1.7.0.

- recipes/tinygltf/all/conandata.yml
- recipes/tinygltf/all/conanfile.py
- recipes/tinygltf/config.yml
Specify library name and version:  **tinygltf/***
---
> tinygltf: add version 2.8.13, update dependencies

- recipes/tinyexr/all/conandata.yml
- recipes/tinyexr/all/conanfile.py
- recipes/tinyexr/config.yml
Specify library name and version:  **tinyexr/1.0.6**
---
> tinyexr: add version 1.0.6, add package_type

- recipes/outcome/all/conandata.yml
- recipes/outcome/config.yml
Specify library name and version:  **outcome/2.2.4**
---
> Add outcome-2.2.4

- recipes/fontconfig/meson/conanfile.py
see converstation in https://github.com/conan-io/conan-center-index/pull/17995#issuecomment-1614987627.
There are a lot of issues that popping on with the consequences and  we will plan how to rollout this next week.
---
> revert: fontconfig: migrate to util-linux-libuuid

- recipes/quill/all/conandata.yml
- recipes/quill/config.yml
> quill: add version 3.1.0, remove older versions

- recipes/libuv/all/conandata.yml
- recipes/libuv/config.yml
Specify library name and version:  **libuv/1.46.0**
---
> libuv: add version 1.46.0

- recipes/libwebp/all/conandata.yml
- recipes/libwebp/all/patches/1.3.1-0001-fix-cmake.patch
- recipes/libwebp/config.yml
Specify library name and version:  **libwebp/1.3.1**
---
> libwebp: add version 1.3.1

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
> glaze: add version 1.3.0, remove older versions

- recipes/mailio/all/conandata.yml
- recipes/mailio/all/conanfile.py
- recipes/mailio/all/patches/0.23.0-adapt-cmakelists.patch
- recipes/mailio/all/test_package/CMakeLists.txt
- recipes/mailio/all/test_package/test_package.cpp
- recipes/mailio/config.yml
Specify library name and version:  **mailio/***
---
> mailio: add version 0.23.0, update boost

- recipes/zimg/all/conandata.yml
- recipes/zimg/all/conanfile.py
- recipes/zimg/config.yml
Specify library name and version:  **zimg/***
---
> zimg: add version 3.0.5, add package_type

- recipes/jsoncons/all/conandata.yml
- recipes/jsoncons/all/conanfile.py
- recipes/jsoncons/all/test_package/CMakeLists.txt
- recipes/jsoncons/config.yml
Specify library name and version:  **jsoncons/***
---
> jsoncons: add version 0.170.2, add package_type

- recipes/libunwind/all/conanfile.py
https://github.com/conan-io/conan-center-index/pull/18319
---
> libunwind: bump dep xz_utils

- recipes/sdl_image/all/conanfile.py
> sdl_image: bump dep sdl to latest patch

- recipes/cjson/all/conandata.yml
- recipes/cjson/config.yml
Specify library name and version:  **cjson/1.7.16**
---
> cjson: add version 1.7.16

- recipes/pprint/all/conanfile.py
- recipes/pprint/all/test_package/CMakeLists.txt
- recipes/pprint/all/test_package/conanfile.py
- recipes/pprint/all/test_v1_package/CMakeLists.txt
- recipes/pprint/all/test_v1_package/conanfile.py
> pprint: migrate to Conan v2

- recipes/benchmark/all/conandata.yml
- recipes/benchmark/config.yml
Specify library name and version:  **benchmark/1.8.1**
---
> benchmark: add version 1.8.1

- recipes/snowhouse/all/conanfile.py
- recipes/snowhouse/all/test_package/CMakeLists.txt
- recipes/snowhouse/all/test_package/conanfile.py
- recipes/snowhouse/all/test_v1_package/CMakeLists.txt
- recipes/snowhouse/all/test_v1_package/conanfile.py
> snowhouse: migrate to Conan v2

- recipes/uvw/all/conandata.yml
- recipes/uvw/all/conanfile.py
- recipes/uvw/config.yml
Specify library name and version:  **uvw/3.2.0**
---
> uvw: add version 3.2.0

- recipes/libtiff/all/conanfile.py
Specify library name and version:  **libtiff/***
---
> libtiff/all: bump deps

- recipes/thelink2012-any/all/conanfile.py
- recipes/thelink2012-any/all/test_package/CMakeLists.txt
- recipes/thelink2012-any/all/test_package/conanfile.py
- recipes/thelink2012-any/all/test_v1_package/CMakeLists.txt
- recipes/thelink2012-any/all/test_v1_package/conanfile.py
> thelink2012-any: migrate to Conan v2

- recipes/nanoflann/all/conandata.yml
- recipes/nanoflann/config.yml
Specify library name and version:  **nanoflann/1.5.0**
---
> nanoflann: add version 1.5.0

- recipes/quaternions/all/conanfile.py
- recipes/quaternions/all/test_package/CMakeLists.txt
- recipes/quaternions/all/test_package/conanfile.py
- recipes/quaternions/all/test_v1_package/CMakeLists.txt
- recipes/quaternions/all/test_v1_package/conanfile.py
> quaternions: migrate to Conan v2

- recipes/opencv/4.x/conanfile.py
Specify library name and version:  **opencv/4.X**
Was causing build failures for me.
---
> opencv: bump libwebp version

- recipes/cppcheck/all/conandata.yml
- recipes/cppcheck/all/conanfile.py
- recipes/cppcheck/config.yml
> cppcheck: Add version 2.11.1

- recipes/freetype/all/conanfile.py
> freetype: bump dep libpng

- recipes/pranav-csv2/all/conanfile.py
- recipes/pranav-csv2/all/test_package/CMakeLists.txt
- recipes/pranav-csv2/all/test_package/conanfile.py
- recipes/pranav-csv2/all/test_package/test_package.cpp
- recipes/pranav-csv2/all/test_v1_package/CMakeLists.txt
- recipes/pranav-csv2/all/test_v1_package/conanfile.py
> pranav-csv2: migrate to Conan v2

- recipes/type_safe/all/conanfile.py
- recipes/type_safe/all/test_package/CMakeLists.txt
- recipes/type_safe/all/test_package/conanfile.py
- recipes/type_safe/all/test_v1_package/CMakeLists.txt
- recipes/type_safe/all/test_v1_package/conanfile.py
> type_safe: migrate to Conan v2

- recipes/serdepp/all/conanfile.py
- recipes/serdepp/all/test_package/CMakeLists.txt
- recipes/serdepp/all/test_package/conanfile.py
- recipes/serdepp/all/test_package/test_package.cpp
- recipes/serdepp/all/test_v1_package/CMakeLists.txt
- recipes/serdepp/all/test_v1_package/conanfile.py
> serdepp: migrate to Conan v2

- recipes/dice-template-library/all/conanfile.py
- recipes/dice-template-library/all/test_package/CMakeLists.txt
- recipes/dice-template-library/all/test_package/conanfile.py
- recipes/dice-template-library/all/test_package/test_package.cpp
- recipes/dice-template-library/all/test_v1_package/CMakeLists.txt
- recipes/dice-template-library/all/test_v1_package/conanfile.py
> dice-template-library: migrate to Conan v2

- recipes/xxsds-sdsl-lite/all/conandata.yml
- recipes/xxsds-sdsl-lite/all/conanfile.py
- recipes/xxsds-sdsl-lite/all/test_package/CMakeLists.txt
- recipes/xxsds-sdsl-lite/all/test_package/conanfile.py
- recipes/xxsds-sdsl-lite/all/test_v1_package/CMakeLists.txt
- recipes/xxsds-sdsl-lite/all/test_v1_package/conanfile.py
> xxsds-sdsl-lite: migrate to Conan v2

- recipes/zug/all/conanfile.py
- recipes/zug/all/test_package/CMakeLists.txt
- recipes/zug/all/test_package/conanfile.py
- recipes/zug/all/test_package/example.cpp
- recipes/zug/all/test_v1_package/CMakeLists.txt
- recipes/zug/all/test_v1_package/conanfile.py
> zug: migrate to Conan v2

- recipes/libdivide/all/conanfile.py
- recipes/libdivide/all/test_package/CMakeLists.txt
- recipes/libdivide/all/test_package/conanfile.py
- recipes/libdivide/all/test_v1_package/CMakeLists.txt
- recipes/libdivide/all/test_v1_package/conanfile.py
- recipes/libdivide/all/test_v1_package/test_package.c
> libdivide: migrate to Conan v2

- recipes/pretty-name/all/conanfile.py
- recipes/pretty-name/all/test_package/CMakeLists.txt
- recipes/pretty-name/all/test_package/conanfile.py
- recipes/pretty-name/all/test_v1_package/CMakeLists.txt
- recipes/pretty-name/all/test_v1_package/conanfile.py
- recipes/pretty-name/all/test_v1_package/src/test.cpp
> pretty-name: migrate to Conan v2

- recipes/ffmpeg/all/conandata.yml
- recipes/ffmpeg/all/conanfile.py
- recipes/ffmpeg/config.yml
> ffmpeg: add version 6.0

- recipes/hwloc/all/conandata.yml
- recipes/hwloc/config.yml
Specify library name and version:  **hwloc/2.9.2**
---
> hwloc 2.9.2

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.2.1**
---
> simdjson: add version 3.2.1, remove older versions

- recipes/eastl/all/conandata.yml
- recipes/eastl/all/conanfile.py
- recipes/eastl/all/patches/3.21.12-0001-cmake-shared-use-conan-add-install.patch
- recipes/eastl/all/patches/3.21.12-0003-rename_reference.patch
- recipes/eastl/config.yml
Specify library name and version:  **eastl/***
---
> eastl: add version 3.21.12, add patch descriptions

- .github/workflows/alert-community.yml
> Add MartinDelille as reviewer for snowhouse

- recipes/zxing-cpp/all/conandata.yml
- recipes/zxing-cpp/all/conanfile.py
- recipes/zxing-cpp/config.yml
Specify library name and version:  **zxing-cpp/2.1.0**
---
> zxing-cpp: add version 2.1.0, add package_type

- recipes/etl/all/conandata.yml
- recipes/etl/config.yml
Specify library name and version:  **etl/***
---
> etl: add version 20.37.0, remove older versions

- recipes/cyclonedds/all/conandata.yml
- recipes/cyclonedds/config.yml
**cyclonedds/0.10.3**
Update version to 0.10.3
---
> cyclonedds: Bump version to 0.10.3

- recipes/libharu/all/conanfile.py
> libharu: bump deps

- recipes/jsoncons/all/conandata.yml
- recipes/jsoncons/config.yml
Specify library name and version:  **jsoncons/0.171.0**
---
> jsoncons: add version 0.171.0

- recipes/uni-algo/all/conandata.yml
- recipes/uni-algo/config.yml
Specify library name and version:  **uni-algo/1.0.0**
---
> uni-algo: add version 1.0.0

- recipes/sentry-crashpad/all/conandata.yml
- recipes/sentry-crashpad/config.yml
> [sentry-crashpad/0.6.5] Add version

- recipes/freeimage/all/conanfile.py
Specify library name and version:  **freeimage/all**
---
> freeimage/all: bump deps

- recipes/cairo/meson/conanfile.py
Specify library name and version:  **cairo/meson**
---
> cairo/meson: bump deps

- recipes/opencv/2.x/conanfile.py
Specify library name and version:  **opencv/2.x**
---
> opencv/2.x: bump deps

- recipes/sqlpp11/all/conandata.yml
- recipes/sqlpp11/config.yml
Specify library name and version:  **sqlpp11/0.63**
---
> sqlpp11: add version 0.63

- recipes/spdlog/all/conandata.yml
- recipes/spdlog/config.yml
Specify library name and version:  **spdlog/1.12.0**
Try to close https://github.com/conan-io/conan-center-index/issues/18445.
---
> spdlog: add version 1.12.0

- recipes/libraw/all/conanfile.py
Specify library name and version:  **libraw/all**
This should also generate some missing packages required by https://github.com/conan-io/conan-center-index/pull/18432
---
> libraw/all: bump deps

- recipes/fastgltf/all/conandata.yml
- recipes/fastgltf/all/conanfile.py
- recipes/fastgltf/all/patches/0.5.0-0001-find_package-simdjson.patch
- recipes/fastgltf/all/test_package/CMakeLists.txt
- recipes/fastgltf/all/test_package/conanfile.py
- recipes/fastgltf/all/test_package/test_package.cpp
- recipes/fastgltf/all/test_v1_package/conanfile.py
- recipes/fastgltf/config.yml
Specify library name and version:  **fastgltf/***
---
> fastgltf: add version 0.5.0, update simdjson, small improvements

- recipes/sail/all/conanfile.py
Specify library name and version:  **sail/all**
---
> sail/all: bump deps

- recipes/opencv/3.x/conanfile.py
Specify library name and version:  **opencv/3.x**
---
> opencv/3.x: bump deps

- recipes/leptonica/all/conanfile.py
Specify library name and version:  **leptonica/all**
---
> leptonica/all: bump deps

- recipes/opencv/4.x/conanfile.py
Specify library name and version:  **opencv/4.x**
---
> opencv/4.x: bump deps

- recipes/wavelet_buffer/all/conanfile.py
Specify library name and version:  **wavelet_buffer/all**
---
> wavelet_buffer/all: bump deps

- recipes/tinydir/all/conanfile.py
- recipes/tinydir/all/test_package/CMakeLists.txt
- recipes/tinydir/all/test_package/conanfile.py
- recipes/tinydir/all/test_v1_package/CMakeLists.txt
- recipes/tinydir/all/test_v1_package/conanfile.py
- recipes/tinydir/all/test_v1_package/test_package.c
> tinydir: migrate to Conan v2

- recipes/indirect_value/all/conanfile.py
- recipes/indirect_value/all/test_package/CMakeLists.txt
- recipes/indirect_value/all/test_package/conanfile.py
- recipes/indirect_value/all/test_v1_package/CMakeLists.txt
- recipes/indirect_value/all/test_v1_package/conanfile.py
> indirect_value: migrate to Conan v2

- recipes/tllist/all/conanfile.py
- recipes/tllist/all/test_package/CMakeLists.txt
- recipes/tllist/all/test_package/conanfile.py
- recipes/tllist/all/test_v1_package/CMakeLists.txt
- recipes/tllist/all/test_v1_package/conanfile.py
- recipes/tllist/all/test_v1_package/test_package.c
> tllist: migrate to Conan v2

- recipes/inversify-cpp/all/conanfile.py
- recipes/inversify-cpp/all/test_package/CMakeLists.txt
- recipes/inversify-cpp/all/test_package/conanfile.py
- recipes/inversify-cpp/all/test_package/test_package.cpp
- recipes/inversify-cpp/all/test_v1_package/CMakeLists.txt
- recipes/inversify-cpp/all/test_v1_package/conanfile.py
> inversify-cpp: migrate to Conan v2

- recipes/source_location/all/conanfile.py
- recipes/source_location/all/test_package/CMakeLists.txt
- recipes/source_location/all/test_package/conanfile.py
- recipes/source_location/all/test_v1_package/CMakeLists.txt
- recipes/source_location/all/test_v1_package/conanfile.py
- recipes/source_location/all/test_v1_package/src/test.cpp
> source_location: migrate to Conan v2

- recipes/proj/all/conanfile.py
> proj: bump deps

- recipes/highway/all/conandata.yml
- recipes/highway/all/conanfile.py
- recipes/highway/config.yml
Specify library name and version:  **highway/***
---
> highway: add version 1.0.4, add package_type

- recipes/capstone/all/conandata.yml
- recipes/capstone/all/conanfile.py
- recipes/capstone/all/patches/5.0-0001-disable-warning-flags.patch
- recipes/capstone/config.yml
Specify library name and version:  **capstone/***
---
> capstone: add version 5.0, add package_type

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/all/conanfile.py
- recipes/mongo-c-driver/all/patches/1.24.1-0001-disable-shared-when-static.patch
- recipes/mongo-c-driver/all/patches/1.24.1-0002-fix-uninitialized-warning.patch
- recipes/mongo-c-driver/config.yml
Specify library name and version:  **mongo-c-driver/***
---
> mongo-c-driver: add version 1.24.1, update icu, remove older versions

- recipes/proj/all/conanfile.py
Specify library name and version:  **proj/all**
---
> proj/all: bump deps

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
> glaze: add version 1.3.1, remove older versions

- recipes/proj/all/conandata.yml
- recipes/proj/all/patches/0001-use-cmake-targets-9.2.1.patch
- recipes/proj/config.yml
Specify library name and version:  **proj/9.2.1**
---
> [proj] add version 9.2.1

- recipes/b2/config.yml
- recipes/b2/portable/conandata.yml
Specify library name and version:  **b2/4.10.1**
---
> b2: add version 4.10.1

- recipes/gmp/all/conandata.yml
> [GMP] change the data source

- recipes/libspatialite/all/conanfile.py
Specify library name and version:  **libspatialite/all**
---
> libspatialite/all: bump deps

- recipes/jxrlib/all/conanfile.py
Specify library name and version:  **jxrlib/all**
This should also generate some missing packages required by #18432 
---
> jxrlib/all: add package_type

- recipes/librasterlite/all/conanfile.py
Specify library name and version:  **librasterlite/all**
---
> librasterlite/all: bump deps

- recipes/enhex-generic_serialization/all/conanfile.py
- recipes/enhex-generic_serialization/all/test_package/CMakeLists.txt
- recipes/enhex-generic_serialization/all/test_package/conanfile.py
- recipes/enhex-generic_serialization/all/test_v1_package/CMakeLists.txt
- recipes/enhex-generic_serialization/all/test_v1_package/conanfile.py
> enhex-generic_serialization: migrate to Conan v2

- recipes/gstreamer/all/conanfile.py
Specify library name and version:  **gstreamer/all**
---
> gstreamer/all: bump deps

- recipes/openscenegraph/all/conanfile.py
Specify library name and version:  **openscenegraph/all**
---
> openscenegraph/all: bump deps

- recipes/coin-utils/all/conandata.yml
- recipes/coin-utils/all/patches/0003-cpp17-compat.patch
- recipes/coin-utils/config.yml
Specify library name and version:  **coin-utils/2.11.9**
- [X I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
> Bump coin-utils to 2.11.9

- recipes/tl-optional/all/conandata.yml
- recipes/tl-optional/config.yml
Specify library name and version:  **tl-optional/1.1.0**
---
> tl-optional: add version 1.1.0

- recipes/cimg/all/conanfile.py
Specify library name and version:  **cimg/all**
---
> cimg/all: bump deps

- recipes/redis-plus-plus/all/conandata.yml
- recipes/redis-plus-plus/all/conanfile.py
- recipes/redis-plus-plus/config.yml
Specify library name and version:  **redis-plus-plus/***
---
> redis-plus-plus: add version 1.3.10, update libuv

- recipes/hiredis/all/conandata.yml
- recipes/hiredis/all/conanfile.py
- recipes/hiredis/config.yml
Specify library name and version:  **hiredis/1.2.0**
---
> hiredis: add version 1.2.0

- recipes/openimageio/all/conanfile.py
Specify library name and version:  **openimageio/all**
---
> openimageio/all: bump deps

- recipes/sjson-cpp/all/conanfile.py
- recipes/sjson-cpp/all/test_package/CMakeLists.txt
- recipes/sjson-cpp/all/test_package/conanfile.py
- recipes/sjson-cpp/all/test_v1_package/CMakeLists.txt
- recipes/sjson-cpp/all/test_v1_package/conanfile.py
> sjson-cpp: migrate to Conan v2

- recipes/rtm/all/conanfile.py
- recipes/rtm/all/test_package/CMakeLists.txt
- recipes/rtm/all/test_package/conanfile.py
- recipes/rtm/all/test_package/test_package.cpp
- recipes/rtm/all/test_v1_package/CMakeLists.txt
- recipes/rtm/all/test_v1_package/conanfile.py
> rtm: migrate to Conan v2

- recipes/range-v3/all/conanfile.py
Specify library name and version:  **range-v3**
close https://github.com/conan-io/conan-center-index/issues/17152
---
> range-v3: set cpp_info.libdirs and cpp_info.bindirs to empty, add package_type

- recipes/etl/all/conandata.yml
- recipes/etl/config.yml
Specify library name and version:  **etl/20.37.1**
---
> etl: add version 20.37.1

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.3.2**
---
> glaze: add version 1.3.2

- recipes/catch2/3.x.x/conandata.yml
- recipes/catch2/config.yml
Specify library name and version:  **catch2/3.4.0**
Try to close https://github.com/conan-io/conan-center-index/issues/18534.
---
> catch2: add version 3.4.0

- .c3i/config_v1.yml
- .c3i/config_v2.yml
In relation to / close https://github.com/conan-io/conan-center-index/pull/18527
> [config] Add pcl reference to the extra-large pod size list

- recipes/ua-nodeset/all/conanfile.py
- recipes/ua-nodeset/all/test_package/conanfile.py
- recipes/ua-nodeset/all/test_v1_package/conanfile.py
Specify library name and version:  **ua-nodeset/***
---
> ua-nodeset: migrate to Conan v2

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/config.yml
> daw_json_link: add version 3.19.0, remove older versions

- recipes/effolkronium-random/all/conandata.yml
- recipes/effolkronium-random/config.yml
Specify library name and version:  **effolkronium-random/1.5.0**
---
> effolkronium-random: add version 1.5.0

- recipes/libidn/all/conanfile.py
Specify library name and version:  **libidn/***
fixes conan-io/conan-center-index#18518
---
> Libidn: bump deps

- recipes/hdf4/all/conanfile.py
Specify library name and version:  **hdf4/***
closes conan-io/conan-center-index#18502
---
> Hdf4: bump deps

- recipes/librasterlite2/all/conanfile.py
Specify library name and version:  **librasterlite2/***
closes conan-io/conan-center-index#18456
---
> Librasterlite2: bump deps

- recipes/dlib/all/conanfile.py
Specify library name and version:  **dlib/***
fixes conan-io/conan-center-index#18457
---
> dlib: bump deps

- recipes/pdfium/all/conanfile.py
Specify library name and version:  **pdfium/***
fixes conan-io/conan-center-index#18430
---
> pdfium: bump deps

- recipes/cpp-peglib/1.x.x/conandata.yml
- recipes/cpp-peglib/1.x.x/conanfile.py
- recipes/cpp-peglib/1.x.x/test_package/CMakeLists.txt
- recipes/cpp-peglib/config.yml
Specify library name and version:  **cpp-peglib/***
---
> cpp-peglib: add version 1.8.4, remove older versions

- recipes/dbg-macro/all/conanfile.py
- recipes/dbg-macro/all/test_package/CMakeLists.txt
- recipes/dbg-macro/all/test_package/conanfile.py
Specify library name and version:  **dbg-macro/0.4.0**
bumps recipe to conan 2.x format
---
- [*] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [*] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [*] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> dbg-macro fixes for conan2

- recipes/dbus/1.x.x/conanfile.py
Specify library name and version:  **dbus/***
---
> dbus/1.x.x: bump deps

- recipes/openexr/3.x/conandata.yml
- recipes/openexr/3.x/conanfile.py
- recipes/openexr/config.yml
Specify library name and version:  **openexr/3.1.9**
---
> Add OpenEXR to 3.1.9

- recipes/qt/5.x.x/conanfile.py
> qt/5.x.x: bump deps

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Testing to see if it works for me
---
> ada: add version 2.5.1

- recipes/opencv/4.x/conanfile.py
Specify library name and version:  **opencv/4.x**
---
> Bump opencv requirements

- recipes/platform.delegates/all/conandata.yml
- recipes/platform.delegates/all/conanfile.py
- recipes/platform.delegates/all/test_package/CMakeLists.txt
- recipes/platform.delegates/all/test_package/conanfile.py
- recipes/platform.delegates/config.yml
Specify library name and version:  **platform.delegates/***
---
> platform.delegates: add version 0.3.7, support conan v2

- docs/changelog.md
> [changelog] C3I Jenkins Release - 19 July 2013

- recipes/highway/all/conandata.yml
- recipes/highway/config.yml
Specify library name and version:  **highway/1.0.5**
---
> highway: add version 1.0.5

- recipes/dav1d/all/conandata.yml
- recipes/dav1d/config.yml
> Add dav1d/1.2.1

- recipes/libaom-av1/all/conandata.yml
- recipes/libaom-av1/config.yml
> Add libaom-av1 release 3.6.1

- recipes/opentelemetry-proto/all/conanfile.py
- recipes/opentelemetry-proto/all/test_package/conanfile.py
- recipes/opentelemetry-proto/all/test_v1_package/conanfile.py
Specify library name and version:  **opentelemetry-proto/***
---
> opentelemetry-proto: add package_type, clean up

- recipes/re2/all/conandata.yml
- recipes/re2/all/conanfile.py
- recipes/re2/config.yml
Specify library name and version:  **re2/***
---
> re2: add version 20230701, update icu, remove older versions

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  **cmake/3.27.0**
---
> Added cmake 3.27

- recipes/aeron/all/conandata.yml
- recipes/aeron/config.yml
Specify library name and version:  **aeron/1.41.4**
---
> aeron: add version 1.41.4

- recipes/tiny-dnn/all/CMakeLists.txt
- recipes/tiny-dnn/all/conanfile.py
- recipes/tiny-dnn/all/test_package/CMakeLists.txt
- recipes/tiny-dnn/all/test_package/conanfile.py
- recipes/tiny-dnn/all/test_v1_package/CMakeLists.txt
- recipes/tiny-dnn/all/test_v1_package/conanfile.py
> tiny-dnn: migrate to Conan v2

- recipes/libmnl/all/conanfile.py
- recipes/libmnl/all/test_package/CMakeLists.txt
- recipes/libmnl/all/test_package/conanfile.py
Specify library name and version:  **libmnl**
---
> [libmnl] migrate to v2

- recipes/platform.hashing/all/conandata.yml
- recipes/platform.hashing/all/conanfile.py
- recipes/platform.hashing/config.yml
Specify library name and version:  **platform.hashing/0.5.6**
---
> platform.hashing: add version 0.5.6

- recipes/cairo/all/conanfile.py
Specify library name and version:  **cairo/all**
---
> cairo/all: bump deps

- recipes/st_tree/all/conanfile.py
- recipes/st_tree/all/test_package/CMakeLists.txt
- recipes/st_tree/all/test_package/conanfile.py
Specify library name and version:  **st_tree/***
---
> st_tree: support conan v2

- docs/adding_packages/conanfile_attributes.md
- docs/faqs.md
This follow @jcar87 comment https://github.com/conan-io/conan-center-index/pull/18481#discussion_r1260070682 wtih extra formatting
The main issue is there was contridicting sections and advice
https://github.com/conan-io/conan-center-index/pull/18481 was merged before it was finished
---
> docs: Improve license attribute guidelines

- recipes/seqan/2.x.x/conanfile.py
- recipes/seqan/2.x.x/test_package/CMakeLists.txt
- recipes/seqan/2.x.x/test_package/conanfile.py
- recipes/seqan/2.x.x/test_package/test_package.cpp
- recipes/seqan/2.x.x/test_v1_package/CMakeLists.txt
- recipes/seqan/2.x.x/test_v1_package/conanfile.py
> seqan: migrate to Conan v2

- recipes/mcap/all/conandata.yml
- recipes/mcap/all/test_package/conanfile.py
- recipes/mcap/config.yml
Specify library name and version:  **mcap/1.1.0** & **mcap/1.2.0**
---
> mcap: add version 1.1.0 and 1.2.0

- recipes/xxhash/all/conandata.yml
- recipes/xxhash/all/conanfile.py
- recipes/xxhash/config.yml
Specify library name and version:  **xxhash/0.8.2**
---
> xxhash: add version 0.8.2, add package_type

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/***
---
> unordered_dense: add version 4.0.4, remove older versions

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.13.3**
---
> cpp-httplib: add version 0.13.3

- recipes/bx/all/test_package/conanfile.py
Specify library name and version:  **bx/cci.20221116**
Required by #16134
---
> [bx] Fix test package imports

- recipes/asio/all/conandata.yml
- recipes/asio/config.yml
Specify library name and version:  **asio/1.28.1**
---
> asio: add version 1.28.1

- .c3i/config_v1.yml
- .c3i/config_v2.yml
> [config] Update Conan client version: 1.60.2 and 2.0.9

- recipes/asio-grpc/all/conandata.yml
- recipes/asio-grpc/all/conanfile.py
- recipes/asio-grpc/config.yml
Specify library name and version:  **asio-grpc/***
---
> asio-grpc: add version 2.5.1, update dependencies

- recipes/emsdk/all/conandata.yml
- recipes/emsdk/config.yml
Specify library name and version:  **emsdk/3.1.44**
Adds the latest emsdk version to conan center.
---
> emsdk: add version 3.1.44

- recipes/msgpack-c/all/conandata.yml
- recipes/msgpack-c/config.yml
msgpack-c/3.3.0
Added latest package for major version 3
no recipe changes!
---
> msgpack-c/3.3.0: Added version 3.3.0

- recipes/luajit/all/conanfile.py
> luajit: specify `provides` attribute

- recipes/libunwind/all/conandata.yml
- recipes/libunwind/config.yml
Specify library name and version:  **libunwind/1.7.2**
---
> libunwind: add version 1.7.2

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.2.2**
---
> simdjson: add version 3.2.2

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Specify library name and version:  **glib/2.77.1**
---
> glib: add version 2.77.1

- recipes/cgal/all/conandata.yml
- recipes/cgal/config.yml
Specify library name and version:  **cgal/5.5.3**
Add the latest upstream bug-fix release
---
> [cgal] add cgal/5.5.3

- recipes/qt/6.x.x/conanfile.py
Specify library name and version:  **qt/6.x**
fixes https://github.com/conan-io/conan-center-index/issues/18775
---
> qt6: add new components

- recipes/zpp_bits/all/conandata.yml
- recipes/zpp_bits/config.yml
Specify library name and version:  **zpp_bits/4.4.18**
---
> zpp_bits: add version 4.4.18

- recipes/libuvc/all/conanfile.py
Specify library name and version:  **libuvc/***
---
> libuvc: update libjpeg-turbo/3.0.0

- recipes/libtiff/all/conanfile.py
Specify library name and version:  **libtiff/***
---
> libtiff: update libjpeg-turbo

- recipes/wt/all/conandata.yml
- recipes/wt/config.yml
Specify library name and version:  **wt/4.10.0**
---
> wt: add version 4.10.0

- recipes/jasper/all/conanfile.py
Specify library name and version:  **jasper/***
---
> jasper: update libjpeg-turbo

- recipes/function2/all/conandata.yml
- recipes/function2/config.yml
Specify library name and version:  **function2/4.2.3**
---
> function2: add version 4.2.3

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/config.yml
Specify library name and version:  **mongo-c-driver/1.24.3**
---
> mongo-c-driver: add version 1.24.3
