- recipes/libcurl/all/conandata.yml
- recipes/libcurl/config.yml
Specify library name and version:  **libcurl/8.0.1**
A minor upgrade fixing a crash in CURL's destructor.
---
> libcurl: update to 8.0.1

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/config.yml
Specify library name and version:  **libxml2/2.10.4**
Fix for CVEs:
* [CVE-2023-29469](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-29469)
* [CVE-2023-28484](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28484)
see also https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.4
---
> libxml2: add 2.10.4

- docs/changelog.md
- New CI job which should run two time every day and update the `.c3i/conan_v2_ready_references.yml` automatically
- Improved Automatic merge to execute less steps, resulting a faster execution
---
> [changelog] New CCI release

- recipes/qt/5.x.x/conandata.yml
- recipes/qt/5.x.x/conanfile.py
- recipes/qt/5.x.x/patches/android-backtrace.diff
- recipes/qt/5.x.x/patches/android-new-ndk.diff
- recipes/qt/5.x.x/patches/android-openssl.diff
Specify library name and version:  **qt/5.15.x**
- `CROSS_COMPILE` option isn't required for Android according to https://doc.qt.io/qt-5/android-building.html
- With NDK 24 it's not buildable because of backtrace functions which are available only since API level 33 according to `execinfo.h`.
- fixes #15536 - linking to OpenSSL libs built by Conan
- iOS fix from #15471
- adds option to pass path to Android SDK which is required to build Qt
- fixes #15552 - backported patch for NDK >= 23
---
> qt5: fix some Android and iOS errors

- recipes/imath/all/conanfile.py
Specify library name and version:  **imath/3.1.7**
The code relies on `__cplusplus` macro to provide implementation of some functionality unavailable before C++20. As msvc doesn't define that macro by default it results in compilation error. See [/Zc:__cplusplus](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170).
Error details:
```bash
error C2668: 'bit_cast': ambiguous call to overloaded function [E:\conan\packages\t\imatha94c88 
21de43e\b\build\src\ImathTest\ImathTest.vcxproj]
E:\conan\packages\t\imatha94c8821de43e\b\src\src\ImathTest\testFun.cpp(26,5): message : could be 'To bit_cast<uint64_t,double>(From)' [E:\conan\packages\t\imatha94c8821de43e\b 
\build\src\ImathTest\ImathTest.vcxproj]
with
[
To=uint64_t,
From=double
]
D:\dev\Microsoft Visual …
```
> imath: fix for msvc c++20 build

- recipes/tinycthread/all/CMakeLists.txt
- recipes/tinycthread/all/conanfile.py
- recipes/tinycthread/all/test_package/CMakeLists.txt
- recipes/tinycthread/all/test_package/conanfile.py
- recipes/tinycthread/all/test_v1_package/CMakeLists.txt
- recipes/tinycthread/all/test_v1_package/conanfile.py
This is a v2 requirement for #14703 
---
> tinycthread: support conan v2

- recipes/libde265/all/conandata.yml
- recipes/libde265/all/conanfile.py
- recipes/libde265/config.yml
Upstream has changed CMake imported target (inadvertently, I guess, in https://github.com/strukturag/libde265/commit/29698db09134bef7be5b0bb6b270cdd28ee66f1e) from `libde265` to `de265`.
To avoid breaking users, both targets are provided in CMakeDeps and cmake_find_package(_multi).
---
> libde265: add 1.0.11 & package_type

- recipes/fakeit/all/conanfile.py
Specify library name and version:  **fakeit/all**
The fakeit package package only one header, but the header is selected based on the "integration" option, therefor this option must be part of the package id. This PR solves that and fixes #14900.
---
> Fix fakeit/all: Fixed package_id() to make it dependent on option:integration.

- recipes/emsdk/all/conanfile.py
Specify library name and version:  **emsdk/***
`node` from the `nodejs` package is not found. The error was hidden because most systems have `node` installed so it was used instead:
```
embuilder:INFO: building struct_info
cache:INFO: generating system asset: sysroot/lib/wasm32-emscripten/struct_info.json... (this will be cached in "/tmp/conan_home/.conan2/p/t/emsdk656b996f7a7a2/p/bin/.emscripten_cache/sysroot/lib/wasm32-emscripten/struct_info.json" for subsequent builds)
emcc: warning: cannot check node version: [Errno 2] No such file or directory: 'node' [-Wversion-check]
emcc: error: The configured node executable (['node']) does not seem to work, check the paths in /tmp/conan_home/.conan2/p/t/emsdk656b996f7a7a2/p/bin/.emscripten ([Errno 2] No such file or directory: 'node')
FAIL: …
```
> fix(emsdk): add conanrun env to package method

- recipes/mpdecimal/2.5.x/conandata.yml
- recipes/mpdecimal/2.5.x/conanfile.py
- recipes/mpdecimal/2.5.x/test_package/CMakeLists.txt
- recipes/mpdecimal/2.5.x/test_package/conanfile.py
- recipes/mpdecimal/2.5.x/test_v1_package/CMakeLists.txt
- recipes/mpdecimal/2.5.x/test_v1_package/conanfile.py
Specify library name and version:  **mpdecimal/2.5.x**
The recipe required system autconf for a single invocation of autoreconf. I could reason out that so I removed that line, and the recipe seems to work without any problems. It could be remnants of past but on the other hand it could be for a specific corner case which I am not aware of.
---
> mpdecimal: support conan v2

- recipes/proposal/all/CMakeLists.txt
- recipes/proposal/all/conanfile.py
- recipes/proposal/all/test_package/CMakeLists.txt
- remove useless CMakeLists wrapper (not required anymore after migration to CMakeToolchain)
- add cmake_layout
- handle msvc in check of min compiler version
---
> proposal: remove unused CMakeLists wrapper + add layout + bump dependencies

- recipes/tinycthreadpool/all/conandata.yml
- recipes/tinycthreadpool/all/conanfile.py
- recipes/tinycthreadpool/all/test_package/CMakeLists.txt
- recipes/tinycthreadpool/all/test_package/conanfile.py
- recipes/tinycthreadpool/all/test_package/example.c
- recipes/tinycthreadpool/all/test_v1_package/CMakeLists.txt
- recipes/tinycthreadpool/all/test_v1_package/conanfile.py
- recipes/tinycthreadpool/config.yml
Specify library name and version:  **tinycthreadpool/1.0**
This is a portable C threadpool. It is based on [tinycthread](https://github.com/tinycthread/tinycthread) and supports both Windows and POSIX systems.
---
> add tinycthreadpool

- recipes/libusb/all/conanfile.py
Noticed its required for https://github.com/conan-io/conan-center-index/pull/17041#issuecomment-1510431964
---
> libusb: add package_type (generate v2 packages)

- recipes/ogdf/all/conandata.yml
- recipes/ogdf/all/conanfile.py
- recipes/ogdf/all/test_package/CMakeLists.txt
- recipes/ogdf/all/test_package/conanfile.py
- recipes/ogdf/all/test_package/main.cpp
- recipes/ogdf/all/test_v1_package/CMakeLists.txt
- recipes/ogdf/all/test_v1_package/conanfile.py
- recipes/ogdf/config.yml
Specify library name and version:  **ogdf/2022.02**
I am one of the OGDF developers.
Remark: The recipe deletes lots of content from the sources as they contain many libs via copy&paste. Everything that is provided by conan was dropped and replaced by conan dependencies. Other libs remain in the sources, for example coin-abacus and minisat, for which no conan packages exist. Here is the complete list:
Dropped:
* pugixml: was contained in `(src|include)/ogdf/lib/pugixml`, replaced by the dependency on pugixml/1.13 from conan center
* coin-clp: was contained in `(src|include)/coin`, replaced by the dependency on coin-clp/1.17.7 from conan-center
* backward-cpp: was contained in `include/ogdf/lib/backward`, dropped as only required for a special parameter settings not supported in the recipe …
> Add library OGDF with graph algorithms and data structures

- recipes/kmod/all/conanfile.py
Since kmod is always a shared lib, fPIC option is removed.
---
> kmod: add package_type + bump dependencies

- .c3i/config_v2.yml
When a package which is listed in https://github.com/conan-io/conan-center-index/blob/master/.c3i/conan_v2_ready_references.yml fails to build on a new PR, it will be considered a regression error, which means, for that specific package, Conan v2 will be mandatory.
However, the current information on the PR, informs that Conan v2 is only informative and is not mandatory, creating a misinformation.
We are preparing a new feature which will update the message according the situation, so users will not be confused by the build result message.
---
> [config] Add regression message for Conan v2 builds

- recipes/xorg/all/conanfile.py
it is needed for qt 6.5.0
https://github.com/qt/qtbase/commit/012132c60d
---
> xorg: add xcb-cursor

- recipes/uni-algo/all/conanfile.py
- fix logic in `validate()`:
- it was broken for legacy compiler=Visual Studio because it was testing version of this flavor against version of compiler=msvc flavor...
- check compiler.cppstd if set
- consistent min versions between legacy Visual Studio & new msvc
- remove dead code (export_conandata_patches useless here)
- no need to call CMakeToolchain in case of header-only
- simplify definition of cmake_file_name & cmake_target_name. Relying on self.name to explicitly define these properties is not only unnecessarily confusing, but also not future proof in case of recipe renaming. Rule of thumb: never rely on `self.name` to set libs intrinsic values. It's fine for stuff like ConanInvalidConfiguration or creating a custom file because they are related to recipe, not lib underlying …
> uni-algo: fix broken logic in validate() + cleanup dead code

- recipes/restinio/all/conanfile.py
Specify library name and version:  **restinio/[>0.6.17]**
Since version `0.6.17` restinio requires at least `fmt/9.1.0`, which has not been updated in the conanfile.
This deficiency is fixed with this PR.
---
> restinio: update dependencies

- recipes/ldns/all/conanfile.py
This removes mistakenly committed `print` statement in the ldns recipe.
---
> ldns: remove debug print statement

- .c3i/config_v1.yml
- .c3i/config_v2.yml
We are using the configuration ID to store the log paths of each build. Having `config/` creates unneded folders in Artifactory.
This avoids creating unneeded nested folders when storing the logs in the generic repo of artifactory
> [config] Fix build log paths

- recipes/libmysqlclient/all/conanfile.py
Specify library name and version:  **libmysqlclient/\***
On Linux `FORCE_UNSUPPORTED_COMPILER` is disabled by default and libmysqlclient is trying to guess what compiler to use depending on distribution. I use CentOS 7 with built from source gcc 10 and I get this error when building libmysqlclient:
```
-- Running cmake version 3.25.2
-- Found Git: /usr/bin/git (found version "2.36.5")
-- This is .el7. as found from 'rpm -qf /'
-- Looking for a devtoolset compiler
CMake Warning at CMakeLists.txt:392 (MESSAGE):
Could not find devtoolset compiler/linker in /opt/rh/devtoolset-11
CMake Warning at CMakeLists.txt:394 (MESSAGE):
You need to install the required packages:
yum install devtoolset-11-gcc devtoolset-11-gcc-c++ devtoolset-11-binutils
CMake Error at CMakeLists.txt:396 (MESSAGE):
Or you …
```
> libmysqlclient: stop it from dictating which compiler to use

- recipes/quill/all/conandata.yml
- recipes/quill/all/conanfile.py
- recipes/quill/all/test_package/test_package.cpp
- recipes/quill/config.yml
Specify library name and version:  **quill/2.8.0**
- add version 2.8.0
- some cmake options are moved into macro
- add with_bounded_blocking_queue macro
- return types of several APIs are changed. (with shared_ptr)
---
> quill: add version 2.8.0, add package_type

- docs/adding_packages/dependencies.md
- docs/faqs.md
As we continue the migration to Conan 2.0, we are going to start allowing version ranges in a limited way, starting with OpenSSL and CMake.
This should have a few advantages:
* No need to update downstream consumers when OpenSSL or CMake are updated. Note that this may still require new binaries being generated for those downstream consumers. 
* Once enough recipes are updated, there should be no version conflicts related to these
* For users that have a profile with settings for which there are no binaries provided by Conan Center, if `--build=missing` is passed, those recipes that have CMake as a tool-requires will now resolve to a single version, rather than multiple versions. This has been problematic in the past if multiple versions of CMake have to be built from source.
> Docs: update policy on version ranges

- recipes/mariadb-connector-c/all/conanfile.py
> mariadb-connector-c: use version range for openssl

- recipes/screen_capture_lite/all/conandata.yml
- recipes/screen_capture_lite/all/conanfile.py
- recipes/screen_capture_lite/config.yml
Specify library name and version:  **screen_capture_lite/***
- add version 17.1.1173
- use `rm_safe` in `configure()`
- fix `validate()` not to use check_min_vs
- remove `destination` argument from `get`
---
> screen_capture_lite: add version 17.1.1173, add package_type

- recipes/capnproto/all/conanfile.py
> capnproto: use version range for openssl

- recipes/mongo-c-driver/all/conanfile.py
> mongo-c-driver: use version range for openssl

- recipes/caf/all/conanfile.py
> caf: use version range for openssl

- recipes/g3log/all/conandata.yml
- recipes/g3log/config.yml
Specify library name and version:  **g3log/2.3**
---
> g3log: add version 2.3

- recipes/ffmpeg/all/conanfile.py
`update_configure_args` from the `AutotoolsToolchain` strips out duplicate configuration flags, even if they have different values. e.g. `--enable-encoder=gif --enable-encoder=mp3`
This commit simply appends those flags after the offending method call to avoid them being stripped.
Specify library name and version:  **ffmpeg/***
fixes #17140
---
> ffmpeg: Fix list options with Conan 2.0.

- recipes/grpc/all/conanfile.py
Specify library name and version:  **openssl/all**
(DRAFT)
* grpc recipe: bump version of OpenSSL to use version range that covers OpenSSL 1.1.x and OpenSSL 3.x. This should resolve to the highest available unless overridden elsewhere. This should fix conflict issues in Conan 2.x, make it easier to continue maintaining Conan 1.x without version bumps, and users can control the exact version with lockfiles (encouraged) or overrides (discouraged)
---
> grpc: use newer openssl

- recipes/cppbenchmark/all/conanfile.py
- bump hdrhistogram-c
- remove _cmake_new_enough()
- fix msvc min version
---
> cppbenchmark: add package_type + use version range for cmake

- recipes/quazip/all/conanfile.py
- use self.dependencies
- bump qt
- remove useless VirtualBuildEnv
- add bzip2 to requirements since 1.4 (https://github.com/stachenov/quazip/commit/6709e83fb31bca3d4168f905213b5f92feea32e4). I guess this issue was hidden in c3i because it was able to find system installed bzip2, but basically it fails for me on WSL2 since bzip2 is not installed.
---
> quazip: fix recipe for conan v2

- recipes/libpcap/all/conanfile.py
`flex` raises if os is Windows, therefore we must use `winflexbison` in build requirements of `libpcap` recipe if build machine is Windows.
closes https://github.com/conan-io/conan/issues/13754
---
> libpcap: use winflexbison if build machine is Windows

- recipes/s2n/all/conanfile.py
Remove component workaround to avoid to define a `AWS::AWS` target in legacy generators. Rely on custom cmake module instead.
---
> s2n: remove component workaround for legacy generators

- recipes/aws-c-common/all/conanfile.py
see https://github.com/awslabs/aws-c-common/blob/v0.8.17/include/aws/common/exports.h
---
> aws-c-common: add AWS_COMMON_USE_IMPORT_EXPORT interface definition if shared

- recipes/mailio/all/conanfile.py
- recipes/mailio/all/test_package/conanfile.py
- bump openssl
- bump cmake
- call VirtualBuildEnv since there is a build requirement
- don't use self.output.warn, it's not compatible with conan v2
- cleanup unused imports
---
> mailio: add package_type + bump openssl & cmake + few improvements

- recipes/cppserver/all/conanfile.py
> cppserver: use version range for openssl & bump asio

- recipes/zlib/all/conandata.yml
> zlib: add mirror url for tarball of 1.2.13

- recipes/h3/all/conanfile.py
uses https://github.com/conan-io/conan-center-index/pull/17192 instead
---
> h3: drop cmake_new_enough

- recipes/duckdb/all/conanfile.py
> duckdb: use version range for openssl

- recipes/opusfile/all/conanfile.py
> opusfile: add package_type + bump openssl

- recipes/libtiff/all/conanfile.py
There are conflicts in several downstream recipes currently, like opencv
---
> libtiff: bump dependencies

- recipes/qarchive/all/conanfile.py
- recipes/qarchive/all/test_package/conanfile.py
- recipes/qarchive/all/test_v1_package/CMakeLists.txt
- use conan.tools.files.copy instead of self.copy
- protect double deletion of fPIC
- fix import of cmake_layout in test package
---
> qarchive: fix recipe for conan v2 + use version range for cmake

- recipes/libffi/all/conandata.yml
- recipes/libffi/all/patches/0007-3.4.3-forward-declare-open_temp_exec_file.patch
This patch allows building with newer versions of Clang out-of-the-box. Clang 15.0.0 removed support for implicit function declarations. This is mentioned here: https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#c2x-feature-support. This removal breaks builds using the default C standard in Clang. This is because the function open_temp_exec_file is not properly declared.
This patch is from the upstream project and declares the function.
---
> libffi/3.4.3: Add patch to allow building with the C2x standard

- recipes/aws-checksums/all/conanfile.py
- recipes/aws-checksums/all/test_v1_package/CMakeLists.txt
see https://github.com/awslabs/aws-checksums/blob/v0.1.14/include/aws/checksums/exports.h
---
> aws-checksums: add missing interface definition if shared + modernize more for conan v2

- recipes/coin-clp/all/conanfile.py
Specify library name and version:  **coin-clp/***
This fixes linking problems with coin-clp: https://github.com/conan-io/conan-center-index/pull/16053#issuecomment-1512637106
---
> coin-clp: make dependency on coin-utils libs transitive

- recipes/xmlsec/all/conandata.yml
- recipes/xmlsec/all/conanfile.py
- recipes/xmlsec/all/test_package/CMakeLists.txt
- recipes/xmlsec/all/test_package/conanfile.py
- recipes/xmlsec/all/test_v1_package/conanfile.py
- tarballs of versions < 1.2.33 have been removed from https://www.aleksey.com/xmlsec/download/ and only live under https://www.aleksey.com/xmlsec/download/older-releases/
- bump some dependencies, and specially openssl from 1.1.x to 3.x.x
---
> xmlsec: fix url of tarballs + bump dependencies

- recipes/tesseract/all/conanfile.py
- recipes/tesseract/all/test_package/test_package.cpp
This recipe is not fully v2 compatible due to usage of legacy `self.deps_cpp_info`.
---
> tesseract: bump dependencies + modernize more for conan v2

- recipes/libnice/all/conandata.yml
- recipes/libnice/all/conanfile.py
- recipes/libnice/all/test_package/CMakeLists.txt
- recipes/libnice/all/test_package/conanfile.py
- recipes/libnice/all/test_package/meson.build
- recipes/libnice/all/test_package/src/example.c
- recipes/libnice/all/test_v1_package/CMakeLists.txt
- recipes/libnice/all/test_v1_package/conanfile.py
- recipes/libnice/config.yml
Specify library name and version:  **libnice/0.1.19**
libnice is is a library that implements the Interactive Connectivity Establishment (ICE) standard ([RFC 5245](https://tools.ietf.org/html/rfc5245) & [RFC 8445](https://tools.ietf.org/html/rfc8445)). It provides a GLib-based library, libnice, as well as [GStreamer](http://gstreamer.freedesktop.org/) elements to use it.
---
> libnice: add recipe

- recipes/restbed/all/conanfile.py
- recipes/restbed/all/test_v1_package/CMakeLists.txt
- remove ipc option in config_options() instead of configure()
- sort methods by order of execution
- use version range for openssl
- bump asio
---
> restbed: use version range openssl + modernize more for conan v2

- recipes/grpc/all/conanfile.py
- recipes/grpc/all/test_package/conanfile.py
- remove full_package_mode for protobuf
- avoid to have protobuf in build requirements in case of native build.
- avoid to have grpc in build requirements of test package in case of native build, mainly to avoid missing packages in c3i (see errors in https://github.com/conan-io/conan-center-index/pull/17190#issuecomment-1520609055 where "all shared" flavor fails in test package because static flavor dragged by build requirement has not been built yet I guess).
- use tool_requires instead of build_requires
- don't rely on self.info in validate()
- bump c-ares & re2
---
> grpc: several improvements for conan v2

- recipes/libcap/all/conandata.yml
- recipes/libcap/config.yml
Specify library name and version:  **libcap/2.68**
A new libcap release. This version improves documentation mostly, but also contains a few API cleanups.
---
> libcap/2.68: Bump version

- recipes/libbigwig/all/conanfile.py
- recipes/libbigwig/all/test_package/CMakeLists.txt
- recipes/libbigwig/all/test_package/conanfile.py
- recipes/libbigwig/all/test_v1_package/CMakeLists.txt
- recipes/libbigwig/all/test_v1_package/conanfile.py
- recipes/libbigwig/all/test_v1_package/test_package.c
Specify library name and version:  **libbigwig/all**
- Modernize recipe
- Bump dependencies
- Change defaults to build with CURL to be consistent with upstream
---
> libbigwig: conan v2 support; bump deps

- recipes/soci/all/conanfile.py
soci searches for POSTGRESQL_LIBRARIES etc. instead of what conan defines (PostgreSQL_LIBRARIES).
fixes #11628
---
- [] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> soci: fix linking against dependencies with conanv1

- recipes/cppcheck/all/conanfile.py
> [cppcheck] Remove deprecated with_z3 option

- recipes/tensorflow-lite/all/conanfile.py
- recipes/tensorflow-lite/all/test_v1_package/CMakeLists.txt
- use version range for cmake (see https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/lite/CMakeLists.txt#L29)
- fix required_conan_version (it requires conan >= 1.53.0 due to options.rm_safe)
- add msvc to _compilers_minimum_version
- add VirtualBuildEnv since there is a build requirement
- sort methods by order of execution to make recipe easier to understand
- do not hardcode build_folder, just let cmake_layout does its job
---
> tensorflow-lite: use version range for cmake + add package_type

- recipes/libsystemd/all/conandata.yml
- recipes/libsystemd/all/conanfile.py
- recipes/libsystemd/all/patches/247.13/0001-Remove-dependency-from-coreutils.patch
- recipes/libsystemd/all/patches/248.12/0001-missing_syscalls.py-Replace-unicode-with-ascii.patch
- recipes/libsystemd/all/patches/249.16/0001-Remove-dependency-from-coreutils.patch
- recipes/libsystemd/all/patches/251.15/0001-Remove-dependency-from-coreutils.patch
- recipes/libsystemd/all/patches/253.3/0001-missing_syscalls.py-Replace-unicode-with-ascii.patch
- recipes/libsystemd/config.yml
Specify library name and version:  **libsystemd/253.3**
Changes summary:
* Versions in conandata and config files are sorted to fit contributing recommendations.
* All minor versions updated. The systemd versioning schema is something like `systemd_version.build_patch`, where `build_patch` contains fixes related to build files and security updates. So it should be fine to replace all minor versions.
* Bump dependencies
* Bump version (253.3)
---
> libsystemd/253.3: Bump versions and dependencies

- recipes/arduinojson/all/conanfile.py
- recipes/arduinojson/all/test_package/CMakeLists.txt
- recipes/arduinojson/all/test_package/conanfile.py
- recipes/arduinojson/all/test_v1_package/CMakeLists.txt
Fix cppstd logic again. While there was an issue, the new logic of https://github.com/conan-io/conan-center-index/pull/17250 is also broken.
---
> arduinojson: fix cppstd check logic

- recipes/onnxruntime/all/conandata.yml
- recipes/onnxruntime/all/conanfile.py
- recipes/onnxruntime/all/patches/1.14.1-0001-cmake-dependencies.patch
- recipes/onnxruntime/all/patches/1.14.1-0002-cmake-dependencies.patch
- recipes/onnxruntime/all/patches/1.14.1-0003-amx-gas-version.patch
- recipes/onnxruntime/all/patches/1.14.1-0004-abseil-no-string-view.patch
- recipes/onnxruntime/all/test_package/CMakeLists.txt
- recipes/onnxruntime/all/test_package/conanfile.py
- recipes/onnxruntime/all/test_package/test_package.cpp
- recipes/onnxruntime/all/test_v1_package/CMakeLists.txt
- recipes/onnxruntime/all/test_v1_package/conanfile.py
- recipes/onnxruntime/config.yml
Specify library name and version: onnxruntime/1.14.1
Fixes #4806
Fixes #16699
Closes #16842
This is similar to #16842 but I already had some work done before that PR was created and thought I'd share the state of said work.
Differences with #16842:
- nothing is downloaded, only conan packages are used. This comes with some caveats:
- ~~mac armv8 will fail because eigen 3.4.0 has a bug (onnxruntime pins a git commit before 3.4.0, the not released 3.4.1 has a fix for this), c.f. #16854~~
- ~~Windows will most likely fail (pending #16701 & update of the requirement/patch)~~
- unit tests can't be built without onnx sources (requires a proto definition from those sources, not patched)
- ~~no options are implemented yet.~~ only `with_xnnpack` option is implemented.
It's been built and tested on …
> onnxruntime: add 1.14.1

- recipes/arsenalgear/all/conandata.yml
- recipes/arsenalgear/all/conanfile.py
- recipes/arsenalgear/config.yml
Specify library name and version:  **arsenalgear/2.1.0**
- add version 2.1.0
- 2.1.0 provides official CMakeLists.txt
---
> arsenalgear: add version 2.1.0

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Specify library name and version:  **glib/2.76.2**
---
> glib: add version 2.76.2

- .c3i/config_v2.yml
Service configuration:
When building packages with Conan 2.0, it will build packages for the first compatible `cppstd` in the list, that is, the first one that does not throw a `ConanInvalidConfiguration`.
This should enable building packages in Conan Center with Conan 2.0 for recipes that require a higher value of `cppstd` .
> [config] Add values for cppstds for conan v2 pipeline

- recipes/cmake/3.x.x/conanfile.py
Specify library name and version:  **cmake/3.26.3**
---
> CMake [build from source] Added missing definition needed when bootstrapping with OpenSSL

- recipes/libffi/all/conandata.yml
This patch is also necessary for version 3.4.4.
This patch shouldn't need to be carried forward any further after this release since it was upstreamed after the release of 3.4.4.
---
> libffi/3.4.4: Pull forward the forward declaration patch

- recipes/libmysqlclient/all/conanfile.py
Specify library name and version:  **libmysqlclient**
* Move `check_min_cppstd` logic to `validate_build()` rather than `validate()`
* Move checks for cross-building to `validate_build()` as well 
Conan 2.0 profiles now define the `compiler.cppstd` setting by default, and will propagate that when building binaries from source. 
Some libraries, such as `libmysqlclient`'s most recent version, can only be built with C++17 or above. 
When a downstream consumer that depends on `libmysqlclient` is on `cppstd=14`, before this PR they would get that a package for `libmysqlclient` with `cppstd=14` is _not_ possible, and thus will get an error - and would otherwise force the consumer to be on C++17 as well. 
However, `libmysqclient` can be consumed with clients on other versions of the C++ …
> libmysqlclient: move check_min_cppstd to validate_build

- recipes/yajl/all/conandata.yml
- recipes/yajl/all/conanfile.py
- recipes/yajl/all/test_package/CMakeLists.txt
- recipes/yajl/all/test_package/conanfile.py
- recipes/yajl/all/test_package/test_package.c
- recipes/yajl/all/test_v1_package/CMakeLists.txt
- recipes/yajl/all/test_v1_package/conanfile.py
- recipes/yajl/config.yml
Specify library name and version:  **yajl/2.1.0**
This PR aims at adding the [YAJL library](https://github.com/lloyd/yajl) to the Conan Center.
Overall, it was a very straightforward process and I essentially was able to follow the template project. 
The looks hooks all reported OK.
> yajl: initial onboarding (v2.1.0)

- recipes/boost/all/conanfile.py
This allows cross-compiling the Boost recipe.
Related to issue #16051.
---
> boost: Use the sysroot conf variable

- recipes/onnx/all/conandata.yml
- recipes/onnx/config.yml
Specify library name and version:  **onnx/1.14.0**
---
> onnx: add version 1.14.0

- recipes/libuuid/all/conanfile.py
This fixes compilation when using Clang 16.
Due to the removal of support for implicit declarations, libuuid fails to build due to an issue where the `<sys/file.h>` header is not included. Specifically, the `flock` function requires `<sys/file.h>` to be included. Since the compiler preprocessor macro `HAVE_SYS_FILE_H` is not defined, that header is not included. This worked previously since the compiler assumed that is was an implicit function declaration. Defining the macro on the necessary platforms solves the issue.
Specify library name and version:  **libuuid/1.0.3**
---
> libuuid/1.0.3: Fix missing include for the sys/file.h header

- recipes/norm/all/conandata.yml
- recipes/norm/all/conanfile.py
- recipes/norm/all/patches/0003-cpp20-compat.patch
- bump libxml2
- fix compilation with C++20. There was an error with apple-clang 14 and C++20:
```
/Users/spaceim/.conan2/p/t/norm134268ea437dd/b/src/src/common/normNode.cpp:1624:19: error: use of overloaded operator '==' is ambiguous (with operand types 'int' and 'NormObjectId')
if (0 == sync_id)
~ ^  ~~~~~~~
```
---
> norm: add package_type + bump deps + small patch to fix compilation with apple-clang & C++20

- recipes/onetbb/all/conandata.yml
- recipes/onetbb/config.yml
Specify library name and version:  **onetbb/2021.9.0**
---
> onetbb: bump to 2021.9.0

- recipes/wg21-linear_algebra/all/conanfile.py
Specify library name and version:  **wg21-linear_algebra/0.7.3**
As a maintainer of this library, I am submitting this fix to address the final comment of this review, which was received post-merge: https://github.com/conan-io/conan-center-index/pull/16392
---
> Remove output.warn, no longer supported in Conan 2.0

- recipes/perfetto/all/conandata.yml
- recipes/perfetto/config.yml
Specify library name and version:  **perfetto/v34.0**
```
v34.0 - 2023-05-02:
* --continuous-dump in tools/java_heap_dump now keeps recording until it
receives CTRL+C.
UI:
* Add support for parsing large integers from Trace Processor into
bigint. This is the default behaviour for unknown fields and can
be enabled specifically via the LONG and LONG_NULL column types.
SDK:
* Changed the type of the static constexpr metadata on protozero
generated bindings from a function returning the metadata to
metadata itself. For a field 'foo' the variable kFoo previously
defined as:
`static constexpr FieldMetadata_Foo kFoo() = { return {}; };`
it is now defined as:
`static constexpr FieldMetadata_Foo kFoo;`
This is a breaking change for users who directly access field …
```
> (#17461) Perfetto: Bump v34.0

- recipes/foonathan-memory/all/conanfile.py
Specify library name and version:  **foonathan-memory/all**
I have tried to reproduce the error with cross compilation but all available versions of foonathan-memory are working while cross compiling to armv8. 
In Versions smaller then 0.7.2 there will be the output:
```
CMake Warning at src/CMakeLists.txt:108 (message):
cross-compiling, but emulator is not defined, cannot generate
container_node_sizes_impl.hpp, node size information will be unavailable
```
but it is working. Since 0.7.2, the method how to generate the node sizes seems to be changed and there was no warning at all.
> foonathan-memory remove crosscompile check

- recipes/ada/all/conandata.yml
- recipes/ada/all/conanfile.py
- recipes/ada/config.yml
Specify library name and version:  **ada/***
* Add `shared` option, as some versions support it
* Change package type to `library` (since it can now be shared or static)
* In the `configure()` method, conditionally remove the `shared` option for older versions, and set the `package_type` to `static_library` instead - note that there is a limitation in Conan Center CI, but this should be done in `config_options()` instead.
* Add version `2.3.1`
---
> ada: add version 2.3.1, enable shared build

- recipes/fontconfig/all/conanfile.py
Specify library name and version:  **fontconfig/***
created from https://ericlemanissier.github.io/conan-center-index-bump-deps/
---
> fontconfig/all/: bump deps

- recipes/aws-c-compression/all/conanfile.py
- recipes/aws-c-compression/all/test_v1_package/CMakeLists.txt
see https://github.com/awslabs/aws-c-compression/blob/v0.2.16/include/aws/compression/exports.h
---
> aws-c-compression: add missing interface definition if shared + modernize more for conan v2

- recipes/libzippp/all/conanfile.py
When it has been migrated to CMakeToolchain, a tricky detail has been skipped: this recipe was relying on the implicit behavior that it was built as a subdirectory through the old CMakeLists wrapper, and since upstream CMakeLists has a special logic to enable tests by default if CMakeLists is top project (https://github.com/ctabin/libzippp/blob/libzippp-v6.0-1.9.2/CMakeLists.txt#L30) and that this recipe did not explicitly manage this option, therefore tests were built after the migration and failed on Linux with conan v2 client (see https://github.com/conan-io/conan/issues/13560).
This PR explicitly disables the build of upstream tests.
---
> libzippp: fix all shared build on Linux for conan v2 + add package_type

- recipes/screen_capture_lite/all/conanfile.py
- recipes/screen_capture_lite/all/test_v1_package/conanfile.py
- fix min cppstd, it's C++17 since 17.1.596: https://github.com/smasherprog/screen_capture_lite/blob/17.1.596/CMakeLists.txt#L4
- remove injection of CMP0077 (for BUILD_SHARED_LIBS), it's fixed in conan 1.54.0
- don't use self.info in validate()
- fix a check in validate() related to apple-clang
- remove unused python imports
---
> screen_capture_lite: use version range for cmake + few minor improvements

- recipes/bitserializer/all/conanfile.py
- recipes/bitserializer/all/test_package/conanfile.py
- recipes/bitserializer/all/test_v1_package/conanfile.py
- fix regression introduced by https://github.com/conan-io/conan-center-index/pull/14933 regarding conan v2 (it's self.info.clear(), and we must rely on self.info in package_id())
- add fPIC option when with_csv option is enabled since it generates a static lib
- use cmake_layout in case of CMake build
- fix transitive traits of rapidyaml (it's a dependency of header-only part of this lib, like other dependencies) 
- remove with_csv & with_rapidyaml options if version < 0.50, instead of raising
- avoid replace_in_file() with strict=False, it's a bad practice
---
> bitserializer: fix conan v2 regression introduced by previous PR & new logic in 0.50

- recipes/fast-cdr/all/conandata.yml
- recipes/fast-cdr/config.yml
Specify library name and version:  **fast-cdr/1.0.27**
This is a dependency for a newer fast-dds version, which is in preparation
---
> fast-cdr: Bump version to 1.0.27

- recipes/at-spi2-core/config.yml
- recipes/at-spi2-core/new/conandata.yml
Specify library name and version:  **at-spi2-core/2.48.0**
---
> at-spi2-core: add version 2.48.0

- recipes/thrift/all/conanfile.py
- recipes/thrift/all/test_package/conanfile.py
- fix build os logic in build requirement
- use version range for openssl
- bump qt
- use export_conandata_patches()
- remove CMP0077 workaround (fixe in conan 1.54.0)
- fix test package with conan v2 client (add run=True to be able to call executable from requirement: `thrift --version`)
---
> thrift: use version range for openssl + modernize more for conan v2

- recipes/librdkafka/all/conanfile.py
- bump dependencies and use version range for openssl
- remove workarounds for 2  issues (includedirs/libdirs/bindirs of components, and PKG_CONFIG_PATH for CMake) fixed in conan 1.50.0 & 1.55.0 respectively. This is why required_conan_version is updated to 1.55.0
---
> librdkafka: add package_type + bump dependencies

- recipes/sophus/all/conandata.yml
- recipes/sophus/all/conanfile.py
- recipes/sophus/config.yml
Specify library name and version:  **sophus **
sophus update its versioning scheme (https://github.com/strasdat/Sophus/releases), the old download link is 404
---
> sophus: update sophus version schema, update download link and modernize more

- recipes/libpointmatcher/all/conandata.yml
- recipes/libpointmatcher/all/conanfile.py
- recipes/libpointmatcher/all/patches/1.3.1-0001-fix-cmake.patch
- recipes/libpointmatcher/all/test_package/CMakeLists.txt
- recipes/libpointmatcher/all/test_package/conanfile.py
- recipes/libpointmatcher/all/test_package/test_package.cpp
- recipes/libpointmatcher/all/test_v1_package/CMakeLists.txt
- recipes/libpointmatcher/all/test_v1_package/conanfile.py
- recipes/libpointmatcher/config.yml
There are at least 2 issues to fix for v2 pipeline:
- libpointmatcher is broken with eigen 3.4.0, so it depends on eigen 3.3.9 (until a fix can be found: https://github.com/ethz-asl/libpointmatcher/issues/496). But libnabo (another dependency of libpointmatcher) depends on eigen 3.4.0 in its recipe, so v2 pipeline will hard fail since conan v2 client is super strict regarding version override.
- libpointmatcher depends on yaml-cpp 0.3.0 (vendored), which relies on auto_ptr, so it will fail to compile with C++17 or higher.
---
> New recipe libpointmatcher/1.3.1

- recipes/sfml/all/conanfile.py
> sfml: bump dependencies and depend on openal-soft instead of deprecated openal

- recipes/qt/5.x.x/conanfile.py
- recipes/qt/5.x.x/test_package/CMakeLists.txt
- recipes/qt/5.x.x/test_package/conanfile.py
- recipes/qt/5.x.x/test_package/meson.build
- recipes/qt/5.x.x/test_v1_package/CMakeLists.txt
- recipes/qt/5.x.x/test_v1_package/conanfile.py
- recipes/qt/5.x.x/test_v1_package/meson.build
- recipes/qt/5.x.x/test_v1_package/test_package.pro
- inject `VirtualRunEnv` in `build` scope (in case of native build) since path to shared libs of several requirements must be visible when executables built during qt build process are executed (because these executables link to some requirements).
- Also fix `DYLD_LIBRARY_PATH` workaround on macOS, it was broken (it's the same usage than previous point, but as usual SIP defeats everything, leading to this workaround).
- as a consequence, also remove some build requirements erroneously added by https://github.com/conan-io/conan-center-index/pull/16404 (see https://github.com/conan-io/conan-center-index/pull/16404#discussion_r1148160492). They are requirements actually, but their shared libs must be visible in PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH during build process as described in …
> qt 5.x: several fixes for conan v2

- recipes/h5pp/all/conandata.yml
- recipes/h5pp/all/conanfile.py
- recipes/h5pp/all/patches/fix-support-new-hdf5-v1.8.3-5.patch
- recipes/h5pp/all/patches/fix-support-new-hdf5-v1.8.6.patch
- recipes/h5pp/all/patches/fix-support-new-hdf5-v1.9.0.patch
- recipes/h5pp/all/test_package/CMakeLists.txt
- recipes/h5pp/all/test_package/conanfile.py
- recipes/h5pp/all/test_v1_package/CMakeLists.txt
- recipes/h5pp/all/test_v1_package/conanfile.py
- recipes/h5pp/all/test_v1_package/test_package.cpp
**h5pp/1.11.0**
Updated the recipe and tests to work with conan v2. As far as I can tell the hooks for conan 2 aren't working yet, so I haven't tried that.
Edit: should fix https://github.com/conan-io/conan-center-index/issues/17394 and https://github.com/conan-io/conan-center-index/pull/17395.
---
> h5pp: conan v2 support

- recipes/flatbuffers/all/conandata.yml
- recipes/flatbuffers/all/conanfile.py
Specify library name and version:  **flatbuffers/23.3.3**
Old versions of flatbuffers, up to and including `v23.1.21`, required CMake 3.16 or newer de-facto, see: https://github.com/google/flatbuffers/blob/v23.1.21/CMakeLists.txt#L4-L16. Since https://github.com/google/flatbuffers/pull/7801 and starting with version 23.3.3, the `cmake_minimum_required` is now 3.8, which mean an explicit `tool_requires` is no longer required as per Conan Center's current conventions.
---
> flatbuffers/23.3.3: updated cmake required version

- recipes/clove-unit/all/conanfile.py
- recipes/clove-unit/all/test_package/CMakeLists.txt
follow up of https://github.com/conan-io/conan-center-index/pull/17050
- many useless stuff from package template are removed
- fix required_conan_version. conan 1.50.0 is sufficient.
- cmake names are removed. This library doesn't provide a CMake config file.
/cc @fdefelici
---
> clove-unit: cleanup recipe and don't suggest unofficial CMake names

- recipes/googleapis/all/conandata.yml
- recipes/googleapis/all/conanfile.py
- recipes/googleapis/all/helpers.py
- recipes/googleapis/config.yml
Specify library name and version:  **googleapis/cci.20230501**
This is the first in a series of PRs to update `google-cloud-cpp` to v2.10.1.  It updates googleapis to a snapshot circa 2023-05-01 (thus the version).  The SHA matches what `google-cloud-cpp` expects.  Future PRs will update `grpc-protos`, `grpc`, and finally `google-cloud-cpp`.
---
> [googleapis] prepare for google-cloud-cpp-2.10.1

- recipes/zbar/all/conanfile.py
follow up of https://github.com/conan-io/conan-center-index/pull/16569
- bump requirements and build requirements
- use output.warning instead of output.warn (removed in conan v2)
- fix copy of gnu-config files
- add VirtualBuildEnv since there are requirements
- properly handle dependencies:
- add PkgConfigDeps & AutotoolsDeps
- libiconv is required even in 0.10
- remove iconv from system libs if macOS, since we have libiconv in requirements
- cleanup topics
---
> zbar: bump dependencies + few fixes following v2 migration

- recipes/fmt/all/conanfile.py
Specify library name and version:  **fmt/9.1.0**
In the header-only version of the library the libdirs and bindirs obsolete and generate some compiler warnings.
The fix is related to issue #17152.
---
> fmt: invalid libdirs and bindirs when packaging header-only version

- recipes/grpc-proto/all/conanfile.py
Specify library name and version:  **grpc-proto/cci.20220627**
This is the second PR in a series to update `google-cloud-cpp` to v2.10.1.  The first PR updated `googleapis` to match the requirements in `google-cloud-cpp`. This PR bumps `grpc-proto` dependency on googleapis.  I will follow up with PRs to update `grpc` and then `google-cloud-cpp`.
---
> [grpc-proto] prepare for google-cloud-cpp-v2.10.1

- recipes/grpc/all/conanfile.py
Specify library name and version:  **grpc/1.50.1**
This is the third PR in a series to update `google-cloud-cpp` to v2.10.1. The first PR updated `googleapis` to match the requirements in `google-cloud-cpp`.  A second PR bumped the `grpc-protos` dependency, this PR bumps the `grpc` dependency on `googleapis`.  The next PR in the series will (I expect) update `google-cloud-cpp`.
---
> [grpc] prepare for google-cloud-cpp-v2.10.1

- recipes/ninja/all/conanfile.py
Specify library name and version:  **ninja/all**
This PR ensures that ninja is built with a static C++ runtime on Linux, taking advantage of the fact that Ninja has no dependency on other libraries. 
Additional background:
This recipe erases the `compiler` setting, however it is still relevant at runtime since it requires that the system this executable is run on, has a version of libstdc++ that is _at least_ the same or greater than the one it was built with, which can cause problems on other systems.
More information:
**Before this change**:
```
0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
0x0000000000000001 (NEEDED) …
```
> ninja: use static runtime on Linux

- recipes/glib/all/conanfile.py
- recipes/glib/all/test_package/conanfile.py
Specify library name and version:  **glib/all**
Revert the `shared` option to have a `False` value by default, in line with the Conan Center defaults.
The PR that introduced this change: https://github.com/conan-io/conan-center-index/pull/12171 attempted to do so in order to be able to _remove_ the `full_package_mode` on the `glib` dependency found in recipes where `glib` is a dependency. However, `full_package_mode` has not been removed, and most crucially, having `shared=True` by default does _not_ solve the problem mentioned in this issue: https://github.com/conan-io/conan-center-index/issues/11684 - there will still be missing binaries if the exact version of glib changes across the dependency graph. 
Having a default on `shared=True` causes "missing binary" problems in the Conan 2.0 …
> glib: revert shared option to be False by default

- recipes/mawk/all/conandata.yml
- recipes/mawk/all/conanfile.py
- recipes/mawk/all/test_package/conanfile.py
- recipes/mawk/config.yml
Specify library name and version:  **mawk/1.3.4-20230404**
The native version (1.3.3) installed in Conan docker images is bugged and can't be updated by Ubuntu repo because it's the only version available. As optional fix, we can package the newest version of mawk application and use it as tool requirement.
Required by #16284
---
> [mawk] Add new recipe for awk language interpreter

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/config.yml
Specify library name and version:  **libxml2/1.11.4**
---
> libxml2: add version 2.11.4

- recipes/ftxui/all/conandata.yml
- recipes/ftxui/all/conanfile.py
- recipes/ftxui/config.yml
Specify library name and version:  **ftxui/4.1.0**
- add version 4.1.0
- since 4.1.0, ftxui provides pkgconfig
---
> ftxui: add version 4.1.0, add package_type

- recipes/opus/all/conanfile.py
Add an option to allow the stack protector to be disabled to make it easier to build with Emscripten. This is already exposed through CMake, so the Conan recipe change is minimal; just add an option & pass it through.
The `OPUS_STACK_PROTECTOR` option defaults to `ON` in the CMake build, so I have defaulted the Conan option to `True` to mirror that.
---
> opus: Add option to disable stack protector.

- recipes/bshoshany-thread-pool/all/conanfile.py
- recipes/bshoshany-thread-pool/all/test_package/CMakeLists.txt
- recipes/bshoshany-thread-pool/all/test_package/conanfile.py
- recipes/bshoshany-thread-pool/all/test_v1_package/CMakeLists.txt
- recipes/bshoshany-thread-pool/all/test_v1_package/conanfile.py
Specify library name and version:  **bshoshany-thread-pool/all**
Modernize recipe:
- Update `test_package` to work with Conan2
- Add `test_v1_package`
- Fix `validate()` in `conanfile.py` (calling `self.output.warn` raises)
---
> bshoshany-thread-pool: conan v2 support

- recipes/catch2/3.x.x/conanfile.py
Add recipe option to catch to toggle CATCH_CONFIG_NO_POSIX_SIGNALS.
Specify library name and version:  catch2/3.x.x
Adds a recipe option so that conan can be used to build this dependency for bare metal platforms which do not implement some or all of the posix signals.
---
> Catch2: Add recipe option for CATCH_CONFIG_NO_POSIX_SIGNALS

- recipes/sdbus-cpp/all/conanfile.py
There is no `self.output.warn` method in `conan2`.
---
> sdbus-cpp/all: Conan v2 compatibility fix

- recipes/dataframe/all/conandata.yml
- recipes/dataframe/all/conanfile.py
- recipes/dataframe/all/patches/2.0.0-0002-no-export-templates.patch
follow up of https://github.com/conan-io/conan-center-index/pull/16848#discussion_r1158549411
From https://github.com/hosseinmoein/DataFrame/pull/235
---
> dataframe: remove dllimport of templates in 2.0.0

- recipes/libmad/all/CMakeLists.txt
- recipes/libmad/all/conandata.yml
- recipes/libmad/all/conanfile.py
- recipes/libmad/all/test_package/CMakeLists.txt
- recipes/libmad/all/test_package/conanfile.py
- recipes/libmad/all/test_v1_package/CMakeLists.txt
- recipes/libmad/all/test_v1_package/conanfile.py
I've replaced build system by a simple CMakeList.txt for 2 reasons:
- msvc build was relying on `.dsp` files which are not supported anymore by `devenv` since Visual Studio 2022.
- these old autotools files didn't scale (no support for macOS M1)
---
> libmad: conan v2 support

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.92.0**
---
> daw_header_libraries: add version 2.92.0

- recipes/gstreamer/all/conandata.yml
- recipes/gstreamer/all/conanfile.py
- recipes/gstreamer/all/test_package/CMakeLists.txt
- recipes/gstreamer/all/test_package/conanfile.py
- recipes/gstreamer/all/test_v1_package/CMakeLists.txt
- recipes/gstreamer/all/test_v1_package/conanfile.py
- recipes/gstreamer/config.yml
Add tests for PkgConfigDeps generator as for `glib`.
Specify library name and version:  **gstreamer/***
---
> gstreamer: Support Conan V2

- recipes/c-ares/all/conandata.yml
- recipes/c-ares/config.yml
This fixes the following security issues:
- CVE-2023-32067. High. 0-byte UDP payload causes Denial of Service [12]
- CVE-2023-31147. Moderate. Insufficient randomness in generation of DNS query IDs [13]
- CVE-2023-31130. Moderate. Buffer Underwrite in ares_inet_net_pton() [14]
- CVE-2023-31124. Low. AutoTools does not set CARES_RANDOM_FILE during cross compilation [15]
Specify library name and version:  **c-ares/1.19.1**
---
> c-ares: add version 1.19.1

- recipes/arrow/all/conandata.yml
- recipes/arrow/all/conanfile.py
- recipes/arrow/config.yml
Specify library name and version:  **arrow/12.0.0**
On the Arrow 12.0.0 release [PLASMA was removed](https://github.com/apache/arrow/issues/33243) and [ACERO was moved to its own shared library](https://github.com/apache/arrow/issues/15280).
---
> arrow: add version 12.0.0

- recipes/fmt/all/test_package/test_package.cpp
Specify library name and version:  **fmt/10.0.0**
test_package was having issues with C++20, this fixes the issues in the test_package
---
> Fix fmt test_package for C++20

- recipes/magic_enum/all/conandata.yml
- recipes/magic_enum/all/conanfile.py
- recipes/magic_enum/all/test_v1_package/CMakeLists.txt
- recipes/magic_enum/config.yml
Specify library name and version:  **magic_enum/***
- add version 0.9.0
- sort versions in config.yml and conandata.yml
- use add_subdirectory in test_v1_package
---
> magic_enum: add version 0.9.0, minor improvements

- recipes/libserial/all/conandata.yml
- recipes/libserial/all/conanfile.py
- recipes/libserial/all/patches/0001-add-cstdint.patch
Specify library name and version:  **libserial/***
- include cstdint for gcc13 compilation error
---
> libserial: include cstdint for gcc13, add package_type

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **leson/1.1.1**
---
> meson: add version 1.1.1

- recipes/arsenalgear/all/conanfile.py
Specify library name and version:  **exprtk/1.2.2**
While exprtk is used in public header of arsenalgear,
https://github.com/JustWhit3/arsenalgear-cpp/blob/v1.2.2/include/math.hpp
I have to add transitive_headers to exprtk.
---
> arsenalgear: add transitive_headers to exprtk

- recipes/arrow/all/conanfile.py
In correspondence of what is done here:
https://github.com/apache/arrow/blob/apache-arrow-12.0.0/cpp/src/arrow/dataset/CMakeLists.txt#L56-L63
> arrow: add a missing dependency

- recipes/minizip-ng/all/conandata.yml
- recipes/minizip-ng/all/conanfile.py
- recipes/minizip-ng/config.yml
Specify library name and version:  **minizip-ng/***
Try to fix #17634.
- add version 4.0.0
- fix patch for POSITION_INDEPENDENT_CODE
- add `include/minizip-ng` to include path 
---
> minizip-ng: add version 4.0.0

- recipes/vir-simd/all/conandata.yml
- recipes/vir-simd/all/conanfile.py
- recipes/vir-simd/all/test_package/CMakeLists.txt
- recipes/vir-simd/all/test_package/conanfile.py
- recipes/vir-simd/all/test_package/test_package.cpp
- recipes/vir-simd/all/test_v1_package/CMakeLists.txt
- recipes/vir-simd/all/test_v1_package/conanfile.py
- recipes/vir-simd/config.yml
**vir-simd/0.2.0**
I'd like to add the vir-simd library which provides a fallback implementation for std::experimental::simd, since I think it will be useful.
---
> Add vir-simd library

- recipes/backward-cpp/all/conanfile.py
- recipes/backward-cpp/all/patches/backward-cpp-1.5.patch
Specify library name and version:  **backward-cpp/1.6**
---
> backward-cpp: Add support for `libunwind` and Apple Silicon Macs

- recipes/opentelemetry-proto/all/conanfile.py
- recipes/opentelemetry-proto/all/test_package/conanfile.py
- recipes/opentelemetry-proto/all/test_v1_package/conanfile.py
Specify library name and version:  **opentelemetry-proto/***
---
> opentelemetry-proto: support conan v2

- recipes/gstreamer/all/conandata.yml
- recipes/gstreamer/config.yml
Specify library name and version:  **gstreamer/1.20.4**
The current recipe only contains the old 1.19 version of GStreamer, IMHO an update to the 1.20 is needed
---
> gstreamer: Add version 1.20

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.12.4**
---
> cpp-httplib: add version 0.12.4

- recipes/liblsl/all/conandata.yml
- recipes/liblsl/config.yml
Specify library name and version:  **liblsl/1.16.2**
This updates the recipe of liblsl to the latest version.
---
> liblsl: add version 1.16.2

- recipes/di/all/conandata.yml
- recipes/di/config.yml
Specify library name and version:  **di/1.3.0**
---
> di: add version 1.3.0

- recipes/onnx/all/conanfile.py
Specify library name and version:  **onnx/any**
Expose cmake `ONNX_DISABLE_STATIC_REGISTRATION` (Disabled by default as CMakeLists.txt default value).
This option is required to True when using packaged onnx with onnxruntime. See https://github.com/microsoft/onnxruntime/issues/8556#issuecomment-1005672965
This PR provides a programatic way to overcome https://github.com/conan-io/conan-center-index/issues/17380 (`-o onnx:disable_static_registration=True`).
onnxruntime package probably should require this option set to True (but not sure if CCI currently can consume non-default options).
---
> Onnx expose ONNX_DISABLE_STATIC_REGISTRATION with recipe option

- recipes/libpfm4/all/conandata.yml
- recipes/libpfm4/all/conanfile.py
- recipes/libpfm4/config.yml
Saw that it had a validate for Linux only, decided to simplify the recipe logic.
* Added `package_type`
* Removed `fPIC` management on Windows, as it does not run there
* Used `rm_safe`
* Removed logic conditional to the `os`, it's always Linux
For #17702
Specify library name and version:  **libpfm4/all**
> libpfm4: Simplify logic as only Linux is supported

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/all/conanfile.py
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/***
Since 5.0.0, fast_float add bsl-1.0 license.
https://github.com/fastfloat/fast_float/pull/203
---
> fast_float: add version 5.0.0, add BSL-1.0 license

- recipes/benchmark/all/conanfile.py
Specify library name and version:  **benchmark/1.8.0**
Benchmark has a build option for enabling performance counters: https://github.com/google/benchmark/blob/v1.5.4/docs/perf_counters.md
We want to use this feature, therefore I try to add an option which is disabled by default. As far as I have seen this is currently only for Linux supported, and requires the "libpfm4" library, which is available via Conan. This feature was added with version 1.5.4, therefore I include a version check too (even if our supported versions starts with a higher version number). 
Some time past by since I made my last contribution, and this is my very first in the time of Conan 2.x - I hope I did everything in the right way, please correct me if not.
---
> benchmark: add pfm option

- recipes/libcurl/all/conandata.yml
- recipes/libcurl/all/conanfile.py
- recipes/libcurl/config.yml
- add version 8.1.1
- update libnghttp2
---
> libcurl: add version 8.1.1, update libnghttp2

- recipes/expat/all/conanfile.py
Specify library name and version:  **expat/***
Try to fix #17541.
Because EXPAT_LARGE_SIZE has been introduced since 2.2.8, all versions in conan recipe support this feature.
https://github.com/libexpat/libexpat/blob/R_2_2_8/expat/Changes
---
> expat: add `large_size` option`

- recipes/at-spi2-core/all/conanfile.py
Specify library name and version:  **at-spi2-core/***
---
> at-spi2-core: deprecate old recipe

- recipes/atk/all/conanfile.py
Specify library name and version:  **atk/***
---
> atk: deprecate in favor of at-spi2-core

- .gitignore
Specify library name and version: all
While developing cmake recipes it's a bit annoying to not have cmakebuildinfo.cmake git-ignored by default. I thought it was more straighforward to create a PR with the changes, that you are free to accept or dismiss (if there is any reason to not exclude cmakebuildinfo.cmake), rather than opening an issue.
Thanks!
> cmake: add `conanbuildinfo.cmake` to `.gitignore`

- recipes/arrow/all/conanfile.py
- recipes/arrow/all/test_package/conanfile.py
I suggest a revival of #15983 to use it as a starting point for further improvements. See discussion in the original PR.
> arrow: modernize more for conan v2 (take two)

- recipes/quill/all/conandata.yml
- recipes/quill/all/conanfile.py
- recipes/quill/config.yml
Specify library name and version:  **quill/2.9.1**
- add version 2.9.1
- avoid applying patch since 2.9.1
---
> quill: add version 2.9.1

- recipes/cppitertools/all/conanfile.py
- recipes/cppitertools/all/test_package/CMakeLists.txt
- recipes/cppitertools/all/test_package/conanfile.py
Specify library name and version:  **cppitertools/2.1**
I'm updating for it to be conan v2 compatabile
---
> Update cppitertools for conan v2

- recipes/opencl-headers/all/conandata.yml
- recipes/opencl-headers/all/conanfile.py
- recipes/opencl-headers/config.yml
Specify library name and version:  **opencl-headers/all**
Scope of changes:
- Added several new versions including latest 2023.04.17
- Fixed `.pc` file name to be aligned with original [OpenCL-Headers.pc](https://github.com/KhronosGroup/OpenCL-Headers/blob/main/OpenCL-Headers.pc.in)
---
> opencl-headers: removed copy-paste errors in package_info section, added new versions

- recipes/libmount/all/conanfile.py
> libmount: Correctly identify the library's license as LGPL-2.1-or-later

- recipes/xtensor/all/conanfile.py
Specify library name and version:  **xtensor/all**
Add missing package type. This fixes issue in Conan 2.0 where consumers may get compiler errors due to missing headers from xsimd.
This will cause the package to be generated and published for Conan 2.0 as well.
> xtensor: add missing package_type

- recipes/libuv/all/conandata.yml
- recipes/libuv/all/conanfile.py
- recipes/libuv/all/patches/1.45.0/fix-cmake.patch
- recipes/libuv/config.yml
Specify library name and version:  **libuv/***
- add version 1.45.0
- added `LIBUV_BUILD_SHARED` macro
- rename uv_a.a to uv in static build
- add `package_type`
- remove destination from `get()`
---
> libuv: add version 1.45.0, support conan v2 more

- recipes/aws-c-cal/all/conanfile.py
- recipes/aws-c-cal/all/test_package/CMakeLists.txt
- recipes/aws-c-cal/all/test_package/conanfile.py
- recipes/aws-c-cal/all/test_v1_package/CMakeLists.txt
- recipes/aws-c-cal/all/test_v1_package/conanfile.py
- conan v2:
- fix windows/shared (protect double deletion of fPIC)
- fix test package (logic based on self.user_info can't work for conan v2, and it was anyway wrong to define this user_info for the sole purpose of test package)
- bump openssl to 3.x
---
> aws-c-cal: modernize more for conan v2 + bump openssl

- recipes/magic_enum/all/conandata.yml
- recipes/magic_enum/config.yml
Specify library name and version:  **magic_enum/0.9.1**
---
> magic_enum: Bump to 0.9.1

- recipes/openssl/1.x.x/conandata.yml
- recipes/openssl/3.x.x/conandata.yml
- recipes/openssl/config.yml
Specify library name and version:  **openssl/1.1.1u|3.0.9|3.1.1**
Routine upgrade to add latest security patch updates.
---
> openssl: add versions 1.1.1u/3.0.9/3.1.1

- recipes/miniaudio/all/conandata.yml
- recipes/miniaudio/config.yml
Specify library name and version:  **miniaudio/0.11.17**
---
> miniaudio: add version 0.11.17

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.93.1**
---
> daw_header_libraries: add version 2.93.1

- recipes/avahi/all/conanfile.py
This function is not declared on Linux.
Configure ignores warnings about the missing declaration. This causes issues when building with recent versions of Clang. Support for implicit declarations was removed in newer C standards in Clang. Telling configure that the setproctitle function is not available disables the use of this function in Avahi.
Fixes #17354.
Specify library name and version:  **avahi/0.8**
Note that `setproctitle` is correctly disabled on Linux in Avahi's master branch, so no upstream patches are necessary. I tested this in commit `6395c45` of Avahi locally.
Using both GCC and Clang, results in `ac_cv_func_setproctitle=no` in `config.log` without any manual intervention.
---
> avahi/0.8: Disable the use of the setproctitle function on Linux

- recipes/ring-span-lite/all/conanfile.py
This change performs some simple cleanup of these conanfile.py files in order to trigger a conan2 build of each.
---
> Bring ring-span-lite to conan2

- recipes/flatbuffers/all/conandata.yml
- recipes/flatbuffers/config.yml
Specify library name and version:  **flatbuffers/23.5.26**
---
> flatbuffers: add version 23.5.26

- recipes/boost/all/conandata.yml
- recipes/boost/all/dependencies/dependencies-1.82.0.yml
- recipes/boost/all/patches/1.82.0-locale-iconv-library-option.patch
- recipes/boost/config.yml
Boost/1.82.0
Bump the supported Boost version to the latest release. Needed by everybody.
---
> Add Boost 1.82.0

- recipes/mbits-diags/all/conandata.yml
- recipes/mbits-diags/config.yml
Specify library name and version:  **mbits-diags/0.9.5**
---
> add mbits-diags/0.9.5

- recipes/llhttp/all/CMakeLists.txt
- recipes/llhttp/all/conandata.yml
- recipes/llhttp/all/conanfile.py
- recipes/llhttp/all/test_package/CMakeLists.txt
- recipes/llhttp/all/test_package/conanfile.py
- recipes/llhttp/all/test_v1_package/CMakeLists.txt
- recipes/llhttp/all/test_v1_package/conanfile.py
> llhttp: conan v2 support

- recipes/libxcrypt/all/conandata.yml
- recipes/libxcrypt/config.yml
Specify library name and version:  ** libxcrypt/4.4.34**
---
> libxcrypt: add version 4.4.34

- recipes/nsync/all/conandata.yml
- recipes/nsync/config.yml
Specify library name and version:  ** nsync/1.26.0**
---
> nsync: add version 1.26.0

- recipes/lief/all/conandata.yml
- recipes/lief/config.yml
Specify library name and version:  **lief/0.13.1**
---
> lief: add version 0.13.1

- recipes/bshoshany-thread-pool/all/conandata.yml
- recipes/bshoshany-thread-pool/all/conanfile.py
- recipes/bshoshany-thread-pool/config.yml
Specify library name and version:  **bshoshany-thread-pool/3.5.0**
---
> bshoshany-thread-pool: add version 3.5.0

- recipes/opentelemetry-proto/all/conandata.yml
- recipes/opentelemetry-proto/config.yml
Specify library name and version:  **opentelemetry-proto/0.20.0**
---
> opentelemetry-proto: add version 0.20.0

- recipes/aws-c-io/all/conanfile.py
- add AWS_IO_USE_IMPORT_EXPORT interface definition. This definition is mandatory to properly define __delcspec(dllimport) if shared on windows.It's very important since aws-c-io has at least one global symbol in its interface. I've seen this issue while trying to build `aws-c-http` shared against `aws-c-io` shared with Visual Studio. It was failing with `h1_connection.c.obj : error LNK2019: unresolved external symbol g_aws_channel_max_fragment_size referenced in function s_connection_new` (`g_aws_channel_max_fragment_size` is a global symbol defined in `aws-c-io`, so it MUST have `__declspec(dllimport)` at consume time).
- bump s2n
---
> aws-c-io: fix interface definition for shared lib on windows + bump s2n + add package_type

- recipes/libnghttp2/all/conandata.yml
- recipes/libnghttp2/config.yml
Specify library name and version:  **libnghttp2/1.54.0**
---
> libnghttp2: add version 1.54.0

- recipes/pixman/all/conandata.yml
- recipes/pixman/all/conanfile.py
Specify library name and version:  **pixman/0.40.0**
The Pixman library is missing in ConanCenter for Debug build type. I tried to generate again via Tapaholes, but is still missing. This PR should generate a new recipe revision and new packages, fixing the problem (I hope). 
Related to https://github.com/conan-io/conan-center-index/pull/17844
/cc @ericLemanissier 
---
> [pixman] Remove collect_libs and use library real name

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/5.1.**
---
> fast_float: add version 5.1.0

- recipes/libxcrypt/all/conandata.yml
- recipes/libxcrypt/config.yml
Specify library name and version:  **libxcrypt/4.4.35**
---
> libxcrypt: add version 4.4.35

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/5.2.0**
---
> fast_float: add version 5.2.0

- recipes/glaze/all/conandata.yml
- recipes/glaze/all/conanfile.py
- recipes/glaze/config.yml
> glaze: add version 1.2.5, update dependencies

- recipes/roaring/all/conandata.yml
- recipes/roaring/config.yml
Specify library name and version:  **roaring/1.3.0**
---
> roaring: add version 1.3.0

- recipes/opencl-icd-loader/all/conandata.yml
- recipes/opencl-icd-loader/all/conanfile.py
- recipes/opencl-icd-loader/config.yml
Specify library name and version:  **opencl-icd-loader/2023.x.y**
Reason: to overcome the issue https://github.com/conan-io/conan/issues/14007
---
> opencl-icd-loader: added versions from 2023 year

- recipes/ftxui/all/conandata.yml
Specify library name and version:  **ftxui/4.1.1**
---
The given sha seems to be wrong.
> ftxui: Fix sha for version 4.1.1

- recipes/absent/all/conanfile.py
- recipes/absent/all/test_package/conanfile.py
- recipes/absent/all/test_v1_package/CMakeLists.txt
- recipes/absent/all/test_v1_package/conanfile.py
Specify library name and version:  **absent/0.0.1**, **absent/0.1.0**, **absent/0.2.0**, **absent/0.3.0**, **absent/0.3.1**
I tested this recipe with conan 1.60.1 and conan 2.0.6 on Linux.
---
> absent: conan v2 support

- recipes/at-spi2-core/all/conanfile.py
Specify library name and version:  **at-spi2-core/***
---
> at-spi2-core: remove outdated workaround

- recipes/hwloc/all/conandata.yml
- recipes/hwloc/all/conanfile.py
- recipes/hwloc/all/test_package/CMakeLists.txt
- recipes/hwloc/all/test_package/conanfile.py
- recipes/hwloc/all/test_package/test_package.c
- recipes/hwloc/config.yml
Specify library name and version:  **hwloc/2.9.0**
Closes https://github.com/conan-io/conan-center-index/issues/16973
Required for onetbb to support NUMA architectures / Hybrid cores.
---
> [hwloc] new recipe

- recipes/7bitconf/all/conandata.yml
- recipes/7bitconf/all/conanfile.py
- recipes/7bitconf/all/test_package/CMakeLists.txt
- recipes/7bitconf/all/test_package/conanfile.py
- recipes/7bitconf/all/test_package/test_package.cpp
- recipes/7bitconf/config.yml
Specify library name and version: 7bitconf/1.0.0
This is my C++17 configuration provider library.
https://github.com/7bitcoder/7bitConf
I will use this library in my other projects
---
> 7bitconf: add new recipe

- recipes/aws-c-http/all/conanfile.py
- recipes/aws-c-http/all/test_v1_package/CMakeLists.txt
see https://github.com/awslabs/aws-c-http/blob/v0.7.7/include/aws/http/exports.h
Without this fix, the build of aws-c-auth "all shared" fails with msvc.
---
> aws-c-http: add missing interface definition if shared + modernize more for conan v2

- recipes/opentelemetry-cpp/all/conandata.yml
- recipes/opentelemetry-cpp/all/conanfile.py
- recipes/opentelemetry-cpp/all/patches/1.9.1-0001-fix-cmake.patch
- recipes/opentelemetry-cpp/config.yml
Specify library name and version:  **opentelemetry-cpp/***
---
> opentelemetry-cpp: add version 1.9.1, update dependencies

- recipes/thrift/all/conandata.yml
- recipes/thrift/all/conanfile.py
- recipes/thrift/all/patches/0.18.1-0002-include-stddef.patch
- recipes/thrift/config.yml
Specify library name and version:  **thrift/***
---
> thrift: add version 0.18.1, use official urls, update boost

- recipes/opencore-amr/all/conandata.yml
- recipes/opencore-amr/all/conanfile.py
- recipes/opencore-amr/all/patches/0001-remove-deprecated-register-keyword.patch
- recipes/opencore-amr/all/test_package/CMakeLists.txt
- recipes/opencore-amr/all/test_package/conanfile.py
- recipes/opencore-amr/all/test_v1_package/CMakeLists.txt
- recipes/opencore-amr/all/test_v1_package/conanfile.py
Specify library name and version:  **opencore-amr/***
---
> opencore-amr: add Conan 2 support

- recipes/thrust/all/conanfile.py
Thrust can now use a custom version of CUB after merging #17411.
---
> Thrust: use cub from Conan

- recipes/util-linux-libuuid/all/conandata.yml
- recipes/util-linux-libuuid/all/conanfile.py
- recipes/util-linux-libuuid/all/test_package/CMakeLists.txt
- recipes/util-linux-libuuid/all/test_package/conanfile.py
- recipes/util-linux-libuuid/all/test_package/test_package.c
- recipes/util-linux-libuuid/config.yml
* This is the most actively maintained fork of libuuid
* This package should supersede the existing libuuid recipe, which should be deprecated as an inactive fork of the original libuuid. The existing libuuid recipe does not match what gets installed on linux systems, which causes a symbol conflict when a `system` package is used with `libuuid` in the dependency tree, such as `xorg/system`. See https://github.com/conan-io/conan-center-index/pull/17427#issuecomment-1545476420 for a concrete example of this.
Closes #17337
Specify library name and version:  **libuuid/2.39**
---
> [util-linux-libuuid] Add util-linux-libuuid package

- recipes/cpprestsdk/all/conanfile.py
- recipes/cpprestsdk/all/test_package/CMakeLists.txt
- bump boost & openssl
- follow import conventions of conan API
- remove boost minor mode (useless in conan v2 and problematic for v1 pipeline)
---
> cpprestsdk: add package_type + bump boost & openssl + remove package id boost minor mode

- recipes/argtable3/all/test_package/conanfile.py
Fixes the following error when using Conan 2.0:
```
======== Testing the package: Executing test ========
argtable3/3.2.0 (test package): Running test()
ERROR: argtable3/3.2.0 (test package): Error in test() method, line 25
self.run(f"{bin_path} --help", run_environment=True)
TypeError: run() got an unexpected keyword argument 'run_environment'
```
> argtable: fix test_package Conan 2 compatibility

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
Specify library name and version: imgui/1.89.5
---
> imgui: add version 1.89.5

- recipes/opencolorio/all/CMakeLists.txt
- recipes/opencolorio/all/conandata.yml
- recipes/opencolorio/all/conanfile.py
- recipes/opencolorio/all/patches/1.1.1-fix-cmake.patch
- recipes/opencolorio/all/patches/2.1.0-0001-fix-cmake-source-dir-and-targets.patch
- recipes/opencolorio/all/patches/2.1.0-0002-fix-pystring.patch
- recipes/opencolorio/all/patches/2.1.0-0003-strlen.patch
- recipes/opencolorio/all/patches/2.1.0-0004-fix-cpp-version-check.patch
- recipes/opencolorio/all/patches/2.2.1-0001-fix-cmake-source-dir-and-targets.patch
- recipes/opencolorio/all/patches/2.2.1-0002-fix-pystring.patch
- recipes/opencolorio/all/patches/2.2.1-0003-strlen.patch
- recipes/opencolorio/all/test_package/CMakeLists.txt
- recipes/opencolorio/all/test_package/conanfile.py
- recipes/opencolorio/all/test_v1_package/CMakeLists.txt
- recipes/opencolorio/all/test_v1_package/conanfile.py
- recipes/opencolorio/config.yml
Specify library name and version:  **opencolorio/***
- add version 2.2.1
- fix C++20 compilation errors in 2.1.0
- add version prefix to patch files
Retry https://github.com/conan-io/conan-center-index/pull/14683.
---
> opencolorio: add version 2.2.1, support conan v2, support C++20 in 2.1.0

- recipes/perfetto/all/conandata.yml
- recipes/perfetto/config.yml
Specify library name and version:  **perfetto/35.0**
```
v35.0 - 2023-06-07:
* Compression has been moved from perfetto_cmd to traced. Now compression is
supported even with write_into_file. The `compress_from_cli` config option
can be used to restore the old behavior.
* Changed the android.statsd datasource to batch multiple atoms into
a single trace packet. This improves performance and information
density.
* Fixed protozero parsing code to support field ids larger than
2^16 - 1. protozero now supports field ids up to 1,000,000
See https://github.com/google/perfetto/issues/510.
UI:
* Add support for deep links into the UI via query parameters.
* Fixed multiple issues around the display of track event log
messages See …
```
> (18044) Bump perfetto to v35.0

- recipes/at-spi2-core/config.yml
- recipes/at-spi2-core/new/conandata.yml
Specify library name and version:  **at-spi2-core/2.48.3**
---
> at-spi2-core: add version 2.48.3

- recipes/cmake/3.x.x/conandata.yml
Specify library name and version:  **cmake/3.26.4**
This adds instructions for building `cmake/3.2.6.4` from source.
The binary package for `cmake/3.26.4` was added previously for `x86_64` and `arm` but this causes breakage for other architectures when a dependency depends on `cmake/3.26.4` since the binaries for them are not present and the recipe doesn't allow for building version 3.26.4 from source.
---
> Add source code build for CMake 3.26.4

- recipes/mppp/all/conandata.yml
- recipes/mppp/all/conanfile.py
- recipes/mppp/all/patches/0.27-0002-remove-fmt-version.patch
Specify library name and version:  **mppp/0.27**
When I created mppp recipe with `with_fmt=True`, there is a compilation error following:
> Could not find a configuration file for package "fmt" that is compatible
It may be caused by `find_package(fmt)` with old version(6.2).
```cmake
set(_MPPP_MIN_FMT_VERSION "6.2")
if(MPPP_WITH_FMT)
find_package(fmt ${_MPPP_MIN_FMT_VERSION} REQUIRED CONFIG)
```
Then I created the patch to remove version number from `find_package`.
---
> mppp: update fmt, fix compilation error on with_fmt=True

- recipes/gdcm/all/conanfile.py
Specify library name and version:  **gdcm/all**
zlib-ng will be needed for new ITK release (5.3.0) so I'm trying to add zlib-ng to libraries that are used by ITK.
---
> gdcm: add with_zlibng option

- recipes/simde/all/conandata.yml
- recipes/simde/all/conanfile.py
Specify library name and version:  **simde/0.7.6**
Simde supports all platforms.
https://github.com/conan-io/conan-center-index/pull/18087#pullrequestreview-1501929198
I removed `validate()` method.
---
> simde: supports all platforms

- recipes/certify/all/conanfile.py
- recipes/certify/all/test_package/CMakeLists.txt
- recipes/certify/all/test_package/conanfile.py
- recipes/certify/all/test_package/test_package.cpp
> certify: migrate to Conan v2

- recipes/libinterpolate/all/conandata.yml
- recipes/libinterpolate/all/conanfile.py
- recipes/libinterpolate/config.yml
Specify library name and version: libinterpolate/2.6.4
Finally figured out why Windows builds were failing.
---
- [x ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> [libinterpolate]: added version 2.6.4, which adds Windows support.

- recipes/spdlog/all/conandata.yml
- recipes/spdlog/all/conanfile.py
- recipes/spdlog/all/patches/1.11.0-0001-fix-fmt10-build.patch
Specify library name and version:  **spdlog/1.11.0**
problems:
spdlog 1.11.0 do not support. fmt 10
https://github.com/gabime/spdlog/issues/2782
https://github.com/gabime/spdlog/issues/2767
relate pr:
https://github.com/gabime/spdlog/pull/2694
https://github.com/spack/spack/pull/38082
---
> spdlog: bump fmt10.0.0 and apply patch to fix build error

- recipes/portable-file-dialogs/all/conanfile.py
- recipes/portable-file-dialogs/all/test_package/CMakeLists.txt
- recipes/portable-file-dialogs/all/test_package/conanfile.py
Specify library name and version:  **portable-file-dialogs/***
---
> portable-file-dialogs: migrate to Conan v2

- recipes/stringtoolbox/all/conanfile.py
- recipes/stringtoolbox/all/test_package/CMakeLists.txt
- recipes/stringtoolbox/all/test_package/conanfile.py
Specify library name and version:  **stringtoolbox/***
---
> stringtoolbox: migrate to Conan v2

- recipes/opentelemetry-cpp/all/conanfile.py
Some of these tool requirements are only needed with some options enabled
Specify library name and version:  **opentelemetry/***
---
> opentelemetry: fixup requirements

- recipes/create-dmg/all/conanfile.py
The content of the res folder was wrong and the script wasn't working properly:
```
~/.conan/data/create-dmg/1.1.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/create-dmg --volname MyApp --background /Users/martindelille/dev/phonations/core/platform/apple/dmg_bg.png --app-drop-link 450 218 --icon MyApp.app 150 218 --window-size 600 450 MyApp.dmg MyApp.app
Creating disk image...
.................................................................................................
created: /Users/martindelille/dev/phonations/core/build/Release/_CPack_Packages/Darwin/External/MyApp_Grand-Mont_23.6.5.3_6c2616171_commercial_dirty/rw.MyApp.dmg
Mounting disk image...
Mount directory: /Volumes/MyApp
Device name:     /dev/disk8
Copying background file …
```
> Fix create-dmg res folder

- recipes/pkgconf/all/conandata.yml
Specify library name and version:  **pkgconf/all**
The old source https://distfiles.dereferenced.org is down, the only info I found about it was https://git.alpinelinux.org/aports/commit/?id=75a42157eee297c14726eb622d5ce50d99fc27ba
Taking their proposed url, unless there is an "official" one?
---
> Fix pkgconf source url

- recipes/libsecret/all/conanfile.py
Specify library name and version:  **libsecret/all**
Libsecret depends on glib's gio, but it is not expressed in the cppinfo like the other components from glib.
This causes an issue in the `test_package` when `*:shared=True` and the linker is not configured to pass `--as-needed` (it's the default in modern distros, but not in Conan Center).
```
[100%] Linking CXX executable test_package
/usr/bin/cmake -E cmake_link_script CMakeFiles/test_package.dir/link.txt --verbose=1
/usr/local/bin/c++  -m64 -O3 -DNDEBUG  -m64 CMakeFiles/test_package.dir/test_package.cpp.o  -o test_package  -L/home/conan/.conan2/p/libsedbf40cfdd3a8b/p/lib  -L/home/conan/.conan2/p/glibf695b2f38b33d/p/lib  -L/home/conan/.conan2/p/pcre2f38075352b369/p/lib  -L/home/conan/.conan2/p/zlib5fd5adbde7f5c/p/lib …
```
> libsecret: add dependency on glib::gio component in cpp_info

- recipes/seadex-essentials/all/conanfile.py
Specify library name and version:  **seadex-essentials/all**
Fixes the conflicts from https://github.com/conan-io/conan-center-index/issues/18134, while also improving simplifying logic that as @czoido pointed out, is no good either way.
> seadex-essentials: Bump versions, remove header option force

- recipes/breakpad/all/conandata.yml
- recipes/breakpad/all/conanfile.py
- recipes/breakpad/all/patches/0003-Fix-gcc11-compilation.patch
Specify library name and version:  **breakpad/cci.20210521**
Fixes #18137
> #18137 Fix compilation of breakpad with gcc-11

- recipes/jpcre2/all/conanfile.py
- recipes/jpcre2/all/test_package/CMakeLists.txt
- recipes/jpcre2/all/test_package/conanfile.py
- recipes/jpcre2/all/test_package/test_package.cpp
- recipes/jpcre2/all/test_v1_package/CMakeLists.txt
- recipes/jpcre2/all/test_v1_package/conanfile.py
Specify library name and version:  **jpcre2/***
---
> jpcre2: migrate to Conan v2

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
Specify library name and version:  **imgui/1.89.7**
---
> imgui: add version 1.89.7, 1.89.7-docking

- recipes/nlohmann_json/all/conandata.yml
- recipes/nlohmann_json/config.yml
Specify library name and version:  **nlohmann_json/3.5.0**
I am not the author of nlohmann_json.
I am adding version 3.5.0 because it is used by other software I am working on. I am migrating to conan and I wish to isolate any conan issues vs library upgrade issues.
---
- [*] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [*] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [*] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> nlohmann_json: add version 3.5.0

- recipes/libpng/all/conandata.yml
- recipes/libpng/config.yml
Specify library name and version:  **libpng/1.6.32**
I am not the author of this library.
I am porting an application to conan. The application used this exact version of libpng, so I added it to conan.
---
- [*] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [*] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [*] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> libpng: add version 1.6.32

- recipes/bison/all/conanfile.py
Specify library name and version:  **bison/all**
Use `conf_info` instead of legacy user info.
> bison: fix building on Windows with Conan 2.0

- recipes/armadillo/all/conandata.yml
- recipes/armadillo/all/conanfile.py
- recipes/armadillo/all/patches/0002-Guard-dependency-discovery-11.4.x.patch
- recipes/armadillo/all/patches/0003-Guard-dependency-discovery-12.2.x.patch
- recipes/armadillo/all/test_package/CMakeLists.txt
- recipes/armadillo/all/test_package/conanfile.py
- recipes/armadillo/config.yml
Specify library name and version:  **armadillo/12.2.0**
12.2.0 saw the removal of HDF5 from the armadillo wrapper as per https://gitlab.com/conradsnicta/armadillo-code/-/issues/227. I've added it back in here for consistency with the interface of previous versions and remove the need for consumers to concern themselves with dependency management of armadillo dependencies. This represents a deviation from the way this is being managed upstream though, so happy to take guidance on whether hdf5 should still be included as a dependency in the armadillo recipe for 12.2.0.
---
> [armadillo] Add version 12.2.0

- recipes/aws-c-mqtt/all/conanfile.py
- recipes/aws-c-mqtt/all/test_v1_package/CMakeLists.txt
see https://github.com/awslabs/aws-c-mqtt/blob/v0.8.10/include/aws/mqtt/exports.h
---
> aws-c-mqtt: add missing interface definition if shared + modernize more for conan v2

- recipes/aws-c-event-stream/all/conanfile.py
- recipes/aws-c-event-stream/all/test_v1_package/CMakeLists.txt
see https://github.com/awslabs/aws-c-event-stream/blob/v0.2.20/include/aws/event-stream/event_stream_exports.h
---
> aws-c-event-stream: add missing interface definition if shared + modernize more for conan v2

- recipes/libssh2/all/conanfile.py
Specify library name and version:  **libssh2/1.11.0**
Using the version range for the dependency on openssl.
Support for openssl 3.x was marked at *not working* in a comment that I added previously, but that appears to have been a local configuration issue. It is working now.
---
> Use version range for openssl dependency including version 3.x

- recipes/aaf/all/conanfile.py
Specify library name and version:  **aaf/all**
While this package contained dynamically loaded libraries, the library [documentation](https://aaf.sourceforge.net/AAFProjectFAQ.html) specifies that consumers are to link against two _static_ libraries:
- aaflib
- aafiid
The `aaflib` static library contains logic to load the DLLs _at runtime_,  which it does via `dlopen` - in order for that to work, at runtime it needs to be able to locate those libraries.
This PR:
* removes `AAFCOAPI` and `libcom-api` from being expressed as libraries in the `package_info()`, as these are not meant to be directly linked. This is further supported by the scripts in the original sources, which only places two `.a` files in the `lib` folder, and places the `.so/.dylib/.dll` files in the `bin` folder for all …
> aaf: add package type and fix test_package on Windows with Conan 2

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Specify library name and version:  **glib/2.77.0**
---
> glib: add version 2.77.0

- recipes/aws-c-auth/all/conanfile.py
see https://github.com/awslabs/aws-c-auth/blob/v0.6.26/include/aws/auth/exports.h
Without this fix, the build of aws-c-s3 "all shared" fails with msvc.
---
> aws-c-auth: add missing interface definition if shared + modernize more for conan v2

- .c3i/config_v1.yml
- .c3i/config_v2.yml
Add msvc 193 to the Conan 2.0 platform matrix.
> infra: add Visual Studio 2022 configuration to Conan 2.0 checks (msvc 193)

- recipes/nudb/all/conanfile.py
- recipes/nudb/all/test_package/CMakeLists.txt
- recipes/nudb/all/test_package/conanfile.py
- recipes/nudb/all/test_v1_package/CMakeLists.txt
- recipes/nudb/all/test_v1_package/conanfile.py
Only substantial changes in the recipe:
* Replaced `cmake_target_name` + `cmake_target_module_name` with `cmake_target_name` + `cmake_target_aliases`. Having different targets for module and config modes seemed bug-prone to me.
* Bumped boost from 1.78 to 1.82
> nudb: migrate to Conan v2

- recipes/mingw-builds/all/conanfile.py
- recipes/mingw-builds/all/test_package/conanfile.py
- recipes/mingw-builds/all/test_package/main.cpp
closes https://github.com/conan-io/conan-center-index/pull/17768
Some of the changes in this PR are due to the fact that conan-center-index does not build packages for mingw, so this means it does not use mingw profiles to generate this package. In order to make this package comaptible, I had to turn some of the invalid configuration excetions into warnings. I know it is not the best solution but I think we should go this way for now because:
- It is more important to have a mingw tool recipe working for conan 2 asap than to make sure it raises when the compiler is not gcc and so.
- I believe, people using this recipe as tool require already know that they should use the "gcc" compiler in their profiles (in case they did not see the warnings"
I have also removed the compilation of the …
> [mingw-builds] Recipe and test package compatibility for conan v2

- recipes/charls/all/conanfile.py
Specify library name and version:  **charls/all**
Add flags to skip building tests and samples in the `charls` recipe. This fixes ability to build with Visual Studio 2022, which fails with these errors:
```
C:\Users\conan\.conan2\p\b\charlbaf5e7f3ca287\b\src\test\bitstreamdamage.cpp(105,54): error C3848: expression having type 'const std::uniform_int_distributio
n<uint32_t>' would lose some const-volatile qualifiers in order to call 'unsigned int std::uniform_int<_Ty>::operator ()<std::mt19937>(_Engine &)' [C:\Users\
conan\.conan2\p\b\charlbaf5e7f3ca287\b\build\test\charlstest.vcxproj]
with
[
_Ty=uint32_t,
_Engine=std::mt19937
]
C:\Users\conan\.conan2\p\b\charlbaf5e7f3ca287\b\src\test\main.cpp(124,44): error C3848: expression having type 'const std::uniform_int_distribution<uint32_t>
' …
```
> charls: skip building tests

- recipes/inih/all/conandata.yml
- recipes/inih/all/conanfile.py
- recipes/inih/config.yml
Specify library name and version:  **inih/***
- add with_inireader option
- INIReader library requires C++
- INIReader in inih>=57 requires C++11
---
> inih: add version 57, add with_inireader option

- recipes/zookeeper-client-c/all/conandata.yml
- recipes/zookeeper-client-c/all/conanfile.py
- recipes/zookeeper-client-c/all/patches/3.8.1-0001-add-install.patch
- recipes/zookeeper-client-c/all/test_package/CMakeLists.txt
- recipes/zookeeper-client-c/all/test_package/conanfile.py
- recipes/zookeeper-client-c/all/test_package/test_package.c
- recipes/zookeeper-client-c/config.yml
Specify library name and version:  **zookeeper/3.8.1**
Try to close https://github.com/conan-io/conan-center-index/issues/17787.
While zookkeeper-client-c requires code generated from jute, this recipe requires the installation of jdk and maven, which are needed to execute jute.
---
> zookeeper-client-c: add recipe

- recipes/eastl/all/conanfile.py
Specify library name and version:  **eastl/all**
Older versions of eastl lack this patch: https://github.com/electronicarts/EASTL/pull/474/files, which is required to be compatible with the most recent updates of Visual Studio 2022.
Given that the recently released version has these fixes, we can raise an invalid configuration for the older version.
> eastl: older versions not compatible with msvc193

- recipes/commata/all/conandata.yml
- recipes/commata/config.yml
Specify library name and version:  **commata/0.2.5**
---
> commata: add version 0.2.5

- recipes/harfbuzz/all/conandata.yml
- recipes/harfbuzz/config.yml
Specify library name and version:  **harfbuzz/8.0.0**
---
> harfbuzz: add version 8.0.0

- recipes/simple-websocket-server/all/conanfile.py
- recipes/simple-websocket-server/all/test_package/CMakeLists.txt
- recipes/simple-websocket-server/all/test_package/conanfile.py
- recipes/simple-websocket-server/all/test_v1_package/CMakeLists.txt
- recipes/simple-websocket-server/all/test_v1_package/conanfile.py
> simple-websocket-server: migrate to Conan v2

- recipes/flecs/all/conandata.yml
- recipes/flecs/config.yml
Specify library name and version:  **flecs/3.2.4**
The latest version wasn't on conan.io, so I wanted to add it.
---
> Add flecs version 3.2.4

- recipes/sdl_ttf/all/conandata.yml
- recipes/sdl_ttf/all/conanfile.py
- recipes/sdl_ttf/all/patches/2.20.1-0002-remove-unsupported-property.patch
- recipes/sdl_ttf/config.yml
> sdl_ttf: and 2.20.2, bump dep sdl, conan v2 fixes

- recipes/onnx/all/conanfile.py
The version check for the "disable_static_registration" on the onnx library wasn't checking correctly and was causing versions that did have the flag to not properly display it. This patch seeks to fix that issue.
---
> Onnx Static Initialization Bug

- recipes/harfbuzz/all/conandata.yml
- recipes/harfbuzz/config.yml
Specify library name and version:  **harfbuzz/8.0.1**
---
> harfbuzz: add version 8.0.1

- recipes/opencolorio/all/conanfile.py
Specify library name and version:  **opencolorio/2.1.0**
Require `imath/3.1.6` only when using `openexr/3.1.7` as `imath` is part of open exr 2.x.x versions.
Currently `openimageio/2.4.7.1` can not be built with cache cleared due to duplicated IMath includes.
We get tons of redefinition errors: 
```
~/.conan/data/openexr/2.5.4/_/_/package/be7c7ddd85063690fecab75a01562df151c61ad9/include/OpenEXR/half.h:676:1: error: redefinition of ‘bool Imath_3_1::half::isNan() const’
676 | half::isNan () const
| ^~~~
In file included from ~/.conan/data/openimageio/2.4.7.1/_/_/build/3b8626e7c738cbaa73a42a0d4cf6a182a761d03a/build_subfolder/include/OpenImageIO/half.h:12,
from ~/.conan/data/openimageio/2.4.7.1/_/_/build/3b8626e7c738cbaa73a42a0d4cf6a182a761d03a/build_subfolder/include/OpenImageIO/Imath.h:9, …
```
> Fix openimageio duplicate IMath includes

- recipes/clickhouse-cpp/all/conanfile.py
Don't remove it in case of static library.
fixes #18493
> clickhouse-cpp: respect fPIC option

- recipes/screen_capture_lite/all/conandata.yml
- recipes/screen_capture_lite/config.yml
Specify library name and version:  **screen_capture_lite/17.1.1327**
---
> screen_capture_lite: add version 17.1.1327

- recipes/sfml/all/conandata.yml
- recipes/sfml/all/conanfile.py
- recipes/sfml/all/patches/2.6.0-0007-use-cci-minimp3.patch
Specify library name and version:  **sfml/2.6.0**
This patch makes use cci's minimp3 instead of the internal minimp3.
---
> sfml: use cci's minimp3

- recipes/jwt-cpp/all/conanfile.py
jwt-cpp/0.6.0
This PR adds wider range of openssl libraries that can be used to build it
---
- [*] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [*] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [*] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> adds range of openssl libs to have wider compatibility

- recipes/libgeotiff/all/conanfile.py
Specify library name and version:  **libgeotiff/all**
---
> libgeotiff/all: bump deps

- recipes/libsystemd/all/conandata.yml
- recipes/libsystemd/all/conanfile.py
- recipes/libsystemd/config.yml
Specify library name and version:  **libsystemd/253.6**
libsystemd's meson build script had a missing dependency declaration to `libcrypt`.
Problem was issued [here](https://github.com/systemd/systemd/issues/28161) and released in version `253.6`.
The missing dependency is specially a problem when [cross-compiling the library](https://github.com/conan-io/conan-center-index/issues/15101).
I don't know whether there will be more backports to other major versions. If not, this could be provided to other versions via patches.
---
> [libsystemd] add 253.6, add dependency to libcrypt

- recipes/dice-template-library/all/CMakeLists.txt
- recipes/dice-template-library/all/conandata.yml
- recipes/dice-template-library/all/conanfile.py
- recipes/dice-template-library/all/test_package/CMakeLists.txt
- recipes/dice-template-library/all/test_package/test_package.cpp
- recipes/dice-template-library/config.yml
Specify library name and version:  **dice-template-library/***
Try to solve these issues.
- https://github.com/dice-group/dice-template-library/issues/18
- https://github.com/dice-group/dice-template-library/issues/7
---
> dice-template-library: add version 1.0.0

- recipes/structopt/all/conandata.yml
- recipes/structopt/all/conanfile.py
- recipes/structopt/all/test_package/CMakeLists.txt
- recipes/structopt/all/test_package/conanfile.py
- recipes/structopt/all/test_v1_package/CMakeLists.txt
- recipes/structopt/all/test_v1_package/conanfile.py
> structopt: migrate to Conan v2

- recipes/minizip-ng/all/conanfile.py
Specify library name and version:  **minizip-ng**
When using minizip with mz_compatibility=True, I met following error.
```
ERROR: Provide Conflict: Both 'minizip-ng/4.0.0' and 'minizip-ng/4.0.0' provide 'minizip'.
```
This PR tries to fix this error and other mz_compatibility issues.
---
> minizip-ng: fix duplicate provides with mz_compatibility=True, update dependencies

- recipes/libnghttp2/all/conandata.yml
- recipes/libnghttp2/config.yml
Specify library name and version:  **libnghttp2/1.55.1**
---
> libnghttp2: add version 1.55.1

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/1.2.0**
---
> meson: add version 1.2.0

- recipes/concurrencpp/all/conandata.yml
- recipes/concurrencpp/all/conanfile.py
- recipes/concurrencpp/config.yml
Specify library name and version:  **concurrentcpp/***
concurrentcpp/0.1.7 supports gcc 13+.
---
> concurrentcpp: add version 0.1.7

- recipes/cli11/all/conanfile.py
- recipes/cli11/all/test_package/CMakeLists.txt
Specify library name and version:  **cli11/***
Try to fix https://github.com/conan-io/conan-center-index/issues/18531.
---
> cli11: make bindirs and libdirs empty

- recipes/gegles-spdlog_setup/all/conanfile.py
Specify library name and version:  **spdlog_setup/1.1.0**
Just bump `spdlog` and `fmt` deps to the latest versions.
---
> spdlog_setup: bump dependencies

- .c3i/config_v2.yml
> [config] Update conan v2 to 2.0.8

- recipes/restinio/all/conanfile.py
Specify library name and version:  **restinio/0.6.18**
Bump `fmt`, `string-view-lite` and `boost` dependencies to latest
---
> restinio: bump dependencies

- recipes/qt/6.x.x/conanfile.py
Hopefully, conan V2 will pass this time
---
> qt/6.x.x: bump deps

- recipes/ccache/all/conandata.yml
- recipes/ccache/all/conanfile.py
- recipes/ccache/config.yml
Also update the dependencies
Specify library name and version:  **ccache/4.8.2**
---
> ccache: add version 4.8.2

- recipes/turtle/all/conanfile.py
Since turtle is header-only recipe, we should unset libdirs and bindirs as per https://github.com/conan-io/conan/issues/13702#issuecomment-1510507647
> turtle: fix lib/bindirs

- recipes/restinio/all/conandata.yml
- recipes/restinio/all/conanfile.py
- recipes/restinio/config.yml
Specify library name and version:  **restinio/0.6.18**
* bump standalone asio
* remove older versions as per guidelines [here](https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/sources_and_patches.md#removing-old-versions)
---
> restinio: bump standalone asio & remove older versions

- recipes/snappy/all/conanfile.py
Specify library name and version:  **snappy/\***
There is a similar PR in vcpkg
See https://github.com/conda-forge/snappy-feedstock/issues/24 and https://github.com/google/snappy/blob/2b63814b15a2aaae54b7943f0cd935892fae628f/CMakeLists.txt#L179
---
> snappy: add with_bmi2 and with_ssse3 options

- recipes/libcurl/all/conandata.yml
- recipes/libcurl/all/conanfile.py
- recipes/libcurl/config.yml
> libcurl: add version 8.2.0, update libnghttp2, remove older versions

- recipes/etl/all/conandata.yml
- recipes/etl/config.yml
Specify library name and version:  **etl/20.37.2**
---
> etl: add version 20.37.2, remove older versions

- recipes/aws-libfabric/all/conanfile.py
- recipes/aws-libfabric/all/test_package/CMakeLists.txt
- recipes/aws-libfabric/all/test_package/conanfile.py
- recipes/aws-libfabric/all/test_v1_package/CMakeLists.txt
- recipes/aws-libfabric/all/test_v1_package/conanfile.py
Specify library name and version:  **aws-libfabric/all**
---
> aws-libfabric: migrate to Conan v2

- recipes/xtr/all/conandata.yml
- recipes/xtr/config.yml
Specify library name and version:  **xtr/2.1.0**
Bump xtr to 2.1.0, I am the library author.
---
> xtr: bump to 2.1.0

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
Specify library name and version:  **imgui/***
---
> imgui: add version 1.89.8, 1.89.8-docking

- recipes/harfbuzz/all/conandata.yml
- recipes/harfbuzz/config.yml
Specify library name and version:  **harfbuzz/8.11**
---
> harfbuzz: add version 8.1.1

- docs/changelog.md
- ConanCenterIndex CI is now running Conan 2.0.9 (latest) and 1.60.2
- Jenkins server used to build packages is now running in a newer version
- When a build take many hours, now internal logs and treatment is better filtered.
---
> [docs] Add changelog 2023-Aug-04

- recipes/bimg/all/test_package/conanfile.py
Specify library name and version:  **bimg/cci.20230114**
The `cmake_layout` should be imported from CMake, other otherwise will have python import error.
Required by #16134 
Continues #19026
---
> [bimg] Fix imports for test package

- recipes/onetbb/all/conanfile.py
Specify library name and version:  **onetbb/2021.9.0**
Use feature https://github.com/conan-io/conan/issues/13809
Aligned with oneTBB https://github.com/oneapi-src/oneTBB/blob/master/CMakeLists.txt#L268-L269
---
> onetbb: use AnyNewerVersion cmake version policy

- recipes/dice-template-library/all/conandata.yml
Specify library name and version:  **dice-template-library/1.0.0**
For some reason the hash was wrong. Probably another hash algorithm was used to generate it. 
---
> Fix: sha256 sum of data for dice-template-library v1.0.0

- recipes/util-linux-libuuid/all/conanfile.py
- recipes/util-linux-libuuid/all/test_package/CMakeLists.txt
This is in line with what conan recipes seem to expect, which will minimise the number of patches required. LibUUID was chosen as the target name given this is what's used internally within cmake, but this isn't a public interface and so there is no common usage to take guidance from.
See discussion in original ticket adding `util-linux-libuuid` after merge: https://github.com/conan-io/conan-center-index/pull/17664#discussion_r1249000485
The following tickets are blocked until this change is merged:
* https://github.com/conan-io/conan-center-index/pull/18552
* https://github.com/conan-io/conan-center-index/pull/18553
* https://github.com/conan-io/conan-center-index/pull/18556
* https://github.com/conan-io/conan-center-index/pull/18557
Closes #18554
---
> [util-linux-libuuid] Change CMake target from LibUUID::LibUUID to libuuid::libuuid

- recipes/zookeeper-client-c/all/conandata.yml
closes https://github.com/conan-io/conan-center-index/issues/19098
---
> zookeeper-client-c: use stable url for tarball of source code

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/1.2.1**
---
> meson: add version 1.2.1

- recipes/azure-storage-cpp/all/conanfile.py
> [azure-storage-cpp] Use util-linux-libuuid instead of deprecated libuuid

- recipes/cppcommon/all/conanfile.py
> [cppcommon] Use util-linux-libuuid instead of deprecated libuuid

- recipes/czmq/all/conanfile.py
> [czmq] Use util-linux-libuuid instead of deprecated libuuid

- recipes/drogon/all/conanfile.py
> [drogon] Use util-linux-libuuid instead of deprecated libuuid

- recipes/fontconfig/all/conanfile.py
- recipes/fontconfig/meson/conanfile.py
> [fontconfig] Use util-linux-libuuid instead of deprecated libuuid

- recipes/stduuid/all/conanfile.py
Transition from deprecated `libuuid` recipe to `util-linux-libuuid`, which is actively maintained. See #17664 for discussion
The `libuuid` package uses a stale project. Use the active project instead to fix conflicts.
---
> [stduuid] Use util-linux-libuuid instead of deprecated libuuid

- recipes/onetbb/all/conandata.yml
- recipes/onetbb/all/conanfile.py
- recipes/onetbb/all/patches/pkg-search-module-use-imported-target.diff
Specify library name and version:  **onetbb/2021.9.0**
**Description:** This PR is submitted as a continuation of adding hwloc library. With adding hwloc as a dependency, TBB provides extra plugin library which provides abilities to detect information about system topology such as number of NUMA nodes, number of P / E cores on CPU.
**Details of implementation:**
- TBB does not support TBBBind library when TBB is built statically (just not implemented in TBB itself)
- TBB has extra cmake option `TBB_DISABLE_HWLOC_AUTOMATIC_SEARCH` to control whether HWLOC should be automatically found by `pkg-config`, but available only since 2021.4. Created patch to have an unified recipe without a lot of conditions which are version dependent.
- Before 2021 major release, TBB does not support HWLOC (no …
> [onetbb] added tbbbind (via hwloc) support

- recipes/fontconfig/meson/conanfile.py
The recent changes in `fontconfig` w.r.t to the libuuid dependency were introduced and then subsequently reversed - causing an interesting case where the recipe revision for the most recent commit still has the "earlier" timestamp for the same changes.
This PR touches the recipe minimally to ensure that a new recipe revision with a fresh timestamp is published.
> fontconfig: minimal change to ensure most recent rrev

- recipes/capnproto/all/conandata.yml
- recipes/capnproto/config.yml
Specify library name and version:  **capnproto/0.10.4**
Add the capnproto 0.10.4 minor to allow for using a c++20 compiler (https://github.com/capnproto/capnproto/issues/1622).
---
> Add capnproto/0.10.4

- recipes/gdal/config.yml
- recipes/gdal/post_3.5.0/conandata.yml
- recipes/gdal/post_3.5.0/patches/3.7.0/0-replace-find-package.patch
Specify library name and version:  **gdal/3.7.0**
---
> [gdal] add version 3.7.0

- recipes/cpuinfo/all/conandata.yml
- recipes/cpuinfo/all/conanfile.py
- recipes/cpuinfo/all/test_package/CMakeLists.txt
- recipes/cpuinfo/all/test_package/conanfile.py
- recipes/cpuinfo/all/test_v1_package/conanfile.py
- recipes/cpuinfo/config.yml
- Add 20230118 20220618 versions
- Refactor package_info and expose clog as a component. Require that component from cpuinfo only in the specific versions that required it
Specify library name and version:  **cpuinfo/cci.20230118, cpuinfo/cci.20220618,**
Obs: 
cpuinfo exposed `cpuinfo::clog` target and this was missing in the recipe. Other packages like `onnxruntime` were starting to depend on that : https://github.com/microsoft/onnxruntime/blob/2fd25de3600df5680eeb21b5ede9546e6731966a/cmake/onnxruntime_common.cmake#L197 
Also seems that after 20230118 version this 'component' has been merged into `cpuinfo` library.
---
> [cpuinfo] Add 20230118 20220618 versions

- recipes/mpfr/all/conanfile.py
Specify library name and version:  **mpfr/4.2.0**
When building with Conan 2.0, and `*/*:shared=True`, the `mpfr` executes a validation with autotools to check if is possible to use `gmp`. However, as `VirtualRunEnv` was not configured, the `LD_LIBRARY_PATH` was not present, resulting in failure when trying to run its test:
```
configure:4522: gcc -o conftest  -m64 -O3  -I/home/conan/.conan2/p/gmp0bfdd57764b0f/p/include -DNDEBUG -I/home/conan/.conan2/p/gmp0bfdd57764b0f/p/include  -L/home/conan/.conan2/p/gmp0bfdd57764b0f/p/lib -m64 -L/home/conan/.conan2/p/gmp0bfdd57764b0f/p/lib conftest.c  -lgmpx
x -lgmp -lm >&5
configure:4526: $? = 0
configure:4533: ./conftest
./conftest: error while loading shared libraries: libgmpxx.so.4: cannot open shared object file: No such file or directory …
```
> [mpfr] Fix when building shared library on Linux

- recipes/fast-dds/all/conanfile.py
Specify library name and version:  **fastdds**
We need to regenerate the fastdds binaries as per https://github.com/conan-io/conan/issues/14388, they have been built with different ``package_id`` relations to ``asio``, due to the historical evolution of asio recipe, and recently adding ``package_type = "header-library"``. This PR will create a new recipe revision with updated binaries.
Close https://github.com/conan-io/conan/issues/14388
> fix fastdds binaries

- recipes/fast-cdr/all/conandata.yml
- recipes/fast-cdr/all/conanfile.py
- recipes/fast-cdr/config.yml
Specify library name and version:  **fast-cdr/1.1.0**
New version, closes #19012. Needs newer CMake version than installed in Linux build image.
---
> fast-cdr: add version 1.1.0

- recipes/vulkan-loader/all/conandata.yml
- recipes/vulkan-loader/all/conanfile.py
- recipes/vulkan-loader/config.yml
**vulkan-loader**
vulkan-loader and vulkan-headers should be kept in sync otherwise packages that requiere both will have problems.
> [vulkan-loader] Bump version to 1.3.243.0

- recipes/cuda-samples/all/conandata.yml
- recipes/cuda-samples/all/conanfile.py
- recipes/cuda-samples/all/test_package/CMakeLists.txt
- recipes/cuda-samples/all/test_package/conanfile.py
- recipes/cuda-samples/all/test_package/test_package.cpp
- recipes/cuda-samples/config.yml
Adds `cuda-samples`: https://github.com/NVIDIA/cuda-samples
Only packages the header files under the `Common/` directory.
These are used by `libfreenect2` when CUDA is enabled, for example (see the [recent PR](https://github.com/conan-io/conan-center-index/pull/18834/files#diff-cb2819ba0ebbd5d06929b0bb8497ce9293f83af7c4532c2896f15cdffb629d46R93-R94)).
I'm not too happy about the size of the "sources" being downloaded vs what actually ends up packaged - 144 MB for just a small subset of the header files. I'm not aware of a good way to fetch a subset of a GitHub repo, though. I even gave downloading the files via a REST API a shot, but it was not much faster and was prone to failure due to rate limits.
---
> cuda-samples: add new package

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/***
daw_header_libraries is required by daw_utf_range and daw_json_link.
Both of them require latest version only.
---
> daw_header_libraries: add version 2.95.0, remove older versions

- recipes/capnproto/all/conandata.yml
- recipes/capnproto/all/conanfile.py
- recipes/capnproto/all/patches/0015-disable-tests-for-1.0.0.patch
- recipes/capnproto/config.yml
Specify library name and version:  **capnproto/1.0.0**
---
> capnproto: add version 1.0.0

- recipes/fast-dds/all/conandata.yml
- recipes/fast-dds/all/patches/2.11.1-0001-fix-find-asio-and-tinyxml2.patch
- recipes/fast-dds/config.yml
Specify library name and version:  **fast-dds/2.11.1**
Add latest version, previous version did not build in GCC 13.
---
> fast-dds: add version 2.11.1

- recipes/screen_capture_lite/all/conandata.yml
- recipes/screen_capture_lite/config.yml
Specify library name and version:  **screen_capture_lite/17.1.1369**
---
> screen_capture_lite: add version 17.1.1369

- recipes/r8brain-free-src/all/conandata.yml
- recipes/r8brain-free-src/config.yml
Specify library name and version:  **r8brain-free-src/6.4**
---
> r8brain-free-src: add version 6.4

- recipes/jwt-cpp/all/conanfile.py
jwt-cpp: fix OpenSSL range - the one that was last merged is not what we intend to have in Conan Center. 
An internal bug was has been raised to fix the bump dependencies bot to avoid this issue in the future.
> jwt-cpp: update version range for OpenSSL

- recipes/lz4/all/conandata.yml
- recipes/lz4/all/patches/0004-Added-namespace-declaration-for-xxhash-in-CMake.patch
Specify library name and version:  **lz4/1.9.4**
In the current release of lz4 it is using xxhash (internally, not as a dependency). This results in multiple definitions of the same symbol when using xxhash and lz4 in the same project. I have already created a merged PR on lz4 (https://github.com/lz4/lz4/pull/1258) that alters the CMakeLists.txt to prefix all xxhash functions within LZ4_ to resolve the naming conflict. I talked with the developers of lz4, and it's not intended to add xxhash as an external dependency, and the prefix/pseudo-namespace is the way to go.
This is a PR fixing this issue by applying a patch to CMakeLists.txt (I tested it locally on the current release tag).
fixes #19221 
---
> [package] lz4/1.9.4 : Bugfix / Patch to support lz4 and xxhash at the same time.

- recipes/autoconf/all/test_package/conanfile.py
- recipes/autoconf/all/test_v1_package/conanfile.py
Specify library name and version:  **autoconf/\***
This fixes `fatal error C1041: cannot open program database` when building test_package with Debug build type and msvc compiler. C3I doesn't build this configuration and marks it as duplicated, but our CI is not as smart as C3I :)
---
> autoconf: fix msvc debug build for test_package

- recipes/tinyxml/all/conanfile.py
Needed for #17347.
Including STL support in a C++ library by default should not be an issue, I assume.
> tinyxml: enable with_stl by default

- docs/changelog.md
- The C3I Jenkins captures and process many types of exceptions. This new hotfix will avoid invoking missing methods to properly log all of them.
- The Bump Dependencies is now restricted only to `semver`, `major.minor` and `cci.<DATE>` format.
- For a better logging, RREV (recipe-revision) has been included to the summary output.
> [docs] Add changelog 17-Aug-2023

- recipes/kdbindings/all/conandata.yml
- recipes/kdbindings/all/conanfile.py
- recipes/kdbindings/all/test_package/CMakeLists.txt
- recipes/kdbindings/all/test_package/conanfile.py
- recipes/kdbindings/all/test_package/main.cpp
- recipes/kdbindings/config.yml
**kdbindings/1.0.3**
KDBindings enables reactive programming & data binding in C++ From plain C++ you get:
- Signals + Slots.
- Properties templated on the contained type.
- Property bindings allowing reactive code to be written without having to do all the low-level, error prone plumbing by hand. Lazy evaluation of property bindings.
- No more broken bindings.
- Totally stand-alone "header-only" library.
I'm working for KDAB (the company behind this library). I have their support for adding and maintaining this library to conan center index.
---
> Added kdbindings/1.0.3

- recipes/etl/all/conanfile.py
- recipes/etl/all/test_package/CMakeLists.txt
- recipes/etl/all/test_v1_package/CMakeLists.txt
Add etl::etl library alias to follow the convention.
---
> Follow the convention and also provide etl::etl alias.

- recipes/nodejs/all/conandata.yml
- recipes/nodejs/config.yml
Specify library name and version:  **nodejs/16.20.2**
Adds the latest node.js 16 LTS version, 16.3.0 is more than 2 years old at this point.
---
> nodejs: add version 16.20.2

- recipes/arsenalgear/all/conanfile.py
Specify library name and version:  **arsenalgear/2.1.0**
Required by #16320
---
> [arsenalgear] Bump dependencies: Boost 1.82.0

- recipes/loguru/all/conanfile.py
Loguru expects 0 or 1, but the recipe would set "False"/"True", which C's preprocessor would always evaluate to false.
Specify library name and version:  **loguru/***
PR #14543 added loguru, but improperly sets its preprocessor options. It sets the strings "False" or "True" as preprocessor definition due to quirks with how options are embedded. C's preprocessor evaluates both to false, so essentially all options are always off.
This PR sets 0 or 1 instead, so options can actually be toggled.
---
> loguru: fix preprocessor definition values

- recipes/cpuinfo/all/conanfile.py
Specify library name and version:  **cpuinfo/** (all versions impacted)
A bug was introduced by this PR: https://github.com/conan-io/conan-center-index/pull/18164
It shall not require pthread when compiling for Android
See https://stackoverflow.com/questions/38666609/cant-find-lpthread-when-cross-compile-to-arm: "The android libc, bionic, provides built-in support for pthreads, so no additional linking (-lpthreads) is necessary."
---
> [cpuinfo] fix bug when compiling for Android

- recipes/yaclib/all/conanfile.py
- recipes/yaclib/all/test_v1_package/conanfile.py
Specify library name and version:  **yaclib/2022.12.20**
- Import `cmake_layout` from `cmake`, otherwise will raise a python import error
- Remove `Version` import as it's unused
- Use only legacy imports for test_v1_package
---
> [yaclib] Fix import for cmake_layout

- recipes/libpqxx/all/conandata.yml
- recipes/libpqxx/config.yml
Specify library name and version:  **libpqxx/7.8.1**
This release fixes a build bug in v7.8.0.
If v7.8.1 is supported, v7.8.0 is no longer needed.
---
> libpqxx: add version 7.8.1

- recipes/lyra/all/conanfile.py
Specify library name and version:  **lyra/1.6.1**
This PR removes the following warning (on macOS) as no libdirs are needed for a header only lib:
```
ld: warning: directory not found for option '-L/Users/gegles/.conan2/p/b/lyraec857ade44df1/p/lib'
```
This is a much smaller PR than my other one [here](https://github.com/conan-io/conan-center-index/pull/19280) where I do more cleaning up as well. Depending on which gets merged first, I'll either rebase or close the other.
---
> lyra: make sure libdirs is empty for this header-only library

- recipes/taocpp-json/all/conandata.yml
- recipes/taocpp-json/config.yml
Specify library name and version:  **taocpp-json/1.0.0-beta.14**
---
The only warning I saw is:
```
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.filenames' used in: taocpp-json/1.0.0-beta.14, taocpp-pegtl/3.2.7
WARN: deprecated:     'cpp_info.names' used in: taocpp-json/1.0.0-beta.14, taocpp-pegtl/3.2.7
```
shall I fix it?
> Bump Taocpp JSON to 1.0.0-beta.14

- recipes/fmt/all/conanfile.py
Specify library name and version:  **fmt/10.1.0**
This PR aims at avoiding the following warning when used in `header_only=True` mode:
```
ld: warning: directory not found for option '-L/Users/gegles/.conan2/p/fmt04167ccd841e1/p/lib'
```
The `libdirs = []` and `bindirs = []` should apply to the component in this situation
Now, when doing ` conan create --version 10.1.0 -o header_only=True all` the warning is gone.
---
> fmt: make sure libdirs is empty when header_only=True

- recipes/boost/all/conanfile.py
Specify library name and version:  **boost/1.83.0**
This PR removes the following warning (on macOS) when the library is used in header_only=True mode:
```
ld: warning: directory not found for option '-L/Users/gegles/.conan2/p/b/boost594a6a5d9c263/p/lib'
```
---
> boost: make sure libdirs is empty when header_only=True

- recipes/openssl/1.x.x/conanfile.py
- recipes/openssl/3.x.x/conanfile.py
openssl/1.x.x 
Added "socket" to system_libs for Neutrino
---
> openssl/1.x.x: Added socket to system_libs for Neutrino

- recipes/spdlog/all/conanfile.py
Specify library name and version:  **spdlog/1.12.0**
This PR removes the following warning (on macOS) when the library is used in `header_only=True` mode:
```
ld: warning: directory not found for option '-L/Users/gegles/.conan2/p/b/spdlo6818b9a6a2366/p/lib'
```
---
> spdlog: make sure libdirs is empty when header_only=True

- recipes/ogdf/all/conanfile.py
Specify library name and version:  **OGDF/2022.02**
This enables building with `shared=True` on Windows
---
> [OGDF] enable shared build on Windows

- recipes/pupnp/all/conanfile.py
`self.options[]` returns a `PackageOptions` object instead of a `PackageOption` one like attribute access or `.get_safe()` does.
> pupnp: fix invalid use of self.options[]

- recipes/date/all/conanfile.py
Specify library name and version:  **date/3.0.1**
This PR helps remove the following warning on macOS:
```
ld: warning: directory not found for option '-L/Users/gegles/.conan2/p/date512b8c2307f3f/p/lib'
```
---
> date: make sure libdirs is empty when `header-only=True`

- recipes/boost/all/conanfile.py
Specify library name and version:  **boost/1.83**
This PR helps remove the following warning on macOS when boost is used as header-only, but the `boost::boost` target is used in CMake as opposed to the `Boost::headers`:
```
ld: warning: directory not found for option '-L/Users/gegles/.conan2/p/boost3ea68282e5511/p/lib'
```
I faced this issue when using `restinio` that transitively brings in `boost` but internally uses the `boost::boost` CMake target.
---
> boost: make sure libdirs is empty with header-only=True and used via `boost::boost` target

- recipes/qt/6.x.x/conanfile.py
they are legacy from qt5, but never existed in qt6: https://github.com/qt/qtmultimedia/commit/805b10624ced9b97283e94594a5c7db4c10c63c4 https://github.com/qt/qtmultimedia/commit/98148969b112f82d2b49e77950ea5f6d8b37b8b2 https://github.com/qt/qtmultimedia/commit/aa441d63a1ed0843f4632da2d0a97a7b8bb24b43 https://github.com/qt/qtmultimedia/commit/f16dbe174cee73308cae2aae512fe837e07e0f55 https://github.com/qt/qtmultimedia/commit/58e74015c5239f269a1f0a59eabe43e92c47acd5
fixes https://github.com/conan-io/conan-center-index/issues/19146
---
> qt6: remove multimedia plugins

- recipes/aws-c-s3/all/conandata.yml
- recipes/aws-c-s3/all/conanfile.py
- recipes/aws-c-s3/all/test_v1_package/CMakeLists.txt
- recipes/aws-c-s3/config.yml
see https://github.com/awslabs/aws-c-s3/blob/v0.2.8/include/aws/s3/exports.h
---
> aws-c-s3: add missing interface definition if shared + modernize more for conan v2

- recipes/nasm/all/conanfile.py
Specify library name and version:  **nasm/2.15.2**
Related to https://github.com/conan-io/conan-center-index/pull/18016
The `nasm` Conan package only stores binaries but forget to configure them properly to packages that will use as a tool requirement.
CMake will try use the system nasm and ignore that one provided by the package, in case not configured. Plus, `AS` variable is used for assembler.
This PR fixes a situation found when building `intel-ipsec-mb` where I needed to pass:
`tc.variables["CMAKE_ASM_NASM_COMPILER"] = os.path.join(self.dependencies.direct_build["nasm"].package_folder, "bin", "nasm")`
So I'm able to use nasm from Conan. Otherwise, CMake (using CMakeToolchain + CMakeDeps) will consume from system.
---
> [nasm] Configure assembler compiler by cpp_info

- recipes/utfcpp/all/conanfile.py
- recipes/utfcpp/all/test_package/CMakeLists.txt
Specify library name and version:  **utfcpp/all**
Recipe was missing target alias utf8::cpp
https://github.com/nemtrif/utfcpp/blob/dbb2423248dd5b97acd4125a29bdfbf6b36cd7b1/utf8cppConfig.cmake.in#L6C1-L6C37
https://github.com/nemtrif/utfcpp/blob/dbb2423248dd5b97acd4125a29bdfbf6b36cd7b1/CMakeLists.txt#L19C1-L19C37
---
> utfcpp: add utf8::cpp alias

- recipes/expected-lite/all/conanfile.py
Clean up and removed test_v1_package and v1-specific package_info code
Specify library name and version:  **expected-lite/0.6.3**
on macOS, before this PR it would generate the following warning:
```
ld: warning: directory not found for option '-L/Users/gegles/.conan2/p/b/expeced3ee1a13d86f/p/lib'
```
---
> expected-lite: make sure libdirs is empty for this header-only library

- recipes/gperftools/all/conandata.yml
- recipes/gperftools/config.yml
Specify library name and version:  **gperftools/2.12.0**
---
> gperftools: add version 2.12.0

- recipes/xmlsec/all/conanfile.py
- recipes/xmlsec/all/test_package/conanfile.py
xmlsec: libxml2 dependency bump to latest version (2.11.4)
---
> xmlsec: bump libxml2 to 2.11.4

- recipes/spdlog/all/conanfile.py
Specify library name and version:  **spdlog/***
In spdlog/1.11.0 with fmt/10.1.0, there is a compilation error:
```
~/.conan2/p/b/spdloace6fef9ea4cd/p/include/spdlog/logger.h:374:75: error: cannot bind non-const lvalue reference of type ‘int&’ to an rvalue of type ‘int’
374 |             fmt::vformat_to(fmt::appender(buf), fmt, fmt::make_format_args(std::forward<Args>(args)...));
|                                                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
So I decided to update to fmt/10.1.0 for spdlog/1.12.0 only.
It seems to be reasonable because spdlog officialy supports fmt/10.x.x since 1.12.0.
---
> spdlog: update fmt/10.1.0

- recipes/capnproto/all/conandata.yml
- recipes/capnproto/config.yml
Specify library name and version:  **capnproto/1.0.1**
---
> capnproto: add version 1.0.1

- recipes/scippp/all/conanfile.py
Specify library name and version:  **scippp/1.0.2**
Removes obsolete `exports_sources`, see https://github.com/conan-io/conan-center-index/pull/19120#discussion_r1305458497
---
> [scippp] Remove obsolete exports_sources from recipe

- recipes/arrow/all/conanfile.py
Solve potential version conflict on boost when requiring thrift as well. See https://github.com/conan-io/conan/issues/14587
---
> arrow: bump version of boost dependency

- recipes/zlib-ng/all/conanfile.py
Specify library name and version:  **zlib-ng/***
Try to close https://github.com/conan-io/conan-center-index/issues/19363.
The upstream default value of `WITH_OPTIM` is true at least since 2.0.0.
---
> zlib-ng: fix `with_optim` default value

- recipes/onetbb/all/conanfile.py
Specify library name and version:  **onetbb/2021.10.0**
**Reason:** without `pkgconf` TBB cannot find `hwloc` dependency 
---
> onetbb: added pkgconf build dependency to find hwloc

- recipes/sqlpp11/all/conanfile.py
`from conan import Version` was illegal but allowed for some reason. Now it breaks in conan 2.0.10
---
> sqlpp11: fix import of Version

- recipes/lefticus-tools/all/conanfile.py
fix illegal import which breaks in conan 2.0.10
---
> lefticus-tools: fix import of Version + add a layout

- recipes/aws-crt-cpp/all/conanfile.py
see https://github.com/awslabs/aws-crt-cpp/blob/v0.19.9/include/aws/crt/Exports.h
closes https://github.com/conan-io/conan-center-index/issues/17382
---
> aws-crt-cpp: add missing interface definition if shared

- recipes/drogon/all/conandata.yml
- recipes/drogon/all/conanfile.py
- recipes/drogon/all/patches/1.8.6-0002-find-cci-packages.patch
- recipes/drogon/config.yml
> drogon: add version 1.8.6, fix compilation error on 1.8.5 with yaml-cpp

- recipes/fruit/all/conanfile.py
- recipes/fruit/config.yml
`from conan import Version` doesn't work anymore since conan 2.0.10 (I didn't even know that it was possible)
---
> fruit: fix import of Version + add package_type + bump boost + remove deprecated option use_boost

- recipes/libcap/all/conandata.yml
- recipes/libcap/config.yml
Specify library name and version:  **libcap/2.69**
This version contains only the minor fixes.
---
> libcap/2.69: Bump version

- recipes/onetbb/all/conandata.yml
- recipes/onetbb/config.yml
Specify library name and version:  **onetbb/2021.10.0**
---
> onetbb: added 2021.10.0 version

- recipes/libnice/all/conanfile.py
- recipes/libnice/all/test_package/conanfile.py
- recipes/libnice/all/test_v1_package/conanfile.py
Specify library name and version:  **libnice/0.1.21**
- The `cmake_layout` should be imported from `cmake`, not from `layout` otherwise will have a python import error
- Bump dependencies version
- Update test_v1_package to use only Conan legacy imports
- The header `nice/agent.h` exposes `glib-object.h` header, so we need transitive_headers
- Needs transitive libs due `ld: CMakeFiles/example.dir/src/example.c.o: undefined reference to symbol 'g_object_unref'`
---
> [libnice] Fix cmake_layout import error

- docs/changelog.md
This new release fixes the current problem with Windows environment, by improving the path separator used in Windows paths when running CI workspace. 
---
> Add changelog 01 Sep 2023

- .c3i/config_v2.yml
Following Conan 2.x migration schedule. From now, all PRs should pass by Conan 2.x CI build.
More information in https://github.com/conan-io/conan-center-index/discussions/19104
Most of recipes are ported now to Conan 2.x, and the recommendation for those that are still missing is pinging us in the PR, so we can help to migrate it too.
This PR only updates the feedback message, not the CI behavior. The behavior should be done in a separated PR.
/cc @jcar87 @danimtb @RubenRBS 
---
> [docs] Change conan v2 feedback message

- docs/developing_recipes_locally.md
To support users to know what should be used when reproducing CCI builds, it would be better having the relation of docker images used by CCI. This PR adds a new section explaining the configuration behind Jenkins when fetching Docker images used to build official packages.
closes #19173
/cc @klausholstjacobsen
---
> [docs] Add section about Docker images used by CCI

- recipes/earcut/all/conanfile.py
- recipes/earcut/all/test_package/CMakeLists.txt
Specify library name and version:  **earcut/\***
See [earcut CMakeLists](https://github.com/mapbox/earcut.hpp/blob/a299ad92b93b03aeab5d95195bb34bfc8f0b3263/CMakeLists.txt#L143)
---
> earcut: fix target name

- docs/adding_packages/dependencies.md
This PR adds `zlib` and `libcurl` as part of the allowed ones to be declared with version ranges in recipe's dependencies.
The CCI maintainers will create the necessary PRs to change the requirements so as to not miss any :)
Zlib: 
For libcurl: https://curl.se/libcurl/abi.html
We're also discussing if allowing `sqlite` too
> [docs] Add `zlib` and `libcurl` to the list of allowed version ranges

- recipes/tracy/all/conanfile.py
Specify library name and version:  **tracy/0.9**
The option "only_ipv" is typo. The right is "only_ipv4".
https://github.com/wolfpld/tracy/blob/f15de19fda5f03f97ea0f779c2c846228350a640/CMakeLists.txt#L72
---
> fix TRACY_ONLY_IPV4 not work and add new option

- recipes/autoconf/all/conanfile.py
same rational than https://github.com/conan-io/conan-center-index/pull/19497#issue-1873328386
---
> autoconf: less verbose package_info()

- recipes/octo-encryption-cpp/all/conandata.yml
- recipes/octo-encryption-cpp/all/conanfile.py
- recipes/octo-encryption-cpp/all/test_package/CMakeLists.txt
- recipes/octo-encryption-cpp/all/test_package/conanfile.py
Specify library name and version:  **octo-encryption-cpp/***
---
> octo-encryption-cpp: support conan v2, add package_type, relax openssl and cmake versions

- recipes/freetype/all/conanfile.py
Version range is not allowed yet for libpng. Version range for zlib is extended.
---
> freetype: bump brotli, restore fixed version of libpng, and proper version range for zlib

- recipes/gdk-pixbuf/all/conanfile.py
> gdk-pixbuf: bump glib

- recipes/mpc/all/conandata.yml
- recipes/mpc/all/conanfile.py
- recipes/mpc/all/test_package/CMakeLists.txt
- recipes/mpc/all/test_package/conanfile.py
- recipes/mpc/config.yml
Specify library name and version:  **mpc/***
The old homepage is now 404.
---
> mpc: add version 1.3.1, update dependencies, fix homepage

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
Specify library name and version:  **imgui/***
---
> imgui: add version 1.89.9/1.89.9-docking

- recipes/xtensor/all/conanfile.py
Specify library name and version:  **xtensor/***
I checked this PR with `tbb=True` in local environment.
---
> xtensor: update dependencies

- recipes/arrow/all/conanfile.py
see https://github.com/conan-io/conan-center-index/pull/19462#issuecomment-1699680668
---
> arrow: do not add build requires to cmake before arrow 13.0.0

- recipes/platform.hashing/all/conanfile.py
Specify library name and version:  **platform.hashing/***
---
> platform.hashing: update cpu_features/0.9.0

- recipes/pcre2/all/conanfile.py
> pcre2: use version range for zlib + add package_type

- recipes/cgal/all/conanfile.py
Specify library name and version:  **cgal/5.6**
In a private discussion, a user of the `cgal` package pointed out the lack of the CMake variable `CGAL_USE_GMP`, that they want to use in the downstream project https://bitbucket.org/taucgl/cgal-python-bindings
The upstream CGAL CMake scripts define that variable, as well as `CGAL_USE_MPFR`, when CGAL is configured with GMP, but the Conan package `cgal` does not. This pull-request fixes that.
---
> cgal: add CMake variable CGAL_USE_GMP for compatibility

- recipes/vectorclass/all/conanfile.py
- recipes/vectorclass/all/test_v1_package/CMakeLists.txt
- package_type is static-library (can be checked in our CMakeLists)
- use self.compiler/self.settings in validate() instead of self.info.compiler/self.info.settings. Since we don't need anymore a feature of 1.51.1 (get_safe in self.info), required_conan_version is decreased to 1.50.0
- add msvc to _compilers_minimum_version()
- simplify CMakeLists of test_v1_package
---
> vectorclass: add package type & modernize a little bit more

- docs/package_templates/header_only/all/conanfile.py
Version suggested for compiler=msvc is incorrect and fixed in this PR.
It's worth noting that several recipes have incorrect "msvc versions":
- boost-leaf
- cprocessing (https://github.com/conan-io/conan-center-index/pull/19923)
- cub (https://github.com/conan-io/conan-center-index/pull/19922)
- gurkenlaeufer (https://github.com/conan-io/conan-center-index/pull/19919)
- imutils-cpp
- libinterpolate (https://github.com/conan-io/conan-center-index/pull/19918)
- namedtype (https://github.com/conan-io/conan-center-index/pull/19915)
- octo-logger-cpp (https://github.com/conan-io/conan-center-index/pull/19883)
- octo-wildcardmatching-cpp (https://github.com/conan-io/conan-center-index/pull/19884)
- qcoro
- rpclib (https://github.com/conan-io/conan-center-index/pull/19916)
- vir-simd …
> [doc] fix msvc version in header-only template

- recipes/fmi2/all/conandata.yml
- recipes/fmi2/all/conanfile.py
- recipes/fmi2/all/test_package/CMakeLists.txt
- recipes/fmi2/all/test_package/conanfile.py
- recipes/fmi2/all/test_package/test_package.cpp
- recipes/fmi2/config.yml
Specify library name and version:  **fmi2/2.0.4**
This adds major version 2 of fmi from https://fmi-standard.org/, where the rationale is that fmi v1, v2, v3 can be required at the same time in downstream dependencies. A related PR for fmi1 is #19833. 
This is a dependency of a new package to be added: fmilibrary
---
> fmi2: add new recipe

- recipes/vc/all/conanfile.py
- recipes/vc/all/test_v1_package/CMakeLists.txt
- package_type is static-library
- use self.settings in validate() instead of self.info.settings. Since we don't need anymore a feature of 1.51.1 (get_safe in self.info), required_conan_version is decreased to 1.50.0
- cleanup topics
- simplify CMakeLists of test_v1_package
---
> vc: add package_type + modernize a little bit more

- recipes/sdbus-cpp/all/conandata.yml
In one of the previous pull requests I noticed the following warnings:
```
Schema outlined in https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conandata_yml_format.md#patches-fields is not followed.
found arbitrary text in 
patch_type: backport
```
This is because "backport" is not a valid patch_type anymore. The closest type the [documentation](https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conandata_yml_format.md#patches-fields) provides is "bugfix". Technically, it's really a bugfix to the build files.
---
> sdbus-cpp/all: Fix patch_types

- recipes/libsystemd/all/conanfile.py
Specify library name and version:  **libsystemd/all**
This PR is just a little cleanup. The original warning:
```
Lint changed conanfile.py (v2 migration)
Using open without explicitly specifying an encoding
```
---
> libsystemd/all: Fix v2 migration linter warnings

- recipes/lely-core/all/conanfile.py
- libtool is required in build requirements, because autoreconf is called in build() and autotools may not be installed on build machine
- fix pkg_config_name of each component
- cleanup recipe:
- remove export_conandata_patches() & apply_conandata_patches() since there is no patch
- remove fix_apple_shared_install_name() since apple OS is not supported
- sort methods by order of execution
---
> lely-core: add missing build requirements + cleanup recipe

- recipes/octo-logger-cpp/all/conanfile.py
- msvc min version is 192, not 1923...
- don't use self.info in validate()
- sort methods by order of execution
- fix msvc runtime check
- ~remove hardcoded properties in package_info() since this library doesn't export CMake targets upstream, nor pkgconfig file.~ => kept to not break other octo* libs, but it's a lie. @ofiriluz could you properly export your targets in a CMake config file please (in upstream CMakeLists)?
---
> octo-logger-cpp: fix msvc min version & few minor fixes

- recipes/octo-wildcardmatching-cpp/all/conanfile.py
- recipes/octo-wildcardmatching-cpp/all/test_package/CMakeLists.txt
- recipes/octo-wildcardmatching-cpp/all/test_package/conanfile.py
- fix msvc min version
- don't use self.info in validate()
- use tool_requires instead of legacy build_requires
- remove pkgconf properties in package_info() since upstream doesn't create pkgconfig file (I would have removed cmake targets also but upstream seems to rely on these names even though it doesn't export CMake targets in its CMakeLists /cc @ofiriluz)
---
> octo-wildcardmatching-cpp: fix several issues and modernize

- recipes/hdrhistogram-c/all/conanfile.py
> Bump hdrhistogram-c's zlib requirement to [>=1.2.11 <2] range

- recipes/openvino/all/conandata.yml
- recipes/openvino/all/conanfile.py
- recipes/openvino/all/patches/2023.1.0/0001-cpu-plugin-compilation-c++17.patch
- recipes/openvino/all/patches/2023.1.0/0002-core-compilation-c++17.patch
- recipes/openvino/all/patches/2023.1.0/0003-fixed-gpu-with-onednn-build.patch
- recipes/openvino/all/test_package/CMakeLists.txt
- recipes/openvino/all/test_package/conanfile.py
- recipes/openvino/all/test_package/test_package.cpp
- recipes/openvino/config.yml
Specify library name and version:  **openvino/2023.1.0**
Closes https://github.com/conan-io/conan-center-index/issues/7277
---
> openvino: add 2023.1.0 version

- recipes/zint/all/conanfile.py
- recipes/zint/all/test_package/CMakeLists.txt
- recipes/zint/all/test_package/conanfile.py
- recipes/zint/all/test_v1_package/CMakeLists.txt
- recipes/zint/all/test_v1_package/conanfile.py
- modernize more (use rm_safe)
- fix test package for conan v2 client (legacy self.options["zint"].with_qt and new self.dependencies can't be used in test(), therefore we use the know trick with ctest)
- bump libpng & qt
- use version range for zlib
---
> zint: add package_type + fix test package for conan v2 + use version range for zlib

- docs/changelog.md
- When a PR fails due missing dependencies, the CI should mark the PR with the label `Missing dependencies`. It should be used not only filter those PRs, but also to be improved in the future with other CCCI features.
- Some internal CI jobs were executed daily, but cost +10h be executed each, impacting directly Jenkins working queue. We re-scheduled them to be executed only during weekends.
- When Conan 2.x was introduced in CCI, there was a regression test the be sure once a recipe was working with Conan 2.x, it should not fail in a next PR. This feature has been removed, because any new PR should now pass by both Conan 1.x and 2.x as mandatory
- The epochs feature, a configuration to avoid mixing old and new configurations when builds, is now being deprecated. This is the first step. …
> [docs] Add changelog September, 25 2023

- recipes/tcl/all/conanfile.py
- relocatable shared lib on macOS (see https://github.com/conan-io/conan-center-index/pull/16745#issuecomment-1722299372)
- use version range for zlib
- cleanup topics
- less verbose package_info()
---
> tcl: relocatable shared libs on macos + use version range for zlib

- recipes/fmi3/all/conandata.yml
- recipes/fmi3/all/conanfile.py
- recipes/fmi3/all/test_package/CMakeLists.txt
- recipes/fmi3/all/test_package/conanfile.py
- recipes/fmi3/all/test_package/test_package.cpp
- recipes/fmi3/config.yml
Specify library name and version:  **fmi3/3.0.1**
This adds major version 3 of fmi from https://fmi-standard.org/, where the rationale is that fmi v1, v2, v3 can be required at the same time in downstream dependencies. There are related PRs for fmi1 #19833 and fmi2 #19834
This is a dependency of a new package to be added: fmilibrary
---
> fmi3: new package

- recipes/yyjson/all/conanfile.py
Specify library name and version:  **yyjson/***
I missed new option for 0.8.0 in https://github.com/conan-io/conan-center-index/pull/19885
---
> yyjson: add with_utf8_validation for yyjson>=0.8.0

- recipes/armadillo/all/conandata.yml
- recipes/armadillo/all/conanfile.py
- recipes/armadillo/all/patches/0004-Guard-dependency-discovery-12.6.x.patch
- recipes/armadillo/config.yml
Specify library name and version:  **armadillo/12.6.4**
Add version 12.6.4 of armadillo. The patch file here makes the same changes as previous patches, but added to account for differences in the upstream CMakeLists.txt that prevents existing patch files from being applied.
---
> [armadillo] Add version 12.6.4

- recipes/stringzilla/all/conandata.yml
- recipes/stringzilla/config.yml
Specify library name and version:  **stringzilla/1.2.2**
---
> stringzilla: add version 1.2.2

- recipes/cgif/all/conanfile.py
Without this bump, it fails during configuration with apple-clang 15:
```
../src/meson.build:1:0: ERROR: Unable to detect linker for compiler `clang -Wl,--version -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64`
stdout:
stderr: ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I guess that all meson based recipes are affected and will need a bump (version range for meson would help).
---
> cgif: bump meson

- recipes/inih/all/conanfile.py
> inih: bump meson

- recipes/libepoxy/all/conanfile.py
> libepoxy: bump meson

- recipes/websocketpp/all/conanfile.py
Specify library name and version:  **websocketpp/any**
---
> [websocketpp] Bump zlib requirement to [>=1.2.11 <2] range

- recipes/libheif/all/conandata.yml
- recipes/libheif/all/patches/0001-cmake_1.16.2.patch
- recipes/libheif/all/patches/0002-plugins_cmake_1.16.2.patch
Specify library name and version:  **libheif/1.16.2**
libheif fail to find libde265 when with_libde265 is True.
<details><summary>before fix</summary>
➜  ~ conan install libheif/1.16.2@_/_ -pr:b default -pr:h windows  --build libheif
Configuration (profile_host):
[settings]
arch=x86
arch_build=x86_64
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
libheif/1.16.2: Not found in local cache, looking in remotes...
libheif/1.16.2: Trying with 'conan-local'...
libheif/1.16.2: Trying with …
> libheif: fix dependencies cannot be found

- recipes/libpsl/all/conanfile.py
Same issue than https://github.com/conan-io/conan-center-index/pull/19968#issue-1903862552 with apple-clang 15. Upgrading meson helps.
And I take advantage of this PR to bump icu & pkgconf.
---
> libpsl: bump icu, meson & pkgconf

- recipes/rapidcsv/all/conandata.yml
- recipes/rapidcsv/config.yml
Specify library name and version:  **rapidcsv/8.80**
---
> rapidcsv: add version 8.80

- linter/conandata_yaml_linter.py
base_path is necessary in some cases (eg qt) where upstream patches apply to only a sub-directory of the sources. This happens when the sources are an aggregation of several repositories. cf https://github.com/conan-io/conan-center-index/pull/18376/files
the presence of base_path is an indirect consequence of explicitly setting the `destination` argument  of the `get` function,  so a better diagnostic would be to detect these.
---
> yaml linter: remove warning about base_path

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/1.2.2**
---
> meson: add version 1.2.2

- recipes/7bitconf/all/conandata.yml
- recipes/7bitconf/all/conanfile.py
- recipes/7bitconf/config.yml
Specify library name and version:  7bitconf /1.1.0
7bitconf add new 1.1.0 version and bump tapcpp json lib to 1.0.0-beta.14
---
> add 7bitconf 1.1.0 version

- recipes/platform.converters/all/conanfile.py
- Avoid to display these noisy warnings in case of "unknown" compilers, can't image someone with hundreds recipes like this
- Add min version of "msvc"
- fix required_conan_version, 1.50.0 is sufficient
---
> platform.converters: improve compiler versions checks for msvc and cleanup a little bit

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  **cmake/binary**
---
> cmake/binary: add version 3.27.6 & 3.26.5, remove older versions

- recipes/libzippp/all/conandata.yml
- recipes/libzippp/config.yml
Specify library name and version:  **libzippp/7.0-1.10-1**
---
> libzippp: add version 7.0-1.10.1

- recipes/highs/all/conandata.yml
- recipes/highs/config.yml
Specify library name and version:  **highs/1.6.0**
---
> [highs] bump version to 1.6.0

- recipes/xlsxio/all/conanfile.py
- relocatable shared lib on macOS by injecting CMAKE_POLICY_DEFAULT_CMP0042 NEW (cmake_minimum_required of upstream is super old: 2.6 !)
- remove VirtualBuildEnv, it's useless here, there is no build requirements
- no cmake_find_mode both, there is no Find module file upstream, only a CMake config file
- no explicit global pc file, there is none upstream, only pc files per component
---
> xlsxio: relocatable shared libs on macOS + cleanup recipe a little bit

- recipes/shapelib/all/conandata.yml
- recipes/shapelib/all/conanfile.py
- recipes/shapelib/all/patches/0003-relocatable-shared-macos.patch
also remove `CMAKE_POLICY_DEFAULT_CMP0077` trick (and increase `required_conan_version` to 1.54.0 since it's a workaround for a bug fixed in 1.54.0)
---
> shapelib: relocatable shared lib on macOS + add package_type

- recipes/clickhouse-cpp/all/conandata.yml
- recipes/clickhouse-cpp/config.yml
Specify library name and version:  **clickhouse-cpp/2.5.1**
---
> clickhouse-cpp: add version 2.5.1

- .c3i/config_v1.yml
- .c3i/config_v2.yml
As we are deprecating the usage of epochs, in the latest deployment we introduced the change to only use the configuration of the latest epoch, so we can remove the other ones at this point.
> [config] Remove old profile configurations

- recipes/bitserializer/all/conandata.yml
- recipes/bitserializer/all/conanfile.py
- recipes/bitserializer/config.yml
Specify library name and version:  **BitSerializer/0.65**
- Add new version 0.65
- Fix build when option `with_rapidyaml=False`
- Change references to new home of library (I'm author)
---
> [BitSerializer] Add new version 0.65, migrate repository to GitHub

- recipes/fontconfig/meson/conanfile.py
Specify library name and version:  **fontconfig/***
---
> fontconfig/meson: bump deps 

- recipes/android-ndk/all/conandata.yml
- recipes/android-ndk/config.yml
Specify library name and version:  **android-ndk/r26**
This adds the new r26 LTS.
---
> android-ndk: add r26

- recipes/armadillo/all/conanfile.py
For armadillo to wrap other libraries, these other libraries must be either statically compiled into the armadillo binary or dynamically linked to by libarmadillo. This is not possible when armadillo is a static library itself, without doing some unusual modification of the armadillo archive.
This change ensures that armadillo is built as a shared library when use_wrapper=True, which is the only configuration that would enable libarmadillo to be used this way.
For wider context for what this feature should do, see the [armadillo FAQ](https://arma.sourceforge.net/faq.html) and read my initial discussion of the problem in #7840. 
Closes #7840
---
> [armadillo] Prevent static builds when use_wrapper=True

- recipes/xkbcommon/all/conanfile.py
> xkbcommon/all: bump deps

- recipes/libevdev/all/conandata.yml
- recipes/libevdev/all/conanfile.py
- recipes/libevdev/all/test_package/conanfile.py
- recipes/libevdev/all/test_package/meson.build
- recipes/libevdev/all/test_package/test_package.c
- recipes/libevdev/config.yml
Specify library name and version:  **libevdev/1.13.1**
The libevdev library is required to make a libinput package.
---
> libevdev: Add recipe

- recipes/playrho/all/conandata.yml
- recipes/playrho/all/conanfile.py
follow up https://github.com/conan-io/conan-center-index/pull/18755#issuecomment-1745725479
- remove CMakeDeps, there is not dependency
- less verbose validate() for unknown compilers
- remove unecessary move of DLL files (they are already installed in bin folder by CMake, see https://github.com/conan-io/conan-center-index/pull/18755#issuecomment-1745725479)
---
> playrho: cleanup recipe in order to remove unnecessay/misleading logic

- recipes/qdbm/all/CMakeLists.txt
- recipes/qdbm/all/conanfile.py
The copying of DLLs in `package()` can be avoided.
Related to #20331.
> qdbm: fix install() in CMakeLists.txt

- recipes/uchardet/all/conanfile.py
The copying of DLLs in `package()` can be avoided.
Related to #20331.
> uchardet: fix unnecessary copying of DLLs

- recipes/libcurl/all/conandata.yml
- recipes/libcurl/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/20154
I've also changed from .tar.gz to .tar.xz since archives are smaller.
---
> libcurl: add GitHub mirror & prefer .tar.xz

- recipes/nanodbc/all/conandata.yml
- recipes/nanodbc/all/conanfile.py
- recipes/nanodbc/all/test_package/CMakeLists.txt
- recipes/nanodbc/all/test_package/conanfile.py
- recipes/nanodbc/config.yml
- disable warnings as errors (otherwise it fails with apple-clang 15:
```
/Users/spaceim/.conan2/p/b/nanodb0f0d557a98e9/b/src/nanodbc/nanodbc.cpp:263:25: error: 'char_traits<unsigned char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
```
- add required_conan_version
- bump boost & odbc
- don't raise for version > 2.14.0 if apple-clang
- explicit CMake names since upstream export nanodbc::nanodbc target
- sort version by desc order
---
> nanodbc: no warnings as errors + bump deps + don't raise if apple-clang and nanodbc > 2.14.0

- recipes/libliftoff/all/conandata.yml
- recipes/libliftoff/all/conanfile.py
- recipes/libliftoff/all/test_package/conanfile.py
- recipes/libliftoff/all/test_package/meson.build
- recipes/libliftoff/all/test_package/test_package.c
- recipes/libliftoff/config.yml
Specify library name and version:  **libliftoff/0.4.1**
libliftoff is a lightweight KMS plane library.
It is required to create a `wlroots` Conan package.
---
> libliftoff: Add recipe

- recipes/pkgconf/all/conanfile.py
Printing env vars in `package_info()` is useless (why not printing other informations like lib name etc for example? It's not the job of the recipe to print these informations, they are available through other way provided by conan) and can be very verbose during conan install because this method can be called multiple consecutive times (I have a conanfile where it's called 13 consecutive times for pkgconf/1.9.3 and 7 times for pkgconf/1.9.5...).
---
> pkgconf: less verbose package_info() + bump meson

- recipes/gdbm/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/20002
---
> gdbm: Inject `-headerpad_max_install_names` to ensure that `install_name_tool` can succeed on Apple

- recipes/at-spi2-core/config.yml
- recipes/at-spi2-core/new/conandata.yml
- recipes/at-spi2-core/new/conanfile.py
- recipes/at-spi2-core/new/test_package/conanfile.py
- recipes/at-spi2-core/new/test_package/meson.build
- recipes/at-spi2-core/new/test_package/test_package.c
Specify library name and version:  **at-spi2-core/***
---
> at-spi2-core: enable non-linux

- recipes/serial/all/conanfile.py
> serial: better way to set install_name to `@rpath` in shared lib macOS

- recipes/mpfr/all/conanfile.py
- recipes/mpfr/all/test_package/CMakeLists.txt
- recipes/mpfr/all/test_package/conanfile.py
- recipes/mpfr/all/test_v1_package/CMakeLists.txt
closes https://github.com/conan-io/conan-center-index/issues/20366
- Install COPYING.LESSER instead of COPYING since mpfr is LGPL (see https://github.com/conan-io/conan-center-index/issues/20366)
- explicit pkg_config_name since there is a pkgconfig file upstream
- use export_conandata_patches()
- call VirtualBuildEnv since there might be build requirements
- do not add -FS is msvc < 180
- modernize test package & test v1 package a little bit
---
> mpfr: package correct LGPL license + few minor fixes

- recipes/usockets/all/conanfile.py
- do not use self.output.warn since it doesn't exist in conan v2
- test `self.dependencies["wolfssl"].options.opensslextra` instead of `self.options["wolfssl"].opensslextra`
- add VirtualBuildEnv in autotools branch since there are build requirements if build machine is windows
- more robust injection of libuv include dirs in autotools + msvc branch
---
> usockets: several fixes for conan v2

- recipes/mariadb-connector-c/all/conanfile.py
Specify library name and version:  **mariadb-connector-c/all**
---
> mariadb-connector-c/all: bump libcurl

- docs/changelog.md
1) When a having a version conflict as error in a PR, it will be labeled by CCI. This feature enables a better way to filter those PRs that are blocked due a conflict and need more attention.
2) When C3I Jenkins service is under maintenance, the CI bot shows a default message warning about the current state. This new feature enables Conan team to improve the message with a short section about the motivation of the out-of-service. It does not replace status.conan.io
3) Improved the code that promotes merged packages to Conan Center, right after be in the master branch. It reduced the execution to only few minutes, about 60%.
4) When Conan 2. was introduced in CCI, there was an internal step to check if the recipe could be exported with Conan 2.x, validating if was Conan 2.x compatible. …
> [changelog] New C3I Release: 2023-Oct-06

- recipes/mbits-mstch/all/conanfile.py
Specify library name and version:  **mbits-mstch/1.0.4**
This is a refinement of the recipe as it works also on GCC 10 (which is also a common baseline for embedded development). The README in [their repo](https://github.com/mbits-libs/libmstch) also specifies GCC 4.7 as minimum requirement.
---
> mbits-mstch: Compile for GCC 10

- recipes/libucl/all/conanfile.py
Specify library name and version:  **libucl/all**
---
> libucl/all: bump deps, use version range for OpenSSL

- recipes/cpp-jwt/all/conanfile.py
Specify library name and version:  **cpp-jwt/all**
---
> cpp-jwt/all: use OpenSSL version range

- recipes/simple-websocket-server/all/conanfile.py
Specify library name and version:  **simple-websocket-server/all**
---
> simple-websocket-server/all: bump deps, use OpenSSL version range

- recipes/scip/all/conandata.yml
- recipes/scip/all/conanfile.py
- recipes/scip/config.yml
Specify library name and version:  **scip/8.0.4**
SCIP and SoPlex are coupled together: there is a 1-to-1 correspondence between the SCIP version and the SoPlex version, thus the new map in this recipe.
---
> [SCIP] bump version to 8.0.4

- recipes/npcap/all/test_package/conanfile.py
Specify library name and version:  **npcap/1.70**
This recipe and version already exist in ConanCenter, but probably not in the Conan 2.0 repo. That's probably why the PcapPlusPlus PR fails: https://github.com/conan-io/conan-center-index/pull/20296
This PR mostly fixes the test to be compatible with Conan 2.0.
---
> npcap 1.70: migrate to Conan 2.0

- recipes/libglvnd/all/conanfile.py
- recipes/libglvnd/all/test_package/CMakeLists.txt
- recipes/libglvnd/all/test_package/conanfile.py
Specify library name and version:  **libglvnd/***
The package's license has been updated from the meaningless `LicenseRef-LICENSE` to `MIT`.
Several updates to the outdated Conan recipe were also done.
---
> libglvnd: Fix incorrect license and update recipe

- recipes/util-linux-libuuid/all/conanfile.py
For some reason, it tries to install a systemd directory and bash completions in the usr directory.
Specify library name and version:  **util-linux-libuuid/2.39**
---
> util-linux-libuuid/2.39: Remove usr directory from package folder

- recipes/libtasn1/all/conanfile.py
> libtasn1: use winflexbison instead of bison if build machine is Windows

- recipes/commata/all/conandata.yml
- recipes/commata/config.yml
Specify library name and version:  **commata/0.2.6**
---
> commata: add version 0.2.6

- .c3i/config_v1.yml
Replaces the issue #2232 in favor of #20516 that's owned by CCI bot, so no humans related in case leaving the team.
closes #2232
After merging, #2232 should be updated with a message that we moved to the new issue and check in case it's pinned in GH issues as well. 
---
> [config] Uses CCI Bot as ower of Conan 1.x scheduled export results

- docs/changelog.md
Related to the PR https://github.com/conan-io/conan-center-index/pull/20498
New Conan client versions are now running in CCI.
---
> [docs] Add changelog for new conan versions

- recipes/s2geometry/all/conandata.yml
- recipes/s2geometry/all/conanfile.py
- recipes/s2geometry/all/patches/bump_cmake_cxx_standard.patch
- recipes/s2geometry/all/test_package/CMakeLists.txt
- recipes/s2geometry/all/test_package/conanfile.py
follow up of https://github.com/conan-io/conan-center-index/pull/20187#discussion_r1346311080
- honor C++ standard from profile
- do not define custom CMake target since upstream doesn't install a CMake config file
- cleanup topics
- bump required_conan_version to 1.54.0 because upstream defines BUILD_SHARED_LIBS as an option in its CMakeLists
- prefer to not scatter min compiler version logic
- prefer tar.gz tarball
---
> s2geometry: do not suggest unofficial CMake imported target + cleanup a little bit recipe

- recipes/tcp-wrappers/all/conanfile.py
> tcp-wrappers: relocatable shared lib on macOS + handle windows build machine + raise in validate() instead of configure()

- recipes/poly2tri/all/CMakeLists.txt
- recipes/poly2tri/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/17054
closes https://github.com/conan-io/conan-center-index/issues/20471
@StellaSmith @algarcia-ujaen please test this PR with your compiler and report whether it fixes your issue.
---
> poly2tri: fix MinGW by injecting `_USE_MATH_DEFINES` to avoid `M_PI` not defined

- recipes/libnghttp2/all/conandata.yml
- recipes/libnghttp2/config.yml
Specify library name and version:  **libnghttp2/1.57.0**
---
> libnghttp2: add version 1.57.0 (fix CVE-2023-44487)

- recipes/nmslib/all/conanfile.py
It's a more efficient and faster way to set @rpath in shared lib on macOS (fix_apple_shared_install_name() should be the last ressort).
---
> nmslib: better way to create relocatable shared lib on macOS

- recipes/yaclib/all/conanfile.py
- Definition of `YACLIB_CXX_STANDARD` in CMakeToolchain was broken with `compiler.cppstd` set to something like `gnu*`:
```
CMake Error in src/CMakeLists.txt:
The CXX_STANDARD property on target "yaclib" contained an invalid value:
"gnu20".
```
- add package_type (yaclib is always static: https://github.com/YACLib/YACLib/blob/v2022.12.10/src/CMakeLists.txt#L36)
---
> yaclib: fix `YACLIB_CXX_STANDARD` + add package_type

- recipes/wayland-protocols/all/conandata.yml
- recipes/wayland-protocols/config.yml
Specify library name and version:  **wayland-protocols/1.32**
---
> wayland-protocols: add version 1.32

- recipes/libx265/all/conanfile.py
> libx265: fix missing glibc symbols on newer systems

- recipes/android-ndk/all/conandata.yml
- recipes/android-ndk/config.yml
Specify library name and version:  **android-ndk/r26b**
This adds Android NDK r26b released two days ago: https://github.com/android/ndk/wiki/Changelog-r26#r26b
---
> android-ndk: add r26b

- recipes/jinja2cpp/all/conanfile.py
Definition of `JINJA2CPP_CXX_STANDARD` in CMakeToolchain was broken with `compiler.cppstd` set to something like gnu*:
```
CMake Error in CMakeLists.txt:
The CXX_STANDARD property on target "jinja2cpp" contained an invalid value:
"gnu20".
```
---
> jinja2cpp: fix `JINJA2CPP_CXX_STANDARD` mapping with `compiler.cppstd` when cppstd is `gnu*`

- recipes/rpclib/all/conandata.yml
- recipes/rpclib/all/conanfile.py
- recipes/rpclib/all/patches/2.3.0-0001-win-link-winsock.patch
backport https://github.com/rpclib/rpclib/pull/287 in order to fix build of shared lib with MinGW.
---
> rpclib: fix MinGW shared

- recipes/tinkerforge-bindings/all/CMakeLists.txt
- recipes/tinkerforge-bindings/all/conanfile.py
There was an incorrect logic in custom CMakeLists shipped by recipe. Windows system libs must be linked if Windows, it's unrelated to compiler name (here there was a link only for msvc).
Without this fix, you get a link error with MinGW shared:
```
ld.exe: CMakeFiles/tinkerforge_bindings.dir/src/source/ip_connection.c.obj:ip_connection.:(.text+0x90): undefined reference to `__imp_closesocket'
```
I take also advantage of this PR to write a neater CMakeLists.
---
> tinkerforge-bindings: fix MinGW shared

- recipes/m4/all/conanfile.py
- recipes/m4/all/test_package/conanfile.py
- recipes/m4/all/test_v1_package/conanfile.py
Specify library name and version:  **m4/\***
fixes #18054
I got the fix from libiconv:
https://github.com/conan-io/conan-center-index/blob/10658342a6999c03616d1ed4dc3666a9c6f1ef62/recipes/libiconv/all/conanfile.py#L93C9-L105C19
This also fixes running test_package for Windows x86. I'm not sure why x86_64 runs m4 without extension but x86 requires it. Maybe this is because I use windows docker container.
Honorable mention: https://github.com/conan-io/conan/issues/12546 & https://github.com/conan-io/conan/issues/7460
---
> m4: fix windows x86 build and test_package

- recipes/fltk/all/conanfile.py
fltk/1.3.8
On Linux I got undefined references when using the `fltk` library.
~~~~
undefined reference to `XftFontMatch'
undefined reference to `XftFontOpenPattern'
undefined reference to `XftFontOpen'
undefined reference to `XftFontOpenXlfd'
undefined reference to `XftTextExtents32'
undefined reference to `XftDrawChange'
undefined reference to `XftDrawSetClip'
undefined reference to `XftDrawString32'
~~~~
Found a stale pull request #15277 and bug report  #15276.
--
> fltk: Disable xft to fix compilation on Linux

- recipes/yajl/all/conandata.yml
- recipes/yajl/all/conanfile.py
- recipes/yajl/all/patches/2.1.0-0001-fix-cmake.patch
- Fix build with MinGW (cleanup bloated CMakeLists which was injecting unnecessary msvc warning flags if windows regardless of compiler, leading to `gcc.exe: error: /W4: linker input file not found: No such file or directory` with MinGW).
- Package either static or shared, not both. Indeed yajl builds and installs both flavors, and cci hook didn't catch this issue because static and shared lib names are different. I've preferred removing unwanted flavor afterwards instead of patching CMakeLists, because several executables are always link to static flavor.
- Disable build of doc, example, test, perf
- Better way to install relocatable shared lib for macOS (by removing hardcoded `INSTALL_NAME_DIR` in CMakeLists, and bumping cmake_minimum_required which was very very old and deprecated).
- …
> yajl: fix MinGW + package either static or shared lib

- recipes/cpr/all/conandata.yml
Specify library name and version:  **cpr/1.10.4**
---
> cpr: fix wrong url of 1.10.4

- recipes/amqp-cpp/all/conandata.yml
- recipes/amqp-cpp/config.yml
Specify library name and version: amqp-cpp/4.3.26
This version contains a fix of iterator invalidation / crash when a user space program publishes more messages as a result of an onAck/onNack callback in AMQP::Reliable
---
> amqp-cpp: add version 4.3.26

- recipes/mpg123/all/conanfile.py
> mpg123: fix missing glibc symbols on newer systems

- recipes/graphene/all/conanfile.py
> graphene: fix missing glibc symbols on newer systems

- recipes/libx264/all/conanfile.py
> libx264: fix missing glibc symbols on newer systems

- recipes/nmslib/all/conanfile.py
> nmslib: fix missing glibc symbols on newer systems

- recipes/openjpeg/all/conanfile.py
> openjpeg: fix missing glibc symbols on newer systems

- recipes/mtdev/all/conanfile.py
Specify library name and version:  **mtdev/***
Unless autoreconf is called when cross-compiling for armv8, the follow error occurs:
```
checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `aarch64-linux-gnu': machine `aarch64' not recognized
```
---
> mtdev: Call autoreconf to allow cross-compiling for armv8

- recipes/libsystemd/all/conandata.yml
- recipes/libsystemd/all/conanfile.py
- recipes/libsystemd/all/patches/253.3/0002-meson-use-c_args-in-generator-scripts.patch
- recipes/libsystemd/all/test_package/conanfile.py
- recipes/libsystemd/all/test_v1_package/conanfile.py
Specify library name and version:  **libsystemd/253.***
Bump versions of pkgconf and Meson.
Add  a patch to ensure that necessary compiler flags are passed through when the build system is invoking the compiler to generate files.
Without the proper compiler flags when cross-compiling, the system include directories and such are used which causes problems.
The patch has been applied upstream in systemd/systemd#29538.
---
> libsystemd/253.*: Fix cross-compilation

- recipes/mongo-c-driver/all/conanfile.py
Specify library name and version:  **mongo-c-driver/***
---
> mongo-c-driver/all: bump deps

- recipes/zstd/all/conandata.yml
- recipes/zstd/all/conanfile.py
- recipes/zstd/all/patches/1.5.5-qnx_support.patch
- recipes/zstd/all/test_package/conanfile.py
Library: zstd/*
Added option ("build_programs") to let the consumer choose whether to build executables/programs for zstd along with the static library.
Also added tests to verify the built executables!
---
> zstd/*: Added "build_programs" option

- recipes/harfbuzz/all/conandata.yml
- recipes/harfbuzz/config.yml
Specify library name and version:  **harfbuzz/8.2.2**
---
> harfbuzz: add version 8.2.2

- recipes/soundtouch/all/conanfile.py
> soundtouch: fix missing glibc symbols on newer systems

- recipes/gdcm/all/conanfile.py
Specify library name and version:  **gdcm/all**
gdcm uses [ERR_load_crypto_strings ](https://www.openssl.org/docs/man1.1.1/man3/ERR_load_crypto_strings.html)and [OpenSSL_add_all_algorithms](https://www.openssl.org/docs/man1.1.1/man3/OpenSSL_add_all_algorithms.html)  that are deprecated since OpenSSL 1.1.0. Using OPENSSL_API_COMPAT allows compiling this code without additional patching.
Fixes #19323 
---
> gdcm: fix compilation with old OpenSSL and bump dependencies

- recipes/rapidfuzz/all/conandata.yml
- recipes/rapidfuzz/config.yml
Specify library name and version:  **rapidfuzz/2.1.1**
---
> rapidfuzz: add version 2.1.1

- docs/package_templates/meson_package/all/conanfile.py
- docs/package_templates/meson_package/all/test_package/conanfile.py
Improve the Meson test package.
Minor clean up and organizing.
Use newer versions of Meson and pkgconf.
Delete pkg-config files.
Show how to enable a feature.
Show how to disable all features by default.
Update the check for the minimum compiler version for msvc.
---
> Update meson test package

- .c3i/config_v1.yml
When having a failure like missing dependencies or version conflict for Conan 2.x, it will be merged to Conan 1.x status and pushed to the PR labels.
---
> [config] Enable merge labels for Conan 1.x

- recipes/tre/all/CMakeLists.txt
- recipes/tre/all/conandata.yml
- recipes/tre/all/conanfile.py
- recipes/tre/all/test_package/CMakeLists.txt
- recipes/tre/all/test_package/conanfile.py
- recipes/tre/all/test_package/test_package.c
- recipes/tre/config.yml
Specify library name and version:  **tre/cci.20230717**: https://github.com/laurikari/tre
Did not include the last official release v0.8.0, since it's 14 years old and there have been minor improvements since without a version bump.
[![Packaging status](https://repology.org/badge/tiny-repos/tre.svg)](https://repology.org/project/tre/versions)
> tre: add recipe

- docs/package_templates/meson_package/all/conanfile.py
Use a lambda to enable and disable features based on options.
Demonstrate how to disable all features by default.
This is a follow up PR to #20645.
---
> Update meson template package

- recipes/numcpp/all/conandata.yml
- recipes/numcpp/config.yml
Specify library name and version:  **numcpp/2.12.1**
Since numcpp/2.12.1 fixed https://github.com/dpilger26/NumCpp/issues/204,
numcpp/2.12.1 supports apple-clang again.
---
> numcpp: add version 2.12.1, support apple-clang again

- recipes/hwloc/all/conandata.yml
- recipes/hwloc/config.yml
Specify library name and version:  **hwloc/2.9.2**
Reason: this version resolves this CVE https://nvd.nist.gov/vuln/detail/CVE-2022-47022
---
> hwloc: added 2.9.3

- recipes/onetbb/all/conanfile.py
Specify library name and version:  **onetbb/all**
**Changes:** bump hwloc to 2.9.3 which is updated here https://github.com/conan-io/conan-center-index/pull/20691, because older one has CVE
---
> onetbb: bump hwloc dependency

- recipes/aeron/all/conanfile.py
> aeron: fix missing glibc symbols on newer systems

- recipes/avahi/all/conanfile.py
- recipes/avahi/all/test_package/test_package.c
Specify library name and version:  **avahi/0.8**
The avahi package also provides `mdnsresponder`,  and when doing it, the consumer does not expect avahi, but the true include header, like `#include <dns.h>`. 
This reverts part of the commit https://github.com/conan-io/conan-center-index/pull/20706/commits/88c85c9b2c5cc25e2a1574fcc937695bdc7cadc3, but keep both root and module name as include folder.
Required by https://github.com/conan-io/conan-center-index/pull/20287
---
> [avahi] Expose both root include folder and module name

- recipes/grpc/all/conandata.yml
- recipes/grpc/all/patches/v1.50.x/001-disable-cppstd-override.patch
- recipes/grpc/config.yml
Specify library name and version:  **grpc/1.50.1**
The PR #18544 sanitized old versions for gRPC, but true is the version `1.50.1` is still largely used in CCI:
```
$ find .. -name conanfile.py -exec grep grpc/1.50. {} +  
../recipes/microservice-essentials/all/conanfile.py:            self.requires("grpc/1.50.1")
../recipes/arrow/all/conanfile.py:            self.requires("grpc/1.50.0")
../recipes/bear/all/conanfile.py:        self.requires("grpc/1.50.1")
../recipes/bear/all/conanfile.py:        self.tool_requires("grpc/1.50.1")
../recipes/asio-grpc/all/conanfile.py:        self.requires("grpc/1.50.1")
../recipes/google-cloud-cpp/2.x/conanfile.py:        self.requires("grpc/1.50.1", transitive_headers=True)
../recipes/google-cloud-cpp/2.x/conanfile.py: …
```
> [grpc] Build versions 1.50.x

- recipes/directx-headers/all/conandata.yml
- recipes/directx-headers/all/conanfile.py
- recipes/directx-headers/all/test_package/conanfile.py
- recipes/directx-headers/all/test_package/meson.build
- recipes/directx-headers/all/test_package/test_package.cpp
- recipes/directx-headers/config.yml
This recipe is for the [DirectX-Headers](https://github.com/microsoft/DirectX-Headers/) library. These are the official Direct3D 12 headers.
Add versions 1.610.2 and 1.711.3-preview.
---
> directx-headers: Add recipe

- recipes/sdl/all/conanfile.py
**sdl/2.28.3**
There is an issue with the sdl package, where it creates a cmake string with a path, but does not escape or convert the path slashes, this creates invalid escape sequences and invalid paths.
---
> SDL EXTRA_CFLAGS variable had invalid escape sequences, resolve them

- recipes/signals-light/all/conandata.yml
- recipes/signals-light/all/conanfile.py
- recipes/signals-light/all/test_package/CMakeLists.txt
- recipes/signals-light/all/test_package/conanfile.py
- recipes/signals-light/all/test_package/test_package.cpp
- recipes/signals-light/config.yml
Specify library name and version:  **signals-light/***
signals-light is one of the termox(https://github.com/a-n-t-h-o-n-y/TermOx)'s dependency libraries.
---
> signals-light: add recipe

- recipes/wt/all/conanfile.py
Specify library name and version:  **wt/4.10.1**
Related to https://github.com/conan-io/conan-center-index/pull/19989#issuecomment-1775331230
Doing more builds locally, only MSVC and with the version 4.10.1 the error occurs.
Testing with LInux and Mac, but also with the version 4.10.0, everything works.
It could be related to https://github.com/emweb/wt/commit/7956a40c736aae9c5be87ed68d19e2b00bb81bc2
I opened an issue to Wt asking about: https://redmine.emweb.be/issues/12073
/cc @SpaceIm 
---
> [wt] Unblock Linux and Mac for 4.10.1 + cppstd=17

- recipes/zstd/all/conanfile.py
fix regression from https://github.com/conan-io/conan-center-index/pull/18826 where both shared & static were packaged on Windows if shared=True (see https://github.com/conan-io/conan-center-index/pull/18826#issuecomment-1769360351)
---
> zstd: do not package both static & shared on windows

- docs/changelog.md
- Allow X.Y semver for version bumps
So far, CCI has only accepting `<semver>` format to be automatically marked as `bump version`, but looking at some projects that only use `<major>.<minor>` format, they could be aggregated to the same rule without problem. However, in case adding a new version to a PR only, but mixing between `<semver>` and `<major>.<minor>`, this will not be considered an automatic bump version by the CI bot.
- Add assert message for parent commit checks on PR checkout
Sometimes users can experience an internal CI error related to concurrency: 
`parentCommits[1] == masterCommit`
This error is a bit hard to track, so some logs were added to filter it better when failing in the CI.
- JobRelauncher restarts both Conan v1 and v2 pipelines
When a build fails due an …
> [changelog] New C3I Jenkins version: release 2023.10.26

- docs/adding_packages/conanfile_attributes.md
Any project is free to change its license, so to follow-up in the recipe, we can change it through `configure()` and `self.license`
Related to https://github.com/conan-io/conan-center-index/pull/19152
/cc @fschoenm 
---
> [docs] Add license change explanation

- recipes/netcdf/all/conanfile.py
Also remove several workarounds (CMAKE_POLICY_DEFAULT_CMP0077 and explicit libdirs & includedirs in components) for old conan clients (not required anymore with conan >=1.54.0)
---
> netcdf: version range for libcurl + add package_type

- recipes/easylzma/all/conanfile.py
It's a more efficient and faster way to set `@rpath` in shared lib on macOS (`fix_apple_shared_install_name()` should be the last ressort)
Moroever it avoids these warnings during CMake configuration:
```
CMake Warning (dev) at elzma/CMakeLists.txt:36 (GET_TARGET_PROPERTY):
Policy CMP0026 is not set: Disallow use of the LOCATION target property.
Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The LOCATION property should not be read from target "elzma".  Use the
target name directly with add_custom_command, or use the generator
expression $<TARGET_FILE>, as appropriate.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at test/CMakeLists.txt:24 (GET_TARGET_PROPERTY): …
```
> easylzma: better way to create relocatable shared lib on macOS

- recipes/opencv/2.x/conanfile.py
- recipes/opencv/3.x/conanfile.py
- recipes/opencv/4.x/conanfile.py
- Define several CMake variables of upstream config file (see https://github.com/opencv/opencv/blob/4.8.1/cmake/templates/OpenCVConfig.cmake.in):
- `OpenCV_LIBS`
- `OpenCV_VERSION_MAJOR`
- `OpenCV_VERSION_MINOR`
- `OpenCV_VERSION_PATCH`
- Bump dependencies
- opencv 4.x: Use `<host_version>` for protobuf in build requirements (and update `required_conan_version` accordingly).
---
> opencv: define several official cmake vars of OpenCV in CMakeDeps + use `<host_version>` for protobuf in build requirements

- recipes/qt/6.x.x/conanfile.py
closes conan-io/conan-center-index#20565
fixes conan-io/conan-center-index#20383
---
> qt6: do not define default_options for modules

- recipes/backward-cpp/all/conanfile.py
The library is nearly header-only anyway and is being used as such in #19074, so it made sense to perhaps add the option to the recipe.
Also removed the redundant `transitive_libs=True` params and made Linux OS detection more consistent.
> backward-cpp: add header_only option

- recipes/ozz-animation/all/CMakeLists.txt
- recipes/ozz-animation/all/conandata.yml
- recipes/ozz-animation/all/conanfile.py
- recipes/ozz-animation/all/test_package/conanfile.py
- recipes/ozz-animation/all/test_v1_package/CMakeLists.txt
- recipes/ozz-animation/all/test_v1_package/conanfile.py
- recipes/ozz-animation/all/test_v1_package/test_package.cpp
- recipes/ozz-animation/config.yml
Specify library name and version:  **ozz-animation/0.14.1**
Add version 0.14.1 and update recipe to be compatible with Conan 2.0
---
> Package/ozz animation 0.14.1

- recipes/onetbb/all/conanfile.py
Specify library name and version:  **onetbb/2021.3.0**
The PR https://github.com/conan-io/conan-center-index/pull/19152 is blocked because OneTBB is missing. The explanation is simple: We raise an invalid configuration when building OneTBB, but not when consuming, so there is no package, and will not be available ever. 
That condition should be moved to `validate()` instead. 
/cc @fschoenm
---
> [onetbb] Use validate method for package compatibility

- recipes/miniaudio/all/conandata.yml
- recipes/miniaudio/config.yml
Specify library name and version:  **miniaudio/0.11.18**
---
> miniaudio: add version 0.11.18

- recipes/cassandra-cpp-driver/all/conandata.yml
- recipes/cassandra-cpp-driver/config.yml
Specify library name and version:  **cassandra-cpp-driver/2.17.1**
---
> cassandra-cpp-driver: add version 2.17.1

- recipes/google-cloud-cpp/2.x/conandata.yml
- recipes/google-cloud-cpp/2.x/conanfile.py
- recipes/google-cloud-cpp/2.x/patches/2.5.0/006-cannot-use-or-with-windows.patch
Specify library name and version:  **google-cloud-cpp/v2.5.0** and **google-cloud-cpp/v2.12.0**.
Several requirements need version bumps. Where possible I chose version ranges over pinning specific versions.
I had to backport fixes for MSVC. I am only guessing, but it seems the toolchain changed in the CI system and now spelling `||` as `or` results in build errors.
I also disabled `-Werror` because the code in `v2.5.0` has warnings with newer toolchains. This is to be expected, and that is why the project no longer enables `-Werror` by default.
---
> [google-cloud-cpp] bump requirements and other fixes

- recipes/yaml-cpp/all/conanfile.py
- recipes/yaml-cpp/all/test_package/CMakeLists.txt
- Since 0.8.0, `YAML_CPP_STATIC_DEFINE` is an interface definition of static yaml-cpp, irrespective of compiler or OS (see https://github.com/jbeder/yaml-cpp/blob/0.8.0/CMakeLists.txt#L126). And looking at https://github.com/jbeder/yaml-cpp/blob/0.8.0/include/yaml-cpp/dll.h, you can quickly see that it's very important on windows (not only msvc), otherwise you have tones of `__declspec(dllimport)` in public headers of static lib, which is not good.
- Since 0.8.0 also, imported target is namespaced (https://github.com/jbeder/yaml-cpp/blob/0.8.0/CMakeLists.txt#L171), therefore `cmake_target_name` is updated with this new target. Non-namespaced target is still provided in `cmake_target_aliases` for compatibility.
closes https://github.com/conan-io/conan-center-index/issues/20825
---
> yaml-cpp: fix interface definition for windows + provide `yaml-cpp::yaml-cpp` imported target

- recipes/libwebm/all/conandata.yml
- recipes/libwebm/all/test_package/conanfile.py
- recipes/libwebm/all/test_package/test_package.cpp
- recipes/libwebm/config.yml
Specify library name and version:  **libwebm/1.0.0.31**
The library makes use of some deprecated features which were removed in the C++20 spec. Some compilers are now getting around to removing these, for example older versions of this library no longer build with XCode 15 when targeting C++20. 
This update fixes the build when targeting C++20, without breaking it when targeting older spec versions.
---
> libwebm: Update to 1.0.0.31 to fix C++20 builds.

- recipes/libarchive/all/conandata.yml
- recipes/libarchive/all/patches/0007-3.7.1-include-getopt.patch
libarchive 3.7.1
Including getopt.h when HAVE_GETOPT_OPTRESET is defined.
[Upstream PR](https://github.com/libarchive/libarchive/pull/2007)
---
> libarchive: patch to include getopt.h when required

- recipes/openssl/3.x.x/conanfile.py
Specify library name and version:  **openssl/3.x.x**
See OpenSSL documentation for [no-autoload-config](https://github.com/openssl/openssl/blob/master/INSTALL.md#no-autoload-config)
---
> openssl: add no_autoload_config option

- recipes/detools/all/CMakeLists.txt
- recipes/detools/all/conandata.yml
- recipes/detools/all/conanfile.py
- recipes/detools/all/test_package/CMakeLists.txt
- recipes/detools/all/test_package/conanfile.py
- recipes/detools/all/test_package/test_package.c
- recipes/detools/config.yml
Specify library name and version:  **detools/***
- add version 0.53.0
- replace zip to tar ball
---
> detools: add version 0.53.0, suppport conan v2

- recipes/rapidfuzz/all/conandata.yml
- recipes/rapidfuzz/config.yml
Specify library name and version:  **rapidfuzz/2.2.0**
---
> rapidfuzz: add version 2.2.0

- recipes/openssl/1.x.x/conanfile.py
https://github.com/conan-io/conan-center-index/pull/20441 has removed versions < 1.1.1 but did not remove all the logic of these versions in recipe.
---
> openssl 1.x: cleanup recipe after removal of versions < 1.1.1 in #20441

- recipes/opentdf-client/all/conandata.yml
- recipes/opentdf-client/config.yml
Specify library name and version:  **opentdf-client/1.5.6**
- Add support for non-encrypted TDF
- Changes to support SWIG
---
> opentdf-client: add version 1.5.6

- recipes/icu/all/conandata.yml
- recipes/icu/config.yml
Specify library name and version:  **icu/74.1**
Add support for ICU version 74.1
---
> Add support for ICU version 74.1

- recipes/pixman/all/conandata.yml
- recipes/pixman/all/conanfile.py
- recipes/pixman/all/patches/0.42.2-0001-pixman-arma64-Adjustments-to-build-with-llvm-integra.patch
- recipes/pixman/config.yml
Specify library name and version:  **pixman/0.42.2**
---
> pixman: Add version 0.42.2

- recipes/brunsli/all/conandata.yml
- recipes/brunsli/all/conanfile.py
- recipes/brunsli/all/patches/0.1/001-cmake-use-conan-deps.patch
- recipes/brunsli/all/patches/0.1/002-fix-shared-windows-build.patch
- recipes/brunsli/all/patches/cci.20230730/001-cmake-use-conan-deps.patch
- recipes/brunsli/all/patches/cci.20230730/002-fix-shared-windows-build.patch
- recipes/brunsli/all/test_package/CMakeLists.txt
- recipes/brunsli/all/test_package/conanfile.py
- recipes/brunsli/all/test_package/test_package.cpp
- recipes/brunsli/config.yml
Adds **brunsli**, a JPEG repacker library that applies Brotli compression to losslessly repack JPEG files: https://github.com/google/brunsli
Used by GDAL as an optional dependency.
Resolves #8629.
[![Packaging status](https://repology.org/badge/tiny-repos/brunsli.svg)](https://repology.org/project/brunsli/versions)
> brunsli: add new package

- recipes/asio-grpc/all/conandata.yml
- recipes/asio-grpc/all/conanfile.py
- recipes/asio-grpc/config.yml
Specify library name and version:  **asio-grpc/***
The version of grpc is kept at 1.50.1 because 1.54.3 causes compile errors.
---
> asio-grpc: add version 2.7.0, update asio

- recipes/grpc-proto/all/conanfile.py
> grpc-proto: use host_version for protobuf in build requirements and bump protobuf

- recipes/qt/5.x.x/conanfile.py
fixes #20816
Specify library name and version:  **qt/5.15.11**
I wrote a little proof of concept here:
https://github.com/fnadeau/qt-demo.git
A simple app that display 4 buttons with icons. Two use SVG and two use PNG as image source.
When build with ```qt/5.15.11``` in conanfile.txt, this is the result
If locally building this PR with something like:
```
conan create .\recipes\qt\5.x.x\ --name qt --version 5.15.11 -pr:b default -pr:h default -o qt*:qtsvg=True --user fnadeau --channel github
```
and changing ```qt/5.15.11``` to ```qt/5.15.11@fnadeau/github``` in conanfile.txt, you'll get this
---
I'm using conan 2.0, not yet supported as per documentation, but I did try at least one configuration.
> qt/5.15.11: Expose QSvgPlugin and QSvgIconPlugin

- recipes/usockets/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/20896
---
> usockets: fix mistake in _minimum_compilers_version logic

- recipes/rapidfuzz/all/conandata.yml
- recipes/rapidfuzz/config.yml
Specify library name and version:  **rapidfuzz/2.2.3**
---
> rapidfuzz: add version 2.2.3

- recipes/assimp/5.x/patches/0001-unvendor-deps-5.0.x.patch
- recipes/assimp/5.x/patches/0003-unvendor-deps-5.1.x.patch
- recipes/assimp/5.x/patches/0004-unvendor-deps-5.1.6.patch
- recipes/assimp/5.x/patches/0006-unvendor-deps-5.2.x.patch
closes https://github.com/conan-io/conan-center-index/issues/20553
---
> assimp: fix cmake configuration when zlib is not a direct dependency but minizip is

- docs/package_templates/autotools_package/all/conanfile.py
- docs/package_templates/cmake_package/all/conanfile.py
- docs/package_templates/cmake_package/all/test_package/CMakeLists.txt
- docs/package_templates/header_only/all/conanfile.py
- docs/package_templates/meson_package/all/conanfile.py
- docs/package_templates/meson_package/all/test_package/conanfile.py
- docs/package_templates/msbuild_package/all/conanfile.py
- docs/package_templates/msbuild_package/all/test_package/CMakeLists.txt
- docs/package_templates/prebuilt_tool_package/all/conanfile.py
Alphabetize things.
Use `_min_cppstd` and `_compilers_minimum_version` consistently.
Omit keywords from the `copy` command and use the same order of the arguments across all calls.
Use the `LANGUAGES` keyword in CMake project commands.
Bump the Meson version in the Meson test package.
---
> Minor clean up of template packages

- recipes/openvino/all/conandata.yml
- recipes/openvino/all/patches/2023.1.0/0007-compilation-c++23.patch
Specify library name and version:  **openvino/2023.1.0**
**Changes:** Ported upstream patch for compilation with C++23 for better portability
---
> openvino: ported upstream patch for C++23 support

- recipes/iconfontcppheaders/all/conandata.yml
- recipes/iconfontcppheaders/all/conanfile.py
- recipes/iconfontcppheaders/config.yml
Bumping iconfontcppheaders to latest version (cci.20231102) which adds the Lucide font. Package description also updated to include the new font.
---
> iconfontcppheaders: bump version to cci.20231102 with added Lucide font

- recipes/trompeloeil/all/conandata.yml
- recipes/trompeloeil/config.yml
Specify library name and version:  **trompeloeil/46**
---
> trompeloeil: add version 46

- recipes/octo-logger-cpp/all/conandata.yml
- recipes/octo-logger-cpp/config.yml
Specify library name and version:  **octo-logger-cpp/1.5.0**
---
> octo-logger-cpp: add version 1.5.0

- recipes/easyloggingpp/all/conanfile.py
Linking against `easyloggingpp` fails due to a missing `-fPIC` flag in #18833: https://c3i.jfrog.io/c3i/misc/logs/pr/18833/7-linux-gcc/hexl/1.2.4//d5422ba2c62d28d2eca578d61ab395bd6284fc93-build.txt
> easyloggingpp: add -fPIC option

- recipes/libpq/all/conandata.yml
- recipes/libpq/all/patches/15/001-mingw-build-static-libraries.patch
mingw patch has been forgotten while adding 15.x versions in https://github.com/conan-io/conan-center-index/pull/18317 & https://github.com/conan-io/conan-center-index/pull/19201
14.8 was also broken but it has been removed (very quickly!) in https://github.com/conan-io/conan-center-index/pull/19653...
---
> libpq: fix 15.x for mingw by adding missing patch

- recipes/soplex/all/conanfile.py
When shared=True, import lib is not installed for mingw, its extension is `.dll.a`. Since everything is copied manually in package(), well it's fragile so you have to know all kind of extensions...
Also cleanup recipe a little bit and provide a more elegant way to discovery GMP (with set_property in CMakeDeps).
---
> soplex: fix installation of import for mingw shared + cleanup recipe

- recipes/libsolace/all/conandata.yml
- recipes/libsolace/all/conanfile.py
- recipes/libsolace/all/test_package/CMakeLists.txt
- recipes/libsolace/all/test_package/conanfile.py
- recipes/libsolace/all/test_v1_package/CMakeLists.txt
- recipes/libsolace/all/test_v1_package/conanfile.py
- recipes/libsolace/config.yml
> libsolace: migrate to Conan v2

- recipes/hwloc/all/conanfile.py
Specify library name and version:  **hwloc/all**
Related to #20897
Removing shared option for OneTBB will not be enough to fix our current error with missing packages, because it uses hwloc as dependency.
The `hwloc` supports both static and shared, but when running CCI, it will be consumed by OneTBB without `shared`, resulting in a single configuration.
The problem occurs because when CCI builds with Conan 2.x, it will use `*/*:shared=True/False`, resulting in `hwloc/*:shared=True` with OneTBB, a configuration not available in Conan Center, because only the default configuration is available (the static one).
This PR sacrifices `hwloc`, by removing its support for static library, but provide only shared, so it should be kept aligned with OneTBB. Also, only OneTBB uses `hwloc` in CCI, so …
> [hwloc] Build shared library only

- recipes/hdf5/all/conanfile.py
https://github.com/conan-io/conan-center-index/pull/15674 broke packaging of MinGW shared, by removing import lib (extension `.dll.a`). This PR fixes this issue.
---
> hdf5: do not remove import lib during packaging if mingw shared

- recipes/faac/all/conanfile.py
There is incorrect logic in recipe for mingw. It tries to patch Makefile after autoreconf, not configure, leading to:
```
faac/1.30: ERROR:
Package '50706d5c263b28ec09259a73ef46fa9f215f442d' build failed
faac/1.30: WARN: Build folder C:\Users\spaceim\.conan2\p\b\faacf76c1fb6f02e0\b\build-release
*********************************************************
Recipe 'faac/1.30' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************
ERROR: faac/1.30: Error in build() method, line 155
replace_in_file(self, os.path.join(self.build_folder, "libfaac", "Makefile"), …
```
> faac: fix build with mingw

- recipes/nettle/all/conanfile.py
Patch `config.m4` if build machine is Windows after configure() (instead of autreconf()), otherwise file doesn't exist yet and therefore replace_in_file fails.
---
> nettle: fix patch logic when build machine is windows

- recipes/base64/all/conandata.yml
- recipes/base64/config.yml
Specify library name and version:  **base64/0.5.1**
---
> base64: add version 0.5.1

- recipes/onetbb/all/conanfile.py
- regarding removal of shared option: see https://github.com/conan-io/conan/issues/15040#issuecomment-1790753531
- for tbbmaloc & tbbproxy, well current logic was super weird. It comes from https://github.com/conan-io/conan-center-index/pull/17311, but it doesn't really make sense. These options didn't exist before 2021.5.0 or 2021.6.0, so they have to be removed in config_option, that's all.
---
> onetbb: remove shared option + fix tbbmaloc & tbbproxy logic

- recipes/duckdb/all/conandata.yml
- recipes/duckdb/all/conanfile.py
Any logic which tries to naively remove  static lib with pattern `*.a` when we want to keep shared only is broken for MinGW, since import libs have extension `.dll.a`
---
> duckdb: do not remove import lib during packaging if mingw shared

- recipes/libarchive/all/conanfile.py
- recipes/libarchive/all/patches/0003-3.7.1-cmake.patch
Fix regression of https://github.com/conan-io/conan-center-index/pull/19718
So we build either shared or static in 3.7.1 like all other previous versions, and avoid this removal of .a files if shared which breaks mingw shared since import lib is .dll.a
---
> libarchive: fix mingw shared

- recipes/qt/6.x.x/conanfile.py
Specify library name and version:  **qt/6.5.3**
Fix issue #20924.
Note to reviewers:
- See #20817 for Svg
- Technically, some version of msvc 191 support c++17. Is there a better way to detect cpp standard?
- Qt6 support DirectX 9,11 and 12. Shoud we add d3d12?
Tested with
```
#include <QApplication>
#include <QPushButton>
#include <QtPlugin>
Q_IMPORT_PLUGIN (QWindowsIntegrationPlugin);
//#pragma comment(lib, "d3d9")
//#pragma comment(lib, "setupapi")
//#pragma comment(lib, "SHCore")
int main(int argc, char *argv[])
{
QApplication a(argc, argv);
QPushButton button ("Hello world!");
button.show();
return a.exec(); 
}
```
Pragmas are needed without patch
```
set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES cmake/conan_provider.cmake)
cmake_minimum_required(VERSION 3.9)
project(FormatOutput CXX) …
```
> qt: fix minor issues in 6.x

- recipes/fastgltf/all/conandata.yml
- recipes/fastgltf/all/conanfile.py
- recipes/fastgltf/all/patches/0.6.0-0001-find_package-simdjson.patch
- recipes/fastgltf/all/patches/0.6.1-0001-find_package-simdjson.patch
- recipes/fastgltf/config.yml
Specify library name and version:  **fastgltf/0.6.0**
Updates fastgltf to 0.6.0. Also I've seen spnda/fastgltf#22. Would adding an option like `FASTGLTF_FIND_SIMDJSON` be appropriate, which if set calls `find_package` so that these patches can be avoided? That would be for the next release, though I think.
> fastgltf: Update to 0.6.1

- recipes/tcsbank-uconfig/all/conanfile.py
follow up https://github.com/conan-io/conan-center-index/pull/18353
validate() was fragile, there is a python error if compiler is not in `_compilers_minimum_version`.
---
> tcsbank-uconfig: robust to "unknow compilers" in validate()

- recipes/glew/all/conanfile.py
- recipes/glew/all/test_package/CMakeLists.txt
Specify library name and version:  **glew/***
Use `rm_safe` function.
Update minimum CMake version in test package.
---
> glew: Add package type

- recipes/abseil/all/conandata.yml
- recipes/abseil/all/patches/20230802.1-0001-fix-mingw.patch
Build erros of 20230802.1 with MinGW:
```
[213/236] Linking CXX shared library bin\libabsl_synchronization.dll
FAILED: bin/libabsl_synchronization.dll absl/synchronization/libabsl_synchronization.dll.a
cmd.exe /C "cd . && D:\Prog\winlibs64-13.1.0msvcrt\mingw64\bin\x86_64-w64-mingw32-g++.exe -std=c++17 -O3 -DNDEBUG   -shared -o bin\libabsl_synchronization.dll -Wl,--out-implib,absl\synchronization\libabsl_synchronization.dll.a -Wl,--major-image-version,0,--minor-image-version,0 absl/synchronization/CMakeFiles/synchronization.dir/barrier.cc.obj absl/synchronization/CMakeFiles/synchronization.dir/blocking_counter.cc.obj absl/synchronization/CMakeFiles/synchronization.dir/internal/create_thread_identity.cc.obj absl/synchronization/CMakeFiles/synchronization.dir/internal/futex_waiter.cc.obj …
```
> abseil: fix build of 20230802.1 with MinGW

- recipes/sfml/all/conanfile.py
Specify library name and version:  **sfml/2.6.1**
When I attempt to link a C++ program that uses Conan package sfml/2.6.1 on Linux, I get this error:
```
/home/runner/.conan2/p/b/sfml9a8b35e144b99/p/lib/libsfml-window-s-d.a(VulkanImplX11.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
```
whereas sfml/2.5.1 worked fine. The CMake code in the SFML repo links with `dl` on linux [as shown here](https://github.com/SFML/SFML/blob/39ba64cfc63866a868c94a41ca331c12235c190e/src/SFML/Window/CMakeLists.txt#L325) so I'm just propagating that to the Conan package.
---
> Fix SFML linker error on Linux

- recipes/onnxruntime/all/conanfile.py
Specify library name and version:  **onnxruntime/all**
conan v1 completely ignores traits in self.requires(...) so without custom self.cpp_info.requires list onnxruntime was linking to all components of boost.
---
> onnxruntime: don't bring link dependency to boost on conanv1

- recipes/commata/all/conandata.yml
- recipes/commata/config.yml
Specify library name and version:  **commata/0.2.6-bug1**
---
> commata: add version 0.2.6-bug1

- recipes/libavif/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/21055
also add package_type, and bump required_conan_version in order to remove `CMAKE_POLICY_DEFAULT_CMP0077` workaround 
---
> libavif >= 0.11.0: add libwebp to requirements in order to get sharpyuv and therefore ensure reproducible build

- recipes/minizip-ng/all/conandata.yml
- recipes/minizip-ng/config.yml
Specify library name and version:  **minizip-ng/4.0.3**
---
> minizip-ng: add version 4.0.3

- recipes/liburing/all/conandata.yml
- recipes/liburing/all/conanfile.py
- recipes/liburing/all/test_package/CMakeLists.txt
- recipes/liburing/all/test_package/conanfile.py
- recipes/liburing/all/test_v1_package/CMakeLists.txt
- recipes/liburing/all/test_v1_package/conanfile.py
- recipes/liburing/config.yml
Specify library name and version:  **liburing/2.3**
> liburing: Add 2.3+2.4 and update to Conan 2

- recipes/mold/all/conandata.yml
- recipes/mold/all/conanfile.py
- recipes/mold/config.yml
Specify library name and version:  **mold/2.0.0**
Essentially a version bump. mold 2.0.0 has been relicensed from AGPL to MIT (see [Release Notes for mold 2.0.0](https://github.com/rui314/mold/releases/tag/v2.0.0)), which is why I moved the old _all_ folder to _1.x.x_ and created a new _all_ folder that essentially only changed the `license` attribute. I hope that's the correct approach.
---
> Add mold 2.0.0

- recipes/ffmpeg/all/conanfile.py
I'm blocked by missing packages of ffmpeg for https://github.com/conan-io/conan-center-index/pull/19194
---
> ffmpeg: bump dependencies + disable with_vulkan by default

- recipes/magic_enum/all/conandata.yml
- recipes/magic_enum/all/test_package/CMakeLists.txt
- recipes/magic_enum/all/test_package/test_package.cpp
- recipes/magic_enum/config.yml
Specify library name and version:  **magic_enum/***
Since 0.9.4, magic_enum places `magic_enum.hpp` to `include/magic_enum/` folder.
---
> magic_enum: add version 0.9.4, remove older versions

- recipes/pdfium/all/CMakeLists.txt
- recipes/pdfium/all/conandata.yml
- recipes/pdfium/all/conanfile.py
- recipes/pdfium/all/test_package/CMakeLists.txt
- recipes/pdfium/all/test_package/conanfile.py
- recipes/pdfium/all/test_v1_package/CMakeLists.txt
- recipes/pdfium/all/test_v1_package/conanfile.py
- recipes/pdfium/config.yml
Bumped the version to the newest one supported by `pdfium-cmake`.
The existing version had compilation issues in its C++17 compatibility library.
> pdfium: migrate to Conan v2

- recipes/libdisplay-info/all/conandata.yml
- recipes/libdisplay-info/all/conanfile.py
- recipes/libdisplay-info/all/test_package/conanfile.py
- recipes/libdisplay-info/all/test_package/meson.build
- recipes/libdisplay-info/all/test_package/test_package.c
- recipes/libdisplay-info/config.yml
Specify library name and version:  **libdisplay-info/0.1.1**
`libdisplay-info` is required to create a `wlroots` Conan package.
Requires #20278.
Note that I might need to disable Windows / macOS builds if they don't work. I didn't see anything that wouldn't allow them to build there, so I left them enabled at first.
---
> libdisplay-info: Add recipe

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.6.0**
---
> glaze: add version 1.6.0

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
Specify library name and version:  **imgui/1.90,1.90-docking**
---
> imgui: add version 1.90, 1.90-docking

- recipes/onnx/all/conanfile.py
Specify library name and version:  **onnx/all**
Similar reason as https://github.com/conan-io/conan-center-index/pull/20976, because on Windows shared library for ONNX is not available and we don't have package available.
For OpenVINO Conan v2 case https://github.com/conan-io/conan-center-index/pull/20933 we have failed dynamic builds https://c3i.jfrog.io/c3i/misc-v2/summary.html?json=https://c3i.jfrog.io/c3i/misc-v2/logs/pr/20933/5/openvino/2023.2.0//summary.json
---
> onnx: make static-library only

- recipes/cityhash/all/conandata.yml
- recipes/cityhash/config.yml
Specify library name and version:  **cityhash/1.0.1**
Corresponding issue: #21173 
---
> cityhash: add version 1.0.1

- recipes/wavelet_buffer/all/conanfile.py
Specify library name and version:  **wavelet_buffer/***
migrates to a cimg version which is compatible with conan 2
---
> wavelet_buffer/all: bump deps

- recipes/shapelib/all/conanfile.py
- recipes/shapelib/all/test_package/CMakeLists.txt
- recipes/shapelib/all/test_v1_package/CMakeLists.txt
Specify library name and version:  **shapelib/1.5.0**
Disabling the `USE_RPATH` CMake option in the conanfile.py currently has no effect on the shapelib build system.
This is because the `USE_RPATH` variable is set as a normal variable and not a cache variable and due to the fact that the minimum required version of CMake is 3.7.
As of CMake 3.13, policy CMP0077 fixes this behavior so that the `option()` function in CMake accepts normal variables for setting options.
For now, this PR sets `USE_RPATH` as a cache variable to workaround this issue.
Additionally, the CMake version required in the test packages is updated.
---
> shapelib: Fix RPATH on macOS

- recipes/cfitsio/all/conanfile.py
The project uses
https://spdx.org/licenses/CFITSIO.html
not the currently set
https://spdx.org/licenses/ISC.html
> cfitsio: more accurate license identifier

- recipes/perfetto/all/conandata.yml
- recipes/perfetto/config.yml
Specify library name and version:  **perfetto/39.0**
```
v39.0 - 2023-11-15:
* Added reporting of TZ offset under system_info.timezone_off_mins .
* Added no_flush option to DataSourceDescriptor to avoid unnecessary IPC
roundtrips to flush data sources like track_event that rely uniquely on
server-side scraping.
* Added support for running on Linux & Android systems configured with 16K
pagetables.
* New android_boot metric.
* Added new PerfettoSQL syntax (CREATE PERFETTO VIEW) for adding schemas to views.
* Support perf.data import format.
* Add dvfs and cpu_idle to stdlib.
UI:
* Add a new type of debug tracks: counter.
* Improved visualization of timestamps for durations.```
---
- [ x ] I've read the [contributing …
> perfetto: Bump version: 39.0

- recipes/miniaudio/all/conandata.yml
- recipes/miniaudio/config.yml
Specify library name and version:  **miniaudio/0.11.21**
---
> miniaudio: add version 0.11.21

- recipes/libyuv/all/conandata.yml
- recipes/libyuv/all/conanfile.py
- recipes/libyuv/all/patches/1880-0001-fix-cmake.patch
- recipes/libyuv/config.yml
Same rational as https://github.com/conan-io/conan-center-index/pull/17228, https://github.com/conan-io/conan-center-index/pull/21144 & https://github.com/conan-io/conan-center-index/pull/21202
libyuv is a dependency of libavif, so without this change libavif shared is never built for msvc in v2 pipeline.
---
> libyuv: add 1880 + remove shared option if msvc instead of raising

- recipes/fftw/all/conanfile.py
It's `ENABLE_QUAD_PRECISION` (https://github.com/FFTW/fftw3/blob/38ea230e25e69e7a3f35b957b815bac4f9aa22b0/CMakeLists.txt#L22) instead of `EENABLE_QUAD_PRECISION`
---
> fftw: fix typo in quad precision CMake option

- recipes/ccfits/all/conanfile.py
The project uses
https://spdx.org/licenses/CFITSIO.html
not the currently set
https://spdx.org/licenses/ISC.html
> ccfits: use a more accurate license identifier

- recipes/fltk/all/conanfile.py
Adds FLTK-exceptio: https://spdx.org/licenses/FLTK-exception.html
See https://github.com/fltk/fltk/blob/master/COPYING#L1-L45
> fltk: use a more accurate license identifier

- recipes/openjdk/all/conanfile.py
Adds
https://spdx.org/licenses/OpenJDK-assembly-exception-1.0.html
https://spdx.org/licenses/Classpath-exception-2.0.html
See also https://openjdk.org/legal/
Sorry about the clunky license ID. There is no valid way to strictly specify more than one exception using a SPDX license expression.
> openjdk: use a more specific license identifier

- recipes/qt/6.x.x/conanfile.py
It requires `Quick`, as the name suggests
see also https://github.com/qt/qtdeclarative/blob/v6.6.0/src/qmltest/CMakeLists.txt#L44
CC @petermbauer
fixes https://github.com/conan-io/conan-center-index/issues/17743
fixes https://github.com/conan-io/conan-center-index/issues/17977
fixes https://github.com/conan-io/conan-center-index/issues/21231
fixes https://github.com/conan-io/conan-center-index/issues/20921
---
> qt6: fix QuickTest declaration

- recipes/stb/all/conanfile.py
There is a `with_deprecated` option in stb recipe, and this option controls whether some headers are packaged or not, so stb recipe can't clear info.options in package_id().
---
> stb: add package_type + fix package id

- recipes/trantor/all/conanfile.py
> trantor: remove legacy output.warn in order to properly support conan v2 + bump c-ares

- recipes/wt/all/conanfile.py
These `*_PREFIX` variables were broken because `_cmakify_path_list()` expects a list, and sometimes a string was passed, so each character was split:
```
CMake Warning (dev) at cmake/WtFindBoost.txt:64 (find_package):
Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
CMake variable BOOST_ROOT is set to:
/;U;s;e;r;s;/;s;p;a;c;i;m;/;.;c;o;n;a;n;2;/;p;/;b;/;b;o;o;s;t;d;c;2;f;5;9;d;0;f;d;6;c;a;/;p
For compatibility, find_package is ignoring the variable, but code in a
.cmake module might still use it.
Call Stack (most recent call first):
cmake/WtFindBoost.txt:79 (find_boost_system)
CMakeLists.txt:242 (INCLUDE)
```
---
> wt: fix `*_PREFIX` variables passed to CMakeToolchain + bump sqlite3

- recipes/glfw/all/conanfile.py
- do not required xorg if not Linux or FreeBSD (regression of https://github.com/conan-io/conan-center-index/pull/20913)
- update required_conan_version due to host_version in build requirements
- fix version comparison in CMake variables logic
- do not add wayland in build requirements if 1 profile
---
> glfw: fix regressions introduced by #20913

- recipes/replxx/all/conandata.yml
- recipes/replxx/all/conanfile.py
- recipes/replxx/all/patches/0.0.3-0001-fix-export-symbols-windows.patch
- recipes/replxx/all/patches/0.0.4-0001-fix-export-symbols-windows.patch
- recipes/replxx/config.yml
- Fix MinGW shared. There were link errors in examples (they were not disabled in 0.0.3 & 0.0.4) due to bad export of symbols: `ld.exe: CMakeFiles/replxx-example-cxx-api.dir/examples/cxx-api.cxx.obj:cxx-api.cxx:(.text+0x17e1): undefined reference to 'replxx::color::bold(replxx::Replxx::Color)'`. Actually all the export logic for Windows was a little bit messy.
**I still need to test these patches (submitted upstream https://github.com/AmokHuginnsson/replxx/pull/151), but I'm not on Windows currently.**
- remove maintenance of 0.0.2
- disable build of examples in versions >= 0.0.3
- fix lib name in `cpp_info.libs` if build_type `RelWithDebInfo`, there is a `-rd` suffix: https://github.com/AmokHuginnsson/replxx/blob/release-0.0.4/CMakeLists.txt#L117
- explicit cmake names: …
> replxx: fix MinGW shared + remove old version + fix cpp_info.libs for RelWithDebInfo

- recipes/libvpx/all/conandata.yml
- recipes/libvpx/all/conanfile.py
- recipes/libvpx/config.yml
`libvpx` is a dependency of `ffmpeg` (optional but enabled by default), therefore v2 pipeline can't build `ffmpeg` shared for msvc because `libvpx` with `shared=True` raises for Windows. And as a consequence, it also prevents v2 pipeline to build shared flavor of downstream packages of `ffmpeg`, like `opencv`.
Therefore this PR removes shared option of `libvpx` if Windows, so that v2 pipeline can build downstream packages with `-o *:shared=True`.
It's the same rational as https://github.com/conan-io/conan-center-index/pull/17228 or https://github.com/conan-io/conan-center-index/pull/21144
---
> libvpx: add 1.13.1 + remove shared option and set package_type to static-library if Windows instead of raising for shared=True

- recipes/aws-c-event-stream/all/conandata.yml
- recipes/aws-c-event-stream/config.yml
Specify library name and version:  **aws-c-event-stream/0.3.2**
---
> aws-c-event-stream: add version 0.3.2

- recipes/ms-gsl/all/conanfile.py
remove this `self.output.warn` (conan v1, not compatible with conan v2)
---
> ms-gsl: remove conan v1 warning for unknown compilers

- recipes/exiv2/all/conanfile.py
Specify library name and version:  **exiv2**
Follow up from https://github.com/conan-io/conan/issues/15065, fixing ``provides`` definition
---
> fix exiv2 provides

- recipes/onetbb/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/21315
see https://github.com/oneapi-src/oneTBB/blob/a71747cd869882e51cec231d822c5f31ed70da71/cmake/hwloc_detection.cmake#L48-L64
---
> onetbb: don't require pkgconf when tbbbind is disabled

- recipes/pcl/all/conanfile.py
Specify library name and version:  **qhull/1.13.1**
The exported `pcl_config.h` is not following the requested package options:
https://github.com/PointCloudLibrary/pcl/blob/pcl-1.13.1/pcl_config.h.in#L41
Let's export those defines directly. 
fixes #21290
/cc @DevlBert
---
> [pcl] Hotfix: export qhull define

- recipes/capnproto/all/conanfile.py
follow up https://github.com/conan-io/conan-center-index/pull/18983#issuecomment-1823852552
I've refactored components logic, so that we can more easily extend conditionally each component.
---
> capnproto: remove zlib from dependencies of kj-http before 1.0.0

- recipes/qarchive/all/conandata.yml
- recipes/qarchive/config.yml
Specify library name and version:  **qarchive/2.2.8**
---
> qarchive: add version 2.2.8

- recipes/libhal/all/conandata.yml
- recipes/libhal/all/conanfile.py
- recipes/libhal/config.yml
Specify library name and version:  **libhal/2.0.0**
Boost does not work as a dependency for baremetal platforms. Boost-leaf must be used for `libhal/[^2.0.0]` 
---
> libhal: Correct 2.0.1 dependency on conan center

- recipes/openssl/3.x.x/conandata.yml
- recipes/openssl/config.yml
Specify library name and version:  **openssl/3.2.0**
---
> openssl: add 3.2.0

- recipes/pcl/all/conanfile.py
properly address https://github.com/conan-io/conan-center-index/issues/21290
see https://github.com/conan-io/conan-center-index/pull/21325#issuecomment-1825853655
And regarding HAVE_PNG and HAVE_CUDA, they were already properly defined when needed in pcl_configure.h, so no fix is needed at all for those dependencies.
---
> pcl: properly configure pcl_configure.h regarding qhull

- recipes/libhal/all/conanfile.py
- recipes/libhal/all/test_package/test_package.cpp
libhal 2.Y.Z requires tl-function-ref as well as boost-leaf.
Specify library name and version:  **libhal/***
---
> Add missing requirement for libhal

- recipes/foxglove-websocket/all/conandata.yml
- recipes/foxglove-websocket/config.yml
Specify library name and version:  **foxglove-websocket/1.2.0**
---
> foxglove-websocket: Add version 1.2.0

- recipes/cpp-lazy/all/conanfile.py
explicit cmake names since there is a config file upstream: https://github.com/MarcDirven/cpp-lazy/blob/5ee8d81ba6ccaa808a97c0ac1c1eb9431d38a149/CMakeLists.txt#L122-L129
---
> cpp-lazy: add package_type & explicit cmake names

- recipes/pulseaudio/all/conanfile.py
Specify library name and version:  **pulseaudio/any**
The PR #20888 adds support for multiple precision, but we needed to update its options too.
---
> [pulseaudio] Update fftw options

- recipes/harfbuzz/all/conanfile.py
Specify library name and version:  **harfbuzz/all**
Before #13942 (switch from cmake to meson), CoreText was always enabled on macOS.
Meson is the official way to build and has CoreText disabled by default. The CMake build had a default of enabling CoreText on macOS.
This PR adds the option to enable/disable CoreText with the default being to enable it (which differs from the official default).
Why enabled by default: the pango recipe being ported to v2 in multiple PRs requires harfbuzz to be built with CoreText enabled (c.f. the v2 build logs in https://github.com/conan-io/conan-center-index/pull/20795#issuecomment-1788139568).
I couldn't get pango to build on macOS by disabling CoreText (by patching pango). While this might be doable, I won't have the time to investigate this option and …
> harfbuzz: add with_coretext option

- recipes/modern-cpp-kafka/all/conanfile.py
- recipes/modern-cpp-kafka/all/test_package/CMakeLists.txt
- recipes/modern-cpp-kafka/all/test_v1_package/CMakeLists.txt
- do not invent unofficial target name (there is no config file upstream, and the target name representing interface lib in their CMakeLists is not even the same as suggested in this recipe)
- empty cpp_info.bindirs & libdirs
- bump librdkafka
---
> modern-cpp-kafka: add package_type + reset cmake names to default value

- recipes/harfbuzz/all/conanfile.py
Specify library name and version:  **harfbuzz/all**
This addresses the comment https://github.com/conan-io/conan-center-index/pull/20870#issuecomment-1836088235 by @SpaceIm 
Apple frameworks are only used when `with_coretext=True`.
On macOS, harfbuzz links against the ApplicationServices framework.
For other Apple OS, it links against CoreFoundation, CoreGraphics & CoreText frameworks.
---
> harfbuzz: fix frameworks used in package_info

- recipes/minizip-ng/all/conanfile.py
Specify library name and version:  **minizip-ng**
Upgrading the xz_utils requirement to match the requirement of libtiff, as I can't build other recipes without a force version override, as both minizip-ng and libtiff are in the dependency graph
Would be curious why normally versions are fully defined for all dependencies on conan-center-index besides zlib which everywhere seems to use a version range now.
---
> minizip-ng: Update xz_utils requirements

- recipes/ffmpeg/all/conanfile.py
Specify library name and version:  **ffmpeg**
Upgrading the xz_utils requirement to match the requirement of libtiff, as I can't build other recipes without a force version override, as both ffmpeg and libtiff are in the dependency graph
---
> ffmpeg: Update xz_utils requirements

- recipes/very-simple-smtps/all/conanfile.py
Specify library name and version:  **very-simple-smtps/all**
---
> very-simple-smtps: use version range for libcurl

- recipes/exiv2/all/conanfile.py
Specify library name and version:  **exiv2/all**
---
> exiv2: bump deps, use version range for libcurl

- recipes/ulfius/all/conanfile.py
Specify library name and version:  **ulfius/all**
---
> ulfius: use version range for libcurl

- recipes/coost/all/conanfile.py
Specify library name and version:  **coost/all**
---
> coost: use version range for libcurl

- recipes/sentry-crashpad/all/conanfile.py
Specify library name and version:  **sentry-crashpad/all**
---
> sentry-crashpad: use version range for libcurl

- docs/changelog.md
Latest changes introduced in the build service
> [docs] Add changelog 05-December-2023

- recipes/libbpf/all/conandata.yml
- recipes/libbpf/all/conanfile.py
- recipes/libbpf/config.yml
**libbpf/1.1.0**
- The dependency on libelf has been replaced with elfutils v0.180, improving compatibility and ensuring a more streamlined build process.
- The linux-headers-generic version has been bumped to v5.15.128 LTS version.
- Add option to install UAPI headers, providing greater flexibility for users who require bpf UAPI headers.
---
> Add version libbpf v1.1.0, replace libelf dependency, bump linux-headers-generic, and add UAPI headers installation option

- recipes/teemo/all/conandata.yml
- recipes/teemo/all/conanfile.py
Specify library name and version:  **teemo/***
teemo has been renamed to zoe.
---
> teemo: make deprecate

- recipes/waf/all/conandata.yml
- recipes/waf/all/conanfile.py
- recipes/waf/all/test_package/conanfile.py
- recipes/waf/all/test_v1_package/conanfile.py
- recipes/waf/config.yml
> waf: migrate to Conan v2

- recipes/perfetto/all/conandata.yml
- recipes/perfetto/config.yml
Specify library name and version:  **perfetto/40.0**
```
v40.0 - 2023-12-04:
* Added support for collecting battery voltage from the Android Power HAL.
* Added support for emitting machine id from producers on remote hosts.
* Added of flow id from trace as a column in the flow table.
* Fixed computation of trace_bounds table when using UI native acceleration.
UI:
* Switched to use "v2" querying and rendering system for tracks by default.
```
---
> perfetto: Bump version: 40.0

- recipes/opengl-registry/all/conanfile.py
We package xml files in res dir, so set cpp_info.resdirs accordingly.
---
> opengl-registry: add package_type and set cpp_info.resdirs

- recipes/r8brain-free-src/all/conandata.yml
- recipes/r8brain-free-src/config.yml
Specify library name and version:  **r8brain-free-src/6.5**
---
> r8brain-free-src: add version 6.5

- recipes/zxing-cpp/all/conandata.yml
- recipes/zxing-cpp/config.yml
Specify library name and version:  **zxing-cpp/2.2.1**
I'm the maintainer of this library and just released a new version. It includes bug fixes and new support for QRCode Model 1 and rMQRCode symbols.
I'm not a conan user myself and hence, I did not test anything related to this conan packaging.
---
> zxing-cpp: add version 2.2.1

- recipes/ceres-solver/all/conanfile.py
Specify library name and version:  **ceres-solver/***
Closes: https://github.com/conan-io/conan-center-index/issues/21715
`ceres-solver` uses the `IOS_DEPLOYMENT_TARGET` cmake variable to verify that the iOS version is higher than 7.
Indeed, the CMakeLists.txt does not include the iOS.cmake toolchain so it's up to the consumer to include that one as the official documentation reads http://ceres-solver.org/installation.html#ios
> [fix][ceres-solver] Added IOS_DEPLOYMENT_TARGET variable

- recipes/directshowbaseclasses/all/CMakeLists.txt
- recipes/directshowbaseclasses/all/conanfile.py
- recipes/directshowbaseclasses/all/test_package/CMakeLists.txt
- recipes/directshowbaseclasses/all/test_package/conanfile.py
- recipes/directshowbaseclasses/all/test_v1_package/CMakeLists.txt
- recipes/directshowbaseclasses/all/test_v1_package/conanfile.py
> directshowbaseclasses: migrate to Conan v2

- recipes/glaze/all/conandata.yml
- recipes/glaze/all/conanfile.py
- recipes/glaze/config.yml
> glaze: add version 1.9.5, remove older versions, relax gcc version check

- recipes/readline/all/conanfile.py
Specify library name and version:  **readline/all**
The issue could be reproduced with the following build options:
```
conan create . --version 8.1.2 -o with_library=curses -o shared=True
```
Fixes the following build error:
```
gcc -shared -Wl,-soname,libreadline.so.8.1 -m64 -L/opt/conan/p/ncursd4659b2179361/p/lib -Wl,-rpath,//lib -Wl,-soname,`basename libreadline.so.8.1 .1` -o libreadline.so.8.1 readline.so vi_mode.so funmap.so keymaps.so parens.so search.so rltty.so complete.so bind.so isearch.so display.so signals.so util.so kill.so undo.so macro.so input.so callback.so terminal.so text.so nls.so misc.so history.so histexpand.so histfile.so histsearch.so shell.so mbutil.so tilde.so colors.so parse-colors.so xmalloc.so xfree.so compat.so  -ltermcap …
```
> readline: fix build with shared ncurses

- recipes/whisper-cpp/all/conandata.yml
- recipes/whisper-cpp/all/conanfile.py
- recipes/whisper-cpp/config.yml
Specify library name and version:  **whisper-cpp/1.4.3**
Will add the new patch version for whisper-cpp: https://github.com/ggerganov/whisper.cpp/releases/tag/v1.4.3
---
> whisper-cpp: add version 1.4.3

- recipes/quill/all/conandata.yml
- recipes/quill/config.yml
Specify library name and version:  **quill/3.6.0**
---
> quill: add version 3.6.0

- recipes/libatomic_ops/all/conandata.yml
- recipes/libatomic_ops/config.yml
Specify library name and version: libatomic_ops/7.8.2
* update package version from 7.8.0 to 7.8.2
I'm maintainer of libatomic_ops upstream; v7.8.2 has been released recently - it contains a number of bug fixes.
---
> libatomic_ops: update to 7.8.2

- recipes/tcl/all/conanfile.py
I've tried to build tcl with MinGW, and there was several issues:
- Value passed to `build_script_folder` of `Autotools.configure()` was an absolute path, while it should be a relative path. It leads to a duplicate root symbol `//` for *nix platforms, which is not a big deal, but for windows you get something like `/c/c` which doesn't exist.
- Once fixed, there was another error because custom `prefix` passed to `Autotoolschain` was not converted with unix_path, leading very quickly to a configure error since paths separators were stripped out. I've fixed this by simply removing this custom `prefix`, it doesn't play well to mix up `prefix` and `DESTDIR` with the same absolute path anyway (it would have lead to other issues for mingw also, like files installed in weird locations).
- Once …
> tcl: fix MinGW and properly split build and install in autotools branch

- recipes/b2/config.yml
- recipes/b2/portable/conandata.yml
- recipes/b2/portable/conanfile.py
The `b2` recipe cannot be currently cross-built because `b2 install` is called immediately after building it - thus, it needs to be able to run it. We are working towards upgrading all mac CI build agents to Apple Silicon - and we don't want to lose the ability to generate the x86_64 binaries for this package.
This PR tweaks the recipe such that on macOS the binary is built targeting both architectures (`x86_64` and `armv8`) - which would give us working binaries for armv8 (which we don't currently have), and will continue being able to produce them after the CI agents are upgraded.
There are more possible solutions:
* require a compatible version of the b2 executable only when crossbuilding (a tool requires on  itself) 
* re-implement the logic of `b2 install`, but in python - looks …
> b2: build universal binary with intel and arm

- recipes/opencv/3.x/conandata.yml
- recipes/opencv/config.yml
Specify library name and version:  **opencv/3.4.20**
the current 3.x version (3.4.17) doesn't compile with GCC12
---
> opencv/3.x add version 3.4.20

- recipes/cpp-sort/all/conanfile.py
> cpp-sort: remove legacy conan v1 output.warn which breaks conan v2 with "unknown compilers"

- recipes/arsenalgear/all/conandata.yml
- recipes/arsenalgear/all/conanfile.py
- recipes/arsenalgear/all/patches/2.1.0-0001-fix-cmake.patch
- Restore shared option, it has been removed by https://github.com/conan-io/conan-center-index/pull/16264, but I think it was a mistake. Moreover removing shared option leads to missing arsenalgear packages for osmanip (see https://github.com/conan-io/conan-center-index/pull/19882#issuecomment-1819891094 & https://github.com/conan-io/conan-center-index/issues/21283)
- Allow msvc since 2.1.0, it seems to build fine (I've tested with 2.0.1, and it didn't pass, so only since 2.1.0)
- We use upstream CMakeLists since 2.1.0, but it has several issues (build & download doctest, pollutes install dir with doctest headers, doesn't honor compiler.cppstd, don't allow to build shared while it works just fine). So I've added a patch and submitted a PR upstream: …
> arsenalgear: restore shared option + allow msvc since 2.1.0 + fix CMakeLists of 2.1.0 to avoid building and packaging doctest

- recipes/libiconv/all/conanfile.py
**libiconv/1.17**
Create a patch to resolve this x86 libiconv build error:
`libiconv.res.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'`
Close https://github.com/conan-io/conan-center-index/issues/20689
> libiconv: apply x86 resource patch

- recipes/re2c/all/conanfile.py
- recipes/re2c/all/test_package/CMakeLists.txt
- recipes/re2c/all/test_package/syntax.re
Specify library name and version:  **re2c/***
Problem: Current recipe for re2c does not provide stdlib for this tool. 
---
> re2c: Add RE2C_STDLIB_DIR variable with re2c stdlib

- recipes/restinio/v0.7/conanfile.py
Specify library name and version:  **restinio/0.7**
Enable compilation with Visual Studio 2019 which supports C++17.
---
- [ x] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [ x] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [x ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
> (#21870) restinio/0.7: build with Visual Studio 2019 

- recipes/commata/all/conandata.yml
- recipes/commata/all/conanfile.py
- recipes/commata/all/patches/0.2.7-0001-include-optional.patch
Specify library name and version:  **commata/0.2.7**
This PR is to create a patch file instead of using `replace_in_file`.
---
> commata: create patch file for 0.2.7

- recipes/bzip2/all/conanfile.py
The current one (http://www.bzip.org) does not look legitimate. Replaced it with https://sourceware.org/bzip2
> bzip2: fix project URL

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/1.3.1**
---
> meson: add version 1.3.1

- recipes/libzen/all/patches/0002-export-data-in-windows-dlls.patch
Patch `0002-export-data-in-windows-dlls.patch` was broken. msvc didn't complain, but MinGW did.
---
> libzen: fix build of shared lib with MinGW

- recipes/boost-ext-ut/all/conandata.yml
- recipes/boost-ext-ut/config.yml
Specify library name and version:  **boost-ext-ut/2.0.1**
Add version 2.0.1.
---
> boost-ext-ut: Add version 2.0.1

- recipes/minizip-ng/all/conandata.yml
- recipes/minizip-ng/config.yml
Specify library name and version:  **minizip-ng/4.0.4**
---
> minizip-ng: add version 4.0.4

- recipes/catch2/3.x.x/conandata.yml
- recipes/catch2/config.yml
Specify library name and version:  **catch2/3.5.1**
---
> catch2: add version 3.5.1

- recipes/gperftools/all/conandata.yml
- recipes/gperftools/config.yml
Specify library name and version:  **gperftools/2.14.0**
---
> gperftools: add version 2.14.0

- recipes/trompeloeil/all/conandata.yml
- recipes/trompeloeil/config.yml
Specify library name and version:  **trompeloell/47**
---
> trompeloell: add version 47

- recipes/cuda-api-wrappers/all/conandata.yml
- recipes/cuda-api-wrappers/config.yml
See issue #22071 ; this removes the use of the beta as a regular version.
If it can, instead, be marked as a beta and kept, that would be better - please advise on how to do that.
FYI: I also plan to submit a PR with _actual_ newer non-beta releases, and an update of the package's meta-data in the recipe, independently of this one.
---
- [YES] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [N/A] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [N/A] I've tried at least one configuration locally with the [conan-center …
> Remove cuda-api-wrappers/0.7

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/config.yml
Specify library name and version:  **libxml2/all**
search all recipe usage with:
`find recipes -name 'conanfile.py' -exec grep 'libxml2/' {} +`
Can't remove more versions for now (especially old ones), it will have to wait for #20992 to be completed.
---
> libxml2: remove unused versions

- recipes/libtiff/all/conandata.yml
The conandata.yml files in this git repo contains 6411 https:// uris and 109 http:// uris. There is no reason not to use https with the libtiff downloads from download.osgeo.org and some organizations block http:// file transfers for security reasons.
---
> libtiff: use https for download

- recipes/xorg/all/conanfile.py
xvmc is the X-Video Motion Compensation API client library. The xvmc library is not referenced in any other package in
conan-center-index. The libXvMC-devel has unceremoniously been removed from RHEL 9. A github search for xvmc finds 15 repositories and not one of them seem to be an important consuming application of this API. libxcb-devel contains libxcb-xvmc.so which provides an XCB based API.
As the xvmc library is unused in conan-center-index, appears to be nearly unreferenced in github and has been removed from a major distribution it should not be included in xorg/system either so xorg/system can be built on RHEL 9.
Documentation for the removal of libXvMC in RHEL 9:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/considerations_in_adopting_rhel_9 …
> xorg: remove xvmc as dependency

- recipes/libmysqlclient/all/conanfile.py
Specify library name and version:  **libmysqlclient/8.1.0**
There is no official CMake file for mysql client library, so each project consume mysql headers or using "mysql/mysql.h" or "mysql.h" directly.
This PR provides the option of including the header directly. The Poco project uses on that way and we need to use patches to fix it. 
Related to https://github.com/conan-io/conan-center-index/pull/21879/files#diff-359080320353606291963031f9c2e4ccc955802bd4ea9232fcbed7577843ba36
/cc @toge 
---
> [libmysqlclient] Add include/mysql directory
