conan-io/conan-center-index

recipes/libyuv/all/conanfile.py
Specify library name and version:  **libyuv/***
---
=> libyuv: update libjpeg-turbo/3.0.0

recipes/quill/all/conandata.yml, recipes/quill/all/test_package/CMakeLists.txt, recipes/quill/all/test_package/test_package.cpp, recipes/quill/config.yml
Specify library name and version:  **quill/3.3.1**
---
=> quill: add version 3.3.1

recipes/proj/all/conanfile.py
Specify library name and version:  **proj/9.2.1**
Required by #16613
---
=> [proj] Bump libcurl version

recipes/cmake/binary/conandata.yml, recipes/cmake/config.yml
Specify library name and version:  **cmake/3.27.1**
---
=> cmake: add 3.27.1

recipes/sentry-crashpad/all/conanfile.py
=> [sentry-breakpad] bump libcurl to 8.2.0

recipes/libgeotiff/all/conanfile.py
Specify library name and version:  **libgeotiff/all**
---
=> libgeotiff: bump deps

recipes/libsvtav1/all/conandata.yml, recipes/libsvtav1/config.yml
=> Add libsvtav1/1.6.0

recipes/leptonica/all/conandata.yml, recipes/leptonica/all/conanfile.py, recipes/leptonica/config.yml
Specify library name and version:  **leptonica/1.83.1**
---
=> leptonica: add version 1.83.1, update libjpeg-turbo

recipes/cargs/all/CMakeLists.txt, recipes/cargs/all/conanfile.py, recipes/cargs/all/test_package/CMakeLists.txt, recipes/cargs/all/test_package/conanfile.py, recipes/cargs/all/test_v1_package/CMakeLists.txt, recipes/cargs/all/test_v1_package/conanfile.py
=> cargs: migrate to Conan v2

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.37.3**
---
=> etl: add version 20.37.3

recipes/fpzip/all/conandata.yml, recipes/fpzip/all/conanfile.py, recipes/fpzip/all/test_package/CMakeLists.txt, recipes/fpzip/all/test_package/conanfile.py, recipes/fpzip/all/test_package/test_package.c, recipes/fpzip/config.yml
Specify library name and version:  **fpzip/1.3.0**
---
=> fpzip: add recipe

recipes/libmysqlclient/all/conandata.yml, recipes/libmysqlclient/all/patches/0006-fix-cpp20-build-8.1.0.patch, recipes/libmysqlclient/config.yml
Specify library name and version:  **libmysqlclient/8.1.0**
---
=> libmysqlclient: add version 8.1.0

recipes/freetype/all/conanfile.py
=> [freetype] Bump requirements for libpng and zlib

recipes/libde265/all/conandata.yml, recipes/libde265/all/conanfile.py, recipes/libde265/config.yml
=> Add libde265/1.0.12

recipes/mongo-cxx-driver/all/conandata.yml, recipes/mongo-cxx-driver/all/conanfile.py, recipes/mongo-cxx-driver/all/patches/3.8.0-0001-dirs.patch, recipes/mongo-cxx-driver/config.yml
Specify library name and version:  **mongo-cxx-driver/***
---
=> mongo-cxx-driver: add version 3.8.0, update mongo-c-driver

recipes/fusepp/all/CMakeLists.txt, recipes/fusepp/all/conanfile.py, recipes/fusepp/all/test_package/CMakeLists.txt, recipes/fusepp/all/test_package/conanfile.py, recipes/fusepp/all/test_v1_package/CMakeLists.txt, recipes/fusepp/all/test_v1_package/conanfile.py
=> fusepp: migrate to Conan v2

recipes/etc2comp/all/CMakeLists.txt, recipes/etc2comp/all/conandata.yml, recipes/etc2comp/all/conanfile.py, recipes/etc2comp/all/test_package/CMakeLists.txt, recipes/etc2comp/all/test_package/conanfile.py, recipes/etc2comp/all/test_v1_package/CMakeLists.txt, recipes/etc2comp/all/test_v1_package/conanfile.py
=> etc2comp: migrate to Conan v2

recipes/sol2/all/conandata.yml, recipes/sol2/all/conanfile.py, recipes/sol2/config.yml
Specify library name and version:  **sol2/***
---
=> sol2: add version 3.3.1, add package_type, update lua

recipes/ctre/all/conandata.yml, recipes/ctre/all/conanfile.py, recipes/ctre/config.yml
Specify library name and version:  **ctre/3.8**
---
=> ctre: add version 3.8, add package_type

recipes/hictk/all/conandata.yml, recipes/hictk/all/conanfile.py, recipes/hictk/all/test_package/CMakeLists.txt, recipes/hictk/all/test_package/conanfile.py, recipes/hictk/all/test_package/test_package.cpp, recipes/hictk/config.yml
Specify library name and version:  **hictk/0.0.1**
---
=> hictk: new recipe

recipes/rtmidi/all/conandata.yml, recipes/rtmidi/all/conanfile.py, recipes/rtmidi/config.yml
=> [rtmidi/6.0.0] Add version

recipes/blend2d/all/conandata.yml, recipes/blend2d/all/patches/0.10-0001-disable-embed-asmjit.patch, recipes/blend2d/config.yml
Specify library name and version:  **blend2d/0.10**
---
=> blend2d: add version 0.10

recipes/libmpdclient/all/conandata.yml, recipes/libmpdclient/all/conanfile.py, recipes/libmpdclient/all/test_package/CMakeLists.txt, recipes/libmpdclient/all/test_package/conanfile.py, recipes/libmpdclient/all/test_package/test_package.c, recipes/libmpdclient/all/test_v1_package/CMakeLists.txt, recipes/libmpdclient/all/test_v1_package/conanfile.py, recipes/libmpdclient/config.yml
=> Add new recipe: libmpdclient/2.20

recipes/bandit/all/conanfile.py
=> [bandit] Add transitive headers for snowhouse

recipes/bzip3/all/conandata.yml, recipes/bzip3/all/conanfile.py, recipes/bzip3/config.yml
Specify library name and version:  **bzip3/***
---
=> bzip3: add version 1.3.2, remove older versions

recipes/args-parser/all/conandata.yml, recipes/args-parser/config.yml
Specify library name and version:  **args-parser/6.3.3**
---
=> args-parser: bump version

recipes/fmt/all/conandata.yml, recipes/fmt/config.yml
Specify library name and version:  **fmt/10.1.0**
---
=> fmt: add version 10.1.0

recipes/fakeit/all/conanfile.py, recipes/fakeit/all/test_package/CMakeLists.txt
Specify library name and version:  **fakeit/***
Try to fix https://github.com/conan-io/conan-center-index/issues/18532.
And with small improvements.
---
=> fakeit: make bindirs and libdirs empty, update dependencies

recipes/quill/all/conanfile.py
=> quill: update fmt/10.1.0

recipes/date/all/conanfile.py
Specify library name and version:  **date/all**
---
=> date: update libcurl

recipes/mppp/all/conanfile.py
Specify library name and version:  **mppp/***
---
=> mppp: update dependencies

recipes/pngpp/all/conanfile.py
Specify library name and version:  **pngpp/all**
---
=> pngpp: update libpng

recipes/blend2d/all/conandata.yml, recipes/blend2d/config.yml
Specify library name and version:  **blend2d/0.10.4**
---
=> blend2d: add version 0.10.4

recipes/fmtlog/all/conanfile.py
Specify library name and version:  **fmtlog/***
---
=> fmtlog: update fmt/10.1.0

recipes/jinja2cpp/all/conanfile.py
Specify library name and version:  **jinja2cpp/***
---
=> jinja2cpp: update fmt/10.1.0

recipes/maven/all/conandata.yml, recipes/maven/config.yml
Specify library name and version:  **maven/3.9.4**
---
=> maven: add version 3.9.4

recipes/cppcommon/all/conanfile.py
Specify library name and version:  **cppcommon/***
---
=> cppcommon: update fmt/10.1.0

recipes/rgbcx/all/conanfile.py, recipes/rgbcx/all/test_package/CMakeLists.txt, recipes/rgbcx/all/test_package/conanfile.py, recipes/rgbcx/all/test_package/test_package.cpp, recipes/rgbcx/all/test_v1_package/CMakeLists.txt, recipes/rgbcx/all/test_v1_package/conanfile.py
=> rgbcx: migrate to Conan v2

recipes/nodesoup/all/CMakeLists.txt, recipes/nodesoup/all/conandata.yml, recipes/nodesoup/all/conanfile.py, recipes/nodesoup/all/test_package/CMakeLists.txt, recipes/nodesoup/all/test_package/conanfile.py
Specify library name and version:  **nodesoup/cci.20200905**
Update recipe to Conan v2
---
=> Update nodesoup to conan v2

recipes/onetbb/all/conanfile.py
Specify library name and version:  **onetbb/2021.10.0**
---
=> onetbb: set package_type

recipes/xbyak/all/conandata.yml, recipes/xbyak/all/conanfile.py, recipes/xbyak/config.yml
Specify library name and version:  **xbyak/6.73**
---
=> xbyak: add version 6.73, add package_type

recipes/libpq/all/conandata.yml, recipes/libpq/all/conanfile.py, recipes/libpq/config.yml
Also update the openssl dependency, >=13.5 builds with openssl 3.x: https://bugs.launchpad.net/ubuntu/+source/postgresql-13/+bug/1946013
=> libpq: add 15.4

recipes/utfcpp/all/conandata.yml, recipes/utfcpp/config.yml
Specify library name and version:  **utfcpp/3.2.4**
Add new version 3.2.4.
---
=> utfcpp: add 3.2.4

recipes/json-c/all/conandata.yml, recipes/json-c/config.yml
Specify library name and version:  **json-c/0.17**
---
=> json-c: add version 0.17

recipes/onnxruntime/all/conanfile.py, recipes/onnxruntime/all/patches/1.14.1-0002-cmake-dependencies.patch, recipes/onnxruntime/all/patches/1.15.1-0001-cmake-dependencies.patch
Specify library name and version:  **onnxruntime/all**
---
=> onnxruntime: bump deps

recipes/cotila/all/conanfile.py, recipes/cotila/all/test_package/CMakeLists.txt, recipes/cotila/all/test_package/conanfile.py, recipes/cotila/all/test_v1_package/CMakeLists.txt, recipes/cotila/all/test_v1_package/conanfile.py
=> cotila: migrate to Conan v2

recipes/immer/all/conandata.yml, recipes/immer/all/conanfile.py, recipes/immer/all/test_package/CMakeLists.txt, recipes/immer/all/test_package/conanfile.py, recipes/immer/all/test_package/example.cpp, recipes/immer/all/test_v1_package/CMakeLists.txt, recipes/immer/all/test_v1_package/conanfile.py, recipes/immer/config.yml
=> immer: migrate to Conan v2

recipes/fpgen/all/conandata.yml, recipes/fpgen/all/conanfile.py, recipes/fpgen/all/test_package/CMakeLists.txt, recipes/fpgen/all/test_package/conanfile.py, recipes/fpgen/all/test_package/main.cpp, recipes/fpgen/all/test_v1_package/CMakeLists.txt, recipes/fpgen/all/test_v1_package/conanfile.py, recipes/fpgen/config.yml
=> fpgen: migrate to Conan v2

recipes/rangeless/all/conanfile.py, recipes/rangeless/all/test_package/CMakeLists.txt, recipes/rangeless/all/test_package/conanfile.py, recipes/rangeless/all/test_package/test_package.cpp, recipes/rangeless/all/test_v1_package/CMakeLists.txt, recipes/rangeless/all/test_v1_package/conanfile.py
=> rangeless: migrate to Conan v2

recipes/plusaes/all/conanfile.py, recipes/plusaes/all/test_package/CMakeLists.txt, recipes/plusaes/all/test_package/conanfile.py, recipes/plusaes/all/test_v1_package/CMakeLists.txt, recipes/plusaes/all/test_v1_package/conanfile.py
=> plusaes: migrate to Conan v2

recipes/openssl/1.x.x/conandata.yml, recipes/openssl/3.x.x/conandata.yml, recipes/openssl/config.yml
=> openssl: add 1.1.1v, 3.0.10, 3.1.2

recipes/trompeloeil/all/conandata.yml, recipes/trompeloeil/all/conanfile.py, recipes/trompeloeil/config.yml
Specify library name and version:  **trompeloeil/***
Try to solve https://github.com/conan-io/conan-center-index/issues/18879.
---
=> trompeloeil: add version 45

recipes/gperftools/all/conandata.yml, recipes/gperftools/all/conanfile.py, recipes/gperftools/all/test_package/CMakeLists.txt, recipes/gperftools/config.yml
Specify library name and version:  **gperftools/2.11.0**
---
=> gperftools: add version 2.11.0

recipes/plusaes/all/conandata.yml, recipes/plusaes/config.yml
Specify library name and version:  **plusaes/1.0.0**
---
=> plusaes: add version 1.0.0

recipes/s2n/all/conandata.yml, recipes/s2n/config.yml
Specify library name and version:  **s2n/1.3.49**
---
=> s2n: add version 1.3.49

recipes/angelscript/all/conandata.yml, recipes/angelscript/config.yml
First draft for updating angelscript
(Maybe we need the last patch again)
Specify library name and version:  **angelscript/2.36.1**
fixes #19243
---
=> [package] angelscript/2.36.1 (Update)

recipes/maven/all/conandata.yml, recipes/maven/all/conanfile.py, recipes/maven/config.yml
Based on https://repology.org/repository/conancenter/problems
=> maven: fix dead URL, bump JDK dep

recipes/harfbuzz/all/conanfile.py
Specify library name and version:  **harfbuzz/all**
As part of the work to get https://github.com/conan-io/conan-center-index/pull/18429 working
=> harfbuzz: Bump dependencies, fix glib tool_requires

recipes/procxx-boost-ext-simd/all/conanfile.py, recipes/procxx-boost-ext-simd/all/test_package/CMakeLists.txt, recipes/procxx-boost-ext-simd/all/test_package/conanfile.py, recipes/procxx-boost-ext-simd/all/test_package/test_package.cpp, recipes/procxx-boost-ext-simd/all/test_v1_package/CMakeLists.txt, recipes/procxx-boost-ext-simd/all/test_v1_package/conanfile.py
=> procxx-boost-ext-simd: migrate to Conan v2

recipes/mozjpeg/all/conandata.yml, recipes/mozjpeg/all/patches/4.1.3-0001-cmake-fixes.patch, recipes/mozjpeg/config.yml
Specify library name and version:  **mozjpeg/4.1.3**
---
=> mozjpeg: add version 4.1.3

recipes/libsndfile/all/conandata.yml, recipes/libsndfile/config.yml
=> [libsnd] Update to 1.2.2

recipes/restinio/all/conandata.yml, recipes/restinio/all/conanfile.py, recipes/restinio/config.yml
Specify library name and version:  **restinio/0.6.19**
Just a regular version update to add the latest.
---
=> restinio: add 0.6.19

recipes/maddy/all/conandata.yml, recipes/maddy/all/conanfile.py, recipes/maddy/all/test_package/CMakeLists.txt, recipes/maddy/config.yml
Specify library name and version:  **maddy/***
---
=> maddy: add version 1.2.1 with several improvements

recipes/nudb/all/conanfile.py
Specify library name and version:  **nudb/***
---
=> nudb: update boost/1.83.0

recipes/nfrechette-acl/all/conandata.yml, recipes/nfrechette-acl/all/conanfile.py, recipes/nfrechette-acl/all/test_package/CMakeLists.txt, recipes/nfrechette-acl/all/test_package/conanfile.py, recipes/nfrechette-acl/all/test_v1_package/CMakeLists.txt, recipes/nfrechette-acl/all/test_v1_package/conanfile.py, recipes/nfrechette-acl/config.yml
=> nfrechette-acl: migrate to Conan v2

recipes/cpp_project_framework/all/conanfile.py, recipes/cpp_project_framework/all/test_package/CMakeLists.txt, recipes/cpp_project_framework/all/test_package/conanfile.py, recipes/cpp_project_framework/all/test_v1_package/CMakeLists.txt, recipes/cpp_project_framework/all/test_v1_package/conanfile.py
=> cpp_project_framework: migrate to Conan v2

recipes/scippp/all/conandata.yml, recipes/scippp/all/conanfile.py, recipes/scippp/all/test_package/CMakeLists.txt, recipes/scippp/all/test_package/conanfile.py, recipes/scippp/all/test_package/test_package.cpp, recipes/scippp/config.yml
Specify library name and version:  **SCIP++/1.0.2**
I am the author of this library. It is based on SCIP which was added to conan-center recently
---
=> Add library SCIP++

recipes/re2/all/conandata.yml, recipes/re2/config.yml
Specify library name and version:  **re2/20230801**
---
=> re2: add version 20230801

recipes/cpp-sort/all/conandata.yml, recipes/cpp-sort/all/conanfile.py, recipes/cpp-sort/config.yml
Specify library name and version:  **cpp-sort/***
---
=> cpp-sort: add version 1.15.0, remove older versions

recipes/restinio/all/conanfile.py
Specify library name and version:  **restinio/0.6.19**
---
=> restinio: bump boost & asio deps

recipes/asio-grpc/all/conanfile.py
Specify library name and version:  **asio-grpc/***
---
=> asio-grpc: update boost/1.83.0

recipes/asyncly/all/conanfile.py
Specify library name and version:  **asyncly/***
---
=> asyncly: update dependencies

recipes/tcl/all/conandata.yml, recipes/tcl/config.yml
Specify library name and version:  **tcl/8.6.13**
---
=> tcl: add version 8.6.13

recipes/boost-leaf/all/conandata.yml, recipes/boost-leaf/config.yml
Specify library name and version:  **boost-leaf/1.83.0**
---
=> boost-leaf: add version 1.83.0

recipes/ftxui/all/conandata.yml, recipes/ftxui/config.yml
Specify library name and version:  **ftxui/5.0.0**
---
=> ftxui: add version 5.0.0

recipes/docopt.cpp/all/conanfile.py
Specify library name and version:  **docopt.cpp/***
---
=> docopt.cpp: update boost/1.83.0

recipes/numcpp/all/conanfile.py
Specify library name and version:  **numcpp/***
---
=> numcpp: update boost/1.83.0

recipes/wt/all/conanfile.py
Specify library name and version:  **wt/***
---
=> wt: update dependencies

recipes/unordered_dense/all/conandata.yml, recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/4.1.0**
---
=> unordered_dense: add version 4.1.0

recipes/mp-units/0.8.0/conanfile.py
Specify library name and version:  **mp-units/***
---
=> mp-units: update dependencies

recipes/mbits-diags/all/conanfile.py
Specify library name and version:  **mbits-diags/***
---
=> mbits-diags: update fmt/10.1.0

recipes/mbits-lngs/all/conanfile.py
Specify library name and version:  **mbits-lngs/***
---
=> mbits-lngs: update fmt/10.1.0

recipes/rtmidi/all/conandata.yml
closes https://github.com/conan-io/conan-center-index/issues/19211
=> rtmidi: fix sha256 of 6.0.0

recipes/trantor/all/conandata.yml, recipes/trantor/all/conanfile.py, recipes/trantor/all/patches/1.5.12-0001-disable-werror.patch, recipes/trantor/config.yml
Specify library name and version:  **trantor/1.5.12**
---
=> trantor: add version 1.5.12

recipes/binutils/all/conandata.yml, recipes/binutils/all/patches/2.41-0001-no-texinfo.patch, recipes/binutils/config.yml
Specify library name and version:  **binutils/2.41**
---
=> binutils: add version 2.41

recipes/svgwrite/all/conanfile.py
Specify library name and version:  **svgwrite/***
---
=> svgwrite: update fmt/10.1.0

recipes/fpgen/all/conanfile.py
To fix the regression in the recipe @SpaceIm pointed out: https://github.com/conan-io/conan-center-index/pull/18243/files#r1296945213
=> fpgen: use lazy_lt_semver() in validate()

recipes/dlib/all/CMakeLists.txt, recipes/dlib/all/conanfile.py, recipes/dlib/all/test_package/CMakeLists.txt, recipes/dlib/all/test_package/conanfile.py, recipes/dlib/all/test_v1_package/CMakeLists.txt, recipes/dlib/all/test_v1_package/conanfile.py
Specify library name and version:  **dlib/19.24**
Required by https://github.com/conan-io/conan-center-index/pull/18457
---
=> [dlib] Port to Conan 2.x

recipes/drogon/all/conandata.yml, recipes/drogon/all/conanfile.py, recipes/drogon/all/patches/1.8.5-0001-remove-shared-libs.patch, recipes/drogon/all/patches/1.8.5-0002-find-cci-packages.patch, recipes/drogon/config.yml
=> drogon: add version 1.8.5, update dependencies

recipes/sophus/all/conanfile.py
Specify library name and version:  **sophus/***
---
=> sophus: update fmt/10.1.0, delete with_fmt in 1.0.0

recipes/sdl/all/conandata.yml, recipes/sdl/config.yml
Specify library name and version:  **sdl/2.28.2**
---
=> Added SDL version 2.28.2

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/1.3.6**
---
=> glaze: add version 1.3.6

recipes/trantor/all/conandata.yml, recipes/trantor/config.yml
Specify library name and version:  **trantor/1.5.13**
---
=> trantor: add version 1.5.13

recipes/simdjson/all/conandata.yml, recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.2.3**
---
=> simdjson: add version 3.2.3

recipes/cpp-httplib/all/conandata.yml, recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.14.0**
---
=> cpp-httplib: add version 0.14.0

recipes/drogon/all/conanfile.py
=> drogon: update trantor/1.5.13

recipes/dbus/1.x.x/conandata.yml, recipes/dbus/config.yml
Specify library name and version:  **dbus/1.15.8**
---
=> dbus 1.15.8

recipes/cimg/all/conandata.yml, recipes/cimg/all/conanfile.py, recipes/cimg/config.yml
Specify library name and version:  **cimg/***
---
=> cimg: add version 3.2.6, fix requires

recipes/sobjectizer/all/CMakeLists.txt, recipes/sobjectizer/all/conandata.yml, recipes/sobjectizer/all/conanfile.py, recipes/sobjectizer/all/test_package/CMakeLists.txt, recipes/sobjectizer/all/test_package/conanfile.py, recipes/sobjectizer/all/test_v1_package/CMakeLists.txt, recipes/sobjectizer/all/test_v1_package/conanfile.py, recipes/sobjectizer/config.yml
Specify library name and version:  **sobjectizer/5.8.0**
---
=> [SObjectizer] Add version 5.8.0 and support Conan 2.x

recipes/glib/all/conandata.yml, recipes/glib/config.yml
Specify library name and version:  **glib/2.77.2**
---
=> glib: add version 2.77.2

recipes/lexbor/all/conandata.yml, recipes/lexbor/config.yml
Specify library name and version:  **lexbor/2.3.0**
---
=> lexbor: add version 2.3.0

recipes/sqlite3/all/conandata.yml, recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.43.0**
---
=> sqlite3: add version 3.43.0

recipes/libsecret/all/conanfile.py
Specify library name and version:  **libsecret/***
---
=> libsecret/all: bump deps

recipes/libselinux/all/conanfile.py
Specify library name and version:  **libselinux/***
---
=> libselinux/all: bump deps

recipes/glibmm/all/conanfile.py
Specify library name and version:  **glibmm/***
---
=> glibmm/all: bump deps

recipes/pulseaudio/all/conanfile.py
Specify library name and version:  **pulseaudio/***
---
=> pulseaudio/alll: bump deps

recipes/aws-c-event-stream/all/conandata.yml, recipes/aws-c-event-stream/all/conanfile.py, recipes/aws-c-event-stream/config.yml
Specify library name and version:  **aws-c-event-stream/0.3.1**
---
=> aws-c-event-stream: add version 0.3.1

recipes/simdutf/all/conandata.yml, recipes/simdutf/all/patches/3.2.17-0001-fix-cmake.patch, recipes/simdutf/config.yml
Specify library name and version:  **simdutf/3.2.17**
---
=> simdutf: add version 3.2.17

recipes/libmount/all/conanfile.py
Specify library name and version:  **libmount/***
---
=> libmount: fixup license files

recipes/keychain/all/conanfile.py
Specify library name and version:  **keychain/***
---
=> keychain/all: bump deps

recipes/libverto/all/conanfile.py
Specify library name and version:  **libverto/***
---
=> libverto/all: bump deps

recipes/simple-yaml/all/conanfile.py
Specify library name and version:  **simple-yaml/***
---
=> simple-yaml: update dependencies

recipes/serdepp/all/conanfile.py
Specify library name and version:  **serdepp/***
---
=> serdepp: update dependencies

recipes/s2n/all/conandata.yml, recipes/s2n/config.yml
Specify library name and version:  **s2n/1.3.50**
---
=> s2n: add version 1.3.50

recipes/onnx/all/conandata.yml, recipes/onnx/config.yml
Specify library name and version:  **onnx/1.14.1**
---
=> onnx: add version 1.14.1

recipes/opencl-clhpp-headers/all/conandata.yml, recipes/opencl-clhpp-headers/all/test_package/CMakeLists.txt, recipes/opencl-clhpp-headers/all/test_package/test_package.cpp, recipes/opencl-clhpp-headers/config.yml
Required for https://github.com/conan-io/conan-center-index/pull/19349
---
=> opencl-clhpp-headers: align versions with opencl-headers

recipes/ada/all/conandata.yml, recipes/ada/config.yml
Specify library name and version:  **ada/2.6.2**
---
=> ada: add version 2.6.2

recipes/gegles-spdlog_setup/all/conanfile.py
Specify library name and version:  **gegles-spdlog_setup/***
---
=> gegles-spdlog_setup: update fmt/10.1.0

recipes/seadex-essentials/all/conanfile.py
Specify library name and version:  **seadex-essentials/***
---
=> seadex-essentials: update dependencies

recipes/aws-c-io/all/conanfile.py
Specify library name and version:  **aws-c-io/***
---
=> aws-c-io: update s2n/1.3.50

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.38.0**
---
=> etl: add version 20.38.0

recipes/implot/all/conandata.yml, recipes/implot/config.yml
Specify library name and version:  **implot/0.16**
---
=> implot: add version 0.16

recipes/gsl-lite/all/conandata.yml, recipes/gsl-lite/config.yml
Specify library name and version:  **gsl-lite/0.41.0**
---
=> gsl-lite: add version 0.41.0

recipes/cassandra-cpp-driver/all/conandata.yml, recipes/cassandra-cpp-driver/config.yml
Specify library name and version:  **cassandra-cpp/2.17.0**
---
=> cassandra-cpp-driver: add version 2.17.0

recipes/maddy/all/conandata.yml, recipes/maddy/config.yml
Specify library name and version:  **maddy/1.3.0**
---
=> maddy: add version 1.3.0

recipes/openapi-generator/all/conandata.yml, recipes/openapi-generator/config.yml
=> [openapi-generator] Add version 7.0.0

recipes/fmt/all/conandata.yml, recipes/fmt/config.yml
Specify library name and version:  **fmt/10.1.1**
---
=> fmt: add version 10.1.1

recipes/onetbb/all/conanfile.py
Specify library name and version:  **onetbb/2021.10.0**
Closes #19168
---
=> onetbb: fixed hwloc setting on Windows

recipes/ada/all/conandata.yml, recipes/ada/config.yml
Specify library name and version:  **ada/2.6.4**
---
=> ada: add version 2.6.4

recipes/msgpack-cxx/all/conanfile.py
=> msgpack-cxx: update boost/1.83

recipes/wasm-micro-runtime/all/conandata.yml, recipes/wasm-micro-runtime/all/patches/1.2.3-0001-fix-cmake.patch, recipes/wasm-micro-runtime/config.yml
Specify library name and version:  **wasm-micro-runtime/1.2.3**
---
=> wasm-micro-runtime: add version 1.2.3

recipes/nodejs/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/19454
---
=> nodejs: remove compiler from package id + add package_type

recipes/c-blosc2/all/conandata.yml, recipes/c-blosc2/all/conanfile.py, recipes/c-blosc2/all/patches/2.10.2-0001-fix-cmake.patch, recipes/c-blosc2/config.yml
Specify library name and version:  **c-blosc2/***
---
=> c-blosc2: add version 2.10.2, update dependencies

recipes/libheif/all/conandata.yml, recipes/libheif/all/conanfile.py, recipes/libheif/all/patches/0001-cmake_1.16.2.patch, recipes/libheif/config.yml
Specify library name and version:  **libheif/***
---
=> libheif: add version 1.16.2, update dependencies

recipes/ccache/all/conandata.yml, recipes/ccache/config.yml
Specify library name and version:  **ccache/4.8.3**
---
=> ccache: add version 4.8.3

recipes/sdbus-cpp/all/conandata.yml, recipes/sdbus-cpp/config.yml
Specify library name and version:  **sdbus-cpp/1.3.0**
---
=> sdbus-cpp/1.3.0: Bump version

recipes/highway/all/conandata.yml, recipes/highway/config.yml
Specify library name and version:  **highway/1.0.7**
---
=> highway: add version 1.0.7

recipes/pkgconf/all/conandata.yml, recipes/pkgconf/config.yml
Specify library name and version:  **pkgconf/2.0.2**
---
=> pkgconf 2.0.2

recipes/graphene/all/conanfile.py
Specify library name and version:  **graphene/***
---
=> graphene/all: bump deps

recipes/glib/all/conandata.yml, recipes/glib/config.yml
Specify library name and version:  **glib/2.77.3**
---
=> glib 2.77.3

recipes/cmake/binary/conandata.yml, recipes/cmake/config.yml
Specify library name and version:  **cmake/3.27.4**
---
=> cmake: add 3.27.4

recipes/c-blosc/all/conandata.yml, recipes/c-blosc/config.yml
Specify library name and version:  **c-blosc/1.21.5**
---
=> c-blosc: add version 1.21.5

recipes/enkits/all/CMakeLists.txt, recipes/enkits/all/conandata.yml, recipes/enkits/all/conanfile.py, recipes/enkits/all/patches/cmake-install-lib-location.patch, recipes/enkits/all/test_package/CMakeLists.txt, recipes/enkits/all/test_package/conanfile.py, recipes/enkits/all/test_v1_package/CMakeLists.txt, recipes/enkits/all/test_v1_package/conanfile.py
=> enkits: migrate to Conan v2

recipes/qdbm/all/CMakeLists.txt, recipes/qdbm/all/conandata.yml, recipes/qdbm/all/conanfile.py, recipes/qdbm/all/test_package/CMakeLists.txt, recipes/qdbm/all/test_package/conanfile.py, recipes/qdbm/all/test_package/test_package.c, recipes/qdbm/all/test_v1_package/CMakeLists.txt, recipes/qdbm/all/test_v1_package/conanfile.py
=> qdbm: migrate to Conan v2

recipes/lzip/all/conandata.yml, recipes/lzip/all/conanfile.py, recipes/lzip/all/patches/1.21-0001-any-compiler.patch, recipes/lzip/all/patches/1.22-0001-any-compiler.patch, recipes/lzip/all/patches/1.23-0001-any-compiler.patch, recipes/lzip/all/test_package/conanfile.py, recipes/lzip/config.yml
lzip/*
Updated recipe for conan 2.0 compliance
---
=> lzip/*: Updated recipe for conan 2.0

recipes/octo-logger-cpp/all/conandata.yml, recipes/octo-logger-cpp/all/conanfile.py, recipes/octo-logger-cpp/all/test_package/CMakeLists.txt, recipes/octo-logger-cpp/all/test_package/conanfile.py, recipes/octo-logger-cpp/config.yml
Specify library name and version:  **octo-logger-cpp/***
---
=> octo-logger-cpp: support conan v2, update fmt/10.1.1, add package_type

recipes/troldal-zippy/all/conanfile.py
Specify library name and version:  **troldal-zippy/\***
see https://github.com/conan-io/conan-center-index/pull/18359#pullrequestreview-1516476037
---
=> troldal-zippy: fix "package requires C++17 support. The current compiler Visual Studio 16 does not support it", add msvc compiler support, bump deps

recipes/mcap/all/conanfile.py, recipes/mcap/all/test_package/conanfile.py
Specify library name and version:  **mcap/***
---
=> mcap: update zstd/1.5.5, add package_type

recipes/arsenalgear/all/conanfile.py
Specify library name and version:  **arsenalgear/***
---
=> arsenalgear: update boost/1.8.30

recipes/jinja2cpp/all/conanfile.py
Specify library name and version:  **jinja2cpp/***
---
=> jinja2cpp: update dependencies

recipes/websocketpp/all/conanfile.py
Specify library name and version:  **websocketpp/***
---
=> websocketpp: update dependencies

recipes/cpprestsdk/all/conanfile.py
Specify library name and version:  **cpprestsdk/***
---
=> cpprestsdk: update boost/1.83.0

recipes/fakeit/all/conanfile.py
Specify library name and version:  **fakeit/***
---
=> fakeit: update dependencies

recipes/onetbb/all/conanfile.py
Specify library name and version:  **onetbb/2021.9.0**
---
=> [onetbb] Bump dependencies

recipes/cubicinterpolation/all/CMakeLists.txt, recipes/cubicinterpolation/all/conanfile.py, recipes/cubicinterpolation/all/test_package/CMakeLists.txt, recipes/cubicinterpolation/config.yml
Specify library name and version:  **cubicinterpolation/***
---
=> cubicinterpolation: update dependencies, remove unused file

recipes/mpfr/all/conandata.yml, recipes/mpfr/all/conanfile.py, recipes/mpfr/all/test_package/conanfile.py, recipes/mpfr/config.yml
Specify library name and version:  **mpfr/***
---
=> mpfr: add version 4.2.1, update dependenies

recipes/llvm-openmp/all/CMakeLists.txt, recipes/llvm-openmp/all/conandata.yml, recipes/llvm-openmp/all/conanfile.py, recipes/llvm-openmp/all/test_package/CMakeLists.txt, recipes/llvm-openmp/all/test_package/conanfile.py, recipes/llvm-openmp/all/test_package/test_package.c, recipes/llvm-openmp/all/test_v1_package/CMakeLists.txt, recipes/llvm-openmp/all/test_v1_package/conanfile.py
=> llvm-openmp: migrate to Conan v2

recipes/csvmonkey/all/conanfile.py
Specify library name and version:  **csvmonkey/***
---
=> csvmonkey: update boost/1.83.0, add package_type

docs/changelog.md
There was a missing changelog entry from last week
=> [changelog] Add changelog 31-August-2023

recipes/uchardet/all/CMakeLists.txt, recipes/uchardet/all/conanfile.py, recipes/uchardet/all/test_package/CMakeLists.txt, recipes/uchardet/all/test_package/conanfile.py, recipes/uchardet/all/test_v1_package/CMakeLists.txt, recipes/uchardet/all/test_v1_package/conanfile.py
=> uchardet: migrate to Conan v2

recipes/dacap-clip/all/conandata.yml, recipes/dacap-clip/all/conanfile.py, recipes/dacap-clip/all/test_package/CMakeLists.txt, recipes/dacap-clip/config.yml
Specify library name and version:  **dacap-clip/***
---
=> dacap-clip: add version 1.6, add package_type

recipes/libtins/all/conandata.yml, recipes/libtins/all/conanfile.py, recipes/libtins/all/test_package/CMakeLists.txt, recipes/libtins/config.yml
Specify library name and version:  **libtins/***
Try to close https://github.com/conan-io/conan-center-index/issues/19545.
---
=> libtins: add version 4.5, update boost

recipes/cppitertools/all/conandata.yml, recipes/cppitertools/all/conanfile.py, recipes/cppitertools/all/test_package/CMakeLists.txt, recipes/cppitertools/all/test_package/conanfile.py
Specify library name and version:  **cppitertools/***
---
=> cppitertools: support conan v2 more, update boost

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.96.1**
---
=> daw_header_libraries: add version 2.96.1

recipes/wasmer/all/conandata.yml, recipes/wasmer/config.yml
Specify library name and version:  **wasmer/4.2.0**
---
=> wasmer: add version 4.2.0

recipes/zmqpp/all/conandata.yml, recipes/zmqpp/all/conanfile.py
Specify library name and version:  **zmqpp/***
Try to close https://github.com/conan-io/conan-center-index/issues/19607.
---
=> zmqpp: support conan v2 more, add patch description

recipes/wasmtime/all/conandata.yml, recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/12.0.1**
---
=> wasmtime: add version 12.0.1

recipes/octo-keygen-cpp/all/conandata.yml, recipes/octo-keygen-cpp/all/conanfile.py, recipes/octo-keygen-cpp/all/test_package/CMakeLists.txt, recipes/octo-keygen-cpp/all/test_package/conanfile.py, recipes/octo-keygen-cpp/all/test_package/test_package.cpp
Specify library name and version:  **octo-keygen-cpp/***
---
=> octo-keygen-cpp: update dependencies, add package_type

recipes/tree-sitter-c/all/CMakeLists.txt, recipes/tree-sitter-c/all/conanfile.py
Some fixes for the recipe that I did not have time to push before the recipe was merged:
- Use correct layout
- Remove non-existent source dir in CMakeLists.txt
- Remove repeated lines in recipe
=> Some improvements for tree-sitter-c recipe

docs/adding_packages/dependencies.md
Asks for contributors not to open PRs moving to ranges for now
=> Change Zlib ranges docu

recipes/tidy-html5/all/CMakeLists.txt, recipes/tidy-html5/all/conandata.yml, recipes/tidy-html5/all/conanfile.py, recipes/tidy-html5/all/test_package/CMakeLists.txt, recipes/tidy-html5/all/test_package/conanfile.py, recipes/tidy-html5/all/test_v1_package/CMakeLists.txt, recipes/tidy-html5/all/test_v1_package/conanfile.py
=> tidy-html5: migrate to Conan v2

recipes/zpp_bits/all/conandata.yml, recipes/zpp_bits/config.yml
Specify library name and version:  **zpp_bits/4.4.19**
---
=> zpp_bits: add version 4.4.19

recipes/quill/all/conanfile.py
=> quill: update fmt/10.1.1

recipes/soci/all/conanfile.py
Specify library name and version:  **soci/***
---
=> soci: update dependencies

recipes/visit_struct/all/conanfile.py
Specify library name and version:  **visit_struct/***
---
=> visit_struct: update boost/1.83.0

recipes/samurai/all/conandata.yml, recipes/samurai/config.yml
Specify library name and version:  **samurai/0.6.0**
---
=> samurai: add version 0.6.0

recipes/restinio/all/conanfile.py
Specify library name and version:  **restinio/***
---
=> restinio: update fmt/10.1.1

recipes/usockets/all/conanfile.py
Specify library name and version:  **usockets/***
---
=> usockets: update boost/1.83.0

recipes/seadex-genesis/all/conanfile.py
Specify library name and version:  **seadex-genesis/***
---
=> seadex-genesis: update fmt/10.1.0

recipes/highfive/all/conanfile.py
Specify library name and version:  **highfive/***
---
=> highfive: update dependencies

recipes/daw_utf_range/all/conanfile.py
Specify library name and version:  **daw_utf_range/***
---
=> daw_utf_range: update daw_header_libraries/2.96.1

recipes/ada/all/conandata.yml, recipes/ada/all/conanfile.py, recipes/ada/config.yml
Specify library name and version:  **ada/***
---
=> ada: add version 2.6.7, remove older versions

recipes/xz_utils/all/conandata.yml, recipes/xz_utils/config.yml
Specify library name and version:  **xz/5.4.4**
---
=> xz_utils: add v5.4.4

recipes/libavif/all/conanfile.py
=> libavif: bump deps

recipes/samurai/all/conanfile.py
Specify library name and version:  **samurai/***
---
=> samurai: update dependencies

recipes/libcurl/all/conanfile.py
=> libcurl: update dependencies

recipes/ade/all/conandata.yml, recipes/ade/config.yml
Specify library name and version:  **ade/0.1.2c**
---
=> ade: 0.1.2c

recipes/daw_json_link/all/conandata.yml, recipes/daw_json_link/all/conanfile.py, recipes/daw_json_link/config.yml
=> daw_json_link: add version 3.20.1, update dependencies

recipes/cppcheck/all/conandata.yml, recipes/cppcheck/all/patches/0004-pcre-debuglib-name-2.12.patch, recipes/cppcheck/config.yml
=> add cppcheck 2.12.0

recipes/glib/all/conandata.yml, recipes/glib/config.yml
Specify library name and version:  **glib/2.78.0**
---
=> glib: add version 2.78.0

recipes/pkgconf/all/conandata.yml, recipes/pkgconf/config.yml
Specify library name and version:  **pkgconf/2.0.3**
---
=> pkgconf: add version 2.0.3

recipes/sqlite3/all/conandata.yml, recipes/sqlite3/config.yml
=> sqlite3: add version 3.43.1

recipes/libspng/all/conanfile.py
=> Bump libspng's zlib requirement to [>=1.2.11 <2] range

recipes/functionalplus/all/conanfile.py
Specify library name and version:  **functionalplus/***
---
=> functionalplus: add package_type

recipes/pcre/all/conanfile.py
=> pcre: use version range for zlib

recipes/gperftools/all/conandata.yml, recipes/gperftools/config.yml
Specify library name and version:  **gperftools/2.13.0**
---
=> gperftools: add version 2.13.0

recipes/platform.equality/all/conanfile.py, recipes/platform.equality/all/test_package/CMakeLists.txt, recipes/platform.equality/all/test_package/conanfile.py, recipes/platform.equality/all/test_package/test_package.cpp, recipes/platform.equality/all/test_v1_package/CMakeLists.txt, recipes/platform.equality/all/test_v1_package/conanfile.py
=> platform.equality: migrate to Conan v2

recipes/redboltz-mqtt_cpp/all/conanfile.py, recipes/redboltz-mqtt_cpp/all/test_package/CMakeLists.txt, recipes/redboltz-mqtt_cpp/all/test_package/conanfile.py, recipes/redboltz-mqtt_cpp/all/test_package/test_package.cpp, recipes/redboltz-mqtt_cpp/all/test_v1_package/CMakeLists.txt, recipes/redboltz-mqtt_cpp/all/test_v1_package/conanfile.py
=> redboltz-mqtt_cpp: migrate to Conan v2

recipes/spdlog/all/conanfile.py
=> spdlog: update fmt/10.1.1

recipes/openexr/3.x/conanfile.py
=> openexr 3.x: use version range for zlib + add package_type

recipes/openexr/2.x/conanfile.py
=> openexr 2.x: use version range for zlib

recipes/minizip/all/conanfile.py
=> minizip: use version range for zlib + add package_type

recipes/dirent/all/conandata.yml, recipes/dirent/config.yml
Specify library name and version:  **dirent/1.24**
---
=> dirent: add version 1.24

recipes/openssl/1.x.x/conandata.yml, recipes/openssl/config.yml
Specify library name and version:  **openssl/1.1.1w**
---
=> openssl: add version 1.1.1w

recipes/make/all/conandata.yml, recipes/make/config.yml
Specify library name and version:  **make/4.4**
---
=> add make/4.4

recipes/drwav/all/conandata.yml, recipes/drwav/config.yml
Specify library name and version:  **drwav/0.13.12**
---
=> Add drwav 0.13.12

recipes/libsodium/all/conandata.yml, recipes/libsodium/config.yml
Specify library name and version:  **libsodium/1.0.19**
---
=> libsodium 1.0.19

recipes/libwebp/all/conandata.yml, recipes/libwebp/config.yml
Specify library name and version:  **libwebp/1.3.2**
---
=> libwebp: add version 1.3.2

recipes/libtiff/all/conandata.yml, recipes/libtiff/config.yml
Specify library name and version:  **libtiff/4.6.0**
---
=> libtiff: add version 4.6.0

recipes/antlr4-cppruntime/all/conandata.yml, recipes/antlr4-cppruntime/config.yml
Specify library name and version:  **antlr4-cppruntime/4.13.1**
---
=> antlr4-cppruntime: Add version 4.13.1.

recipes/tk/all/conandata.yml, recipes/tk/all/conanfile.py, recipes/tk/all/patches/0001-Add-unix-conan-compatibility.patch, recipes/tk/all/patches/0002-Add-windows-conan-compatibility.patch, recipes/tk/all/patches/0003-Patch-tkConfig.sh.patch, recipes/tk/all/test_package/CMakeLists.txt, recipes/tk/all/test_package/conanfile.py, recipes/tk/all/test_package/src/test_package.c, recipes/tk/all/test_v1_package/CMakeLists.txt, recipes/tk/all/test_v1_package/conanfile.py
* Move to modern conan implementation
* Transition most file modifications to patches
Specify library name and version:  **tk/8.6.10**
---
=> [tk] Migrate tk to conan 2.0

recipes/spectra/all/conanfile.py
=> spectra: add package_type

recipes/taocpp-taopq/all/conanfile.py
=> taocpp-taopq: add package_type + fix traits of dependencies

recipes/tscns/all/conanfile.py, recipes/tscns/all/test_v1_package/CMakeLists.txt
=> tscns: add package_type

recipes/tsl-array-hash/all/conanfile.py, recipes/tsl-array-hash/all/test_v1_package/CMakeLists.txt
=> tsl-array-hash: add package_type

recipes/tsl-hat-trie/all/conanfile.py, recipes/tsl-hat-trie/all/test_v1_package/CMakeLists.txt
=> tsl-hat-trie: add package_type

recipes/tsl-robin-map/all/conanfile.py
=> tsl-robin-map: add package_type

recipes/gettext/all/conanfile.py
=> gettext: less verbose `package_info()` + add a layout + fix win_bash logic when `tools.microsoft.bash:path` is set

recipes/wasmtime/all/conandata.yml, recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/12.0.2**
---
=> wasmtime: add version 12.0.2

recipes/tsl-sparse-map/all/conanfile.py, recipes/tsl-sparse-map/all/test_v1_package/CMakeLists.txt
=> tsl-sparse-map: add package_type

recipes/tuplet/all/conanfile.py
=> tuplet: add package_type

recipes/uncrustify/all/conanfile.py
=> uncrustify: add package_type

recipes/units/all/conanfile.py, recipes/units/all/test_v1_package/CMakeLists.txt
=> units: add package_type

recipes/utf8.h/all/conanfile.py, recipes/utf8.h/all/test_v1_package/CMakeLists.txt
=> utf8.h: add package_type

recipes/v-hacd/all/conanfile.py
=> v-hacd: add package_type

recipes/xpack/all/conanfile.py
=> xpack: add package_type

recipes/xproperty/all/conanfile.py
=> xproperty: add package_type

recipes/zopfli/all/conanfile.py, recipes/zopfli/all/test_v1_package/CMakeLists.txt
=> zopfli: add package_type

recipes/gegles-spdlog_setup/all/conanfile.py
Specify library name and version:  **gegles-spdlog_setup/1.1.0**
bump fmt to 10.1.1
---
=> gegles-spdlog_setup: bump fmt

recipes/xorstr/all/conanfile.py
=> xorstr: add package_type

recipes/yyjson/all/conandata.yml, recipes/yyjson/config.yml
Specify library name and version:  **yyjson/0.8.0**
---
=> yyjson: add version 0.8.0

recipes/cpu_features/all/conandata.yml, recipes/cpu_features/config.yml
Specify library name and version:  **cpu_features/0.9.0**
---
=> cpu_features: add version 0.9.0

recipes/uni-algo/all/conandata.yml, recipes/uni-algo/config.yml
Specify library name and version:  **uni-algo/1.1.0**
---
=> uni-algo: add version 1.1.0

recipes/implot/all/conanfile.py
Specify library name and version:  **implot/***
---
=> implot: update imgui/1.89.9

recipes/emio/all/conandata.yml, recipes/emio/config.yml
Specify library name and version: emio/0.4.0
---
=> emio: add version 0.4.0

recipes/libdeflate/all/conandata.yml, recipes/libdeflate/config.yml
Specify library name and version:  **libdeflate/1.19**
---
=> libdeflate: add version 1.19

recipes/libalsa/all/conandata.yml, recipes/libalsa/config.yml
Specify library name and version:  **libalsa/1.2.10**
---
=> libalsa: add version 1.2.10

recipes/libinterpolate/all/conanfile.py
=> libinterpolate: fix msvc min version + add package_type

recipes/cmake/binary/conandata.yml, recipes/cmake/config.yml
Specify library name and version:  **cmake/3.27.5**
---
=> cmake: add version 3.27.5

recipes/wildmidi/all/conanfile.py
=> wildmidi: add package_type

recipes/zpp_throwing/all/conanfile.py
also relax `required_conan_version`, 1.50.0 is sufficient.
---
=> zpp_throwing: add package_type

recipes/vcglib/all/conanfile.py, recipes/vcglib/all/test_v1_package/CMakeLists.txt
transitive_headers=True may have to be added to eigen, I'm waiting feedback from v2 pipeline.
---
=> vcglib: add package_type

recipes/vectorial/all/conanfile.py, recipes/vectorial/all/test_package/conanfile.py, recipes/vectorial/all/test_v1_package/CMakeLists.txt
=> vectorial: add package_type

recipes/winmd/all/conanfile.py
=> winmd: add package_type & clear bindirs and libdirs in package_info()

recipes/crowcpp-crow/all/conanfile.py, recipes/crowcpp-crow/all/test_package/conanfile.py
Specify library name and version:  **crowcpp-crow/***
---
=> crowcpp-crow: update dependencies, fix requires names

recipes/continuable/all/conandata.yml, recipes/continuable/all/conanfile.py, recipes/continuable/all/test_package/CMakeLists.txt, recipes/continuable/config.yml
Specify library name and version:  **continuable/***
---
=> continuable: add version 4.2.2, update dependencies

recipes/platform.converters/all/conanfile.py, recipes/platform.converters/all/test_package/CMakeLists.txt, recipes/platform.converters/all/test_package/conanfile.py, recipes/platform.converters/all/test_package/test_package.cpp, recipes/platform.converters/all/test_v1_package/CMakeLists.txt, recipes/platform.converters/all/test_v1_package/conanfile.py
=> platform.converters: migrate to Conan v2

recipes/seqan3/all/conanfile.py, recipes/seqan3/all/test_package/CMakeLists.txt, recipes/seqan3/all/test_package/conanfile.py, recipes/seqan3/all/test_v1_package/CMakeLists.txt, recipes/seqan3/all/test_v1_package/conanfile.py
=> seqan3: migrate to Conan v2

recipes/lazycsv/all/conandata.yml, recipes/lazycsv/all/conanfile.py, recipes/lazycsv/all/test_package/CMakeLists.txt, recipes/lazycsv/all/test_package/conanfile.py, recipes/lazycsv/all/test_package/test_package.cpp, recipes/lazycsv/config.yml
Specify library name and version:  **lazycsv/***
---
=> lazycsv: add recipe

recipes/ssp/all/conandata.yml, recipes/ssp/all/conanfile.py, recipes/ssp/all/test_package/CMakeLists.txt, recipes/ssp/all/test_package/conanfile.py, recipes/ssp/all/test_package/test_package.cpp, recipes/ssp/config.yml
Specify library name and version:  **ssp/1.6.1**
---
=> ssp: add recipe

recipes/stringzilla/all/conandata.yml, recipes/stringzilla/all/conanfile.py, recipes/stringzilla/all/test_package/CMakeLists.txt, recipes/stringzilla/all/test_package/conanfile.py, recipes/stringzilla/all/test_package/test_package.cpp, recipes/stringzilla/config.yml
Specify library name and version:  **stringzilla/***
---
=> stringzilla: add recipe

recipes/cryptopp/all/conandata.yml, recipes/cryptopp/all/conanfile.py, recipes/cryptopp/config.yml
Specify library name and version:  **cryptopp/8.8.0**
---
=> cryptopp 8.8.0

recipes/valijson/all/conanfile.py, recipes/valijson/all/test_package/CMakeLists.txt, recipes/valijson/all/test_package/conanfile.py, recipes/valijson/all/test_v1_package/CMakeLists.txt, recipes/valijson/all/test_v1_package/conanfile.py
=> valijson: add package_type + simplify & fix test package

recipes/libnl/all/conandata.yml, recipes/libnl/all/conanfile.py, recipes/libnl/config.yml
Specify library name and version:  **libnl/3.8.0**
---
=> libnl: add version 3.8.0

recipes/mathfu/all/conanfile.py
=> mathfu: add package_type

recipes/oboe/all/conanfile.py
=> oboe: add package_type

recipes/platform.equality/all/conanfile.py
=> platform.equality: no warning for msvc or unknown compilers

recipes/redboltz-mqtt_cpp/all/conanfile.py
=> redboltz-mqtt_cpp: no warning for msvc or unknown compilers

recipes/cminpack/all/conanfile.py, recipes/cminpack/all/test_package/CMakeLists.txt, recipes/cminpack/all/test_package/conanfile.py, recipes/cminpack/all/test_v1_package/CMakeLists.txt
=> cminpack: modernize more for conan v2

recipes/crc_cpp/all/conandata.yml, recipes/crc_cpp/all/conanfile.py, recipes/crc_cpp/all/test_package/CMakeLists.txt, recipes/crc_cpp/all/test_package/conanfile.py, recipes/crc_cpp/all/test_v1_package/CMakeLists.txt, recipes/crc_cpp/all/test_v1_package/conanfile.py, recipes/crc_cpp/config.yml
=> crc_cpp: conan v2 support

recipes/vir-simd/all/conandata.yml, recipes/vir-simd/all/conanfile.py, recipes/vir-simd/all/test_package/conanfile.py
=> vir-simd: fix msvc min version & cleanup recipe

recipes/gnutls/all/conanfile.py
=> Bump gnutls's zlib requirement to [>=1.2.11 <2] range

recipes/zziplib/all/conanfile.py
=> Bump zziplib's zlib requirement to [>=1.2.11 <2] range

recipes/uwebsockets/all/conanfile.py
=> Bump uwebsockets's zlib requirement to [>=1.2.11 <2] range

recipes/librdkafka/all/conanfile.py
=> Bump librdkafka's zlib requirement to [>=1.2.11 <2] range

recipes/civetweb/all/conanfile.py
=> Bump civetweb's zlib requirement to [>=1.2.11 <2] range

recipes/cpp-httplib/all/conanfile.py
=> Bump cpp-httplib's zlib requirement to [>=1.2.11 <2] range

recipes/libtar/all/conanfile.py
=> Bump libtar's zlib requirement to [>=1.2.11 <2] range

recipes/cfitsio/all/conanfile.py
=> Bump cfitsio's zlib requirement to [>=1.2.11 <2] range

recipes/highs/all/conanfile.py
=> Bump highs's zlib requirement to [>=1.2.11 <2] range

recipes/libdwarf/all/conanfile.py
=> Bump libdwarf's zlib requirement to [>=1.2.11 <2] range

recipes/c-blosc/all/conanfile.py
=> Bump c-blosc's zlib requirement to [>=1.2.11 <2] range

recipes/libunwind/all/conanfile.py
=> Bump libunwind's zlib requirement to [>=1.2.11 <2] range

recipes/coin-utils/all/conanfile.py
=> Bump coin-utils's zlib requirement to [>=1.2.11 <2] range

recipes/readosm/all/conanfile.py
=> Bump readosm's zlib requirement to [>=1.2.11 <2] range

recipes/libmicrohttpd/all/conanfile.py
=> Bump libmicrohttpd's zlib requirement to [>=1.2.11 <2] range

recipes/ptex/all/conanfile.py
=> Bump ptex's zlib requirement to [>=1.2.11 <2] range

recipes/tcl/all/conanfile.py
=> Bump tcl's zlib requirement to [>=1.2.11 <2] range

recipes/restinio/all/conanfile.py
=> Bump restinio's zlib requirement to [>=1.2.11 <2] range

recipes/libgd/all/conanfile.py
=> Bump libgd's zlib requirement to [>=1.2.11 <2] range

recipes/cnpy/all/conanfile.py
=> Bump cnpy's zlib requirement to [>=1.2.11 <2] range

recipes/libpng/all/conanfile.py
=> Bump libpng's zlib requirement to [>=1.2.11 <2] range

recipes/tinyexr/all/conanfile.py
=> Bump tinyexr's zlib requirement to [>=1.2.11 <2] range

recipes/xapian-core/all/conanfile.py
=> Bump xapian-core's zlib requirement to [>=1.2.11 <2] range

recipes/crowcpp-crow/all/conanfile.py, recipes/crowcpp-crow/all/test_package/conanfile.py
=> Bump crowcpp-crow's zlib requirement to [>=1.2.11 <2] range

recipes/gzip-hpp/all/conanfile.py
=> Bump gzip-hpp's zlib requirement to [>=1.2.11 <2] range

recipes/minisat/all/conanfile.py
=> Bump minisat's zlib requirement to [>=1.2.11 <2] range

recipes/tng/all/conanfile.py
=> Bump tng's zlib requirement to [>=1.2.11 <2] range

recipes/taglib/all/conanfile.py
=> Bump taglib's zlib requirement to [>=1.2.11 <2] range

recipes/seasocks/all/conanfile.py
=> Bump seasocks's zlib requirement to [>=1.2.11 <2] range

recipes/libnghttp2/all/conanfile.py
=> Bump libnghttp2's zlib requirement to [>=1.2.11 <2] range

recipes/hdf5/all/conanfile.py
=> Bump hdf5's zlib requirement to [>=1.2.11 <2] range

recipes/hdf4/all/conanfile.py
=> Bump hdf4's zlib requirement to [>=1.2.11 <2] range

recipes/libtiff/all/conanfile.py
=> libtiff: use version range for zlib + bump mozjpeg

recipes/libxml2/all/conanfile.py
=> libxml2: use version range for zlib + bump icu & pkgconf

recipes/zstr/all/conanfile.py
=> zstr: add package_type + use version range for zlib

recipes/ccfits/all/conanfile.py, recipes/ccfits/all/test_v1_package/CMakeLists.txt
=> ccfits: add package_type + bump cfitsio

recipes/cprocessing/all/conanfile.py, recipes/cprocessing/all/test_package/CMakeLists.txt, recipes/cprocessing/all/test_v1_package/conanfile.py
- fix msvc min version
- do not suggest unofficial CMake names
- bump glfw & stb
- remove no_copy_source since there is a patch
---
=> cprocessing: fix min msvc version + do not suggest unofficial CMake names + bump glfw & stb

recipes/wyhash/all/conanfile.py
=> wyhash: add package_type

recipes/beauty/all/conanfile.py
=> beauty: use version range for openssl

recipes/ffmpeg/all/conanfile.py
There's a version conflict with opencv that broke the example repo: https://ci.conan.io/blue/organizations/jenkins/Examples2.0/detail/main/655/pipeline
=> Bump xz_utils for ffmpeg

recipes/openssl/3.x.x/conandata.yml, recipes/openssl/config.yml
Specify library name and version:  **openssl/3.1.3**
Add v3.1.3 and v3.0.11. 
---
=> openssl: add 3.1.3 & 3.0.11

recipes/libzippp/all/conanfile.py
=> Bump libzippp's zlib requirement to [>=1.2.11 <2] range

recipes/libssh2/all/conanfile.py
From the original PR, needed by #18458
=> Bump libssh2's zlib requirement to [>=1.2.11 <2] range

recipes/boost/all/conanfile.py
=> boost: use version range zlib + bump icu & b2

recipes/libmysqlclient/all/conanfile.py
Closing #19757 in favour of this one
(Thanks to @oleurodecision for bringing up a good reason not to remove the .25 version!)
Closes #19654
=> libmysqlcient: Disable doxxygen generation

recipes/coost/all/conandata.yml, recipes/coost/all/conanfile.py, recipes/coost/all/test_package/CMakeLists.txt, recipes/coost/all/test_package/conanfile.py, recipes/coost/all/test_package/test_package.cpp, recipes/coost/config.yml
Specify library name and version:  **coost/3.0.1**
retry https://github.com/conan-io/conan-center-index/pull/12789.
---
=> coost: add recipe

recipes/cimg/all/conandata.yml, recipes/cimg/all/conanfile.py, recipes/cimg/config.yml
Specify library name and version:  **cimg/***
---
=> cimg: add version 3.3.0, update libtiff/4.6.0

recipes/dav1d/all/conanfile.py
=> dav1d: bump meson

recipes/fribidi/all/conanfile.py
=> fribidi: bump meson

recipes/lcms/all/conanfile.py
=> lcms: bump meson

recipes/kmod/all/conanfile.py
Specify library name and version:  **kmod/any**
---
=> [kmod] Bump zlib requirement to [>=1.2.11 <2] range

recipes/pcl/all/conanfile.py
=> Bump pcl's zlib requirement to [>=1.2.11 <2] range

recipes/soplex/all/conanfile.py
=> Bump soplex's zlib requirement to [>=1.2.11 <2] range

recipes/libkml/all/conanfile.py
=> Bump libkml's zlib requirement to [>=1.2.11 <2] range

recipes/itk/all/conanfile.py
Specify library name and version:  **itk/1.0**
---
=> [itk] Bump zlib requirement to [>=1.2.11 <2] range

recipes/poco/all/conanfile.py
=> Bump poco's zlib requirement to [>=1.2.11 <2] range

recipes/podofo/all/conanfile.py
Specify library name and version:  **podofo/any**
---
=> [podofo] Bump zlib requirement to [>=1.2.11 <2] range

recipes/opencv/2.x/conanfile.py
=> Bump opencv's zlib requirement to [>=1.2.11 <2] range

recipes/wt/all/conanfile.py
Specify library name and version:  **wt/any**
---
=> Bump wt's zlib requirement to [>=1.2.11 <2] range

recipes/wayland/all/conanfile.py, recipes/wayland/all/test_package/conanfile.py
=> wayland/all: bump deps

recipes/trantor/all/conandata.yml, recipes/trantor/all/conanfile.py, recipes/trantor/config.yml
Specify library name and version:  **trantor/1.5.14**
---
=> trantor: add version 1.5.14

recipes/mpg123/all/conanfile.py
Specify library name and version:  **mpg123/***
---
=> mpg123/all: bump deps

recipes/aws-c-common/all/conandata.yml, recipes/aws-c-common/config.yml
=> aws-c-common: add new versions, remove old versions

recipes/cuda-api-wrappers/all/conandata.yml, recipes/cuda-api-wrappers/config.yml
=> cuda-api-wrappers: add version 0.7

recipes/pixman/all/conanfile.py
same issue than https://github.com/conan-io/conan-center-index/pull/19968#issue-1903862552 with apple-clang 15. Upgrading meson helps.
---
=> pixman: bump meson

recipes/proj/all/conandata.yml, recipes/proj/config.yml
=> proj: add version 9.3.0

recipes/simdjson/all/conandata.yml, recipes/simdjson/all/conanfile.py, recipes/simdjson/config.yml
Specify library name and version:  **simdjson/***
---
=> simdjson: add version 3.3.0, remove older versions

recipes/symengine/all/conandata.yml, recipes/symengine/all/conanfile.py, recipes/symengine/config.yml
**symengine/0.11.1**
Also update boost version.
=> Add symengine 0.11.1

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/1.5.1**
---
=> glaze: add version 1.5.1

recipes/clickhouse-cpp/all/conandata.yml, recipes/clickhouse-cpp/all/conanfile.py, recipes/clickhouse-cpp/config.yml
Specify library name and version:  **clickhouse-cpp/***
---
=> clickhouse-cpp: add version 2.5.0

recipes/dlib/all/conanfile.py
Specify library name and version:  **dlib/all**
---
=> dlib/all: bump deps

recipes/harfbuzz/all/conandata.yml, recipes/harfbuzz/config.yml
Specify library name and version:  **harfbuzz/8.2.1**
---
=> harfbuzz: add version 8.2.1

recipes/cpp-httplib/all/conandata.yml, recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.14.1**
---
=> cpp-httplib: add version 0.14.1

recipes/cassandra-cpp-driver/all/conanfile.py
=> cassandra-cpp-driver: add package_type + bump boost + better way to package relocatable shared lib on macOS

recipes/ldns/all/conanfile.py
Also remove:
- `apply_conandata_patches`/`export_conandata_patches` since there is no patch
- `_settings_build` since it's not used at all
---
=> ldns: relocatable shared lib on macOS + add package_type + version range for openssl

recipes/serd/all/conanfile.py
same issue than https://github.com/conan-io/conan-center-index/pull/19968#issue-1903862552 with apple-clang 15. Upgrading meson helps.
---
=> serd: bump meson

recipes/streamvbyte/all/conandata.yml, recipes/streamvbyte/all/patches/1.0.0-0002-relocatable-shared-macos.patch
=> streamvbyte: relocatable shared lib for macOS

recipes/xkbcommon/all/conanfile.py
=> xkbcommon: silence console log

recipes/libnpy/all/conandata.yml, recipes/libnpy/all/conanfile.py, recipes/libnpy/all/test_package/CMakeLists.txt, recipes/libnpy/all/test_package/conanfile.py, recipes/libnpy/all/test_package/test_package.cpp, recipes/libnpy/config.yml
Specify library name and version:  **libnpy/***
---
=> libnpy: add recipe

recipes/alembic/all/conanfile.py, recipes/alembic/all/patches/1.8.5-0001-fix-cmake.patch
=> alembic 1.8.5: relocatable shared lib on macOS + disable warnings as errors

recipes/wasmtime-cpp/all/conanfile.py
Specify library name and version:  **wasmtime-cpp/***
---
=> wasmtime-cpp: update wasmtime/12.0.1

recipes/libcoro/all/conandata.yml, recipes/libcoro/all/conanfile.py, recipes/libcoro/all/patches/0.9-0001-allow-shared-lib.patch, recipes/libcoro/all/patches/0.9-0002-disable-git-config.patch, recipes/libcoro/all/patches/0.9-0003-include-exception.patch, recipes/libcoro/config.yml
Specify library name and version:  **libcoro/0.9**
---
=> libcoro: add version 0.9

recipes/ada/all/conandata.yml, recipes/ada/all/conanfile.py, recipes/ada/config.yml
Specify library name and version:  **ada/2.6.10**
---
=> ada: add version 2.6.10

recipes/onnx/all/conanfile.py
Specify library name and version:  **onnx/all**
---
=> onnx: respect protobuf lite option

recipes/qpdf/all/conanfile.py
Specify library name and version:  **qpdf/all**
---
=> qpdf/all: bump deps

recipes/libgd/all/conanfile.py
Specify library name and version:  **libgd/all**
---
=> libgd/all: bump deps

recipes/pugixml/all/conandata.yml, recipes/pugixml/config.yml
Specify library name and version:  **pugixml/***
---
=> pugixml: add version 1.14

recipes/brotli/all/conanfile.py, recipes/brotli/all/patches/1.1.0-target-props.patch
see https://github.com/conan-io/conan-center-index/pull/19540#issuecomment-1738105619
---
=> brotli: relocatable shared libs on macOS for 1.1.0

recipes/hictk/all/conandata.yml, recipes/hictk/all/conanfile.py, recipes/hictk/config.yml
Specify library name and version:  **hictk/0.0.3**
---
=> hictk: add v0.0.3 and bump deps

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/1.5.2**
---
=> glaze: add version 1.5.2

recipes/s2geometry/all/conandata.yml, recipes/s2geometry/all/conanfile.py, recipes/s2geometry/all/patches/add_message_to_static_assert.patch, recipes/s2geometry/all/patches/bump_cmake_cxx_standard.patch, recipes/s2geometry/all/test_package/CMakeLists.txt, recipes/s2geometry/all/test_package/conanfile.py, recipes/s2geometry/all/test_package/test_package.cpp, recipes/s2geometry/config.yml
Specify library name and version:  **s2geometry/0.10.0**
---
=> s2geometry: add recipe

recipes/mtdev/all/conandata.yml, recipes/mtdev/all/conanfile.py, recipes/mtdev/all/test_package/CMakeLists.txt, recipes/mtdev/all/test_package/conanfile.py, recipes/mtdev/all/test_package/test_package.c, recipes/mtdev/config.yml
Specify library name and version:  **mtdev/1.1.6**
The mtdev package is required to create a libinput package.
---
=> mtdev: Add recipe

recipes/libgphoto2/all/conanfile.py
Specify library name and version:  **libgphoto2/all**
---
=> libgphoto2: bump deps

recipes/netcdf/all/conanfile.py
Specify library name and version:  **netcdf/all**
---
=> netcdf/all: bump deps

recipes/libxslt/all/conanfile.py
=> libxslt/all: bump deps

recipes/cfitsio/all/conanfile.py
Specify library name and version:  **cfitsio/all**
---
=> cfitsio/all: bump deps

recipes/wasmtime/all/conanfile.py
- this recipes requires at least conan 1.53.0 due to usage of rm_safe
- consistent min version between legacy Visual Studio and new msvc
- do not use self.output.warn since it doesn't exist in conan v2
---
=> wasmtime: several fixes for conan v2

.c3i/config_v1.yml, .c3i/config_v2.yml
Specify library name and version:  **llvm**
The PR #17509 requires more time to be built.
---
=> Add llvm to larger timeout list

recipes/mfast/all/conanfile.py, recipes/mfast/all/test_package/conanfile.py
Similar implementation than the one proposed in https://github.com/conan-io/conan-center-index/pull/20089#issue-1909986791
---
=> mfast: improve creation of executable imported target + add package_type + bump sqlite3

recipes/cppcommon/all/conandata.yml, recipes/cppcommon/all/conanfile.py, recipes/cppcommon/all/patches/0001-update-cmakelists-1-0-4-0.patch, recipes/cppcommon/all/patches/0003-define-win32-winnt-1-0-4-0.patch, recipes/cppcommon/config.yml
Specify library name and version:  **cppcommon/1.0.4.0**
---
=> cppcommon: add version 1.0.4.0

recipes/prometheus-cpp/all/conanfile.py
Specify library name and version:  **prometheus-cpp/all**
---
=> prometheus-cpp/all: bump libcurl

recipes/libbigwig/all/conanfile.py
Specify library name and version:  **libbigwig/all**
---
=> libbigwig/all: bump libcurl

recipes/libmediainfo/all/conanfile.py
Specify library name and version:  **libmediainfo/all**
---
=> libmediainfo/all: bump libcurl

recipes/czmq/all/conanfile.py
Specify library name and version:  **czmq/all**
---
=> czmq/all: bump libcurl

recipes/imutils-cpp/all/conanfile.py
Specify library name and version:  **imutils-cpp/all**
---
=> imutils-cpp/all: bump libcurl

recipes/sentry-crashpad/all/conanfile.py
Specify library name and version:  **sentry-crashpad/all**
---
=> sentry-crashpad/all: bump libcurl

recipes/emio/all/conandata.yml, recipes/emio/config.yml
Specify library name and version:  **emio/0.5.0**
---
=> emio: add version 0.5.0

recipes/tmx/all/conanfile.py
Specify library name and version:  **tmx/all**
---
=> tmx/all: bump deps

recipes/norm/all/conanfile.py
Specify library name and version:  **norm/all**
---
=> norm/all: bump libxml2

recipes/civetweb/all/conanfile.py
Specify library name and version:  **civetweb/all**
---
=> civetweb/all: bump OpenSSL

recipes/libmysqlclient/all/conanfile.py
Specify library name and version:  **libmysqlclient/all**
---
=> libmysqlclient/all: bump deps

recipes/libwebsockets/all/conanfile.py
Specify library name and version:  **libwebsockets/all**
---
=> libwebsockets/all: bump OpenSSL

recipes/libpq/all/conanfile.py
Specify library name and version:  **libpq/all**
---
=> libpq/all: bump OpenSSL

recipes/cocoyaxi/all/conanfile.py
Specify library name and version:  **cocoyaxi/all**
close #20235
---
=> cocoyaxi/all: bump lib curl, use version range for OpenSSL, make deprecated

recipes/hwloc/all/conanfile.py
Specify library name and version:  **hwloc/all**
---
=> hwloc/all: bump libxml2

recipes/platform.exceptions/all/conandata.yml, recipes/platform.exceptions/config.yml
Mostly to close these two PRs permanently stuck in a "pending" state:
* Resolves #19400
* Resolves #18919
=> platform.exceptions: bump versions

recipes/pkgconf/all/conanfile.py
Specify library name and version:  **pkgconf/all**
---
=> bump dependencies of pkgconf

recipes/c-client/all/conanfile.py
Specify library name and version:  **c-client/all**
---
=> c-client/all: bump OpenSSL

recipes/cmake/binary/conandata.yml, recipes/cmake/config.yml
Specify library name and version:  **cmake/3.27.7**
---
=> cmake: add version 3.27.7

recipes/mosquitto/1.x/conanfile.py
Specify library name and version:  **mosquitto/1.x**
---
=> mosquitto/1.x: bump OpenSSL

recipes/xkbcommon/all/conandata.yml, recipes/xkbcommon/config.yml
Specify library name and version:  **xkbcommon/1.6.0**
---
=> xkbcommon 1.6.0

recipes/boost-ext-ut/all/conandata.yml, recipes/boost-ext-ut/all/conanfile.py, recipes/boost-ext-ut/config.yml
Specify library name and version:  **boost-ext-ut/2.0.0**
---
=> boost-ext-ut: Add version 2.0.0

recipes/c-ares/all/conandata.yml, recipes/c-ares/config.yml
Specify library name and version:  **c-ares/1.20.1**
---
=> c-ares: add version 1.20.1

recipes/xorg-gccmakedep/all/conanfile.py
Specify library name and version:  **xorg-gccmakedep/***
---
=> xorg-gccmakedep/all: bump deps

recipes/xorg-makedepend/all/conanfile.py
Specify library name and version:  **xorg-makedepend/***
---
=> xorg-makedepend/all: bump deps

recipes/simde/all/conanfile.py
Specify library name and version:  **simde/***
---
=> simde/all: bump deps

recipes/xorg-proto/all/conanfile.py
Specify library name and version:  **xorg-proto/***
---
=> xorg-proto/all: bump deps

recipes/btyacc/all/CMakeLists.txt, recipes/btyacc/all/conanfile.py, recipes/btyacc/all/test_package/CMakeLists.txt, recipes/btyacc/all/test_package/conanfile.py, recipes/btyacc/all/test_v1_package/CMakeLists.txt, recipes/btyacc/all/test_v1_package/conanfile.py
=> btyacc: conan v2 support

recipes/yder/all/conanfile.py
Specify library name and version:  **yder/all**
---
=> yder: fix macOS build, bump libsystemd

recipes/fastnoise2/all/conandata.yml, recipes/fastnoise2/all/conanfile.py, recipes/fastnoise2/all/test_package/CMakeLists.txt, recipes/fastnoise2/all/test_package/conanfile.py, recipes/fastnoise2/all/test_package/test_package.cpp, recipes/fastnoise2/config.yml
Specify library name and version:  **fastnoise2/***
---
=> fastnoise2: add recipe

recipes/twitch-native-ipc/all/conanfile.py
=> twitch-native-ipc: move checks to validate()

recipes/sdbus-cpp/all/conanfile.py
Specify library name and version:  **sdbus-cpp/***
---
=> sdbus-cpp/all: bump deps

recipes/sqlite3/all/conandata.yml, recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.43.2**
---
=> sqlite3: add version 3.43.2

recipes/glib/all/conanfile.py
Specify library name and version:  **glib/all**
---
=> bump glib dependencies

recipes/onnxruntime/all/conandata.yml, recipes/onnxruntime/config.yml
Specify library name and version:  **onnxruntime/1.16.1**
---
=> onnxruntime: add version 1.16.1

recipes/openvino/all/conanfile.py, recipes/openvino/all/test_package/CMakeLists.txt, recipes/openvino/all/test_package/conanfile.py, recipes/openvino/all/test_package/test_package.c, recipes/openvino/all/test_package/test_package.cpp
Specify library name and version:  **openvino/all**
**Reason:** to be aligned with default OpenVINOConfig.cmake generated by cmake
---
=> openvino/all: added component for C API

recipes/tomlplusplus/all/conanfile.py, recipes/tomlplusplus/all/test_package/conanfile.py, recipes/tomlplusplus/all/test_v1_package/conanfile.py
=> tomplusplus: add package_type & layout

recipes/qwt/all/conanfile.py
Library name and version:  **qwt/6.2.0**
Fixes issue #19601
---
=> qwt: Fixed transitive requirement of qt

recipes/watcher/all/conandata.yml, recipes/watcher/config.yml
Specify library name and version:  **watcher/0.9.5**
---
=> watcher: add version 0.9.5

recipes/fltk/all/conanfile.py
fltk/1.3.8
Tested on local msys2/ucrt64.
Also see https://www.fltk.org/newsgroups.php?s1684+gfltk.issues+v1691
---
=> fltk: Fixes undefined reference to `__imp__TrackMouseEvent' on msys2.

recipes/luau/all/conandata.yml, recipes/luau/config.yml
Specify library name and version:  **luau/0.598**
---
=> luau: add version 0.598

recipes/emio/all/conandata.yml, recipes/emio/config.yml
Specify library name and version:  **emio/0.6.0**
---
=> emio: add version 0.6.0

recipes/ctre/all/conandata.yml, recipes/ctre/config.yml
Specify library name and version:  **ctre/3.8.1**
---
=> ctre: add version 3.8.1

recipes/mbedtls/all/conandata.yml, recipes/mbedtls/config.yml
Specify library name and version:  **mbedtls/3.5.0**
---
=> mbedtls: add version 3.5.0

recipes/mp-units/0.8.0/conanfile.py, recipes/mp-units/2.0.0/conandata.yml, recipes/mp-units/2.0.0/conanfile.py, recipes/mp-units/2.0.0/test_package/CMakeLists.txt, recipes/mp-units/2.0.0/test_package/conanfile.py, recipes/mp-units/2.0.0/test_package/test_package.cpp, recipes/mp-units/2.0.0/test_v1_package/CMakeLists.txt, recipes/mp-units/2.0.0/test_v1_package/conanfile.py, recipes/mp-units/2.0.0/test_v1_package/test_package.cpp, recipes/mp-units/config.yml
Specify library name and version:  **mp-units/2.0**
---
=> Mp-units-2.0

recipes/thelink2012-any/all/conandata.yml, recipes/thelink2012-any/config.yml
Specify library name and version:  **thelink2012-any/cci.20230118**
---
=> thelink2012-any: add version cci.20230118

recipes/oniguruma/all/conandata.yml, recipes/oniguruma/config.yml
Specify library name and version:  **oniguruma/6.9.9**
---
=> oniguruma: add version 6.9.9

recipes/sqlpp11/all/conandata.yml, recipes/sqlpp11/config.yml
Specify library name and version:  **sqlpp11/0.64**
---
=> sqlpp11: add version 0.64

recipes/tomlplusplus/all/conandata.yml, recipes/tomlplusplus/config.yml
Specify library name and version:  **tomlplusplus/3.4.0**
---
=> tomlplusplus: add version 3.4.0

recipes/libsass/all/conanfile.py, recipes/libsass/all/test_package/CMakeLists.txt, recipes/libsass/all/test_package/conanfile.py, recipes/libsass/all/test_v1_package/CMakeLists.txt, recipes/libsass/all/test_v1_package/conanfile.py
=> libsass: migrate to Conan v2

recipes/c-blosc2/all/conandata.yml, recipes/c-blosc2/all/patches/2.10.5-0001-fix-cmake.patch, recipes/c-blosc2/config.yml
Specify library name and version:  **c-blosc2/2.10.5**
---
=> c-blosc2: add version 2.10.5

recipes/numcpp/all/conandata.yml, recipes/numcpp/all/conanfile.py, recipes/numcpp/config.yml
Specify library name and version:  **numcpp/2.12.0**
---
=> numcpp: add 2.12.0

recipes/kmod/all/conanfile.py
Specify library name and version:  **kmod/***
---
=> kmod/all: bump deps

recipes/nettle/all/conanfile.py
Specify library name and version:  **nettle/***
---
=> nettle/all: bump deps

recipes/uncrustify/all/conandata.yml, recipes/uncrustify/all/test_package/conanfile.py, recipes/uncrustify/config.yml
=> [uncrustify/0.77.1] Bump recipe

recipes/libseat/all/conandata.yml, recipes/libseat/all/conanfile.py, recipes/libseat/all/patches/0001-Disable-building-tests.patch, recipes/libseat/all/test_package/CMakeLists.txt, recipes/libseat/all/test_package/conanfile.py, recipes/libseat/all/test_package/test_package.c, recipes/libseat/config.yml
Specify library name and version:  **libseat/0.8.0**
---
=> libseat: Add recipe

recipes/chipmunk2d/all/conanfile.py
=> chipmunk2d: fix missing glibc symbols on newer systems

recipes/dataframe/all/conandata.yml, recipes/dataframe/all/conanfile.py, recipes/dataframe/all/test_package/CMakeLists.txt, recipes/dataframe/config.yml
Specify library name and version:  **dataframe/2.2.0**
---
=> dataframe: add version 2.2.0

recipes/clipboard_lite/all/conandata.yml, recipes/clipboard_lite/all/conanfile.py, recipes/clipboard_lite/all/patches/0001-include-string.patch, recipes/clipboard_lite/all/test_package/CMakeLists.txt, recipes/clipboard_lite/all/test_package/conanfile.py, recipes/clipboard_lite/all/test_package/test_package.cpp, recipes/clipboard_lite/config.yml
Specify library name and version:  **clipboard_lite/3.4**
---
=> clipboard_lite: add recipe

recipes/gnutls/all/conanfile.py
Specify library name and version:  **gnutls/***
---
=> gnutls/all: bump deps

recipes/sobjectizer/all/conandata.yml, recipes/sobjectizer/config.yml
Specify library name and version:  **sobjectizer/5.8.1**
---
=> SObjectizer: add version 5.8.1

recipes/iowow/all/conandata.yml, recipes/iowow/all/conanfile.py, recipes/iowow/all/patches/1.4.16-0001-some-fix-for-macOS.patch, recipes/iowow/all/patches/1.4.16-0002-fix-uint64_t-format.patch, recipes/iowow/all/test_package/CMakeLists.txt, recipes/iowow/all/test_package/conanfile.py, recipes/iowow/all/test_package/test_package.c, recipes/iowow/config.yml
Specify library name and version:  **iowow/***
---
=> iowow: add recipe

recipes/xmlsec/all/conanfile.py, recipes/xmlsec/all/test_package/conanfile.py
Specify library name and version:  **xmlsec/***
---
=> xmlsec/all: bump deps

recipes/nghttp3/all/conandata.yml, recipes/nghttp3/all/conanfile.py, recipes/nghttp3/all/test_package/CMakeLists.txt, recipes/nghttp3/all/test_package/test_package.c, recipes/nghttp3/config.yml
Specify library name and version:  **nghttp3/***
---
=> nghttp3: add version 1.0.0, with small improvements

recipes/mm_file/all/conandata.yml, recipes/mm_file/all/conanfile.py, recipes/mm_file/all/test_package/CMakeLists.txt, recipes/mm_file/all/test_package/conanfile.py, recipes/mm_file/all/test_package/test_package.cpp, recipes/mm_file/config.yml
Specify library name and version:  **mm_file/1.0.0**
---
=> mm_file: add recipe

recipes/vulkan-loader/all/conanfile.py
Specify library name and version:  **vulkan-loader/***
---
=> vulkan-loader/all: bump deps

recipes/libuvc/all/conanfile.py
Specify library name and version:  **libuvc/***
---
=> libuvc/all: bump deps

recipes/libgeotiff/all/conanfile.py
Specify library name and version:  **libgeotiff/***
---
=> libgeotiff/all: bump deps

recipes/tracy/all/conandata.yml, recipes/tracy/config.yml
Specify library name and version:  **tracy/0.10**
---
=> tracy: add version 0.10

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/1.5.3**
---
=> glaze: add version 1.5.3

recipes/coin-osi/all/conanfile.py, recipes/coin-osi/all/test_package/conanfile.py
Specify library name and version:  **coin-osi/***
---
=> coin-osi/all: bump deps

recipes/zlib-ng/all/conandata.yml, recipes/zlib-ng/config.yml
Specify library name and version:  **zlib-ng/2.1.4**
---
=> zlib-ng: add version 2.1.4

recipes/tesseract/all/conanfile.py
Specify library name and version:  **tesseract/all**
---
=> tesseract/all: bump deps

recipes/ade/all/conandata.yml, recipes/ade/config.yml
Specify library name and version:  **ade/0.1.2d**
---
=> ade: added 0.1.2d version

recipes/zulu-openjdk/all/conandata.yml, recipes/zulu-openjdk/all/conanfile.py, recipes/zulu-openjdk/config.yml
Specify library name and version:  **zulu-openjdk/***
- LTS 21.0.1
- LTS 17.0.9
---
=> zulu-openjdk: add version 21.0.1, 17.0.9

recipes/meson/all/conandata.yml, recipes/meson/config.yml
Specify library name and version:  **meson/1.2.3**
---
=> meson: Add version 1.2.3

recipes/librttopo/all/conanfile.py
=> librttopo/all: bump deps

recipes/coin-clp/all/conanfile.py
Specify library name and version:  **coin-clp/***
---
=> coin-clp/all: bump deps

recipes/utfcpp/all/conandata.yml, recipes/utfcpp/config.yml
Specify library name and version:  **utfcpp/4.0.0**
---
=> utfcpp: add version 4.0.0

recipes/objectbox/all/conandata.yml, recipes/objectbox/all/conanfile.py, recipes/objectbox/all/test_package/CMakeLists.txt, recipes/objectbox/config.yml
Specify library name and version:  **objectbox/***
---
=> objectbox: add version 0.19.0, add package_type

recipes/ensmallen/all/conandata.yml, recipes/ensmallen/all/conanfile.py, recipes/ensmallen/all/test_package/CMakeLists.txt, recipes/ensmallen/all/test_package/conanfile.py, recipes/ensmallen/all/test_package/src/example.cpp, recipes/ensmallen/config.yml
Specify library name and version:  **ensmallen/2.19.1**
Closes #6797
---
=> [ensmallen] Add ensmallen recipe

recipes/utf8proc/all/conandata.yml, recipes/utf8proc/all/conanfile.py, recipes/utf8proc/config.yml
Specify library name and version:  **utf8proc/***
---
=> utf8proc: add version 2.9.0

recipes/coin-cgl/all/conanfile.py, recipes/coin-cgl/all/test_package/conanfile.py
Specify library name and version:  **coin-cgl/***
---
=> coin-cgl/all: bump deps

recipes/cppfront/all/conandata.yml, recipes/cppfront/config.yml
Specify library name and version:  **cppfront/cci.20231017**
---
=> cppfront: bump

recipes/vulkan-validationlayers/all/conandata.yml, recipes/vulkan-validationlayers/all/conanfile.py, recipes/vulkan-validationlayers/all/dependencies/dependencies-1.2.182.yml, recipes/vulkan-validationlayers/all/dependencies/dependencies-1.2.189.2.yml, recipes/vulkan-validationlayers/all/dependencies/dependencies-1.2.198.0.yml, recipes/vulkan-validationlayers/all/dependencies/dependencies-1.3.204.1.yml, recipes/vulkan-validationlayers/config.yml
Specify library name and version:  **vulkan-validationlayers/***
---
=> vulkan-validationlayers/all: bump deps

recipes/ixwebsocket/all/conanfile.py
Specify library name and version:  **ixwebsocket/any**
---
=> [ixwebsocket] Bump ixwebsocket's zlib requirement to [>=1.2.11 <2] range

recipes/wide-integer/all/conandata.yml, recipes/wide-integer/all/conanfile.py, recipes/wide-integer/all/test_package/CMakeLists.txt, recipes/wide-integer/all/test_package/conanfile.py, recipes/wide-integer/all/test_package/test_package.cpp, recipes/wide-integer/config.yml
Specify library name and version:  **wide-integer/***
---
=> wide-integer: add recipe

recipes/xerces-c/all/conanfile.py
=> xerces-c: bump icu, libcurl version range, `host_version` in build requirements

recipes/libmediainfo/all/conanfile.py
=> libmediainfo: version range for libcurl

recipes/linux-headers-generic/all/conanfile.py
Specify library name and version:  **linux-headers-generic**
See problem described in https://github.com/conan-io/conan-center-index/issues/18877
---
=> [linux-headers-generic] remove cross-building constraint

recipes/cfitsio/all/conandata.yml, recipes/cfitsio/all/conanfile.py, recipes/cfitsio/config.yml
=> cfitsio: add 4.3.0 + version range for libcurl

recipes/libxft/all/conanfile.py
Specify library name and version:  **libxft/all**
---
=> libxft/all: bump deps

recipes/c-ares/all/conandata.yml, recipes/c-ares/config.yml
Specify library name and version:  **c-ares/1.21.0**
---
=> c-ares: add version 1.21.0

recipes/simdjson/all/conandata.yml, recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.5.0**
---
=> simdjson: add version 3.5.0

recipes/highfive/all/conanfile.py
Specify library name and version:  **highfive/***
---
=> highfive: update xtensor/0.24.6

recipes/ada/all/conandata.yml, recipes/ada/config.yml
Specify library name and version:  **ada/2.7.2**
---
=> ada: add version 2.7.2

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.38.6**
---
=> etl: add version 20.38.6

recipes/utfcpp/all/conandata.yml, recipes/utfcpp/config.yml
Specify library name and version:  **utfcpp/4.0.1**
---
=> utfcpp: add version 4.0.1

recipes/jsoncons/all/conandata.yml, recipes/jsoncons/config.yml
Specify library name and version:  **jsoncons/0.171.1**
---
=> jsoncons: add version 0.171.1

recipes/s2n/all/conandata.yml, recipes/s2n/config.yml
Specify library name and version:  **s2n/1.3.55**
---
=> s2n: add version 1.3.55

recipes/asio/all/conandata.yml, recipes/asio/config.yml
Specify library name and version:  **asio/1.28.2**
---
=> asio: add version 1.28.2

recipes/openssl/3.x.x/conandata.yml, recipes/openssl/config.yml
Specify library name and version:  **openssl/3.x.x**
---
=> openssl: add 3.0.12 & 3.1.4

recipes/samurai/all/conandata.yml, recipes/samurai/all/conanfile.py, recipes/samurai/all/test_package/conanfile.py, recipes/samurai/config.yml
Specify library name and version:  **samurai/***
---
=> samurai: add version 0.8.0, update dependenies

recipes/cairo/config.yml, recipes/cairo/meson/conandata.yml, recipes/cairo/meson/conanfile.py
Specify library name and version:  **cairo/1.18.0**
cairo/1.18.0 drop reference to OpenGL backend. (https://cairographics.org/news/cairo-1.18.0/)
---
=> cairo: add version 1.18.0, update meson

recipes/itlib/all/conandata.yml, recipes/itlib/config.yml
Specify library name and version:  **itlib/1.10.0**
---
=> itlib: add version 1.10.0, remove older versions

recipes/crossguid/all/conandata.yml, recipes/crossguid/all/conanfile.py, recipes/crossguid/all/patches/0001-add-installer.patch, recipes/crossguid/all/test_package/CMakeLists.txt, recipes/crossguid/all/test_package/conanfile.py, recipes/crossguid/all/test_package/test_package.cpp, recipes/crossguid/config.yml
Specify library name and version:  **crossguid/***
---
=> crossguid: add recipe

recipes/librdkafka/all/conandata.yml, recipes/librdkafka/all/conanfile.py, recipes/librdkafka/all/patches/0002-Change-library-targets-and-result-variables-2-3-0.patch, recipes/librdkafka/config.yml
Specify library name and version:  **librdkafka/***
---
=> librdkafka: add version 2.3.0, make libcurl version ranges

recipes/drogon/all/conandata.yml, recipes/drogon/all/conanfile.py, recipes/drogon/all/patches/1.9.0-0002-find-cci-packages.patch, recipes/drogon/config.yml
=> drogon: add version 1.9.0, update dependencies

recipes/cpp-ipc/all/conandata.yml, recipes/cpp-ipc/config.yml
Specify library name and version:  **cpp-ipc/1.3.0**
---
=> cpp-ipc: add version 1.3.0

recipes/sqlite3/all/conandata.yml, recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.44.0**
---
=> sqlite3: add version 3.44.0

recipes/openjpeg/all/conanfile.py
Specify library name and version:  **openjpeg/2.5.0**
---
=> openjpeg: Prefer SPDX identifier

recipes/minizip-ng/all/conandata.yml, recipes/minizip-ng/all/conanfile.py, recipes/minizip-ng/config.yml
Specify library name and version:  **minizip-ng/***
---
=> minizip-ng: add version 4.0.2, update dependencies, remove duplicated package_type

recipes/spirv-headers/all/conandata.yml, recipes/spirv-headers/config.yml
=> spirv-headers: add 1.3.261.1 & 1.3.268.0 + remove several old versions

recipes/jsbsim/all/conandata.yml, recipes/jsbsim/all/conanfile.py, recipes/jsbsim/all/patches/1.1.13-0001-expat-link.patch, recipes/jsbsim/all/patches/1.1.13-0002-cmake-install.patch, recipes/jsbsim/all/patches/1.1.13-0003-fix-use-t-before-auto-deduction.patch, recipes/jsbsim/all/test_package/CMakeLists.txt, recipes/jsbsim/all/test_package/conanfile.py, recipes/jsbsim/all/test_package/test_package.cpp, recipes/jsbsim/all/test_v1_package/CMakeLists.txt, recipes/jsbsim/all/test_v1_package/conanfile.py, recipes/jsbsim/config.yml
closes https://github.com/conan-io/conan-center-index/issues/20846
---
=> add jsbsim/1.1.13

recipes/re2/all/conandata.yml, recipes/re2/config.yml
Specify library name and version:  **re2/20231101**
---
=> re2: add version 20231101

recipes/libxmlpp/all/conandata.yml, recipes/libxmlpp/all/conanfile.py, recipes/libxmlpp/all/patches/5.0.3-0001-enable_static_builds_on_msvc.patch, recipes/libxmlpp/config.yml
Specify library name and version:  **libxmlpp/***
---
=> libxmlpp: add version 5.0.3, update dependencies

recipes/onnx/all/conandata.yml, recipes/onnx/all/conanfile.py, recipes/onnx/config.yml
Specify library name and version:  **onnx/1.15.0**
closes https://github.com/conan-io/conan-center-index/pull/20090
---
=> onnx: add version 1.15.0

recipes/cyrus-sasl/all/conandata.yml, recipes/cyrus-sasl/all/conanfile.py, recipes/cyrus-sasl/config.yml
Specify library name and version:  **cyrus-sasl/***
---
=> cyrus-sasl: add version 2.1.28, update dependencies

recipes/libgcrypt/all/conanfile.py
Specify library name and version:  **libgcrypt/all**
---
=> bump dependencies of libgcrypt

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/1.5.7**
---
=> glaze: add version 1.5.7

recipes/nsimd/2.x/CMakeLists.txt, recipes/nsimd/2.x/conanfile.py, recipes/nsimd/2.x/test_package/conanfile.py, recipes/nsimd/2.x/test_v1_package/CMakeLists.txt, recipes/nsimd/2.x/test_v1_package/conanfile.py
Specify library name and version:  **nsimd/3.0.1**
---
=> (#20906) nsimd: conan v2 support

recipes/accellera-uvm-systemc/all/conanfile.py, recipes/accellera-uvm-systemc/all/test_package/CMakeLists.txt, recipes/accellera-uvm-systemc/all/test_package/conanfile.py, recipes/accellera-uvm-systemc/all/test_package/example.cpp, recipes/accellera-uvm-systemc/all/test_v1_package/CMakeLists.txt, recipes/accellera-uvm-systemc/all/test_v1_package/conanfile.py
=> accellera-uvm-systemc: migrate to Conan v2

recipes/hayai/all/conandata.yml, recipes/hayai/all/conanfile.py, recipes/hayai/all/patches/fix-cmake-project.patch, recipes/hayai/all/test_package/CMakeLists.txt, recipes/hayai/all/test_package/conanfile.py, recipes/hayai/all/test_package/test_package.cpp, recipes/hayai/config.yml
Adds https://github.com/nickbruun/hayai, a C++ benchmarking framework
=> hayai: add a new recipe

recipes/highfive/all/conandata.yml, recipes/highfive/all/conanfile.py, recipes/highfive/config.yml
Specify library name and version:  **highfive/2.8.0**
---
- [X ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [X ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [X ] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
=> [highfive] Bump version to 2.8.0

recipes/aws-c-sdkutils/all/conanfile.py
Specify library name and version:  **aws-c-sdkutils/***
---
=> aws-c-sdkutils: update aws-c-common/0.9.6

recipes/cs_libguarded/all/conandata.yml, recipes/cs_libguarded/config.yml
Specify library name and version:  **cs_libguarded/1.4.1**
---
=> cs_libguarded: add version 1.4.1

recipes/aws-c-compression/all/conanfile.py
Specify library name and version:  **aws-c-compression/***
---
=> aws-c-compression: update aws-c-common/0.9.6

recipes/zpp_bits/all/conandata.yml, recipes/zpp_bits/config.yml
Specify library name and version:  **zpp_bits/4.4.20**
---
=> zpp_bits: add version 4.4.20

recipes/hwdata/all/conandata.yml, recipes/hwdata/config.yml
Specify library name and version:  **hwdata/0.376**
---
=> hwdata: add version 0.376

recipes/paho-mqtt-c/all/conandata.yml, recipes/paho-mqtt-c/config.yml
Specify library name and version:  **paho-mqtt-c/1.3.13**
---
=> paho-mqtt-c: add version 1.3.13

recipes/parg/all/conandata.yml, recipes/parg/all/conanfile.py, recipes/parg/config.yml
Specify library name and version:  **parg/1.0.3**
---
=> parg: add version 1.0.3

recipes/quill/all/conandata.yml, recipes/quill/config.yml
Specify library name and version:  **quill/3.4.0**
---
=> quill: add version 3.4.0

recipes/aws-lambda-cpp/all/conandata.yml, recipes/aws-lambda-cpp/all/conanfile.py, recipes/aws-lambda-cpp/config.yml
Specify library name and version:  **aws-lambda-cpp/***
---
=> aws-lambda-cpp: add version 0.2.9

recipes/twitchtv-libsoundtrackutil/all/CMakeLists.txt, recipes/twitchtv-libsoundtrackutil/all/conandata.yml, recipes/twitchtv-libsoundtrackutil/all/conanfile.py, recipes/twitchtv-libsoundtrackutil/all/patches/cmake-fixes.patch, recipes/twitchtv-libsoundtrackutil/all/test_package/CMakeLists.txt, recipes/twitchtv-libsoundtrackutil/all/test_package/conanfile.py, recipes/twitchtv-libsoundtrackutil/all/test_v1_package/CMakeLists.txt, recipes/twitchtv-libsoundtrackutil/all/test_v1_package/conanfile.py
=> twitchtv-libsoundtrackutil: migrate to Conan v2

recipes/libdispatch/all/CMakeLists.txt, recipes/libdispatch/all/conanfile.py, recipes/libdispatch/all/test_package/CMakeLists.txt, recipes/libdispatch/all/test_package/conanfile.py, recipes/libdispatch/all/test_v1_package/CMakeLists.txt, recipes/libdispatch/all/test_v1_package/conanfile.py
=> libdispatch: migrate to Conan v2

recipes/dime/all/CMakeLists.txt, recipes/dime/all/conanfile.py, recipes/dime/all/test_package/CMakeLists.txt, recipes/dime/all/test_package/conanfile.py, recipes/dime/all/test_v1_package/CMakeLists.txt, recipes/dime/all/test_v1_package/conanfile.py
=> dime: migrate to Conan v2

recipes/libcoap/all/CMakeLists.txt, recipes/libcoap/all/conandata.yml, recipes/libcoap/all/conanfile.py, recipes/libcoap/all/test_package/CMakeLists.txt, recipes/libcoap/all/test_package/conanfile.py, recipes/libcoap/all/test_v1_package/CMakeLists.txt, recipes/libcoap/all/test_v1_package/conanfile.py, recipes/libcoap/config.yml
=> libcoap: migrate to Conan v2

recipes/nanosvg/all/conandata.yml, recipes/nanosvg/all/conanfile.py, recipes/nanosvg/all/test_package/conanfile.py, recipes/nanosvg/config.yml
Specify library name and version:  **nanosvg/cci.20231025**
---
=> nanosvg: add version cci.20231025

recipes/sfml/all/conandata.yml, recipes/sfml/all/conanfile.py, recipes/sfml/all/patches/2.6.1-0006-disable-warning-flags.patch, recipes/sfml/config.yml
Specify library name and version:  **sfml/***
---
=> sfml: add version 2.6.1, update stb

recipes/function2/all/conandata.yml, recipes/function2/config.yml
Specify library name and version:  **function2/4.2.4**
---
=> function2: add version 4.2.4

recipes/cthash/all/conanfile.py
Most folks won't define something like compiler.version=12.2, but compiler.version=12, so relax version check.
Do not define msvc min version since it raises anyway for msvc, it's misleading.
---
=> cthash: relax compiler version check

recipes/aws-c-cal/all/conandata.yml, recipes/aws-c-cal/all/patches/0002-apple-corefoundation-0.6.9.patch, recipes/aws-c-cal/config.yml
Specify library name and version:  **aws-c-cal/0.6.9**
---
=> aws-c-cal: add  version 0.6.9

recipes/microservice-essentials/all/conanfile.py
Specify library name and version:  **microservice-essentials/***
---
=> microservice-essentials/all: bump deps

recipes/volk/all/conandata.yml, recipes/volk/all/conanfile.py, recipes/volk/config.yml
=> volk: add 1.3.250.0, 1.3.261.1 and 1.3.268.0 + remove old versions

recipes/czmq/all/conanfile.py
Specify library name and version:  **czmq/***
---
=> czmq/all: bump deps

recipes/arrow/all/conandata.yml, recipes/arrow/config.yml
Specify library name and version:  **arrow/14.0.0**
=> arrow: add version 14.0.0

recipes/emio/all/conandata.yml, recipes/emio/config.yml
Specify library name and version:  **emio/0.6.1**
---
=> emio: add version 0.6.1

recipes/fakeit/all/conanfile.py
Specify library name and version:  **fakeit/***
---
=> fakeit/all: bump deps

recipes/aws-c-io/all/conanfile.py
Specify library name and version:  **aws-c-io/***
---
=> aws-c-io: update dependencies

recipes/zstd/all/conanfile.py
It fixes another regression coming from https://github.com/conan-io/conan-center-index/pull/18826, this time for MinGW
---
=> zstd: do not remove import lib for mingw if shared & build_programs

recipes/enchant/all/CMakeLists.txt, recipes/enchant/all/conandata.yml, recipes/enchant/all/conanfile.py, recipes/enchant/all/test_package/CMakeLists.txt, recipes/enchant/all/test_package/conanfile.py, recipes/enchant/all/test_v1_package/CMakeLists.txt, recipes/enchant/all/test_v1_package/conanfile.py
=> enchant: migrate to Conan v2

recipes/continuable/all/conanfile.py
Specify library name and version:  **continuable/***
---
=> continuable: update funciton2/4.2.4

recipes/asyncly/all/conanfile.py
Specify library name and version:  **asyncly/***
---
=> asyncly: update function2/4.2.4

recipes/cimg/all/conanfile.py
Specify library name and version:  **cimg/***
---
=> cimg: update openexr/3.2.1

recipes/aws-c-io/all/conandata.yml, recipes/aws-c-io/config.yml
Specify library name and version:  **aws-c-io/0.13.35**
---
=> aws-c-io: add version 0.13.35

recipes/aws-checksums/all/conanfile.py
Specify library name and version:  **aws-checksums/***
---
=> aws-checksums: update aws-c-common/0.9.6

recipes/ada/all/conandata.yml, recipes/ada/config.yml
Specify library name and version:  **ada/2.7.3**
---
=> ada: add version 2.7.3

recipes/cglm/all/conandata.yml, recipes/cglm/all/conanfile.py, recipes/cglm/all/test_package/CMakeLists.txt, recipes/cglm/all/test_package/conanfile.py, recipes/cglm/all/test_v1_package/CMakeLists.txt, recipes/cglm/config.yml
=> cglm: migrate to Conan v2

recipes/libpciaccess/all/conanfile.py
Specify library name and version:  **libpciaccess/***
---
=> libpciaccess: bump pkgconf

recipes/aws-kvs-pic/all/test_package/conanfile.py, recipes/aws-kvs-pic/all/test_v1_package/conanfile.py
Specify library name and version:  **aws-kvs-pic/***
---
=> aws-kvs-pic: bump pkgconf

recipes/emsdk/all/conandata.yml, recipes/emsdk/config.yml
Specify library name and version:  **emsdk/all**
---
=> emsdk: new versions

recipes/libcap/all/test_package/conanfile.py, recipes/libcap/all/test_v1_package/conanfile.py
Specify library name and version:  **libcap/***
---
=> libcap: bump pkgconf

recipes/sdbus-cpp/all/test_pkgconf/conanfile.py
Specify library name and version:  **sdbus-cpp/***
---
=> sdbus-cpp: bump pkgconf

recipes/coin-cgl/all/test_v1_package/conanfile.py
=> coin-cgl: bump pkgconf

recipes/libmaxminddb/all/conandata.yml, recipes/libmaxminddb/config.yml
Specify library name and version:  **libmaxminddb/1.8.0**
---
=> libmaxminddb: add version 1.8.0

recipes/sentry-breakpad/all/test_package/conanfile.py
Specify library name and version:  **sentry-breakpad/***
---
=> sentry-breakpad: bump pkgconf

recipes/coin-utils/all/test_package/conanfile.py, recipes/coin-utils/all/test_v1_package/conanfile.py
Specify library name and version:  **coin-utils/***
---
=> coin-utils: bump pkgconf

recipes/arrow/all/conandata.yml, recipes/arrow/config.yml
Specify library name and version:  **arrow/14.0.1**
=> arrow: add version 14.0.1

recipes/onnxruntime/all/conandata.yml, recipes/onnxruntime/config.yml
Specify library name and version:  **onnxruntime/1.16.2**
---
=> onnxruntime: add version 1.16.2

recipes/c-blosc2/all/conandata.yml, recipes/c-blosc2/config.yml
Specify library name and version:  **c-blosc2/2.11.2**
---
=> c-blosc2: add version 2.11.2

recipes/luau/all/conandata.yml, recipes/luau/config.yml
Specify library name and version:  **luau/0.603**
---
=> luau: add version 0.603

recipes/sjson-cpp/all/conandata.yml, recipes/sjson-cpp/config.yml
Specify library name and version:  **sjson-cpp/***
---
=> sjson-cpp: add version 0.9.0

recipes/roaring/all/conandata.yml, recipes/roaring/config.yml
=> roaring: add 2.0.4

recipes/flecs/all/conandata.yml, recipes/flecs/config.yml
=> flecs: add 3.2.8

recipes/libjpeg-turbo/all/conandata.yml, recipes/libjpeg-turbo/config.yml
=> Bump libjpeg-turbo/3.0.1

recipes/ezc3d/all/conandata.yml, recipes/ezc3d/config.yml
=> ezc3d: add 1.5.5

recipes/zbar/all/conanfile.py
Specify library name and version:  **zbar/***
---
=> zbar: bump pkgconf

recipes/harfbuzz/all/conandata.yml, recipes/harfbuzz/config.yml
Specify library name and version:  **harfbuzz/8.3.0**
---
=> harfbuzz: add version 8.3.0

recipes/spirv-tools/all/conandata.yml, recipes/spirv-tools/all/conanfile.py, recipes/spirv-tools/config.yml
=> spirv-tools: add new versions, remove old ones

recipes/sdl_net/all/conanfile.py, recipes/sdl_net/all/test_package/CMakeLists.txt, recipes/sdl_net/all/test_package/conanfile.py
- bump sdl
- add transitive_headers=True for sdl dependency, since SDL_net.h includes several public headers of sdl
- add sdl to direct dependencies of test package, because this test package has to initialize sdl and therefore use some symbols of sdl lib (we can't just rely on transitive_headers=True of sdl_net recipe here).
---
=> sdl_net: add package_type + bump sdl + fix transitive_headers of sdl

recipes/libuv/all/conandata.yml, recipes/libuv/all/patches/1.47.0/fix-cmake.patch, recipes/libuv/config.yml
Specify library name and version:  **libuv/1.47.0**
---
=> libuv: add version 1.47.0

recipes/oatpp-postgresql/all/conanfile.py
Specify library name and version:  **oatpp-postgresql/***
---
=> oatpp-postgresql/all: bump deps

recipes/si/all/conandata.yml, recipes/si/all/conanfile.py, recipes/si/config.yml
Specify library name and version:  **si/2.5.3**
---
=> si: add version 2.5.3

recipes/stx/all/conanfile.py
validate() doesn't need all these checks after https://github.com/conan-io/conan-center-index/pull/20861, it can be simplified a lot
---
=> stx: simplify validate()

recipes/llhttp/all/conandata.yml, recipes/llhttp/all/conanfile.py, recipes/llhttp/all/patches/v9.1.3-cmake_remove_pcfiles.patch, recipes/llhttp/config.yml
Specify library name and version:  **llhttp/9.1.3**
---
=> Add llhttp v9.1.3

recipes/alembic/all/conandata.yml, recipes/alembic/all/conanfile.py, recipes/alembic/config.yml
also fix description of patches
---
=> alembic: add 1.8.6 + bump hdf5

recipes/blend2d/all/conandata.yml, recipes/blend2d/all/conanfile.py, recipes/blend2d/all/patches/0.10.6-0001-disable-embed-asmjit.patch, recipes/blend2d/config.yml
Specify library name and version:  **blend2d/***
---
=> blend2d: add version 0.10.6, add with_jit option

linter/check_package_name.py
fixes error raised on sdbs-cpp/all/test_pkgconf test recipe for example
cf https://github.com/conan-io/conan-center-index/actions/runs/6824776047/job/18561352288?pr=21047#step:8:19
---
=> linter: fix name detection

recipes/opene57/all/conanfile.py
=> opene57: add min version for `compiler=msvc`

recipes/libdc1394/all/conanfile.py
Specify library name and version:  **libdc1394/***
---
=> libdc1394: bump pkgconf

recipes/mozjpeg/all/conanfile.py
Specify library name and version:  **mozjpeg/***
---
=> mozjpeg/all: bump deps

recipes/msys2/all/conandata.yml, recipes/msys2/config.yml
Specify library name and version:  **msys2/***
---
=> msys2: bump

recipes/imake/all/conandata.yml, recipes/imake/all/conanfile.py, recipes/imake/all/test_package/conanfile.py, recipes/imake/config.yml
Specify library name and version:  **imake/***
---
=> imake/all: bump deps

recipes/very-simple-smtps/all/conanfile.py, recipes/very-simple-smtps/all/test_package/conanfile.py
Specify library name and version:  **very-simple-smtps/1.0**
---
=> very-simple-smtps/all: bump deps

recipes/elfutils/all/conanfile.py
Specify library name and version:  **elfutils/***
---
=> elfutils: bump deps

recipes/libdicom/all/conandata.yml, recipes/libdicom/all/conanfile.py, recipes/libdicom/all/test_package/conanfile.py, recipes/libdicom/all/test_package/meson.build, recipes/libdicom/all/test_package/test_package.c, recipes/libdicom/config.yml
Adds libdicom: https://github.com/ImagingDataCommons/libdicom
[![Packaging status](https://repology.org/badge/tiny-repos/libdicom.svg)](https://repology.org/project/libdicom/versions)
=> libdicom: add a new recipe

recipes/libnetfilter_queue/all/conanfile.py
Specify library name and version:  **libnetfilter_queue/***
---
=> libnetfilter queue/all: bump deps

recipes/avahi/all/conanfile.py
Specify library name and version:  **avahi/***
---
=> avahi/all: bump deps

recipes/libxshmfence/all/conanfile.py
Specify library name and version:  **libxshmfence/***
---
=> libxshmfence/all: bump deps

recipes/coin-osi/all/test_v1_package/conanfile.py
Specify library name and version:  **coin-osi/***
---
=> coin-osi: bump deps

recipes/libnice/all/conanfile.py
Specify library name and version:  **libnice/***
---
=> libnice/all:bump deps

recipes/sdbus-cpp/all/test_v1_pkgconf/conanfile.py
Specify library name and version:  **sdbus-cpp/***
---
=> sdbus-cpp: bump deps

recipes/pupnp/all/conanfile.py
Specify library name and version:  **pupnp/***
---
=> pupnp/all: bump deps

recipes/cpr/all/conandata.yml, recipes/cpr/config.yml
Specify library name and version:  **cpr/1.10.5**
---
=> cpr: add version 1.10.5

recipes/tsil/all/conandata.yml, recipes/tsil/all/conanfile.py
=> tsil: use rm_safe

recipes/czmq/all/conanfile.py
=> czmq: use version range for libcurl + add package_type

recipes/libgphoto2/all/conanfile.py
=> libgphoto2: use version range for libcurl + bump deps

recipes/c4core/all/conanfile.py
=> c4core: update fast_float/5.3.0

recipes/restinio/config.yml, recipes/restinio/v0.7/conandata.yml, recipes/restinio/v0.7/conanfile.py, recipes/restinio/v0.7/test_package/CMakeLists.txt, recipes/restinio/v0.7/test_package/conanfile.py, recipes/restinio/v0.7/test_package/test_package.cpp
Specify library name and version:  **RESTinio/0.7.0**
---
=> Update RESTinio to version 0.7.0

recipes/xorg-cf-files/all/conanfile.py, recipes/xorg-cf-files/all/test_package/conanfile.py
=> xorg-cf-files/all: bump deps

recipes/llvm-openmp/all/conandata.yml
identified in https://github.com/conan-io/conan-center-index/issues/21146
Specify library name and version:  **llvm-openmp/***
---
=> llvm-openmp: fix patching

recipes/serf/all/conanfile.py
=> serf: relocatable shared lib for macOS

recipes/rangesnext/all/conandata.yml
There never was any patch in this recipe
identified in https://github.com/conan-io/conan-center-index/issues/21146
Specify library name and version:  **rangesnext/***
---
=> rangesnext: remove bogus patches section

recipes/ssp/all/conanfile.py
Specify library name and version:  **ssp/***
---
=> ssp: update fast_float/5.3.0

recipes/dacap-clip/all/conandata.yml, recipes/dacap-clip/config.yml
Specify library name and version:  **dacap-clip/1.7**
---
=> dacap-clip: add version 1.7

recipes/c-ares/all/conandata.yml, recipes/c-ares/config.yml
Specify library name and version:  **c-ares/1.22.0**
---
=> c-ares: add version 1.22.0

.c3i/authorized_users.yml
Remove usernames that no longer exist in Github
=> Remove missing users from authorized_users.yml

recipes/cimg/all/conandata.yml, recipes/cimg/config.yml
Specify library name and version:  **cimq/any**
Reduce the number of supported versions, so we update the fftw too.
---
=> [cimq] Reduce number of versions supported

recipes/fast-cdr/all/conandata.yml, recipes/fast-cdr/config.yml
Specify library name and version:  **fast-cdr/2.1.0**
Add latest version.
---
=> fast-cdr: add version 2.1.0

recipes/iowow/all/conandata.yml, recipes/iowow/config.yml
Specify library name and version:  **iowow/1.4.17**
---
=> iowow: add version 1.4.17

recipes/libarchive/all/conandata.yml, recipes/libarchive/all/patches/0001-3.7.2-zlib-winapi.patch, recipes/libarchive/config.yml
Specify library name and version:  **libarchive/3.7.2**
---
=> libarchive: add version 3.7.2

recipes/certify/all/conanfile.py
=> certify/all: bump deps

recipes/soci/all/conanfile.py
Specify library name and version:  **soci/all**
---
=> soci: bump sqlite3

recipes/libwebsockets/all/conanfile.py
Specify library name and version:  **libwebsockets/all**
---
=> libwebsockets: bump deps

recipes/sqlitecpp/all/conanfile.py
Specify library name and version:  **sqlitecpp/all**
---
=> sqlitecpp: bump sqlite3

recipes/samurai/all/conandata.yml, recipes/samurai/config.yml
Specify library name and version:  **samurai/0.9.0**
---
=> samurai: add version 0.9.0

recipes/mcap/all/conandata.yml, recipes/mcap/config.yml
Specify library name and version:  **mcap/1.3.0**
---
=> mcap: add version 1.3.0

recipes/simdutf/all/conandata.yml, recipes/simdutf/config.yml
Specify library name and version:  **simdutf/4.0.4**
---
=> simdutf: add version 4.0.4

recipes/uncrustify/all/conandata.yml, recipes/uncrustify/config.yml
=> [uncrustify] Add version 0.78.0

recipes/shield/all/conandata.yml, recipes/shield/config.yml
Specify library name and version:  **shield/0.5**
---
=> shield: add version 0.5

recipes/hictk/all/conanfile.py
Specify library name and version:  **hictk/***
---
=> hictk: update dependencies

recipes/rtmidi/all/conanfile.py
=> rtmidi: bump libalsa

recipes/openal-soft/all/conanfile.py
=> openal-soft: bump libalsa

recipes/s2n/all/conandata.yml, recipes/s2n/config.yml
Specify library name and version:  **s2n/1.3.56**
---
=> s2n: add version 1.3.56

recipes/fontconfig/all/conanfile.py, recipes/fontconfig/meson/conanfile.py
=> fontconfig: bump dependencies

recipes/stringzilla/all/conandata.yml, recipes/stringzilla/config.yml
Specify library name and version:  **stringzilla/2.0.3**
---
=> stringzilla: add version 2.0.3

recipes/proj/all/conanfile.py
And hopefully fixes the missing `proj` binary for #19298.
=> proj: bump sqlite3 dependency

recipes/aggeom-agg/all/conanfile.py
Specify library name and version:  **aggoem-agg/***
---
=> aggeom-agg: update freetype/2.13.2

recipes/pdfium/all/conanfile.py
Specify library name and version:  **pdfuim/***
---
=> pdfuim: update freetype/2.13.2
