recipes/openblas/all/conanfile.py
Version 0.3.21 of openblas introduced the ability to build lapack from C. Make this default to enable CCI recipes to use lapack when depending on openblas.
Additionally, fix an inconsistency in version constraint. Review was provided in https://github.com/conan-io/conan-center-index/pull/19808 to constrain it to 0.3.24 as this was the latest version available in CCI. However, functionality to build lapack was added in 0.3.21, so it doesn't really make sense to exclude versions between 0.3.21 and 0.3.24 from building lapack should they be added at a later date.
Closes #7361
Specify library name and version:  **openblas/0.3.24**
---
=> [openblas] Make build_lapack=True default for >= 0.3.21

recipes/json-schema-validator/all/conandata.yml, recipes/json-schema-validator/all/conanfile.py, recipes/json-schema-validator/all/test_package/CMakeLists.txt, recipes/json-schema-validator/config.yml
Specify library name and version:  **json-schema-validator/***
---
=> json-schema-validator: add version 2.3.0, downgrade nolhmann_json in older versions

recipes/gsoap/all/conandata.yml, recipes/gsoap/config.yml
Dropped versions that are no longer available upstream: https://sourceforge.net/projects/gsoap2/files/
=> gsoap: add v2.8.132, drop old versions

recipes/msys2/all/test_package/conanfile.py, recipes/msys2/all/test_v1_package/conanfile.py
Specify library name and version:  **msys2/cci.latest**
Test package recipes use `print()`, which breaks the json output of conan commands.
I think they are just leftovers from previous debugging sessions.
---
=> Remove prints from msys2 test recipes

recipes/bazel/all/conandata.yml, recipes/bazel/config.yml
Specify library name and version:  **bazel/5.4.1**
_fixes #22210_
Reason:
The tensorflow_cc package does not support current versions and requires versions >= 4.2.2 and <= 5.99.0
Version 5.4.1 is the latest in this required range (>= 4.2.2 and <= 5.99.0).
---
=> (#22210) bazel: add version 5.4.1

recipes/llvm-openmp/all/conandata.yml, recipes/llvm-openmp/all/conanfile.py, recipes/llvm-openmp/config.yml
* Fixes #22104
This enables the package for non-macOS apple-clang builds and for MinGW (which should be compatible: https://packages.msys2.org/package/mingw-w64-clang-x86_64-openmp).
=> llvm-openmp: add v17.0.6, relax OS/compiler checks

recipes/base64/all/conandata.yml, recipes/base64/config.yml
Specify library name and version:  **base64/0.5.2**
---
=> base64: add version 0.5.2

recipes/boost/all/conandata.yml, recipes/boost/all/patches/1.83.0-locale-msvc.patch
Specify library name and version:  **boost/1.83.0**
unblocks:
- https://github.com/conan-io/conan-center-index/pull/22239
- https://github.com/conan-io/conan-center-index/pull/21536
- https://github.com/conan-io/conan-center-index/pull/21334
- https://github.com/conan-io/conan-center-index/pull/19506
And probably most windows consumers of boost 1.83.0
---
=> boost 1.83.0: fix windows without NOMINMAX

recipes/perfetto/all/conandata.yml, recipes/perfetto/config.yml
Specify library name and version:  **perfetto/41.0**
```
v41.0 - 2023-01-02:
* Added support for ADB_SERVER_SOCKET in the websocket bridge.
* Added support for reading Pressure Stall Information (PSI) from the kernel.
* Added capability to control trace processor using stdin/stdout when using
shell binary. This acts as a simpler alternative to the existing HTTP
control API.
* Fixed multiple edge-case issues in RestoreInitialTables.
SDK:
* Fixed a long standing bug that caused the last TrackEvent event for each
thread to be lost during scraping. The fix works with old versions of the
tracing service.
```
---
=> perfetto: Bump version: 41.0

recipes/restinio/v0.7/conanfile.py
Specify library name and version:  **restinio/0.7.1**
This PR bumps `fmt` to `10.2.0` to match other deps in conan center (i.e. `spdlog`, etc..) so as to avoid needing an `override`.
---
=> restinio: bump to `fmt/10.2.0`

recipes/rapidjson/all/conanfile.py
rapidjson/*
Specify that the library is a header-only library to get rid of a warning.
```
ld64.lld: warning: directory not found for option -L/Users/me/.conan2/p/rapidf6bdd1718c30a/p/lib
```
Feature documentation.
https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/header_only_packages.html?highlight=libdirs
---
=> rapidjson/* Specify that rapidjson is a header-only library.

recipes/opentelemetry-proto/all/conandata.yml, recipes/opentelemetry-proto/config.yml
Specify library name and version:  **opentelemetry-proto/1.1.0**
---
=> opentelemetry-proto: add version 1.1.0

recipes/dice-template-library/all/conandata.yml, recipes/dice-template-library/config.yml
Specify library name and version:  **dice-template-library/1.2.0**
---
=> dice-template-library: add version 1.2.0

recipes/rapidjson/all/conanfile.py
Specify library name and version:  **rapidjson/***
The last update to the rapidjson recipe included a `package_id_embed_mode` value of `minor` instead of `minor_mode` which caused build errors such as `AttributeError: 'RequirementInfo' object has no attribute 'minor'` and `'minor' is not a known package_id_mode`.
Problem found in conjunction with @matthewkandiah-sonocent
---
=> rapidjson/*: Fix incorrect `package_id_embed_mode` value.

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  **imgui/1.90.1,1.90.1-docking**
---
=> imgui: add version 1.90.1/1.90.1-docking

recipes/gperftools/all/conanfile.py
The gperftools project exports a .pc file for each of the libraries and also sets `-pthread` in addition to `-lpthread`.
https://github.com/gperftools/gperftools/blob/gperftools-2.15/CMakeLists.txt#L1468-L1484
Required for `jxl`: https://github.com/libjxl/libjxl/blob/v0.9.1/lib/jxl.cmake#L176-L177
=> gperftools: set pkg_config_name for components

recipes/cryptopp/all/conandata.yml, recipes/cryptopp/all/patches/8.9.0-0001-cve-2023-50980.patch
Specify library name and version:  **cryptopp/8.9.0**
Add patch for CVE-2023-50980 that is based on 3 commits:
https://github.com/weidai11/cryptopp/commit/eb383b8e1622
https://github.com/weidai11/cryptopp/commit/641ae35258de
https://github.com/weidai11/cryptopp/commit/93208e83937a
---
=> cryptopp: add patch for CVE-2023-50980

recipes/aws-c-common/all/conandata.yml, recipes/aws-c-common/config.yml
Specify library name and version:  **aws-c-common/0.9.12**
Import the latest version of this library because I am working on this issue: https://github.com/conan-io/conan-center-index/issues/2275
---
=> aws-c-common: add version 0.9.12

recipes/gegles-spdlog_setup/all/conanfile.py
Specify library name and version:  **gegles-spdlog_setup/1.1.0**
---
=> gegles-spdlog_setup: bump to `spdlog/1.13.0`

recipes/libvpx/all/conanfile.py
When cross-building to iOS, the `--target` was `darwin`. Added `iphonesimulator` as the valid target OS name.
Closes: https://github.com/conan-io/conan-center-index/issues/20513
=> libvpx: Added iOS target name

recipes/jasper/all/conandata.yml, recipes/jasper/config.yml
Specify library name and version:  **jasper/4.1.2**
This version fixed [CVE-2023-51257](https://github.com/advisories/GHSA-c74w-77jp-9c48).
---
=> jasper: add version 4.1.2

recipes/arsenalgear/all/conandata.yml, recipes/arsenalgear/all/patches/2.1.1-0001-fix-cmake.patch, recipes/arsenalgear/config.yml
Specify library name and version:  **arsenalgear/2.1.1**
---
=> arsenalgear: add version 2.1.1

.c3i/config_v1.yml
Drop:
- Debug builds for Linux gcc5, gcc7, gcc9 - these are less demanded than gcc11
- Builds for Linux gcc10 - these are a lot less requested than 11, 9 and 7. Not surprising, since 11,9,7 match the default gcc versions in the most recent Ubuntu LTS releases
- Builds for Linux clang12 - very few requests
- Debug builds for Linux clang13 - very few requests, but still valuable to test clang builds on Linux. In v2 pipeline we will add newer versions of clang in the future.
- macOS x86_64 builds - there is already enough testing going on with Conan 2.0 - users who want x86_64 are encouraged to use Conan 2.0.
=> Update CI Conan 1.x configurations

recipes/cairo/meson/conanfile.py
Set `ipc_rmid_deferred_release` property when cross building. Setting this according to runtime behavior is impossible when cross-compiling. Refer to https://gitlab.freedesktop.org/cairo/cairo/-/issues/408. To fix this, set the property `ipc_rmid_deferred_release`. According to the discussion in the issue, this should at least be enabled on Linux. Since other systems may behave differently, this is disabled otherwise.
---
=> cairo: Fix cross-compilation when using Meson

recipes/daw_utf_range/all/conanfile.py
Specify library name and version:  **daw_utf_range/***
daw_header_libraries has changed API since 2.98.0.
---
=> daw utf range header libraries 2.97.0

recipes/libnghttp2/all/conandata.yml, recipes/libnghttp2/config.yml
Specify library name and version:  **libnghttp2/1.59.0**
---
=> libnghttp2: add version 1.59.0

recipes/libe57format/all/conanfile.py
I've asked upstream to remove this hardcoded warning as errors. There is an option, but it's no-op when you build from project tree directly...
Without this fix, it doesn't build with C++20 (errors with msvc 2022 and gcc 12).
---
=> libe57format: disable warnings as errors

recipes/libsystemd/all/conandata.yml, recipes/libsystemd/all/conanfile.py, recipes/libsystemd/config.yml
Fixes the outdated `required_conan_version` value, as mentioned at https://github.com/conan-io/conan-center-index/pull/22436#issuecomment-1900995086 by @bhutch29
=> libsystemd: correct required_conan_version, add v255.2

recipes/qt/5.x.x/conanfile.py
cf https://github.com/qt/qt3d/blob/v5.15.12-lts-lgpl/src/input/frontend/frontend.pri#L82
fixes conan-io/conan-center-index#22435
---
=> qt5: fix qt3D without qtgamepad

recipes/libmicrohttpd/all/conanfile.py
Specify library name and version:  **libmicrohttpd/***
I think pkg_config_name is typo.
https://git.gnunet.org/libmicrohttpd.git/tree/libmicrohttpd.pc.in?h=v0.9.77&id=0c91379e116cd12644d908ca1743cdaab1906816#n6
---
=> libmicrohttpd: fix pkg_config_name

recipes/lksctp-tools/all/conanfile.py
autoreconf is called in build(), therefore libtool is a build requirement. Indeed we can't assume that libtool is installed on users systems.
---
=> lksctp-tools: add libtool in build requirements

recipes/gperftools/all/conanfile.py, recipes/gperftools/all/test_package/CMakeLists.txt, recipes/gperftools/all/test_package/test_package.c
Fixes the build failure in the jxl recipe (#18812):
```
/usr/bin/ld: /home/conan/w/prod-v1/bsr/90439/bedfd/.conan/data/gperftools/2.13.0/_/_/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56/lib/libtcmalloc_minimal.a(libtcmalloc_minimal_la-tcmalloc.o): undefined reference to symbol '_ZSt20__throw_length_errorPKc@@GLIBCXX_3.4'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/libstdc++.so: error adding symbols: DSO missing from command line
```
I can reproduce it in this recipe as well after switching test_package to pure C and building statically without the libcxx dependency added.
=> gperftools: fix missing libcxx dependency

recipes/wolfssl/all/conanfile.py
Specify library name and version:  **wolfssl/***
I met compilation errors on executing `conan install --requires=libcurl/8.5.0@ --build=missing -o libcurl/\*:with_ssl=wolfssl`.
```
libcu091943b01efd5/b/src/lib/http_aws_sigv4.c: In function 'sha256_to_hex':
CC       libcurl_la-if2ip.lo
libcu091943b01efd5/b/src/lib/http_aws_sigv4.c:67:23: error: 'SHA256_DIGEST_LENGTH' undeclared (first use in this function); did you mean 'SHA256_HEX_LENGTH'?
67 |   Curl_hexencode(sha, SHA256_DIGEST_LENGTH,
|                       ^~~~~~~~~~~~~~~~~~~~
|                       SHA256_HEX_LENGTH
libcu091943b01efd5/b/src/lib/http_aws_sigv4.c:67:23: note: each undeclared identifier is reported only once for each function it appears in
libcu091943b01efd5/b/src/lib/http_aws_sigv4.c: In function …
```
=> wolfssl: add with_curl option

recipes/gstreamer/all/conandata.yml, recipes/gstreamer/all/conanfile.py, recipes/gstreamer/config.yml
Specify library name and version: gstreamer/1.22.6
We request the update of the GStreamer version to have all the GStreamer modules aligned to version 1.22.6, the last version before the release of version 1.24
---
=> gstreamer: Add version 1.22.6

recipes/duckdb/all/conanfile.py
Specify library name and version:  **duckdb/0.9.2**
Resolves #22347
The duckdb makefile is the only reference how to specify build flags. That has deteriorated for extensions as of version >=0.9
I have not tried it with a conan center hook, but would be interested to learn how that would be done.
---
=> [fix] Fix DuckDB extension build

docs/changelog.md
- The ConanCenterIndex is now running both Conan 1.62.0 and 2.0.16
- Any bump PR will require a maintainer review to be merged. It has several reasons, including security and coordination to avoid missing dependencies. 
- Previously, header_only option values was now shown in Conan 2.x build results. Now it's fixed.
- Profile config (e.g tools.system.package_manager) is now propagated to test_package execution, fixing those cases where system package are needed
- Fixed internal usage for Github labels, to be treated as string only when parsing.
---
=> [docs] Update changelog 24 January 2024

docs/review_process.md
To avoid mistakes related to incompatible versions and mainly to dependencies graph that result in missing dependencies, the bump PR will require a maintainer review to be merged.
It may delay some PRs to be merged, but in other hand, the team will be able to check the dependencies graph and see what could be broken in terms of missing package ID after merging.
This PR will be in effect after updating C3I jenkins. 
---
=> [docs] Update bump PR review rule

recipes/pulseaudio/all/conanfile.py
To fix the regression in https://github.com/conan-io/conan-center-index/pull/22195#issuecomment-1884818744 caused by the removal of `xvmc`.
This change should avoid the linking against unrelated xorg libraries in the first place in the future.
=> pulseaudio: make xorg requirement more specifc

.c3i/config_v1.yml, .c3i/config_v2.yml
Add entry to list the number of maintainers reviewers required to merge a bump pull request (bump version or bump requirements)
This entry has no effect right now, only will have affect after next C3I Jenkins release (24-jan-2024)
---
=> [config] Add reviews required bump entry in config.yml

recipes/opene57/all/conandata.yml, recipes/opene57/all/conanfile.py, recipes/opene57/config.yml
Specify library name and version:  **opene57/1.6.5**
A new release of opene57 is available (1.6.5), therefore the recipe has been updated.
---
=> Updated Opene57 to 1.6.5

recipes/openvino/all/conanfile.py
Required for OpenCV https://github.com/conan-io/conan-center-index/pull/21204 since it still uses old API in some places
---
=> openvino: added OpenVINO 1.0 API headers for older releases

recipes/libpng/all/conandata.yml, recipes/libpng/config.yml
Specify library name and version:  **libpng/1.6.42**
---
=> libpng: add version 1.6.42

recipes/nuraft/all/conanfile.py
**nuraft/\***
The `homepage` metadata is pointing to an internal github service at eBay. Correct this to the upstream OSS site in github.com
---
=> Fix NuRaft Homepage metadata.

recipes/openssl/3.x.x/conandata.yml, recipes/openssl/config.yml
Specify library name and version:  **openssl/3.2.1**
Just adding v3.2.1 for OpenSSL
---
=> openssl: add 3.2.1

.c3i/config_v1.yml, .c3i/config_v2.yml
Add new entry to manage bump dependencies PR execution. Still not in production. It will be better documented in the changelog, so it can be updated internally until next c3i jenkins release. 
---
=> [config] Add bump deps entry

recipes/libcurl/all/conandata.yml, recipes/libcurl/config.yml
Specify library name and version:  **libcurl/8.6.0**
---
=> libcurl: add version 8.6.0

recipes/eventpp/all/conandata.yml, recipes/eventpp/all/conanfile.py, recipes/eventpp/all/test_package/CMakeLists.txt, recipes/eventpp/all/test_package/conanfile.py, recipes/eventpp/all/test_package/test_package.cpp, recipes/eventpp/all/test_v1_package/CMakeLists.txt, recipes/eventpp/all/test_v1_package/conanfile.py, recipes/eventpp/config.yml
Specify library name and version:  **eventpp/0.1.3**
[Eventpp](https://github.com/wqking/eventpp) is a C++11 header-only library for thread-safe callbacks, event dispatchers, and event queues.
---
=> eventpp: new recipe

recipes/simdutf/all/conandata.yml, recipes/simdutf/all/conanfile.py, recipes/simdutf/config.yml
Specify library name and version:  **simdutf/4.0.9**
The setting for building tests changed in simdutf 3.2.3. There's a lot of tests and building them is slow. Let's spare CCI and end-users of that pain.
Also added 4.0.9
---
=> simdutf: add v4.0.9, stop building tests

recipes/libpq/all/conandata.yml, recipes/libpq/all/patches/15/0001-Use-BIO_-get-set-_app_data-instead-of-BIO_-get-se.patch
fixes #21547
Specify library name and version:  **libpq/15.x*
Since libpq did some trickery in OpenSSL's internals, which broke with OpenSSL 3.2.x, we need to patch it to work correctly. See:
https://github.com/Homebrew/homebrew-core/issues/155651
https://www.postgresql.org/message-id/CXA1532Q80DK.81UOGP3O5AP6%40neon.tech
---
=> libpq: fix with openssl>=3.2.x

recipes/icu/all/conandata.yml
The current URL used in CCI is no longer available, making impossible to build this package from source. Without the suffix `FIXED` we can find the source package with same checksum.
https://github.com/unicode-org/icu/releases/tag/release-74-2
fixes #22632
/cc @lukasz-matysiak
---
=> [ICU] Fix source URL in conandata

recipes/crowcpp-crow/all/conandata.yml, recipes/crowcpp-crow/config.yml
Specify library name and version:  **crowcpp-crow/***
Since 1.1.1 has been deleted, I will add 1.1.0 instead.
https://github.com/conan-io/conan-center-index/pull/22537#issuecomment-1923322498
---
=> crowcpp-crow: remove 1.1.1, add 1.1.0

recipes/cwalk/all/conandata.yml, recipes/cwalk/all/conanfile.py, recipes/cwalk/all/patches/0001-fix-cmake-1.2.8.patch, recipes/cwalk/config.yml
Specify library name and version:  **cwalk/***
- add version 1.2.8
- add patch_type, patch_description
- since 1.2.8, cwalk install a pkgconf file. (which should be removed in cci)
---
=> cwalk: add version 1.2.8

recipes/poco/all/conanfile.py
Specify library name and version: poco/all
Add the transitive_headers=True trait on the expat dependency to reflect that poco headers transitively include expat headers
Fixes https://github.com/conan-io/conan-center-index/issues/22482
---
=> (#22482) poco: add transitive_headers trait on expat dependency

recipes/zlib-ng/all/conanfile.py, recipes/zlib-ng/all/test_package/CMakeLists.txt, recipes/zlib-ng/all/test_package/conanfile.py, recipes/zlib-ng/all/test_v1_package/conanfile.py
Specify library name and version:  **zlib-ng/all**
This change will allow zlib-ng to have same file/target names as zlib.
---
=> zlib-ng: provide better compatibility with zlib

recipes/boost/all/conandata.yml, recipes/boost/all/patches/1.84.0-reimplement-string_set-as-any-string.patch
Specify library name and version:  **boost/1.84.0**
This fixes the compilation on macOS (and other libcxx platforms) with cppstd=20. The commit has already landed upstream: https://github.com/boostorg/locale/commit/c5e8f02c903696a213fc4b710f6740ccd1f07f4e .
---
=> boost: add upstream patch to fix build w/ c++20 on macOS

recipes/coin-utils/all/conanfile.py, recipes/coin-utils/all/test_package/CMakeLists.txt, recipes/coin-utils/all/test_package/conanfile.py, recipes/coin-utils/all/test_v1_package/conanfile.py
BLAS and LAPACK were getting picked up from the system automatically otherwise. This breaks downstream package builds.
Also added a separate test_package test against CMakeDeps. Not that important here, but the `coin-cbc` package is having severe issues with `PkgConfigDeps` (#18864), but not `CMakeDeps`, so I thought it would not hurt to include it for all COIN packages.
=> coin-utils: explicitly disable blas and lapack, add CMakeDeps test

.github/workflows/stale.yml
[stale-pr-message](https://github.com/actions/stale?tab=readme-ov-file#stale-pr-message) and [close-pr-message](https://github.com/actions/stale?tab=readme-ov-file#close-pr-message) require `pull-requests: write`  permissions
current workflow fails with `Error when creating a comment: Resource not accessible by integration` https://github.com/conan-io/conan-center-index/actions/runs/7795682541/job/21259012260#step:2:4504
---
=> stale bot: fix permissions and line endings

.c3i/authorized_users.yml, .c3i/config_v1.yml, .c3i/config_v2.yml, .c3i/waitlist_users.yml, docs/faqs.md
- This configuration is not running yet.
- Some users change name in middle of asking for access request and when asking about the old username, there is no answer about. These outdated and not responded users will be moved to a waiting list where we can ping from to time, but will not have access to PRs until be move to authorized users list.
---
=> [config] Add waitaing list for users in authorized users

recipes/c-blosc2/all/conandata.yml, recipes/c-blosc2/all/conanfile.py
Partially revert of https://github.com/conan-io/conan-center-index/pull/22674
The author warned about reverting back the project name, which affects the package checksum too: https://github.com/Blosc/c-blosc2/issues/583#issuecomment-1931905036
---
=> [c-blosc2] Revert checksum

recipes/tk/all/conanfile.py
Specify library name and version:  **tk/all**
Should be self explanatory. Per documentation, this is typically needed in autotools builds.
---
=> tk: Fix apple shared install name

recipes/influxdb-cxx/all/conandata.yml, recipes/influxdb-cxx/all/conanfile.py, recipes/influxdb-cxx/all/test_package/CMakeLists.txt, recipes/influxdb-cxx/all/test_package/conanfile.py, recipes/influxdb-cxx/all/test_package/test_package.cpp, recipes/influxdb-cxx/config.yml
Specify library name and version:  **influxdb-cxx/0.7.1**
Try to close https://github.com/conan-io/conan-center-index/issues/19125.
---
=> influxdb-cxx: add recipe

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  **imgui/1.90.2, 1.90.2-docking**
---
=> imgui: add version 1.90.2, 1.90.2-docking

recipes/libzippp/all/conandata.yml, recipes/libzippp/config.yml
Specify library name and version:  **libzippp/7.1-1.10.1**
---
=> libzippp: add version 7.1-1.10.1

recipes/b2/portable/conanfile.py
This is a fix for a regression introduced in #21093
Without this cxxflags are set to "None" which causes a compile failure.
Specify library name and version:  **b2/5.0.0**
---
=> b2: Don't apply CXXFLAGS env var if it doesn't exist

recipes/md4qt/all/conandata.yml, recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.7.2**
---
=> md4qt: bump version to 2.7.2

recipes/hiredis/all/conanfile.py
The version 1.1.0 has a patch move `project()` in CMakeLists.txt, which works when using toolchain. However, we didn't have it to 1.2.0, than fails.
This PR uses cache variables to pass all variables via command line, skip toolchain.
fixes #22514
/cc @aligirayhanozbay-abex
/cc @bronekrab
---
=> [hiredis] Use cache variables to make work with Cmake

recipes/jasper/all/conandata.yml, recipes/jasper/all/conanfile.py, recipes/jasper/all/patches/4.2.0-0003-deterministic-libname.patch, recipes/jasper/config.yml
Specify library name and version:  **jasper/***
https://github.com/jasper-software/jasper/releases/tag/version-4.2.0
- add version 4.2.0
- since 4.2.0, jasper has provided "JAS_PACKAGING" cmake option to control rpath configuration
---
=> jasper: add version 4.2.0, update dependencies

recipes/fontconfig/all/conanfile.py, recipes/fontconfig/all/test_package/test_package.c, recipes/fontconfig/meson/conanfile.py
Fontconfig is causing version conflict in the PR #21387 due expat.
I've simplified the test package for the older versions, for some reason on Mac it is segfaulting if we try to do anything remotely complicated (Can't even call FcFini() without it segfaulting). Seems to be fine on newer versions, so I think this is just some bug in the older versions.
---
=> fontconfig: update expat

recipes/opendis6/all/conanfile.py, recipes/opendis6/all/test_package/CMakeLists.txt
Specify library name and version:  **opendis6/0.1.0**
The current minimum cppstd is set to 17, which excludes RHEL 8 GCC 8.x support. It is critical that opendis6 be available for RHEL 8. GCC 8.x natively uses C++14 as the default standard, so I have set the cppstd accordingly for this package.
---
=> opendis6: Set Minimum C++ Standard to 14 for RHEL 8 Support [CRITICAL]

recipes/libgpg-error/all/conanfile.py
Specify library name and version:  **libgpg-error/1.47**
This was causing the crosscompile to fail in most cases. 
The condition is no longer needed because it should work in most cases if the compiler executable is correctly specified in the Conan profile.
Closes https://github.com/conan-io/conan-center-index/issues/22784
=> [libgpg-error] Fix crosscompile errors

recipes/safe/all/conandata.yml, recipes/safe/all/conanfile.py, recipes/safe/all/test_package/CMakeLists.txt, recipes/safe/all/test_package/conanfile.py, recipes/safe/all/test_package/test_package.cpp, recipes/safe/config.yml
Specify library name and version:  **safe/1.1.1**
[Safe ](https://github.com/LouisCharlesC/safe/) is a header-only mutex wrapper.
---
=> safe: new recipe

recipes/isl/all/conandata.yml, recipes/isl/all/conanfile.py, recipes/isl/all/patches/0.24-0001-fix-ac_test_cflags.patch, recipes/isl/all/test_package/CMakeLists.txt, recipes/isl/all/test_package/conanfile.py, recipes/isl/all/test_v1_package/CMakeLists.txt, recipes/isl/all/test_v1_package/conanfile.py, recipes/isl/config.yml
Minor additions to #14916. Notably, enabled `imath` support.
- Resolves #14916.
- Resolves #14915.
=> isl: migrate to Conan v2

recipes/nmos-cpp/all/conanfile.py
Specify library name and version:  **nmos-cpp**
Bump to json-schema-validator/2.3.0 and nlohmann_json/3.11.3 to align with upstream ahead of new release.
=> [nmos-cpp] Bump dependencies to match upstream

recipes/boost/all/conanfile.py
In Conan 1.x is possible to know the C++ standard flag used by the compiler when having the cppstd declared: https://docs.conan.io/1/reference/tools.html#tools-cppstd-flag
However, we don't have that tool ported to Conan 2.x (yet): https://github.com/conan-io/conan/issues/12603
Plus, there is no such B2 toolchain class supported yet, so we need to dig to find the correct flags that will be passed to b2. The B2 project has its own parameter for stdcpp, the `cxxstd`: https://www.boost.org/doc/libs/1_84_0/tools/build/doc/html/index.html#bbv2.builtin.features.cxxstd. So, we need to pass without any prefix.
This PR partially copies the implementation available in https://github.com/conan-io/conan/blob/develop2/conan/tools/build/flags.py to pass the supported C++ standard flag.
fixes #22816
---
=> [boost] Hotfix: Detect cxxstd flag correctly

recipes/botan/all/conandata.yml, recipes/botan/config.yml
Specify library name and version:  **botan/2.19.4**
Botan 2.x is in maintenance mode. This is a patch release with a few improvements that are relevant to security.
See https://github.com/randombit/botan/blob/release-2/news.rst
---
=> botan: add version 2.19.4

recipes/glaze/all/conandata.yml, recipes/glaze/all/conanfile.py, recipes/glaze/config.yml
- glaze/2.1.4 uses `decltype(auto)` which is not supported by gcc < 11.3 due to gcc bug. [ref](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102229)
---
=> glaze: add version 2.1.4

recipes/zlib/all/conandata.yml
zlib 1.3.1
The alternative url for zlib 1.3.1 in conandata was bad!
=> zlib: Bad alternative url for zlib 1.3.1

recipes/dcmtk/all/conandata.yml, recipes/dcmtk/all/patches/3.6.7-0003-ambiguous-overload-operator-equal.patch
closes https://github.com/conan-io/conan-center-index/issues/20332
closes https://github.com/conan-io/conan-center-index/issues/20444
---
=> dcmtk: fix compilation error `ambiguous overload for operator==` with some compilers

recipes/md4qt/all/conandata.yml, recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.7.4**
---
=> md4qt: bump version to 2.7.4

recipes/daw_utf_range/all/conandata.yml, recipes/daw_utf_range/all/conanfile.py, recipes/daw_utf_range/config.yml
Specify library name and version:  **daw_utf_range/2.2.4**
daw_utf_range/2.2.4 requires daw_header_libraries>=2.98.0 because daw_header_libraries has moved several functions to new header files.
---
=> daw_utf_range: add version 2.2.4

recipes/glaze/all/conandata.yml, recipes/glaze/all/conanfile.py, recipes/glaze/config.yml
Specify library name and version:  **glaze/2.1.6,2.1.7**
glaze/2.1.7 has a breaking change, add glaze/2.1.6 for compatibility. (Thanks @pwqbot)
---
=> glaze: add version 2.1.6, 2.1.7

.c3i/config_v1.yml, .c3i/config_v2.yml
The internal CI build Validate Infrastructure is responsible for updating the document https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md.
It reads the config yaml file to decide if it should or not open a PR to update the document. But reading the C3I code, it actually wants to read `create_docs_pull-request`, but not `open_docs_pull-request`. By default the C3I code does not open the PR, so we need to fix the entry in config anyway.
Kudos @Croydon that spotted this misconfiguration! 💚 
---
=> [config] Fix validate infrastructure entry name

recipes/libpng/all/conandata.yml, recipes/libpng/config.yml
Specify library name and version:  **libpng/1.6.43**
---
=> libpng: add version 1.6.43

recipes/sleef/all/CMakeLists.txt, recipes/sleef/all/conandata.yml, recipes/sleef/all/conanfile.py, recipes/sleef/all/test_package/CMakeLists.txt, recipes/sleef/all/test_package/conanfile.py, recipes/sleef/all/test_v1_package/CMakeLists.txt, recipes/sleef/all/test_v1_package/conanfile.py, recipes/sleef/config.yml
=> sleef: migrate to Conan v2

recipes/aws-crt-cpp/all/conandata.yml, recipes/aws-crt-cpp/all/conanfile.py, recipes/aws-crt-cpp/all/patches/0.24.1-disable-sanitizers.patch, recipes/aws-crt-cpp/all/patches/0.24.1-fix-cast-error.patch, recipes/aws-crt-cpp/config.yml
Specify library name and version:  **aws-crt-cpp/0.24.1**
This is a required dependency to package a more recent aws-sdk-cpp (#20612)
aws-crt-cpp version 0.18.8 has a dependency conflict and is used nowhere:
```
ERROR: Version conflict: Conflict between aws-c-io/0.10.20 and aws-c-io/0.13.4 in the graph.
Conflict originates from aws-c-mqtt/0.7.12
```
---
=> aws-crt-cpp: add version 0.24.1

recipes/poco/all/conanfile.py
Specify library name and version:  **poco/all**
Add the transitive_headers=True trait on the expat dependency to reflect that poco headers transitively include expat headers
Specifically the zlib.h header is exposed in [DeflatingStream.h](https://github.com/pocoproject/poco/blob/devel/Foundation/include/Poco/DeflatingStream.h) and [InflatingStream.h](https://github.com/pocoproject/poco/blob/devel/Foundation/include/Poco/InflatingStream.h)
Fixes #22806
---
=> poco: add transitive_headers on zlib dependency

recipes/sdbus-cpp/all/conandata.yml, recipes/sdbus-cpp/all/conanfile.py, recipes/sdbus-cpp/all/test_pkgconf/conanfile.py, recipes/sdbus-cpp/all/test_v1_pkgconf/conanfile.py, recipes/sdbus-cpp/config.yml
Specify library name and version:  **sdbus-cpp/1.4.0**
Bump dependencies:
* libsystemd
* pkgconf
* expat
---
=> sdbus-cpp/1.4.0: Bump version and dependencies

recipes/velodyne_decoder/all/conandata.yml, recipes/velodyne_decoder/all/conanfile.py, recipes/velodyne_decoder/all/patches/3.0.0-001-fix-msvc-flags.patch, recipes/velodyne_decoder/all/test_package/CMakeLists.txt, recipes/velodyne_decoder/all/test_package/conanfile.py, recipes/velodyne_decoder/all/test_package/test_package.cpp, recipes/velodyne_decoder/config.yml
Adds `velodyne_decoder`: https://github.com/valgur/velodyne_decoder
A decoder library for raw Velodyne data and telemetry info.
I'm the author of the library as well this time.
=> velodyne_decoder: add new recipe

recipes/libglvnd/all/conanfile.py
Meson needs to be a newer version to support Python 3.12.
Specify library name and version:  **libglvnd/***
---
=> libglvnd: Bump build requirements to support Python 3.12

recipes/asio-grpc/all/conanfile.py
Specify library name and version:  **asio-grpc/***
`libunifex/cci.20220430` is not maintained since https://github.com/conan-io/conan-center-index/commit/de3f951acc4aad1b4bf0b62fe6ca977ee472efce
other deps can be safely bumped because there are no dependents on asio-grpc in CCI : https://github.com/search?q=repo%3Aconan-io%2Fconan-center-index+asio-grpc+language%3APython&type=code&l=Python
---
=> asio-grpc: use maintained version of libunifex

recipes/openimageio/all/patches/2.4.17.0-cmake-targets.patch, recipes/openimageio/all/patches/2.4.7.1-cmake-targets.patch, recipes/openimageio/all/patches/2.5.6.0-cmake-targets.patch
Specify library name and version:  **openimageio/2.x.x.x**
While I had recently ported OpenImageIO to Conan 2, I missed that one external dependency I locally normally build with is failing with the patching required to the packages CMake files.
This fixes the build option `'openimageio/*:with_libjpeg=libjpeg-turbo'` (which for the graph also needs `'libtiff/*:jpeg=libjpeg-turbo'` to use the same jpeg library for all dependencies).
---
=> OpenImageIO: Fix CMake patch for non-default option

recipes/qt/5.x.x/conanfile.py, recipes/qt/6.x.x/conanfile.py
=> qt: Bump expat to 2.6.0 to avoid conflicts in xkbcommon and wayland

recipes/cuda-api-wrappers/all/conandata.yml, recipes/cuda-api-wrappers/config.yml
Specify library name and version:  **cuda-api-wrappers/0.6.8**
Adding the latest version, plus - a few months ago, a not-really-beta of 0.7.0 was added, and could not be easily removed. Now, I've added an actual-beta of 0.7.0 for the brave souls who do want to actually try that.
---
=> Updated cuda-api-wrappers with versions 0.6.8 and 0.7.0-b2

recipes/tcl/all/conanfile.py
Specify library name and version:  **tcl/all**
Alternative to https://github.com/conan-io/conan-center-index/pull/22711.
TCL has some extra libraries that it uses just for extensions. I believe these should not be included in the package info, as there is no point in linking against them. They also were not properly fixed by `fix_apple_shared_install_name`, which was causing issues in #21387. This PR fixes this by just removing those extra libraries from the package info altogether.
---
=> tcl: Don't include extensions in package info libs

recipes/wyhash/all/conandata.yml, recipes/wyhash/config.yml
Specify library name and version:  **wyhash/final4**
wyhash is no longer under development.
final4 is the last released version.
---
=> wyhash: add version final4

recipes/minizip/all/conandata.yml, recipes/minizip/config.yml
Specify library name and version:  **minizip/1.3.1**
Minizip 1.3.1 can be created as Zlib as released a 1.3.1 version (with vulnerabilities fix in Minizip)
---
=> Bump minizip to 1.3.1

recipes/gperf/all/conanfile.py
Specify library name and version:  **gperf/3.1**
The original error on FreeBSD 14.0 was:
```console
gperf/3.1: RUN: make -j1
cd lib; make all
cc -m64 -O3 -DNDEBUG -I. -c ./getopt.c
cc -m64 -O3 -DNDEBUG -I. -c ./getopt1.c
c++ -stdlib=libc++ -std=gnu++17 -m64 -O3 -DNDEBUG -I. -c ./getline.cc
c++ -stdlib=libc++ -std=gnu++17 -m64 -O3 -DNDEBUG -I. -c ./hash.cc
rm -f libgp.a
ar rc libgp.a getopt.o getopt1.o getline.o hash.o
ranlib libgp.a
cd src; make all
cd: src: No such file or directory
*** [all] Error code 2
```
The error occurs here:
```make
all : force
cd lib; $(MAKE) all
cd src; $(MAKE) all
cd tests; $(MAKE) all
cd doc; $(MAKE) all
```
in the following directory
```console
$ ls -1ap
./
../
aclocal.m4
AUTHORS
build-aux/
ChangeLog
config.log
config.status
configure
configure.ac
COPYING …
```
=> gperf/all: Fix build on FreeBSD

recipes/expat/all/conandata.yml, recipes/expat/config.yml
Specify library name and version:  **expat/2.6.1**
https://github.com/libexpat/libexpat/compare/R_2_6_0...R_2_6_1
---
=> expat: add version 2.6.1

recipes/nng/all/conandata.yml, recipes/nng/all/conanfile.py, recipes/nng/config.yml
Specify library name and version:  **nng/1.7.3**
- add version 1.7.3
- add `with_ipv6` option for 1.7.3 and later
https://github.com/nanomsg/nng/compare/v1.7.2...v1.7.3
---
=> nng: add version 1.7.3

recipes/qt/6.x.x/conanfile.py
Specify library name and version:  **qt/6.x**
Check if global environment variable `CONAN_CENTER_BUILD_SERVICE` is defined. This negates the need for consumers to have to define `NOT_ON_C3I`.
=> Qt6 check if we are on C3I CI

.c3i/config_v1.yml
The Conan v2 migration linter was created to help us when we started to migrate +1000 recipes, and it was really useful. However, right now we have only few recipes missing to be migrated, most with an open PR.
Related to #22286
---
=> [config] Remove Conan v2 migration check as mandatory

linter/transform_conanfile.py
it is basically like a build_requires:
https://github.com/conan-io/conan/blob/1.63.0/conans/client/graph/graph_manager.py#L321
related to https://github.com/conan-io/conan-center-index/actions/runs/8140241751/job/22245056002?pr=22286#step:8:19
---
=> linter: handle test_requires

recipes/libmount/all/conanfile.py
Adding the eudev package, #20335, requires `libblkid` only. Adding a separate libblkid recipe, PR #20373, hasn't gotten anywhere yet. This PR uses an alternative approach and separates the libraries. Each library is split into its own component.
---
=> libmount: Make the libblkid and libmount libraries separate components

recipes/xz_utils/all/conandata.yml, recipes/xz_utils/cmake/conandata.yml, recipes/xz_utils/cmake/conanfile.py, recipes/xz_utils/cmake/test_package/CMakeLists.txt, recipes/xz_utils/cmake/test_package/conanfile.py, recipes/xz_utils/cmake/test_package/test_package.c, recipes/xz_utils/cmake/test_v1_package/CMakeLists.txt, recipes/xz_utils/cmake/test_v1_package/conanfile.py, recipes/xz_utils/config.yml
Specify library name and version:  **xz_utils/5.6.0**
It seems the project has started hosting their releases on github primarily rather than their website. The old links seem to still exist for backwards compatibility, but I can't find any reference to them on the site, and doesn't exist for this new version.
5.6.0 also removed the visual studio projects, and has moved fully to CMake for Windows. CMake hasn't fully replaced Autotools for them yet, but hopefully it should be good enough for us to use.
---
=> xz_utils: Add 5.6.0 as a new subdir

recipes/md4qt/all/conandata.yml, recipes/md4qt/config.yml
Specify library name and version:  **md4qt/2.8.0**
---
=> md4qt: bump version to 2.8.0

recipes/libxml2/all/conandata.yml, recipes/libxml2/config.yml
Specify library name and version:  **libxml2/2.12.5**
New versions contain fix for CVE-2024-25062
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.7
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.5
---
=> libxml2: add 2.12.5 and 2.11.7

recipes/perfetto/all/conandata.yml, recipes/perfetto/config.yml
Specify library name and version:  **perfetto/43.1**
```
https://android.googlesource.com/platform/external/perfetto/+/refs/tags/v43.1
https://github.com/google/perfetto/tree/v43.1
v43.1 - 2024-03-05:
* Cherry-pick of https://r.android.com/2988674, which fixes the android x86
standalone build.
v43.0 - 2024-03-05:
* Buffers marked as `transfer_on_clone` will be flushed independently when
cloning.
* ftrace: added drain_buffer_percent option to read kernel ring buffer
based on occupancy in addition to existing periodic reads. Requires Linux
kernel v6.1+.
* ftrace: changed default kernel per-cpu ring buffer sizes if a config
doesn't request an explicit size via buffer_size_kb. Added
buffer_size_lower_bound option that lets the service …
```
=> perfetto: add version 43.1

recipes/freetype/all/conanfile.py
freetype: all versions
Use a version range for libpng in requirements. This avoids version conflicts when libpng is consumed transitively, since most of the repo is still in `1.6.40` rather than `1.6.42`.
It's a rather artificial conflict when it happens - `libpng` is backwards compatible at the API level, and Conan 2 defaults (the `minor` version component is encoded in the consumers) will ensure binary compatibility of produced binaries (e.g. `libpng/1.6.x` may not necessarily be binary compatible with `libpng/1.5.x`, but .patch versions of the same minor will be). `libpng` changes the library filename and soname when jumping to new minors. The default documented behaviour https://docs.conan.io/2.0/reference/conanfile/attributes.html#package-id-embed-non-embed-unknown-mode should ensure …
=> freetype: use libpng version range

recipes/xkbcommon/all/conanfile.py
Bump wayland-protocols to version 1.33, which incorporates feature updates: https://www.phoronix.com/news/Wayland-Protocols-1.33
---
=> xkbcommon: Bump wayland-protocols and Meson

docs/adding_packages/dependencies.md
After consideration, we'll allow libpng to the range list
As for the libxml dependency, we're also open to it being added, but still need to do some more research
=> Update range list to add libpng (And mention libxml)

recipes/tensorflow-lite/all/conanfile.py
Work in progress pending tests.
Solve dependency conflicts caused by https://github.com/conan-io/conan-center-index/pull/21762/files.
Need to ensure all tests pass - as it's hard to reason whether tensorflow-lite is still compatible with these newer versions.
Before this PR:
* `conan graph info --requires=tensorflow-lite/2.12.0 --requires=opencv/4.5.5 --profile:host Linux-gcc11-x86_64-Release --profile:build Linux-gcc11-x86_64-Release` fails
After this PR: the command above should pass without conflicts.
=> tensorflow-lite: resolve conflicts

recipes/cn-cbor/all/conandata.yml, recipes/cn-cbor/all/conanfile.py, recipes/cn-cbor/all/test_package/conanfile.py, recipes/cn-cbor/config.yml
Required by the latest version of `cose-c`.
=> cn-cbor: remove invalid check_min_cppstd

recipes/opengl/all/conanfile.py
Using install_substitutes in zypper because in opensuse tumbleweed `glproto-devel` is not available but `xorgproto-devel` provides the same.
I think this should close: https://github.com/conan-io/conan-center-index/issues/18912
And also close: https://github.com/conan-io/conan/issues/15335
=> Add install_substitutes for zypper with "xorgproto-devel"

.github/workflows/stale.yml
the stale label is already removed automatically by the action. `labels-to-remove-when-unstale` is used to remove additional labels.
https://github.com/actions/stale?tab=readme-ov-file#labels-to-remove-when-unstale
https://github.com/conan-io/conan-center-index/actions/runs/8044709241/job/21968729920#step:2:25205
https://github.com/conan-io/conan-center-index/actions/runs/8044709241/job/21968729920#step:2:25208
---
=> stale workflow: don't remove stale label twice

recipes/pcl/all/conanfile.py
This is done the same way as for the FreeGLUT package in #22428. Requires #22956.
Fixes #22944.
=> pcl: Use the mesa-glu Conan package

recipes/xbyak/all/conandata.yml, recipes/xbyak/config.yml
Specify library name and version:  **xbyak/7.06**
https://github.com/herumi/xbyak/compare/v7.05...v7.06
---
=> xbyak: add version 7.06

recipes/pulseaudio/config.yml, recipes/pulseaudio/meson/conandata.yml, recipes/pulseaudio/meson/conanfile.py, recipes/pulseaudio/meson/test_package/CMakeLists.txt, recipes/pulseaudio/meson/test_package/conanfile.py, recipes/pulseaudio/meson/test_package/test_package.c
Specify library name and version:  **pulseaudio/17.0.0**
---
=> pulseaudio 17.0

recipes/libtiff/all/conanfile.py
See also https://spdx.org/licenses/libtiff.html.
Specify library name and version:  **libtiff/4.5.1**
---
=> libtiff: Update license to libtiff

recipes/genie/all/conanfile.py
Specify library name and version:  **genie/all**
Previously, the build system would not respect `tools.build:compiler_executables`. On my system, I don't have a "g++" command, just a handful of profiles that specifically call "g(cc/++)-\<version\>" using that.
This also simplifies a decent amount of logic.
Now it should behave similar to other make-based packages:
1. Use `tools.build:compiler_executables` if defined
2. Use CC if defined
3. Fallback to cc/cxx
---
=> genie: fix compiler paths

recipes/orc/all/conandata.yml, recipes/orc/config.yml
Specify library name and version:  **orc/2.0.0**
Apache ORC 2.0.0 is released: https://orc.apache.org/news/2024/03/08/ORC-2.0.0/
---
=> add orc/2.0.0

recipes/xkbcommon/all/conanfile.py
Installing attempts to install the bash completions in a system directory.
```
Installing /var/home/jordan/.conan2/p/b/xkbco18970aa15216b/b/src/tools/xkbcli-bash-completion.sh to /usr/share/bash-completion/completions
Installation failed due to insufficient permissions.
Attempt to use /usr/bin/sudo to gain elevated privileges? [y/n]
Traceback (most recent call last):
File "/var/home/jordan/.conan2/p/mesond0eabfb2fb735/p/bin/mesonbuild/mesonmain.py", line 194, in run
return options.run_func(options)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/home/jordan/.conan2/p/mesond0eabfb2fb735/p/bin/mesonbuild/minstall.py", line 873, in run
installer.do_install(datafilename)
File "/var/home/jordan/.conan2/p/mesond0eabfb2fb735/p/bin/mesonbuild/minstall.py", line 557, in do_install
self.install_data(d, dm, …
```
=> xkbcommon: Disable installing bash completions

recipes/opentelemetry-cpp/all/conandata.yml, recipes/opentelemetry-cpp/all/conanfile.py, recipes/opentelemetry-cpp/config.yml
- Fixes #22985
Dropped v1.7.0 for maintainability as it handles that library differently altogether.
=> opentelemetry-cpp: fix an invalid optional library, drop v1.7.0

recipes/avahi/all/conanfile.py
To cross-compile Avahi, the `--with-distro` flag must be passed.
Disable introspection.
This must be disabled to cross-compile.
Strangely enough, it doesn't work when enabled when doing a native build.
It only seems to work when set to auto.
When gobject-introspection is updated to support Conan V2 an option could be added to control enabling or disabling introspection.
=> avahi/0.8: Support cross-compilation

recipes/tree-sitter/all/conandata.yml, recipes/tree-sitter/config.yml
Specify library name and version:  **tree-sitter/0.22.1**
https://github.com/tree-sitter/tree-sitter/compare/v0.21.0...v0.22.1
---
=> tree-sitter: add version 0.22.1

recipes/uwebsockets/all/conandata.yml, recipes/uwebsockets/config.yml
Specify library name and version:  **uwebsockets/20.62.0**
https://github.com/uNetworking/uWebSockets/compare/v20.60.0...v20.62.0
---
=> uwebsockets: add version 20.62.0

recipes/openssl/3.x.x/conanfile.py
Specify library name and version:  **openssl/3.x**
The PR #21708 added the new option `tls_security_level` which is capable to configure a OpenSSL property. It's configured according to current versions available for 3.x, but OpenSSL moves fast it can be changed in the future, resulting in a misconfiguration in a solitary bump version PR.
Thanks to @jcar87 for pointing it, this PR keeps the current option, but instead, uses the default value from OpenSSL when not configured to an explicit value.
---
=> [openssl] Set tls security level to automatic for OpenSSL 3.x

recipes/xtr/all/conandata.yml, recipes/xtr/all/conanfile.py, recipes/xtr/all/test_package/CMakeLists.txt, recipes/xtr/all/test_package/conanfile.py, recipes/xtr/all/test_v1_package/CMakeLists.txt, recipes/xtr/all/test_v1_package/conanfile.py, recipes/xtr/config.yml
=> xtr: migrate to Conan v2

docs/changelog.md
The PR #20335 has been affected by a missing configuration in C3I Jenkins, not only a missing package in Conan Center. This new release fixes the case: When a package has `shared-library` as package type, the Conan 2.x build will generate both `*/*:shared=True` and `*/*:shared=False`
The second fix is an internal change to accommodate internal scripts with new Jenkins versions. It should not affect ConanCenterIndex directly, only tooling. 
---
=> [docs] Changelog March 13th, 2024

recipes/libudev/all/conanfile.py
The pkg-config file contains the version of the Conan package. This is problematic because it is `system` which causes version checks for libudev to fail. This happens in Weston I'm making for instance:
```
Dependency libudev found: NO found system but need: '>= 136'
Found CMake: /usr/local/bin/cmake (3.28.20240202)
Run-time dependency libudev found: NO (tried cmake)
../src/libweston/meson.build:196:2: ERROR: Dependency lookup for libudev with method 'pkgconfig' failed: Invalid version, need 'libudev' ['>= 136'] found 'system'.
```
I've set the version in the pkg-config file to that of the version on the system. This fixes version checks in consumers using pkg-config.
=> libudev: Set the pkg-config version to the real version number

recipes/expat/all/conandata.yml, recipes/expat/config.yml
Specify library name and version:  **expat/2.6.2**
2.6.2 contains fix for CVE-2024-28757
https://github.com/libexpat/libexpat/blob/R_2_6_2/expat/Changes
I've also decided to remove older "patch" versions that aren't currently used by any recipes in CCI's master.
Through simple text search I've found only 2.4.1, 2.4.8, 2.5.0 and 2.6.0.
---
=> expat: add 2.6.2 and remove several old versions

recipes/flatbuffers/all/conandata.yml, recipes/flatbuffers/config.yml
Specify library name and version:  **flatbuffers/24.3.7**
https://github.com/google/flatbuffers/compare/v23.5.26...v24.3.7
---
=> flatbuffers: add version 24.3.7

recipes/libvips/all/conandata.yml, recipes/libvips/config.yml
Specify library name and version:  **libvips/8.15.2**
Adding libvips/8.15.2 which contains several bugfixes, including one for https://github.com/conan-io/conan/issues/15578#issuecomment-1952784238 .
---
=> libvips: add v8.15.2

recipes/cgal/all/conandata.yml, recipes/cgal/all/conanfile.py, recipes/cgal/config.yml
Specify library name and version:  **cgal/5.6.1**
New upstream version (bug-fix): CGAL 5.6.1
---
=> [cgal] add cgal/5.6.1

recipes/unity/all/conandata.yml, recipes/unity/config.yml
Specify library name and version:  **unity/2.6.0**
https://github.com/ThrowTheSwitch/Unity/compare/v2.5.2...v2.6.0
---
=> unity: add version 2.6.0

recipes/quill/all/conandata.yml, recipes/quill/config.yml
Specify library name and version:  **quill/3.7.0**
https://github.com/odygrd/quill/compare/v3.6.0...v3.7.0
---
=> quilll: add version 3.7.0

recipes/fltk/all/conanfile.py
Specify library name and version:  **fltk/all**
---
=> fltk: use libpng version range

recipes/pulseaudio/meson/conanfile.py
PulseAudio 17.0 requires `m4`, even though it's using Meson as the build system. The AutoTools build system for previous versions most likely brought in `m4` transitively, which is why it wasn't explicitly required.
Attached are logs for both before and after this change.
[pulseaudio-17-missing-m4-log.txt](https://github.com/conan-io/conan-center-index/files/14620932/pulseaudio-17-missing-m4-log.txt)
[pulseaudio-17-with-m4-log.txt](https://github.com/conan-io/conan-center-index/files/14620947/pulseaudio-17-with-m4-log.txt)
=> pulseaudio/17.0: Add missing tool requirement for m4

recipes/butteraugli/all/conanfile.py
Specify library name and version:  **butteraugli/all**
---
=> butteraugli: use libpng version range

recipes/exiv2/all/conanfile.py
Specify library name and version:  **exiv2/all**
---
=> exiv2: use version range for libpng

recipes/pdf-writer/all/conanfile.py
Specify library name and version:  **pdf-writer/all**
---
=> pdf-writer: use libpng version range

recipes/fast_float/all/conandata.yml, recipes/fast_float/config.yml
Specify library name and version:  **fast_float/6.1.1**
https://github.com/fastfloat/fast_float/compare/v6.1.0...v6.1.1
---
=> fast_float: add version 6.1.1

recipes/fast-cdr/all/conandata.yml, recipes/fast-cdr/config.yml
fast-cdr/2.2.0
Bump version to 2.2.0 and remove extraneous legacy versions.
---
=> fast-cdr: Add version 2.2.0

docs/changelog.md
A new deployment arrives with the beginning of the spring (north hemisphere).
- When opening PR related to change regular version to version range, it will be classified as bump dependencies PR too. In past the rule was the opposite and very strict because the CI bot was merging PRs automatically without reviews.
- When a recipe uses package type `static-library`, it will be built with both `*/*:shared=True/False`. This behavior will avoid missing package when using these packages as dependency.
---
=> [changelog] Deployment March 20, 2023

recipes/tsl-robin-map/all/conandata.yml, recipes/tsl-robin-map/config.yml
Specify library name and version:  **tsl-robin-map/1.2.2**
---
=> tsl-robin-map: add version 1.2.2

recipes/openjdk/all/conanfile.py
Specify library name and version:  **openjdk/***
The current recipe sets JAVA_HOME using `*env_info.append`, but this results in a leading space, which breaks things that are really picky about it. For example, Gradle fails with the following error:
```
ERROR: JAVA_HOME is set to an invalid directory:  /home/aramallo/.conan2/p/b/openje4780c153b838/p /home/aramallo/.conan2/p/b/openje4780c153b838/p
```
It also gets added twice for some reason, but this fixes it regardless.
---
=> openjdk fix JAVA_HOME environment variable

recipes/metis/all/conanfile.py
The library defaults the width of the index and real types to 32 bits rather than 64, as is set by default in the recipe. The library even drops this option in the latest release for CMake: https://github.com/KarypisLab/METIS/commit/81d70ba3d799c0143e38085b4cdd4e891e39b49a
This default value also causes a conflict in the GTSAM recipe: https://github.com/conan-io/conan-center-index/pull/22323#discussion_r1533637368
=> metis: fix incorrect default value for with_64bit_types

recipes/minicoro/all/conandata.yml, recipes/minicoro/all/conanfile.py, recipes/minicoro/all/test_package/CMakeLists.txt, recipes/minicoro/all/test_package/conanfile.py, recipes/minicoro/all/test_package/test_package.c, recipes/minicoro/config.yml
I was checking BehaviorTree.CPP project, if could use third party libraries vendorized in the project as external dependencies.
The https://github.com/edubart/minicoro is listed there, and occurred me that small coroutine header-only project is not available in Conan Center yet.
It actually can use a back-end like ucontext or Windows fibers, via compiler definitions, but it's something that the customer should know about actually. 
---
=> [minicoro] Add new package: minicoro/0.1.3

recipes/wildcards/all/conandata.yml, recipes/wildcards/all/conanfile.py, recipes/wildcards/all/test_package/CMakeLists.txt, recipes/wildcards/all/test_package/conanfile.py, recipes/wildcards/all/test_package/test_package.cpp, recipes/wildcards/config.yml
Very similar context described on #23197. BehaviorTree.CPP uses wildcards as well.
The project generates the header with the version, based on CMake config file, so we need to run cmake configure at least. Another option would be using rename + replace_in_file, but is too much I guess.
https://github.com/zemasoft/wildcards
---
=> [wildcards] Add new package: wilcards 1.4.0

recipes/libunwind/all/conanfile.py
Fixes a conflicting dependency in #20528.
=> libunwind: Bump xz_utils to avoid a dependency conflict in cpython

recipes/minicoro/all/conanfile.py
Specify library name and version:  **minicoro/0.1.3**
The minicoro only exports its headers to "include" folder directly, no namespace folder included, which could result in name collision.
The BehaviorTree.CPP has a vendorized version of this library and uses a namespace folder. 
https://github.com/BehaviorTree/BehaviorTree.CPP/tree/master/3rdparty/minicoro
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/55a7b70b7ab6c1f2be811009e67f6e6630839947/src/action_node.cpp#L15
The current implementation there does not work with the current package in Conan Center.
---
=> [minicoro] Add include folder as namespace

recipes/wildcards/all/conanfile.py
Specify library name and version:  **wildcards/1.4.0**
Very similar to #23209
Here, BehaviorTree.cpp uses on these places:
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/55a7b70b7ab6c1f2be811009e67f6e6630839947/src/bt_factory.cpp#L18
https://github.com/BehaviorTree/BehaviorTree.CPP/tree/master/3rdparty/wildcards
This PR exposes the headers files in a namespace folder too. 
---
=> [wildcards] Add include folder as namespace

recipes/libinput/all/conandata.yml, recipes/libinput/all/conanfile.py, recipes/libinput/all/test_package/conanfile.py, recipes/libinput/all/test_package/meson.build, recipes/libinput/all/test_package/test_package.c, recipes/libinput/config.yml
Specify library name and version:  **libinput/1.25.0**
[libinput](https://www.freedesktop.org/wiki/Software/libinput/) is a library that handles input devices for display servers and other applications that need to directly deal with input devices.
libinput is required to enable the libinput backend in wlroots.
The following PRs are required first:
Optionally, a libwacom package could be added to enable libwacom support.
---
=> libinput: Add recipe

recipes/dbus/1.x.x/conanfile.py
The expat dependency must be bumped to not conflict with wayland. Additionally, glib/2.78.1 and glib/2.78.3 are used much more than glib/2.77.0. I went with glib/2.78.3 since it is newer and also required in the Qt packages. Bump build dependencies as well.
Blocks #22387.
---
=> dbus: Bump expat and glib dependencies to minimize conflicts

recipes/liblzf/all/CMakeLists.txt, recipes/liblzf/all/conanfile.py, recipes/liblzf/all/liblzf.def
Can use a `.def` file instead since the library has an extremely simple API.
=> liblzf: avoid WINDOWS_EXPORT_ALL_SYMBOLS

recipes/openssl/1.x.x/conanfile.py, recipes/openssl/3.x.x/conanfile.py
Specify library name and version:  **openssl/***
Removes the "d" suffix which is only ever introduced in conan, without there being any need in a conan environment as different builds are always in different directories.
---
=> fix(openssl): remove renaming of debug files within the recipe

docs/faqs.md
After talking to Conan team about a non official boost library, having no intention to be integrated to official boost, and finding that even cmake targets and headers are using the name boost, it would be better allow these specific cases to use the project name, including the boost prefix as package name. Otherwise, it would require more changes, like the cmake target and cmake name.
In case the project changes, and want to be part to boost, then, it should be marked as `deprecated` as soon as becomes official in Boost. 
Related to https://github.com/conan-io/conan-center-index/pull/21303
---
=> [docs] Allow boost namespace for non official projects

recipes/fixed-containers/all/conanfile.py, recipes/fixed-containers/all/test_package/CMakeLists.txt, recipes/fixed-containers/all/test_package/test_package.cpp
Specify library name and version:  **fixed-containers/***
fixed_containers requires magic_enum < 0.9.4.
https://github.com/toge/fixed-containers/blob/e78c79176b2d7c9d55aceccaa62ba8aa8ecabdf7/include/fixed_containers/enum_utils.hpp#L5
fix wrong cmake_file_name and cmake_target_name.
https://github.com/teslamotors/fixed-containers?tab=readme-ov-file#cmake
---
=> fixed-containers: fix cmake names, require magic_enum

recipes/dacap-clip/all/conandata.yml, recipes/dacap-clip/all/conanfile.py, recipes/dacap-clip/config.yml
Specify library name and version:  **dacap-clip/***
- add version 1.8
- dacap-clip/1.8 introduces CLIP_ENABLE_IMAGE option
- update libpng
https://github.com/dacap/clip/compare/v1.7...v1.8
---
=> dacap-clip: add version 1.8

recipes/pcl/all/conanfile.py
Add use_sse option to pcl recipe to be able to disable in case of cross-compilation as for arm64.
Specify library name and version:  **pcl/1.13.1**
See https://github.com/PointCloudLibrary/pcl/issues/5843#issuecomment-1761154905
---
=> Add use_sse option to pcl recipe

recipes/boost/all/conanfile.py
**boost/1.83.0**
`math_tr1l` and `math_c99l` don't compile on power, but the conanfile is still verifying that the components exist..
Fixes #22448.
---
=> boost: fix for ppc compile

recipes/alembic/all/conanfile.py
Specify library name and version:  **alembic/1.8.7**
---
=> Alembic: bump imath to 3.1.10 - Avoid conflict with Openvdb 11.0.0

recipes/rabbitmq-c/all/conandata.yml, recipes/rabbitmq-c/all/conanfile.py, recipes/rabbitmq-c/config.yml
Specify library name and version:  **rabbitmq-c/0.14.0**
https://github.com/alanxz/rabbitmq-c/compare/v0.13.0...v0.14.0
---
=> rabbitmq-c: add version 0.14.0

recipes/avahi/all/conanfile.py
Specify library name and version:  **avahi/0.8**
Should fix
```
ERROR: Version conflict: Conflict between expat/2.6.0 and expat/2.5.0 in the graph.
Conflict originates from dbus/1.15.8
```
=> [avahi] Bump expat and glib

recipes/opencv/4.x/conanfile.py
Revert default value of `with_quirc` option.
It has been changed by https://github.com/conan-io/conan-center-index/pull/22136, specifically by these commits: https://github.com/conan-io/conan-center-index/pull/22136/commits/a9001e4c48de8ad7ad69619e54355b06e36d7f1f & https://github.com/conan-io/conan-center-index/pull/22136/commits/b3c5e4e70bff83d0753da656e529a513e65ab92a, but I don't see any reason for these modifications.
See also https://github.com/conan-io/conan-center-index/pull/22136#discussion_r1537354793 & https://github.com/conan-io/conan-center-index/pull/22136#discussion_r1537362051
/cc @RubenRBS 
---
=> opencv 4.x: re-enable quirc by default

recipes/libva/all/conanfile.py
Cross-compilation is currently broken for the libva package for Conan V1. It doesn't properly make the wayland package available in the build context through pkg-config. This is necessary for the project to find the wayland-scanner program. I've updated libva to use the same procedure as xkbcommon to incorporate Wayland's pkg-config in the build context.
[libva-cross-broken-log.txt](https://github.com/conan-io/conan-center-index/files/14696027/libva-cross-broken-log.txt)
[libva-cross-fixed-log.txt](https://github.com/conan-io/conan-center-index/files/14696026/libva-cross-fixed-log.txt)
=> libva/2.20.0: Fix discovery of wayland-scanner

recipes/libunwind/all/conanfile.py
In https://github.com/conan-io/conan-center-index/pull/23312 the recipe revision was already uploaded to conan center repo at https://github.com/conan-io/conan-center-index/pull/23204, so the recipe revision was not uploaded as the latest one. This still causes some issues in dependencies that require this library regarding https://github.com/conan-io/conan-center-index/issues/23310
This PR introduces some formatting to the recipe with just the purpose of generating a new recipe revision that is uploaded as latest to solve the situation.
=> [libunwind] Fix: Generate new recipe revision to upload it as the latest

recipes/libnghttp2/all/conandata.yml, recipes/libnghttp2/all/conanfile.py, recipes/libnghttp2/config.yml
Specify library name and version:  **libnghttp2/***
https://github.com/nghttp2/nghttp2/compare/v1.59.0...v1.60.0
---
=> libnghttp2: add version 1.60.0, disable tests and examples build

recipes/libdrm/all/conanfile.py
linux-headers-generic is linux only
Specify library name and version:  **libdrm/***
---
=> libdrm: fix freebsd

recipes/rapidcsv/all/conandata.yml, recipes/rapidcsv/config.yml
Specify library name and version:  **rapidcsv/8.82**
https://github.com/d99kris/rapidcsv/compare/v8.80...v8.82
---
=> rapidcsv: add version 8.82

recipes/rtmidi/all/conandata.yml
Specify library name and version:  **rtmidi/5.0**, **rtmidi/6.0**
The SSL cerificate on the server is broken - missing cerificate chain - and won't validate correctly via conan download, wget etc.
(Firefox contains the R3 Let's encrypt certificate so it validates correctly.)
---
=> RtMidi: Replace https URLs with http ones to prevent cerificate errors

recipes/libvips/all/conandata.yml
This PR fixes url of 8.15.2 tarball.
Indeed, when I try to build from source, I get this error:
```
ERROR: libvips/8.15.2: Error in source() method, line 233
get(self, **self.conan_data["sources"][self.version], strip_root=True)
NotFoundException: Not found: https://github.com/libvips/libvips/releases/download/v8.15.2a/vips-8.15.2.tar.xz
```
Url provided by https://github.com/conan-io/conan-center-index/pull/23107 is weird. I guess it was correct when it has been submitted, but it's not anymore.
---
=> libvips 8.15.2: fix url of tarball

recipes/imath/all/conandata.yml, recipes/imath/config.yml
https://github.com/AcademySoftwareFoundation/Imath/compare/v3.1.10...v3.1.11
It's virtually identical to v3.1.10 on CCI due to the bugfix in this relase being backported here.
=> imath: add v3.1.11, drop old versions

recipes/libinput/all/conanfile.py
This aligns with how wayland-protocols is handled in every other package. I missed this in my original PR to add the `libinput` package.
=> libinput: Make wayland-protocols a build dependency

recipes/mbedtls/all/conandata.yml, recipes/mbedtls/all/conanfile.py, recipes/mbedtls/config.yml
Specify library name and version:  **mbedtls/3.6.0**
https://github.com/Mbed-TLS/mbedtls/compare/v3.5.2...v3.6.0
The source code structure has been changed since 3.6.0, and the `framework` is now referenced by submodules.
For this reason, a download tarball is now provided.
---
=> mbedtls: add version 3.6.0

recipes/commata/all/conandata.yml, recipes/commata/config.yml
Specify library name and version:  **commata/0.2.9**
https://github.com/furfurylic/commata/compare/v0.2.8...v0.2.9
--
=> commata: add version 0.2.9

recipes/octo-logger-cpp/all/conandata.yml, recipes/octo-logger-cpp/all/conanfile.py, recipes/octo-logger-cpp/config.yml
Specify library name and version:  **octo-logger-cpp/***
https://github.com/ofiriluz/octo-logger-cpp/compare/v1.5.0...v1.6.1
<details>
<summary>
build log with `with_aws=True`
</summary>
WARN: Name containing special chars is discouraged 'octo-logger-cpp'
octo-logger-cpp/1.6.0: Exporting package recipe: /Users/toge/src/conan-center-index/recipes/octo-logger-cpp/all/conanfile.py
octo-logger-cpp/1.6.0: exports: File 'conandata.yml' found. Exporting it...
octo-logger-cpp/1.6.0: Copied 1 '.py' file: conanfile.py
octo-logger-cpp/1.6.0: Copied 1 '.yml' file: conandata.yml
octo-logger-cpp/1.6.0: Exported to cache folder: /Users/toge/.conan2/p/octo-6018dd638a395/e
octo-logger-cpp/1.6.0: Exported: …
=> octo-logger-cpp: add version 1.6.1

recipes/libssh/all/conandata.yml, recipes/libssh/all/conanfile.py, recipes/libssh/all/patches/0.10.6-0001-fix-cmake.patch, recipes/libssh/all/test_package/CMakeLists.txt, recipes/libssh/all/test_package/conanfile.py, recipes/libssh/all/test_package/test_package.c, recipes/libssh/config.yml
Related: #13449
Related: #16899
Fixes: #16747
Specify library name and version:  **libssh/0.10.6**
Changed replace_in_file from previous PR with apply_conandata_patches
Added `tc.cache_variables["CMAKE_TRY_COMPILE_CONFIGURATION"]` to support Visual Studio / Ninja Multi-Config generators
---
=> libssh: add recipe

recipes/sbepp/all/conanfile.py
Specify library name and version:  **sbepp/1.2.0**
This commit extends the list of supported gcc compilers up to g++ v8.1
Following is a link to the ticket:  https://github.com/conan-io/conan-center-index/issues/23205
---
=> + [sbepp] Added support of gcc8.1 to sbeppc

recipes/duckdb/all/conanfile.py
Specify library name and version:  **duckdb/0.10.1**
The recipe did not build on ARM Linux.
Here is an analog change in the setup.py provided by duckdb:
https://github.com/duckdb/duckdb/commit/4a89d97db8a5a23a15f3025c8d2d2885337c2637
---
=> fix: duckdb 0.10.1 jemalloc no longer built for non ARM Linux

recipes/vincentlaucsb-csv-parser/all/conandata.yml, recipes/vincentlaucsb-csv-parser/config.yml
Specify library name and version:  **vincentlaucsb-csv-parser/2.2.0**
https://github.com/vincentlaucsb/csv-parser/compare/2.1.1...2.2.0
---
=> vincentlaucsb-csv-parser: add version 2.2.0

recipes/alembic/all/conanfile.py
Specify library name and version:  **alembic/all**
Pushes back a patch version to get in line with the rest of the imath requirements for now - evetually we'll bump them at once :)
=> alembic: Downgrade imath dependency to 3.1.9 to avoid conflitcs

recipes/openvdb/all/conanfile.py
Specify library name and version:  **openvdb/1.0**
Pushes back a patch version to get in line with the rest of the imath requirements for now - evetually we'll bump them at once :)
=> openvdb: Downgrade imath dependency to 3.1.9 to avoid conflitcs

recipes/libnghttp2/all/conandata.yml, recipes/libnghttp2/config.yml
Specify library name and version:  **libnghttp2/1.61.0**
https://github.com/nghttp2/nghttp2/compare/v1.60.0...v1.61.0
---
=> libnghttp2: add version 1.61.0

recipes/commata/all/conandata.yml, recipes/commata/all/patches/0.2.9-0001-include-set.patch
Specify library name and version:  **commata/0.2.9**
There is a compilation error in commata/0.2.9 on gcc 13.
---
=> commata: include <set> in 0.2.9

recipes/openssl/3.x.x/conanfile.py
Specify library name and version:  **openssl/3.2.1**
Fix the handling of tc.defines into the config_template for openssl. Currently, it is generating a single string that is space-separated, but the toolchain is expecting a comma-separated list of strings.
Fixes #22661
---
=> (#22661) openssl: fix handling of tc.defines in config_template

recipes/cista/all/conandata.yml, recipes/cista/config.yml
Specify library name and version:  **cista/0.15**
---
=> cista: add version 0.15

recipes/mbedtls/all/conanfile.py
Specify library name and version:  **mbedtls/3.6.0**
Related to PR https://github.com/conan-io/conan-center-index/pull/23366
The threading support could be activated via `config.py`, but it would require an extra step invoking python, only to patch that header file that will not be exported to the package folder.
As alternative, we can define it directly to the preprocessor.
About MBedTLS threading feature: https://mbed-tls.readthedocs.io/en/latest/kb/development/thread-safety-and-multi-threading
How to customize the config.h in MBedTLS: https://mbed-tls.readthedocs.io/en/latest/kb/compiling-and-building/how-do-i-configure-mbedtls
Tested the new configuration on Mac only:
```
conan create all --version=3.6.0 -o "&:enable_threading=True" -o "&:shared=True" …
```
=> [mbedtls] Add threading support as option

recipes/macdylibbundler/all/conandata.yml, recipes/macdylibbundler/all/conanfile.py, recipes/macdylibbundler/all/test_package/conanfile.py, recipes/macdylibbundler/config.yml
Specify application name and version:  **macdylibbundler/1.0.5**
Helper tool for bundling macOS applications with dynamic libraries. I want to use it as a build_requirement as I before had it installed via brew but want it as a proper package now. Thought I'll share it with the community.
---
=> macdylibbundler: Add build tool for macOS

recipes/cpr/all/conanfile.py
* Add self.requires("openssl...") call when using openssl on windows
Specify library name and version:  **cpr/1.10.5**
This makes it possible to build cpr on windows with openssl. See issue #23251 for more discussion.
---
=> cpr: Fix build with openssl on Windows and Android (#23251, #23327) 

.github/workflows/alert-community.yml
Add community alert for mocknetworkaccessmanager and qtawesome
---
=> Add community alert for mocknetworkaccessmanager and qtawesome

recipes/dbus/1.x.x/conanfile.py
I dropped (deprecated) the `with_glib` option altogether since it's only used within tests and nowhere else. I guess this might have been intended to enable [`dbus-glib`](https://gitlab.freedesktop.org/dbus/dbus-glib), which has been deprecated and moved to a separate repo a long while ago.
Set the X11 dependency to `visible=False`. As noted by the recipe comment, this is not ideal but it's the best that is currently possible with the tools provided by Conan. 
I also made the licensing details a bit more accurate, since the mix of licenses covering the project is actually quite complex:
https://gitlab.freedesktop.org/dbus/dbus/-/blob/master/COPYING
https://gitlab.freedesktop.org/dbus/dbus/-/tree/master/LICENSES
Also bumped `libselinux` to avoid a conflict with `libsystemd` and removed …
=> dbus: don't propagate X11 libs, drop `with_glib`, update license info

recipes/openimageio/all/conandata.yml, recipes/openimageio/all/patches/2.5.10.1-cmake-targets.patch, recipes/openimageio/config.yml
Specify library name and version:  **openimageio/2.5.10.1**
Add the newest version of OpenImageIO. Contains - as always with OIIO a larger patch, but it has only two lines changed compared to the previous patch for version 2.5.9.0, which are lines 175 and 176 in the patch file.
---
=> OpenImageIO: Add version 2.5.10.1

recipes/libssh/all/conandata.yml, recipes/libssh/all/conanfile.py, recipes/libssh/all/patches/0.10.6-0002-fix-cmake.patch, recipes/libssh/all/patches/0.10.6-0003-fix-mbedtls-private-struct.patch, recipes/libssh/all/test_package/test_package.c
Specify library name and version:  **libssh/0.10.6**
Fix build with `-o crypto_backend=gcrypt`
Add option to build with `-o crypto_backend=mbedtls`
Expand test_package so it won't silently fail
MbedTLS build will exit with the following error in the test_package step:
```
Error in auto_init()
ERROR: libssh/0.10.6 (test package): Error in test() method, line 26
self.run(bin_path, env="conanrun")
ConanException: Error -11 while executing
```
Found in the [README.mbedtls](https://git.libssh.org/projects/libssh.git/tree/README.mbedtls?h=libssh-0.10.6) that "mbedTLS has to be built with threading support enabled", but don't see an option in the mbedtls conan recipe to enable threading to test if this is the cause of the failure
---
=> libssh: fix compatibility for mbedtls and gcrypt

recipes/qtxlsxwriter/all/conanfile.py
Specify library name and version:  **qtxlswriter/***
qt/5.15.7 is not maintained any more in CCI
---
=> qtxlswriter: bump qt

recipes/rapidfuzz/all/conandata.yml, recipes/rapidfuzz/config.yml
Specify library name and version:  **rapidfuzz/3.0.4**
https://github.com/rapidfuzz/rapidfuzz-cpp/compare/v3.0.2...v3.0.4
---
=> rapidfuzz: add version 3.0.4

recipes/iconfontcppheaders/all/conandata.yml, recipes/iconfontcppheaders/config.yml
IconFontCppHeaders cci.20240128
Bump package to includes latest font updates.
---
Hooks not activated since not supported on conan 2.x.
=> iconfontcppheaders: bump version to cci.20240128

recipes/commata/all/conandata.yml, recipes/commata/all/patches/0.2.9-0002-additional-missing-includes.patch
Specify library name and version:  **commata/0.2.9**
Upstream added a few more includes after https://github.com/furfurylic/commata/pull/3
cc @toge
=> commata: Add more missing headers

recipes/binutils/all/conanfile.py, recipes/lcms/all/profile_msvc
Specify library name and version:  **binutils**
The binutils recipe had 2 ``conf_info`` entries that are "options", not basic Python types, and this is broken, it crashes for example when using ``--format=json``. Furthermore, those are not used at all in all ConanCenter, so their existence seems not necessary. The values of those options can be read by consumers via ``self.dependencies["dep"].options``.
Close https://github.com/conan-io/conan/issues/16018
---
=> Remove binutils unused ``conf_info`` entries

recipes/opentelemetry-proto/all/conandata.yml, recipes/opentelemetry-proto/config.yml
Specify library name and version:  **opentelemetry-proto/1.2.0**
https://github.com/open-telemetry/opentelemetry-proto/compare/v1.1.0...v1.2.0
---
=> opentelemetry-proto: add version 1.2.0

recipes/botan/all/conandata.yml, recipes/botan/config.yml
Specify library name and version:  **botan/3.4.0**
This adds support for X448/Ed448. Otherwise, it is mostly a patch release without a lot of new functionality.
Details: https://github.com/randombit/botan/blob/master/news.rst
---
=> botan: add version 3.4.0

recipes/basu/all/conandata.yml, recipes/basu/all/conanfile.py, recipes/basu/all/patches/0001-memfd-util.c-Use-F_ADD_SEALS-definition-from-missing.patch, recipes/basu/all/test_package/conanfile.py, recipes/basu/all/test_package/meson.build, recipes/basu/all/test_package/test_package.c, recipes/basu/config.yml
Specify library name and version:  **basu/0.2.1**
basu is the sd-bus library, extracted from systemd.
Some projects rely on the sd-bus library for DBus support. However not all systems have systemd or elogind installed. This library provides just sd-bus (and the busctl utility).
---
=> add basu/0.2.1

recipes/cyclonedds-cxx/all/conanfile.py, recipes/cyclonedds-cxx/all/test_package/CMakeLists.txt
Specify library name and version:  **cyclonedds-cxx/all**
Resolves https://github.com/conan-io/conan-center-index/issues/22768
---
=> cyclonedds-cxx: add requires to component info

recipes/dice-template-library/all/conandata.yml, recipes/dice-template-library/config.yml
Specify library name and version:  **dice-template-library/1.5.0**
https://github.com/dice-group/dice-template-library/compare/v1.3.0...v1.5.0
---
=> dice-template-library: add version 1.5.0

recipes/imguizmo/all/conanfile.py
For compatibility with `implot` (#23434) and `iridescence` (#23436).
There are no other CCI packages dependening on `imguizmo`.
=> imguizmo: add compatibility with latest imgui versions

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  **imgui/1.90.5, 1.90.5-docking**
https://github.com/ocornut/imgui/compare/v1.90.4...v1.90.5
---
=> imgui: add version 1.90.5

recipes/dbus/1.x.x/conanfile.py
Use relative folders due to this change: https://github.com/conan-io/conan/pull/15706. Remove the useless attempt to modify the separators used for the prefix path. The separators are still inconsistent for the prefix and exec_prefix on Windows. They use both backslashes and forward slashes.
=> dbus: Use relative folders for directories

recipes/freeglut/all/conanfile.py, recipes/freeglut/all/test_package/conanfile.py, recipes/freeglut/all/test_package_module/conanfile.py
This option only enables building Wayland utility programs in xkbcommon, not the library. I added this previously, so I'm fixing my mistake.
Also, remove `opengl/system` requirement from the test package.
=> freeglut: Don't require xkbcommon's with_wayland option

recipes/opentelemetry-cpp/all/conandata.yml, recipes/opentelemetry-cpp/all/conanfile.py, recipes/opentelemetry-cpp/config.yml
Specify library name and version:  **opentelemetry-cpp/1.14.2**
I've also added a check for the logs option, since it's been out of preview since `1.11` and added a missing link to `opentelemetry_otlp_recordable` and fixed the missing `opentelemtry-proto` dependency when running with `-o with_otlp_grpc=False`.
---
=> Upgrade opentelemetry-cpp to 1.14.2

recipes/mcap/all/conandata.yml, recipes/mcap/config.yml
Specify library name and version:  **mcap/1.4.0**
(Also clean up the formatting of these yaml files for consistency.)
---
=> mcap: add version 1.4.0

recipes/imguizmo/all/conanfile.py
A quick follow-up to #23435 after #23486 adding imgui/1.90.5 was merged.
=> imguizmo: bump imgui

recipes/cpython/all/conandata.yml
there was an typo in https://github.com/conan-io/conan-center-index/pull/22599
Specify library name and version:  **cpython/3.11.9**
---
=> cpython 3.11.9: re-apply patches

docs/package_templates/autotools_package/all/conanfile.py
code from template doesn't pass the linter:
```
[C3001(unnecessary-lambda-assignment), OpenldapConan.generate.<lambda>] Lambda expression assigned to a variable. Define a function using the "def" keyword instead.
```
---
=> fix template conan doesn't pass the linter

recipes/sdbus-cpp/all/conanfile.py
fix use of vulnerable version of expat, versions<2.6.2 have known vulnerabilites: https://github.com/conan-io/conan-center-index/issues/23277
---
=> sdbus-cpp: security, bump expat

recipes/wayland/all/conanfile.py
Specify library name and version:  **wayland/all**
fix use of vulnerable version of expat, versions<2.6.2 have known vulnerabilites: https://github.com/conan-io/conan-center-index/issues/23277
fix use of vulnerable version of libxml, versions<2.12.5 have known vulnerabilites: https://github.com/conan-io/conan-center-index/issues/23277
---
=> wayland: security, bump deps

recipes/libcurl/all/conanfile.py
libcurl/*
Update c-ares to the latest version which doesn't have security vulnerabilities.
---
=> libcurl: update to c-ares/1.27.0

recipes/nsync/all/conandata.yml, recipes/nsync/all/patches/0001-1.27.0-darwin-exclude_semaphore_mutex_c_from_nsync_cpp_lib.patch, recipes/nsync/config.yml
Specify library name and version:  **nsync/1.27.0**
---
=> nsync: add version 1.27.0

recipes/hictk/all/conandata.yml, recipes/hictk/all/conanfile.py, recipes/hictk/all/test_package/test_package.cpp, recipes/hictk/config.yml
Specify library name and version:  **hictk/all**
hictk v0.0.11 turned out to be broken due to some targets not being installed properly.
Updating the test_package to include one of hictk's main header files highlights this issue (as in the test package no longer compiles).
I think the best way forward is to entirely drop v0.0.11. Should this not be acceptable, then I can use #ifdef guards to include the old test_package code when version == 0.0.11. 
---
=> hictk: add v0.0.12 and drop v0.0.11

recipes/wayland/all/conanfile.py
`Version conflict: wayland/1.22.0->libxml2/2.12.5, xkbcommon/1.5.0->libxml2/2.12.6.` https://github.com/ericLemanissier/proof-of-conan/actions/runs/8733193394/job/23961456446#step:7:179
---
=> wayland: fix conflict with xkbcommon

recipes/aaf/all/conanfile.py
Specify library name and version:  **aaf/all**
---
=> aaf: use expat version range

recipes/exiv2/all/conanfile.py
Specify library name and version:  **exiv2/all**
expat<2.6.2 has known security issues. We can now use version range: c.f. #23277
---
=> exiv2: use expat version range

recipes/jsbsim/all/conanfile.py
Specify library name and version:  **jsbsim/all**
---
=> jsbsim: use expat version range

recipes/apr-util/all/conanfile.py
Specify library name and version:  **apr-util/all**
---
=> apr-util: use expat version range

recipes/libmetalink/all/conanfile.py
Specify library name and version:  **libmetalink/all**
expat<2.6.2 & libxml2<2.12.5 have known security issues. We can now use version range: c.f. https://github.com/conan-io/conan-center-index/issues/23277
---
=> libmetalink: use version range for expat & libxml2

recipes/xlsxio/all/conanfile.py
Specify library name and version:  **xlsxio/all**
---
=> xlsxio: use version range for expat

recipes/libarchive/all/conanfile.py
Specify library name and version:  **libarchive/all**
We can now use version range for libxml2, this should reduce conflicts.
---
=> libarchive: use version range for libxml2

recipes/hwloc/all/conanfile.py
Specify library name and version:  **hwloc/all**
We can now use version range for libxml2, this should reduce conflicts.
---
=> hwloc: use version range for libxml2

recipes/norm/all/conanfile.py
Specify library name and version:  **norm/all**
We can now use version range for libxml2, this should reduce conflicts.
---
=> norm: use version range for libxml2

recipes/xkbcommon/all/conanfile.py
since https://github.com/conan-io/conan-center-index/commit/3264e15a2117e10f4d286d033876d4bc800e47ff#diff-5c99ca1cb44d19a32c9f1373d8effc9125f8e1b094489ef02ee1cf755feb82f7R53
---
=> xkbcommon: fix conflict with wayland

recipes/ipaddress/all/conandata.yml, recipes/ipaddress/all/conanfile.py, recipes/ipaddress/all/test_package/CMakeLists.txt, recipes/ipaddress/all/test_package/conanfile.py, recipes/ipaddress/all/test_package/test_package.cpp, recipes/ipaddress/config.yml
Specify library name and version:  **ipaddress/1.0.1**
Hi! This is a new library for working with IP addresses and networks.
It is inspired by the well-thought-out API from the Python module for working with addresses and networks. Therefore, it is familiar and understandable for use by many programmers.
This library fills gaps in the implementation of other libraries: network parsing, working with stringize **scope id**, as well as network manipulation
---
=> ipaddress: add recipe

recipes/openjdk/all/conanfile.py
This PR should fix: https://github.com/conan-io/conan-center-index/issues/18564
The issue is that the zip from openjdk contains a file that is decompressed with read only values, and as we have the `no_copy_source = True` the zip is always decompressed in exactly the same location so the second time that you decompress with a subsetting that is different, for example `os.version` the decompressing fails. Removing the subsetting from the package ID and also removing `no_copy_source = True` I think should fix the issue. If you force the build it will be decompressed in a different location than the previous build and when the package ends being the same package ID than the other the older package ID will be removed leaving only one folder.
=> Remove `os.version` from package ID and also removing `no_copy_source = True` in openjdk recipe

recipes/gtest/all/conanfile.py
**gtest/1.14.0**
This PR fixes an issue on Linux where pthreads would be linked anyway as a system library even if the option `gtest_disable_pthreads` was set to `True`. Also mentioned in #19113.
---
=> gtest: don't link pthreads if disabled

recipes/google-cloud-cpp/2.x/conanfile.py, recipes/google-cloud-cpp/2.x/test_package/conanfile.py
Specify library name and version:  **google-cloud-cpp/2.x**
Fixes #23266.  I am copying (without understanding) how `grpc` uses `protobuf`. More specifically, I am copying the changes from #19972.
---
=> [google-cloud-cpp] fix grpc_cpp_plugin on macOS, shared

recipes/openfx/all/conanfile.py
Specify library name and version:  **openfx/all**
xpat<2.6.2 has known security issues. We can now use version range: c.f. https://github.com/conan-io/conan-center-index/issues/23277
---
=> openfx: use version range for expat

recipes/readosm/all/conanfile.py
Specify library name and version:  **readosm/all**
---
=> readosm: use version range for expat

recipes/libstudxml/1.1.x/conanfile.py
Specify library name and version:  **libstudxml/1.1.x**
---
=> libstudxml: use version range for expat

recipes/iowow/all/conandata.yml, recipes/iowow/all/patches/1.4.18-0002-fix-uint64_t-format.patch, recipes/iowow/config.yml
Specify library name and version:  **iowow/1.4.18**
https://github.com/Softmotions/iowow/compare/v1.4.17...v1.4.18
---
=> iowow: add version 1.4.18

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.38.11**
https://github.com/ETLCPP/etl/compare/20.38.10...20.38.11
---
=> etl: add version 20.38.11

recipes/iguana/all/conandata.yml, recipes/iguana/config.yml
Specify library name and version:  **iguana/1.0.4**
https://github.com/qicosmos/iguana/compare/v1.0.3...1.0.4
---
=> iguana: add version 1.0.4

recipes/tmx/all/conandata.yml, recipes/tmx/all/conanfile.py, recipes/tmx/all/patches/0001-missing-stdlib-include.patch, recipes/tmx/config.yml
Specify library name and version:  **tmx/all**
add version 1.10.0
libxml2<2.12.5 has known security issues. We can now use version range: c.f. https://github.com/conan-io/conan-center-index/issues/23277
---
=> tmx: add version 1.10.0, use version range for libxml2

recipes/octo-logger-cpp/all/conandata.yml, recipes/octo-logger-cpp/config.yml
Specify library name and version:  **octo-logger-cpp/1.9.0**
https://github.com/ofiriluz/octo-logger-cpp/compare/v1.6.1...v1.9.0
---
=> octo-logger-cpp: add version 1.9.0

recipes/implot/all/CMakeLists.txt, recipes/implot/all/conanfile.py
Also adds support for v1.89.7+ for v0.14 by renaming a single imgui constant in a .cpp file.
`IMGUI_DEFINE_MATH_OPERATORS` no longer needs to be set in CMake. Dropped it to get rid of a related warning.
The imgui version bump is for compatibility with `imguizmo` (#23435) and `iridescence` (#23436). There are no other packages depending on `implot`.
=> implot: bump imgui for consistency with other packages

recipes/tsl-robin-map/all/conandata.yml, recipes/tsl-robin-map/all/conanfile.py, recipes/tsl-robin-map/config.yml
Specify library name and version:  **tsl-robin-map/1.3.0**
https://github.com/Tessil/robin-map/compare/v1.2.2...v1.3.0
---
=> tsl-robin-map: add version 1.3.0

recipes/boost/all/conanfile.py
Specify library name and version:  **boost/any**
For Conan v1 I use the following custom recipes that wrap system libraries on Apple platforms:
- bzip2: https://github.com/kambala-decapitator/conan-system-libs/blob/main/bzip2/conanfile.py
- zlib: https://github.com/kambala-decapitator/conan-system-libs/blob/main/zlib/conanfile.py
But when I try to build Boost against those, it fails due to attempt to access first element of an empty array. This patch prevents that.
Tested by building Boost as shared library and my project and then running my project successfully.
---
=> boost: ignore dependency if it doesn't provide a library [v1]

recipes/libftp/all/conanfile.py, recipes/libftp/all/test_package/test_package.cpp
Specify library name and version:  **libftp/0.5.0**
Hi!
#23687 has added libftp v0.5.0 (thanks, @toge).
As FTPS support has been added in this version, I would like to suggest the
following improvements to the recipe:
1. Update the description.
2. Update the topics.
3. Update the test package:
- ~~Test that libftp provides OpenSSL routines.~~
- Avoid network operations.
What do you think?
---
=> libftp: recipe improvements

recipes/jsoncons/all/conandata.yml, recipes/jsoncons/config.yml
Specify library name and version:  **jsoncons/0.174.0**
https://github.com/danielaparker/jsoncons/compare/v0.173.4...v0.174.0
---
=> jsoncons: add version 0.174.0

docs/adding_packages/dependencies.md
Document bounds for libxml2 and expat
/cc @mayeut who's been pushing for this lately, thanks!
=> Add expat and libxml2 to list of allowed version ranges

recipes/openldap/all/conanfile.py
Specify library name and version:  **openldap/2.6.7**
The OpenLDAP can be built in Mac, the Brew has a formula for it: https://formulae.brew.sh/formula/openldap
Some extra references:
- http://pig.made-it.com/ldap-mac.html
- https://www.openldap.org/software/release/install.html
Closes: #16555
Fix: Added workaround to cross-build in Linux and macOS (https://bugs.openldap.org/show_bug.cgi?id=9228)
---
=> [openldap] Enable Macos build

recipes/cpr/all/conanfile.py
Specify library name and version:  **cpr/1.10.5**
Fixes Issue #23699
---
=> cpr: lower minimum GCC version requirement

recipes/isl/all/conanfile.py
Recent versions cross-compile on macOS without issues.
=> isl: package supports macOS cross-building

recipes/libkml/all/conandata.yml, recipes/libkml/all/conanfile.py
This library uses features of C++ that are removed in C++17, and is currently failing building with MSVC with C++17 or higher.
in this PR: add fallback to compile with C++14 when anything higher than 14 is requested.
the `compatibility.py` extension in Conan 2 will fallback to the binary with C++14 on the consumer side.
In addition to the configurations tested by CI, this was locally tested on Windows with msvc with C++17.
=> libkml: fall back to C++14

recipes/fftw/all/conanfile.py
Specify library name and version:  **fftw**
This recipe is abusing the ``build_folder``, overwriting it. According to the docs: https://docs.conan.io/2/reference/conanfile.html
> Public attributes and methods, like build(), self.package_folder, are reserved for Conan. Don’t use public members for custom fields or methods in the recipes.
The changes proposed seems to both simplify the recipe and avoid this issue. 
This was originated in https://github.com/conan-io/conan/issues/16166, as recent changes in ``develop2`` makes the ``-DCMAKE_TOOLCHAIN_PATH`` defined in Presets at generation time relative between build-folder and generators-folder, but if ``build_folder`` is changed under the hood, things do not longer match.
Close https://github.com/conan-io/conan/issues/16166
=> fix abuse of Conan attributes in fftw

recipes/libgettext/all/conanfile.py
libgettext: skip check during the configure phase during a Debug build with msvc, as it displays a GUI prompt during an assert failure that halts the build
Rationale: The `n` printf format directive is disabled by default in msvc due to security concerns, https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170 - so this check can be skipped altogether if it is known to be a compile-time constant (it's always "no", so we can hardcode it as such).
Close https://github.com/conan-io/conan-center-index/issues/23698
Close https://github.com/conan-io/conan-center-index/pull/23805 
Tested locally with msvc193, `-s build_type=Debug`.
=> libgettext: fix debug build on Windows

recipes/gettext/all/conanfile.py
gettext: skip check during the configure phase during a Debug build with msvc, as it displays a GUI prompt during an assert failure that halts the build
Rationale: The `n` printf format directive is disabled by default in msvc due to security concerns, https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170 - so this check can be skipped altogether if it is known to be a compile-time constant (it's always "no", so we can hardcode it as such).
Close https://github.com/conan-io/conan-center-index/issues/23789
Tested locally with msvc193, `-s build_type=Debug`.
=> gettext: fix msvc debug builds

recipes/zeus_expected/all/conandata.yml, recipes/zeus_expected/all/conanfile.py, recipes/zeus_expected/config.yml
**zeus_expected/1.1.1**
The upstream has merged the patch from version 1.1.0 and released a new version.
Updated version and something cleanup.
---
=> zeus_expected: add version 1.1.1

recipes/opentelemetry-proto/all/conandata.yml, recipes/opentelemetry-proto/config.yml
Specify library name and version:  **opentelemetry-proto/1.3.0**
https://github.com/open-telemetry/opentelemetry-proto/compare/v1.2.0...v1.3.0
---
=> opentelemetry-proto: add version 1.3.0

recipes/tree-sitter/all/conandata.yml, recipes/tree-sitter/config.yml
Specify library name and version:  **tree-sitter/0.22.5**
https://github.com/tree-sitter/tree-sitter/compare/v0.22.1...v0.22.5
---
=> tree-sitter: add version 0.22.5

recipes/openh264/all/conandata.yml, recipes/openh264/all/patches/2.4.1-0001-platform-android.mk.patch, recipes/openh264/config.yml
Specify library name and version:  **openh264/2.4.1**
https://github.com/cisco/openh264/compare/v2.3.1...v2.4.1
---
=> openh264: add version 2.4.1

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/2.6.0**
https://github.com/stephenberry/glaze/compare/v2.5.5...v2.6.0
---
=> glaze: add version 2.6.0

recipes/imguizmo/all/conandata.yml, recipes/imguizmo/all/conanfile.py, recipes/imguizmo/config.yml
Required for the latest version of Iridescence in #23436.
It has been almost three years from the latest released version and there's no indication about when the next version might be released.
=> imguizmo: add cci.20231114 snapshot version

recipes/c4core/all/conandata.yml, recipes/c4core/all/patches/0.2.0-0001-make-fast_float-external.patch
Specify library name and version:  **c4core/0.2.0**
I'm very sorry for my mistake.
The url of c4core/0.2.0 is wrong.
This PR will fix it.
---
=> c4core: fix url for version 0.2.0

recipes/botan/all/conanfile.py
Minor addition to an error message. Was mildly frustrating being told that my compiler (gcc 11.0) didn't support C++20 and having to dig into the conanfile to work out exactly what the issue was.
=> make minimum compiler version explicit in error message

recipes/gcc/all/conanfile.py
Specify library name and version:  **gcc/***
also fix conflicts:
- `mpc/1.2.0->gmp/6.3.0, gcc/12.2.0->gmp/6.2.1.`
- `mpc/1.2.0->mpfr/4.2.0, gcc/12.2.0->mpfr/4.1.0.`
---
=> gcc: don't use unmaintained binutils

recipes/android-ndk/all/conandata.yml, recipes/android-ndk/config.yml
Specify library name and version:  **android-ndk/r26d**
---
=> android-ndk: add r26d

recipes/behaviortree.cpp/all/conandata.yml, recipes/behaviortree.cpp/config.yml
Specify library name and version:  **behaviortree.cpp/4.6.0**
https://github.com/BehaviorTree/BehaviorTree.CPP/compare/4.5.2...4.6.0
---
=> behaviortree.cpp: add version 4.6.0

recipes/sqlcipher/all/conandata.yml, recipes/sqlcipher/all/patches/Makefile.in-v4.5.7.patch, recipes/sqlcipher/all/patches/Makefile.msc-v4.5.7.patch, recipes/sqlcipher/all/patches/fix_configure-v4.5.7.patch, recipes/sqlcipher/config.yml
Specify library name and version:  **sqlcipher/4.5.7**
https://github.com/sqlcipher/sqlcipher/compare/v4.5.6...v4.5.7
---
=> sqlcipher: add version 4.5.7

recipes/pango/all/conanfile.py
Specify library name and version:  **pango/[>=1.50.12]**
As reported in https://github.com/conan-io/conan-center-index/issues/23876, Pango was missing a system dependency to dwrite that has been there from version 1.50.12 onwards
Thanks @fnadeau for reporting it :) This should fix your issues - could you please provide a successful log compilation with this change? (Let me know if you need some help getting this recipe into your Conan cache!) 
Requires https://github.com/conan-io/conan-center-index/pull/23506
=> pango: Add missing system lib for pango >=1.50.12 in Windows

recipes/jsoncons/all/conandata.yml, recipes/jsoncons/config.yml
Specify library name and version:  **jsoncons/0.175.0**
https://github.com/danielaparker/jsoncons/compare/v0.174.0...v0.175.0
---
=> jsoncons: add version 0.175.0

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.106.0**
https://github.com/beached/header_libraries/compare/v2.101.0...v2.106.0
---
=> daw_header_libraries: add version 2.106.0

recipes/catch2/3.x.x/conandata.yml, recipes/catch2/config.yml
Specify library name and version:  **catch2/3.6.0**
https://github.com/catchorg/Catch2/compare/v3.5.4...v3.6.0
---
=> catch2: add version 3.6.0

recipes/tinycolormap/all/conandata.yml, recipes/tinycolormap/all/conanfile.py, recipes/tinycolormap/all/test_package/CMakeLists.txt, recipes/tinycolormap/all/test_package/conanfile.py, recipes/tinycolormap/all/test_package/test_package.cpp, recipes/tinycolormap/config.yml
Adds tinycolormap: https://github.com/yuki-koyama/tinycolormap
A header-only, single-file library for colormaps written in C++11
=> tinycolormap: new recipe

recipes/tixi3/all/conandata.yml, recipes/tixi3/all/conanfile.py, recipes/tixi3/all/patches/0001-missing-stdlib-include.patch
Specify library name and version:  **tixi3/all**
libxml2<2.12.5 has known security issues. We can now use version range: c.f. https://github.com/conan-io/conan-center-index/issues/23277
---
=> tixi3: use version range for libxml2

recipes/eudev/all/conanfile.py
Fixes conflicts with libxml2 in the graph caused by older version of libxslt.
=> eudev: Bump libxslt to avoid conflicts

recipes/wasmtime/all/conandata.yml, recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/***
https://github.com/bytecodealliance/wasmtime/compare/v19.0.2...v20.0.1
---
=> wasmtime: add version 20.0.1, remove older versions

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/2.6.1**
https://github.com/stephenberry/glaze/compare/v2.6.0...v2.6.1
---
=> glaze: add version 2.6.1

recipes/catch2/3.x.x/conanfile.py
Specify library name and version:  **catch2/3.5.3**
Follow up to the PR https://github.com/conan-io/conan-center-index/pull/21792. The feature compatibility_cppstd is an attribute, using older Conan versions will not break, only will not have the feature available.
This keeps the behaviour of Catch2 inline with GTest which also faced a similar issue: https://github.com/conan-io/conan-center-index/pull/23909
@uilianries, @RubenRBS 
---
=> [catch2] Keep recipe compatible with older Conan versions

recipes/gtest/all/conanfile.py
Specify library name and version:  **gtest/1.14.0**
Follow up to the PR #23856. The feature `compatibility_cppstd` is an attribute, using older Conan versions will not break, only will not have the feature available. 
/cc @Twon @hhowe29
---
=> [gtest] Keep recipe compatible with older Conan versions

recipes/boost/all/conanfile.py
Affects boost 1.85.0 only.
Please, read #23877 and https://github.com/boostorg/stacktrace/issues/163 to understand the context.
This PR does not disable the feature, but enforce the define to ignore errors.
An alternative, would be add a new option like `without_stacktrace_from_exception` and disable it when running on Mac M1/2, for instance. 
fixes #23877
/cc @randomphrase
---
=> [boost] Add default support for from_exception in non intel platforms

recipes/libcurl/all/conanfile.py
Use version range for c-ares in libcurl recipe
* c-ares is a c-library with a stable API/ABI that has been backwards compatible for years: https://abi-laboratory.pro/index.php?view=timeline&l=c-ares (note: last updated in 2020)
* curl aims to be compatible with 1.16.0 onwards, as per: https://github.com/curl/curl/blob/1ea7dce08d7dda985b0ddb153c7cf84c710a01ba/docs/INTERNALS.md?plain=1#L31
* however, here it appears the build-time checks check for API available since 1.6.0: https://github.com/curl/curl/blob/1ea7dce08d7dda985b0ddb153c7cf84c710a01ba/m4/curl-confopts.m4#L531-L547
Use a version range since c-ares is API and ABI compatible, use `1.27` as the lower bound as that is the one currently in use
=> libcurl: use version range for c-ares

recipes/wiringpi/all/CMakeLists.txt, recipes/wiringpi/all/conandata.yml, recipes/wiringpi/all/conanfile.py, recipes/wiringpi/all/test_package/CMakeLists.txt, recipes/wiringpi/config.yml
Specify library name and version:  **wiringpi/3.4**
https://github.com/WiringPi/WiringPi/compare/3.2...3.4
---
=> wiringpi: add version 3.4, fix homepage url

recipes/fast-dds/all/conandata.yml, recipes/fast-dds/all/conanfile.py, recipes/fast-dds/config.yml
fast-dds/2.14.0
Adds the latest long-term support version (2.14.0) of fast-dds.
---
=> fast-dds: add version 2.14.0

recipes/uriparser/all/conandata.yml, recipes/uriparser/all/conanfile.py, recipes/uriparser/config.yml
Specify library name and version:  **uriparser/0.9.8**
https://github.com/uriparser/uriparser/compare/uriparser-0.9.7...uriparser-0.9.8
The new CMake option `URIPARSER_SHARED_LIBS` is added since 0.9.8.
But it's default value refers `BUILD_SHARED_LIBS` values.
So I think it is not needed to set `URIPARSER_SHARED_LIBS`.
```cmake
if(DEFINED BUILD_SHARED_LIBS)
set(_URIPARSER_SHARED_LIBS_DEFAULT ${BUILD_SHARED_LIBS})
else()
set(_URIPARSER_SHARED_LIBS_DEFAULT ON)
endif()
option(URIPARSER_SHARED_LIBS "Build shared libraries (rather than static ones)" ${_URIPARSER_SHARED_LIBS_DEFAULT})
```
---
=> uriparser: add version 0.9.8

recipes/fast_double_parser/all/conandata.yml, recipes/fast_double_parser/all/conanfile.py, recipes/fast_double_parser/all/test_package/CMakeLists.txt, recipes/fast_double_parser/config.yml
Specify library name and version:  **fast_double_parser/0.8.0**
https://github.com/lemire/fast_double_parser/compare/v0.7.0...v0.8.0
---
=> fast_double_parser: add version 0.8.0

recipes/libjpeg-turbo/all/conandata.yml, recipes/libjpeg-turbo/config.yml
Specify library name and version:  **libjpeg-turbo/3.0.3**
---
=> libjpeg-turbo: add version 3.0.3

recipes/libdeflate/all/conandata.yml, recipes/libdeflate/config.yml
Specify library name and version:  **libdeflate/1.20**
https://github.com/ebiggers/libdeflate/compare/v1.19...v1.20
---
=> libdeflate: add version 1.20

recipes/libcurl/all/conanfile.py
Specify library name and version:  **libcurl/all** on macOS (14 and up)
macOS 14 Sonoma has new framework CoreServices, to which libcurl stated linking in https://github.com/curl/curl/commit/6ab7e1990bd548059f08c471d20537bca13c67b6
This PR adds the `CoreServices` to the list of system frameworks only when building on macOS 14.
Absence of that framework caused a runtime crash earlier today to one of the apps as described in [here](https://github.com/curl/curl/issues/11893), however, I couldn't reproduce it with a provided test_package (or FWIW a tweaked one).
```
Conan version 2.0.14
```
---
=> libcurl/all: Add CoreServices framework on macOS 14 Sonoma

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  **imgui/1.90.6**
https://github.com/ocornut/imgui/compare/v1.90.5...v1.90.6
---
=> imgui: add version 1.90.6

recipes/lmdb/all/conandata.yml, recipes/lmdb/config.yml
Specify library name and version:  **lmdb/**
Closes #23888
I've been able to use the [backup source feature](https://blog.conan.io/2023/10/03/backup-sources-feature.html) that Conan Center has had active for a while to download the old release tar, and I've been able to confirm that all the files match between the old and new version, BUT that the new version for some reason has a `.gitignore` file added to it:
Old contents:
```
$ ls -a | xargs shasum -a 256
3c87f63656b6a12fda225b6f798c547fe89e3404f499e890b445761eb310fd4f  COPYRIGHT
30e5862a8cbd7a7f7ce990946460e8761351a2d68b1382a3c1091e0aa2472659  CHANGES
5545f6b049040ce58e6d1a603eaea6b7fb8ae92459f2ab8d3bcbacabcce1014d  Doxyfile
310fe25c858a9515fc8c8d7d1f24a67c9496f84a91e0a0e41ea9975b1371e569  LICENSE …
```
=> Add new lmdb version, fix 0.9.31 checksum

recipes/netcdf/all/conandata.yml, recipes/netcdf/all/conanfile.py, recipes/netcdf/all/patches/4.7.4-0002-fix-cross-compile.patch, recipes/netcdf/all/patches/4.8.1-0002-fix-cross-compile.patch
netcdf is unable to find the math library when cross building, similar to #13418. Ran into this issue when cross building from Linux:x86_64 to Linux:armv8. This PR adds a patch that fixes the issue.
---
=> netcdf: fix libm not found in cross build

recipes/libwebsockets/all/conanfile.py
version is always >=4.2.0
since https://github.com/conan-io/conan-center-index/commit/203af455fe87ab5c5034222e793d2983596f77ce
Specify library name and version:  **libwebsockets/***
fixes https://github.com/conan-io/conan-center-index/issues/23899
---
=> libwebsockets: drop dead code

recipes/gegles-spdlog_setup/all/conanfile.py
Specify library name and version:  **gegles-spdlog_setup/1.1.0**
---
=> gegles-spdlog_setup: bump 3p to `spdlog/1.14.1`

recipes/openssh/all/conanfile.py
openssh/*
Changed requirements to allow all openssl/3.1.x releases and not only 3.1.0
---
=> openssh: Allow all openssl 3.1.x releases

recipes/luau/all/conandata.yml, recipes/luau/config.yml
Specify library name and version:  **luau/0.625**
https://github.com/luau-lang/luau/compare/0.620...0.625
---
=> luau: add version 0.625

recipes/ninja/all/conandata.yml, recipes/ninja/config.yml
Specify library name and version:  **ninja/1.12.1**
https://github.com/ninja-build/ninja/compare/v1.12.0...v1.12.1
---
=> ninja: add version 1.12.1

recipes/xsimd/all/conandata.yml, recipes/xsimd/all/conanfile.py, recipes/xsimd/config.yml
Specify library name and version:  **xsimd/13.0.0**
https://github.com/xtensor-stack/xsimd/compare/12.1.0...13.0.0
---
=> xsimd: add version 13.0.0

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/2.6.2**
https://github.com/stephenberry/glaze/compare/v2.6.1...v2.6.2
---
=> glaze: add version 2.6.2

recipes/yomm2/all/conandata.yml, recipes/yomm2/all/conanfile.py, recipes/yomm2/all/test_package/CMakeLists.txt, recipes/yomm2/all/test_package/conanfile.py, recipes/yomm2/all/test_package/test_package.cpp, recipes/yomm2/config.yml
Adding:  **yomm2/1.5.1**
Repository: https://github.com/jll63/yomm2
=> yomm2: new recipe

recipes/boost/all/conanfile.py
Specify library name and version:  **boost/1.83.0**
Tested locally using deprecated Docker image `conanio/gcc48` and Conan 1.59.0:
```
$ conan create . 1.83.0@
Exporting package recipe
boost/1.83.0 exports: File 'conandata.yml' found. Exporting it...
boost/1.83.0 exports: Copied 1 '.yml' file: conandata.yml
boost/1.83.0: Calling export()
boost/1.83.0: Copied 1 '.yml' file: dependencies-1.83.0.yml
boost/1.83.0: Calling export_sources()
boost/1.83.0: The stored package has not changed
boost/1.83.0: Source folder is corrupted, forcing removal
boost/1.83.0: Exported revision: 8ad9800a94fb1cd8dc6ace6c815cfde3
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.8
os=Linux
os_build=Linux
[options]
[build_requires] …
```
=> [boost] Allow building old compilers using C++11

recipes/libqasm/all/conandata.yml, recipes/libqasm/config.yml
Specify library name and version:  **libqasm/0.6.6**
Add version 0.6.6.
---
=> libqasm: add version 0.6.6

recipes/lzham/all/conanfile.py, recipes/lzham/all/test_package/test_package.cpp
Specify library name and version:  **lzham/cci.20220103**
Adding all lzham library static libs to the `cpp_info.libs`
I describe the issue I found in the bug #23647.
---
=> Add all the lzham lib files for msvc builds.

recipes/librdkafka/all/conanfile.py
Do not rename openssl libs anymore if debug in `rdkafka_ssl.c`, since openssl recipe doesn't add d postfix anymore after https://github.com/conan-io/conan-center-index/pull/20999
closes https://github.com/conan-io/conan-center-index/issues/23988
---
=> librdkafka: fix link to openssl debug for msvc

recipes/glaze/all/conandata.yml, recipes/glaze/all/conanfile.py, recipes/glaze/config.yml
Specify library name and version:  **glaze/2.6.3**
glaze/2.6.3 dropped gcc11 support.
https://github.com/stephenberry/glaze/compare/v2.6.2...v2.6.3
---
=> glaze: add version 2.6.3 (dropped gcc11 support)

recipes/ctre/all/conandata.yml, recipes/ctre/config.yml
Specify library name and version:  **ctre/3.9.0**
https://github.com/hanickadot/compile-time-regular-expressions/compare/v3.8.1...v3.9.0
---
=> ctre: add version 3.9.0

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.38.15**
https://github.com/ETLCPP/etl/compare/20.38.14...20.38.15
Small updates for compilation errors.
---
=> etl: add version 20.38.15

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/2.6.4**
https://github.com/stephenberry/glaze/compare/v2.6.3...v2.6.4
---
=> glaze: add version 2.6.4

recipes/libgit2/all/conandata.yml, recipes/libgit2/all/conanfile.py, recipes/libgit2/all/patches/1.8.0-0001-fix-cmake.patch, recipes/libgit2/all/patches/1.8.1-0001-fix-cmake.patch, recipes/libgit2/config.yml
Specify library name and version:  **libgit2/1.8.1**
https://github.com/libgit2/libgit2/compare/v1.7.2...v1.8.1
- Since 1.8.0, libgit2 add the values of `USE_SSH` as `exec` and `libssh2`. In conan CCI, `libssh2` seems to be adequate.
- Since 1.8.1, libgit2 add `USE_HTTP_PARSER` to select http parser library. (`http-parser` and `llhttp`)
---
=> libgit2: add version 1.8.1

recipes/libbsd/all/conandata.yml, recipes/libbsd/all/patches/0002-fix-getentropy-conditional.patch
Specify library name and version:  **libbsd/0.10.0**
This patch fixes the check to avoid building `getentropy.c` in case the system libc already provides that symbol.
---
=> libbsd: Fix check if getentropy needs building

recipes/platformfolders/all/conandata.yml, recipes/platformfolders/all/conanfile.py, recipes/platformfolders/all/test_package/CMakeLists.txt, recipes/platformfolders/all/test_package/conanfile.py, recipes/platformfolders/all/test_package/test_package.cpp, recipes/platformfolders/config.yml
Specify library name and version:  **platformfolders/4.2.0**
The reason that the package_type is static-library is this library do not export any symbol when build shared library with msvc. The fixup pull request is [here](https://github.com/sago007/PlatformFolders/pull/29). The package_type could be change to library and adding shared option when this pr is merged.
---
=> platformfolders: add new recipe for platformfolders

recipes/libmd/all/conandata.yml, recipes/libmd/all/conanfile.py, recipes/libmd/all/test_package/CMakeLists.txt, recipes/libmd/all/test_package/conanfile.py, recipes/libmd/all/test_package/test_package.c, recipes/libmd/config.yml
Adds `libmd`: a message digest library from BSD. Required for the latest versions of `libbsd`.
[![Packaging status](https://repology.org/badge/tiny-repos/libmd.svg)](https://repology.org/project/libmd/versions)
=> libmd: new recipe

recipes/openssh/all/conanfile.py
openssh/*
openssh: Added ability to control "--disable-strip" configure argument
---
=> openssh: Added ability to control "--disable-strip" configure argument

recipes/samurai/all/conandata.yml, recipes/samurai/all/conanfile.py, recipes/samurai/config.yml
Specify library name and version:  **samurai/0.13.0**
https://github.com/hpc-maths/samurai/compare/v0.9.0...v0.13.0
---
=> samurai: add version 0.13.0, solve version conflict

recipes/sqlite3mc/all/conandata.yml, recipes/sqlite3mc/all/conanfile.py, recipes/sqlite3mc/config.yml
Specify library name and version:  **sqlite3mc/1.8.1**,   **sqlite3mc/1.8.2**, **sqlite3mc/1.8.3**,  **sqlite3mc/1.8.4**
A Conan recipe was added for _SQLite3 Multiple Ciphers_ version **1.8.0** in November 2023, but it was approved only recently. In the meantime further versions of _SQLite3 Multiple Ciphers_ were released. This PR adds those new versions to the Conan recipe.
One compile time option was adjusted, namely `ENABLE_USER_AUTHENTICATION`. The _user authentication_ extension was deprecated by the SQLite core developer team. Therefore this option is now disabled by default. Most likely, the source code of this extension will be removed in a future version.
---
=> Add recent versions of SQLite3 Multiple Ciphers

recipes/assimp/5.x/conandata.yml, recipes/assimp/5.x/conanfile.py, recipes/assimp/config.yml
https://github.com/assimp/assimp/releases/tag/v5.4.0
No new formats or exporters were added in this release.
=> assimp: add v5.4.1

recipes/flatbush/all/conandata.yml, recipes/flatbush/config.yml
Specify library name and version: flatbush/1.2.1
Fix multiple definition error when #included in more than one source file
Address several findings reported by clang-tidy and other minor fine-tunings
Ran through clang-format and include-what-you-use
---
=> flatbush: add release v1.2.1

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Specify library name and version:  **glaze/2.6.6**
https://github.com/stephenberry/glaze/compare/v2.6.5...v2.6.6
---
=> glaze: add version 2.6.6

recipes/pixman/all/conanfile.py
Pixman is licensed under the MIT license: https://gitlab.freedesktop.org/pixman/pixman/-/blob/master/COPYING?ref_type=heads
=> pixman: Fix license

docs/changelog.md
Conan Center Index CI is now running Conan 1.64.1 and 2.3.1!!
---
=> [docs] Add changelog 2024-05-22

recipes/lely-core/all/conandata.yml, recipes/lely-core/all/conanfile.py, recipes/lely-core/all/test_package/CMakeLists.txt, recipes/lely-core/config.yml
Specify library name and version:  **lely-core/2.3.4**
https://gitlab.com/lely_industries/lely-core/-/compare/v2.3.3...v2.3.4
---
=> lely-core: add version 2.3.4

recipes/wasmedge/all/conandata.yml, recipes/wasmedge/config.yml
Specify library name and version:  **wasmedge/0.14.0**
https://github.com/WasmEdge/WasmEdge/compare/0.13.5...0.14.0
---
=> wasmedge: add version 0.14.0

recipes/sqlcipher/all/conandata.yml, recipes/sqlcipher/config.yml
Specify library name and version:  **sqlcipher/4.6.0**
https://github.com/sqlcipher/sqlcipher/compare/v4.5.7...v4.6.0
---
=> sqlcipher: add version 4.6.0

recipes/cpprestsdk/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/24095
see https://github.com/microsoft/cpprestsdk/blob/v2.10.19/Release/cmake/cpprest_find_boost.cmake#L77-L106 (this block of code has not changed for 7 years, which was 2.10.0 and oldest version we have is 2.10.15, so I think it's a good reference for boost dependencies of cpprestsdk).
---
=> cpprestsdk: only propagate boost components cpprestsdk depends on

recipes/stb/all/conandata.yml, recipes/stb/config.yml
Specify library name and version:  **STB/cci.20240213**
Simple update with latest stb commit available. The recipe version number is the date of the commit in the official repository.
---
=> Update STB to cci.20240213

recipes/md4c/all/conanfile.py
Specify library name and version:  **md4c/0.5.2**
Allow disabling building the md2html executable, resulting in simply the library(ies) being built.
---
=> md4c: expose md2html option

recipes/qt/5.x.x/conandata.yml, recipes/qt/5.x.x/qtmodules5.15.14.conf, recipes/qt/config.yml
Specify library name and version:  **qt/5.15.14**
- adds Qt 5.15.14
- removes Android backtrace patch as the fix was upstreamed: https://code.qt.io/cgit/qt/qtbase.git/commit/?h=5.15&id=1f154eec608db6caa027db534856f40d2c7ccf87
---
=> add Qt 5.15.14

recipes/vincentlaucsb-csv-parser/all/conandata.yml, recipes/vincentlaucsb-csv-parser/config.yml
Specify library name and version:  **vincentlaucsb-csv-parser/2.2.3**
https://github.com/vincentlaucsb/csv-parser/compare/2.2.2...2.2.3
---
=> vincentlaucsb-csv-parser: add version 2.2.3

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  **imgui/1.90.7**
https://github.com/ocornut/imgui/compare/v1.90.6...v1.90.7
---
=> imgui: add vresion 1.90.7

recipes/yomm2/all/conandata.yml, recipes/yomm2/all/conanfile.py, recipes/yomm2/all/test_package/test_package.cpp, recipes/yomm2/config.yml
Specify library name and version:  **yomm2/1.5.2**
Updating to the latest version of YOMM2, which I just published. Also:
* I think that the patch is not necessary anymore.
* I changed `test_package.cpp` to make it _call_ a method, not just build method tables (actually, this did nothing in the absence of any declared method).
---
=> yomm2: add version 1.5.2

recipes/sioclient/all/conandata.yml, recipes/sioclient/all/conanfile.py, recipes/sioclient/all/test_package/CMakeLists.txt, recipes/sioclient/all/test_package/conanfile.py, recipes/sioclient/all/test_package/test_package.cpp, recipes/sioclient/config.yml
Adds sioclient/cci.20240405: https://github.com/socketio/socket.io-client-cpp
C++11 implementation of Socket.IO client
[![Packaging status](https://repology.org/badge/tiny-repos/socket.io-client-cpp.svg)](https://repology.org/project/socket.io-client-cpp/versions)
The last official release that was published three years ago is much less compatible with packaging without patching so I did not include it.
=> sioclient: new recipe

recipes/libliftoff/all/conandata.yml, recipes/libliftoff/all/conanfile.py, recipes/libliftoff/config.yml
Specify library name and version:  **libliftoff/***
---
=> libliftoff: add version 0.5.0, fix homepage url

recipes/abseil/all/conanfile.py
Abseil: support shared with msvc for the most recent versions
(tested locally the most recent 3 versions, including consuming with newer protobuf on windows with shared libraries)
=> abseil: support shared on msvc

recipes/strawberryperl/all/conanfile.py
Found while trying to help in https://github.com/conan-io/conan-center-index/pull/23955
=> strawberryperl:  Fix binaries not supporting non x86 archs

.c3i/authorized_users.yml, recipes/geographiclib/all/conanfile.py
Specify library name and version:  **geographiclib/2.3**
After checking with the upstream about adding a native option to build or not tools (PR https://github.com/geographiclib/geographiclib/pull/27), it will be more comfortable only skipping the package step instead. Those generated tools require only small amount of time to be built and so far does not break in the CI.
closes #24053
closes #24092
/cc @zeeshancs07
---
=> [geographiclib] Skip packaging tools when not requested

recipes/qt/6.x.x/conanfile.py, recipes/qt/6.x.x/test_package/CMakeLists.txt
Specify library name and version:  **qt/6.7.1**
fixes https://github.com/conan-io/conan-center-index/issues/24131
---
=> qt6: fix resources object files location

recipes/boost/all/conanfile.py
Specify library name and version:  **boost/1.85.0**
The Boost Cobalt has been introduced in Boost 1.84.0 ([changelog](https://www.boost.org/users/history/version_1_84_0.html) and requires C++20 support for coroutines ([Jamfile](https://github.com/boostorg/cobalt/blob/boost-1.84.0/build/Jamfile#L54)).
The current recipe for Boost only validates C++11 and C++14 (Boost math) compilers, but not C++20 (Cobalt). This PR introduces a new check to validate when building Cobalt: The cppstd should be C++20, or the compiler should be new enough (Conan 1.x).
fixes #24148 
---
=> [boost] Check for C++20 compiler support when building Cobalt

recipes/cpuinfo/all/conanfile.py
Specify library name and version:  **cpuinfo/cci.20231129:**
The cpuinfo package is failing when is built with Android because the `test_package` is not able to resolve the Android log function `__android_log_vprint`. See the log below:
```
======== Testing the package: Building ========
cpuinfo/cci.20231129 (test package): Calling build()
cpuinfo/cci.20231129 (test package): Running CMake.configure()
cpuinfo/cci.20231129 (test package): RUN: cmake -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="E:/gitlab_ws/xrsw/0/conan-center-index/recipes/cpuinfo/all/test_package" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "E:/gitlab_ws/xrsw/0/conan-center-index/recipes/cpuinfo/all/test_package"
-- Using Conan toolchain: …
```
=> cpuinfo/cci.20231129: fix missing "log" dependency with Android

recipes/hwloc/all/conandata.yml, recipes/hwloc/all/conanfile.py, recipes/hwloc/config.yml
Based on https://repology.org/project/hwloc/information
=> hwloc: add v2.10.0, drop vulnerable versions (< 2.9.3)

recipes/popl/all/conandata.yml, recipes/popl/all/conanfile.py, recipes/popl/all/test_package/CMakeLists.txt, recipes/popl/all/test_package/conanfile.py, recipes/popl/all/test_package/test_package.cpp, recipes/popl/config.yml
Adds popl/1.3.0: https://github.com/badaix/popl
Header-only C++ command line arguments parser that supports the same set of options as GNU's getopt.
[![Packaging status](https://repology.org/badge/tiny-repos/popl.svg)](https://repology.org/project/popl/versions)
=> popl: new recipe

.c3i/authorized_users.yml, .c3i/reviewers.yml, docs/community_resources.md
Conan-center-index has very regrettably become less and less welcoming to contributors in the passed months. Among other things:
- pull requests are being locked, in the absence of code of conduct violation (https://github.com/conan-io/conan-center-index/pull/23662 https://github.com/conan-io/conan-center-index/pull/21622 https://github.com/conan-io/conan-center-index/pull/23594)
- useful tools (1 as of today) are being removed, without any sort of warning to the people relying on them https://github.com/conan-io/conan-center-index/commit/0ff926d2b637aa4e71e4ca346f5c9e09ae576ee9 (prepare for more tools removal: https://github.com/conan-io/conan-center-index/pull/23757)
- pain points reported repeatedly are not being addressed (https://github.com/conan-io/conan-center-index/issues/17921 …
=> remove myself from the repository

recipes/elfutils/all/conanfile.py
=> elfutils: Bump gettext to version 0.22.5 to support GCC 14

recipes/meson/all/conandata.yml, recipes/meson/config.yml
Specify library name and version:  **meson/1.4.1**
https://github.com/mesonbuild/meson/compare/1.4.0...1.4.1
---
=> meson: add version 1.4.1

recipes/extra-cmake-modules/all/conandata.yml, recipes/extra-cmake-modules/config.yml
Specify library name and version:  **extra-cmake-modules/6.2.0**
I'm updating this because I'm interested in using it in one of my own projects (and maybe other projects as well). If everything goes well, I might also attempt to add some other libraries from KDE Framework 6 (currently interested in `karchive`, `kimageformats` and `kconfig`).
---
=> add extra-cmake-modules 6.2.0

recipes/wiringpi/all/conandata.yml, recipes/wiringpi/config.yml
Specify library name and version:  **wiringpi/3.6**
https://github.com/WiringPi/WiringPi/compare/3.4...3.6
---
=> wiringpi: add version 3.6

recipes/ipaddress/all/conandata.yml, recipes/ipaddress/config.yml
Specify library name and version:  **ipaddress/1.1.0**
Hello again, everyone! In this PR, I’d like to update the recipe to the new version 1.1.0 of the library [Release Notes](https://github.com/VladimirShaleev/ipaddress/releases/tag/v1.1.0)
---
=> ipaddress: add version 1.1.0

recipes/aws-c-cal/all/conanfile.py
Specify library name and version:  **aws-c-cal/0.6.9**
After adding `was-c-common/0.9.12`, I tried to use this version in `aws-c-io` but got a build failure. It is because the dependency of `aws-c-io`: `aws-c-cal` is hard coded to use `aws-c-common/0.9.6`. So, I filed this PR to adjust the version range of the dependencies.
Related PR: https://github.com/conan-io/conan-center-index/pull/22421
---
=> aws-c-cal: fix dependency version conflict

recipes/xnnpack/all/conanfile.py
Specify library name and version: xnnpack/*
This works around a long-standing bug of XNNPACK, which prevents building for Android with assembly=True set:
https://github.com/google/XNNPACK/issues/4348
The issue will not be fixed upstream and the maintainers comment that this is a clang bug. While correct, it would be impossible to build for Android with the NDK without a recipe-level workaround. Disabling assembly is not really an option for performance reasons. This integrates the workaround suggested in the ticket.
In essence I raise the target level from XNNPACK's default of armv6 to armv7 if the Conan user targets armv7 anyway. Should thus be free of side-effects. The previously broken armv6 build is now explicitly aborted with an invalid configuration error, and the user must turn off …
=> xnnpack: fix cross-compiling for Android/armv7

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Specify library name and version:  **etl/20.38.16**
https://github.com/ETLCPP/etl/compare/20.38.15...20.38.16
---
=> etl: add version 20.38.16

recipes/libjpeg/all/conanfile.py
fix regression introduced by https://github.com/conan-io/conan-center-index/pull/23840 (issue is quite obvious in test package with the message `libjpeg.lib(jerror.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance`: https://c3i.jfrog.io/c3i/misc/logs/pr/23840/6-windows-visual_studio/libjpeg/9f//3fb49604f9c2f729b85ba3115852006824e72cab-test.txt)
closes https://github.com/conan-io/conan-center-index/issues/24116
---
=> libjpeg: don't force LTO by default for msvc

recipes/minizip-ng/all/conandata.yml, recipes/minizip-ng/config.yml
Specify library name and version:  **minizip-ng/4.0.6**
https://github.com/zlib-ng/minizip-ng/compare/4.0.5...4.0.6
---
=> minizip-ng: add version 4.0.6

recipes/pdf-writer/all/conandata.yml, recipes/pdf-writer/config.yml
Specify library name and version:  **pdf-writer/4.6.4**
https://github.com/galkahana/PDF-Writer/compare/v4.6.3...v4.6.4
---
=> pdf-writer: add version 4.6.4

recipes/cpp-dump/all/conandata.yml, recipes/cpp-dump/config.yml
Specify library name and version:  **cpp-dump/0.6.0**
https://github.com/philip82148/cpp-dump/compare/v0.5.0...v0.6.0
---
=> cpp-dump: add version 0.6.0

recipes/libxml2/all/conandata.yml, recipes/libxml2/config.yml
Specify library name and version:  **libxml2/2.11.8**
Specify library name and version:  **libxml2/2.12.7**
> This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to package? Are you the author of the library? Thanks!
Currently the new versions are not known at Conan and they contain security fixes too.
See also <https://gitlab.gnome.org/GNOME/libxml2/-/releases>
---
=> libxml2: add latest releases libxml2/2.11.8 libxml2/2.12.7 (changes for CVE-2024-34459)

recipes/gdcm/all/conandata.yml, recipes/gdcm/all/conanfile.py, recipes/gdcm/all/patches/0006-3.0.24-json.patch, recipes/gdcm/config.yml
Specify library name and version:  **gdcm/3.0.24**
---
=> gdcm: add 3.0.24 and update util-linux-libuuid

recipes/openimageio/all/conandata.yml, recipes/openimageio/all/conanfile.py, recipes/openimageio/all/patches/2.5.12.0-cmake-targets.patch, recipes/openimageio/config.yml
Specify library name and version:  **openimageio/2.5.12.0**
Just adding a new version. The CMake patch needed a small adaptation as a few lines had been changed in the upstream CMake file (`src/cmake/externalpackages.cmake`). Otherwise it is exactly the same as the patch for the previous version.
Also there was a need to bump to **openexr/3.2.3** (from 3.2.1) as opencolorio - which is a dependency of openimageio was bumped to this version in the meantime so the Conan 2 pipeline failed.
---
=> OpenImageIO: Add version 2.5.12.0

recipes/boost/all/conanfile.py
boost/*
The conf setting tools.build:verbosity=verbose will be used to set debug_level option to 2, if it's not already set to a higher value.
---
- [x ] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [x ] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
=> boost: listen to tools.build:verbosity

recipes/civetweb/all/conanfile.py
Specify library name and version:  **civetweb/1.16**
When doing memory-intensive tasks in the thread that handles http requests, then it is needed to set the stack size of the thread. Default it is set to 102400 bytes, so that is low for some situations. This PR allows to set the existing CIVETWEB_THREAD_STACK_SIZE cmake value.
---
=> civetweb: Add option to allow to set stack size per thread.

recipes/kdbindings/all/conanfile.py
**kdbindings/1.0.3**
- added "msvc": "191" to compilers list
- clean settings attribute
---
=> Kdbindings fix

recipes/kdbindings/all/conandata.yml, recipes/kdbindings/config.yml
Specify library name and version:  **kdbindings/1.0.5**
Adding newest version of kdbindings as it has some features we need.
---
=> kdbindings: add version 1.0.5

recipes/bitserializer/all/conandata.yml, recipes/bitserializer/all/conanfile.py, recipes/bitserializer/all/test_package/CMakeLists.txt, recipes/bitserializer/all/test_package/conanfile.py, recipes/bitserializer/all/test_package/test_package.cpp, recipes/bitserializer/all/test_v1_package/conanfile.py, recipes/bitserializer/config.yml
Specify library name and version:  **bitserializer/0.70**
I'd like to add a new version of BitSerializer 0.70 to Conan ([Release notes](https://github.com/PavelKisliak/BitSerializer/releases/tag/v0.70)). I am author of library.
---
- [√] I've read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md).
- [√] I've used a [recent](https://github.com/conan-io/conan/releases/latest) Conan client version close to the [currently deployed](https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L6).
- [√] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
=> [bitserializer] Add new version 0.70

recipes/libpq/all/conanfile.py
Specify library name and version:  **libpq/15.4**
When building libpq as static library and openssl is static library too, it passes pthread as transitive dependency, resulting in the error reported by the issue #24208. The reason is because libpq does not allow calling `exit()` neither `abort()`, so they use a `nm` + `grep exit` with few exceptions.
https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/Makefile#L118
I found few threads about adding some exception, like:
- https://www.postgresql.org/message-id/18424-bc056c6239e511fd@postgresql.org
- https://www.postgresql.org/message-id/3128896.1624742969@sss.pgh.pa.us
This PR skips excludes `pthread_exit` from the Makefile, so we can build libpq with openssl.
Out of curiosity, I found more package managers using openssl …
=> [libpq] Avoid pthread_exit as exit code

recipes/sdbus-cpp/all/conanfile.py
Since version 1.4.0, sdbus-c++ supports FreeBSD. On FreeBSD it uses basu library instead of libsystemd.
---
=> sdbus-cpp/all: Add FreeBSD support

recipes/tar/all/conandata.yml, recipes/tar/all/conanfile.py, recipes/tar/all/patches/1.35-001-fix-iconv-link.patch, recipes/tar/config.yml
Specify library name and version:  **tar/1.35**
Add version 1.35
bump xz_utils to 5.4.5
All versions < 1.35 have known security issues: https://repology.org/project/tar/information
---
=> tar: add version 1.35

recipes/leptonica/all/conanfile.py
Specify library name and version:  **leptonica/all**
Non-default with_* options were broken; closes https://github.com/conan-io/conan-center-index/issues/16906
---
=> leptonica: fix with_{gif|jpeg|png|tiff|openjpeg|webp}=False

recipes/iceoryx/all/conandata.yml, recipes/iceoryx/all/conanfile.py, recipes/iceoryx/config.yml
Specify library name and version:  **iceoryx/***
https://github.com/eclipse-iceoryx/iceoryx/compare/v2.0.5...v2.0.6
---
=> iceoryx: add version 2.0.6, remove .clang-tidy

recipes/gettext/all/conandata.yml, recipes/gettext/all/patches/0.21-include-stdlib_h.patch
Specify library name and version:  **gettext/0.21**
I met compilation error on gcc 14.1.1:
```
getted9230827dca7c/b/src/gettext-tools/src/locating-rule.c: In function ‘locating_rule_match’:
getted9230827dca7c/b/src/gettext-tools/src/locating-rule.c:150:7: error: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
150 |       free (reduced);
|       ^~~~
getted9230827dca7c/b/src/gettext-tools/src/locating-rule.c:50:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘free’
49 | #include "xalloc.h"
+++ |+#include <stdlib.h>
50 | 
getted9230827dca7
```
While gettext/0.22.5 works fine on gcc 14.1.1, gettext/0.21 is required by several important recipes (harfbuzz, pulseaudio, tre).
To minimize the impact, it would be better to create an adhoc patch  rather than …
=> gettext: include stdlib.h on 0.21

recipes/qt/6.x.x/conanfile.py
Fix conditional in source() method, which should not have conditionals on settings as per Conan docs (for [v1.x ](https://docs.conan.io/1/reference/conanfile/methods.html#source) and [2.0](https://docs.conan.io/2/reference/conanfile/methods/source.html))
Fix https://github.com/conan-io/conan-center-index/issues/24233
which affects Conan 2.4 since https://github.com/conan-io/conan/pull/16272
=> qt6 source method: Fix windows conditional

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Specify library name and version:  **imgui/1.90.8**
https://github.com/ocornut/imgui/compare/v1.90.7...v1.90.8
---
=> imgui: add version 1.90.8

recipes/raylib/all/conanfile.py
Specify library name and version:  **raylib/5.0**
This allows the consumer to use the emsdk and raylib packages to build raylib games for the web-browser.
I have built a minimal example project [here](https://github.com/Mercotui/conan-raylib-examples)
I followed the documentation about building raylib for the web from [here](https://github.com/raysan5/raylib/wiki/Working-for-Web-(HTML5)).
I wanted to run the conan-center hook but the documentation says it's not supported on conan 2 yet.
---
=> raylib: add emscripten support

recipes/tree-sitter/all/conandata.yml, recipes/tree-sitter/config.yml
Specify library name and version:  **tree-sitter/0.22.6**
https://github.com/tree-sitter/tree-sitter/compare/v0.22.5...v0.22.6
---
=> tree-sitter: add version 0.22.6

recipes/qt/5.x.x/conanfile.py, recipes/qt/5.x.x/test_package/conanfile.py, recipes/qt/5.x.x/test_v1_package/conanfile.py, recipes/qt/6.x.x/conanfile.py, recipes/qt/6.x.x/test_package/conanfile.py, recipes/qt/6.x.x/test_v1_package/conanfile.py
Specify library name and version:  **qt/***
copy of #23944 by Eric's permission
fixes #23660
---
=> qt: use upstream package folder architecture

recipes/openblas/all/conanfile.py
Specify library name and version:  **openblas/\***
This PR adds support for cross-compiling OpenBLAS. In previous versions of the recipe, cross-building was explicitly disabled.
When cross-compiling, OpenBLAS requires the `TARGET` option to be set, so this option has also been added to the Conan recipe. By default, it is set to `None` which has no effect. When cross-compiling, the default `TARGET` is determined based on `settings.arch`.
Native builds should not be affected by these changes.
---
Differences compared to other open pull requests for the OpenBLAS recipe:
- https://github.com/conan-io/conan-center-index/pull/24038:  
_Checking for cross-compilation support should be done in `validate_build()`, not `validate()`_.  
This change is included in the present PR as well, but the …
=> openblas: cross-compilation support

recipes/mp-units/0.8.0/conanfile.py, recipes/mp-units/2.0.0/conanfile.py
Specify library name and version:  **mp-units/all**
Fix version conflict in fmt library
Closes #24247 
---
=> Bumped fmt to latest version avoiding conflicts

docs/adding_packages/dependencies.md
Helpful because most libraries in CCI diverge on the required version
See https://github.com/libuv/libuv#versioning
=> Add libuv to list of supported version range libraries

recipes/glfw/all/conanfile.py
Prefer `dependencies.build` instead of `deps_cpp_info` for the workaround related to generation of `wayland-protocols` pkgconf file from build context in case of 1 profile (see https://github.com/conan-io/conan-center-index/pull/21242#discussion_r1499466346)
/cc @uilianries 
---
=> glfw: use dependencies.build instead of deps_cpp_info

recipes/xkbcommon/all/conanfile.py
Prefer `dependencies.build` instead of `deps_cpp_info` for the workaround related to generation of `wayland-protocols` pkgconf file from build context in case of 1 profile (see https://github.com/conan-io/conan-center-index/pull/21242#discussion_r1499466346)
/cc @uilianries 
---
=> xkbcommon: use dependencies.build instead of deps_cpp_info

recipes/7bitdi/all/conandata.yml, recipes/7bitdi/all/conanfile.py, recipes/7bitdi/config.yml
Specify library name and version:  **7bitdi/3.3.0**
https://github.com/7bitcoder/7bitDI/compare/v3.2.0...v3.3.0
---
=> 7bitdi: add version 3.3.0

recipes/glaze/all/conandata.yml, recipes/glaze/all/conanfile.py, recipes/glaze/config.yml
https://github.com/stephenberry/glaze/compare/v2.7.0...v2.8.0
---
=> glaze: add version 2.8.0, remove older versions

recipes/cmake/3.x.x/conanfile.py
Specify library name and version:  **cmake/3.x.x**
---
=> cmake/3.x.x: bump OpenSSL

recipes/log4cxx/all/conanfile.py
=> log4cxx: use version range for qt5

recipes/mocknetworkaccessmanager/all/conanfile.py
=> mocknetworkaccessmanager: use version range for qt

recipes/qarchive/all/conanfile.py
=> qarchive: use version range for qt 5.15

recipes/octo-logger-cpp/all/conandata.yml, recipes/octo-logger-cpp/all/conanfile.py, recipes/octo-logger-cpp/config.yml
Specify library name and version:  **octo-logger-cpp/***
https://github.com/ofiriluz/octo-logger-cpp/compare/v1.11.0...v1.12.0
---
=> octo-logger-cpp: add version 1.12.0, update dependencies

recipes/cubicinterpolation/all/conanfile.py
Specify library name and version:  **cubicinterpolation/0.1.5**
Bump boost dependency
---
=> bump boost dependency

recipes/cpp-httplib/all/conandata.yml, recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.16.0**
https://github.com/yhirose/cpp-httplib/compare/v0.15.3...v0.16.0
---
=> cpp-httplib: add version 0.16.0

recipes/arrow/all/conanfile.py, recipes/arrow/all/test_package/CMakeLists.txt
Specify library name and version:  **arrow/all**
Update recipe to use the same target names used by upstream.
See:
- [ArrowConfig.cmake.in](https://github.com/apache/arrow/blob/1c9e393b73195840960dfb9eca8c0dc390be751a/cpp/src/arrow/ArrowConfig.cmake.in#L26-L30)
- [ParquetConfig.cmake.in](https://github.com/apache/arrow/blob/1c9e393b73195840960dfb9eca8c0dc390be751a/cpp/src/parquet/ParquetConfig.cmake.in#L25-L29)
- [ArrowSubstraitConfig.cmake.in](https://github.com/apache/arrow/blob/1c9e393b73195840960dfb9eca8c0dc390be751a/cpp/src/arrow/engine/ArrowSubstraitConfig.cmake.in#L23-L26)
- [ArrowAceroConfig.cmake.in](https://github.com/apache/arrow/blob/1c9e393b73195840960dfb9eca8c0dc390be751a/cpp/src/arrow/acero/ArrowAceroConfig.cmake.in#L22-L26)
- …
=> arrow: fix target names

recipes/libftp/all/conandata.yml, recipes/libftp/config.yml
Specify library name and version:  **libftp/0.5.1**
https://github.com/deniskovalchuk/libftp/compare/v0.5.0...v0.5.1
---
=> libftp: add version 0.5.1

recipes/octo-logger-cpp/all/conandata.yml
Specify library name and version:  **octo-logger-cpp/1.12.0**
octo-logger-cpp/1.12.0 is updated.
https://github.com/ofiriluz/octo-logger-cpp/commit/d7069893b09dd4f21f0faa3ba454938a1b8d1718
---
=> octo-logger-cpp: fix checksum for 1.12.0

recipes/proposal/all/conandata.yml, recipes/proposal/all/conanfile.py, recipes/proposal/config.yml
Specify library name and version:  **proposal/***
---
=> proposal: update dependencies

recipes/octo-keygen-cpp/all/conanfile.py
Specify library name and version:  **octo-keygen-cpp**
Bumped `fmt` library from `v10.1.1` to `v10.2.1` to match `octo-logger-cpp` recent recipe update avoiding conflicts.
---
=> octo-logger-cpp: bumped fmt dependency

recipes/boost/all/conanfile.py
Specify library name and version:  **boost/1.85.0**
The PR #24237 fixed a compatibility situation when using compiler that don't have C++20 fully supported with coroutines, so people can use Boost Cobalt as well.
When using GCC10, the coroutines support is available, but it requires passing `-fcoroutines`, as documented in https://gcc.gnu.org/gcc-10/changes.html. For GCC11 and later it's no longer required.
There was a mistake in the logic to add or not `-fcoroutines`, it uses `or`, but should `and`, to only be applied for GCC10.
The Clang project supports coroutines since version 14, and does not require `-fcoroutines`. 
This bug was originally reported in Discord: https://discord.com/channels/400588936151433218/764433875640123402/1249600810439147531
---
=> [boost] Add -fcoroutines for GCC10 only

recipes/jsoncons/all/conandata.yml, recipes/jsoncons/config.yml
Changes to recipe:  **jsoncons/0.176.0**
upstream has been updated.
https://github.com/danielaparker/jsoncons/compare/v0.175.0...v0.176.0
---
=> jsoncons: add version 0.176.0

recipes/libmaxminddb/all/conandata.yml, recipes/libmaxminddb/all/conanfile.py, recipes/libmaxminddb/config.yml
Specify library name and version:  **libmaxmind/1.10.0**
https://github.com/maxmind/libmaxminddb/compare/1.9.1...1.10.0
---
=> libmaxminddb: add version 1.10.0

recipes/gn/all/conanfile.py
Changes to recipe:  **gn**
It is an executable, it doesn't really need a cppstd to be used, only to be built, so changing its ``validate()`` to ``validate_build()``
This can help with: https://github.com/conan-io/conan-center-index/pull/24320
=> change gn validate to validate_build

recipes/sqlite3mc/all/conandata.yml, recipes/sqlite3mc/config.yml
While working on a Python3 wrapper several bugs/issues were detected and fixed in [_SQLite3 Multiple Ciphers 1.8.6_](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.8.6). Some of the bugs can potentially cause database corruption. Therefore an update is recommended.
Version 1.8.6 (based on _SQLite 3.46.0_) added.
---
=> Update to SQLite3 Multiple Ciphers 1.8.6

recipes/glaze/all/conandata.yml, recipes/glaze/config.yml
Changes to recipe:  **glaze/2.9.0**
glaze/2.9.0 has breaking changes for pure reflection support for C style arrays.
https://github.com/stephenberry/glaze/compare/v2.8.4...v2.9.0
---
=> glaze: add version 2.9.0, remove older versions

recipes/mathter/all/conandata.yml, recipes/mathter/config.yml
Changes to recipe:  **mathter/1.1.1**
The new version of the library contains small but important fixes.
The new version (mathter/1.1.1) is appended to the `config.yml`, and the sources are updated.
---
=> mathter: add version 1.1.1

recipes/readline/all/conanfile.py
Changes to recipe:  **readline/[*]**
The examples were always installed, but newer versions have a typo that made them fail.
Closes https://github.com/conan-io/conan-center-index/issues/24321
This is a follow-up/replacement of https://github.com/conan-io/conan-center-index/pull/24322 with express authorization from the author https://github.com/conan-io/conan-center-index/pull/24322#issuecomment-2166999621 - The changes are different so no cherry-pick/CLA signing is necessary on their part.
I would appreciate if I could get some extra insight into whether keeping the examples could be useful for someone - afaik it does not install any heads/libs, so it's purely documentation on our end, (which unless there's a good reason, keeping those is not what we've been doing with the rest of …
=> readline: Disable example installation

recipes/rapidyaml/all/conandata.yml, recipes/rapidyaml/all/conanfile.py, recipes/rapidyaml/all/patches/0.6.0-001-remove-internal-c4core.patch, recipes/rapidyaml/all/patches/0.7.0-001-remove-internal-c4core.patch, recipes/rapidyaml/config.yml
Specify library name and version:  **rapidyaml/0.7.0**
https://github.com/biojppm/rapidyaml/compare/v0.5.0...v0.7.0
---
=> rapidyaml: add version 0.7.0

.c3i/config_v1.yml, .c3i/config_v2.yml
This enables the status checks for conan v2 and disables the conan v1 one.
As the conan v2 builds gain importance, it is better feedback to the user to show the conan v2 builds in the status checks than the ones in conan 1. As in conan 2 there are less configurations built than in conan 1, this will also help on reducing the noise in the PRs.
See this as an example of a PR with a recipe that has just one version:
---
=> [config] Enable github status checks for conan v2 profiles

recipes/highway/all/conandata.yml, recipes/highway/all/patches/1.2.0-0001-fix-dllexport.patch, recipes/highway/config.yml
Specify library name and version:  **highway/1.2.0**
https://github.com/google/highway/compare/1.1.0...1.2.0
---
=> highway: add version 1.2.0

recipes/outcome/all/conandata.yml, recipes/outcome/all/conanfile.py, recipes/outcome/config.yml
Changes to recipe:  **output/2.2.9**
- adding version 2.2.9
- reorder attributes on conanfile.py
- add "header-only" topic
https://github.com/ned14/outcome/compare/v2.2.8...v2.2.9
Using Boost is option. 
We can use outcome without Boost.
---
=> outcome: add version 2.2.9

recipes/string-view-lite/all/conandata.yml, recipes/string-view-lite/all/conanfile.py, recipes/string-view-lite/config.yml
Changes to recipe:  **string-view-lite/1.8.0**
string-view-lite/1.8.0 has several new features.
https://github.com/martinmoene/string-view-lite/compare/v1.7.0...v1.8.0
---
=> string-view-lite: add version 1.8.0

recipes/reflect-cpp/all/conandata.yml, recipes/reflect-cpp/all/conanfile.py, recipes/reflect-cpp/config.yml
Changes to recipe:  **reflect/0.11.1**
- add version 0.11.1
- 0.11.1 introduces `REFLECTCPP_NO_BUNDLED_DEPENDENCIES` which forces using  third-party libraries from external
- defining `REFLECTCPP_NO_BUNDLED_DEPENDENCIES` forces using external ctre library.
https://github.com/getml/reflect-cpp/compare/v0.11.0...v0.11.1
---
=> reflect-cpp: add version 0.11.1

recipes/libvpx/all/conanfile.py
Changes to recipe:  **libvpx/1.13.1**  and 1.14.0
New MSVC 19.40 is out, aka 194, and this recipe only considered 19.3x
This adds support by mapping 194 to vs17 (vs18 hasn't been released yet)
One line change in recipe to add 193 to the version list.
---
=> libvpx: small recipe fix to support MSVC 19.40 aka 194 --> vs17

recipes/c4core/all/conandata.yml, recipes/c4core/all/conanfile.py, recipes/c4core/config.yml
Changes to recipe:  **c4core/***
1. there are several changes in 0.2.1.
2. removing natvis file in include/c4.
(ex. .conan2/p/b/c4cor1f07fd1a5ad74/p/include/c4/c4core.natvis)
https://github.com/biojppm/c4core/compare/v0.2.0...v0.2.1
---
=> c4core: add version 0.2.1, remove natvis file

recipes/boost/all/conandata.yml, recipes/boost/all/patches/1.85.0-container-aliasing-violation-fix.patch
Changes to recipe:  boost/1.85.0
boost::container in 1.85.0 contains an aliasing violation which causes strange behavior with movable key-value types and optimizations enabled. See https://github.com/boostorg/container/issues/281
The patch file in the PR is taken from https://github.com/boostorg/container/commit/20ad12f20e661978e90dc7f36d8ab8ac05e5a5a9 with the .gitignore file removed.
---
=> boost: fix aliasing violation in boost::container

recipes/simd/all/conandata.yml, recipes/simd/all/conanfile.py, recipes/simd/all/test_package/CMakeLists.txt, recipes/simd/all/test_package/conanfile.py, recipes/simd/all/test_package/test_package.cpp, recipes/simd/config.yml
Specify library name and version:  **simd/***
---
=> simd: add recipe

recipes/grpc/all/conandata.yml, recipes/grpc/all/conanfile.py, recipes/grpc/all/patches/v1.50.x/002-CMake-Add-gRPC_USE_SYSTEMD-option-34384.patch
Changes to the recipe:  **grpc/1.54.3**
Avoid building unnecessary libsystemd and its transitive dependencies.
This merge request backports a commit from upstream that allows disabling systemd support.
The original commit can be found at:
https://github.com/grpc/grpc/commit/5c3400e8dc08d0810e3301d7e8cd8a718c82eeed
---
=> grpc: allow to disable systemd support

recipes/grpc/all/conanfile.py
Changes to recipe:  **grpc/1.54.3**
Fix issue when build with:
```shell
conan create . --version=1.54.3 --build=missing -o with_libsystemd=False
```
Fixes the following build issues:
```shell
ERROR: grpc/1.54.3: required component package 'libsystemd::' not in dependencies
```
---
=> grpc: fix build issues with libsystemd disabled

recipes/tomlplusplus/all/conanfile.py
Changes to recipe:  **tomlplusplus/[*]**
https://github.com/conan-io/conan-center-index/pull/24336 added toggling of the exception support, but it was checking the internal `.value` member of options, which is not correct
Simply checking for the option is enough in all 3 cases
cc @xoorath
=> tomlplusplus: Fix exception option handling

recipes/xmlsec/all/conanfile.py
We can now use version range for libxml2, this should reduce conflicts.
**depends on #23633**
---
=> xmlsec: use version range for libxml2

recipes/botan/all/conanfile.py
- avoid configure.py failure when prefix path contains space
- avoid the exception raised by platform.libc_ver() when python was installed by Windows Store
=> botan: avoid configure.py failure when prefix path contains space

recipes/nsync/all/conandata.yml, recipes/nsync/all/conanfile.py, recipes/nsync/config.yml
Changes to recipe:  **nsync/1.28.0**
https://github.com/google/nsync/compare/1.27.0...1.28.0
---
=> nsync: add version 1.28.0

recipes/drogon/all/conandata.yml, recipes/drogon/all/conanfile.py, recipes/drogon/config.yml
Specify library name and version:  **drogon/1.9.5**
https://github.com/drogonframework/drogon/compare/v1.9.4...v1.9.5
trantor is reqiured by drogon only.
---
=> drogon: add version 1.9.5, update trantor

recipes/c-blosc2/all/conandata.yml, recipes/c-blosc2/config.yml
Changes to recipe:  **c-blosc2/2.15.0**
There are API changes in 2.15.0.
https://github.com/Blosc/c-blosc2/compare/v2.14.4...v2.15.0
---
=> c-blosc2: add version 2.15.0

recipes/uwebsockets/all/conandata.yml, recipes/uwebsockets/config.yml
Changes to recipe:  **uwebsockets/20.63.0**
uwebsockets/20.63.0 removes C-API and provides several bug fixes.
https://github.com/uNetworking/uWebSockets/compare/v20.62.0...v20.63.0
---
=> uwebsockets: add version 20.63.0

recipes/libdisplay-info/all/conandata.yml, recipes/libdisplay-info/config.yml
Changes to recipe:  **libdisplay-info/0.2.0**
There are several new features on 0.2.0.
https://gitlab.freedesktop.org/emersion/libdisplay-info/-/compare/0.1.1...0.2.0
---
=> libdisplay-info: add version 0.2.0

recipes/rapidcsv/all/conandata.yml, recipes/rapidcsv/config.yml
Changes to recipe:  **rapidcsv/8.83**
8.83 is the bugfix release.
https://github.com/d99kris/rapidcsv/compare/v8.82...v8.83
---
=> rapidcsv: add version 8.83

recipes/tensorflow-lite/all/conanfile.py, recipes/tensorflow-lite/all/patches/2.12.0-0001-remove_simple_memory_arena_debug_dump.patch, recipes/tensorflow-lite/all/patches/2.12.0-0002-disable-fetch-content.patch, recipes/tensorflow-lite/all/patches/2.12.0-0003-use-cci-dependencies.patch
Changes to recipe:  **tensorflow-lite/2.12.0**
The patch always links with `pthreadpool`, but it was only ever `find_package`ed if running with `with_xnnpack=True`. This PR fixes the issue for 2.12.0. In 2.10.0, the pthreadpool dependency was exclusive to xnn_pack, but we didn't update properly
Closes https://github.com/conan-io/conan-center-index/issues/24359
The patches unvendorize the `pthreadpool` dependency and assumes it always needs to link, which AFAIK it's correct, (but would appreciate a double check of my findings!), but did not correctly call the `find_package` when necessary
=> Fix with_xnnpack=False

recipes/beauty/all/conandata.yml, recipes/beauty/all/conanfile.py, recipes/beauty/all/patches/0002-remove-openssl-target.patch, recipes/beauty/all/test_package/CMakeLists.txt, recipes/beauty/config.yml
Changes to recipe:  **beauty/1.0.3**
The current recipe uses OpenSSL, but does pass the option to activate the feature.
- Added version 1.0.4 (Support for Boost 1.85.0): https://github.com/dfleury2/beauty/issues/30
- Downgraded required C++ version to 17: https://github.com/dfleury2/beauty/blob/master/CMakeLists.txt#L9
- Add option for OpenSSL: https://github.com/dfleury2/beauty/blob/master/CMakeLists.txt#L28
/cc @barbacar
fixes #24363
---
=> [beauty] Fix Openssl dependency management 

recipes/apr/all/conanfile.py
Changes to recipe:  **apr/[*]**
Coming from: https://github.com/conan-io/conan-center-index/pull/17609
This PR does not provide pre-built cached files, it offers some common flags to let the machine configure the APR library when cross-building.
* Added configuration flags to bypass some common errors trying to cross-compile APR.
* Added user conf variable `user.apr:cache_file` to pass any pre-built cached file.
cc @swebb2066
=> [POC][APR] Support for cross-building using configuration variables

recipes/pixman/all/conanfile.py
Changes to recipe:  **pixman/0.43.4**
Pixman build for Android armv7 looks for the cpu-features.h header, which usually is supplied by the NDK. Without this patch Pixman does not compile for Android armv7.
Pixman's meson build accepts option which tells it where to look for cpu-features.c and cpu-features.h . This patch does exactly just that.
I am aware of #8011 , but it is not merged, and I assume that Pixman's source code too would need to be patched to take a different library, while my suggested patch just supplies the correct meson option and Pixman just works then.
Even with this patch, older versions of pixman (0.43.0 and 0.42.2) are still build broken for Android armv7, but I am not too concerned with them, because they were buildbroken before this patch too.
Link to a CI run …
=> Pixman: Supply cpu-features-path meson option. Required to build for Android-armv7

recipes/pcre2/all/conanfile.py
Changes to recipe:  **pcre2/10.XX**
Add support for passing a configurable PCRE2_LINK_SIZE. 
This directly translates to LINK_SIZE here https://github.com/PCRE2Project/pcre2/blob/9a51f31da1c2d45e1f31d6a0d6b2f62975fed373/src/config.h.generic#L167.
In short, the default size of 2 creates a hard limit of 65535 bytes to be used by the compiled regular expression. This creates a hard upper limit for the size of regular expressions that can be compiled. Using a link size of 4 expands this to 4GB. For most use cases, 64KB is more than enough. But in some edge cases, it's not:
https://github.com/PCRE2Project/pcre2/issues/271
https://github.com/PCRE2Project/pcre2/issues/406
This adds support for the flag in the conan package to support the users in those edge cases.
This just adds an option …
=> pcre2: Add support for PCRE2_LINK_SIZE

recipes/nsync/all/conandata.yml, recipes/nsync/config.yml
Changes to recipe:  **nsync/1.29.1**
add version 1.29.1
https://github.com/google/nsync/compare/1.28.0...1.29.1
---
=> nsync: add version 1.29.1

recipes/dbus/1.x.x/conanfile.py
Changes to recipe:  **dbus/1.15.8**
This bug was reported by @garethsb. Thank you! 
Using option value as `None` is converted to `"None"`, resulting in misconfiguration when consuming the project.
Plus, `with_glib` option is deprecated, and now removed.
The upstream defines specific paths when not configured: https://gitlab.freedesktop.org/dbus/dbus/-/blob/dbus-1.15.8/meson.build?ref_type=tags#L956
It will be better only passing values when the option is configured.
---
=> [dbus] Use default meson values when options are None

recipes/gsoap/all/test_package/conanfile.py, recipes/gsoap/all/test_package/test_package.cpp
Changes to recipe:  gsoap (test package only)
Ensure the we test only a single package_id during `conan test`, to avoid build order issues on CI 
When different package_id are required, CI cannot guarantee that the "other" ID will have been generated and uploaded before test time. We do lose some slice of testing here: it is no longer tested if it is cross-built - however, there is correlation: if `self.run(xxx, env="conanrun")` works, for the `self.requires(self.tested_reference_str)`, then `self.run(xxx, env="conanbuild")` should work for `self.tool_requires(self.tested_reference_str)`, assuming that the only thing we need is the `bin` directory added to the path.
Additionally: simplify the test package C++ file - linking is already tested with minimal code.
=> gsoap: test only the created reference

recipes/lua/all/conandata.yml, recipes/lua/config.yml
Changes to recipe:  **lua/5.4.7**
lua/5.4.7 is a bug-fix release.
https://www.lua.org/work/diffs-lua-5.4.6-lua-5.4.7.html
---
=> lua: add version 5.4.7

recipes/gtlab-logging/all/conandata.yml, recipes/gtlab-logging/all/conanfile.py, recipes/gtlab-logging/all/test_package/CMakeLists.txt, recipes/gtlab-logging/all/test_package/conanfile.py, recipes/gtlab-logging/all/test_package/example.cpp, recipes/gtlab-logging/config.yml
Specify library name and version:  **gtlab-logging/4.4.1**
We are the developers of the gtlab-logging  library. We just open sourced our gtlab ecosystem with libraries etc and now want to support a smooth build experience for the users. 
Therefore, we want to use conan for our builds and we need to provide all libraries as conan packages.
---
(Conan 1.59.0, Conan 2.0.14)
(Shared, Static, debug, release, Windows only)
Closes #21739
=> gtlab-logging: Initial support for the gtlab-logging library (4.4.1)

recipes/iconfontcppheaders/all/conandata.yml, recipes/iconfontcppheaders/all/conanfile.py, recipes/iconfontcppheaders/config.yml
The usual updates as well as adding support for Google Material Design Symbols
Changes to recipe:  **iconfontcppheaders/cci.20240620**
Get support for the latest icon sets.
Just a bump to the latest upstream version and an updated description.
---
=> iconfontcppheaders: bump version to cci.20240620

recipes/pulseaudio/all/conanfile.py
Changes to recipe:  **pulseaudio/[<=14.2]**
Closes: https://github.com/conan-io/conan-center-index/issues/24464
Configure step fails with:
```shell
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking host operating system... linux
checking whether C compiler accepts -std=gnu11... no
configure: error: *** Compiler does not support -std=gnu11
```
Applying this workaround:
```
....
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
compiler=clang
compiler.cppstd=gnu11
compiler.version=15
os=Linux
[conf]
tools.build:compiler_executables={'c': 'clang-15', 'cpp': 'clang++-15'}
....
checking if the linker …
```
=> pulseaudio: Workaround if clang 15

recipes/mongo-c-driver/all/conandata.yml, recipes/mongo-c-driver/config.yml
Changes to recipe:  **mongo-c-driver/1.27.3**
There are several internal improvements in 1.27.3.
https://github.com/mongodb/mongo-c-driver/compare/1.27.2...1.27.3
---
=> mongo-c-driver: add version 1.27.3

recipes/magic_enum/all/conandata.yml, recipes/magic_enum/config.yml
Changes to recipe:  **magic_enum/0.9.6**
There are several improvements in 0.9.6.
https://github.com/Neargye/magic_enum/releases/tag/v0.9.6
https://github.com/Neargye/magic_enum/compare/v0.9.5...v0.9.6
---
=> magic_enum: add version 0.9.6

recipes/artery-font-format/all/conandata.yml, recipes/artery-font-format/all/conanfile.py, recipes/artery-font-format/all/test_package/CMakeLists.txt, recipes/artery-font-format/all/test_package/conanfile.py, recipes/artery-font-format/config.yml
Changes to recipe:  **artery-font-format/1.1**
There is a data structure updated in 1.1.
https://github.com/Chlumsky/artery-font-format/compare/v1.0.1...v1.1
---
=> artery-font-format: add version 1.1

recipes/dbus/1.x.x/conanfile.py
Changes to recipe:  **dbus/1.15.8**
The `localstatedir` affects the system_bus_socket configuration, which is hardcoded in provided binaries. The usual case is consuming from system.
When building DBUS, it shows:
```
Program tools/check-runstatedir.sh found: YES (/home/conan/.conan2/p/b/dbus5310cead1ccb5/b/src/tools/check-runstatedir.sh)
../src/meson.build:934: WARNING: 
NOTE: system bus listens on /res/var/run/dbus/system_bus_socket
| This build of dbus will not interoperate with the well-known
| system bus socket, /var/run/dbus/system_bus_socket.
```
The recommended folder is `/var`, not the package folder. The Prefix points to `/`, which results in `/res`.
Still, people can customize Toolchain directly via configuration: https://github.com/conan-io/conan-center-index/issues/5782#issueco …
=> [dbus] Do not customize system bus listens

recipes/daw_utf_range/all/conandata.yml, recipes/daw_utf_range/all/conanfile.py, recipes/daw_utf_range/config.yml
Changes to recipe:  **daw_utf_range/2.2.5**
This release solves a compilation error in gcc 14.1.
https://github.com/beached/utf_range/compare/v2.2.4...v2.2.5
---
=> daw_utf_range: add version 2.2.5

recipes/qt/5.x.x/conanfile.py
Changes to recipe:  **qt/5.x.x**
`qt/5.15.14` with default options and `*/*:shared=False` fails during `find_package()` in consuming projects due to `qtaudio_alsa` and `gstcamerabin` library files not being found.
These two plugins are always added on Linux in the conanfile. However, they are only enabled in the Qt5 project files if `libalsa` and `gstreamer` are available: https://github.com/qt/qtmultimedia/blob/v5.14.2/src/plugins/plugins.pro#L47-L59
Only add these plugins when `with_libalsa` and `with_gstreamer` are enabled, respectively, as a fix.
This has probably not been caught by the CI due to the `"essential_modules": not os.getenv('CONAN_CENTER_BUILD_SERVICE')` default, which disables `qtmultimedia`.
---
=> Qt5: fix incorrectly added qtaudio_alsa and gstcamerabin plugin libs

recipes/pybind11/all/conandata.yml, recipes/pybind11/all/conanfile.py, recipes/pybind11/all/test_package/CMakeLists.txt, recipes/pybind11/config.yml
Changes to recipe:  **pybind11/2.13.1**
There are several new features since 2.12.0.
https://github.com/pybind/pybind11/compare/v2.12.0...v2.13.1
Sort versions in `config.yml` and `conandata.yml`.
---
=> pybind11: add version 2.13.1

recipes/openimageio/all/conandata.yml, recipes/openimageio/config.yml
Changes to recipe:  **openimageio/2.5.13.0**
Adding the newest version as I use this library for reading/writing images and like to stay up to date.
Just adding a new source & applying the patch of the previous version. The CMake files haven't been changed so the patch for finding dependencies didn't need manual adaptation.
---
=> OpenImageIO: Add version 2.5.13.0

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/all/conanfile.py, recipes/daw_header_libraries/config.yml
Changes to recipe:  **daw_header_libraries/2.106.1**
Small bugfix release.
https://github.com/beached/header_libraries/compare/v2.106.0...v2.106.1
---
=> daw_header_libraries: add version 2.106.1, remove older versions

recipes/libavrocpp/all/conandata.yml, recipes/libavrocpp/all/conanfile.py, recipes/libavrocpp/all/patches/0006-disable-warn-as-error-1-11-3.patch, recipes/libavrocpp/config.yml
Changes to recipe:  **libavrocpp/1.11.3**
Add release 1.11.3, bug fix, Conan v2
- Add release libavroccp/1.11.3
- Fix conan v2 compatibility
- Fix minimum c++14 requirement with some components of boost > 1.81.0
---
- [ x ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ x ] Checked that this PR is not a duplicate: #19911 , #22320 (https://github.com/conan-io/conan-center-index/discussions/24240)
- [ x ] Tested locally with at least one configuration using a recent version of Conan
=> libavrocpp: add version 1.11.3, compatibility conan v2

.c3i/config_v2.yml
PRs merged to master will tigger an additional promotion to this repo only for conan v2 packages
---
=> [config] Add additional repo to promote conan v2 only packages

recipes/fmt/all/conandata.yml, recipes/fmt/all/conanfile.py, recipes/fmt/all/test_package/test_package.cpp, recipes/fmt/config.yml
Changes to recipe:  **fmt/11.0.0**
There are lots of update since 10.2.1.
https://github.com/fmtlib/fmt/compare/10.2.1...11.0.0
I deleted one line in test_package.cpp because it failed in gcc14 with c++20.
I already created [PR](https://github.com/fmtlib/fmt/pull/4042) about this issue. 
Since this seems to be a rare case, I decided to delete this line without waiting for the merge.
---
=> fmt: add version 11.0.0

recipes/roaring/all/conandata.yml, recipes/roaring/config.yml
Changes to recipe:  **roaring/4.1.0**
There are several improvements in 4.1.0.
https://github.com/RoaringBitmap/CRoaring/compare/v4.0.0...v4.1.0
---
=> roaring: add version 4.1.0, remove older versions

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Changes to recipe:  **imgui/1.90.9**
There are lots of improvements in 1.90.9.
There are lots of versions in this recipe which is not referred by any recipes.
https://github.com/ocornut/imgui/compare/v1.90.8...v1.90.9
---
=> imgui: add version 1.90.9, remove older versions

recipes/paho-mqtt-cpp/all/conandata.yml, recipes/paho-mqtt-cpp/all/conanfile.py, recipes/paho-mqtt-cpp/all/patches/1.4.0-0001-fix-cmake.patch, recipes/paho-mqtt-cpp/all/test_package/CMakeLists.txt, recipes/paho-mqtt-cpp/config.yml
Changes to recipe:  **paho-mqtt-cpp/1.4.0**
The link definition to paho-mqtt-c has been changed since 1.4.0.
https://github.com/eclipse/paho.mqtt.cpp/compare/v1.3.2...v1.4.0
---
=> paho-mqtt-cpp: add version 1.4.0

recipes/qr-code-generator/all/CMakeLists.txt, recipes/qr-code-generator/all/conanfile.py
Specify library name and version:  **qr-code-generator/1.8.0**
* Compile as C when the package is built with the new "compile_as_c" option.
---
=> Compile as C

recipes/mongo-cxx-driver/all/conandata.yml, recipes/mongo-cxx-driver/all/conanfile.py, recipes/mongo-cxx-driver/all/patches/3.10.1-0001-dirs.patch, recipes/mongo-cxx-driver/all/patches/3.10.1-0002-remove-abi-suffixes.patch, recipes/mongo-cxx-driver/config.yml
Specify library name and version:  **mongo-cxx-driver/3.10.1**
https://github.com/mongodb/mongo-cxx-driver/compare/r3.8.1...r3.10.1
---
=> mongo-cxx-driver: add version 3.10.1, update mongo-c-driver

recipes/boost/all/conanfile.py
Changes to recipe:  **boost/[*]**
Current Conan recipe for Boost checks for `intel` as compiler name, but in Conan 2.x it should be `intel-cc`.
fixes #22222
In Conan 1.x, the compiler provided by Intel was identified as `intel` initially. Later, a new configuration was added with a new name:  `intel-cc`: https://docs.conan.io/1/reference/config_files/settings.yml.html#settings-yml
The same `intel-cc` compiler name is adopted in Conan 2.x and `intel` is no longer supported: 
https://docs.conan.io/2/reference/config_files/settings.html#settings-yml
I can't build using this compiler, but I checked Boost Build sources and the toolset names are still correct after all this time: https://github.com/boostorg/build/blob/4a52d8c06635435b64e31a56eaf7ca5dc912a71d/src/tools/intel.jam#L68
---
=> [boost] Fix support for intel-cc

recipes/uwebsockets/all/conandata.yml, recipes/uwebsockets/config.yml
Changes to recipe:  **uwebsockets/20.64.0**
There are a (significant) performance improvement in 20.64.0.
https://github.com/uNetworking/uWebSockets/compare/v20.63.0...v20.64.0
---
=> uwebsockets: add version 20.64.0

recipes/commata/all/conandata.yml, recipes/commata/config.yml
Changes to recipe:  **commata/1.0.0**
The patche files for 0.2.9 are merged in 1.0.0.
https://github.com/furfurylic/commata/compare/v0.2.9...v1.0.0
---
=> commata: add version 1.0.0

recipes/ada/all/conandata.yml, recipes/ada/config.yml
Changes to recipe:  **ada/2.9.0**
There are several improvements in 2.9.0.
https://github.com/ada-url/ada/compare/v2.8.0...v2.9.0
---
=> ada: add version 2.9.0, remove older versions

recipes/dtl/all/conanfile.py
Changes to recipe:  **dtl/***
To support gcc 14, make `enableTrivial` mutable.
https://github.com/cubicdaiya/dtl/pull/18
---
=> dtl: support gcc 14

recipes/ffmpeg/all/conanfile.py
Changes to recipe:  **ffmpeg/4.4.4**
When building ffmpeg in an internal CI, the test package failed due missing symbols:
```
[100%] Linking C executable test_package
/opt/conan/binutils/bin/ld: /home/conan/workspace/prod-v2/bsr/58491/efdad/p/b/ffmpec5959be2046a5/p/lib/libavdevice.a(xv.o): undefined reference to symbol 'XShmDetach'
/opt/conan/binutils/bin/ld: /usr/lib/x86_64-linux-gnu/libXext.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/test_package.dir/build.make:134: 
```
This PR adds explicit used modules to avoid DSO missing errors.
When adding `xorg::xext` to fix the original error, it results in new errors related to other required modules:
```
/opt/conan/binutils/bin/ld: …
```
=> [ffmpeg] Link missing xcb components

recipes/openexr/2.x/conanfile.py
Changes to recipe:  **openexr/2.x**
Avoid conflict between files generated by `PkgConfigDeps` for openexr 2.x on case-insensitive file systems.
closes https://github.com/conan-io/conan-center-index/issues/24559
`PkgConfigDeps` generate `OpenEXR.pc` file for `openexr_ilmimf` component , while an unwanted `openexr.pc` file is generated by default for the "global" component. To avoid conflict on case-insensitive file systems like Windows, we enforce an another custom `pkg_config_name` for this global component.
---
=> openexr 2.x: avoid conflict in PkgConfigDeps

.c3i/config_v2.yml
The ConanCenterIndex CI will be running Conan 2.5.0 for any Conan 2.x build. 
---
=> config: Update Conan client version to 2.5.0

docs/changelog.md
- ConanCenterIndex CI is now running Conan 2.5.0 for any Conan 2.x build.
- Fix internal code affecting the PR #24010 when generating graph info in Conan 1.x 
---
=> docs: Changelog 2024 July 10

recipes/msys2/all/conanfile.py
Changes to recipe:  **msys2/all**
Windows users building ffmpeg are reporting issues with the `PKG_CONFIG_PATH` variable due to a spurious `::` empty path that may interfere with pkgconf.exe or msys2 path conversions. See: 
https://github.com/conan-io/conan-center-index/issues/23309
Based on user troubleshooting, the problem goes away if there's no empty entry in the path list.
Use shell parameter expansion such that, if `PKG_CONFIG_PATH` already has a value, we append to it - otherwise, do noting. This avoids an empty `:` when `PKG_CONFIG_PATH` is unset.
see
https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
---
=> msys2: conditionally prepend pkg_config_path

recipes/glib/all/conandata.yml, recipes/glib/all/conanfile.py, recipes/glib/all/patches/remove-distutils-2.77.0.patch, recipes/glib/all/patches/remove-distutils.patch
Changes in this PR:
* Backport: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4133 to support python 3.12 (which does not have distutils). Also compatible with earlier versions of python.
* Use newer version of meson (at least 1.2.3 is required to support python 3.12, otherwise it complains about missing distutils, see [here](https://mesonbuild.com/meson-python/reference/meson-compatibility.html#cmdoption-arg-1.2.3))
=> glib: support python 3.12

recipes/libfdk_aac/all/conanfile.py
Changes to recipe:  **libfdk_acc/2.0.4**
The issue #20511 points an error when building `ffmpeg` for Android:
```
[ 66%] Building CXX object CMakeFiles/fdk-aac.dir/libSBRdec/src/lpp_tran.cpp.o
/Users/paulo/.conan/data/libfdk_aac/2.0.2/_/_/build/36795b10a36cc186da0ea4af22f48240bd009d62/src/libSBRdec/src/lpp_tran.cpp:122:10: fatal error: 'log/log.h' file not found
#include "log/log.h"
^~~~~~~~~~~
1 error generated.
```
That error comes from `fdk-aac`. It's missing a header named as `log.h`, the same error is  reported in the upstream already:
- https://github.com/mstorsjo/fdk-aac/issues/124
- https://github.com/mstorsjo/fdk-aac/issues/150
- https://github.com/mstorsjo/fdk-aac/issues/144
The author is clear about not supporting NDK here: https://github.com/mstorsjo/fdk-aac/issues/124
It's …
=> libfdk_acc: Do not support building for Android when using NDK

recipes/ouster_sdk/all/conandata.yml, recipes/ouster_sdk/config.yml
Adding new version of `ouster_sdk`:  **ouster_sdk/0.12.0**
Ouster has released a new version of their C++ SDK for their lidars. I would like to have it in `conan-center`.
This is just a version bump, no recipe changes.
---
=> ouster_sdk: add version 0.12.0

recipes/mongo-cxx-driver/all/conandata.yml, recipes/mongo-cxx-driver/all/patches/3.10.2-0001-dirs.patch, recipes/mongo-cxx-driver/config.yml
Changes to recipe:  **mongo-cxx-driver/3.10.2**
Try to fix https://github.com/conan-io/conan-center-index/issues/24451.
https://github.com/mongodb/mongo-cxx-driver/compare/r3.10.1...r3.10.2#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---
=> mongo-cxx-driver: add version 3.10.2

recipes/libinterpolate/all/conanfile.py, recipes/libinterpolate/all/test_package/CMakeLists.txt
Changes to recipe:  **libinterpolate/2.6.4**
The issue #24571 is about asking to add for Mac when consuming libinterpolate. The author agreed adding support for Mac: https://github.com/conan-io/conan-center-index/issues/24571#issuecomment-2223614114
/cc @thomas-harries-hasselbalch-maersk @CD3 
closes #24574
closes #24571
The project is indeed working with Mac, we can prove it now by the CI integrated in the upstream: https://github.com/CD3/libInterpolate/actions/workflows/mac-clang.yml
I updated the dependencies versions, it should not conflict CCI, because no other package is consuming libinterpolate directly. 
---
=> libinterpolate: Add support for Mac

recipes/sdl_image/all/conanfile.py
Closes: https://github.com/conan-io/conan-center-index/issues/24406
Uses the same version range for `sdl_image` for `libpng` [that the one used by freetype](https://github.com/conan-io/conan-center-index/blob/739cf667d599a4d2dcd6a7b53bcc29dc019e38c0/recipes/freetype/all/conanfile.py#L61) that is a requirement of `sdl_ttf` so that we avoid conflicts as much as possible as these libraries are frequently used together.
=> Use version range for libpng in sdl_image recipe

recipes/libx265/all/conanfile.py
Changes to recipe:  **libx265/3.4**
As reported by the issue #23721 the libx265 fails to be built to Android when using the option value `assembly=True`. This is not only breaking this package, but also affecting ffmpeg directly when cross-building to Android.
It's a known issue reported in the upstream already, but no official solution so far: https://bitbucket.org/multicoreware/x265_git/issues/603/aarch64-assembly-code-failing-when-cross
To build assembly code in x265, it's used a custom command in the project, which propagates manually which flags should be used by the compiler, resulting in failure when cross-build to Android-armv8.
Other package managers tried custom patches (including Gentoo) to solve the case, but it still fails for me locally. For instance, when passing target to …
=> libx265: Disable assembly when building for Android

recipes/c-ares/all/conandata.yml, recipes/c-ares/config.yml
Changes to recipe:  **c-ares/1.32.2**
There are several bugfixes in 1.32.2.
https://github.com/c-ares/c-ares/compare/v1.32.1...v1.32.2#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---
=> c-ares: add version 1.32.2

recipes/botan/all/conandata.yml, recipes/botan/all/conanfile.py, recipes/botan/config.yml
Adds Botan's [new release 3.5.0](https://github.com/randombit/botan/blob/master/news.rst#version-350-2024-07-08) and introduces recipe options `enable_experimental_features=False` and `enable_deprecated_features=True`.
Botan's module system makes use of a basic 'module lifecycle' starting with version 3.5.0 of the library. Modules can be 'experimental', 'stable' or 'deprecated'. This is reflected by the new recipe options `enable_experimental_features` and `enable_deprecated_features`. Their defaults match the defaults of the upstream library: deprecated modules are built, experimentals are not.
Botan 3.5.0 has deprecated a few modules, namely:
| Module name    | Description                                                                                                             |
| …
=> Botan: add version 3.5.0

recipes/tracy/all/conandata.yml, recipes/tracy/all/conanfile.py, recipes/tracy/config.yml
Changes to recipe:  **tracy/0.11.0**
There are several improvements in 0.11.0.
There are new three cmake options in 0.11.0, but these don't work well in my environments.
I'm investigating.
https://github.com/wolfpld/tracy/compare/v0.10...v0.11.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---
=> tracy: add version 0.11.0

recipes/fast_float/all/conandata.yml, recipes/fast_float/config.yml
Changes to recipe:  **fast_float/6.1.3**
There are several improvements since 6.1.1.
https://github.com/fastfloat/fast_float/compare/v6.1.1...v6.1.3#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---
=> fast_float: add version 6.1.3

linter/conandata_yaml_linter.py
the "description" field is optional, that is, it is not required by `apply_conandata_patches()` 
while useful, this should have never been added without addressing existing "violations" of this linter rule, or at least filtering out violations that predated the PR and are not part of a PR changeset.
It is unacceptable that PR contributors are alerted by things unrelated to their PR, that pre-date the PR and is not their responsibility to fix. It also adds unnecessary noise to reviewers - the focus should be on the changes in the PR, not something pre-existing.
On the other hand, for _some_ PRs that only add new versions, CI knows to only build the version that is added if the recipe is not modified. Well intentioned contributors may choose to address these linter warnings, which would …
=> yaml linter: patch description is optional - reduce noise in pull requests

recipes/modern-cpp-kafka/all/conandata.yml, recipes/modern-cpp-kafka/config.yml
Changes to recipe:  **modern-cpp-kafka/2024.07.03**
There are several bugfixes and interface changes in 2024.07.03.
https://github.com/morganstanley/modern-cpp-kafka/compare/v2023.03.07...v2024.07.03
---
=> modern-cpp-kafka: add version 2024.07.03

recipes/rectanglebinpack/all/conandata.yml, recipes/rectanglebinpack/config.yml
Changes to recipe:  **rectanglebinpack/cci.20230923**
New version with fix for newer compilers and Windows build fix.
Just a new version, upstream library has only two new commits (one with added `#include` and other one fixing Windows build, so the patch is no longer needed).
---
=> rectanglebinpack: add cci.20230923

recipes/ginkgo/all/conandata.yml, recipes/ginkgo/all/conanfile.py, recipes/ginkgo/config.yml
Changes to recipe:  **ginkgo/1.8.0**
A new version was released, so this adds the tag to the version list
---
=> ginkgo: add version 1.8.0

recipes/dtl/all/conandata.yml, recipes/dtl/all/conanfile.py, recipes/dtl/config.yml
Changes to recipe:  **dtl/1.21**
There are several improvements in 1.21.
https://github.com/cubicdaiya/dtl/compare/v1.20...v1.21
---
=> dtl: add new version 1.21, remove cci version

recipes/glib/all/conanfile.py
Changes to recipe:  **glib/***
Both libsystemd and eudev use libselinux 3.6.
---
=> glib: Bump libselinux from 3.5 to 3.6 to avoid conflicts

recipes/cmake/binary/conandata.yml, recipes/cmake/config.yml
Changes to recipe:  **cmake/3.30.1**
Make latest 3.30.x version CMake available inside conan eco system.
Add version CMake v3.30.1
---
=> cmake: add version 3.30.1

recipes/luau/all/conandata.yml, recipes/luau/config.yml
Changes to recipe:  **luau/0.635**
There are several bugfixes and improvements since 0.630.
https://github.com/luau-lang/luau/compare/0.630...0.635#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---
=> luau: add version 0.635

recipes/qt/5.x.x/conanfile.py
Changes to recipe:  **qt/5.x**
Cannot build with 'qt/*:gui=False' on macos as `with_fontconfig` is deleted and then subsequently referred to in `configure`:
```
ERROR: qt/5.15.14: Error in configure() method, line 220
del self.options.with_fontconfig
```
Use `rm_safe` when removing options in the `configure` method
---
=> [qt] enable no-gui build on macos

recipes/grpc/all/target_info/grpc_1.50.0.yml, recipes/grpc/all/target_info/grpc_1.50.1.yml, recipes/grpc/all/target_info/grpc_1.54.3.yml, recipes/grpc/all/target_info/grpc_1.65.0.yml
Changes to recipe:  **grpc/[*]**
The `_grpc` component might be used in some recipes (See `google-cloud-cpp`) which breaks when changing the name. For now let's revert it back
https://github.com/conan-io/conan-center-index/pull/24215 refactored the recipe to make it more maintainable, but this breaking change was not considered important as there was no expectation for the explicit usage of the component outside the recipe
Closes https://github.com/conan-io/conan-center-index/issues/24698
---
=> grpc: Revert `grpc` component name to `_grpc`

recipes/dice-template-library/all/conandata.yml, recipes/dice-template-library/config.yml
Changes to recipe:  **dice-template-library/1.6.0**
There are several new features in 1.6.0.
https://github.com/dice-group/dice-template-library/compare/v1.5.0...v1.6.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---
=> dice-template-library: add version 1.6.0

recipes/vvenc/all/conandata.yml, recipes/vvenc/all/conanfile.py, recipes/vvenc/config.yml
Changes to recipe:  **vvenc/0.12.0**
`vvenc/0.12.0` is required by `libheif/1.18.0`. [ref](https://github.com/strukturag/libheif/blob/v1.18.0/CMakeLists.txt#L158)
`vvenc/[>= 0.10.0]` seems to be relaxed C++14 limitation. [ref](https://github.com/fraunhoferhhi/vvenc/pull/321) (Thanks a lot, @uilianries!)
https://github.com/fraunhoferhhi/vvenc/compare/v1.11.1...v1.12.0
---
=> vvenc: add version 0.12.0, relax c++ std version on 0.10.0 and later

recipes/icu/all/conandata.yml, recipes/icu/all/patches/0002-74.2-fix-emscripten.patch
Changes to recipe:  **icu/74.2**
icu/71.1 was recently removed from CCI and it was the only version that had patch for Emscripten.
Patch that adds Emscripten support has been slightly adjusted for 74.2.
---
=> icu: fix build with Emscripten for 74.2

recipes/qt/5.x.x/conanfile.py, recipes/qt/6.x.x/conanfile.py
**qt/5;6.x.x**
Qt5&6 conan recipe exports many xxxxPrivate modules but QuickPrivate was missing.
---
=> Add QuickPrivate module

recipes/qt/5.x.x/conanfile.py, recipes/qt/6.x.x/conanfile.py
Changes to recipe:  **qt/6.7.1**
The Qt project exports more files and variables than CMakeDeps. The variable `__qt_internal_cmake_apple_support_files_path` is consumed to point where `Info.plist.app.in` should be installed.
To validate the current change, I modified the test package to use `qt_add_executable(${PROJECT_NAME} MACOSX_BUNDLE test_package.cpp)`:
```
diff --git a/recipes/qt/6.x.x/test_package/CMakeLists.txt b/recipes/qt/6.x.x/test_package/CMakeLists.txt
index d12764c12f..14825f5ae6 100644
--- a/recipes/qt/6.x.x/test_package/CMakeLists.txt
+++ b/recipes/qt/6.x.x/test_package/CMakeLists.txt
@@ -1,9 +1,12 @@
-cmake_minimum_required(VERSION 3.8)
+cmake_minimum_required(VERSION 3.15)
project(test_package LANGUAGES CXX)
-find_package(Qt6 COMPONENTS Core Network Sql Concurrent Xml …
```
=> [qt6] Add support for MACOSX_BUNDLE

recipes/stb/all/conandata.yml, recipes/stb/all/conanfile.py, recipes/stb/config.yml
Changes to recipe:  **stb/cci.20240531**
cci.20240531 has stb image resize 2.0.7.
https://github.com/nothings/stb/blob/master/stb_image_resize2.h#L331-L334
---
=> stb: add new version cci.20240531, remove old versions

recipes/opengl-registry/all/conandata.yml, recipes/opengl-registry/all/test_package/test_package.c, recipes/opengl-registry/config.yml
Changes to recipe:  **opengl-registry/20240721**
A simple update to the package for an upcoming [Dawn](https://dawn.googlesource.com/dawn/) PR.
I also switched from the `cci.*` version names to the `GL_GLEXT_VERSION` value set in headers: `20240721`.
---
=> opengl-registry: add v20240721

recipes/glslang/all/conanfile.py
Changes to recipe:  **glslang/***
The `glslang-default-resource-limits` component is exported by the project but not the recipe. Required for [Dawn](https://dawn.googlesource.com/dawn/).
Available since https://github.com/KhronosGroup/glslang/commit/f5fa593143e40c6669d14cc4d6fa38cebefabf8d / v1.3.243.0.
---
=> glslang: add missing `glslang-default-resource-limits` component

recipes/c-ares/all/conandata.yml, recipes/c-ares/config.yml
Changes to recipe:  **c-ares/1.32.3**
There are several improvements and bugfixes(including memory leak) in 1.32.3.
https://github.com/c-ares/c-ares/compare/v1.32.2...v1.32.3#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---
=> c-ares: add version 1.32.3

recipes/octo-logger-cpp/all/conandata.yml, recipes/octo-logger-cpp/config.yml
Changes to recipe:  **octo-logger-cpp/2.0.0**
https://github.com/ofiriluz/octo-logger-cpp/compare/v1.12.0...v2.0.0
---
=> octo-logger-cpp: add version 2.0.0

recipes/libftp/all/conandata.yml, recipes/libftp/config.yml
Changes to recipe:  **libftp/1.1.0**
There is a new function in 1.1.0.
https://github.com/deniskovalchuk/libftp/compare/v0.5.1...v1.1.0
---
=> libftp: add version 1.1.0

docs/adding_packages/dependencies.md
Both `zstd` and `ninja` looks pretty stable and should be backward compatible to be used in ConanCenterIndex.
- Zstd: 
- https://abi-laboratory.pro/index.php?view=timeline&l=zstd
- https://github.com/facebook/zstd/issues/731#issuecomment-310264043
Zstd 1.5 is supported since 2023, so keeping 1.5.x is safest, just in case.
- Ninja
- https://ninja-build.org/manual.html#ref_versioning
---
=> [docs] Add zstd and ninja to version ranges supported

recipes/qt/5.x.x/test_package/CMakeLists.txt, recipes/qt/5.x.x/test_v1_package/CMakeLists.txt, recipes/qt/6.x.x/test_package/CMakeLists.txt
Changes to recipe:  **qt**
The WIN32 option was added to CMake add_executable which prevent from initializing stdout and stderr to the app. This results in no console output of the test on Windows.
* fixes e9bdd352111ec5f462347c8fac170307f1a70ffb for qt6
* fixes 1bca4ac9bc95a012f00ca37ffe0c1e8bbffb6a43 for qt5
No CI run needed, tested on Win10
---
=> qt: make "conan test" using the console for stdout

docs/adding_packages/dependencies.md
Changes to recipe:  **xz_utils/[>=5.4.5 <6]**
The `xz_utils` is used by 23 recipes in CCI right now and most of them are consuming the latest version available in Conan Center: `5.4.5`.
The project looks pretty stable and the backward compatibility is checked until the version 2.3.1: https://abi-laboratory.pro/?view=timeline&l=xz
I didn't find any specific evidence in documentation or in the project repository, ensuring about backward support, so I opened an issue questioning about: https://github.com/tukaani-project/xz/issues/132.
Using a grep you can find how many recipes are using `xz_utils`:
find . -name conanfile.py -exec fgrep xz_utils/ {} +
---
=> [docs] Add xz_utils in version ranges

recipes/qt/5.x.x/conanfile.py
Changes to recipe:  qt/5.x.x
* building qtwebengine requires python2 (still), and the current check in the `validate_build()` method does not work since it checks for stdout
* check the python version by passing `-c "import platform;print(platform.python_version())"` instead, which is correctly printed to stdout - avoids other alternative solutions like pipe redirection or calling the underlying process popen
=> qt5: fix check for python2 version

recipes/aws-lambda-cpp/all/conanfile.py, recipes/aws-lambda-cpp/all/test_package/CMakeLists.txt, recipes/aws-lambda-cpp/all/test_package/conanfile.py
Specify library name and version:  **aws-lambda-cpp/***
aws-lambda-cpp provides cmake functions to package lambda runtime binary.
This PR try to provide such a function.
---
=> aws-lambda-cpp: add cmake module for packaging function

recipes/aws-c-sdkutils/all/conandata.yml, recipes/aws-c-sdkutils/all/conanfile.py, recipes/aws-c-sdkutils/config.yml
Specify library name and version:  **aws-c-sdkutils/0.1.13**
Update this dependency because I want to update `aws-crt-cpp` to the latest version. Here are related issues:
- https://github.com/conan-io/conan-center-index/issues/22404
- https://github.com/conan-io/conan-center-index/issues/2275
The version range is based on the submodules used in `aws-crt-cpp`. I wrote a script to collect the version mapping between `aws-c-sdkutils` and `aws-c-common`. In  the following mapping, keys are the versions of `aws-c-sdkutils` and values are the versions of `was-c-common`.
```
{
'v0.1.10': {'v0.8.21'},
'v0.1.11': {'v0.9.3', 'v0.9.0', 'v0.8.23'},
'v0.1.12': {'v0.9.10', 'v0.9.4', 'v0.9.7', 'v0.9.9'},
'v0.1.13': {'v0.9.12', 'v0.9.10'},
'v0.1.7': {'v0.8.12'},
'v0.1.8': {'v0.8.17', 'v0.8.15'}, …
```
=> aws-c-sdkutils: add v0.1.13, use version range for dependencies

recipes/aws-c-auth/all/conandata.yml, recipes/aws-c-auth/all/conanfile.py, recipes/aws-c-auth/config.yml
Specify library name and version:  **aws-c-auth/***
- add version aws-c-auth/0.7.21
- update aws-c-http/0.8.1 
https://github.com/awslabs/aws-c-auth/compare/v0.7.8...v0.7.21
---
=> aws-c-auth: add version 0.7.21

recipes/libcurl/all/conandata.yml, recipes/libcurl/all/test_package/conanfile.py, recipes/libcurl/config.yml
Changes to recipe:  **libcurl/8.9.1**
There are lots of bugfixes in 8.9.1.
https://github.com/curl/curl/compare/curl-8_8_0...curl-8_9_1#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---
=> libcurl: add version 8.9.1

recipes/bitsery/all/conandata.yml, recipes/bitsery/all/conanfile.py, recipes/bitsery/config.yml
Changes to recipe:  **bitsery/5.2.4**
There are minor improvements in 5.2.4, but it is the first release in 1.5 years.
https://github.com/fraillt/bitsery/compare/v5.2.3...v5.2.4
---
=> bitsery: add version 5.2.4

recipes/boost/all/conanfile.py
logic of this value in configure() can't work in conan v2, it raises a ConanException (see https://cpplang.slack.com/archives/C41CWV9HA/p1696374024080289)
If folks want default layout for Windows, they can set layout to versioned instead of this removed b2-layout, so this value was more or less useless.
---
=> boost: remove `b2-default` value of `layout` option

recipes/mongo-c-driver/all/conandata.yml, recipes/mongo-c-driver/config.yml
Changes to recipe:  **mongo-c-driver/1.27.4**
See https://github.com/mongodb/mongo-c-driver/compare/1.27.3...1.27.4 for full set of changes. Includes bug fix in [CDRIVER-5584](https://jira.mongodb.org/browse/CDRIVER-5584).
PR follows pattern from 1.27.3 in: https://github.com/conan-io/conan-center-index/pull/24461.
Fixes #24223
---
=> mongo-c-driver: add version 1.27.4

recipes/grpc/all/conanfile.py
Changes to recipe:  **grpc/all**
fix #24764
Remove download_archive in CMakeLists.txt, otherwise, build fails
---
- [x ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
© 2024 Morgan Stanley.
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE Conan-io project Contributor License Agreement.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, …
=> grpc : remove download_archive in CmakeLists.txt

recipes/imgui/all/conandata.yml, recipes/imgui/config.yml
Changes to recipe:  **imgui/1.91.0**
There are lots of new features in 1.91.0.
https://github.com/ocornut/imgui/compare/v1.90.9...v1.91.0
https://github.com/ocornut/imgui/compare/v1.90.9-docking...v1.91.0-docking
---
=> imgui: add version 1.91.0

recipes/libdivide/all/conandata.yml, recipes/libdivide/config.yml
Changes to recipe:  **libdivide/5.1**
There are several improvements in 5.1.
5.1 fixes compilation error on newer gcc.
https://github.com/ridiculousfish/libdivide/compare/5.0...v5.1
---
=> libdivide: add version 5.1

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Changes to recipe:  **etl/20.39.0**
There are several improvements in 20.39.0.
https://github.com/ETLCPP/etl/compare/20.38.17...20.39.0
---
=> etl: add version 20.39.0, remove older versions

recipes/rdma-core/all/conandata.yml, recipes/rdma-core/all/conanfile.py, recipes/rdma-core/config.yml
Changes to recipe:  **rdma-core/52.0**
#18979 requires `build_librdmacm=True`. Enabled the remaining `build_libmlx5` as well, since it does not add any dependencies or other notable overhead.
https://github.com/linux-rdma/rdma-core/releases/tag/v52.0
---
=> rdma-core: add v52.0, enable all modules

recipes/fast_io/all/conandata.yml, recipes/fast_io/config.yml
Changes to recipe:  **fast_io/cci.20240729**
There are several improvements since cci.20240219.
compare/316afccde333721b059a761b25217084e84a9ca0...44617e9368b64047fabd00cd98b037c1c2fc7fb2
---
=> fast_io: add version cci.20240729

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/config.yml
Changes to recipe:  **daw_header_libraries/2.106.2**
There are several bug fixes in 2.106.2.
https://github.com/beached/header_libraries/compare/v2.106.1...v2.106.2
---
=> daw_header_libraries: add version 2.106.2

recipes/openimageio/all/conandata.yml, recipes/openimageio/all/conanfile.py, recipes/openimageio/all/patches/2.5.14.0-cmake-targets.patch, recipes/openimageio/config.yml
Changes to recipe:  **openimageio/2.5.14.0**
Just updating to todays release with several small fixes.
* Add source for v2.5.14.0
* Add fixed patch for CMake files (Matches the old patch from 2.5.12.0 but needed to be redone due to changes in the underlying files)
* Bumps the requirement for openjpeg to solve a conflict between this recipe & ffmpeg
Changelog: https://github.com/AcademySoftwareFoundation/OpenImageIO/releases/tag/v2.5.14.0
---
=> OpenImageIO: Add version 2.5.14.0

recipes/libinterpolate/all/conandata.yml, recipes/libinterpolate/all/test_package/conanfile.py, recipes/libinterpolate/config.yml
Changes to recipe:  **libinterpolate/2.7**
There are several new features in 2.7.
Sort version numbers.
https://github.com/CD3/libInterpolate/compare/2.6.4...2.7
---
=> libinterpolate: add version 2.7

recipes/libdeflate/all/conandata.yml, recipes/libdeflate/config.yml
Changes to recipe:  **libdeflate/1.21**
There are several fixes for compilation errors on specific environments in 1.21.
https://github.com/ebiggers/libdeflate/compare/v1.20...v1.21
---
=> libdeflate: add version 1.21

recipes/libjxl/all/conandata.yml, recipes/libjxl/all/conanfile.py, recipes/libjxl/config.yml
Changes to recipe:  **libjxl/***
In some environments, there are compilation errors in static build.
It seems to be caused by linking static libgcc and libcstdc++.
This PR tries to fix it.
Compilation error message are following:
```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
CMake Error at cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first): …
```
=> libjxl: disable linking static libgcc and libstdc++

recipes/simfil/all/conandata.yml, recipes/simfil/all/conanfile.py, recipes/simfil/config.yml
Changes to recipe:  **simfil/0.3.1**
The previous conan recipe did not expose the `SIMFIL_WITH_MODEL_JSON` definition to the consumer, which is a bug.
---
=> simfil: Bump 0.3.1 + Fix Recipe

recipes/ohpipeline/all/conandata.yml
Changes to recipe:  **ohpipeline/1.155.1133**
Headers were missing from the previous CMakeFile
---
=> Update CMakeFile for ohPipeline

recipes/simple_enum/all/conandata.yml, recipes/simple_enum/all/conanfile.py, recipes/simple_enum/all/test_package/CMakeLists.txt, recipes/simple_enum/all/test_package/conanfile.py, recipes/simple_enum/all/test_package/test_package.cpp, recipes/simple_enum/config.yml
Changes to recipe:  **simple_enum/0.8.0**
simple_enum is a simple and fast enum utility library.
simple_enum requires C++20.
https://github.com/arturbac/simple_enum
---
=> simple_enum: add recipe

recipes/vulkan-headers/all/conandata.yml, recipes/vulkan-headers/config.yml
Changes to recipe:  **vulkan-headers/1.3.290.0**
Bump version to allow updating `vulkan-loader` to 1.3.290.0
Just simple new sources version bump
---
=> vulkan-headers: bump to 1.3.290.0

.github/workflows/linter-yaml.yml
Fix list of file to apply linter
It seems we apply we're doing linting for config to conandata instead of config file
Changing to the right set of files
---
=> Fix copy/paste mistake in linter-yaml.yml for  'Run linter (config.yml)'

recipes/libyuv/all/conandata.yml, recipes/libyuv/all/conanfile.py, recipes/libyuv/all/patches/1892-0001-check-arm-sve.patch, recipes/libyuv/all/patches/1892-0001-fix-cmake.patch, recipes/libyuv/config.yml
Changes to recipe:  **libyuv/1892**
Libyuv doesn't have a changelog. The main advancements are for ARM support.
- Updates to 1892 (last commit that modified the version: https://chromium.googlesource.com/libyuv/libyuv/+/4cd90347e78ff76755df2107009e900374aee9cd)
- Updates dependencies to the latest version (only patch updates)
- For ARM, it's checked whether `-march=armv9-a+sve2` is supported by the compiler. This seems to fail on M1 macs (M4 devices should support this from what I understand - not sure why this isn't done in GN)
Full diff (from a GH mirror): https://github.com/lemenkov/libyuv/compare/fb6341d326846fbbe669ad5173e520f66b339621...4cd90347e78ff76755df2107009e900374aee9cd
---
=> libyuv: add 1892

recipes/uwebsockets/all/conandata.yml, recipes/uwebsockets/config.yml
Changes to recipe:  **uwebsockets/20.65.0**
There are several improvements in 20.65.0.
https://github.com/uNetworking/uWebSockets/compare/v20.64.0...v20.65.0
---
=> uwebsockets: add version 20.65.0

recipes/tracy/all/conanfile.py
Changes to recipe:  **tracy/***
This recipe has unsupported options introduced in 0.11.0.
This PR tries to add these.
https://github.com/conan-io/conan-center-index/pull/24647#issuecomment-2242493081
- `TRACY_LIBUNWIND_BACKTRACE` has bug which has been solved in upstream.
- Because `TRACY_DEMANGLE` is an experimental options, I think it is not time to add it.
---
=> tracy: add 3 options introduced in 0.11.0

recipes/opencv/4.x/conanfile.py
The OpenCV projects sets the default of this value to true, there is no reason to change this. If anything, not enabling this by default can lead to unexpected fails at runtime which can be hard to debug.
Changes to recipe:  **lib/opencv**
The OpenCV projects sets the default of this value to true, there is no reason to change this.
If anything, not enabling this by default can lead to unexpected fails at runtime which can be hard to debug.
See #24813.
Changing the default value for option `with_imgcodec_pfm` from `False` to `True`.
---
=> Align opencv image codec option default values to upstream defaults

recipes/s2n/all/conandata.yml, recipes/s2n/config.yml
Changes to recipe:  **s2n/***
- There are several improvents in 1.5.0.
- Fix wrong url of 1.4.16(sorry, It's my fault)
https://github.com/aws/s2n-tls/compare/v1.4.16...v1.5.0
---
=> s2n: add version 1.5.0, fix url of 1.4.16

recipes/dataframe/all/conandata.yml
Changes to recipe:  **dataframe/3.2.0**
sha256 is incorrect for version 3.2.0
fixes #24897
```bash
$ wget -q https://github.com/hosseinmoein/DataFrame/archive/refs/tags/3.2.0.tar.gz && sha256sum 3.2.0.tar.gz
44c513ef7956976738c2ca37384a220c5383e95fc363ad933541c6f3eef9d294  3.2.0.tar.gz
```
This causes downstream builds from source to fail
```bash
======== Installing packages ========
dataframe/3.2.0: Sources downloaded from 'conancenter'
dataframe/3.2.0: Calling source() in /home/vscode/.conan2/p/datafac1e21b045434/s/src
ERROR: dataframe/3.2.0: Error in source() method, line 121
get(self, **self.conan_data["sources"][self.version], strip_root=True)
ConanException: sha256 signature failed for '3.2.0.tar.gz' file. 
Provided signature: …
```
=> [fixes #24897] fix bad sha256 for dataframe/3.2.0

recipes/qt/5.x.x/conanfile.py, recipes/qt/6.x.x/conanfile.py
Recipes: qt5 and qt6
- Restore module option defaults  to what they were before https://github.com/conan-io/conan-center-index/pull/23171, that is, set `essential_modules` is False by default in all cases
- Avoid using different option defaults on CI than outside of it - to ensure that users can properly troubleshoot missing binaries with `conan graph explain` (see https://github.com/conan-io/conan/issues/16215)
- Add debug calls and more information - this can help explain which options are enabled and why (conan needs to be invoked with `-vv`)
- Improve handling of errors when options are contradictory:
- Instead of `"ConanException: Incorrect attempt to modify option 'qtmultimedia' from 'False' to 'True'"`
- Now we get: `ERROR: qt/5.15.14: Invalid configuration: Modules …
=> qt refactor option handling and error reporting

recipes/qt/6.x.x/conanfile.py
Changes to recipe:  qt/6
* Fix issue on macOS where building qt fails when `with_vulkan=True` because it does not find the moltenvk headers
* Record direct dependency on vulkan-headers (these are searched _directly_ by Qt, see [here](https://github.com/qt/qtbase/blob/v6.7.1/cmake/FindWrapVulkanHeaders.cmake))
* Record `transitive_headers` for the vulkan-headers when `with_vulkan=True`, these are used here: https://github.com/qt/qtbase/blob/v6.7.1/src/gui/vulkan/qvulkaninstance.h#L19-L21 - if these are not found, including `<QVulkanWindow>` does not properly include the vulkan headers, leading to include errors
* Fix version conflict when `with_vulkan=True` - moltenvk and vulkan have strict version requirements and need to be paired with the right versions
* Fix version conflict
* Fix …
=> Fix locating moltenvk headers when with_vulkan=True

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/config.yml
Changes to recipe:  **daw_header_libraries/2.107.0**
There are a new features in 2.107.0.
https://github.com/beached/header_libraries/compare/v2.106.2...v2.107.0
---
=> daw_header_libraries: add version 2.107.0

docs/adding_packages/dependencies.md
Changes documentation only.
@SpaceIm spotted an incoherence in the documentation, from the PR #24723:
https://github.com/conan-io/conan-center-index/pull/24723/files#r1712973049
The `[^1.0.0]` means minor version compatible, and `[~1.0.0]` patch version compatible only:
More references: 
- https://docs.conan.io/1/versioning/version_ranges.html#version-ranges
- https://jubianchi.github.io/semver-check/#/^3.1.5/3.2
---
=> [docs] Keep only patch version compatible for zstd

recipes/keychain/all/conandata.yml, recipes/keychain/all/conanfile.py, recipes/keychain/config.yml
Changes to recipe:  **keychain**
This recipe had conflicts between its dependencies, causing a graph error exclusively in linux systems.
- Fix dependency conflicts -> bump `glib/2.78.1` -> `glib/2.78.3`
- Linted and little refactor of recipe
---
=> keychain: Fixed dependency conflict between libsecret and glib

recipes/magic_enum/all/conanfile.py, recipes/magic_enum/all/test_package/CMakeLists.txt, recipes/magic_enum/all/test_package/test_package.cpp
Changes to recipe:  **magic_enum/0.9.6**
This MR is intended to fix #24893
This MR is intended to fix #24893
---
=> (#24893) magic_enum/0.9.6: fixes install dir

recipes/hwdata/all/conandata.yml, recipes/hwdata/config.yml
Changes to recipe:  **hwdata/0.385**
The internal database has been updated since 0.382.
https://github.com/vcrhonek/hwdata/compare/v0.382...v0.385
---
=> hwdata: add version 0.385

recipes/pybind11/all/conandata.yml, recipes/pybind11/config.yml
Changes to recipe:  **pybind11/2.13.2**
There are a new features and several improvements in 2.13.2.
https://github.com/pybind/pybind11/compare/v2.13.1...v2.13.2
---
=> pybind11: add version 2.13.2

recipes/opentelemetry-cpp/all/conanfile.py
Changes to recipe:  **opentelemetry-cpp/[<1.10]**
The recipe for old versions had conflcits on its own graph, fixed those by bumping the boost version. Not done so for the thrift one as that's also used by arrow
=> opentelemetry-cpp: Bump boost to fix old opentelemetry-cpp versions

recipes/mold/all/conandata.yml, recipes/mold/all/conanfile.py, recipes/mold/config.yml
Changes to recipe:  **mold/2.33.0**
There are new features in 2.33.0.
https://github.com/rui314/mold/compare/v2.32.1...v2.33.0
---
=> mold: add new version 2.33.0

recipes/fast-dds/all/conandata.yml, recipes/fast-dds/config.yml
Changes to recipe:  **fast-dds/2.14.3**
The point releases since v2.14.0 contain several improvements and fixes. Among other things, eProsima/Fast-DDS#4565 has been resolved, which makes one of the applied patches no longer necessary.
https://github.com/eProsima/Fast-DDS/compare/v2.14.0..v2.14.3
- eProsima/Fast-DDS#4753
- https://github.com/eProsima/Fast-DDS/releases/tag/v2.14.1
- https://github.com/eProsima/Fast-DDS/releases/tag/v2.14.2
- https://github.com/eProsima/Fast-DDS/releases/tag/v2.14.3
---
=> fast-dds: add version 2.14.3

recipes/thrift/all/conanfile.py
Changes to recipe:  **thrift**
The NOMINMAX macro is leaking from thrift and can easily break code that is relying on min/max from windows.h (including user code and code from the Windows SDK). As the lowest version of thrift that is supposed to need the macro is not supported anymore, this should be removed
Since thrift/0.12.0 NOMINMAX is not a requirement anymore ([THRIFT-4680](https://github.com/apache/thrift/commit/9b75e4fe745a9b08e6ccdc0998ec7a69272f5b4c)) 
Remove NOMINMAX define as 0.14.1 is the lowest version supported
---
=> thrift: Remove NOMINMAX definition

recipes/libsystemd/all/conandata.yml, recipes/libsystemd/config.yml
Changes to recipe:  **libsystemd/255.10**
Fixes https://github.com/conan-io/conan-center-index/issues/24889.
I tested the recipe locally on Fedora 40 (kernel 6.9.12-200.fc40.x86_64).
---
=> libsystemd: add v255.10

recipes/fast-cdr/all/conandata.yml, recipes/fast-cdr/config.yml
Add point release to recipe:  **fast-cdr/2.2.3**
The point release contains mostly changes to workflow and documentation, but also fixes a compile warning in the tests.
https://github.com/eProsima/Fast-CDR/pull/207
https://github.com/eProsima/Fast-CDR/compare/v2.2.0...v2.2.3
---
=> fast-cdr: add version 2.2.3

recipes/catch2/3.x.x/conandata.yml, recipes/catch2/config.yml
Changes to recipe:  **catch2/3.7.0**
There are several improvements in 3.7.0.
https://github.com/catchorg/Catch2/compare/v3.6.0...v3.7.0
---
=> catch2: add version 3.7.0

recipes/mini/all/conandata.yml, recipes/mini/config.yml
Changes to recipe:  **mini/0.9.16**
mini/0.9.15 has serial bug, mini/0.9.16 fix it.
https://github.com/metayeti/mINI/compare/0.9.15...0.9.16
---
=> mini: add version 0.9.16

recipes/pybind11/all/conandata.yml, recipes/pybind11/config.yml
Changes to recipe:  **pybind11/2.13.4**
There are several bugfixes since 2.13.2.
https://github.com/pybind/pybind11/compare/v2.13.2...v2.13.4
---
=> pybind11: add version 2.13.4

recipes/cpp-httplib/all/conandata.yml, recipes/cpp-httplib/all/conanfile.py, recipes/cpp-httplib/all/test_package/conanfile.py, recipes/cpp-httplib/config.yml
There are several improvements in 0.16.3
https://github.com/yhirose/cpp-httplib/compare/v0.16.0...v0.16.3
---
=> cpp-httplib: add version 0.16.3, remove older versions

recipes/etl/all/conandata.yml, recipes/etl/config.yml
Changes to recipe:  **etl/***
There are several new features in 20.39.3.
Removed 20.39.0 because it has been removed.
https://github.com/ETLCPP/etl/compare/20.38.17...20.39.3
---
=> etl: add version 20.39.3, remove version 20.39.0

recipes/tree-gen/all/conandata.yml, recipes/tree-gen/all/conanfile.py, recipes/tree-gen/config.yml
Changes to recipe:  **tree-gen/1.0.8**
Just an update of dependencies.
I have other 2 projects, `qx-simulator` that uses `libqasm` Conan package, and `libqasm` that uses `tree-gen` Conan package.
I wanted to use `fmt/11.0.2` in `qx-simulator`, but that causes a conflict with `fmt/10.2.1` in `libqasm` and `tree-gen`.
So I'm updating first `tree-gen` and then `libqasm` to `fmt/11.0.2`.
And I also take the opportunity to update `gtest` to 1.15.0.
`config.yml` and `conandata.yml` point to the newly created `tree-gen/1.0.8`.
`conanfile.py` updates gtest conan package to 1.15.0 and fmt to 11.0.2.
---
=> tree-gen: add version 1.0.8

recipes/dice-template-library/all/conandata.yml, recipes/dice-template-library/config.yml
Changes to recipe:  **dice-template-library/1.8.0**
There are several new features since 1.6.0.
https://github.com/dice-group/dice-template-library/compare/v1.6.0...v1.8.0
---
=> dice-template-library: add version 1.8.0

recipes/jsoncons/all/conandata.yml, recipes/jsoncons/config.yml
Changes to recipe:  **jsoncons/0.177.0**
There are several improvements in 0.177.0.
https://github.com/danielaparker/jsoncons/compare/v0.176.0...v0.177.0
---
=> jsoncons: add version 0.177.0

recipes/libheif/all/conandata.yml, recipes/libheif/config.yml
Changes to recipe:  **libheif/0.18.2**
There are several bugfixes in 1.18.2.
https://github.com/strukturag/libheif/compare/v1.18.1...v1.18.2
---
=> libheif: add version 0.18.2

recipes/meson/all/conanfile.py
Changes to recipe:  meson
Use version range for ninja (in particular as it is difficult to override versions for transitive dependencies of tool requirements)
=> meson: use version range for ninja

recipes/ninja/all/conanfile.py
Changes to recipe:  ninja (all versions)
Ninja tries to locate the `re2c` executable, which is useful when the `.in` files are being changed - to have cmake re-render certain files. These .in files are not changed by us and we can use the already generated files directly. This fixes issues when building older versions of ninja on systems where `re2c` is found but does not behave as expected.
From https://cpplang.slack.com/archives/C41CWV9HA/p1723843030327379
```
Question: the meson conan package seems to require ninja through a call to self.requires() but the ninja package is showing up as a "build requirement" in the output of conan install. I am trying to override the version of ninja being used by this version of meson but seem unsuccessful in my attempts. I have tried specifying the …
```
=> ninja: prevent locating and using re2c executable during build

recipes/magic_enum/all/conandata.yml
Changes to recipe:  **magic_enum/0.9.6**
Trying to conan install the latest magic_enum version would fail with message
`ERROR: magic_enum/0.9.6: Error in source() method, line 57 get(self, **self.conan_data["sources"][self.version], strip_root=True) ConanException: sha256 signature failed for 'v0.9.6.tar.gz' file.  Provided signature: 814791ff32218dc869845af7eb89f898ebbcfa18e8d81aa4d682d18961e13731   Computed signature: fcda8295256a2084f1f98a63b3d2c66b3d7140eea008e1ef94ea015b2f6d3034`
Magic_enum updated its 0.9.6 package recently, breaking the package (https://github.com/Neargye/magic_enum/releases/tag/v0.9.6)
Updated the signature for 0.9.6 magic_enum package
---
=> Magic_enum/0.9.6: Update signature

recipes/tensorflow-lite/all/conandata.yml, recipes/tensorflow-lite/all/conanfile.py, recipes/tensorflow-lite/all/patches/2.15.0-0001-disable-fetch-content.patch, recipes/tensorflow-lite/all/patches/2.15.0-0002-windows-mmap.patch, recipes/tensorflow-lite/all/patches/2.15.0-0003-use-cci-dependencies.patch, recipes/tensorflow-lite/config.yml
Specify library name and version:  **tensorflow-lite/v2.15.0**
Add 2.15.0 and update a few dependencies which were causing crashes when running on M1 macs under rosetta. Also, remove 2.12.0, which was just a copy of 2.10.0.
Depends on #21762, #21761, #21760 and #21759, which should be merged before this.
---
=> tensorflow-lite: Add v2.15.0

recipes/battery-embed/all/test_package/CMakeLists.txt
Changes to recipe:  **battery-embed/1.2.19**
The test contains a wrong line, I oversaw it while reviewing the PR for adding the package.
To ensure correct testing and the quality of the package, the line should be removed.
The removed line linked to the battery::embed library. However, this should not happen in user code because the function b_embed() already does it automatically, just like it does it for include paths. This is needed, because it is linked on-demand, and only if necessary.
This does not change any functionality.
Since everything already worked before, all test runners should succeed like before.
---
=> battery-embed: Remove link to battery::embed in test package

recipes/opencv/4.x/conanfile.py
Changes to recipe:  **opencv/4.x**
After PR #24814 OpenCV could no longer be built for iOS as described in [this comment](https://github.com/conan-io/conan-center-index/pull/24814#issuecomment-2302132602).
The option `with_jpeg2000` must not be accessed without `get_safe` or a guard that checks `_has_with_jpeg2000_option`. This PR fixes the regression w/o changing other functionality by safely accessing the `with_jpeg2000` option.
---
=> opencv/4.x: fix building for iOS

recipes/compute_library/all/conandata.yml, recipes/compute_library/all/conanfile.py, recipes/compute_library/all/test_package/CMakeLists.txt, recipes/compute_library/all/test_package/conanfile.py, recipes/compute_library/all/test_package/test_package.cpp, recipes/compute_library/config.yml
Specify library name and version:  **compute_library/23.08**
That's a requirement for #19681 (OpenVino)
The ComputeLibrary has experimental CMake support, but it's restricted to a single linux profile, so it does not work with Mac. The official documentation uses SCons: https://github.com/ARM-software/ComputeLibrary
- The fPIC options is missing because is hardcoded in Scons script, so it would require a patch.
- It's not possible to avoid building all tests, but we don't install them at least
- The steps build and install are executed together, because install is a sub-step of build major step. We can not change without a patch, so we copy/clean during package() method
- It builds both static and shared at same build, there is no option to control it.
---
=> [ComputeLibrary] Add new package for ARM-software/ComputeLibrary

recipes/geographiclib/all/conandata.yml, recipes/geographiclib/all/conanfile.py, recipes/geographiclib/config.yml
Changes to recipe:  **geographiclib/2.4**
Adds the latest `geographiclib` version.
https://github.com/geographiclib/geographiclib/compare/v2.3...v2.4
The minimum C++ and CMake versions were increased in this release.
---
=> geographiclib: add v2.4

recipes/tensorflow-lite/all/conandata.yml, recipes/tensorflow-lite/all/patches/2.10.0-0004-use-add-stdint-for-int-types.patch, recipes/tensorflow-lite/all/patches/2.12.0-0004-use-add-stdint-for-int-types.patch
Changes to recipe:  **tensorflow-lite/[< 2.15.0]**
Compilation fails due to missing `<stdint>` header when using GCC-13.
Fix: https://github.com/conan-io/conan-center-index/issues/24538
Bugfix source: https://github.com/tensorflow/tensorflow/pull/60299
Profile host/build:
```ini
[settings]
arch=x86_64
compiler=gcc
compiler.cppstd=gnu17
compiler.version=13
os=Linux
[conf]
tools.build:compiler_executables={"c": "gcc-13", "cpp": "g++-13"}
```
Error log:
```bash
[ 21%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/internal/spectrogram.cc.o
[ 21%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/internal/tensor_utils.cc.o
/root/.conan2/p/b/tensoe72a22e4ba1f5/b/src/tensorflow/lite/kernels/internal/spectrogram.cc:46:22: error: …
```
=> [bugfix] tensorflow-lite and gcc-13

recipes/sqlcipher/all/conandata.yml, recipes/sqlcipher/all/patches/Makefile.in-v4.6.1.patch, recipes/sqlcipher/all/patches/Makefile.msc-v4.6.1.patch, recipes/sqlcipher/config.yml
Changes to recipe:  **sqlcipher/4.6.1**
There are several improvements in 4.6.1.
https://github.com/sqlcipher/sqlcipher/compare/v4.6.0...v4.6.1
---
=> sqlcipher: add version 4.6.1

recipes/assimp/5.x/conandata.yml, recipes/assimp/config.yml
Changes to recipe:  **assimp/5.4.2**
Adds many minor fixes.
https://github.com/assimp/assimp/releases/tag/v5.4.2
https://github.com/assimp/assimp/compare/v5.4.1...v5.4.2
Also hopefully fixes the missing binary issue in #24669.
No changes to the build system that would affect the recipe in this release.
---
=> assimp: add v5.4.2

recipes/boost-ext-ut/all/conandata.yml, recipes/boost-ext-ut/all/conanfile.py, recipes/boost-ext-ut/config.yml
Add  **boost-ext-ut/2.1.0**.
To have the latest version of `boost-ext-ut` available.
https://github.com/boost-ext/ut/compare/v2.0.1...v2.1.0
---
=> boost-ext-ut: Add version 2.1.0

recipes/itlib/all/conandata.yml, recipes/itlib/config.yml
Changes to recipe:  **itlib/1.11.2**
The ocmpilation errors on MinGW are fixes in 1.11.2.
https://github.com/iboB/itlib/compare/v1.11.1...v1.11.2
---
=> itlib: add version 1.11.2

recipes/luau/all/conandata.yml, recipes/luau/config.yml
Changes to recipe:  **luau/0.640**
There are several improvements since 0.635.
https://github.com/luau-lang/luau/compare/0.635...0.640
---
=> luau: add version 0.640

recipes/pybind11/all/conandata.yml, recipes/pybind11/config.yml
Changes to recipe:  **pybind11/2.13.5**
There are several improvements in 2.13.4.
https://github.com/pybind/pybind11/compare/v2.13.4...v2.13.5
---
=> pybind11: add version 2.13.5

recipes/gstreamer/all/conandata.yml, recipes/gstreamer/all/conanfile.py, recipes/gstreamer/config.yml
Changes to recipe:  **gstreamer/1.24.7**
Adds the latest version of GStreamer.
Would like to make progress with the Conan 2.x migration GStreamer and its related packages.
I compared the pkgconfig output of the latest version and previous ones and identified some minor changes. Updated the recipe accordingly.
The `gio-unix-2.0` dependency was added in https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/b004464ac6c9e9a59ebf51139a835dd1fac33201?page=4#5ef7fd2d4f67cb80c17ceb3e596e5f75bdd35838
---
=> gstreamer: add v1.24.7, drop old versions

recipes/qt/6.x.x/conanfile.py
Changes to recipe:  **qt/6.x.x**
Fixes: https://github.com/conan-io/conan-center-index/issues/24988
OS: macOS
Qt will use vulkan-headers from the system (if installed) even passing `with_vulkan=False`. 
Without the fix and vulkan-headers installed in your system:
```bash
-DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
CMake Error at qtbase/cmake/FindWrapVulkanHeaders.cmake:34 (find_package):
By not providing "Findmoltenvk.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "moltenvk",
but CMake did not find one.
Could not find a package configuration file provided by "moltenvk" with any
of the following names:
moltenvkConfig.cmake
moltenvk-config.cmake
Add the installation prefix of "moltenvk" to CMAKE_PREFIX_PATH or set
"moltenvk_DIR" to a …
```
=> qt: Fixed Qt uses vulkan-headers from system

recipes/boost/all/conandata.yml, recipes/boost/all/conanfile.py, recipes/boost/all/dependencies/dependencies-1.86.0.yml, recipes/boost/config.yml
Changes to recipe:  **boost/1.86.0**
New Boost version 1.86.0 has been released and there is a related PR: #25030
The version 1.86.0 brings updates related to required C++ standard. However, most of those components are not exposed as an option.
https://www.boost.org/users/history/version_1_86_0.html
- No new libraries.
- Boost CRC requires C++11
- Boost Format requires C++11
- Boost Graph requires C++14. This one has an option.
- Boost UUID requires C++11
- Boost Heap requires C++14
- Boost Lockfree requires C++14
closes #25030
---
=> [boost] Add version 1.86.0

recipes/dice-template-library/all/conandata.yml, recipes/dice-template-library/config.yml
Changes to recipe:  **dice-template-library/1.9.0**
There is a new features in 1.9.0.
https://github.com/dice-group/dice-template-library/compare/v1.8.0...v1.9.0
---
=> dice-template-library: add version 1.9.0

recipes/onnx/all/conanfile.py
onnxruntime forces this to be True for building: https://github.com/microsoft/onnxruntime/blob/be76e1e1b8e2914e448d12a0cc683c00014c0490/cmake/external/onnxruntime_external_deps.cmake#L542
The problem is that we can't do this right now in Conan Center Index for the onnxruntime recipe:
```
def configure(self):
if self.options.shared:
self.options.rm_safe("fPIC")
self.options["onnx"].disable_static_registration = True
```
Because we would get missing binaries, and if we raise Invalid Configuration then we won't actually build onnxruntime.
As the only recipe that uses onnx y Conan Center Index is onnxruntime and for that case we need to set this. I think it's better to change the default for the upstream and use `True` for this option.
Also related with: …
=> Change default disable_static_registration to True for onnx

recipes/openjdk/all/conanfile.py
Small change to modify the Openjdk policy
This is done until we can clarify the licensing status for redistributing openjdk binaries from a Conan package.
These changes make it so no binaries are ever hosted by Conan, and just get compiled (Or in this case, the precompiled binaries provided by upstream are downloaded) in the local machines of users when the package is used
=> Change openjdk policy

recipes/daw_header_libraries/all/conandata.yml, recipes/daw_header_libraries/all/test_package/CMakeLists.txt, recipes/daw_header_libraries/all/test_package/test_package.cpp, recipes/daw_header_libraries/all/test_package/test_package_old.cpp, recipes/daw_header_libraries/config.yml
Changes to recipe:  **daw_header_libraries/2.110.0**
In 2.110.0, there are lots of breaking changes.
https://github.com/beached/header_libraries/compare/v2.107.0...v2.110.0
---
=> daw_header_libraries: add version 2.110.0

recipes/bzip2/all/conanfile.py
Changes to recipe:  **bzip2**
When preparing for creating an SBoM from conan dependencies, I encountered an issue with bzip2 as _bzip2-1.0.8_ is not a valid license identifier. According to [the documentation](https://github.com/conan-io/conan-center-index/blob/167e8aa5fdf01bb633eae29e6848f42105c1a409/docs/adding_packages/conanfile_attributes.md?plain=1#L50-L58), the _license_ attribute is supposed to be a SPDX-compliant license identifier (or if not available shall start with `LicenseRef-` as a prefix).
According to https://github.com/spdx/license-list-XML/issues/1223 and https://github.com/spdx/license-list-XML/issues/2271, the _bzip-1.0.6_ license was introduced due to some optional paragraphs that were apparently found in some versions of previous bzip2 licenses. Subsequent versions …
=> bzip2: use SPDX-compliant license identifier

recipes/mlpack/all/conandata.yml, recipes/mlpack/all/conanfile.py, recipes/mlpack/all/test_package/CMakeLists.txt, recipes/mlpack/config.yml
Changes to recipe:  **mlpack/4.4.0**
Closes https://github.com/conan-io/conan-center-index/issues/25064
Currently facing some issues in apple-clang:
<details>
```
$ conan create . --version=4.4.0 -b=missing -c="tools.build:verbosity=verbose" -c="tools.compilation:verbosity=verbose"
ERROR: Error loading custom command audit.cmd_catalog: No module named 'rich'
mlpack/4.4.0: Exporting package recipe: /Users/abril/coding/conan-center-index/recipes/mlpack/all/conanfile.py
mlpack/4.4.0: exports: File 'conandata.yml' found. Exporting it...
mlpack/4.4.0: Copied 1 '.py' file: conanfile.py
mlpack/4.4.0: Copied 1 '.yml' file: conandata.yml
mlpack/4.4.0: Exported to cache folder: /Users/abril/.conan2/p/mlpac1e5b78f2be1e7/e
mlpack/4.4.0: Exported: …
```
=> mlpack: Add new 4.4.0 version

recipes/xerces-c/all/conandata.yml, recipes/xerces-c/all/conanfile.py
Changes to recipe:  **xerces-c**
As explained in #24796, when compiling this package with `clang-cl` in Windows, it will through an error which is easily fixable defining `CMAKE_RC_FLAGS` variable.
Close #24796
---
=> xerces-c: Fix clang compilation issue on Windows

recipes/jwt-cpp/all/conanfile.py
Changes to recipe:  **jwt-cpp/0.7.0**
Fix #25070
Fix missing picojson header by using Conan picojson for all versions.
---
© 2024 Morgan Stanley.
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE Conan-io project Contributor License Agreement.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS …
=> (#25070) jwt-cpp: Fix missing picojson header

recipes/arrow/all/conanfile.py
Changes to recipe:  **arrow**
arrow links to `aws-cpp-sdk-identity-management` in addition to `aws-cpp-sdk-s3` when `with_s3` is enabled.
See https://github.com/apache/arrow/blob/6b268f62a8a172249ef35f093009c740c32e1f36/cpp/src/arrow/CMakeLists.txt#L98
---
=> arrow: fix missing dependency when with_s3 is enabled

recipes/luajit/all/conandata.yml, recipes/luajit/all/conanfile.py, recipes/luajit/config.yml
Changes to recipe:  **luajit/2.1.0-beta3**
The issue #25032 brought a case where the upstream dropped the download of tags for tarball files, and recommended to use their rolling release approach instead.
After speaking to the Conan team, we considered doing separated moves, first, fixing the broken recipe to use the backup sources. The current state is not only affecting CCI, but also breaks those packages listed in the issue. So we decided to make available old releases in ConanCenterIndex for now.
In a future moment, we should discuss another move to deal with rolling releases in Lua-JIT.
fixes #25032
/cc @uyha
Using backup sources is not something new in CCI. The same usage can be found in:
- #24290
- #23329
- #18082
It does not changed sources, they are the backup from the original …
=> [luajit] Use Conan Center Backup Sources for sources

recipes/sdl_mixer/all/CMakeLists.txt, recipes/sdl_mixer/all/conanfile.py, recipes/sdl_mixer/all/test_package/CMakeLists.txt, recipes/sdl_mixer/all/test_package/conanfile.py, recipes/sdl_mixer/all/test_v1_package/CMakeLists.txt, recipes/sdl_mixer/all/test_v1_package/conanfile.py
Linking in test_package currently fails for GCC due to #12826.
=> sdl_mixer/all: migrate to Conan v2

recipes/chipmunk2d/all/conandata.yml, recipes/chipmunk2d/all/conanfile.py, recipes/chipmunk2d/all/patches/0001-remove-sysctl-linux-win.patch
Changes to recipe:  chipmunk2d/7.0.3
Apply a small patch to exclude `sysctl.h` on Linux/Win (i.e. only include on Mac).
As per issue #16735 - sysctl has been removed from glib (see <https://sourceware.org/pipermail/libc-announce/2020/000029.html>) thus chipmunk2d no longer builds on (most) Linux toolchains. The development version of chipmunk was updated 5 years ago to address this (see https://github.com/slembcke/Chipmunk2D/commit/9a051e6fb970c7afe09ce2d564c163b81df050a8), however this was after the 7.0.3 release, and there have been no further releases as at 08/2024.
The commit indicated above adds pre-processing directives to exclude `sysctl.h` on Linux/Win; the recipe now applies this as a patch for version 7.0.3.
NOTE: My contributor access request is pending.
=> Fix #16735 and remove sysctl.h from chipmunk/7.0.3

recipes/cutlass/all/conandata.yml, recipes/cutlass/all/conanfile.py, recipes/cutlass/all/test_package/CMakeLists.txt, recipes/cutlass/all/test_package/conanfile.py, recipes/cutlass/all/test_package/test_package.cpp, recipes/cutlass/config.yml
Changes to recipe:  **cutlass/3.5.0**
CUTLASS is a collection of CUDA C++ template abstractions for implementing high-performance matrix-matrix multiplication (GEMM) and related computations at all levels and scales within CUDA.
Required for FBGEMM (#24749) and libtorch (#24759) when building with CUDA enabled.
https://github.com/NVIDIA/cutlass
It's mostly a CUDA library, but can be installed as header-only, which avoids a build-time dependency on CUDA.
`header_only=False` option could be added to build and package library binaries as well, but I think it's better to review and merge the minimal header-only version first.
---
=> cutlass: new recipe

recipes/grpc/all/conanfile.py
Changes to recipe:  grpc/all
Fix regression when grpc and abseil are shared - abseil link requirements should be propagated, as generated code will depend on symbols in abseil libraries.
Fix https://github.com/conan-io/conan-center-index/issues/24806
Close https://github.com/conan-io/conan/issues/16911
=> grpc: fix transitive_libs grpc regression

recipes/libqasm/all/conandata.yml, recipes/libqasm/all/conanfile.py, recipes/libqasm/config.yml
Changes to recipe:  **libqasm/0.6.7**
Just an  update of dependencies.
config.yml and conandata.yml point to the newly created libqasm/0.6.7.
conanfile.py updates fmt conan package version to 11.0.2, gtest to 1.15.0, and tree-gen to 1.0.8.
---
=> libqasm: add version 0.6.7

recipes/swig/all/conandata.yml, recipes/swig/all/conanfile.py, recipes/swig/all/patches/0001-4.2.1-swig-linux-library-path.patch, recipes/swig/all/patches/0002-4.2.1-do-not-define-SWIG_LIB_WIN_UNIX.patch, recipes/swig/config.yml
Changes to recipe:  **swig/4.2.1**
fixes #24842 
adding swig 4.2.1 for support of the python stable abi and further bug fixing
Added the missing version 
updated the patches and added bison as required build tool
---
=> swig: add version 4.2.1

recipes/wiringpi/all/conandata.yml, recipes/wiringpi/config.yml
Changes to recipe:  **wiringpi/3.8**
There are several improvements in 3.8. (3.7 is not released.)
https://github.com/WiringPi/WiringPi/compare/3.6...3.8
---
=> wiringpi: add version 3.8

recipes/premake/5.x/conanfile.py, recipes/premake/5.x/test_package/conanfile.py
Changes to recipe:  **premake/alpha-15**
So far, Conan 1.x is still mandatory for recipes that are present in ConanCenterIndex since before Conan 2.x migration. 
The premake failed previously, but I can not reproduce that same error by running it in an equal docker container.
Using the Docker image `conanio/clang13-ubuntu16.04:1.65.0`, I see no errors when building in Debug mode:
[premake-alpha15-clang13-debug.log](https://github.com/user-attachments/files/16862706/premake-alpha15-clang13-debug.log)
---
=> [premake] Build with Conan 1.x again

recipes/fast_float/all/conandata.yml, recipes/fast_float/config.yml
Changes to recipe:  **fast_float/6.1.5**
There are several improvements in 6.1.5.
https://github.com/fastfloat/fast_float/compare/v6.1.4...v6.1.5
---
=> fast_float: add version 6.1.5

recipes/systemc/all/conanfile.py
Changes to recipe:  **systemc/2.3.4**
Similar to #25131. The Systemc failed in the past, but looks working now.
Locally, is working using the docker image `conanio/gcc5:1.65.0`
[systemc-2.3.3-gcc5-shared.log](https://github.com/user-attachments/files/16868488/systemc-2.3.3-gcc5-shared.log)
---
=> [systemc] Re-enable Conan 1.x build

recipes/eigen/all/conandata.yml, recipes/eigen/config.yml
Changes to recipe:  **eigen/all**
Add a cci specific version in order to be able to build #25039
The 3.4.0 version is 3 years old but unfortunately, there are no tags with all the fixes needed yet. 
https://gitlab.com/libeigen/eigen/-/compare/3.4.0...9df21dc8b4b576a7aa5c0094daa8d7e8b8be60f0?from_project_id=15462818&straight=false
---
=> eigen: add version cci. 20240315 (pre 3.4.1)

recipes/librdkafka/all/conandata.yml, recipes/librdkafka/config.yml
Changes to recipe:  **librdkafka/2.5.3**
2.5.3 fixes the regression which has been introduced in 2.5.0.
https://github.com/confluentinc/librdkafka/releases/tag/v2.5.0
https://github.com/confluentinc/librdkafka/compare/v2.5.0...v2.5.3
---
=> librdkafka: add version 2.5.3

recipes/mongo-c-driver/all/conandata.yml, recipes/mongo-c-driver/config.yml
Changes to recipe:  **mongo-c-driver/1.27.6**
See https://github.com/mongodb/mongo-c-driver/compare/1.27.5...1.27.6 for full set of changes. Includes bug fixes to large string handling in libbson and a TSan fix in libmongoc.
PR follows pattern from 1.27.5 in: https://github.com/conan-io/conan-center-index/pull/24853.
Fixes #25123
---
=> mongo-c-driver: add version 1.27.6

recipes/hwloc/all/conandata.yml, recipes/hwloc/config.yml
Changes to recipe:  **hwloc/2.11.1**
The latest release for hwloc. Might want to upgrade OpenMPI v5 to it in #25162.
Release notes: https://www.mail-archive.com/hwloc-announce@lists.open-mpi.org/msg00166.html
---
=> hwloc: add v2.11.1

recipes/gobject-introspection/all/conandata.yml, recipes/gobject-introspection/config.yml
Changes to recipe:  **gobject-introspection/2.78.1**
To target a newer gobject-introspection version in the updated GTK (#25090) and related recipes (such as harfbuzz #25093).
There is a newer v2.80 release available, but it involves a more substantial change to the Python runtime dependencies.
Limiting this one to a simple version bump.
---
=> gobject-introspection: add v2.78.1

recipes/expat/all/conandata.yml, recipes/expat/config.yml
Three CVEs have been fixed in this version according to the ChangeLog https://github.com/libexpat/libexpat/blob/R_2_6_3/expat/Changes
Changes to recipe:  **expat/2.6.3**
CVE mitigation
---
=> [expxat] Add expat version 2.6.3

recipes/s2n/all/conandata.yml, recipes/s2n/config.yml
Changes to recipe:  **s2n/1.5.2**
There are several bugfixes in 1.5.2.
https://github.com/aws/s2n-tls/compare/v1.5.1...v1.5.2
---
=> s2n: add version 1.5.2

recipes/sentry-native/all/conandata.yml, recipes/sentry-native/all/conanfile.py, recipes/sentry-native/config.yml
Add version : **sentry-native/0.7.7**
---
=> [sentry-native] Add 0.7.8

recipes/mbedtls/all/conandata.yml, recipes/mbedtls/all/conanfile.py, recipes/mbedtls/config.yml
Changes to recipe:  **mbedtls/3.6.1**
There are security bugfixes in 3.6.1.
https://github.com/Mbed-TLS/mbedtls/compare/v3.6.0...mbedtls-3.6.1
---
=> mbedtls: add version 3.6.1

recipes/libcap/all/conandata.yml, recipes/libcap/config.yml
Changes to recipe:  **libcap/2.70**
A new version of libcap is available. It contains only a few cosmetic changes in pam_cap. 
---
=> libcap/2.70: Bump version

recipes/bdwgc/all/conandata.yml, recipes/bdwgc/config.yml
Changes to recipe:  **gc/8.2.8**
It's an update to the latest stable upstream release of bdwgc package.
I'm upstream maintainer of this library.
Full list of changes - https://github.com/ivmai/bdwgc/releases/tag/v8.2.8
---
=> Add gc/8.2.8 recipe

.c3i/config_v1.yml, .c3i/config_v2.yml
Update Conan client used in ConanCentexIndexCI to the versions 2.7.1 and 1.65.0
=> [config] Update Conan client version to 2.7.1 and 1.65.0

recipes/at-spi2-core/config.yml, recipes/at-spi2-core/new/conandata.yml, recipes/at-spi2-core/new/conanfile.py
Changes to recipe:  **at-spi2-core/[*]**
The necessary X11 components are currently not listed at all in `cpp_info`.
The X11 support is needed by the X11 GTK backend in #25090.
Adds the latest release for the GTK PR.
Changes since 2.51.0: https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/AT_SPI2_CORE_2_53_1/NEWS?ref_type=tags#L1-59
`with_x11` should be enabled by default to build the X11 backend by default for GTK on CCI. `xorg/system` is almost guaranteed to be installed by another dependency anyway (such as `opengl`) so leaving it disabled does not have much benefit.
---
=> at-spi2-core: add v2.53.1, fix X11 support and enable by default

recipes/wiringpi/all/conandata.yml, recipes/wiringpi/config.yml
Changes to recipe:  **wiringpi/3.10**
There are several improvements in 3.10. (3.9 is not released.)
https://github.com/WiringPi/WiringPi/compare/3.8...3.10
---
=> wiringpi: add version 3.10

recipes/libarchive/all/conanfile.py
Use version range for xz_utils & zstd dependencies since it's now allowed, and bump some other deps in the meantime.
While bumping versions, I've realized that pcre2 was duplicated in requirements: with_pcreposix actually requires pcre, not pcre2 (and with_pcre2 requires pcre2), so it's fixed in the meantime.
Proof that `with_pcreposix` (which maps to `ENABLE_PCREPOSIX` CMake option of upstream CMakeLists) requires pcre, not pcre2:
https://github.com/libarchive/libarchive/blob/853bf656ef6d294a4fedc9afc74b262c3c0a6501/CMakeLists.txt#L1306-L1307
https://github.com/libarchive/libarchive/blob/853bf656ef6d294a4fedc9afc74b262c3c0a6501/build/cmake/FindPCREPOSIX.cmake
---
=> libarchive: bump deps & use version range for xz_utils & zstd + use correct dependency for with_pcreposix option

recipes/libdwarf/all/conandata.yml, recipes/libdwarf/all/patches/0.10.1-0001-fixes.patch, recipes/libdwarf/all/patches/0.9.2-0001-fixes.patch, recipes/libdwarf/config.yml
Changes to recipe:  **libdwarf/0.9.2, 0.10.1, 0.11.0**
This PR adds three versions of libdwarf, skipping 0.10.0 as it was defective.
---
=> libdwarf: Add versions 0.9.2 to 0.11.0

recipes/itk/all/conandata.yml, recipes/itk/all/conanfile.py, recipes/itk/all/patches/0002-find-conan-packages.patch, recipes/itk/config.yml
Opening in favour of https://github.com/conan-io/conan-center-index/pull/23039
---
=> Add ITK 5.3.0

recipes/pybind11/all/conandata.yml, recipes/pybind11/config.yml
Changes to recipe:  **pybind11/2.13.6**
There are several new features in 2.13.6.
https://github.com/pybind/pybind11/compare/v2.13.5...v2.13.6
---
=> pybind11: add version 2.13.6

recipes/debug_assert/all/conandata.yml, recipes/debug_assert/config.yml
Changes to recipe:  **debug-assert/1.3.4**
There are several improvements in 1.3.4.
https://github.com/foonathan/debug_assert/compare/v1.3.3...v1.3.4
---
=> debug-assert: add version 1.3.4
