conan-io/conan-center-index

- recipes/sfml/all/conanfile.py
Specify library name and version:  **sfml/***
---
> sfml: update freetype/2.13.2

- recipes/wayland/all/conanfile.py
> wayland: bump dependencies

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/1.3.0**
---
> meson 1.3.0

- .github/workflows/alert-community.yml
Specify library name and version:  **libhal**
I am the author of libhal and would like to be notified when new versions or changes are made to it. 
---
> Add kammce as reviewer for libhal recipe

- recipes/elfutils/all/conanfile.py
Specify library name and version:  **elfutils/***
---
> elfutils: Bump zlib requirement to [>=1.2.11 <2]

- recipes/xkbcommon/all/conanfile.py
> xkbcommon: bump libxml2

- recipes/libgeotiff/all/conanfile.py
and hopefully generate missing binaries for https://github.com/conan-io/conan-center-index/pull/20734
---
> libgeotiff: add package_type

- recipes/libselinux/all/conanfile.py
https://spdx.org/licenses/libselinux-1.0.html
> libselinux: use a more specific license identifier

- recipes/libsixel/all/conanfile.py
> libsixel: use version range for libcurl

- recipes/imutils-cpp/all/conanfile.py
> imutils-cpp: use version range for libcurl + bump opencv

- recipes/prometheus-cpp/all/conanfile.py
> prometheus-cpp: use version range for libcurl + add package_type

- recipes/lodepng/all/conandata.yml
- recipes/lodepng/config.yml
Specify library name and version:  **lodepng/cci.20230410**
---
> lodepng: add version cci.20230410

- recipes/entt/3.x.x/conanfile.py
> entt: add package_type

- recipes/glm/all/conanfile.py
> glm: add package_type

- recipes/jwasm/all/conanfile.py
> jwasm: add package_type & modernize more

- recipes/nlohmann_json/all/conanfile.py
> nlohmann_json: add package_type

- recipes/spirv-headers/all/conanfile.py
> spirv-headers: add package_type

- recipes/cairo/meson/conanfile.py
Specify library name and version:  **cairo/***
---
> cairo: update dependencies

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.7.4**
---
> ada: add version 2.7.4

- recipes/c-ares/all/conandata.yml
- recipes/c-ares/config.yml
Specify library name and version:  **c-ares/1.22.1**
---
> c-ares: add version 1.22.1

- recipes/emsdk/all/conandata.yml
- recipes/emsdk/config.yml
Specify library name and version:  **emsdk/3.1.49**
---
> [emsdk] bump to 3.1.49

- recipes/ktx/all/conanfile.py
Specify library name and version:  **ktx/***
---
> ktx: update lodepng

- recipes/sofa/all/conandata.yml
- recipes/sofa/config.yml
> sofa: add 20231011

- recipes/implot/all/conanfile.py
Specify library name and version:  **implot/***
---
> implot: update imgui/1.90

- .c3i/config_v1.yml
- .c3i/config_v2.yml
> [config] Add parallel strategy for BuildSingleReference

- recipes/aws-lambda-cpp/all/conandata.yml
- recipes/aws-lambda-cpp/config.yml
Specify library name and version:  **aws-lambda-cpp/0.2.10**
---
> aws-lambda-cpp: add version 0.2.10

- recipes/serdepp/all/conandata.yml
- recipes/serdepp/all/conanfile.py
- recipes/serdepp/all/patches/0.1.4.1-0001-fix-magic_enum-path.patch
Specify library name and version:  **serdepp/***
---
> serdepp: update magic_enum/0.9.5

- recipes/hictk/all/conanfile.py
> hictk: add package_type + remove legacy conan v1 output.warn which breaks conan v2 with "unknown compilers"

- recipes/refl-cpp/all/conanfile.py
> refl-cpp: add package_type + remove legacy conan v1 output.warn which breaks conan v2 with "unknown compilers"

- recipes/rapidjson/all/conandata.yml
- recipes/rapidjson/config.yml
Specify library name and version:  **rapidjson/cci.20230929**
---
> rapidjson: add version cci.20230929

- recipes/psimd/all/conanfile.py
> psimd: add package_type

- recipes/nanoflann/all/conanfile.py
- recipes/nanoflann/all/test_package/conanfile.py
> nanoflann: add package_type

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.44.1**
---
> sqlite3: add version 3.44.1

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.6.1**
---
> glaze: add version 1.6.1

- recipes/libavif/all/conandata.yml
- recipes/libavif/config.yml
Specify library name and version:  **libavif/1.0.2**
---
> libavif: add version 1.0.2

- recipes/pfr/all/conandata.yml
- recipes/pfr/config.yml
Specify library name and version:  **pfr/2.2.0**
---
> pfr: Bump to v2.2.0

- recipes/xz_utils/all/conandata.yml
- recipes/xz_utils/config.yml
Specify library name and version:  **xz_utils/5.4.5**
---
> xz_utils: add 5.4.5

- recipes/fp16/all/conanfile.py
> fp16: add package_type

- recipes/parallel-hashmap/all/conandata.yml
- recipes/parallel-hashmap/all/conanfile.py
- recipes/parallel-hashmap/all/test_package/conanfile.py
- recipes/parallel-hashmap/config.yml
> parallel-hashmap: add package_type

- recipes/metall/all/conandata.yml
- recipes/metall/config.yml
Specify library name and version:  **metall/0.27**
---
> metall: add version 0.27

- recipes/cereal/all/conanfile.py
- recipes/cereal/all/test_package/conanfile.py
> cereal: add package_type

- docs/adding_packages/conandata_yml_format.md
> [docs] Use official windows PS for sha256sum

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.7.0**
---
> glaze: add version 1.7.0

- recipes/cpptrace/all/conandata.yml
- recipes/cpptrace/all/conanfile.py
- recipes/cpptrace/all/test_package/test_package.cpp
- recipes/cpptrace/config.yml
Specify library name and version:  **cpptrace/0.3.0**
I'm the author, this is the next release.
---
> [cpptrace] Add v0.3.0

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.44.2**
---
> sqlite3: add version 3.44.2

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/config.yml
Specify library name and version:  **simdutf/4.0.5**
---
> simdutf: add version 4.0.5

- recipes/apr-util/all/conanfile.py
Specify library name and version:  **apr-util/all**
---
> apr-util: bump sqlite3

- recipes/poco/all/conanfile.py
Specify library name and version:  **poco/all**
---
> poco: bump sqlite3

- recipes/cyrus-sasl/all/conanfile.py
Specify library name and version:  **cyrus-sasl/all**
---
> cyrus-sasl: bump sqlite3

- recipes/dlib/all/conanfile.py
Specify library name and version:  **dlib/all**
---
> dlib: bump sqlite3

- recipes/sqlite_orm/all/conanfile.py
Specify library name and version:  **sqlite_orm/all**
---
> sqlite_orm: bump sqlite3

- recipes/libwebsockets/all/conanfile.py
Specify library name and version:  **libwebsockets/all**
---
> libwebsockets: bump sqlite3

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.23.0**
---
> daw_json_link: add version 3.23.0

- recipes/qt/6.x.x/conanfile.py
Specify library name and version:  **qt/6.x.x**
---
> qt/6.x.x: bump sqlite3

- recipes/nghttp3/all/conandata.yml
- recipes/nghttp3/config.yml
Specify library name and version:  **nghttp3/1.1.0**
---
> nghttp3: add version 1.1.0

- recipes/proj/all/conanfile.py
Specify library name and version:  **proj/all**
---
> proj: bump sqlite3

- recipes/wt/all/conanfile.py
Specify library name and version:  **wt/all**
---
> wt: bump sqlite3

- recipes/qt/5.x.x/conanfile.py
Specify library name and version:  **qt/5.x.x**
---
> qt/5.x.x: bump sqlite3

- recipes/elfutils/all/conanfile.py
> elfutils/all: bump deps

- recipes/libxslt/all/conandata.yml
- recipes/libxslt/all/conanfile.py
- recipes/libxslt/config.yml
Specify library name and version:  **libxslt/1.1.37**
Update libxslt to 1.1.37
---
> libxslt: add version 1.1.37

- recipes/mozjpeg/all/conandata.yml
- recipes/mozjpeg/all/patches/4.1.5-0001-cmake-fixes.patch
- recipes/mozjpeg/config.yml
Specify library name and version:  **mozjpeg/4.1.5**
---
> mozjpeg: add version 4.1.5

- recipes/protobuf-c/all/conandata.yml
- recipes/protobuf-c/all/conanfile.py
- recipes/protobuf-c/all/patches/1.5.0-disable-msvc-runtime.patch
- recipes/protobuf-c/config.yml
Specify library name and version:  **protobuf-c/1.5.0**
---
> protobuf-c: add version 1.5.0

- recipes/nng/all/conandata.yml
- recipes/nng/all/conanfile.py
- recipes/nng/all/test_package/CMakeLists.txt
- recipes/nng/config.yml
Specify library name and version:  **nng/1.6.0**
---
> nng: add version 1.6.0

- recipes/djinni-generator/all/conandata.yml
- recipes/djinni-generator/config.yml
Specify library name and version:  **djinni-generator/1.4.0**
---
> djinni-generator: add version 1.4.0

- recipes/cista/all/conanfile.py
- recipes/cista/all/test_package/conanfile.py
> cista: add package_type

- recipes/clipp/all/conanfile.py
- recipes/clipp/all/test_package/CMakeLists.txt
- recipes/clipp/all/test_package/conanfile.py
- recipes/clipp/all/test_v1_package/CMakeLists.txt
- recipes/clipp/all/test_v1_package/conanfile.py
- add layout
- add test package with v2 helpers
- check min cppstd 11
- empty bindirs & libdirs in package_info()
- explicit cmake names since there is a config file upstream: https://github.com/muellan/clipp/blob/2c32b2f1f7cc530b1ec1f62c92f698643bb368db/CMakeLists.txt#L31-L34
---
> clipp: modernize more for conan v2

- recipes/blaze/all/conanfile.py
> blaze: add package_type

- recipes/backport-cpp/all/conanfile.py
> backport-cpp: add package_type

- recipes/bit-lite/all/conanfile.py
> bit-lite: add package_type

- recipes/clipper2/all/conandata.yml
- recipes/clipper2/all/patches/1.2.4-0001-remove-macos-suffix.patch
- recipes/clipper2/config.yml
Specify library name and version:  **clipper2/1.2.4**
---
> clipper2: add version 1.2.4

- recipes/cpuinfo/all/conanfile.py
> cpuinfo: remove shared option if msvc (always static) + allow shared for windows & non-msvc + add cmake_file_name property

- recipes/bertrand/all/conanfile.py
> bertrand: add package_type

- recipes/boolinq/all/conanfile.py
> boolinq: add package_type

- recipes/bshoshany-thread-pool/all/conanfile.py
- recipes/bshoshany-thread-pool/all/test_package/CMakeLists.txt
- recipes/bshoshany-thread-pool/all/test_package/conanfile.py
- recipes/bshoshany-thread-pool/all/test_v1_package/CMakeLists.txt
- recipes/bshoshany-thread-pool/all/test_v1_package/conanfile.py
- add layout
- properly copy headers depending on versions in package()
---
> bshoshany-thread-pool: modernize more

- recipes/c-dbg-macro/all/conanfile.py
> c-dbg-macro: add package_type

- recipes/cajun-jsonapi/all/conanfile.py
- add layout
- empty bindirs & libdirs
- fix required_conan_version
---
> cajun-jsonapi: modernize more for conan v2

- recipes/canvas_ity/all/conanfile.py
> canvas_ity: add package_type

- recipes/cd3-boost-unit-definitions/all/conanfile.py
- fix msvc min version
- put src code under src folder
---
> cd3-boost-unit-definitions: modernize more for conan v2

- recipes/chef-fun/all/conandata.yml
- recipes/chef-fun/all/conanfile.py
- recipes/chef-fun/all/test_package/conanfile.py
- recipes/chef-fun/config.yml
- fix required_conan_version
- remove dead code
---
> chef-fun: add package_type & cleanup recipe

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.8.1**
---
> glaze: add version 1.8.1

- recipes/zlib-ng/all/conandata.yml
- recipes/zlib-ng/config.yml
Specify library name and version:  **zlib-ng/2.1.5**
---
> zlib-ng: add version 2.1.5

- recipes/cppcodec/all/conanfile.py
> cppcodec: add package_type

- recipes/clipper2/all/conandata.yml
- recipes/clipper2/config.yml
Specify library name and version:  **clipper2/1.3.0**
---
> clipper2: add version 1.3.0

- recipes/nlohmann_json/all/conandata.yml
- recipes/nlohmann_json/config.yml
Specify library name and version:  **nlohmann_json/3.11.3**
---
> nlohmann_json: add version 3.11.3

- recipes/c-blosc2/all/conanfile.py
Specify library name and version:  **c-blosc2/***
---
> c-blosc2: update zlib-ng/2.1.5

- recipes/canary/all/conanfile.py
- add layout
- empty bindirs & libdirs
---
> canary: modernize more for conan v2

- recipes/libftdi/0.x/CMakeLists.txt
- recipes/libftdi/0.x/conandata.yml
- recipes/libftdi/0.x/conanfile.py
- recipes/libftdi/0.x/test_package/CMakeLists.txt
- recipes/libftdi/0.x/test_package/conanfile.py
- recipes/libftdi/0.x/test_v1_package/CMakeLists.txt
- recipes/libftdi/0.x/test_v1_package/conanfile.py
- recipes/libftdi/1.x/conanfile.py
- recipes/libftdi/1.x/test_package/CMakeLists.txt
> libftdi/0.x: migrate to Conan v2

- recipes/gsl-lite/all/conandata.yml
- recipes/gsl-lite/all/conanfile.py
- recipes/gsl-lite/all/test_package/CMakeLists.txt
- recipes/gsl-lite/all/test_v1_package/CMakeLists.txt
- recipes/gsl-lite/all/test_v1_package/conanfile.py
- recipes/gsl-lite/config.yml
- use a layout
- empty bindirs & libdirs since it's header-only
- fix required_conan_version
---
> gsl-lite: modernize more for conan v2

- recipes/aws-c-mqtt/all/conandata.yml
- recipes/aws-c-mqtt/all/conanfile.py
- recipes/aws-c-mqtt/config.yml
Specify library name and version:  **aws-c-mqtt/***
---
> aws-c-mqtt: add version 0.8.12, 0.9.10

- recipes/aws-c-auth/all/conandata.yml
- recipes/aws-c-auth/all/conanfile.py
- recipes/aws-c-auth/all/patches/0.6.17-0001-fix-macro-usage.patch
- recipes/aws-c-auth/config.yml
- recipes/tcp-wrappers/all/conanfile.py
Specify library name and version:  **aws-c-auth/***
---
> aws-c-auth: add version 0.7.7, update dependencies

- recipes/stx/all/conandata.yml
- recipes/stx/all/patches/1.0.5-0002-add-installer.patch
- recipes/stx/config.yml
Specify library name and version:  **stx/1.0.5**
---
> stx: add version 1.0.5

- recipes/jasper/all/conandata.yml
- recipes/jasper/all/patches/4.1.0-0001-skip-rpath.patch
- recipes/jasper/all/patches/4.1.0-0002-find-libjpeg.patch
- recipes/jasper/all/patches/4.1.0-0003-deterministic-libname.patch
- recipes/jasper/config.yml
Specify library name and version:  **jasper/4.1.0**
---
> jasper: add version 4.1.0

- recipes/egl-headers/all/conanfile.py
- recipes/egl-headers/all/test_package/CMakeLists.txt
> egl-headers: add package_type

- recipes/hlslpp/all/conanfile.py
> hlslpp: add package_type

- recipes/libvips/all/conanfile.py
Specify library name and version:  **libvips/***
---
> libvips/all: bump deps 

- recipes/cxxopts/all/conanfile.py
> cxxopts: add package_type + bump icu

- recipes/decimal_for_cpp/all/conanfile.py
- recipes/decimal_for_cpp/all/test_package/conanfile.py
- recipes/decimal_for_cpp/all/test_v1_package/CMakeLists.txt
> decimal_for_cpp: add package_type

- recipes/enum-flags/all/conanfile.py
> enum-flags: add package_type

- recipes/eternal/all/conanfile.py
- recipes/eternal/all/test_package/CMakeLists.txt
- recipes/eternal/all/test_v1_package/CMakeLists.txt
> eternal: add package_type & cleanup recipe

- recipes/fast-cpp-csv-parser/all/conanfile.py
- recipes/fast-cpp-csv-parser/all/test_package/conanfile.py
- recipes/fast-cpp-csv-parser/all/test_v1_package/CMakeLists.txt
> fast-cpp-csv-parser: add package_type

- recipes/fast_double_parser/all/conanfile.py
> fast_double_parser: add package_type

- recipes/fastprng/all/conanfile.py
- recipes/fastprng/all/test_package/conanfile.py
> fastprng: add package_type

- recipes/gcem/all/conanfile.py
> gcem: add package_type

- recipes/ghc-filesystem/all/conanfile.py
> ghc-filesystem: add package_type

- recipes/gnu-config/all/conanfile.py
also remove no_copy_source since there is a patch
---
> gnu-config: add package_type

- recipes/godot_headers/all/conanfile.py
- recipes/godot_headers/all/test_v1_package/CMakeLists.txt
> godot_headers: add package_type

- recipes/gzip-hpp/all/conanfile.py
> gzip-hpp: add package_type

- recipes/half/all/conanfile.py
- recipes/half/all/test_package/conanfile.py
- recipes/half/all/test_v1_package/CMakeLists.txt
> half: add package_type

- recipes/hedley/all/conanfile.py
> hedley: add package_type

- recipes/hffix/all/conanfile.py
- recipes/hffix/all/test_package/CMakeLists.txt
- recipes/hffix/all/test_package/conanfile.py
- recipes/hffix/all/test_v1_package/CMakeLists.txt
> hffix: add package_type

- recipes/highfive/all/conanfile.py
- recipes/highfive/all/test_v1_package/CMakeLists.txt
> highfive: add package_type + bump opencv

- recipes/ginkgo/all/conanfile.py
follow up https://github.com/conan-io/conan-center-index/pull/21058#discussion_r1409127733
also simplify checks in validate() introduced in https://github.com/conan-io/conan-center-index/pull/21058
---
> ginkgo: cmake >= 3.16 required for ginkgo >= 1.7.0 only

- recipes/im95able-rea/all/conanfile.py
> im95able-rea: add package_type

- recipes/libxslt/all/conanfile.py
> libxslt/all: bump libxml2

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.8.2**
---
> glaze: add version 1.8.2

- recipes/homog2d/all/conanfile.py
> homog2d: add package_type

- recipes/indicators/all/conanfile.py
config file name and imported target upstream: https://github.com/p-ranav/indicators/blob/v2.3/CMakeLists.txt#L59-L65
---
> indicators: add package_type + explicit cmake names

- recipes/glog/all/conanfile.py
> glog: Bump deps to fix conflicts

- recipes/libtiff/all/conanfile.py
> libtiff: Bump deps to fix conflicts

- recipes/inja/all/conanfile.py
- recipes/inja/all/test_package/conanfile.py
> inja: add package_type + bump nlohmann_json

- recipes/intel-neon2sse/all/conanfile.py
- recipes/intel-neon2sse/all/test_v1_package/CMakeLists.txt
- recipes/intel-neon2sse/all/test_v1_package/conanfile.py
also add required_conan_version 
---
> intel-neon2sse: add package_type

- recipes/jeaiii-itoa/all/conanfile.py
- recipes/jeaiii-itoa/all/test_package/CMakeLists.txt
- recipes/jeaiii-itoa/all/test_v1_package/CMakeLists.txt
also cleanup recipe a little bit
---
> jeaiii-itoa: add package_type

- recipes/jfalcou-eve/all/conanfile.py
> jfalcou-eve: add package_type

- recipes/linmath.h/all/conanfile.py
> linmath.h: add package_type

- recipes/pcl/all/conanfile.py
Specify library name and version:  **pcl/***
---
> pcl/all: bump deps

- recipes/mikelankamp-fpm/all/conanfile.py
- recipes/mikelankamp-fpm/all/test_package/conanfile.py
> mikelankamp-fpm: add package_type

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/1.8.3**
---
> glaze: add version 1.8.3

- recipes/metall/all/conandata.yml
- recipes/metall/all/conanfile.py
- recipes/metall/all/test_package/conanfile.py
- recipes/metall/all/test_v1_package/CMakeLists.txt
- recipes/metall/config.yml
> metall: add package_type

- recipes/mio/all/conandata.yml
- recipes/mio/all/conanfile.py
- recipes/mio/all/test_package/conanfile.py
- recipes/mio/all/test_v1_package/CMakeLists.txt
- recipes/mio/config.yml
- add description to patch
- use export_conandata_patches
- simplify test_v1_package
---
> mio: add package_type & modernize more

- recipes/tinydir/all/conandata.yml
- recipes/tinydir/config.yml
Specify library name and version:  **tinydir/1.2.6**
---
> tinydir: add version 1.2.6

- recipes/skyr-url/all/conanfile.py
Specify library name and version:  **skyr-url/***
---
> skyr-url: update nlohmann_json

- recipes/onetbb/all/conanfile.py
> onetbb: Fix hwloc shared detection after changes to that recipe

- recipes/mapbox-geometry/all/conanfile.py
- recipes/mapbox-geometry/all/test_v1_package/CMakeLists.txt
> mapbox-geometry: add package_type

- recipes/lyra/all/conanfile.py
- recipes/lyra/all/test_package/CMakeLists.txt
- recipes/lyra/all/test_package/conanfile.py
> lyra: add package_type

- recipes/mapbox-variant/all/conanfile.py
- recipes/mapbox-variant/all/test_package/conanfile.py
- recipes/mapbox-variant/all/test_v1_package/CMakeLists.txt
> mapbox-variant: add package_type

- recipes/pkgconf/all/conandata.yml
- recipes/pkgconf/all/patches/2.1.0-0001-PKG_CONF_PATH-allow-colon+semicolon-separator.patch
- recipes/pkgconf/config.yml
Specify library name and version:  **pkgconf/2.1.0**
This version solves https://github.com/pkgconf/pkgconf/issues/322
---
> pkgconf: add version 2.1.0

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  ** cmake/binary**
---
> cmake: add versions 3.26.6 & 3.27.9

- recipes/tixi3/all/conanfile.py
Specify library name and version:  **tixi3/all**
---
> tixi3: use version range for libcurl

- recipes/mpark-variant/all/conanfile.py
> mpark-variant: add package_type

- recipes/mpmcqueue/all/conanfile.py
- recipes/mpmcqueue/all/test_package/conanfile.py
- recipes/mpmcqueue/all/test_v1_package/CMakeLists.txt
> mpmcqueue: add package_type

- recipes/libsigcpp/2.x.x/test_v1_package/conanfile.py
Specify library name and version:  **libsigcpp/***
---
> libsigcpp: bump pkgconf

- recipes/libserial/all/conandata.yml
- recipes/libserial/config.yml
Specify library name and version:  **libserial/cci.20230909**
---
> libserial: add version cci.20230909

- recipes/etl/all/conandata.yml
- recipes/etl/config.yml
Specify library name and version:  **etl/20.38.7**
---
> etl: add version 20.38.7

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.14.2**
---
> cpp-httplib: add version 0.14.2

- recipes/cocoyaxi/all/conanfile.py
Specify library name and version:  **cocoyaxi/all**
---
> cocoyaxi: use version range for libcurl

- recipes/poco/all/conandata.yml
- recipes/poco/config.yml
Specify library name and version:  **poco/1.12.5p2**
---
> poco: add version 1.12.5p2

- recipes/cpprestsdk/all/conandata.yml
- recipes/cpprestsdk/config.yml
Specify library name and version:  **cpprestsdk/2.10.19**
---
> cpprestsdk: add version 2.10.19

- recipes/sdl/all/conanfile.py
Specify library name and version:  **sdl/***
---
> sdl/all: bump deps

- recipes/aravis/all/conandata.yml
- recipes/aravis/config.yml
Specify library name and version:  **aravis/0.8.30**
---
> aravis: add version 0.8.30

- recipes/libtins/all/conanfile.py
Mostly to fix the missing binary in #19291
> libtins: bump libpcap

- recipes/date/all/conanfile.py
> date: add package_type

- recipes/nuklear/all/conanfile.py
- recipes/nuklear/all/test_package/conanfile.py
- recipes/nuklear/all/test_v1_package/CMakeLists.txt
> nuklear: add package_type

- recipes/nvtx/all/conanfile.py
> nvtx: add package_type

- recipes/observer-ptr-lite/all/conanfile.py
- recipes/observer-ptr-lite/all/test_package/conanfile.py
- recipes/observer-ptr-lite/all/test_v1_package/CMakeLists.txt
> observer-ptr-lite: add package_type

- recipes/aravis/all/conanfile.py
Specify library name and version:  **aravis/***
---
> aravis: fixup version comparison

- recipes/libssh2/all/conanfile.py
Also to fix missing binaries in #18810
> libssh2: bump mbedtls

- recipes/nanobench/all/conanfile.py
> nanobench: add package_type

- recipes/mppp/all/conandata.yml
- recipes/mppp/all/patches/1.0.0-0001-disable-warning-error.patch
- recipes/mppp/all/patches/1.0.0-0002-remove-fmt-version.patch
- recipes/mppp/config.yml
Specify library name and version:  **mppp/1.0.0**
---
> mppp: add version 1.0.0

- recipes/soxr/all/conanfile.py
identified by https://github.com/conan-io/conan-center-index/issues/21163
Specify library name and version:  **soxr/***
---
> soxr: fix version comparison

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Specify library name and version:  **glib/2.78.3**
---
> glib: add version 2.78.3

- recipes/xsimd/all/conandata.yml
- recipes/xsimd/config.yml
Specify library name and version:  **xsimd/12.1.0**
---
> xsimd: add version 12.1.0

- recipes/readline/all/conanfile.py
Specify library name and version:  **readline/all**
---
> readline/all: bump ncurses to v6.4

- recipes/libbpf/all/conanfile.py
Specify library name and version:  **libbpf/all**
---
> recipes/libbpf: bump elfutils to v0.190

- recipes/rtm/all/conandata.yml
- recipes/rtm/config.yml
Specify library name and version:  **rtm/2.2.0**
Adding the latest version to conan. I am its primary author.
---
> rtm: add version 2.2.0

- recipes/libarchive/all/conanfile.py
Specify library name and version:  **libarchive/***
closes #21710
---
> libarchive/all: bump deps

- recipes/pdqsort/all/conanfile.py
- recipes/pdqsort/all/test_package/conanfile.py
- recipes/pdqsort/all/test_v1_package/CMakeLists.txt
> pdqsort: add package_type

- recipes/xmlsec/all/conanfile.py
Specify library name and version:  **xmlsec/all**
---
> xmlsec: bump libxslt

- recipes/symengine/all/conandata.yml
- recipes/symengine/all/conanfile.py
- recipes/symengine/config.yml
> [symengine] Add version 0.11.2

- recipes/readline/all/conandata.yml
- recipes/readline/config.yml
Specify library name and version:  **readline/8.2**
---
> readline: add version 8.2

- recipes/jwt-cpp/all/conandata.yml
- recipes/jwt-cpp/all/conanfile.py
- recipes/jwt-cpp/all/test_package/CMakeLists.txt
- recipes/jwt-cpp/all/test_package/test_package.cpp
- recipes/jwt-cpp/all/test_v1_package/CMakeLists.txt
- recipes/jwt-cpp/config.yml
Specify library name and version:  **jwt-cpp/0.7.0**
---
> jwt-cpp: add version 0.7.0

- recipes/etl/all/conandata.yml
- recipes/etl/config.yml
Specify library name and version:  **etl/20.38.10**
---
> etl: add version 20.38.10

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/6.0.0**
---
> fast_float: add version 6.0.0

- recipes/valijson/all/conandata.yml
- recipes/valijson/config.yml
Specify library name and version:  **valijson/1.0.2**
---
> valijson: add version 1.0.2

- recipes/scnlib/all/conanfile.py
Specify library name and version:  **scnlib/***
---
> scnlib: update fast_float/6.0.0

- recipes/libdrm/all/conanfile.py
> libdrm/all: bump deps

- recipes/rtm/all/conandata.yml
- recipes/rtm/config.yml
Specify library name and version:  **rtm/2.2.1**
Adding the latest version to conan. I am its primary author.
---
> rtm: add version 2.2.1

- recipes/ssp/all/conanfile.py
Specify library name and version:  **ssp/***
---
> ssp: update fast_float/6.0.0

- recipes/highfive/all/conanfile.py
Specify library name and version:  **highfive/***
---
> highfive: update hdf5/1.14.3

- recipes/c4core/all/conanfile.py
> c4core: update fast_float/6.0.0

- recipes/kickcat/all/conandata.yml
- recipes/kickcat/config.yml
Specify library name and version:  **kickcat/v2.0-rc1**
---
> update kickcat to v2.0-rc1

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/4.3.0**
---
> unordered_dense: add version 4.3.0

- recipes/xtl/all/conandata.yml
- recipes/xtl/config.yml
Specify library name and version:  **xtl/0.7.6**
---
> xtl: add version 0.7.6

- recipes/arrow/all/conandata.yml
- recipes/arrow/config.yml
Specify library name and version:  **arrow/14.0.2**
---
> arrow: add version 14.0.2

- recipes/xkbcommon/all/conanfile.py
> xkbcommon: partial bump

- .c3i/config_v1.yml
- .c3i/config_v2.yml
New Macos M2 machines coming to prod!
> [config] Change configurations to amrv8 arch for Macos build profiles

- recipes/arduinojson/all/conandata.yml
- recipes/arduinojson/all/conanfile.py
- recipes/arduinojson/config.yml
> arduinojson: add version 6.21.4

- recipes/bdwgc/all/conanfile.py
> bdwgc/all: bump deps

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.14.3**
---
> cpp-httplib: add version 0.14.3

- recipes/uwebsockets/all/conandata.yml
- recipes/uwebsockets/config.yml
Specify library name and version:  **uwebsockets/20.51.0**
---
> uwebsockets: add version 20.51.0

- recipes/openapi-generator/all/conandata.yml
- recipes/openapi-generator/config.yml
> [openapi-generator] Add version 7.2.0

- recipes/xkeyboard-config/all/conanfile.py
should unblock https://github.com/conan-io/conan-center-index/pull/21772
Specify library name and version:  **xkeyboard-config/system**
---
> xkeyboard-config: define package_type

- recipes/taocpp-taopq/all/conandata.yml
- recipes/taocpp-taopq/all/conanfile.py
- recipes/taocpp-taopq/config.yml
Specify library name and version:  **taocpp-taopq/cci.20231219**
---
> taocpp-taopq: add version cci.20231219

- recipes/commata/all/conandata.yml
- recipes/commata/config.yml
Specify library name and version:  **commata/0.2.8**
---
> commata: add version 0.2.8

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/config.yml
Specify library name and version:  **unordered_dense/4.4.0**
---
> unordered_dense: add version 4.4.0

- recipes/libavif/all/conandata.yml
- recipes/libavif/config.yml
Specify library name and version:  **libavif/1.0.3**
---
> libavif: add version 1.0.3

- recipes/libxslt/all/conandata.yml
- recipes/libxslt/config.yml
> libxslt: add version 1.1.39

- recipes/uwebsockets/all/conandata.yml
- recipes/uwebsockets/config.yml
Specify library name and version:  **uwebsockets/20.53.0**
---
> uwebsockets: add version 20.53.0

- recipes/aravis/all/conanfile.py
Specify library name and version:  **aravis/all**
---
> aravis: bump deps

- recipes/norm/all/conanfile.py
Specify library name and version:  **norm/all**
---
> norm: bump deps

- recipes/libnghttp2/all/conanfile.py
Specify library name and version:  **libnghttp2/all**
---
> libnghttp2: bump deps

- recipes/libxslt/all/conanfile.py
> libxslt: bump libxml

- recipes/approvaltests.cpp/all/conanfile.py
Specify library name and version:  **approvaltests.cpp/***
---
> approvaltests.cpp/all: bump deps

- recipes/librdkafka/all/conanfile.py
> librdkafka/all: bump deps

- recipes/copypp/all/conandata.yml
- recipes/copypp/all/conanfile.py
- recipes/copypp/all/test_package/CMakeLists.txt
- recipes/copypp/all/test_package/conanfile.py
- recipes/copypp/all/test_package/test_package.cpp
- recipes/copypp/config.yml
copypp/0.3.0
support field copy in different c++ struct/class.
---
> copypp: new version 0.3.0 (#21875)

- recipes/xmlsec/all/conandata.yml
- recipes/xmlsec/all/conanfile.py
- recipes/xmlsec/config.yml
Specify library name and version:  **xmlsec/1.3.2**
---
> xmlsec: add version 1.3.2

- recipes/cpp-httplib/all/conanfile.py
Generated and committed by [Conan Center Bump Deps](https://github.com/ericLemanissier/conan-center-index-bump-deps) 
---
> cpp-httplib/all: bump deps

- recipes/hazelcast-cpp-client/all/conanfile.py
- recipes/hazelcast-cpp-client/all/test_package/test_package.cpp
Specify library name and version:  **hazelcast-cpp-client/***
---
> hazelcast-cpp-client/all: bump deps

- recipes/cppcheck/all/conandata.yml
- recipes/cppcheck/config.yml
> Add cppcheck 2.13

- recipes/rapidfuzz/all/conandata.yml
- recipes/rapidfuzz/config.yml
Specify library name and version:  **rapidfuzz/3.0.0**
---
> rapidfuzz: add version 3.0.0

- recipes/lksctp-tools/all/conandata.yml
- recipes/lksctp-tools/all/conanfile.py
- recipes/lksctp-tools/all/test_package/CMakeLists.txt
- recipes/lksctp-tools/all/test_package/conanfile.py
- recipes/lksctp-tools/all/test_package/test_package.c
- recipes/lksctp-tools/config.yml
Specify library name and version:  **lksctp-tools/1.0.19**
---
> lksctp-tools: add recipe

- recipes/functionalplus/all/conandata.yml
- recipes/functionalplus/config.yml
Specify library name and version:  **functionalplus/0.2.22**
---
> functionalplus: add version 0.2.22

- recipes/cjson/all/conandata.yml
- recipes/cjson/config.yml
Specify library name and version:  **cjson/1.7.17**
---
> cjson: add version 1.7.17

- recipes/xkbcommon/all/conanfile.py
> xkbcommon/all: bump deps

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/config.yml
Specify library name and version:  **libxml2/2.12.3**
---
> libxml2: add 2.12.3

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/config.yml
Specify library name and version:  **libxml2/2.11.6**
---
> libxml2: add version 2.11.6

- recipes/libnetfilter_conntrack/all/conandata.yml
- recipes/libnetfilter_conntrack/config.yml
> libnetfilter_conntrack: add v1.0.9

- recipes/wayland/all/conanfile.py
Specify library name and version:  **wayland/all**
---
> wayland: bump deps

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  **cmake/3.28.1**
---
> cmake: add version 3.28.1

- recipes/cista/all/conandata.yml
- recipes/cista/config.yml
> cista: add v0.14

- recipes/libmetalink/all/conanfile.py
Specify library name and version:  **libmetalink/all**
---
> libmetalink: bump deps

- recipes/hwloc/all/conanfile.py
Specify library name and version:  **hwloc/all**
---
> hwloc: bump deps

- recipes/upx/all/conandata.yml
- recipes/upx/config.yml
> upx: add v4.2.1

- recipes/libxslt/all/conanfile.py
> libxslt: bump deps

- recipes/libfuse/all/conandata.yml
- recipes/libfuse/config.yml
> libfuse: add v3.16.2

- recipes/homog2d/all/conandata.yml
- recipes/homog2d/config.yml
Specify library name and version:  **homo2d/2.11**
---
> homo2d: add version 2.11

- recipes/uncrustify/all/conandata.yml
- recipes/uncrustify/config.yml
> uncrustify: add v0.78.1

- recipes/libnet/all/conandata.yml
- recipes/libnet/config.yml
> libnet: add v1.3

- recipes/mppp/all/conandata.yml
- recipes/mppp/config.yml
Specify library name and version:  **mppp/1.0.2**
---
> mppp: add version 1.0.2

- recipes/autoconf-archive/all/conandata.yml
- recipes/autoconf-archive/config.yml
> autoconf-archive: add v2023.02.20

- recipes/xorg-macros/all/conandata.yml
- recipes/xorg-macros/config.yml
> xorg-macros: add v1.20.0

- recipes/icu/all/conandata.yml
- recipes/icu/config.yml
> icu: add v74.2

- recipes/capstone/all/conandata.yml
- recipes/capstone/config.yml
> capstone: add v5.0.1

- recipes/libtorrent/all/conandata.yml
- recipes/libtorrent/config.yml
> libtorrent: add v2.0.9

- recipes/utfcpp/all/conandata.yml
- recipes/utfcpp/config.yml
Specify library name and version:  **utfcpp/4.0.4**
---
> utfcpp: add version 4.0.4

- recipes/s2n/all/conandata.yml
- recipes/s2n/config.yml
Specify library name and version:  **s2n/1.4.1**
---
> s2n: add version 1.4.1

- recipes/tinyxml2/all/conandata.yml
- recipes/tinyxml2/config.yml
Specify library name and version:  **tinyxml2/10.0.0**
---
> tinyxml2: add version 10.0.0

- recipes/jsoncons/all/conandata.yml
- recipes/jsoncons/config.yml
Specify library name and version:  **jsoncons/0.173.2**
---
> jsoncons: add version 0.173.2

- recipes/proj/all/conandata.yml
- recipes/proj/config.yml
Specify library name and version:  **proj/9.3.1**
---
> proj: add version 9.3.1

- recipes/xmlsec/all/conanfile.py
Specify library name and version:  **xmlsec/all**
---
> xmlsec: bump deps

- recipes/tmx/all/conanfile.py
Specify library name and version:  **tmx/all**
---
> tmx: bump deps

- recipes/opentdf-client/all/conanfile.py
Specify library name and version:  **opentdf-client/all**
---
> opentdf-client: bump deps

- recipes/tixi3/all/conanfile.py
Specify library name and version:  **tixi3/all**
---
> tixi3: bump deps

- recipes/libxmlpp/all/conanfile.py
Specify library name and version:  **libxmlpp/all**
---
> libxmlpp: bump deps

- recipes/fmt/all/conandata.yml
- recipes/fmt/all/conanfile.py
- recipes/fmt/config.yml
Specify library name and version:  **fmt/10.2.0**
---
> fmt: add version 10.2.0

- recipes/libenvpp/all/conanfile.py
Specify library name and version:  **libenvpp/***
---
> libenvpp: update fmt/10.2.0

- recipes/quill/all/conanfile.py
> quill: update fmt/10.2.0

- recipes/jinja2cpp/all/conanfile.py
Specify library name and version:  **jinja2cpp/***
---
> jinja2cpp: update fmt/10.2.0

- recipes/mbits-diags/all/conanfile.py
Specify library name and version:  **mbtis-diags/***
---
> mbits-diags: update fmt/10.2.0

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.0.0**
---
> glaze: add version 2.0.0

- recipes/fmtlog/all/conanfile.py
Specify library name and version:  **fmtlog/***
---
> fmtlog: update fmt/10.2.0

- recipes/onetbb/all/conanfile.py
> onetbb/all: bump deps

- recipes/spdlog/all/conanfile.py
Specify library name and version:  **spdlog/***
---
> spdlog: update fmt/1.12.0

- recipes/zug/all/conandata.yml
- recipes/zug/config.yml
> zug: add v0.1.1, drop custom version

- recipes/cpp-validator/all/conanfile.py
Specify library name and version:  **cpp-validator/***
---
> cpp-validator: update fmt/10.2.0

- recipes/svgwrite/all/conanfile.py
Specify library name and version:  **svgwrite/***
---
> svgwrite: update fmt/10.2.0

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.0.1**
---
> glaze: add version 2.0.1

- recipes/gegles-spdlog_setup/all/conanfile.py
Specify library name and version:  **gegles-spdlog_setup/***
---
> gegles-spdlog_setup: update fmt/10.2.0

- recipes/sbepp/all/conanfile.py
Specify library name and version:  **sbepp/***
---
> sbepp: update dependencies

- recipes/mppp/all/conanfile.py
Specify library name and version:  **mppp/***
---
> mppp: update fmt/10.2.0

- recipes/roaring/all/conandata.yml
- recipes/roaring/config.yml
Specify library name and version:  **roaring/2.1.1**
---
> roaring: add version 2.1.1

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.0.2**
---
> glaze: add version 2.0.2

- recipes/fmt/all/conandata.yml
- recipes/fmt/config.yml
Specify library name and version:  **fmt/10.2.1**
---
> fmt: add version 10.2.1

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.97.0**
---
> daw_header_libraries: add version 2.97.0

- recipes/uwebsockets/all/conandata.yml
- recipes/uwebsockets/config.yml
Specify library name and version:  **uwebsockets/20.55.0**
---
> uwebsockets: add version 20.55.0

- recipes/uwebsockets/all/conanfile.py
Specify library name and version:  **uwebsockets/***
---
> uwebsockets: update libdeflate/1.19

- recipes/nfrechette-acl/all/conandata.yml
- recipes/nfrechette-acl/all/conanfile.py
- recipes/nfrechette-acl/config.yml
Specify library name and version:  **nfrechette-acl/2.1.0**
Adding the latest version to conan. I am its primary author.
---
> nfrechette-acl: add version 2.1.0

- recipes/cmocka/all/conandata.yml
- recipes/cmocka/all/conanfile.py
- recipes/cmocka/config.yml
> cmocka: add v1.1.7

- recipes/ldns/all/conandata.yml
- recipes/ldns/all/test_package/conanfile.py
- recipes/ldns/all/test_v1_package/conanfile.py
- recipes/ldns/config.yml
> ldns: add v1.8.2

- recipes/gsl/all/conandata.yml
- recipes/gsl/config.yml
> gsl: add v2.7.1, better URLs

- recipes/lcms/all/conandata.yml
- recipes/lcms/all/conanfile.py
- recipes/lcms/config.yml
> lcms: add v2.16

- recipes/make/all/conandata.yml
- recipes/make/all/patches/4.4.1-0001-clang.patch
- recipes/make/config.yml
> make: add v4.4.1

- recipes/libmodbus/all/conandata.yml
- recipes/libmodbus/all/patches/3.1.10-0001-msvc-fixes.patch
- recipes/libmodbus/config.yml
> libmodbus: add v3.1.10

- recipes/nv-codec-headers/all/conandata.yml
- recipes/nv-codec-headers/all/conanfile.py
- recipes/nv-codec-headers/config.yml
> nv-codec-headers: add v12.1.14.0

- recipes/nng/all/conandata.yml
- recipes/nng/all/conanfile.py
- recipes/nng/config.yml
- recipes/svgwrite/all/conanfile.py
Specify library name and version:  **nng/***
- add version 1.7.0
- add options "max_poller_threads"
- update mbedtls/3.5.1
---
> nng: add version 1.7.0, update mbedtls/3.5.1

- recipes/luau/all/conandata.yml
- recipes/luau/config.yml
Specify library name and version:  **luau/0.607**
---
> luau: add version 0.607

- recipes/kuba-zip/all/conandata.yml
- recipes/kuba-zip/config.yml
Specify library name and version:  **kuba-zip/0.3.1**
---
> kuba-zip: add version 0.3.1

- recipes/drogon/all/conandata.yml
- recipes/drogon/all/conanfile.py
- recipes/drogon/config.yml
> drogon: add version 1.9.1, update trantor

- recipes/fltk/all/conandata.yml
- recipes/fltk/all/conanfile.py
- recipes/fltk/config.yml
Specify library name and version:  **fltk/1.3.9**
---
> fltk: add version 1.3.9, update libxft

- recipes/uchardet/all/conandata.yml
- recipes/uchardet/all/conanfile.py
- recipes/uchardet/config.yml
> uchardet: add v0.0.8

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/config.yml
> wasmtime: add v16.0.0, drop old versions

- recipes/mold/all/conandata.yml
- recipes/mold/config.yml
Specify library name and version:  **mold/2.4.0**
---
> mold: add version 2.4.0

- recipes/stringzilla/all/conandata.yml
- recipes/stringzilla/config.yml
Specify library name and version:  **stringzilla/2.0.4**
---
> stringzilla: add version 2.0.4

- recipes/openmesh/all/conandata.yml
- recipes/openmesh/all/conanfile.py
- recipes/openmesh/all/patches/restore-cxx11-compatibility.patch
- recipes/openmesh/config.yml
> openmesh: add v10.0

- recipes/z3/all/CMakeLists.txt
- recipes/z3/all/conandata.yml
- recipes/z3/all/conanfile.py
- recipes/z3/config.yml
> z3: add version 4.12.4

- recipes/cppcommon/all/conanfile.py
Specify library name and version:  **cppcommon/***
---
> cppcommon: update fmt/10.2.0

- recipes/toml11/all/conandata.yml
- recipes/toml11/config.yml
Specify library name and version:  **toml11/3.8.1**
---
> toml11: add version 3.8.1

- recipes/at-spi2-core/config.yml
- recipes/at-spi2-core/new/conandata.yml
Specify library name and version:  **at-spi2-core/2.51.0**
---
> at-spi2-core 2.51.0

- recipes/openblas/all/conandata.yml
- recipes/openblas/config.yml
> openblas: add v0.3.26

- recipes/libsass/all/conandata.yml
- recipes/libsass/config.yml
> libsass: add v3.6.6

- recipes/open62541/all/conandata.yml
- recipes/open62541/all/submoduledata.yml
- recipes/open62541/config.yml
> open62541: add v1.3.9

- recipes/libmaxminddb/all/conandata.yml
- recipes/libmaxminddb/config.yml
Specify library name and version:  **libmaxmind/1.9.1**
---
> libmaxmind: add version 1.9.1

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.0.5**
---
> glaze: add version 2.0.5

- recipes/pixman/all/conandata.yml
- recipes/pixman/config.yml
The only patch in v0.42.2 has been merged in this version.
> pixman: add v0.43.0

- recipes/sfml/all/conanfile.py
Specify library name and version:  **sfml/***
---
> sfml/all: bump deps

- recipes/thrift/all/conanfile.py
Specify library name and version:  **thrift/***
---
> thrift: bump boost

- recipes/zlib-ng/all/conandata.yml
- recipes/zlib-ng/config.yml
Specify library name and version:  **zlib-ng/2.1.6**
---
> zlig-nb: add version 2.1.6

- recipes/libvdpau/all/conandata.yml
- recipes/libvdpau/all/conanfile.py
- recipes/libvdpau/all/test_package/CMakeLists.txt
- recipes/libvdpau/all/test_package/conanfile.py
- recipes/libvdpau/all/test_package/test_package.c
- recipes/libvdpau/config.yml
Specify library name and version:  **libvdpau/1.5**
---
> libvdpau 1.5

- recipes/gdcm/all/conandata.yml
- recipes/gdcm/all/conanfile.py
- recipes/gdcm/all/patches/0002-3.0.23-openjpeg.patch
- recipes/gdcm/all/patches/0004-3.0.23-find-expat.patch
- recipes/gdcm/all/patches/0007-3.0.23-find-json.patch
- recipes/gdcm/all/patches/0008-3.0.23-find-libuuid.patch
- recipes/gdcm/config.yml
Specify library name and version:  **gdcm/3.0.23**
New version doesn't require charls patch.
---
> gdcm: add 3.0.23 and update zlib-ng

- recipes/libva/all/conanfile.py
> libva/all: bump deps

- recipes/libvdpau/all/conanfile.py
> libvdpau/all: bump deps

- recipes/spdlog/all/conandata.yml
- recipes/spdlog/config.yml
Specify library name and version:  **spdlog/1.13.0**
---
> spdlog: add version 1.13.0

- recipes/opencl-headers/all/conandata.yml
- recipes/opencl-headers/config.yml
Specify library name and version:  **opencl-headers/2023.12.14**
Issue #22214
> opencl-headers: v2023.12.14

- recipes/opencl-clhpp-headers/all/conandata.yml
- recipes/opencl-clhpp-headers/config.yml
> opencl-clhpp-headers: v2023.12.14

- recipes/opencl-icd-loader/all/conandata.yml
- recipes/opencl-icd-loader/config.yml
> opencl-icd-loader: v2023.12.14

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.0.6**
---
> glaze: add version 2.0.6

- recipes/libnuma/all/conandata.yml
- recipes/libnuma/config.yml
The patch in the previous version has been merged upstream.
> libnuma: add v2.0.16

- recipes/quill/all/conanfile.py
> quill: update fmt/10.2.1

- recipes/mppp/all/conanfile.py
Specify library name and version:  **mppp/***
---
> mppp: update fmt/10.2.1

- recipes/libbigwig/all/conanfile.py
Specify library name and version:  **libbigwig/***
---
> libbigwig: update zlib-ng/2.1.6

- recipes/pdf-writer/all/conandata.yml
- recipes/pdf-writer/config.yml
Specify library name and version:  **pdf-writer/4.6.3**
---
> pdf-writer: add version 4.6.3

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.98.5**
---
> daw_header_libraries: add version 2.98.5

- recipes/libenvpp/all/conanfile.py
Specify library name and version:  **libenvpp/10.2.1**
---
> libenvpp: update fmt/10.2.1

- recipes/mbits-diags/all/conanfile.py
Specify library name and version:  **mbits-diags/***
---
> mbits-diags: update fmt/10.2.1

- recipes/fmtlog/all/conanfile.py
Specify library name and version:  **fmtlog/***
---
> fmtlog: update fmtlog/10.2.1

- recipes/zyre/all/conanfile.py
> zyre: bump deps

- recipes/xbyak/all/conandata.yml
- recipes/xbyak/all/conanfile.py
- recipes/xbyak/config.yml
Specify library name and version:  **xbyak/7.05**
---
> xbyak: add version 7.05

- recipes/json_dto/all/conandata.yml
- recipes/json_dto/all/conanfile.py
- recipes/json_dto/config.yml
Specify library name and version:  **json_dto/0.3.2**
---
> json_dto: add version 0.3.2

- recipes/h5pp/all/conandata.yml
- recipes/h5pp/all/conanfile.py
- recipes/h5pp/all/test_package/test_package.cpp
- recipes/h5pp/config.yml
**h5pp/1.11.1**
Bump version
---
> Update to h5pp/1.11.1

- recipes/xmlsec/all/conanfile.py
Specify library name and version:  **xmlsec/all**
---
> xmlsec: update libxslt/1.1.39

- recipes/tl-expected/all/conanfile.py
Specify library name and version:  **tl-expected/1.0**
---
> tl-expected: set package_type

- recipes/tqdm-cpp/all/conandata.yml
- recipes/tqdm-cpp/all/conanfile.py
- recipes/tqdm-cpp/all/test_package/CMakeLists.txt
- recipes/tqdm-cpp/all/test_package/conanfile.py
- recipes/tqdm-cpp/all/test_package/test_package.cpp
- recipes/tqdm-cpp/config.yml
Adds `tqdm-cpp`: https://github.com/mraggi/tqdm-cpp
Easily display progress in C++17. Inspired by python's awesome tqdm library.
> tqdm-cpp: new recipe

- recipes/osmanip/all/CMakeLists.txt
- recipes/osmanip/all/conandata.yml
- recipes/osmanip/all/conanfile.py
- recipes/osmanip/all/test_package/test_package.cpp
Specify library name and version:  **osmanip/***
---
> Osmanip: fix 4.4.0 url

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/config.yml
Specify library name and version:  **libxml2/2.12.4**
---
> libxml2: add version 2.12.4

- recipes/nuklear/all/conandata.yml
- recipes/nuklear/config.yml
Specify library name and version:  **nuklear/4.12.0**
---
> nuklear: add version 4.12.0

- recipes/logr/0.1.0/conanfile.py
- recipes/logr/all/conanfile.py
> logr: bump deps

- recipes/xmlsec/all/conanfile.py
Specify library name and version:  **xmlsec/***
---
> xmlsec: update dependencies

- recipes/arduinojson/all/conandata.yml
- recipes/arduinojson/all/conanfile.py
- recipes/arduinojson/config.yml
> arduinojson: add v7.0.1, drop old versions

- recipes/sentry-native/all/conandata.yml
- recipes/sentry-native/config.yml
> [sentry-native] bump to 0.7.0

- recipes/xmlsec/all/conandata.yml
- recipes/xmlsec/config.yml
Specify library name and version:  **xmlsec/1.3.3**
---
> xmlsec: add version 1.3.3

- recipes/entt/3.x.x/conandata.yml
- recipes/entt/config.yml
Specify library name and version:  **entt/3.13.0**
---
> entt: add version 3.13.0

- recipes/libversion/all/conandata.yml
- recipes/libversion/all/conanfile.py
- recipes/libversion/all/test_package/CMakeLists.txt
- recipes/libversion/all/test_package/conanfile.py
- recipes/libversion/all/test_package/test_package.c
- recipes/libversion/config.yml
Adds `libversion`: https://github.com/repology/libversion
Advanced version string comparison library.
[![Packaging status](https://repology.org/badge/tiny-repos/libversion.svg)](https://repology.org/project/libversion/versions)
> libversion: new recipe

- recipes/libcoro/all/conanfile.py
Specify library name and version:  **libcoro/***
---
> libcoro: update c-ares

- recipes/osmanip/all/conanfile.py
Specify library name and version:  **osmanip/***
---
> osmanip: update arsenalgear

- recipes/trantor/all/conanfile.py
> trantor: update dependencies

- recipes/cpp-validator/all/conanfile.py
Specify library name and version:  **cpp-validator/***
---
> cpp-validator: update fmt

- recipes/jsonnet/all/conanfile.py
Specify library name and version:  **jsonnet/***
---
> jsonnet: update nlohmann_json

- recipes/sqlitecpp/all/conanfile.py
Specify library name and version:  **sqlitecpp/***
---
> sqlitecpp: update sqlite3/3.45.0

- recipes/poco/all/conanfile.py
Specify library name and version:  **poco/***
---
> poco: update sqlite3/3.45.0

- recipes/sqlite_orm/all/conanfile.py
> sqlite_orm: update sqlite3/3.45.0

- recipes/dlib/all/conanfile.py
Specify library name and version:  **dlib/***
---
> dlib: update dependencies

- recipes/daw_json_link/all/conanfile.py
> daw_json_link: update daw_header_libraries/2.97.0

- recipes/libvpx/all/conanfile.py
Closes https://github.com/conan-io/conan-center-index/issues/22416
> [libvpx] iOS/arm* fix

- recipes/copypp/all/conanfile.py
> copypp: fix min msvc version

- recipes/libxmlpp/all/conandata.yml
- recipes/libxmlpp/all/conanfile.py
- recipes/libxmlpp/all/patches/5.2.0-0001-enable_static_builds_on_msvc.patch
- recipes/libxmlpp/config.yml
Specify library name and version:  **libxmlpp/5.2.0**
---
> libxmlpp: add version 5.2.0

- recipes/flux/all/conandata.yml
- recipes/flux/all/conanfile.py
- recipes/flux/all/test_package/CMakeLists.txt
- recipes/flux/all/test_package/conanfile.py
- recipes/flux/all/test_package/test_package.cpp
- recipes/flux/config.yml
Adds Flux: https://github.com/tcbrindle/flux
Flux is an experimental C++20 library for working with sequences of values. It offers similar facilities to C++20 ranges, D ranges, Python itertools, Rust iterators and related libraries for other languages.
> flux: new recipe

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.7.5**
---
> ada: add verison 2.7.5

- recipes/libe57format/all/conanfile.py
Specify library name and version:  **libe57format/***
---
> libe57format: bump deps

- recipes/libdrm/all/conandata.yml
- recipes/libdrm/config.yml
Specify library name and version:  **libdrm/2.4.120**
---
> libdrm: Add version 2.4.120

- recipes/zlib/all/conandata.yml
- recipes/zlib/all/conanfile.py
- recipes/zlib/all/patches/1.3.1/0001-fix-cmake.patch
- recipes/zlib/config.yml
Specify library name and version:  **zlib/1.3.1**
---
> zlib: add 1.3.1

- recipes/c-blosc2/all/conandata.yml
- recipes/c-blosc2/config.yml
Specify library name and version:  **c-blosc2/2.13.0**
---
> c-blosc2: add version 2.13.0

- recipes/wayland-protocols/all/conandata.yml
- recipes/wayland-protocols/config.yml
Specify library name and version:  **wayland-protocols/1.33**
---
> wayland-protocols: Add version 1.33

- recipes/fftw/all/conanfile.py
closes https://github.com/conan-io/conan-center-index/issues/21784
---
> fftw: avoid side effects from build_folder manipulation with multiple precisions

- recipes/bshoshany-thread-pool/all/conandata.yml
- recipes/bshoshany-thread-pool/all/test_package/test_package.cpp
- recipes/bshoshany-thread-pool/config.yml
Specify library name and version:  **bshoshany-thread-pool/4.0.0**
Thanks! :)
> bshoshany-thread-pool: add version 4.0.0

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/config.yml
Specify library name and version:  **fast_float/6.1.0**
---
> fast_float: add version 6.1.0

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.15.1**
---
> cpp-httplib: add version 0.15.1

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.45.1**
---
> sqlite3: add version 3.45.1

- recipes/xtensor/all/conandata.yml
- recipes/xtensor/config.yml
Specify library name and version:  **xtensor/***
---
> xtensor: add version 0.25.0

- recipes/luau/all/conandata.yml
- recipes/luau/config.yml
Specify library name and version:  **luau/0.610**
---
> luau: add version 0.610

- recipes/inih/all/conandata.yml
- recipes/inih/config.yml
Specify library name and version:  **inih/58**
---
> inih: add version 58

- recipes/uwebsockets/all/conandata.yml
- recipes/uwebsockets/config.yml
Specify library name and version:  **uwebsockets/20.58.0**
---
> uwebsockets: add version 20.58.0

- recipes/c-blosc2/all/conandata.yml
- recipes/c-blosc2/config.yml
Specify library name and version:  **c-blosc2/2.13.1**
---
> c-blosc2: add version 2.13.1

- recipes/cpp-peglib/1.x.x/conandata.yml
- recipes/cpp-peglib/config.yml
Specify library name and version:  **cpp-peglib/1.8.6**
---
> cpp-peglib: add version 1.8.6

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.6.4**
---
> simdjson: add version 3.6.4

- recipes/highfive/all/conandata.yml
- recipes/highfive/all/conanfile.py
- recipes/highfive/config.yml
Specify library name and version:  **highfive/all**
---
> highfive: add v2.9.0 and bump boost

- recipes/asio-grpc/all/conandata.yml
- recipes/asio-grpc/all/conanfile.py
- recipes/asio-grpc/config.yml
Specify library name and version:  **asio-grpc/2.9.2**
---
> asio-grpc: add version 2.9.2

- recipes/json_dto/all/conandata.yml
- recipes/json_dto/config.yml
Specify library name and version:  **json_dto/0.3.3**
---
> json_dto: add version 0.3.3

- recipes/mbedtls/all/conandata.yml
- recipes/mbedtls/config.yml
Specify library name and version:  **mbedtls/3.5.2**
---
> mbedtls: add version 3.5.2

- recipes/keychain/all/conandata.yml
- recipes/keychain/config.yml
Specify library name and version:  **keychain/1.3.0**
Version update.
---
> keychain: add version 1.3.0

- recipes/restinio/v0.7/conanfile.py
Specify library name and version:  **restinio/0.7.1**
---
> restinio: bump to `asio` and `boost`

- recipes/ffmpeg/all/conanfile.py
Specify library name and version:  **ffmpeg/all**
---
> ffmpeg: bump deps

- recipes/dataframe/all/conandata.yml
- recipes/dataframe/config.yml
Specify library name and version:  **dataframe/3.0.0**
---
> Upgrading C++ DataFrame to version 3.0.0

- recipes/libtiff/all/conanfile.py
Specify library name and version:  **libtiff/all**
---
> libtiff: bump libjpeg-turbo

- recipes/jsoncons/all/conandata.yml
- recipes/jsoncons/config.yml
Specify library name and version:  **jsoncons/0.173.3**
---
> jsoncons: add version 0.173.3

- recipes/yder/all/conanfile.py
Specify library name and version:  **yder/***
---
> yder: update orcania/2.3.3

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.15.2**
---
> cpp-httplib: add version 0.15.2

- recipes/beauty/all/conandata.yml
- recipes/beauty/all/conanfile.py
- recipes/beauty/config.yml
Specify library name and version:  **beauty/***
---
> beauty: add version 1.0.3, update boost

- recipes/yder/all/conandata.yml
- recipes/yder/config.yml
Specify library name and version:  **yder/1.4.20**
---
> yder: add version 1.4.20

- recipes/nameof/all/conandata.yml
- recipes/nameof/config.yml
Specify library name and version:  **nameof/0.10.4**
---
> nameof: add version 0.10.4

- recipes/libcbor/all/conandata.yml
- recipes/libcbor/all/conanfile.py
- recipes/libcbor/config.yml
Specify library name and version:  **libcbor/0.11.0**
---
> libcbor: add version 0.11.0

- recipes/ssp/all/conanfile.py
Specify library name and version:  **ssp/***
---
> ssp: update fast_float/6.1.0

- recipes/libnabo/all/conandata.yml
- recipes/libnabo/all/conanfile.py
- recipes/libnabo/all/patches/1.1.0-0001-fix-cmake.patch
- recipes/libnabo/config.yml
Specify library name and version:  **libnabo/1.1.0**
---
> libnabo: add version 1.1.0

- .github/workflows/on-push-do-doco.yml
I did not identify incompatibilities in https://github.com/peter-evans/create-pull-request/releases
---
> actions: bump peter-evans/create-pull-request

- recipes/libsquish/all/conanfile.py
Specify library name and version:  **libsquish/***
---
> libsquish: generate missing binaries

- recipes/span-lite/all/conandata.yml
- recipes/span-lite/all/conanfile.py
- recipes/span-lite/config.yml
Specify library name and version:  **span-lite/***
- add version 0.11.0
- sort versions
- small improvements
---
> span-lite: add version 0.11.0, remove older versions

- recipes/llama-cpp/all/conandata.yml
- recipes/llama-cpp/all/conanfile.py
- recipes/llama-cpp/all/test_package/CMakeLists.txt
- recipes/llama-cpp/all/test_package/conanfile.py
- recipes/llama-cpp/all/test_package/test_package.cpp
- recipes/llama-cpp/config.yml
Specify library name and version:  **llama.cpp**
> Add llama.cpp

- recipes/taglib/all/conandata.yml
- recipes/taglib/all/conanfile.py
- recipes/taglib/all/test_package/CMakeLists.txt
- recipes/taglib/config.yml
> taglib: add v1.13.1, v2.0-beta

- recipes/jsoncons/all/conandata.yml
- recipes/jsoncons/config.yml
Specify library name and version:  **jsoncons/***
---
> jsoncons: add version 0.173.4, remove older versions

- recipes/optional-lite/all/conandata.yml
- recipes/optional-lite/all/conanfile.py
- recipes/optional-lite/config.yml
Specify library name and version:  **optional-lite/3.6.0**
---
> optional-lite: add  version 3.6.0

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Specify library name and version:  **cpp-httplib/0.15.3**
---
> cpp-httplib: add version 0.15.3

- recipes/cppcheck/all/conandata.yml
- recipes/cppcheck/config.yml
> Add cppcheck 2.13.3

- recipes/mapbox-wagyu/all/conandata.yml
- recipes/mapbox-wagyu/all/conanfile.py
- recipes/mapbox-wagyu/all/test_package/CMakeLists.txt
- recipes/mapbox-wagyu/all/test_package/conanfile.py
- recipes/mapbox-wagyu/all/test_package/test_package.cpp
- recipes/mapbox-wagyu/config.yml
Specify library name and version:  **mapbox-wagyu/0.5.0**
Try to close https://github.com/conan-io/conan-center-index/issues/22579.
---
> mapbox-wagyu: add recipe

- recipes/expat/all/conandata.yml
- recipes/expat/config.yml
Specify library name and version:  **expat/2.6.0**
Expat library update to mitigate CVEs
https://github.com/libexpat/libexpat/blob/R_2_6_0/expat/Changes
---
> [expat] Add expat version 2.6.0

- recipes/cli11/all/conandata.yml
- recipes/cli11/config.yml
Specify library name and version:  **cli11/2.4.1**
---
> cli11: add version 2.4.1

- recipes/7bitdi/all/conandata.yml
- recipes/7bitdi/config.yml
Specify library name and version:  **7bitdl/2.1.0**
---
> 7bitdi: add version 2.1.0

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.0.7**
---
> glaze: add version 2.0.7

- recipes/wise_enum/all/conandata.yml
- recipes/wise_enum/config.yml
Specify library name and version:  **wise_enum/3.1.0**
---
> wise_enum: add version 3.1.0

- recipes/openapi-generator/all/conandata.yml
- recipes/openapi-generator/config.yml
> [openapi-generator] Add version 7.3.0

- recipes/bdwgc/all/conandata.yml
- recipes/bdwgc/all/patches/update-cmake-8_2_6.patch
- recipes/bdwgc/config.yml
* Add gc/8.2.6 recipe
Specify library name and version: gc/8.2.6
Full list of changes - https://github.com/ivmai/bdwgc/releases/tag/v8.2.6
I'm upstream maintainer of this library.
---
> Add gc/8.2.6 recipe

- .github/workflows/stale.yml
> stale: process older PRs first

- recipes/drogon/all/conandata.yml
- recipes/drogon/all/test_package/conanfile.py
- recipes/drogon/config.yml
> drogon: add version 1.9.3

- recipes/poco/all/conandata.yml
- recipes/poco/config.yml
Specify library name and version:  **poco/1.13.1**
---
> poco: add version 1.13.1

- recipes/libnfs/all/conandata.yml
- recipes/libnfs/config.yml
Specify library name and version:  **libnfs/5.0.3**
---
> libnfs: add version 5.0.3

- recipes/nanomsg/all/conandata.yml
- recipes/nanomsg/config.yml
Specify library name and version:  **nanomsg/1.2.1**
---
> nanomsg: add version 1.2.1

- recipes/bezier/all/conandata.yml
- recipes/bezier/all/conanfile.py
- recipes/bezier/all/test_package/CMakeLists.txt
- recipes/bezier/all/test_package/conanfile.py
- recipes/bezier/all/test_package/test_package.cpp
- recipes/bezier/config.yml
Specify library name and version:  **bezier/***
---
> bezier: add recipe

- recipes/leveldb/all/conanfile.py
Specify library name and version:  **leveldb/***
---
> leveldb: update snappy/1.1.10

- recipes/uvw/all/conandata.yml
- recipes/uvw/all/conanfile.py
- recipes/uvw/config.yml
Specify library name and version:  **uvw/3.3.0**
---
> uvw: add version 3.3.0

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.1.0**
---
> glaze: add version 2.1.0

- recipes/pthreadpool/all/conandata.yml
- recipes/pthreadpool/config.yml
Specify library name and version:  **pthreadpool/cci.20231129**
---
> pthreadpool: Add cci.20231129

- recipes/h5pp/all/conandata.yml
- recipes/h5pp/config.yml
Update to new h5pp version to 1.11.2
---
> Update to h5pp/1.11.2

- recipes/scnlib/all/conandata.yml
- recipes/scnlib/config.yml
Specify library name and version:  **scnlib/2.0.1**
---
> scnlib: add version 2.0.1

- recipes/cxxopts/all/conandata.yml
- recipes/cxxopts/config.yml
Specify library name and version:  **cxxopts/3.2.0**
---
> cxxopts: add version 3.2.0

- recipes/libucl/all/conandata.yml
- recipes/libucl/all/conanfile.py
- recipes/libucl/all/patches/0002-0.9.0-cmake-add-install+use-find_package.patch
- recipes/libucl/all/patches/0006-0.9.0-remove-glib-types.patch
- recipes/libucl/config.yml
Specify library name and version:  **libucl/0.9.0**
---
> libucl: add version 0.9.0

- recipes/ssp/all/conandata.yml
- recipes/ssp/config.yml
Specify library name and version:  **ssp/1.6.2**
---
> ssp: add version 1.6.2

- recipes/rtm/all/conandata.yml
- recipes/rtm/config.yml
Specify library name and version:  **rtm/2.3.0**
---
> rtm: add version 2.3.0

- recipes/emio/all/conandata.yml
- recipes/emio/all/conanfile.py
- recipes/emio/config.yml
Specify library name and version:  **emio/0.7.0**
---
> emio: add version 0.7.0

- recipes/sfl/all/conandata.yml
- recipes/sfl/config.yml
Specify library name and version:  **sfl/1.2.4**
---
> sfl: add version 1.2.4

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/config.yml
Specify library name and version:  **daw_header_libraries/2.101.0**
---
> daw_header_libraries: add version 2.101.0

- recipes/libpqxx/all/conandata.yml
- recipes/libpqxx/config.yml
Specify library name and version:  **libpqxx/7.9.0**
libpqxx minor upgrade has been released!
---
> libpqxx: add version 7.9.0

- recipes/highway/all/conandata.yml
- recipes/highway/config.yml
Specify library name and version:  **highway/1.1.0**
---
> highway: add version 1.1.0

- recipes/scnlib/all/conandata.yml
- recipes/scnlib/config.yml
Specify library name and version:  **scnlib/2.0.2**
---
> scnlib: add version 2.0.2

- recipes/glog/all/conandata.yml
- recipes/glog/all/conanfile.py
- recipes/glog/all/test_package/CMakeLists.txt
- recipes/glog/config.yml
Specify library name and version:  **glog/0.7.0**
- add versio 0.7.0
- require C++14
- make libunwind transitive_libs which uses lzma
- update libunwind
---
> glog: add version 0.7.0

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
Specify library name and version:  **imgui/1.90.4**
---
> imgui: add version 1.90.4

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/1.3.2**
---
> meson: add version 1.3.2

- recipes/aws-c-s3/all/conandata.yml
- recipes/aws-c-s3/all/conanfile.py
- recipes/aws-c-s3/config.yml
Specify library name and version:  **aws-c-s3/0.3.24**
Needed to update aws-sdk-cpp (#20612)
CC: @toge
---
> aws-c-s3: add version 0.3.24

- recipes/libhal/all/conandata.yml
- recipes/libhal/config.yml
Specify library name and version:  **libhal/2.2.0**
---
> libhal: add version 2.2.0

- recipes/celero/all/conandata.yml
- recipes/celero/all/conanfile.py
- recipes/celero/all/patches/0005-2.9.0-drop-runtime.patch
- recipes/celero/all/patches/0006-2.9.0-fix-install-target.patch
- recipes/celero/config.yml
Specify library name and version:  **celero/***
---
> celero: add version 2.9.0, add patch descriptions

- recipes/tree-sitter/all/CMakeLists.txt
- recipes/tree-sitter/all/conandata.yml
- recipes/tree-sitter/all/conanfile.py
- recipes/tree-sitter/all/test_package/CMakeLists.txt
- recipes/tree-sitter/config.yml
Specify library name and version:  **tree-sitter/0.21.0**
---
> tree-sitter: add version 0.21.0

- recipes/hictk/all/conandata.yml
- recipes/hictk/config.yml
Specify library name and version:  **hictk/0.0.9**
---
> hictk: add v0.0.9

- recipes/glfw/all/conandata.yml
- recipes/glfw/config.yml
Specify library name and version:  **glfw/3.4**
---
> glfw: add version 3.4

- recipes/c-ares/all/conandata.yml
- recipes/c-ares/config.yml
Specify library name and version:  **c-ares/1.27.0**
---
> c-ares: add version 1.27.0

- recipes/fast_io/all/conandata.yml
- recipes/fast_io/all/conanfile.py
- recipes/fast_io/all/test_package/CMakeLists.txt
- recipes/fast_io/all/test_package/conanfile.py
- recipes/fast_io/all/test_package/test_package.cpp
- recipes/fast_io/config.yml
Specify library name and version:  **fast_io/***
---
> fast_io: add recipe

- recipes/utf8.h/all/conandata.yml
- recipes/utf8.h/all/test_package/test_package.cpp
- recipes/utf8.h/config.yml
Specify library name and version:  **utf8.h/cci.20240202**
---
> utf8.h: add version cci.20240202

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.7.0**
---
> simdjson: add version 3.7.0 

- recipes/daw_json_link/all/conandata.yml
- recipes/daw_json_link/all/conanfile.py
- recipes/daw_json_link/config.yml
Specify library name and version:  **daw_json_link/3.23.2**
---
> daw_json_link: add version 3.23.2

- recipes/poco/all/conandata.yml
- recipes/poco/config.yml
Specify library name and version:  **poco/1.13.2**
---
> poco: add version 1.13.2

- recipes/ruy/all/conandata.yml
- recipes/ruy/all/conanfile.py
- recipes/ruy/config.yml
Specify library name and version:  **ruy/cci.20231129**
Depends on #21759, which should be merged before this.
---
> ruy: Add cci.20231129

- recipes/mbedtls/all/conanfile.py
Specify library name and version:  **mbedtls/all**
---
> mbedtls: add required Win32 system_libs

- recipes/imath/all/conandata.yml
- recipes/imath/all/conanfile.py
- recipes/imath/all/patches/3.1.10-gcc5-backport.patch
- recipes/imath/config.yml
Specify library name and version:  **imath/3.1.10**
Just bumping the version of imath to the newest release
---
> Add version 3.1.10 for imath library

- recipes/openjpeg/all/conandata.yml
- recipes/openjpeg/all/conanfile.py
- recipes/openjpeg/config.yml
Specify library name and version:  **openjpeg/2.5.1**
---
> openjpeg: add version 2.5.1

- recipes/cpptrace/all/conandata.yml
- recipes/cpptrace/config.yml
Specify library name and version:  **cpptrace/0.4.1**
I'm the author :)
---
> cpptrace: Add 0.4.1

- recipes/openexr/3.x/conandata.yml
- recipes/openexr/config.yml
Specify library name and version:  **openexr/3.2.2**
Simple version bump
---
> OpenEXR add version 3.2.2

- recipes/nmos-cpp/all/conandata.yml
- recipes/nmos-cpp/all/conanfile.py
- recipes/nmos-cpp/config.yml
Specify library name and version:  **nmos-cpp/cci.20240223**
---
> nmos-cpp/cci.20240223: new release

- recipes/c4core/all/conanfile.py
> c4core: update fast_float/6.1.0

- .github/workflows/alert-community.yml
Add me for community alerts on packages I'm working on regularly right now.
As I'm currently working on the given packages which are all also from one pool (Academy software foundation) and them being some main dependencies in my fun project, I'd like to keep myself in the loop about MRs relating those packages.
---
> Add me for community alerts on packages I'm working on

- recipes/pdfium/all/conandata.yml
**pdfium/95.0.4629**
See https://github.com/madebr/pdfium-cmake/pull/2
---
> Fix build with libjpeg-turbo

- recipes/xorg/all/conanfile.py
Motivation: https://github.com/conan-io/conan-center-index/pull/20502#issuecomment-1757742671
---
> xorg/system: Add xcb-dri2, xcb-dri3, xcb-glx, and xcb-present

- recipes/influxdb-cpp/all/conandata.yml
- recipes/influxdb-cpp/config.yml
Specify library name and version:  **influxdb-cpp/***
There are several improvements and bug fixes since cci.20201227.
---
> influxdb-cpp: add version cci.20240102

- recipes/nghttp3/all/conandata.yml
- recipes/nghttp3/all/conanfile.py
- recipes/nghttp3/all/patches/1.2.0-0001-disable-always-static-build.patch
- recipes/nghttp3/config.yml
Specify library name and version:  **nghttp3/1.2.0**
---
> nghttp3: add version 1.2.0

- recipes/ssp/all/conandata.yml
- recipes/ssp/config.yml
Specify library name and version:  **ssp/1.7.2**
https://github.com/red0124/ssp/compare/v1.6.2...v1.7.2
---
> ssp: add version 1.7.2

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.1.9**
https://github.com/stephenberry/glaze/compare/v2.1.7...v2.1.9
---
> glaze: add version 2.1.9

- recipes/crcpp/all/conandata.yml
- recipes/crcpp/all/conanfile.py
- recipes/crcpp/all/test_package/CMakeLists.txt
- recipes/crcpp/all/test_package/conanfile.py
- recipes/crcpp/all/test_package/test_package.cpp
- recipes/crcpp/config.yml
Specify library name and version:  **crcpp/***
---
> crcpp: add recipe

- recipes/openimageio/all/conandata.yml
- recipes/openimageio/all/patches/2.5.9.0-cmake-targets.patch
- recipes/openimageio/config.yml
Specify library name and version:  **openimageio/2.5.9.0**
Version bump to the newest release version.
---
> OpenImageIO: Add version 2.5.9.0

- recipes/opencolorio/all/conandata.yml
- recipes/opencolorio/config.yml
Specify library name and version:  **opencolorio/2.3.2**
Version bumpd only
---
> Add OpenColorIO version 2.3.2

- recipes/hictk/all/conandata.yml
- recipes/hictk/config.yml
Specify library name and version:  **hictk/0.0.10**
---
> hictk: add v0.0.10

- recipes/openjpeg/all/conandata.yml
- recipes/openjpeg/config.yml
Specify library name and version:  **openjpeg/2.5.2**
---
> openjpeg: add version 2.5.2

- recipes/glfw/all/conanfile.py
> glfw: Bump wayland-protocols

- recipes/neargye-semver/all/conandata.yml
- recipes/neargye-semver/config.yml
Specify library name and version:  **neargye-semver/0.3.1**
https://github.com/Neargye/semver/compare/v0.3.0...v0.3.1
---
> neargye-semver: add version 0.3.1

- recipes/strong_type/all/conandata.yml
- recipes/strong_type/config.yml
Specify library name and version:  **strong_type/v14**
https://github.com/rollbear/strong_type/compare/v13...v14
---
> strong_type: add version v14

- recipes/openexr/3.x/conandata.yml
- recipes/openexr/config.yml
Specify library name and version:  **OpenEXR/3.2.3**
Just bumping the version which contains some small fixes, e.g. for problems found by fuzzing.
---
> OpenEXR: Add 3.2.3

- recipes/luau/all/conandata.yml
- recipes/luau/config.yml
Specify library name and version:  **luau/0.615**
https://github.com/luau-lang/luau/compare/0.610...0.615
---
> luau: add version 0.615

- recipes/fast_float/all/conandata.yml
Specify library name and version:  **fast_float/6.1.0**
Update digest. See https://github.com/fastfloat/fast_float/pull/241 for more details.
---
> fast_float: fix digest

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.2.1**
https://github.com/stephenberry/glaze/compare/v2.1.9...v2.2.1
---
> glaze: add version 2.2.1

- recipes/cppcheck/all/conandata.yml
- recipes/cppcheck/config.yml
> [cppcheck] Add new version and remove old patch versions

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.7.7**
https://github.com/ada-url/ada/compare/v2.7.5...v2.7.7
---
> ada: add version 2.7.7

- recipes/libavif/all/conandata.yml
- recipes/libavif/config.yml
Specify library name and version:  **libavif/1.0.4**
https://github.com/AOMediaCodec/libavif/compare/v1.0.3...v1.0.4
---
> libavif: add version 1.0.4

- recipes/xz_utils/cmake/conandata.yml
- recipes/xz_utils/config.yml
Specify library name and version:  **xz_utils/5.6.1**
---
> xz_utils: add version 5.6.1

- recipes/oatpp-libressl/all/conanfile.py
Specify library name and version:  **oatpp-libressl/all**
> oatpp-libressl: Fix header propagation, moderenize a bit

- recipes/winreg/all/conandata.yml
- recipes/winreg/all/conanfile.py
- recipes/winreg/all/test_package/CMakeLists.txt
- recipes/winreg/all/test_package/conanfile.py
- recipes/winreg/all/test_package/test_package.cpp
- recipes/winreg/config.yml
Specify library name and version:  **winreg/6.2.0**
---
> winreg: add winreg 6.2.0

- recipes/easyexif/all/CMakeLists.txt
- recipes/easyexif/all/conanfile.py
- recipes/easyexif/all/test_package/CMakeLists.txt
- recipes/easyexif/all/test_package/conanfile.py
Specify library name and version:  **easyexif/1.0**
> easyexif: Fix test_package and modernize a tiny bit more

- recipes/kmod/all/conandata.yml
- recipes/kmod/config.yml
> kmod: add v31

- recipes/openapi-generator/all/conandata.yml
- recipes/openapi-generator/config.yml
I removed old versions according the CCI policy
---
> [openapi-generator] Bump version 7.4.0 and remove older

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.45.2**
https://github.com/sqlite/sqlite/compare/version-3.45.1...version-3.45.2
---
> sqlite3: add version 3.45.2

- recipes/sfl/all/conandata.yml
- recipes/sfl/config.yml
Specify library name and version:  **sfl/1.3.0**
https://github.com/slavenf/sfl-library/compare/1.2.4...1.3.0
---
> sfl: add version 1.3.0

- recipes/cpptrace/all/conandata.yml
- recipes/cpptrace/config.yml
Specify library name and version:  **cpptrace/0.5.0**
I'm the author
---
> cpptrace: add 0.5.0

- recipes/iguana/all/conandata.yml
- recipes/iguana/all/conanfile.py
- recipes/iguana/all/test_package/CMakeLists.txt
- recipes/iguana/all/test_package/conanfile.py
- recipes/iguana/all/test_package/test_package.cpp
- recipes/iguana/config.yml
Specify library name and version:  **iguana/***
---
> iguana: add recipe

- recipes/simde/all/conandata.yml
- recipes/simde/config.yml
Specify library name and version:  **simde/0.8.0**
https://github.com/simd-everywhere/simde/compare/v0.7.6...v0.8.0
---
> simde: add version 0.8.0

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/config.yml
Specify library name and version:  **wasmtime/18.0.3**
---
> wasmtime: add version 18.0.3

- recipes/xz_utils/cmake/conanfile.py
> xz_utils: skip building tests

- recipes/dlib/all/conanfile.py
Specify library name and version:  **dlib/all**
---
> dlib: use libpng version range

- recipes/imagl/all/conanfile.py
Specify library name and version:  **imagl/all**
---
> imagl: use libpng version range

- recipes/sail/all/conanfile.py
Specify library name and version:  **sail/all**
---
> sail: use version range for libpng

- recipes/pcl/all/conanfile.py
Specify library name and version:  **pcl/all**
---
> pcl: use libpng version range

- recipes/libgd/all/conanfile.py
Specify library name and version:  **libgd/all**
---
> libgd: use libpng version range

- recipes/dnet/all/conandata.yml
- recipes/dnet/config.yml
Specify library name and version:  **dnet/1.18.0**
https://github.com/ofalk/libdnet/compare/libdnet-1.17.0...libdnet-1.18.0
---
> dnet: add version 1.18.0

- recipes/pngpp/all/conanfile.py
Specify library name and version:  **pngpp/all**
---
> pngpp: use libpng version range

- recipes/libfork/all/conandata.yml
- recipes/libfork/all/conanfile.py
- recipes/libfork/all/test_package/CMakeLists.txt
- recipes/libfork/all/test_package/conanfile.py
- recipes/libfork/all/test_package/test_package.cpp
- recipes/libfork/config.yml
libfork 2.1.1
Libfork is a fast multithreading framework for c++ employing the commonly known the fork-join methodology to branch split tasks in a smart way using continuation passing. It doesn't depend on anything but requires c++20 coroutines. Unfortunately due to a bug in msvc compiler that will hopefully soon be fixed it shouldn't be built with msvc. I'm not the author of this package but I'm working closely together with him.
---
> added libfork

- recipes/libharu/all/conanfile.py
Specify library name and version:  **libharu/all**
---
> libharu: use libpng version range

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/config.yml
Specify library name and version:  **simdutf/5.0.0**
https://github.com/simdutf/simdutf/compare/v4.0.9...v5.0.0
---
> simdutf: add version 5.0.0

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Specify library name and version:  **meson/1.4.0**
https://github.com/mesonbuild/meson/compare/1.3.2...1.4.0
---
> meson: add version 1.4.0

- recipes/tree-gen/all/conandata.yml
- recipes/tree-gen/config.yml
Specify library name and version:  **lib/1.0.7**
Bump version to 1.0.7.
---
> Add tree-gen 1.0.7.

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.3.1**
https://github.com/stephenberry/glaze/compare/v2.3.0...v2.3.1
---
> glaze: add version 2.3.1

- recipes/roaring/all/conandata.yml
- recipes/roaring/config.yml
Specify library name and version:  **roaring/3.0.0**
https://github.com/RoaringBitmap/CRoaring/compare/v2.1.2...v3.0.0
---
> roaring: add version 3.0.0

- recipes/cpptrace/all/conandata.yml
- recipes/cpptrace/config.yml
Specify library name and version:  **cpptrace/0.5.1**
I'm the maintainer
---
> cpptrace: add version 0.5.1

- recipes/openjdk/all/conandata.yml
- recipes/openjdk/config.yml
Specify library name and version:  **openjdk/21.0.2**
---
> openjdk: add version 21.0.2

- recipes/simfil/all/conandata.yml
- recipes/simfil/all/conanfile.py
- recipes/simfil/config.yml
Specify library name and version:  **simfil/0.1.2**
Updating package to version 0.1.2.
---
> simfil: Bump 0.1.2

- recipes/sfl/all/conandata.yml
- recipes/sfl/config.yml
Specify library name and version:  **sfl/1.3.1**
https://github.com/slavenf/sfl-library/compare/1.3.0...1.3.1
---
> sfl: add version 1.3.1

- recipes/jom/all/conandata.yml
- recipes/jom/all/conanfile.py
- recipes/jom/config.yml
> jom: add v1.1.4

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.3.2**
https://github.com/stephenberry/glaze/compare/v2.3.1...v2.3.2
---
> glaze: add version 2.3.2

- recipes/wasmer/all/conandata.yml
- recipes/wasmer/config.yml
Specify library name and version:  **wasmer/4.2.7**
---
> wasmer: add version 4.2.7

- recipes/libassert/all/conandata.yml
- recipes/libassert/all/conanfile.py
- recipes/libassert/all/patches/2.0.0/0001-fix-export-and-include.patch
- recipes/libassert/all/test_package/CMakeLists.txt
- recipes/libassert/all/test_package/conanfile.py
- recipes/libassert/all/test_package/test_package.cpp
- recipes/libassert/all/test_v1_package/CMakeLists.txt
- recipes/libassert/all/test_v1_package/conanfile.py
- recipes/libassert/config.yml
Specify library name and version:  **libassert/2.0**
I'm the author of the library
---
> libassert: add 2.0.0

- recipes/libboxes/all/conandata.yml
- recipes/libboxes/all/conanfile.py
- recipes/libboxes/all/test_package/CMakeLists.txt
- recipes/libboxes/all/test_package/conanfile.py
- recipes/libboxes/all/test_package/src/example.cpp
- recipes/libboxes/config.yml
**libboxes/0.1.1**
I'm the author of the library.  The library is in its infancy ATM but I plan to actively contribute towards it.
fixes #22906
---
> libboxes: add recipe for v0.1.1

- recipes/hictk/all/conandata.yml
- recipes/hictk/all/conanfile.py
- recipes/hictk/config.yml
Specify library name and version:  **hictk/all**
---
> hictk: add v0.0.11, bump deps and add missing define

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  **cmake/3.29.0**
---
> cmake: add version `3.29.0`

- recipes/ensmallen/all/conandata.yml
- recipes/ensmallen/all/conanfile.py
- recipes/ensmallen/config.yml
> ensmallen: add v2.21.0

- recipes/libftp/all/conandata.yml
- recipes/libftp/all/conanfile.py
- recipes/libftp/all/test_package/CMakeLists.txt
- recipes/libftp/all/test_package/conanfile.py
- recipes/libftp/all/test_package/test_package.cpp
- recipes/libftp/config.yml
Specify library name and version:  **libftp/***
---
> libftp: add recipe

- recipes/libunwind/all/conanfile.py
> libunwind: Downgrade xz_utils to mitigate CVE-2024-3094

- recipes/cpython/all/conanfile.py
> cpython: Downgrade xz_utils to mitigate CVE-2024-3094

- recipes/proxy/all/conandata.yml
- recipes/proxy/all/conanfile.py
- recipes/proxy/all/test_package/CMakeLists.txt
- recipes/proxy/all/test_package/conanfile.py
- recipes/proxy/all/test_package/test_package.cpp
- recipes/proxy/config.yml
Adds `proxy`:  https://github.com/microsoft/proxy
Proxy: Next Generation Polymorphism in C++
The "proxy" is a single-header, cross-platform C++ library that Microsoft uses to make runtime polymorphism easier to implement and faster. Please find the design details at https://wg21.link/p0957.
[![Packaging status](https://repology.org/badge/tiny-repos/proxy.svg)](https://repology.org/project/proxy/versions)
> proxy: new recipe

- recipes/7bitdi/all/conandata.yml
- recipes/7bitdi/config.yml
Specify library name and version:  **7bitdi/3.0.0**
https://github.com/7bitcoder/7bitDI/compare/v2.1.0...v3.0.0
---
> 7bitdi: add version 3.0.0

- recipes/c-ares/all/conandata.yml
- recipes/c-ares/config.yml
Specify library name and version:  **c-ares/1.28.1**
https://github.com/c-ares/c-ares/compare/cares-1_27_0...cares-1_28_1
---
> c-ares: add version 1.28.1

- recipes/wiringpi/all/CMakeLists.txt
- recipes/wiringpi/all/conandata.yml
- recipes/wiringpi/all/conanfile.py
- recipes/wiringpi/config.yml
Specify library name and version:  **wiringpi/3.2**
https://github.com/WiringPi/WiringPi/compare/2.61-1...3.2
---
> wiringpi: add version 3.2

- recipes/z3/all/conandata.yml
- recipes/z3/config.yml
Specify library name and version:  **z3/4.13.0**
https://github.com/Z3Prover/z3/compare/z3-4.12.4...z3-4.13.0
---
> z3: add version 4.13.0

- recipes/exiv2/all/conandata.yml
- recipes/exiv2/all/conanfile.py
- recipes/exiv2/config.yml
Based on https://repology.org/project/exiv2/information
> exiv2: add v0.28.2, bump deps, drop vulnerable v0.28.0

- recipes/toon/all/conandata.yml
- recipes/toon/all/conanfile.py
- recipes/toon/all/config.hh
- recipes/toon/all/patches/001-bugfixes-backport.patch
- recipes/toon/all/test_package/CMakeLists.txt
- recipes/toon/all/test_package/conanfile.py
- recipes/toon/all/test_package/test_package.cpp
- recipes/toon/config.yml
Adds TooN: 
https://codedocs.xyz/edrosten/TooN/
https://github.com/edrosten/TooN
The TooN library is a set of C++14 header files which provide basic numerics facilities.
[![Packaging status](https://repology.org/badge/tiny-repos/toon.svg)](https://repology.org/project/toon/versions)
Required for #23216.
> toon: new recipe

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.4.0**
https://github.com/stephenberry/glaze/compare/v2.3.2...v2.4.0
---
> glaze: add version 2.4.0

- recipes/cpp-peglib/1.x.x/conandata.yml
- recipes/cpp-peglib/config.yml
Specify library name and version:  **cpp-peglib/1.8.7**
https://github.com/yhirose/cpp-peglib/compare/v1.8.6...v1.8.7
---
> cpp-peglib: add version 1.8.7

- recipes/pybind11/all/conandata.yml
- recipes/pybind11/config.yml
https://github.com/pybind/pybind11/releases/tag/v2.12.0
> pybind: add v2.12.0

- recipes/kuba-zip/all/conandata.yml
- recipes/kuba-zip/config.yml
Specify library name and version:  **kuba-zip/0.3.2**
https://github.com/kuba--/zip/compare/v0.3.1...v0.3.2
---
> kuba-zip: add version 0.3.2

- recipes/libressl/all/conandata.yml
- recipes/libressl/all/conanfile.py
- recipes/libressl/config.yml
Specify library name and version:  **libressl/3.9.1**
> libressl: Add version 3.9.1

- recipes/cpp-peglib/1.x.x/conandata.yml
- recipes/cpp-peglib/config.yml
Specify library name and version:  **cpp-peglib/1.8.8**
1.8.8 is small update, but fix the performance problem.
https://github.com/yhirose/cpp-peglib/compare/v1.8.7...v1.8.8
---
> cpp-peglib: add version 1.8.8

- .c3i/config_v1.yml
- .c3i/config_v2.yml
> [config] Update conan versions to 2.2.2 and 1.63.0

- docs/changelog.md
Running new Conan versions 1.63.0 and 2.2.2 in the CI. Both are the latest version in their majors.
---
> [docs] Update changelog 2024-04-03

- recipes/sentry-native/all/conandata.yml
- recipes/sentry-native/config.yml
> [sentry-native] Bump 0.7.2 version

- recipes/openexr/3.x/conandata.yml
- recipes/openexr/config.yml
Specify library name and version:  **openexr/3.2.4**
Just a version bump for openexr.
---
> OpenEXR: Add version 3.2.4

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/config.yml
Specify library name and version:  **simdutf/5.2.2**
https://github.com/simdutf/simdutf/compare/v5.0.0...v5.2.2
---
> simdutf: add version 5.2.2

- recipes/poco/all/conandata.yml
- recipes/poco/config.yml
Specify library name and version:  **poco/1.13.3**
https://github.com/pocoproject/poco/compare/poco-1.13.2-release...poco-1.13.3-release
---
> poco: add version 1.13.3

- recipes/snappy/all/conandata.yml
- recipes/snappy/all/patches/1.2.0-0003-fix-clobber-list-older-llvm.patch
- recipes/snappy/all/patches/1.2.0-0004-rtti-by-default.patch
- recipes/snappy/config.yml
Specify library name and version:  **snappy/1.2.0**
https://github.com/google/snappy/compare/1.1.10...1.2.0
---
> snappy: add version 1.2.0

- recipes/sdl_mixer/cmake/conanfile.py
Specify library name and version:  sdl_mixer/all
Prettier error messages
> sdl_mixer: Validate out invalid requirement options

- recipes/poco/all/conandata.yml
Specify library name and version:  **poco/1.13.3**
fixes: https://github.com/conan-io/conan-center-index/issues/23407
---
> poco: fix poco 1.13.3 sha256

- recipes/7bitdi/all/conandata.yml
- recipes/7bitdi/config.yml
Specify library name and version:  **7bitdi/3.1.0**
https://github.com/7bitcoder/7bitDI/compare/v3.0.0...v3.1.0
---
> 7bitdi: add version 3.1.0

- recipes/wolfssl/all/conandata.yml
- recipes/wolfssl/all/conanfile.py
- recipes/wolfssl/config.yml
Specify library name and version:  **wolfssl/5.7.0**
https://github.com/wolfSSL/wolfssl/compare/v5.6.6-stable...v5.7.0-stable
---
> wolfssl: add version 5.7.0

- recipes/libpq/all/conandata.yml
- recipes/libpq/config.yml
Specify library name and version:  **libpq/15.5**
---
> libpq: add 15.5

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.9.1**
https://github.com/simdjson/simdjson/compare/v3.8.0...v3.9.1
---
> simdjson: add version 3.9.1

- recipes/cpp-dump/all/conandata.yml
- recipes/cpp-dump/all/conanfile.py
- recipes/cpp-dump/all/test_package/CMakeLists.txt
- recipes/cpp-dump/all/test_package/conanfile.py
- recipes/cpp-dump/all/test_package/test_package.cpp
- recipes/cpp-dump/config.yml
Specify library name and version:  **cpp-dump/0.5.0**
---
> cpp-dump: add recipe

- recipes/libxlsxwriter/all/conandata.yml
- recipes/libxlsxwriter/all/patches/1.1.7-0001-fix-cmake.patch
- recipes/libxlsxwriter/config.yml
Specify library name and version:  **libxlsxwriter/1.1.7**
https://github.com/jmcnamara/libxlsxwriter/compare/RELEASE_1.1.5...RELEASE_1.1.7
---
> libxlsxwriter: add version 1.1.7

- recipes/yyjson/all/conandata.yml
- recipes/yyjson/all/conanfile.py
- recipes/yyjson/config.yml
Specify library name and version:  **yyjson/0.9.0**
https://github.com/ibireme/yyjson/compare/0.8.0...0.9.0
---
> yyjson : add version 0.9.0

- recipes/asio/all/conandata.yml
- recipes/asio/config.yml
Specify library name and version:  **asio/1.30.1**
https://github.com/chriskohlhoff/asio/compare/asio-1-29-0...asio-1-30-1
---
> asio: add version 1.30.1

- .c3i/config_v1.yml
> [config] Update conan version to 1.64.0

- recipes/physfs/all/conandata.yml
- recipes/physfs/all/conanfile.py
- recipes/physfs/config.yml
> physfs: add v3.2.0

- recipes/bshoshany-thread-pool/all/conandata.yml
- recipes/bshoshany-thread-pool/config.yml
Specify library name and version:  **bshoshany-thread-pool/4.1.0**
Update to the latest version.
---
> bshoshany-thread-pool: add version 4.1.0

- recipes/chunkio/all/conandata.yml
- recipes/chunkio/all/conanfile.py
- recipes/chunkio/all/patches/1.5.2-0001-add-installer.patch
- recipes/chunkio/all/test_package/CMakeLists.txt
- recipes/chunkio/all/test_package/test_package_1_5_0.c
- recipes/chunkio/config.yml
Specify library name and version:  **chunkio/***
---
> chunkio: add version 1.5.2, update url

- recipes/rocksdb/all/conandata.yml
- recipes/rocksdb/all/conanfile.py
- recipes/rocksdb/config.yml
Specify library name and version:  **meson/9.0.0**
https://github.com/facebook/rocksdb/compare/v8.8.1...v9.0.0
---
> rocksdb: add version 9.0.0

- recipes/ada/all/conandata.yml
- recipes/ada/config.yml
Specify library name and version:  **ada/2.7.8**
https://github.com/ada-url/ada/compare/v2.7.7...v2.7.8
---
> ada: add version 2.7.8

- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Specify library name and version:  **sqlite3/3.45.3**
https://github.com/sqlite/sqlite/compare/version-3.45.2...version-3.45.3
---
> sqlite3: add version 3.45.3

- recipes/perfetto/all/conandata.yml
- recipes/perfetto/all/conanfile.py
- recipes/perfetto/config.yml
Specify library name and version:  **perfetto/44.0**
https://github.com/google/perfetto/compare/v43.1...v44.0
---
> perfetto: add version 44.0

- recipes/harfbuzz/all/conanfile.py
> harfbuzz: Bump glib to 2.78.3 to avoid conflicts

- recipes/enet/all/conandata.yml
- recipes/enet/all/patches/fix-cmake-1.3.18.patch
- recipes/enet/config.yml
Specify library name and version:  **enet/1.3.18**
---
> add enet/1.3.18

- recipes/leopard/all/conandata.yml
- recipes/leopard/all/conanfile.py
- recipes/leopard/all/test_package/CMakeLists.txt
- recipes/leopard/all/test_package/conanfile.py
- recipes/leopard/all/test_package/test_package.cpp
- recipes/leopard/config.yml
Specify library name and version:  **leopard/2.0.0**
---
> leopard: add recipe

- recipes/sfl/all/conandata.yml
- recipes/sfl/config.yml
Specify library name and version:  **sfl/1.4.0**
https://github.com/slavenf/sfl-library/compare/1.3.1...1.4.0
---
> sfl: add version 1.4.0

- recipes/libwebp/all/conandata.yml
- recipes/libwebp/all/patches/1.4.0-0001-fix-cmake.patch
- recipes/libwebp/config.yml
Specify library name and version:  **libwebp/1.4.0**
---
> libwebp: add 1.4.0

- recipes/proxy/all/conandata.yml
- recipes/proxy/config.yml
Specify library name and version:  **proxy/2.3.1**
https://github.com/microsoft/proxy/compare/2.3.0...2.3.1
---
> proxy: add version 2.3.1

- recipes/asio/all/conandata.yml
- recipes/asio/config.yml
Specify library name and version:  **asio/1.30.2**
https://github.com/chriskohlhoff/asio/compare/asio-1-30-1...asio-1-30-2
---
> asio: add version 1.30.2

- recipes/libxslt/all/conanfile.py
> libxslt: bump libxml2 to v2.12.6

- recipes/streaming-percentiles/all/conandata.yml
- recipes/streaming-percentiles/all/conanfile.py
- recipes/streaming-percentiles/all/patches/3.1.0-0001-add-includes.patch
- recipes/streaming-percentiles/all/test_package/CMakeLists.txt
- recipes/streaming-percentiles/all/test_package/conanfile.py
- recipes/streaming-percentiles/all/test_package/test_package.cpp
- recipes/streaming-percentiles/config.yml
Specify library name and version:  **streaming-percentile/***
---
> streaming-percentile: add recipe

- recipes/aws-kvs-pic/all/conandata.yml
- recipes/aws-kvs-pic/all/conanfile.py
- recipes/aws-kvs-pic/config.yml
Specify library name and version:  **aws-kvs-pic/1.1.0**
---
> aws-kvs-pic: add version v1.1.0

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  **cmake/3.29.2**
---
> cmake: add version 3.29.2

- recipes/onetbb/all/conandata.yml
- recipes/onetbb/all/conanfile.py
- recipes/onetbb/config.yml
Specify library name and version:  **onetbb/2021.12.0**
---
> onetbb: add 2021.12.0

- recipes/annoy/all/conandata.yml
- recipes/annoy/all/conanfile.py
- recipes/annoy/all/test_package/CMakeLists.txt
- recipes/annoy/all/test_package/conanfile.py
- recipes/annoy/all/test_package/test_package.cpp
- recipes/annoy/config.yml
Adds Annoy: https://github.com/spotify/annoy
Approximate Nearest Neighbors in C++/Python optimized for memory usage and loading/saving to disk.
[![Packaging status](https://repology.org/badge/vertical-allrepos/annoy.svg)](https://repology.org/project/annoy/versions)
> annoy: new recipe

- recipes/bitsery/all/conandata.yml
- recipes/bitsery/all/conanfile.py
- recipes/bitsery/config.yml
> bitsery: add package_type

- recipes/rocksdb/all/conandata.yml
- recipes/rocksdb/config.yml
Specify library name and version:  **rocksdb/9.1.0**
https://github.com/facebook/rocksdb/compare/v9.0.0...v9.1.0
---
> rocksdb: add version 9.1.0

- recipes/libftp/all/conandata.yml
- recipes/libftp/all/conanfile.py
- recipes/libftp/config.yml
Specify library name and version:  **libftp/0.5.0**
https://github.com/deniskovalchuk/libftp/compare/v0.4.1...v0.5.0
---
> libftp: add version 0.5.0

- recipes/freetype/all/conandata.yml
- recipes/freetype/all/conanfile.py
Specify library name and version:  **freetype/***
---
> freetype: drop dead code

- recipes/nng/all/conandata.yml
- recipes/nng/config.yml
Specify library name and version:  **nng/1.8.0**
https://github.com/nanomsg/nng/compare/v1.7.3...v1.8.0
---
> nng: add version 1.8.0

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Specify library name and version:  **glaze/2.5.4**
https://github.com/stephenberry/glaze/compare/v2.5.3...v2.5.4
---
> glaze: add version 2.5.4

- recipes/cppcheck/all/conandata.yml
- recipes/cppcheck/all/conanfile.py
- recipes/cppcheck/config.yml
> Add cppcheck 2.14

- recipes/libenvpp/all/conandata.yml
- recipes/libenvpp/config.yml
Specify library name and version:  **libenvpp/1.4.1**
https://github.com/ph3at/libenvpp/compare/v1.4.0...v1.4.1
---
> libenvpp: add version 1.4.1

- recipes/rotor/all/conandata.yml
- recipes/rotor/all/conanfile.py
- recipes/rotor/config.yml
Specify library name and version:  **rotor/0.30**
I'm library author.
---
> Add rotor v0.30

- recipes/type_safe/all/conandata.yml
- recipes/type_safe/config.yml
Specify library name and version:  **type_safe/0.2.4**
https://github.com/foonathan/type_safe/compare/v0.2.3...v0.2.4
---
> type_safe: add version 0.2.4

- recipes/libdrm/all/conanfile.py
https://gitlab.freedesktop.org/mesa/drm/-/blob/main/meson_options.txt?ref_type=heads#L85
Bump pkgconf to 2.2.0.
> libdrm: Disable man-page generation

- recipes/box2d/2.4.x/conanfile.py
Specify library name and version:  **box2d/4.x**
---
> box2d: modernize

- recipes/c4core/all/conandata.yml
- recipes/c4core/config.yml
Specify library name and version:  **c4core/0.2.0**
https://github.com/biojppm/c4core/compare/v0.1.11...v0.2.0
---
> c4core: add version 0.2.0

- recipes/qarchive/all/conanfile.py
since https://github.com/conan-io/conan-center-index/commit/c4495e47cf56cdc97b0815bdd40dcec56dd11a6a
Specify library name and version:  **qarchive/***
---
> qarchive: use maintained version of libarchive

- recipes/proxy/all/conandata.yml
- recipes/proxy/config.yml
Specify library name and version:  **proxy/2.3.2**
https://github.com/microsoft/proxy/compare/2.3.1...2.3.2
---
> proxy: add version 2.3.2

- recipes/pciutils/all/conandata.yml
- recipes/pciutils/config.yml
Specify library name and version:  **pciutils/3.12.0**
https://github.com/pciutils/pciutils/compare/v3.10.0...v3.12.0
---
> pciutils: add version 3.12.0

- recipes/qcbor/all/conandata.yml
- recipes/qcbor/config.yml
Specify library name and version:  **qcbor/1.3**
https://github.com/laurencelundblade/QCBOR/compare/v1.2...v1.3
---
> qcbor: add version 1.3

- recipes/libvpx/all/conandata.yml
- recipes/libvpx/config.yml
Specify library name and version:  **libvpx/1.14.0**
https://github.com/webmproject/libvpx/compare/v1.13.1...v1.14.0
---
> libvpx: addversion 1.14.0

- recipes/libunwind/all/conandata.yml
- recipes/libunwind/config.yml
Specify library name and version:  **libunwind/1.8.1**
https://github.com/libunwind/libunwind/compare/v1.8.0...v1.8.1
---
> libunwind: add version 1.8.1

- recipes/cpptrace/all/conandata.yml
- recipes/cpptrace/config.yml
Specify library name and version:  **cpptrace/0.5.3**
I'm the author
---
> cpptrace: Add v0.5.3

- recipes/ohnet/all/conandata.yml
- recipes/ohnet/all/patches/0001-makefile-1.36.5344.patch
- recipes/ohnet/config.yml
Specify library name and version:  **ohNet/1.36.5344**
---
> ohNet: Add 1.36.5344

- recipes/cr/all/conandata.yml
- recipes/cr/all/conanfile.py
- recipes/cr/all/test_package/CMakeLists.txt
- recipes/cr/all/test_package/conanfile.py
- recipes/cr/all/test_package/test_package.cpp
- recipes/cr/config.yml
Adds cr: https://github.com/fungos/cr
cr.h: A Simple C Hot Reload Header-only Library
[![Packaging status](https://repology.org/badge/tiny-repos/cr.svg)](https://repology.org/project/cr/versions)
> cr: new recipe

- recipes/mbedtls/all/conandata.yml
- recipes/mbedtls/config.yml
Specify library name and version:  **mbedtls/2.28.8**
Resolves #23650
> mbedtls: Add 2.28.8

- recipes/libtorrent/all/conandata.yml
- recipes/libtorrent/all/conanfile.py
- recipes/libtorrent/config.yml
Specify library name and version:  **libtorrent/2.0.10**
Resolves #23643
> libtorrent: Add 2.0.10

- recipes/cpptrace/all/conandata.yml
- recipes/cpptrace/config.yml
Specify library name and version:  **cpptrace/0.5.4**
I'm the author, just a super quick patch release
---
> cpptrace: Update 0.5.4

- recipes/cpp-yyjson/all/conandata.yml
- recipes/cpp-yyjson/all/conanfile.py
- recipes/cpp-yyjson/all/test_package/CMakeLists.txt
- recipes/cpp-yyjson/all/test_package/conanfile.py
- recipes/cpp-yyjson/all/test_package/test_package.cpp
- recipes/cpp-yyjson/config.yml
Specify library name and version:  **cpp-yyjson/***
cpp-yyjson is a C++20 wrapper for yyjson.
---
> cpp-yyjson: add recipe

- recipes/enumbitmask/.gitignore
- recipes/enumbitmask/all/conandata.yml
- recipes/enumbitmask/all/conanfile.py
- recipes/enumbitmask/all/test_package/CMakeLists.txt
- recipes/enumbitmask/all/test_package/conanfile.py
- recipes/enumbitmask/all/test_package/test_package.cpp
- recipes/enumbitmask/config.yml
Specify library name and version:  **enumbitmask/1.0**
---
> enumbitmask add recipe

- recipes/spdlog/all/conandata.yml
- recipes/spdlog/config.yml
Specify library name and version:  **spdlog/1.14.1**
https://github.com/gabime/spdlog/compare/v1.14.0...v1.14.1
---
> spdlog: add version 1.14.1

- recipes/leopard/all/conandata.yml
- recipes/leopard/all/test_package/CMakeLists.txt
- recipes/leopard/all/test_package/test_package.cpp
- recipes/leopard/config.yml
Specify library name and version:  **leopard/2.1.0**
https://github.com/hosseinmoein/Leopard/compare/2.0.0...2.1.0
---
> leopard: add version 2.1.0

- recipes/simde/all/conandata.yml
- recipes/simde/config.yml
Specify library name and version:  **simde/0.8.2**
https://github.com/simd-everywhere/simde/compare/v0.8.0...v0.8.2
---
> simde: add version 0.8.2

- recipes/openimageio/all/conandata.yml
- recipes/openimageio/config.yml
Specify library name and version:  **openimageio/2.5.11.0**
Bumping to the monthly release.
---
> OpenImageIO: Add version 2.5.11.0

- recipes/simfil/all/conandata.yml
- recipes/simfil/config.yml
Specify library name and version:  **simfil/0.1.3**
---
> simfil: Add version 0.1.3

- recipes/cli11/all/conandata.yml
- recipes/cli11/config.yml
Specify library name and version:  **cli11/2.4.2**
https://github.com/CLIUtils/CLI11/compare/v2.4.1...v2.4.2
---
> cli11: add version 2.4.2

- recipes/clove-unit/all/conandata.yml
- recipes/clove-unit/all/conanfile.py
- recipes/clove-unit/config.yml
Specify library name and version:  **clove-unit/***
https://github.com/fdefelici/clove-unit/compare/v2.4.1...v2.4.4
---
> clove-unit: add version 2.4.4

- recipes/sdl/all/conandata.yml
- recipes/sdl/config.yml
Specify library name and version:  **sdl/2.30.3**
https://github.com/libsdl-org/SDL/compare/release-2.30.2...release-2.30.3
---
> sdl: add version 2.30.3

- recipes/taskflow/all/conandata.yml
- recipes/taskflow/all/conanfile.py
- recipes/taskflow/config.yml
Specify library name and version:  **taskflow/3.7.0**
https://github.com/taskflow/taskflow/compare/v3.6.0...v3.7.0
---
> taskflow: add version 3.7.0

- recipes/morton-nd/all/conandata.yml
- recipes/morton-nd/all/conanfile.py
- recipes/morton-nd/all/patches/0001-v3.0.0-fix-include-cstdint.patch
- recipes/morton-nd/all/patches/0001-v4.0.0-fix-include-cstdint.patch
- recipes/morton-nd/all/test_package/conanfile.py
- recipes/morton-nd/all/test_v1_package/CMakeLists.txt
> morton-nd: add package_type

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Specify library name and version:  **cmake/3.29.3**
---
> cmake: add version 3.29.3

- recipes/librdkafka/all/conandata.yml
- recipes/librdkafka/config.yml
Specify library name and version:  **librdkafka/2.4.0**
https://github.com/confluentinc/librdkafka/compare/v2.3.0...v2.4.0
---
> librdkafka: add version 2.4.0

- recipes/sbepp/all/conandata.yml
- recipes/sbepp/config.yml
Specify library name and version:  **sbepp/1.3.0**
I'm the author, releasing version `1.3.0`.
---
> sbepp: add version 1.3.0

- recipes/rdma-core/all/conandata.yml
- recipes/rdma-core/all/conanfile.py
- recipes/rdma-core/config.yml
Also to fix the missing binary issues in #18980.
> rdma-core: add v51.0

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Specify library name and version:  **simdjson/3.9.2**
https://github.com/simdjson/simdjson/compare/v3.9.1...v3.9.2
---
> simdjson: add version 3.9.2
