conan-io/conan-center-index

recipes/arrow/all/conandata.yml
recipes/arrow/config.yml

Specify library name and version:  **arrow/16.0.0**
https://github.com/apache/arrow/compare/apache-arrow-15.0.0...apache-arrow-16.0.0
---

arrow: add version 16.0.0

---

recipes/lightgbm/all/conandata.yml
recipes/lightgbm/all/conanfile.py
recipes/lightgbm/config.yml

Specify library name and version:  **lightgbm/4.3.0**
https://github.com/microsoft/LightGBM/compare/v4.2.0...v4.3.0
---

lightgbm: add version 4.3.0

---

recipes/openblas/all/conandata.yml
recipes/openblas/all/conanfile.py
recipes/openblas/config.yml

https://github.com/OpenMathLib/OpenBLAS/releases/tag/v0.3.27
I also 
* cleaned up some messier parts of the recipe (mostly badly-formatted patching),
* added `build_relapack` and `use_locking` options,
* set CMP0077 to ensure that fPIC is handled correctly.

openblas: add v0.3.27, recipe cleanup, add options

---

recipes/proxy/all/conandata.yml
recipes/proxy/config.yml

Specify library name and version:  **proxy/2.4.0**
https://github.com/microsoft/proxy/compare/2.3.2...2.4.0
---

proxy: add version 2.4.0

---

recipes/perfetto/all/conandata.yml
recipes/perfetto/config.yml

Specify library name and version:  **perfetto/45.0**
https://github.com/google/perfetto/compare/v44.0...v45.0
---

perfetto: add version 45.0

---

recipes/hwdata/all/conandata.yml
recipes/hwdata/config.yml

Specify library name and version:  **hwdata/0.382**
https://github.com/vcrhonek/hwdata/compare/v0.378...v0.382
---

hwdata: add version 0.382

---

recipes/liburing/all/conandata.yml
recipes/liburing/all/conanfile.py
recipes/liburing/config.yml

Specify library name and version:  **liburning/2.6**
https://github.com/axboe/liburing/compare/liburing-2.5...liburing-2.6
---

liburning: add version 2.6

---

recipes/libfork/all/conandata.yml
recipes/libfork/all/conanfile.py
recipes/libfork/all/test_package/CMakeLists.txt
recipes/libfork/all/test_package/conanfile.py
recipes/libfork/config.yml

Specify library name and version:  **libfork/3.8.0**
https://github.com/ConorWilliams/libfork/compare/v3.7.2...v3.8.0
---

libfork: add version 3.8.0

---

recipes/cjson/all/conandata.yml
recipes/cjson/all/conanfile.py
recipes/cjson/config.yml

Specify library name and version:  **cjson/1.7.18**
https://github.com/DaveGamble/cJSON/compare/v1.7.17...v1.7.18
---

cjson: add version 1.7.18

---

recipes/roaring/all/conandata.yml
recipes/roaring/config.yml

Specify library name and version:  **roaring/4.0.0**
https://github.com/RoaringBitmap/CRoaring/compare/v3.0.0...v4.0.0
---

roaring: add version 4.0.0

---

recipes/duckdb/all/conandata.yml
recipes/duckdb/all/patches/0.10.2-0001-fix-cmake.patch
recipes/duckdb/config.yml

Specify library name and version:  **duckdb/0.10.2**
https://github.com/duckdb/duckdb/compare/v0.10.1...v0.10.2
---

duckdb: add version 0.10.2

---

recipes/iguana/all/conandata.yml
recipes/iguana/all/conanfile.py
recipes/iguana/all/test_package/CMakeLists.txt
recipes/iguana/config.yml

Specify library name and version:  **iguana/1.0.5**
https://github.com/qicosmos/iguana/compare/1.0.4...1.0.5
---

iguana: add version 1.0.5

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Specify library name and version:  **quill/3.9.0**
https://github.com/odygrd/quill/compare/v3.8.0...v3.9.0
---

quill: add version 3.9.0

---

recipes/simdutf/all/conandata.yml
recipes/simdutf/config.yml

Specify library name and version:  **simdutf/5.2.8**
https://github.com/simdutf/simdutf/compare/v5.2.6...v5.2.8
---

simdutf: add version 5.2.8

---

recipes/scnlib/all/conandata.yml
recipes/scnlib/config.yml

Specify library name and version:  **scnlib/2.0.3**
https://github.com/eliaskosunen/scnlib/compare/v2.0.2...v2.0.3
---

scnlib: add version 2.0.3

---

recipes/libsvtav1/all/conandata.yml
recipes/libsvtav1/all/conanfile.py
recipes/libsvtav1/all/test_package/CMakeLists.txt
recipes/libsvtav1/config.yml

Specify library name and version:  **libsvtav1/2.1.0**
https://gitlab.com/AOMediaCodec/SVT-AV1/-/compare/v1.7.0...v2.1.0
---

libsvtav1: add version 2.1.0

---

recipes/vincentlaucsb-csv-parser/all/conandata.yml
recipes/vincentlaucsb-csv-parser/all/conanfile.py
recipes/vincentlaucsb-csv-parser/config.yml

Specify library name and version:  **vincentlaucsb-csv-parser/2.2.2**
https://github.com/vincentlaucsb/csv-parser/compare/2.2.0...2.2.2
---

vincentlaucsb-csv-parser: add version 2.2.2

---

recipes/libva/all/conandata.yml
recipes/libva/all/test_package/conanfile.py
recipes/libva/config.yml

Specify library name and version:  **libva/2.21.0**
https://github.com/intel/libva/compare/2.20.0...2.21.0
---

libva: add version 2.21.0

---

recipes/behaviortree.cpp/all/conandata.yml
recipes/behaviortree.cpp/all/conanfile.py
recipes/behaviortree.cpp/config.yml

Specify library name and version:  **behaviortree.cpp/4.6.1**
https://github.com/BehaviorTree/BehaviorTree.CPP/compare/4.6.0...4.6.1
---

behaviortree.cpp: add version 4.6.1, add package_type

---

recipes/wasmtime/all/conandata.yml
recipes/wasmtime/config.yml

Specify library name and version:  **wasmtime/21.0.0**
---

wasmtime: add version 21.0.0

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/all/conanfile.py
recipes/thorvg/config.yml

Specify library name and version:  **thorvg/0.13.4**
https://github.com/thorvg/thorvg/compare/v0.13.2...v0.13.4
---

thorvg: add version 0.13.4

---

recipes/ring-span-lite/all/conandata.yml
recipes/ring-span-lite/all/conanfile.py
recipes/ring-span-lite/all/test_package/conanfile.py
recipes/ring-span-lite/config.yml

Specify library name and version:  **ring-span-lite/0.7.0**
https://github.com/martinmoene/ring-span-lite/compare/v0.6.0...v0.7.0
---

ring-span-lite: add version 0.7.0

---

.c3i/config_v1.yml
.c3i/config_v2.yml

Following new Conan Releases:
- https://github.com/conan-io/conan/releases/tag/2.3.1
- https://github.com/conan-io/conan/releases/tag/1.64.1
---

[config] Update Conan versions 2.3.1 and 1.64.1

---

recipes/snappy/all/conandata.yml
recipes/snappy/config.yml

Specify library name and version:  **snappy/1.2.1**
https://github.com/google/snappy/compare/1.2.0...1.2.1
---

snappy: add version 1.2.1

---

recipes/onnx/all/conandata.yml
recipes/onnx/config.yml

Specify library name and version:  **onnx/1.16.1**
---

onnx: add version 1.16.1

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Specify library name and version:  **thorvg/0.13.5**
https://github.com/thorvg/thorvg/compare/v0.13.4...v0.13.5
---

thorvg: add version 0.13.5

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/config.yml

Add cppcheck 2.14.1

---

recipes/uncrustify/all/conandata.yml
recipes/uncrustify/config.yml

[uncrustify] Add version 0.79.0 and remove 0.75.1 and 0.74.0

---

recipes/benchmark/all/conandata.yml
recipes/benchmark/all/conanfile.py
recipes/benchmark/config.yml

Specify library name and version:  **benchmark/1.8.4**
https://github.com/google/benchmark/compare/v1.8.3...v1.8.4
---

benchmark: add version 1.8.4

---

recipes/sonic-cpp/all/conandata.yml
recipes/sonic-cpp/all/conanfile.py
recipes/sonic-cpp/config.yml

Specify library name and version:  **sonic-cpp/1.0.1**
https://github.com/bytedance/sonic-cpp/compare/v1.0.0...v1.0.1
---

sonic-cpp: add version 1.0.1

---

recipes/dfp/all/conandata.yml
recipes/dfp/config.yml

Specify library name and version:  **dfp/1.0.3**
https://github.com/epam/DFP/compare/1.0.2...1.0.3
---

dfp: add version 1.0.3

---

recipes/watcher/all/conandata.yml
recipes/watcher/config.yml

Specify library name and version:  **watcher/0.10.1**
https://github.com/e-dant/watcher/compare/release/0.10.0...release/0.10.1
---

watcher: add version 0.10.1

---

recipes/whisper-cpp/all/conandata.yml
recipes/whisper-cpp/config.yml

Let me know if you want me to remove old versions.
---

[whisper-cpp] Bump version 1.6.2

---

recipes/symengine/all/conandata.yml
recipes/symengine/config.yml

[symengine] Add version 0.12.0.

---

recipes/arcus/all/conanfile.py

Use 3.21.12 to align with the rest of the repo

arcus: update protobuf to 3.21.12

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/config.yml

Specify library name and version:  **cpptrace/0.6.0**
I'm the author :)
---

cpptrace: Add 0.6.0

---

recipes/foxglove-schemas-protobuf/all/conanfile.py

Align with the rest of the repo so that we can remove older versions

foxglove-schemas-protobuf: update protobuf to 3.21.12

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/config.yml

[sentry-native] Add 0.7.4 and remove 0.7.0

---

.c3i/reviewers.yml

Add perseo as part of the review team

---

recipes/sioclient/all/conanfile.py

Specify library name and version:  **sioclient/cci.xxx**
I saw the project actually can be built as static library in Windows, is only not prepared for shared.
Plus, it's possible to disable tests without patching the test/CMakeLists.txt.
---

[sioclient] Build static libraries in Windows

---

recipes/ada/all/conandata.yml
recipes/ada/config.yml

Specify library name and version:  **ada/2.8.0**
https://github.com/ada-url/ada/compare/v2.7.8...v2.8.0
---

ada: add version 2.8.0

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Specify library name and version:  **thorvg/0.13.6**
https://github.com/thorvg/thorvg/compare/v0.13.5...v0.13.6
---

thorvg: add version 0.13.6

---

recipes/sfl/all/conandata.yml
recipes/sfl/config.yml

Specify library name and version:  **sfl/1.6.0**
https://github.com/slavenf/sfl-library/compare/1.5.0...1.6.0
---

sfl: add version 1.6.0

---

recipes/cmake/binary/conandata.yml
recipes/cmake/config.yml

Specify library name and version:  **cmake/3.29.4**
---

cmake: add version 3.29.4

---

recipes/lest/all/conandata.yml
recipes/lest/all/test_package/CMakeLists.txt
recipes/lest/all/test_package/test_package.cpp
recipes/lest/config.yml

Specify library name and version:  **lest/1.35.2**
https://github.com/martinmoene/lest/compare/v1.35.1...v1.35.2
---

lest: add version 1.35.2

---

recipes/s2let/all/CMakeLists.txt
recipes/s2let/all/conandata.yml
recipes/s2let/all/conanfile.py
recipes/s2let/all/test_package/CMakeLists.txt
recipes/s2let/all/test_package/conanfile.py
recipes/s2let/all/test_v1_package/CMakeLists.txt
recipes/s2let/all/test_v1_package/conanfile.py
recipes/s2let/config.yml

s2let: migrate to Conan v2

---

recipes/expected-lite/all/conandata.yml
recipes/expected-lite/all/conanfile.py
recipes/expected-lite/all/test_package/conanfile.py
recipes/expected-lite/config.yml

Specify library name and version:  **expected-lite/0.7.0**
https://github.com/martinmoene/expected-lite/compare/v0.6.3...v0.7.0
---

expected-lite: add version 0.7.0

---

recipes/tesseract/all/conandata.yml
recipes/tesseract/all/patches/0004-control-optimizations-5.4.0.patch
recipes/tesseract/config.yml

Specify library name and version:  **tesseract/5.4.0**
https://github.com/tesseract-ocr/tesseract/compare/5.3.4...5.4.0
---

tesseract: add version 5.4.0

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Specify library name and version:  **thorvg/0.13.7**
https://github.com/thorvg/thorvg/compare/v0.13.6...v0.13.7
---

thorvg: add version 0.13.7

---

recipes/mold/all/conandata.yml
recipes/mold/config.yml

Specify library name and version:  **mold/2.31.0**
https://github.com/rui314/mold/compare/v2.4.0...v2.31.0
---

mold: add version 2.31.0

---

recipes/simdjson/all/conandata.yml
recipes/simdjson/config.yml

Specify library name and version:  **simdjson/***
https://github.com/simdjson/simdjson/compare/v3.9.2...v3.9.3
---

simdjson: add version 3.9.3, remove older versions

---

recipes/boost/all/conanfile.py

Specify library name and version:  **boost/1.84.0**
Since Boost 1.84.0, the new library Cobalt was introduced and requires not only C++20, but also concepts and coroutines:
- https://github.com/boostorg/cobalt/blob/boost-1.85.0/build/Jamfile#L54
- https://github.com/boostorg/cobalt/blob/boost-1.85.0/include/boost/cobalt/concepts.hpp#L8
This PR adds a new check to validate the compiler version if has support to coroutines, based on https://en.cppreference.com/w/cpp/compiler_support#cpp20
fixes #24216
---

[boost] Add check for coroutine support for Cobalt build

---

recipes/expected-lite/all/conandata.yml
recipes/expected-lite/config.yml

Specify library name and version:  **expected-lite/0.8.0**
https://github.com/martinmoene/expected-lite/compare/v0.7.0...v0.8.0
---

expected-lite: add version 0.8.0

---

recipes/shield/all/conandata.yml
recipes/shield/config.yml

Specify library name and version:  **shield/0.6**
---

shield: add version 0.6

---

recipes/sdl_net/all/conandata.yml
recipes/sdl_net/all/conanfile.py
recipes/sdl_net/all/test_package/conanfile.py
recipes/sdl_net/config.yml

sdl_net: add v2.2.0, bump sdl

---

recipes/metall/all/conandata.yml
recipes/metall/all/conanfile.py
recipes/metall/config.yml

Specify library name and version:  **metall/0.28**
https://github.com/LLNL/metall/compare/v0.27...v0.28
---

metall: add version 0.28

---

recipes/c-ares/all/conandata.yml
recipes/c-ares/all/test_package/test_package.c
recipes/c-ares/config.yml

Specify library name and version:  **c-ares/1.30.0**
https://github.com/c-ares/c-ares/compare/cares-1_28_1...v1.30.0
---

c-ares: add version 1.30.0

---

recipes/libpqxx/all/conandata.yml
recipes/libpqxx/config.yml

Specify library name and version:  **libpqxx/7.9.1**
New patch version released.
---

libpqxx: add version 7.9.1

---

recipes/trantor/all/conandata.yml
recipes/trantor/all/patches/1.5.19-0001-disable-werror.patch
recipes/trantor/config.yml

Specify library name and version:  **trantor/1.5.19**
https://github.com/an-tao/trantor/compare/v1.5.16...v1.5.19
---

trantor: add version 1.5.19

---

recipes/reflect-cpp/all/conandata.yml
recipes/reflect-cpp/config.yml

Specify library name and version:  **reflect/0.11.0**
https://github.com/getml/reflect-cpp/compare/v0.10.0...v0.11.0
---

reflect: add version 0.11.0

---

recipes/geographiclib/all/conanfile.py

Specify library name and version:  **geographiclib/2.3**
The PR #24121 tried to predict the generated libraries, but some cases are hard to track:
- When using multi-config generator, it will add debug postfix: https://github.com/geographiclib/geographiclib/blob/v2.3/CMakeLists.txt#L187
Using `collect_libs` is fragile, but this project is generating a single library, so it should not be a risk.
fixes #24271
---

[geographiclib] Revert provided libs to use collect_libs

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Specify library name and version:  **glaze/2.8.1**
https://github.com/stephenberry/glaze/compare/v2.8.0...v2.8.1
---

glaze: add version 2.8.1

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/config.yml

[sentry-native] Add versions 0.7.5/0.7.6 and remove 0.7.1/0.7.2

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Specify library name and version:  **glaze/2.8.2**
https://github.com/stephenberry/glaze/compare/v2.8.1...v2.8.2
---

glaze: add version 2.8.2

---

recipes/mini/all/conandata.yml
recipes/mini/all/conanfile.py
recipes/mini/all/test_package/CMakeLists.txt
recipes/mini/all/test_package/conanfile.py
recipes/mini/all/test_package/test_package.cpp
recipes/mini/config.yml

Specify library name and version:  **mini/***
---

mini: add recipe

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/2.8.4**
upstream has been updated with several improvements.
https://github.com/stephenberry/glaze/compare/v2.8.2...v2.8.4
---

glaze: add version 2.8.4

---

recipes/pcre2/all/conandata.yml
recipes/pcre2/config.yml

Changes to recipe:  **pcre2/10.44**
pcre2 has been updated with some new features.
https://github.com/PCRE2Project/pcre2/compare/pcre2-10.43...pcre2-10.44
---

pcre2: add version 10.44

---

recipes/hdf5/all/conandata.yml
recipes/hdf5/all/conanfile.py
recipes/hdf5/config.yml

Support hdf5 cross-building if the version is greater than 1.14.4-3

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml
recipes/quill/old/conandata.yml
recipes/quill/old/conanfile.py

Specify library name and version:  **quill/4.4.0**
https://github.com/odygrd/quill/compare/v4.3.0...v4.4.0
---

quill: add version 4.4.0, remove older versions

---

recipes/luau/all/conandata.yml
recipes/luau/config.yml

Changes to recipe:  **luau/0.630**
Since luau releases once a week, I usually try to package every 5 releases.
https://github.com/luau-lang/luau/compare/0.625...0.630
---

luau: add version 0.630

---

recipes/xbyak/all/conandata.yml
recipes/xbyak/config.yml

xbyak/7.0.7 supports new instructions.
https://github.com/herumi/xbyak/compare/v7.06...v7.07
---

xbyak: add version 7.07

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/all/conanfile.py
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.13.8**
- thorvg/0.13.8 has several improvements.
- fix url of homage
https://github.com/thorvg/thorvg/compare/v0.13.7...v0.13.8
---

thorvg: add version 0.13.8, fix homepage

---

recipes/rocksdb/all/conandata.yml
recipes/rocksdb/config.yml

Changes to recipe:  **rocksdb/9.2.1**
9.2.1 has several new features, API changes.
https://github.com/facebook/rocksdb/compare/v9.1.0...v9.2.1
---

rocksdb: add version 9.2.1

---

recipes/scnlib/all/conandata.yml
recipes/scnlib/all/conanfile.py
recipes/scnlib/config.yml

Specify library name and version:  **scnlib/3.0.1**
https://github.com/eliaskosunen/scnlib/compare/v2.0.3...v3.0.1
---

scnlib: add version 3.0.1

---

recipes/vincentlaucsb-csv-parser/all/conandata.yml
recipes/vincentlaucsb-csv-parser/all/conanfile.py
recipes/vincentlaucsb-csv-parser/config.yml

Changes to recipe:  **vincentlaucsb-csv-parser/2.3.0**
- 2.3.0 privide new features.
- fix settings
https://github.com/vincentlaucsb/csv-parser/compare/2.2.3...2.3.0
---

vincentlaucsb-csv-parser: add version 2.3.0

---

recipes/msdfgen/all/conandata.yml
recipes/msdfgen/all/conanfile.py
recipes/msdfgen/config.yml

Changes to recipe:  **msdfgen/1.12**
https://github.com/Chlumsky/msdfgen/compare/v1.11...v1.12
---

msdfgen: add version 1.12

---

recipes/sdl/all/conandata.yml
recipes/sdl/config.yml

Changes to recipe:  **sdl/2.30.4**
SDL/2.30.4 has several bug fixes.
https://github.com/libsdl-org/SDL/compare/release-2.30.3...release-2.30.4
---

sdl: add version 2.30.4

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Changes to recipe:  **quill/4.4.1**
There are several bug fixes on quill/4.4.1.
https://github.com/odygrd/quill/compare/v4.4.0...v4.4.1
---

quill: add version 4.4.1

---

.c3i/config_v1.yml

We're having problems compiling SIMD in Debug mode. Trying in a large container.

[simd] Large container

---

.c3i/reviewers.yml

This PR add @ErniGH to reviewers list in the configuration file, as team member. 
---

Add ErniGH as team reviewer in config

---

recipes/cmake/binary/conandata.yml
recipes/cmake/config.yml

Changes to recipe:  **cmake/3.29.6**
Add CMake version 3.29.6
---

cmake: add version 3.29.6

---

recipes/bredis/all/conandata.yml
recipes/bredis/all/conanfile.py
recipes/bredis/all/test_package/CMakeLists.txt
recipes/bredis/all/test_package/conanfile.py
recipes/bredis/all/test_package/test_package.cpp
recipes/bredis/config.yml

Specify library name and version:  **bredis/***
---

bredis: add recipe

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/0.6.2**
Bugfixes, I'm the author
Just a new version
---

cpptrace: Add 0.6.2

---

CONTRIBUTING.md
README.md
docs/consuming_recipes.md
docs/developing_recipes_locally.md

Fix typo and grammar errors

---

recipes/cargs/all/conandata.yml
recipes/cargs/config.yml

Changes to recipe:  **cargs/1.2.0**
cargs/1.2.0 has a bug fix.
https://github.com/likle/cargs/compare/v1.1.0...v1.2.0
---

cargs: add version 1.2.0

---

recipes/mujs/all/conandata.yml
recipes/mujs/all/conanfile.py
recipes/mujs/config.yml

Changes to recipe:  **mujs/1.3.5**
mujs/1.3.5 has several improvements.
https://github.com/ccxvii/mujs/compare/1.3.4...1.3.5
---

mujs: add version 1.3.5

---

recipes/sfl/all/conandata.yml
recipes/sfl/config.yml

Changes to recipe:  **sfl/1.7.0**
There are several improvements in 1.7.0.
https://github.com/slavenf/sfl-library/compare/1.6.0...1.7.0
---

sfl: add version 1.7.0

---

recipes/cpp-sort/all/conandata.yml
recipes/cpp-sort/config.yml

Changes to recipe:  **cpp-sort/1.16.0**
There are several new features on 1.16.0.
https://github.com/Morwenn/cpp-sort/compare/1.15.0...1.16.0
---

cpp-sort: add version 1.16.0

---

recipes/zlib-ng/all/conandata.yml
recipes/zlib-ng/all/conanfile.py
recipes/zlib-ng/config.yml

Changes to recipe:  **zlib-ng/2.1.7**
2.1.7 is the last release of 2.1.x.
https://github.com/zlib-ng/zlib-ng/compare/2.1.6...2.1.7
---

zlib-ng: add version 2.1.7

---

recipes/gcem/all/conandata.yml
recipes/gcem/config.yml

Changes to recipe:  **gcem/1.18.0**
New release contains new fabs funcitonality
https://github.com/kthohr/gcem/compare/v1.17.0...v1.18.0

gcem: Add version 1.18.0

---

recipes/s2n/all/conandata.yml
recipes/s2n/config.yml

Changes to recipe:  **s2n/1.4.16**
There are several new features since 1.4.13.
https://github.com/aws/s2n-tls/compare/v1.4.13...v1.4.16
---

s2n: add version 1.4.16

---

recipes/nghttp3/all/conandata.yml
recipes/nghttp3/all/conanfile.py
recipes/nghttp3/config.yml

Changes to recipe:  **nghttp3/1.4.0**
Several improvements, and function names modification
https://github.com/ngtcp2/nghttp3/compare/v1.3.0...v1.4.0
---

nghttp3: add version 1.4.0

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/config.yml

Add cppcheck 2.14.2

---

recipes/zoe/all/conandata.yml
recipes/zoe/all/conanfile.py
recipes/zoe/all/patches/3.1-0002-support-macosx.patch
recipes/zoe/config.yml

Changes to recipe:  **zoe/3.1**
zoe/3.1 has several fixes.
https://github.com/winsoft666/zoe/compare/v3.0...v3.1
---

zoe: add version 3.1

---

recipes/c-ares/all/conandata.yml
recipes/c-ares/all/conanfile.py
recipes/c-ares/config.yml

Changes to recipe:  **c-ares/1.31.0**
There are several improvements on 1.31.0.
https://github.com/c-ares/c-ares/compare/v1.30.0...v1.31.0
---

c-ares: add version 1.31.0 

---

recipes/mold/all/conandata.yml
recipes/mold/config.yml

Changes to recipe:  **mold/2.32.1**
There are several bug fixes on 2.32.1.
https://github.com/rui314/mold/compare/v2.32.0...v2.32.1
---

mold: add version 2.32.1

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Changes to recipe:  **quill/4.5.0**
There are several improvements in 4.5.0.
https://github.com/odygrd/quill/compare/v4.4.1...v4.5.0
---

quill: add version 4.5.0

---

recipes/pdf-writer/all/conandata.yml
recipes/pdf-writer/all/patches/4.6.6-0001-fix-cmake.patch
recipes/pdf-writer/config.yml

Changes to recipe:  **pdf-writer/4.6.6**
There are several bug fixes in 4.6.6.
https://github.com/galkahana/PDF-Writer/compare/v4.6.4...v4.6.6
---

pdf-writer: add version 4.6.6

---

.c3i/authorized_users.yml
.c3i/reviewers.yml

Or: What's in a name? Something something roses something something same smell

Hello World! Change my username 🏳️‍⚧️ 

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/all/conanfile.py
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.14.0**
Thare are lots of improvements in 0.14.0.
https://github.com/thorvg/thorvg/compare/v0.13.8...v0.14.0
---

thorvg: add version 0.14.0

---

recipes/nsync/all/conandata.yml
recipes/nsync/config.yml

Changes to recipe:  **nsync/1.29.2**
https://github.com/google/nsync/compare/1.29.1...1.29.2
---

nsync: add version 1.29.2

---

recipes/re2/all/conandata.yml
recipes/re2/config.yml

Changes to recipe:  **re2/20240702**
https://github.com/google/re2/compare/2024-03-01...2024-07-02
---

re2: add version 20240702

---

recipes/zlib-ng/all/conandata.yml
recipes/zlib-ng/all/conanfile.py
recipes/zlib-ng/config.yml

Changes to recipe:  **zlib-ng/2.2.1**
There are performance improvements in 2.2.1.
https://github.com/zlib-ng/zlib-ng/compare/2.1.7...2.2.1
---

zlib-ng: add version 2.2.1

---

recipes/tinygltf/all/conandata.yml
recipes/tinygltf/config.yml

Changes to recipe:  **tinygltf/2.9.0**
There are several improvements since 2.8.19.
https://github.com/syoyo/tinygltf/compare/v2.8.19...v2.9.0
---

tinygltf: add version 2.9.0

---

recipes/cmake/binary/conandata.yml
recipes/cmake/config.yml

Changes to recipe:  **cmake/3.30.0**
Add latest version (v3.30.0) of CMake.
Have the latest version of CMake available inside conan ecosystem.
---

cmake: add version 3.30.0

---

recipes/abseil/all/conandata.yml
recipes/abseil/all/patches/0004-test-allocator-testonly.patch

Changes to recipe:  **abseil/20240116.1 & 20240116.2**
closes https://github.com/conan-io/conan-center-index/issues/24500
see https://github.com/conan-io/conan-center-index/issues/24500#issuecomment-2205899367
---

abseil: do not build test_allocator target in abseil 20240116.1 & 20240116.2

---

recipes/lunasvg/all/conandata.yml
recipes/lunasvg/config.yml

Changes to recipe:  **lunasvg/2.4.0**
There are several improvements in 2.4.0.
https://github.com/sammycage/lunasvg/compare/v2.3.9...v2.4.0
---

lunasvg: add version 2.4.0

---

recipes/caf/all/conandata.yml
recipes/caf/all/conanfile.py
recipes/caf/config.yml

Changes to recipe:  **caf/1.0.0**
major version up.
https://github.com/actor-framework/actor-framework/compare/0.19.4...1.0.0
---

caf: add version 1.0.0

---

recipes/icu/all/conanfile.py

Changes to recipe:  **icu/[*]**
Closes https://github.com/conan-io/conan-center-index/issues/24501

icu: Update ICU license where needed to Unicode-3.0

---

recipes/opencv/4.x/conandata.yml
recipes/opencv/4.x/conanfile.py
recipes/opencv/4.x/patches/4.10.0-0001-fix-zlib-static-android.patch
recipes/opencv/config.yml

Changes to recipe:  **opencv/4.10.0**
fix #24222
https://github.com/opencv/opencv/compare/4.9.0...4.10.0
---

opencv: add 4.10.0

---

recipes/jsonifier/all/conandata.yml
recipes/jsonifier/all/test_package/test_package.cpp
recipes/jsonifier/config.yml

Changes to recipe:  **jsonifier/0.9.96**
There are several improvements in 0.9.96.
https://github.com/RealTimeChris/Jsonifier/compare/v0.9.95...v0.9.96
---

jsonifier: add version 0.9.96

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.14.1**
There are several improvements in 0.14.1.
https://github.com/thorvg/thorvg/compare/v0.14.0...v0.14.1
---

thorvg: add new version 0.14.1

---

recipes/sdl/all/conandata.yml
recipes/sdl/config.yml

There are several improvements and bug fixes in 2.30.5.
https://github.com/libsdl-org/SDL/compare/release-2.30.4...release-2.30.5
---

sdl: add version 2.30.5

---

recipes/fmt/all/conandata.yml
recipes/fmt/config.yml

Changes to recipe:  **fmt/11.0.1**
There are several improvements in 11.0.1.
https://github.com/fmtlib/fmt/compare/11.0.0...11.0.1
---

fmt: add version 11.0.1

---

recipes/toml11/all/conandata.yml
recipes/toml11/config.yml

Changes to recipe:  **toml11/4.0.3**
There are several improvements in 4.0.3.
https://github.com/ToruNiina/toml11/compare/v4.0.1...v4.0.3
---

toml11: add version 4.0.3

---

recipes/strong_type/all/conandata.yml
recipes/strong_type/config.yml

Changes to recipe:  **strong_type/15**
There are several improvements in v15.
https://github.com/rollbear/strong_type/compare/v14...v15
---

strong_type: add version 15

---

recipes/blend2d/all/conandata.yml
recipes/blend2d/config.yml

Changes to recipe:  **blend2d/0.11.3**
There are several improvements in 0.11.3.
https://github.com/blend2d/blend2d/compare/a7f9476..8891919
---

blend2d: add version 0.11.3

---

recipes/libjxl/all/conandata.yml
recipes/libjxl/config.yml

Changes to recipe:  **libjxl/0.10.3**
There is a bugfix in 0.10.3.
https://github.com/libjxl/libjxl/compare/v0.10.2...v0.10.3
---

libjxl: add version 0.10.3

---

recipes/libcoro/all/conandata.yml
recipes/libcoro/all/conanfile.py
recipes/libcoro/config.yml

Changes to recipe:  **libcoro/0.12**
There are several bug fixes and improvements in 0.12.
https://github.com/jbaldwin/libcoro/compare/v0.11.1...v0.12
---

libcoro: add version 0.12

---

recipes/meshoptimizer/all/conandata.yml
recipes/meshoptimizer/config.yml

Changes to recipe:  **meshoptimizer/0.21**
---

meshoptimizer: add version 0.21

---

recipes/yyjson/all/conandata.yml
recipes/yyjson/config.yml

Changes to recipe:  **yyjson/0.10.0**
There is a new feature in 0.10.0.
https://github.com/ibireme/yyjson/compare/0.9.0...0.10.0
---

yyjson: add version 0.10.0

---

recipes/sbepp/all/conandata.yml
recipes/sbepp/config.yml

Changes to recipe:  **sbepp/1.4.0**
I'm the project author, adding version 1.4.0.
---

sbepp: add version 1.4.0

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.14.2**
There are lots of improvements in 0.14.2.
https://github.com/thorvg/thorvg/compare/v0.14.1...v0.14.2#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4
---

thorvg: add version 0.14.2

---

recipes/dav1d/all/conandata.yml
recipes/dav1d/config.yml

Changes to recipe:  **dav1d/1.4.3**
The two releases add bugfixes and improvements for ARM (https://code.videolan.org/videolan/dav1d/-/blob/1.4.3/NEWS?ref_type=tags#L1-21).
- Adds the new download link and version
---

dav1d: add 1.4.3

---

recipes/dataframe/all/conandata.yml
recipes/dataframe/config.yml

Changes to recipe:  **dataframe/3.2.0**
Upgrading C++ DataFrame to version 3.2.0
Enhanced documentation and code clean ups
Converted DateTime doc to html
Implemented PeaksAndValleysVisitor visitor
Implemented EhlersHighPassFilterVisitor visitor
Implemented EhlersBandPassFilterVisitor visitor
Implemented reading/writing in binary format
Implemented reading binary data format in chunks
Implemented serialize() and deserialize()
Implemented reading/writing containers in binary format
Added optional time-zone to strings parsed by DateTime constructor
Implemented PowerFitVisitor visitor
Implemented QuadraticFitVisitor visitor
Implemented fill_policy::lagrange_interpolate
Implemented correlation_type::kendall_tau
Implemented change_freq()
Implemented duplication_mask()
---
- [ x ] Read the …

Upgrading C++ DataFrame to version 3.2.0

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/0.6.3**
New release, I'm the maintainer
---

cpptrace: Add version 0.6.3

---

recipes/xapian-core/all/conandata.yml
recipes/xapian-core/all/conanfile.py
recipes/xapian-core/config.yml

xapian-core: add v1.4.24

---

recipes/protobuf/all/conanfile.py

protobuf: use RPATH instead of RUNPATH

---

recipes/llnl-units/all/conandata.yml
recipes/llnl-units/all/conanfile.py
recipes/llnl-units/all/test_package/CMakeLists.txt
recipes/llnl-units/all/test_package/conanfile.py
recipes/llnl-units/all/test_package/test_package.cpp
recipes/llnl-units/config.yml

Adds a new recipe for https://github.com/LLNL/units
We maintain a local copy of this conanfile.py, it would be nice to use the index so we don't need to keep maitaining a local copy.
This is tested with conan 1.x locally, not with conan2
---

llnl-units: Add 0.9.1 to conan center index

---

recipes/gtest/all/conandata.yml
recipes/gtest/config.yml

Changes to recipe:  gtest/1.15.0
new version released
close https://github.com/conan-io/conan-center-index/issues/24658

gtest: add 1.15.0

---

recipes/zserio/all/conandata.yml
recipes/zserio/config.yml

Changes to recipe:  **zserio/2.14.1**
New patch release 2.14.1
---

zserio: Add new Zserio release 2.14.1

---

recipes/fmt/all/conandata.yml
recipes/fmt/config.yml

Changes to recipe:  **fmt/11.0.2**
There are several improvements in 11.0.2.
https://github.com/fmtlib/fmt/compare/11.0.1...11.0.2
---

fmt: add version 11.0.2

---

recipes/mold/README.md

Changes to recipe:  **mold**
Add mold README
---

mold: Add README

---

recipes/android-ndk/all/conandata.yml
recipes/android-ndk/config.yml

Changes to recipe:  **android-ndk/r27**
New version was released.
---

android-ndk: add r27

---

recipes/arrow/all/conandata.yml
recipes/arrow/config.yml

Changes to recipe:  **arrow/17.0.0**
There are lots of new features in 17.0.0.
https://github.com/apache/arrow/compare/apache-arrow-16.1.0...apache-arrow-17.0.0#diff-1bba462ab050e89360fd88110a689e85ee037749cea091a1848ab574381d3795
---

arrow: add version 17.0.0

---

recipes/cmake/binary/conandata.yml
recipes/cmake/config.yml

Changes to recipe:  **cmake/3.29.7**
Add CMake version 3.29.7.
Support latest CMake of the 3.29.x releases.
---

cmake: add version 3.29.7

---

recipes/argparse/all/conandata.yml
recipes/argparse/all/conanfile.py
recipes/argparse/config.yml

Changes to recipe:  **argparse/3.1**
There are several improvements in 3.1.
https://github.com/p-ranav/argparse/compare/v3.0...v3.1
---

argparse: add version 3.1

---

recipes/glaze/all/conandata.yml
recipes/glaze/all/conanfile.py
recipes/glaze/config.yml

Changes to recipe:  **glaze/2.9.5**
There are several improvements in 2.9.5.
https://github.com/stephenberry/glaze/compare/v2.9.2...v2.9.5
---

glaze: add version 2.9.5

---

recipes/rocksdb/all/conandata.yml
recipes/rocksdb/all/conanfile.py
recipes/rocksdb/config.yml

Changes to recipe:  **rocksdb/9.4.0**
There are lots of new features and bugfixes since 9.2.1.
https://github.com/facebook/rocksdb/compare/v9.2.1...v9.4.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---

rocksdb: add version 9.4.0

---

recipes/json_dto/all/conandata.yml
recipes/json_dto/all/conanfile.py
recipes/json_dto/config.yml

Changes to recipe:  **json_dto/0.3.4**
There are several new features in 0.3.4.
https://github.com/Stiffstream/json_dto/compare/v.0.3.3...v.0.3.4
---

json_dto: add version 0.3.4

---

recipes/blend2d/all/conandata.yml
recipes/blend2d/config.yml

Changes to recipe:  **blend2d/0.11.4**
There are minor improvements in 0.11.4.
https://github.com/blend2d/blend2d/compare/8891919aaf873c09c909338c82e4bd5c1d2d5f37...9a86b2700917ced827c008c3dd488108afb3490c#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---

blend2d: add version 0.11.4

---

recipes/simfil/all/conandata.yml
recipes/simfil/config.yml

Changes to recipe:  **simfil/0.3.0**
---

simfil: Bump 0.3.0

---

recipes/glaze/all/conandata.yml
recipes/glaze/all/conanfile.py
recipes/glaze/all/test_package/CMakeLists.txt
recipes/glaze/all/test_package/conanfile.py
recipes/glaze/config.yml

Changes to recipe:  **glaze/3.1.7**
glaze/3.x.x requires C++23.
https://github.com/stephenberry/glaze/compare/v2.9.5...v3.1.7
---

glaze: add version 3.1.7

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.14.2**
There are several bugfixes and improvements since 0.14.2.
https://github.com/thorvg/thorvg/compare/v0.14.2...v0.14.4#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4
---

thorvg: add version 0.14.4, remove older versions

---

recipes/quill/all/conandata.yml
recipes/quill/all/conanfile.py
recipes/quill/config.yml
recipes/quill/old/conanfile.py

Changes to recipe:  **quill/6.0.0**
There are lots of improvements since 4.5.0.
Use official zip files.
https://github.com/odygrd/quill/compare/v4.5.0...v6.0.0
---

quill: add version 6.0.0

---

recipes/libxslt/all/conanfile.py

Fix to libxslt
Close https://github.com/conan-io/conan-center-index/issues/24730

fix libxslt for extensions static library

---

recipes/nanoflann/all/conandata.yml
recipes/nanoflann/all/conanfile.py
recipes/nanoflann/config.yml

Changes to recipe:  **nanoflann/1.6.0**
Adds the latest version of `nanoflann`.
No changes to the build system since v1.5.2: https://github.com/jlblancoc/nanoflann/releases
---

nanoflann: add v1.6.0

---

recipes/toml11/all/conandata.yml
recipes/toml11/all/conanfile.py
recipes/toml11/config.yml

Changes to recipe:  **toml11/4.1.0**
There are new features in 4.1.0.
https://github.com/ToruNiina/toml11/compare/v4.0.3...v4.1.0
---

toml11: add version 4.1.0

---

recipes/libavif/all/conandata.yml
recipes/libavif/all/conanfile.py
recipes/libavif/all/patches/1.1.0-0001-disable-developer-only-codepaths.patch
recipes/libavif/config.yml

Changes to recipe:  **libavif/1.1.0**
There are several improvements with experimental compile options in 1.1.0.
https://github.com/AOMediaCodec/libavif/compare/v1.0.4...v1.1.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---

libavif: add new version 1.1.0

---

recipes/bazel/all/conandata.yml
recipes/bazel/config.yml

Changes to recipe:  **bazel/7.2.1**
Not critical, just to provide the latest available version. Would like to use it to package [Skia](https://skia.org/).
Edit: added the latest release of each major version as well.
---

bazel: add v7.2.1, v6.5.0, v4.2.4

---

recipes/gn/all/conandata.yml
recipes/gn/all/conanfile.py
recipes/gn/config.yml

Changes to recipe:  **gn/cci.20240611**
Not critical, just to provide the latest available version. The latest version on CCI is three years old. Would like to potentially use it to package [Skia](https://skia.org/).
---

gn: add cci.20240611

---

recipes/libsvm/all/conandata.yml
recipes/libsvm/all/conanfile.py
recipes/libsvm/config.yml

Changes to recipe:  **libsvm/333**
There are slight modification in 333.
Since the final release of libsvm is in 2023, it would be worth adding a version to the recipe. 
https://github.com/cjlin1/libsvm/compare/v332...v333
---

libsvm: add version 333

---

recipes/highfive/all/conandata.yml
recipes/highfive/all/conanfile.py
recipes/highfive/config.yml

Changes to recipe:  **highfive/2.10.0**
There are several improvements in 2.10.0.
https://github.com/BlueBrain/HighFive/compare/v2.9.0...v2.10.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---

highfive: add version 2.10.0

---

recipes/aws-c-io/all/conandata.yml
recipes/aws-c-io/all/conanfile.py
recipes/aws-c-io/config.yml

Specify library name and version:  **aws-c-io/0.14.1**
Related issues:
- https://github.com/conan-io/conan-center-index/issues/22420
- https://github.com/conan-io/conan-center-index/issues/2275
---

aws-c-io: add v0.14.1

---

recipes/roaring/all/conandata.yml
recipes/roaring/config.yml

Changes to recipe:  **roaring/4.1.1**
There are several improvements in 4.1.1.
https://github.com/RoaringBitmap/CRoaring/compare/v4.1.0...v4.1.1
---

roaring: add version 4.1.1

---

recipes/ffmpeg/all/conanfile.py

Changes to recipe:  **ffmpeg/6.1.1**
Both Conan 1.x and Conan 2.x are clear about not using `self.dependencies` in `build()`. It may cause unexpected behavior, as it's not documented and may change in the future.
- https://docs.conan.io/1/reference/conanfile/dependencies.html#dependencies-interface
- https://docs.conan.io/2/reference/conanfile/methods/generate.html#dependencies-interface
I moved to collect the openssl libraries in generate, then, re-use the same variable later. I tested locally using both Conan 1.64.0 and 2.5.0:
```
cd recipes/ffmpeg/all/
conan install . --version=6.1.1
conan source . --version=6.1.1
conan build . --version=6.1.1
```
fixes #24689
/cc @Drllap
---

[ffmpeg] Do not use self.dependencis in build

---

recipes/libxlsxwriter/all/conandata.yml
recipes/libxlsxwriter/all/conanfile.py
recipes/libxlsxwriter/config.yml

Changes to recipe:  **libxlsxwriter/1.1.8**
https://github.com/jmcnamara/libxlsxwriter/compare/RELEASE_1.1.7...v1.1.8
---

libxlsxwriter: add version 1.1.8

---

recipes/foxglove-websocket/all/conandata.yml
recipes/foxglove-websocket/config.yml

Changes to recipe:  **foxglove-websocket/1.3.0**
Release 1.3.0 version
---

foxglove-websocket: Add version 1.3.0

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/3.1.9**
There are several improvements since 3.1.7.
https://github.com/stephenberry/glaze/compare/v3.1.7...v3.1.9
---

glaze: add version 3.1.9

---

recipes/status-code/all/conandata.yml
recipes/status-code/all/conanfile.py
recipes/status-code/all/test_package/test_package.cpp
recipes/status-code/all/test_v1_package/CMakeLists.txt
recipes/status-code/config.yml

Changes to recipe:  **status-code/cci.20240614**
Add version.
---

[status-code] Add version cci.20240614

---

recipes/librdkafka/all/conandata.yml
recipes/librdkafka/all/conanfile.py
recipes/librdkafka/all/patches/0002-Change-library-targets-and-result-variables-2-5-0.patch
recipes/librdkafka/all/patches/0003-add-forward-declaration-2-5-0.patch
recipes/librdkafka/config.yml

Changes to recipe:  **librdkafka/2.5.0**
There are several new features in 2.5.0.
https://github.com/confluentinc/librdkafka/compare/v2.4.0...v2.5.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---

librdkafka: add version 2.5.0

---

recipes/libavif/all/conandata.yml
recipes/libavif/all/patches/1.1.1-0001-disable-developer-only-codepaths.patch
recipes/libavif/config.yml

Changes to recipe:  **libavif/1.1.1**
There are several improvements in 1.1.1.
https://github.com/AOMediaCodec/libavif/compare/v1.1.0...v1.1.1#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---

libavif: add version 1.1.1

---

recipes/libpqxx/all/conandata.yml
recipes/libpqxx/config.yml

Changes to recipe:  **libpqxx/7.9.2**
New patch version released.
---

libpqxx: add version 7.9.2

---

recipes/libcoro/all/conandata.yml
recipes/libcoro/config.yml

Changes to recipe:  **libcoro/0.12.1**
There are several improvements in 0.12.1.
https://github.com/jbaldwin/libcoro/compare/v0.12...v0.12.1
---

libcoro: add version 0.12.1

---

recipes/sfl/all/conandata.yml
recipes/sfl/config.yml

Changes to recipe:  **sfl/1.8.0**
There are several new features in 1.8.0.
https://github.com/slavenf/sfl-library/compare/1.7.0...1.8.0
---

sfl: add version 1.8.0

---

recipes/libxshmfence/all/conandata.yml
recipes/libxshmfence/config.yml

libxshmfence: add v1.3.2

---

recipes/simdjson/all/conandata.yml
recipes/simdjson/config.yml

Changes to recipe:  **simdjson/3.10.0**
There are several improvements since 3.9.3.
https://github.com/simdjson/simdjson/compare/v3.9.3...v3.10.0
---

simdjson: add version 3.10.0

---

recipes/c-ares/all/conandata.yml
recipes/c-ares/all/conanfile.py
recipes/c-ares/all/patches/1.33.0-0001-fix-tcp-fastopen.patch
recipes/c-ares/config.yml

Changes to recipe:  **c-ares/1.33.0**
There are several new features in 1.33.0.
https://github.com/c-ares/c-ares/compare/v1.32.3...v1.33.0#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---

c-ares: add version 1.33.0

---

recipes/cpp-yyjson/all/conandata.yml
recipes/cpp-yyjson/all/conanfile.py
recipes/cpp-yyjson/config.yml

Changes to recipe:  **cpp-yyjson**
0.6.0 supports yyjson/0.10.0 features.
https://github.com/yosh-matsuda/cpp-yyjson/compare/v0.5.0...v0.6.0
---

cpp-yyjson: add version 0.6.0

---

recipes/meson/all/conandata.yml
recipes/meson/all/conanfile.py
recipes/meson/config.yml

Changes to recipe:  **meson/1.5.1**
There are several improvements in 1.5.1.
https://github.com/mesonbuild/meson/compare/1.5.0...1.5.1
---

meson: add version 1.5.1

---

recipes/aws-c-common/all/conandata.yml
recipes/aws-c-common/config.yml

[aws refactor] aws-c-common: Add 0.6.11 version

---

recipes/sdl/all/conandata.yml
recipes/sdl/all/conanfile.py
recipes/sdl/config.yml

Changes to recipe:  **sdl/2.30.6**
There are several improvements in 2.30.6.
https://github.com/libsdl-org/SDL/compare/release-2.30.5...release-2.30.6
---

sdl: add new version 2.30.6

---

recipes/stringzilla/all/conandata.yml
recipes/stringzilla/config.yml

Changes to recipe:  **stringzilla/3.9.0**
There are minor version up.
https://github.com/ashvardanian/StringZilla/compare/v3.8.4...v3.9.0
---

stringzilla: add version 3.9.0

---

recipes/poselib/all/conandata.yml
recipes/poselib/all/conanfile.py
recipes/poselib/config.yml

Changes to recipe:  **poselib/2.0.4**
https://github.com/PoseLib/PoseLib/releases/tag/v2.0.4
https://github.com/PoseLib/PoseLib/compare/v2.0.3...v2.0.4
/cc @pablospe
---

poselib: add v2.0.4

---

recipes/argz/all/conandata.yml
recipes/argz/all/conanfile.py
recipes/argz/all/test_package/CMakeLists.txt
recipes/argz/all/test_package/conanfile.py
recipes/argz/all/test_package/test_package.cpp
recipes/argz/config.yml

Changes to recipe:  **argz/0.2.1**
C++20 argument parser library.
https://github.com/stephenberry/argz
---

argz: add recipe

---

recipes/simdutf/all/conandata.yml
recipes/simdutf/config.yml

Changes to recipe:  **simdutf/5.3.2**
There are several bug fixes in 5.3.2.
https://github.com/simdutf/simdutf/compare/v5.3.1...v5.3.2#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a
---

simdutf: add version 5.3.2

---

recipes/intx/all/conandata.yml
recipes/intx/all/conanfile.py
recipes/intx/config.yml

Changes to recipe:  **intx/0.11.0**
There are minor improvements in 0.11.0
https://github.com/chfast/intx/compare/v0.10.1...v0.11.0
---

intx: add version 0.11.0

---

recipes/openssl/3.x.x/conandata.yml
recipes/openssl/3.x.x/conanfile.py
recipes/openssl/config.yml

Changes to recipe:  **openssl/3.3.1**
---

openssl: add version `3.3.1`

---

recipes/aws-c-sdkutils/all/conandata.yml
recipes/aws-c-sdkutils/all/conanfile.py
recipes/aws-c-sdkutils/config.yml

[aws refactor] aws-c-sdkutils: Add 0.1.15 and remove old versions

---

recipes/perfetto/all/conandata.yml
recipes/perfetto/config.yml

Changes to recipe:  **perfetto/47.0**
There are lots of improvements in 47.0.
https://github.com/google/perfetto/compare/v45.0...v47.0
---

perfetto: add version 47.0

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.14.5**
There are several improvements in 0.14.5.
https://github.com/thorvg/thorvg/compare/v0.14.4...v0.14.5
---

thorvg: add version 0.14.5

---

recipes/aws-c-io/all/conandata.yml
recipes/aws-c-io/all/conanfile.py
recipes/aws-c-io/config.yml

[aws refactor] aws-c-io: Remove some versions and unify dependencies

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Changes to recipe:  **quill/6.1.0**
There are several improvements in 6.1.0
https://github.com/odygrd/quill/compare/v6.0.0...v6.1.0
---

quill: add version 6.1.0

---

recipes/aws-c-http/all/conandata.yml
recipes/aws-c-http/all/conanfile.py
recipes/aws-c-http/config.yml

[aws refactor] aws-c-http: Reduce versions and unify dependency versions

---

recipes/aws-c-mqtt/all/conandata.yml
recipes/aws-c-mqtt/all/conanfile.py
recipes/aws-c-mqtt/config.yml

[aws refactor] aws-c-mqtt: Add only needed versions (0.10.3 and 0.7.8)

---

recipes/cpp-channel/all/conandata.yml
recipes/cpp-channel/config.yml

Changes to recipe:  **cpp-channel/0.8.3**
There are minor improvements in 0.8.3.
https://github.com/andreiavrammsd/cpp-channel/compare/v0.8.2...v0.8.3
---

cpp-channel: add version 0.8.3

---

recipes/simdutf/all/conandata.yml
recipes/simdutf/config.yml

Changes to recipe:  **simdutf/5.3.5**
There are several improvements since 5.3.2.
https://github.com/simdutf/simdutf/compare/v5.3.2...v5.3.5
---

simdutf: add version 5.3.5

---

recipes/functionalplus/all/conandata.yml
recipes/functionalplus/config.yml

Changes to recipe:  **functionplus/0.2.25**
There are small improvements in 0.2.24.
https://github.com/Dobiasd/FunctionalPlus/compare/v0.2.24...v0.2.25
---

functionplus: add version 0.2.25

---

recipes/aws-c-s3/all/conandata.yml
recipes/aws-c-s3/all/conanfile.py
recipes/aws-c-s3/config.yml

[aws refactor] aws-c-s3: Add versions 0.1.26 and 0.5.5 only

---

recipes/asio/all/conandata.yml
recipes/asio/config.yml

Changes to recipe:  **asio/1.31.0**
There are several improvements in 1.31.0.
https://github.com/chriskohlhoff/asio/compare/12e0ce9e0500bf0f247dbd1ae894272656456079...1f534288b4be0be2dd664aab43882a0aa3106a1d
---

asio: add version 1.31.0

---

recipes/samurai/all/conandata.yml
recipes/samurai/config.yml

Changes to recipe:  **samurai/0.16.0**
There are several improvements and bugfixes since 0.13.0.
https://github.com/hpc-maths/samurai/compare/v0.13.0...v0.16.0
---

samurai: add version 0.16.0

---

recipes/sqlite3/all/conandata.yml
recipes/sqlite3/config.yml

Changes to recipe:  **sqlite3/3.46.1**
There are several improvements in 3.46.1.
https://github.com/sqlite/sqlite/compare/version-3.46.0...version-3.46.1
---

sqlite3: add version 3.46.1

---

recipes/llama-cpp/all/cmake/llama-cpp-cuda-static.cmake
recipes/llama-cpp/all/conanfile.py

This PR adds a build module for consumers to add the CUDA targets when using CUDA with llama-cpp in static.

Fix linking problems when using CUDA with llama-cpp in static

---

recipes/spy/all/conandata.yml
recipes/spy/all/conanfile.py
recipes/spy/all/test_package/conanfile.py
recipes/spy/config.yml

Changes to recipe:  **spy/1.1.0**
There are several improvements in 1.1.0.
https://github.com/jfalcou/spy/compare/1.0.0...1.1.0
---

spy: add version 1.1.0

---

recipes/toml11/all/conandata.yml
recipes/toml11/config.yml

Changes to recipe:  **toml11/***
There are several improvements in 4.2.0.
https://github.com/ToruNiina/toml11/compare/v4.1.0...v4.2.0
---

toml11: add version 4.2.0, remove older versions

---

recipes/entt/3.x.x/conandata.yml
recipes/entt/config.yml

entt: add version 3.13.2

---

recipes/simdutf/all/conandata.yml
recipes/simdutf/config.yml

Changes to recipe:  **simdutf/5.3.7**
There is an improvements in 5.3.7.
https://github.com/simdutf/simdutf/compare/v5.3.5...v5.3.7.
---

simdutf: add version 5.3.7

---

recipes/utfcpp/all/conandata.yml
recipes/utfcpp/all/conanfile.py
recipes/utfcpp/all/test_package/conanfile.py
recipes/utfcpp/config.yml

Changes to recipe:  **utfcpp/***
Try to close https://github.com/conan-io/conan-center-index/issues/24760.
https://github.com/nemtrif/utfcpp/compare/v4.0.4...v4.0.5
---

utfcpp: add version 4.0.5 and remove older versions

---

recipes/fast_float/all/conandata.yml
recipes/fast_float/all/conanfile.py
recipes/fast_float/all/test_package/conanfile.py
recipes/fast_float/config.yml

Changes to recipe:  **fast_float/6.1.4**
There are several improvements in 6.1.4.
https://github.com/fastfloat/fast_float/compare/v6.1.3...v6.1.4
---

fast_float: add version 6.1.4

---

recipes/rapidyaml/all/conandata.yml
recipes/rapidyaml/all/patches/0.7.1-001-remove-internal-c4core.patch
recipes/rapidyaml/config.yml

Changes to recipe:  **rapidyaml/0.7.1**
There are several bugfixes in 0.7.1.
https://github.com/biojppm/rapidyaml/compare/v0.7.0...v0.7.1
---

rapidyaml: add version 0.7.1

---

recipes/c4core/all/conandata.yml
recipes/c4core/all/patches/0.2.2-0001-make-fast_float-external.patch
recipes/c4core/config.yml

Changes to recipe:  **c4core/0.2.2**
There are several new features in 0.2.2.
https://github.com/biojppm/c4core/compare/v0.2.1...v0.2.2
---

c4core: add version 0.2.2

---

recipes/sqlitecpp/all/conandata.yml
recipes/sqlitecpp/config.yml

Changes to recipe:  **sqlitecpp/3.3.2**
There are several improvements in 3.3.2.
https://github.com/SRombauts/SQLiteCpp/compare/3.3.1...3.3.2
---

sqlitecpp: add version 3.3.2

---

recipes/liburing/all/conandata.yml
recipes/liburing/all/patches/liburing-2.4-disable_samples_and_tests.patch
recipes/liburing/config.yml

Changes to recipe:  **liburning/2.7**
There are several improvements in 2.7.
https://github.com/axboe/liburing/compare/liburing-2.6...liburing-2.7
---

liburning: add version 2.7

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.14.6**
There are several improvements in 0.14.6.
https://github.com/thorvg/thorvg/compare/v0.14.5...v0.14.6
---

thorvg: add version 0.14.6

---

recipes/abseil/all/conandata.yml
recipes/abseil/all/conanfile.py
recipes/abseil/config.yml

Changes to recipe:  **abseil/all**
New version
https://github.com/abseil/abseil-cpp/compare/20240116.2...20240722.0
---

abseil: add version 20240722.0

---

recipes/libalsa/all/conandata.yml
recipes/libalsa/all/conanfile.py
recipes/libalsa/config.yml

Changes to recipe:  **libalsa/1.2.12**
There are several improvements since 1.2.10.
https://github.com/alsa-project/alsa-lib/compare/v1.2.10...v1.2.12
---

libalsa: add version 1.2.12

---

recipes/qt/6.x.x/conanfile.py
recipes/qt/6.x.x/test_package/CMakeLists.txt
recipes/qt/6.x.x/test_package/conanfile.py
recipes/qt/6.x.x/test_package/test_macos_bundle.cpp

Changes to recipe:  **qt/6.x.x**
Previous PR: https://github.com/conan-io/conan-center-index/pull/24642 did not fix this issue https://github.com/conan-io/conan-center-index/issues/20574
The path is still wrong and doesn't work with downstream projects.
* Set the correct path to the `Info.plist.app.in` folder.
* Removed the previous copy of this file.
* Added extra simple check to test_package
---

Fix Mac installation

---

recipes/hdf5/all/conanfile.py

Changes to recipe:  **hdf5/[1.14.4]**
URL gives 404.
---

hdf5; Fix broken URL

---

recipes/sdbus-cpp/all/conandata.yml
recipes/sdbus-cpp/all/conanfile.py
recipes/sdbus-cpp/all/patches/0003-fix-expat-casing-and-library-linkage.patch

sdbus-cpp: setting the correct variable for newer version

---

recipes/angelscript/all/conandata.yml
recipes/angelscript/all/conanfile.py
recipes/angelscript/config.yml

Changes to recipe:  **angelscript/2.37.0**
Try to close https://github.com/conan-io/conan-center-index/issues/24757.
https://github.com/codecat/angelscript-mirror/compare/4649200f34a8f67378776c87e6f144136b26e2ee...d259eab41fd08fbde83cf1a7b01f4def6a09e895
---

angelscript: add version 2.37.0

---

recipes/cpp-dump/all/conandata.yml
recipes/cpp-dump/all/conanfile.py
recipes/cpp-dump/config.yml

Changes to recipe:  **cpp-dump/0.7.0**
There are several new features in 0.7.0.
https://github.com/philip82148/cpp-dump/compare/v0.6.0...v0.7.0
---

cpp-dump: add version 0.7.0

---

recipes/s2n/all/conandata.yml
recipes/s2n/all/conanfile.py
recipes/s2n/config.yml

Changes to recipe:  **s2n/1.5.1**
There is several new features in 1.5.1.
https://github.com/aws/s2n-tls/compare/v1.5.0...v1.5.1
---

s2n: add version 1.5.1

---

recipes/mgclient/all/conandata.yml
recipes/mgclient/config.yml

There are several improvements in 1.4.3.
https://github.com/memgraph/mgclient/compare/v1.4.2...v1.4.3
---

mgclient: add version 1.4.3

---

recipes/nghttp3/all/conandata.yml
recipes/nghttp3/config.yml

Changes to recipe:  **nghttp3/1.5.0**
There are several improvements in 1.5.0.
https://github.com/ngtcp2/nghttp3/compare/v1.4.0...v1.5.0
---

nghttp3: add version 1.5.0

---

recipes/simdutf/all/conandata.yml
recipes/simdutf/config.yml

Changes to recipe:  **simdutf/5.4.15**
There are several improvements since 5.3.7.
https://github.com/simdutf/simdutf/compare/v5.3.7...v5.4.15
---

simdutf: add version 5.4.15

---

recipes/openmesh/all/conandata.yml
recipes/openmesh/config.yml

Changes to recipe:  **openmesh/11.0**
A new release for OpenMesh: https://www.graphics.rwth-aachen.de/software/openmesh/download/
---

openmesh: add v11.0

---

recipes/stringzilla/all/conandata.yml
recipes/stringzilla/config.yml

Changes to recipe:  **stringzilla/3.9.3**
There are several improvements since 3.9.0.
https://github.com/ashvardanian/StringZilla/compare/v3.9.0...v3.9.3
---

stringzilla: add version 3.9.3

---

recipes/openvino/all/conanfile.py

[openvino] enable debug build

---

recipes/sqlite_orm/all/conandata.yml
recipes/sqlite_orm/all/conanfile.py
recipes/sqlite_orm/config.yml

Changes to recipe:  **sqlite_orm/1.9**
There are several new features in 1.9.
https://github.com/fnc12/sqlite_orm/compare/v1.8.2...v1.9
---

sqlite_orm: add version 1.9

---

recipes/iphreeqc/all/conandata.yml
recipes/iphreeqc/all/conanfile.py
recipes/iphreeqc/all/patches/3.8.1-0001-dont-build-examples-doc-database.patch
recipes/iphreeqc/all/test_package/CMakeLists.txt
recipes/iphreeqc/all/test_package/conanfile.py
recipes/iphreeqc/all/test_package/test_package.c
recipes/iphreeqc/config.yml

Changes to recipe:  **iphreeqc/3.8.1**
Add iphreeqc (a geochemical library) to conan-center.
---

Add new recipe iphreeqc/3.8.1

---

recipes/ada/all/conandata.yml
recipes/ada/config.yml

Changes to recipe:  **ada/2.9.1**
There are several improvements in 2.9.1.
https://github.com/ada-url/ada/compare/v2.9.0...v2.9.1
---

ada: add version 2.9.1

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/all/conanfile.py
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/v0.7.0**
New release of https://github.com/jeremy-rifkin/cpptrace
I'm the author :)
---

cpptrace: Add v0.7.0

---

recipes/valijson/all/conandata.yml
recipes/valijson/config.yml

Changes to recipe:  **valijson/1.0.3**
There are several improvements in 1.0.3.
https://github.com/tristanpenman/valijson/compare/v1.0.2...v1.0.3
---

valijson: add version 1.0.3

---

recipes/rocksdb/all/conandata.yml
recipes/rocksdb/config.yml

Changes to recipe:  **rocksdb/9.5.2**
New version
---

rocksdb: Add version 9.5.2

---

recipes/tree-sitter/all/conandata.yml
recipes/tree-sitter/all/conanfile.py
recipes/tree-sitter/config.yml

Changes to recipe:  **tree-sitter/0.23.0**
There are several improvements in 0.23.0.
https://github.com/tree-sitter/tree-sitter/compare/v0.22.6...v0.23.0
---

tree-sitter: add version 0.23.0

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/config.yml

Add cppcheck 2.15.0

---

recipes/arrow/all/conanfile.py
recipes/date/all/conanfile.py

Changes to recipe:  **date/all**
Fix #24997
Add an option to install all headers
---
© 2024 Morgan Stanley.
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE Conan-io project Contributor License Agreement.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY …

date : add an option to install all headers

---

recipes/podofo/all/conandata.yml
recipes/podofo/all/conanfile.py
recipes/podofo/config.yml

Changes to recipe:  **podofo/[*]**
Old version uses auto_ptr, remove it, and fix conflicts in its own graph. Use version ranges where necessary

podofo: Fix conflicts in podofo, remove oldest version

---

recipes/simfil/all/conandata.yml
recipes/simfil/config.yml

Changes to recipe:  **simfil/0.3.2**
Bump simfil to the latest version.
---

simfil: Bump 0.3.2

---

recipes/etl/all/conandata.yml
recipes/etl/config.yml

Changes to recipe:  **etl/20.39.4**
There are several improvements in 20.39.4.
https://github.com/ETLCPP/etl/compare/20.39.3...20.39.4
---

etl: add version 20.39.4

---

recipes/popt/1.19/conanfile.py

Changes to recipe:  **popt/1.19**
Updated libiconv dependency to version 1.17
---

popt: Updated libiconv dependency to version 1.17

---

recipes/sdl/all/conandata.yml
recipes/sdl/all/conanfile.py
recipes/sdl/all/test_package/conanfile.py
recipes/sdl/config.yml

Changes to recipe:  **sdl/2.30.7**
There are several bugfixes in 2.30.7.
https://github.com/libsdl-org/SDL/compare/release-2.30.6...release-2.30.7
---

sdl: add version 2.30.7

---

recipes/cpp-httplib/all/conandata.yml
recipes/cpp-httplib/config.yml

Changes to recipe:  **cpp-httplib/0.17.1**
There is a new features in 0.17.1.
https://github.com/yhirose/cpp-httplib/compare/v0.16.3...v0.17.1
---

cpp-httplib: add version 0.17.1

---

recipes/xorg/all/conanfile.py

Alpine support for `xorg` using `apk`
Close: #25111

Alpine support for `xorg`

---

recipes/eigen/all/conandata.yml
recipes/eigen/config.yml

Reverts conan-io/conan-center-index#25048

Revert "eigen: add version cci. 20240315 (pre 3.4.1)"

---

recipes/ada/all/conandata.yml
recipes/ada/config.yml

Changes to recipe:  **ada/2.9.2**
There is a bugfix on 2.9.2.
https://github.com/ada-url/ada/compare/v2.9.1...v2.9.2
---

ada: add version 2.9.2

---

recipes/itlib/all/conandata.yml
recipes/itlib/config.yml

Changes to recipe:  **itlib/1.11.3**
There is a bugfix in 1.11.3.
https://github.com/iboB/itlib/compare/v1.11.2...v1.11.3
---

itlib: add version 1.11.3

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/3.3.2**
There are several bugfixes in 3.3.2.
https://github.com/stephenberry/glaze/compare/v3.3.1...v3.3.2
---

glaze: add version 3.3.2

---

recipes/frozen/all/conandata.yml
recipes/frozen/config.yml

Changes to recipe:  **frozen/1.2.0**
Add frozen 1.2.0
---

[frozen] add 1.2.0

---

recipes/cpp-peglib/1.x.x/conandata.yml
recipes/cpp-peglib/config.yml

Changes to recipe:  **cpp-peglib/1.9.0**
There is a new feature in 1.9.0.
https://github.com/yhirose/cpp-peglib/compare/v1.8.8...v1.9.0
---

cpp-peglib: add version 1.9.0

---

recipes/intx/all/conandata.yml
recipes/intx/config.yml

Changes to recipe:  **intx/0.12.0**
There are several new features in 0.12.0.
https://github.com/chfast/intx/compare/v0.11.0...v0.12.0
---

intx: add version 0.12.0

---

recipes/roaring/all/conandata.yml
recipes/roaring/config.yml

Changes to recipe:  **roaring/4.1.2**
There is a new feature in 4.1.2.
https://github.com/RoaringBitmap/CRoaring/compare/v4.1.1...v4.1.2
---

roaring: add version 4.1.2

---

recipes/c-ares/all/conandata.yml
recipes/c-ares/config.yml

Changes to recipe:  **c-ares/1.33.1**
1.33.1 is bugfix release.
https://github.com/c-ares/c-ares/compare/v1.33.0...v1.33.1
---

c-ares: add version 1.33.1

---

recipes/simdutf/all/conandata.yml
recipes/simdutf/config.yml

Changes to recipe:  **simdutf/5.5.0**
There are several improvements in 5.5.0.
https://github.com/simdutf/simdutf/compare/v5.4.15...v5.5.0
---

simdutf: add version 5.5.0

---

recipes/plutovg/all/conandata.yml
recipes/plutovg/config.yml

Changes to recipe:  **plutovg/0.0.4**
There are several bugfixes and new features in 0.0.4.
https://github.com/sammycage/plutovg/compare/v0.0.1...v0.0.4
---

plutovg: add version 0.0.4

---

recipes/cpp-httplib/all/conandata.yml
recipes/cpp-httplib/config.yml

Changes to recipe:  **cpp-httplib/0.17.3**
There is a bugfix and a performance improvement in 0.17.3.
https://github.com/yhirose/cpp-httplib/compare/v0.17.1...v0.17.3
---

cpp-httplib: add version 0.17.3

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/3.3.4**
3.3.4 supports 32bit build.
https://github.com/stephenberry/glaze/compare/v3.3.2...v3.3.4
---

glaze: add version 3.3.4

---

recipes/wxwidgets/all/conandata.yml
recipes/wxwidgets/config.yml

Changes to recipe:  **wxwidgets/3.2.6**
There are lots of improvements in 3.2.6.
https://www.wxwidgets.org/news/2024/09/wxwidgets-3.2.6-released/
https://github.com/wxWidgets/wxWidgets/compare/v3.2.5...v3.2.6
---

wxwidgets: add version 3.2.6

---

docs/package_templates/autotools_package/all/conanfile.py
docs/package_templates/meson_package/all/conanfile.py
docs/package_templates/meson_package/all/test_package/conanfile.py

Changes package templates in docs
Update package templates in order to follow version range recommendation for meson & pkgconf.
---

docs: use version range for meson & pkgconf in package templates

---

recipes/liblqr/all/CMakeLists.txt
recipes/liblqr/all/conandata.yml
recipes/liblqr/all/conanfile.py
recipes/liblqr/all/test_package/CMakeLists.txt
recipes/liblqr/all/test_package/conanfile.py
recipes/liblqr/all/test_package/test_package.c
recipes/liblqr/config.yml

Changes to recipe:  **liblqr/0.4.3**
Add Liquid Rescale library to conancenter.
There is no build files for Visual Studio, but instructions in https://github.com/carlobaldassi/liblqr/blob/master/README.Windows. I've created a specific CMakeLists for this case, so that include layout and lib name can be consistent with autotools install for other compilers, and what is written in upstream pkgconfig file.
---

add new recipe liblqr/0.4.3

---

recipes/imath/all/conandata.yml
recipes/imath/config.yml

Changes to recipe:  **imath/3.1.12**
Just bumping to the newest release.
Improvements according to announcmenet are mainly in the build system and small improvements for the headers for compile compatibility with some platforms.
---

imath: Add version 3.1.12

---

recipes/aravis/all/conandata.yml
recipes/aravis/config.yml

Changes to recipe:  **aravis/0.8.33**
Contains some bug fixes, doesn't seem to contain any changes to the build system.
[Changes between 0.8.30..0.8.33](https://github.com/AravisProject/aravis/compare/0.8.30...0.8.33)
---

aravis: add version 0.8.33

---

docs/changelog.md

Update the changelog with most important changes related to the ConanCenterIndex CI service.
The configuration update has been done by: https://github.com/conan-io/conan-center-index/pull/25227
Validated on the PR https://github.com/conan-io/conan-center-index/pull/25239 
---

[docs] Add changelog entry for update done on 12-SEP-2024

---

recipes/trantor/all/conandata.yml
recipes/trantor/config.yml

Changes to recipe:  **trantor/1.5r.21**
There is a new features in 1.5.21.
https://github.com/an-tao/trantor/compare/v1.5.20...v1.5.21
---

trantor: add version 1.5.21

---

recipes/materialx/all/conandata.yml
recipes/materialx/all/conanfile.py
recipes/materialx/config.yml

Upgrade MaterialX to 1.39.1 release

---

recipes/openssl/3.x.x/conandata.yml
recipes/openssl/3.x.x/conanfile.py
recipes/openssl/config.yml

Changes to recipe:  **openssl/[3.0.15, 3.1.7, 3.2.3, 3.3.2]**
---

openssl: add versions `3.0.15`, `3.1.7`, `3.2.3`, `3.3.2`

---

recipes/cpp-httplib/all/conandata.yml
recipes/cpp-httplib/config.yml

Changes to recipe:  **cpp-httplib/0.18.0**
There are several new features in 0.18.0.
https://github.com/yhirose/cpp-httplib/compare/v0.17.3...v0.18.0
---

cpp-httplib: add version 0.18.0

---

recipes/geos/all/conandata.yml
recipes/geos/all/conanfile.py
recipes/geos/config.yml

Changes to recipe:  **geos/3.13.0**
There are lots of improvements in 3.13.0.
https://github.com/libgeos/geos/compare/3.12.2...3.13.0
---

geos: add version 3.13.0

---

recipes/stringzilla/all/conandata.yml
recipes/stringzilla/config.yml

Changes to recipe:  **stringzilla/3.9.6**
There are several improvements since 3.9.6.
https://github.com/ashvardanian/StringZilla/compare/v3.9.3...v3.9.6
---

stringzilla: add version 3.9.6

---

recipes/md4qt/all/conandata.yml
recipes/md4qt/config.yml

Changes to recipe:  **md4qt/3.0.0**
This is a major update to **md4qt**, were done a lot of addons and useful things for developers,
were fixed different issues.
**Full Changelog:** [2.8.2...3.0.0](https://github.com/igormironchik/md4qt/compare/2.8.2...3.0.0)
---

md4qt: add version 3.0.0

---

recipes/inipp/all/conandata.yml
recipes/inipp/all/conanfile.py
recipes/inipp/all/test_package/CMakeLists.txt
recipes/inipp/all/test_package/conanfile.py
recipes/inipp/all/test_package/test_package.cpp
recipes/inipp/config.yml

Changes to recipe:  **inipp/***
ini parser library.
https://github.com/mcmtroffaes/inipp/
---

inipp: add new recipe

---

recipes/statistic/all/conandata.yml
recipes/statistic/all/conanfile.py
recipes/statistic/all/test_package/CMakeLists.txt
recipes/statistic/all/test_package/conanfile.py
recipes/statistic/all/test_package/test_package.cpp
recipes/statistic/config.yml

Changes to recipe:  **statistic/1.0.8**
Simple and easy-to-use statistics library
https://github.com/RobTillaart/Statistic
---

statistic: add recipe

---

recipes/daw_utf_range/all/conandata.yml

Changes to recipe:  **daw_utf_range/2.2.5**
daw_header_libraries/2.110.0 fixed several bugs.
I want to apply these fixes to daw_utf_range and daw_json_link.
---

daw_utf_range: update daw_header_libraries/2.110.0

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/3.4.1**
There is breaking changes.
https://github.com/stephenberry/glaze/compare/v3.3.4...v3.4.1
---

glaze: add version 3.4.1

---

recipes/libtiff/all/conandata.yml
recipes/libtiff/config.yml

Changes to recipe:  **libtiff/4.7.0**
Add version 4.7.0 
CVE fixes - 
Read about this release at 
https://libtiff.gitlab.io/libtiff/releases/v4.7.0.html
---

[libtiff/4.7.0] Add version 4.7.0 to libtiff

---

recipes/greg7mdp-gtl/all/conandata.yml
recipes/greg7mdp-gtl/config.yml

[greg7mdp-gtl] Bump version to 1.2.0

---

recipes/roaring/all/conandata.yml
recipes/roaring/config.yml

Changes to recipe:  **roaring/4.1.7**
There are several minor improvemens since 4.1.2.
https://github.com/RoaringBitmap/CRoaring/compare/v4.1.2...v4.1.7
---

roaring: add version 4.1.7

---

recipes/wayland-protocols/all/conandata.yml
recipes/wayland-protocols/all/conanfile.py
recipes/wayland-protocols/config.yml

Needed by the latest GTK 4.x in #25090.
---

wayland-protocols: add v1.36

---

recipes/plutovg/all/conandata.yml
recipes/plutovg/config.yml

There are several improvements in 0.0.5.
https://github.com/sammycage/plutovg/compare/v0.0.4...v0.0.5
---

plutovg: add version 0.0.5

---

recipes/quill/all/conandata.yml
recipes/quill/all/conanfile.py
recipes/quill/config.yml

Changes to recipe:  **quill/7.2.1**
There are several new features since 7.2.1.
https://github.com/odygrd/quill/compare/v7.1.0...v7.2.1
---

quill: add version 7.2.1

---

recipes/sbepp/all/conandata.yml
recipes/sbepp/config.yml

Specify library name and version:  **sbepp/1.4.1**
I'm the project author, adding version 1.4.1.
---

sbepp: add version 1.4.1

---

recipes/s2n/all/conandata.yml
recipes/s2n/config.yml

Changes to recipe:  **s2n/1.5.3**
There are several bugfixes in 1.5.3.
https://github.com/aws/s2n-tls/compare/v1.5.2...v1.5.3
---

s2n: add version 1.5.3

---

recipes/aws-c-io/all/conanfile.py

aws-c-io: Bring s2n verison in line with sdk

---

recipes/proj/all/conandata.yml
recipes/proj/all/conanfile.py
recipes/proj/all/test_package/CMakeLists.txt
recipes/proj/config.yml

Changes to recipe:  **proj/9.5.0**
There are lots of improvements in 9.5.0.
https://github.com/OSGeo/PROJ/compare/9.4.1...9.5.0
---

proj: add version 9.5.0

---

recipes/optimlib/all/CMakeLists.txt
recipes/optimlib/all/conandata.yml
recipes/optimlib/all/conanfile.py
recipes/optimlib/all/test_package/CMakeLists.txt
recipes/optimlib/all/test_package/conanfile.py
recipes/optimlib/all/test_package/test_package.cpp
recipes/optimlib/config.yml

Changes to recipe:  **optimlib/3.1.3**
OptimLib: a lightweight C++ library of numerical optimization methods for nonlinear functions
https://github.com/kthohr/optim
The project uses a custom `./configure` + `Makefile` setup to configure and build the library. The configure script mostly deals with the third-party dependencies, plus setting some defines and build flags. Although I would prefer not to, I found it more straightforward and robust to simply rewrite it as a CMakeLists.txt instead. Most of the logic in the configure script is already covered by the generated CMakeDeps modules and the default build_type-specific CMake behaviors.
/cc @kthohr
---

optimlib: new recipe

---

recipes/wasmedge/all/conandata.yml
recipes/wasmedge/config.yml

Changes to recipe:  **wasmedge/0.14.1**
There are several improvements in 0.14.1.
https://github.com/WasmEdge/WasmEdge/compare/0.14.0...0.14.1
---

wasmedge: add version 0.14.1

---

recipes/tixi3/all/conanfile.py

Builds locally for me on Macos

tixi3: Bump lixslt for libxml2 support

---

recipes/eudev/all/conanfile.py
recipes/xmlsec/all/conanfile.py

Compiles locally in linux for me

eudev: Bump lixslt for libxml2 support

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Changes to recipe:  **quill/7.2.2**
There are several improvements in 7.2.2.
https://github.com/odygrd/quill/compare/v7.2.1...v7.2.2
---

quill: add version 7.2.2

---

recipes/plutovg/all/conandata.yml
recipes/plutovg/all/test_package/test_package.c
recipes/plutovg/config.yml

Changes to recipe:  **plutovg/0.0.6**
There is an improvement in 0.0.6.
https://github.com/sammycage/plutovg/compare/v0.0.5...v0.0.6
---

plutovg: add version 0.0.6

---

recipes/wolfssl/all/conandata.yml
recipes/wolfssl/all/conanfile.py
recipes/wolfssl/config.yml

Changes to recipe:  **wolfssl/5.7.2**
There are several vulnerabilities fix in 5.7.2.
https://github.com/wolfSSL/wolfssl/compare/v5.7.0-stable...v5.7.2-stable
---

wolfssl: add version 5.7.2

---

recipes/mcap/all/conandata.yml
recipes/mcap/config.yml

Changes to recipe:  **mcap/1.4.1**
Version bump only
Version bump only
---

mcap: add version 1.4.1

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.14.10**
There are lots of improvements since 0.14.6.
https://github.com/thorvg/thorvg/compare/v0.14.6...v0.14.10
---

thorvg: add version 0.14.10

---

recipes/openpam/all/conandata.yml
recipes/openpam/all/conanfile.py
recipes/openpam/config.yml

Changes to recipe:  **openpam/20230627**
Also
- Removed an irrelevant C++ version check for a C-only library.
- Added an alternative official URL for the source code archives.
---

openpam: add v20230627

---

recipes/itlib/all/conandata.yml
recipes/itlib/all/conanfile.py
recipes/itlib/config.yml

Changes to recipe:  **itlib/***
There is an minor improvements in 1.11.4.
https://github.com/iboB/itlib/compare/v1.11.3...v1.11.4
---

itlib: add version 1.11.4, remove older versions

---

recipes/cpython/all/conandata.yml
recipes/cpython/config.yml

Changes to recipe:  **cpython/3.12.7**
All CPython version 3.12.5 and below have CVEs: https://repology.org/project/python/information
---

cpython: add v3.12.7

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/config.yml

[sentry-native] Add version 0.7.10

---

recipes/sail/all/conandata.yml
recipes/sail/config.yml

Changes to recipe:  **sail/0.9.6**
New upstrem release.
---

sail: Add 0.9.6

---

recipes/dataframe/all/conandata.yml
recipes/dataframe/config.yml

Changes to recipe:  **DataFrame/3.3.0**
Moving to a new version
Improved documentation both visually and content-wise
Changed NLargestVisitor to take N as constructor parameter instead of template parameter (backward incompatible change)
**Implemented get_top_n_\[data|view\]()**
**Implemented get_bottom_n_\[data|view\]()**
**Implemented get_above_quantile_\[data|view\]()**
**Implemented get_below_quantile_\[data|view\]()**
Added period parameter to ReturnVisitor visitor
Implemented starts_with()
Implemented ends_with()
Implemented CumCountVisitor visitor
Implemented in_between()
Implemented peaks()
Implemented valleys()
Made reading/writing large files faster
Implemented apply()
Made replace() faster with better algorithm
Implemented truncate()
Implemented a version of load_column() with …

Upgrading C++ DataFrame to version 3.3.0

---

recipes/cnats/all/conandata.yml
recipes/cnats/config.yml

Changes to recipe:  **cnats/3.9.0**
v3.9.0 is released with new features: https://github.com/nats-io/nats.c/releases/tag/v3.9.0
Changelog:
- https://github.com/nats-io/nats.c/compare/v3.8.0...v3.9.0
- https://github.com/nats-io/nats.c/compare/v3.9.0...v3.9.1
---

cnats: add version 3.9.1

---

recipes/imgui/all/conandata.yml
recipes/imgui/config.yml

Changes to recipe:  **imgui/1.91.3**
A few nice small fixes added in upstream that I'm interested in.
See upstream changelog: https://github.com/ocornut/imgui/releases/tag/v1.91.3
---

imgui: add version 1.91.3

---

recipes/fakeit/all/conandata.yml
recipes/fakeit/config.yml

Changes to recipe:  **fakeit/2.4.1**
There are several improvements in 2.4.1.
https://github.com/eranpeer/FakeIt/compare/2.4.0...2.4.1
---

fakeit: add version 2.4.1

---

recipes/xbyak/all/conandata.yml
recipes/xbyak/config.yml

Changes to recipe:  **xbyak/7.08**
There is a new feature in 7.08.
https://github.com/herumi/xbyak/compare/v7.07.1...v7.08
---

xbyak: add version 7.08

---

recipes/onnx/all/conandata.yml
recipes/onnx/all/conanfile.py
recipes/onnx/config.yml

Changes to recipe:  **onnx/1.17.0**
Add version 1.17.0
https://github.com/onnx/onnx/compare/v1.16.2...v1.17.0
---

onnx: add version 1.17.0

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/0.7.2**
New version, I'm the author.
---

cpptrace: Add v0.7.2

---

recipes/libvips/all/conandata.yml
recipes/libvips/all/conanfile.py
recipes/libvips/all/patches/0001-fix-8-15-3-msvc-build.patch
recipes/libvips/config.yml

Changes to recipe:  **libvips/8.15.3**
I added a patch to fix a msvc build issue ([see](https://github.com/libvips/libvips/pull/4153)). 
I had to hand modify the patch line numbers, I hope that's not a problem?
Also I tried to add the nifti_clib support, that resulted in link errors however. I guess that requires some further attention in the future...
---

libvips update to 8.15.3

---

recipes/plutovg/all/conandata.yml
recipes/plutovg/config.yml

Changes to recipe:  **plutovg/0.0.7**
There is a bug fix in 0.0.7.
https://github.com/sammycage/plutovg/compare/v0.0.6...v0.0.7
---

plutovg: add version 0.0.7

---

recipes/safe/all/conandata.yml
recipes/safe/config.yml

Changes to recipe:  **safe/2.0.0**
This is a major version up.
https://github.com/LouisCharlesC/safe/compare/v1.1.1...v2.0.0
---

safe: add version 2.0.0

---

recipes/nng/all/conandata.yml
recipes/nng/all/conanfile.py
recipes/nng/config.yml

Changes to recipe:  **nng/1.9.0**
nng/1.9.0 supports wolfssl.
https://github.com/nanomsg/nng/compare/v1.8.0...v1.9.0
---

nng: add version 1.9.0

---

recipes/zpp_bits/all/conandata.yml
recipes/zpp_bits/config.yml

Changes to recipe:  **zpp_bits/4.4.24**
Try to close https://github.com/conan-io/conan-center-index/issues/25581.
https://github.com/eyalz800/zpp_bits/compare/v4.4.20...v4.4.24
---

zpp_bits: add version 4.4.24

---

recipes/tree-sitter/all/conandata.yml
recipes/tree-sitter/all/conanfile.py
recipes/tree-sitter/config.yml

Changes to recipe:  **tree-sitter/0.24.3**
There are several of improvements since 0.23.1.
https://github.com/tree-sitter/tree-sitter/compare/v0.23.1...v0.24.3
---

tree-sitter: add new version 0.24.3

---

recipes/cpr/all/conandata.yml
recipes/cpr/all/conanfile.py
recipes/cpr/all/patches/008-1.11.0-remove-warning-flags.patch
recipes/cpr/config.yml

Changes to recipe:  **cpr/1.11.0**
There are lots of improvements in 1.11.0.
https://github.com/libcpr/cpr/compare/1.10.5...1.11.0
---

cpr: add version 1.11.0

---

recipes/wasmer/all/conandata.yml
recipes/wasmer/config.yml

Changes to recipe:  **wasmer/4.4.0**
There are several improvements and bugfixes since 4.4.0.
https://github.com/wasmerio/wasmer/compare/v4.3.3...v4.4.0
---

wasmer: add version 4.4.0

---

recipes/xbyak/all/conandata.yml
recipes/xbyak/config.yml

Changes to recipe:  **xbyak/7.10**
There are several new features since 7.08.
https://github.com/herumi/xbyak/compare/v7.08...v7.10
---

xbyak: add version 7.10

---

recipes/date/all/conandata.yml
recipes/date/all/conanfile.py
recipes/date/config.yml

Changes to recipe:  **date/3.0.2**
There are several improvements in 3.0.2.
https://github.com/HowardHinnant/date/compare/v3.0.1...v3.0.2
---

date: add version 3.0.2

---

recipes/assimp/5.x/conandata.yml
recipes/assimp/5.x/conanfile.py
recipes/assimp/config.yml

Changes to recipe:  **assimp/5.4.3**
Add the latest release

Add assimp 5.4.3

---

recipes/c-blosc2/all/conanfile.py

Changes to recipe:  **c-blosc2/all**
---

c-blosc2: bump zlib-ng

---

recipes/gdcm/all/conanfile.py

Changes to recipe:  **gdcm/all**
---

gdcm: bump zlib-ng

---

recipes/roaring/all/conandata.yml
recipes/roaring/config.yml

Changes to recipe:  **roaring/4.2.1**
This version removed printf debug code.
https://github.com/RoaringBitmap/CRoaring/compare/v4.2.0...v4.2.1
---

roaring: add version 4.2.1

---

recipes/redis-plus-plus/all/conandata.yml
recipes/redis-plus-plus/all/patches/1.3.13-0001-fix-dependencies-injection.patch
recipes/redis-plus-plus/config.yml

Changes to recipe:  **redis-plus-plus/1.3.13**
There are several improvements in 1.3.13.
https://github.com/sewenew/redis-plus-plus/compare/1.3.12...1.3.13
---

redis-plus-plus: add version 1.3.13

---

recipes/plutovg/all/conandata.yml
recipes/plutovg/config.yml

Changes to recipe:  **plutovg/0.0.8**
There are several improvements in 0.0.8.
https://github.com/sammycage/plutovg/compare/v0.0.7...v0.0.8
---

plutovg: add version 0.0.8

---

recipes/bx/all/conanfile.py

Changes to recipe:  **bgfx/cci.20230216**
Only one library can be changed in the same PR
See: #25606
See: #25606

bx: add msvc version 194

---

recipes/bimg/all/conanfile.py

Changes to recipe:  **bgfx/cci.20230216**
Only one library can be changed in the same PR
See: #25606
See: #25606

bimg: add msvc version 194

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/all/conanfile.py
recipes/thorvg/all/test_package/test_package.cpp
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.15.1**
There are lots of improvements since 0.14.10.
https://github.com/thorvg/thorvg/compare/v0.14.10...v0.15.1
---

thorvg: add version 0.15.1

---

recipes/emio/all/conandata.yml
recipes/emio/config.yml

Changes to recipe:  **emio/0.8.0**
Version bump
---

update emio to 0.8.0

---

recipes/imgui/all/conandata.yml
recipes/imgui/config.yml

Changes to recipe:  **imgui/1.91.4**
Keep recipe up to date with upstream
See release notes: https://github.com/ocornut/imgui/releases/tag/v1.91.4
---

imgui: Add version 1.91.4

---

recipes/tl-ranges/all/conandata.yml
recipes/tl-ranges/all/conanfile.py
recipes/tl-ranges/all/test_package/CMakeLists.txt
recipes/tl-ranges/all/test_package/conanfile.py
recipes/tl-ranges/all/test_package/test_package.cpp
recipes/tl-ranges/config.yml

Changes to recipe:  **tl-ranges/cci.20221207**
tl-ranges covers lacks of C++20 standard library.
https://github.com/TartanLlama/ranges/
---

tl-ranges: add recipe

---

recipes/rc_ptr/all/conandata.yml
recipes/rc_ptr/all/conanfile.py
recipes/rc_ptr/all/test_package/CMakeLists.txt
recipes/rc_ptr/all/test_package/conanfile.py
recipes/rc_ptr/all/test_package/test_package.cpp
recipes/rc_ptr/config.yml

Changes to recipe:  **rc_ptr/0.0.2**
Try to close https://github.com/conan-io/conan-center-index/issues/25503.
https://github.com/Chylynsky/rc_ptr/
---

rc_ptr: add recipe

---

recipes/highs/all/conandata.yml
recipes/highs/all/test_package/CMakeLists.txt
recipes/highs/config.yml

Changes to recipe:  **highs/1.8.0**
There are several new features in 1.8.0.
https://github.com/ERGO-Code/HiGHS/compare/v1.7.2...v1.8.0
---

highs: add version 1.8.0

---

recipes/libgit2/all/conandata.yml
recipes/libgit2/config.yml

Changes to recipe:  **libgit2/1.8.2**
There is a new feature in 1.8.2.
https://github.com/libgit2/libgit2/compare/v1.8.1...v1.8.2
---

libgit2: add version 1.8.2

---

recipes/rotor/all/conandata.yml
recipes/rotor/config.yml

Changes to recipe:  **rotor/0.31**
veresion bump
---

[bump] add rotor v0.31

---

recipes/thorvg/all/conanfile.py

Updated the topic to reflect that ThorVG's main feature is its support for Lottie in a 2D vector graphics engine.
---

thorvg: updated topic

---

recipes/date/all/conandata.yml
recipes/date/config.yml

Changes to recipe:  **date/3.0.3**
There is an improvement in 3.0.3.
https://github.com/HowardHinnant/date/compare/v3.0.2...v3.0.3
---

date: add version 3.0.3

---

recipes/openssh/all/conandata.yml
recipes/openssh/config.yml

Changes to recipe:  **openssh/9.9p1**
New version out!
---

openssh: Added openssh 9.9p1

---

recipes/sqlite3/all/conandata.yml
recipes/sqlite3/config.yml

Changes to recipe:  **sqlite3/3.47.0**
There are lots of improvements in 3.47.0.
https://www.sqlite.org/releaselog/3_47_0.html
https://github.com/sqlite/sqlite/compare/version-3.46.1...version-3.47.0
---

sqlite3: add version 3.47.0

---

recipes/kangaru/all/conandata.yml
recipes/kangaru/all/conanfile.py
recipes/kangaru/config.yml

Changes to recipe:  **kangaru/4.3.2**
There is a bug fix in 4.3.2.
https://github.com/gracicot/kangaru/compare/v4.3.1...v4.3.2
---

kangaru: add version 4.3.2

---

recipes/libgit2/all/conandata.yml
recipes/libgit2/config.yml

Changes to recipe:  **libgit2/1.8.3**
There are several bugfixes in 1.8.3.
https://github.com/libgit2/libgit2/compare/v1.8.2...v1.8.3
---

libgit2: add version 1.8.3

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Changes to recipe:  **quill/7.4.0**
There are several improvements in 7.4.0.
https://github.com/odygrd/quill/releases/tag/v7.4.0
---

quill: add version 7.4.0

---

recipes/cfitsio/all/conandata.yml

Changes to recipe:  **cfitsio/[*]**
Closes #25712
As discussed in the linked issue and https://github.com/HEASARC/cfitsio/issues/31 with upstream, this is a valid change based on server modifications

cfitsio: Update checksums based on discussion with upstream

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/all/conanfile.py
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.15.2**
There are several new features in 0.15.2.
https://github.com/thorvg/thorvg/compare/v0.15.1...v0.15.2
---

thorvg: add version 0.15.2

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/all/conanfile.py
recipes/cppcheck/config.yml

Changes to recipe:  **cppcheck/2.16.0**
There are several new features in 2.16.0
https://github.com/danmar/cppcheck/compare/2.15.0...2.16.0
---

cppcheck: add version 1.4.1

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/config.yml

Changes to recipe: **sentry-native/0.7.11**
---

[sentry-native] Add version 0.7.11

---

recipes/kdbindings/all/conandata.yml
recipes/kdbindings/all/conanfile.py
recipes/kdbindings/config.yml

Changes to recipe:  **kdbindings/1.1.0**
There are several new features in 1.1.0.
https://github.com/KDAB/KDBindings/compare/v1.0.5...v1.1.0
---

kdbindings: add version 1.1.0

---

recipes/ocilib/all/conandata.yml
recipes/ocilib/all/conanfile.py
recipes/ocilib/all/test_package/CMakeLists.txt
recipes/ocilib/all/test_package/conanfile.py
recipes/ocilib/all/test_package/test_package.cpp
recipes/ocilib/config.yml

Added new recipe:  **ocilib/4.7.6**
This PR will address issue https://github.com/conan-io/conan-center-index/issues/23867
Reopening #23954 with squashed commits.
---

Add new recipe ocilib/4.7.6

---

recipes/cli/all/conandata.yml
recipes/cli/all/test_package/CMakeLists.txt
recipes/cli/all/test_package/conanfile.py
recipes/cli/config.yml

Changes to recipe:  **cli/2.2.0**
There are several new features in 2.2.0.
Try to close https://github.com/conan-io/conan-center-index/issues/25742.
https://github.com/daniele77/cli/compare/v2.1.0...v2.2.0
---

cli: add version 2.2.0

---

recipes/wasmer/all/conandata.yml
recipes/wasmer/config.yml

Changes to recipe:  **wasmer/5.0.0**
major version up.
https://github.com/wasmerio/wasmer/compare/v4.4.0...v5.0.0
---

wasmer: add version 5.0.0

---

.gitignore

Reverts conan-io/conan-center-index#25752

Revert "Add src folder to .gitignore"

---

recipes/zserio/all/conandata.yml
recipes/zserio/config.yml

Changes to recipe:  **zserio/2.15.0**
New release
---
- [x ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)

zserio: Add new Zserio release 2.15.0

---

recipes/flux/all/conandata.yml
recipes/flux/config.yml

Changes to recipe:  **flux/0.4.0**
https://github.com/tcbrindle/flux/issues/206
---

update flux to version 0.4.0

---

recipes/msgpack-c/all/conandata.yml
recipes/msgpack-c/config.yml

Changes to recipe:  **msgpack-c/6.1.0**
There are several new features in 6.1.0.
https://github.com/msgpack/msgpack-c/compare/c-6.0.0...c-6.1.0
---

msgpack-c: add version 6.1.0

---

recipes/lunasvg/all/conandata.yml
recipes/lunasvg/config.yml

Changes to recipe:  **lunasvg/3.0.1**
There are several bugfixes in 3.0.1.
https://github.com/sammycage/lunasvg/compare/v3.0.0...v3.0.1
---

lunasvg: add version 3.0.1

---

recipes/gsl-lite/all/conandata.yml
recipes/gsl-lite/all/conanfile.py
recipes/gsl-lite/config.yml

Changes to recipe:  **gsl-lite/0.42.0**
There are several new features in 0.42.0.
https://github.com/gsl-lite/gsl-lite/compare/v0.41.0...v0.42.0
---

gsl-lite: add version 0.42.0

---

recipes/asyncpp/all/conanfile.py
recipes/asyncpp/all/test_package/CMakeLists.txt
recipes/asyncpp/all/test_package/conanfile.py

Changes to recipe:  **asyncpp/***
The homepage in conanfile.py is wrong.
https://github.com/petiaccja/asyncpp/
---

asyncpp: fix homepage url

---

recipes/thorvg/all/conandata.yml
recipes/thorvg/config.yml

Changes to recipe:  **thorvg/0.15.3**
There are several bug fixes and improvements in 0.15.3.
https://github.com/thorvg/thorvg/compare/v0.15.2...v0.15.3
---

thorvg: add version 0.15.3

---

recipes/libzip/all/conandata.yml
recipes/libzip/all/patches/1.11.2-0002-remove-rpath.patch
recipes/libzip/config.yml

Changes to recipe:  **libzip/1.11.2**
There is a performance improvements in 1.11.2.
https://github.com/nih-at/libzip/compare/v1.11.1...v1.11.2
---

libzip: add version 1.11.2

---

recipes/rocksdb/all/conandata.yml
recipes/rocksdb/config.yml

Changes to recipe:  **rocksdb/9.7.4**
This is a bug fix release.
https://github.com/facebook/rocksdb/compare/v9.7.3...v9.7.4
---

rocksdb: add version 9.7.4

---

recipes/crossdb/all/conandata.yml
recipes/crossdb/all/conanfile.py
recipes/crossdb/config.yml

Changes to recipe:  **crossdb/0.10.0**
There are several new features in 0.10.0.
https://github.com/crossdb-org/crossdb/compare/0.9.0...0.10.0
---

crossdb: add version 0.10.0

---

recipes/xbyak/all/conandata.yml
recipes/xbyak/config.yml

Changes to recipe:  **xbyak/7.21**
There are several improvements since 7.20.
https://github.com/herumi/xbyak/compare/v7.20...v7.21
---

xbyak: add version 7.21

---

recipes/libxlsxwriter/all/conandata.yml
recipes/libxlsxwriter/all/conanfile.py
recipes/libxlsxwriter/all/patches/1.1.9-0001-fix-cmake.patch
recipes/libxlsxwriter/config.yml

There are a minor improvement in 1.1.9.
https://github.com/jmcnamara/libxlsxwriter/compare/v1.1.8...v1.1.9
---

libxlsxwriter: add new version 1.1.9

---

recipes/daw_json_link/all/conandata.yml
recipes/daw_json_link/config.yml

Changes to recipe:  **daw_json_link/3.29.2**
There are several new features and bugfixes in 3.29.2.
https://github.com/beached/daw_json_link/compare/v3.28.3...v3.29.2
---

daw_json_link: add version 3.29.2

---

recipes/exprtk/all/conandata.yml
recipes/exprtk/all/conanfile.py
recipes/exprtk/all/test_package/test_package.cpp
recipes/exprtk/config.yml

Changes to recipe:  **exprtk/0.0.3**
There are several improvements in 0.0.3.
There is the official license file since 0.0.3.
https://github.com/ArashPartow/exprtk/compare/0.0.2...0.0.3
---

exprtk: add version 0.0.3

---

recipes/s2n/all/conandata.yml
recipes/s2n/config.yml

Changes to recipe:  **s2n/1.5.7**
There are several new features in 1.5.7.
https://github.com/aws/s2n-tls/compare/v1.5.6...v1.5.7
---

s2n: add version 1.5.7

---

recipes/libssh2/all/conanfile.py

Changes to recipe:  libssh2/all
Fix https://github.com/conan-io/conan-center-index/issues/25855
There is a bit of a mis/match between the package name and the expected variables - so tried to align them.
Verified on Windows that it builds without errors and the test package passes (need to verify on Linux and macOS as well)

libssh2 fix issues with mbedtls on Windows

---

recipes/sbepp/all/conandata.yml
recipes/sbepp/config.yml

Changes to recipe:  **sbepp/1.4.2**
I'm the author, adding version `1.4.2`.
---

sbepp: add version 1.4.2

---

recipes/zeus_expected/all/conandata.yml
recipes/zeus_expected/config.yml

Changes to recipe:  **zeus_expected/1.2.0**
Add a new upstream version.
---

zeus_expected: add version 1.2.0

---

recipes/libpopcnt/all/conandata.yml
recipes/libpopcnt/all/conanfile.py
recipes/libpopcnt/all/test_package/CMakeLists.txt
recipes/libpopcnt/all/test_package/conanfile.py
recipes/libpopcnt/all/test_package/test_package.c
recipes/libpopcnt/config.yml

Changes to recipe:  **libpopcnt/3.1**
Fast C/C++ bit population count library.
https://github.com/kimwalisch/libpopcnt
---

libpopcnt: add recipe

---

recipes/yomm2/all/conandata.yml
recipes/yomm2/all/conanfile.py
recipes/yomm2/config.yml

Changes to recipe:  **yomm2/1.6.0**
Updating to the latest version of YOMM2, which I just published.
---

yomm2: add version 1.6.0

---

recipes/ctrl-c/all/conandata.yml
recipes/ctrl-c/config.yml

Changes to recipe:  **ctrl/1.0**
This is the first public release.
https://github.com/evgenykislov/ctrl-c/releases/tag/v1.0.0
---

ctrl-c: add version 1.0.0

---

recipes/fast-cdr/all/conandata.yml
recipes/fast-cdr/config.yml

Changes to recipe:  **fast-cdr/2.2.5**
Minor version update
Minor version update
---

fast-cdr: add version 2.2.5

---

recipes/sdl/all/conandata.yml
recipes/sdl/all/conanfile.py
recipes/sdl/config.yml

Changes to recipe:  **sdl/2.30.9**
This is a bugfix release.
https://github.com/libsdl-org/SDL/compare/release-2.30.8...release-2.30.9
---

sdl: add version 2.30.9

---

recipes/zoe/all/conandata.yml
recipes/zoe/all/conanfile.py
recipes/zoe/all/test_package/CMakeLists.txt
recipes/zoe/all/test_package/test_package.cpp
recipes/zoe/config.yml

Changes to recipe:  **zoe/3.3**
There are several improvements since 3.1.
https://github.com/winsoft666/zoe/compare/v3.1...v3.3
---

zoe: add version 3.3

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/all/conanfile.py
recipes/sentry-native/config.yml

- **[sentry-native] Add version 0.7.12**
- **Remove sentry-native 0.7.8**
---

[sentry-native] Add 0.7.12

---

recipes/c-ares/all/conandata.yml
recipes/c-ares/config.yml

Changes to recipe:  **c-ares/1.34.3**
There are several bugfixes since 1.34.1.
https://github.com/c-ares/c-ares/releases/tag/v1.34.3
https://github.com/c-ares/c-ares/compare/v1.34.1...v1.34.3
---

c-ares: add version 1.34.3

---

recipes/sfl/all/conandata.yml
recipes/sfl/config.yml

Changes to recipe:  **lib/1.8.2**
There are a bugfixe and new feature since 1.8.0.
https://github.com/slavenf/sfl-library/compare/1.8.0...1.8.2
---

sfl: add new version 1.8.2

---

recipes/efsw/all/conandata.yml
recipes/efsw/config.yml

Changes to recipe:  **efsw/1.4.1**
There are several new features in 1.4.1.
https://github.com/SpartanJ/efsw/compare/1.4.0...1.4.1
---

efsw: add version 1.4.1

---

recipes/crossdb/all/conandata.yml
recipes/crossdb/config.yml

Changes to recipe:  **crossdb/0.11.0**
There are several new features in 0.11.0.
https://github.com/crossdb-org/crossdb/releases/tag/0.11.0
https://github.com/crossdb-org/crossdb/compare/0.10.0...0.11.0
---

crossdb: add version 0.11.0

---

recipes/openexr/3.x/conandata.yml
recipes/openexr/config.yml

Changes to recipe:  **openexr/3.3.2**
Contains small fixes and performance improvements.
https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.3.2
Just needed adaptation of the data source, no patching etc.
---

OpenEXR: Add 3.3.2

---

recipes/tree-sitter-cql/all/conanfile.py

Changes to recipe:  **tree-sitter-cql**
See explanation in https://github.com/conan-io/conan-center-index/pull/25940
---

Extend configure logic due to auto_shared_fpic does not work

---

recipes/qoixx/all/conandata.yml
recipes/qoixx/all/conanfile.py
recipes/qoixx/all/test_package/CMakeLists.txt
recipes/qoixx/all/test_package/conanfile.py
recipes/qoixx/all/test_package/test_package.cpp
recipes/qoixx/config.yml

Changes to recipe:  **qoixx/0.1.7**
This is a new library.
https://github.com/wx257osn2/qoixx
---

qoixx: add recipe

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/0.7.3**
New version, I'm the author
---

cpptrace: Bump to 0.7.3

---

recipes/opentrackio-cpp/all/conandata.yml
recipes/opentrackio-cpp/all/conanfile.py
recipes/opentrackio-cpp/all/test_package/CMakeLists.txt
recipes/opentrackio-cpp/all/test_package/conanfile.py
recipes/opentrackio-cpp/all/test_package/test_package.cpp
recipes/opentrackio-cpp/config.yml

First upload of the `opentrackio-cpp` open source library.
To allow for easier consumption of the project for developers.
[OpenTrackIO](https://www.opentrackio.org/) is a new standard developed by SMPTE and this is our open source implementation of a parsing library that can handle processing OpenTrackIO protocol payloads and formatting them into an easy to use abstraction in C++.
---

opentrackio-cpp: Initial upload

---

recipes/cpp-peglib/1.x.x/conandata.yml
recipes/cpp-peglib/config.yml

Changes to recipe:  **cpp-peglib/1.9.1**
There is a bugfix in 1.9.1.
https://github.com/yhirose/cpp-peglib/compare/v1.9.0...v1.9.1
---

cpp-peglib: add version 1.9.1

---

recipes/audiofile/all/conandata.yml
recipes/audiofile/config.yml

Changes to recipe:  **audiofile/1.1.2**
There are several improvements in 1.1.2.
https://github.com/adamstark/AudioFile?tab=readme-ov-file#112---18th-november-2024
https://github.com/adamstark/AudioFile/compare/1.1.1...1.1.2
---

audiofile: add version 1.1.2

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/config.yml

- **[sentry-native] Update to 0.7.15**
- **Remove 0.7.10 version**
---

[sentry-native] Add 0.7.15

---

recipes/fast_float/all/conandata.yml
recipes/fast_float/config.yml

Changes to recipe:  **fmt/7.0.0**
Major version up!
https://github.com/fastfloat/fast_float/releases/tag/v7.0.0
https://github.com/fastfloat/fast_float/compare/v6.1.6...v7.0.0
---

fast_float: add version 7.0.0

---

recipes/reactiveplusplus/all/conandata.yml
recipes/reactiveplusplus/config.yml

Changes to recipe: **reactiveplusplus/2.2.1**
There are several fixes in v2.2.1
https://github.com/victimsnino/ReactivePlusPlus/compare/v2.2.0...v2.2.1
---

Bump ReactivePlusPlus v2.2.1

---

recipes/arrow/all/conandata.yml
recipes/arrow/config.yml

Changes to recipe:  **arrow/18.1.0**
This is a minor release which doesn't contain any critical changes but it does include new APIs.
Arrow keeps a very clean git history so this compare view is a good overview: https://github.com/apache/arrow/compare/apache-arrow-18.0.0...apache-arrow-18.1.0
---

arrow: add version 18.1.0

---

recipes/sqlite3/all/conandata.yml
recipes/sqlite3/config.yml

Changes to recipe:  **sqlite3/3.47.1**
New version is available.
https://www.sqlite.org/releaselog/3_47_1.html
---

sqlite3: add 3.47.1

---

recipes/raylib/all/conandata.yml
recipes/raylib/config.yml

Changes to recipe:  **raylib/5.5**
Updates `raylib` with version 5.5.
- Updates `raylib` with version 5.5
- Release https://github.com/raysan5/raylib/releases/tag/5.5
---

raylib: add version 5.5

---

recipes/libplist/all/conandata.yml
recipes/libplist/all/conanfile.py
recipes/libplist/all/test_package/CMakeLists.txt
recipes/libplist/all/test_package/conanfile.py
recipes/libplist/all/test_package/test_package.c
recipes/libplist/all/test_package/test_package.cpp
recipes/libplist/config.yml

Changes to recipe:  **libplist/[2.6.0]**
Closes https://github.com/conan-io/conan-center-index/issues/582
Only 1 question remains:
The library is a C library which creats C++ bindings by default - For now I've just added the C one, but maybe we want to use C++ instead?

libplist: Add new recipe

---

recipes/xerces-c/all/conandata.yml
recipes/xerces-c/config.yml

Changes to recipe:  **xerces-c/3.3.0**
There are several improvements in 3.3.0.
https://github.com/apache/xerces-c/compare/v3.2.5...v3.3.0
---

xerces-c: add version 3.3.0

---

recipes/cpr/all/conandata.yml
recipes/cpr/config.yml

Changes to recipe:  **cpr/1.11.1**
There are several minor improvements in 1.11.1.
https://github.com/libcpr/cpr/compare/1.11.0...1.11.1
---

cpr: add version 1.11.1

---

recipes/emsdk/all/conandata.yml
recipes/emsdk/config.yml

Changes to recipe:  **emsdk/3.1.72**
---

[emsdk] bump to 3.1.72

---

recipes/libftp/all/conandata.yml
recipes/libftp/all/conanfile.py
recipes/libftp/config.yml

Changes to recipe:  **libftp/1.4.0**
Added support for building a shared library on Windows.
https://github.com/deniskovalchuk/libftp/releases/tag/v1.4.0
https://github.com/deniskovalchuk/libftp/compare/v1.3.0...v1.4.0
---

libftp: add version 1.4.0

---

recipes/gn/all/conanfile.py

:  gn/*
Want to use the recipe!
Syntax error in the function checking minimum cppstd version!
---

gn: Fixed error when checking min cppstd version

---

recipes/libdwarf/all/conandata.yml
recipes/libdwarf/all/patches/0.11.1-0001-fixes.patch
recipes/libdwarf/config.yml

Changes to recipe:  **libdwarf/0.11.1**
Adding newly released version
---

libdwarf: add version 0.11.1

---

recipes/proxy/all/conandata.yml
recipes/proxy/all/conanfile.py
recipes/proxy/config.yml

Changes to recipe:  **proxy/3.1.0**
There are several improvements in 3.1.0.
https://github.com/microsoft/proxy/releases/tag/3.1.0
https://github.com/microsoft/proxy/compare/3.0.0...3.1.0
---

proxy: add version 3.1.0

---

recipes/zserio/all/conandata.yml
recipes/zserio/config.yml

Changes to recipe:  **zserio/2.16.0**
New release
---

zserio: Add new Zserio release 2.16.0

---

recipes/simfil/all/conandata.yml
recipes/simfil/config.yml

Changes to recipe: simfil/0.3.4
Bump simfil to the latest version.
---

 simfil: Bump 0.3.4

---

recipes/simdjson/all/conandata.yml
recipes/simdjson/config.yml

Changes to recipe:  **simdjson/3.11.2**
There are lots of improvements since 3.10.1.
https://github.com/simdjson/simdjson/compare/v3.10.1...v3.11.2
---

simdjson: add version 3.11.2

---

recipes/cnats/all/conandata.yml
recipes/cnats/config.yml

Changes to recipe:  **cnats/3.9.2**
v3.9.2 is released with new features: https://github.com/nats-io/nats.c/releases/tag/v3.9.2
Changelog: https://github.com/nats-io/nats.c/compare/v3.9.1...v3.9.2
---

cnats: add version 3.9.2

---

recipes/cmake/binary/conandata.yml
recipes/cmake/config.yml

Changes to recipe:  **cmake/3.31.1**
Add CMake version 3.31.1.
Support next CMake of the 3.31.x releases.
---

cmake: add version 3.31.3

---

recipes/libpqxx/all/conandata.yml
recipes/libpqxx/config.yml

Changes to recipe:  **libpqxx/7.10.0**
New version releases.
---

libpqxx: add version 7.10.0

---

recipes/libwebp/all/conandata.yml
recipes/libwebp/all/patches/1.5.0-0001-fix-cmake.patch
recipes/libwebp/config.yml

Changes to recipe:  **libwebp/1.5.0**
new upstream version
https://github.com/webmproject/libwebp/compare/v1.4.0...v1.5.0
---

libwebp: add version 1.5.0

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/0.7.4**
I'm the author
---

cpptrace: Bump to 0.7.4

---

recipes/sbepp/all/conandata.yml
recipes/sbepp/config.yml

Changes to recipe:  **sbepp/1.5.1**
Hi, I'm the author, it's a version bump to 1.5.1.
---

sbepp: add version 1.5.1

---

recipes/rotor/all/conandata.yml
recipes/rotor/config.yml

Changes to recipe:  **rotor/v0.32**
I'm library author
---

Add rotor v0.32

---

recipes/cpp-httplib/all/conandata.yml
recipes/cpp-httplib/config.yml

Changes to recipe:  **cpp-httplib/0.18.3**
Bugfix release.
https://github.com/yhirose/cpp-httplib/releases/tag/v0.18.3
https://github.com/yhirose/cpp-httplib/compare/v0.18.2...v0.18.3
---

cpp-httplib: add version 0.18.3

---

recipes/minizip-ng/all/conandata.yml
recipes/minizip-ng/all/conanfile.py
recipes/minizip-ng/config.yml

Changes to recipe:  **minizip-ng/4.0.7**
There is a new feature in 4.0.7.
https://github.com/zlib-ng/minizip-ng/releases/tag/4.0.7
https://github.com/zlib-ng/minizip-ng/compare/4.0.6...4.0.7
---

minizip-ng: add version 4.0.7

---

recipes/ccache/all/conanfile.py
recipes/ccache/all/test_package/conanfile.py

Closes https://github.com/conan-io/conan-center-index/issues/26201
Added version range on `fmt` dependency and removed conan v1 specific code

ccache: Added version range on fmt

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/config.yml

- **[sentry-native] Update to 0.7.16**
- **Remove version 0.7.11**
---

[sentry-native] Add 0.7.16 and 0.7.17

---

recipes/stringzilla/all/conandata.yml
recipes/stringzilla/config.yml

Changes to recipe:  **stringzilla/3.11.3**
There are several improvements since 3.10.3.
https://github.com/ashvardanian/StringZilla/compare/v3.10.3...v3.11.3
---

stringzilla: add version 3.11.3

---

recipes/ccache/all/conanfile.py

Changes to recipe:  **ccache/4.10.2**
---

ccache: bump `zstd` and `hiredis` deps

---

recipes/openjpeg/all/conandata.yml
recipes/openjpeg/config.yml

Changes to recipe:  **openjpeg/all**
Bug fixes from upstream
https://github.com/uclouvain/openjpeg/compare/v2.5.2...v2.5.3
---

openjpeg: add version 2.5.3

---

recipes/libassert/config.yml
recipes/libassert/v2/conandata.yml

Changes to recipe:  **libassert/2.1.4**
I'm the author, new version
---

libassert: Add 2.1.4

---

recipes/zlib-ng/all/conandata.yml
recipes/zlib-ng/config.yml

Changes to recipe:  **zlib-ng/2.2.3**
2.2.3 improves inflate performance.
https://github.com/zlib-ng/zlib-ng/releases/tag/2.2.3
https://github.com/zlib-ng/zlib-ng/compare/2.2.2...2.2.3
---

zlib-ng: add version 2.2.3

---

recipes/libxls/all/conandata.yml
recipes/libxls/config.yml

Changes to recipe:  **libxls/1.6.3**
First update in 4 years.
https://github.com/libxls/libxls/releases/tag/v1.6.3
https://github.com/libxls/libxls/compare/v1.6.2...v1.6.3
---

libxls: add version 1.6.3

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/config.yml

[cppcheck] Add version 2.16.2

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/all/conanfile.py
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/0.7.5**
I'm the author, new version
---

cpptrace: Add 0.7.5

---

recipes/dataframe/all/conandata.yml
recipes/dataframe/all/conanfile.py
recipes/dataframe/config.yml

Changes to recipe:  **DataFrame/3.4.0**
Releasing a new version
**[_Please consider sponsoring DataFrame, especially if you are using it in Production Capacity. It is the strongest form of appreciation_](https://github.com/sponsors/hosseinmoein)**
Improved documentation and code quality
Fixed a bug in assign()
**Implemented get_[data|view]_by_kmeans()**
Changed interface and optimized code in AffinityPropVisitor (backward incompatible change)
Implemented get_[data|view]_by_affin()
Added option to HampelFilterVisitor to populate indices to datapoints affected
Implemented remove_data_by_hampel()
Implemented MeanShiftVisitor visitor
Implemented get_[data|view]_by_dbscan()
Impelmented get_[data|view]_by_mshift()
Improved performance in remove_duplicates()
Added FixedSizeString as one of the …

[dataframe]: Upgrading C++ DataFrame to version 3.4.0

---

recipes/simdjson/all/conandata.yml
recipes/simdjson/all/conanfile.py
recipes/simdjson/config.yml

simdjson: reduce versions concurrently maintained - update version used in fastgltf

simdjson: maintain fewer versions

---

recipes/sol2/all/conandata.yml
recipes/sol2/all/conanfile.py
recipes/sol2/all/patches/0001-Fix-emplace.patch

Integrate upstream fixes on top of latest (2022) release:
https://github.com/ThePhD/sol2/commit/d805d027e0a0a7222e936926139f06e23828ce9f 
https://github.com/ThePhD/sol2/issues/1617
Fix build issues on systems using modern clang-19
Bugfix
---

sol2: Fix a bug building with clang-19

---

recipes/sfl/all/conandata.yml
recipes/sfl/config.yml

Changes to recipe:  **sfl/1.9.0**
There are several improvements in 1.9.0.
https://github.com/slavenf/sfl-library/compare/1.8.2...1.9.0
---

sfl: add version 1.9.0

---

recipes/emsdk/all/conandata.yml
recipes/emsdk/config.yml

Changes to recipe:  **emsdk/3.1.73**
---

emsdk: add version 3.1.73

---

recipes/rocksdb/all/conandata.yml
recipes/rocksdb/config.yml

Changes to recipe:  **rocksdb**
Bug fixes and features
---

rocksdb: Add version 9.9.3

---

recipes/sqlite3/all/conandata.yml
recipes/sqlite3/config.yml

Changes to recipe:  **sqlite3/3.48.0**
New version is available.
Releaselog: https://www.sqlite.org/releaselog/3_48_0.html
---

sqlite3: add 3.48.0

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/4.3.1**
There are several improvements and new features since 4.0.1.
https://github.com/stephenberry/glaze/releases/tag/v4.3.1
https://github.com/stephenberry/glaze/compare/v4.0.1...v4.3.1
---

glaze: add version 4.3.1

---

recipes/z3/all/conanfile.py

Changes to recipe:  **z3/[*]**
See https://github.com/conan-io/conan-center-index/issues/26296#issuecomment-2598558154

z3: use correct check_min_cppstd validation

---

recipes/nifti_clib/all/conanfile.py

Changes to recipe:  **nifti_clib**
The following lines in `nifti_clib` recipe are incorrect. They are directly overriding an internal conan property which is generated by the client:
https://github.com/conan-io/conan-center-index/blob/7da0a3dba6d4aa56dabfcaef15e19e5cf13305d4/recipes/nifti_clib/all/conanfile.py#L105-L107
Also, renamed CMake library names to conan defined ones.
In a future client update, we will add a mechanism to detect private API usages avoiding similar issues.
Closes https://github.com/conan-io/conan-center-index/issues/26455

nifti_clib: Fix private usage of required_components

---

recipes/fmt/all/conandata.yml
recipes/fmt/config.yml

Changes to recipe:  **fmt/11.1.3**
---

fmt: add v11.1.3

---

recipes/openssl/3.x.x/conandata.yml
recipes/openssl/config.yml

Changes to recipe:  **openssl/3.4.0**
---

openssl: add version `3.4.0`

---

recipes/doxygen/all/conandata.yml
recipes/doxygen/config.yml

Changes to recipe:  **doxygen/1.13.2**
Update to the latest version with new features and bugfixes
Simple update
---

doxygen updated to 1.13.2

---

recipes/proxy/all/conandata.yml
recipes/proxy/config.yml

Changes to recipe:  **proxy/3.2.0**
update
---

Update proxy to version 3.2.0

---

recipes/taskflow/all/conandata.yml
recipes/taskflow/config.yml

Changes to recipe:  **taskflow/3.9.0**
There are several features in 3.9.0.
https://taskflow.github.io/taskflow/release-3-9-0.html
https://github.com/taskflow/taskflow/compare/v3.8.0...v3.9.0
---

taskflow: add version 3.9.0

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/config.yml

cppcheck update to 2.17

---

recipes/whisper-cpp/all/conandata.yml
recipes/whisper-cpp/all/conanfile.py
recipes/whisper-cpp/config.yml

[whisper-cpp] Add version 1.7.4

---

recipes/sail/all/conandata.yml
recipes/sail/config.yml

Changes to recipe:  **sail/0.9.8**
Upstream update.
---

sail: Bump version to 0.9.8

---

recipes/argparse/all/conandata.yml
recipes/argparse/config.yml

Add argparse/3.2
Close: https://github.com/conan-io/conan-center-index/issues/26689
https://github.com/p-ranav/argparse/compare/v3.1...v3.2

argparse new 3.2 version

---

recipes/libxml2/all/conandata.yml
recipes/libxml2/config.yml

Add libxml2/2.13.6
Close: https://github.com/conan-io/conan-center-index/issues/26680
https://gitlab.gnome.org/GNOME/libxml2/-/compare/v2.13.6..v2.13.4?from_project_id=1665

new version `libxml2/2.13.6`

---

recipes/rotor/all/conandata.yml
recipes/rotor/all/conanfile.py
recipes/rotor/config.yml

Changes to recipe:  **rotor/v0.33**
I'm library author

rotor: add version v0.33

---

recipes/swig/all/conandata.yml
recipes/swig/all/patches/0001-4.3.0-swig-linux-library-path.patch
recipes/swig/all/patches/0002-4.3.0-do-not-define-SWIG_LIB_WIN_UNIX.patch
recipes/swig/config.yml

Changes to recipe:  **swig/4.3.0**
update to the new version of the tool
just straight update of version
---

swig: added version 4.3.0

---

recipes/jsoncons/all/conandata.yml
recipes/jsoncons/all/conanfile.py
recipes/jsoncons/config.yml

Changes to recipe:  **jsoncons/1.1.0**
There are several bug fixes in 1.1.0.
https://github.com/danielaparker/jsoncons/releases/tag/v1.1.0
https://github.com/danielaparker/jsoncons/compare/v1.0.0...v1.1.0
---

jsoncons: add version 1.2.0

---

recipes/boost/all/conandata.yml
recipes/boost/all/dependencies/dependencies-1.87.0.yml
recipes/boost/all/patches/1.87.0-boost-fiber-fix-property-numa.patch
recipes/boost/config.yml

Changes to recipe:  **boost/1.87.0**
close #26539
close #26709
---

boost: add version `1.87.0`

---

recipes/json-c/all/conanfile.py

json-c/*
Support for building for qnx
---

json-c: Added support  for qnx

---

recipes/sqlite3/all/conandata.yml
recipes/sqlite3/config.yml

Changes to recipe:  **sqlite3/3.49.1**
New version is available
https://sqlite.org/releaselog/3_49_1.html
https://github.com/sqlite/sqlite/compare/version-3.48.0...version-3.49.1
---

sqlite3: add 3.49.1

---

recipes/mimalloc/all/conandata.yml
recipes/mimalloc/all/conanfile.py
recipes/mimalloc/all/patches/2.1.9-0002-support-older-compiler.patch
recipes/mimalloc/config.yml

- support windows arm64
- add `guard` option
https://github.com/microsoft/mimalloc/blob/v2.1.9/readme.md#releases
https://github.com/microsoft/mimalloc/compare/v2.1.7...v2.1.9
---

mimalloc: add version 2.1.9

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/config.yml

[cppcheck] Add version 2.17.1

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/all/conanfile.py
recipes/sentry-native/config.yml

Changes to recipe: **sentry-native/0.7.20**
---

[sentry-native] Update to 0.7.20

---

recipes/toml11/all/conandata.yml
recipes/toml11/config.yml

Changes to recipe:  **toml11/4.4.0**
There are new features and performance improvements since 4.2.0.
https://github.com/ToruNiina/toml11/releases/tag/v4.4.0
---

toml11: add version 4.4.0

---

recipes/simdutf/all/conandata.yml
recipes/simdutf/config.yml

Changes to recipe:  **simdutf/6.2.0**
https://github.com/simdutf/simdutf/compare/v5.6.3...v6.2.0
---

simdutf: add version 6.2.0

---

recipes/fast_float/all/conandata.yml
recipes/fast_float/config.yml

Changes to recipe:  **fast_float/8.0.0**
https://github.com/fastfloat/fast_float/compare/v7.0.0...v8.0.0
---

fast_float: add version 8.0.0

---

recipes/rapidyaml/all/conandata.yml
recipes/rapidyaml/all/patches/0.8.0-001-remove-internal-c4core.patch
recipes/rapidyaml/config.yml

Changes to recipe:  **rapidyaml/0.8.0**
There are several breaking changes include supporting edge case yaml format.
https://github.com/biojppm/rapidyaml/releases/tag/v0.8.0
---

rapidyaml: add version 0.8.0

---

recipes/fmt/all/conandata.yml
recipes/fmt/config.yml

Changes to recipe:  **fmt/11.1.4**
Code improvements
https://github.com/fmtlib/fmt/compare/11.1.3...11.1.4
https://github.com/fmtlib/fmt/releases/tag/11.1.4
---

fmt: add 11.1.4

---

recipes/zlib-ng/all/conandata.yml
recipes/zlib-ng/config.yml

Changes to recipe:  **zlib-ng/2.2.4**
2.2.4 fixes several bugs
https://github.com/zlib-ng/zlib-ng/releases/tag/2.2.4
https://github.com/zlib-ng/zlib-ng/compare/2.2.3...2.2.4
---

zlib-ng: add 2.2.4

---

recipes/jom/all/conandata.yml

Changes to recipe:  **jom/\***
PR adds mirrors for jom (the same that qt package have) and for its license.
---

jom: add mirrors

---

recipes/cnats/all/conandata.yml
recipes/cnats/config.yml

Changes to recipe:  **cnats/3.9.3**
v3.9.3 is released with bug fixes: https://github.com/nats-io/nats.c/releases/tag/v3.9.3
Changelog: https://github.com/nats-io/nats.c/compare/v3.9.2...v3.9.3
---

cnats: add version 3.9.3

---

recipes/symengine/all/conandata.yml
recipes/symengine/all/conanfile.py
recipes/symengine/config.yml

Changes to recipe:  **symengine/0.14.0**
Also update versions of `boost` and `fast_float` dependencies.
---

[symengine] Add version 0.14.0

---

recipes/sobjectizer/all/conandata.yml
recipes/sobjectizer/config.yml

Changes to recipe:  **sobjectizer/5.8.4**
---

Update SObjectizer version to v5.8.4

---

recipes/sdl/all/conandata.yml
recipes/sdl/config.yml

Changes to recipe:  **sdl/2.32.2**
Versions past 2.30.9 have multiple crash/bug fixes
Adds the latest available version
---

package/sdl: add v2.32.2

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/5.0.0**
`Customizable Compile-Time Options` is added.
https://github.com/stephenberry/glaze/releases/tag/v5.0.0
https://github.com/stephenberry/glaze/compare/v4.4.3...v5.0.0
---

glaze: add version 5.0.0

---

recipes/cli11/all/conandata.yml
recipes/cli11/config.yml

Changes to recipe:  **cli11/2.5.0**
Lots of new features are added.
https://github.com/CLIUtils/CLI11/releases/tag/v2.5.0
https://github.com/CLIUtils/CLI11/compare/v2.4.2...v2.5.0
---

cli11: add version 2.5.0

---

recipes/ydcpp-tcpcat/all/conandata.yml
recipes/ydcpp-tcpcat/config.yml

Changes to recipe:  **ydcpp-tcpcat/1.0.5**
new release of the library
new release of the library
---

tpcat: add version 1.0.5

---

recipes/depot_tools/all/conandata.yml
recipes/depot_tools/all/test_package/conanfile.py
recipes/depot_tools/config.yml

depot_tools:cci.20241206
Want to use newest depot_tools
---

depot_tools: Added latest revision

---

recipes/c-blosc2/all/conandata.yml
recipes/c-blosc2/all/conanfile.py
recipes/c-blosc2/all/patches/2.17.0-0001-fix-cmake.patch
recipes/c-blosc2/config.yml

Changes to recipe:  **c-blosc2/2.17.0**
There are several new features since 2.15.0.
https://github.com/Blosc/c-blosc2/compare/v2.15.0...v2.17.0
---

c-blosc2: add version 2.17.0

---

recipes/sparrow/all/conandata.yml
recipes/sparrow/all/conanfile.py
recipes/sparrow/all/test_package/CMakeLists.txt
recipes/sparrow/all/test_package/conanfile.py
recipes/sparrow/all/test_package/main.cpp
recipes/sparrow/config.yml

Changes to recipe:  **sparrow/0.5.0**
Add the recipe for the [sparrow](https://github.com/man-group/sparrow) library.
It add a new recipe for the version 0.5.0
---

sparrow: add new recipe

---

recipes/ccache/all/conandata.yml
recipes/ccache/config.yml

Changes to recipe:  **ccache/4.11**
Add latest version of ccache.
Add latest version of ccache.
---

ccache: add version 4.11

---

recipes/icecream-cpp/all/conandata.yml
recipes/icecream-cpp/config.yml

Changes to recipe:  **icecream-cpp/1.0.0**
The new version was just released
Only adde the paths to the new version
---

icecream-cpp: add version 1.0.0

---

recipes/openssl/3.x.x/conanfile.py

Changes to recipe:  **openssl/3.4.1**
Closes #26847
Remove unnecessarily disabled options
---

openssl: enable stdio, threads, etc. for Emscripten

---

recipes/openapi-generator/all/conandata.yml
recipes/openapi-generator/config.yml

Changes to recipe:  **openapi-generator/7.12.0**
New version of the tool with many bugfixes and improvements is available
Just adding the latest version
---

add version 7.12.0

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/all/conanfile.py
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/0.8.2**
There are several new features in 0.8.0.
https://github.com/jeremy-rifkin/cpptrace/compare/v0.7.5...v0.8.2
---

cpptrace: add version 0.8.2

---

recipes/cppitertools/all/conandata.yml
recipes/cppitertools/all/conanfile.py
recipes/cppitertools/config.yml

Changes to recipe:  **cppitertools/2.2**
First release in 4 years.
https://github.com/ryanhaining/cppitertools/releases/tag/v2.2
https://github.com/ryanhaining/cppitertools/compare/v2.1...v2.2
---

cppitertools: add version 2.2

---

recipes/imgui-sfml/all/conanfile.py

Let the consumers define it
Closes https://github.com/conan-io/conan-center-index/issues/26888

imgui-sfml: Remove bad define

---

recipes/orc/all/conandata.yml
recipes/orc/all/conanfile.py
recipes/orc/config.yml

Changes to recipe:  **orc/2.1.1**
Add the latest version of Apache ORC
See https://orc.apache.org/news/2025/03/06/ORC-2.1.1/
---

add orc/2.1.1

---

recipes/vulkan-loader/all/conandata.yml
recipes/vulkan-loader/config.yml

Changes to recipe:  **vulkan-loader/1.4.309**
https://github.com/KhronosGroup/Vulkan-Loader/compare/vulkan-sdk-1.3.290.0...v1.4.309

new version vulkan loader 1.4.309

---

recipes/argtable3/all/conanfile.py

argtable3: fixes to support CMake 4
Upstream [CMakeLists.txt](https://github.com/argtable/argtable3/blob/master/CMakeLists.txt#L31) is already in 3.5 so as soon as new version is released, the cmake 4 specific injection should be updated

argtable3: CMake 4 support

---

recipes/highfive/all/conanfile.py
recipes/highfive/all/test_package/CMakeLists.txt

Changes to recipe:  **highfive/all**
The main motivation is addressing version conflicts when building hictk with `with_arrow=True` (see https://github.com/conan-io/conan-center-index/pull/26078).
---

highfive: bump boost to v1.85.0

---

recipes/libnfs/all/conandata.yml
recipes/libnfs/all/conanfile.py
recipes/libnfs/all/patches/6.0.2-0001-fix-dllname.patch
recipes/libnfs/all/test_package/test_package.c
recipes/libnfs/config.yml

Changes to recipe:  **libnfs/6.0.2**
There are several improvements since 5.0.3.
https://github.com/sahlberg/libnfs/compare/libnfs-5.0.3...libnfs-6.0.2
---

libnfs: add version 6.0.2

---

recipes/czmq/all/conanfile.py

czmq: fixes to support CMake 4

czmq: CMake 4 support

---

recipes/gflags/all/conanfile.py

gflags: fixes to support CMake 4

gflags: CMake 4 support

---

recipes/openssl/3.x.x/conanfile.py

Changes to recipe:  **openssl/3.x.x**
This PR was created pursuant to the resolution of #18011, which is reproducible in an application developed by my organization. Essentially, the official Conan recipe for OpenSSL could result in a misconfiguration where the library attempts to load a static library (`zdll.lib`) as a DLL.
In #18011, it was demonstrated that the official Conan recipe for OpenSSL could result in a build misconfiguration, leading to a "Bad Image" message box appearing at runtime. This was ultimately the result of attempting to load a static library as a DLL. I confirmed this by placing a breakpoint on the following Win32 APIs:
* `LoadLibraryA()`
* `LoadLibraryW()`
These are the standard Win32 APIs for injecting a DLL into the address space of the current process at …

Fixed an issue where the wrong ZLIB library could be specified during OpenSSL configuration.

---

recipes/hictk/all/conandata.yml
recipes/hictk/all/conanfile.py
recipes/hictk/all/test_package/CMakeLists.txt
recipes/hictk/all/test_package/test_package.cpp
recipes/hictk/config.yml

Changes to recipe:  **hictk/all**
Supersedes https://github.com/conan-io/conan-center-index/pull/26078.
https://github.com/paulsengroup/hictk/compare/v1.0.0...v2.0.2
---

hictk: add v2.0.2 and bump deps

---

recipes/libuvc/all/conanfile.py

libuvc: fixes to support CMake 4

libuvc: CMake 4 support

---

recipes/libzen/all/conanfile.py

libzen: fixes to support CMake 4

libzen: CMake 4 support

---

recipes/sentry-native/all/conandata.yml
recipes/sentry-native/config.yml

[sentry-native] Update to 0.8.3

---

recipes/streamvbyte/all/conandata.yml
recipes/streamvbyte/config.yml

Changes to recipe:  **streamvbyte/2.0.0**
Major version up with several new functions.
https://github.com/fast-pack/streamvbyte/compare/v1.0.0...v2.0.0
---

streamvbyte: add version 2.0.0

---

recipes/tinyxml2/all/conandata.yml
recipes/tinyxml2/config.yml

There are API changes.
https://github.com/leethomason/tinyxml2/releases/tag/11.0.0
https://github.com/leethomason/tinyxml2/compare/10.0.0...11.0.0
---

tinyxml2: add version 11.0.0

---

recipes/systemc/all/conandata.yml
recipes/systemc/all/conanfile.py
recipes/systemc/config.yml

Changes to recipe:  **systemc/3.0.1**
https://github.com/accellera-official/systemc/compare/2.3.3...3.0.1
We need to disable the sanitizer on macOS:
https://github.com/accellera-official/systemc/blob/3.0.1/src/CMakeLists.txt#L95
Windows with shared=True needs `SC_WIN_DLL`:
https://github.com/accellera-official/systemc/blob/main/INSTALL.md#33-building-against-a-systemc-dll
Close: https://github.com/conan-io/conan-center-index/issues/26906

Add: new version systemc/3.0.1

---

recipes/octomap/all/conanfile.py

octomap: fixes to support CMake 4

octomap: CMake 4 support

---

recipes/ogg/all/conanfile.py

ogg: fixes to support CMake 4
* Added `package_type = "library"`. This recipe only generates a library (no apps and toolchains)

ogg: CMake 4 support

---

recipes/expat/all/conandata.yml
recipes/expat/config.yml

Changes to recipe:  **expat/***
New version is available with bug fixes
https://github.com/libexpat/libexpat/compare/R_2_7_0...R_2_7_1
https://github.com/libexpat/libexpat/blob/R_2_7_1/expat/Changes#L40
---

expat: add version 2.7.1

---

recipes/zlib/all/conanfile.py
recipes/zlib/all/patches/1.2.13/0001-Fix-cmake.patch
recipes/zlib/all/patches/1.2.x/0001-fix-cmake.patch

Newer versions are already working

zlib 1.2.x: fix cmake 4 compatibility

---

recipes/rotor/all/conandata.yml
recipes/rotor/all/conanfile.py
recipes/rotor/config.yml

Changes to recipe:  **lib/rotor**
I'm library author
---

rotor v0.34 version bump

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/5.0.2**
There are several improvements since 5.0.0.
https://github.com/stephenberry/glaze/releases/tag/v5.0.2
---

glaze: add version 5.0.2

---

recipes/redis-plus-plus/all/conanfile.py

redis-plus-plus: fixes to support CMake 4

redis-plus-plus: CMake 4 support

---

recipes/cpputest/all/conanfile.py

cpputest: fixes to support CMake 4
* Removed legacy generator code
Upstream master branch already supports CMake 4: https://github.com/cpputest/cpputest/blob/master/CMakeLists.txt#L4
Version not yet released

cpputest: CMake 4 support

---

recipes/spirv-tools/all/conanfile.py

spirv-tools: fixes to support CMake 4
* Removed legacy generator conan v1

spirv-tools: CMake 4 support

---

recipes/zeromq/all/conanfile.py

zeromq: fixes to support CMake 4

zeromq: CMake 4 support

---

recipes/wslay/all/conanfile.py

wslay: fixes to support CMake 4

wslay: CMake 4 support

---

recipes/winflexbison/all/conanfile.py

winflexbison: fixes to support CMake 4

winflexbison: CMake 4 support

---

recipes/tlx/all/conanfile.py

tlx: fixes to support CMake 4
Upstream `master` branch already supports CMake 4: https://github.com/tlx/tlx/blob/master/CMakeLists.txt#L11
A new version with those changes has not been released yet.

tlx: CMake 4 support

---

recipes/szip/all/conanfile.py

szip: fixes to support CMake 4
* Removed legacy generator conan v1 code
* Added missing `package_type = "library"`. This recipe only packages a library and no binary

szip: CMake 4 support

---

recipes/pugixml/all/conandata.yml
recipes/pugixml/config.yml

pugixml: add version 1.15

---

recipes/open-dis-cpp/all/conandata.yml
recipes/open-dis-cpp/all/conanfile.py
recipes/open-dis-cpp/config.yml

Changes to recipe:  **open-dis-cpp/1.1.0**
Update recipe to include the latest 1.1.0 library release.
---

open-dis-cpp: add version 1.1.0

---

recipes/libdrm/all/conandata.yml
recipes/libdrm/all/conanfile.py
recipes/libdrm/config.yml

Changes to recipe:  **libdrm/2.4.124**
New version required for wlroots
* Add version 2.4.124
* Allow version ranges for build deps
---

Libdrm bump version

---

recipes/dataframe/all/conandata.yml
recipes/dataframe/config.yml

Changes to recipe:  **dataframe/[3.5.0]**
**[_Please consider sponsoring DataFrame, especially if you are using it in Production Capacity. It is the strongest form of appreciation_](https://github.com/sponsors/hosseinmoein)**
Enhanced documentation
Implementing SpectralClusteringVisitor visitor
Enhanced ThreadPool parallel_loop()
Implemented get_[data|view]_by_spectral()
Implemented determinant() + a bunch of other stuff in Matrix
Implemented canon_corr()
Implemented MC_station_dist()
**Implemented SeasonalPeriodVisitor visitor**
**Improved performance in reading files of different types**
Changed read() signature to take a struct for its parameters -- _backward incompatible change_
Changed write() signature to take a struct for its parameters -- _backward incompatible change_ …

dataframe: Upgrading C++ DataFrame to version 3.5.0

---

recipes/sml/all/conandata.yml
recipes/sml/config.yml

Changes to recipe:  **sml/1.1.12**
This is a bugfix release.
---

sml: add version 1.1.12

---

recipes/zstd/all/conanfile.py

zstd: fixes to support CMake 4

zstd: CMake 4 support

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/0.8.3**
New version, I'm the author
---

cpptrace: add 0.8.3

---

recipes/libpqxx/all/conandata.yml
recipes/libpqxx/all/patches/remove-get-target-property-to-get-postgresql_include_dirs.patch
recipes/libpqxx/config.yml

Changes to recipe:  **libpqxx/7.10.1**
Big fix release: https://github.com/jtv/libpqxx/releases/tag/7.10.1
---

libpqxx: add version 7.10.1

---

recipes/highs/all/conandata.yml
recipes/highs/config.yml

Changes to recipe:  **highs/1.9.0** **highs/1.10.0**
Add new releases of highs
Just the version bump 
---

highs add new versions

---

recipes/simdjson/all/conandata.yml
recipes/simdjson/config.yml

Changes to recipe:  **simdjson/3.12.3**
New version is available
https://github.com/simdjson/simdjson/compare/v3.12.2...v3.12.3
---

simdjson: add version 3.12.3

---

recipes/librealsense/all/conandata.yml
recipes/librealsense/all/conanfile.py
recipes/librealsense/all/patches/2.49.0-0005-fix-os-flags-arm64.patch
recipes/librealsense/all/patches/2.53.1-0004-fix-os-flags-arm64.patch
recipes/librealsense/all/test_package/test_package.cpp

librealsense: fixes to support CMake 4

librealsense: CMake 4 support

---

recipes/flac/all/conandata.yml
recipes/flac/all/conanfile.py
recipes/flac/config.yml

Changes to recipe:  **flac/1.5.0**
This adds the latest version 1.5.0 for library flac.
---

flac: add version 1.5.0

---

recipes/srt/all/conandata.yml
recipes/srt/all/conanfile.py
recipes/srt/config.yml

Changes to recipe:  **srt/1.5.4**
Add new version 1.5.4
---

srt: add version 1.5.4 and CMake 4 support

---

recipes/plutovg/all/conandata.yml
recipes/plutovg/config.yml

Changes to recipe:  **plutovg/1.0.0**
First major version up.
https://github.com/sammycage/plutovg/releases/tag/v1.0.0
https://github.com/sammycage/plutovg/compare/v0.0.8...v1.0.0
---

plutovg: add version 1.0.0

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Changes to recipe:  **quill/9.0.2**
major version up.
https://github.com/odygrd/quill/releases/tag/v9.0.2
---

quill: add version 9.0.2

---

recipes/ftxui/all/conandata.yml
recipes/ftxui/all/patches/6.0.2-0001-disable-pic.patch
recipes/ftxui/config.yml

Changes to recipe:  **ftxui/6.0.2**
There are several new features since 5.0.0.
https://github.com/ArthurSonzogni/FTXUI/compare/v5.0.0...v6.0.2
---

ftxui: add version 6.0.2

---

recipes/libcoro/all/conandata.yml
recipes/libcoro/config.yml

Changes to recipe:  **libcoro/0.14.1**
This updates the recipe for libcoro to the latest version 0.14.1.
---

libcoro: add version 0.14.1

---

recipes/rocksdb/all/conandata.yml
recipes/rocksdb/config.yml

Changes to recipe:  **rocksdb/10.0.1**
https://github.com/facebook/rocksdb/compare/v9.10.0...v10.0.1
https://github.com/facebook/rocksdb/blob/v10.0.1/HISTORY.md
---

rocksdb: add version 10.0.1

---

recipes/bitmagic/all/conandata.yml
recipes/bitmagic/config.yml

Changes to recipe:  **bitmagic/8.0.1**
https://github.com/tlk00/BitMagic/compare/v7.13.4...v8.0.1
---

bitmagic: add version 8.0.1

---

recipes/nss/all/conanfile.py
recipes/nss/all/test_package/CMakeLists.txt
recipes/nss/all/test_package/conanfile.py

Make NSS Package recipe be usable with Conan 2.x
Changes to recipe:  **nss/3.93**
Fix the issues for not being compatible with conan 2.x.
Closes https://github.com/conan-io/conan-center-index/issues/22878
The changes are necessary to create the package on both conan 1 and 2.
Internal changes only to meet the conan 2.x rules
---

fix: nss package for conan 2.x

---

recipes/nlohmann_json/all/conandata.yml
recipes/nlohmann_json/config.yml

Changes to recipe:  **nlohmann-json/3.12.0**
There are several new features since 3.11.x.
https://github.com/nlohmann/json/releases/tag/v3.12.0
---

nlohmann-json: add version 3.12.0

---

recipes/manifold/all/conandata.yml
recipes/manifold/all/conanfile.py
recipes/manifold/all/test_package/CMakeLists.txt
recipes/manifold/all/test_package/conanfile.py
recipes/manifold/all/test_package/test_package.cpp
recipes/manifold/config.yml

Recipe to add:  **manifold/3.0.1**
To have a new geometry topological library more optimized than OpenCascade.
---

Add new recipe for manifold

---

recipes/fmt/all/conandata.yml
recipes/fmt/config.yml

Changes to recipe:  **fmt/11.2.0**
Add the latest version 11.2.0.
https://github.com/fmtlib/fmt/releases/tag/11.2.0
---

fmt: Add v11.2.0.

---

recipes/meshoptimizer/all/conandata.yml
recipes/meshoptimizer/config.yml

Changes to recipe:  **meshoptimizer/0.23**
Version bump
https://github.com/zeux/meshoptimizer/compare/v0.22...v0.23
config.yml and conandata.yml point to the newly created meshoptimizer/0.23.
---

Add meshoptimizer/0.23

---

recipes/nudb/all/conandata.yml
recipes/nudb/config.yml

nudb: add 2.0.9

---

recipes/strawberryperl/all/conandata.yml
recipes/strawberryperl/config.yml

Version bump for strawberryperl
---

strawberryperl 5.38.2.2 and 5.40.0.1

---

recipes/openjph/all/conandata.yml
recipes/openjph/all/conanfile.py
recipes/openjph/all/patches/0.21.2_cmake-cxx-standard.patch
recipes/openjph/config.yml

Changes to recipe:  **openjph/0.21.2**
Quite a number of new features but also bugfixes and general improvements.
https://github.com/aous72/OpenJPH/releases/tag/0.21.2
---

OpenJPH: Add version 0.21.2

---

recipes/sdl/3.x/conanfile.py

After checking with the team, we're moving to version ranges for libalsa allowing different patch versions - please do not open further PRs to other recipes to update this dependency there unless you are facing a version conflict (do report that, thanks!), we'll do it progressively.
Closes https://github.com/conan-io/conan-center-index/issues/27366

sdl3: Add version range for libalsa

---

recipes/graaf/all/conandata.yml
recipes/graaf/all/conanfile.py
recipes/graaf/all/test_package/CMakeLists.txt
recipes/graaf/all/test_package/conanfile.py
recipes/graaf/all/test_package/test_package.cpp
recipes/graaf/config.yml

Changes to recipe:  **Graaf/1.1.1**
Add [Graaf library](https://github.com/bobluppes/graaf).
Graaf is designed with the goal of simplifying graph-related tasks. It offers a lightweight alternative to the [Boost Graph Library (BGL)](https://www.boost.org/doc/libs/1_82_0/libs/graph/doc/index.html) and is built for simplicity and extensibility. With Graaf, you can easily create, manipulate, and analyze graphs, making it suitable for a wide range of applications.
This is my first time contributing a new recipe, so please review with extra care. I have tested locally on Linux with gcc 14.
Minimum versions for Windows and Mac are guesses.
---

Add Graaf header-only library

---

recipes/icu/all/conandata.yml
recipes/icu/config.yml

Changes to recipe:  **icu/77.1**
https://github.com/unicode-org/icu/releases/tag/release-77-1
---

icu: add version 77.1

---

recipes/sdl/3.x/conandata.yml
recipes/sdl/3.x/conanfile.py
recipes/sdl/config.yml

Changes to recipe:  **SDL/[3.2.14]**
Add the new version
recipes/sdl/3.x/conandata.yml (the version)
recipes/sdl/config.yml (the version)
---
conan create . --build=missing --version=3.2.14
This change can require [https://github.com/conan-io/conan-center-index/pull/27458](https://github.com/conan-io/conan-center-index/pull/27458) libsndfile (support CMake 4)

sdl: version 3.2.14

---

recipes/nlopt/all/conandata.yml
recipes/nlopt/config.yml

Changes to recipe:  **nlopt/2.10.0**
Follow library versions
Only added tag version
---

nlopt: add versions 2.10

---

recipes/sbepp/all/conandata.yml
recipes/sbepp/config.yml

Changes to recipe:  **sbepp/1.6.0**
I'm the author, adding new version.
---

sbepp: add version 1.6.0

---

recipes/cxxopts/all/conandata.yml
recipes/cxxopts/config.yml

Changes to recipe:  **cxxopts/3.3.1**
Add the latest release.
- Release: https://github.com/jarro2783/cxxopts/releases/tag/v3.3.1
- Changelog: https://github.com/jarro2783/cxxopts/blob/master/CHANGELOG.md#330
---

cxxopts: Add the latest version 3.3.1.

---

recipes/plutosvg/all/conandata.yml
recipes/plutosvg/all/conanfile.py
recipes/plutosvg/all/test_package/conanfile.py
recipes/plutosvg/all/test_package/meson.build
recipes/plutosvg/all/test_package/test_package.c
recipes/plutosvg/config.yml
recipes/plutovg/all/conanfile.py

Necessary for sdl_ttf v3, split from https://github.com/conan-io/conan-center-index/pull/27166
`plutovg`: fix include directory expected by consumers

Plutosvg: Add new recipe

---

recipes/spirv-headers/all/conandata.yml
recipes/spirv-headers/config.yml

Changes to recipe:  **spirv-headers/[1.4.313.0]**
Add the new version
recipes/spirv-headers/all/conandata.yml (the new version)
recipes/spirv-headers/config.yml (the new version)
---
conan create . --version=1.4.313.0

spirv-headers: version 1.4.313.0

---

recipes/rapidyaml/all/conandata.yml
recipes/rapidyaml/all/patches/0.9.0-001-remove-internal-c4core.patch
recipes/rapidyaml/config.yml

Changes to recipe:  **rapidyaml/0.9.0**
There are several improvements since 0.8.0.
https://github.com/biojppm/rapidyaml/releases/tag/v0.9.0
---

rapidyaml: add version 0.9.0

---

recipes/cpp-httplib/all/conandata.yml
recipes/cpp-httplib/all/conanfile.py
recipes/cpp-httplib/config.yml

Changes to recipe:  **cpp-httplib/0.20.0**
- popular library
- there are several bugfixes and new features in 0.20.0.
https://github.com/yhirose/cpp-httplib/releases/tag/v0.20.0
---

cpp-httplib: add version 0.20.1

---

recipes/rapidhash/all/conandata.yml
recipes/rapidhash/all/conanfile.py
recipes/rapidhash/config.yml

Changes to recipe:  **rapidhash/2.2**
https://github.com/Nicoshev/rapidhash/releases/tag/rapidhash_v2.2
---

rapidhash: add version 3.0

---

recipes/proj/all/conandata.yml
recipes/proj/all/conanfile.py
recipes/proj/config.yml

Changes to recipe:  **proj/9.6.0**
Fixes: https://github.com/conan-io/conan-center-index/issues/26998
Upgrade proj version to latest
Updated 9.5.x recipe from 9.5.0 to 9.5.1 and added 9.6.0 version
---

proj: add version 9.6.0

---

recipes/date/all/conandata.yml
recipes/date/config.yml

Changes to recipe:  **date/3.0.4**
---

date: add version `3.0.4`

---

recipes/trantor/all/conandata.yml
recipes/trantor/config.yml

Changes to recipe:  **trantor/[1.5.23]**
This PR contains only the new version.
recipes/trantor/all/conandata.yml (only the version)
recipes/trantor/config.yml (only the version)
---
Tested locally:
conan source . --version=1.5.23
conan install . --build=missing --version=1.5.23
conan build . --version=1.5.23
conan export-pkg . --version=1.5.23
conan create . --version=1.5.23
[https://github.com/an-tao/trantor/compare/v1.5.21...v1.5.23](https://github.com/an-tao/trantor/compare/v1.5.21...v1.5.23)

trantor: add version 1.5.23

---

recipes/ada/all/conandata.yml
recipes/ada/all/conanfile.py
recipes/ada/config.yml

Changes to recipe:  **ada/3.2.1**
https://github.com/ada-url/ada/compare/v2.9.2...v3.2.1
https://www.yagiz.co/release-of-ada-v3/
---

ada: add version 3.2.1

---

recipes/cpu_features/all/conandata.yml
recipes/cpu_features/config.yml

Changes to recipe:  **cpu_features/0.10.1**
These releases add cross-platform support and update dependencies
https://github.com/google/cpu_features/releases/tag/v0.10.1
https://github.com/google/cpu_features/releases/tag/v0.10.0
---

cpu_features: add version 0.10.1

---

recipes/foxglove-schemas-protobuf/all/conandata.yml
recipes/foxglove-schemas-protobuf/all/conanfile.py
recipes/foxglove-schemas-protobuf/config.yml

Continued from https://github.com/conan-io/conan-center-index/pull/27542

foxglove-schemas-protobuf: add version 0.7.1

---

recipes/ktx/all/conanfile.py
recipes/ktx/all/patches/4.3.2/0004-unvendor-dependencies.patch
recipes/ktx/all/test_package/test_package.c

See reasoning and discussion in https://github.com/conan-io/conan-center-index/issues/27428

ktx: Unvendorize fmt

---

recipes/gnu-config/all/conanfile.py

Changes to recipe:  **gnu-config/***
The settings were not correctly defined for this package. This PR fixes it.
---

gnu-config: fix settings

---

recipes/resultlib/all/conandata.yml
recipes/resultlib/all/conanfile.py
recipes/resultlib/all/test_package/CMakeLists.txt
recipes/resultlib/all/test_package/conanfile.py
recipes/resultlib/all/test_package/test_package.c
recipes/resultlib/config.yml

Add new recipe:  **resultlib/1.0.0**
Close: #27005
https://result.guillermo.dev/
---

resultlib: new recipe

---

recipes/highs/all/conandata.yml
recipes/highs/all/conanfile.py
recipes/highs/config.yml

Changes to recipe:  **highs/1.11.0**
Add new version of HiGHS 
Version bump and an update of the source directory name in HiGHS 
---
- [ X] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ X] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ X] Tested locally with at least one configuration using a recent version of Conan

Update highs to 1.11.0

---

.gitattributes

Closes: https://github.com/conan-io/conan-center-index/issues/27494

Adding *.in files in .gitattributes

---

recipes/opentelemetry-cpp/all/conandata.yml
recipes/opentelemetry-cpp/all/conanfile.py
recipes/opentelemetry-cpp/config.yml

Changes to recipe:  **opentelemetry-cpp/1.21**
Add OpenTelemetry 1.21
* Add release from: https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.21.0
* Wider abseil range `[>=20240116.1 <=20250127.0]` (avoid missing dependencies with protobuf)
---

opentelemetry-cpp: 1.21

---

recipes/cmake/binary/conandata.yml
recipes/cmake/config.yml

Changes to recipe:  **cmake/4.0.3**
Have the latest CMake version of the 4.x branch.
Have the latest CMake version of the 4.x branch.
---

CMake: update to version 4.0.3

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/all/patches/1.0.0/0001-static_assert.patch
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/1.0.0**
I'm the author, new release
---

cpptrace: Add version 1.0.0

---

recipes/glaze/all/conandata.yml
recipes/glaze/config.yml

Changes to recipe:  **glaze/5.4.1**
There are lots of new features with breaking changes in 5.4.0.
https://github.com/stephenberry/glaze/releases/tag/v5.4.0
https://github.com/stephenberry/glaze/releases/tag/v5.4.1
---

glaze: add version 5.4.1

---

recipes/libharu/all/conandata.yml
recipes/libharu/config.yml

Changes to recipe:  **libharu/all**
new upstream version
https://github.com/libharu/libharu/compare/v2.4.4...v2.4.5
---

libharu: add version 2.4.5

---

recipes/libftp/all/conandata.yml
recipes/libftp/all/conanfile.py
recipes/libftp/config.yml

Changes to recipe:  **libftp/1.5.0**
Add the new version.
https://github.com/deniskovalchuk/libftp/releases/tag/v1.5.0
https://github.com/deniskovalchuk/libftp/compare/v1.4.0...v1.5.0
---

libftp: add version 1.5.0

---

recipes/liburing/all/conandata.yml
recipes/liburing/config.yml

Adds version 2.11 (No make changes), needed by folly https://github.com/conan-io/conan-center-index/pull/25838

liburing: Add version 2.11

---

recipes/mcap/all/conandata.yml
recipes/mcap/config.yml

Changes to recipe:  **mcap/2.0.2**
Adding the latest version: v2.0.2.
https://github.com/foxglove/mcap/releases/tag/releases%2Fcpp%2Fv2.0.2
---

mcap: Add v2.0.2

---

recipes/harfbuzz/all/conandata.yml
recipes/harfbuzz/config.yml

Changes to recipe:  **harfbuzz/11.2.1**
New major version
https://github.com/harfbuzz/harfbuzz/compare/10.4.0...11.2.1
config.yml and conandata.yml point to the newly created harfbuzz/11.2.1.
---

Add harfbuzz/11.2.1

---

recipes/perfetto/all/conandata.yml
recipes/perfetto/config.yml

Changes to recipe:  **perfetto/[v50.1]**
Update recipe
---
- [ x ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ x ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ x ] Tested locally with at least one configuration using a recent version of Conan

Bump perfetto: v50.1

---

recipes/fmi3/all/conandata.yml
recipes/fmi3/config.yml

Changes to recipe:  **fmi3/3.0.1**
Adding latest version 3.0.2
Fixes #27820
Adding latest download link for release 3.0.2
---

Add fmi3/3.0.2 (fixes #27820)

---

recipes/crowcpp-crow/all/conandata.yml
recipes/crowcpp-crow/all/conanfile.py
recipes/crowcpp-crow/config.yml

Changes to recipe:  **crowcpp-crow/***
[v1.2.1 needs at least C++ 17 compiler](https://github.com/CrowCpp/Crow/releases/tag/v1.2.1.2)
https://github.com/CrowCpp/Crow/compare/v1.1.0...v1.2.1.2
---

crowcpp-crow: add version 1.2.1

---

recipes/libpng/all/conandata.yml
recipes/libpng/config.yml

Changes to recipe:  **libpng/all**
https://github.com/pnggroup/libpng/compare/v1.6.48...v1.6.50
---

libpng: add version 1.6.50

---

recipes/wayland/all/conandata.yml
recipes/wayland/all/test_package/CMakeLists.txt
recipes/wayland/config.yml

Changes to recipe:  **wayland/[1.23.92]**
Add the newer version
recipes/wayland/all/conandata.yml
recipes/wayland/all/test_package/CMakeLists.txt CMake 3.1 -> 3.15
recipes/wayland/config.yml
---

wayland: version 1.23.92

---

recipes/moltenvk/all/CMakeLists.txt
recipes/moltenvk/all/conandata.yml
recipes/moltenvk/all/dependencies/dependencies-1.3.0.yml
recipes/moltenvk/config.yml

Changes to recipe:  **moltenvk/1.3.0**
Upgrading to this version addresses an issue we have in moltenvk.
Wide changes, a lot of vulkan changes need to go hand in hand. One cherrypick from another branch.
Tested locally using conan 2.4.1.
---

Moltenvk 1.3.0

---

recipes/boost-ext-ut/all/conandata.yml
recipes/boost-ext-ut/all/conanfile.py
recipes/boost-ext-ut/config.yml

Changes to recipe:  **boost-ext-ut/[2.3.1]**
Add the new version
recipes/boost-ext-ut/all/conandata.yml
recipes/boost-ext-ut/all/conanfile.py
recipes/boost-ext-ut/config.yml
[https://github.com/boost-ext/ut/compare/v2.1.0...v2.3.1](https://github.com/boost-ext/ut/compare/v2.1.0...v2.3.1)
---

boost-ext-ut: version 2.3.1

---

recipes/benchmark/all/conandata.yml
recipes/benchmark/config.yml

Changes to recipe:  **benchmark/[1.9.4]**
Add the new version
recipes/benchmark/all/conandata.yml
recipes/benchmark/config.yml
[https://github.com/google/benchmark/compare/v1.9.1...v1.9.4](https://github.com/google/benchmark/compare/v1.9.1...v1.9.4)
---

benchmark: version 1.9.4

---

recipes/vulkan-loader/all/conandata.yml
recipes/vulkan-loader/config.yml

Changes to recipe:  **vulkan-loader/[1.4.313.0]**
Add the new version.
recipes/vulkan-loader/all/conandata.yml (the new version)
recipes/vulkan-loader/config.yml (the new version)
---
conan create . --version=1.4.313.0
[https://github.com/KhronosGroup/Vulkan-Loader/compare/vulkan-sdk-1.4.309.0...vulkan-sdk-1.4.313.0](https://github.com/KhronosGroup/Vulkan-Loader/compare/vulkan-sdk-1.4.309.0...vulkan-sdk-1.4.313.0)

vulkan-loader: version 1.4.313.0

---

recipes/onnx/all/conandata.yml
recipes/onnx/all/conanfile.py
recipes/onnx/config.yml

Add onnx 1.18.0

---

recipes/zookeeper-client-c/all/conandata.yml
recipes/zookeeper-client-c/config.yml

Changes to recipe:  **zookeeper-client-c/3.9.3**
Version bump to latest 3.9.3 as requested by #27324
Added new version and respective download information
---

zookeeper-client-c version 3.9.3

---

recipes/libuv/all/conanfile.py

---
* Moved to use `CMAKE_POLICY_VERSION_MINIMUM`
* Removed old Conan 1 generators file creation
* Moved `apply_conandata_patches` to source method

libuv: Fix CMake 4 support

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/config.yml

Add Cppcheck v2.18.0

---

recipes/tl-expected/all/conandata.yml
recipes/tl-expected/config.yml

Changes to recipe:  **tl-expected/1.2.0**
cf https://github.com/TartanLlama/expected/compare/v1.1.0...v1.2.0
---

tl-expected 1.2.0

---

recipes/spirv-headers/all/conanfile.py

As described here https://github.com/conan-io/conan-center-index/issues/26878

spirv-tools: Add CMake 4 support

---

recipes/ninja/all/conandata.yml
recipes/ninja/config.yml

Changes to recipe:  **ninja/1.13.1**
Add the latest version of the Ninja build tool.
Have the latest version of 1.13.x branch with recent bugfixes
---

ninja: add version 1.13.1

---

recipes/openexr/3.x/conanfile.py

- fix cppstd (builds with c++11)
- use version ranges for deps
- use newer convention for cppstd
- remove dead code (Conan 1)

openexr: fix cppstd

---

recipes/openexr/3.x/conandata.yml
recipes/openexr/config.yml

Changes to recipe:  **openexr/3.3.5**
Fixes a memory leak in the file reader.
https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.3.5
---

OpenEXR: Add version 3.3.5

---

recipes/hlslpp/all/conandata.yml
recipes/hlslpp/config.yml

Changes to recipe:  **hlslpp/3.7**
Updating to a most recent release.
Bump recipe version to 3.7
---

hlslpp: add v3.7

---

recipes/spirv-reflect/all/conandata.yml
recipes/spirv-reflect/all/conanfile.py
recipes/spirv-reflect/all/test_package/CMakeLists.txt
recipes/spirv-reflect/all/test_package/conanfile.py
recipes/spirv-reflect/all/test_package/test_package.cpp
recipes/spirv-reflect/config.yml

Changes to recipe:  **spirv-reflect/[1.4.313.0]**
Add the library [https://github.com/KhronosGroup/SPIRV-Reflect/](https://github.com/KhronosGroup/SPIRV-Reflect/)
recipes/spirv-reflect/all/conandata.yml (the version)
recipes/spirv-reflect/all/conanfile.py (a new recipe)
recipes/spirv-reflect/all/test_package/CMakeLists.txt (a test)
recipes/spirv-reflect/all/test_package/conanfile.py (a test)
recipes/spirv-reflect/all/test_package/test_package.cpp (a test)
recipes/spirv-reflect/config.yml (the version)
---

spirv-reflect: version 1.4.313.0

---

recipes/opusfile/all/conandata.yml
recipes/opusfile/all/conanfile.py
recipes/opusfile/config.yml

Changes to recipe:  **opusfile/0.12**
Fixes building with msvc for ARM64 architecture.
Error that appears without this change:
> opusfile/0.12: RUN: msbuild.exe "C:\Users\runneradmin\.conan2\p\b\opusf812186880deb3\b\src\win32\VS2015\opusfile.sln" -p:Configuration="Release" -p:Platform=ARM64 -target:opusfile
> conanvcvars.bat: Activating environment Visual Studio 17 - arm64 - winsdk_version=None - vcvars_ver=14.4
> [vcvarsall.bat] Environment initialized for: 'arm64'
> MSBuild version 17.14.14+a129329f1 for .NET Framework
> Build started 8/2/2025 3:30:54 PM.
> 
> Project "C:\Users\runneradmin\.conan2\p\b\opusf812186880deb3\b\src\win32\VS2015\opusfile.sln" on node 1 (opusfile target(s)).
> C:\Users\runneradmin\.conan2\p\b\opusf812186880deb3\b\src\win32\VS2015\opusfile.sln.metaproj : error …

opusfile: fix building with msvc for ARM64

---

recipes/wxwidgets/all/conanfile.py

Changes to recipe:  **wxwidgets/all**
Due to https://github.com/conan-io/conan-center-index/issues/28092, wxwidgets package get broken
---

fix: wxwidgets broken due to libjpeg confliction.

---

recipes/dataframe/all/conandata.yml
recipes/dataframe/config.yml

Changes to recipe:  **dataframe/3.6.0**
Upgrading C++ DataFrame to version 3.6.0
**[_Please consider sponsoring DataFrame, especially if you are using it in Production Capacity. It is the strongest form of appreciation_](https://github.com/sponsors/hosseinmoein)**
**Improved documentation by creating split windows**
Added cheat-sheet to docs
Fixed some edge bug in parallel sort
Implemented detect_and_fill()
Implemented detect_and_change()
Implemented KolmoSmirnovTestVisitor visitor
Implemented MannWhitneyUTestVisitor visitor
Implemented mask()
Added many more functionalities to the internal Matrix class
Implemented fast_ica()
Fixed the inconsistency in writing/reading DateTime columns to/from files
**Added ability to read only selected columns from files**
Implemented MutualInfoVisitor …

dataframe: Upgrading C++ DataFrame to version 3.6.0

---

recipes/function2/all/conandata.yml
recipes/function2/config.yml

Changes to recipe:  **function2/[4.2.5]**
Get access to fixes in the latest version: [changelog](https://github.com/Naios/function2/releases/tag/4.2.5)
---

function2: add version 4.2.5

---

recipes/libassert/config.yml
recipes/libassert/v2/conandata.yml

Changes to recipe:  **libassert/2.2.1**
I'm the author, new version
---

libassert: Bump to 2.2.1

---

recipes/cpptrace/all/conandata.yml
recipes/cpptrace/config.yml

Changes to recipe:  **cpptrace/1.0.4**
I'm the author, new version
---

cpptrace: Bump to 1.0.4

---

recipes/lyra/all/conandata.yml
recipes/lyra/config.yml

Changes to recipe:  **lyra/1.7.0**
Version bump for new release.
Lyra 1.7.0 released
---

lyra-1.7.0

---

recipes/meson/all/conandata.yml
recipes/meson/config.yml

Changes to recipe:  **meson/1.8.2**
Lots of features have been introduces in 1.8.0.
https://github.com/mesonbuild/meson/releases/tag/1.8.2
https://mesonbuild.com/Release-notes-for-1-8-0.html
---

meson: add version 1.8.2

---

recipes/angelscript/all/conandata.yml
recipes/angelscript/all/conanfile.py
recipes/angelscript/config.yml

Changes to recipe:  **angelscript/2.38.0**
New minor version
https://www.angelcode.com/angelscript/changes.php
config.yml and conandata.yml point to the newly created angelscript/2.38.0.
---

Add angelscript/2.38.0

---

recipes/libjwt/all/conandata.yml
recipes/libjwt/all/conanfile.py
recipes/libjwt/all/test_package/CMakeLists.txt
recipes/libjwt/all/test_package/conanfile.py
recipes/libjwt/all/test_package/src/example.cpp
recipes/libjwt/config.yml

libjwt: add new recipe

---

docs/faqs.md

Fix typo: generators

---

recipes/sentry-native/all/conanfile.py

- **wip_qt**
- **[sentry-native] Add OpenSSL dependency for Qt support**
---

[sentry-native] Remove OpenSSL dependency for Qt support

---

recipes/readline/all/conandata.yml
recipes/readline/all/conanfile.py
recipes/readline/config.yml

readline: Add mirror sources

---

recipes/libiberty/all/conandata.yml
recipes/libiberty/all/conanfile.py

Also cleans ups a bit of the recipe

libiberty: Add mirror sources

---

recipes/gmp/all/conandata.yml
recipes/gmp/all/conanfile.py
recipes/gmp/config.yml

Also cleans up the recipe and removes unused version in CCI

gmp: Add mirror sources

---

recipes/open62541/all/conanfile.py

fixes https://github.com/conan-io/conan-center-index/issues/28246
Changes to recipe:  **open62541/***
https://github.com/eirikb/proof-of-conan/actions/runs/17159328028
---

fix regression in older versions of open62541

---

recipes/binutils/all/conandata.yml

From https://github.com/conan-io/conan-center-index/issues/28269

binutils: Fix mirror URLs

---

recipes/spirv-cross/all/conandata.yml
recipes/spirv-cross/config.yml

Changes to recipe: **spirv-cross/[1.4.321.0]**
Add the new version.
recipes/spirv-cross/all/conandata.yml (the new version)
recipes/spirv-cross/config.yml (the new version)
---

spirv-cross: version 1.4.321.0

---

recipes/nuraft/all/conandata.yml
recipes/nuraft/all/conanfile.py
recipes/nuraft/all/test_package/CMakeLists.txt
recipes/nuraft/all/test_package/conanfile.py
recipes/nuraft/config.yml

Changes to recipe:  **nuraft/3.0.0**
The PR adds nuraft 3.0.0 version which was recently released. 
Conanfile.py is the same as [here](https://github.com/eBay/NuRaft/blob/master/conanfile.py) with an update of how source is used.
---

Nuraft 3.0.0

---

recipes/au/all/conandata.yml
recipes/au/all/conanfile.py
recipes/au/config.yml

Changes to recipe:  **au** (add 0.5.0)
There is a significant new Au release!  See [release notes].
To test these changes:
```sh
cd recipes/au
conan create all/conanfile.py --version=0.5.0
```
This ran with no errors and produced the expected output.
---
[release notes]: https://github.com/aurora-opensource/au/releases/tag/0.5.0

Add Au 0.5.0 to conan

---

recipes/ppqsort/all/conandata.yml
recipes/ppqsort/all/conanfile.py
recipes/ppqsort/all/test_package/CMakeLists.txt
recipes/ppqsort/all/test_package/conanfile.py
recipes/ppqsort/all/test_package/test_package.cpp
recipes/ppqsort/config.yml

Changes to recipe:  **ppqsort/1.0.6**
New package. Used in [Tracy profiler](https://github.com/wolfpld/tracy) for example.
recipes/ppqsort
---

ppqsort: add initial recipe and test package for version 1.0.6

---

recipes/clickhouse-cpp/all/conanfile.py

Changes to recipe:  **clickhouse-cpp**
Fix https://github.com/conan-io/conan-center-index/issues/28404
Reduce minimum abseil version introduced in here https://github.com/conan-io/conan-center-index/commit/745473ca739568e87da8c1c5ba5f0330c53012a6

clickhouse-cpp: Relax abseil minimum requirement

---

recipes/di/all/conandata.yml
recipes/di/config.yml

Add new version: di/1.3.2
Add new version with important fixes
I have added the version 1.3.2 that was released long timem ago
---

di: add version 1.3.2

---

recipes/qtawesome/all/conandata.yml
recipes/qtawesome/config.yml

[qtawesome] Add version 7.0.0

---

recipes/eigen/all/conandata.yml
recipes/eigen/all/conanfile.py
recipes/eigen/config.yml

Changes to recipe:  **eigen/5.0.0**
Release notes: [link](https://gitlab.com/libeigen/eigen/-/releases)
Changelog: [link](https://gitlab.com/libeigen/eigen/-/milestones/10#tab-issues)
It looks like v5.0.0 introduces two new build knobs ([link](https://gitlab.com/libeigen/eigen/-/blob/master/CMakeLists.txt#L62-75)) that it may be worth exposing as an option in the recipe:
- EIGEN_BUILD_BLAS
- EIGEN_BUILD_LAPACK
For now both options are turned off in the recipe becase they result in one shared and one static library (see build log below):
<details>
<summary>Build log</summary>
```
eigen/5.0.0: Exporting package recipe: /home/user/github/conan-center-index/recipes/eigen/all/conanfile.py
eigen/5.0.0: exports: File 'conandata.yml' found. …
```

[eigen] add v5.0.0

---

recipes/expat/all/conandata.yml
recipes/expat/config.yml

Changes to recipe:  **expat/2.7.3**
Security fixes listed here https://github.com/libexpat/libexpat/blob/R_2_7_3/expat/Changes
Add the latest version of expat, 2.7.3 just released.
---

[expat] Update expat recipe to suport version 2.7.3.

---

recipes/tiny-optional/all/conandata.yml
recipes/tiny-optional/config.yml

Changes to recipe:  **tiny-optional/1.5.2**
Issue: #28483 
Just updating the source. The upstream CMakeLists.txt doesn't seem to change since the last version.
---

tiny-optional: Update to 1.5.2 (#28483)

---

recipes/openssl/3.x.x/conandata.yml
recipes/openssl/config.yml

Changes to recipe:  **openssl/3.6.0**
---

openssl: add version `3.6.0`

---

recipes/cmake/binary/conandata.yml
recipes/cmake/config.yml

Changes to recipe:  **cmake/4.1.2**
Have latest version of CMake v4.1.x
Have the latest bugfixes and improvements.
---

CMake: update to version 4.1.2

---

recipes/libpqxx/all/conandata.yml
recipes/libpqxx/all/patches/fix-cannot-build-c++17-msvc-7.10.2.patch
recipes/libpqxx/config.yml

Changes to recipe:  **libpqxx/7.10.2**
The latest release version: https://github.com/jtv/libpqxx/releases/tag/7.10.2
---

libpqxx: add version 7.10.2
