- recipes/zulu-openjdk/all/conandata.yml
- recipes/zulu-openjdk/config.yml
Changes to recipe:  **zulu-openjdk/11.0.24**
Adding the binaries for zulu for these less popular platforms allows us to switch to using this for a JNI interface, where in the past we have had multiple JDK Conan packages in use.
Add the Zulu jdk version 11.0.24 for x86, x86_64, armv8 and SPARC v9 (64-bit) platforms.
---
> [zulu-openjdk/11.0.24] Add Zulu JDK version 11.0.24 for platforms of interest.

- recipes/libpng/all/conandata.yml
- recipes/libpng/all/conanfile.py
- recipes/libpng/config.yml
Changes from version 1.6.43 to version 1.6.44
---------------------------------------------
* Hardened calculations in chroma handling to prevent overflows, and
relaxed a constraint in cHRM validation to accomodate the standard
ACES AP1 set of color primaries.
(Contributed by John Bowler)
* Removed the ASM implementation of ARM Neon optimizations and updated
the build accordingly. Only the remaining C implementation shall be
used from now on, thus ensuring the support of the PAC/BTI security
features on ARM64.
(Contributed by Ross Burton and John Bowler)
* Fixed the pickup of the PNG_HARDWARE_OPTIMIZATIONS option in the
CMake build on FreeBSD/amd64. This is an important performance fix
on this platform.
* Applied various fixes and improvements to the CMake build.
(Contributed by Eric …
> [libpng/1.6.44] Add a new version of libpng

- recipes/drogon/all/conandata.yml
- recipes/drogon/all/conanfile.py
- recipes/drogon/all/patches/1.9.7-0002-find-cci-packages.patch
- recipes/drogon/all/patches/1.9.7-0003-include-exception.patch
- recipes/drogon/config.yml
Changes to recipe:  **drogon/1.9.7**
There are several improvements in 1.9.7.
https://github.com/drogonframework/drogon/compare/v1.9.6...v1.9.7
---
> drogon: add version 1.9.7

- recipes/vulkan-validationlayers/all/conanfile.py
Changes to recipe:  **vulkan-validationlayers/1.3.224.1**
The `vulkan-validationlayers` Conan recipe is not well supported for Android, this PR fixes the current state.
Current error:
```
[50/53] /home/uilian/.conan2/p/androc80020a02a776/p/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android32 --sysroot=/home/uilian/.conan2/p/androc80020a02a776/p/bin/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DAPI_NAME=\"Vulkan\" -DUSE_ROBIN_HOOD_HASHING -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_ANDROID_KHR -DVK_USE_PLATFORM_ANDROID_KHX -DVkLayer_khronos_validation_EXPORTS -I/home/uilian/.conan2/p/b/vulka645cb56898d3a/b/src/layers -I/home/uilian/.conan2/p/b/vulka645cb56898d3a/b/src/layers/generated -I/home/uilian/.conan2/p/vulka6a51cc1ce5120/p/include …
```
> [vulkan-validationlayers] Add support for Android

- recipes/libdatrie/all/conandata.yml
- recipes/libdatrie/all/conanfile.py
- recipes/libdatrie/all/patches/fix-exports.patch
- recipes/libdatrie/all/test_package/CMakeLists.txt
- recipes/libdatrie/all/test_package/conanfile.py
- recipes/libdatrie/all/test_package/test_package.c
- recipes/libdatrie/config.yml
Adds libdatrie: https://linux.thai.net/projects/datrie
datrie is an implementation of double-array structure for representing trie, as proposed by Junichi Aoe.
Trie is a kind of digital search tree, an efficient indexing method with O(1) time complexity for searching. Comparably as efficient as hashing, trie also provides flexibility on incremental matching and key spelling manipulation. This makes it ideal for lexical analyzers, as well as spelling dictionaries.
[![Packaging status](https://repology.org/badge/tiny-repos/libtirpc.svg)](https://repology.org/project/libtirpc/versions)
> libdatrie: new recipe

- recipes/ann/all/CMakeLists.txt
- recipes/ann/all/conandata.yml
- recipes/ann/all/conanfile.py
- recipes/ann/all/patches/1.1.2-0001-fix-windows-static.patch
- recipes/ann/all/patches/1.1.2-0002-fix-cppstd17+-register-keyword.patch
- recipes/ann/all/test_package/CMakeLists.txt
- recipes/ann/all/test_package/conanfile.py
- recipes/ann/all/test_package/test_package.cpp
- recipes/ann/config.yml
Changes to recipe: **ann/1.1.2**
Add ANN library to conancenter.
- Upstream there are some raw Makefiles and a vcproj file (only for DLL, not static). I've written a simple CMakeLists instead (library is very simple to compile), so that it can be more portable.
- A small fix is needed for static lib on windows in order to avoid dllexport/dllimport. So a `ANN_STATIC` definition is introduced, it must be defined at build & consume time if windows & static.
- Another fix is needed for compilation with C++17 or above: there are `register` keyword in front of several variables in source code (several cpp files & private headers, no fix required in public headers). It's useless and not supported at all since C++17.
- The latest version is from 2010, so I don't hope any backport of these patches …
> add new recipe ann/1.1.2

- recipes/catch2/3.x.x/conandata.yml
- recipes/catch2/3.x.x/conanfile.py
- recipes/catch2/config.yml
Changes to recipe:  **catch2/3.7.1**
There are several improvements in 3.7.1.
https://github.com/catchorg/Catch2/compare/v3.7.0...v3.7.1
---
> catch2: add version 3.7.1

- recipes/libjpeg-turbo/all/conandata.yml
- recipes/libjpeg-turbo/config.yml
Changes to recipe:  **libjpeg-turbo/3.0.4**
Add version 3.0.4
https://github.com/libjpeg-turbo/libjpeg-turbo/compare/3.0.3...3.0.4
---
> libjpeg-turbo: add version 3.0.4

- recipes/range-v3/all/conandata.yml
- recipes/range-v3/config.yml
Added newest `range-v3` `master` as `cci.20240905`.  
`range-v3` didn't see a release for over 2 years, despite numerous bug fixes and improvements being implemented. This new version adds support for new versions of GCC.
This version fixes compilation issues in newer versions of GCC.  
See this issue: https://github.com/ericniebler/range-v3/issues/1672
Just added a version, that is not an official release of `range-v3`.  
I've chosen `cci.20240905` as a version number, as I've seen this format used in other packages.
---
> range-v3: add version cci.20240905.

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/config.yml
Changes to recipe:  **mongo-c-driver/1.28.0**
There are several new features in 1.28.0.
https://github.com/mongodb/mongo-c-driver/compare/1.27.6...1.28.0
Try to close https://github.com/conan-io/conan-center-index/issues/25313.
---
> mongo-c-driver: add version 1.28.0

- recipes/vir-simd/all/conandata.yml
- recipes/vir-simd/config.yml
Changes to recipe:  **vir-simd/0.3.1**
Add releases 0.3.0 and 0.3.1
- https://github.com/mattkretz/vir-simd/releases/tag/v0.3.0
- https://github.com/mattkretz/vir-simd/releases/tag/v0.3.1 
---
> vir-simd: add versions 0.3.0, 0.3.1

- recipes/fixed_math/1.x.x/conandata.yml
- recipes/fixed_math/1.x.x/conanfile.py
- recipes/fixed_math/1.x.x/test_package/CMakeLists.txt
- recipes/fixed_math/1.x.x/test_package/conanfile.py
- recipes/fixed_math/1.x.x/test_package/test_package.cpp
- recipes/fixed_math/all/conandata.yml
- recipes/fixed_math/all/conanfile.py
- recipes/fixed_math/all/test_package/test_package.cpp
- recipes/fixed_math/config.yml
Changes to recipe:  **fixed_math/***
- fixed_math becomes header only
- add version 2.0.0
- fix install path (https://github.com/arturbac/fixed_math/issues/8)
https://github.com/arturbac/fixed_math/compare/v1.0.2...v2.0.0
---
> fixed_math: add version 2.0.0, fix install path

- recipes/cairo/all/conandata.yml
- recipes/cairo/all/patches/1.18.0-msvc-alloca.patch
Changes to recipe:  **cairo/[1.18]**
Couldn't compile on my local MSVC setup, but it's interesting to note that the CI did not have the same issue.
This patch is present in most other package managers, seems like we added the version too soon to catch it
Before:
```
[150/151] Linking target util/cairo-script/csi-exec.exe
FAILED: util/cairo-script/csi-exec.exe
"link"  /MACHINE:x64 /OUT:util/cairo-script/csi-exec.exe util/cairo-script/csi-exec.exe.p/csi-exec.c.obj "/release" "/nologo" "/OPT:REF" "src/libcairo.a" "util/cairo-script/libcairo-script-interpreter.a" "C:/Users/abril/.conan2/p/zlib6f797a4dd16fb/p/lib/zlib.lib" "C:/Users/abril/.conan2/p/libpn214f4edd5a70e/p/lib/libpng16_static.lib" "C:/Users/abril/.conan2/p/fontc74b173433a2a8/p/lib/fontconfig.lib" …
```
> cairo: Fix alloca issue in MSVC cairo

- recipes/libzip/all/conandata.yml
- recipes/libzip/all/conanfile.py
- recipes/libzip/all/patches/1.11.1-0002-remove-rpath.patch
- recipes/libzip/config.yml
There are several improvements since 1.10.1.
https://github.com/nih-at/libzip/compare/v1.10.1...v1.11.1
---
> libzip: add version 1.11.1

- recipes/libsndfile/all/conanfile.py
- recipes/libsndfile/all/test_package/CMakeLists.txt
- recipes/libsndfile/all/test_package/conanfile.py
- recipes/libsndfile/all/test_package/test_package.c
- recipes/libsndfile/all/test_package/test_package.cpp
- recipes/libsndfile/all/test_v1_package/conanfile.py
> libsndfile: fix missing glibc symbols on newer systems

- recipes/onetbb/all/conanfile.py
hwloc can't be built for these platforms
Changes to recipe:  **onetbb/***
to use the latest version of tbb for iOS, one must explicitly disable tbbind option which is inconvenient
hwloc can only be built for macOS among Apple platforms
---
> onetbb: disable tbbind for Apple non-macOS

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/config.yml
Changes to recipe:  **libxml2/***
2.11.9 and 2.12.9 contain fix for [CVE-2024-40896] Fix XXE protection in downstream code
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.11.9
https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.12.9
I've also removed bugfix versions that aren't present in current master
---
> libxml2: add 2.11.9, 2.12.9 and remove unused versions

- recipes/libnl/all/conanfile.py
- recipes/libnl/all/test_package/CMakeLists.txt
Changes to recipe:  **libnl/[*]**
The PR https://github.com/conan-io/conan-center-index/pull/23383, when building with libnl support, libpcap failed to find libnl-genl-3.0.pc
/cc @valgur 
The libnl uses specific names for its components, using 3.0 as suffix:
```
/bin/mkdir -p '/home/conan/.conan2/p/b/libnlef6c99bdd2af2/p//lib/pkgconfig'
/usr/bin/install -c -m 644 /home/conan/.conan2/p/b/libnlef6c99bdd2af2/b/src/man/genl-ctrl-list.8 /home/conan/.conan2/p/b/libnlef6c99bdd2af2/b/src/man/nl-classid-lookup.8 /home/conan/.conan2/p/b/libnlef6c99bdd2af2/b/src/man/nl-pktloc-lookup.8 /home/conan/.conan2/p/b/libnlef6c99bdd2af2/b/src/man/nl-qdisc-add.8 /home/conan/.conan2/p/b/libnlef6c99bdd2af2/b/src/man/nl-qdisc-delete.8 /home/conan/.conan2/p/b/libnlef6c99bdd2af2/b/src/man/nl-qdisc-list.8 …
```
> Add correct pkfconfig name for libnl components

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/all/conanfile.py
- recipes/libxml2/config.yml
Changes to recipe:  **libxml2**
Stay up to date with somewhat recent releases of upstream, fix CVE issues. Update to latest patch version.
See also: <https://gitlab.gnome.org/GNOME/libxml2/-/releases>
Version bump
---
> libxml2: Add version 2.13.4, fixes a few CVE issues

- recipes/libxslt/all/conandata.yml
- recipes/libxslt/all/conanfile.py
- recipes/libxslt/config.yml
Changes to recipe:  **libxslt/[*]**
New libxml2 1.13 removed deprecated symbols that were in used by old versions of this recipe
Reported by @gsantner in https://github.com/conan-io/conan-center-index/pull/25322#issuecomment-2373299498
> libxslt: Add new version that supports newer libxml2 versions

- docs/package_templates/autotools_package/all/conanfile.py
Fix my own mistake in version range of pkgconf in autotools package template (https://github.com/conan-io/conan-center-index/pull/25218)
---
> docs: fix version range of pkgconf in autotools package template

- recipes/libuvc/all/conanfile.py
Changes to recipe:  **libuvc/all**
We have found an error thanks to the experimental conan linter:
```
recipes/libuvc/all/conanfile.py::53:16 - W0104: Statement seems to have no effect (pointless-statement)
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│    52             if self.options.jpeg_turbo:                                                                                                                              │
│    53                 self.options.with_jpeg == "libjpeg-turbo"                                                                                                            │
╰─────────────────────────────────────────────────────────────────── …
```
> libuvc: remove deprecated libjpeg-turbo option

- recipes/fire-hpp/all/conandata.yml
- recipes/fire-hpp/all/test_package/CMakeLists.txt
- recipes/fire-hpp/config.yml
Changes to recipe:  **fire-hpp/1.0**
This is the first stable release.
https://github.com/kongaskristjan/fire-hpp/compare/v0.2...v1.0
---
> fire-hpp: add version 1.0

- recipes/aws-sdk-cpp/all/conanfile.py
Changes to recipe:  **aws-sdk-cpp/[version]**
Follow-up to https://github.com/conan-io/conan-center-index/pull/24924
Thanks @maksim-petukhov for the heads-up
> aws-sdk-cpp: Fix s2n requirement

- recipes/libmagic/all/conanfile.py
Changes to recipe:  **libmagic/[*]**
Needed for `xz_utils/[>=5.4.5 <6]` in #19381.
---
> libmagic: use version ranges

- recipes/azure-storage-cpp/all/conanfile.py
Changes to recipe:  **azure-storage-cpp/7.5.0**
The azure-storage-cpp library was deprecated in March 2024: https://azure.microsoft.com/en-us/updates/retirement-notice-the-legacy-azure-storage-c-client-libraries-will-be-retired-on-29-march-2025/
This PR marks the recipe as deprecated accordingly. `azure-sdk-for-cpp::azure-storage-blobs-cpp` should be used instead.
---
> azure-storage-cpp: mark as deprecated

- recipes/xmlsec/all/conanfile.py
Also took the chance to bump pkgconf to a version range 
Successful compilation logs with `-o="&:with_xslt=True"`:
<details>
```
$ conan create . --version=1.3.4 -b=missing -o="&:with_xslt=True" -c="tools.files.download:verify=False"
xmlsec/1.3.4: Exporting package recipe: /Users/abril/coding/conan-center-index/recipes/xmlsec/all/conanfile.py
xmlsec/1.3.4: exports: File 'conandata.yml' found. Exporting it...
xmlsec/1.3.4: Copied 1 '.py' file: conanfile.py
xmlsec/1.3.4: Copied 1 '.yml' file: conandata.yml
xmlsec/1.3.4: Exported to cache folder: /Users/abril/coding/conan-center-index/recipes/eudev/all/conan_home/p/xmlsea5015bc8e5356/e
xmlsec/1.3.4: Exported: xmlsec/1.3.4#02398c20557217516a34c637a1919d19 (2024-09-25 15:31:21 UTC)
======== Input …
```
> xmlsec: Avoid conflicts with the rest of libxslt

- recipes/libpq/all/conandata.yml
- recipes/libpq/all/patches/15.5/0001-Use-BIO_-get-set-_app_data-instead-of-BIO_-get-se.patch
Changes to recipe:  **libpq/15.5**
Include backported bugfix for using it along with OpenSSL 3.2.x also to version 15.5  [issue](https://github.com/conan-io/conan-center-index/issues/24440)
The same patch is already applied to 15.3 and 15.4, the update to 15.5 was merged in the same time window as this patch was included, so it was probably missed out.
The patch needed to be rebased to the 15.5 postgres release changing only line numbers and commit hashes. Original author information was left in place.
Upstream includes a fix starting from 15.6 according to the [libpq 15.6 release notes](https://www.postgresql.org/docs/release/15.6/)
Open PR [21951](https://github.com/conan-io/conan-center-index/pull/21951)  should therefore hopefully not be affected by this PR.
---
> libpq: add backported OpenSSL 3.2.x fix to libpq/15.5

- recipes/box2d/all/conandata.yml
- recipes/box2d/all/conanfile.py
- recipes/box2d/all/patches/3.0.0-0001-fix-cmake.patch
- recipes/box2d/all/patches/3.0.0-0002-use-cci.patch
- recipes/box2d/all/test_package/CMakeLists.txt
- recipes/box2d/all/test_package/conanfile.py
- recipes/box2d/all/test_package/test_package3.c
- recipes/box2d/config.yml
Changes to recipe:  **box2d/3.0.0**
box2d/3.0.0 has been completely overhauled.
It is written in C instead of C++.
https://github.com/erincatto/box2d/compare/v2.4.2...v3.0.0
---
> box2d: add new version 3.0.0

- recipes/brunsli/all/conanfile.py
Reverts conan-io/conan-center-index#21238
The bot ignored the blocked label while we investigated
> Revert "brunsli: allow shared brotli dependency"

- recipes/quazip/all/conandata.yml
- recipes/quazip/all/conanfile.py
- recipes/quazip/config.yml
Changes to recipe:  **quazip/1.3**
The maintained version of Qt-5 is 5.15.14, resulting in missing binary packages when building this package. Using version ranges for Qt solves the current error.
More about current version ranges in CCI: https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges
I also remove version 1.1. Quazip is not used in CCI, only consumed externally. Most of issues only mention version: https://github.com/conan-io/conan-center-index/issues?q=is%3Aissue+quazip
---
> [quazip] Use version range for Qt

- recipes/qwt/all/conanfile.py
Changes to recipe:  **qwt/6.2.0**
The maintained version of Qt-5 is 5.15.14, resulting in missing binary packages when building this package. Using version ranges for Qt solves the current error.
---
> [qwt] Use version range for Qt

- recipes/xtr/all/conandata.yml
- recipes/xtr/all/conanfile.py
- recipes/xtr/config.yml
Changes to recipe:  Bump version to xtr/2.1.2 and guard CMakefiles.txt patch to exclude 2.1.2
Updates the xtr recipe to the latest version.
Bumps version to 2.1.2 and excludes 2.1.2 from having a patch applied, as this patch has been merged into xtr.
---
> xtr: bump to 2.1.2

- recipes/pcre2/all/conandata.yml
- recipes/pcre2/all/patches/0002-fix-cmake-c-std.patch
* Fixes compilation issues with for loops
Specify library name and version:  **pcre2/10.42**
Fixes https://github.com/conan-io/conan-center-index/issues/19725
---
> PCRE2: Explicitly specify cmake c standard

- recipes/daw_json_link/all/conandata.yml
Fixes `Version conflict: Conflict between daw_header_libraries/2.110.0 and daw_header_libraries/2.106.0 in the graph.
Conflict originates from daw_utf_range/2.2.5`
> daw_json: Bring daw_json and daw_regex in line with their respective daw_headers

- recipes/luau/all/conandata.yml
- recipes/luau/config.yml
Changes to recipe:  **luau/0.645**
There are lots of improvements since 0.640.
https://github.com/luau-lang/luau/compare/0.640...0.645
---
> luau: add version 0.645

- recipes/rapidcsv/all/conandata.yml
- recipes/rapidcsv/config.yml
Changes to recipe:  **rapidcsv/8.84**
There is an bugfix in 8.84.
https://github.com/d99kris/rapidcsv/compare/v8.83...v8.84
---
> rapidcsv: add version 8.84

- recipes/tracy/all/conandata.yml
- recipes/tracy/all/conanfile.py
- recipes/tracy/config.yml
There are several improvements in 0.11.1.
1. add `TRACY_VERBOSE` option.
2. fix `libbacktrace_elf_dynload_support` issue.
https://github.com/wolfpld/tracy/compare/v0.11.0...v0.11.1
---
> tracy: add version 0.11.1

- recipes/tinyad/all/conandata.yml
- recipes/tinyad/all/conanfile.py
- recipes/tinyad/all/test_package/CMakeLists.txt
- recipes/tinyad/all/test_package/conanfile.py
- recipes/tinyad/all/test_package/test_package.cpp
- recipes/tinyad/config.yml
Changes to recipe:  **tinyad/cci.20240718**
TinyAD is a library for automatic differentiation, presented at Eurographics Symposium on Geometry Processing 2022
Add the library
---
- [X ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [X ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [X ] Tested locally with at least one configuration using a recent version of Conan
> Add TinyAD

- .c3i/config_v1.yml
Add warning for change in Conan 1.x support
Looking for something like this:
> Add warning for Conan 1.x support

- recipes/fcl/all/conanfile.py
- recipes/fcl/all/test_package/test_package.cpp
Changes to recipe:  **fcl/[*]**
---
> fcl: add missing transitive_headers=True, CMP0077

- recipes/lielab/all/conandata.yml
- recipes/lielab/config.yml
Changes to recipe:  lielab/0.4.x
Added lielab/0.4.1
Uses the existing recipe. Updated for new 0.4.1 tarball.
---
> lielab: add version 0.4.1

- recipes/rapidhash/all/conandata.yml
- recipes/rapidhash/all/conanfile.py
- recipes/rapidhash/all/test_package/CMakeLists.txt
- recipes/rapidhash/all/test_package/conanfile.py
- recipes/rapidhash/all/test_package/test_package.cpp
- recipes/rapidhash/config.yml
Changes to recipe:  **rapidhash/1.0**
rapidhash is the official successor of [wayhash](https://github.com/wangyi-fudan/wyhash).
https://github.com/Nicoshev/rapidhash/
---
> rapidhash: add new recipe

- recipes/iguana/all/conandata.yml
- recipes/iguana/all/test_package/CMakeLists.txt
- recipes/iguana/all/test_package/test_package_1_0_5.cpp
- recipes/iguana/config.yml
Changes to recipe:  **iguana/1.0.6**
There are lots of improvements in 1.0.6.
https://github.com/qicosmos/iguana/compare/1.0.5...1.0.6
The name of macro has been renamed from `REFLECTION` to `YLT_REFL` in 1.0.6.
---
> iguana: add version 1.0.6

- recipes/libheif/all/conanfile.py
Changes to recipe:  **libheif/***
Add with_openjph option. (openjph recipe has been added.)
`WITH_OPENJPH_ENCODER` has been added since 1.18.0.
Build log with `with_openjph=True` in apple-clang 16.
<details>
libheif/1.18.2: Exporting package recipe: /Users/toge/src/conan-center-index/recipes/libheif/all/conanfile.py
libheif/1.18.2: exports: File 'conandata.yml' found. Exporting it...
libheif/1.18.2: Calling export_sources()
libheif/1.18.2: Copied 1 '.py' file: conanfile.py
libheif/1.18.2: Copied 1 '.yml' file: conandata.yml
libheif/1.18.2: Exported to cache folder: /Users/toge/.conan2/p/libhe6595530092c3a/e
libheif/1.18.2: Exported: libheif/1.18.2#f72c842f870e00e68589c2bfd5269e2b (2024-09-30 14:20:54 UTC)
======== Input profiles ======== …
> libheif: add with_openjph

- recipes/libjpeg/all/conanfile.py
- recipes/libjpeg/all/test_package/conanfile.py
Changes to recipe:  **libjpeg/all**
Fix build of libjpeg with clang-cl (might be a regression coming from https://github.com/conan-io/conan-center-index/pull/23840)
Use MSBuild branch when we detect a msvc or clang-cl profile (what I call a cl like profile). I don't know if these MSBuild files can work with clang-cl, I'm not sure that replacing NMake by MSBuild in https://github.com/conan-io/conan-center-index/pull/23840 was a good move.
closes https://github.com/conan-io/conan-center-index/issues/24933
---
> libjpeg: fix build with clang-cl

- recipes/cnats/all/conandata.yml
- recipes/cnats/config.yml
Changes to recipe:  **cnats/3.8.2**
v3.8.3 is released with some fixes: https://github.com/nats-io/nats.c/releases/tag/v3.8.3
No build changes: https://github.com/nats-io/nats.c/compare/v3.8.2...v3.8.3
---
> cnats: add version 3.8.3

- recipes/sdl/all/conandata.yml
- recipes/sdl/config.yml
Changes to recipe:  **sdl/***
There are several bugfixes in 2.30.8.
https://github.com/libsdl-org/SDL/compare/release-2.30.7...release-2.30.8
---
> sdl: add version 2.30.8, remove older versions

- recipes/gperftools/all/conandata.yml
- recipes/gperftools/all/conanfile.py
- recipes/gperftools/config.yml
Changes to recipe:  **gperftools/2.16**
There are lots of internal improvements in 2.16.
Now C++17 is required.
https://github.com/gperftools/gperftools/compare/gperftools-2.15...gperftools-2.16
---
> gperftools: add version 2.16

- recipes/tree-sitter/all/conandata.yml
- recipes/tree-sitter/config.yml
Changes to recipe:  **tree-sitter/***
There are several improvements in 0.23.1.
https://github.com/tree-sitter/tree-sitter/compare/v0.23.0...v0.23.1
---
> tree-sitter: add version 0.23.1, remove older versions

- recipes/mongo-cxx-driver/all/conandata.yml
- recipes/mongo-cxx-driver/all/conanfile.py
- recipes/mongo-cxx-driver/config.yml
Changes to recipe:  **mongo-cxx-driver/***
There are lots of improvements in 3.11.0.
Updating mongo-c-driver to 1.28.0.
Remove older versions.
https://github.com/mongodb/mongo-cxx-driver/compare/r3.10.2...r3.11.0
---
> mongo-cxx-driver: add version 3.11.0, update mongo-c-driver

- recipes/wyhash/all/conanfile.py
Changes to recipe:  **wyhash/***
rapidhash is released for successor of wyhash.
> wyhash has evolved into [rapidhash](https://github.com/Nicoshev/rapidhash) !
> With improved speed, quality and compatibility.
https://github.com/wangyi-fudan/wyhash?tab=readme-ov-file#wyhash-has-evolved-into-rapidhash-with-improved-speed-quality-and-compatibility
---
> wyhash: deprecated (rapidhash is successor)

- recipes/nghttp3/all/conandata.yml
- recipes/nghttp3/config.yml
Changes to recipe:  **nghttp3/1.6.0**
There are several improvements in 1.6.0.
https://github.com/ngtcp2/nghttp3/compare/v1.5.0...v1.6.0
---
> nghttp3: add version 1.6.0

- recipes/libdeflate/all/conandata.yml
- recipes/libdeflate/config.yml
Changes to recipe:  **libdeflater/1.22**
There are several improvements in 1.22.
https://github.com/ebiggers/libdeflate/compare/v1.21...v1.22
---
> libdeflate: add version 1.22

- recipes/freetype/config.yml
- recipes/freetype/meson/conandata.yml
- recipes/freetype/meson/conanfile.py
Changes to recipe:  **freetype/2.13.3**
"The B/W rasterizer has become much faster; besides that, it is a maintenance release."
https://sourceforge.net/projects/freetype/files/freetype2/2.13.3/
---
> freetype: add version 2.13.3

- recipes/mold/all/conandata.yml
- recipes/mold/all/conanfile.py
- recipes/mold/config.yml
Changes to recipe:  **mold/2.34.1**
There are new features since 2.33.0.
DEC Alpha is no longer supported in 2.34.0.
https://github.com/rui314/mold/compare/v2.33.0...v2.34.1
---
> mold: add version 2.34.1, remove older versions

- recipes/kplot/all/CMakeLists.txt
- recipes/kplot/all/conanfile.py
- recipes/kplot/all/test_package/test_package.c
Changes to recipe:  **kplot/[*]**
One of the few remaining recipes that does not use `import from conans ...` but is still not Conan 2.x compatible.
---
> kplot: add package_type, missing transitive_headers, simplify CMakeLists.txt

- recipes/opencolorio/all/conandata.yml
- recipes/opencolorio/all/patches/2.4.0-0001-fix-cmake-source-dir-and-targets.patch
- recipes/opencolorio/config.yml
Changes to recipe:  **opencolorio/2.4.0**
Brings a large set of updates in general and supports the new ACES 2.0 transforms.
Only minimal patches for the CMake needed as before. Same logic, just needed a new patch to work for changed CMake files.
https://github.com/AcademySoftwareFoundation/OpenColorIO/compare/v2.3.2...v2.4.0
---
> OpenColorIO: Add version 2.4.0

- recipes/fontconfig/all/conanfile.py
No longer used since v2.13.91:
- https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/500e77a01d00471900755d96ba6ad236d916947a
- https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/acc017e67210ee6d8fed7ffd41a1f55fe04d056b
No includes for `uuid/uuid.h` remain in the codebase: https://gitlab.freedesktop.org/search?group_id=1174&project_id=890&repository_ref=main&scope=blobs&search=uuid.h
---
> fontconfig: drop unnecessary util-linux-libuuid dependency

- recipes/openjph/all/conandata.yml
- recipes/openjph/all/conanfile.py
- recipes/openjph/config.yml
Changes to recipe:  **openjph/0.17.0**
There are several improvements in 0.17.0.
https://github.com/aous72/OpenJPH/compare/0.16.0...0.17.0
---
> openjph: add version 0.17.0

- recipes/watcher/all/conandata.yml
- recipes/watcher/config.yml
There are internal improvements in 0.12.0.
The c library named watcher-c is provided. I will create seperate recipe for it.
https://github.com/e-dant/watcher/compare/release/0.11.0...release/0.12.0
---
> watcher: add version 0.12.0

- recipes/openexr/3.x/conandata.yml
- recipes/openexr/config.yml
Changes to recipe:  **openexr/3.3.1**
Contains a few fixes for performance regression in the latest 3.3.1 release.
Besides a fix of performance regressions only contains some changes in documentation and small build system cleanups. None of those seem relevant for us according to the diff:
https://github.com/AcademySoftwareFoundation/openexr/compare/v3.3.0...v3.3.1
---
> openexr: Add version 3.3.1

- recipes/turtle/all/conandata.yml
- recipes/turtle/all/conanfile.py
- recipes/turtle/all/test_package/CMakeLists.txt
- recipes/turtle/config.yml
Changes to recipe:  **turtle/2.0.0**
turtle/2.0.0 requires C++14.
https://github.com/mat007/turtle/compare/v1.3.2...v2.0.0
---
> turtle: add new version 2.0.0

- recipes/glfw/all/conanfile.py
Changes to recipe:  **glfw/[*]**
To reduce overlinking of X11 libs (there's about 60 additional libs that xorg/system otherwise links against in addition to the 5 listed ones). GLFW is a quite common dependency as well.
---
> glfw: explicitly list xorg and wayland components

- recipes/ouster_sdk/all/conandata.yml
- recipes/ouster_sdk/all/conanfile.py
- recipes/ouster_sdk/config.yml
Adding new version of `ouster_sdk`: **ouster_sdk/0.13.0**
Ouster has released a new version of their C++ SDK for their lidars. I would like to have it in `conan-center`.
This is just a version bump, no recipe changes.
---
> ouster_sdk: add version 0.13.0

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Changes to recipe:  **cmake/3.30.5**
Make latest 3.30.x version CMake available inside conan eco system.
Add version CMake v3.30.5
For the checksums see https://github.com/Kitware/CMake/releases/download/v3.30.5/cmake-3.30.5-SHA-256.txt
---
> cmake: add version 3.30.5

- recipes/xerces-c/all/conanfile.py
Changes to recipe: xerces-c all
nsl is not a system library that is installed by default or found in all distros - so it shouldn't be listed as a system dependency without further safeguards.
However, nsl appears to be completely unused even when found by the build system (there are no evaluations of the `HAVE_LIBNSL` macro, and no uses of any headers in the `rpcsvc/*` folder. 
On systms where gcc is configured to pass `--as-needed` to the linker, the dependency is never encoded even if libnsl was found.
> xerces-c: fix handling of nsl library

- recipes/bitserializer/all/conanfile.py
Changes to recipe:  **bitserializer/0.50**, **bitserializer/0.65**, **bitserializer/0.70**
Broken recipe and prebuilt packages.
Due to how `package_id` is implemented, when `_is_header_only()` returns True, the package_id will be the same for both values of `with_rapidyaml`. In addition to that, it seems conan-center contains prebuild version of the package_id that was created with `with_rapidyaml=False`. In effect, it contains broken headers for builds with `with_rapidyaml=True`
This fix makes sure we always patch header related to rapidyaml (it is harmless if this functionality is disabled).
NOTE TO CONAN-CENTER MAINTAINERS: To properly complete the fix, the current prebuild packages in conan-center must be replaced with fresh versions build with updated conanfile.py.
Fixes #25516
---
> Fix: incorrect headers in prebuilt package

- recipes/freetype/meson/conandata.yml
- recipes/freetype/meson/patches/2.13.0-0002-meson-Fix-static-windows.patch
- recipes/freetype/meson/patches/2.13.3-0002-meson-Fix-static-windows.patch
backport patch from https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/341
Changes to recipe:  **freetype/2.13.***
Without this patch I'm getting link errors in my project.
Before patch meson has been injecting DLL_EXPORT compile definition to build process. With this define freetype uses "__declspec(dllexport)" even for static libraries.
---
> freetype: define DLL_EXPORT for shared library only

- recipes/libuv/all/conandata.yml
- recipes/libuv/config.yml
Changes to recipe:  **libuv/1.49.1**
There is important bugs in 1.49.1.
https://github.com/libuv/libuv/compare/v1.49.0...v1.49.1
---
> libuv: add version 1.49.1

- recipes/cutlass/all/conandata.yml
- recipes/cutlass/all/conanfile.py
- recipes/cutlass/config.yml
Changes to recipe:  **cutlass/3.5.1**
There are several improvements in 3.5.1.
Fix homepage url in conanfile.py
https://github.com/NVIDIA/cutlass/compare/v3.5.0...v3.5.1
---
> cutlass: add version 3.5.1, fix homepage url

- recipes/librdkafka/all/conandata.yml
- recipes/librdkafka/config.yml
Changes to recipe:  **librdkafka/2.6.0**
There are several improvements in 2.6.0.
https://github.com/confluentinc/librdkafka/compare/v2.5.3...v2.6.0
---
> librdkafka: add version 2.6.0

- recipes/s2n/all/conandata.yml
- recipes/s2n/all/conanfile.py
- recipes/s2n/config.yml
Changes to recipe:  **s2n/***
There are several improvements since 1.5.3.
https://github.com/aws/s2n-tls/compare/v1.5.3...v1.5.5
---
> s2n: add version 1.5.5, remove older versions

- recipes/au/all/conandata.yml
- recipes/au/all/conanfile.py
- recipes/au/all/patches/0001-v0.3.5-disable-gtest.patch
- recipes/au/all/test_package/CMakeLists.txt
- recipes/au/all/test_package/conanfile.py
- recipes/au/all/test_package/test_package.cpp
- recipes/au/config.yml
Changes to recipe:  **au/[0.3.5]**
Add recipe for https://github.com/aurora-opensource/au
This is an incomplete recipe, it only exposes the main `Au::au` target and not the `io` component (which is used for the `<<` operator).
I'm not sure why it is needed since it works anyway? Their CMake is a bit weird.
---
> Add au recipe

- recipes/hdf5/all/conandata.yml
- recipes/hdf5/all/conanfile.py
- recipes/hdf5/config.yml
Changes to recipe:  **hdf5/all**
Add v.1.14.5 and expose option to link against zlib-ng instead of zlib.
[HDF5 changelog](https://raw.githubusercontent.com/HDFGroup/hdf5/hdf5_1_14_5/release_docs/RELEASE.txt)
I've also opened the following PRs to bump the zlib-ng version used throughout cci. Let me know if you prefer instead to make hdf5 depend on v 2.1.6.
https://github.com/conan-io/conan-center-index/pull/25522 https://github.com/conan-io/conan-center-index/pull/25523 https://github.com/conan-io/conan-center-index/pull/25524
Build log for:
```bash
conan create recipes/hdf5/all --version 1.14.5 --name=hdf5 --build=missing -o '*/*:shared=True' -o 'hdf5/*:with_zlibng=True' -o 'hdf5/*:with_zlib=False'
```
<details>
<summary>LOG</summary>
``` …
```
> hdf5: add v1.14.5

- recipes/duckdb/all/conandata.yml
- recipes/duckdb/config.yml
Changes to recipe:  **duckdb/1.1.2**
There are lots of bug fixes in 1.1.2.
https://github.com/duckdb/duckdb/compare/v1.1.1...v1.1.2
---
> duckdb: add version 1.1.2

- recipes/commata/all/conandata.yml
- recipes/commata/config.yml
Changes to recipe:  **commata/1.0.1**
There are several bugfixes in 1.0.1.
https://github.com/furfurylic/commata/compare/v1.0.0...v1.0.1
---
> commata: add version 1.0.1

- recipes/octo-logger-cpp/all/conandata.yml
- recipes/octo-logger-cpp/all/conanfile.py
- recipes/octo-logger-cpp/config.yml
Changes to recipe:  **octo-logger-cpp/2.1.2**
There are several improvements since 2.0.2.
octo-logger-logger/2.x.x require aws-cpp-sdk/1.11.x.
https://github.com/ofiriluz/octo-logger-cpp/compare/v2.0.2...v2.1.2
---
> octo-logger-cpp: add version 2.1.2, update aws-sdk-cpp for 2.x.x

- recipes/xbyak/all/conandata.yml
- recipes/xbyak/config.yml
Changes to recipe:  **xbyak/7.20**
7.20 supports AVX-10.2.
https://github.com/herumi/xbyak/compare/v7.10...v7.20
---
> xbyak: add version 7.20

- recipes/stringzilla/all/conandata.yml
- recipes/stringzilla/config.yml
Changes to recipe:  **stringzilla/3.10.3**
There are several bugfixes since 3.10.0.
https://github.com/ashvardanian/StringZilla/compare/v3.10.0...v3.10.3
---
> stringzilla: add version 3.10.3

- recipes/pcapplusplus/cmake/conanfile.py
Changes to recipe:  **pcapplusplus/[>=23.09]**
The package fails to compile on non-msvc compiler when `cppstd` is not set to `gnuXX`.
The error looks like this:
```
pcapplusplus/23.09: Invalid: The cppstd GNU extension is required 
```
Example profile:
```
[settings]
arch=x86_64
os=Linux
compiler=gcc
compiler.version=11
compiler.cppstd=20
```
This PR simply removes the requirement for gnu extensions for any compiler.
---
> Fix compilation error on non-msvc compilers without gnu extensions enabled

- recipes/curlpp/all/conandata.yml
- recipes/curlpp/all/conanfile.py
- recipes/curlpp/all/patches/0001-disable-static-on-shared.patch
- recipes/curlpp/all/patches/0002-disable-cpp11.patch
- recipes/curlpp/all/patches/0003-replace-project-declaration.patch
- recipes/curlpp/all/test_package/CMakeLists.txt
- recipes/curlpp/all/test_package/conanfile.py
- recipes/curlpp/all/test_package/test_package.cpp
- recipes/curlpp/config.yml
Changes to recipe:  **curlpp/0.8.1.cci.20240530**
curlpp is required by [minio-cpp](https://github.com/minio/minio-cpp).
I want to add minio-cpp to cci.
https://github.com/jpbarrette/curlpp
---
> curlpp: add recipe

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/config.yml
Changes to recipe:  **simd/5.6.0**
There are several improvements in 5.6.0.
https://github.com/simdutf/simdutf/compare/v5.5.0...v5.6.0
---
> simdutf: add version 5.6.0, remove older versions

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Changes to recipe:  **simdjson/3.10.1**
Version bump
config.yml and conandata.yml point to the newly created simdjson/3.10.1.
---
> simdjson: add version 3.10.1

- recipes/bgfx/all/conanfile.py
Changes to recipe:  **bgfx/cci.20230216**
The latest version of MSVC 2022 presents as 194; there is no key to handle that number, resulting in a key error when building.
Add version 194 that maps to MSVC 2022
---
> bgfx: add msvc version 194

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Changes to recipe:  **cpp-httplib/0.18.1**
There are several improvements in 0.18.1.
https://github.com/yhirose/cpp-httplib/compare/v0.18.0...v0.18.1
---
> cpp-httplib: add version 0.18.1, remove older versions

- recipes/meson/all/conandata.yml
- recipes/meson/config.yml
Changes to recipe:  **meson/1.6.0**
There are several new features in 1.6.0.
https://github.com/mesonbuild/meson/compare/1.5.1...1.6.0#files_bucket
---
> meson: add version 1.6.0

- recipes/tree-sitter-c/all/CMakeLists.txt
- recipes/tree-sitter-c/all/conandata.yml
- recipes/tree-sitter-c/all/conanfile.py
- recipes/tree-sitter-c/all/test_package/CMakeLists.txt
- recipes/tree-sitter-c/all/test_package/test_package.c
- recipes/tree-sitter-c/config.yml
Changes to recipe:  **tree-sitter-c/0.23.1**
There are lots of improvements in 0.23.1 and 0.20.7.
0.20.7 is the latest official version.
https://github.com/tree-sitter/tree-sitter-c/compare/v0.20.3...v0.23.1
https://github.com/tree-sitter/tree-sitter-c/compare/v0.20.3...v0.20.7
---
> tree-sitter-c: add version 0.23.1, update tree-sitter

- recipes/rocksdb/all/conandata.yml
- recipes/rocksdb/config.yml
Changes to recipe:  **rocksdb/9.7.3**
There is a behavior change in 9.7.3.
https://github.com/facebook/rocksdb/compare/v9.7.2...v9.7.3
---
> rocksdb: add version 9.7.3

- recipes/crowcpp-crow/all/conanfile.py
Changes to recipe:  Add "wsock32", "ws2_32" to the package_info when on windows so that linking can function on windows.
Previously with msys2 clang, the above libraries were missing from the linker args.
---
> add socket system library to crowcpp's package

- recipes/botan/all/conandata.yml
- recipes/botan/config.yml
Changes to recipe:  **botan/3.6.0**
Version bump
See the release notes here: https://github.com/randombit/botan/blob/master/news.rst#version-360-2024-10-21
---
> Botan: add version 3.6.0

- recipes/botan/all/conandata.yml
- recipes/botan/config.yml
Changes to recipe:  **botan/2.19.5**
Bugfix release of botan's legacy 2.x branch. This update was missed when it got released back in July.
See the release notes: https://github.com/randombit/botan/blob/release-2/news.rst#version-2195-2024-07-08
Also note that Botan 2.x is currently scheduled to reach its end of life by the end of 2024.
---
> Botan: add version 2.19.5

- recipes/foxglove-websocket/all/conandata.yml
- recipes/foxglove-websocket/config.yml
Changes to recipe:  **foxglove-websocket/1.3.1**
Version bump
New version available: https://github.com/foxglove/ws-protocol/releases/tag/releases%2Fcpp%2Fv1.3.1
---
> foxglove-websocket: add version 1.3.1

- recipes/sqlite3mc/all/conandata.yml
- recipes/sqlite3mc/config.yml
**sqlite3mc version 1.9.0** includes an important bug fix for the SQLCipher cipher scheme.
An entry for version 1.9.0 was added to the recipe.
---
> Update to SQLite3 Multiple Ciphers 1.9.0

- .gitignore
`.conanrunner` is a folder created by the runner feature when using it to create packages from docker, and it's helpful if it's already ignored by git
Alongside it `conan_home` is my (maybe in the docs too?) convention for the value of `CONAN_HOME` env var or the `conan_home` variable in `.conanrc` (Files which for now will also be ignored), which is an useful feature when trying to isolate runner builds, for which creating a separate conan_home for the build is usually the best approach
> Add `.conanrunner` & `.conanrc` to gitignored ignored, alongside `conan_home`

- recipes/entt/3.x.x/conandata.yml
- recipes/entt/config.yml
Changes to recipe:  **entt/3.14.0**
- A new release (entt v3.14.0) has been published.
- Add recipe for entt v3.14.0
---
> entt: add version 3.14.0

- recipes/cgal/all/conandata.yml
- recipes/cgal/all/conanfile.py
- recipes/cgal/config.yml
Changes to recipe:  **cgal/6.0**
Resolves #25050.
New upstream release: CGAL version 6.0, https://github.com/CGAL/cgal/releases/tag/v6.0
CGAL 6.0 has a few breaking changes. The major one is that C++17 or later is now required (instead of C++14 for version 5.6).
Also: the PR https://github.com/CGAL/cgal/pull/7512 is merged in CGAL-6.0. That changes the creation of the file `lib/cmake/CGAL/conan-official-cgal-variables.cmake`, that is now simpler:
```cmake
include(${CMAKE_CURRENT_LIST_DIR}/CGAL_SetupCGALDependencies.cmake)
CGAL_setup_CGAL_flags(CGAL::CGAL)
set(CGAL_USE_GMP  TRUE CACHE INTERNAL "CGAL library is configured to use GMP")
set(CGAL_USE_MPFR TRUE CACHE INTERNAL "CGAL library is configured to use MPFR")
```
---
> cgal: add cgal/6.0

- recipes/rapidfuzz/all/conandata.yml
- recipes/rapidfuzz/config.yml
Changes to recipe:  **raipdfuzz/3.1.1**
There are several improvements since 3.0.4.
https://github.com/rapidfuzz/rapidfuzz-cpp/compare/v3.0.4...v3.1.1
---
> rapidfuzz: add version 3.1.1

- recipes/fast_float/all/conanfile.py
As seen in [this log](https://c3i.jfrog.io/c3i/misc-v2/logs/pr/25113/1-macos-m1-clang/fast_float/6.1.5//da39a3ee5e6b4b0d3255bfef95601890afd80709-test.txt), there is a warning for a nonexistent link directory:
```
ld: warning: directory not found for option '-L/Users/jenkins/workspace/prod-v2/bsr/82427/cdfca/p/fast_09661d46c7c97/p/lib'
```
[New log](https://c3i.jfrog.io/c3i/misc-v2/logs/pr/25729/1-macos-m1-clang/fast_float/1.1.2//da39a3ee5e6b4b0d3255bfef95601890afd80709-test.txt) no longer has that warning.
This is due to the extra component still having `libdirs` and `bindirs` set to the default.
Could probably also just remove that section after the 1.x freeze, I'm happy so long as the warning is silenced.
> Remove fast_float component dirs

- recipes/icu/all/conanfile.py
Changes to recipe:  **icu/all**
Honor `compiler.cppstd` from profile for msvc and icu >= 75.1
https://github.com/conan-io/conan-center-index/pull/24623 has added a logic forcing C++17 for msvc if icu version is >= 75.1, irrespective of compiler.cppstd in profile.
This PR adds a check for `compiler.cppstd`. If it's set, not need to force C++17 flag, since it's automatically injected by `AutootoolsToolchain` in `CXXFLAGS` with C++ standard from profile (potentially C++20 or C++23).
Moreover, this manual injection was done in `CXX` env var, it's not very neat, it's moved to `tc.extra_cxxflags`.
---
> icu: honor compiler.cppstd from profile when compiler is msvc

- recipes/trantor/all/conandata.yml
- recipes/trantor/config.yml
Changes to recipe:  **trantor/1.5.22**
There are several bugfixes in 1.5.22.
https://github.com/an-tao/trantor/compare/v1.5.21...v1.5.22
---
> trantor: add version 1.5.22

- recipes/daw_header_libraries/all/conandata.yml
- recipes/daw_header_libraries/config.yml
Changes to recipe:  **daw_header_libraries/2.114.0**
There are several improvements in 2.114.0.
https://github.com/beached/header_libraries/compare/v2.110.0...v2.114.0
---
> daw_header_libraries: add version 2.114.0

- recipes/vulkan-headers/all/conandata.yml
- recipes/vulkan-headers/config.yml
Changes to recipe:  **vulkan-headers/1.3.296.0**
Version bump
config.yml and conandata.yml point to the newly created vulkan-headers/1.3.296.0.
---
> vulkan-headers: Add version 1.3.296.0

- recipes/cgal/all/conandata.yml
- recipes/cgal/config.yml
Changes to recipe:  **cgal**. Add the last bug-fixes versions:
- **cgal/6.0.1**,
- **cgal/5.6.2**, and
- **cgal/5.5.5**.
Allows CGAL users to use the last bug-fix versions for a given release branch. See the annoucement at https://www.cgal.org/2024/10/23/CGAL-6.0/.
---
> add cgal/6.0.1, cgal/5.6.2, and cgal/5.5.5

- recipes/volk/all/conandata.yml
- recipes/volk/all/conanfile.py
- recipes/volk/config.yml
Changes to recipe:  **volk/1.3.296.0**
Version bump
https://github.com/zeux/volk/compare/vulkan-sdk-1.3.268...vulkan-sdk-1.3.296
config.yml and conandata.yml point to the newly created volk/1.3.296.0.
conanfile.py adapts changed include path discovery from this [commit](https://github.com/zeux/volk/commit/01b5e061d44af7cd29e25b5a0b62164ed79e7aeb)
---
> volk: Add version 1.3.296.0

- recipes/spirv-headers/all/conandata.yml
- recipes/spirv-headers/all/conanfile.py
- recipes/spirv-headers/config.yml
Changes to recipe:  **spirv-headers/1.3.296.0**
Version bump
https://github.com/KhronosGroup/SPIRV-Headers/compare/vulkan-sdk-1.3.268.0...vulkan-sdk-1.3.296.0
config.yml and conandata.yml point to the newly created spirv-headers/1.3.296.0.
conanfile.py additionaly disables building of a test project, option to disable this has been introduced in [commit](https://github.com/KhronosGroup/SPIRV-Headers/commit/3b11b02093a959bba57d960f6c28a12e56df9559), which was after 1.3.275.0 release
---
> spirv-headers: Add version 1.3.296.0

- recipes/opentelemetry-cpp/all/conanfile.py
grpc proto library is missing when using grpc exporters. This will cause build to fail.
Found in opentelemetry-cpp/1.14.2.
---
> opentelemetry-cpp/1.14.2: adding missing grpc proto library

- recipes/sentry-native/all/conandata.yml
- recipes/sentry-native/config.yml
Changes to recipe: **sentry-native**
- Remove 0.7.5 and 0.7.6 versions according to https://github.com/conan-io/conan-center-index/blob/5b58888878c588cc2803c11b0845a3ee89dfd237/docs/adding_packages/sources_and_patches.md#removing-old-versions
---
> [sentry-native] Remove old versions

- recipes/libsodium/all/conandata.yml
- recipes/libsodium/config.yml
Changes to recipe:  **libsodium/1.0.20**
fork from [qchateau](https://github.com/conan-io/conan-center-index/commit/ebc1900d197d229a168cd02e37bc481e3c93bb47)
mainly addressing compilation issues
---
> libsodium: add version 1.0.20

- recipes/libssh2/all/conandata.yml
- recipes/libssh2/all/conanfile.py
- recipes/libssh2/config.yml
Changes to recipe: libssh2/1.11.1
There are several bugfixes since 1.11.0 including a fix for [terrapin attack](https://terrapin-attack.com/).
https://github.com/libssh2/libssh2/compare/libssh2-1.11.0...libssh2-1.11.1
---
> libssh2: add version 1.11.1

- recipes/liburing/all/conandata.yml
- recipes/liburing/all/conanfile.py
- recipes/liburing/config.yml
Changes to recipe:  **liburing/2.8**
There are several new features in 2.8.
Adding license list to MIT.
https://github.com/axboe/liburing/compare/liburing-2.7...liburing-2.8
LICENSE is described in README.
> All software contained within this repo is dual licensed LGPL and MIT, see
> COPYING and LICENSE, except for a header coming from the kernel which is
> dual licensed GPL with a Linux-syscall-note exception and MIT, see
COPYING.GPL and <https://spdx.org/licenses/Linux-syscall-note.html>.
https://github.com/axboe/liburing/
---
> liburing: add version 2.8

- recipes/dpp/all/conandata.yml
- recipes/dpp/all/conanfile.py
- recipes/dpp/all/test_package/CMakeLists.txt
- recipes/dpp/all/test_package/conanfile.py
- recipes/dpp/all/test_package/test_package.cpp
- recipes/dpp/config.yml
Adds new recipe  **dpp/10.0.34**
This library does not exist in Conan yet.
Adds the initial build for dpp 10.0.34. I am the lead developer of the library in the recipe.
Installs from a zip of the release.
---
> new package: dpp 10.0.34

- recipes/log4cplus/all/conandata.yml
- recipes/log4cplus/all/conanfile.py
- recipes/log4cplus/all/patches/2.1.2-0001-fix-cmake.patch
- recipes/log4cplus/config.yml
Changes to recipe:  **log4cplus/2.1.2**
There are several new features in 2.1.2.
2.1.2 drops Visual Studio 2017 support.
https://github.com/log4cplus/log4cplus/compare/REL_2_1_1...REL_2_1_2
---
> log4cplus: add version 2.1.2, add package_type

- .gitignore
All recipes define this in their layout (Guess who almost just commits the whole src of a library!)
> Add src folder to .gitignore

- recipes/cli11/all/conanfile.py
- recipes/cli11/all/test_package/CMakeLists.txt
CLI11 supports static library builds. This PR changes the recipe to build a static library by default and adds a header only option.
Fixes #25737.
---
> cli11: Compile by default, add header_only option

- recipes/jsoncons/all/conandata.yml
- recipes/jsoncons/config.yml
Changes to recipe:  **jsoncons/0.178.0**
There are several new features in 0.178.0.
https://github.com/danielaparker/jsoncons/compare/v0.177.0...v0.178.0
---
> jsoncons: add version 0.178.0

- recipes/botan/all/conandata.yml
- recipes/botan/config.yml
Changes to recipe:  **botan/3.6.1**
https://github.com/randombit/botan/blob/master/news.rst#version-361-2024-10-26
When creating a signature using the SLH-DSA algorithm, Botan 3.6.0 did not default to the 'Hedged' mode, but to 'Deterministic'.
Due to a bug in the detection of the CPU's capabilities, 3.6.0 could crash when invoking specific algorithms on certain platforms.
---
> Botan: add version 3.6.1

- recipes/games101-cgl/all/conandata.yml
- recipes/games101-cgl/all/conanfile.py
- recipes/games101-cgl/all/test_package/CMakeLists.txt
- recipes/games101-cgl/all/test_package/conanfile.py
- recipes/games101-cgl/all/test_package/test_package.cpp
- recipes/games101-cgl/all/test_v1_package/CMakeLists.txt
- recipes/games101-cgl/all/test_v1_package/conanfile.py
- recipes/games101-cgl/config.yml
New recipe:  **games101-cgl/0.1.0**
Resolves #24581 
games101-cgl is a wrapper library used in homework 8 of [GAMES101](https://sites.cs.ucsb.edu/~lingqi/teaching/games101.html) which is the most popular computer graphics course in China. However, the installation of dependencies of this library is too complicated, so it is difficult for novices to complete the homeowork correctly. By adding this recipe to conan, novices can directly use conan to complete the installation of the library.
---
> games101-cgl: new recipe

- recipes/opencolorio/all/conanfile.py
Changes to recipe:  **opencolorio/all**
To prepare OpenImageIO 3.0.0.0 which is currently in beta and added libjxl support, to support both opencolorio & libjxl requirements at the same time, the lcms version needs to match.
(I have a branch for OpenImageIO 3.0.0.0 which currently uses the beta but will be published as an MR once the release has happened. https://github.com/conan-io/conan-center-index/pull/25672 is created to start discussion and try if everything else builds in all CI combinations already)
OpenImageIO with the addition of libjxl currently results in a graph error due to libjxl requireing *lcms/2.16* while opencolorio requires *lcms/2.14*
The only user of OpenColorIO in CCI is OpenImageIO so the side effect should hopefully be small.
---
> opencolorio: Bump lcms requirement to 2.16

- recipes/opencolorio/all/conanfile.py
Reverts conan-io/conan-center-index#25660
This was not meant to be merged until https://github.com/conan-io/conan-center-index/pull/25672 is ready, as it creates a conflict with its whole tree
> Revert "opencolorio: Bump lcms requirement to 2.16"

- recipes/msgpack-cxx/all/conandata.yml
- recipes/msgpack-cxx/config.yml
Changes to recipe:  **msgpack-cxx/7.0.0**
There is a breaking change in 7.0.0.
https://github.com/msgpack/msgpack-c/compare/cpp-6.1.1...cpp-7.0.0
---
> msgpack-cxx: add version 7.0.0

- recipes/openimageio/all/conandata.yml
- recipes/openimageio/all/patches/2.5.17.0-cmake-targets.patch
- recipes/openimageio/config.yml
Changes to recipe:  **openimageio/2.5.17.0**
Release contains several bugfixes
https://github.com/AcademySoftwareFoundation/OpenImageIO/releases/tag/v2.5.17.0
Patch is derived from previous (2.5.14.0) patch. Due to small changes in externalpackages.cmake it needed to be adapted with an upgraded patch.
---
> OpenImageIO: Add version 2.5.17.0

- recipes/trompeloeil/all/conandata.yml
- recipes/trompeloeil/all/test_package/test_package.cpp
- recipes/trompeloeil/config.yml
Changes to recipe:  **trompeloeil/49**
This is the 10 years anniversary release.
https://github.com/rollbear/trompeloeil/compare/v48...v49
---
> trompeloeil: add version 49

- recipes/libgit2/all/conandata.yml
- recipes/libgit2/config.yml
Changes to recipe:  **libgit2/1.8.2**
Making `libgit2/1.8.4` available on Conan Center.
Very minimal changes necessary to update the version.
---
> Updated libgit2 to 1.8.4

- recipes/prometheus-cpp/all/conandata.yml
- recipes/prometheus-cpp/all/conanfile.py
- recipes/prometheus-cpp/config.yml
Changes to recipe:  **prometheus-cpp/1.3.0**
There are several improvements in 1.3.0.
https://github.com/jupp0r/prometheus-cpp/compare/v1.2.4...v1.3.0
---
> prometheus-cpp: add version 1.3.0

- recipes/libdwarf/all/conanfile.py
Changes to recipe:  **libdwarf/all**
#24849 updated mongo-c-driver to use a version range for zstd which causes it to conflict with libdwarf
---
> Bump zstd for libdwarf

- recipes/efsw/all/conanfile.py
- recipes/efsw/all/test_package/conanfile.py
Changes to recipe:  **efsw/1.4.0**
The PR #25448 introduced the new recipe for efsw. However, it missed my review. 
- The upstream enforces fPIC always, overriding the recipe option: https://github.com/SpartanJ/efsw/blob/1.4.0/CMakeLists.txt#L5
- The upstream generates a second static library that's packaged, but not listed in cpp_info: 
- https://github.com/SpartanJ/efsw/blob/1.4.0/CMakeLists.txt#L27
- https://c3i.jfrog.io/artifactory/cci-build-logs/cci/prod/PR-25448/11/package_build_logs/build_log_efsw_1_4_0_6542073374ca622afe046e6c97ae7645_13be611585c95453f1cbbd053cea04b3e64470ca.success.txt
- Explicit is no longer required as the require requires Conan 2.x. Using implements feature.
---
> [efsw] Honor fPIC and require Conan 2.x features

- recipes/certify/all/conanfile.py
Changes to recipe:  **certify/***
Reduce the number of boost dependencies in the public interface
---
> certify: Reduce boost dependencies

- recipes/libpcap/all/conanfile.py
Changes to recipe:  **libpcap/1.10.4**
Fixing: #25700 
Previously, libpcap (on Android) defaulted to pcap-null.c, preventing live packet capture. Now correctly uses pcap-linux.c, enabling capture.
Results:
Before:
```
Available interfaces:
nflog - Linux netfilter log (NFLOG) interface
nfqueue - Linux netfilter queue (NFQUEUE) interface 
Error creating handle: live packet capture not supported on this system
```
After (this PR):
Recipe for testing created with:
```
~/projects/conan-center-index/recipes/libpcap$ conan create --user=nikita --channel=dev --profile:host=~/projects/redacted/profiles/android_api21_arm64-v8a.jinja --settings:host=build_type=RelWithDebInfo --build=missing --version=1.10.4 all/
```
```
Available interfaces:
eth0:LL - No description
eth0 - No description
any - …
```
> [libpcap] fix: #25700 - enable proper packet capture on Android using pcap-linux.c

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/config.yml
Changes to recipe:  **mongo-c-driver/1.28.1**
There are several bug fixes in 1.28.1.
Try to close https://github.com/conan-io/conan-center-index/issues/25577.
https://github.com/mongodb/mongo-c-driver/compare/1.28.0...1.28.1
---
> mongo-c-driver: add version 1.28.1

- recipes/box2d/all/conanfile.py
Changes to recipe:  **box2d/3.0.0**
This (hopefully) closes https://github.com/conan-io/conan-center-index/issues/25797
Box2D compiles on Linux, Windows, and macOS, but not for WebAssembly using emsdk. This PR attempts to address the compilation error I’m encountering and should not impact other users.
---
> box2d: Do not force warnings as errors by default

- recipes/cppfront/all/conandata.yml
- recipes/cppfront/all/conanfile.py
- recipes/cppfront/all/test_package/conanfile.py
- recipes/cppfront/config.yml
Changes to recipe:  **cppfront/0.8.0**
There are already official releases.
Try to close https://github.com/conan-io/conan-center-index/issues/25787.
---
> cppfront: add version 0.8.0, remove cci snapshots

- recipes/dpp/all/conandata.yml
- recipes/dpp/all/conanfile.py
- recipes/dpp/config.yml
Changes to recipe: **dpp/10.0.35**
This is an automatic update from our CI which adds the new version 10.0.35 of D++
[Release announcement for D++ v10.0.35](https://github.com/brainboxdotcc/DPP/releases/tag/v10.0.35)
> dpp: add version 10.0.35

- recipes/sail/all/conanfile.py
Changes to recipe:  **sail/\***
Enable JPEGXL as it's now available in Conan. 0.8.2 version is used as 0.10.x fails to compile. The issue needs to be fixed on the SAIL side later.
Should close https://github.com/conan-io/conan-center-index/pull/25575
---
> sail: Enable jpegxl

- recipes/spirv-cross/all/conandata.yml
- recipes/spirv-cross/config.yml
Changes to recipe:  **spirv-cross/1.3.296.0**
Version bump
https://github.com/KhronosGroup/SPIRV-Cross/compare/vulkan-sdk-1.3.268.0...vulkan-sdk-1.3.296.0
config.yml and conandata.yml point to the newly created spirv-cross/1.3.296.0.
---
> Add spirv-cross/1.3.296.0

- recipes/libmount/all/conandata.yml
- recipes/libmount/config.yml
Changes to recipe:  libmount, add version 2.40.2 and stop publishing revisions for 2.33.1
> libmount: add 2.40.2

- recipes/boost/all/conanfile.py
Added "s390x" to the  _b2_address_model function to return "64".
Changes to recipe:  **lib/all**
Boost library fails to build on IBM Z and IBM LinuxONE processors due to recipe defaulting to 32-bits architecture due to the following function: 
```
def _b2_address_model(self):
if self.settings.arch in ("x86_64", "ppc64", "ppc64le", "mips64", "armv8", "armv8.3", "sparcv9"):
return "64"
return "32"
```
Added "s390x" to the architecture tuple returning "64": 
```
def _b2_address_model(self):
if self.settings.arch in ("x86_64", "ppc64", "ppc64le", "mips64", "armv8", "armv8.3", "sparcv9", "s390x"):
return "64"
return "32"
```
---
> Boost: correct address model for "s390x" architecture

- README.md
Update documentation regarding remote.
> Update documentation for remote

- recipes/glu/all/conanfile.py
Changes to recipe:  **glu/system**
Same rational as https://github.com/conan-io/conan-center-index/pull/25399
closes https://github.com/conan-io/conan-center-index/issues/25391
---
> glu avoid unecessary call to package manager for irrelevant host OS

- recipes/level-zero/all/conandata.yml
- recipes/level-zero/all/conanfile.py
- recipes/level-zero/all/patches/1.17.39/001-patch-remove-qspectre.patch
- recipes/level-zero/all/test_package/CMakeLists.txt
- recipes/level-zero/all/test_package/conanfile.py
- recipes/level-zero/all/test_package/test_package.cpp
- recipes/level-zero/config.yml
Changes to recipe:  **level-zero/1.17.28**
Openvino recipe needs level-zero to support execution on Intel NPU devices
this library also might be used by libfabric
---
> [level-zero] added new recipe

- recipes/symengine/all/conanfile.py
**symengine/0.13.0**
Compiler version check was checking the version of the package rather than the compiler.
Fix check.
---
> symengine: fix compiler version check

- recipes/boost/all/conanfile.py
Changes to recipe:  **boost/1.86.0**
Fix https://github.com/conan-io/conan-center-index/issues/25864.
We can see the relevant part of the build definition for boost 1.86.0 [here](https://github.com/boostorg/stacktrace/blob/boost-1.86.0/build/Jamfile.v2#L148).  The token `$(arch:G=)` will evaluate to `x86` in two conan recipe scenarios:
* settings.arch = "x86"
* settings.arch = "x86_64"
We also see an existing helper property `_b2_architecture` in the conan recipe [here](https://github.com/conan-io/conan-center-index/blob/f7a9ac9570e8f7d6fe806e1ca9b9be5dbdf828a5/recipes/boost/all/conanfile.py#L1206).
Therefore this change seems reasonable.
VS 2019 16.11.41
```
[settings]
arch=x86
compiler=msvc
compiler.runtime_type=Debug
compiler.version=192 …
```
> Fix boost 1.86.0 recipe for x86 arch

- recipes/openjph/all/conandata.yml
- recipes/openjph/config.yml
Changes to recipe:  **openjph/0.18** (add), **openjph/0.15** (remove)
- Contains improvements for lossless compression
- Fixes a bug on some x86 platforms when compiled with Clang and run on non-avx systems.
https://github.com/aous72/OpenJPH/releases/tag/0.18.0
---
> openjph: Add 0.18.0, remove 0.15.0

- recipes/opentelemetry-cpp/all/conanfile.py
Changes to recipe:  **opentelemetry/1.14.2**
fixes #25869
gRPC/1.65.0 is affected by a change in absl logging that produces unwanted log output to stdout.
grpc dependency is bumped from 1.65.0 to 1.67.1
---
> opentelemetry-cpp: bump grpc to fix unwanted absl log output

- recipes/opentelemetry-proto/all/conandata.yml
- recipes/opentelemetry-proto/config.yml
Changes to recipe:  **opentelemetry-proto**
These versions are dependencies for opentelemetry-cpp package, namely:
- opentelemetry-cpp/1.17.0 requires opentelemetry-proto/1.3.2 [(Release v1.17.0)](https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.17.0)
- opentelemetry-cpp/1.16.0 requires opentelemetry-proto/1.3.1 [(Release v1.16.0)](https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.16.0)
https://github.com/open-telemetry/opentelemetry-proto/compare/v1.3.1...v1.3.2
https://github.com/open-telemetry/opentelemetry-proto/compare/v1.3.0...v1.3.1
---
> opentelemetry-proto: add version 1.3.1, 1.3.2

- recipes/imagemagick/all/conanfile.py
- recipes/libraw/all/conanfile.py
- recipes/libvips/all/conanfile.py
- recipes/opencolorio/all/conanfile.py
- recipes/pdfium/all/conanfile.py
- recipes/poppler/all/conanfile.py
Align version of dependency on `lcms` across the entire repository to `lcms/2.16`. The aim is to avoid conflicts.
This affects the following recipes:
* imagemagick
* libraw
* libvips
* opencolorio
* pdfium
* poppler
Note that the following have not yet been migrated to Conan 2 - so this PR will not run checks for those
* `imagemagic/7.0.11-4`
* `poppler/20.09.0` and `poppler/21.07.0`
> Align lcms version across repository

- docs/package_templates/cmake_package/config.yml
Missing config.yml for CMake Conan recipe templates. 
---
> [docs] Add missing config.yml for CMake templates

- docs/package_templates/autotools_package/all/conanfile.py
`self.settings_build` is always defined in Conan 2.x.
A small follow-up to #25849.
/cc @uilianries 
---
> [docs] Remove _settings_build from the autotools template

- recipes/expat/all/conandata.yml
- recipes/expat/config.yml
A CVE has been fixed in this version
https://github.com/libexpat/libexpat/blob/R_2_6_4/expat/Changes
Changes to recipe:  **expat/2.6.4**
CVE mitigation
---
> [expxat] Add expat version 2.6.4

- recipes/cryptopp/all/conandata.yml
- recipes/cryptopp/all/conanfile.py
- recipes/cryptopp/all/test_package/test_package.cpp
- recipes/cryptopp/config.yml
This option is present in Crypto++'s CMakeList.txt but was not exposed in the conanfile.py. Adding exposure for it.
Changes to recipe:  **cryptopp/\***
This is an option that allows enabling OpenMP for the cryptographic algorithms in Crypto++. It will speed up some and slow down other algorithms.
Default is `False` since it can have a negative performance impact on some algorithms. But it will speed up others, so it should be up to the caller.
---
> cryptopp: Add use_openmp option

- recipes/leptonica/all/conandata.yml
- recipes/leptonica/all/conanfile.py
- recipes/leptonica/config.yml
Changes to recipe:  **leptonica/1.85.0**
There are several new features in 1.85.0.
https://github.com/DanBloomberg/leptonica/compare/1.83.1...1.85.0
---
> leptonica: add new version 1.85.0

- recipes/tree-sitter-cql/all/CMakeLists.txt
- recipes/tree-sitter-cql/all/conandata.yml
- recipes/tree-sitter-cql/all/conanfile.py
- recipes/tree-sitter-cql/all/test_package/CMakeLists.txt
- recipes/tree-sitter-cql/all/test_package/conanfile.py
- recipes/tree-sitter-cql/all/test_package/test_package.c
- recipes/tree-sitter-cql/config.yml
Changes to recipe:  **tree-sitter-cql/***
CQL(Cassandra Query Language) parser on tree-sitter.
https://github.com/shotover/tree-sitter-cql/tree/main/src
---
> tree-sitter-cql: add recipe

- recipes/freeimage/all/conandata.yml
Changes to recipe:  **freeimage/[3.18.0]**
See  #25929
self-explanatory
cc @jcar87
---
> freeimage: substitute whitespace in URL with urlencoded equivalent

- recipes/tesseract/all/conandata.yml
- recipes/tesseract/all/patches/0005-disable-install-pdb-5.4.1.patch
- recipes/tesseract/all/patches/0005-disable-install-pdb-5.5.0.patch
- recipes/tesseract/config.yml
Changes to recipe:  **tesseract/5.4.1,5.5.0**
Fix wrong url of 5.4.1 (Sorry. It's my mistake)
There are several improvements in 5.5.0.
https://github.com/tesseract-ocr/tesseract/compare/5.4.1...5.5.0
---
> tesseract: add version 5.5.0, fix url of 5.4.1

- docs/package_templates/autotools_package/all/conanfile.py
- docs/package_templates/cmake_package/all/conanfile.py
- docs/package_templates/meson_package/all/conanfile.py
- docs/package_templates/msbuild_package/all/conanfile.py
The `auto_shared_fpic` works only when `configure()` or `config_options()` are not declared in the recipe. Otherwise, each method should manage the shared/fPIC as usual.
The `auto_shared_fpic` will act by replacing `configure()` or `config_options()`. In case one of them is defined, it will replace what is missing with the fPIC removal logic. 
I also updated the template for msbuild, as it's focused on Visual Studio, I removed fPIC option as well. 
Reference:
- https://docs.conan.io/2/reference/conanfile/methods/configure.html#auto-shared-fpic
- https://docs.conan.io/2/reference/conanfile/methods/config_options.html#auto-shared-fpic
---
> [docs] Fix auto_shared_fpic usage in CCI recipe templates

- recipes/libalsa/all/conandata.yml
- recipes/libalsa/config.yml
Changes to recipe:  **libalsa/1.2.13**
There are several improvements in 1.2.13.
https://github.com/alsa-project/alsa-lib/compare/v1.2.12...v1.2.13
---
> libalsa: add version 1.2.13

- recipes/libftp/all/conandata.yml
- recipes/libftp/all/conanfile.py
- recipes/libftp/config.yml
Changes to recipe:  **libftp/***
There are a new features and several improvements since 1.1.0.
Make static-library package type on msvc instead of validation check.
https://github.com/deniskovalchuk/libftp/compare/v1.1.0...v1.3.0
---
> libftp: add version 1.3.0

- recipes/libqasm/all/conandata.yml
- recipes/libqasm/config.yml
Changes to recipe:  **libqasm/0.6.9**
config.yml and conandata.yml point to the newly created libqasm/0.6.9.
---
> libqasm: add version 0.6.9

- recipes/reproc/all/conandata.yml
- recipes/reproc/all/conanfile.py
- recipes/reproc/all/test_package/CMakeLists.txt
- recipes/reproc/all/test_package/conanfile.py
- recipes/reproc/all/test_package/test_package.c
- recipes/reproc/all/test_package/test_package.cpp
- recipes/reproc/config.yml
Adds  **reproc/14.2.5**
https://github.com/DaanDeMeyer/reproc
reproc (Redirected Process) is a cross-platform C/C++ library that simplifies starting, stopping and communicating with external programs. The main use case is executing command line applications directly from C or C++ code and retrieving their output.
[![Packaging status](https://repology.org/badge/tiny-repos/reproc.svg)](https://repology.org/project/reproc/versions)
This project exports two CMake config files (`reproc` and `reproc++`) but due to a Conan limitation the recipe exports just a single `reproc` one.
- Closes: https://github.com/conan-io/conan-center-index/issues/978
- Closes: https://github.com/conan-io/conan-center-index/issues/25531
---
> reproc: new recipe

- recipes/aws-sdk-cpp/all/conanfile.py
`validate_build()` is defined twice, causing the first one to be ignored.
> aws-sdk-cpp: fix an ignored validate_build()

- recipes/fswatch/all/CMakeLists.txt
- recipes/fswatch/all/conandata.yml
- recipes/fswatch/all/conanfile.py
- recipes/fswatch/all/test_package/CMakeLists.txt
- recipes/fswatch/all/test_package/conanfile.py
- recipes/fswatch/all/test_package/test_package.cpp
- recipes/fswatch/config.yml
Add [fswatch](https://github.com/emcrisostomo/fswatch) package.
Make fswatch available to the community.
While the latest release version is 1.17.1, there is a documented [known issue](https://github.com/emcrisostomo/fswatch/issues/291#issuecomment-1230541663) which leads to the version 1.17.1-36 
---
> fswatch: add package

- recipes/flac/all/conanfile.py
Changes to recipe:  **flac/all**
Currently Flac can't be built for iOS, disabling this option fixes that
When building for iOS, Flac fails at cmake configuration step with an error:
```
CMake Error at src/flac/CMakeLists.txt:23 (install):
install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
target "flacapp".
CMake Error at src/metaflac/CMakeLists.txt:16 (install):
install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
target "metaflac".
```
The PR disables building supplemental programs for Apple non-macOS.
---
> Flac: don't build programs for Apple non-macOS

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/config.yml
Changes to recipe:  **simdutf/5.6.2**
There are several improvements in 5.6.2.
https://github.com/simdutf/simdutf/releases/tag/v5.6.2
https://github.com/simdutf/simdutf/compare/v5.6.0...v5.6.2
---
> simdutf: add version 5.6.2

- recipes/msys2/all/conanfile.py
base-devel 2024.11 does not contain pkgconf any more [1], and the attempt to remove it will resulting in "error: no targets specified (use -h for help)".
[1] https://github.com/msys2/MSYS2-packages/commit/ad465ec8df5813c26505568595658a2303cd3e45
Resolves #25970.
---
> msys2: Check if package exists before removing it

- recipes/boost/all/conanfile.py
Changes to recipe:  **boost/1.86.0**
iOS does not support subprocesses (all apps have to be a single process), so the operating system APIs this library depends on do not exist on iOS.
fixes #25628
Set `without_process` by default on iOS, but only on Boost 1.86+ (the process library is header-only before this version).
Sadly, it is not possible to do iOS builds of Boost in Conan 2 right now, because ios-cmake isn't building (see #21532). I have locally tested:
- a normal macOS (Xcode 15) build on conan 2.9.1
- an iOS build on conan 1.65.0
---
> (#25628) [boost] Disable process library on iOS

- recipes/openimageio/all/conanfile.py
Specify library name and version:  **openimageio/all**
---
> openimageio: use libpng version range

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Changes to recipe:  **glaze/4.0.1,3.6.2**
There is a major version up (4.0.1).
There are several improvements in 3.6.2
https://github.com/stephenberry/glaze/compare/v3.6.1...v3.6.2
https://github.com/stephenberry/glaze/compare/v3.6.2...v4.0.1
---
> glaze: add version 4.0.1, 3.6.2

- recipes/xmlsec/all/conandata.yml
- recipes/xmlsec/config.yml
Changes to recipe:  **xmlsec/1.3.6**
There are several improvements since 1.3.4.
https://github.com/lsh123/xmlsec/compare/xmlsec_1_3_4...1.3.6
---
> xmlsec: add version 1.3.6

- recipes/frugen/all/conandata.yml
- recipes/frugen/all/conanfile.py
- recipes/frugen/all/patches/0001-cmake-use-find_package-to-locate-json-c-library.patch
- recipes/frugen/all/patches/0002-libfru-fix-build-on-MacOS.patch
- recipes/frugen/all/patches/0003-let-conan-choose-optimization-flags.patch
- recipes/frugen/all/test_package/CMakeLists.txt
- recipes/frugen/all/test_package/conanfile.py
- recipes/frugen/all/test_package/test_package.c
- recipes/frugen/config.yml
New recipe:  **frugen/2.0**
Frugen is a small but useful tool to work with IPMI FRU data widely used in telecom industry to encode hardware inventory information.
This adds a new recipe. The recipe mostly focus on `libfru` which is part of frugen and can be used in other projects to encode/decode FRU information but also deploys `frugen` tool itself. 
Includes patch to support macOS: https://codeberg.org/IPMITool/frugen/pulls/8
---
**tested with Conan version 2.7.1**
> frugen: new recipe for frugen and libfru v2.0

- recipes/sdl_mixer/cmake/conanfile.py
Changes to recipe:  **sdl_mixer/2.8.0**
Fixes linker error in iOS project that consumes sdl_mixer
AudioUnit framework is available only for macOS, on iOS you'd receive
```
ld: framework 'AudioUnit' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
---
> sdl_mixer: link AudioUnit only on macOS

- recipes/libheif/all/conandata.yml
- recipes/libheif/config.yml
Changes to recipe:  **libheif/1.19.5**
There are several bugfixes since 1.19.0.
https://github.com/strukturag/libheif/releases/tag/v1.19.5
https://github.com/strukturag/libheif/compare/v1.19.0...v1.19.5
---
> libheif: add version 1.19.5

- recipes/thorvg/all/conandata.yml
- recipes/thorvg/config.yml
Added recipe:  **thorvg/0.15.4**
Removed older patches.
There are several improvements and bugfixes in 0.15.4.
https://github.com/thorvg/thorvg/releases/tag/v0.15.4
https://github.com/thorvg/thorvg/compare/v0.15.3...v0.15.4
---
> thorvg: add version 0.15.4 and removed older versions

- recipes/tree-sitter-c/all/conandata.yml
- recipes/tree-sitter-c/all/conanfile.py
- recipes/tree-sitter-c/all/patches/0.23.2-0001-disable-gencode-fpic.patch
- recipes/tree-sitter-c/all/test_package/CMakeLists.txt
- recipes/tree-sitter-c/all/test_package/test_package.c
- recipes/tree-sitter-c/config.yml
Changes to recipe:  **tree-sitter-c/0.23.2**
upstream added official CMakeLists.txt.
https://github.com/tree-sitter/tree-sitter-c/compare/v0.23.1...v0.23.2
---
> tree-sitter-c: add version 0.23.2

- recipes/libsvtav1/all/conandata.yml
- recipes/libsvtav1/all/conanfile.py
- recipes/libsvtav1/config.yml
Changes to recipe:  **libsvtav1/2.2.1**
There are several new features since 2.1.2.
https://gitlab.com/AOMediaCodec/SVT-AV1/-/compare/v2.1.2...v2.2.1
---
> libsvtav1: add new version 2.2.1

- recipes/orc/all/conandata.yml
- recipes/orc/all/conanfile.py
- recipes/orc/config.yml
Changes to recipe:  **orc/2.0.3**
Sync recent releases from Apache ORC.
Add several news releases from Apache ORC 2.0.x, 1.9.x and 1.8.x major versions.
---
> orc: add version 2.0.3 (and other stable releases)

- recipes/android-ndk/all/conandata.yml
- recipes/android-ndk/config.yml
Changes to recipe:  **android-ndk/r27c**
Adds the latest available NDK version
The update is highly desired because CMake projects declaring minimum version < 3.3 can't be built using r27 due to https://github.com/android/ndk/issues/2032 which was fixed in r27b
---
> add Android NDK r27c

- recipes/rabbitmq-c/all/conandata.yml
- recipes/rabbitmq-c/config.yml
Changes to recipe:  **rabbitmq-c/0.15.0**
There are several improvements in 0.15.0.
https://github.com/alanxz/rabbitmq-c/releases/tag/v0.15.0
https://github.com/alanxz/rabbitmq-c/compare/v0.14.0...v0.15.0
---
> rabbitmq-c: add version 0.15.0

- recipes/libsndfile/all/conanfile.py
- recipes/libsndio/all/conanfile.py
Changes to recipe:  **libsndfile/1.2.2**
The FFMPEG is being affected by the PR https://github.com/conan-io/conan-center-index/pull/23150, where not libsndio is always required now, but uses ALSA always as well. 
First, libsndio only work on Windows, so it makes FFMPEG not possible to be used in Windows. Second, consuming ALSA by default creates a conflict when consuming FFMPEG as well:
```
ERROR: There are invalid packages:
libsndio/1.9.0: Invalid: libsndio/1.9.0 requires libalsa to be built as a shared library
```
The libsndfile has no exported option for sndio, but it's optional:
- https://github.com/libsndfile/libsndfile/blob/v1.0.30/CMakeLists.txt#L82
- https://github.com/libsndfile/libsndfile/blob/v1.0.30/CMakeLists.txt#L466
The libsdnio only has the version 1.9.0 maintained in …
> [libsndfile] Make libsndio optional to avoid ffmpeg breakage

- recipes/simdutf/all/conandata.yml
- recipes/simdutf/config.yml
Changes to recipe:  **simdutf/5.6.3**
There is an improvements in 5.6.3.
https://github.com/simdutf/simdutf/releases/tag/v5.6.3
https://github.com/simdutf/simdutf/compare/v5.6.2...v5.6.3
---
> simdutf: add version 5.6.3

- recipes/sdl/all/conanfile.py
Changes to recipe:  **sdl/all**
- fixes building Android shared library
- exposes SDL_HIDAPI setting
Even though SDL is a C library, on Android it starts requiring C++ only when you build the HIDAPI subsystem, see here: https://github.com/libsdl-org/SDL/blob/bbc9c75618fbc60583123e03f31f4e856f2654bf/cmake/sdlchecks.cmake#L1105-L1106
Without the fix cmake picks the default C++ library from NDK toolchain which is static. This is an issue when your profile requests shared C++ library and could be a source of strange behavior later, like we faced in our project: https://github.com/vcmi/vcmi/issues/4973
---
> SDL: fix Android shared library and expose HIDAPI setting

- recipes/libwebm/all/conanfile.py
Header files of libweb include others without 'webm' path prefix. So if I include any header or libwebm with INCLUDE_PATH to 'include' dir only, it can not resolve other libwebm headers.
In my case it fails to compile on macos
Changes to recipe:  **libwebm/1.0.0.31**
Compilation error on macos due to insufficient include path
Headers of libweb include others without webm prefix, which is required with current cpp_info.includedirs set
---
- [v] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [v] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [v] Tested locally with at least one configuration using a recent version of Conan
> libwebm: add webm directory to include path

- recipes/json_struct/all/conandata.yml
- recipes/json_struct/all/conanfile.py
- recipes/json_struct/all/test_package/CMakeLists.txt
- recipes/json_struct/all/test_package/conanfile.py
- recipes/json_struct/all/test_package/main.cpp
- recipes/json_struct/config.yml
Add recipe:  **json_struct/1.0.1**
Adding the json_struct header only library
json_struct is a single header only library that parses JSON to C++ structs/classes and serializing structs/classes to JSON.
---
- [x ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [x ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [x ] Tested locally with at least one configuration using a recent version of Conan
> json_struct receipt

- recipes/tree-sitter-sql/all/conandata.yml
- recipes/tree-sitter-sql/all/conanfile.py
- recipes/tree-sitter-sql/all/patches/0.3.7-0001-fix-cmake.patch
- recipes/tree-sitter-sql/all/test_package/CMakeLists.txt
- recipes/tree-sitter-sql/all/test_package/test_package.c
- recipes/tree-sitter-sql/config.yml
Changes to recipe:  **tree-sitter-sql/0.3.7**
There are several improvements in 0.3.7.
https://github.com/DerekStride/tree-sitter-sql/releases/tag/v0.3.7
https://github.com/DerekStride/tree-sitter-sql/compare/v0.3.5...v0.3.7
---
> tree-sitter-sql: add version 0.3.7

- recipes/open62541/all/conanfile.py
I have tried locally and fixes the not found headers error when using encryption=mbedtls
Closes: https://github.com/conan-io/conan-center-index/issues/23930
> Fix: Add MBEDTLS to variable prefixes for mbedtls to enable building with encryption=mbedtls

- recipes/librdkafka/all/conandata.yml
- recipes/librdkafka/config.yml
Changes to recipe:  **librdkafka/2.6.1**
There are several improvements in 2.6.1.
https://github.com/confluentinc/librdkafka/releases/tag/v2.6.1
https://github.com/confluentinc/librdkafka/compare/v2.6.0...v2.6.1
---
> librdkafka: add version 2.6.1

- recipes/zoe/all/conandata.yml
- recipes/zoe/config.yml
Changes to recipe:  **zoe/3.6**
- disable SHA1
- support macOS without patch
https://github.com/winsoft666/zoe/compare/v3.3...v3.6
---
> zoe: add version 3.6

- recipes/opentelemetry-proto/all/conandata.yml
- recipes/opentelemetry-proto/config.yml
Changes to recipe:  **opentelemetry-proto/1.4.0**
There are several improvements in 1.4.0.
https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v1.4.0
https://github.com/open-telemetry/opentelemetry-proto/compare/v1.3.2...v1.4.0
---
> opentelemetry-proto: add version 1.4.0

- recipes/libx264/all/conanfile.py
In [this PR](https://github.com/conan-io/conan-center-index/pull/24587), self._settings_build was introduced, but not defined. I'm not certain how it passed CI, but this should be self.settings_build.
Fixes #26098
> libx264: Fix use of self_settings_build

- recipes/emsdk/all/conandata.yml
- recipes/emsdk/config.yml
Changes to recipe:  **emsdk/3.1.38**
Version 3.1.38 was added because it is used in the current Unity game engine: https://docs.unity3d.com/6000.0/Documentation/Manual/webgl-native-plugins-with-emscripten.html
Additional version was added.
---
> emsdk: add version used for unity 6

- recipes/mingw-w64/linux/conanfile.py
Changes to recipe:  **mingw-w64/8.0.2**
Fix #25719 reported by @pkoshevoy
When building mingw-w64 crt (C Runtime Library), it should use the gcc already built in the same Conan package, one step before. However, when having mingw-w64 installed in the system already, the PATH may find the system's compiler instead. In order to fix it, the PATH should updated to look fist in package folder.
Full build log based on the commit a0498ea: [mingw-w64-8.0.2-gcc9-var-path.log](https://github.com/user-attachments/files/18024584/mingw-w64-8.0.2-gcc9-var-path.log)
The was built using Docker ubuntu:20.04 and with mingw installed in Linux.
---
> [mingw-w64] Prioritize PATH to always use package apps first

- recipes/mingw-builds/all/conandata.yml
- recipes/mingw-builds/config.yml
Changes to recipe:  **mingw-builds/14.2.0**
I've been using it this last few days locally and works as expected, and is been useful to debug some gcc 14 related issues (See https://github.com/conan-io/conan-center-index/issues/26034)
Some extra cleanup can be made, but that would regenerate revisions for the old versions, no need to do that unless another valid change would be needed
> mingw-builds: Add 14.2.0

- recipes/abseil/all/conandata.yml
- recipes/abseil/all/patches/0006-backport-arm-compilation-fix.patch
Changes to recipe:  **abseil/[*]**
There is a single file in the abseil build that is built with both x86_64 and armv8. When using LLVM clang (this is *not* an issue on Apple-Clang), some versions fail with this error:
```
clang++: error: unsupported option '-msse4.1' for target 'arm64-apple-darwin23.6.0'
make[2]: *** [absl/random/CMakeFiles/random_internal_randen_hwaes_impl.dir/internal/randen_hwaes.cc.o] Error 1
make[1]: *** [absl/random/CMakeFiles/random_internal_randen_hwaes_impl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
Backport the upstream fix - this is only a fix in the build system to work as intended.
Close https://github.com/conan-io/conan-center-index/issues/25992
Close https://github.com/conan-io/conan-center-index/issues/25747
> abseil: Fix build on macOS when using LLVM clang

- recipes/libzip/all/conanfile.py
Changes to recipe:  **libzip/[<1.11]**
On gcc 14, `-Wincompatible-pointer-types` has now become an error by default
To account for this, newer upstream versions suppress that warning altogether https://github.com/nih-at/libzip/issues/440#issuecomment-2185616767
This PR passes the warning suppression as a flag for older versions.
See https://github.com/conan-io/conan-center-index/issues/26034 for additional details
The recipe could get a cleanup, but I'm going for a minimal fix for this diff, another PR will follow once this gets merged
> libzip: backport warning suppression for gcc >= 14

- recipes/libssh2/all/conanfile.py
Changes to recipe:  **libssh2/[*]**
Closes https://github.com/conan-io/conan-center-index/issues/26062
The CMake dependency was incorrecty added on a previous PR for old versions
> libssh2: Fix cmake dependency for old versions

- recipes/rusty-cpp/all/conandata.yml
- recipes/rusty-cpp/all/conanfile.py
- recipes/rusty-cpp/all/test_package/CMakeLists.txt
- recipes/rusty-cpp/all/test_package/conanfile.py
- recipes/rusty-cpp/all/test_package/test_package.cpp
- recipes/rusty-cpp/config.yml
Changes to recipe:  **rusty-cpp**
This is a library I find handy to use, and others may find it useful, too.
It is currently header-only. If I make it non-header-only in the future, should I modify the existing `conanfile.py`, or should I create a new folder and write a new `conanfile.py` there?
> rusty-cpp: new recipe

- recipes/cspice/all/conandata.yml
Changes to recipe:  **cspice/0067**
The current cspice recipe rejects building on Linux armv8 as it cannot find the correct source package to download, however it is possible to build cspice for Linux armv8 even if it is not officially released on the platform by NASA, and is even packaged for Linux armv8 by conda-forge.
The patches to build for Apple Silicon macOS (essentially removal of `-m64`) are the same for Linux armv8 and appear to what conda-forge uses for their Linux armv8 cspice package.
https://naif.jpl.nasa.gov/pipermail/spice_discussion/2021-April/000466.html
This adds the Linux armv8 to the sources data via the Apple Silicon macOS tarball from NASA.
This was tested using a Linux virtual machine running on an M1 Pro Mac.
---
> cspice: Add Linux armv8 support for N0067

- recipes/p7zip/all/conanfile.py
- recipes/p7zip/all/test_package/conanfile.py
Changes to recipe:  **p7zip/[*]**
This PR ensures we can generate binaries for the library in Conan 2. This is a minimal diff that almost exclusively targets the test_package (except for a change in the recipe's package_type to force an export)
Closes https://github.com/conan-io/conan-center-index/issues/25059 which complained about Conan 2 not having packages for the recipe
* Use a regular requires in the test_package and test as such
* Add missing package_type
Incidentally, this fixes the issue of missing binaries as it will generate a new revision and publish the necessary binaries.
> p7zip: fix test package

- recipes/opencv/4.x/conanfile.py
Changes to recipe:  **OpenCV/4.x** (all 4.x versions), there was typo in requires for "cudaoptflow" this pull request fixes it.
Packaging recipe compiled with `cudaoptflow=True` fails due to `cudaimgproc` not being found.
Compilation of OpenCV 4.x library with cuda and cudaoptiacal flow is, but error is thrown during processing `package_info`, due to `cudaimgproc` not being found.
Not really to explain, just a simple typo: in requires for `cudaoptflow` instead of requiring `opencv_cudaimgproc` recipe uses `cudaimgproc` with is not known to conan.
---
> OpenCV/4.x: fix cudaoptflow requires

- recipes/enchant/all/conandata.yml
- recipes/enchant/all/conanfile.py
Changes to recipe:  **enchant/2.3.2**
The current source URL (https://github.com/AbiWord/enchant/releases/download/v2.3.2/enchant-2.3.2.tar.gz) no longer works. The source distribution archives appear to have been moved to https://github.com/rrthomas/enchant/releases, which the home page points to as well.
---
> enchant: fix changed source URL

- recipes/libzip/all/conanfile.py
Succesful compilation logs:
```
$ conan create . --version=1.11.2 -b=missing -o="&:crypto=gnutls"
libzip/1.11.2: Exporting package recipe: /Users/abril/coding/conan-center-index/recipes/libzip/all/conanfile.py
libzip/1.11.2: exports: File 'conandata.yml' found. Exporting it...
libzip/1.11.2: Calling export_sources()
libzip/1.11.2: Copied 1 '.py' file: conanfile.py
libzip/1.11.2: Copied 1 '.yml' file: conandata.yml
libzip/1.11.2: Copied 2 '.patch' files: 1.7.3-0001-cmake-install-bundle.patch, 1.11.2-0002-remove-rpath.patch
libzip/1.11.2: Exported to cache folder: /Users/abril/.conan2/p/libzic7c4caa36301c/e
libzip/1.11.2: Exported: libzip/1.11.2#99bad9f93eca0800c372d7e723c1bcb4 (2024-12-09 11:21:55 UTC) …
```
> libzip: Add gnutls support & cleanup recipe

- recipes/openimageio/all/test_package/conanfile.py
Changes to recipe:  **openimageio**
Testing the following issue https://github.com/conan-io/conan-center-index/issues/10327
I found the `conanfile.py` test_package has an incorrect logic introduced in during the recipe migration to conan v2, see https://github.com/conan-io/conan-center-index/pull/19950/files#diff-af6917236b5b08ff903a94d288a0226a9d6b7159b086a3694de1da36c6b42749R23
Changed logic in `test_package` for `not can_run` to `can_run`.
Minor improvements have been made. 
---
> openimageio: Fixed test_package bug

- recipes/scnlib/all/conanfile.py
Changes to recipe:  **scnlib/[*]**
As reported in https://github.com/conan-io/conan-center-index/issues/26224, scnlib compiles just fine for gcc 11 for newer versions, the recipe was never updated to reflect this
Linux logs for gcc 11:
<details>
```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Running in container: "conan create /root/conanrunner/all --version=3.0.2 -b=missing -pr:h=docker_example_host -pr:b=docker_example_build -f json > create.json" |
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘ …
```
> scnlib: 3.0.2 onwards works for gcc 11

- recipes/foxglove-websocket/all/conandata.yml
- recipes/foxglove-websocket/config.yml
Changes to recipe:  **foxglove-websocket/1.4.0**
Version bump
See https://github.com/foxglove/ws-protocol/releases/tag/releases%2Fcpp%2Fv1.4.0
---
> foxglove-websocket: add version 1.4.0

- recipes/sdl/all/conanfile.py
Changes to recipe:  **sdl/all**
Same logic behind disabling iconv for macOS applies to all Apple platforms actually
---
> SDL: disable iconv dependency on all Apple platforms by default

- recipes/xnnpack/all/conanfile.py
Co-authored-by: @czoido
Changes to recipe:  **xnnpack <= cci.20220801**
Fixes https://github.com/conan-io/conan-center-index/issues/10327
Current conflict: 
By securely bumping `cpuinfo` in `xnnpack` on versions <= `cci.20220801`, the conflict will be fixed.
**Note**: apart from `onnxruntime`, only `tensorflow-lite` depends on `xnnpack`, but it would not be affected as it depends on a new version, see https://github.com/conan-io/conan-center-index/blob/97ba1699a4e855e32573f93fb0572e284f36b624/recipes/tensorflow-lite/all/conanfile.py?plain=1#L93 
Little refactors have been made.
---
> xnnpack: bump cpuinfo dep fixing version conflict with onnxruntime

- docs/package_templates/cmake_package/all/test_package/config.yml
Remove a `cmake_package/all/test_package/config.yml` accidentally added in #25849.
@uilianries
> package_templates: remove a misplaced config.yml

- recipes/libssh/all/conandata.yml
- recipes/libssh/all/patches/0.11.1-0001-fix-cmake.patch
- recipes/libssh/config.yml
Add version 0.11.1 of libssh
We are using this version of libssh and as the change is pretty minor, I thought it could be useful to add it here.
I simply added the new version of the library and checked which patches very still required.
I tested it with two different crypto options (gcrypt and mbedtls) and conan 2.11 on Linux.
---
> [libssh] Add version 0.11.1

- recipes/libcap/all/conandata.yml
- recipes/libcap/all/patches/2.73/0001-libcap-Remove-hardcoded-fPIC.patch
- recipes/libcap/all/patches/2.73/0002-Make.Rules-Make-compile-tools-configurable.patch
- recipes/libcap/config.yml
Changes to recipe:  **libcap/2.73**
A new version of libcap is available. Full diff between 2.70 and 2.73: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/diff/?id=libcap-2.73&id2=libcap-2.70
Conan-specific patches are the same as for the previous versions. They are only rebased on version 2.73.
---
> libcap/2.73: Bump version

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/config.yml
add mongo-c-driver/1.29.1
close: https://github.com/conan-io/conan-center-index/issues/26166
New tag: https://github.com/mongodb/mongo-c-driver/releases/tag/1.29.1
Compared to the previous version: https://github.com/mongodb/mongo-c-driver/compare/1.29.0...1.29.1
> add mongo 1.29.1

- recipes/libjpeg-turbo/all/conandata.yml
- recipes/libjpeg-turbo/config.yml
Changes to recipe:  **libjpeg-turbo/all**
https://github.com/libjpeg-turbo/libjpeg-turbo/compare/3.0.4...3.1.0
---
> libjpeg-turbo: add version 3.1.0

- recipes/asmjit/all/conandata.yml
- recipes/asmjit/all/conanfile.py
- recipes/asmjit/config.yml
Changes to recipe:  **asmjit/cci.20241216**
To update blend2d, we need to update asmjit.
blend2d/0.11.5 on arm requires latest asmjit due to changing namespace of `Inst`.
https://github.com/asmjit/asmjit/commit/514a89f4c47b22328285e445c3298a377b9ce02a
https://github.com/blend2d/blend2d/commit/292c9d339b56ef54edf1879084c3794425f9db45
---
> asmjit: add version cci.20241216 (for blend2d)

- recipes/opencolorio/all/conandata.yml
- recipes/opencolorio/config.yml
Changes to recipe:  **opencolorio/2.4.1**
Patch level so a number of fixes and internal optimization that have been introduced since 2.4.0.
https://github.com/AcademySoftwareFoundation/OpenColorIO/releases/tag/v2.4.1
---
> OpenColorIO: Add version 2.4.1

- recipes/md4c/all/conanfile.py
Changes to recipe:  **md4c/all**
Fixes building for Apple non-macOS
Building the package with default options for iOS produces the following CMake configuration error:
```
CMake Error at md2html/CMakeLists.txt:14 (install):
install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
target "md2html".
```
As executable for Apple non-macOS doesn't really make any sense, it's disabled and the corresponding option is deleted. Basically same fix as #25964
Also, the option `BUILD_MD2HTML_EXECUTABLE` appeared only in v0.5.0 (see https://github.com/mity/md4c/commit/ecce1715b771b8784e2b7174223570f149693a48), this is now checked.
---
> md4c: fix building for Apple non-macOS

- recipes/pcapplusplus/all/conanfile.py
Changes to recipe:  **pcapplusplus/[>=21.05 <=22.11]**
Fix https://github.com/conan-io/conan-center-index/issues/26269 by disabling `<WholeProgramOptimization>`  to prevent error when the consumer is using a different compiler version (but still compatible)
Add `iphlpapi` to system libraries on Windows: - fixes issue:
```
Pcap++.lib(PcapLiveDeviceList.obj) : error LNK2019: unresolved external symbol __imp_GetNetworkParams referenced in function "private: void __cdecl pcpp::PcapLiv 
eDeviceList::setDnsServers(void)" (?setDnsServers@PcapLiveDeviceList@pcpp@@AEAAXXZ) [Z:\sources\conan-center-index\recipes\pcapplusplus\all\test_package\build\ms 
vc-194-x86_64-14-release\test_package.vcxproj]
```
---
> pcapplusplus: Fix iphlpap linkage and WholeProgramOptimization

- recipes/cuda-api-wrappers/all/conandata.yml
- recipes/cuda-api-wrappers/all/conanfile.py
- recipes/cuda-api-wrappers/all/test_package/CMakeLists.txt
- recipes/cuda-api-wrappers/config.yml
Changes to recipe:  **cuda-api-wrappers**
* [previous PR](https://github.com/conan-io/conan-center-index/pull/25029) for one the last version was ignored for months
* New version of the library have been released
* Mistype in the CMakeLists.txt for the test package
* Updated the recipe with versions [0.7.1](https://github.com/eyalroz/cuda-api-wrappers/releases/v0.7.1) and [0.8.0](https://github.com/eyalroz/cuda-api-wrappers/releases/v0.7.1) 
* fixed a mistype in the test package CMakeLists.txt.
---
> Updated cuda-api-wrappers with versions 0.7.1 and 0.8.0

- recipes/cyclonedds-cxx/all/conanfile.py
- recipes/cyclonedds/all/conanfile.py
Fix #26288
cyclonedds:
* Disable LTO which makes the binaries extra sensitive to the exact compiler version
cyclonedds-cxx:
* Properly expose with_shm: this controls the conditional dependency
* Ensure in `validate()` that when it is enabled, it is also enabled in `cyclonedds`
* Via cmakedeps, use the name expected by the cmake build scripts
> cyclonedds-cxx: properly handle shm support

- recipes/fmt/all/conandata.yml
- recipes/fmt/all/conanfile.py
- recipes/fmt/config.yml
Changes to recipe:  **fmt/11.1.1**
There are several improvements since 11.0.2.
https://github.com/fmtlib/fmt/compare/11.0.2...11.1.1
* Define `cmake_config_version_compat` to `AnyNewerVersion` to mirror what upstream does (proper fix for https://github.com/conan-io/conan-center-index/pull/17545)
* Propagate `FMT_UNICODE=0` macro when unicode is disabled (mirror what upstream does) - https://github.com/conan-io/conan-center-index/issues/26267
* Remove "dead" code in Conan 2 (legacy cpp_info properties)
Close https://github.com/conan-io/conan-center-index/issues/26267
---
> fmt: add version 11.1.1, fix unicode and cmake version handling

- recipes/mbedtls/all/conanfile.py
When the recipe started defining the `MBEDTLS_PLATFORM_SNPRINTF_MACRO` as a build-time macro, it causes a mismatch for some versions of the recipe - where consumers who don't define this macro with the same value, end up falling back with its default value (as set by upstream) - resulting in undefined references because different symbols are expected - this was experienced here:
* https://github.com/conan-io/conan-center-index/pull/25623/checks?check_run_id=32491832397 ([logs](https://c3i.jfrog.io/artifactory/cci-build-logs/cci/prod/PR-25623/3/package_build_logs/test_log_lief_0_15_1_947d4157b396ee3cc726a8c556d10689_547d30ce0e93556d841360172fd5bdac4ffd1893.txt))
* https://github.com/conan-io/conan-center-index/pull/25623#discussion_r1841907794
Version 3.6.0 and newer should handle this …
> mbedtls: propagate snprintf macro in package_info, only for current versions

- recipes/boost/all/conandata.yml
Boost sources are now available from archive.boost.io 
The recipe was still working fine since it falls back to the second URL otherwise (sourceforge) - but this reflects the new URLs.
> boost: get sources from archives.boost.io

- recipes/jsoncons/all/conandata.yml
- recipes/jsoncons/config.yml
Changes to recipe:  **jsoncons/1.0.0**
https://github.com/danielaparker/jsoncons/releases/tag/v1.0.0
https://github.com/danielaparker/jsoncons/compare/v0.178.0...v1.0.0
---
> jsoncons: add version 1.0.0

- recipes/bitserializer/all/conandata.yml
- recipes/bitserializer/config.yml
Changes to recipe:  **bitserializer/0.75**
New version of BitSerializer 0.75 has been released ([Release notes](https://github.com/PavelKisliak/BitSerializer/releases/tag/v0.75)). I am author of library.
Add new version of library to recipe
---
> [bitserializer] Add new version 0.75

- recipes/openimageio/all/conandata.yml
- recipes/openimageio/all/patches/2.5.18.0-cmake-targets.patch
- recipes/openimageio/config.yml
Changes to recipe:  **openimageio/2.5.18.0**
Monthly bugfix release with several fixes and small improvements.
https://github.com/AcademySoftwareFoundation/OpenImageIO/releases/tag/v2.5.18.0
Conan compatibility patch needed to be updated - content is the same but due to changes upstream the lines didn't match.
---
> openimageio: Add version 2.5.18.0

- recipes/zxing-cpp/all/conandata.yml
- recipes/zxing-cpp/all/conanfile.py
- recipes/zxing-cpp/config.yml
Changes to recipe:  **zxing-cpp/2.3.0**
I'm the maintainer of this library and just released a new version.
I'm not a conan user myself and hence, I did not test anything related to this conan packaging.
---
> zxing-cpp: add version 2.3.0

- recipes/unordered_dense/all/conandata.yml
- recipes/unordered_dense/config.yml
Changes to recipe:  **unordered_dense/4.5.0**
There are several improvements in 4.5.0.
https://github.com/martinus/unordered_dense/releases/tag/v4.5.0
https://github.com/martinus/unordered_dense/compare/v4.4.0...v4.5.0
---
> unordered_dense: add new version 4.5.0

- recipes/luau/all/conandata.yml
- recipes/luau/config.yml
Changes to recipe:  **luau/0.655**
There are several improvements since 0.650.
https://github.com/luau-lang/luau/releases/tag/0.655
https://github.com/luau-lang/luau/compare/0.650...0.655
---
> luau: add version 0.655

- recipes/reflect-cpp/all/conandata.yml
- recipes/reflect-cpp/all/conanfile.py
- recipes/reflect-cpp/config.yml
Changes to recipe:  **reflect-cpp/0.17.0**
reflect-cpp 0.17.0 was recently released. This updates the Conan package.
- reflect-cpp 0.17.0 added support for Cap'n Proto, so I added this as an option. 
- reflect-cpp 0.17.0 switched to jsoncons as the package for CBOR, so I updated the dependencies accordingly, while maintaining backward compatibility.
---
> reflect-cpp: Added new version 0.17.0

- recipes/mongo-c-driver/all/conandata.yml
- recipes/mongo-c-driver/config.yml
Changes to recipe:  **mongo-c-driver/1.29.2**
Requested in https://github.com/conan-io/conan-center-index/issues/26321
Changelog: https://github.com/mongodb/mongo-c-driver/compare/1.29.1...1.29.2
This new version aims to solve compilation issues on Windows arm64
Fix https://github.com/conan-io/conan-center-index/issues/26321
---
> mongo-c-driver: add version 1.29.2

- recipes/libpng/all/conandata.yml
- recipes/libpng/config.yml
Changes to recipe:  **libpng/1.6.45**
https://github.com/pnggroup/libpng/compare/v1.6.44...v1.6.45
---
> libpng: add version 1.6.45

- recipes/openexr/3.x/conanfile.py
Changes to recipe:  **openexr/3.x**
Recently, libtiff was changed to use version range: https://github.com/conan-io/conan-center-index/commit/04911c61af10b04a3f85b4ba7c3ee740d32c3aab
This now results into version conflicts downstream, namely for OpenImageIO: https://github.com/conan-io/conan-center-index/pull/25672
The changeset of libdeflate between 1.19 and 1.22 looks innocent enough with only internal changes and bugfixes & optimizations based on the changelog and openexr still builds well with 1.22.
---
> openexr: Suggest libdeflate version range

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/config.yml
Changes to recipe:  **simdjson/3.11.5**
Version bump
https://github.com/simdjson/simdjson/compare/v3.11.2...v3.11.5
config.yml and conandata.yml point to the newly created simdjson/3.11.5
---
> simdjson: Add version 3.11.5

- recipes/gdal/pre_3.5.0/conanfile.py
- recipes/hictk/all/conanfile.py
- recipes/uwebsockets/all/conanfile.py
Changes to recipe:  **libtiff/all**
libdeflate < v1.20 can't be built for iOS with apple-clang 15, upstream added a workaround only in v1.20, see https://github.com/ebiggers/libdeflate/issues/354
Now using the latest available version of libdeflate
---
> multiple recipes: align dependency on libdeflate

- recipes/libdeflate/all/conandata.yml
- recipes/libdeflate/config.yml
Changes to recipe:  **libdeflate/1.23**
When looking into #26364 I just saw that a new version of libdeflate with some bugfixes was released in December.
* https://github.com/ebiggers/libdeflate/blob/master/NEWS.md
* https://github.com/ebiggers/libdeflate/compare/v1.22...v1.23
---
> libdeflate: Add version 1.23

- recipes/bshoshany-thread-pool/all/conandata.yml
- recipes/bshoshany-thread-pool/all/conanfile.py
- recipes/bshoshany-thread-pool/config.yml
Changes to recipe:  **bshoshany-thread-pool/5.0.0**
Updated to v5.0.0.
Starting with this version, the library is also available as a C++20 module. I tried to find if Conan supports modules, but could not find anything other than a blog post saying you're working on it. Currently, in addition to copying the header file `include/BS_thread_pool.hpp` (which can still be included as a normal header file if C++20 modules are not available) to `os.path.join(self.package_folder, "include")`, the recipe also copies the module file, `modules/BS.thread_pool.cppm`, to `os.path.join(self.package_folder, "modules")`. Does that make sense, or would the user not have access to that folder? Any help would be appreciated.
---
> bshoshany-thread-pool: add version 5.0.0

- recipes/mpg123/all/conanfile.py
fixes #26380 I found if building process is in msvc environment, mpg123 never use msys2, but these lines aways add the msys2 requirement if os is windows, could we only add the requirement if that's not msvc environment?
please refer to:
https://github.com/conan-io/conan-center-index/blob/master/recipes/mpg123/all/conanfile.py#L103-L105
Changes to recipe:  **mpg123/1.31.2**
if building process is in msvc environment, mpg123 never use msys2, but these lines aways add the msys2 requirement if os is windows.
I found if building process is in msvc environment, mpg123 never use msys2, but these lines aways add the msys2 requirement if os is windows, could we only add the requirement if that's not msvc environment?
please refer to:
https://github.com/conan-io/conan-center-index/blob/master/recip …
> mpg123: dont require msys2 when using msvc, fix macos crossbuild

- recipes/libsersi/all/conandata.yml
- recipes/libsersi/all/conanfile.py
- recipes/libsersi/all/test_package/CMakeLists.txt
- recipes/libsersi/all/test_package/conanfile.py
- recipes/libsersi/all/test_package/test_package.cpp
- recipes/libsersi/config.yml
- recipes/opendis6/all/conandata.yml
Changes to recipe:  **libsersi/[*]**/**opendis/[*]**
Upstream renamed, with the new CI system this is now actually not an issue
See https://github.com/conan-io/conan-center-index/pull/24487 for details
(Also https://github.com/conan-io/conan-center-index/pull/24601 for the old CI system workaround, this PR combines both)
The idea is that after the current opendis6 revision is published, we can stop publishing new revisions for it by removing from the Git repository (But note that we won't remove the already-published binaries for Opendis6 at any point)
> libsersi: Deprecate opendis6 in favour of libsersi

- recipes/sqlite3mc/all/conandata.yml
- recipes/sqlite3mc/config.yml
**sqlite3mc version 2.0.2** supports the latest _SQLite_ version **3.48.0**, adds the new cipher scheme _AEGIS_, and includes several bug fixes.
An entry for version 2.0.2 was added to the recipe.
---
> Update to SQLite3 Multiple Ciphers 2.0.2

- recipes/uwebsockets/all/conandata.yml
- recipes/uwebsockets/config.yml
Changes to recipe:  **uwebsockets/20.71.0**
There are several improvements in 20.71.0.
Retry https://github.com/conan-io/conan-center-index/pull/26345.
https://github.com/uNetworking/uWebSockets/releases/tag/v20.71.0
https://github.com/uNetworking/uWebSockets/compare/v20.70.0...v20.71.0
---
> uwebsockets: add version 20.71.0 (retry)

- recipes/nlopt/all/conandata.yml
- recipes/nlopt/all/conanfile.py
- recipes/nlopt/config.yml
Changes to recipe:  **nlopt/[2.8.0 2.9.0 2.9.1]**
Follow library versions
Starting from 2.8.0, the patch used in the recipe is not valid anymore.
The related lines were removed in commit 3106ca560ac6 of nlopt repository.
I think that the "fPIC" option in `recipes/nlopt/all/conanfile.py: 25` should be removed, but as I'm not sure I leave it untouched.
---
> nlopt: add version 2.9.1

- recipes/librdkafka/all/conandata.yml
- recipes/librdkafka/config.yml
Changes to recipe:  **librdkafka/2.8.0**
There are several fixes in 2.8.0.
https://github.com/confluentinc/librdkafka/releases/tag/v2.8.0
https://github.com/confluentinc/librdkafka/compare/v2.6.1...v2.8.0
---
> librdkafka: add version 2.8.0

- recipes/pango/all/conanfile.py
Changes to recipe:  **pango/***
closes https://github.com/conan-io/conan-center-index/issues/26410
---
> [pango] Fix cairo not in dependency graph error when with_cairo=False option

- recipes/sdl_ttf/all/conandata.yml
- recipes/sdl_ttf/all/conanfile.py
- recipes/sdl_ttf/config.yml
Changes to recipe:  **sdl_ttf/2.24.0**
new library version
---
> sdl_ttf: add v2.24.0

- recipes/libzip/all/conandata.yml
- recipes/libzip/all/patches/1.11.3-0002-remove-rpath.patch
- recipes/libzip/config.yml
Changes to recipe:  **lib/1.11.3**
Bugfix release, addressing among others:
- https://github.com/nih-at/libzip/issues/253
- https://github.com/nih-at/libzip/issues/478
- https://github.com/nih-at/libzip/issues/474
The 0001 patch has not been needed for [~ 4 years](https://github.com/nih-at/libzip/commit/e7bfb68e99905991cee97793d49d2acbc00829fa) and has been removed for this version. I left previous versions unchanged, though it should be fine to remove it from all versions down to (included) 1.9.0.
The 0002 patch needed a change to the line numbers.
---
> Add libzip 1.11.3

- recipes/pcl/all/conandata.yml
- recipes/pcl/all/patches/1.13.1-0006-Compatibility-with-clang-19.patch
Changes to recipe:  **pcl/1.13.1**
pcl recipe does not compile with clang-19
This is a patch from the master branch of pcl, to be able to compile pcl with clang-19
fix the following error when building with clang-19:
```
In file included from /conan/.conan2/p/b/pclb478583a31512/b/src/surface/include/pcl/surface/3rdparty/poisson4/sparse_matrix.h:185:
/conan/.conan2/p/b/pclb478583a31512/b/src/surface/include/pcl/surface/3rdparty/poisson4/sparse_matrix.hpp:231:20: error: no member named 'm_N' in 'SparseMatrix<T>'
231 |       Resize(this->m_N, this->m_M);
|              ~~~~  ^
/conan/.conan2/p/b/pclb478583a31512/b/src/surface/include/pcl/surface/3rdparty/poisson4/sparse_matrix.hpp:231:31: error: no member named 'm_M' in 'SparseMatrix<T>'
231 |       Resize(this->m_N, this->m_M);
| …
```
> pcl: add a patch for compiling with clang-19

- recipes/flecs/all/conandata.yml
- recipes/flecs/config.yml
Changes to recipes:  **flecs/4.0.4**
Last modification to flecs recipe is 4.0.0.
This PR add the version 4.0.4, which is the latest stable version for flecs, as of today.
Previous PR:
https://github.com/conan-io/conan-center-index/pull/24621
Add URL for flecs 4.0.4.
Based on the latest update by @NukeBird.
---
> flecs: add 4.0.4

- recipes/libiconv/all/conanfile.py
Changes to recipe:  libiconv/all
Fix autodetection of `windres` by autotools - let autotools pick up the correct executable, OR let the executable be defined by either RC (env var) or `rc` conan configuration - rather than hardcode a name.
Close https://github.com/conan-io/conan-center-index/issues/26445
Fix the following issue when working with a mingw toolchain *on Linux*, where the executable has a different name
```
libtool: compile:  windres --target=pe-x86-64 -DPACKAGE_VERSION_STRING=\\\"1.17\\\" -DPACKAGE_VERSION_MAJOR=1 -DPACKAGE_VERSION_MINOR=17 -DPACKAGE_VERSION_SUBMINOR=0 -i /home/crash/.conan2/p/b/libic2b01ca099ce3a/b/src/lib/../windows/libiconv.rc --output-format=coff -o libiconv.res.o
../libtool: line 1932: windres: command not found
```
By reverting …
> libiconv: don't hardcode name of windres executable

- recipes/libe57format/all/conandata.yml
- recipes/libe57format/all/conanfile.py
- recipes/libe57format/config.yml
Changes to recipe:  **libe57format/3.2.0**
Add 3.2.0 release
> Add libe57format/3.2.0 release

- recipes/drogon/all/conandata.yml
- recipes/drogon/config.yml
Changes to recipe:  **drogon/1.9.9**
The Drogon Framework was updated three weeks ago. So, the current version is 1.9.9
[the framework on GitHub](https://github.com/drogonframework/drogon)
---
PR exists, but it was not created correctly.
That's my first PR to Conan.
I followed these tutorials:
https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html
https://docs.conan.io/2/tutorial/creating_packages/test_conan_packages.html
This package requires an exact version with each command such as --version 1.9.9 (and the other versions)
> drogon: add version 1.9.9

- recipes/qt/6.x.x/conanfile.py
###
* when crossbuilding, raise `ConanInvalidConfiguration` from `validate_build()` instead of `validate()` - this actually fixes an issue where qt cannot otherwise be used in crossbuilding scenarios
* https://github.com/conan-io/conan-center-index/pull/25024: remove dependency on perl  for recent versions of qt (see  https://www.qt.io/blog/perl-is-out-of-the-list-of-dependencies)
* https://github.com/conan-io/conan-center-index/pull/26006 - reflect metal framework on macOS/iOS for QtGUI
* https://github.com/conan-io/conan-center-index/pull/25550 - unconditionally set `CMAKE_TRY_COMPILE_CONFIGURATION` 
commits are chery-picked, authorship is preserved
> qt6: condense small fixes in single PR

- recipes/resiprocate/cmake/conandata.yml
- recipes/resiprocate/cmake/conanfile.py
- recipes/resiprocate/cmake/test_package/CMakeLists.txt
- recipes/resiprocate/cmake/test_package/conanfile.py
- recipes/resiprocate/cmake/test_package/test_package.cpp
- recipes/resiprocate/config.yml
Specify library name and version:  **resiprocate/1.13.1**
Since the 1 and a half years that this PR is open (😢) a new stable release happened. The PR has been updated accordingly. 
---
> resiprocate: add 1.13.1

- recipes/opencolorio/all/conanfile.py
Changes to recipe:  **opencolorio/?**
Bumping the dependency to OpenEXR 3.3.2 (latest one) as the current one is no longer supported and thus doesn't support libdeflate ranges. However, to be compatible with libtiff when both are required by OpenImageIO, they require a version of OpenEXR with libdeflate support.
I have problems to solve the dependency tree of #25672 due to libdeflate so this change should solve the problem. Also I guess it is beneficial to have a supported version of a dependency in the requires.
---
> OpenColorIO: Bump version of OpenEXR to a supported one

- recipes/librasterlite2/all/conanfile.py
- recipes/opencascade/all/conanfile.py
- recipes/opencv/3.x/conanfile.py
- recipes/pdf-writer/all/conanfile.py
Closes https://github.com/conan-io/conan-center-index/issues/26515
Brings all freetype/2.13 to .2 patch to avoid conflicts.
Note that there are other recipes that require a different minor version, but those are:
- Not yet ported to Conan 2
- Very old, and we haven't received any request to upgrade those
> Bring all requirements to freetype/2.13 to .2 patch

- recipes/sdl_image/all/conandata.yml
- recipes/sdl_image/all/conanfile.py
- recipes/sdl_image/config.yml
Changes to recipe:  **sdl_image/[*]**
Fix for https://github.com/conan-io/conan-center-index/issues/26522
The library has tons of improvements, but that can be tackled in a follow-up PR to keep this diff clear
Only in msvc is the name changed
From sdl_image's CMakeLists, for the static case:
```cmake
if(MSVC OR (WATCOM AND (WIN32 OR OS2)))
set_target_properties(SDL2_image PROPERTIES
OUTPUT_NAME "SDL2_image-static"
)
endif()
```
---
> sdl_image: Fix static builds for mingw 

- recipes/libe57format/all/conandata.yml
- recipes/libe57format/all/conanfile.py
- recipes/libe57format/all/patches/0001-Fix-gcc13-compilation.patch
See: https://gcc.gnu.org/gcc-13/porting_to.html
Changes to recipe:  **libe57format/[2.3.0]**
Does not compile with gcc-13
See: https://gcc.gnu.org/gcc-13/porting_to.html
`<cstdint>` now needs to be included directly.
> [libe57format] Fix compilation with gcc-13

- recipes/linux-syscall-support/all/conanfile.py
This is probably a leftover from Conan 1
> linux-syscall-support: fix validate() method

- recipes/breakpad/all/conandata.yml
- recipes/breakpad/all/patches/0004-Fix-gcc13-compilation.patch
- recipes/breakpad/all/patches/0005-Apply-upstream-fixes.patch
Changes to recipe:  **breakpad/cci.20210521**
Breakpad would not compile with gcc-13 on Ubuntu 24.02 Noble Numbat
See for reference: https://gcc.gnu.org/gcc-13/porting_to.html
> Some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. As such, C++ programs that used standard library components without including the right headers will no longer compile.
> 
> The following headers are used less widely in libstdc++ and may need to be included explicitly when compiling with GCC 13:
> - <string> (for std::string, std::to_string, std::stoi etc.)
> - <system_error> (for std::error_code, std::error_category, std::system_error).
> - <cstdint> (for std::int8_t, std::int32_t etc.)
> - <cstdio> (for std::printf, std::fopen …
> [breakpad] Fix compilation with gcc-13

- recipes/qt/6.x.x/conanfile.py
- recipes/qt/6.x.x/test_package/conanfile.py
Changes to recipe:  qt/6.x.x
Provide ability to cross-build recipe
* Preserve `Qt6HostInfoConfig.cmake` in the package folder - this is needed by Qt itself when crossbuilding (it does not define targets, just some meta-information about the build)
* Define `QT_HOST_PATH` to point to the self-dependency in the build context 
* In lieu of `Qt6CoreTools` - simply pre-include the target executable information that is already in the dependency in the build context - that will define things like `Qt6::moc` and will use those instead
* Include executables part of Qtbase tools that were not defined in the targets file - these are needed when crossbuilding qt
* Delete logic around `android_sdk` (is not an option)
* Minimally adapt the test_package to get it to work when cross-building (it's …
> qt6: add ability to crossbuild

- recipes/libmnl/all/conanfile.py
Changes to recipe:  **libmnl/1.0.5**
The actual recipe revision raises `ConanInvalidConfiguration` under `configure()`, breaking not only the natural build order but also affecting directly the CI.
The PR https://github.com/conan-io/conan-center-index/pull/26200 requires libmnl and when computing this requirement, the CI can not continue due to this recipe bug. 
---
> [libmnl] Fix OS validation position

- recipes/llama-cpp/all/cmake/llama-cpp-cuda-static.cmake
- recipes/llama-cpp/all/conandata.yml
- recipes/llama-cpp/all/conanfile.py
- recipes/llama-cpp/all/patches/b4570-001-curl-patch-targets.patch
- recipes/llama-cpp/all/test_package/CMakeLists.txt
- recipes/llama-cpp/config.yml
Changes to recipe:  **llama-cpp/b4570**
We wanted to use it in a future blogpost
Lots of changes for this new version, so the package_info is split in two: the old one, and the new one. Maybe it would be better to remove the old versions from the conandata and just keep this new version, but thought that the current approach is a bit better until we can decide
The ARM msvc validation check is due to this:
`ggml/src/ggml-cpu/CMakeLists.txt` has this when adding ggml-cpu:
```
if (MSVC AND NOT CMAKE_C_COMPILER_ID STREQUAL "Clang")
message(FATAL_ERROR "MSVC is not supported for ARM, use clang")
else()
```
As the cpu backend is always enabled in the recipe, I just validate this case out
> llama-cpp: Add new b4570 version

- recipes/mold/all/conandata.yml
- recipes/mold/all/conanfile.py
- recipes/mold/all/test_package/conanfile.py
- recipes/mold/config.yml
follow up on https://github.com/conan-io/conan-center-index/pull/26553 
* Add version 2.36.0
* Refactor handling of min cpp std
* Move checks to validate_build()  - this is an executable/application where the compiler.cppstd should not cause issues to downstream consumers
> mold: add version 2.36.0

- recipes/quill/all/conandata.yml
- recipes/quill/config.yml
Add [Quill ](https://github.com/odygrd/quill) version 8.1.0
Version dump that includes improvements and fixes. For example
```
Updated bundled libfmt to 11.1.3
Suppressed clang-19 warning when building the tests with C++17
Fixed windows linkage error 
Fixed redefinition of struct fmt_detail::time_zone error
```
config.yml and conandata.yml point to the latest version
---
> [quill] add version 8.1.0

- recipes/libpng/all/conandata.yml
- recipes/libpng/config.yml
Changes to recipe:  **libpng/1.6.46**
New upstream version released.
https://github.com/pnggroup/libpng/compare/v1.6.45...v1.6.46
---
> libpng: add version 1.6.46

- recipes/cutlass/all/conandata.yml
- recipes/cutlass/config.yml
Changes to recipe:  **cutlass/3.1.0**
PR adds older version of cutlass - 3.1.0. This specific version is required to build onnxruntime 1.18.x with `with_cuda=True`: https://github.com/microsoft/onnxruntime/blob/v1.18.2/cmake/deps.txt#L56. I've had no success building onnxruntime with newer cutlass.
---
> cutlass: add version 3.1.0

- recipes/libsvtav1/all/conanfile.py
- recipes/libwebp/all/conanfile.py
- recipes/libx264/all/conanfile.py
- recipes/vorbis/all/conanfile.py
libsvtav1, libwebp, vorbis:
* Add missing system libraries on Android (this only affects consumers of the static variant) - in all cases, consumers get missing symbols from either the m library or log library (see logs) 
libx264:
* remove broken Android handling logic, fix https://github.com/conan-io/conan-center-index/issues/24640 - tested with the current android-ndk recipe, there seems to be no need for any custom logic in the recipe, for details [see](https://github.com/conan-io/conan-center-index/pull/26583#discussion_r1952710345) 
This fixes issues experienced when building ffmpeg for Android using static dependencies:
Note: despite the "not found using pkg-config" errors - the libraries _are_ found by pkg-config, it's the subsequent test that fails. 
```
ERROR: SvtAv1Enc >= 0.9.0 …
```
> media libraries: fix missing system libs for Android, fix libx264 android build

- recipes/libffi/all/conanfile.py
bug
conan profile
```
[settings]
os=Windows
arch=x86_64
compiler=clang
compiler.version=18
compiler.libcxx=libc++
compiler.cppstd=20
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```
conanfile.txt
```
[requires]
qt/6.7.3
[generators]
CMakeDeps
CMakeToolchain
[layout]
cmake_layout
```
error
```
ERROR: libffi/3.4.4: Error in generate() method, line 130
ar_wrapper = unix_path(self, self.dependencies.build["automake"].conf_info.get("user.automake:lib-wrapper"))
KeyError: "'automake' not found in the dependency set"
```
> libffi: fix conditionals when building on Windows

- recipes/android-ndk/all/conanfile.py
- recipes/android-ndk/all/test_package/conanfile.py
Revert https://github.com/conan-io/conan-center-index/pull/23346
While the documentation is correct (the compiler should be used as the assembler and as the linker) - that's a determination for build systems (and they usually get it right) - they usually _do_ invoke the compiler to perform the link stage, and not the linker directly
This PR fixes an issue in some autotools recipes when targetting android and the linker needs to be invoked (e.g. when building shared libraries)
```
configure:7608: checking for ld used by /Users/conan/.conan2/p/androc439eef6aa9d6/p/bin/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android26-clang
configure:7676: result: /Users/conan/.conan2/p/androc439eef6aa9d6/p/bin/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android26-clang++ …
```
> android-ndk: dont set LD and AS variables

- recipes/openssl/3.x.x/conandata.yml
- recipes/openssl/config.yml
OpenSSL 3.4.1 is a security patch release. The most severe CVE fixed in this release is High ([CVE-2024-12797](https://openssl-library.org/news/secadv/20250211.txt)).
Changes to recipe:  **openssl/***
---
> openssl: add versions `3.0.16`, `3.1.8`, `3.2.4`, `3.3.3`, `3.4.1`, stop publishing new revisions for version `3.0.15`

- recipes/grpc/all/conandata.yml
- recipes/grpc/all/conanfile.py
- recipes/grpc/all/target_info/grpc_1.69.0.yml
- recipes/grpc/config.yml
Changes to recipe:  **grpc/1.69.0**
Close https://github.com/conan-io/conan-center-index/issues/26590
* Newer version of gRPC contains an important fix of compilation errors caused by new version of Windows 
SDK 10.0.26100. [Issue](https://github.com/grpc/grpc/issues/37210#issuecomment-2226809722)
* Includes a fix for https://nvd.nist.gov/vuln/detail/CVE-2024-11407
Updated target_info file by checking diff for gRPC CMakeLists.txt.
Tested new version package in Windows x64 environment.
---
> grpc: add version 1.69.0

- recipes/abseil/all/conanfile.py
Changes to recipe:  **abseil/all**
With newer versions of abseil the variable ABSL_MSVC_STATIC_RUNTIME needs to be defined.
Added with https://github.com/abseil/abseil-cpp/pull/1699
With msvc, set ABSL_MSVC_STATIC_RUNTIME based on is_msvc_static_runtime.
---
> [abseil] Handle msvc static runtime

- recipes/libpng/all/conandata.yml
- recipes/libpng/config.yml
Changes to recipe:  **libpng/1.6.47**
https://github.com/pnggroup/libpng/compare/v1.6.46...v1.6.47
---
> libpng: add version 1.6.47

- recipes/avahi/all/conanfile.py
- recipes/avahi/all/test_package/test_package.c
Changes to recipe:  **avahi/0.8**
This PR fixes the shadowing of standard headers as described in #26265.
This PR reverts the change introduced in #20741 for headers in `<avahi-common/*.h>`.
---
> avahi: fix shadowed headers (#26265)

- recipes/md4qt/all/conandata.yml
- recipes/md4qt/all/conanfile.py
- recipes/md4qt/all/test_package/CMakeLists.txt
- recipes/md4qt/all/test_package/test_package.cpp
- recipes/md4qt/config.yml
Changes to recipe:  **md4qt/4.1.0**
This is a major update of the library.
https://invent.kde.org/libraries/md4qt/-/commits/master?ref_type=HEADS
* The code is formatted with KDE Coding Style.
* Fixed performance regression introduced in `3.0.0`.
* Fixed RTL support in generated HTML.
* Made text entities in Markdown AST with spaces as in source Markdown file. 
* Fixed parsing of HTML in some cases in lists.
* HTML visitor and function made more generic.
* Fixed performance slowdown in parsing emphasises.
* Fixed parsing of breaked lists.
* Fixed parsing of HTML in combinations with fenced code blocks.
* Minor improvements and fixes.
Development is going in KDE repository, but I have a hitch there with release process, so I imported all done things to GitHub and made there releases of …
> md4qt: bump version

- recipes/tesseract/all/conanfile.py
Update the version of libarchive used by tesseract because 3.7.2 is vulnerable.
[NVD libarchive](https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe%3A2.3%3Aa%3Alibarchive%3Alibarchive%3A3.7.2%3A*%3A*%3A*%3A*%3A*%3A*%3A*)
Changes to recipe:  **tesseract/[all]**
[NVD libarchive](https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe%3A2.3%3Aa%3Alibarchive%3Alibarchive%3A3.7.2%3A*%3A*%3A*%3A*%3A*%3A*%3A*)
bump version from 3.7.2 to 3.7.6
---
> [tesseract] Update the version of libarchive used by tesseract

- recipes/foxglove-schemas-protobuf/all/conandata.yml
- recipes/foxglove-schemas-protobuf/all/conanfile.py
Changes to recipe:  **foxglove-schemas-protobuf/0.1.0**
Update URL + hash sum that changed because github repository has been renamed
The repository github.com/foxglove/schemas got recently renamed to github.com/foxglove/foxglove-sdk which unfortunately changed the hash sum of all source code archives downloaded from github. This is because the archives include a top level folder which is made up of the repository name. Since that name changed, also the top level folder name changed and effectively also the hash sum of the entire archive.
Name of top-level folder before and after the repository got renamed:
Before: `schemas-releases-python-foxglove-schemas-protobuf-v0.1.0`
After: `foxglove-sdk-releases-python-foxglove-schemas-protobuf-v0.1.0`
---
> foxglove-schemas-protobuf: Update url + hash sum

- recipes/grpc/all/conanfile.py
Changes to recipe:  **grpc**
Close https://github.com/conan-io/conan/issues/17703
When grpc has shared dependencies in Windows, the grpc_cpp_plugin execution can fail. The recipe already had provisioned for Linux scenario and LD_LIBRARY_PATH, but not for Windows PATH
It is necessary to add ``cmake/3.25`` to be able to correctly inject PATHs in ``cmake -E env --modify`` syntax
Also, small removals of Conan 1 legacy dead code, and minor refactors to reduce the recipe.
I have tested manually in Windows and Linux the static-shared scenario
```
conan create . --version=1.54.3 -o "*:shared=True" -o "&:shared=False"
```
> Fix grpc static in Windows with shared protobuf dependency

- recipes/xmlsec/all/conanfile.py
Changes to recipe:  **xmlsec/1.3.6**
fixes #26621 
Set the define `WIN32_LEAN_AND_MEAN` when the compiler is mingw . The `WIN32_LEAN_AND_MEAN` define is used in Windows to exclude some of the less frequently used APIs from the Windows headers. This can help prevents the inclusion of some headers like cryptography, among others that can help to fix header conflicts with openssl.
This is based on the defines used on msvc makefile in the project:
https://github.com/lsh123/xmlsec/blob/f48168188a9d0ecda4a19b3f5586860b00d81b69/win32/Makefile.msvc#L365-L375
---
> xmlsec: fix header conflicts between OpenSSL and Windows

- recipes/cnats/all/conanfile.py
- recipes/folly/all/conanfile.py
- recipes/gamenetworkingsockets/all/conanfile.py
- recipes/yojimbo/all/conanfile.py
- recipes/zeromq/all/conanfile.py
Fix https://github.com/conan-io/conan-center-index/issues/26682
The following recipes have been updated to avoid any `libsodium` conflict. 
* cnats
* folly
* gamenetworkingsockets
* zeromq
Attaching logs of recipes which have `libsodium` disabled by default, all compiling:
```sh
$ conan create recipes/cnats/all --version 3.9.2 -o '&:with_sodium=True' --build missing
```
[cnats_with_sodium.txt](https://github.com/user-attachments/files/18961512/cnats_with_sodium.txt)
```sh
$  conan create recipes/gamenetworkingsockets/all --version 1.4.1 -o '&:encryption=libsodium' -s arch=x86_64 --build=missing 
```
[gamenetworkingsockets_encryption_libsodium.txt](https://github.com/user-attachments/files/18961513/gamenetworkingsockets_encryption_libsodium.txt)
libsodium/1.0.19 is broken and has been …
> Bump libsodium to 1.0.20

- recipes/arrow/all/conandata.yml
- recipes/arrow/all/conanfile.py
- recipes/arrow/all/patches/19.0.1-0001-fix-cmake.patch
- recipes/arrow/all/patches/19.0.1-0002-fix-downloaded-mimalloc.patch
- recipes/arrow/config.yml
Changes to recipe:  **arrow/19.0.1**
This provides access to the 19.0.1 release of Arrow.
The change provides access to a new version and updates the required patch currently needed for this package to build correctly.
Tested locally with:
```[settings]
arch=armv8
compiler=gcc
compiler.cppstd=20
compiler.version=13
os=Macos
mold*:build_type=Release
[conf]
tools.build:compiler_executables={'c': 'gcc-13', 'cpp': 'g++-13'}
```
---
> Add support for the arrow 19.0.1 package

- recipes/libjxl/all/conanfile.py
- recipes/libvips/all/conanfile.py
Changes to recipe:  **libvips/[*]** & **libjxl[*]**
Fixes #26465
The generated pc file in libjxl contains `Requires: libhwy libbrotlienc libbrotlidec libjxl_cms`, but the recipe did not reflect this
The recipes, specially libjxl's, need some improvements (It currently fetches dependencies from the system instead of Conan, for example), but that's left as a follow-up PR to minimize the diff here
> Fix libjxl usage in libvips

- recipes/qarchive/all/test_package/CMakeLists.txt
- recipes/qarchive/all/test_package/conanfile.py
Changes to recipe:  **qarchive/\***
When building test_package and using qt6 this error occurs:
```
CMake Warning (dev) at D:/conan2/qtd87b8da2e6f46/p/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2827 (if):
Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
--help-policy CMP0057" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
IN_LIST will be interpreted as an operator when the policy is set to NEW.
Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
D:/conan2/qtd87b8da2e6f46/p/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2884 (_qt_internal_add_deploy_support)
D:/conan2/qtd87b8da2e6f46/p/lib/cmake/Qt6Core/Qt6CoreConfigExtras.cmake:30 (_qt_internal_setup_deploy_support) …
```
> qarchive: fix test_package build with qt6

- recipes/box2d/all/conandata.yml
- recipes/box2d/all/patches/3.0.0-0003-disable-warning-as-errors.patch
- recipes/box2d/all/patches/3.0.0-0003-remove-compile-warnings-as-error.patch
Changes to recipe:  **box2d/3.0.0**
box2d fails to build on MacOS with clang-19, because box2d builds traits compiler warning as error and clang-19 has stricter rules than the installed apple-clang 16.
I've created an [issue](https://github.com/erincatto/box2d/issues/882) on the upstream project. 
clang-19 fails the build with the following error, for more details, see the issue above.
```
contact_solver.c:824:28: error: AVX vector return of type 'simde__m256' (vector of 8 'simde_float32' values) without 'avx' enabled changes the ABI [-Werror,-Wpsabi]
824 |                 b2FloatW tangentY = sub( simde_mm256_setzero_ps(), c->normal.X );
|                                          ^
```
The fix is to disable the warnign as errors.
---
> box2d/3.0.0: fix build issue with clang-19 on MacOS

- recipes/websocketpp/all/conanfile.py
- recipes/websocketpp/all/test_package/test_package.cpp
Changes to recipe: websocketpp/0.8.2
fix https://github.com/conan-io/conan-center-index/issues/26452
Continued the PR #26453
Websocketpp requires boost random when creating websocket client.
---
> [websocketpp] Add missing linkage to boost random

- recipes/joltphysics/5.x/conanfile.py
- recipes/joltphysics/5.x/test_package/test_package.cpp
Changes to recipe:  **joltphysics/5.2.0**
I'm able to reproduce the bug reported by #26561. The Joltphysics has several compiler definition exposed as public, but some of them are missing in the recipe: https://github.com/jrouwe/JoltPhysics/blob/v5.2.0/Jolt/Jolt.cmake
fixes #26561
Build logs on Windows, using the example listed in issue #26561
- [jost-static-fix-windows.log](https://github.com/user-attachments/files/18795297/jost-static-fix-windows.log)
- [jost-shared-fix-windows.log](https://github.com/user-attachments/files/18795298/jost-shared-fix-windows.log)
/cc @AbrilRBS 
---
> [joltphysics] Export missing compiler definitions

- recipes/onetbb/all/conandata.yml
- recipes/onetbb/all/conanfile.py
- recipes/onetbb/config.yml
Changes to recipe:  onetbb
in OneTBB 2021.13.0 a new flag has been added to allow tbb to be build into Apple .frameworks instead of dylibs. iOS doesn't allow for bare dylibs to be loaded unless they are system libaries.
- add source url for version 2021.13.0
- add an 'Apple OS only' recipe option to enable oneTBB to build into frameworks
I'm aware there is also a PR for 2022.0.0, but that one doesn't add the build option 'build_apple_frameworks' and makes some changes to the test_package, so scope isn't the same.
Since that PR doesn't make changes to the recipe itself, merging should be easy.
---
> Add onetbb 2021.13.0 and add recipe flags to build into apple frameworks

- recipes/libqasm/all/conandata.yml
- recipes/libqasm/config.yml
Changes to recipe:  **libqasm/1.0.0**
`config.yml` and `conandata.yml` point to the newly created libqasm/1.0.0.
---
> libqasm: add version 1.0.0

- recipes/asio-grpc/all/conandata.yml
- recipes/asio-grpc/all/conanfile.py
- recipes/asio-grpc/all/test_package/CMakeLists.txt
- recipes/asio-grpc/all/test_package/test_package.cpp
- recipes/asio-grpc/config.yml
Specify library name and version:  **asio-grpc/3.4.1**
Asio-grpc v3.0.0 no longer uses `local_allocator_option`. It could have a new `backend_option` in https://github.com/NVIDIA/stdexec but there does not seem to be a recipe for it here in conan-center.
Contains https://github.com/conan-io/conan-center-index/pull/19070
Note, I am the author of asio-grpc.
---
> asio-grpc: add version 3.4.1

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
* Add version 1.91.8/1.91.8-docking
* Remove some older patch levels
Changes to recipe:  **imgui/1.91.8**
Number of improvement and fixes as usual.
Also cleaning up the history a bit by removing old/unused version. (1.90.5 is kept intentionally as it is required by two other recipes.)
https://github.com/ocornut/imgui/releases/tag/v1.91.8
---
> imgui: Add version 1.91.8

- recipes/opentelemetry-cpp/all/conandata.yml
- recipes/opentelemetry-cpp/all/conanfile.py
- recipes/opentelemetry-cpp/config.yml
Changes to recipe:  **opentelemetry-cpp/***
There are several new features and improvements in 1.18.0.
opentelemetry-cpp/1.18.0 requires opentelemetry-proto/1.4.0. [ref](https://github.com/open-telemetry/opentelemetry-cpp/pull/3157)
https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.18.0
https://github.com/open-telemetry/opentelemetry-cpp/compare/v1.17.0...v1.18.0
---
> opentelemetry-cpp: add version 1.18.0, update opentelemetry-proto

- recipes/fltk/all/conandata.yml
- recipes/fltk/all/conanfile.py
- recipes/fltk/config.yml
Changes to recipe:  **fltk/1/4.1**
There are lots of new features in 1.4.1.
Try to close https://github.com/conan-io/conan-center-index/issues/26041.
https://github.com/fltk/fltk/compare/release-1.3.9...release-1.4.1
---
> fltk: add version 1.4.1

- recipes/glaze/all/conandata.yml
- recipes/glaze/config.yml
Changes to recipe:  **glaze/4.4.2**
- Add TRACE Option
- AVX2 is used by default, also disable AVX2 flag is added.
https://github.com/stephenberry/glaze/compare/v4.3.1...v4.4.2
---
> glaze: add version 4.4.3

- recipes/commata/all/conandata.yml
- recipes/commata/config.yml
Changes to recipe:  **commata/1.0.2**
There are several bug fixes in 1.0.2.
https://github.com/furfurylic/commata/releases/tag/v1.0.2
https://github.com/furfurylic/commata/compare/v1.0.1...v1.0.2
---
> commata: add version 1.0.2

- recipes/openscenegraph/all/conanfile.py
Changes to recipe:  **openscenegraph/\***
This allows openscenegraph to build when `with_jpeg=libjpeg-turbo` or when `with_jpeg=mozjpeg`
---
> openscenegraph: fix building with other jpeg implementations

- recipes/protobuf/all/conandata.yml
- recipes/protobuf/all/conanfile.py
- recipes/protobuf/config.yml
Changes to recipe:  **protobuf/* **
Fixes https://github.com/conan-io/conan-center-index/issues/26604
Remaining current with protobuf repo releases
Started from https://github.com/conan-io/conan-center-index/pull/25693, who deserves most of the credit
https://github.com/protocolbuffers/protobuf/compare/v27.0...v29.3
---
> protobuf: add version 5.29.3, depends on toge:protobuf-5.28.2

- recipes/tree-sitter/all/conandata.yml
- recipes/tree-sitter/config.yml
Changes to recipe:  **tree-sitter/0.25.1**
0.25.0 is a large release. There are lots of improvements.
https://github.com/tree-sitter/tree-sitter/releases/tag/v0.25.0
https://github.com/tree-sitter/tree-sitter/compare/v0.24.4...v0.25.1
---
> tree-sitter: add version 0.25.1

- recipes/mimalloc/all/conanfile.py
Changes to recipe:  **mimalloc/***
proposes fix for #26646
Adding an option for MI_WIN_REDIRECT adds transparency and avoids hard to find build errors. See  #26646
---
> mimalloc: Added recipe option for MI_WIN_REDIRECT

- recipes/gdal/post_3.5.0/conanfile.py
This PR affects GDAL/[>=3.5.3], including its package ID.
Following the issue #26287 , this PR add options to manage both `GDAL_BUILD_OPTIONAL_DRIVERS` and `OGR_BUILD_OPTIONAL_DRIVERS` upstream options.
For specific drivers, I would suggest by using:
> tools.cmake.cmaketoolchain:extra_variables: Dictionary with variables to be injected in CMakeToolchain (potential override of CMakeToolchain defined variables)
https://docs.conan.io/2/reference/config_files/global_conf.html
close #26287
/cc @rickyjames35
I built locally by disabling both `GDAL_BUILD_OPTIONAL_DRIVERS` and `OGR_BUILD_OPTIONAL_DRIVERS`. Here are my build logs:
[gdal-3.5.3-full-no-drivers.log](https://github.com/user-attachments/files/18479290/gdal-3.5.3-full-no-drivers.log) …
> [GDAL] Add options for optional drivers

- recipes/jtckdint/all/conandata.yml
- recipes/jtckdint/all/conanfile.py
- recipes/jtckdint/all/test_package/CMakeLists.txt
- recipes/jtckdint/all/test_package/conanfile.py
- recipes/jtckdint/all/test_package/test_package.c
- recipes/jtckdint/config.yml
Changes to recipe:  **jtckdint/1.0**
a portable single-file header-only library that defines C23 three type generic functions.
https://github.com/jart/jtckdint
---
> jtckdint: add recipe

- recipes/abseil/all/conandata.yml
- recipes/abseil/config.yml
Changes to recipe:  **abseil/20240722.1**
New upstream version to fix CVE-2025-0838
https://github.com/abseil/abseil-cpp/compare/20240722.0...20240722.1
---
> abseil: add version 20240722.1

- recipes/wt/all/conandata.yml
- recipes/wt/config.yml
Changes to recipe:  **wt/4.11.2**
New release of Wt library.
Only a new version 4.11.2 added, no other changes.
---
> Update Wt version to 4.11.2

- recipes/libcurl/all/conanfile.py
- recipes/libcurl/all/test_package/test_package.c
Changes to recipe:  **libcurl/[*]**
Simpler fix for missing libnghttp2 detection
Closes https://github.com/conan-io/conan-center-index/issues/26054 and is a subset of the changes from https://github.com/conan-io/conan-center-index/pull/26063
Without the fix, the test_package for `conan create . --version=8.11.1 -b=missing -o="&:with_nghttp2=True"` on Windows shows:
```
======== Testing the package: Executing test ========
libcurl/8.11.1 (test package): Running test()
libcurl/8.11.1 (test package): RUN: Release\test_package
protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
version: 8.11.1
ssl version: OpenSSL/3.3.2
features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP Unicode …
```
> Fix http2 detection in CMake builds

- recipes/libpq/all/conanfile.py
Changes to recipe:  **libpq/all versions**
The pg_config should be built ahead of `interfaces/libpq`, otherwise we could get the following undefined errors, it does NOT always happen(I don't know why it does not fail though)
```
/home/hsuan/.conan/data/libpq/15.4/_/_/build/c11224e931af7eb47df7c689b7ad7afc6b151bd9/src/src/port/path.c: In function ‘get_includeserver_path’:
/home/hsuan/.conan/data/libpq/15.4/_/_/build/c11224e931af7eb47df7c689b7ad7afc6b151bd9/src/src/port/path.c:863:38: error: ‘INCLUDEDIRSERVER’ undeclared (first use in this function); did you mean ‘INCLUDEDIR’?
863 |         make_relative_path(ret_path, INCLUDEDIRSERVER, PGBINDIR, my_exec_path);
|                                      ^~~~~~~~~~~~~~~~
|                                      INCLUDEDIR
/usr/bin/gcc-13 -Wall …
```
> libpq: pg_config should be built first

- recipes/muparser/all/conandata.yml
- recipes/muparser/config.yml
Ref #14561
This should resolve issue #17356
Changes to recipe:  **muparser/2.3.5**
Bump muparser patch release to allow building with MSVC / C++20
Just bump version, no change to the recipe needed. Tested locally on Win 11 machine running msvc v194 compiler
---
> muparser: add version 2.3.5

- recipes/zstd/all/conandata.yml
- recipes/zstd/config.yml
Changes to recipe:  **zstd/1.5.7**
zstd/1.5.7 brings better compression speed.
https://www.phoronix.com/news/Zstd-Zstandard-1.5.7
https://github.com/facebook/zstd/compare/v1.5.6...v1.5.7
---
> zstd: add version 1.5.7

- recipes/libjxl/all/conanfile.py
Changes to recipe:  **libjxl**
Fixes #26707
It is undesirable to force allocation libs dependencies that can have unexpected effects on other dependencies depending on linkage. libjxl should probably remove it as a dependency from the main lib as it will now be included if it exists on the system, but until then we shouldn't at least fetch it from cci.
---
> libjxl: don't force tcmalloc dependency on linux

- recipes/onnxruntime/all/cmake/onnxruntime_external_deps.cmake
Changes to recipe:  **onnxruntime/\***
onnxruntime expects `ABSEIL_LIBS` in cmake to be set to all the targets of abseil library: 
https://github.com/microsoft/onnxruntime/blob/3e4c5e64877c6d9814e4ebce5dcbb1fe71588ec5/cmake/external/abseil-cpp.cmake#L52
In the recipe we replace `onnxruntime_external_deps.cmake` with our own:
https://github.com/conan-io/conan-center-index/blob/c305e9cf19080bdec9db1e803ed6757606f77fb1/recipes/onnxruntime/all/conanfile.py#L189-L191 which doesn't define `ABSEIL_LIBS` at all.
But this is especially important when cuda prodivers are built (i.e. with_cuda=True):
https://github.com/microsoft/onnxruntime/blob/3e4c5e64877c6d9814e4ebce5dcbb1fe71588ec5/cmake/onnxruntime_providers_cuda.cmake#L196-L210 
and when `ABSEIL_LIBS` is empty you'll get linking errors like …
> onnxruntime: fix abseil linking errors when with_cuda=True

- recipes/c4core/all/conandata.yml
- recipes/c4core/all/patches/0.2.5-0001-make-fast_float-external.patch
- recipes/c4core/config.yml
Changes to recipe:  **c4core/0.2.5**
Several CPU architectures are supported since 0.2.2.
There are lots of new features and improvements.
Those will be required by future rapidyaml releases.
https://github.com/biojppm/c4core/releases/tag/v0.2.3
---
> c4core: add version 0.2.5

- recipes/quill/all/conandata.yml
- recipes/quill/all/test_package/CMakeLists.txt
- recipes/quill/config.yml
Changes to recipe: **quill/8.2.0**  
This is an upstream update that introduces a long-requested feature, making it easier to log user-defined types. Additionally, it includes several minor improvements.  
- Changelog: [v8.2.0](https://github.com/odygrd/quill/releases/tag/v8.2.0)  
- Compare: [v8.1.0...v8.2.0](https://github.com/odygrd/quill/compare/v8.1.0...v8.2.0)  
---
> quill: add version 8.2.0

- recipes/boost/all/dependencies/dependencies-1.87.0.yml
Changes to recipe:  **boost/1.87.0**
fixes #26741
The boost 1.87.0 will always produce the library boost context, because is required by boost asio. When disabling it, but keeping boost process enabled, it will result in a mismatch.
This fix is palliative, as the boost 1.87.0 introduced the modular build support (https://github.com/boostorg/asio/commit/a31cca5ec175b0d3b2e5b7f5e211f3ca75616e30), we should investigate the script `rebuild-dependencies.py` to avoid similar problems. 
---
> [boost] Boost process requires boost context as transitive dependency of asio

- recipes/nifti_clib/all/conanfile.py
There is an issue with how `zlib` is being consumed. `zlib` is used in one of the components of `nifti_clib`, but this requirement is not being passed to that component. Additionally, upstream needs to set the `HAVE_ZLIB` variable to ensure the correct use of the library.
Close: https://github.com/conan-io/conan-center-index/issues/26713
`HAVE_ZLIB`: https://github.com/NIFTI-Imaging/nifti_clib/blob/v3.0.0/znzlib/znzlib.h#L71
> fix nifti_clib zlib

- recipes/simdjson/all/conandata.yml
- recipes/simdjson/all/conanfile.py
- recipes/simdjson/config.yml
simdjson is dual licensed(Apache-2.0 and MIT) since 3.12.0.
performance improvements on Zen4 CPU in 3.12.2.
https://github.com/simdjson/simdjson/compare/v3.11.5...v3.12.2
---
> simdjson: add version 3.12.2, add MIT license

- recipes/nspr/all/conanfile.py
- recipes/nspr/all/test_package/conanfile.py
Fix this error when building natively on macOS arm64:
```
ERROR: nspr/4.35: Error in generate() method, line 110
tc.cflags.remove("-arch arm64")
ValueError: list.remove(x): x not in list
```
Re: 
> conan adds `-arch`, which conflicts with nspr's apple silicon support
Conan only adds `-arch` when crossbuilding, which is explicitly disabled as unsupported in this recipe - there should no issue building this natively
> nspr: fix macos build on arm64

- recipes/ffmpeg/all/conanfile.py
Changes to recipe:  **ffmpeg/[*]**
Closes https://github.com/conan-io/conan-center-index/issues/23118
Note that this issue, regardless of its title, intended to address soxr in ffmpeg as a final goal. I've confirmed that I can compile soxr in my Mac M2, so that stopped being an issue at some point in the past few months
The additions are quite straightforward. All supported versions of ffmpeg support the option, and running `yq '.versions |keys' ../config.yml | cut -d ' '  -f 2 | xargs -n1 conan create . -b=missing -o="&:swresample=True" -o="&:with_soxr=True" --version` correctly compiles for all versions, noting that:
* If the library was not found, we would see `ERROR: libsoxr not found`
* If the option was unknown, we would see `Unknown option "--enable-libsoxr"`
* By default this is …
> ffmpeg: Add missing soxr support

- recipes/openmvg/all/conanfile.py
Changes to recipe:  **openmvg/2.0**
Some components lack additional include directory `include/openMVG`, which leads to compile time errors when using the library includes:
https://github.com/openMVG/openMVG/blob/d0fe73dd426ae4001631a51272cff71047522df9/src/openMVG/features/CMakeLists.txt#L30
https://github.com/openMVG/openMVG/blob/d0fe73dd426ae4001631a51272cff71047522df9/src/openMVG/matching/CMakeLists.txt#L29
https://github.com/openMVG/openMVG/blob/d0fe73dd426ae4001631a51272cff71047522df9/src/openMVG/matching_image_collection/CMakeLists.txt#L30
https://github.com/openMVG/openMVG/blob/d0fe73dd426ae4001631a51272cff71047522df9/src/openMVG/robust_estimation/CMakeLists.txt#L16
https://github.com/openMVG/openMVG/blob/d0fe73dd426ae4001631a51272cff71047522df9/src/openMVG/sfm/CMakeLists.txt#L45 …
> openmvg: some components lack additional include dir

- recipes/sqlite3mc/all/conandata.yml
- recipes/sqlite3mc/config.yml
**sqlite3mc version 2.1.0** supports the latest SQLite version **3.49.1**, and includes an important bug fix affecting multi-threaded applications.
An entry for version 2.1.0 was added to the recipe.
---
> Update to SQLite3 Multiple Ciphers 2.1.0

- recipes/bzip3/all/CMakeLists.txt
- recipes/grpc-proto/all/CMakeLists.txt
- recipes/gsoap/all/CMakeLists.txt
- recipes/libelf/all/CMakeLists.txt
- recipes/pthreadpool/all/CMakeLists.txt
- bzip3
- grpc-proto
- gsoap
- libelf
- pthreadpool
```
```
Notes:
* We follow the recommendations …
> multiple recipes: increase cmake_minimum_required

- recipes/wayland/all/conanfile.py
- recipes/xkbcommon/all/conanfile.py
- recipes/xkeyboard-config/all/conanfile.py
Changes to recipe:  xkbcommon (and its dependencies wayland, xkeyboard-config) to enable building for Android
X11 is not supported, neither are xkbcommon CLI tools. Both are disabled.
We are experimenting with porting wayland applications to Android, and xkbcommon is a dependency.
- Adds "Android" to the allowed configurations for the above packages 
- Makes `with_x11` an optional option that is removed for Android
- Disables `enable_tools` for Android builds
---
> xkbcommon: Enable building for Android

- recipes/emio/all/conandata.yml
- recipes/emio/config.yml
Changes to recipe:  **emio/0.9.0**
New version with new features and bug fixes.
https://github.com/viatorus/emio/compare/0.8.0...0.9.0
---
> emio: add version 0.9.0

- recipes/bigint/all/CMakeLists.txt
- recipes/cgltf/all/CMakeLists.txt
- recipes/cmp/all/CMakeLists.txt
- recipes/co/all/CMakeLists.txt
- recipes/cpp-optparse/all/CMakeLists.txt
- bigint
- cgltf
- cmp
- co
- cpp-optparse
```
```
Notes: …
> multiple recipes: increase cmake_minimum_required (2)

- recipes/cqrlib/all/CMakeLists.txt
- recipes/csm/all/CMakeLists.txt
- recipes/diligent-fx/all/CMakeLists.txt
- recipes/diligent-tools/all/CMakeLists.txt
- recipes/drflac/all/CMakeLists.txt
- cqrlib
- csm
- diligent-fx
- diligent-tools
- drflac
```
```
Notes:
* We follow the …
> multiple recipes: increase cmake_minimum_required (3)

- recipes/drmp3/all/CMakeLists.txt
- recipes/drwav/all/CMakeLists.txt
- recipes/farmhash/all/CMakeLists.txt
- recipes/fft/all/CMakeLists.txt
- recipes/flatc/all/CMakeLists.txt
- drmp3
- drwav
- farmhash
- fft
- flatc
```
```
Notes: …
> multiple recipes: increase cmake_minimum_required (4)

- recipes/lmdb/all/CMakeLists.txt
- recipes/lodepng/all/CMakeLists.txt
- recipes/microprofile/all/CMakeLists.txt
- recipes/microtar/all/CMakeLists.txt
- recipes/mikktspace/all/CMakeLists.txt
- lmdb
- lodepng
- microprofile
- microtar
- mikktspace
```
```
Notes:
* We follow the …
> multiple recipes: increase cmake_minimum_required (7)

- recipes/sdl_net/all/CMakeLists.txt
- recipes/seasocks/all/CMakeLists.txt
- recipes/semver.c/all/CMakeLists.txt
- recipes/sofa/all/CMakeLists.txt
- recipes/ssht/all/CMakeLists.txt
- sdl_net
- seasocks
- semver.c
- sofa
- ssht
```
```
Notes: …
> multiple recipes: increase cmake_minimum_required (11)

- recipes/termcap/all/CMakeLists.txt
- recipes/tgc/all/CMakeLists.txt
- recipes/tiny-bignum-c/all/CMakeLists.txt
- recipes/tiny-regex-c/all/CMakeLists.txt
- recipes/tinyxml/all/CMakeLists.txt
- termcap
- tgc
- tiny-bignum-c
- tiny-regex-c
- tinyxml
```
```
Notes:
* We follow the …
> multiple recipes: increase cmake_minimum_required (12)

- recipes/tree-sitter-c/all/CMakeLists.txt
- recipes/tree-sitter/all/CMakeLists.txt
- recipes/tsil/all/CMakeLists.txt
- recipes/voropp/all/CMakeLists.txt
- tree-sitter-c
- tree-sitter
- tsil
- voropp
```
```
Notes: …
> multiple recipes: increase cmake_minimum_required (13)

- recipes/cpp-httplib/all/conandata.yml
- recipes/cpp-httplib/config.yml
Changes to recipe:  **cpp-httplib/0.19.0**
Bump version of cpp-httplib. It contains one new feature and various bug fixes since the previously released conan package (0.18.3).
https://github.com/yhirose/cpp-httplib/compare/v0.18.3...v0.19.0
---
> cpp-httplib: add version 0.19.0

- recipes/vulkan-headers/all/conandata.yml
- recipes/vulkan-headers/all/test_package/CMakeLists.txt
- recipes/vulkan-headers/config.yml
Changes to recipe:  **vulkan-headers/1.4.304.0**
Version bump
https://github.com/KhronosGroup/Vulkan-Headers/compare/vulkan-sdk-1.3.296.0...vulkan-sdk-1.4.304.0
config.yml and conandata.yml point to the newly created vulkan-headers/1.4.304.0.
---
> vulkan-headers: Add version 1.4.309.0

- recipes/spirv-headers/all/conandata.yml
- recipes/spirv-headers/all/test_package/CMakeLists.txt
- recipes/spirv-headers/config.yml
Changes to recipe:  **spirv-headers/1.4.304.0**
Version bump
https://github.com/KhronosGroup/SPIRV-Headers/compare/vulkan-sdk-1.3.296.0...vulkan-sdk-1.4.304.0
config.yml and conandata.yml point to the newly created spirv-headers/1.4.304.0.
---
> spirv-headers: Add version 1.4.309.0

- recipes/spirv-cross/all/conandata.yml
- recipes/spirv-cross/all/test_package/CMakeLists.txt
- recipes/spirv-cross/config.yml
Changes to recipe:  **spirv-cross/1.4.304.0**
Version bump
https://github.com/KhronosGroup/SPIRV-Cross/compare/vulkan-sdk-1.3.296.0...vulkan-sdk-1.4.304.0
config.yml and conandata.yml point to the newly created spirv-cross/1.4.304.0.
---
> spirv-cross: Add version 1.4.304.0

- recipes/libnftnl/all/conandata.yml
- recipes/libnftnl/all/conanfile.py
- recipes/libnftnl/all/test_package/CMakeLists.txt
- recipes/libnftnl/all/test_package/conanfile.py
- recipes/libnftnl/all/test_package/example.cpp
- recipes/libnftnl/config.yml
Add new recipe:  **libnftnl/[1.2.8]**, fixes #26198
This library helps to work with nf_tables subsystem
---
> libnftnl: add new recipe (#26198)

- recipes/numcpp/all/conandata.yml
- recipes/numcpp/config.yml
Changes to recipe:  **numcpp/2.14.0**
First release in 1.5 years.
Several new features since 2.12.1.
https://github.com/dpilger26/NumCpp/releases/tag/Version_2.14.0
https://github.com/dpilger26/NumCpp/compare/Version_2.12.1...Version_2.14.0
---
> numcpp: add version 2.14.0

- recipes/cccl/all/conandata.yml
- recipes/cccl/all/conanfile.py
- recipes/cccl/all/patches/0001-uname-detect-msys.patch
- recipes/cccl/all/test_package/conanfile.py
Changes to recipe:  **cccl/1.3**
The configuration `tools.microsoft.bash:path` should be string, not boolean, it's documented in the official Conan docs: https://docs.conan.io/2/examples/tools/autotools/create_your_first_package_windows.html#id1
The second, about the wrong triplet, by consuming the MATCHTYPE, it was discussed in msys2 issue https://github.com/msys2/MSYS2-packages/issues/5232, and its motivation is well explained on the blog post https://www.msys2.org/news/#2025-02-14-moving-msys2-closer-to-cygwin. They offered a workaround, like using the environment variable `MSYS2_ARG_CONV_EXCL='*'`, but it could break cccl as well, because it really uses `MATCHTYPE` variable.
I'm able to reproduce the ported case as well: [cccl-1.3-msys-conan-center.log](https://github.com/user-attachme …
> [cccl] Fix microsoft.bash configuration usage

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Changes to recipe:  **cmake/4.0.0-rc4**
Following https://github.com/conan-io/conan-center-index/issues/26878
Adding CMake latest release candidate will facilitate testing recipes.
Also, this is a good opportunity to distinguish from other package managers which does not yet support any v4 CMake version.
Checkout SHAs here: https://cmake.org/files/ReleaseCandidate/cmake-4.0.0-rc4-SHA-256.txt
> CMake: add version 4.0.0-rc4

- recipes/openssl/3.x.x/conandata.yml
- recipes/openssl/config.yml
OpenSSL 3.x can take too long to build on CI - and there's diminshing returns in terms of simultaneously maintaining too many versions from the same recipe, considering that as per OpenSSL's policy, OpenSSL 3.x is to remain backwards compatible https://openssl-library.org/policies/releasestrat/index.html)
- Other recipes in Conan Center depend on the version range `openssl/[>=1.1 <4]` (or similar) - which means that they will require the most recent version as soon as it's published
- Align with the supported releases by OpenSSL maintainers
This does *not* mean that those other versions are "deleted" - once a version is published in the Conan Center remote, it remains there, and if it works for a user, it will continue to work.
What this means is that we will not be maintaining the recipe …
> openssl: clarify maintained versions

- recipes/harfbuzz/all/conandata.yml
- recipes/harfbuzz/config.yml
Changes to recipe:  add version **harfbuzz/10.4.0**
many versions have been skipped over, but CVEs are reported in 8.5.0 through 10.0.1, so we wouldn't want to add those.
add a version that has no known vulnerabilities
---
> Add a new version of harfbuzz 10.4.0

- recipes/expat/all/conandata.yml
- recipes/expat/config.yml
Expat 2.7.0 has a few security fixes CVE-2024-8176
Release notes at: https://github.com/libexpat/libexpat/blob/R_2_7_0/expat/Changes
for details.
Changes to recipe:  **expat/2.7.0**
Accommodate the new version.
CVE-2024-8176
as per [release notes](https://github.com/libexpat/libexpat/blob/R_2_7_0/expat/Changes)
---
> [expat] Add version 2.7.0 to libexpat

- recipes/libqasm/all/conandata.yml
- recipes/libqasm/config.yml
Changes to recipe:  **libqasm/1.1.0**
`config.yml` and `conandata.yml` point to the newly created libqasm/1.1.0.
---
> libqasm: add version 1.1.0

- recipes/glslang/all/CMakeLists.txt
- recipes/hash-library/all/CMakeLists.txt
- recipes/http_parser/all/CMakeLists.txt
- recipes/irrxml/all/CMakeLists.txt
- recipes/jxrlib/all/CMakeLists.txt
- glslang
- hash-library
- http_parser
- irrxml
- jxrlib
```
```
Notes:
* We follow the …
> multiple recipes: increase cmake_minimum_required (5)

- recipes/miniaudio/all/CMakeLists.txt
- recipes/minizip/all/CMakeLists.txt
- recipes/mujs/all/CMakeLists.txt
- recipes/newmat/all/CMakeLists.txt
- recipes/pffft/all/CMakeLists.txt
- miniaudio
- minizip
- mujs
- newmat
- pffft
```
```
Notes: …
> multiple recipes: increase cmake_minimum_required (8)

- recipes/ragel/all/CMakeLists.txt
- recipes/rg-etc1/all/CMakeLists.txt
- recipes/rmlui/4.x/CMakeLists.txt
- recipes/rply/all/CMakeLists.txt
- recipes/sdl_image/all/CMakeLists.txt
- ragel
- rg-etc1
- rmlui/4.x
- rply
- sdl_image
```
```
Notes: …
> multiple recipes: increase cmake_minimum_required (10)

- recipes/libsigcpp/2.x.x/conandata.yml
Changes to recipe:  **libsigcpp/2.10.8**
close #26899
Both the old and the new URLs provide the very same source package, including the same SHA-256. The version 3.x of this project is using GNOME for source downloading already. 
---
> [libsigcpp] Use GNOME repository for source downloading

- recipes/pcre/all/conandata.yml
- recipes/pcre/all/conanfile.py
- recipes/pcre/all/patches/0001-fix-cmake-8.45.patch
- recipes/pcre/config.yml
pcre 8.45: fixes to support CMake 4
* increase cmake minimum required to 3.5, fixes build error when using CMake 4.0
* use `$<TARGET_FILE:dftables>` instead of inspecting the `LOCATION` target property
* remove lines that are a no-op in Conan 2
* remove older versions: this is the last release of pcre
> pcre 8.45: support cmake 4

- recipes/qt/5.x.x/conanfile.py
Changes to recipe:  **qt/5.x**
Fixes cross-building from ARM to Intel on macOS
Existing approach already worked fine for Intel -> ARM cross-building, this PR extends it to cover also the reverse case
---
> qt5: fix macOS cross-building from ARM to Intel

- recipes/azure-sdk-for-cpp/all/conanfile.py
Changes to recipe:  **azure-sdk-for-cpp/all**
We are using this package with AppleClang-16 on MacOS and Clang-17 on Ubuntu, and this is upstreaming our local patch.
There is a single warning that Clang finds for which we don't have a patch that we are confident in, and as such we're disabling warnings-as-errors while building this package as a dependency.
We loosened the checks in the conanfile.py to allow building with clang and on macos. The check for clang-10 is to give an early error for very old versions; we have only tested with 16 and 17 but want to avoid a sequence of "actually this works on 15", "actually ..." PRs after this.
---
> azure-sdk-for-cpp: allow macos and clang in conanfile

- recipes/opentrackio-cpp/all/conandata.yml
- recipes/opentrackio-cpp/all/test_package/test_package.cpp
- recipes/opentrackio-cpp/config.yml
Changes to recipe:  **opentrackio-cpp/1.0.0**
Replacing with the correct version 1.0.0 to match the outputs of [CamDKit](https://github.com/SMPTE/ris-osvp-metadata-camdkit)
Fix link and SHA to v1.0.0
---
> opentrackio-cpp: add version 1.0.1

- recipes/libtool/all/conanfile.py
- recipes/libtool/all/test_package/conanfile.py
- recipes/libtool/all/test_package/ltdl/CMakeLists.txt
Changes to recipe:  libtool/all
`automake` contains build-time-only executable scripts - so this should not be propagated as a dependency of libtool
`m4` appears in the _host_ context when crossbuilding, due to libtools dependency on automake (which depends on m4) - this causea Android build failures (as m4 does not build on android as it currently is, the reasons are irrelevanat).
`m4` is also a build-time executable and should not appear in the host profile
- use the languages property and `auto_shared_fpic` rather than implementing `config_options` and `configure` (equivalent functionality)
- use `settings_build`
- assume `-FS` is already passed by Conan where needed
- remove `env_info` (no-ops in Conan 2)
<details>
<summary> Before and after logs </summary>
```
conan install …
```
> libtool: automake is a tool requirement

- recipes/magnum-extras/all/CMakeLists.txt
- recipes/magnum-integration/all/CMakeLists.txt
- recipes/magnum-plugins/all/CMakeLists.txt
- recipes/magnum/all/CMakeLists.txt
- recipes/msgpack/all/CMakeLists.txt
- recipes/osgearth/all/CMakeLists.txt
- recipes/pdal/all/CMakeLists.txt
- recipes/qcoro/all/CMakeLists.txt
- recipes/rmlui/3.3/CMakeLists.txt
For the following conan v1 recipes:
(Any of this recipes would be built by CI)
- magnum-extras
- magnum-integration
- magnum-plugins
- magnum
- msgpack
- osgearth
- pdal
- qcoro
- rmlui/3.3
```
``` …
> multiple v1 recipes: increase cmake_minimum_required (14) [last one]

- recipes/vulkan-validationlayers/all/conandata.yml
- recipes/vulkan-validationlayers/all/conanfile.py
- recipes/vulkan-validationlayers/all/dependencies/dependencies-1.3.243.0.yml
- recipes/vulkan-validationlayers/all/dependencies/dependencies-1.4.309.0.yml
- recipes/vulkan-validationlayers/all/patches/1.3.243.0-0001-fix-cmake.patch
- recipes/vulkan-validationlayers/config.yml
Specify library name and version:  **vulkan-validationlayers/1.3.243.0**
This library was out of sync with the other Vulkan libraries on Conan Center, specifically vulkan-headers and, vulkan-loader. This patch adds support for the same version of validation layer, so that validation layers can be used with the headers and libraries packages.
---
> Bump version for vulkan-validationlayers/1.3.243.0

- recipes/ade/all/conanfile.py
ade: fixes to support CMake 4
Upstream issue tracker: https://github.com/opencv/ade/issues
Shows no recent activity and no intention of upgrading CMake minimum version.
> ade: CMake 4 support

- recipes/grpc/all/conanfile.py
The gRPC CMake configuration step can fail to due to a failure when downloading third party archives.  These failures are expected, and the user is instructed to retry.  So, if configuration fails, retry it
Also set the `gRPC_DOWNLOAD_ARCHIVES` CMake flag to `False`, to avoid downloading these unnecessary archives in the first place, in versions of gRPC that understand the flag
Specify library name and version:  **grpc/all**
This fixes https://github.com/conan-io/conan-center-index/issues/23094
---
> grpc: set gRPC_DOWNLOAD_ARCHIVES to false

- recipes/libtool/all/conanfile.py
- recipes/libtool/all/test_package/conanfile.py
Quite a few recipes that perform `autoreconf` were inadvertently relying on a `tool_requires` against `libtool` to bring in automake to be able to call autoreconf. Those recipes should encode the correct direct `tool_requires`, however partially reverting the change to minimise disruption
Close https://github.com/conan-io/conan-center-index/issues/26926
> libtool: depend on automake

- recipes/brotli/all/conanfile.py
brotli: fixes to support CMake 4
This fix only applies to versions < 1.1.0 as newer versions already support CMake 4
> brotli: CMake 4 support

- recipes/c-blosc/all/conanfile.py
c-blosc: fixes to support CMake 4
The upstream issue tracker does not contain any CMake 4 related request and seems to be no plan in the future https://github.com/Blosc/c-blosc/issues
> c-blosc: CMake 4 support

- recipes/libssh2/all/conandata.yml
- recipes/libssh2/all/patches/libssh2-1.8.0-CVE2020-22218.patch
- recipes/libssh2/all/patches/libssh2-1.8.2-CVE2020-22218.patch
- recipes/libssh2/all/patches/libssh2-1.9.0-CVE2020-22218.patch
https://nvd.nist.gov/vuln/detail/CVE-2020-22218
patch source: https://github.com/libssh2/libssh2/pull/476
Changes to recipe:  **lib/1.10.0**
Changes to recipe:  **lib/1.9.0**
Changes to recipe:  **lib/1.8.2**
Changes to recipe:  **lib/1.8.0**
I noticed CVE-2020-22218 with a severity of 7.5HIGH was not patched in Conan center, and it was fairly easy to fix.
all .patch files differ only by the line address the code itself is from https://github.com/libssh2/libssh2/pull/476 which is cited by nist as the fix.
---
> libssh2/1.10.0: Fix CVE-2020-22218

- recipes/cassandra-cpp-driver/all/conanfile.py
cassandra-cpp-driver: fixes to support CMake 4
The upstream issue tracker does not contain any CMake 4 related request and there seems to be no plan in the future https://github.com/datastax/cpp-driver/pulls
> cassandra-cpp-driver: CMake 4 support

- recipes/cjson/all/conanfile.py
cjson: fixes to support CMake 4
* Removed code related to legacy generators (`_create_cmake_module_alias_targets`)
> cjson: CMake 4 support

- recipes/wayland-protocols/all/conandata.yml
- recipes/wayland-protocols/all/conanfile.py
- recipes/wayland-protocols/all/test_package/conanfile.py
- recipes/wayland-protocols/config.yml
Changes to recipe:  **wayland-protocols/1.42**
Closes: https://github.com/conan-io/conan-center-index/issues/26861
* Removed usage of `VirtualBuildEnv`.
* No breaking changes: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/compare/1.36...1.42?from_project_id=2891
> wayland-protocols: Added version 1.42

- recipes/cjson/all/conanfile.py
Policy `CMP0042` was being set to `NEW` before this PR https://github.com/conan-io/conan-center-index/pull/26943
Removing that definition introduces breaking changes as `CMAKE_POLICY_VERSION_MINIMUM` (which enforces `CMP0042` to `NEW`) is only read by CMake 4.
> cjson: Restore CMP0042 policy

- recipes/chunkio/all/conanfile.py
Policy `CMP0042` was being set to `NEW` before this PR https://github.com/conan-io/conan-center-index/pull/26942/
Removing that definition introduces breaking changes as `CMAKE_POLICY_VERSION_MINIMUM` (which enforces `CMP0042` to `NEW`) is only read by CMake 4.
> chunkio: Restore CMP0042 policy

- recipes/c-blosc/all/conanfile.py
Policy `CMP0042` was being set to `NEW` before this PR https://github.com/conan-io/conan-center-index/pull/26931
Removing that definition introduces breaking changes as `CMAKE_POLICY_VERSION_MINIMUM` (which enforces `CMP0042` to `NEW`) is only read by CMake 4.
> c-blosc: Restore CMP0042 policy

- recipes/brotli/all/conanfile.py
Policy `CMP0042` was being set to `NEW` before this PR https://github.com/conan-io/conan-center-index/pull/26930/
Removing that definition introduces breaking changes as `CMAKE_POLICY_VERSION_MINIMUM` (which enforces `CMP0042` to `NEW`) is only read by CMake 4.
> brotli: Restore CMP0042 policy

- recipes/anyrpc/all/conanfile.py
Policy `CMP0042` was being set to `NEW` before this PR https://github.com/conan-io/conan-center-index/pull/26922/ 
Removing that definition introduces breaking changes as `CMAKE_POLICY_VERSION_MINIMUM` (which enforces `CMP0042` to `NEW`) is only read by CMake 4. 
> anyrpc: Restore CMP0042 policy

- recipes/capnproto/all/conanfile.py
capnproto: fixes to support CMake 4
Upstream v2 [CMakeLists.txt](https://github.com/capnproto/capnproto/blob/v2/CMakeLists.txt#L1) already supports CMake 4.
> capnproto: CMake 4 support

- recipes/cctz/all/conanfile.py
cctz: fixes to support CMake 4
Upstream master [CMakeLists.txt](https://github.com/google/cctz/blob/master/CMakeLists.txt#L3) already supports CMake 4.
> cctz: CMake 4 support

- recipes/clipper/all/conanfile.py
clipper: fixes to support CMake 4
* Added `package_type`
Deprecated library using 2.6 https://sourceforge.net/p/polyclipping/code/HEAD/tree/trunk/cpp/CMakeLists.txt#l1
> clipper: CMake 4 support

- recipes/ittapi/all/conandata.yml
- recipes/ittapi/all/conanfile.py
- recipes/ittapi/all/test_package/CMakeLists.txt
- recipes/ittapi/config.yml
Changes to recipe:  **ittapi/\***
The target name used by the Conan recipe was different from the target name in the project's official CMake installation. This PR fixes that, and adds the latest version.
The target name in the installed ittapiConfig.cmake by the project itself is `ittapi::ittnotify`, whereas Conan used `ittapi::ittapi`.
https://github.com/intel/ittapi/blob/03f7260c96d4b437d12dceee7955ebb1e30e85ad/CMakeLists.txt#L176
---
> ittapi: fix CMake target name (ittapi::ittapi → ittapi::ittnotify)

- recipes/cppcheck/all/conanfile.py
cppcheck: fixes to support CMake 4
* Increase CMake minimum required to 3.5 on versions < 2.14.0, fixing build error when using CMake 4.0
> cppcheck: CMake 4 support

- recipes/cpprestsdk/all/conanfile.py
cpprestsdk: fixes to support CMake 4
* Increase CMake minimum required to 3.5 on versions < 2.10.15, fixing build error when using CMake 4.0
> cpprestsdk: CMake 4 support

- recipes/crossdb/all/conanfile.py
crossdb: fixes to support CMake 4
* Increase CMake minimum required to 3.5 fixing build error when using CMake 4.0
> crossdb: CMake 4 support

- recipes/devil/all/conanfile.py
devil: fixes to support CMake 4
> devil: CMake 4 support

- recipes/discount/all/conanfile.py
discount: fixes to support CMake 4
> discount: CMake 4 support

- recipes/dlib/all/conanfile.py
dlib: fixes to support CMake 4
* Increase CMake minimum required to 3.5 on versions less than 19.24.2 fixing build error when using CMake 4.0
> dlib: CMake 4 support

- recipes/dsp-filters/all/conanfile.py
dsp-filters: fixes to support CMake 4
* Increase CMake minimum required to 3.5 fixing build error when using CMake 4.0
Project not maintained for 8 years https://github.com/vinniefalco/DSPFilters
Not adding version check as it is using a `cci.` version
> dsp-filters: CMake 4 support

- recipes/eastl/all/conanfile.py
eastl: fixes to support CMake 4
Version `3.21.23` not yet added to CCI does support CMake 4.
> eastl: CMake 4 support

- recipes/sol2/all/conandata.yml
- recipes/sol2/config.yml
Add version:  **sol2/3.5.0**
This was released a few weeks ago. Let's make it available through conan.
- https://github.com/ThePhD/sol2/releases/tag/v3.5.0
- https://github.com/ThePhD/sol2/commit/9190880c593dfb018ccf5cc9729ab87739709862
- https://github.com/ThePhD/sol2/issues/1680
cc @ErniGH (as you most recently merged something in the `sol2` dir)
---
> Add sol2 version 3.5.0

- recipes/easylzma/all/conandata.yml
- recipes/easylzma/all/conanfile.py
- recipes/easylzma/all/patches/cmake4-support.patch
easylzma: fixes to support CMake 4
* Create a patch to support CMake4 avoiding old `LOCATION` usage
* Removed `CMP0026` policy as the patch already fixes the issue and the OLD flag is no longer required
* Remove `tests` from compilation
> easylzma: CMake 4 support

- recipes/enet/all/conanfile.py
enet: fixes to support CMake 4
Since `1.3.18` upstream supports CMake 4
> enet: CMake 4 support

- recipes/flann/all/conanfile.py
flann: fixes to support CMake 4
> flann: CMake 4 support

- recipes/fruit/all/conanfile.py
fruit: fixes to support CMake 4
> fruit: CMake 4 support

- recipes/bzip2/all/CMakeLists.txt
Our custom CMakeLists had a min required version of 3.4. Bumping it to 3.5 will allow this to build with CMake 4
Successful configure/build logs for CMake 4:
<details>
```
$ conan create . --version=1.0.6 -b=missing
bzip2/1.0.6: Exporting package recipe: /Users/abril/coding/conan-center-index/recipes/bzip2/all/conanfile.py
bzip2/1.0.6: exports: File 'conandata.yml' found. Exporting it...
bzip2/1.0.6: Calling export_sources()
bzip2/1.0.6: Copied 1 '.py' file: conanfile.py
bzip2/1.0.6: Copied 1 '.yml' file: conandata.yml
bzip2/1.0.6: Copied 1 '.txt' file: CMakeLists.txt
bzip2/1.0.6: Copied 1 '.patch' file: 0001-fix-sys-stat-include.patch
bzip2/1.0.6: Exported to cache folder: /Users/abril/.conan2/p/bzip2f2aa593c0cba6/e
bzip2/1.0.6: Exported: …
```
> bzip2: Add support for CMake 4

- recipes/glslang/all/conanfile.py
glslang: fixes to support CMake 4
Upstream supports CMake 4 since `1.3.224.1`.
> glslang: CMake 4 support

- recipes/gtest/all/conanfile.py
gtest: fixes to support CMake 4
Upstream supports CMake 4 since `1.12.0`.
> gtest: CMake 4 support

- recipes/http_parser/all/conanfile.py
http_parser: fixes to support CMake 4
> http_parser: CMake 4 support

- recipes/iir1/all/conanfile.py
iir1: fixes to support CMake 4
> iir1: CMake 4 support

- recipes/kcov/all/conanfile.py
kcov: fixes to support CMake 4
> kcov: CMake 4 support

- recipes/folly/all/conanfile.py
folly: fixes to support CMake 4
* Removed `is_msvc` check in `_cppstd_flag_value` as it is already checked in L169 and linter was reporting `possibly using variable 'prefix' before assignment (possibly-used-before-assignment)`
> folly: CMake 4 support

- recipes/kuba-zip/all/conanfile.py
kuba-zip: fixes to support CMake 4
> kuba-zip: CMake 4 support

- recipes/libcoro/all/conanfile.py
libcoro: fixes to support CMake 4
> libcoro: CMake 4 support

- recipes/json-c/all/conanfile.py
json-c: fixes to support CMake 4
* Disable compilation of tests and, in newer versions, the application compilation (`json_parse`) which is a demo application never installed by cmake.
> json-c: CMake 4 support

- recipes/libevent/all/conanfile.py
libevent: fixes to support CMake 4
> libevent: CMake 4 support

- recipes/libfreenect/all/conanfile.py
libfreenect: fixes to support CMake 4
> libfreenect: CMake 4 support

- recipes/libmodplug/all/conanfile.py
libmodplug: fixes to support CMake 4
> libmodplug: CMake 4 support

- recipes/mimalloc/all/conanfile.py
mimalloc: fixes to support CMake 4
> mimalloc: CMake 4 support

- recipes/mbedtls/all/conanfile.py
mbedtls: fixes to support CMake 4
> mbedtls: CMake 4 support

- recipes/lzham/all/conanfile.py
lzham: fixes to support CMake 4
> lzham: CMake 4 support

- recipes/lz4/all/conanfile.py
> lz4: CMake 4 support

- recipes/libjuice/all/conanfile.py
Changes to recipe:  **libjuice/[*]**
Closes https://github.com/conan-io/conan-center-index/issues/26979 by fixing the `package_info` of the library. The upstream CMakeLists.txt does not add a suffix to the debug configuration at any point, which was causing issues when used as a dependency in `libdatachannel` when built as debug
Upstream CMakeLists.txt does not add the suffix when building a debug configuration with msvc. It's my bad that I didn't originally detect this in the original https://github.com/conan-io/conan-center-index/pull/25993 PR, so I'm fixing it now :)
Also fixes the fact that this is a C library, but we weren't deleting the corresponding cppstd settings, and asked for a min cppstd when it's not necessary
> libjuice: Do not add a debug suffix to the library

- recipes/lzfse/all/conanfile.py
lzfse: fixes to support CMake 4
This library is no longer maintained so no need to worry about a new release
> lzfse: CMake 4 support

- recipes/libcorrect/all/conanfile.py
libcorrect: fixes to support CMake 4
* Added `package_type = "library"`. This recipe only generates a library (no apps or toolchains)
> libcorrect: CMake 4 support

- recipes/libssh2/all/conanfile.py
libssh2: fixes to support CMake 4
> libssh2: CMake 4 support

- recipes/libmikmod/all/conanfile.py
libmikmod: fixes to support CMake 4
> libmikmod: CMake 4 support

- recipes/keystone/all/conandata.yml
- recipes/keystone/all/conanfile.py
- recipes/keystone/all/patches/0.9.2-cmake4-support.patch
keystone: fixes to support CMake 4
* This recipe needed a patch to disable `CMP0051` old policy
> keystone: CMake 4 support

- recipes/detours/all/conanfile.py
Replaces restrictions on build type and runtime by warnings.
Changes to recipe:  **detours** (all versions)
For further explanation, see issue #27020
The unneeded restrictions are replaced by mere warnings, as even though there is no evidence building with dynamic runtime or with debug symbols does any harm it is not particularly testable.
One could imagine the debug build enabling certain optimizations that mess with the address calculation Detours has to do. Or maybe it has an impact on the binary section layout.
We patched the recipe locally for our use cases and did not (yet) run into any issues. Also as elaborated in #27020, our previous package manager did not have these restrictions and we used it successfully for quite a while.
---
> Detours - Replace restriction by warning

- recipes/jwt-cpp/all/conandata.yml
- recipes/jwt-cpp/config.yml
Changes to recipe:  jwt-cpp/0.7.1
New minor version has been released: https://github.com/Thalhammer/jwt-cpp/releases/tag/v0.7.1
There are several important changes, like enabling creation of cryptographic objects directly from specific JWK claims.
Full changelog: https://github.com/Thalhammer/jwt-cpp/compare/v0.7.0...v0.7.1
---
> jwt-cpp: add new version 0.7.1

- recipes/lunasvg/all/conanfile.py
lunasvg: fixes to support CMake 4
* Fix bug on following lines where `generate()` method is being called before toolchain modification. 
https://github.com/conan-io/conan-center-index/blob/3cb830010d0cf0798b1d0334a2413bf53fa3320d/recipes/lunasvg/all/conanfile.py?plain=1#L98-L102 
* Renamed `CMakeDeps` object to `deps` to avoid future confusion.
> lunasvg: CMake 4 support

- recipes/nanomsg/all/conanfile.py
nanomsg: fixes to support CMake 4
> nanomsg: CMake 4 support

- recipes/nsync/all/conanfile.py
nsync: fixes to support CMake 4
> nsync: CMake 4 support

- recipes/ode/all/conanfile.py
> ode: CMake 4 support

- recipes/pbtools/all/conanfile.py
pbtools: fixes to support CMake 4
> pbtools: CMake 4 support

- recipes/paho-mqtt-c/all/conanfile.py
paho-mqtt-c: fixes to support CMake 4
> paho-mqtt-c: CMake 4 support

- recipes/openvr/all/conanfile.py
openvr: fixes to support CMake 4
> openvr: CMake 4 support

- recipes/openblas/all/conanfile.py
openblas: fixes to support CMake 4
> openblas: CMake 4 support

- recipes/openal-soft/all/conanfile.py
- recipes/openal/all/conanfile.py
openal and openal-soft: fixes to support CMake 4
* Added `package_type = "library"`. This recipe only generates a library (no apps and toolchains)
> openal & openal-soft: CMake 4 support

- recipes/openexr/3.x/conandata.yml
- recipes/openexr/config.yml
Changes to recipe:  **openexr/3.3.3**
The newest release contains a ton of bugfixes including some buffer overflows/out of bound memory access issues.
https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.3.3
---
> OpenEXR: Add version 3.3.3

- recipes/msgpack23/all/conandata.yml
- recipes/msgpack23/all/conanfile.py
- recipes/msgpack23/all/test_package/CMakeLists.txt
- recipes/msgpack23/all/test_package/conanfile.py
- recipes/msgpack23/all/test_package/test_package.cpp
- recipes/msgpack23/config.yml
Changes to recipe:  **msgpack23/2.0**
Add a new library for MessagePack based on the C++23 standard.
Add a new library that supports serialization and deserialization of the MessagePack standard.
---
> msgpack23: add version 2.1

- recipes/picobench/all/conanfile.py
picobench: fixes to support CMake 4
> picobench: CMake 4 support

- recipes/qt/5.x.x/conandata.yml
- recipes/qt/5.x.x/conanfile.py
Specify library name and version:  **qt/5.15**
* ~Added a patch for QTBUG-117073 : QtWebEngine build error for msvc 2022~ Done in https://github.com/conan-io/conan-center-index/pull/24826 and part of the last 5.15.16
* Defined QT_NO_DEBUG for non Debug build
* ~Added missing private modules for Quick~ (done in https://github.com/conan-io/conan-center-index/pull/19082)  and Scxml
* Add support to use mariadb-connector-c  as sql backend instead of libmysqlclient
---
> Qt5 various fixes

- recipes/log4cxx/all/conandata.yml
- recipes/log4cxx/config.yml
Changes to recipe:  log4cxx - none
log4cxx 1.4.0 was released a month ago - see [release notes](https://logging.apache.org/log4cxx/1.4.0/changelog.html#rel_1_4_0) for changes
Add version 1.4.0 
---
> log4cxx: add 1.4.0

- recipes/minhook/all/conandata.yml
- recipes/minhook/config.yml
Changes to recipe:  **minhook/1.3.4**
The one currently available in Conan is slightly outdated. There's a been a few commits that were pushed since then, one of which mitigates an issue related to multithreaded programs.
Nothing significant. Just adding a new snapshot to use.
---
> minhook: Adds latest version (v1.3.4)

- recipes/pro-mdnsd/all/conanfile.py
pro-mdnsd: fixes to support CMake 4
* Removed legacy generator code
> pro-mdnsd: CMake 4 support

- recipes/pybind11/all/conanfile.py
pybind11: fixes to support CMake 4
> pybind11: CMake 4 support

- recipes/roaring/all/conanfile.py
roaring: fixes to support CMake 4
> roaring: CMake 4 support

- recipes/sbp/all/conanfile.py
> sbp: CMake 4 support

- recipes/norm/all/conandata.yml
- recipes/norm/all/conanfile.py
- recipes/norm/all/patches/0004-cmake4-support.patch
norm: fixes to support CMake 4
Created a new patch file which increases `cmake_minimum_required` on `protolib/CMakeLists.txt` submodule to 3.5, minimum version supporting CMake 4
There is only one version in CCI, so updating `required_conan_version` will no compile more versions than needed `1.5.9`
> norm: CMake 4 support

- recipes/zserio/all/conanfile.py
zserio: fixes to support CMake 4
> zserio: CMake 4 support

- recipes/zopfli/all/conanfile.py
zopfli: fixes to support CMake 4
> zopfli: CMake 4 support

- recipes/xxhash/all/conanfile.py
xxhash: fixes to support CMake 4
> xxhash: CMake 4 support

- recipes/xlsxio/all/conanfile.py
xlsxio: fixes to support CMake 4
> xlsxio: CMake 4 support

- recipes/vorbis/all/conanfile.py
vorbis: fixes to support CMake 4
> vorbis: CMake 4 support

- recipes/utf8proc/all/conanfile.py
utf8proc: fixes to support CMake 4
> utf8proc: CMake 4 support

- recipes/uncrustify/all/conanfile.py
uncrustify: fixes to support CMake 4
> uncrustify: CMake 4 support

- recipes/snappy/all/conanfile.py
snappy: fixes to support CMake 4
> snappy: CMake 4 support

- recipes/tinyply/all/conanfile.py
tinyply: fixes to support CMake 4
* Changed license to tuple (linter)
> tinyply: CMake 4 support

- recipes/tiny-aes-c/all/conanfile.py
tiny-aes-c: fixes to support CMake 4
* Added missing `package_type = "library"`. This recipe only packages a library and no binary
Upstream `master` branch already supports CMake 4, but no release has been published since 2019
I've created an issue requesting a new release here https://github.com/kokke/tiny-AES-c/issues/238
It is expected that if a new release is published, it will have `master` changes. This explains the conditional statement.
> tiny-aes-c: CMake 4 support

- recipes/xlnt/all/conanfile.py
xlnt: fixes to support CMake 4
> xlnt: CMake 4 support

- recipes/tcsbank-uri-template/all/conanfile.py
tcsbank-uri-template: fixes to support CMake 4
Archive project https://github.com/Tinkoff/uri-template
> tcsbank-uri-template: CMake 4 support

- recipes/tmxlite/all/conanfile.py
tmxlite: fixes to support CMake 4
~Depends on https://github.com/conan-io/conan-center-index/pull/27115 if compiling with CMake 4~
> tmxlite: CMake 4 support

- recipes/miniz/all/conanfile.py
miniz: fixes to support CMake 4
Upstream `master` branch already supports CMake 4: https://github.com/richgel999/miniz/blob/master/CMakeLists.txt#L1A new version with those changes has not been released yet.
> miniz: CMake 4 support

- recipes/systemc/all/conanfile.py
systemc: fixes to support CMake 4
> systemc: CMake 4 support

- recipes/serial/all/conanfile.py
serial: fixes to support CMake 4
Even though CCI has a custom `CMakeLists.txt` with a greater `cmake_minimum_required` than needed for CMake 4.
That `CMakeLists.txt` is calling [upstream `CMakeLists.txt`](https://github.com/wjwwood/serial/blob/main/CMakeLists.txt#L1) which is still in 2.8 and have not been updated for 6 years
> serial: CMake 4 support

- recipes/seasocks/all/conanfile.py
seasocks: fixes to support CMake 4
* Added `library` as `package_type`. This recipe does not package any executable
> seasocks: CMake 4 support

- recipes/muparserx/all/conanfile.py
muparserx: fixes to support CMake 4
* master branch already in 3.17 https://github.com/beltoforion/muparserx/commit/c605872591d542e1630e3fcc4b292d8a0702acd2
* Extra: added validate method on old version (`4.0.8`) explicitly requiring a maximum `cppstd` version of 14 as `std::binary_function` was removed in C++17. See  https://en.cppreference.com/w/cpp/utility/functional/binary_function
See usage in upstream code: https://github.com/beltoforion/muparserx/blob/v4.0.8/parser/suSortPred.h#L47
This function is in a header file which belongs to the API
> muparserx: CMake 4 support

- recipes/libqasm/all/conandata.yml
- recipes/libqasm/config.yml
Changes to recipe:  **libqasm/1.2.0**
`config.yml` and `conandata.yml` point to the newly created libqasm/1.2.0.
---
> libqasm: add version 1.2.0

- recipes/reflect-cpp/all/conandata.yml
- recipes/reflect-cpp/all/conanfile.py
- recipes/reflect-cpp/config.yml
Changes to recipe:  ** reflect-cpp/0.18.0**
Nothing special - just a version update.
The only details worth mentioning is that as of reflect-cpp 0.18.0, toml11 is used for the TOML support, instead of tomlplusplus. This is reflected in the conanfile.py.
---
> reflect-cpp: Add version 0.18.0

- recipes/lua/all/CMakeLists.txt
- recipes/lua/all/conanfile.py
> lua: CMake 4 support

- recipes/double-conversion/all/conanfile.py
double-conversion: fixes to support CMake 4
Already fixed on upstream https://github.com/google/double-conversion/pull/240
Version not yet released
> double-conversion: CMake 4 support

- recipes/jerryscript/all/conanfile.py
jerryscript: fixes to support CMake 4
> jerryscript: CMake 4 support

- recipes/lexbor/all/conandata.yml
- recipes/lexbor/all/conanfile.py
- recipes/lexbor/all/patches/2.1.0-0000-macos-rpath.patch
lexbor: fixes to support CMake 4
> lexbor: CMake 4 support

- recipes/libcurl/all/conanfile.py
- recipes/libcurl/all/test_package/CMakeLists.txt
Fixes all libidn usages of libcurl, it's now consumed properly
This option is on by default, but in the spirit of not breaking potential users that expect this to be off by default, I've left the default in the recipe untouched.
I'll submit compilation reports in a bit
Closes https://github.com/conan-io/conan-center-index/issues/27152
> Libcurl: libidn fixes

- recipes/yaml-cpp/all/conanfile.py
Changes to recipe:  **yaml-cpp**
Increase CMake minimum required to 3.5, fixing build error when using CMake 4.0
There is already [yaml-cpp PR](https://github.com/jbeder/yaml-cpp/pull/1351) but it's not merged yet
> Updating yaml-cpp recipe to work with CMake 4.0

- recipes/glew/all/conanfile.py
- recipes/glew/all/patches/0001-fix-cmake-2.1.0.patch
- recipes/glew/all/patches/0001-fix-cmake-2.2.0.patch
Changes to recipe:  **glew/2.2.0**
CMake 4.0 Removes compatibility with CMake < 3.5.
Increase CMake minimum required to 3.5, fixing build error when using CMake 4.0
---
> glew: CMake 4 support

- recipes/poco/all/conanfile.py
Changes to recipe:  **poco/1.13.3**
Fixes #26404
Added `_is_mingw` property.
Modified `package_info` to extend `system_libs` with `mswsock` for the `poco_net` component when building with MinGW.
This happens when building poco as a static library, when `enable_net` is set to True and when the version of poco is >= 1.13.0.
[output_before_patch.txt](https://github.com/user-attachments/files/18474075/output_before_patch.txt): Build output before applying change.
[output_after_patch.txt](https://github.com/user-attachments/files/18474077/output_after_patch.txt): Build output after applying change.
---
> [package]poco/1.13.3 Extend system_libs with mswsock for poco_net component, when building with MinGW

- recipes/z3/all/conandata.yml
- recipes/z3/all/conanfile.py
- recipes/z3/config.yml
Diff https://github.com/Z3Prover/z3/compare/z3-4.13.0...z3-4.14.1
Closes https://github.com/conan-io/conan-center-index/issues/27193
Newer clang releases fail to build older versions.
Test package logs showing that even if you compile for C++20, consuming it in C++11 is still posible:
<details>
```
======== Testing the package ========
Removing previously existing 'test_package' build folder: /Users/abril/coding/conan-center-index/recipes/z3/all/test_package/build/apple-clang-16-armv8-11-release
z3/4.14.1 (test package): Test package build: build/apple-clang-16-armv8-11-release
z3/4.14.1 (test package): Test package build folder: /Users/abril/coding/conan-center-index/recipes/z3/all/test_package/build/apple-clang-16-armv8-11-release
z3/4.14.1 (test package): Writing generators to …
```
> Add new z3 4.14.1 release, fixes newer clang versions compilations

- recipes/hiredis/all/conanfile.py
hiredis: fixes to support CMake 4
* Increase CMake minimum required to 3.7, fixing build error when using CMake 4
This follows upstream commit https://github.com/redis/hiredis/commit/138794853c6adb677e34f6003df339befc1b8a13 therefore is applied only for versions <= 1.2.0
> hiredis: CMake 4 support

- recipes/grpc/all/conanfile.py
This is needed as the new CMakeConfigDeps generator does not expect frameworks in non-apple OS,
as per @memsharded:
> The generator assumes that dependencies do not add frameworks information for other systems different than Apple, in the same way that dependencies shouldn't add any libraries, flags, pre-processor definitions, etc that don't work for other systems.
Closes https://github.com/conan-io/conan-center-index/issues/27206
> grpc: Add frameworks only when on apple os

- recipes/mfast/all/conanfile.py
- recipes/mfast/all/patches/0001-fix-cmake-1.2.2.patch
mfast: fixes to support CMake 4
Updated patch `0001-fix-cmake-1.2.2.patch` removing the `CMP0054` OLD policy behavior, which is not compatible with CMake 4.
The previous version, `1.2.1`, does not need this patch.
Upstream `master` branch already supports CMake 4 https://github.com/objectcomputing/mFAST/blob/master/CMakeLists.txt#L5 
TODO: check `std::unary_function` issue with macos compiler. 
apple-clang, compiling `1.2.1` with `gnu17` fails:
```
error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
```
This is an expected behavior as `std::binary_function` is not included in STL since `std17` …
> mfast: CMake 4 support

- recipes/cmake/binary/conandata.yml
- recipes/cmake/config.yml
Changes to recipe:  **cmake/4.0.1**
Have the latest version of CMake.
Replace CMake version 4.0.0-rc4 with version 4.0.1
---
> cmake: replace 4.0.0-rc4 with 4.0.1

- recipes/cnats/all/conandata.yml
- recipes/cnats/all/conanfile.py
- recipes/cnats/config.yml
Changes to recipe:  **cnats/3.10.1**
Nats.c introduced release 3.10.0, but there was problem about cmake definition, now it is fixed (https://github.com/nats-io/nats.c/pull/860) and releases in 3.10.1. 
I just add option for experimental API and turn off it by default. I think one CMAKE option and C definition for older versions no make sense. Of course, I think you can advice more interesting solutions (I thought about using self.version for disabling definition for older packages version, but I think it is should make recipe more readable).
P.S. add trailing comma for default opts =)
I read about Experimental - it will bail off if TLS if off, but this flag for all unstable API, and I believe we shouldn't link it with TLS option
---
> cnats: add version 3.10.1

- recipes/antlr4-cppruntime/all/conandata.yml
- recipes/antlr4-cppruntime/all/patches/0005-update-IncludeChronoForMSVC.patch
- recipes/antlr4-cppruntime/config.yml
Changes to recipe:  **antlr4-cppruntime/4.13.2**
- Upgrade to the runtime library to 4.13.2.
- Fix the compiler errors reported by Visual Studio 2022 v17.13 (MSVC 19.43.34808).
- This is done by providing a patch, which applies to 4.9.3, 4.10.x, 4.11.x, 4.12.x and 4.13.x.
Related PR: https://github.com/antlr/antlr4/pull/4738
Related Issue: https://github.com/antlr/antlr4/issues/4784
---
> antlr4-cppruntime: Upgrade to 4.13.2 and Fix the compiler errors reported by MSVC 19.43.34808

- recipes/nasm/all/conandata.yml
- recipes/nasm/config.yml
Changes to recipe:  **nasm/***
* nasm.us is down
* Pointing to new server available
* Stop publishing new revisions for older version
Supersed: https://github.com/conan-io/conan-center-index/pull/27279 https://github.com/conan-io/conan-center-index/pull/27294
Closes: https://github.com/conan-io/conan-center-index/issues/27266
> nasm: Update download URLs, stop publishing new revisions for older version 

- recipes/linux-headers-generic/all/conanfile.py
Changes to recipe:  **linux-headers-generic/6.5.9**
closes #27205
From https://github.com/torvalds/linux/blob/v6.14/Makefile:
> When performing cross compilation for other architectures ARCH shall be set
> to the target architecture. (See arch/* for the possibilities).
> ARCH can be set during invocation of make:
> make ARCH=arm64
> Another way is to have ARCH set in the environment.
> The default ARCH is the host where make is executed.
When generating for same arch (x86_64) vs cross-building to armv8, we have several header files with different content:
```
diff -q -r /home/uilian/.conan2/p/b/linuxbc0bc2d267420/p/include /home/uilian/.conan2/p/b/linux943683da64fec/p/include/
Only in /home/uilian/.conan2/p/b/linuxbc0bc2d267420/p/include/asm: amd_hsmp.h
Only in …
```
> [linux-headers-generic] Pass ARCH when cross-building

- recipes/onetbb/all/conanfile.py
Add missing onetbb support for CMake 4 that was missed in the initial pass
See https://github.com/conan-io/conan-center-index/issues/26878
> onetbb: Add CMake 4 support for onetbb

- recipes/libcurl/all/conanfile.py
- recipes/libcurl/all/lib_Makefile_add.am
Changes to recipe:  **libcurl/8.12.1**
It's possible to use Conan to cross-compile libcurl from Linux to Windows with a few adjustments!
I'm able to reproduce the reported scenario #27212 as I commented [here](https://github.com/conan-io/conan-center-index/issues/27212#issuecomment-2802334662).
fix #27212
/cc @gim
To be able to build it, I used Arch Linux and installed MinGW GCC 14.2.0 with `pacman -S mingw-w64-gcc mingw-w64-headers`
The `lib_Makefile_add.am` need to be consumed in order to generate the .dll files. 
The RC ?= allows passing `x86_64-w64-mingw32-windres` as executable, otherwise, will only look for `windres` in the system.
Consuming `LIBCURL_PC_LIBS_PRIVATE` links to dependencies:
```
LIBCURL_PC_LIBS_PRIVATE = -lbcrypt -ladvapi32 -lcrypt32 -lssl -lcrypto -lgdi32 -lz -lssl …
```
> [libcurl] Allow cross-building from Linux to Windows with mingw

- recipes/libidn2/all/conandata.yml
- recipes/libidn2/config.yml
Changes to recipe:  **libidn2/2.3.8**
This PR is a replacement for #27305
fixes https://github.com/conan-io/conan-center-index/issues/27192
As commented [here](https://github.com/conan-io/conan-center-index/pull/27305#issue-3019851684), enforcing pre-defined values for build and host may result in side-effects for users that are cross-building the project. 
Plus, since the version 2.3.5 there is a rule for "*-windows", which covers the triplet i686-unknown-windows.
This PR was tested cross-building to x86 on Windows: [libidn2-2.3.8-windows-x86.log](https://github.com/user-attachments/files/19909803/libidn2-2.3.8-windows-x86.log)
And its dumpbin result proves be x86 as well: [libidn2-headers.log](https://github.com/user-attachments/files/19909900/libidn2-headers.log)
The only observation …
> [libidn2] Bump version to 2.3.8

- recipes/zeus_expected/all/conandata.yml
- recipes/zeus_expected/config.yml
Changes to recipe:  **zeus_expected/1.3.0**
Add a new upstream version.
https://github.com/zeus-cpp/expected/releases/tag/v1.3.0
---
> zeus_expected: add version 1.3.0

- recipes/libpng/all/conandata.yml
- recipes/libpng/config.yml
Changes to recipe:  **libpng/1.6.48**
Add a new version of libpng - 1.6.48
new version of libpng
add 1.6.48 using the hash from the release announcement
---
> Add a new version of libpng - 1.6.48

- recipes/libiconv/all/conandata.yml
- recipes/libiconv/config.yml
Changes to recipe:  **libiconv/1.18**
Add latest version of libiconv
Fixes compilation error when using GCC 15
Fixes #27265
Add latest version of libiconv
---
> package(libiconv): Update libiconv to 1.18 to fix gcc 15 compile

- recipes/boost/all/conanfile.py
- recipes/boost/all/test_package/CMakeLists.txt
Changes to recipe:  **boost/1.87.0+**
Boost fails to build on Conan since 1.87.0 on Emscripten with:
boost/1.87.0: WARN: Boost component 'math_c99l' is missing libraries. Try building boost with '-o boost:without_math_c99l'. (Option is not guaranteed to exist)
boost/1.87.0: WARN: Boost component 'math_tr1l' is missing libraries. Try building boost with '-o boost:without_math_tr1l'. (Option is not guaranteed to exist)
ERROR: boost/1.87.0: Error in package_info() method, line 2011
raise ConanException(f"These libraries were expected to be built, but were not built: {non_built}")
ConanException: These libraries were expected to be built, but were not built: {'boost_math_c99l', 'boost_math_tr1l'}
The [boost math patch notes](https://github.com/boostorg/math/releases/tag/boost-1.87.0) mention: …
> [boost] math: 1.87.0 no longer builds long double variants on Emscripten

- recipes/asio/all/conandata.yml
- recipes/asio/all/test_package/CMakeLists.txt
- recipes/asio/all/test_package/test_package.cpp
- recipes/asio/config.yml
Changes to recipe:  **asio/[1.34.2]**
add new version
1. add version 1.34.2
2. ~add platform check for win10 build(asio rely on windows sdk)~
3. fix test_package.cpp as 1.34.2 has removed io_service, which has been deprecated from several versions ago
---
> add asio_1.34.2

- recipes/gklib/all/patches/004-increase-minimum-cmakelists.patch
Since CMake 4.0 has dropped compatibility with version < 3.5, this needs to be updated.
I don't expect this to break anything (but haven't thoroughly tested).
Changes to recipe:  **gklib/5.1.1**
---
>  gklib: CMake 4 support

- recipes/libxslt/all/conandata.yml
- recipes/libxslt/all/conanfile.py
- recipes/libxslt/config.yml
* Changes to recipe:  **libxslt: Add version 1.1.43**
New upstream releases, known security vulnerabilities
* libxslt
* https://gitlab.gnome.org/GNOME/libxslt/-/tags
* https://gitlab.gnome.org/GNOME/libxslt/-/commits/master
* https://download.gnome.org/sources/libxslt/1.1/
Version bumps
---
> libxslt: Add version 1.1.43 (CVE-2025-24855, CVE-2024-55549)

- recipes/libxml2/all/conandata.yml
- recipes/libxml2/config.yml
Changes to recipe: libxml2: Add version 2.13.8
New upstream releases, known security vulnerabilities
libxml2
https://gitlab.gnome.org/GNOME/libxml2/-/tags
https://download.gnome.org/sources/libxml2/2.13/
---
> libxml2: Add version 2.13.8 (CVE-2025-32414, CVE-2025-32415)

- recipes/ffmpeg/all/conanfile.py
Changes to recipe:  **recipes/ffmpeg/all/conanfile.py**
'fontconfig', 'freetype', and 'harbuzz' are required configurations for the drawtext avfilter. 'fribidi' is optional but can improve rendering. https://ffmpeg.org/ffmpeg-filters.html#drawtext-1
This PR updates the FFmpeg conan recipe so the following configurations can be enabled: 'fontconfig', 'freetype', 'harfbuzz', 'fribidi'.
https://github.com/conan-io/conan-center-index/issues/22578
---
> recipes/ffmpeg/all/conanfile.py: support drawtext avfilter

- recipes/xtl/all/conandata.yml
- recipes/xtl/all/conanfile.py
- recipes/xtl/all/test_package/CMakeLists.txt
- recipes/xtl/all/test_package/test_package.cpp
- recipes/xtl/config.yml
Add version:  **xtl/0.8.0**
This version will be required for bumping the xtensor version to 0.26.0.
The version 0.8.0 required some changes to the conanfile.py. Starting from this version a cppstd >= 17 is required. This also means, that newer compiler versions will be required. I took those exact versions from the cppreference and looked at other packages that use cppstd >= 17.
Further, the xvariant header was removed from that version. So the test_package was updated to test with xoptional instead, which is available in every version.
---
> Add xtl 0.8.0 version

- recipes/xsimd/all/conandata.yml
- recipes/xsimd/config.yml
Add version:  **xsimd/13.2.0**
This version will be required for bumping the xtensor version to 0.26.0.
This just adds the latest version of `xsimd` to the conan registry.
---
> Add xsimd 13.2.0 version

- recipes/taskflow/all/conandata.yml
- recipes/taskflow/config.yml
Changes to recipe:  **taskflow/3.10.0**
This release improves scheduling performance through optimized work-stealing threshold tuning and a constrained decentralized buffer. It also introduces index-range-based parallel-for and parallel-reduction algorithms and modifies subflow tasking behavior to significantly enhance the performance of recursive parallelism.
- [Changes](https://taskflow.github.io/taskflow/release-3-10-0.html)
- [Diff](https://github.com/taskflow/taskflow/compare/v3.9.0...v3.10.0)
---
> taskflow: add version 3.10.0

- recipes/autoconf/all/conanfile.py
Avoids compatibility issues between Windows and Linux.
Changes to recipe:  **autoconf**
Not including `os` information in the package means that packages built on Linux and Windows mix up, with same package ID and different package revisions. The most recent one will then be pulled from the remote and used, but they might actually not be fully compatible between OSes. In our case the Windows-built version did not have the executable flag set on the scripts in `bin/`, this caused issues when using the package in a Linux environment.
The symptoms were similar to https://github.com/conan-io/conan/issues/14345, so we initially thought the problem happened in decompressing the package files.
Just keep the `os` information, it causes minimal duplication and it makes sure the package works in …
> autoconf: Do not clear "os" from package info

- recipes/catch2/3.x.x/conandata.yml
- recipes/catch2/config.yml
Changes to recipe:  **catch2/3.8.1**
Version bump
https://github.com/catchorg/Catch2/compare/v3.8.0...v3.8.1
config.yml and conandata.yml point to the newly created catch2/3.8.1.
---
> Add catch2/3.8.1

- recipes/easyloggingpp/all/conanfile.py
Changes to recipe:  **easyloggingpp/9.97.1**
This fixes a few bugs in the current recipe.
* Add check for C++11 or higher (the [README](https://github.com/abumq/easyloggingpp) mentions that the library requires at least C++11)
* Fix the broken option `disable_trace_logs` (this previously set the wrong define)
* Fix the broken option `enable_default_logfile` (this previously behaved in the opposite way as expected)
* Add pthread to system libs on Linux/FreeBSD if option `enable_thread_safe` is enabled (the README mentions that linking with pthread is required in this case)
This PR has been split up from https://github.com/conan-io/conan-center-index/pull/27261.
---
> easyloggingpp: various fixes

- recipes/arrow/all/conanfile.py
Changes to recipe:  **arrow/[*]**
Closes: https://github.com/conan-io/conan-center-index/issues/27420
`filesystem_layer` represents `ARROW_FILESYSTEM ` variable upstream. It is `False` by default, but I think it's worth having it as `True`.
Why:
* It does not introduce new dependencies.
* It does not introduce a new component as it's part of the `libarrow` binary. In terms of weight:
`arrow` with `filesystem_layer = True`:
```
-rw-r--r-- 1 root root 32M May 15 13:14 libarrow.a
```
`arrow` with `filesystem_layer = False`:
```
-rw-r--r-- 1 root root 30M May 15 13:30 libarrow.a
```
Notice that it only adds 2M more.
And several headers:
```
-- Installing: /root/.conan2/p/b/arrow84b75e3ac2694/p/include/arrow/filesystem/api.h
-- Installing: …
```
> arrow: `filesystem_layer = True` as default value. Removed dead code.

- recipes/c-ares/all/conandata.yml
- recipes/c-ares/config.yml
Changes to recipe:  **c-ares/[1.34.5]**
Version bump. 1.34.5 fixes CVE-2025-31498. Requested in #27225.
Adds 1.34.5.
---
> Add c-ares 1.34.5

- recipes/libsafec/all/conandata.yml
- recipes/libsafec/all/conanfile.py
- recipes/libsafec/config.yml
Changes to recipe:  **libsafec/3.9.1**
This is to make `libsafec` 3.9.1 available on conan-center-index.
- adding the URL and SHA256 of libsafec 3.9.1's source archive
- start supporting Apple Silicon by building universal binaries from 3.9.1
- build universal binaries in both x86_64 and armv8
- NOTE: all of the flags are straight from the package https://github.com/rurban/safeclib/blob/v3.9.1/README.md#userspace-library
---
> Adding libsafec 3.9.1

- recipes/ipaddress/all/conandata.yml
- recipes/ipaddress/config.yml
Changes to recipe:  **ipaddress/1.2.0**
New version 1.2.0 adds new features for working with networks.
A more detailed description of the changes:
https://github.com/VladimirShaleev/ipaddress/releases/tag/v1.2.0
---
> ipaddress: add version 1.2.0

- recipes/msys2/all/conanfile.py
Changes to recipe:  **msys2/cci.latest**
it removes the content of bin\msys64\var\cache\pacman\pkg saving more than 100MB
---
> msys2: clear package cache

- recipes/openssl/3.x.x/conanfile.py
Changes to recipe:  **openssl/3.x.x**
Fixes  #27424
Adds `-headerpad_max_install_names` behind a `is_apple_os` check in the `generate()` method of the openssl/3.x.x conanfile. This fix allows `install_name_tool` to succeed, which is called by `fix_apple_shared_install_name` in the `package()` step of the conanfile.
I validated this fix by performing the following steps:
1. Cloned my fork.
2. Added my fork as a local repository, as described [here](https://docs.conan.io/2/devops/devops_local_recipes_index.html).
3. Cleared my conan cache.
4. Ran my test command `conan install --requires openssl/3.4.1 --build=missing -o "*:shared=True"`.
---
> openssl (3.x.x): Add `-headerpad_max_install_names` to generate method so that `install_name_tool` succeeds on MacOS

- recipes/simdjson/all/conanfile.py
Changes to recipe:  **simdjson/***
Fixes #27128 
Provide cppstd through SIMDJSON_CXX_STANDARD that overrides CMAKE_CXX_STANDARD from CMakeToolchain.
---
> simdjson: fix cppstd

- recipes/xtensor/all/conandata.yml
- recipes/xtensor/all/conanfile.py
- recipes/xtensor/all/test_package/CMakeLists.txt
- recipes/xtensor/all/test_package/test_package.cpp
- recipes/xtensor/config.yml
Add version:  **xtensor/0.26.0**
This version adds support for clang 19 and above.
The version 0.26.0 required some changes to the conanfile.py. Starting from this version a cppstd >= 17 is required. This also means, that newer compiler versions will be required. I took those exact versions from the cppreference and looked at other packages that use cppstd >= 17.
Further, code was restructured between this and the last version and with that include paths changed. The changes to the test_package make sure that the test still works with all versions.
Requires:
- https://github.com/conan-io/conan-center-index/pull/27016
- https://github.com/conan-io/conan-center-index/pull/27019
---
> Add xtensor 0.26.0 version

- recipes/console_bridge/all/conanfile.py
console_bridge: fixes to support CMake 4
Increase CMake minimum required to 3.5, fixing build error when using CMake 4.0
An issue has been created regarding this: https://github.com/ros/console_bridge/issues/100
However, considering the date of the last commit, I think it's reasonable to fix the recipe.
---
> console_bridge: CMake 4 support

- recipes/fast_float/all/conandata.yml
- recipes/fast_float/config.yml
Changes to recipe:  **fast_float/8.0.2**
There are several improvements since 8.0.0.
https://github.com/fastfloat/fast_float/releases/tag/v8.0.2
https://github.com/fastfloat/fast_float/releases/tag/v8.0.1
---
> fast_float: add version 8.0.2

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/all/conanfile.py
- recipes/wasmtime/config.yml
Changes to recipe:  **wasmtime/31.0.0**
There are lots of releases since 21.0.0.
https://github.com/bytecodealliance/wasmtime/releases/tag/v31.0.0
https://github.com/bytecodealliance/wasmtime/compare/v21.0.0...v31.0.0
---
> wasmtime: add version 31.0.0

- recipes/clipper2/all/conandata.yml
- recipes/clipper2/config.yml
Changes to recipe:  **clipper2/1.5.3**
There are lots of bugfixes since 1.4.0.
https://github.com/AngusJohnson/Clipper2/releases/tag/Clipper2_1.5.3
---
> clipper2: add version 1.5.3

- recipes/hdf5/all/conandata.yml
- recipes/hdf5/config.yml
Changes to recipe:  **hdf5/1.14.6**
#27544 
The HDF5 introduced a bug with 1.14.4 & 1.14.5 for Windows with the handling of UTF-8 file names. 
The 1.14.6 fixes it.
Only added the 1.14.6, no changes to the recipe itself.
---
> hdf5: add version 1.14.6

- recipes/libffi/all/conandata.yml
- recipes/libffi/all/patches/0002-3.4.8-fix-libtool-path.patch
- recipes/libffi/all/patches/0004-3.4.8-fix-complex-type-msvc.patch
- recipes/libffi/all/patches/0006-3.4.8-library-no-version-suffix.patch
- recipes/libffi/all/patches/0008-3.4.4-invalid-CFI-advance_loc.patch
- recipes/libffi/all/patches/0008-3.4.6-invalid-CFI-advance_loc.patch
- recipes/libffi/config.yml
New version libffi/3.4.8
patch from: https://github.com/libffi/libffi/pull/857
close: https://github.com/conan-io/conan-center-index/issues/27533
https://github.com/libffi/libffi/releases/tag/v3.4.8
https://github.com/libffi/libffi/compare/v3.4.6...v3.4.8
> add new version libffi/3.4.8

- recipes/bitserializer/all/conandata.yml
- recipes/bitserializer/all/conanfile.py
- recipes/bitserializer/all/test_package/conanfile.py
- recipes/bitserializer/config.yml
Changes to recipe:  **bitserializer/0.80**
New version of BitSerializer 0.80 has been released ([Release notes](https://github.com/PavelKisliak/BitSerializer/releases)).
- Add new version of library to recipe
- Remove too old versions (allows to simplify the recipe a bit)
- Remove support of "cmake_find_package*" generators
---
> bitserializer: add version 0.80

- recipes/tiledb/all/conandata.yml
- recipes/tiledb/all/conanfile.py
- recipes/tiledb/config.yml
Changes to recipe:  **tiledb/***
There are several new features in 2.27.0.
https://github.com/TileDB-Inc/TileDB/releases/tag/2.27.0
---
> tiledb: add version 2.28.0

- recipes/sparrow/all/conandata.yml
- recipes/sparrow/all/conanfile.py
- recipes/sparrow/config.yml
Changes to recipe:  **arcticdb-sparrow/0.6.0**
Add version 0.6.0
Add version 0.6.0, this version is compatible with GCC 11 which was not the case with the version 0.5.0
---
> arcticdb-sparrow: add version 0.6.0

- recipes/pdfium/all/conandata.yml
- recipes/pdfium/all/conanfile.py
- recipes/pdfium/all/patches/95.0.4629-0001-include-cstdint.patch
- recipes/pdfium/all/patches/95.0.4629-0001-include-stdint.patch
Changes to recipe:  **pdfium/95.0.4692**
The build is currently broken on newer versions of gcc because of a missing include. See #23529
- Added a patch to introduce the missing include.
- Also added the code for applying patches. 
fixes #23529
---
- [ x ] Read the [contributing guidelines](https://github.com/conan-io/conan-center-index/blob/master/CONTRIBUTING.md)
- [ x ] Checked that this PR is not a duplicate: [list of PRs by recipe](https://github.com/conan-io/conan-center-index/discussions/24240)
- [ x ] Tested locally with at least one configuration using a recent version of Conan
> Fix pdfium build on new versions of gcc

- recipes/gmp/all/conandata.yml
- recipes/gmp/all/patches/cpp23-unprototyped-functions.patch
Changes to recipe:  **gmp/6.3.0**
Adds patch to fix building on C++ 23.
fixes #27451
C++ 23 changed the function declaration syntax such that:
void g(){}
no longer means, function with unknown parameters and now reads as function that takes no parameters. Therefore in C++ 23:
void g(){}
is no equivalent to 
void g(void){}
Current GMP relies on this in a single test, causing the build to fail if compiled from source on C++ 23, as seen in the [mailing list](https://gmplib.org/list-archives/gmp-bugs/2024-November/005550.html)
Add a patch to correctly define the function using the new declaration syntax
---
>  gmp: add patch to fix build error on cpp 23 due to removal of unprototyped functions

- recipes/pro-mdnsd/all/conanfile.py
Changes to recipe:  **pro-mdnsd/***
configurable logging level (as in recipe open62541)
new option `logging_level` - see open62541
Loglevels: https://github.com/Pro/mdnsd/blob/bae3748287558cb06d9aa46a191c2c04153bea29/libmdnsd/mdnsd.h#L22
---
> pro-mdnsd: Add option logging_level

- recipes/soci/all/conanfile.py
Fix regression introduced in https://github.com/conan-io/conan-center-index/pull/27513
Fixes error:
```
soci/4.0.3: RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan2/p/b/soci75a423422f08d/p" -DCMAKE_POLICY_DEFAULT_CMP0042="NEW" -DSOCI_SHARED="OFF" -DSOCI_STATIC="ON" -DSOCI_TESTS="OFF" -DSOCI_CXX11="ON" -DSOCI_EMPTY="OFF" -DWITH_SQLITE3="ON" -DWITH_DB2="OFF" -DWITH_ODBC="OFF" -DWITH_ORACLE="OFF" -DWITH_FIREBIRD="OFF" -DWITH_MYSQL="OFF" -DWITH_POSTGRESQL="OFF" -DWITH_BOOST="OFF" -DCMAKE_POLICY_VERSION_MINIMUM="3.5" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan2/p/b/soci75a423422f08d/b/src"
CMake Deprecation Warning at CMakeLists.txt:13 (cmake_minimum_required):
Compatibility with …
```
> soci: fix sqlite3 regression

- recipes/mbedtls/all/conandata.yml
- recipes/mbedtls/config.yml
Changes to recipe:  **mbedtls/2.28.10**
Add the final 2.28.x (old LTS) version, to minimize security issues with outdated projects still on this branch.
See https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-2.28.10
---
> Add MbedTLS 2.28.10

- recipes/cpuinfo/all/conandata.yml
- recipes/cpuinfo/config.yml
Changes to recipe:  **cpuinfo/cci.20250110**
This is the version required by onnxruntime 1.21.1 in order to build with xnnpack
https://github.com/pytorch/cpuinfo/compare/9d809924011af8ff49dadbda1499dc5193f1659c..8a1772a0c5c447df2d18edf33ec4603a8c9c04a6
---
> cpuinfo: add version cci.20250110

- recipes/extra-cmake-modules/all/conandata.yml
- recipes/extra-cmake-modules/all/conanfile.py
- recipes/extra-cmake-modules/all/patches/0001-fix-find_package-qt.patch
- recipes/extra-cmake-modules/config.yml
Changes to recipe:  **extra-cmake-modules/6.8.0**
* Added new version: 6.8.0
* Fixed `find_package` line for Qt. Added patch.
* Stopped publishing new revisions for older versions.
Conan's qt package does not define config file for each qt component, also <component>_FOUND are not defined.
For example: 
* `find_package(Qt6Core)` does not work with conan, and therefore I had to change it to `find_package(Qt6 COMPONENTS Core)`
* `Qt5Core_FOUND` is not defined by conan, and I had to change it to `if (TARGET Qt5::Core)`
---
> added extra-cmake-modules 6.8.0

- recipes/opentelemetry-proto/all/conandata.yml
- recipes/opentelemetry-proto/config.yml
opentelemetry-proto/1.7.0
* Add new version: 1.7.0
* Removed old versions, as they are no longer required by any recipe in CCI.
---
> opentelemetry-proto 1.7.0

- recipes/spirv-tools/all/conandata.yml
- recipes/spirv-tools/all/conanfile.py
- recipes/spirv-tools/all/patches/0001-fix-clang-20-build-issue.patch
Changes to recipe:  **spirv-tools/1.3.236.0+**
Trying to build the library using clang-20 results in a build issue. I submitted a PR upstream as well. If this PR is merged we can backport the fix here as well.
Before: 
The output before this PR:
```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
compiler=clang
compiler.cppstd=26
compiler.libcxx=libc++
compiler.version=20
os=Linux
[tool_requires]
*: cmake/3.31.6
[conf]
tools.cmake.cmake_layout:build_folder_vars=['settings.os', 'settings.arch', 'settings.compiler', 'settings.compiler.version']
tools.cmake.cmaketoolchain:extra_variables={'CMAKE_EXPORT_COMPILE_COMMANDS': 'TRUE', 'CMAKE_EXPERIMENTAL_CXX_IMPORT_STD': '0e5b6991-d74f-4b3d-a41c-cf096e0b2508'}
tools.cmake.cmaketoolchain:generator=Ninja …
```
> spirv-tools: backport patch to fix clang-10, fix compiler.cppstd validation

- recipes/robin-hood-hashing/all/conandata.yml
- recipes/robin-hood-hashing/all/patches/3.11.5-0001-fix-missing-stdint-include.patch
Changes to recipe:  **robin-hood-hashing/3.11.5**
Build fails with GCC 15
patch missing include
---
> robin-hood-hashing: fix missing include

- recipes/libjpeg-turbo/all/conandata.yml
- recipes/libjpeg-turbo/config.yml
Changes to recipe:  **libjpeg-turbo/all**
https://github.com/libjpeg-turbo/libjpeg-turbo/compare/3.1.0...3.1.1
---
> libjpeg-turbo: add version 3.1.1

- recipes/glibmm/all/conandata.yml
- recipes/glibmm/all/conanfile.py
- recipes/glibmm/config.yml
Changes to recipe:  **glibmm/[version]**
Added newer glibmm v2.82.0.
The newer glibmm requires glib >= 2.81.0. The dependency has been updated.
---
> glibmm: add v2.82.0.

- recipes/fastpfor/all/conandata.yml
- recipes/fastpfor/all/conanfile.py
After https://github.com/conan-io/conan-center-index/issues/27684#issuecomment-2978052628, we can confirm that the release was re-tagged and thus the checksum has changed
Closes https://github.com/conan-io/conan-center-index/issues/27684
> fastpfor: Fix sha256 for 0.2.0 after retagging

- recipes/podofo/all/conandata.yml
- recipes/podofo/all/conanfile.py
- recipes/podofo/config.yml
Adds recipe for `podofo/0.10.4`
There was a big API shift from `podofo/0.9.*` to `podofo/0.10.*` so these are very distinct versions. I would argue both should be available.
Also see https://github.com/podofo/podofo/issues/87 and https://github.com/conan-io/conan-center-index/issues/18323
Changes in `conandata.yml`:
- Add version 0.10.4, using the correct github location of source
Changes in `conanfile.py`:
- Automated formatting (I can revert if it's unwanted, it was not my intention)
- Add `with_lib_only` option, which is a shorthand for removing tools, tests, and playground
- Fix for podofo/0.9.7 when `with_openssl` is `False`
- Forced some options based on version
- Remove `PODOFO_BUILD_SHARED` with the new version, will cause configure error
- Adjust libs and defines to correctly …
> podofo: Add version 0.10.4

- recipes/boost/all/conanfile.py
Changes to recipe:  **boost/1.88.0**
When building Boost under Mac and requiring static libraries only, the resulting build will produce both static and dynamic libraries for a few Boost modules.
This reported scenario can be viewed too by the produced build in the last Boost 1.88 PR: https://c3i.jfrog.io/artifactory/cci-build-logs/cci/prod/PR-27526/3/package_build_logs/build_log_boost_1_88_0_02627a4b63c60cef7daff8b936b121ff_7a20febe5394559edf1d4111f529a5e35161a75e.success.txt
The same does not occur on Linux and Windows, only for Mac.
fixes #27604
Something changed in Boost 1.88.0. I was not able to detect the root cause. So far, I tried:
- Use the previous version of b2 (5.2.1)
- Compare Boost 1.88.0 and 1.87.0 build logs: Defines like BOOST_CHARCONV_DYN_LINK are active only in 1.88.0
I …
> [boost] Fix: Remove dynamic libs when building with static 

- recipes/sentry-native/all/conanfile.py
Changes to recipe:  **sentry-native**
Close https://github.com/conan-io/conan-center-index/issues/27718
```
conan install --requires=sentry-native/0.8.3 -o "&:qt=True" -o "&:crashpad_with_tls=openssl"
```
Gives duplicated requirement
Was introduced in https://github.com/conan-io/conan-center-index/pull/20762
> avoid duplicated requirement in sentry-native with qt=True

- recipes/protopuf/all/conanfile.py
Changes to recipe:  **protopuf/**
I've tried the library on mac os x (apple-clang-17) and it works perfectly: all tests do pass as well as library internal tests.
I asked the author to mention "os x support" in readme ( https://github.com/PragmaTwice/protopuf/issues/51 ).
The code itself has no any specifics to hardware/compiler, probably author has no access to apple hardware. 
---
> Add apple-clang support for protopuf

- recipes/libcbor/all/conandata.yml
- recipes/libcbor/config.yml
Changes to recipe:  **libcbor/0.12.0**
Make most recent version of libcbor available. Released on May 03, 2025.
- Added url and sha256 checksum of libcbor/0.12.0 to conandata.yml
- Added version 0.12.0 to config.yml
---
> libcbor: Bump to 0.12.0

- recipes/opusfile/all/conanfile.py
Changes to recipe:  **opusfile/all**
Fixes building opusfile with `http=True` for Android
Build fails due to using C99 features but compiling in C89 mode. I've opened issue in upstream https://github.com/xiph/opusfile/issues/52 as I'm not sure what's the right way to proceed here (if I can blindly replace 89 with 99). In the recipe I replace 89 with 99 only for Android (because again I'm not sure if there will be any side effects on other platforms).
---
> opusfile: fix building for Android with http=True

- recipes/expected-lite/all/conandata.yml
- recipes/expected-lite/config.yml
Changes to recipe:  **expected-lite/0.9.0**
There is a new version available of expected-lite, make it available for Conan.
Added version 0.9.0 to the recipe
---
> expected-lite: add version 0.9.0

- recipes/libsigcpp/3.x.x/conandata.yml
- recipes/libsigcpp/3.x.x/patches/3.6.0-0001-libsigcpp.patch
- recipes/libsigcpp/config.yml
Changes to recipe:  **libsigcpp/3.6.0**
Straightforward version bump, except for the updating of line numbers in a patch.
---
> libsigcpp: add version 3.6.0

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
Changes to recipe:  **imgui/1.92.0**
The new version of imgui was just released adding a ton of changes to (font) rendering to improve the handling of "Retina"/High pixel density screens.
https://github.com/ocornut/imgui/releases/tag/v1.92.0
---
> Add imgui version 1.92.0

- recipes/dcmtk/all/conanfile.py
- recipes/dcmtk/all/patches/3.6.7-0001-cmake-robust-deps-handling.patch
- recipes/dcmtk/all/patches/3.6.8-0001-cmake-robust-deps-handling.patch
- recipes/dcmtk/all/patches/3.6.9-0001-cmake-robust-deps-handling.patch
* Prevent autodetection of `nsl`, which causes the test package to fail on a Linux system where nsl is not yet installed. This was only in the recipe because the autodetection was picking it up on our CI. 
* Switch to using CONFIG for libxml2 find package, as find modules will not be available moving forward (e.g. CMakeConfigDeps)
> dcmtk: small maintenance fixes

- recipes/box2d/all/conanfile.py
As reported in the linked issue, the new versions contain https://github.com/erincatto/box2d/blob/main/src/CMakeLists.txt#L88
Closes https://github.com/conan-io/conan-center-index/issues/27847
Successful debug compilation:
<details>
```
$ conan create . --version=3.1.0 -b=missing -s="&:build_type=Debug"
box2d/3.1.0: Exporting package recipe: /Users/abril/coding/conan-center-index/recipes/box2d/all/conanfile.py
box2d/3.1.0: exports: File 'conandata.yml' found. Exporting it...
box2d/3.1.0: Calling export_sources()
box2d/3.1.0: Copied 1 '.py' file: conanfile.py
box2d/3.1.0: Copied 1 '.yml' file: conandata.yml
box2d/3.1.0: Copied 1 '.patch' file: 3.1.0-0003-remove-compile-warnings-as-error.patch
box2d/3.1.0: Exported to cache folder: …
```
> box2d/3.1.0: Fix debug lib name

- recipes/soci/all/conanfile.py
Changes to recipe:  **soci/4.1.2**
4.1.2: introduced automatic way to detect LTO.
However to enable LTO soci library does not consider internal checks for supported versions, in the setup with clang-18/cmake 3.28.3 any release builds such as RelWithDebInfo/Release produce corrupted artifacts, so that final linking is failing with following:
```
/usr/bin/ld: /mnt/d/cache/wsl/conan2/b/socicef571bafca39/p/lib/libsoci_postgresql.a: error adding symbols: file format not recognized                                                       
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
4.0.3 library has SOCI_LTO equal False by default,
---
> soci/4.1.2: disable autodetect lto optimization by default to avoid issues in release builds

- recipes/libpq/meson/conanfile.py
Changes to recipe:  **libpq/17.5**
When cross-building libpq and disabling openssl for libpq 17.5, it resulted in:
```
conan create meson --version=17.5  -o "&:with_openssl=False" 
libpq/17.5: Exporting package recipe: /home/uilian/Development/conan/conan-center-index/recipes/libpq/meson/conanfile.py
libpq/17.5: exports: File 'conandata.yml' found. Exporting it...
libpq/17.5: Calling export_sources()
libpq/17.5: Copied 1 '.py' file: conanfile.py
libpq/17.5: Copied 1 '.yml' file: conandata.yml
libpq/17.5: Copied 1 '.patch' file: 17.5-pgflex-preserve-environment-variables.patch
libpq/17.5: Exported to cache folder: /home/uilian/.conan2/p/libpq07ec98de5bcfd/e
libpq/17.5: Exported: libpq/17.5#2581ed805fba78891a91aa3c759f05ac (2025-07-04 07:07:45 …
```
> [libpq] OpenSSL option is none when disabled

- recipes/libpq/meson/conanfile.py
Changes to recipe:  **libpq/17.5**
When trying to cross-build from Linux to Windows, it fails because is trying to consume `strawberry perl` on Linux, which is invalid:
```
======== Computing necessary packages ========
libpq/17.5: Forced build from source
Requirements
libpq/17.5#2581ed805fba78891a91aa3c759f05ac:30fa8dcf91a98313887a8538d67f74a70ffe118f - Build
lz4/1.9.4#652b313a0444c8b1d60d1bf9e95fb0a1:726c1053e53f5cbfb929d3ab6761995dd6db21ad#7089c881147c4690019ee9dfb5ef87fa - Cache
openssl/3.4.1#638c4c4df8ecdef1f7aa73fc0d07fde6:b88d8be022b8b697c98fbdf0a6140844b0a7e487#807add2420aa41484a1edc525c30df64 - Cache
zlib/1.3.1#b8bc2603263cf7eccbd6e17e66b0ed76:726c1053e53f5cbfb929d3ab6761995dd6db21ad#861ee0d701f44834eb69eed5b826e240 - Cache …
```
> [libpq] Add Mingw support for Linux

- recipes/mdns/all/conanfile.py
Removed incompatible pthread dependency for Android on **mdns/1.4.3**
Fix issue [#27859](https://github.com/conan-io/conan-center-index/issues/27859)
The pthread dependency on Android will cause the error `unable to find library -lpthread` because pthread is a built-in feature of Android libc (Bionic).
---
> mdns: remove pthread for Android recipe

- recipes/cmake/binary/conandata.yml
Changes to recipe:  **cmake/[3.31.8 ]**
The sha256 hash for this package introduced in #27717 is incorrect, it has an extra `3` appended to the end, making it 65 characters long instead of 64, which causes installation of this package to fail as the hash does not match the actual package hash.
Removes the extra character.
---
> Fix sha256 hash for CMake v3.31.8 for Windows armv8

- recipes/mpg123/all/conandata.yml
- recipes/mpg123/all/conanfile.py
- recipes/mpg123/config.yml
Changes to recipe:  **mpg123/1.33.0**
Fixes compilation when using gcc 15.
Update to latest version, fixing several issues in the library
Add version 1.33.0
Skip 1.32.10 since that fails to link on Windows due to using strtok_r
Remove ancient 1.26.4 since it fails on Windows using current MSVC
---
> package(mpg123): Update to 1.33.0 to fix compilation with GCC 15

- recipes/metal-cpp/all/conandata.yml
- recipes/metal-cpp/config.yml
Changes to recipe:  **metal-cpp/15.2**
New version of 15.2 supports bug fixes related to `NS::Bundle` introspection.
Link to the issue: https://developer.apple.com/forums/thread/775258
Apple does not publish detailed changelog, so unfortunately I could only refer to an issue that I've personally stumbled upon (cannot iterate over `NS::Bundle` frameworks).
---
> metal-cpp: Add version 15.2

- recipes/libtiff/all/conanfile.py
Changes to recipe:  **libtiff/4.7.0**
Related to the PR #27877. There is a conflict involving `zstd` (transitive dependency). The `libtiff` wants `zstd/1.5.5`, but `elfutils` wants `zstd/1.5.7`.
The graph conflict can be visualized by the `conan graph info`: [graph.html.txt](https://github.com/user-attachments/files/21116525/graph.html.txt)
The `zstd` in ConanCenterIndex is using version already: https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/dependencies.md#version-ranges
---
> [libtiff] Use version range for zstd

- recipes/strawberryperl/all/conanfile.py
`strawberryperl`: only binaries for x86_64 are published, but the recipe can be used on arm64 (due to emulation), to build those libraries that need it (e.g. OpenSSL)
This PR defines the `compatibility()` method so that Conan can retrieve an x86_64 when on a native arm64 build on Windows - without having to define additional settings.
close https://github.com/conan-io/conan-center-index/issues/27752
Otherwise this requires a Windows arm64 user to add:
`--settings:build=strawberryperl/*:arch=x86_64` to the CLI invocation (or its profile equivalent)
* move the architecture validation to `validate_build()` instead of `validate()` - this still prevents a binary with armv8 architecture from being created, as it can't be created
* add `compatibility()` method to allow falling back to x86_64 …
> strawberryperl: fallback to x86_64 binaries when on arm64

- recipes/msys2/all/conanfile.py
* When targetting arm64 Windows (irrespective if we are cross-building or not), install the `mingw-w64-cross-mingwarm64-gcc` package so that it contains the right tools to target that architecture. This fixes previously reported issues e.g. building libiconv on/for arm64
* Define the `compatibility()` method so allow a x86_64 package to be transparently retrieved on Windows ARM64 - this makes it possible to just download a preexisting package (or build a missing one with `--build=compatible`)
Close https://github.com/conan-io/conan-center-index/issues/26379
Close https://github.com/conan-io/conan-center-index/issues/14279
Close https://github.com/conan-io/conan-center-index/issues/25055
Close https://github.com/conan-io/conan-center-index/issues/18777
Fixes this (e.g. libiconv):
``` …
```
> msys2: improve compatibility when targetting arm64 Windows

- recipes/cppzmq/all/conandata.yml
- recipes/cppzmq/config.yml
Changes to recipe:  **cppzmq/[4.11.0]**
Recipe for cppzmq was missing the newest version of the library.
Added the newest version of cppzmq (4.11.0) to the recipe.
---
> cppzmq: add version 4.11.0

- recipes/boost/all/conanfile.py
Changes to recipe: riscv support for boost
This change aims to add support for building Boost recipes on the riscv architecture in the ConanCenter repository. By enabling Boost to work on riscv, developers targeting this platform will be able to easily include and use Boost in their projects, just as they do on other architectures.
closes https://github.com/conan-io/conan-center-index/issues/27856
This pull request updates the `recipes/boost/all/conanfile.py` file to add support for the `riscv `architecture. The changes ensure that the appropriate configurations, such as address model, architecture, ABI, and cross-building flags, are handled correctly for `riscv`.
---
> add risc-v support for boost recipe

- recipes/exiv2/all/conanfile.py
Whilst iconv is supported by exiv2 also on Windows, the maintainers have expressed that it relies on Windows APis and it is not needed: https://github.com/Exiv2/exiv2/issues/3302#issuecomment-3061542298
Changes to recipe:  **Exiv2/all**
The upstream project's documentation specifically instruct to **not** build and link against iconv for build made under Windows with Visual Studio's toolchain.
If you run this Conan recipe, it will attempt to do so, and fail to build when the libiconv `./configure` script is ran (for example under git bash) because it expect to do very UNIXy/GNU things...
See https://github.com/Exiv2/exiv2/blob/main/README.md#dependencies
And specifically https://github.com/Exiv2/exiv2/blob/main/README.md#libiconv
This patch is an attempt to fix …
> exiv2: remove unneeded libiconv dependency on Windows

- recipes/vaapi/all/conanfile.py
Changes to recipe:  **vaapi/system**
Closes: https://github.com/conan-io/conan-center-index/issues/27939
Let's set the component's name without adding the prefix `vaapi` to each `*.pc` file
Normally, vaapi's components are required without adding the lib name as prefix. For instance:
* **ffmpeg**: https://github.com/FFmpeg/FFmpeg/blob/e6af82c49895825d0cbea71e24c77be6b16571c4/configure#L7388
* **libfreenect2**: https://github.com/OpenKinect/libfreenect2/blob/fd64c5d9b214df6f6a55b4419357e51083f15d93/CMakeLists.txt#L197
* **gst-plugins-bad**: https://github.com/GStreamer/gst-plugins-bad/blob/ca8068c6d793d7aaa6f2e2cc6324fdedfe2f33fa/sys/va/meson.build#L38
In CCI, ffmpeg and libfreenect2 require vaapi components, but they are not failing because these components are already present in the …
> vaapi: Setting components pkg_config_name

- recipes/sqlite3mc/all/conandata.yml
- recipes/sqlite3mc/all/conanfile.py
- recipes/sqlite3mc/config.yml
**sqlite3mc version 2.2.2** supports the latest SQLite version 3.50.2, and includes an important bug fix affecting systems without AVX hardware support.
Version 2.2.2 includes important changes and bug fixes:
- Improved check for Apple platforms
- Improved retrieving of entropy on Apple platforms
- Support for plaintext header option for ciphers _chacha20_, _ascon128_, and _aegis_ in addition to _sqlcipher_ - very important for **iOS** applications
- Simplified specification of raw key and salt
- Fixed bug causing crashes on Linux systems without AVX support
---
> Update to SQLite3 Multiple Ciphers 2.2.3

- recipes/libxslt/all/conanfile.py
- recipes/libxslt/all/test_package/CMakeLists.txt
- Define `cmake_additional_variable_prefixes` so that variables prefixed with all upper case `LIBXSLT` are added in the generated config files, to match the legacy behaviour of https://cmake.org/cmake/help/latest/module/FindLibXslt.html
Close https://github.com/conan-io/conan-center-index/issues/27923
> libxslt: define cmake additional variable prefixes

- recipes/tsl-robin-map/all/conandata.yml
- recipes/tsl-robin-map/config.yml
Changes to recipe:  **tsl-robin-map/1.4.0**
Adds a new version, 1.4.0, of tsl-robin-map
---
> tsl-robin-map: Add version 1.4.0

- recipes/boost/all/conanfile.py
Changes to recipe:  **boost**
Boost cross compilation fails due to cross compilation args passed directly to b2 without a `compileflags=` prefix.
Closes #27483
---
> boost: fix arm cross compilation

- recipes/m4/all/test_package/conanfile.py
- recipes/ninja/all/test_package/conanfile.py
Ensure the built reference is tested, rather than potentially a different one that matches the build profile.
> ninja and m4: fix test package when cross building

- recipes/libpq/all/conanfile.py
Need to address this properly in the latest version, and move all downstream recipes to use newer libpq instead, so this is just an interim solution on the legacy build system.
> legacy libpq 15.x: support Windows arm64

- recipes/vulkan-validationlayers/all/conanfile.py
The recipe currently tries to copy the config file generated for spirv-tools so that upstream can do `find_package(SPIRV-Tools-opt)`, as the current recipe for spriv-tools only generates one filename.
Instead of copying files, patch the find_packages out and assume that all necessary targets come from the global file for spirv-tools `find_package(SPIRV-Tools REQUIRED CONFIG QUIET)`.
(Note that [CMAKE_DISABLE_FIND_PACKAGE_<PackageName>](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html#variable:CMAKE_DISABLE_FIND_PACKAGE_%3CPackageName%3E) is not usable here as all `SPIRV-Tools-opt` calls have a `REQUIRED` attribute, so we can't easily disable it)
Closes https://github.com/conan-io/conan-center-index/issues/27170
> vulkan-validationlayers: Fix compilation with CMakeConfigDeps

- recipes/influxdb-cxx/all/conandata.yml
- recipes/influxdb-cxx/all/conanfile.py
- recipes/influxdb-cxx/all/test_package/CMakeLists.txt
- recipes/influxdb-cxx/config.yml
Changes to recipe:  **influxdb-cxx/**
Discussion: https://github.com/conan-io/conan-center-index/discussions/28037
* Added 0.7.4 version. Stopped publishing 0.7.2 revisions.
* Requires C++20.
* Added version ranges for boost and cpr (only patches for this).
With both `shared=False` and `shared=True`
* Linux  Ubuntu noble 24.04
```ini
[settings]
arch=armv8
compiler=gcc
compiler.cppstd=gnu20
compiler.version=13
os=Linux
```
* Windows 11
```ini
[settings]
arch=armv8
compiler=msvc
compiler.cppstd=20
compiler.runtime_type=Release
compiler.version=194
os=Windows
```
* OSX 15.4.1
```ini
[settings]
arch=armv8
compiler=apple-clang
compiler.cppstd=20
compiler.libcxx=libc++ …
```
> influxdb-cxx: Added 0.7.4. Stopped publishing older version.

- recipes/cpr/all/conandata.yml
- recipes/cpr/all/patches/008-1.12.0-remove-warning-flags.patch
- recipes/cpr/all/patches/009-1.12.0-windows-msvc-runtime.patch
- recipes/cpr/config.yml
Changes to recipe:  **cpr/1.12.0**
Requested [here](https://github.com/conan-io/conan-center-index/issues/27759)
Version bump to 1.12.0 with re-use of slightly adapted patches.
They apply cleanly (now), but I haven't tested with MSVC.
---
Tested with conan 2.17.0 and gcc 11
```
Local Cache
cpr
cpr/1.12.0
revisions
b588be43c30df182c479089dbe6f1eb4 (2025-06-24 07:16:33 UTC)
packages
6fe3b8731fbd142a61a987a111c5e7b2c52e2b72
info
settings
arch: x86_64
build_type: Release
compiler: gcc
compiler.cppstd: gnu17
compiler.libcxx: libstdc++11
compiler.version: 11
os: Linux
options
fPIC: True
shared: False
signal: True
verbose_logging: False
with_ssl: openssl
requires
libcurl/8.10.Z
openssl/3.3.Z
zlib/1.3.Z
```
> Bump cpr 1.12.0

- recipes/gas-preprocessor/all/conanfile.py
Changes to recipe:  **gas-preprocessor** 
gas-preprocessor is not using the sha256 provided by the conandata
> gas-preprocessor use sha256

- recipes/sqlite3/all/CMakeLists.txt
- recipes/sqlite3/all/conandata.yml
- recipes/sqlite3/config.yml
Changes to recipe:  **sqlite3/all**
New version is available
https://sqlite.org/releaselog/3_49_2.html
https://sqlite.org/releaselog/3_50_3.html
https://github.com/sqlite/sqlite/compare/version-3.49.1...version-3.49.2
https://github.com/sqlite/sqlite/compare/version-3.49.2...version-3.50.0
https://github.com/sqlite/sqlite/compare/version-3.50.0...version-3.50.1
https://github.com/sqlite/sqlite/compare/version-3.50.1...version-3.50.2
https://github.com/sqlite/sqlite/compare/version-3.50.2...version-3.50.3
shell.c now uses functions from math.h so I've added "m" to list of libraries for executable
---
> sqlite3: add 3.49.2 and 3.50.3

- recipes/openh264/all/conandata.yml
- recipes/openh264/config.yml
Changes to recipe:  **openh264/2.6.0**
Doing Debug builds on macOS breaks my pipeline due to -Werror together with a seemingly intentional warning inside the code via pragma: https://github.com/cisco/openh264/pull/3809
Contains some more fixes but that -Werror is the one that made me update now.
https://github.com/cisco/openh264/releases/tag/v2.6.0
---
> openh264: Add version 2.6.0

- recipes/libqasm/all/conandata.yml
- recipes/libqasm/config.yml
Changes to recipe:  **libqasm/1.2.1**
`config.yml` and `conandata.yml` point to the newly created libqasm/1.2.1.
---
> libqasm: add version 1.2.1

- recipes/open62541/all/conandata.yml
Changes to recipe:  **open62541/1.4.13**
Duplicate keys fixed in conandata.yml, as pointed out by @ericLemanissier 
Removed duplicate patch_type-key in the list of patches for 1.4.13
---
> open62541: Remove duplicate patch_type-keys introduced by bump to 1.4.13

- recipes/xtensor/all/conandata.yml
- recipes/xtensor/all/conanfile.py
- recipes/xtensor/all/test_package/CMakeLists.txt
- recipes/xtensor/all/test_package/conanfile.py
- recipes/xtensor/all/test_package/test_package.cpp
- recipes/xtensor/config.yml
Closes https://github.com/conan-io/conan-center-index/issues/28105
The recipe now uses CMake to drive the installation, which allows us to generate the aggregated header in the configure step too, which was missing from the copy-file based approach.
I've simplified the requirements, as per the readme in upstream the dependencies should still be compatible if I understood it correctly
> xtensor: Use CMake to generate aggregated header

- recipes/cmaes/all/conandata.yml
- recipes/cmaes/all/conanfile.py
- recipes/cmaes/config.yml
Changes to recipe:  **cmaes/0.10.2**
Closes #28077 
This is an update to cmaes/0.10.0.
With this release the compability with Windows and CMake 4 is fixed.
Differences between v0.10.0 and v0.10.2 are:
- Support Windows
- Support CMake 4
---
> Update: cmaes 0.10.2

- recipes/libcurl/all/conanfile.py
Changes to recipe:  **libcurl/8.15.0**
libcurl can't be used on windows when schannel is enabled. System lib **secur32** isn't linked.
`libcurl.lib(curl_sspi.c.obj) : error LNK2019: unresolved external symbol __imp_InitSecurityInterfaceW referenced in function Curl_sspi_global_init`
It seems that since libcurl 8.15.0, we need to link to **secur32** when schannel/sspi is enabled.
[libcurl commit](https://github.com/curl/curl/commit/0d71b18153c8edb996738f8a362373fc72d0013b)
---
> libcurl: add missing secur32 system lib when schannel is enabled

- recipes/openblas/all/conandata.yml
- recipes/openblas/all/conanfile.py
- recipes/openblas/config.yml
New version of OpenBLAS that fixes a compilation issue with GCC 15 (OpenBLAS#5255)
Changes to recipe:  openblas/0.3.30
openblas/0.3.27 has a compilation failure with GCC 15
Add new version of OpenBLAS that fixes compilation issue.
Tested working on linux x86_64
> Add OpenBLAS version 0.3.30

- recipes/ncurses/all/conandata.yml
- recipes/ncurses/all/conanfile.py
Also cleans up the recipe.
Did not remove any version because the older ones are still used in CCI
> ncurses: Add mirror sources

- recipes/glib/all/conandata.yml
- recipes/glib/config.yml
Changes to recipe:  **glib/2.85.3**
latest version of pango requires at least glib 2.82 https://github.com/GNOME/pango/commit/7020a41a47bbdebafc79d42d70f01c542ad7a75e
---
> glib 2.85.3

- recipes/libtiff/all/conanfile.py
It was a tad too premature to increase the lower bound to `9f` - this gives us some breathing room to prevent graph conflicts, while we update the rest of the recipes
> libtiff: expand lower bound of libjpeg version range to include 9e

- docs/adding_packages/conandata_yml_format.md
In the past, the `patch_type` was introduced so that contributors could "self-certify" what type of patch it was. We think this was:
- an unnecessary burden on contributors, who had to read what's basically a decision tree laid out in text format
- unnecessary in general, as there is no actual technical motivation behind it
- misleading: patches contents MUST be reviewed either way. That is, if a contributor opens a PR and says they are backporting a fix, part of our process is to literally check the patch contents coincide with the pre-existing patch upstream. Sometimes patches need to be tweaked to be backported to a specific older version, leaving us in some weird limbo.
We have reviewed what happens in Conan Center:
- That in most cases, the `patch_description` is the same information …
> docs: reflect simplified requirements for patch meta info

- recipes/dcmtk/.gitattributes
force lf eol in dcmtk .h files
Closes #28261
> force lf eol in dcmtk .h files

- recipes/pybind11/all/conandata.yml
- recipes/pybind11/all/conanfile.py
- recipes/pybind11/all/test_package/CMakeLists.txt
- recipes/pybind11/all/test_package/conanfile.py
- recipes/pybind11/config.yml
Changes to recipe:  **pybind11/3.0.0**
Adds the latest version: https://github.com/pybind/pybind11/releases/tag/v3.0.0
The new version has been added to `config.yml` and `conandata.yml`.  
One of the patches to `tools/pybind11Common.cmake` is no longer necessary since the `if(TARGET ...)` guard logic was removed in https://github.com/pybind/pybind11/commit/28dbce4157c89219705801b06e5a94b612d611a5.
---
> pybind11: add version 3.0.0

- recipes/intrusive_shared_ptr/all/conandata.yml
- recipes/intrusive_shared_ptr/all/conanfile.py
- recipes/intrusive_shared_ptr/all/test_package/CMakeLists.txt
- recipes/intrusive_shared_ptr/all/test_package/conanfile.py
- recipes/intrusive_shared_ptr/all/test_package/src/test.cpp
- recipes/intrusive_shared_ptr/config.yml
Changes to recipe:  **intrusive_shared_ptr/1.9**
This is an initial PR for `intrusive_shared_ptr`. The library provides an intrusive reference counting smart pointer, highly configurable reference counted base class and various adapters.
This library is currently only available via vcpkg or as a Debian/Ubuntu package. Would be great to have it on Conan
---
> intrusive_shared_ptr: add new recipe

- recipes/pybind11/all/conandata.yml
- recipes/pybind11/config.yml
Changes to recipe:  **pybind11/3.0.1**
Simply adds the latest patch release: https://github.com/pybind/pybind11/releases/tag/v3.0.1
Added version 3.0.1 to `config.yml` and `conandata.yml`.
---
> pybind11: add version 3.0.1

- recipes/librdkafka/all/conandata.yml
- recipes/librdkafka/all/patches/0004-Fix_compilation_with_CMake_and_without_CURL.patch
- recipes/librdkafka/config.yml
Changes to recipe:  **librdkafka/2.11.1**
latest version of librdkafka with [bugfixes and features](https://github.com/confluentinc/librdkafka/releases)
CMakeLists.txt has not changed between 2.8.0 and 2.11.1, so re-using the patches from 2.8.0
---
> librdkafka 2.11.1

- recipes/imgui/all/conandata.yml
- recipes/imgui/config.yml
Changes to recipe:  **imgui/1.92.2b**
There have been quite a few bugfixes to the larger changeset of 1.92.0 with 1.92.1, 2 and 2b. So my suggestion is to replace it. It at least isn't used by other CCI recipes yet.
https://github.com/ocornut/imgui/releases/tag/v1.92.2b
---
> imgui: Add version 1.92.2b as a replacement for 1.92.0

- recipes/gdal/post_3.5.0/conanfile.py
Changes to recipe:  **gdal/[>=3.5.3]**
The issue #28263 points to a linkage error with libdeflate related to `port/cpl` target.
```
/usr/bin/ld: src/port/CMakeFiles/cpl.dir/cpl_compressor.cpp.o: in function `CPLGZipCompress(void const*, unsigned long, int, void*, unsigned long, unsigned long*)':
/home/uilian/.conan2/p/b/gdal9fc0454b5af40/b/src/port/cpl_compressor.cpp:786: undefined reference to `libdeflate_alloc_compressor'
/usr/bin/ld: /home/uilian/.conan2/p/b/gdal9fc0454b5af40/b/src/port/cpl_compressor.cpp:795: undefined reference to `libdeflate_gzip_compress_bound'
/usr/bin/ld: /home/uilian/.conan2/p/b/gdal9fc0454b5af40/b/src/port/cpl_compressor.cpp:803: undefined reference to `libdeflate_free_compressor'
/usr/bin/ld: /home/uilian/.conan2/p/b/gdal9fc0454b5af40/b/src/port/cpl_compressor. …
```
> [gdal] Do not patch libdeflate

- recipes/etl/all/conandata.yml
- recipes/etl/config.yml
Changes to recipe:  **etl/20.43.0**
etl has not been updated for 3 minor releases.  There is already an open PR #27558 but it seems inactive.
Add the missing minor release, `20.43.0`.
---
> Etl 20.43.0

- recipes/fontconfig/all/conanfile.py
Changes to recipe:  **meson/2.15.0**
To create a git revision of the repository that is self-contained when building fontconfig/2.15.0
This PR ensures that, in the event that a build of meson is necessary when building fontconfig/2.15.0, we are able to do that.
fixes #IssueNumber
The meson recipe was updated two weeks ago, among the changes version 1.4.0 was removed and version 1.4.1 was added. 
The requirement for meson is updated to include all versions 1.4.x.
Fixes #28286 
---
> Update fontconfig recipe meson version

- recipes/asio-grpc/all/conandata.yml
- recipes/asio-grpc/all/conanfile.py
- recipes/asio-grpc/config.yml
Changes to recipe:  asio-grpc/3.5.0
boost 1.86 has regression where bad_executor thrown, see [beast issue 1599](https://github.com/boostorg/beast/issues/1599) and [beast pr 2926](https://github.com/boostorg/beast/pull/2926).
Update boost version to 1.88. 
---
> Bump asio-grpc/3.5.0 with boost/1.88.0

- recipes/tiny-optional/all/conanfile.py
Changes to recipe:  **tiny-optional**
Close https://github.com/conan-io/conan-center-index/issues/28309
the problem is that the recipe checks the ``compiler.cppstd`` without defining ``settings = "compiler"..``
Not sure why the PR passed https://github.com/conan-io/conan-center-index/pull/26186
> tiny-optional: use compiler setting for check_min_cppstd

- recipes/poselib/all/conandata.yml
- recipes/poselib/all/conanfile.py
- recipes/poselib/config.yml
Bump version of poselib to 2.0.5
New version of poselib is out (https://github.com/PoseLib/PoseLib/releases/tag/v2.0.5) since a while back, should bump the version.
Just followed instructions here: https://github.com/conan-io/conan-center-index/blob/master/docs/bump_version.md
---
> poselib: add version 2.0.5

- recipes/wayland-protocols/all/conanfile.py
Changes to recipe:  **wayland-protocols/x** (all supported versions)
Switch to version range for meson to allow building simde. Due to #27650 the current version is no longer available so that when using CCI via the `local-recipes-index` repo type and `--build missing`, it will fail to find the meson version requested.
I use a local fork of CCI with a few changes that I depend on with `local-recipes-index`. I'm stay mostly true to CCI and today I run my somewhat monthly update to CCI and now needed to hotfix a few recipes in my branch for this.
---
> wayland-protocols: Use meson version range

- recipes/splunk-opentelemetry-cpp/all/conanfile.py
This library is no longer maintained by authors, see notice at
https://github.com/signalfx/splunk-otel-cpp/
A further commit will remove this from the master branch, however all published versions will continue to be served by the Conan Center remote.
> splunk-opentelemetry-cpp: deprecate

- recipes/yasm/all/conanfile.py
- recipes/yasm/all/patches/0001-cmake-updates.patch
fixes #27893
Changes to recipe:  **yasm/1.3.0**
When using CMake 4 building this recipe fails with an error
`Compatibility with CMake < 3.5 has been removed from CMake`
Original project has a CMake 2.4 minimum, patch increases it to 3.0. Support for newer versions of CMake, like CMake < 3.20, will probably be revoked in the future releases too.
Add a CMake version requirement, min and max, so that CMake generation succeeds.
> yasm: CMake 4 support

- recipes/sdl/3.x/conanfile.py
* The recipe was making an assumption that libusb is required by default - it is not strictly
* The handling of shared libusb requires knowing the name of the libusb shared library filename, which is only possible with CMake target introspection with the newer CMakeConfigDeps  - comment this out so that it is not attempted (irrespective of whether we have CMakeConfigDeps or not)
* Fix the logic around when libusb is available, by completely removing `_needs_libusb()`
* Set `SDL_HIDAPI_LIBUSB_SHARED` to False unconditionally - it does not mean "libusb is shared", but rather, "libusb will be runtime-loaded via dlopen()`. The build scripts will fall back to _linking_ libusb, so it will be recorded as a dependency of libsdl3 instead. 
We can reconsider these changes if they cause issues.
> sdl3: only require libusb if explicitly requested

- recipes/libyuv/all/conanfile.py
Changes to recipe:  **libyuv**
Fix version conflict in `SDL_Image`: https://github.com/conan-io/conan-center-index/pull/28361/checks?check_run_id=50030809657
> libyuv: use version range in libjpeg and mozjpeg

- recipes/cjson/all/conandata.yml
- recipes/cjson/all/conanfile.py
- recipes/cjson/config.yml
Changes to recipe:  **cjson/1.7.19**
Multiple bug fixes https://github.com/DaveGamble/cJSON/compare/v1.7.18...v1.7.19
* Fix indentation (should use spaces), see [#814](https://github.com/DaveGamble/cJSON/pull/814)
* Fix spelling errors found by CodeSpell, see [#841](https://github.com/DaveGamble/cJSON/pull/841)
* Check for NULL in cJSON_DetachItemViaPointer, fixes [#882](https://github.com/DaveGamble/cJSON/issues/882), see [#886](https://github.com/DaveGamble/cJSON/pull/886)
* Fix [#881](https://github.com/DaveGamble/cJSON/issues/881), check overlap before calling strcpy in cJSON_SetValuestring, see [#885](https://github.com/DaveGamble/cJSON/pull/885)
* Fix [#880](https://github.com/DaveGamble/cJSON/issues/880) Max recursion depth for cJSON_Duplicate to prevent stack exhaustion, see …
> cjson: add version 1.7.19

- recipes/android-ndk/all/conandata.yml
- recipes/android-ndk/config.yml
Changes to recipe:  **android-ndk/r28c**
Bump version to r28c.
---
> android-ndk: add version r28c

- recipes/libavif/all/conandata.yml
- recipes/libavif/all/patches/1.3.0-0001-disable-developer-only-codepaths.patch
- recipes/libavif/config.yml
Added the latest libavif version to be used by [SDL_Image 3.x PR](https://github.com/conan-io/conan-center-index/pull/28361)
New patch is a replica of https://github.com/perseoGI/conan-center-index/blob/master/recipes/libavif/all/patches/1.1.1-0001-disable-developer-only-codepaths.patch
> libavif: add v1.3.0

- recipes/fmt/all/conandata.yml
- recipes/fmt/config.yml
Changes to recipe:  **fmt/12.0.0** -- added new version
New fmt version has just released here https://github.com/fmtlib/fmt/releases/tag/12.0.0
Added source url and sha256 hash to conandata.yml
closes #28406
---
> fmt: add version 12.0.0

- recipes/cyrus-sasl/all/test_package/CMakeLists.txt
Changes to recipe:  **cyrus-sasl/***
fix test recipe on cmake >= 4
Currently fails with
```
cyrus-sasl/2.1.28 (test package): RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/runner/work/cocorepo/cocorepo/recipes/cyrus-sasl/all/test_package" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/runner/work/cocorepo/cocorepo/recipes/cyrus-sasl/all/test_package"
Or, add …
```
> cyrus-sasl: fix test on cmake >=4

- recipes/re2c/all/conandata.yml
- recipes/re2c/config.yml
Changes to recipe:  **re2c/4.3**
There are 3 releases since 4.0.2.
https://re2c.org/releases/release_notes.html#release-4-3
https://re2c.org/releases/release_notes.html#release-4-2
https://re2c.org/releases/release_notes.html#release-4-1
---
> re2c: add version 4.3

- recipes/rsync/all/conanfile.py
Changes to recipe:  **rsync/3.2.7**
Fix rsync broken recipe (see #28347).
The generated compilation options according to the Conan recipes are wrong (details in the ticket).
This PR fixes the recipe with the correct options for zstd and lz4.
---
> Fix rsync compilation options (#28347)

- recipes/expat/all/conandata.yml
- recipes/expat/config.yml
Fixes CVE-2025-59375 as per https://github.com/libexpat/libexpat/blob/R_2_7_2/expat/Changes
Changes to recipe:  add support for version **expat/2.7.2**
Fixes CVE-2025-59375 as per https://github.com/libexpat/libexpat/blob/R_2_7_2/expat/Changes
simple version addition
---
> [expat] Add the latest release of libexpat version 2.7.2

- recipes/cryptopp/all/test_package/CMakeLists.txt
Changes to recipe:  **cryptopp/***
fix test recipe on cmake >= 4
Currently fails with
```
cryptopp/8.9.0 (test package): RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/Users/runner/work/cocorepo/cocorepo/recipes/cryptopp/all/test_package" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/Users/runner/work/cocorepo/cocorepo/recipes/cryptopp/all/test_package"
Or, add …
```
> cryptopp: fix test on cmake >=4

- recipes/cuda-api-wrappers/all/conandata.yml
- recipes/cuda-api-wrappers/config.yml
Changes to recipe:  **cuda-api-wrappers/[0.8.1]**
Adding support for version 0.8.1
Resolving #27984 
Added `0.8.1` to `versions` list
Added `0.8.1` source and sha256 hash
---
> Updated cuda-api-wrappers with version 0.8.1

- recipes/llama-cpp/all/conandata.yml
- recipes/llama-cpp/all/conanfile.py
- recipes/llama-cpp/config.yml
Changes to recipe:  **llama-cpp/b6565**
Request: #28433
Patch no longer seems necessary, as of https://github.com/ggml-org/llama.cpp/pull/14613
---
> llama-cpp: Bump to version b6565 (#28433)

- recipes/qhull/all/conanfile.py
- recipes/qhull/all/test_package/conanfile.py
Changes to recipe:  **qhull/8.0.2**
Fixes this error when consuming `qhull/8.0.2` using `PkgConfigDeps` generator:
```bash
qhull/8.0.2 (test package): CMakeDeps necessary find_package() and targets for your CMakeLists.txt
find_package(Qhull)
target_link_libraries(... Qhull::qhullstatic_r)
qhull/8.0.2 (test package): Generator 'PkgConfigDeps' calling 'generate()'
OSError: [Errno 22] Invalid argument: 'Qhull::qhullcpp.pc'
ERROR: Error in generator 'PkgConfigDeps': [Errno 22] Invalid argument: 'Qhull::qhullcpp.pc'
```
> qhull: fix libqhullcpp PC file name

- recipes/cpprestsdk/all/conanfile.py
Changes to recipe:  **cpprestsdk/2.10.19**
fixes #27492
Boost headers are listed in public headers of cpprestsdk:
- https://github.com/microsoft/cpprestsdk/blob/v2.10.19/Release/include/cpprest/http_listener.h#L20
- https://github.com/microsoft/cpprestsdk/blob/v2.10.19/Release/include/cpprest/ws_client.h#L36
- https://github.com/microsoft/cpprestsdk/blob/v2.10.19/Release/include/cpprest/http_client.h#L68
---
> [cpprestsdk] List Boost as transitive headers

- recipes/oatpp-swagger/all/conanfile.py
Changes to recipe:  **oatpp-swagger**
Requested in https://github.com/conan-io/conan-center-index/issues/26878#issuecomment-3332651610
Upstream project already supports CMake 4 https://github.com/oatpp/oatpp-swagger/commit/13437a96936d54bb2893356c3b5e26cfb8fda341 but there is no release associated with that commit.
> oatpp-swagger: added CMake 4 support

- recipes/symengine/all/conandata.yml
- recipes/symengine/all/conanfile.py
- recipes/symengine/all/patches/0.14.0-0001-gcc15-ciso646.patch
Symengine v0.14.0 compiled with gcc>=15 emits a warning caused by including `ciso646`, which becomes an error with `-Werror`. This was fixed in symengine/symengine#2102. This fix is introduced as a patch here, as symengine has not released a new version since this fix was merged.
- Note: The patch file introduced in this PR applies symengine/symengine#2102 verbatim.
---
> Patch symengine for gcc15

- recipes/upa-url/all/conandata.yml
- recipes/upa-url/config.yml
Add new version: **upa-url/2.3.0**
Update to the latest release of the Upa URL library, which contains bug fixes and improvements.
See: https://github.com/upa-url/upa/releases/tag/v2.3.0
---
> upa-url: add version 2.3.0

- recipes/openssl/3.x.x/conandata.yml
- recipes/openssl/config.yml
Changes to recipe:  **openssl/3.5.3**
New LTS version is available
https://github.com/openssl/openssl/releases/tag/openssl-3.5.3
https://github.com/openssl/openssl/compare/openssl-3.5.2...openssl-3.5.3
---
> openssl: add version 3.5.3

- recipes/boost/all/conanfile.py
The `boost` recipe provides two targets that include the python version used at compile time, e.g. when boost is compiled with python 3.10 we get `Boost::python310` and `Boost::numpy310` But these two targets are being generated with the wrong casing on the namespace (`boost` instead of `Boost`).
Before:
```
-- Conan: Component target declared 'Boost::python'
-- Conan: Component target declared 'Boost::numpy'
-- Conan: Component target declared 'boost::python310'
-- Conan: Component target declared 'boost::numpy310'
```
After:
```
-- Conan: Component target declared 'Boost::python'
-- Conan: Component target declared 'Boost::numpy'
-- Conan: Component target declared 'Boost::python310'
-- Conan: Component target declared 'Boost::numpy310'
```
---
> Fix target names for the versioned variats of Boost::python and Boos::numpy

- recipes/openjph/all/conandata.yml
- recipes/openjph/all/conanfile.py
- recipes/openjph/all/patches/0.24.1-cmake-cxx-standard-pic.patch
- recipes/openjph/config.yml
Changes to recipe:  **openjph/0.24.1**
Fixes in aligned memory handling have been added.
No large changes since previous version but fixes for the recently introduced aligned memory handling. Main relevant change for us appears to be just that. Rest is small build changes that I have not seen relevant differences from the conan managed build perspective.
The two related releases changelogs:
* https://github.com/aous72/OpenJPH/releases/tag/0.24.0
* https://github.com/aous72/OpenJPH/releases/tag/0.24.1
---
> openjph: Update to 0.24.1

- recipes/boost/all/conanfile.py
Changes to recipe:  **boost**
-j0 is broken for boost
Happens when ``tools.build:jobs=0`` that should use the tool defaults, not add ``-j0``
Follow up from https://github.com/conan-io/conan/pull/15422
> fix boost njobs=0

- recipes/libtiff/all/conanfile.py
- recipes/libtiff/all/patches/4.5.1-0001-cmake-dependencies.patch
Changes to recipe:  **libtiff/***
I'm using libjpeg-turbo instead of libjpeg and it supports both 8 and 12-bit jpegs. So I would like libtiff to be able to handle 12-bit too.
Patch has been hardcoding value of `HAVE_JPEGTURBO_DUAL_MODE_8_12 ` to `FALSE`. But it should be `TRUE` in case of `libjpeg-turbo >= 3.0` which is already the case with current conan recipe.
`conan create . --version 4.7.0 -o libtiff/*:jpeg=libjpeg-turbo`
Before the change:
`--   JPEG 8/12 bit dual mode:            Requested:OFF Availability:FALSE Support:FALSE`
After the change:
`--   JPEG 8/12 bit dual mode:            Support: yes (libjpeg turbo >= 3.0 dual mode)`
---
> libtiff: enable HAVE_JPEGTURBO_DUAL_MODE_8_12 when using libjpeg-turbo

- recipes/gperftools/all/conandata.yml
- recipes/gperftools/config.yml
Changes to recipe:  **gperftools/2.17.2**
There was a new upstream release August this year.
Tested on macOS arm64, macOS x86_64, Linux x86_64 by building and linking tcalloc against a program of mine.
---
> gperftools: add 2.17.2

- recipes/zserio/all/conandata.yml
- recipes/zserio/config.yml
Changes to recipe:  **zserio/2.17.0**
New release 2.17.0.
The only change is the addition of the new released version 2.17.0.
---
> zserio: Add new Zserio release 2.17.0

- recipes/rocksdb/all/conanfile.py
The change was the only one missing for successfully build of rockdb on 24.04.1-Ubuntu:
```
> uname -a
Linux 5ce862dec84f 6.14.0-24-generic #24.1~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jun 26 03:59:26 UTC riscv64 riscv64 riscv64 GNU/Linux
> /home/dev/.local/bin/conan list "rocksdb:*" --cache
Found 1 pkg/version recipes matching rocksdb in local cache
Local Cache
rocksdb
rocksdb/9.7.4
revisions
763fb87b2974dcc2bb048c1cc56772b4 (2025-10-04 14:38:04 UTC)
packages
bf3d943981a31f0653ceab2c7fc80004db11644e
info
settings
arch: riscv64
build_type: Release
compiler: gcc
compiler.cppstd: 17
compiler.libcxx: libstdc++11
compiler.version: 13
os: Linux
options
enable_sse: False
fPIC: True
lite: False
shared: False
use_rtti: False
with_gflags: False
with_jemalloc: False
with_lz4: False
with_snappy: …
```
> Add riscv64 architecture support for RocksDB

- recipes/dbus-cxx/2.x.x/conandata.yml
- recipes/dbus-cxx/2.x.x/conanfile.py
- recipes/dbus-cxx/config.yml
Changes to recipe:  **dbus-cxx/[2.6.0]**
Acquire newest dbus-cxx for: https://github.com/aui-framework/aui/pull/635
Already done:
https://github.com/dbus-cxx/dbus-cxx/pull/191
https://github.com/xmake-io/xmake-repo/pull/8297
https://github.com/microsoft/vcpkg/pull/47617 In progress: https://github.com/microsoft/vcpkg/pull/47683
Adds newest dbus-cxx https://github.com/dbus-cxx/dbus-cxx/compare/2.5.2...2.6.0
---
> dbus-cxx: add version `2.6.0`

- recipes/libpcap/all/conanfile.py
Changes to recipe:  **libpcap/***
With the current recipe, libpcap grabs the system version of openssl if it is detected, because openssl is not in the requirements. Also it ends up making the build fail
cf https://github.com/the-tcpdump-group/libpcap/blob/0276de45b4a6037a31dc557a557d7b8723571d01/CMakeLists.txt#L1571
see in the log below:
`-- Found OpenSSL: optimized;C:/Program Files/OpenSSL/lib/VC/x64/MD/libcrypto.lib;debug;C:/Program Files/OpenSSL/lib/VC/x64/MDd/libcrypto.lib (found version "3.4.1")`
<details><summary>failing log</summary>
Host profile:
Build profile:
[settings]
arch=x86_64
compiler=msvc
compiler.cppstd=14
compiler.runtime_type=Release
compiler.version=194
os=Windows
[options]
*/*:shared=True
[conf] …
> libpcap: disable openssl

- recipes/wasmtime/all/conandata.yml
- recipes/wasmtime/all/conanfile.py
- recipes/wasmtime/config.yml
Changes to recipe: **wasmtime/37.0.0**
Additionally, we should include the C++ headers files too, alongside the C API ones.
Conan package includes only the C API, but not the C++ one.
https://github.com/bytecodealliance/wasmtime/releases/tag/v37.0.0
---
> Wasmtime 37.0.0

- recipes/7zip/all/conandata.yml
- recipes/7zip/config.yml
Changes to recipe:  **7zip/25.01**
CVE-2025-55188
https://www.7-zip.org/history.txt
---
> 7zip: add version 25.01

- recipes/ccfits/all/conandata.yml
Changes to recipe:  **CCfits**
Rediscover of #28353
> We are in the process of streamlining our CCfits locations on our website.
The new/future locations of the CCfits tarballs are in a new area in our website. Eventually, the old locations/symlinks will be removed.
The old shasums were the unzipped values, but in the new location, the shasum correctly reflects the zipped versions (I'm unsure how the old shasums still worked).
/cc @krutkow
> CCfits: update URLs in conandata.yml
