recipes/tinyxml2/all/CMakeLists.txt
recipes/tinyxml2/all/conanfile.py

- cache cmake configuration with lru_cache
---

tinyxml2: modernize

---

recipes/bullet3/all/CMakeLists.txt
recipes/bullet3/all/conandata.yml
recipes/bullet3/all/conanfile.py
recipes/bullet3/all/test_package/CMakeLists.txt
recipes/bullet3/all/test_package/conanfile.py
recipes/bullet3/config.yml

- CMakeDeps support
- provide official CMake variables from upstream config file
- keep `UseBullet.cmake`
- fix libs ordering, there were several issues
- enable `bullet3` option by default to honor default upstream value
- compiler=msvc support
---

bullet3: fix libs ordering + improve cmake generators + modernize

---

.github/workflows/linters.yml

The linter should match the version we are running in the CI, otherwise it might report errors (or suggestions) that might not work.
Note.- Pylint plugin is here: https://github.com/conan-io/conan/blob/develop/conans/pylint_plugin.py

[ci] Conan linter: match version running in CI

---

recipes/libxml2/all/conandata.yml
recipes/libxml2/all/conanfile.py
recipes/libxml2/config.yml

Specify library name and version:  **libxml2/2.9.13**
This version fixes the following bugs (most importantly the CVE):
- [CVE-2022-23308] Use-after-free of ID and IDREF attributes
(Thanks to Shinji Sato for the report)
- Use-after-free in xmlXIncludeCopyRange (David Kilzer)
- Fix null deref in xmlSchemaGetComponentTargetNs (huangduirong)
- Fix memory leak in xmlXPathCompNodeTest
- Fix null pointer deref in xmlStringGetNodeList
- Fix several memory leaks found by Coverity (David King)
---

libxml2: add 2.9.13

---

recipes/qt/6.x.x/conanfile.py

fixes conan-io/conan-center-index#9794
Specify library name and version:  **qt/6.*.***
---

qt6: fix usage of glib in cpp_info

---

recipes/boost/all/conanfile.py

other minor modifications:
- move few `ConanInvalidConfiguration` from `configure()` to `validate()`
- use `conan.tools.files.rename()` instead of `tools.rename()`
---

boost: compiler=msvc support + bump dependencies

---

recipes/libepoxy/all/conandata.yml
recipes/libepoxy/config.yml

Specify library name and version:  **libepoxy1.5.10**
---

libepoxy: add version 1.5.10

---

recipes/gdal/all/conandata.yml
recipes/gdal/all/patches/3.1.x/fix-include-podofo.patch
recipes/gdal/all/patches/3.2.x/fix-include-podofo.patch
recipes/gdal/all/patches/3.3.x/fix-include-podofo.patch
recipes/gdal/all/patches/3.4.x/fix-include-podofo.patch

Specify library name and version:  **gdal/3.1.0**
Fixes #9407 
---

(#9407) [gdal] fix podofo include

---

recipes/cryptopp/all/conandata.yml
recipes/cryptopp/all/patches/fix-cmake-8.6.0.patch
recipes/cryptopp/config.yml

**cryptopp/8.6.0**
added cryptopp-8.6.0, given patch of CMakeLists.txt to make it compile
---

added cryptopp-8.6.0

---

recipes/protobuf/all/CMakeLists.txt
recipes/protobuf/all/conanfile.py

- cache CMake configuration with functools.lru_cache
- rely on `conan.tools.microsoft.msvc_runtime_flag` to set vc runtime
---

protobuf: relocatable shared libs on macOS + modernize

---

recipes/librasterlite/all/conanfile.py
recipes/librasterlite/all/test_package/CMakeLists.txt
recipes/librasterlite/all/test_package/conanfile.py

- fix all shared on macOS (see https://github.com/conan-io/conan/issues/10668)
---

librasterlite: fix "all shared" on macOS + modernize

---

recipes/cpuinfo/all/CMakeLists.txt
recipes/cpuinfo/all/conandata.yml
recipes/cpuinfo/all/conanfile.py
recipes/cpuinfo/all/test_package/CMakeLists.txt
recipes/cpuinfo/all/test_package/conanfile.py
recipes/cpuinfo/config.yml

- honor `CMAKE_SYSTEM_PROCESSOR` if already set by user
- cpuinfo now provides a pkg-config file, so it's defined in package_info()
---

cpuinfo: add cci.20220228 + modernize

---

recipes/imath/all/CMakeLists.txt
recipes/imath/all/conandata.yml
recipes/imath/all/conanfile.py
recipes/imath/all/test_package/CMakeLists.txt
recipes/imath/all/test_package/conanfile.py
recipes/imath/all/test_package/test_package.cpp
recipes/imath/config.yml

Specify library name and version:  **Imath/3.1.4**
Imath is a library of utilities for working with vectors, matrices, half precision floating point numbers and alike.
Formerly, Imath was part of OpenEXR. Starting with OpenEXR 3.0, these two libraries are released independently. 
This PR is adds only Imath, [another one](https://github.com/p-podsiadly/conan-center-index/tree/openexr3) will add OpenEXR 3.1.4.
Note: the separation of OpenEXR and Imath and changes to exported CMake targets in OpenEXR 3 mean that bugs #2219 and #3464 will not affect OpenEXR 3 packages.
---

Add Imath 3.1.4

---

recipes/sqlcipher/all/conanfile.py

Specify library name and version:  **sqlcipher/4.5.1**
Update dependent libraries to openssl/1.1.1n and libressl/3.4.3.
---

sqlcipher: update dependent libraries

---

recipes/sentry-native/all/conanfile.py

Specify library name and version:  **sentry-native/0.4.15**
Adding a new option for native performance monitoring.
The option is currently set to true but I will change it to false before merging.
---

Add sentry-native performance option

---

recipes/qt/5.x.x/conanfile.py

It breaks qt compilation because the linker would have to be
overridden too, but there is no environment variable for that
fixes conan-io/conan-center-index#9857
---

qt5: ignore CC and CXX variables on MSVC

---

recipes/glew/all/CMakeLists.txt
recipes/glew/all/conanfile.py
recipes/glew/all/test_package/CMakeLists.txt

- explicit pkg-config name
---

glew: modernize

---

recipes/diligent-core/all/conanfile.py

Specify library name and version:  **diligent-core/2.5.1**
The include paths for the D3D11 and D3D12 backends were not exposed. As a result, consumers of the recipes could not use the D3D11/12 backends.
The fix is to simply add the missing include paths to `self.cpp_info` in `package_info()`.
Fixes #9811
---

fix: Direct3D includes are not exposed

---

recipes/aws-c-common/all/conandata.yml
recipes/aws-c-common/config.yml

Specify library name and version:  **aws-c-common/0.6.19**
New symbols is added in 0.6.19 which is used in aws-c-io recipe.
---

aws-c-common: add version 0.6.19

---

recipes/ffmpeg/all/conanfile.py

If SSL is enable with GPL, the build fails with output : openssl is incompatible with the gpl and --enable-nonfree is not specified.
Specify library name and version:  **ffmpeg/4.3.2**
---

FFMPEG : Enable nonfree if SSL and GPL are enable

---

recipes/wasmer/all/test_package/conanfile.py

After https://github.com/conan-io/conan-center-index/pull/9916 MacOS machines are using CMake 3.20.1. This addition shouldn´t be needed.

[wasmer] MacOS is using newer CMake

---

recipes/termcap/all/conanfile.py

I happened to find this misnamed identifier in the termcap port. I am not sure why the mistake hasn't been caught in any tests.
---

Fix defines for termcap

---

recipes/imgui/all/conandata.yml
recipes/imgui/all/conanfile.py
recipes/imgui/all/test_package/CMakeLists.txt
recipes/imgui/all/test_package/conanfile.py
recipes/imgui/all/test_package/test_package.cpp
recipes/imgui/config.yml

close #7557 
We proposed versions like `cci.20220207+docking` for the docking branch, but I'm thinking that it would be useful to include some reference to the `1.87` version, which is the matching one. Something like `cci.20220207+1.87.docking`, wdyt?
cc/ @uilianries @SSE4

[imgui] Add docking branch

---

recipes/embree3/all/conanfile.py

closes: #9808
Specify library name and version:  **embree3/all**
---

- [embree3] fix clang-cl by converting resource to UTF-8

---

recipes/expat/all/conandata.yml
recipes/expat/config.yml

Specify library name and version:  **expat/2.4.8**
Package the latest version of the expat library, version 2.4.8
---

New version of expat, 2.4.8

---

recipes/spdlog/all/conanfile.py

Specify library name and version:  **spdlog**
when use `spdlog` with option `header_only=True` for iOS, compiler produce errors.
```
In file included from /Users/xyz1001/.conan/data/spdlog/1.9.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/details/os.h:117:
/Users/xyz1001/.conan/data/spdlog/1.9.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/spdlog/details/os-inl.h:362:12: error: thread-local storage
is not supported for the current target
static thread_local const size_t tid = _thread_id();
```
---
[conan-center …

fix header only spdlog iOS build error

---

recipes/opencv/3.x/conanfile.py
recipes/opencv/3.x/test_package/CMakeLists.txt
recipes/opencv/3.x/test_package/conanfile.py
recipes/opencv/3.x/test_package/test_package.cpp
recipes/opencv/4.x/CMakeLists.txt
recipes/opencv/4.x/conanfile.py
recipes/opencv/4.x/test_package/CMakeLists.txt
recipes/opencv/4.x/test_package/conanfile.py
recipes/opencv/4.x/test_package/test_package.cpp

Specify library name and version:  **opencv/3.4.17**
In Windows, there is no need for version correspondence, multiview and numeric libraries.
---

opencv: Fixed correspondence not requiring version on Windows.

---

recipes/hidapi/all/conanfile.py
recipes/hidapi/all/test_package/conanfile.py

- compiler=msvc support
- explicitly call autoreconf from our autoconf recipe (instead of obfuscating the call through upstream bootstrap script). Also call it in `build()` instead of `_configure_autotools()` (otherwise it could be called again with `conan -kb`)
- conan 1.36 is sufficient for this recipe
I'm pretty sure that MinGW is broken by design in this recipe, but I won't fix it here.
It's also quite strange to see `pkg_config` in generators for the build, without `pkgconf` in `build_requirements()` (since there is a dependency if Linux or FreeBSD, I guess it breaks or build is fragile if build machine doesn't have pkg-config installed).
---
[conan-center hook](https://github.com/conan-io/hooks.git) …

hidapi: relocatable shared lib on macOS + modernize

---

recipes/clipper/all/CMakeLists.txt
recipes/clipper/all/conandata.yml
recipes/clipper/all/conanfile.py

- url of tarball of 4.8.8 is not persistent, it may or may not exist at a given time.  So we must force sourceforge to generate the link prior to download attempt. 
closes https://github.com/conan-io/conan-center-index/issues/9991
---

clipper: fix download of 4.8.8 tarball + relocatable shared lib on macOS

---

recipes/aws-c-http/all/conandata.yml
recipes/aws-c-http/all/conanfile.py
recipes/aws-c-http/config.yml

Specify library name and version:  **aws-c-http/0.6.13**
---

aws-c-http: add version 0.6.13 with updating dependencies

---

recipes/zlib/all/conandata.yml
recipes/zlib/all/conanfile.py
recipes/zlib/all/patches/0003-gzguts-fix-widechar-condition.patch
recipes/zlib/config.yml

Specify library name and version:  **zlib/1.2.12**
---

zlib: add version 1.2.12

---

recipes/theora/all/conanfile.py
recipes/theora/all/test_package/CMakeLists.txt
recipes/theora/all/test_package/conanfile.py

- fix all shared on macOS (see https://github.com/conan-io/conan/issues/10668)
- bump ogg
---

theora: fix all shared & relocatable shared libs on macOS + modernize

---

recipes/libnoise/all/CMakeLists.txt
recipes/libnoise/all/conanfile.py
recipes/libnoise/all/test_package/CMakeLists.txt
recipes/libnoise/all/test_package/conanfile.py

- cache CMake configuration with functools.lru_cache
- use cmake_find_package_multi in test_package
---

libnoise: modernize

---

recipes/miniz/all/CMakeLists.txt
recipes/miniz/all/conanfile.py
recipes/miniz/all/test_package/conanfile.py

- cache CMake configuration with functools.lru_cache
- use set_property()
---

miniz: modernize

---

recipes/protobuf/all/conandata.yml
recipes/protobuf/config.yml

Specify library name and version:  **protobuf/3.18.1**
This adds version 3.18.1 for protobuf. Some applications require very specific versions of protobuf so it's good to have all minor versions of protobuf available on ConanCenter.
---

Add protobuf 3.18.1

---

recipes/libpqxx/all/conandata.yml
recipes/libpqxx/all/patches/fix-install-library-symlink-7.7.2.patch
recipes/libpqxx/all/patches/fix-not-declared-dumb_stringstream-7.0.1_to_7.0.5.patch
recipes/libpqxx/all/patches/fix-not-declared-dumb_stringstream-7.0.6_to_7.0.7.patch
recipes/libpqxx/all/patches/fix-not-declared-dumb_stringstream-7.1.1.patch
recipes/libpqxx/all/patches/fix-remove-unlikely-annotation-before-return-7.6.0_to_7.6.1.patch
recipes/libpqxx/config.yml

Specify library name and version:  **libpqxx/7.7.2**
Add libpqxx new version (bugfix release).
**NOTE:** libpqxx version 7.7.1 was skipped because it is an incomplete version due to several missing commits.
This release fixes conan-io/conan-center-index#9852
---

Add libpqxx/7.7.2

---

recipes/c-dbg-macro/all/conandata.yml
recipes/c-dbg-macro/all/conanfile.py
recipes/c-dbg-macro/all/test_package/CMakeLists.txt
recipes/c-dbg-macro/all/test_package/conanfile.py
recipes/c-dbg-macro/all/test_package/test_package.c
recipes/c-dbg-macro/config.yml

Add version 0.12.1.
A few macros that prints and returns the value of a given expression
for quick and dirty debugging, inspired by Rusts dbg!(…) macro and its
C++ variant.
* dbg(expr) for primitive data types (int, float, etc.), strings and pointers.
* dbgb(expr) to force boolean true/false output.
* dbga(expr, length) for array of primitive data types.
* dbgh(expr, size) for hexdump output.
* dbge(expr) for negative error codes.
* dbgbt() for a backtrace.
Just include dbg.h in your project to use it.

c-dbg-macro: A set of dbg(…) macros for C

---

recipes/mcap/all/conandata.yml
recipes/mcap/all/conanfile.py
recipes/mcap/all/test_package/CMakeLists.txt
recipes/mcap/all/test_package/conanfile.py
recipes/mcap/all/test_package/test_package.cpp
recipes/mcap/config.yml

Hello 👋
I'm part of a team developing a file format, [MCAP](https://github.com/foxglove/mcap), and we would like the C++ reader/writer libraries to be available on ConanCenter. This is the first published version of the package, which is a header-only library, with dependencies on `fmt`, `lz4`, and `zstd`.
Closes https://github.com/foxglove/mcap/issues/201
---

mcap: add version 0.1.0

---

recipes/clove-unit/all/conandata.yml
recipes/clove-unit/all/conanfile.py
recipes/clove-unit/all/test_package/CMakeLists.txt
recipes/clove-unit/all/test_package/conanfile.py
recipes/clove-unit/all/test_package/test_package.cpp
recipes/clove-unit/config.yml

Specify library name and version:  **clove-unit/2.2.3**
I'm the author of the library. It is a single-header unit testing librarary for both C and C++
---

clove-unit: add version 2.2.3

---

recipes/libffi/all/conanfile.py

Specify library name and version:  **libffi/3.4.2@**
closes: #9954
---

fix windows clang compilation for ffi

---

recipes/onnx/all/conandata.yml
recipes/onnx/all/conanfile.py
recipes/onnx/all/patches/0001-fix-concurrent-proto3-remove-1.11.0.patch
recipes/onnx/config.yml

Specify library name and version:  **onnx/1.11.0**
This adds support for the latest version 1.11.0 of onnx.
---

Add onnx 1.11.0

---

recipes/assimp/5.x/CMakeLists.txt
recipes/assimp/5.x/conanfile.py
recipes/assimp/5.x/test_package/conanfile.py

- bump clipper to 4.10.0: sha256 of clipper/4.8.8 tarball always changes, the one of 4.10.0 is stable.
- bump minizip & zlib
closes https://github.com/conan-io/conan-center-index/issues/10032
---

assimp: bump clipper, minizip & zlib + modernize

---

recipes/cli11/all/conandata.yml
recipes/cli11/config.yml

Specify library name and version:  **cli11/2.2.0**
Version bump.
---

cli11: add version 2.2.0

---

recipes/pcre/all/conanfile.py

Specify library name and version:  **pcre/8.45**
I'm getting a conflict in one of my recipes.  Weirdly it occurs on mac and msvc, but not on gcc.
https://github.com/jmarrec/conan-openstudio-ruby/runs/5822256011?check_suite_focus=true#step:5:404
```
'pcre/8.45' requires 'zlib/1.2.11' while 'minizip/1.2.12' requires 'zlib/1.2.12'.
```
My conanfile.py has `self.requires("zlib/1.2.12")`. My t`est_package/conanfile.py` has `self.requires("minizip/1.2.12")` (and I tried adding `self.requires("zlib/1.2.12")` in the `test_package/conanfile.py` too)
---

pcre: Bump requirement zlib/1.2.11 to zlib/1.2.12

---

recipes/opentdf-client/all/conandata.yml
recipes/opentdf-client/config.yml

Specify library name and version: opentdf-client/0.6.3
- Fixed the regression caused by not using the right network provider interface
---
- [x ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ x] I've tried at least one configuration locally with the
[conan-center …

opentdf-client: add version 0.6.3

---

recipes/libusb/all/conandata.yml
recipes/libusb/all/conanfile.py
recipes/libusb/all/test_package/CMakeLists.txt
recipes/libusb/config.yml

Specify library name and version:  **libusb/1.0.25**
2022-01-31: v1.0.25
* Linux: Fix regression with some particular devices
* Linux: Fix regression with libusb_handle_events_timeout_completed()
* Linux: Fix regression with cpu usage in libusb_bulk_transfer
* Darwin (macOS): Add support for detaching kernel drivers with authorization.
* Darwin (macOS): Do not drop partial data on timeout.
* Darwin (macOS): Silence pipe error in set_interface_alt_setting().
* Windows: Fix HID backend missing byte
* Windows: Fix segfault with libusbk driver
* Windows: Fix regression when using libusb0 driver
* Windows: Support LIBUSB_TRANSFER_ADD_ZERO_PACKET on winusb
* New NO_DEVICE_DISCOVERY option replaces WEAK_AUTHORITY option
* Various other bug fixes and improvements
closes #10037
---
[conan-center …

(#10037) Bump libusb to 1.0.25

---

recipes/libpqxx/all/CMakeLists.txt
recipes/libpqxx/all/conanfile.py
recipes/libpqxx/all/test_package/CMakeLists.txt
recipes/libpqxx/all/test_package/conanfile.py

libpqxx: bump libpq + modernize

---

recipes/aws-c-s3/all/conandata.yml
recipes/aws-c-s3/all/conanfile.py
recipes/aws-c-s3/config.yml

Specify library name and version:  **aws-c-s3/0.1.37**
Since aws-c-s3/0.1.36, this recipe requires aws-checksums.
---

aws-c-s3: add version 0.1.37

---

recipes/etl/all/conandata.yml
recipes/etl/config.yml

Specify library name and version:  **etl/20.27.1**
---

etl: add version 20.27.1

---

recipes/wolfssl/all/conandata.yml
recipes/wolfssl/config.yml

Specify library name and version:  **wolfssl/5.2.0**
---

wolfssl: add version 5.2.0

---

recipes/ffmpeg/all/conanfile.py

Add advanced linker flags for clang too
Specify library name and version:  **ffmpeg/all**
Fixes #9903
---

ffmpeg include advanced linking flags for clang

---

recipes/opencv/4.x/conanfile.py

Specify library name and version:  **opencv/4.x**
By default, opencv is built against all supported CUDA arch. I just added an option to select CUDA architectures. It has an `"ANY"` type since it works with a comma-separated list of versions.
---

opencv: add cuda_arch_bin settings

---

recipes/aws-crt-cpp/all/conandata.yml
recipes/aws-crt-cpp/all/conanfile.py
recipes/aws-crt-cpp/all/patches/0.17.23-fix-cast-error.patch
recipes/aws-crt-cpp/config.yml

Specify library name and version:  **aws-crt-cpp/0.17.23**
---

aws-crt-cpp: add version 0.17.23 with updating dependencies

---

recipes/libunwind/all/conanfile.py

Specify library name and version:  **libunwind/1.5.0**
libunwind has optional support for working with 2 types of compressed debuginfo: "minidebuginfo" with LZMA, and "zlibdebuginfo" with zlib. By default it enables these if it can find the relevant libraries at configuration time, and the recipe had a mandatory dependency on liblzma and no dependency on libz. This PR changes that to expose both options explicitly.
---

libunwind: allow compression configuration

---

recipes/daw_header_libraries/all/conandata.yml
recipes/daw_header_libraries/config.yml

Specify library name and version:  **daw_header_libraries/2.33.2**
---

daw_header_libraries: add version 2.33.2

---

recipes/llvm-core/all/CMakeLists.txt
recipes/llvm-core/all/conanfile.py

Specify library name and version:  **llvm-core/all**
These changes are mandatory for packaging llvm tools like clang:
- Keep TableGen binary
- Add option (disabled by default) to use cmake official config files
---

llvm-core: Add option to use cmake official config files + Keep TableGen binary

---

recipes/libavrocpp/all/CMakeLists.txt
recipes/libavrocpp/all/conandata.yml
recipes/libavrocpp/all/conanfile.py
recipes/libavrocpp/all/patches/0001-add-iterator-include-1-11-0.patch
recipes/libavrocpp/all/patches/0002-disable-tests-1-11-0.patch
recipes/libavrocpp/all/patches/0003-allow-static-boost-linkage-1-11-0.patch
recipes/libavrocpp/all/patches/0004-fix-windows-shared-installation-1-11-0.patch
recipes/libavrocpp/all/test_package/CMakeLists.txt
recipes/libavrocpp/all/test_package/conanfile.py
recipes/libavrocpp/config.yml

Specify library name and version:  **libavrocpp/1.11.0**
---

libavrocpp: add version 1.11.0

---

recipes/libgettext/all/conanfile.py

closes: #9972 
Specify library name and version:  **libgettext/all**
---

- [libgettext] fix clang-cl

---

recipes/poco/all/CMakeLists.txt
recipes/poco/all/conandata.yml
recipes/poco/all/conanfile.py

- remove `apr` & `apr-util` from requirements of DataMySQL component. /cc @SSE4 since you added these requirements in https://github.com/conan-io/conan-center-index/pull/1917, but I don't understand why.
---

poco: bump dependencies + modernize

---

recipes/gdal/all/conanfile.py
recipes/gdal/all/patches/3.1.x/fix-autotools-3.1.4.patch
recipes/gdal/all/patches/3.2.x/fix-autotools.patch
recipes/gdal/all/patches/3.3.x/fix-autotools-3.3.3.patch
recipes/gdal/all/patches/3.4.x/fix-autotools.patch

closes https://github.com/conan-io/conan-center-index/issues/10077
Explanation:
- gdal recipe doesn' trust custom GEOS_INIT m4 macro which is fragile, so we patch configure.ac to rely on pkg-conf
- GEOS_INIT macro substitutes HAVE_GEOS in Makefiles, and based on this value Makefiles inject a definition to enable geos during compilation, but this substitution was missing in our patch of configure.ac
---

gdal: fix GEOS in autotools build + bump dependencies

---

recipes/lexbor/all/CMakeLists.txt
recipes/lexbor/all/conandata.yml
recipes/lexbor/all/conanfile.py
recipes/lexbor/all/test_package/CMakeLists.txt
recipes/lexbor/all/test_package/conanfile.py
recipes/lexbor/all/test_package/test_package.c
recipes/lexbor/config.yml

Specify library name and version:  **lexbor/2.1.0**
lexbor is an html parser and rendering library.
It is being developed as the successor library to myhtml.
lexbor supports the option to build modules separately.
However, this recipe is not yet supported.
lexbor/2.1.0 doen't support for Windows with static build.
(see https://github.com/lexbor/lexbor/issues/69)
---

lexbor: add recipe

---

recipes/perfetto/all/conandata.yml
recipes/perfetto/all/patches/v25.0/0001-MSVC-Fix-narrowing-conversion-error.patch
recipes/perfetto/config.yml

Specify library name and version:  **perfetto/v25.0**
```
v25.0 - 2022-04-01:
* Added prebuilts for mac-arm64.
* Removed merged trace and config protos from Bazel. Embedder should
instead depend on the non-merged proto targets.
* Added FtraceConfig.disable_generic_events. If set, the ftrace data source
will not emit events for which it doesn't have a compile-time proto
message.
* Added ingestion support for cros_ec (CrOS sensors) ftrace events.
* Added ingestion support for kvm trace events.
* Added reporting of atrace failures. Now they are bubbled up to the UI
rather than causing atrace data to be silently missing.
* Added prebuilts for mac-arm64.
* Changed LIKE comparisions to be case-insenstive. This reverts the change
introduced in v22. …
```

(#10125) perfetto: bump version to v25.0

---

recipes/glib/all/conanfile.py
recipes/glib/all/test_package/CMakeLists.txt
recipes/glib/all/test_package/conanfile.py

- bump zlib
- bump meson (build requirements)
- cache Meson configuration
- raise `ConanInvalidConfiguration` in `validate()` instead of `configure()`
- reorder methods by order of execution
- test_package: enforce C, and remove useless pkgconfig stuff
---

glib: bump zlib & meson + modernize

---

recipes/ghc-filesystem/all/conandata.yml
recipes/ghc-filesystem/config.yml

Specify library name and version:  **ghc-filesystem/1.5.12**
---

ghc-filesystem: add version 1.5.12

---

recipes/tree-sitter/all/conandata.yml
recipes/tree-sitter/config.yml

Specify library name and version:  **tree-sitter/0.20.6**
---

tree-sitter: add version 0.20.6

---

recipes/libnghttp2/all/conandata.yml
recipes/libnghttp2/config.yml

Specify library name and version:  **libnghttp2/1.47.0**
---

libnghttp2: add version 1.47.0

---

recipes/boost/all/conanfile.py

boost: bump dependencies

---

recipes/protobuf/all/conanfile.py

closes: #9965
Specify library name and version:  **protobuf/all**
---

- [protobuf] fix clang-cl

---

recipes/automake/all/conanfile.py

Specify library name and version:  **automake**
This is (sometimes) a transitive requirement via `libtool`. New generators are not removing empty directories, and these folders are added by default (https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html#the-package-info-method), so CMake complains about not-existing directory.

[automake] Empty includedirs

---

recipes/log4cplus/all/conandata.yml
recipes/log4cplus/config.yml

Specify library name and version:  **log4cplus/2.0.6+2.0.7**
Two new releases of log4cplus has been issued since last recipe update
---

log4cplus 2.0.6 + 2.0.7

---

recipes/folly/all/CMakeLists.txt
recipes/folly/all/conanfile.py

- reorder methods by order of execution
---

folly: bump dependencies + modernize

---

recipes/libbacktrace/all/conanfile.py

Make libbacktrace build work in Conan's 2 profile mode (host and build profile).
Specify library name and version:  **libbacktrace/cci.20210118**
---

(#10167) libbacktrace: Bug when using Conan 2 profile mode

---

recipes/freeimage/all/conandata.yml
recipes/freeimage/all/conanfile.py
recipes/freeimage/all/patches/014_no_auto_ptr.patch

closes https://github.com/conan-io/conan-center-index/issues/10171
freeimage uses `auto_ptr`, therefore it can't work in C++17 or higher.
---

freeimage: bump zlib + C++17 handling

---

recipes/rapidcsv/all/conandata.yml
recipes/rapidcsv/config.yml

Specify library name and version:  **rapidcsv/8.62**
This updates the rapidcsv recipe to the latest version.
---

Update rapidcsv to 8.62

---

recipes/pagmo2/all/CMakeLists.txt
recipes/pagmo2/all/conanfile.py

- depend on onetbb instead of deprecated tbb recipe
---

pagmo2: relocatable shared lib on macOS + depend on onetbb instead of tbb

---

recipes/mariadb-connector-c/all/CMakeLists.txt
recipes/mariadb-connector-c/all/conanfile.py

relocatable shared lib on macOS: see https://github.com/conan-io/hooks/issues/376
---

mariadb-connector-c: bump dependencies + relocatable shared lib on macOS

---

recipes/civetweb/all/CMakeLists.txt
recipes/civetweb/all/conanfile.py

- also bump `required_conan_version` to 1.43.0 since explicit target name is used in `set_property()`
---

civetweb: bump dependencies + relocatable shared libs on macOS

---

recipes/vulkan-headers/all/conandata.yml
recipes/vulkan-headers/config.yml

Latest Vulkan SDK will be based on 1.3.211 (MoltenVK has already released its last version based on 1.3.211).
SDK version is not available yet, but volk recipe relies on non-sdk version.
---

Bump vulkan-headers/1.3.211

---

recipes/opentelemetry-proto/all/conandata.yml
recipes/opentelemetry-proto/config.yml

Specify library name and version:  **opentelemetry-proto/0.16.0**
---

opentelemetry-proto: add version 0.16.0

---

recipes/quazip/all/conanfile.py

**quazip/x.x**
Simple zlib requirement version bump
---

quazip: bump zlib

---

recipes/yasm/all/conanfile.py

Specify library name and version:  **yasm/all**
The recipe is broken when trying to compile with `RelWithDebInfo`:
```
FileNotFoundError: [Errno 2] No such file or directory: 'source_subfolder\\Mkfiles\\vc10\\x64\\RelWithDebInfo\\yasm.exe'
```
---

[yasm/all] Fix RelWithDebInfo

---

recipes/taglib/all/CMakeLists.txt
recipes/taglib/all/conanfile.py
recipes/taglib/all/test_package/CMakeLists.txt
recipes/taglib/all/test_package/conanfile.py

- use `cmake_find_package_multi` in test package
- bump zlib to 1.2.12
---

taglib: bump zlib + modernize

---

recipes/xtensor/all/conanfile.py

xtensor: depend on onetbb instead of deprecated tbb recipe

---

recipes/yasm/all/conanfile.py

yasm/1.3.0
This fixes #9198
---

yasm: Do not require devenv

---

recipes/glog/all/conandata.yml
recipes/glog/all/conanfile.py
recipes/glog/config.yml

Specify library name and version:  **glog/0.6.0**
[patch](https://github.com/conan-io/conan-center-index/blob/master/recipes/glog/all/patches/0001-fix-msvc-snprintf.patch) from 0.5.0 is not needed anymore. Problem was [fixed](https://github.com/google/glog/commit/9c1a25b9310b0bb73a605aecb72463bab5901721) in upstream. 
---

Add glog/0.6.0

---

recipes/caf/all/conandata.yml
recipes/caf/config.yml

Specify library name and version:  **caf/0.18.6**
---

caf: add version 0.18.6

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/config.yml

Specify library name and version:  **cppcheck/2.7.5**
Trying @qchateau automatic PR generation.
---

cppcheck: add version 2.7.5

---

recipes/opentdf-client/all/conandata.yml
recipes/opentdf-client/config.yml

Specify library name and version:  opentdf-client/0.9.0
- A new public API for storing encrypted metadata in TDF
- A new public API to check a valid TDF
---

opentdf-client: add version 0.9.0

---

recipes/libharu/all/CMakeLists.txt
recipes/libharu/all/conanfile.py
recipes/libharu/all/test_package/CMakeLists.txt
recipes/libharu/all/test_package/conanfile.py

- compiler=msvc support
- cache CMake configuration with functools.lru_cache
- use cmake_find_package_multi in test package
- bump zlib to 1.2.12
---

libharu: bump zlib + modernize

---

recipes/librdkafka/all/CMakeLists.txt
recipes/librdkafka/all/conanfile.py

- bump zlib, zstd and openssl
---

librdkafka: bump dependencies + relocatable shared libs on macOS

---

recipes/drmp3/all/CMakeLists.txt
recipes/drmp3/all/conandata.yml
recipes/drmp3/all/conanfile.py
recipes/drmp3/all/dr_mp3.c
recipes/drmp3/all/test_package/CMakeLists.txt
recipes/drmp3/all/test_package/conanfile.py
recipes/drmp3/all/test_package/test_package.c
recipes/drmp3/config.yml

Specify library name and version:  **drmp3/0.6.32**
This adds a new recipe for the [dr_mp3](https://github.com/mackron/dr_libs/tree/master) library.
See also the existing PRs for the very similar [dr_wav](https://github.com/mackron/dr_libs/tree/master) and [dr_flac](https://github.com/mackron/dr_libs/tree/master) libraries. Apart from naming, there is no difference to the drwav recipe.
---

Add drmp3/0.6.32

---

recipes/visit_struct/all/conandata.yml
recipes/visit_struct/all/conanfile.py
recipes/visit_struct/all/test_package/CMakeLists.txt
recipes/visit_struct/all/test_package/conanfile.py
recipes/visit_struct/all/test_package/test_package.cpp
recipes/visit_struct/config.yml

Specify library name and version:  **visit_struct**
visit_struct is used by structopt internally.
I want to separate it.
---

visit_struct: add recipe

---

recipes/argh/all/conandata.yml
recipes/argh/config.yml

Specify library name and version:  **argh/1.3.2**
---

argh: add version 1.3.2

---

recipes/automake/all/test_package/conanfile.py

Specify library name and version:  **automake/any**
Fixes **automake** test_package build with `compiler=msvc` in profile
```
[settings]
os=Windows
arch=x86_64
compiler=msvc
compiler.version=193
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]
```
---

automake: fix test_package build for compiler=msvc

---

recipes/bison/all/conandata.yml
recipes/bison/all/patches/0006-dont-link-bison-against-libreadline.patch

Specify library name and version:  **bison/3.7.1**
Bison does not need libradline but linked to it on some versions. It has been fixed since official bison/3.7.3. This PR fixes this for current versions on CCI.
Fix #4443
---

bison: remove useless linking to libreadline

---

recipes/meson/all/conandata.yml
recipes/meson/config.yml

Specify library name and version:  **meson/0.62.0**
---

meson: add version 0.62.0

---

recipes/libtiff/all/conanfile.py

closes https://github.com/conan-io/conan-center-index/issues/10268
Before https://github.com/conan-io/conan-center-index/pull/7278, build of libtiff with disabled jbig or zstd was ok for versions < 4.3.0 , but broken for 4.3.0. After, it was the opposite.
Current PR should satisfy all versions.
---

libtiff: fix build of libtiff < 4.3.0 when jbig or zstd disabled

---

recipes/libusb/all/conandata.yml
recipes/libusb/config.yml

Specify library name and version:  **libusb/1.0.26**
2022-04-10: v1.0.26
* Fix regression with transfer free's after closing device
* Fix regression with destroyed context if API is misused
* Workaround for applications using missing default context
* Fix hotplog enumeration regression
* Fix Windows isochronous transfer regression since 1.0.24
* Fix macOS exit crash in some multi-context cases
* Build fixes for various platforms and configurations
* Fix Windows HID multi-interface product string retrieval
* Update isochronous OUT packet actual lengths on Windows
* Add interface bound checking for broken devices
* Add umockdev tests on Linux
closes #10437 
---

(#10437) Bump libusb to 1.0.26

---

recipes/spdlog/all/conanfile.py

Specify library name and version:  **spdlog/1.10.0**
Spdlog switched to fmt/8.1.1 internally, it's better if we use the same version externally too. See: https://github.com/gabime/spdlog/releases/tag/v1.10.0
---

spdlog: Bump fmt version

---

recipes/minizip/all/conandata.yml
recipes/minizip/all/patches/ioapi.patch

Specify library name and version:  **minizip/1.2.12**
Whereas `conan.exe install minizip/1.2.11@ --build -s compiler.version=11` worked with MSVC it got broken by v1.2.12. This PR introduces the patch from https://github.com/madler/zlib/pull/624 to keep compatibiliy with VS2010 or VS2012.
---

[minizip] Keep compatibility with older compilers

---

recipes/abseil/all/CMakeLists.txt

Specify library name and version:  **abseil/all**
Reason for this PR: https://github.com/conan-io/conan-center-index/pull/9703#issuecomment-1101278361
In short: build breakage on CMake versions which share code between `check_c_source_compiles` and `check_cxx_source_compiles` due to older CMake policy settings baked into their definitions by Abseil's policy settings.
---

[abseil] Work around check_cxx_source_compiles/CMP0067 build issue

---

recipes/gdk-pixbuf/all/conandata.yml
recipes/gdk-pixbuf/all/conanfile.py
recipes/gdk-pixbuf/all/test_package/CMakeLists.txt
recipes/gdk-pixbuf/all/test_package/conanfile.py
recipes/gdk-pixbuf/config.yml

gdk-pixbuf: modernize

---

recipes/podofo/all/CMakeLists.txt
recipes/podofo/all/conanfile.py

- fix pkg_config_name for podofo >= 0.9.7. Indeed upstream has changed this file name, it's `libpodofo.pc` now (instead of `libpodofo-0.pc`)
- bump zlib & openssl
---

podofo: bump zlib & openssl + few fixes

---

recipes/http_parser/all/CMakeLists.txt
recipes/http_parser/all/conandata.yml
recipes/http_parser/all/conanfile.py
recipes/http_parser/all/test_package/CMakeLists.txt
recipes/http_parser/all/test_package/conanfile.py
recipes/http_parser/all/test_package/test_package.c
recipes/http_parser/config.yml

- C test package
- use `strip_root` in `source()`
- cache CMake configuration with `functools.lru_cache()`
---

http_parser: modernize

---

recipes/libssh2/all/CMakeLists.txt
recipes/libssh2/all/conanfile.py

libssh2: bump dependencies + relocatable shared lib on macOS

---

recipes/uchardet/all/CMakeLists.txt
recipes/uchardet/all/conandata.yml
recipes/uchardet/all/conanfile.py

Specify library name and version:  **uchardet/0.0.7**
- Modernize recipe
- Use sha256 in conandata.yml
related to https://github.com/conan-io/hooks/pull/407
---

[uchardet] Use sha256 in conandata.yml

---

recipes/libcurl/all/conandata.yml
recipes/libcurl/all/conanfile.py
recipes/libcurl/config.yml

Specify library name and version:  **libcurl/7.82.0**
- Add libcurl version 7.82.0
- Adapt recipe to upstream renaming of cmake identifiers, starting with version 7.81.0: https://github.com/curl/curl/issues/7988
Closes #10418
---

Add libcurl version 7.82.0

---

recipes/sentry-breakpad/all/conandata.yml
recipes/sentry-breakpad/all/conanfile.py
recipes/sentry-breakpad/config.yml

Specify library name and version:  **sentry-breakpad/0.4.17**
I also clean old versions including 0.4.14 since sentry-native doesn't handle it.
---

Add sentry-breakpad/0.4.17

---

recipes/draco/all/conanfile.py
recipes/draco/all/test_package/CMakeLists.txt
recipes/draco/all/test_package/conanfile.py

Since 1.4.0, config file is `draco-config.cmake` (but without an imported target). Before 1.4.0 it was `DracoConfig.cmake` but the file was broken.
In master branch, `draco::draco` import target is now available (since https://github.com/google/draco/pull/840). 
Therefore I think it's better to unconditionally change CMake names defined in this recipe.
---

draco: fix CMake config file & target name

---

recipes/websocketpp/all/conandata.yml
recipes/websocketpp/all/conanfile.py
recipes/websocketpp/all/test_package/CMakeLists.txt
recipes/websocketpp/all/test_package/conanfile.py
recipes/websocketpp/config.yml

I've added explicit config & imported target names (from https://github.com/zaphoyd/websocketpp/blob/1b11fd301531e6df35a6107c1e8665b1e77a2d8e/CMakeLists.txt#L266-L281 + https://github.com/zaphoyd/websocketpp/blob/1b11fd301531e6df35a6107c1e8665b1e77a2d8e/websocketpp-config.cmake.in)
---

websocketpp: bump dependencies + modernize

---

recipes/sdl_image/all/CMakeLists.txt
recipes/sdl_image/all/conanfile.py

- remove zlib from requirements (not a direct dependency)
---

sdl_image: bump deps + modernize

---

recipes/stringtoolbox/all/conandata.yml
recipes/stringtoolbox/all/conanfile.py
recipes/stringtoolbox/all/test_package/CMakeLists.txt
recipes/stringtoolbox/all/test_package/conanfile.py
recipes/stringtoolbox/all/test_package/test_package.cpp
recipes/stringtoolbox/config.yml

Specify library name and version:  **stringtoolbox/0.0.4**
stringtoolbox is reqiured by libcluon which I am going to add recipe.
---

stringtoolbox: add recipe

---

recipes/tmx/all/CMakeLists.txt
recipes/tmx/all/conanfile.py

tmx: bump dependencies + relocatable shared lib on macOS

---

recipes/aruco/3.x.x/CMakeLists.txt
recipes/aruco/3.x.x/conandata.yml
recipes/aruco/3.x.x/conanfile.py
recipes/aruco/3.x.x/test_package/CMakeLists.txt
recipes/aruco/3.x.x/test_package/conanfile.py
recipes/aruco/config.yml

- remove zlib from requirements (not a direct dependency)
---

aruco: bump dependencies + modernize

---

recipes/zint/all/CMakeLists.txt
recipes/zint/all/conanfile.py
recipes/zint/all/test_package/CMakeLists.txt
recipes/zint/all/test_package/conanfile.py

- remove hardcoded `CMAKE_OSX_SYSROOT` in upstream CMakeLists :sweat:
---

zint: bump dependencies + modernize

---

recipes/soxr/all/CMakeLists.txt
recipes/soxr/all/conandata.yml
recipes/soxr/all/conanfile.py

Specify library name and version:  **soxr/0.1.3**
- Modernize few parts of the recipe (missing set_property)
- Update checksum from sha-1 to sha-256
Related to https://github.com/conan-io/hooks/pull/407
---

[soxr] Use SHA-256 in Conandata.yml

---

recipes/quill/all/conandata.yml
recipes/quill/all/conanfile.py
recipes/quill/config.yml

Specify library name and version:  **quill/1.7.2**
I also updated fmt version from 7.1.2 to 7.1.3 on quill/[>= 1.5.2, <= 1.6.2] to fix some bugs.
---

quill: add version 1.7.2

---

docs/changelog.md
docs/review_process.md

- [config] Update Conan client to 1.46.2
- [fix] Do not create GitHub pull-request statuses in advance.
We have been experiencing issues in GitHub with status checks that were not reported after the build finishes successfully. This situation is very inconvenient for reviewers, as pull-requests appear to be running forever and reviewers usually don't look at them until the green check appears. With this change, these status checks won't be sent when the job begins (with value _running_), but only when they are finished with either status success or failure.
We have added an issue to our backlog to investigate it and recover this feature in the future, but there are other developments with more priority now (Conan v2 is in the horizon)
- [fix] Move some Conan command calls to the wrapper. …

[changelog] Deploy new version

---

recipes/miniaudio/all/conandata.yml
recipes/miniaudio/config.yml

Specify library name and version:  **miniaudio/0.11.9**
mniaudio doesn't use release features in github.
---

miniaudio: add version 0.11.9

---

recipes/doxygen/all/conanfile.py

Specify library name and version:  **doxygen/***
Version bump zlib dependency to version 1.2.12
Since to zlib update to 1.2.12, using the doxygen package throws a diamond conflict with boost. 
---

Version bump zlib/1.2.12 in doxygen packages

---

recipes/qt/6.x.x/conanfile.py

Fixes conan-io/conan-center-index#10538
---

Qt6: fix multi profile windows build

---

recipes/sentry-crashpad/all/conanfile.py

sentry-crashpad requires C++ 14 to compile which is fully implemented in GCC 5
https://gcc.gnu.org/projects/cxx-status.html#cxx14
For some reason the minimum GCC version has been bumped here https://github.com/conan-io/conan-center-index/pull/10429
This broke our GCC 8 builds.
**UPDATE**: For some reason the GCC5 builds fail with a cryptic error. This used to work, it must be related to the newer sentry versions. It looks like a bug  in the compiler rather than GCC5 not supporting C++ 14.
---

Relax minimun required GCC version

---

recipes/minizip-ng/all/conandata.yml
recipes/minizip-ng/config.yml

Specify library name and version:  **minizip-ng/3.0.6**
---

minizip-ng: add version 3.0.6

---

recipes/tomlplusplus/all/conandata.yml
recipes/tomlplusplus/config.yml

Specify library name and version:  **tomlplusplus/3.1.0**
---

tomlplusplus: add version 3.1.0

---

recipes/magnum/all/CMakeLists.txt
recipes/magnum/all/conanfile.py
recipes/magnum/all/test_package/CMakeLists.txt
recipes/magnum/all/test_package/conanfile.py

- use target `glfw` instead of unofficial `glfw::glfw` target
- reorder methods by order of execution
- bump `vulkan-loader`
---

magnum: bump dependencies + modernize

---

recipes/hipony-enumerate/all/conanfile.py
recipes/hipony-enumerate/all/test_package/CMakeLists.txt
recipes/hipony-enumerate/all/test_package/conanfile.py

hipony-enumerate: bump pfr + modernize

---

recipes/onetbb/all/conandata.yml
recipes/onetbb/all/conanfile.py
recipes/onetbb/all/test_package/conanfile.py

- remove `provides = "tbb"`, since tbb recipe is deprecated
- CMakeDeps & PkgConfigDeps support
- fix pkgconfig name
---

onetbb 2021.x: modernize

---

recipes/abseil/all/conanfile.py

Specify library name and version:  **abseil**
Fix for https://github.com/conan-io/conan-center-index/pull/10502#discussion_r862453247
closes https://github.com/conan-io/conan-center-index/issues/10545
closes https://github.com/conan-io/conan-center-index/issues/10596
closes https://github.com/conan-io/conan-center-index/issues/10599

abseil: ensure build-modules are a list (fix for CMakeDeps)

---

recipes/sentry-native/all/conanfile.py

Specify library name and version:  **sentry-native**
---

sentry-native: Bump qt version to 5.15.3

---

recipes/qcustomplot/all/CMakeLists.txt
recipes/qcustomplot/all/conandata.yml
recipes/qcustomplot/all/conanfile.py
recipes/qcustomplot/config.yml

Specify library name and version:  **qcustomplot/1.3.2**
Due to the possibility of commercial licenses, I think it makes sense 
to add the old major version of QCustomPlot as a Conan recipe.
Since the old major version of QCustomPlot only support Qt5, we use
`qt/5.15.3`.
Add also CMake's `VERSION` and `SOVERSION` for creating correct 
library version details.
Also bump requirement for `qcustomplot/2.1.0` to `qt/6.3.0`.
---

qcustomplot: add version 1.3.2

---

recipes/libsigcpp/2.x.x/conandata.yml
recipes/libsigcpp/2.x.x/conanfile.py
recipes/libsigcpp/2.x.x/test_package/CMakeLists.txt
recipes/libsigcpp/2.x.x/test_package/conanfile.py
recipes/libsigcpp/2.x.x/test_package/test_package.cpp
recipes/libsigcpp/config.yml

Specify library name and version:  **libsigcpp/2.0**
I'm trying to use conan to fetch [Synfig](https://www.synfig.org/)'s dependencies. One of these dependencies is gtkmm 3, which depends on libsigc++ 2, so this is a step on the direction of writing a recipe for gtkmm 3.
---

Add recipe for libsigc++-2.0

---

recipes/minizip-ng/all/CMakeLists.txt
recipes/minizip-ng/all/conanfile.py
recipes/minizip-ng/all/test_package/CMakeLists.txt
recipes/minizip-ng/all/test_package/conanfile.py

- `CMakeDeps` & `PkgConfigDeps` support
- explicit `cpp_info.libs` in `package_info()`
---

minizip-ng: bump dependencies + modernize

---

recipes/openimageio/all/CMakeLists.txt
recipes/openimageio/all/conanfile.py

- `CMakeDeps` & `PkgConfigDeps` support
---

openimageio: bump dependencies + modernize

---

recipes/sfml/all/CMakeLists.txt
recipes/sfml/all/conanfile.py

- bump `stb`
- rely on `is_msvc()` & `is_msvc_static_runtime()` instead of custom methods
---

sfml: relocatable shared libs on macOS + bump stb + modernize

---

recipes/libressl/all/conandata.yml
recipes/libressl/config.yml

Specify library name and version:  **libressl/3.5.2**
LibreSSL 3.5.2 Release
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.5.2-relnotes.txt
---

libressl: add 3.5.2

---

recipes/cppcheck/all/conandata.yml
recipes/cppcheck/all/conanfile.py
recipes/cppcheck/all/patches/0003-handle-exename-on-macos.patch
recipes/cppcheck/all/test_package/conanfile.py
recipes/cppcheck/all/test_package/file_to_check.cpp
recipes/cppcheck/config.yml

Specify library name and version:  **cppcheck/...**
This test hightlights an issue in the current cppcheck recipe which fails to detect std.cfg.
Any idea how to fix this ?
---

cppcheck/*: Test against dummy file fix #5831

---

recipes/taocpp-taopq/all/CMakeLists.txt
recipes/taocpp-taopq/all/conanfile.py
recipes/taocpp-taopq/all/test_package/CMakeLists.txt
recipes/taocpp-taopq/all/test_package/conanfile.py

- bump libpq to 14.2
- move `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` to CMakeList wrapper
---

taocpp-taopq: bump libpq + modernize

---

recipes/yaml-cpp/all/CMakeLists.txt
recipes/yaml-cpp/all/conanfile.py

- rely on `is_msvc()` & `is_msvc_static_runtime()` instead of custom methods
- add `YAML_CPP_DLL` interface definition if msvc & shared to properly define `__declspec(dllimport)` at consume time, since yaml-cpp has several global symbols.
closes https://github.com/conan-io/conan-center-index/issues/10629
---

yaml-cpp: fix msvc shared + modernize

---

recipes/imgui/all/conandata.yml
recipes/imgui/all/conanfile.py
recipes/imgui/config.yml

Specify library name and version:  **imgui**
After #10636 and #10637 these versions are no longer used

imgui: remove older versions

---

recipes/oniguruma/all/CMakeLists.txt
recipes/oniguruma/all/conandata.yml
recipes/oniguruma/all/conanfile.py
recipes/oniguruma/config.yml

oniguruma: add 6.9.8 + modernize

---

recipes/vcglib/all/CMakeLists.txt
recipes/vcglib/all/conandata.yml
recipes/vcglib/all/conanfile.py
recipes/vcglib/all/test_package/CMakeLists.txt
recipes/vcglib/all/test_package/conanfile.py
recipes/vcglib/config.yml

vcglib: add 2022.02 + modernize

---

recipes/dlib/all/conanfile.py

OpenBLAS will provide a hgh performance BLAS library instead of falling back to builtin BLAS library
closes #9281 
---

dlib/all: Added OpenBLAS dependency to dlib package

---

recipes/opentelemetry-cpp/all/conanfile.py

Specify library name and version:  **opentelemetry-cpp/***
The recipe for opentelemetry-cpp could not be compiled in an environment without the git command.
By patching cmake module, it is now referenced from the opentelemetry-proto recipe.
---

opentelemetry-cpp: retrieve proto files from opentelemetry-proto (with updating dependencies)

---

recipes/sentry-native/all/conanfile.py

If we delete options on the `validate()` method their value gets captured in the lockfiles which renders them unusable. See associated issue for a complete explanation. 
Closes https://github.com/conan-io/conan/issues/11137
---

[Sentry-native] Move option deletion to the configure method

---

recipes/thelink2012-any/all/conandata.yml
recipes/thelink2012-any/all/conanfile.py
recipes/thelink2012-any/all/test_package/CMakeLists.txt
recipes/thelink2012-any/all/test_package/conanfile.py
recipes/thelink2012-any/all/test_package/test_package.cpp
recipes/thelink2012-any/config.yml

Specify library name and version:  **thelink2012-any/cci.20200719**
This is renamed version of linb-any. https://github.com/conan-io/conan-center-index/pull/10616
thelink-any is required by libcluon which I am going to add recipe.
---

thelink2012-any: add recipe

---

recipes/libcurl/all/conandata.yml
recipes/libcurl/config.yml

Specify library name and version:  **libcurl/7.83.0**
Bumping to the latest upstream. I depend on this package, and this version corrects several security vulnerabilities.
---

add libcurl version 7.83.0

---

recipes/gdal/all/conanfile.py

In some (most?) linux distros gdal headers files are installed in /usr/include/gdal
instead of /usr/include, the problem is that most of the apps that are using it they
will #include <gdal/gdal.h> not #include <gdal.h> and they can not work with the
current package layout.
List of distros that are using prefixed install:
- debian https://packages.debian.org/bullseye/amd64/libgdal-dev/filelist
- ubuntu (no surprise here) https://packages.ubuntu.com/jammy/amd64/libgdal-dev/filelist 
- fedora https://packages.fedoraproject.org/pkgs/gdal/gdal-devel/fedora-rawhide.html#files
Specify library name and version:  **gdal/1.0**
---

gdal: Allow the headers to be installed in include/gdal

---

recipes/zlib/all/conandata.yml

zlib/1.2.12
zlib/1.2.11
`zlib` puts old releases in [zlib/fossils](https://zlib.net/fossils/), not the root path. This means that the root path breaks sometimes. This fixes the remotes to always use the fossils directory.
This also uses zlib.net for all sources, instead of using sourceforge for older releases.
---

zlib/1.2.* Fix zlib urls

---

recipes/wayland/all/conanfile.py

During the compile, "wayland-scanner" exe is built and used for further
steps in the build.
The execution can fail as libxml2 does not include the rpath for
libiconv.
So, use the handy tools.run_environment(self) so "wayland-scanner" can
find its libraries.
I'm not sure why the execution doesn't fail for everyone else.  I am forcing all libs to be built shared, with -o "*:shared=True", and I added a dummy flag in the compiler settings in settings.yml + profile, to ensure the packages don't match anything prebuilt on CCI (ie to avoid linking static libs into shared libs, due to known v1 package_id issues).
Specify library name and version:  **wayland/1.20.0**
---

wayland - run the build in a run_environment

---

recipes/protobuf/all/conanfile.py

Specify library name and version:  **protobuf/3.20**
Add an option to provide protobuf library names without suffix in debug builds.
Protobuf Cmake already exposes this option, so this just adds an option to make the protobuf package in conan usable even if one does not happen to use cmake.
Fixes #10598 
---

Add an option to provide protobuf library names without suffix

---

recipes/libipt/all/CMakeLists.txt
recipes/libipt/all/conandata.yml
recipes/libipt/all/conanfile.py
recipes/libipt/all/test_package/CMakeLists.txt
recipes/libipt/all/test_package/conanfile.py
recipes/libipt/all/test_package/test_package.cpp
recipes/libipt/config.yml

Specify library name and version:  **libipt/v.1.0.5**
Intel(R) Processor Trace Decoder Library
========================================
The Intel Processor Trace (Intel PT) Decoder Library is Intel's reference
implementation for decoding Intel PT.  It can be used as a standalone library or
it can be partially or fully integrated into your tool.
The library comes with a set of sample tools built on top of it and a test
system built on top of the sample tools.  The samples demonstrate how to use the
library and may serve as a starting point for integrating the library into your
tool.
Closes #10577 
---

(#10577) Add libipt recipe

---

recipes/libxml2/all/conandata.yml
recipes/libxml2/config.yml

Specify library name and version:  **libxml2/2.9.14**
Fixes CVE-2022-29824
---

libxml2: add 2.9.14

---

recipes/qt/5.x.x/conanfile.py

Fixes conan-io/conan-center-index#10704
Specify library name and version:  **qt/1.0**
---

Qt5: fix servicesupport

---

recipes/libxml2/all/conandata.yml

xmlsoft.org is nowadays a redirect to Gnome GitLab, and using old URLs causes error 403 (same as #10750)
Specify library name and version:  **libxml2/2.9.***
I've been trying to build older versions of the package, and encountered an error during `source()` step.
---

libxml2: use up-to-date URL for old sources tarballs

---

recipes/qt/5.x.x/conandata.yml
recipes/qt/6.x.x/conandata.yml

Signed-off-by: Dylan <2894220@gmail.com>
Specify library name and version:  **qt/5.x**
Specify library name and version:  **qt/6.x**
Added mirror(USTC) for download qt source code.
---

[qt] add USTC mirror address for download qt source

---

recipes/libarchive/all/conandata.yml
recipes/libarchive/all/patches/android_compile.patch
recipes/libarchive/config.yml

Bump version in the process
Specify library name and version:  **libarchive/3.6.x**
---

libarchive/3.6.x: Fix compile for Android

---

recipes/libxslt/all/conandata.yml

xmlsoft.org is nowadays a redirect to Gnome GitLab, and using old URLs causes error 403 (same as #10643)
Specify library name and version:  **libxslt/1.1.34**
I've been trying to build older versions of the package, and encountered an error during source() step.
---

libxslt: use up-to-date URL for sources tarball

---

recipes/gettext/all/conanfile.py
recipes/gettext/all/test_package/conanfile.py

Specify library name and version:  **gettext/***
closes conan-io/conan-center-index#9592
---

gettext: fix hooks

---

recipes/daw_header_libraries/all/conandata.yml
recipes/daw_header_libraries/config.yml

Specify library name and version:  **daw_header_libraries/2.50.0**
---

daw_header_libraries: add version 2.50.0

---

recipes/opentelemetry-proto/all/conandata.yml
recipes/opentelemetry-proto/config.yml

Specify library name and version:  **opentelemetry-proto/0.17.0**
---

opentelemetry-proto: add version 0.17.0

---

recipes/zimg/all/conandata.yml
recipes/zimg/all/conanfile.py
recipes/zimg/all/test_package/CMakeLists.txt
recipes/zimg/all/test_package/conanfile.py
recipes/zimg/config.yml

- cache Autotools configuration with `functools.lru_cache`
---

zimg: add 3.0.4 + modernize

---

recipes/ezc3d/all/CMakeLists.txt
recipes/ezc3d/all/conandata.yml
recipes/ezc3d/all/conanfile.py
recipes/ezc3d/config.yml

ezc3d: add 1.4.8 + modernize

---

recipes/dlib/all/CMakeLists.txt
recipes/dlib/all/conandata.yml
recipes/dlib/all/conanfile.py
recipes/dlib/all/test_package/CMakeLists.txt
recipes/dlib/all/test_package/conanfile.py
recipes/dlib/all/test_package/test_package.cpp
recipes/dlib/config.yml

- use `cmake_find_package` for discovery/injections of external dependencies (I guess it was the reason of failures when `with_gif` was True for msvc)
- enable `with_gif` option by default
- add `with_sqlite3` option (enabled by default upstream, so it also avoids to discover system sqilte)
- disable `DLIB_USE_CUDA` & `DLIB_USE_MKL_FFT` for the moment
- enable `DLIB_NO_GUI_SUPPORT`, otherwise it requires X11 (also on macOS)
- I've explicitly enabled `DLIB_USE_BLAS` & `DLIB_USE_LAPACK` (default value upstream), but mainly to add a FIXME. Indeed what happen behind these options is quite obscure and does not guarantee that `OpenBlas` is used for example.
- add dlib/19.24: a new option `with_webp` is introduced
---

dlib: add 19.24 + add options + improve reproducibility of builds

---

recipes/st_tree/all/conandata.yml
recipes/st_tree/config.yml

Specify library name and version:  **st_tree/1.2.2**
---

st_tree: add version 1.2.2

---

docs/package/all/CMakeLists.txt
docs/package/all/conandata.yml
docs/package/all/conanfile.py
docs/package/all/test_package/CMakeLists.txt
docs/package/all/test_package/conanfile.py
docs/package/config.yml

this can help new contributors, and reviewers too.
This is a very quick draft.
We should probably also add more comments to this template, in order to explain all these conventions.
Also, if you find this template could be useful, then we should link to it from the documentation .md files
I added all CCI's approved reviewers as contributor to my fork, so please edit the files directly, instead of doing code suggestion.
this partially answers item 3. in https://github.com/conan-io/conan-center-index/issues/2857#issuecomment-860785693

create a recipe template

---

recipes/aws-c-common/all/conandata.yml
recipes/aws-c-common/config.yml

Signed-off-by: Dylan <2894220@gmail.com>
**aws-c-common/0.6.20 ~ 0.7.4**
added new version for aws-c-common: 0.6.20, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4
---

[aws-c-common] add new versions

---

recipes/shield/all/conandata.yml
recipes/shield/config.yml

Specify library name and version:  **shield/0.2**
---

shield: add version 0.2

---

recipes/nng/all/conanfile.py

Specify library name and version:  **nng/1.5.2**
nng supports a cmake option NNG_MAX_TASKQ_THREADS that allows setting of the maximum number of worker threads. Being able to control the number of worker threads is esp. important when working with constrained devices (the name of the library is "nanomsg", after all)
Hence, add conanfile support for this configuration value
---

Add 'maxTaskqThreads' option

---

recipes/quill/all/conandata.yml
recipes/quill/all/conanfile.py
recipes/quill/all/test_package/CMakeLists.txt
recipes/quill/all/test_package/conanfile.py
recipes/quill/config.yml

I deleted several old versions because there are lots of versions in this recipe.
---

quill: add version 1.7.3 and remove old versions 

---

recipes/zlib/all/conanfile.py
recipes/zlib/all/patches/0001-fix-cmake.patch

closes https://github.com/conan-io/conan-center-index/issues/10770
I don't know whether it was a good idea in the first place to rename zlibstatic on Windows, and remove d postfix for debug build type, but now it's done directly in CMakeLists with simple criteria (`zlib` for Windows, `z` for other platforms).
---

zlib: fix lib name in CMakeLists directly instead of fragile renaming

---

recipes/tllist/all/conandata.yml
recipes/tllist/all/conanfile.py
recipes/tllist/all/test_package/CMakeLists.txt
recipes/tllist/all/test_package/conanfile.py
recipes/tllist/all/test_package/meson.build
recipes/tllist/all/test_package/test_package.c
recipes/tllist/config.yml

From #8588 and the changes proposed in the reviews of such PR (including https://github.com/aacebedo/conan-center-index/pull/1)
closes #8588

Add tllist

---

recipes/gcc/all/conandata.yml
recipes/gcc/all/conanfile.py
recipes/gcc/all/test_package/conanfile.py
recipes/gcc/all/test_package/hello.c
recipes/gcc/all/test_package/hello.cpp
recipes/gcc/config.yml

Specify library name and version:  **gcc/10.1.0**

- add GCC 10.1.0

---

recipes/coin-cbc/all/conandata.yml
recipes/coin-cbc/all/conanfile.py
recipes/coin-cbc/all/patches/0002-pthreads4w.patch

**coin-cbc/2.10.5**
Allows consumers to enable parallel mode on non-Windows platforms
---

coin-cbc : enable parallel mode (non-Windows os only)

---

recipes/glibmm/all/conandata.yml
recipes/glibmm/all/conanfile.py
recipes/glibmm/all/patches/enable_static_libs_2_66_4.patch
recipes/glibmm/all/patches/enable_static_libs_2_72_1.patch
recipes/glibmm/all/patches/fix_initialization_order_fiasco_2_66_4.patch
recipes/glibmm/all/patches/fix_initialization_order_fiasco_2_72_1.patch
recipes/glibmm/all/test_package/CMakeLists.txt
recipes/glibmm/all/test_package/conanfile.py
recipes/glibmm/all/test_package/test_package.cpp
recipes/glibmm/config.yml

Specify library name and version:  glibmm
This adds glibmm 2.72.0 for gtkmm 4, and 2.66.2 for gtkmm 3. However, glibmm 2.66.2 is commented out until [libsigcpp 2](https://github.com/conan-io/conan-center-index/pull/10517) is merged.
---

Add recipe for glibmm

---

recipes/dbus/1.x.x/conanfile.py

Specify library name and version:  **dbus/1.x.x**
This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): Fix syntax warning in conan file
---

fix SyntaxWarning: "is not" with a literal in `dbus/1.x.x`

---

recipes/protobuf/all/conandata.yml
recipes/protobuf/config.yml

Specify library name and version:  **protobuf/3.15.8**
There are some applications that require this version.
---

Add protobuf v3.15.8

---

docs/faqs.md

We cannot simply recommend them, there are some known bugs that won't be fixed in v1

lockfiles: link issues in v1, add note around recommendation

---

docs/changelog.md

A couple of notes:
- Conan v2 export step is still not enabled, it will be soon.
- Access request already working https://github.com/conan-io/conan-center-index/issues/4#issuecomment-1131761348

[docs] Update changelog 19-May-2022

---

recipes/libsodium/all/conandata.yml
recipes/libsodium/all/conanfile.py
recipes/libsodium/all/readme-update-cci.txt
recipes/libsodium/config.yml

Upstream does not tag new releases anymore,
instead they continue to push to the stable branch, and expect consumers
to use the latest commit on the stable branch.
libsodium/cci.20220501
I also added support for MSVC 2022 in the recipe.
---

libsodium: add cci.20220501

---

recipes/diligent-core/all/conanfile.py

Specify library name and version:  **diligent-core/all**
This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): Fix syntax warning in conan file.
---

fix SyntaxWarning: "is not" with a literal in `diligent-core/all`

---

recipes/botan/all/conanfile.py
recipes/botan/all/test_package/CMakeLists.txt
recipes/botan/all/test_package/conanfile.py
recipes/botan/all/test_package/test_package.cpp

- pkgconfig file is `botan-2.pc`: see https://github.com/randombit/botan/blob/2.19.1/configure.py#L2215-L2216
- support of `compiler=msvc` in profile
- use `cmake_find_package_multi` in test package
- don't force value of `amalgamation` option when `single_amalgamation` option is enabled, but raise instead if value is not the expected one.
---

botan: fix pkgconfig name + bump dependencies + modernize

---

recipes/seqan3/all/conandata.yml
recipes/seqan3/all/conanfile.py
recipes/seqan3/all/test_package/CMakeLists.txt
recipes/seqan3/all/test_package/conanfile.py
recipes/seqan3/all/test_package/test_package.cpp
recipes/seqan3/config.yml

Library name and version:  **seqan3/3.1.0**
[seqan3](https://github.com/seqan/seqan3) is a header-only C++ library for sequence analysis
I am adding this recipe since a user requested it to be added: https://github.com/seqan/seqan3/issues/2974
It is very likely that we will add applications in the future that rely on seqan3 as a dependency, we have by now done so for other package repositories.
There is already a `seqan` recipe, it is for the old 2.x.x versions. _SeqAn3 is a complete rewrite_.
I am uncertain whether it should be added as a new version for the `seqan` recipe, or if it may exist as a separate package. 
**I am happy to handle this in whatever way you deem appropriate.**
Currently, we have some standalone packages (alongside the "old" `seqan` package):
* Conda: …

New: seqan3/3.1.0

---

recipes/libxml2/all/conanfile.py

run_environment is needed for icu=True build to work,
as there is no rpath for the required icu libs.
---

libxml2 - bump ICU dep, use run_environment

---

recipes/libgd/all/conanfile.py

Add other operating systems to the list of those who need the math library added for the package check build.
Specify library name and version: libgd/2.3.2
fixes https://github.com/conan-io/conan-center-index/issues/10937
Static library packages fail the package check on these operating systems as well, so add them to the list of OS' that wil add -lm to the package check link line.
---

libgd: Add other operating systems to the list of those who need the math lib

---

recipes/wolfssl/all/conandata.yml
recipes/wolfssl/config.yml

Specify library name and version:  **wolfssl/5.3.0**
---

wolfssl: add version 5.3.0

---

recipes/pango/all/conanfile.py

Note: not sure if this still needs an explicit requirement for xorg::xrender
Part of the series to move libxft out of xorg, see #10900 
Should be merged all at the same time.

pango - switch to libxft

---

recipes/libpng/all/conanfile.py

Add other operating systems to the list of those who need the math library added for the package check build.
Specify library name and version: **libpng/1.6.37**
https://github.com/conan-io/conan-center-index/issues/10937
Static library packages fail the package check on these operating systems as well, so add them to the list of OS' that wil add -lm to the package check link line.
---

[libpng] Add other operating systems to the list of those who need the math library

---

recipes/libtiff/all/conanfile.py

Add other operating systems to the list of those who need the math library added for the package check build.
Specify library name and version: **libtiff/4.3.0**
https://github.com/conan-io/conan-center-index/issues/10937
Static library packages fail the package check on these operating systems as well, so add them to the list of operating systems that will add -lm to the package check link line.
---

libtiff: Add other operating systems to the list of those who need the math lib

---

recipes/zulu-openjdk/all/conandata.yml
recipes/zulu-openjdk/config.yml

Specify library name and version:  **zulu-openjdk/11.0.15**
Download page: https://www.azul.com/downloads/?version=java-11-lts
Related to https://github.com/conan-io/conan-center-index/issues/10519
---

Add zulu jdk 11.0.15

---

recipes/argparse/all/conandata.yml
recipes/argparse/all/conanfile.py
recipes/argparse/all/patches/0001-v2.1-add-missing-include.patch
recipes/argparse/all/patches/0001-v2.2-add-missing-include.patch
recipes/argparse/all/patches/0001-v2.3-add-missing-include.patch

This has been fixed in upstream already, so starting from v2.5 this shouldn't be needed anymore.

Fix argparse compilation on gcc12

---

recipes/capnproto/all/conandata.yml
recipes/capnproto/all/patches/0012-msvc-nogdi-fix-0.9.1.patch

capnproto/0.9.1
There is a bug in the 0.9.1 release that prevents it from compiling using MSVC with NOGDI flag. To fix this I backported patches from master.
Issue: https://github.com/capnproto/capnproto/issues/1421
---

capnproto: Patch for fixing compilation with NOGDI flag

---

recipes/libressl/all/conandata.yml
recipes/libressl/config.yml

Specify library name and version:  **libressl/3.5.3**
LibreSSL 3.5.3 Release
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.5.3-relnotes.txt
---

libressl: add 3.5.3

---

recipes/etl/all/conandata.yml
recipes/etl/config.yml

Specify library name and version:  **etl/20.28.0**
---

etl: add version 20.28.0

---

recipes/fltk/all/conandata.yml
recipes/fltk/all/conanfile.py
recipes/fltk/all/patches/1.3.8-0003-build-static-only-on-static.patch

Specify library name and version:  **fltk/1.3.8**
try to fix https://github.com/conan-io/conan-center-index/issues/10852.
The original CMakeLists.txt always build static library.
It causes a lot of linked errors.
---

fltk: fix windows build error on shared=True

---

recipes/cwalk/all/conandata.yml
recipes/cwalk/config.yml

Specify library name and version:  **cwalk/1.2.7**
---

cwalk: add version 1.2.7

---

recipes/daw_header_libraries/all/conandata.yml
recipes/daw_header_libraries/config.yml

Specify library name and version:  **daw_header_libraries/2.53.3**
---

daw_header_libraries: add version 2.53.3

---

recipes/opengl/all/conanfile.py
recipes/opengl/all/test_package/conanfile.py
recipes/opengl/all/test_package/test_package.cpp

Specify library name and version:  **opengl/system**
#2311 requires the package (finders) and target name to be "opengl_system", and not "opengl", so conan's cmake files do not shadow the system's FindOpenGL.cmake files.
This worked with the old cmake_find_package, but needed an upgrade to work with CMakeDeps
Thanks go to VTK's cmake checkers, which pointed out that its opengl targets didn't declare any include_dirs or libs.
QUESTION: there is one more warning from the hooks that could be resolved.
```
[HOOK - conan-center.py] pre_export(): WARN: [MANDATORY SETTINGS (KB-H070)] The values 'arch', 'compiler', 'build_type' are missing on 'settings' attribute. Update settings with the missing values and use 'package_id(self)' method to manage the package ID.
```
How can that be fixed?
---

opengl: Fix package and target name for CMakeDeps generator

---

recipes/icu/all/conanfile.py

Trust in the compiler given to it by conan.
Before, it would use "gcc" no matter if you asked it to use gcc-11 or otherwise.
---

icu - Use the env's CC compiler for Linux/GCC platform

---

recipes/libsodium/all/conanfile.py

Continuing #10628 
Not sure if this is the right way of handling this issue.
Doesn't feel very streamlined to me.

libsodium/1.0.18 - Don't use vs2022 for old v1.0.18

---

recipes/llvm-openmp/all/CMakeLists.txt
recipes/llvm-openmp/all/conanfile.py
recipes/llvm-openmp/all/test_package/CMakeLists.txt
recipes/llvm-openmp/all/test_package/conanfile.py

Specify library name and version:  **llvm-openmp/12.0.1**
The default fPIC option should be True to account for the case where it is linked to a dynamic library.
---

llvm-openmp: change default fPIC option to True and modernize

---

recipes/libcurl/all/conanfile.py

We needed a way to expose control of the --with_ca_bundle and --with_ca_path libcurl option to the users of this recipe.
---

(#10919) libcurl: Expose control to --with_ca_bundle and --with_ca_path

---

recipes/imagemagick/all/conanfile.py

Pango now depends on the new libxft recipe, which removes the need for
this workaround/hack.
Part of the series to move libxft out of xorg/system
See PR #10900 
These should all be merged together.

imagemagick - bump pango dep AND remove xft hack

---

recipes/cpp-peglib/1.x.x/conandata.yml
recipes/cpp-peglib/config.yml

Specify library name and version:  **cpp-peglib/1.4.1**
---
-[x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.

cpp-peglib: add version 1.4.1

---

recipes/rotor/all/conanfile.py

Specify library name and version:  **rotor/0.xx**
The `BUILD_THREAD_UNSAFE` should be used every time during compilation of user's code, when multithreading option is disabled.
I'm the author of the library
---

[rotor] export thread unsafety

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Specify library name and version:  **quill/2.0.2**
---

quill: add version 2.0.2

---

recipes/libpciaccess/all/conanfile.py

fixes conan-io/conan-center-index#10909
Specify library name and version:  **libpciaccess/***
---

libpciaccess: fix unexpected keyword argument

---

recipes/argparse/all/conandata.yml
recipes/argparse/all/conanfile.py
recipes/argparse/config.yml

Specify library name and version:  **argparse/2.5**
Try to solve https://github.com/conan-io/conan-center-index/issues/10979.
---

argparse: add version 2.5

---

recipes/opentdf-client/all/conandata.yml
recipes/opentdf-client/config.yml

Specify library name and version:  **opentdf-client/1.0.0**
Upgrades to official 1.0.0 release of opentdf c++ client.  See opentdf.io for more information.
---

opentdf-client: add version 1.0.0

---

recipes/croncpp/all/CMakeLists.txt
recipes/croncpp/all/conandata.yml
recipes/croncpp/all/conanfile.py
recipes/croncpp/all/test_package/CMakeLists.txt
recipes/croncpp/all/test_package/conanfile.py
recipes/croncpp/all/test_package/test_package.cpp
recipes/croncpp/config.yml

Specify library name and version:  **croncpp/cci.20220503**
croncpp is unix cron expression parser library.
---

croncpp: add recipe

---

recipes/drogon/all/conandata.yml
recipes/drogon/all/patches/1.7.5-0003-find-package-trantor.patch

Specify library name and version:  **drogon/1.7.5**
A compile error occurs with drogon:with_ctl=True.
This is due to a missing link library in the drogon library.
I want to add Trantor in cci recipe.
---

drogon: fix drogon_ctl compilation error

---

recipes/simdjson/all/conandata.yml
recipes/simdjson/all/conanfile.py
recipes/simdjson/config.yml

Specify library name and version:  **simdjson/2.0.3**
simdjson/2.0.2 fix compilation error in gcc 8.
simdjson/2.0.3 fix compilation error in Visual Sutdio 2019.
---

simdjson: add version 2.0.3

---

recipes/ffmpeg/all/conanfile.py
recipes/ffmpeg/all/test_package/test_package.c

Specify library name and version:  **ffmpeg/5.0**
This PR fixes #10700 by adding options to allow enabling / disabling various ffmpeg features such as encoder, decoders, muxers etc. See the original issue for the discussion around how to surface these options.
The formatter in VS Code seems to have reformatted some of the existing code, but looking a the pep8 guidelines the lines were previously too long anyway, so I guess I've left it. If this is wrong I'm happy to revert those changes,  or split them into a precursor PR for easier review.
---

ffmpeg: extra configuration options

---

recipes/opencolorio/all/conandata.yml
recipes/opencolorio/all/patches/strlen.patch

Specify library name and version:  **opencolorio/2.1.0**
fix #11031
---

opencolorio: fixed missing strlen

---

recipes/gdk-pixbuf/all/conandata.yml
recipes/gdk-pixbuf/all/conanfile.py
recipes/gdk-pixbuf/all/patches/define_dllmain_only_when_shared.patch
recipes/gdk-pixbuf/config.yml

Specify library name and version:  **gdk-pixbuf**
gdk-pixbuf defines DllMain which makes it impossible for a shared library that also defines DllMain to link against it.
DllMain is defined to enable "reloaction" functionality. I added a patch that disables this functionality when built as a static library, since it's not possible to get the location of the dll (which doesn't exist).
This is a step towards completely static gtk 3 on windows.
It's worth noting that even with a static gdk-pixbuf it is not possible to copy a resulting application on a different pc and expect it to work correctly, since directories will be hard coded inside the library (a.k.a. not relocatable). Same case on Linux.
I suggest either we do this patch, or we disable building static gdk-pixbuf on Windows, since …

[gdk-pixbuf]: bump requirements and fix linking against static gdk-pixbuf

---

recipes/libsixel/all/conandata.yml
recipes/libsixel/all/conanfile.py
recipes/libsixel/all/test_package/CMakeLists.txt
recipes/libsixel/all/test_package/conanfile.py
recipes/libsixel/all/test_package/test_package.c
recipes/libsixel/config.yml

Specify library name and version:  **libsixel/1.10.3**
libsixel provide sixel support which is a bitmap graphics format supported by terminal and printers.
Original repository is https://github.com/saitoha/libsixel, but it seems not to be maintained since 2020.
This recipe uses forked repository (https://github.com/libsixel/libsixel)
---

libsixel: add recipe

---

recipes/arrow/all/conanfile.py
recipes/arrow/all/patches/7.0.0-0004-remove-find-modules.patch
recipes/arrow/all/patches/7.0.0-0005-use-find-package.patch

Specify library name and version:  **arrow/7.0.0**
Try to fix https://github.com/conan-io/conan-center-index/issues/11074.
quick fix for arrow/7.0.0 and thrift.
---

arrow: fix compilation error about thrift

---

recipes/cereal/all/conandata.yml
recipes/cereal/config.yml

Specify library name and version:  **cereal/1.3.2**
---

cereal: add version 1.3.2

---

recipes/cpp-httplib/all/conandata.yml
recipes/cpp-httplib/config.yml

Specify library name and version:  **cpp-httplib/0.10.8**
---

cpp-httplib: add version 0.10.8

---

recipes/cpp-peglib/1.x.x/conandata.yml
recipes/cpp-peglib/config.yml

Specify library name and version:  **cpp-peglib/1.4.2**
---

cpp-peglib: add version 1.4.2

---

recipes/tinycthread/all/CMakeLists.txt
recipes/tinycthread/all/conandata.yml
recipes/tinycthread/all/conanfile.py
recipes/tinycthread/all/test_package/CMakeLists.txt
recipes/tinycthread/all/test_package/conanfile.py
recipes/tinycthread/all/test_package/test_package.c
recipes/tinycthread/config.yml

Specify library name and version:  **tinycthread/cci.20161001**
tinycthread has 1.1 release but it doesn't use CMakeLists.txt.
Because HEAD already uses CMakeLists.txt, I decide to use it.
Try to solve https://github.com/conan-io/conan-center-index/issues/11070.
---

tinycthread: add recipe

---

recipes/capnproto/all/conandata.yml
recipes/capnproto/all/patches/0014-disable-tests-for-0.10.1.patch
recipes/capnproto/config.yml

Specify library name and version:  **capnproto/0.10.1**
0.10.1 has made some performance improvements.
---

capnproto: add version 0.10.1

---

recipes/catch2/3.x.x/conanfile.py

Specify library name and version:  **catch2/3.0.1**
In 2.x.x, cmake scripts are placed in `contrib`.
In 3.x.x, cmake scripts are placed in `extras`.
fix https://github.com/conan-io/conan-center-index/issues/11112.
---

catch2: add extras cmake script in 3.0.1

---

recipes/b2/portable/conanfile.py

Specify library name and version:  **b2/4.8.0**
Fixes a problem using the `cxx` and `cross-cxx` toolsets. Those toolsets only have meaning when passed to `build.sh`, so don't pass them to `b2` in the second step of building.
Also remove the include dirs, because the hooks got an error.
Amends #10292 
---

b2: Fix problems building with toolset=cxx

---

recipes/xbyak/all/conandata.yml
recipes/xbyak/config.yml

Specify library name and version:  **xbyak/6.60**
---

xbyak: add version 6.60

---

recipes/cairo/meson/conanfile.py

Specify library name and version:  **cairo**
Building shared libraries that depend on static glib causes problems since this shared library will get its unique instance of glib. This is particularly a problem for gtk for example, which is a main user of cairo. See https://github.com/conan-io/conan-center-index/issues/11022.
Same problem when mixing different versions of static glib. For example if gtk is built with static cairo with glib 2.73, and with static pango with static glib 2.72. Or when mixing shared and static glibs. This is why I changed package_id to use full_package_mode with glib.
I would like to apply this patch to all dependencies of gtk.
---

[cairo]: use shared glib for shared cairo

---

recipes/ctml/all/conandata.yml
recipes/ctml/all/conanfile.py
recipes/ctml/all/test_package/CMakeLists.txt
recipes/ctml/all/test_package/conanfile.py
recipes/ctml/all/test_package/test_package.cpp
recipes/ctml/config.yml

Specify library name and version:  **ctml/2.0.0**
ctml is header only HTML generater.
---

ctml: add recipe

---

recipes/fontconfig/all/conanfile.py

Specify library name and version:  **fontconfig**
bump freetype dependency
---

[fontconfig]: bump dependencies

---

recipes/libmysqlclient/all/conandata.yml
recipes/libmysqlclient/all/conanfile.py
recipes/libmysqlclient/all/patches/0006-fix-cpp20-build-8.0.29.patch
recipes/libmysqlclient/config.yml

Specify library name and version:  **libmysqlclient/8.0.29**
libmysqlclient uses `requires` C++20 keyword since 8.0.0.
I have to update libmysqlclient to 8.0.29 to compile it with C++20.
---

libmysqlclient: add version 8.0.29

---

recipes/kuba-zip/all/conandata.yml
recipes/kuba-zip/config.yml

Specify library name and version:  **kuba-zip/0.2.3**
---

kuba-zip: add version 0.2.3

---

recipes/thrift/all/conandata.yml
recipes/thrift/all/conanfile.py
recipes/thrift/all/patches/cmake-0.16.0.patch
recipes/thrift/config.yml

Specify library name and version:  **thrift/0.16.0**
- update boost/1.79.0
- enable with_qt (renamed as with_qt5 because cmake option is `WITH_QT5`
- some cmake options(WITH_STATIC_LIB, WITH_SHARED_LIB) are deprecated since 0.12.0. So they are removed.
---

thrift: add version 0.16.0 and update dependencies

---

recipes/perfetto/all/conandata.yml
recipes/perfetto/config.yml

Package Name/Version: perfetto/v26.1
Changelog: https://github.com/google/perfetto/releases/tag/v26.1
The above mentioned version is newly released by the upstream project and not yet available as a recipe.
Closes #11195 
```
v26.1 - 2022-06-13:
* Fixed build failures on Windows.
v26.0 - 2022-06-13:
* Added wildcard (*) support when targeting processes by their command line
in the Android perf profiler ("linux.perf" data source) and Java heap
snapshots ("android.java_hprof").
* Added support for kernel thread sampling, and kernel-only callstacks in
the Android perf profiler.
* Fixed rare crash when parsing zero-length ftrace __data_loc strings.
* Fixed rare crash on 4.19 kernel when encountering unexpected zero-padded
ftrace pages.
* Removed …
```

(#11195) perfetto: bump version to v26.1

---

recipes/scons/all/conandata.yml
recipes/scons/config.yml

Specify library name and version:  scons/4.3.0
This will be a dependency for adding a visual studio 2022 build of serf: https://scons.org/scons-430-is-available.html
---

scons: add version 4.3.0

---

recipes/icu/all/conanfile.py

runConfigureICU sets up a few fixed configuraitons, providing flags to configure, but also
prevents configure from using other environment variables it is designed to use.
We could, if there is a need, add these to flags set in conanfile.py, but because
Conan supports Autoconf directly, there probably isn't a need for this.
The reciple only supports a few configuraitons, so adding support for a new compiler
or operating system would require modificaitons to runConfgiureICU - none of which is actually useful.
Specify library name and version:  **icu/71.1**
As discussed in [PR#10906](https://github.com/conan-io/conan-center-index/pull/10906) (previous PR for the ICU recipe), runConfigureICU really just limits what Autoconf can do.
For the Msys/Cygwin flags that it does set, these probably …

[icu] Eliminate the runConfigureICU script from the ICU build.

---

recipes/icu/all/conandata.yml
recipes/icu/all/patches/0001-71.1-fix-undef-strict-ansi.patch

This prevents compiling with GCC11 with C++20,
and has probably not been needed for some time now.
There is a pending bug report upstream:
https://unicode-org.atlassian.net/browse/ICU-22002
Specify library name and version:  **icu/71.1**
---

icu/71.1 - Don't undef __STRICT_ANSI__

---

recipes/pango/all/conanfile.py

Specify library name and version:  **pango**
Building shared libraries that depend on static glib causes problems. See https://github.com/conan-io/conan-center-index/issues/11022.
---

[pango]: use shared glib for shared pango

---

recipes/atk/all/conanfile.py

Specify library name and version:  **atk**
Building shared libraries that depend on static glib causes problems. See https://github.com/conan-io/conan-center-index/issues/11022.
---

[atk]: use shared glib for shared atk

---

recipes/at-spi2-core/all/conanfile.py

Specify library name and version:  **at-spi2-core**
Building shared libraries that depend on static glib causes problems. See https://github.com/conan-io/conan-center-index/issues/11022.
---

[at-spi2-core]: use shared glib for shared at-spi2-core

---

recipes/glfw/all/conanfile.py

Specify library name and version:  **glfw/3.3.7**
When using both moltenvk/1.1.9 & glfw/3.3.7 as dependencies, the required version of vulkan-headers will be different when `vulkan_static ` is set. This PR fixes and aligns them.
Related to #11237
---

Bump vulkan-loader in glfw for static build

---

recipes/ignition-utils/all/conandata.yml
recipes/ignition-utils/all/conanfile.py

* Name: ignition-utils/1.3.0
* URL: https://gazebosim.org/libs/utils
*
* The current recipe of ignition-math has bugs
- it doesn't provide `CLI11` component
- It doesn't set the ignition-math cmake VERSION info which is used in downstream dependencies
- It uses the outdated ignition-utls urls
- Look at this post from gazebo on more updates: https://discourse.ros.org/t/a-new-era-for-gazebo-cross-post/25012
* This MR fixes the issues described above
* Similar to fixes in #11172
---

fix: ignition-utils

---

recipes/scons/all/conanfile.py

scons/* (all versions)
`$*` is a single shell word contatenating all the arguments
`$@` is multiple words and expanding it inside "" keeps the word boundaries
No change is required to the .bat version, as cmd's `%*` expands to the
entire verbatim command-line, preserving the original caller's quoting.
Fixes #9308 and #9311, should unblock #9301 and #11215
Fixes #9308
Fixes #9311
---

scons: Preserve word boundaries in wrapper script

---

recipes/zxing-cpp/all/conandata.yml
recipes/zxing-cpp/all/conanfile.py
recipes/zxing-cpp/all/patches/0004-include-cstddef.patch
recipes/zxing-cpp/all/test_package/CMakeLists.txt
recipes/zxing-cpp/all/test_package/conanfile.py
recipes/zxing-cpp/all/test_package/test_package_1.1.cpp
recipes/zxing-cpp/config.yml

Specify library name and version:  **zxing-cpp/***
- support gcc >= 11 (adding additional patches)
- another test_package.cpp for zing-cpp/1.3.0
- add find_package(stb) in test_package
---

zxing-cpp: add version 1.3.0

---

recipes/msgpack-cxx/all/conandata.yml
recipes/msgpack-cxx/config.yml

Specify library name and version:  **msgpack-cxx**
---

msgpack-cxx: add version 4.1.1

---

recipes/hidapi/all/conandata.yml
recipes/hidapi/config.yml

Specify library name and version:  **lhidapi/0.12.0**
---

hidapi: add version 0.12.0

---

recipes/nsync/all/conandata.yml
recipes/nsync/config.yml

Specify library name and version:  **nsync/1.25.0**
---

nsync: add version 1.25.0

---

recipes/pybind11/all/conandata.yml
recipes/pybind11/all/conanfile.py
recipes/pybind11/all/test_package/CMakeLists.txt
recipes/pybind11/all/test_package/conanfile.py
recipes/pybind11/config.yml

Specify library name and version:  **pybind11/2.9.1**
- Mac OS is no longer supported (temporary until https://github.com/pybind/pybind11/issues/3081 become fixed)
- Removed old releases
- Cache CMake instance with lru_cache
- Remove cmake test support. We use test_package.py only
Related to https://github.com/conan-io/conan-center-index/pull/10817
/cc @ericLemanissier 
/cc @vectorsli
---

[pybind11] Do not support Mac for now

---

recipes/sentry-breakpad/all/conandata.yml
recipes/sentry-breakpad/config.yml

Specify library name and version:  **sentry-breakpad/0.4.18**
Version bump
---

sentry-breakpad/0.4.18

---

recipes/sentry-crashpad/all/conandata.yml
recipes/sentry-crashpad/config.yml

Specify library name and version:  **sentry-crashpad/0.4.18**
Version bump
---

sentry-crashpad/0.4.18

---

recipes/taskflow/all/conandata.yml
recipes/taskflow/all/conanfile.py
recipes/taskflow/all/test_package/CMakeLists.txt
recipes/taskflow/all/test_package/conanfile.py
recipes/taskflow/config.yml

Specify library name and version:  **taskflow/***
- add version 3.4.0
- remove versions 2.2.0, 2.4.0
- taskflow/3.4.0 doesn't require patch for taskflow/3.3.0. (already fixed)
- sort versions 
---

taskflow: add version 3.4.0

---

recipes/qr-code-generator/all/conandata.yml
recipes/qr-code-generator/config.yml

Specify library name and version:  **qr-code-generator/1.8.0**
---

qr-code-generator: add version 1.8.0

---

recipes/graphene/all/conanfile.py

Specify library name and version:  **graphene**
Building shared libraries that depend on static glib causes problems. See https://github.com/conan-io/conan-center-index/issues/11022.
Last dependency at last!
---

[graphene]: use shared glib for shared graphene

---

recipes/rmlui/4.x/conanfile.py

Specify library name and version:  **rmlui/4.x**
This should fix #9284.
---

rmlui 4.x: Upgrade CMake to support VS2022

---

recipes/quazip/all/conanfile.py

Specify library name and version:  **quazip/1.3.0**
This replace https://github.com/conan-io/conan-center-index/pull/10049 
fixes https://github.com/conan-io/conan-center-index/issues/10640
, after getting help from https://github.com/stachenov/quazip/issues/145#issuecomment-1158950307
---

quazip/1.3.0: Add qt6 support

---

recipes/qr-code-generator/all/conandata.yml
recipes/qr-code-generator/all/conanfile.py
recipes/qr-code-generator/all/test_package/CMakeLists.txt
recipes/qr-code-generator/all/test_package/conanfile.py
recipes/qr-code-generator/config.yml

Specify library name and version:  **qr-code-generator/***
- add math lib in Linux, FreeBSD
- sort versions
- use lru_cache for configure_cmake
- use `find_package` in test_package
---

qr-code-generator: add math lib and modernize

---

recipes/qt/5.x.x/conanfile.py

Neither the Conan or the vanilla CMake-build version of the dbus
package use a d-suffix for the debug version of the library on
Windows.
Fixes #11286
Specify library name and version:  **qt/5.15.4**
---

qt: Link dbus-1 not dbus-1d in Debug builds on Windows

---

recipes/dcmtk/all/conanfile.py

Dcmtk explicitly compares the value of DCMTK_ENABLE_STL with the
string "ON". This will hopefully be fixed with
https://github.com/DCMTK/dcmtk/pull/60 but this makes the recipe work
correctly with already released versions of Dcmtk.
fixes #11124 
---

dcmtk: Correctly enable DCMTK_ENABLE_STL

---

recipes/cubicinterpolation/all/conanfile.py

Specify library name and version:  **cubicinterpolation/x.x.x**
Temporary solution to make packages compiling again (see issue #11207).
---

cubicinterpolation: temporatily downgrade boost dependency

---

recipes/qt/5.x.x/conandata.yml
recipes/qt/5.x.x/patches/0001-Find-fontconfig-using-pkg-config.patch

The included patch is the fix for QTBUG-61158 committed to
qtwebengine-chromium.git branch 90-based rebased on the branch
87-based to match the chromium version shipped with Qt 5.15.4.
Fixes #11300
Specify library name and version:  **qt/5.15.4** and **qt/5.15.5**
---

qt: Fix qtwebengine not finding fontconfig correctly

---

recipes/nmos-cpp/all/conandata.yml
recipes/nmos-cpp/all/conanfile.py
recipes/nmos-cpp/config.yml

Latest upstream, bumps dependencies to boost/1.79.0 and openssl/1.1.1o

Add nmos-cpp/cci.20220620

---

recipes/flatcc/all/conandata.yml
recipes/flatcc/all/conanfile.py
recipes/flatcc/all/test_package/CMakeLists.txt
recipes/flatcc/all/test_package/conanfile.py
recipes/flatcc/config.yml

Specify library name and version:  **flatcc/0.6.1**
- add version 0.6.1
- support gcc on Windows in 0.6.1
- use lru_cache in _configure_cmake
- use find_package in test_package
---

flatcc: add version 0.6.1

---

recipes/websocketpp/all/conanfile.py

Specify library name and version:  **websocketpp/0.8.2**
websocketpp: bump to boost/1.79.0 and openssl/1.1.1o
---

websocketpp: bump to boost/1.79.0 and openssl/1.1.1o

---

recipes/fontconfig/all/patches/0001-meson-win32.patch

Specify library name and version:  **fontconfig/2.13.93**
On non-English versions of Windows, the error message is localized so the condition does not work as expected and build fails.
---

fontconfig: fixed build on non-English versions of Windows

---

recipes/xorg/all/conanfile.py

fixed by conan-io/hooks#425
---

xorg: remove obsolete workaround

---

recipes/libcuckoo/all/conandata.yml
recipes/libcuckoo/all/conanfile.py
recipes/libcuckoo/all/test_package/CMakeLists.txt
recipes/libcuckoo/all/test_package/conanfile.py
recipes/libcuckoo/all/test_package/test_package.cpp
recipes/libcuckoo/config.yml

Specify library name and version:  **libcuckoo/0.3.0**
Contribute recipe for [efficient/libcuckoo](https://github.com/efficient/libcuckoo), a high-performance concurrent hash table.
I am not the author of this library, but some of my projects depend on it.
---

libcuckoo: new recipe

---

recipes/ffmpeg/all/conanfile.py

When linking to avformat statically,
we also need to link with the system library Secur32.lib
Specify library name and version:  **ffmpeg/5.0**
Without this patch, we get "unresolved external symbol AcquireCredentialsHandleA referenced in function tls_open" and other errors.
---

ffmpeg - link avformat with Secur32.lib on windows for static builds

---

recipes/cityhash/all/test_package/conanfile.py

All Macos nodes are running CMake +3.22. It is longer required a specific CMake version for test package.

[cityhash] Macos: Remove cmake as build_requirement

---

recipes/itlib/all/conandata.yml
recipes/itlib/config.yml

Specify library name and version:  **itlib/1.5.1**
---

itlib: add version 1.5.1

---

recipes/veque/all/conandata.yml
recipes/veque/config.yml

veque: add version 1.3.6

---

recipes/ignition-math/all/conandata.yml
recipes/ignition-math/all/conanfile.py

* The current recipe of ignition-math has bugs
- it doesn't provide `Eigen` compoent
- It doesn't set the ignition-math cmake VERSION info which is used in downstream dependencies
- It uses the outdated ignition-math urls
- Look at this post from gazebo on more updates: https://discourse.ros.org/t/a-new-era-for-gazebo-cross-post/25012
* This MR fixes the issues described above
* Both the versions 6.7.0 and 6.10.0 are fixed in this MR
---

fix: package/ignition-math 

---

recipes/opentelemetry-cpp/all/conandata.yml
recipes/opentelemetry-cpp/config.yml

Specify library name and version:  **opentelemetry-cpp/1.4.1**
---

opentelemetry-cpp: add version 1.4.1

---

recipes/xoshiro-cpp/all/conandata.yml
recipes/xoshiro-cpp/all/conanfile.py
recipes/xoshiro-cpp/all/test_package/CMakeLists.txt
recipes/xoshiro-cpp/all/test_package/conanfile.py
recipes/xoshiro-cpp/all/test_package/test_package.cpp
recipes/xoshiro-cpp/config.yml

Specify library name and version:  **xoshiro-cpp/1.1**
Contribute recipe for [Reputeless/Xoshiro-cpp](https://github.com/Reputeless/Xoshiro-cpp), a C++ header only library for PRNG using [xoshiro](https://prng.di.unimi.it/).
I am not the author of this library, but some of my projects depend on it.
---

xoshiro-cpp: new recipe

---

recipes/bison/all/conanfile.py

When running with CONAN_HOOK_ERROR_LEVEL=40, the bison package fails to build:
```sh
[HOOK - conan-center.py] post_package_info(): ERROR: [INCLUDE PATH DOES NOT EXIST (KB-H071)] Component bison::bison include dir 'include' is listed in the recipe, but not found in package folder. The include dir should probably be fixed or removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H071) 
```
This is because the default include directory is empty.
This PR just sets the include directory to be empty explicitly.
Specify library name and version:  **bison/3.7.6**
This is also a good place to share with all of us **why you are submitting this PR** (specially if it is a new addition to ConanCenter): is it a dependency of other libraries you want to …

bison: Fix Conan Hook warning for empty include directory

---

recipes/objectbox/all/CMakeLists.txt
recipes/objectbox/all/conandata.yml
recipes/objectbox/all/conanfile.py
recipes/objectbox/all/patches/0001-fix-cmake.patch
recipes/objectbox/all/test_package/CMakeLists.txt
recipes/objectbox/all/test_package/conanfile.py
recipes/objectbox/all/test_package/test_package.c
recipes/objectbox/config.yml

Specify library name and version:  **objectbox/0.17.0**
Try to fix https://github.com/conan-io/conan-center-index/issues/11235.
---

objectbox: add recipe

---

recipes/argparse/all/conandata.yml
recipes/argparse/config.yml

Specify library name and version:  **argparse/2.6**
---

argparse: add version 2.6

---

recipes/boost/all/conanfile.py

Specify library name and version:  **boost/any version**
I've mentioned a few past PRs in the hope that some boost-experts can weigh in on this PR.
I've done what I think is right, but I'm just a humble long time boost user.
Linking to Boost::headers only can still trigger autolink, even if the package had magic_autolink=False, because the no-auto-link define (BOOST_ALL_NO_LIB) was not set for the Boost::headers target.
This matters on the MSVC platform.
In my case, it was even more complicated.   For MSVC:
My boost package had magic_autolink=False and layout=tagged (the default is versioned).
I had a library LibA that `#include <boost/atomic.hpp>` in its public header, and linked PUBLIC Boost::headers PRIVATE Boost::atomic
I had an exe in the same cmake project that linked to LibA.
The …

boost - apply defines to Boost::headers too

---

recipes/etl/all/conandata.yml
recipes/etl/config.yml

Specify library name and version:  **etl/20.29.3**
---

etl: add version 20.29.3

---

recipes/imgui/all/conandata.yml
recipes/imgui/config.yml

Specify library name and version:  **imgui/1.88**
---

imgui: add version 1.88 and 1.88.docking

---

recipes/gperf/all/conanfile.py

Specify library name and version:  **gperf/3.1**
---

gperf/3.1: Fix Conan Hook warning for empty include directory

---

recipes/kissfft/all/conanfile.py

These were defined in kissfft's CMakeLists.txt, but they did not exist
in the recipe.
kissfft/131.1.0
---

kissfft/131.1.0: add more public defines

---

recipes/libdrm/all/conanfile.py

Fixes Conan Hook warning for empty include directory.
```
[HOOK - conan-center.py] post_package_info(): ERROR: [INCLUDE PATH DOES NOT EXIST (KB-H071)] Component libdrm::libdrm_nouveau include dir 'include/nouveau' is listed in the recipe, but not found in package folder. The include dir should probably be fixed or removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H071)
```
Specify library name and version:  **libdrm/2.4.109**
---

libdrm/2.4.109: Remove empty include directory from package

---

.c3i/config_v1.yml

On our [roadmap to v2](https://github.com/conan-io/conan-center-index/blob/master/docs/v2_roadmap.md), one of the first things to do is to start exporting recipes using Conan v2. The time is now.
With this change, the bot will start to show the output from Conan v2 export command:
ATM, this is just informative, so people start to gain awareness about Conan v2 changes

config - execute (and report) v2 export

---

recipes/objectbox-generator/all/conandata.yml
recipes/objectbox-generator/all/conanfile.py
recipes/objectbox-generator/all/test_package/conanfile.py
recipes/objectbox-generator/config.yml

Specify library name and version:  **objectbox-generator/0.13.0**
objectbox-generator provides precompiled binary to generate codes for objectbox.
It is written in golang, but it is required to use objectbox in C++.
---

objectbox-generator: add recipe

---

recipes/nodejs/all/conanfile.py

Specify library name and version:  **nodejs/***
Fixes empty include directory Conan Hook warning:
```
[HOOK - conan-center.py] post_package_info(): ERROR: [INCLUDE PATH DOES NOT EXIST (KB-H071)] Component nodejs::nodejs include dir 'include' is listed in the recipe, but not found in package folder. The include dir should probably be fixed or removed. (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H071) 
```
---

nodejs: Fix Conan Hook warning for empty include directory

---

recipes/kcov/all/conandata.yml
recipes/kcov/all/conanfile.py
recipes/kcov/all/test_package/conanfile.py
recipes/kcov/config.yml

Specify library name and version:  **kcov/40**
closes #11231
---

[kcov] Bump version release 40

---

docs/README.md

Commit fd5f1d05b253 moved the guide from docs/contributing.md ->
CONTRIBUTING.md without updating the reference in
docs/README.md. Commit 2ad9eec8326c (#11227) attempted to fix the link
but did not uppercase the filename as needed.
---

README.md: Fix broken link to contribution guide

---

recipes/parallel-hashmap/all/conandata.yml
recipes/parallel-hashmap/config.yml

Specify library name and version:  **parallel-hashmap/1.35**
---

parallel-hashmap: add version 1.35

---

.c3i/reviewers.yml

We want to welcome @prince-chrismc to the team. He joined JFrog some months ago to work on the [Pyrsia project](https://github.com/pyrsia), but now he will finally join the Conan team as a developer advocate. He has been contributing to ConanCenter from the very beginning, and he is the author of the [pull-requests-ready-to-be-reviewed automation](https://github.com/prince-chrismc/conan-center-index-pending-review/issues/1). We are very happy to have you here 🎉 🎉 🎉

Add `prince-chrismc` as team member

---

recipes/arsenalgear/all/CMakeLists.txt
recipes/arsenalgear/all/conandata.yml
recipes/arsenalgear/all/conanfile.py
recipes/arsenalgear/all/test_package/CMakeLists.txt
recipes/arsenalgear/all/test_package/conanfile.py
recipes/arsenalgear/all/test_package/test_package.cpp
recipes/arsenalgear/config.yml

Specify library name and version:  **arsenalgear/1.2.2**
The repository name in github is "arsenalgear-cpp".
But the reddit post by author is "arsenalgear: a library containing general purpose utils I developed to summarize helper tools of various projects (constantly in update)".
https://www.reddit.com/r/cpp/comments/vmwnm5/arsenalgear_a_library_containing_general_purpose/
So I use "arsenalgear" in conan recipe.
---

arsenalgear: add recipe

---

recipes/cairomm/all/conanfile.py

Specify library name and version:  **cairomm**
groundwork for https://github.com/conan-io/conan-center-index/pull/11415
---

[cairomm]: use shared glib for shared cairomm

---

recipes/qt/5.x.x/conanfile.py

Specify library name and version:  qt/5.x
Add QMacStylePlugin under macOS by default.
---

Qt: Add QMacStylePlugin under macOS

---

recipes/daw_header_libraries/all/conandata.yml
recipes/daw_header_libraries/config.yml

Specify library name and version:  **daw_header_libraries/2.65.0**
---

daw_header_libraries: add version 2.65.0

---

recipes/meson/all/conandata.yml
recipes/meson/config.yml

Specify library name and version:  **meson/0.63.0**
---

meson: add version 0.63.0

---

recipes/ogg/all/conanfile.py

Specify library name and version:  **ogg**
Sometimes you don't want to run the BUILD_TESTING steps from the CMakeLists.
This adds an option for it
---

ogg: Add option to disable testing

---

recipes/rapidcsv/all/conandata.yml
recipes/rapidcsv/config.yml

Specify library name and version:  **rapidcsv/8.64**
---

rapidcsv: add version 8.64

---

recipes/uncrustify/all/conanfile.py

uncrustify/*: Define includedirs to fix hook error

---

recipes/libdrm/all/conanfile.py

Fixes the Conan Hook warning when man pages are installed under share/man.
Specify library name and version:  **libdrm/2.4.109**
---

libdrm/2.4.109: Package man pages in res/man

---

recipes/qt/6.x.x/conanfile.py

Specify library name and version:  **qt/6.x.x**
QT needs to know where its plugins live.
If QT_PLUGIN_PATH is not set, it'll look in the exe's directory.
qmake.exe and other simple things don't need the plugins,
but any sophisticated consumer of QT will need it set.
I'm not sure I need to set buildenv_info, but runenv_info was needed.
---

qt: set QT_PLUGIN_PATH for the run/build environments

---

recipes/qt/6.x.x/conanfile.py

qt6: add md4c dependency

---

recipes/pango/all/conanfile.py

Specify library name and version:  **pango/***
Pango only uses xrender when Xft, fontconfig and freetype are enabled

fix pango requirements

---

recipes/qt/5.x.x/conanfile.py

qt5: add md4c dependency

---

recipes/ogg/all/conanfile.py

Always disable tests and remove `build_testing` option. See https://github.com/conan-io/conan-center-index/pull/11042#issuecomment-1173930259
---

ogg: remove build_testing option

---

recipes/perfetto/all/conandata.yml
recipes/perfetto/config.yml

Specify library name and version:  **perfetto/27.0**
```
v27.0 - 2022-07-01:
* Fix rare crash due to watchdog timeout being too short.
* Removed enable_perfetto_x64_cpu_opt by default for x64 MacOS
since it caused issues for CIs.
* Improved performance of filtering and sorting on most queries.
UI:
* Changed sorting of process groups to take slice count and presence of
perf profiles into account.
SDK:
```
Closes #11540 
---
- [ x ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ x ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ x ] I've used the …

(#11540) perfetto: Bump version to 27.0

---

.gitignore

When using new layout like `cmake_layout(self)`, these files appear at root level

gitignore - with new generators some files appear at root level

---

recipes/xerces-c/all/CMakeLists.txt

Without `@rpath` in the install_name MacOS won't search for Xerces-C in the `RPATH` that's baked into a binary.
---

xerces-c: fixup install name on MacOS

---

.c3i/config_v2.yml

At this moment every v2 build fails, this is especially noisy when the PRs are merged. This change will stop those notifications.

v2 - Do not notify via slack

---

recipes/qt/5.x.x/conanfile.py

Jumbo builds consistently crash builds when building QtWebEngine.
On a fairly new machine with 32 GB of RAM, I can't have other applications open.
On a the Pinebook Pro, an aarch64 machine, compilation just freezes when it reaches jumbo builds.
Although jumbo builds can improve build times, they should never be defaulted on.
This is explained in the CMake documentation for unity builds.
To ensure builds complete, jumbo builds must be disabled.
The QMake configure command-line option `-webengine-jumbo-build 0` accomplishes this.
Specify library name and version:  **qt/5.x.x**
---

qt/5.x.x: Disable QtWebEngine jumbo builds

---

recipes/ruy/all/conandata.yml
recipes/ruy/all/conanfile.py
recipes/ruy/config.yml

Specify library name and version: **ruy/cci.20220628**
This is done as part of https://github.com/conan-io/conan-center-index/pull/11477, but split into a separate PR, since the bot complains. This needs to be merged first!
---

[ruy] Upgrade ruy to cci.20220628

---

recipes/qt/5.x.x/conanfile.py

Specify library name and version:  **qt/5.x.x**
Fixes issue #11352.
Add the library directories of Conan dependencies to the RPATH search directories.
This allows transitive library dependencies among shared libraries to be found by the linker.
Additionally, the `QMAKE_LFLAGS` variable creates confusion by passing linker flags via `LFLAGS`, i.e. lexer flags, instead of `LDFLAGS`.
There is a better variable for passing link directories to QMake, `QMAKE_LIBDIR`, which automatically handles platform-specific flags.
Using this variable makes the generated Makefiles easier to understand and avoids extra work in the Conanfile to use the proper flags to pass link directories to the compiler.
---

qt/5.x.x: Fix passing link directories to QMake

---

recipes/qt/6.x.x/conanfile.py

Running CMake in the package method requires the build context.
Without using the required build context, libraries will not be found.
This PR uses a build context function to wrap CMake calls.
This ensures the necessary build environment can be used when running CMake.
Fixes #11489.
Specify library name and version:  **qt/6.x.x**
---

qt/6.x.x: Run CMake in build context

---

recipes/tracy/all/conandata.yml
recipes/tracy/config.yml

Specify library name and version:  **tracy/0.8.2.1**
---

tracy: add version 0.8.2.1

---

docs/faqs.md
docs/packaging_policy.md

This PR is motivated by https://github.com/conan-io/conan-center-index/pull/11534
Testing a project does not affect the packaged binaries, but changes the package ID. For those cases which the package ID should not be affect, the [global conf](https://docs.conan.io/en/latest/reference/config_files/global_conf.html) is the answer.
The configuration `skip_test` is supported by CMake and Meson (Meson is bugged), but it only executes or not the tests.
/cc @SpaceIm  
---

[docs] Why not build testing as a recipe option

---

recipes/geotrans/all/conandata.yml
recipes/geotrans/all/conanfile.py
recipes/geotrans/all/patches/3.8-fix-for-cxx20.patch

Specify library name and version:  **geotrans/3.8**
Small simple patch to add const where required on 2 lines.
---

geotrans/3.8: patch to compile with MSVC2022 and c++20

---

recipes/verilator/all/conandata.yml
recipes/verilator/all/conanfile.py
recipes/verilator/all/patches/0005-msvc-patches.patch
recipes/verilator/all/test_package/CMakeLists.txt
recipes/verilator/config.yml

Specify library name and version:  **verilator/4.200**
Adding a version 4.200 of the Verilator tool.
---

Verilator: add version 4.200

---

recipes/grpc-proto/all/conandata.yml
recipes/grpc-proto/all/conanfile.py
recipes/grpc-proto/all/test_package/CMakeLists.txt
recipes/grpc-proto/all/test_package/conanfile.py
recipes/grpc-proto/all/test_package/test_package.cpp
recipes/grpc-proto/config.yml

According to the documentation:
> This repository contains the canonical versions of common protocol definitions for peripheral services around gRPC such as health checking and load balancing.
and these repositories (`grpc` and `grpc-proto`) are synced: https://github.com/grpc/grpc/pull/27957, nevertheless, I've found that sometimes information flows from `grpc` to `grpc-proto`... so I have my doubts about how development is being organized around those repositories.

grpc-proto - Add repository

---

recipes/libjpeg-turbo/all/conandata.yml
recipes/libjpeg-turbo/all/conanfile.py
recipes/libjpeg-turbo/all/patches/2.1.3-0001-fix-cmake.patch
recipes/libjpeg-turbo/config.yml

Specify library name and version:  **libjpeg-turbo/2.1.3**
Second try to upgrade.
https://github.com/conan-io/conan-center-index/pull/11533
- add version 2.1.3
- create a patch to fix CMAKE_SOURCE_DIR issue in 2.1.3
- remove versions 2.0.2, 2.0.4
- use is_msvc
- use lru_cache
---

libjpeg-turbo: add version 2.1.3

---

recipes/detours/all/conanfile.py

Specify library name and version:  **detours/all**
Fix runtime compile flag
---

detours: fix static debug runtime

---

recipes/itlib/all/conandata.yml
recipes/itlib/config.yml

Specify library name and version:  **itlib/1.5.2**
---

itlib: add version 1.5.2

---

recipes/gtest/all/conandata.yml
recipes/gtest/all/conanfile.py
recipes/gtest/all/patches/gtest-1.11.0.patch
recipes/gtest/config.yml

Specify library name and version:  **gtest/***
Try to fix https://github.com/conan-io/conan-center-index/issues/11458.
- add version 1.12.1
- use `is_msvc()`
- make disable `replace_in_file` for "-Werror" after 1.12.0
---

gtest: add version 1.12.1

---

recipes/sqlite3/all/conandata.yml
recipes/sqlite3/all/conanfile.py
recipes/sqlite3/config.yml

Specify library name and version:  **sqlite3/3.39.0**
- add version 3.39.0
- remove versions 3.29.0, 3.30.1, 3.31.0, 3.31.1, 3.32.2, 3.33.0, 3.34.0, 3.34.1, 3.35.2, 3.35.3, 3.35.4
- 3.32.3 is required by sqlpp11-connector-sqlite3
- use lru_cache in _configure_cmake
---

sqlite3: add version 3.39.0

---

recipes/openssl/1.x.x/conandata.yml
recipes/openssl/3.x.x/conandata.yml
recipes/openssl/config.yml

Specify library name and version:  **openssl/3.0.4** **openssl/1.1.1p**
Security fix: https://www.openssl.org/news/secadv/20220621.txt
Fixes #11319
---

openssl: add 3.0.4,3.0.5,1.1.1p,1.1.1q

---

recipes/fmt/all/conandata.yml
recipes/fmt/all/conanfile.py
recipes/fmt/all/test_cmakedeps/conanfile.py
recipes/fmt/all/test_cmakedeps/test_package.cpp
recipes/fmt/all/test_package/conanfile.py
recipes/fmt/all/test_package/test_package.cpp
recipes/fmt/config.yml

Specify library name and version:  **fmt/9.0.0**
---

fmt: Add version 9.0.0

---

recipes/draco/all/conandata.yml
recipes/draco/config.yml

No need for CMake patch anymore since 1.5.3, dll install location has been fixed in https://github.com/google/draco/pull/838
---

Bump draco/1.5.3

---

recipes/poco/all/conandata.yml
recipes/poco/all/conanfile.py
recipes/poco/all/patches/1.12.0.patch
recipes/poco/config.yml

Specify library name and version:  **poco/1.12.0**
I want to test the new Poco::Prometheus component and thus I updated the config and recipe for version 1.12.0
important: needs pcre2 (v10.40) instead of pcre (v8.45) - this has to be reflected in the external dependencies
(the other PR https://github.com/conan-io/conan-center-index/pull/11607 does not handle this)
---

poco: update for version 1.12.0 (handle pcre2)

---

recipes/ixwebsocket/all/conandata.yml
recipes/ixwebsocket/all/conanfile.py
recipes/ixwebsocket/config.yml

Specify library name and version:  **ixwebsocket/11.4.3**
I'm the author of this library. I noticed some users use a more outdated one, and that new version has fixes for expressing dependencies in cmake files which were contributed by the vcpkg guys, so maybe it will be a good fixes for conan as well.
---
- [ x ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.

ixwebsocket 11.4.3

---

recipes/xorg/all/conanfile.py

Fix file names of *.pc files when using PkgConfigDeps generator.
Include custom variables in *.pc files.
Fixes a long-standing issue of a missing variable when building xkbcommon.
Fixes #3377.
---

xorg/system: Support PkgConfigDeps

---

recipes/libjpeg/all/conanfile.py

Specify library name and version:  libjpeg/all
I've altered the license info in the libjpeg recipe to use the appropriate SPDX identifier. The existing recipe refers to http://ijg.org/files/README which doesn't cover actual license information. The SPDX ID `IJG` is the "Independent JPEG Group License" listed here: https://spdx.org/licenses/IJG.html
This follows the SPDX recommendation mentioned here: https://github.com/conan-io/docs/blob/master/reference/conanfile/attributes.rst#license
---

[libjpeg] Use SPDX license identifer

---

docs/community_resources.md
recipes/bzip3/all/CMakeLists.txt
recipes/bzip3/all/conandata.yml
recipes/bzip3/all/conanfile.py
recipes/bzip3/all/patches/0001-make-restrict-alias.patch
recipes/bzip3/all/test_package/CMakeLists.txt
recipes/bzip3/all/test_package/conanfile.py
recipes/bzip3/all/test_package/test_package.c
recipes/bzip3/config.yml

Specify library name and version:  **bzip3/1.1.4**
Bzip3 is a compression library.
---

bzip3: add recipe

---

recipes/aws-c-cal/all/conanfile.py

aws-c-cal - bump deps

---

recipes/openssl/1.x.x/conanfile.py
recipes/openssl/3.x.x/conanfile.py

md2 has been disabled in openssl since openssl.git commit 4e9de7aa3a12
which is from 2009. It must be explicitly enabled with enable-md2.
Specify library name and version:  **openssl/3.0.3**
I've created this PR, because I need openssl with the EVP_md2 function available.
---

openssl: Fix option no_md2

---

recipes/spirv-tools/all/conandata.yml

Specify library name and version:  **spirv-tools/1.3.216**
This fixes #11550 where the sha256 sum of the tarball changed after the original publication of the recipe
---

spirv-tools package 1.3.216 has the wrong git hash

---

recipes/wayland/all/conanfile.py
recipes/wayland/all/test_package/CMakeLists.txt
recipes/wayland/all/test_package/conanfile.py

Specify library name and version:  **wayland**
Fixes issue #11332 and issue #11362. See issue #11579 for an explanation of why the package requires itself as a `tool_requires`.
Let me know if this PR should be a draft until `MesonToolchain` is supported and I will mark it as such.
---

wayland: Switch to MesonToolchain generator to allow cross-compiling

---

recipes/openssl/1.x.x/conandata.yml
recipes/openssl/3.x.x/conandata.yml
recipes/openssl/config.yml

Remove old `openssl` versions. If some version is _important_ for whatever reason, please share it here. Thanks!

openssl - remove old versions

---

docs/how_to_add_packages.md
docs/v2_linter.md

See example of application in this PR: https://github.com/conan-io/conan-center-index/pull/10456

[doc] How to disable linter for v1-only tests

---

recipes/etl/all/conandata.yml
recipes/etl/config.yml

Specify library name and version:  **etl/20.31.0**
---

etl: add version 20.31.0

---

recipes/trantor/all/conandata.yml
recipes/trantor/config.yml

Specify library name and version:  **trantor/1.5.6**
---

trantor: add version 1.5.6

---

recipes/osmanip/all/CMakeLists.txt
recipes/osmanip/all/conandata.yml
recipes/osmanip/all/conanfile.py
recipes/osmanip/all/test_package/test_package.cpp
recipes/osmanip/config.yml

Specify library name and version:  **osmanip/4.1.0**
- add version 4.1.0
- osmanip/4.1.0 doesn't need patch for arsenalgear
- the list of source files are changed in 4.1.0.
- `utility/option.hpp` is added in 4.1.0 which is used by `test_package.cpp`.
- no need `osmanip_inc`.
---

osmanip: add version 4.1.0

---

recipes/imagl/all/conanfile.py

this was not actually deprecated but it was a temporary workaround for a bug in the infrastructure
If it's preferred, I can leave the setting and added a deprecated warning and circle back later
Specify library name and version:  **imagl/all**
---

imagl: Remove deprecated setting

---

recipes/quill/all/conandata.yml
recipes/quill/all/conanfile.py
recipes/quill/all/test_package/CMakeLists.txt
recipes/quill/config.yml

Specify library name and version:  **quill/2.1.0**
- add version 2.1.0
- remove versions 1.2.3, 1.3.3, 1.4.0, 1.7.0, 1.7.2
- remove if expression for removed versions
- update fmtlib version
---

quill: add version 2.1.0

---

recipes/bitmagic/all/conandata.yml
recipes/bitmagic/all/conanfile.py
recipes/bitmagic/all/test_package/CMakeLists.txt
recipes/bitmagic/config.yml

Specify library name and version:  **bitmagic/7.12.3**
- add version 7.12.3
- remove version 7.3.1, 7.4.0
- remove condition for C++11 (because bitmagic supports C++17 since 7.5.0)
---

bitmagic: add version 7.12.3

---

recipes/redboltz-mqtt_cpp/all/conandata.yml
recipes/redboltz-mqtt_cpp/all/conanfile.py
recipes/redboltz-mqtt_cpp/all/test_package/CMakeLists.txt
recipes/redboltz-mqtt_cpp/all/test_package/conanfile.py
recipes/redboltz-mqtt_cpp/all/test_package/test_package.cpp
recipes/redboltz-mqtt_cpp/config.yml

Specify library name and version:  **redboltz-mqtt_cpp/13.0.0**
There is "paho-mqtt-cpp" in cci recipes.
So I think this recipe's name should have a prefix, "redboltz".
---

redboltz-mqtt_cpp: add recipe

---

recipes/libxml2/all/conanfile.py

Specify library name and version:  **libxml2/all**
---

bump libxml2 dependencies

---

recipes/pdfium/all/CMakeLists.txt
recipes/pdfium/all/conandata.yml
recipes/pdfium/all/conanfile.py
recipes/pdfium/all/test_package/CMakeLists.txt
recipes/pdfium/all/test_package/conanfile.py
recipes/pdfium/all/test_package/test_package.c
recipes/pdfium/config.yml

Specify library name and version:  **pdfium/cci.20210703**
The upstream pdfium project uses gn as build system, but I found it hard to patch that system to create a minimal pdfium library using system packages instead of vendored libraries and also using as less git submodules as possible.
https://github.com/madebr/pdfium-cmake contains the cmake build scripts.
---

pdfium: add pdfium/cci.20210730 recipe

---

recipes/skyr-url/all/CMakeLists.txt
recipes/skyr-url/all/conandata.yml
recipes/skyr-url/all/conanfile.py
recipes/skyr-url/all/patches/1.12.0-0001-fix-cmake.patch
recipes/skyr-url/all/patches/1.13.0-0001-fix-cmake.patch
recipes/skyr-url/all/test_package/CMakeLists.txt
recipes/skyr-url/all/test_package/conanfile.py

Specify library name and version:  **skyr-url/***
- apply patches to CMakeLists.txt for shared build
- remove gcc validation error in 1.13.0
- use `is_msvc()`
- use `lru_cache` in `_configure_cmake()`
---

skyr-url: support shared build and gcc in 1.13.0

---

recipes/glm/all/conandata.yml
recipes/glm/all/conanfile.py
recipes/glm/config.yml

Thanks Paul Harris for the hand-holding and bug hunting.
* recipes/glm/all/conandata.yml (sources): Add a source for the latest
commit of 20220420.
* recipes/glm/config.yml: Also mention new version here.
* recipes/glm/all/conanfile.py (GlmConan.package): Tweak for
"cci.*" versions.
Specify library name and version:  **glm/cci.20220420** built from GitHub's on-demand per-commit zip service.
> This is also a good place to share with all of us **why you are submitting this PR**
Oh, just because the latest tagged verion 0.9.9.8 is from ~2018~2020 but it has a nagging warning (which converts to error with `-Werror` with C++20 that has been fixed 2 years ago.  They should really make a new version tag.
I'm afraid I didn't do any of the below items  :point_down:  :grimacing:   I'm very new to …

New glm version in recipes/glm/all/conandata.yml

---

recipes/libmp3lame/all/conanfile.py

Specify library name and version:  **libmp3lame/all**
Handle Windows on ARM build. With conan arch set to `armv8`. Fixes #10800 
---

libmp3lame: Handle MSVC ARM64

---

recipes/ruby/all/conanfile.py

Specify library name and version:  **ruby/3.1.0**
* Fix #11553 
* Do not override the AutotoolsToolchain default install flags
---

Fix #11553 - ruby/3.1.0: build error on all platforms due to wrong prefix

---

recipes/modern-cpp-kafka/all/conandata.yml
recipes/modern-cpp-kafka/all/conanfile.py
recipes/modern-cpp-kafka/all/test_package/CMakeLists.txt
recipes/modern-cpp-kafka/all/test_package/conanfile.py
recipes/modern-cpp-kafka/all/test_package/test_package.cpp
recipes/modern-cpp-kafka/config.yml

Specify library name and version:  **modern-cpp-kafka/v2022.06.15**
Hi,
I'm the author of `modern-cpp-kafka` (https://github.com/morganstanley/modern-cpp-kafka), a Kafka C++ API, wrapper over `librdkafka`).
Now I'm trying to add this header-only library to the ConanCenter (https://github.com/morganstanley/modern-cpp-kafka/issues/105)
Thanks!
---

modern-cpp-kafka: new recipe

---

recipes/mcap/all/conandata.yml
recipes/mcap/config.yml

Reverts conan-io/conan-center-index#11755 and replaces it with an update to v0.1.2
This tag was for a TypeScript language release, not C++. I have a PR to fix the bot here: https://github.com/qchateau/conan-center-bot/pull/72

mcap: add version 0.1.2, revert addition of 0.2.2

---

recipes/xorg/all/conanfile.py

fixes conan-io/conan-center-index#11733
---

xorg: fix pkg_config generation

---

recipes/daw_header_libraries/all/conandata.yml
recipes/daw_header_libraries/config.yml

Specify library name and version:  **daw_header_libraries/2.68.1**
---

daw_header_libraries: add version 2.68.1

---

recipes/numcpp/all/conandata.yml
recipes/numcpp/config.yml

Specify library name and version:  **numcpp/2.8.0**
Second trial.
https://github.com/conan-io/conan-center-index/pull/11881
https://github.com/dpilger26/NumCpp/issues/151
---

numcpp: add version 2.8.0

---

recipes/opengrm/all/conandata.yml
recipes/opengrm/all/conanfile.py
recipes/opengrm/all/test_package/CMakeLists.txt
recipes/opengrm/all/test_package/conanfile.py
recipes/opengrm/all/test_package/test_package.cpp
recipes/opengrm/config.yml

Specify library name and version:  **opengrm/1.3.8**
---

Add opengrm/1.3.8

---

recipes/luau/all/conandata.yml
recipes/luau/config.yml

Specify library name and version:  **luau/***
---

luau: add version 0.537

---

recipes/valijson/all/conandata.yml
recipes/valijson/config.yml

Specify library name and version:  **valijson/0.7**
---

valijson: add version 0.7

---

recipes/tclap/all/conandata.yml
recipes/tclap/config.yml

The latest tclap release fixes issues when using c++20. The current
tclap in conan.io/center does not work with gcc12/c++20.
Specify library name and version:  **tclap/1.2.5**
---

Latest tclap version

---

recipes/create-dmg/all/conandata.yml
recipes/create-dmg/all/conanfile.py
recipes/create-dmg/all/patches/0001-change-share-to-res.patch

Specify library name and version:  **create-dmg**
---

create-dmg/x.x.x: change support location

---

recipes/gtsam/all/conandata.yml
recipes/gtsam/all/conanfile.py
recipes/gtsam/all/patches/0001-conan-4.1.1.patch
recipes/gtsam/all/patches/0002-macos-rpath-4.1.1.patch
recipes/gtsam/config.yml

Specify library name and version:  **gtsam/4.1.1**
Bumps GTSAM to 4.1.1.
---

Added gtsam 4.1.1

---

recipes/diligent-tools/all/CMakeLists.txt
recipes/diligent-tools/all/conandata.yml
recipes/diligent-tools/all/conanfile.py
recipes/diligent-tools/all/patches/0013-api.252004-fix_pip3_modules_install.diff
recipes/diligent-tools/config.yml

Specify library name and version:  **diligent-tools/all**
---

make it possible to delete diligent-tools patches

---

recipes/xorg/all/conanfile.py
recipes/xorg/all/test_package/CMakeLists.txt
recipes/xorg/all/test_package/conanfile.py

Use tools.system.package_manager ang tools.gnu.PkgConfig from the `conan` namespace.
This greatly reduces complexity of the package.
---

xorg/system: Modernize

---

recipes/googleapis/all/CMakeLists.txt
recipes/googleapis/all/conandata.yml
recipes/googleapis/all/conanfile.py
recipes/googleapis/all/helpers.py
recipes/googleapis/all/test_package/CMakeLists.txt
recipes/googleapis/all/test_package/conanfile.py
recipes/googleapis/config.yml

I found myself trapped here (https://github.com/conan-io/conan-center-index/pull/11624#issuecomment-1181555046), it was not possible to use different versions of `googleapis` for different versions of `google-cloud-cpp` libraries because of the different package id computed for `grpc` after the override. 
One alternative would be to heavily patch the build-system files of `google-cloud-cpp` to work with any version of `googleapis` (and keep building the protos inside), alternatively, we can keep patching the `google-cloud-cpp` but to use precompiled binaries of `googleapis`.
The second approach is probably more sound (and CC-friendly) as both libraries `grpc` and `google-cloud-cpp` can link to the same binaries (instead of building the same protos twice) and probably the ABI of …

googleapis - dynamically build cmake project

---

recipes/xorg/all/conanfile.py

The `f` goes before the `"`...
---

xorg/system: Fix my really stupid typo in Python f-string

---

recipes/tesseract/all/CMakeLists.txt
recipes/tesseract/all/conandata.yml
recipes/tesseract/all/conanfile.py
recipes/tesseract/all/patches/0002-Link-with-targets-5.2.0.patch
recipes/tesseract/all/patches/0004-control-optimizations-5.2.0.patch
recipes/tesseract/all/test_package/CMakeLists.txt
recipes/tesseract/all/test_package/conanfile.py
recipes/tesseract/config.yml

Specify library name and version:  **tesseract/***
- add version 5.2.0
- use `lru_cache()` in `_configure_cmake()`
- use `conan.tools.build.cross_building`
---

tesseract: add version 5.2.0

---

recipes/etl/all/conandata.yml
recipes/etl/config.yml

Specify library name and version:  **etl/20.31.3**
---

etl: add version 20.31.3

---

recipes/range-v3/all/conanfile.py

Specify library name and version:  **rangev3/all**
a follow up to #11369
`/experimental:preprocessor` only needed for [0.9.0; 0.11.0)
first added in https://github.com/ericniebler/range-v3/commit/6325f5215c69af836054bdf7a7fb27022d755c33, removed in https://github.com/ericniebler/range-v3/commit/cce62b1bdf5b004628fa5ecf34d50d44637cd317
---

- [rangev3] apply "/experimental:preprocessor" only when needed

---

recipes/etl/all/conandata.yml
recipes/etl/config.yml

Specify library name and version:  **etl/20.32.1**
---

etl: add version 20.32.1

---

recipes/expat/all/conanfile.py

Specify library name and version:  **expat/all**
Tried the recipe with Conan 1.45 and it failed.
---

[expat/all] Some imports used are only available in Conan 1.47.0 or newer

---

recipes/cpp-httplib/all/conandata.yml
recipes/cpp-httplib/config.yml

Specify library name and version:  **cpp-httplib/0.11.0**
---

cpp-httplib: add version 0.11.0

---

recipes/qt/6.x.x/conanfile.py

Specify library name and version:  **qt/6.x.x**
---

qt/6.x.x: Added missing imageformats plugins

---

recipes/luau/all/conandata.yml
recipes/luau/config.yml

Specify library name and version:  **luau/0.538**
---

luau: add version 0.538

---

recipes/fmt/all/conanfile.py
recipes/wayland/all/conanfile.py
recipes/wayland/all/test_package/CMakeLists.txt

Specify library name and version:  **waylan/1.21.0**
The PR #11580 replaced `env_info` by `buildenv_info` and `runenv_info`, which follows the migration guide and is correct: https://docs.conan.io/en/latest/reference/conanfile/tools/env/environment.html#environment-definition
However, those new attributes need `Environment` or similar class, which is not wide supported yet on CCI, causing missing PATH.
Related issue: https://github.com/conan-io/conan-center-index/pull/11974
/cc @paulocoutinhox 
---

[wayland] Re-add env_info.PATH

---

linter/check_no_test_package_name.py
linter/conanv2_test_transition.py
linter/pylintrc_testpackage
recipes/aaf/all/test_package/conanfile.py

Rules for recipe `conanfile.py` and for `test_package/conanfile.py` should be different. Here I'm introducing the first difference (easy one):
* recipe files require a `name` attribute
* that `name` attribute is forbidden in test-package ones
This should serve as a starting point to add more rules.

[linter] Add first rule for test_package files

---

recipes/cpp-httplib/all/conandata.yml
recipes/cpp-httplib/config.yml

Specify library name and version:  **cpp-httplib/0.11.1**
---

cpp-httplib: add version 0.11.1

---

recipes/kmod/all/conanfile.py
recipes/kmod/all/test_package/CMakeLists.txt
recipes/kmod/all/test_package/conanfile.py

- handle `pkgconf` shared in build requirements (with `VirtualBuildEnv`)
- remove most workarounds since related issues are fixed (bump min conan version accordingly: 1.48.0)
- add a layout (`basic_layout`)
- rely on `autotools.autoreconf()` instead of manual `self.run` of autoreconf
- `self.copy` replaced by `conan.tools.files.copy`
- `CMakeToolchain`/`CMakeDeps`/`VirtualRunEnv` in test_package
- reorder methods by order of execution to provide a better understanding of recipe flow.
---

kmod: modernize

---

recipes/entt/3.x.x/conandata.yml
recipes/entt/3.x.x/conanfile.py
recipes/entt/3.x.x/test_package/CMakeLists.txt
recipes/entt/3.x.x/test_package/conanfile.py
recipes/entt/config.yml

entt: add 3.10.3 + conan v2 migration

---

recipes/cmake/3.x.x/conandata.yml
recipes/cmake/config.yml

Specify library name and version:  **cmake/3.23.3**
---

cmake: add version 3.23.3

---

linter/pylintrc_testpackage

`conan-bad-name` and `conan-missing-name` are identifiers defined in a rule that is not included for `test_package/conanfile.py` files.

[linter] Fix enabled/disabled items for test_package

---

recipes/fast_float/all/conandata.yml
recipes/fast_float/config.yml

Specify library name and version:  **fast_float/3.5.1**
---

fast_float: add version 3.5.1

---

recipes/boost/all/conanfile.py

fixes #11955 
in fact the import in question wasn't released until v1.46.x: https://github.com/conan-io/conan/blob/release/1.46/conan/tools/build/__init__.py
---

import is used which is only available from conan >= 1.46.0

---

recipes/serd/all/conandata.yml
recipes/serd/all/conanfile.py
recipes/serd/config.yml

Specify library name and version:  **serd/0.30.14**
The build system changed to meson in this release. So a more thorough review is required. 
---

serd: add version 0.30.14

---

recipes/folly/all/conanfile.py
recipes/folly/all/test_package/conanfile.py
recipes/folly/all/test_v1_package/CMakeLists.txt
recipes/folly/all/test_v1_package/conanfile.py
recipes/folly/all/test_v1_package/test_package.cpp

Specify library name and version:  **folly/all**
* Fixes https://github.com/conan-io/conan-center-index/issues/11937
* updates `fmt` dependency to latest 7.x.x supported in CCI (7.1.3)
* Migrate test_package to comply with v2 linter 
---

Fix folly CXX_STD

---

recipes/zlib-ng/all/CMakeLists.txt
recipes/zlib-ng/all/conanfile.py
recipes/zlib-ng/all/test_package/CMakeLists.txt
recipes/zlib-ng/all/test_package/conanfile.py
recipes/zlib-ng/all/test_package_v1/CMakeLists.txt
recipes/zlib-ng/all/test_package_v1/conanfile.py

Specify library name and version:  **zlib-ng/all**
Adapt recipe to be cross-compatible with v1 and v2. 
Tested with Conan 1.51.0 and Conan 2.0.0-beta2

[zlib-ng] Adapt recipe to be cross-compatible with Conan v1 and v2

---

recipes/android-ndk/all/conandata.yml
recipes/android-ndk/all/conanfile.py
recipes/android-ndk/config.yml

Specify library name and version:  **android-ndk/r25**
This is an LTS version that works on M1 Macs, this version will be the only one until the 2023 release. 
So this version seems relevant to me.
---

[android-ndk/r25] add 2022 LTS version

---

recipes/boost/all/conanfile.py

Specify library name and version:  **boost/\***
Fixes https://github.com/conan-io/conan-center-index/issues/11861
Seems like `_create_emscripten_libs` was originally called inside `build` and was naturally skipped if `header_only=True`, but after https://github.com/conan-io/conan-center-index/commit/11d4960a30abb45f897029380cfdc44f5d1c7db6 it moved to `package()` and causes failure.
---

Fix packaging of boost if os=Emscripten and header_only=True

---

recipes/expat/all/conandata.yml
recipes/expat/all/conanfile.py
recipes/expat/all/test_v1_package/CMakeLists.txt
recipes/expat/all/test_v1_package/conanfile.py

- `CMAKE_POLICY_DEFAULT_CMP*` must be injected through `CMakeToolchain` with `cache_variables`, not `variables`, otherwise it has no effect.
- add a `test_v1_package`
- add `cmake_layout` (the default one is an in source build, and everything is mixed-up in source & build: patches, source code, build artifacts)
---

expat: fix CMAKE_POLICY_DEFAULT_CMP0042 injection + add test_v1_package

---

recipes/opentelemetry-proto/all/conandata.yml
recipes/opentelemetry-proto/config.yml

Specify library name and version:  **opentelemetry-proto/0.19.0**
---

opentelemetry-proto: add version 0.19.0

---

recipes/at-spi2-core/config.yml
recipes/at-spi2-core/new/conandata.yml

Specify library name and version:  **at-spi2-core/2.45.90**
---

at-spi2-core: add version 2.45.90

---

recipes/aws-c-common/all/conandata.yml
recipes/aws-c-common/config.yml

Specify library name and version:  **aws-c-common/0.7.5**
---

aws-c-common: add version 0.7.5

---

recipes/luau/all/conandata.yml
recipes/luau/config.yml

Specify library name and version:  **luau/0.539**
---

luau: add version 0.539

---

recipes/libtiff/all/conandata.yml
recipes/libtiff/all/conanfile.py
recipes/libtiff/all/patches/4.4.0-0001-cmake-add-libjpeg-turbo.patch
recipes/libtiff/config.yml

Specify library name and version:  **libtiff/4.4.0**
---

libtiff: add libtiff/4.4.0

---

recipes/highway/all/conandata.yml
recipes/highway/config.yml

Specify library name and version:  **highway/1.0.0**
---

highway: add version 1.0.0

---

recipes/qcustomplot/all/CMakeLists.txt
recipes/qcustomplot/all/conanfile.py

Specify library name and version:  **qcustomplot/2.1.0**
This PR adds an option to enable opengl support in the QCustomPlot recipe. In the current recipe there is a TODO that this should be done, and this PR fixes that TODO. The default is to have opengl support disabled, so as to not change the behaviour for current users.
---

Add option to enable opengl support in QCustomPlot

---

recipes/log4cplus/all/conanfile.py

log4cplus all versions
As we need to disable the thread pool feature on Windows, I'm adding an option to do so.
---

log4cplus: add thread_pool option

---

recipes/jfalcou-eve/all/conandata.yml
recipes/jfalcou-eve/all/conanfile.py
recipes/jfalcou-eve/config.yml

**jfalcou-eve/v2022.03.0**
Latest version of EVE now requires clang 13 and g++ 11 on Linux
---

Update jfalcou-eve requirements as of v2022.03.0

---

recipes/boost/all/conanfile.py

The new `scm.Version` no longer parses `semver`, it only splits the version string.
fixes #12044
/cc @markferry
---

[boost] Fix scm.Version usage

---

recipes/dataframe/all/CMakeLists.txt
recipes/dataframe/all/conandata.yml
recipes/dataframe/all/conanfile.py
recipes/dataframe/all/test_package/conanfile.py
recipes/dataframe/all/test_v1_package/CMakeLists.txt
recipes/dataframe/all/test_v1_package/conanfile.py

dataframe: cross-compatibility conan v1 & v2

---

recipes/cmake/3.x.x/conanfile.py

This PR adds the possibility to bootstrap the CMake recipe *without* having CMake installed.
For this the option `bootstrap` is provided.
This option is intentionally disabled by default and no automatic logic is provided.
If somebody needs this it can be implemented independently.
See #4334
---

[cmake] Add bootstrap option

---

docs/v2_linter.md
linter/transform_imports.py

Do not promote the new `Version` class as its interface will be broken in the upcoming Conan release (1.52). The future interface might be backported to 1.50.x and 1.51.x, but better not to use the current one.
Please, @jcar87, explain what is the future `Version` class to be used and the expected interface (maybe it is already documented and it can be just linked).

[linter] Do not promote migration of `Version` class (yet)

---

.github/workflows/on-push-do-doco.yml
docs/conandata_yml_format.md
docs/consuming_recipes.md
docs/policy_patching.md
docs/v2_migration.md
docs/v2_roadmap.md

I noticed it was missing on a few pages when I was poking in the docs 😄 
Tested on my fork https://github.com/prince-chrismc/conan-center-index/pull/31/files

docs: fix markup for automatic table of contents

---

.c3i/reviewers.yml

It's being a while since @jcar87 joined Conan team and I've just realized he hasn't been added as a team member to the reviewers list (shame on me!) 🙈 
Welcome @jcar87! I'm sure your contributions will be really valuable to recipes here (they already are!). Great times ahead! 🎉 🎉 🎉

Add @jcar87 to reviewers list (as a team member)

---

recipes/modern-cpp-kafka/all/conandata.yml
recipes/modern-cpp-kafka/config.yml

Specify library name and version:  **modern-cpp-kafka/2022.08.01**
---

modern-cpp-kafka: add version 2022.08.01

---

recipes/libtiff/all/conanfile.py

Specify library name and version:  libtiff/all
Fix https://github.com/conan-io/conan-center-index/issues/12155

Revert to use conans.tools.Version in libtiff recipe

---

recipes/android-ndk/all/conanfile.py
recipes/android-ndk/all/test_package/CMakeLists.txt
recipes/android-ndk/all/test_package/conanfile.py
recipes/android-ndk/all/test_v1_package/CMakeLists.txt
recipes/android-ndk/all/test_v1_package/conanfile.py

Specify library name and version:  **android-ndk/r24**
Since CMakeToolchain has been added to Conan Center, it consumes user configuration to determine which Android NDK path should be use: https://docs.conan.io/en/1.51/reference/conanfile/tools/cmake/cmaketoolchain.html#conf 
To keep same compatibility, that configuration need to be expose by the recipe too.
fixes #11863
fixes #11952
/cc @paulocoutinhox @n00b42
---

[android-ndk] Export NDK path for CMakeToolchain

---

recipes/boost/all/conanfile.py

- ~Remove `scm.Version` and use the legacy `conan.tools.Version`~
- ~We will have a hotfix for Conan, but so far, that's the best move.~
- Keep the new `scm.Version`, because v2 Linter does NOT allow the old one
- Need to wait for a patch version from Conan client, then, update it in CCI.
Related to https://github.com/conan-io/conan-center-index/pull/12119 (read all the discussion there)
/cc @lasote @jcar87
---

[boost] Revert scm.Version usage

---

recipes/opensubdiv/all/CMakeLists.txt
recipes/opensubdiv/all/conandata.yml
recipes/opensubdiv/all/conanfile.py
recipes/opensubdiv/all/test_package/CMakeLists.txt
recipes/opensubdiv/all/test_package/conanfile.py
recipes/opensubdiv/all/test_package/example.cpp
recipes/opensubdiv/config.yml

Specify library name and version:  **opensubdiv/3.4.4**
---

opensubdiv: Add recipe

---

recipes/asmjit/all/CMakeLists.txt
recipes/asmjit/all/conanfile.py
recipes/asmjit/all/test_package/conanfile.py
recipes/asmjit/all/test_v1_package/CMakeLists.txt
recipes/asmjit/all/test_v1_package/conanfile.py

asmjit: cross-compatibility conan v1 & v2

---

recipes/meson/all/conandata.yml
recipes/meson/config.yml

Specify library name and version:  **meson/0.63.1**
---

meson: add version 0.63.1

---

recipes/wayland/all/conanfile.py
recipes/wayland/all/test_package/CMakeLists.txt
recipes/wayland/all/test_package/conanfile.py
recipes/wayland/all/test_v1_package/CMakeLists.txt
recipes/wayland/all/test_v1_package/conanfile.py

Specify library name and version:  **wayland/1.20.0**
- Exported all required .pc files when cross-building
- Add test_v1_package: Test compatibility with Conan v1
- Keep env_info.PATH: Needed for Conan v1 generators
fixes #11332
Full log, cross-building to armv8:
<details>
<summary>Details</summary>
```
$ conan create  . 1.20.0@ -pr:b=default -pr:h=armv8
Exporting package recipe
wayland/1.20.0 exports: File 'conandata.yml' found. Exporting it...
wayland/1.20.0 exports: Copied 1 '.yml' file: conandata.yml
wayland/1.20.0: The stored package has not changed
wayland/1.20.0: Exported revision: 2f1f60bc8f84caa450d2a179f2f83719
Configuration (profile_host):
[settings]
arch=armv8
arch_build=x86_64
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux …
```

[wayland] Cross-building is now supported

---

recipes/xbyak/all/conandata.yml
recipes/xbyak/config.yml

Specify library name and version:  **xbyak/6.61.2**
---

xbyak: add version 6.61.2

---

recipes/luau/all/conandata.yml
recipes/luau/config.yml

Specify library name and version:  **luau/0.540**
---

luau: add version 0.540

---

.c3i/config_v1.yml
docs/v2_linter.md
linter/transform_imports.py

Conan `1.50.2` exposes the proper `conan.tool.scm.Version` API 🎉

Up Conan version + recover linter for Version

---

recipes/libwebp/all/conandata.yml
recipes/libwebp/config.yml

Specify library name and version:  **libwebp/1.2.4**
---

libwebp: add version 1.2.4

---

recipes/bzip2/all/CMakeLists.txt
recipes/bzip2/all/conandata.yml
recipes/bzip2/all/conanfile.py
recipes/bzip2/all/test_package/conanfile.py
recipes/bzip2/all/test_v1_package/CMakeLists.txt
recipes/bzip2/all/test_v1_package/conanfile.py

bzip2: cross-compatibility conan v1 & v2

---

recipes/libjpeg-turbo/all/conandata.yml
recipes/libjpeg-turbo/config.yml

Specify library name and version:  **libjpeg-turbo/2.1.4**
---

libjpeg-turbo: add version 2.1.4

---

docs/v2_linter.md
linter/transform_imports.py
recipes/7zip/19.00/conanfile.py

Exceptions should be imported from new module `conan.errors`

linter v2 - Request migration of `conans.errors` to `conan.errors`

---

recipes/boost/all/conanfile.py

Define allows changing implementation of several inline methods in boost::filesystem
Closes #11930
---

boost: add BOOST_FILESYSTEM_VERSION

---

recipes/civetweb/all/CMakeLists.txt
recipes/civetweb/all/conandata.yml
recipes/civetweb/all/conanfile.py
recipes/civetweb/all/test_package/conanfile.py
recipes/civetweb/all/test_v1_package/CMakeLists.txt
recipes/civetweb/all/test_v1_package/conanfile.py
recipes/civetweb/all/test_v1_package/test_package.cpp

Specify library name and version:  **civetweb/all**
---

civetweb: conan v2 support

---

recipes/googleapis/all/conandata.yml
recipes/googleapis/config.yml

This is the version vendored in `google-cloud-cpp/1.34.1`, I'll need it for this PR https://github.com/conan-io/conan-center-index/pull/11624.
After https://github.com/conan-io/conan-center-index/pull/11624, the plan is to consume actual binaries, so any version from `googleapis` should work for the consumers, but I prefer to make the changes step by step.

googleapis - add version

---

recipes/glib/all/conanfile.py

Specify library name and version:  **glib**
Attempt to solve miscellaneous Glib related issues by making the library shared by default.
See #11684 
---

[glib] build as shared by default

---

recipes/pybind11/all/conanfile.py

Specify library name and version:  **pybind11/all**
The property `cmake_build_modules` has to be assigned at the root `self.cpp_info`.
This is described in the migration guide: https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html
And in the documentation of CMakeDeps: https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html#properties
In the changelog: https://docs.conan.io/en/latest/changelog.html#jul-2022
Also in the 2.0 beta docs.
---

cmake_build_modules property has to be in the root self.cpp_info

---

recipes/openssl/1.x.x/conanfile.py
recipes/openssl/1.x.x/test_package/conanfile.py

This access to the cpp_info was creating a new config shared in that object and that finally turned into this error for some users: https://github.com/conan-io/conan/issues/11856

Fix openssl old version access to shared option of zlib

---

recipes/protobuf/all/conanfile.py

Specify library name and version:  **protobuf/3.21.4**
Since Conan [1.51.3](https://docs.conan.io/en/latest/changelog.html#aug-2022), the private import `from conan.tools.apple.apple import is_apple_os` is no longer available. Need to use the legacy version and wait for infrastructure update.
fixes https://github.com/conan-io/conan-center-index/issues/12334
---

[protobuf] Use legacy tools to import is_apple_os

---

recipes/dbus/1.x.x/conanfile.py

Specify library name and version:  **dbus/1.12.20**
Since Conan [1.51.3](https://docs.conan.io/en/latest/changelog.html#aug-2022), the private import `from conan.tools.apple.apple import is_apple_os` is no longer available. Need to use the legacy version and wait for infrastructure update.
Related to https://github.com/conan-io/conan-center-index/pull/12335
---

[dbus] Use legacy tools to import is_apple_os 

---

recipes/luau/all/conandata.yml
recipes/luau/config.yml

Specify library name and version:  **luau/0.541**
---

luau: add version 0.541

---

recipes/civetweb/all/conanfile.py

Specify library name and version:  **civetweb/all**
A different implementation of conan.tools.scm.Version in v1.51.0 causes the recipe to fail.
The implementation has been fixed in v1.51.2.
---

civetweb: skip broken Conan v1.51.0 version

---

recipes/prometheus-cpp/all/conandata.yml
recipes/prometheus-cpp/config.yml

Specify library name and version:  **prometheus-cpp/1.0.1**
Update prometheus-cpp to latest patch release.
---

prometheus-cpp: Bump to 1.0.1

---

docs/v2_linter.md

When adding new tools, many times is not clear which version should be used. We have it documented in docs.conan.io (thanks to @SpaceIm).
---

[docs] Conan v2 Linter: Required Conan version

---

recipes/gn/all/conanfile.py

Specify library name and version:  **gn/cci.20210429**
Trying to resolve an issue I ran into while trying to make https://github.com/conan-io/conan-center-index/pull/12189 build.
For the other PR, I got this error: `Do not raise ConanInvalidConfiguration from build() method. Please, move that same check to validate() method.`
Checking the log, I saw this message: `ERROR: gn/cci.20210429: Invalid configuration: gn requires a compiler supporting c++17`
My assumption is that the root cause is that `gn` validates its configuration in `configure()` instead of `validate()`.
---

Use validate in gn

---

recipes/doxygen/all/conanfile.py

Specify library name and version:  **doxygen/1.9.4**
xapian-core package is available as version 1.4.19.
Doxygen should use this most recent version.
---

feat: update xapian-core dependency of doxygen to most recent version

---

recipes/grpc/all/CMakeLists.txt

Specify library name and version:  grpc
update to support all default CMake build types
---

update grpc recipe to support RelWithDebInfo and MinSizeRel build types

---

recipes/box2d/all/conanfile.py

When deleting options/settings we need to add try/catch to avoid failures with conan v2 commands. In this case, the folloeing error was raising with `conan graph info` command:
```
conan graph info --requires box2d/2.3.1@#3f0bf2bd11b95e7834b5f98058862a1c -f json -pr:h /home/conan/w/prod-v2_cci_PR-12067/9/10bcc10b-d364-464d-96e7-fc4cd3d8a1aa/profile_windows_192_release_dynamic_msvc_release_64.*-shared-True.txt -pr:b /home/conan/w/prod-v2_cci_PR-12067/9/10bcc10b-d364-464d-96e7-fc4cd3d8a1aa/profile_windows_192_release_dynamic_msvc_release_64.*-shared-True.txt
-------- Input profiles --------
Profile host:
[settings]
arch=x86_64
compiler=msvc
compiler.runtime_type=Release
compiler.version=192
os=Windows
[options]
*/*:shared=True
Profile build: …
```

[conan v2] Migrate box2d recipe - take 2

---

recipes/cpp-peglib/1.x.x/conandata.yml
recipes/cpp-peglib/config.yml

Specify library name and version:  **cpp-peglib/1.6.1**
---

cpp-peglib: add version 1.6.1

---

recipes/metall/all/CMakeLists.txt
recipes/metall/all/conandata.yml
recipes/metall/all/conanfile.py
recipes/metall/all/test_package/conanfile.py
recipes/metall/all/test_v1_package/CMakeLists.txt
recipes/metall/all/test_v1_package/conanfile.py
recipes/metall/config.yml

- this lib is header only
- options were useless (no build nor consume effect in previous recipe), they are removed
- fix test_package (weird mix of cmake_find_package & CMakeDeps)
- add test_v1_package
---

metall: conan v2 support + remove options + header only

---

recipes/openexr/3.x/CMakeLists.txt
recipes/openexr/3.x/conandata.yml
recipes/openexr/3.x/conanfile.py
recipes/openexr/3.x/test_package/conanfile.py
recipes/openexr/3.x/test_v1_package/CMakeLists.txt
recipes/openexr/3.x/test_v1_package/conanfile.py

openexr 3.x: conan v2 support

---

recipes/octo-encryption-cpp/all/conanfile.py

Specify library name and version:  **octo-encryption-cpp/1.1.0**
---
Package info fixes to comply with conan v2

Package info fixes for conan v2 octo-encryption-cpp

---

recipes/libcap/all/conandata.yml
recipes/libcap/all/conanfile.py
recipes/libcap/all/test_package/CMakeLists.txt
recipes/libcap/all/test_package/conanfile.py
recipes/libcap/all/test_v1_package/CMakeLists.txt
recipes/libcap/all/test_v1_package/conanfile.py
recipes/libcap/config.yml

Specify library name and version:  **libcap/2.65**
libcap was updated to the latest release. And a few warnings from conan-center hooks were fixed.
Also, as I see it, there is ongoing refactoring in the repo. A lot of packages were rewritten to be compatible with conan v2. So I did a little refactoring of the recipe too (have a few concerns though).
---

libcap/2.65 + conan v2 compatibility

---

recipes/g3log/all/CMakeLists.txt
recipes/g3log/all/conandata.yml
recipes/g3log/all/conanfile.py
recipes/g3log/all/test_package/CMakeLists.txt
recipes/g3log/all/test_package/conanfile.py
recipes/g3log/all/test_v1_package/CMakeLists.txt
recipes/g3log/all/test_v1_package/conanfile.py
recipes/g3log/config.yml

CMake imported target is not namespace: it's `g3log`.
Actually upstream config file & target names were `g3logger` before 1.3.4, but they were changed to `g3log` in 1.3.4 for consistency with project name, so I've decided to use these new names (and it avoids to break consumers in the meantime since find/config file generated by cmake_find_package* generators were already g3log).
---

g3log: add 1.3.4 + conan v2 support + fix cmake imported target

---

recipes/wt/all/conandata.yml
recipes/wt/all/conanfile.py
recipes/wt/all/test_package/CMakeLists.txt
recipes/wt/all/test_package/conanfile.py

Specify library name and version:  **wt/***
- use `target_compile_features` in test_package (because gcc12 failed to compile test_package)
- use `TARGET` instead of cmake options `WITH_DBO` in test_package
---

wt: update dependencies and support gcc 12

---

recipes/boost-ext-ut/all/conanfile.py

Specify library name and version:  **boost-ext-ut/***
This allows overriding the default value for the option `disable_module`.
---

boost-ext-ut: Default disable_module option in config_options method

---

recipes/blend2d/all/CMakeLists.txt
recipes/blend2d/all/conandata.yml
recipes/blend2d/all/conanfile.py
recipes/blend2d/all/patches/0.0.17-0001-disable-embed-asmjit.patch
recipes/blend2d/all/patches/0.0.18-0002-fix-gcc12-compilationerror.patch
recipes/blend2d/all/test_package/CMakeLists.txt
recipes/blend2d/all/test_package/conanfile.py
recipes/blend2d/all/test_v1_package/CMakeLists.txt
recipes/blend2d/all/test_v1_package/conanfile.py

Specify library name and version:  **blend2d/***
- migratioon to Conan v2
- add sha256 in 0.0.18
- add test_v1_package
- fix compilation error in gcc12 with c++20 (backport from upstream)
---

blend2d: migration to Conan v2 and fix compilation error in gcc12 with c++20

---

recipes/entt/3.x.x/conanfile.py
recipes/entt/3.x.x/test_v1_package/CMakeLists.txt
recipes/entt/3.x.x/test_v1_package/conanfile.py

entt: improve support of conan v2 & add test_v1_package

---

recipes/swig/all/patches/0001-swig-linux-library-path.patch

Use return value from `dirname` since this function is not required to
modify input buffer. This PR fixes issue #11354
fixes #11354
---
- [+] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [no recipe changes] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [+] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [+] I've tried at least one configuration locally with the [conan-center hook](https://github.com/conan-io/hooks.git) activated.
- Activating hook gives the following error:
```
[HOOK - conan-center.py] post_package_info(): ERROR: [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] Exception …
```

(#11354) swig/4.0.2: portable dirname usage in get_exe_path

---

recipes/sqlite3/all/CMakeLists.txt
recipes/sqlite3/all/conanfile.py

This PR replaces the last conan v1 tool (conans.tools.is_apple_os) by its conan v2 counterpart.
---

sqlite3: full conan v2 support

---

recipes/brotli/all/conanfile.py

Specify library name and version:  **brotli/1.0.9**
We'd like to use configuration options in brotli, so I made [these options](https://github.com/google/brotli/blob/v1.0.9/c/common/platform.h#L10-L20) configurable.
---

brotli: Add configuration options

---

recipes/harfbuzz/all/conanfile.py

Fixes #12618
Specify library name and version:  **harfbuzz/all**
Ran into this when I was going out of my way to not have to include glib in my chain of dependencies QT/6.3.1 because on Windows that would require gettext, which requires autoconf and automake, which I can't seem to build because autoconf is not on the PATH for msys2 https://github.com/conan-io/conan-center-index/issues/10028 
---

[harfbuzz] Only check glib shared option if glib is a dependency

---

recipes/artery-font-format/all/conandata.yml
recipes/artery-font-format/config.yml

Specify library name and version:  **artery-font-format/1.0.1**
---

artery-font-format: add version 1.0.1

---

recipes/boost/all/conanfile.py

Otherwise LC_VERSION_MIN_MACOSX / LC_BUILD_VERSION isn't added to dylib. Also slight refactoring: extracted a couple of variables.
Fixes #12328
---

Boost: pass Apple deployment target flag to linker as well + v2 linter changes

---

recipes/clipper/all/conandata.yml

Older source versions are removed from Sourceforge's archive, so previous link was no longer valid, see #12064
I've recreated the archive, the original author restored it to the original location so we just need to update the checksum now.
**clipper/4.10.0**
fixes #12064
---

clipper: update checksum for v4.10.0 

---

recipes/libatomic_ops/all/conandata.yml
recipes/libatomic_ops/config.yml

Specify library name and version:  **libatomic_ops/7.6.14**
I'm maintainer of libatomic_ops upstream; v7.6.14 has been released recently.
---

libatomic_ops: add version 7.6.14

---

recipes/libmysqlclient/all/conandata.yml

Specify library name and version:  **libmysqlclient/8.0.29**
---

libmysqlclient/8.0.29: add sources mirror

---

docs/changelog.md
docs/code_of_conduct.md
docs/community_resources.md
docs/consuming_recipes.md
docs/error_knowledge_base.md
docs/faqs.md
docs/labels.md
docs/review_process.md
docs/v2_linter.md
docs/v2_migration.md
docs/v2_roadmap.md

Docs!
- 85% is just formatting was inconsistent in some files
- code fences, trailing white space
- heading levels
The biggest thing is there were small typos (dont git blame they are probably my fault) that I discovered while working on docs

docs: spelling and formatting

---

recipes/libpng/all/conanfile.py

Specify library name and version:  **libpng/1.6.37**
CMake configure step fails with error:
```
CMake Error at source_subfolder/CMakeLists.txt:892 (install):
install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
target "pngfix".
```
<details><summary>Full output:</summary>
```
libpng/1.6.37: Calling build()
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler …
```

libpng/1.6.37: fix building shared library for iOS

---

recipes/sdl/all/conanfile.py

Specify library name and version:  **sdl/2.0.20**
- shared library no longer enforces linked frameworks on consumers, as this info is already encoded in the library itself
- CoreHaptics appeared fairly recently (iOS 13 / macOS 10.15) and should be weakly linked to avoid "dylib not found" error when deploying to older OS versions
- also performed v2 migration based on linter report
Note that simple `-weak_framework CoreHaptics` doesn't work (as well as quoting it): it's translated into
-weak_framework  -lCoreHaptics
Looks like something that should be adjusted in Conan.
---

SDL: improve linker settings for Apple platforms + v2 linter changes

---

recipes/mpir/all/conanfile.py
recipes/mpir/all/test_package/CMakeLists.txt
recipes/mpir/all/test_package/conanfile.py

Specify library name and version:  **MPIR/3.0.0**
MPIR recipe does not work if you have just Visual Studio 2022 or 2019 installed.
---

mpir: patch for Visual Studio 2019 and 2022

---

recipes/android-ndk/all/conanfile.py
recipes/android-ndk/all/test_package/CMakeLists.txt
recipes/android-ndk/all/test_package/conanfile.py
recipes/android-ndk/all/test_v1_package/CMakeLists.txt

- define env vars in `buildenv_info`
- prepend toolchain file to `tools.cmake.cmaketoolchain:user_toolchain`
- run build requirements executables in test package regardless of whether we cross-build or not and fix the variables context of these executions.
---

android-ndk: more conan v2 stuff

---

recipes/cairo/all/conanfile.py
recipes/cairo/meson/conanfile.py

Specify library name and version:  **cairo/**
The cairo package sets the name of the base pkg-config component file to "cairo" which renames the default parent component (the one containing all the sub-components).
The result is that dependent packages using the pkg-config generator and linking to "cairo" only get the base cairo component and not additional components such as `cairo-gobject`. This can result linking errors in dependent packages (specifically in the MSVC build of gtkmm which expects `cairo` to also include `cairo-gobject`)
---

[cairo] v2 support

---

recipes/z3/all/conandata.yml
recipes/z3/all/conanfile.py
recipes/z3/all/patches/0001-cmake-use-conan-mpir-4.10.2.patch
recipes/z3/all/patches/0001-cmake-use-conan-mpir-4.8.8.patch
recipes/z3/all/patches/0002-python-interp-3-4.8.8.patch
recipes/z3/all/patches/0003-cmake-try-compile-flags-4.10.2.patch
recipes/z3/config.yml

Library name and version:  **z3/4.10.2**.
Using `mpir` for `z3` is a specific use, and it is incompatible with using `gmp`, the more usual dependency `z3` supports. It results with the impossibility to use `z3` along with other libraries using `gmp`. See #11583.
With this PR, we let `gmp` be used by default, while letting the possibility to build `z3` with `mpir` or an internal implementation.
---

(#11583) z3: versions 4.10.2 and do not require `mpir`

---

recipes/wayland/all/conanfile.py

wayland: Fix compatibility with Conan 1.52

---

recipes/wasmedge/all/conandata.yml

While I wait for [this PR](https://github.com/conan-io/conan-center-index/pull/12765) to pass, let's do some housecleaning.

wasmedge - fix YML linter (conandata.yml)

---

recipes/qt/5.x.x/conanfile.py

Designer isn't built by Qt in such case, but Conan creates a module for it and then cmake configuration fails with:
```
CMake Error at build-arm/cmakedeps_macros.cmake:39 (message):
Library 'Qt5Designer' not found in package.  If 'Qt5Designer' is a system
library, declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
build-arm/Qt5-Target-release.cmake:34 (conan_package_library_targets)
build-arm/Qt5Targets.cmake:26 (include)
build-arm/Qt5Config.cmake:10 (include)
CMakeLists.txt:252 (find_package)
```
Specify library name and version:  **Qt/5.15.5**
Also performed v2 migration.
I have cross-built shared version of Qt 5.15.5 for ARM Mac (armv8) successfully, used the following options:
```
"qt/*:openssl": False,
"qt/*:qttools": True,
"qt/*:with_freetype": …
```

Qt 5: don't create Designer module when cross-building + v2 linter changes

---

recipes/tixi3/all/conandata.yml
recipes/tixi3/all/conanfile.py
recipes/tixi3/all/patches/disable_tixi_examples.patch
recipes/tixi3/all/patches/link_curl.patch
recipes/tixi3/all/test_package/CMakeLists.txt
recipes/tixi3/all/test_package/conanfile.py
recipes/tixi3/all/test_package/main.cpp
recipes/tixi3/all/test_v1_package/CMakeLists.txt
recipes/tixi3/all/test_v1_package/conanfile.py
recipes/tixi3/config.yml

Specify library name and version:  **tixi3/3.3.0**
Tixi3 is a xml library based on libxml2 with a very simple API and is used by multiple open source software packages, in particular used by the German Aerospace Center.
Website: https://github.com/DLR-SC/tixi
I was the main author of the library for the last 10 years and I'd like to share the conan package. 
Tixi3 is not yet used by other packages in the conan center index, but we plan to publish more packages that use tixi3.
_Note: This is my first conan package, so I might need more explanations than usually if changes are required._
---

Added tixi3 3.3.0 conan package

---

recipes/argh/all/conanfile.py
recipes/argh/all/test_package/CMakeLists.txt
recipes/argh/all/test_package/conanfile.py
recipes/argh/all/test_v1_package/CMakeLists.txt
recipes/argh/all/test_v1_package/conanfile.py

CMake imported target is not namespaced, see https://github.com/adishavit/argh/blob/v1.3.2/CMakeLists.txt#L48-L52
---

argh: conan v2 support + fix CMake imported target (`argh` instead of `argh::argh`)

---

recipes/glog/all/conandata.yml
recipes/glog/all/conanfile.py

Fixes #8568
Specify library name and version:  **glog/0.5.0** **glog/0.6.0**
`glog` didnt specify `libunwind` as a dependency: add it to the requirements and make it optional.
---

glog: Make libunwind optional, add to requirements

---

recipes/libgd/all/conanfile.py

fixes #12069
The occurred when building the libgd package having with_png=true.
This would add a dependency to getopt-for-visual-studio which
is configured to fail immediately if the compiler is not visual studio.
The CI was probably able to build this since the with_png option is by
default false.
The proposed solution is to only add getopt-for-visual-studio if the
detected compiler is in fact visual studio, and only then.
Specify library name and version:  **libgd/2.3.2**
I am submitting this PR because I use libgd in my project, but wasn't able to build it for linux when png was enabled. Investigating the recipe, I discovered that the problem is a bug in the recipe, and I would like to contribute a fix to the community.
---

libgd: Only add getopt-for-visual-studio if compiler is visual studio

---

recipes/minizip/all/conanfile.py

Specify library name and version:  **minizip/***
---

minizip: generate gcc11 binaries

---

recipes/matchit/all/conandata.yml
recipes/matchit/all/conanfile.py
recipes/matchit/all/test_package/CMakeLists.txt
recipes/matchit/all/test_package/conanfile.py
recipes/matchit/all/test_package/test_package.cpp
recipes/matchit/all/test_v1_package/CMakeLists.txt
recipes/matchit/all/test_v1_package/conanfile.py
recipes/matchit/config.yml

**matchit/1.0.1**
It's a brand new C++ header-only library that was released recently. I've seen that it only [has](https://github.com/BowenFu/matchit.cpp#option-4-manage-with-vcpkg) vcpkg support. So I decided to add conan support too as I would prefer to use it myself. It's main purpose to represent Rust-like enum pattern matchers into C++ and provide new coding style paradigm into the language.
---

add matchit 1.0.1

---

recipes/boost/all/conanfile.py

As was discovered in https://github.com/faithfracture/Apple-Boost-BuildScript/issues/50 / https://github.com/boostorg/filesystem/issues/147, using `BOOST_SP_USE_SPINLOCK` instead of `BOOST_*_USE_PTHREADS` fixes boost.filesystem crashes on iOS.
Original issue: #3867
---

Boost: iOS should use spinlock instead of pthread to prevent filesystem crashes

---

recipes/sdbus-cpp/all/CMakeLists.txt
recipes/sdbus-cpp/all/conandata.yml
recipes/sdbus-cpp/all/conanfile.py
recipes/sdbus-cpp/all/test_package/CMakeLists.txt
recipes/sdbus-cpp/all/test_package/conanfile.py
recipes/sdbus-cpp/all/test_pkgconf/CMakeLists.txt
recipes/sdbus-cpp/all/test_pkgconf/conanfile.py
recipes/sdbus-cpp/all/test_v1_package/CMakeLists.txt
recipes/sdbus-cpp/all/test_v1_package/conanfile.py
recipes/sdbus-cpp/all/test_v1_pkgconf/CMakeLists.txt
recipes/sdbus-cpp/all/test_v1_pkgconf/conanfile.py
recipes/sdbus-cpp/config.yml

* Package dependencies/build dependencies were updated.
* The recipe has been updated to be compatible with Conan V1/V2.
* A few warning fixes and random clean-ups.
* Updated information about package license.
---

sdbus-cpp: conan v2 support

---

recipes/boost/all/conanfile.py

The `msvs_toolset()` function does not support the `msvc` compiler.
The function derives the toolset version from the `Visual Studio` version.
Since the `msvc` compiler uses a different versioning scheme, this does not work for `msvc`.
This commit just adds the corresponding logic to do this for `msvc`.
The same logic is still used for `Visual Studio`.
Specify library name and version:  **boost/***
---

boost: Add support for retrieving the toolset when using msvc

---

recipes/libaom-av1/all/CMakeLists.txt
recipes/libaom-av1/all/conandata.yml
recipes/libaom-av1/all/conanfile.py
recipes/libaom-av1/all/patches/0001-3.4.0-fix-install.patch
recipes/libaom-av1/all/test_package/conanfile.py
recipes/libaom-av1/all/test_v1_package/CMakeLists.txt
recipes/libaom-av1/all/test_v1_package/conanfile.py
recipes/libaom-av1/config.yml

Few improvements as well:
- relax constraints on compiler versions by injecting CMAKE_C_STANDARD 99 (looking at original PR, it was coming from for loops with value initialization, a C99 feature).
- libaom-av1 is a pure C library (examples are in C++, as well as few optional vendored deps which are disabled here), so remove libcxx & cppstd
---

libaom-av1: add 3.4.0 + conan v2 support

---

recipes/libalsa/all/conandata.yml
recipes/libalsa/all/conanfile.py
recipes/libalsa/all/test_package/conanfile.py
recipes/libalsa/all/test_v1_package/CMakeLists.txt
recipes/libalsa/all/test_v1_package/conanfile.py

libalsa: conan v2 support

---

recipes/openssl/1.x.x/conanfile.py
recipes/openssl/3.x.x/conanfile.py

`OPENSSL_FOUND` is not defined if `find_package()` consumes the config file from CMakeDeps (another side effect for https://github.com/conan-io/conan/issues/10387). This PR fixes this issue by setting `OPENSSL_FOUND` to `TRUE` unconditionally.
I've seen this issue while trying to migrate mariadb-connector-c, its CMakeLists has a strong logic based on OPENSSL_FOUND, and it miserably fails if casing is wrong.
---

openssl: define `OPENSSL_FOUND` in `CMakeDeps` generator

---

recipes/bzip2/all/conanfile.py

same fix than https://github.com/conan-io/conan-center-index/pull/12838
---

bzip2: fix `BZIP2_FOUND` in CMakeDeps

---

recipes/ittapi/all/conandata.yml
recipes/ittapi/all/conanfile.py
recipes/ittapi/all/test_package/CMakeLists.txt
recipes/ittapi/all/test_package/conanfile.py
recipes/ittapi/all/test_package/test_package.cpp
recipes/ittapi/all/test_v1_package/CMakeLists.txt
recipes/ittapi/all/test_v1_package/conanfile.py
recipes/ittapi/config.yml

Specify library name and version:  **ittapi/3.23.0**
Intel ITT API (Instrumentation and Tracing Technology API) enables generation and control over profiling using Intel's VTune Profiler. This is a key API required to collect useful trace data for performance optimization work.
This API is similar in functionality to NVTX API, which targets Nvidia's Nsight Systems Profiler (`nvtx` already exists in Conan Center).
---

Adding intel itt api

---

recipes/daw_json_link/all/conandata.yml
recipes/daw_json_link/config.yml

Specify library name and version:  **daw_json_link/3.0.5**
---

daw_json_link: add version 3.0.5

---

docs/package_templates/header_only/all/conandata.yml
docs/package_templates/header_only/all/conanfile.py
docs/package_templates/header_only/all/test_package/CMakeLists.txt
docs/package_templates/header_only/all/test_package/conanfile.py
docs/package_templates/header_only/all/test_package/test_package.cpp
docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt
docs/package_templates/header_only/all/test_v1_package/conanfile.py
docs/package_templates/header_only/config.yml

Related to https://github.com/conan-io/conan-center-index/pull/12678
- Add cross-compatible Conan v1 & v2 template based on header-only example
---

[docs] header-only package template

---

docs/package_templates/msbuild_package/all/conandata.yml
docs/package_templates/msbuild_package/all/conanfile.py
docs/package_templates/msbuild_package/all/test_package/CMakeLists.txt
docs/package_templates/msbuild_package/all/test_package/conanfile.py
docs/package_templates/msbuild_package/all/test_package/test_package.cpp
docs/package_templates/msbuild_package/all/test_v1_package/CMakeLists.txt
docs/package_templates/msbuild_package/all/test_v1_package/conanfile.py
docs/package_templates/msbuild_package/config.yml

Related to https://github.com/conan-io/conan-center-index/pull/12678
- Add cross-compatible Conan v1 & v2 template based on msbuild example
---

[docs] Add msbuild package template

---

recipes/opentdf-client/all/conanfile.py
recipes/opentdf-client/all/test_package/conanfile.py

Specify library name and version:  **opentdf-client/1.1.5**
- Allow visual studio 15
- Add option to have 3rd party libs exclude libiconv
---

opentdf-client - recipe enhancements

---

recipes/cminpack/all/conandata.yml
recipes/cminpack/all/conanfile.py
recipes/cminpack/all/test_package/CMakeLists.txt
recipes/cminpack/all/test_package/conanfile.py
recipes/cminpack/all/test_package/tchkderc.c
recipes/cminpack/all/test_v1_package/CMakeLists.txt
recipes/cminpack/all/test_v1_package/conanfile.py
recipes/cminpack/config.yml

Specify library name and version:  **cminpack/1.3.8**
CMinPack is a mathematical solver used in numerical computing. It is quite popular, hence a conan package is yet missed.
The test package uses an official example from the cminpack repository.
The official cmake targets are `cminpack::cminpack` for the double precision library and `cminpack::cminpacks` for the single precision version of it.
---

Added recipe for cminpack

---

recipes/openssl/1.x.x/test_package/conanfile.py

On `1.50.2` the class `scm.Version` was changed (https://github.com/conan-io/conan/pull/11823). This `test_package` fails with `1.50.1`. I've been bitten by this today, so I think it can be useful to annotate it.

openssl - Annotate version required to run the tests

---

recipes/cpp-peglib/1.x.x/conandata.yml
recipes/cpp-peglib/config.yml

Specify library name and version:  **cpp-peglib/1.8.1**
---

cpp-peglib: add version 1.8.1

---

recipes/android-ndk/all/conanfile.py

Specify library name and version:  **android-ndk/r25**
A recent change of this package added the cmake toolchain file from the NDK as a user toolchain, which is problematic because the CMakeToolchain generator also adds this, resulting in breakage for packages that use this generator, as described in issue #12723 
---

fixes android-ndk regression with CMakeToolchain

---

recipes/opencore-amr/all/conandata.yml
recipes/opencore-amr/all/conanfile.py
recipes/opencore-amr/config.yml

Specify library name and version:  **opencore-amr/0.1.6**
Added new version of the library. Tested locally with msvc15.
I also started recipe migration for Conan 2.0 but not sure if I am doing it right.
---

opencore-amr/0.1.6: bump library version

---

recipes/roaring/all/conandata.yml
recipes/roaring/config.yml

Specify library name and version:  **roaring/0.7.1**
---

roaring: add version 0.7.1

---

recipes/xkbcommon/all/conanfile.py
recipes/xkbcommon/all/test_package/conanfile.py

Small fixes that weren't able to be addressed before #11636 was merged.
@SpaceIm PTAL
---

xkbcommon: Small fixes

---

recipes/earcut/all/conandata.yml
recipes/earcut/config.yml

Specify library name and version:  **earcut/2.2.4**
---

earcut: add version 2.2.4

---

recipes/msgpack-cxx/all/conandata.yml
recipes/msgpack-cxx/config.yml

Specify library name and version:  **msgpack-cxx/4.1.2**
---

msgpack-cxx: add version 4.1.2

---

docs/labels.md

It's not documented that the CI restarts automatically unexpected error.
---

[docs] Clarify Unexpected error restarting

---

recipes/etl/all/conandata.yml
recipes/etl/config.yml

Specify library name and version:  **etl/20.34.0**
---

etl: add version 20.34.0

---

recipes/xnnpack/all/conandata.yml
recipes/xnnpack/config.yml

Specify library name and version:  **xnnpack/cci.20220801**
This version is required by **tensorflow-lite/2.10.0**. See #12390.
---

[xnnpack] Add cci.20220801

---

docs/package_templates/autotools_package/all/test_v1_package/CMakeLists.txt
docs/package_templates/cmake_package/all/test_v1_package/CMakeLists.txt
docs/package_templates/header_only/all/test_v1_package/CMakeLists.txt
docs/package_templates/msbuild_package/all/test_v1_package/CMakeLists.txt

The method `set_compile_features`  does not exist. The correct one is [target_compile_features](https://cmake.org/cmake/help/latest/command/target_compile_features.html)
---

[docs] Hotfix replace wrong cmake method in docs

---

recipes/vulkan-validationlayers/all/conanfile.py

Specify library name and version:  **vulkan-validationlayers/all**
It is needed to avoid version conflicts in diligent-core
---

bump dependencies of vulkan-validationlayers; partial conan v2 upgrade

---

recipes/bandit/all/conandata.yml
recipes/bandit/all/conanfile.py
recipes/bandit/all/patches/0001-change-snowhouse-path.patch
recipes/bandit/all/test_package/CMakeLists.txt
recipes/bandit/all/test_package/conanfile.py
recipes/bandit/all/test_package/test_package.cpp
recipes/bandit/all/test_v1_package/CMakeLists.txt
recipes/bandit/all/test_v1_package/conanfile.py
recipes/bandit/config.yml

Add bandit

---

linter/check_import_conanfile.py

As importing the `ConanFile` from new `conan` namespace does not have a major implication on recipes, it is time to make the linter error in case it is imported from `conans`. This way we can make a step forward toward Conan 2
/cc @jgsogo @uilianries as commented on today's meeting

[linter] Convert import ConanFile from conans into an error

---

recipes/qxmpp/all/conanfile.py

Fixes #12180
Specify library name and version:  **qxmpp/1.4.0**
Noticed the problem when attempting to build this recipe on MacOS 12.5. It was an openssl version mismatch (diamond dependency issue).
---

Update qxmpp to use Qt 6.2.4

---

recipes/fmt/all/conanfile.py
recipes/fmt/all/test_package/conanfile.py

fmt: conan v2 modernize

---

docs/package_templates/cmake_package/all/conanfile.py

Specify library name and version:  **docs**
- `tc.cache_variables.definitions` seems to be wrong. fix it.
- there is no `configure` in `build()`. add it.
---

[docs] package_templates/cmake_package : fix `cache_variables.definitions` and add `configure`

---

recipes/magic_enum/all/conandata.yml
recipes/magic_enum/config.yml

Specify library name and version:  **magic_enum/0.8.1**
---

magic_enum: add version 0.8.1

---

recipes/libnghttp2/all/conandata.yml
recipes/libnghttp2/config.yml

Specify library name and version:  **libnghttp2/***
---

libnghttp2: add version 1.49.0

---

recipes/kuba-zip/all/conandata.yml
recipes/kuba-zip/config.yml

Specify library name and version:  **kuba-zip/0.2.5**
---

kuba-zip: add version 0.2.5

---

recipes/statslib/all/conandata.yml
recipes/statslib/config.yml

Specify library name and version:  **statslib/3.2.0**
!
---

statslib: add version 3.2.0

---

recipes/at-spi2-core/config.yml
recipes/at-spi2-core/new/conandata.yml

Specify library name and version:  **at-spi2-core/2.46.0**
---

at-spi2-core: add version 2.46.0

---

recipes/thrift/all/conandata.yml
recipes/thrift/config.yml

Specify library name and version:  **thrift/0.17.0**
---

thrift: add version 0.17.0

---

recipes/bitflags/all/conandata.yml
recipes/bitflags/all/conanfile.py
recipes/bitflags/all/test_package/CMakeLists.txt
recipes/bitflags/all/test_package/conanfile.py
recipes/bitflags/all/test_package/test_package.cpp
recipes/bitflags/all/test_v1_package/CMakeLists.txt
recipes/bitflags/all/test_v1_package/conanfile.py
recipes/bitflags/config.yml

Specify library name and version:  **bitflags/1.5.0**
Contribute recipe for [m-peko/bitflags](https://github.com/m-peko/bitflags), a header-only library for easily managing set of auto-generated type-safe flags.
I am not the author of this library, but some of my projects depend on it.
---

biflags: new recipe

---

recipes/wayland/all/conanfile.py

closes https://github.com/conan-io/conan-center-index/issues/12947
---

wayland: fix native build when dependencies of wayland-scanner are shared

---

docs/package_templates/cmake_package/all/conanfile.py

Reported by @Nekto89 
Related to https://github.com/conan-io/conan-center-index/pull/12978#discussion_r973554223
---

[docs] Fix leftover dot for cache_variables

---

recipes/qwt/all/conandata.yml
recipes/qwt/all/conanfile.py
recipes/qwt/all/patches/cmake-support-patch.patch
recipes/qwt/all/patches/cmake-support.patch
recipes/qwt/all/test_package/CMakeLists.txt
recipes/qwt/all/test_package/conanfile.py
recipes/qwt/config.yml

Specify library name and version:  **qwt/6.2.0**
---
- [x ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.

qwt: Use Cmake instead of qmake

---

recipes/json-c/all/conandata.yml
recipes/json-c/config.yml

Specify library name and version:  **json-c/0.16**
---

json-c: add version 0.16

---

recipes/unordered_dense/all/conandata.yml
recipes/unordered_dense/all/conanfile.py
recipes/unordered_dense/all/test_package/CMakeLists.txt
recipes/unordered_dense/all/test_package/conanfile.py
recipes/unordered_dense/all/test_package/test_package.cpp
recipes/unordered_dense/all/test_v1_package/CMakeLists.txt
recipes/unordered_dense/all/test_v1_package/conanfile.py
recipes/unordered_dense/config.yml

Specify library name and version:  **unordered_dense/1.3.1**
unordered_dense seems to be the successor of [robin-hood-hashing](https://github.com/martinus/robin-hood-hashing).
---

unordered_dense: add recipe

---

recipes/opentdf-client/all/conandata.yml
recipes/opentdf-client/config.yml

Specify library name and version:  **opentdf-client/1.1.6**
Added benchmarking functions
---

opentdf-client: add version 1.1.6

---

docs/how_to_add_packages.md
docs/package_templates/README.md

Our current documentation is fragmented, so users need to visit recursive links, which makes the learning curve a maze. I would like to centralize a good and centralize documentation, where people can read from the start and stop jumping to another pages, then provide their first recipe.
This model also updates the first recipe, it should use the current templates. It harder for users, because their will arrive in middle a migration, so need to learn about both v1 and v2, but avoids the technical debt in the future.
---

[docs] How to add packages based on new templates

---

.github/ISSUE_TEMPLATE/package_bug.yml

Frequently we have broken packages reported without any further information, making it impossible to be reproduced. Users should be more inclined to populate useful information.
---

[docs] Enforce to ask more details when reporting a bug report

---

recipes/cpp-peglib/1.x.x/conandata.yml
recipes/cpp-peglib/config.yml

Specify library name and version:  **cpp-peglib/1.8.2**
---

cpp-peglib: add version 1.8.2

---

recipes/libpng/all/conandata.yml
recipes/libpng/config.yml

Specify library name and version:  **libpng/1.6.38**
The libpng 1.6.38 version was just released earlier this week, and we would like to stay up-to-date with the latest version for maintenance of internal products.
---

Add libpng 1.6.38 to conandata and config

---

recipes/unordered_dense/all/conandata.yml
recipes/unordered_dense/config.yml

Specify library name and version:  **unordered_dense/1.3.2**
---

unordered_dense: add version 1.3.2

---

docs/package_templates/autotools_package/all/conanfile.py
docs/package_templates/cmake_package/all/conanfile.py
docs/package_templates/header_only/all/conanfile.py
docs/package_templates/msbuild_package/all/conanfile.py

As Conan 1.52.0 is now running on CCI, `export_conandata_patches` will become commonly used.
---

[templates] Use Conan 1.52.0 feature

---

docs/how_to_add_packages.md
docs/reviewing.md

docs: use export_conandata_patches

---

recipes/quill/all/conandata.yml
recipes/quill/config.yml

Specify library name and version:  **quill/2.2.0**
---

quill: add version 2.2.0

---

recipes/glslang/all/conandata.yml
recipes/glslang/all/conanfile.py
recipes/glslang/all/test_package/conanfile.py
recipes/glslang/all/test_v1_package/CMakeLists.txt
recipes/glslang/all/test_v1_package/conanfile.py
recipes/glslang/config.yml

glslang: add 1.3.224.0 + partial conan v2 support

---

recipes/unordered_dense/all/conandata.yml
recipes/unordered_dense/config.yml

Specify library name and version:  **unordered_dense/1.3.3**
---

unordered_dense: add version 1.3.3

---

recipes/itlib/all/conandata.yml
recipes/itlib/config.yml

Specify library name and version:  **itlib/1.6.3**
---

itlib: add version 1.6.3

---

recipes/greg7mdp-gtl/all/conandata.yml
recipes/greg7mdp-gtl/config.yml

Specify library name and version:  **greg7mdp-gtl/1.1.4**
---

greg7mdp-gtl: add version 1.1.4

---

recipes/argparse/all/conandata.yml
recipes/argparse/config.yml

Specify library name and version:  **argparse/2.9**
---

argparse: add version 2.9

---

recipes/nlohmann_json/all/conanfile.py
recipes/nlohmann_json/all/test_package/CMakeLists.txt
recipes/nlohmann_json/all/test_package/conanfile.py
recipes/nlohmann_json/all/test_v1_package/CMakeLists.txt

- avoid to propagate empty bin/lib/res dirs
- check min cppstd
---

nlohmann_json: small improvements

---

recipes/gtest/all/conanfile.py

gtest: set the correct required_conan_version + few minor fixes

---

recipes/parallel-hashmap/all/conandata.yml
recipes/parallel-hashmap/config.yml

Specify library name and version:  **parallel-hashmap/1.37**
---

parallel-hashmap: add version 1.37

---

recipes/libalsa/all/conanfile.py
recipes/libalsa/all/test_package/conanfile.py

see https://github.com/conan-io/docs/issues/2767
---

libalsa: set cpp_info.resdirs & minor improvements

---

recipes/poco/all/conanfile.py

Specify library name and version:  **poco/1.9.4**
Fixes MacOS 12.6 compilation of **poco** library.
---

poco: bump sqlite3 dependency version for MacOS

---

docs/how_to_add_packages.md

Fix for https://github.com/conan-io/conan-center-index/pull/12931
Asked for better documentation here: https://github.com/conan-io/docs/issues/2750
---

[docs] Templates documentation: Fix link for test package

---

recipes/xz_utils/all/conanfile.py
recipes/xz_utils/all/test_package/CMakeLists.txt
recipes/xz_utils/all/test_package/conanfile.py
recipes/xz_utils/all/test_v1_package/CMakeLists.txt
recipes/xz_utils/all/test_v1_package/conanfile.py

xz_utils: conan v2 support

---

.c3i/config_v1.yml
recipes/libatomic_ops/all/conandata.yml
recipes/libatomic_ops/all/conanfile.py
recipes/libatomic_ops/all/patches/enable-cmake-7_6_14.patch
recipes/libatomic_ops/all/patches/update-cmake-7_6_14.patch
recipes/libatomic_ops/all/test_package/CMakeLists.txt
recipes/libatomic_ops/all/test_package/conanfile.py
recipes/libatomic_ops/config.yml

This is to match cmake package/target naming of upstream.
Also, prepare for Conan 2.0.
Specify library name and version:  **libatomic_ops/7.6.14**
---

libatomic_ops: change cmake package name to Atomic_ops

---

.github/workflows/marldown-links.yml
.github/workflows/mlc_config.json

There are a handful of broken links in the docs. It would be nice to catch them in PRs and double check master.
---

github_config: add an action to validate markdown links

---

recipes/concurrencpp/all/conandata.yml
recipes/concurrencpp/all/conanfile.py
recipes/concurrencpp/all/patches/directory-name-0.1.5.patch
recipes/concurrencpp/config.yml

Specify library name and version:  **concurrencpp/0.1.5**
This updates the recipe for the latest version of the library.
---

concurrencpp: Update to 0.1.5

---

recipes/wasmtime/all/conandata.yml
recipes/wasmtime/all/conanfile.py
recipes/wasmtime/all/test_package/conanfile.py
recipes/wasmtime/all/test_v1_package/CMakeLists.txt
recipes/wasmtime/all/test_v1_package/conanfile.py
recipes/wasmtime/config.yml

Specify library name and version:  **wasmtime/***
- add version 1.0.0
- remove old versions
---

wasmtime: add version 1.0.1 and support conan V2

---

recipes/mcap/all/conandata.yml
recipes/mcap/all/conanfile.py
recipes/mcap/all/test_package/CMakeLists.txt
recipes/mcap/all/test_package/conanfile.py
recipes/mcap/all/test_v1_package/CMakeLists.txt
recipes/mcap/all/test_v1_package/conanfile.py
recipes/mcap/config.yml

Upgrades `mcap` to 0.5.0.
Updates the recipe with the new license info, which was changed in https://github.com/foxglove/mcap/pull/601 / https://github.com/foxglove/mcap/pull/608.
---

mcap: add 0.3.0, 0.4.0, 0.5.0

---

recipes/drmp3/all/CMakeLists.txt
recipes/drmp3/all/conandata.yml
recipes/drmp3/all/conanfile.py
recipes/drmp3/all/test_package/conanfile.py
recipes/drmp3/all/test_v1_package/CMakeLists.txt
recipes/drmp3/all/test_v1_package/conanfile.py
recipes/drmp3/config.yml

Specify library name and version:  **drmp3/0.6.34**
This updates the recipe for the latest version of the library and also updates it for Conan v2. See also the almost identical update for drflac: https://github.com/conan-io/conan-center-index/pull/13145
---

drmp3: update to 0.6.34

---

.c3i/reviewers.yml

Replaces https://github.com/conan-io/conan-center-index/pull/13188, only maintainers can make PRs modifying these configuration files.
From @ericLemanissier ´s PR:
> This is a proposition: add @jwillikers to the community reviewers, as he already spends some time to review pull requests https://github.com/conan-io/conan-center-index/pulls?q=is%3Apr+reviewed-by%3Ajwillikers and he also has a significant number of merged pull requests https://github.com/conan-io/conan-center-index/pulls?q=is%3Apr+author%3Ajwillikers

[community] Add jwillikers as community reviewer

---

recipes/nettle/all/conandata.yml
recipes/nettle/all/conanfile.py
recipes/nettle/all/test_package/conanfile.py
recipes/nettle/all/test_v1_package/CMakeLists.txt
recipes/nettle/all/test_v1_package/conanfile.py
recipes/nettle/config.yml

Specify library name and version:  **nettle/3.8.1**
- Add latest nettle release available: 3.8.1
- Fix pkgconfig: Should generate separated files, one per library
- Add support for Conan 2.0
- Add custom cmake targets, based on libarchive and libzip
---

[nettle] support Conan 2.0 and add 3.8.1

---

recipes/opentdf-client/all/conandata.yml
recipes/opentdf-client/config.yml

Specify library name and version:  **opentdf-client/1.2.0**
- API updates to improve use of TDFStorageType
- Added better reporting and handling of exceptions
---

opentdf-client: add version 1.2.0

---

recipes/mosquitto/2.x/conanfile.py

fixes #13006
Specify library name and version:  **mosquitto/2.x**
The mosquitto recipe does not allow to set the WITH_THREADING cmake option.
This MR add a boolean "threading" option to the recipe, with the default value of "True".
fixes #13006.
---
- [ x] I've read the [guidelines](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md) for contributing.
- [ x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ x] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.

[mosquitto] support threading options in recipe

---

recipes/osmanip/all/conandata.yml
recipes/osmanip/config.yml

Specify library name and version:  **osmanip/4.2.2**
---

osmanip: add version 4.2.2

---

recipes/bdwgc/all/conanfile.py
recipes/bdwgc/all/patches/update-cmake-8_0_4.patch
recipes/bdwgc/all/patches/update-cmake-8_0_6.patch
recipes/bdwgc/all/patches/update-cmake-8_2_2.patch

Specify library name and version:  **bdwgc/8.2.2** (and existing older versions)
This is a fix of dependency package/target name after the corresponding change in libatomic_ops, https://github.com/conan-io/conan-center-index/pull/13042.
I'm upstream maintainer of bdwgc and libatomic_ops.
---

bdwgc: Fix libatomic_ops dependency package/target name

---

recipes/c-blosc2/all/conandata.yml
recipes/c-blosc2/config.yml

Specify library name and version:  **c-blosc2/2.4.2**
---

c-blosc2: add version 2.4.2

---

recipes/parallel-hashmap/all/conandata.yml
recipes/parallel-hashmap/config.yml

Specify library name and version:  **parallel-hashmap/1.3.8**

Bump parallel-hashmap version to 1.3.8

---

recipes/ctre/all/conandata.yml
recipes/ctre/config.yml

Specify library name and version:  **ctre/3.7.1**
---

ctre: add version 3.7.1

---

recipes/paho-mqtt-c/all/conandata.yml
recipes/paho-mqtt-c/config.yml

Specify library name and version:  **paho-mqtt-c/1.3.11**
---

paho-mqtt-c: add version 1.3.11

---

recipes/libmodbus/all/conanfile.py
recipes/libmodbus/all/test_package/test_package.c
recipes/libmodbus/all/test_v1_package/conanfile.py

addresses reviews in https://github.com/conan-io/conan-center-index/pull/12835, and more
- remove useless generators
- do not test compiler.cppstd, it's a C library
- restore cpp_info.includedirs before https://github.com/conan-io/conan-center-index/pull/12835, to add `include/modbus` (convention of upstream pkgconf file).
- fix `compiler=msvc` & shared
---

libmodbus: several improvements

---

recipes/nettle/all/conanfile.py
recipes/nettle/all/test_package/CMakeLists.txt
recipes/nettle/all/test_v1_package/CMakeLists.txt

addresses reviews in https://github.com/conan-io/conan-center-index/pull/13176:
- requires conan > 1.51.1
- `win_bash=True` required if build os is windows (it's not a host os logic)
- remove useless PkgConfigDeps
- relocatable shared libs on macOS
- fix install on Windows
- restore previous component names & do not suggest unofficial cmake names
- hogweed lib requires nettle lib, not the opposite
---

nettle: several fixes

---

recipes/libsystemd/all/conanfile.py

Specify library name and version:  **libsystemd/all**
We need VirtualBuildEnv in this recipe to guarantee that build_requirements will be used during build. Or else locally installed dependencies may be used instead.
---

libsystemd/all: Add missing VirtualBuildEnv

---

recipes/unordered_dense/all/conandata.yml
recipes/unordered_dense/config.yml

Specify library name and version:  **unordered_dense/1.4.0**
---

unordered_dense: add version 1.4.0

---

recipes/aws-c-common/all/conandata.yml
recipes/aws-c-common/config.yml

Specify library name and version:  **aws-c-common/0.8.2**
---

aws-c-common: add version 0.8.2

---

recipes/libtasn1/all/test_v1_package/CMakeLists.txt
recipes/libtasn1/all/test_v1_package/conanfile.py

There's a possible bug in Conan (https://github.com/conan-io/conan/issues/12237) that may cause a bad interaction between `find_package()` and `find_program()` when the same dependency is listed both as `requires` and `tool_requires`, and we are cross-building. This test also uses the legacy generators, so this might not get fixed in Conan 1.x.
While I appreciate that the `test_v1_package` will be eventually removed and may be of lower priority, suppressing tests in a way that makes them look like they passed on CI is probably not a good idea, unless there are comments explaining the reasoning behind it.
This PR restores the test in that scenario, and adds `NO_CMAKE_PATH` as a workaround to the aforementioned bug.

libtasn1: Restore ability to run test_v1_package when cross-building

---

recipes/gdal/post_3.5.0/conanfile.py

**gdal/3.5.2**
libjpeg-turbo was not referenced properly. For some reason it worked on my linux install, but the problem shows up on windows.
This fixes linking with static and shared libjpeg-turbo.
Closes #13270 
---

gdal/3.5.2: fix with_jpeg=libjpeg-turbo option

---

recipes/simdjson/all/conandata.yml
recipes/simdjson/all/conanfile.py
recipes/simdjson/config.yml

Specify library name and version:  **simdjson/2.2.3**
- add version 2.2.3
- set `pkg_config_name` when version is 2.2.3 or later.
---

simdjson: add version 2.2.3 and set pkg_config_name in 2.2.3

---

recipes/libiconv/all/conandata.yml
recipes/libiconv/all/conanfile.py
recipes/libiconv/all/test_package/CMakeLists.txt
recipes/libiconv/all/test_package/conanfile.py
recipes/libiconv/all/test_v1_package/CMakeLists.txt
recipes/libiconv/all/test_v1_package/conanfile.py

Specify library name and version:  **libiconv**
Conan v2 and toolchain updates
---

[libiconv] conan v2 update

---

recipes/jwt-cpp/all/conanfile.py

Specify library name and version:  **jwt-cpp/0.6.0**
fixes #13286
---

[jwt-cpp] Requires conan 1.50.0 at least

---

recipes/aws-checksums/all/conandata.yml
recipes/aws-checksums/all/conanfile.py
recipes/aws-checksums/config.yml

Specify library name and version:  **aws-checksums/0.1.13**
- add version 0.1.13.
- use `export_conandata_patches`
- update aws-c-common to 0.8.2
---

aws-checksums: add version 0.1.13 and update dependencies

---

recipes/aws-c-io/all/CMakeLists.txt
recipes/aws-c-io/all/conandata.yml
recipes/aws-c-io/all/conanfile.py
recipes/aws-c-io/all/test_package/conanfile.py
recipes/aws-c-io/all/test_v1_package/CMakeLists.txt
recipes/aws-c-io/all/test_v1_package/conanfile.py
recipes/aws-c-io/config.yml

Specify library name and version:  **aws-c-io/***
- add version 0.13.4
---

aws-c-io: add version 0.13.4 and support conan v2

---

recipes/gcem/all/conandata.yml
recipes/gcem/config.yml

Specify library name and version:  **gcem/1.16.0**
---

gcem: add version 1.16.0

---

recipes/flatbuffers/all/conandata.yml
recipes/flatbuffers/all/conanfile.py
recipes/flatbuffers/all/test_package/CMakeLists.txt
recipes/flatbuffers/all/test_v1_package/CMakeLists.txt
recipes/flatbuffers/config.yml

Specify library name and version:  **flatbuffers/2.0.8**
This updates flatbuffers to the latest version 2.0.8.
---

[flatbuffers] update to 2.0.8

---

recipes/meson/all/conandata.yml
recipes/meson/config.yml

Specify library name and version:  **meson/0.63.3**
---

meson: add version 0.63.3

---

recipes/perfetto/all/conandata.yml
recipes/perfetto/config.yml

Specify library name and version:  **perfetto/30.0**
```
v30.0 - 2022-10-06:
* Fixed parsing of "R+" (preempted) and "I" (idle kernel thread) end states
of sched_switch events, collected on Linux kernels v4.14 and above.
Previously, preemption was not recognised, and idle was reported as
"x" (task dead). See commit c60a630cfe0.
* Add support for parsing sys_write syscalls.
* Remove the thread_slice table: all columns have moved to the slice table
and thread_slice exists as a view for backwards compatibility. This view
will also be removed in the future
* Add Base64 encode SQL function.
* Add support for importing function graph ftrace events.
* Add support for importing V4L2 ftrace events.
* Add support for importing virtio-video ftrace events.
UI:
* Fix downloading …
```

(#13323) Bump perfetto to v30.0

---

docs/package_templates/autotools_package/all/conanfile.py
docs/package_templates/cmake_package/all/conanfile.py
docs/package_templates/header_only/all/conanfile.py
docs/package_templates/msbuild_package/all/conanfile.py
docs/package_templates/prebuilt_tool_package/all/conanfile.py
docs/package_templates/prebuilt_tool_package/all/test_package/conanfile.py

closes #13289
- Using 120 chars as max line length
/cc @winterz
---

[docs] Apply python black formatter over recipe templates

---

recipes/aws-c-event-stream/all/CMakeLists.txt
recipes/aws-c-event-stream/all/conandata.yml
recipes/aws-c-event-stream/all/conanfile.py
recipes/aws-c-event-stream/all/test_package/CMakeLists.txt
recipes/aws-c-event-stream/all/test_package/conanfile.py
recipes/aws-c-event-stream/all/test_v1_package/CMakeLists.txt
recipes/aws-c-event-stream/all/test_v1_package/conanfile.py
recipes/aws-c-event-stream/config.yml

Specify library name and version:  **aws-c-event-stream/***
---

aws-c-event-stream: add version 0.2.15 and support conan v2

---

recipes/boost/all/conanfile.py

must be .dylib instead of .so
Specify library name and version:  **boost/\***
fixes #12716
I took the idea from [custom build script](https://github.com/kambala-decapitator/Apple-Boost-BuildScript/blob/build-shared/boost.sh) that produces shared libraries with correct extension. Tested by building Boost.System:
```
> conan install boost/1.79.0@ --build --profile:build=default --profile:host=ios-arm64 -o 'boost/*:shared=True' -o "boost/*:without_atomic=True" -o "boost/*:without_chrono=True" -o "boost/*:without_container=True" -o …
```

boost: fix output shared library extension on iOS/tvOS/watchOS

---

recipes/qt/5.x.x/conanfile.py

Specify library name and version:  **qt/5.15.x**
fixes #13352
---

qt5: don't create PrintSupport module for iOS/tvOS/watchOS

---

recipes/fmtlog/all/conandata.yml
recipes/fmtlog/all/conanfile.py
recipes/fmtlog/all/patches/2.2.1-0001-fix-cmake.patch
recipes/fmtlog/all/test_package/CMakeLists.txt
recipes/fmtlog/all/test_package/conanfile.py
recipes/fmtlog/all/test_package/test_package.cpp
recipes/fmtlog/all/test_v1_package/CMakeLists.txt
recipes/fmtlog/all/test_v1_package/conanfile.py
recipes/fmtlog/config.yml

Specify library name and version:  **fmglog/2.2.1**
fmtlog is a faster logging library which uses fmt.
---

fmtlog: add recipe

---

recipes/leptonica/all/conanfile.py

Specify library name and version:  **leptonica/all**
migrate with_jpeg option to be handled like the other recipes. (e.g. opencv)
---

leptonica recipe enhancement: option with_jpeg: select jpeg provider instead of binary switch

---

recipes/aws-c-cal/all/conandata.yml
recipes/aws-c-cal/config.yml

Specify library name and version:  **aws-c-cal/0.5.20**
---

aws-c-cal: add version 0.5.20

---

recipes/gdcm/all/CMakeLists.txt
recipes/gdcm/all/conandata.yml
recipes/gdcm/all/conanfile.py
recipes/gdcm/all/patches/0003-gcc-11-compilation.patch
recipes/gdcm/all/patches/0004-find-expat.patch
recipes/gdcm/all/test_package/CMakeLists.txt
recipes/gdcm/all/test_package/conanfile.py
recipes/gdcm/all/test_package/test_package.cpp
recipes/gdcm/all/test_v1_package/CMakeLists.txt
recipes/gdcm/all/test_v1_package/conanfile.py

Specify library name and version:  **gdcm/3.0.9**
conan v2 support
Fix compilation with gcc11 and bump dependencies.
Patch was taken from https://github.com/malaterre/GDCM/commit/4404b770be337bd0d5d3c2289abfd34426433db2
---

gdcm: conan v2 support

---

recipes/jom/all/conanfile.py

Specify library name and version:  **jom/***
I think this is the only requirement of qt5 not yet transitioned to the new GCC11 epoch
---

jom: modernize

---

recipes/libpng/all/conanfile.py

Specify library name and version:  **libpng/1.6.38**
v1.6.38 introduced new CMake variable `PNG_EXECUTABLES`, now building executables can be disabled as they're removed from package anyway.
---

libpng 1.6.38: pass PNG_EXECUTABLES=OFF + fix v2 linter error

---

recipes/sdl_image/all/CMakeLists.txt
recipes/sdl_image/all/conanfile.py

Specify library name and version:  **sdl_image/2.0.5**
- other Apple platforms can now be built against ImageIO
- fixed macOS shared build with ImageIO - required frameworks weren't linked
- added framework dependencies for consumers of static lib
---

sdl_image: build improvements for ImageIO option for Apple platforms

---

recipes/wayland/all/conanfile.py

Now that Conan 1.52.0 is available, this can be done properly.
Includes changes from PR #12781.
Fixes #13359.
---

wayland: Fix missing libffi and cross-compilation

---

recipes/qt/5.x.x/conanfile.py

Specify library name and version:  **qt/5.15.x**
partially solves #13332 for Apple platforms
---

qt5: fix dependencies for static build on Apple platforms

---

recipes/aws-c-http/all/CMakeLists.txt
recipes/aws-c-http/all/conandata.yml
recipes/aws-c-http/all/conanfile.py
recipes/aws-c-http/all/test_package/CMakeLists.txt
recipes/aws-c-http/all/test_package/conanfile.py
recipes/aws-c-http/all/test_v1_package/CMakeLists.txt
recipes/aws-c-http/all/test_v1_package/conanfile.py
recipes/aws-c-http/config.yml

Specify library name and version:  **aws-c-http/***
---

aws-c-http: add version 0.6.22 and support conan v2

---

recipes/libmysqlclient/all/conanfile.py

Specify library name and version:  **libmysqlclient/***
fixes https://github.com/conan-io/conan-center-index/issues/13413
zlib and openssl can actually not be disabled:
- https://github.com/mysql/mysql-server/blob/mysql-8.0.30/cmake/ssl.cmake#L23
- https://github.com/mysql/mysql-server/blob/mysql-8.0.30/cmake/zlib.cmake#L24
---

libmysqlclient: remove wrong options

---

recipes/glib/all/conanfile.py

Specify library name and version:  **glib/***
Dependencies like `gst-plugins-base` can't find `gio-unix-2.0` when using the `PkgConfigDeps` generator because it is currently named incorrectly as `glib-gio-unix-2.0`.
---

glib: Add missing pkg_config_names for PkgConfigDeps generator

---

recipes/sqlite3/all/CMakeLists.txt

When cross-building sqlite3 for Linux/arm64 on some systems `find_library` will fail to locate the `m` library, as seen in https://github.com/conan-io/conan-center-index/issues/13418. 
The math library `libm` is part of the compiler toolchain (in this case `glibc`) and the compiler should know to correctly handle `-lm`. For some compilers/toolchains, `libm` is not a separate library, but is part of the implicitly linked C runtime.  In these cases, `-lm` may be a no-op for those compilers.
This PR uses the `check_library_exists` macro to check if the compiler will accept `-lm` for a file that calls the `log()` function - if this succeeds, then we conditionally link against `m` directly. This is a similar approach to what CMake does internally to locate the "threads" library - by testing …

[sqlite3] Refactor handling of math library

---

recipes/unordered_dense/all/conandata.yml
recipes/unordered_dense/config.yml

Specify library name and version:  **unordered_dense/2.0.0**
---

unordered_dense: add version 2.0.0

---

recipes/luau/all/CMakeLists.txt
recipes/luau/all/conandata.yml
recipes/luau/all/conanfile.py
recipes/luau/all/test_package/CMakeLists.txt
recipes/luau/all/test_package/conanfile.py
recipes/luau/all/test_v1_package/CMakeLists.txt
recipes/luau/all/test_v1_package/conanfile.py
recipes/luau/config.yml

Specify library name and version:  **luau/***
Since luau/0.548, Luau.CodeGen depends Luau.VM and LuaU.VM.Internals.
So conan recipe has to fix LUAI_FUNC definition.
---

luau: add version 0.548 and support conan v2

---

recipes/swig/all/conanfile.py

Specify library name and version:  **swig/***
Fixes #13343.
---

swig: Link against dl on Linux, not just for GCC

---

recipes/gdk-pixbuf/all/conanfile.py

Specify library name and version:  **gdk-pixbuf/1.0**
Removed the glib version exception for Windows as this is no longer necessary.
---

[gdk-pixbuf] remove windows glib version exception

---

recipes/daw_header_libraries/all/conandata.yml
recipes/daw_header_libraries/config.yml

Specify library name and version:  **daw_header_libraries/2.71.0**
---

daw_header_libraries: add version 2.71.0

---

recipes/qcbor/all/CMakeLists.txt
recipes/qcbor/all/conandata.yml
recipes/qcbor/all/conanfile.py
recipes/qcbor/all/patches/1.1-0001-fix-cmake.patch
recipes/qcbor/all/test_package/conanfile.py
recipes/qcbor/all/test_v1_package/CMakeLists.txt
recipes/qcbor/all/test_v1_package/conanfile.py
recipes/qcbor/config.yml

Specify library name and version:  **qcbor/***
---

qcbor: add version 1.1 and support conan v2

---

recipes/openssl/1.x.x/conanfile.py
recipes/openssl/1.x.x/test_package/CMakeLists.txt
recipes/openssl/1.x.x/test_v1_package/CMakeLists.txt

It's required for https://github.com/conan-io/conan-center-index/pull/12938 & https://github.com/conan-io/conan-center-index/pull/13458, and basically any recipe depending on openssl recipe and relying on `AutotoolsDeps` (see https://github.com/conan-io/conan/issues/12106)
---

openssl 1.x: add empty layout & factorize tests of CMake variables

---

recipes/protobuf/all/conandata.yml
recipes/protobuf/config.yml

For mitigation of CVE 2022-3171
Closes #13469
Specify library name and version:  **protobuf/3.19.6**
---

(#13469) Protobuf: Add 3.19.6

---

recipes/aws-c-auth/all/CMakeLists.txt
recipes/aws-c-auth/all/conandata.yml
recipes/aws-c-auth/all/conanfile.py
recipes/aws-c-auth/all/test_package/conanfile.py
recipes/aws-c-auth/all/test_v1_package/CMakeLists.txt
recipes/aws-c-auth/all/test_v1_package/conanfile.py
recipes/aws-c-auth/config.yml

Specify library name and version:  **aws-c-auth/***
While there is newer version of `aws-c-cal/0.5.20`, this recipe requires `aws-c-cal/0.5.13`.
Because `aws-c-io` requires `aws-c-cal/0.5.13`.
---

aws-c-auth: add version 0.6.17 and support conan v2

---

recipes/boost-ext-ut/all/conanfile.py
recipes/boost-ext-ut/all/test_package/CMakeLists.txt
recipes/boost-ext-ut/all/test_v1_package/CMakeLists.txt

Specify library name and version:  **boost-ext-ut/1.1.9**
https://github.com/boost-ext/ut/blob/v1.1.9/CMakeLists.txt#L139
---

boost-ext-ut: Use upstream CMake target namespace in 1.1.9

---

recipes/modern-cpp-kafka/all/conandata.yml
recipes/modern-cpp-kafka/config.yml

Specify library name and version:  **modern-cpp-kafka/2022.10.12**
---

modern-cpp-kafka: add version 2022.10.12

---

recipes/opengv/all/conandata.yml
recipes/opengv/all/patches/0003-let-conan-handle-shared-fpic-and-marchs.patch

Yet another follow up to https://github.com/conan-io/conan-center-index/pull/13225
---

opengv | Extend patch so conan also handles the -march flags

---

recipes/cyrus-sasl/all/conanfile.py
recipes/cyrus-sasl/all/test_package/conanfile.py
recipes/cyrus-sasl/all/test_v1_package/CMakeLists.txt
recipes/cyrus-sasl/all/test_v1_package/conanfile.py

cyrus-sasl: conan v2 support

---

recipes/daw_json_link/all/conandata.yml
recipes/daw_json_link/config.yml

Specify library name and version:  **daw_json_link/3.1.0**
---

daw_json_link: add version 3.1.0

---

recipes/minizip-ng/all/conandata.yml
recipes/minizip-ng/config.yml

Specify library name and version:  **minizip-ng/3.0.7**
---

minizip-ng: add version 3.0.7

---

recipes/qt/5.x.x/conanfile.py

Specify library name and version:  **qt/5.x.x**
Currently there's no standard way to control if a recipe must be built with bitcode or not, most recipes are built with bitcode off. But Qt 5 defaults to on which makes it impossible to build with dependencies that have bitcode off (e.g. libpng), and there seems no way to disable it through configure options. Besides, [starting with Xcode 14 bitcode is no longer required](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes):
> Deprecations
>
> Starting with Xcode 14, bitcode …

qt5: disable bitcode

---

recipes/osmanip/all/conandata.yml
recipes/osmanip/config.yml

Specify library name and version:  **osmanip/4.3.0**
---

osmanip: add version 4.3.0

---

recipes/aws-c-http/all/conanfile.py

Specify library name and version:  **aws-c-http/***
This PR is trying to solve missing-dependencies in aws-c-s3. https://github.com/conan-io/conan-center-index/pull/13494.
---

aws-c-http: change dependeant recipe version for aws-c-s3

---

recipes/libbacktrace/all/conandata.yml
recipes/libbacktrace/all/conanfile.py
recipes/libbacktrace/all/test_package/conanfile.py
recipes/libbacktrace/all/test_v1_package/CMakeLists.txt
recipes/libbacktrace/all/test_v1_package/conanfile.py

libbacktrace: conan v2 support

---

recipes/xerces-c/all/CMakeLists.txt
recipes/xerces-c/all/conandata.yml
recipes/xerces-c/all/conanfile.py
recipes/xerces-c/all/test_package/conanfile.py
recipes/xerces-c/all/test_v1_package/CMakeLists.txt
recipes/xerces-c/all/test_v1_package/conanfile.py

xerces-c: conan v2 support

---

recipes/opengl/all/conanfile.py

with arch settings, it always installs the system's default arch for system packages
Specify library name and version:  **opengl/system**
---

opengl: allow cross compilation

---

recipes/tcb-span/all/conandata.yml
recipes/tcb-span/all/conanfile.py
recipes/tcb-span/all/test_package/conanfile.py
recipes/tcb-span/all/test_v1_package/CMakeLists.txt
recipes/tcb-span/all/test_v1_package/conanfile.py
recipes/tcb-span/config.yml

Specify library name and version:  **tcb-span/***
tcb-span has many revisions in the two years since 2020-06-03.
I think it is a good time to add a new cci version.
---

tcb-span: add vercion cci.20220616 and support conan v2

---

recipes/aws-c-auth/all/conanfile.py

Specify library name and version:  **aws-c-auth/***
This PR is trying to solve missing-dependencies in aws-c-s3. https://github.com/conan-io/conan-center-index/pull/13494.
---

aws-c-auth: change dependeant recipe version for aws-c-s3
